// Transactions Domain - Complete Source to Target Mapping (STTM)
// Maps FIS-ADS source tables (Bronze Layer) → Silver (Core Transactions) → Gold (Analytics)

export interface ColumnMapping {
  sourceSystem: string;
  sourceTable: string;
  sourceColumn: string;
  bronzeSchema: string;
  bronzeTable: string;
  bronzeColumn: string;
  silverSchema: string;
  silverTable: string;
  silverColumn: string;
  goldSchema: string;
  goldTable: string;
  goldColumn: string;
  dataType: string;
  businessLogic: string;
  businessMeaning: string;
}

// ============================================================================
// MONEY TRANSACTION - FIS-ADS TB_DP_OZO_MNY_TXN_ARD (BRONZE) → FCT_DEPOSIT_CERTIFICATE_TRANSACTION (SILVER)
// ============================================================================
export const moneyTransactionMappings: ColumnMapping[] = [
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_DP_OZO_MNY_TXN_ARD",
    sourceColumn: "TRN_TRANS_TME_SEQ",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_DP_OZO_MNY_TXN_ARD",
    bronzeColumn: "TRN_TRANS_TME_SEQ",
    silverSchema: "CORE_TRANSACTIONS",
    silverTable: "FCT_DEPOSIT_CERTIFICATE_TRANSACTION",
    silverColumn: "TRANSACTION_ID",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "VARCHAR(16777216)",
    businessLogic: "1=1",
    businessMeaning: "Unique transaction sequence identifier",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_DP_OZO_MNY_TXN_ARD",
    sourceColumn: "TRN_ACCT_NBR",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_DP_OZO_MNY_TXN_ARD",
    bronzeColumn: "TRN_ACCT_NBR",
    silverSchema: "CORE_TRANSACTIONS",
    silverTable: "FCT_DEPOSIT_CERTIFICATE_TRANSACTION",
    silverColumn: "ACCOUNT_NUMBER",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: "ACCOUNT_NUMBER",
    dataType: "VARCHAR(16777216)",
    businessLogic: "1=1",
    businessMeaning: "Account number for transaction",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_DP_OZO_MNY_TXN_ARD",
    sourceColumn: "TRN_TRANS_DTE",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_DP_OZO_MNY_TXN_ARD",
    bronzeColumn: "TRN_TRANS_DTE",
    silverSchema: "CORE_TRANSACTIONS",
    silverTable: "FCT_DEPOSIT_CERTIFICATE_TRANSACTION",
    silverColumn: "TRANSACTION_DATE",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "DATE",
    businessLogic: "1=1",
    businessMeaning: "Date transaction occurred",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_DP_OZO_MNY_TXN_ARD",
    sourceColumn: "TRN_TRANS_CDE",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_DP_OZO_MNY_TXN_ARD",
    bronzeColumn: "TRN_TRANS_CDE",
    silverSchema: "CORE_TRANSACTIONS",
    silverTable: "FCT_DEPOSIT_CERTIFICATE_TRANSACTION",
    silverColumn: "TRANSACTION_CODE",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "VARCHAR(16777216)",
    businessLogic: "1=1",
    businessMeaning: "Transaction type code",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_DP_OZO_MNY_TXN_ARD",
    sourceColumn: "TRN_TRANS_AMT",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_DP_OZO_MNY_TXN_ARD",
    bronzeColumn: "TRN_TRANS_AMT",
    silverSchema: "CORE_TRANSACTIONS",
    silverTable: "FCT_DEPOSIT_CERTIFICATE_TRANSACTION",
    silverColumn: "TRANSACTION_AMOUNT",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: "DP_TOTAL_AMOUNT_12M",
    dataType: "NUMBER(18,2)",
    businessLogic: "1=1",
    businessMeaning: "Transaction amount",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_DP_OZO_MNY_TXN_ARD",
    sourceColumn: "TRN_TRANS_TYP",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_DP_OZO_MNY_TXN_ARD",
    bronzeColumn: "TRN_TRANS_TYP",
    silverSchema: "CORE_TRANSACTIONS",
    silverTable: "FCT_DEPOSIT_CERTIFICATE_TRANSACTION",
    silverColumn: "DEBIT_CREDIT_INDICATOR",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "CHAR(1)",
    businessLogic: "CASE WHEN source='D' THEN 'Debit' WHEN source='C' THEN 'Credit' ELSE source END",
    businessMeaning: "Debit or Credit indicator",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_DP_OZO_MNY_TXN_ARD",
    sourceColumn: "TRN_TRANS_DESC",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_DP_OZO_MNY_TXN_ARD",
    bronzeColumn: "TRN_TRANS_DESC",
    silverSchema: "CORE_TRANSACTIONS",
    silverTable: "FCT_DEPOSIT_CERTIFICATE_TRANSACTION",
    silverColumn: "TRANSACTION_DESCRIPTION",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "VARCHAR(16777216)",
    businessLogic: "1=1",
    businessMeaning: "Transaction description",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_DP_OZO_MNY_TXN_ARD",
    sourceColumn: "TRN_TRANS_CNTL",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_DP_OZO_MNY_TXN_ARD",
    bronzeColumn: "TRN_TRANS_CNTL",
    silverSchema: "CORE_TRANSACTIONS",
    silverTable: "FCT_DEPOSIT_CERTIFICATE_TRANSACTION",
    silverColumn: "TRANSACTION_CONTROL_NUMBER",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "VARCHAR(16777216)",
    businessLogic: "1=1",
    businessMeaning: "Transaction control number",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_DP_OZO_MNY_TXN_ARD",
    sourceColumn: "PRCS_DTE",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_DP_OZO_MNY_TXN_ARD",
    bronzeColumn: "PRCS_DTE",
    silverSchema: "CORE_TRANSACTIONS",
    silverTable: "FCT_DEPOSIT_CERTIFICATE_TRANSACTION",
    silverColumn: "BUSINESS_DATE",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: "PRCS_DTE",
    dataType: "DATE",
    businessLogic: "1=1",
    businessMeaning: "Processing date for batch tracking",
  },
];

// ============================================================================
// MAINTENANCE LOG TRANSACTION - FIS-ADS TB_DP_OZU_MAINT_ARD (BRONZE) → FCT_DEPOSIT_MAINTENANCE_TRANSACTION (SILVER)
// ============================================================================
export const maintenanceLogMappings: ColumnMapping[] = [
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_DP_OZU_MAINT_ARD",
    sourceColumn: "LG_TRANS_TME_SEQ",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_DP_OZU_MAINT_ARD",
    bronzeColumn: "LG_TRANS_TME_SEQ",
    silverSchema: "CORE_TRANSACTIONS",
    silverTable: "FCT_DEPOSIT_MAINTENANCE_TRANSACTION",
    silverColumn: "TRANSACTION_ID",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "TEXT",
    businessLogic: "1=1",
    businessMeaning: "Maintenance transaction sequence ID",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_DP_OZU_MAINT_ARD",
    sourceColumn: "LG_ACCT_NBR",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_DP_OZU_MAINT_ARD",
    bronzeColumn: "LG_ACCT_NBR",
    silverSchema: "CORE_TRANSACTIONS",
    silverTable: "FCT_DEPOSIT_MAINTENANCE_TRANSACTION",
    silverColumn: "ACCOUNT_NUMBER",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: "ACCOUNT_NUMBER",
    dataType: "TEXT",
    businessLogic: "1=1",
    businessMeaning: "Account number",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_DP_OZU_MAINT_ARD",
    sourceColumn: "LG_TRANS_CDE",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_DP_OZU_MAINT_ARD",
    bronzeColumn: "LG_TRANS_CDE",
    silverSchema: "CORE_TRANSACTIONS",
    silverTable: "FCT_DEPOSIT_MAINTENANCE_TRANSACTION",
    silverColumn: "MAINTENANCE_TRANSACTION_CODE",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "TEXT",
    businessLogic: "1=1",
    businessMeaning: "Maintenance transaction code",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_DP_OZU_MAINT_ARD",
    sourceColumn: "LG_BANK_NBR",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_DP_OZU_MAINT_ARD",
    bronzeColumn: "LG_BANK_NBR",
    silverSchema: "CORE_TRANSACTIONS",
    silverTable: "FCT_DEPOSIT_MAINTENANCE_TRANSACTION",
    silverColumn: "BANK_NUMBER",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "NUMBER",
    businessLogic: "1=1",
    businessMeaning: "Bank number",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_DP_OZU_MAINT_ARD",
    sourceColumn: "LG_HOLD_ID",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_DP_OZU_MAINT_ARD",
    bronzeColumn: "LG_HOLD_ID",
    silverSchema: "CORE_TRANSACTIONS",
    silverTable: "FCT_DEPOSIT_HOLD_TRANSACTION",
    silverColumn: "HOLD_NUMBER",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "NUMBER",
    businessLogic: "1=1",
    businessMeaning: "Hold ID if applicable",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_DP_OZU_MAINT_ARD",
    sourceColumn: "LG_HOLD_TYP",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_DP_OZU_MAINT_ARD",
    bronzeColumn: "LG_HOLD_TYP",
    silverSchema: "CORE_TRANSACTIONS",
    silverTable: "FCT_DEPOSIT_HOLD_TRANSACTION",
    silverColumn: "HOLD_TYPE",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "TEXT",
    businessLogic: "1=1",
    businessMeaning: "Type of hold (LEGAL, LEVY, NSF, etc)",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_DP_OZU_MAINT_ARD",
    sourceColumn: "LG_AMT",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_DP_OZU_MAINT_ARD",
    bronzeColumn: "LG_AMT",
    silverSchema: "CORE_TRANSACTIONS",
    silverTable: "FCT_DEPOSIT_HOLD_TRANSACTION",
    silverColumn: "HOLD_AMOUNT",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "NUMBER",
    businessLogic: "1=1",
    businessMeaning: "Hold or transaction amount",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_DP_OZU_MAINT_ARD",
    sourceColumn: "PRCS_DTE",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_DP_OZU_MAINT_ARD",
    bronzeColumn: "PRCS_DTE",
    silverSchema: "CORE_TRANSACTIONS",
    silverTable: "FCT_DEPOSIT_MAINTENANCE_TRANSACTION",
    silverColumn: "BUSINESS_DATE",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: "PRCS_DTE",
    dataType: "DATE",
    businessLogic: "1=1",
    businessMeaning: "Processing date",
  },
];

// ============================================================================
// STOP PAYMENT DETAILS - FIS-ADS TB_DP_OZQ_STP_ARD (BRONZE) → FCT_DEPOSIT_STOP_TRANSACTION (SILVER)
// ============================================================================
export const stopPaymentMappings: ColumnMapping[] = [
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_DP_OZQ_STP_ARD",
    sourceColumn: "STP_ID",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_DP_OZQ_STP_ARD",
    bronzeColumn: "STP_ID",
    silverSchema: "CORE_TRANSACTIONS",
    silverTable: "FCT_DEPOSIT_STOP_TRANSACTION",
    silverColumn: "STOP_PAYMENT_I_D",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "VARCHAR(100)",
    businessLogic: "1=1",
    businessMeaning: "Stop payment unique identifier",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_DP_OZQ_STP_ARD",
    sourceColumn: "STP_ACCT_NBR",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_DP_OZQ_STP_ARD",
    bronzeColumn: "STP_ACCT_NBR",
    silverSchema: "CORE_TRANSACTIONS",
    silverTable: "FCT_DEPOSIT_STOP_TRANSACTION",
    silverColumn: "ACCOUNT_NUMBER",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: "ACCOUNT_NUMBER",
    dataType: "VARCHAR(16777216)",
    businessLogic: "1=1",
    businessMeaning: "Account number",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_DP_OZQ_STP_ARD",
    sourceColumn: "STP_AMT",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_DP_OZQ_STP_ARD",
    bronzeColumn: "STP_AMT",
    silverSchema: "CORE_TRANSACTIONS",
    silverTable: "FCT_DEPOSIT_STOP_TRANSACTION",
    silverColumn: "TRANSACTION_AMOUNT",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "NUMBER(38,0)",
    businessLogic: "1=1",
    businessMeaning: "Stop payment amount",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_DP_OZQ_STP_ARD",
    sourceColumn: "STP_DTE_ENTRD",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_DP_OZQ_STP_ARD",
    bronzeColumn: "STP_DTE_ENTRD",
    silverSchema: "CORE_TRANSACTIONS",
    silverTable: "FCT_DEPOSIT_STOP_TRANSACTION",
    silverColumn: "STOP_ENTERED_DATE",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "DATE",
    businessLogic: "1=1",
    businessMeaning: "Date stop payment was entered",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_DP_OZQ_STP_ARD",
    sourceColumn: "STP_DTE_EXP",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_DP_OZQ_STP_ARD",
    bronzeColumn: "STP_DTE_EXP",
    silverSchema: "CORE_TRANSACTIONS",
    silverTable: "FCT_DEPOSIT_STOP_TRANSACTION",
    silverColumn: "STOP_EXPIRATION_DATE",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "DATE",
    businessLogic: "1=1",
    businessMeaning: "Stop payment expiration date",
  },
];

// ============================================================================
// HOLD TRANSACTION DETAILS - FIS-ADS TB_DP_OZV_HLD_ARD (BRONZE) → FCT_DEPOSIT_HOLD_TRANSACTION (SILVER)
// ============================================================================
export const holdTransactionMappings: ColumnMapping[] = [
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_DP_OZV_HLD_ARD",
    sourceColumn: "HD_AMT",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_DP_OZV_HLD_ARD",
    bronzeColumn: "HD_AMT",
    silverSchema: "CORE_TRANSACTIONS",
    silverTable: "FCT_DEPOSIT_HOLD_TRANSACTION",
    silverColumn: "HOLD_AMOUNT",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "NUMBER",
    businessLogic: "1=1",
    businessMeaning: "Hold amount",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_DP_OZV_HLD_ARD",
    sourceColumn: "LG_HOLD_TYP",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_DP_OZV_HLD_ARD",
    bronzeColumn: "LG_HOLD_TYP",
    silverSchema: "CORE_TRANSACTIONS",
    silverTable: "FCT_DEPOSIT_HOLD_TRANSACTION",
    silverColumn: "HOLD_TYPE",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "TEXT",
    businessLogic: "1=1",
    businessMeaning: "Hold type",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_DP_OZV_HLD_ARD",
    sourceColumn: "LG_ACCT_NBR",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_DP_OZV_HLD_ARD",
    bronzeColumn: "LG_ACCT_NBR",
    silverSchema: "CORE_TRANSACTIONS",
    silverTable: "FCT_DEPOSIT_HOLD_TRANSACTION",
    silverColumn: "ACCOUNT_NUMBER",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: "ACCOUNT_NUMBER",
    dataType: "TEXT",
    businessLogic: "1=1",
    businessMeaning: "Account number",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_DP_OZV_HLD_ARD",
    sourceColumn: "LG_TRANS_CDE",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_DP_OZV_HLD_ARD",
    bronzeColumn: "LG_TRANS_CDE",
    silverSchema: "CORE_TRANSACTIONS",
    silverTable: "FCT_DEPOSIT_HOLD_TRANSACTION",
    silverColumn: "TRANSACTION_CODE",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "TEXT",
    businessLogic: "1=1",
    businessMeaning: "Transaction code for hold",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_DP_OZV_HLD_ARD",
    sourceColumn: "PRCS_DTE",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_DP_OZV_HLD_ARD",
    bronzeColumn: "PRCS_DTE",
    silverSchema: "CORE_TRANSACTIONS",
    silverTable: "FCT_DEPOSIT_HOLD_TRANSACTION",
    silverColumn: "BUSINESS_DATE",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: "PRCS_DTE",
    dataType: "DATE",
    businessLogic: "1=1",
    businessMeaning: "Processing date",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_DP_OZV_HLD_ARD",
    sourceColumn: "REFRESH_TIME",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_DP_OZV_HLD_ARD",
    bronzeColumn: "REFRESH_TIME",
    silverSchema: "CORE_TRANSACTIONS",
    silverTable: "FCT_DEPOSIT_HOLD_TRANSACTION",
    silverColumn: "RECORD_DATE",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "TIMESTAMP_NTZ(9)",
    businessLogic: "MAX(REFRESH_TIME)",
    businessMeaning: "Last refresh timestamp",
  },
];

// Combine all Transactions STTM mappings
export const transactionsSTTMMapping: ColumnMapping[] = [
  ...moneyTransactionMappings,
  ...maintenanceLogMappings,
  ...stopPaymentMappings,
  ...holdTransactionMappings,
];

// STTM gaps (columns not yet mapped)
export const transactionsSTTMGaps: ColumnMapping[] = [];

// Table coverage summary
export const transactionsTableCoverage = [
  {
    fisTable: "TB_DP_OZO_MNY_TXN_ARD",
    columnCount: 9,
    mappedCount: 9,
    coverage: "100%",
    businessKey: "TRN_TRANS_TME_SEQ",
    silverTable: "FCT_DEPOSIT_CERTIFICATE_TRANSACTION (CORE_TRANSACTIONS)",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
  },
  {
    fisTable: "TB_DP_OZU_MAINT_ARD",
    columnCount: 8,
    mappedCount: 8,
    coverage: "100%",
    businessKey: "LG_TRANS_TME_SEQ",
    silverTable: "FCT_DEPOSIT_MAINTENANCE_TRANSACTION, FCT_DEPOSIT_HOLD_TRANSACTION (CORE_TRANSACTIONS)",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
  },
  {
    fisTable: "TB_DP_OZQ_STP_ARD",
    columnCount: 5,
    mappedCount: 5,
    coverage: "100%",
    businessKey: "STP_ID",
    silverTable: "FCT_DEPOSIT_STOP_TRANSACTION (CORE_TRANSACTIONS)",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
  },
  {
    fisTable: "TB_DP_OZV_HLD_ARD",
    columnCount: 6,
    mappedCount: 6,
    coverage: "100%",
    businessKey: "HD_ID",
    silverTable: "FCT_DEPOSIT_HOLD_TRANSACTION (CORE_TRANSACTIONS)",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
  },
];

export default transactionsSTTMMapping;
