// Transactions Domain - Source to Target Mapping (STTM)
// Schema: CORE_TRANSACTIONS
// Contains mappings for 5 deposit-related transaction fact tables moved from Deposits domain

export interface ColumnMapping {
  sourceSystem: string;
  sourceTable: string;
  sourceColumn: string;
  bronzeSchema: string;
  bronzeTable: string;
  bronzeColumn: string;
  silverSchema: string;
  silverTable: string;
  silverColumn: string;
  goldSchema: string;
  goldTable: string;
  goldColumn: string | null;
  dataType: string;
  businessLogic: string;
  businessMeaning: string;
  mappingType?: "Direct" | "Derived" | "System";
}

// ============================================================================
// 1. FCT_DEPOSIT_ACCOUNT_TRANSACTION
// Source: FIS-ADS DP_OZO_MNY_TXN_ARD_RAW → CORE_TRANSACTIONS.FCT_DEPOSIT_ACCOUNT_TRANSACTION
// ============================================================================
export const depositAccountTransactionMappings: ColumnMapping[] = [
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "DP_OZO_MNY_TXN_ARD_RAW",
    sourceColumn: "TXN_ACCT_NBR",
    bronzeSchema: "FIS_RAW",
    bronzeTable: "DP_OZO_MNY_TXN_ARD_RAW",
    bronzeColumn: "TXN_ACCT_NBR",
    silverSchema: "CORE_TRANSACTIONS",
    silverTable: "FCT_DEPOSIT_ACCOUNT_TRANSACTION",
    silverColumn: "ACCOUNT_NUMBER",
    goldSchema: "ANALYTICS",
    goldTable: "TRANSACTION_ANALYTICS",
    goldColumn: "ACCOUNT_NUMBER",
    dataType: "VARCHAR(100)",
    businessLogic: "1:1 mapping",
    businessMeaning: "Account number for transaction",
    mappingType: "Direct",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "DP_OZO_MNY_TXN_ARD_RAW",
    sourceColumn: "TXN_ID",
    bronzeSchema: "FIS_RAW",
    bronzeTable: "DP_OZO_MNY_TXN_ARD_RAW",
    bronzeColumn: "TXN_ID",
    silverSchema: "CORE_TRANSACTIONS",
    silverTable: "FCT_DEPOSIT_ACCOUNT_TRANSACTION",
    silverColumn: "TRANSACTION_ID",
    goldSchema: "ANALYTICS",
    goldTable: "TRANSACTION_ANALYTICS",
    goldColumn: "TRANSACTION_ID",
    dataType: "VARCHAR(100)",
    businessLogic: "1:1 mapping",
    businessMeaning: "Unique transaction identifier",
    mappingType: "Direct",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "DP_OZO_MNY_TXN_ARD_RAW",
    sourceColumn: "TXN_DTE",
    bronzeSchema: "FIS_RAW",
    bronzeTable: "DP_OZO_MNY_TXN_ARD_RAW",
    bronzeColumn: "TXN_DTE",
    silverSchema: "CORE_TRANSACTIONS",
    silverTable: "FCT_DEPOSIT_ACCOUNT_TRANSACTION",
    silverColumn: "TRANSACTION_DATE",
    goldSchema: "ANALYTICS",
    goldTable: "TRANSACTION_ANALYTICS",
    goldColumn: "TRANSACTION_DATE",
    dataType: "DATE",
    businessLogic: "1:1 mapping",
    businessMeaning: "Transaction date",
    mappingType: "Direct",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "DP_OZO_MNY_TXN_ARD_RAW",
    sourceColumn: "TXN_AMT",
    bronzeSchema: "FIS_RAW",
    bronzeTable: "DP_OZO_MNY_TXN_ARD_RAW",
    bronzeColumn: "TXN_AMT",
    silverSchema: "CORE_TRANSACTIONS",
    silverTable: "FCT_DEPOSIT_ACCOUNT_TRANSACTION",
    silverColumn: "TRANSACTION_AMOUNT",
    goldSchema: "ANALYTICS",
    goldTable: "TRANSACTION_ANALYTICS",
    goldColumn: "TRANSACTION_AMOUNT",
    dataType: "NUMBER(18,6)",
    businessLogic: "1:1 mapping",
    businessMeaning: "Transaction amount",
    mappingType: "Direct",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "DP_OZO_MNY_TXN_ARD_RAW",
    sourceColumn: "TXN_TYPE_CDE",
    bronzeSchema: "FIS_RAW",
    bronzeTable: "DP_OZO_MNY_TXN_ARD_RAW",
    bronzeColumn: "TXN_TYPE_CDE",
    silverSchema: "CORE_TRANSACTIONS",
    silverTable: "FCT_DEPOSIT_ACCOUNT_TRANSACTION",
    silverColumn: "TRANSACTION_CODE",
    goldSchema: "ANALYTICS",
    goldTable: "TRANSACTION_ANALYTICS",
    goldColumn: "TRANSACTION_CODE",
    dataType: "VARCHAR(50)",
    businessLogic: "1:1 mapping",
    businessMeaning: "Transaction type code",
    mappingType: "Direct",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "DP_OZO_MNY_TXN_ARD_RAW",
    sourceColumn: "TXN_DESC",
    bronzeSchema: "FIS_RAW",
    bronzeTable: "DP_OZO_MNY_TXN_ARD_RAW",
    bronzeColumn: "TXN_DESC",
    silverSchema: "CORE_TRANSACTIONS",
    silverTable: "FCT_DEPOSIT_ACCOUNT_TRANSACTION",
    silverColumn: "TRANSACTION_DESCRIPTION",
    goldSchema: "ANALYTICS",
    goldTable: "TRANSACTION_ANALYTICS",
    goldColumn: null,
    dataType: "VARCHAR(500)",
    businessLogic: "1:1 mapping",
    businessMeaning: "Transaction description",
    mappingType: "Direct",
  },
];

// ============================================================================
// 2. FCT_DEPOSIT_CERTIFICATE_TRANSACTION
// Source: FIS-ADS TB_DP_OZP_TD_ARD_RAW → CORE_TRANSACTIONS.FCT_DEPOSIT_CERTIFICATE_TRANSACTION
// ============================================================================
export const depositCertificateTransactionMappings: ColumnMapping[] = [
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_DP_OZP_TD_ARD_RAW",
    sourceColumn: "TD_ACCT_NBR",
    bronzeSchema: "FIS_RAW",
    bronzeTable: "TB_DP_OZP_TD_ARD_RAW",
    bronzeColumn: "TD_ACCT_NBR",
    silverSchema: "CORE_TRANSACTIONS",
    silverTable: "FCT_DEPOSIT_CERTIFICATE_TRANSACTION",
    silverColumn: "ACCOUNT_NUMBER",
    goldSchema: "ANALYTICS",
    goldTable: "TRANSACTION_ANALYTICS",
    goldColumn: "ACCOUNT_NUMBER",
    dataType: "VARCHAR(100)",
    businessLogic: "1:1 mapping",
    businessMeaning: "Certificate of deposit account number",
    mappingType: "Direct",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_DP_OZP_TD_ARD_RAW",
    sourceColumn: "TD_TXN_ID",
    bronzeSchema: "FIS_RAW",
    bronzeTable: "TB_DP_OZP_TD_ARD_RAW",
    bronzeColumn: "TD_TXN_ID",
    silverSchema: "CORE_TRANSACTIONS",
    silverTable: "FCT_DEPOSIT_CERTIFICATE_TRANSACTION",
    silverColumn: "TRANSACTION_ID",
    goldSchema: "ANALYTICS",
    goldTable: "TRANSACTION_ANALYTICS",
    goldColumn: "TRANSACTION_ID",
    dataType: "VARCHAR(100)",
    businessLogic: "1:1 mapping",
    businessMeaning: "Certificate transaction identifier",
    mappingType: "Direct",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_DP_OZP_TD_ARD_RAW",
    sourceColumn: "TD_TXN_DTE",
    bronzeSchema: "FIS_RAW",
    bronzeTable: "TB_DP_OZP_TD_ARD_RAW",
    bronzeColumn: "TD_TXN_DTE",
    silverSchema: "CORE_TRANSACTIONS",
    silverTable: "FCT_DEPOSIT_CERTIFICATE_TRANSACTION",
    silverColumn: "TRANSACTION_DATE",
    goldSchema: "ANALYTICS",
    goldTable: "TRANSACTION_ANALYTICS",
    goldColumn: "TRANSACTION_DATE",
    dataType: "DATE",
    businessLogic: "1:1 mapping",
    businessMeaning: "Certificate transaction date",
    mappingType: "Direct",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_DP_OZP_TD_ARD_RAW",
    sourceColumn: "TD_TXN_AMT",
    bronzeSchema: "FIS_RAW",
    bronzeTable: "TB_DP_OZP_TD_ARD_RAW",
    bronzeColumn: "TD_TXN_AMT",
    silverSchema: "CORE_TRANSACTIONS",
    silverTable: "FCT_DEPOSIT_CERTIFICATE_TRANSACTION",
    silverColumn: "TRANSACTION_AMOUNT",
    goldSchema: "ANALYTICS",
    goldTable: "TRANSACTION_ANALYTICS",
    goldColumn: "TRANSACTION_AMOUNT",
    dataType: "NUMBER(18,6)",
    businessLogic: "1:1 mapping",
    businessMeaning: "Certificate transaction amount",
    mappingType: "Direct",
  },
];

// ============================================================================
// 3. FCT_DEPOSIT_HOLD_TRANSACTION
// Source: FIS-ADS TB_DP_OZV_HLD_ARD → CORE_TRANSACTIONS.FCT_DEPOSIT_HOLD_TRANSACTION
// ============================================================================
export const depositHoldTransactionMappings: ColumnMapping[] = [
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_DP_OZV_HLD_ARD",
    sourceColumn: "LG_ACCT_NBR",
    bronzeSchema: "FIS_RAW",
    bronzeTable: "TB_DP_OZV_HLD_ARD",
    bronzeColumn: "LG_ACCT_NBR",
    silverSchema: "CORE_TRANSACTIONS",
    silverTable: "FCT_DEPOSIT_HOLD_TRANSACTION",
    silverColumn: "ACCOUNT_NUMBER",
    goldSchema: "ANALYTICS",
    goldTable: "TRANSACTION_ANALYTICS",
    goldColumn: "ACCOUNT_NUMBER",
    dataType: "VARCHAR(100)",
    businessLogic: "1:1 mapping",
    businessMeaning: "Account number with hold",
    mappingType: "Direct",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_DP_OZV_HLD_ARD",
    sourceColumn: "LG_TRANS_TME_SEQ",
    bronzeSchema: "FIS_RAW",
    bronzeTable: "TB_DP_OZV_HLD_ARD",
    bronzeColumn: "LG_TRANS_TME_SEQ",
    silverSchema: "CORE_TRANSACTIONS",
    silverTable: "FCT_DEPOSIT_HOLD_TRANSACTION",
    silverColumn: "TRANSACTION_ID",
    goldSchema: "ANALYTICS",
    goldTable: "TRANSACTION_ANALYTICS",
    goldColumn: "TRANSACTION_ID",
    dataType: "VARCHAR(100)",
    businessLogic: "1:1 mapping",
    businessMeaning: "Hold transaction sequence ID",
    mappingType: "Direct",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_DP_OZV_HLD_ARD",
    sourceColumn: "HD_AMT",
    bronzeSchema: "FIS_RAW",
    bronzeTable: "TB_DP_OZV_HLD_ARD",
    bronzeColumn: "HD_AMT",
    silverSchema: "CORE_TRANSACTIONS",
    silverTable: "FCT_DEPOSIT_HOLD_TRANSACTION",
    silverColumn: "HOLD_AMOUNT",
    goldSchema: "ANALYTICS",
    goldTable: "TRANSACTION_ANALYTICS",
    goldColumn: null,
    dataType: "NUMBER(18,6)",
    businessLogic: "1:1 mapping",
    businessMeaning: "Amount of hold placed",
    mappingType: "Direct",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_DP_OZV_HLD_ARD",
    sourceColumn: "LG_HOLD_TYP",
    bronzeSchema: "FIS_RAW",
    bronzeTable: "TB_DP_OZV_HLD_ARD",
    bronzeColumn: "LG_HOLD_TYP",
    silverSchema: "CORE_TRANSACTIONS",
    silverTable: "FCT_DEPOSIT_HOLD_TRANSACTION",
    silverColumn: "HOLD_TYPE",
    goldSchema: "ANALYTICS",
    goldTable: "TRANSACTION_ANALYTICS",
    goldColumn: null,
    dataType: "VARCHAR(100)",
    businessLogic: "1:1 mapping",
    businessMeaning: "Type of hold (LEGAL, LEVY, NSF)",
    mappingType: "Direct",
  },
];

// ============================================================================
// 4. FCT_DEPOSIT_MAINTENANCE_TRANSACTION
// Source: FIS-ADS TB_DP_OZU_MAINT_ARD → CORE_TRANSACTIONS.FCT_DEPOSIT_MAINTENANCE_TRANSACTION
// ============================================================================
export const depositMaintenanceTransactionMappings: ColumnMapping[] = [
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_DP_OZU_MAINT_ARD",
    sourceColumn: "LG_ACCT_NBR",
    bronzeSchema: "FIS_RAW",
    bronzeTable: "TB_DP_OZU_MAINT_ARD",
    bronzeColumn: "LG_ACCT_NBR",
    silverSchema: "CORE_TRANSACTIONS",
    silverTable: "FCT_DEPOSIT_MAINTENANCE_TRANSACTION",
    silverColumn: "ACCOUNT_NUMBER",
    goldSchema: "ANALYTICS",
    goldTable: "TRANSACTION_ANALYTICS",
    goldColumn: "ACCOUNT_NUMBER",
    dataType: "VARCHAR(100)",
    businessLogic: "1:1 mapping",
    businessMeaning: "Account number",
    mappingType: "Direct",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_DP_OZU_MAINT_ARD",
    sourceColumn: "LG_TRANS_TME_SEQ",
    bronzeSchema: "FIS_RAW",
    bronzeTable: "TB_DP_OZU_MAINT_ARD",
    bronzeColumn: "LG_TRANS_TME_SEQ",
    silverSchema: "CORE_TRANSACTIONS",
    silverTable: "FCT_DEPOSIT_MAINTENANCE_TRANSACTION",
    silverColumn: "TRANSACTION_ID",
    goldSchema: "ANALYTICS",
    goldTable: "TRANSACTION_ANALYTICS",
    goldColumn: "TRANSACTION_ID",
    dataType: "VARCHAR(100)",
    businessLogic: "1:1 mapping",
    businessMeaning: "Maintenance transaction sequence ID",
    mappingType: "Direct",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_DP_OZU_MAINT_ARD",
    sourceColumn: "LG_TRANS_CDE",
    bronzeSchema: "FIS_RAW",
    bronzeTable: "TB_DP_OZU_MAINT_ARD",
    bronzeColumn: "LG_TRANS_CDE",
    silverSchema: "CORE_TRANSACTIONS",
    silverTable: "FCT_DEPOSIT_MAINTENANCE_TRANSACTION",
    silverColumn: "MAINTENANCE_TRANSACTION_CODE",
    goldSchema: "ANALYTICS",
    goldTable: "TRANSACTION_ANALYTICS",
    goldColumn: null,
    dataType: "VARCHAR(100)",
    businessLogic: "1:1 mapping",
    businessMeaning: "Maintenance transaction code",
    mappingType: "Direct",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_DP_OZU_MAINT_ARD",
    sourceColumn: "LG_KWRD_NEW_VAL",
    bronzeSchema: "FIS_RAW",
    bronzeTable: "TB_DP_OZU_MAINT_ARD",
    bronzeColumn: "LG_KWRD_NEW_VAL",
    silverSchema: "CORE_TRANSACTIONS",
    silverTable: "FCT_DEPOSIT_MAINTENANCE_TRANSACTION",
    silverColumn: "KEYWORD_NEW_VALUE",
    goldSchema: "ANALYTICS",
    goldTable: "TRANSACTION_ANALYTICS",
    goldColumn: null,
    dataType: "VARCHAR(100)",
    businessLogic: "1:1 mapping",
    businessMeaning: "New value after maintenance",
    mappingType: "Direct",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_DP_OZU_MAINT_ARD",
    sourceColumn: "LG_KWRD_OLD_VAL",
    bronzeSchema: "FIS_RAW",
    bronzeTable: "TB_DP_OZU_MAINT_ARD",
    bronzeColumn: "LG_KWRD_OLD_VAL",
    silverSchema: "CORE_TRANSACTIONS",
    silverTable: "FCT_DEPOSIT_MAINTENANCE_TRANSACTION",
    silverColumn: "KEYWORD_OLD_VALUE",
    goldSchema: "ANALYTICS",
    goldTable: "TRANSACTION_ANALYTICS",
    goldColumn: null,
    dataType: "VARCHAR(100)",
    businessLogic: "1:1 mapping",
    businessMeaning: "Old value before maintenance",
    mappingType: "Direct",
  },
];

// ============================================================================
// 5. FCT_DEPOSIT_STOP_TRANSACTION
// Source: FIS-ADS TB_DP_OZQ_STP_ARD → CORE_TRANSACTIONS.FCT_DEPOSIT_STOP_TRANSACTION
// ============================================================================
export const depositStopTransactionMappings: ColumnMapping[] = [
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_DP_OZQ_STP_ARD",
    sourceColumn: "STP_ACCT_NBR",
    bronzeSchema: "FIS_RAW",
    bronzeTable: "TB_DP_OZQ_STP_ARD",
    bronzeColumn: "STP_ACCT_NBR",
    silverSchema: "CORE_TRANSACTIONS",
    silverTable: "FCT_DEPOSIT_STOP_TRANSACTION",
    silverColumn: "ACCOUNT_NUMBER",
    goldSchema: "ANALYTICS",
    goldTable: "TRANSACTION_ANALYTICS",
    goldColumn: "ACCOUNT_NUMBER",
    dataType: "VARCHAR(16777216)",
    businessLogic: "1:1 mapping",
    businessMeaning: "Account number with stop payment",
    mappingType: "Direct",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_DP_OZQ_STP_ARD",
    sourceColumn: "STP_ID",
    bronzeSchema: "FIS_RAW",
    bronzeTable: "TB_DP_OZQ_STP_ARD",
    bronzeColumn: "STP_ID",
    silverSchema: "CORE_TRANSACTIONS",
    silverTable: "FCT_DEPOSIT_STOP_TRANSACTION",
    silverColumn: "STOP_PAYMENT_I_D",
    goldSchema: "ANALYTICS",
    goldTable: "TRANSACTION_ANALYTICS",
    goldColumn: null,
    dataType: "VARCHAR(100)",
    businessLogic: "1:1 mapping",
    businessMeaning: "Stop payment unique identifier",
    mappingType: "Direct",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_DP_OZQ_STP_ARD",
    sourceColumn: "STP_TXN_ID",
    bronzeSchema: "FIS_RAW",
    bronzeTable: "TB_DP_OZQ_STP_ARD",
    bronzeColumn: "STP_TXN_ID",
    silverSchema: "CORE_TRANSACTIONS",
    silverTable: "FCT_DEPOSIT_STOP_TRANSACTION",
    silverColumn: "TRANSACTION_ID",
    goldSchema: "ANALYTICS",
    goldTable: "TRANSACTION_ANALYTICS",
    goldColumn: "TRANSACTION_ID",
    dataType: "VARCHAR(100)",
    businessLogic: "1:1 mapping",
    businessMeaning: "Stop payment transaction ID",
    mappingType: "Direct",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_DP_OZQ_STP_ARD",
    sourceColumn: "STP_AMT",
    bronzeSchema: "FIS_RAW",
    bronzeTable: "TB_DP_OZQ_STP_ARD",
    bronzeColumn: "STP_AMT",
    silverSchema: "CORE_TRANSACTIONS",
    silverTable: "FCT_DEPOSIT_STOP_TRANSACTION",
    silverColumn: "TRANSACTION_AMOUNT",
    goldSchema: "ANALYTICS",
    goldTable: "TRANSACTION_ANALYTICS",
    goldColumn: null,
    dataType: "NUMBER(38,0)",
    businessLogic: "1:1 mapping",
    businessMeaning: "Stop payment amount",
    mappingType: "Direct",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_DP_OZQ_STP_ARD",
    sourceColumn: "STP_TYP",
    bronzeSchema: "FIS_RAW",
    bronzeTable: "TB_DP_OZQ_STP_ARD",
    bronzeColumn: "STP_TYP",
    silverSchema: "CORE_TRANSACTIONS",
    silverTable: "FCT_DEPOSIT_STOP_TRANSACTION",
    silverColumn: "STOP_TYPE",
    goldSchema: "ANALYTICS",
    goldTable: "TRANSACTION_ANALYTICS",
    goldColumn: null,
    dataType: "VARCHAR(100)",
    businessLogic: "1:1 mapping",
    businessMeaning: "Type of stop payment",
    mappingType: "Direct",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_DP_OZQ_STP_ARD",
    sourceColumn: "STP_DTE_ENTRD",
    bronzeSchema: "FIS_RAW",
    bronzeTable: "TB_DP_OZQ_STP_ARD",
    bronzeColumn: "STP_DTE_ENTRD",
    silverSchema: "CORE_TRANSACTIONS",
    silverTable: "FCT_DEPOSIT_STOP_TRANSACTION",
    silverColumn: "STOP_ENTERED_DATE",
    goldSchema: "ANALYTICS",
    goldTable: "TRANSACTION_ANALYTICS",
    goldColumn: null,
    dataType: "DATE",
    businessLogic: "1:1 mapping",
    businessMeaning: "Date stop payment was entered",
    mappingType: "Direct",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_DP_OZQ_STP_ARD",
    sourceColumn: "STP_DTE_EXP",
    bronzeSchema: "FIS_RAW",
    bronzeTable: "TB_DP_OZQ_STP_ARD",
    bronzeColumn: "STP_DTE_EXP",
    silverSchema: "CORE_TRANSACTIONS",
    silverTable: "FCT_DEPOSIT_STOP_TRANSACTION",
    silverColumn: "STOP_EXPIRATION_DATE",
    goldSchema: "ANALYTICS",
    goldTable: "TRANSACTION_ANALYTICS",
    goldColumn: null,
    dataType: "DATE",
    businessLogic: "1:1 mapping",
    businessMeaning: "Stop payment expiration date",
    mappingType: "Direct",
  },
];

// ============================================================================
// COMBINED MAPPINGS
// ============================================================================
export const transactionsSTTMMapping: ColumnMapping[] = [
  ...depositAccountTransactionMappings,
  ...depositCertificateTransactionMappings,
  ...depositHoldTransactionMappings,
  ...depositMaintenanceTransactionMappings,
  ...depositStopTransactionMappings,
];

// Table coverage summary
export const transactionsTableCoverage = [
  {
    sourceTable: "DP_OZO_MNY_TXN_ARD_RAW",
    silverTable: "FCT_DEPOSIT_ACCOUNT_TRANSACTION",
    schema: "CORE_TRANSACTIONS",
    mappedColumns: depositAccountTransactionMappings.length,
    coverage: "Core columns mapped",
  },
  {
    sourceTable: "TB_DP_OZP_TD_ARD_RAW",
    silverTable: "FCT_DEPOSIT_CERTIFICATE_TRANSACTION",
    schema: "CORE_TRANSACTIONS",
    mappedColumns: depositCertificateTransactionMappings.length,
    coverage: "Core columns mapped",
  },
  {
    sourceTable: "TB_DP_OZV_HLD_ARD",
    silverTable: "FCT_DEPOSIT_HOLD_TRANSACTION",
    schema: "CORE_TRANSACTIONS",
    mappedColumns: depositHoldTransactionMappings.length,
    coverage: "Core columns mapped",
  },
  {
    sourceTable: "TB_DP_OZU_MAINT_ARD",
    silverTable: "FCT_DEPOSIT_MAINTENANCE_TRANSACTION",
    schema: "CORE_TRANSACTIONS",
    mappedColumns: depositMaintenanceTransactionMappings.length,
    coverage: "Core columns mapped",
  },
  {
    sourceTable: "TB_DP_OZQ_STP_ARD",
    silverTable: "FCT_DEPOSIT_STOP_TRANSACTION",
    schema: "CORE_TRANSACTIONS",
    mappedColumns: depositStopTransactionMappings.length,
    coverage: "Core columns mapped",
  },
];

export default transactionsSTTMMapping;
