// CUSTOMER DOMAIN - SOURCE-TO-TARGET MAPPING (STTM)
// Comprehensive Bronze → Silver layer column mappings
// Maps Bronze standardized column names to Silver dimension tables

export interface ColumnMapping {
  sourceSystem: string;
  sourceTable: string;
  sourceColumn: string;
  bronzeSchema: string;
  bronzeTable: string;
  bronzeColumn: string;
  silverSchema: string;
  silverTable: string;
  silverColumn: string;
  goldSchema: string;
  goldTable: string;
  goldColumn: string | null;
  dataType: string;
  businessLogic: string;
  businessMeaning: string;
}

// ============================================================================
// CUSTOMER MASTER - bronze.customer_master → silver.DIM_CUSTOMER
// Complete 33-column mapping from Bronze to Silver
// ============================================================================
export const customerMasterMappings: ColumnMapping[] = [
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_CI_OZ6_CUST_ARD",
    sourceColumn: "CID_CUST_CUST_NBR",
    bronzeSchema: "bronze",
    bronzeTable: "customer_master",
    bronzeColumn: "CUSTOMER_ID",
    silverSchema: "silver",
    silverTable: "DIM_CUSTOMER",
    silverColumn: "CUSTOMER_NUMBER",
    goldSchema: "gold",
    goldTable: "FACT_CUSTOMER_DAILY",
    goldColumn: "CUSTOMER_NUMBER",
    dataType: "VARCHAR(20)",
    businessLogic: "Direct mapping with LPAD for standardization",
    businessMeaning: "Unique customer identifier",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_CI_OZ6_CUST_ARD",
    sourceColumn: "CID_CUST_ETHNIC_CDE",
    bronzeSchema: "bronze",
    bronzeTable: "customer_master",
    bronzeColumn: "ETHNIC_CODE",
    silverSchema: "silver",
    silverTable: "DIM_CUSTOMER",
    silverColumn: "ETHNICITY_CODE",
    goldSchema: "gold",
    goldTable: "FACT_CUSTOMER_DAILY",
    goldColumn: "ETHNICITY_CODE",
    dataType: "VARCHAR(10)",
    businessLogic: "Direct mapping with code validation",
    businessMeaning: "Customer ethnicity classification code",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_CI_OZ6_CUST_ARD",
    sourceColumn: "CID_CUST_ETHNIC_DESC",
    bronzeSchema: "bronze",
    bronzeTable: "customer_master",
    bronzeColumn: "ETHNIC_DESC",
    silverSchema: "silver",
    silverTable: "DIM_CUSTOMER",
    silverColumn: "ETHNICITY_DESCRIPTION",
    goldSchema: "gold",
    goldTable: "FACT_CUSTOMER_DAILY",
    goldColumn: null,
    dataType: "VARCHAR(50)",
    businessLogic: "Direct mapping",
    businessMeaning: "Ethnicity description",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_CI_OZ6_CUST_ARD",
    sourceColumn: "CID_CUST_TYPE_CDE",
    bronzeSchema: "bronze",
    bronzeTable: "customer_master",
    bronzeColumn: "GENDER_CODE",
    silverSchema: "silver",
    silverTable: "DIM_CUSTOMER",
    silverColumn: "GENDER_CODE",
    goldSchema: "gold",
    goldTable: "FACT_CUSTOMER_DAILY",
    goldColumn: "GENDER_CODE",
    dataType: "VARCHAR(5)",
    businessLogic: "Standardize to M/F/U/O",
    businessMeaning: "Customer gender code",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_CI_OZ6_CUST_ARD",
    sourceColumn: "CID_CUST_MARITAL_STAT_CDE",
    bronzeSchema: "bronze",
    bronzeTable: "customer_master",
    bronzeColumn: "MARITAL_STATUS_CODE",
    silverSchema: "silver",
    silverTable: "DIM_CUSTOMER",
    silverColumn: "MARITAL_STATUS_CODE",
    goldSchema: "gold",
    goldTable: "FACT_CUSTOMER_DAILY",
    goldColumn: "MARITAL_STATUS_CODE",
    dataType: "VARCHAR(10)",
    businessLogic: "Direct mapping with validation",
    businessMeaning: "Marital status code (S/M/D/W)",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_CI_OZ6_CUST_ARD",
    sourceColumn: "CID_CUST_MARITAL_STAT_DESC",
    bronzeSchema: "bronze",
    bronzeTable: "customer_master",
    bronzeColumn: "MARITAL_STATUS_DESC",
    silverSchema: "silver",
    silverTable: "DIM_CUSTOMER",
    silverColumn: "MARITAL_STATUS_DESCRIPTION",
    goldSchema: "gold",
    goldTable: "FACT_CUSTOMER_DAILY",
    goldColumn: null,
    dataType: "VARCHAR(50)",
    businessLogic: "Direct mapping",
    businessMeaning: "Marital status description",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_CI_OZ6_CUST_ARD",
    sourceColumn: "CID_CUST_EDUCATION_CDE",
    bronzeSchema: "bronze",
    bronzeTable: "customer_master",
    bronzeColumn: "EDUCATION_CODE",
    silverSchema: "silver",
    silverTable: "DIM_CUSTOMER",
    silverColumn: "EDUCATION_LEVEL_CODE",
    goldSchema: "gold",
    goldTable: "FACT_CUSTOMER_DAILY",
    goldColumn: "EDUCATION_LEVEL_CODE",
    dataType: "VARCHAR(10)",
    businessLogic: "Map to standard education levels",
    businessMeaning: "Education level code",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_CI_OZ6_CUST_ARD",
    sourceColumn: "CID_CUST_EDUCATION_DESC",
    bronzeSchema: "bronze",
    bronzeTable: "customer_master",
    bronzeColumn: "EDUCATION_DESC",
    silverSchema: "silver",
    silverTable: "DIM_CUSTOMER",
    silverColumn: "EDUCATION_LEVEL_DESCRIPTION",
    goldSchema: "gold",
    goldTable: "FACT_CUSTOMER_DAILY",
    goldColumn: null,
    dataType: "VARCHAR(50)",
    businessLogic: "Direct mapping",
    businessMeaning: "Education level description",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_CI_OZ6_CUST_ARD",
    sourceColumn: "CID_CUST_INCOME_CDE",
    bronzeSchema: "bronze",
    bronzeTable: "customer_master",
    bronzeColumn: "INCOME_CODE",
    silverSchema: "silver",
    silverTable: "DIM_CUSTOMER",
    silverColumn: "INCOME_RANGE_CODE",
    goldSchema: "gold",
    goldTable: "FACT_CUSTOMER_DAILY",
    goldColumn: "INCOME_RANGE_CODE",
    dataType: "VARCHAR(10)",
    businessLogic: "Map to standard income brackets",
    businessMeaning: "Annual income range code",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_CI_OZ6_CUST_ARD",
    sourceColumn: "CID_CUST_INCOME_DESC",
    bronzeSchema: "bronze",
    bronzeTable: "customer_master",
    bronzeColumn: "INCOME_DESC",
    silverSchema: "silver",
    silverTable: "DIM_CUSTOMER",
    silverColumn: "INCOME_RANGE_DESCRIPTION",
    goldSchema: "gold",
    goldTable: "FACT_CUSTOMER_DAILY",
    goldColumn: null,
    dataType: "VARCHAR(50)",
    businessLogic: "Direct mapping",
    businessMeaning: "Income range description",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_CI_OZ6_CUST_ARD",
    sourceColumn: "CID_CUST_BIRTH_DTE",
    bronzeSchema: "bronze",
    bronzeTable: "customer_master",
    bronzeColumn: "BIRTH_DATE",
    silverSchema: "silver",
    silverTable: "DIM_CUSTOMER",
    silverColumn: "DATE_OF_BIRTH",
    goldSchema: "gold",
    goldTable: "FACT_CUSTOMER_DAILY",
    goldColumn: "DATE_OF_BIRTH",
    dataType: "DATE",
    businessLogic: "Direct mapping with age calculation",
    businessMeaning: "Customer birth date",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_CI_OZ6_CUST_ARD",
    sourceColumn: "CID_CUST_BUS_SINCE_DTE",
    bronzeSchema: "bronze",
    bronzeTable: "customer_master",
    bronzeColumn: "BUSINESS_INCEPTION_DATE",
    silverSchema: "silver",
    silverTable: "DIM_CUSTOMER",
    silverColumn: "BUSINESS_START_DATE",
    goldSchema: "gold",
    goldTable: "FACT_CUSTOMER_DAILY",
    goldColumn: null,
    dataType: "DATE",
    businessLogic: "Direct mapping for commercial customers",
    businessMeaning: "Business inception date",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_CI_OZ6_CUST_ARD",
    sourceColumn: "CID_CUST_BUS_TYP",
    bronzeSchema: "bronze",
    bronzeTable: "customer_master",
    bronzeColumn: "BUSINESS_TYPE_CODE",
    silverSchema: "silver",
    silverTable: "DIM_CUSTOMER",
    silverColumn: "BUSINESS_TYPE_CODE",
    goldSchema: "gold",
    goldTable: "FACT_CUSTOMER_DAILY",
    goldColumn: "BUSINESS_TYPE_CODE",
    dataType: "VARCHAR(10)",
    businessLogic: "Standardize business type codes",
    businessMeaning: "Business type classification code",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_CI_OZ6_CUST_ARD",
    sourceColumn: "CID_CUST_BUS_TYP_DESC",
    bronzeSchema: "bronze",
    bronzeTable: "customer_master",
    bronzeColumn: "BUSINESS_TYPE_DESC",
    silverSchema: "silver",
    silverTable: "DIM_CUSTOMER",
    silverColumn: "BUSINESS_TYPE_DESCRIPTION",
    goldSchema: "gold",
    goldTable: "FACT_CUSTOMER_DAILY",
    goldColumn: null,
    dataType: "VARCHAR(100)",
    businessLogic: "Direct mapping",
    businessMeaning: "Business type description",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_CI_OZ6_CUST_ARD",
    sourceColumn: "CID_CUST_LANG_PREF_DESC",
    bronzeSchema: "bronze",
    bronzeTable: "customer_master",
    bronzeColumn: "LANGUAGE_PREFERENCE",
    silverSchema: "silver",
    silverTable: "DIM_CUSTOMER",
    silverColumn: "PREFERRED_LANGUAGE",
    goldSchema: "gold",
    goldTable: "FACT_CUSTOMER_DAILY",
    goldColumn: "PREFERRED_LANGUAGE",
    dataType: "VARCHAR(50)",
    businessLogic: "Standardize to ISO language codes",
    businessMeaning: "Customer preferred language",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_CI_OZ6_CUST_ARD",
    sourceColumn: "CID_CUST_COST_CENTER_NBR",
    bronzeSchema: "bronze",
    bronzeTable: "customer_master",
    bronzeColumn: "COST_CENTER_NUMBER",
    silverSchema: "silver",
    silverTable: "DIM_CUSTOMER",
    silverColumn: "COST_CENTER_ID",
    goldSchema: "gold",
    goldTable: "FACT_CUSTOMER_DAILY",
    goldColumn: null,
    dataType: "VARCHAR(20)",
    businessLogic: "Direct mapping",
    businessMeaning: "Cost center assignment for internal tracking",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_CI_OZ6_CUST_ARD",
    sourceColumn: "CID_CUST_OCCUPATION_CDE",
    bronzeSchema: "bronze",
    bronzeTable: "customer_master",
    bronzeColumn: "OCCUPATION_CODE",
    silverSchema: "silver",
    silverTable: "DIM_CUSTOMER",
    silverColumn: "OCCUPATION_CODE",
    goldSchema: "gold",
    goldTable: "FACT_CUSTOMER_DAILY",
    goldColumn: "OCCUPATION_CODE",
    dataType: "VARCHAR(10)",
    businessLogic: "Map to SOC codes",
    businessMeaning: "Occupation classification code",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_CI_OZ6_CUST_ARD",
    sourceColumn: "CID_CUST_OCCUPATION_DESC",
    bronzeSchema: "bronze",
    bronzeTable: "customer_master",
    bronzeColumn: "OCCUPATION_DESC",
    silverSchema: "silver",
    silverTable: "DIM_CUSTOMER",
    silverColumn: "OCCUPATION_DESCRIPTION",
    goldSchema: "gold",
    goldTable: "FACT_CUSTOMER_DAILY",
    goldColumn: null,
    dataType: "VARCHAR(100)",
    businessLogic: "Direct mapping",
    businessMeaning: "Occupation description",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_CI_OZ6_CUST_ARD",
    sourceColumn: "CID_CUST_TAX_ID",
    bronzeSchema: "bronze",
    bronzeTable: "customer_master",
    bronzeColumn: "TAX_ID",
    silverSchema: "silver",
    silverTable: "DIM_CUSTOMER",
    silverColumn: "TAX_IDENTIFICATION_NUMBER",
    goldSchema: "gold",
    goldTable: "FACT_CUSTOMER_DAILY",
    goldColumn: null,
    dataType: "VARCHAR(20)",
    businessLogic: "Hash/Tokenize for PII protection",
    businessMeaning: "SSN or EIN - encrypted in Silver",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_CI_OZ6_CUST_ARD",
    sourceColumn: "CID_CUST_PRIM_OFF_NBR",
    bronzeSchema: "bronze",
    bronzeTable: "customer_master",
    bronzeColumn: "PRIMARY_OFFICER_NUMBER",
    silverSchema: "silver",
    silverTable: "DIM_CUSTOMER",
    silverColumn: "PRIMARY_RELATIONSHIP_OFFICER_ID",
    goldSchema: "gold",
    goldTable: "FACT_CUSTOMER_DAILY",
    goldColumn: "PRIMARY_OFFICER_ID",
    dataType: "VARCHAR(20)",
    businessLogic: "Direct mapping with FK validation",
    businessMeaning: "Primary relationship officer employee ID",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_CI_OZ6_CUST_ARD",
    sourceColumn: "CID_CUST_PRIM_OFF_NAME",
    bronzeSchema: "bronze",
    bronzeTable: "customer_master",
    bronzeColumn: "PRIMARY_OFFICER_NAME",
    silverSchema: "silver",
    silverTable: "DIM_CUSTOMER",
    silverColumn: "PRIMARY_RELATIONSHIP_OFFICER_NAME",
    goldSchema: "gold",
    goldTable: "FACT_CUSTOMER_DAILY",
    goldColumn: null,
    dataType: "VARCHAR(100)",
    businessLogic: "Direct mapping",
    businessMeaning: "Primary relationship officer name",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_CI_OZ6_CUST_ARD",
    sourceColumn: "CID_CUST_SEC_OFF_NBR",
    bronzeSchema: "bronze",
    bronzeTable: "customer_master",
    bronzeColumn: "SECONDARY_OFFICER_NUMBER",
    silverSchema: "silver",
    silverTable: "DIM_CUSTOMER",
    silverColumn: "SECONDARY_RELATIONSHIP_OFFICER_ID",
    goldSchema: "gold",
    goldTable: "FACT_CUSTOMER_DAILY",
    goldColumn: null,
    dataType: "VARCHAR(20)",
    businessLogic: "Direct mapping with FK validation",
    businessMeaning: "Secondary relationship officer employee ID",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_CI_OZ6_CUST_ARD",
    sourceColumn: "CID_CUST_SEC_OFF_NAME",
    bronzeSchema: "bronze",
    bronzeTable: "customer_master",
    bronzeColumn: "SECONDARY_OFFICER_NAME",
    silverSchema: "silver",
    silverTable: "DIM_CUSTOMER",
    silverColumn: "SECONDARY_RELATIONSHIP_OFFICER_NAME",
    goldSchema: "gold",
    goldTable: "FACT_CUSTOMER_DAILY",
    goldColumn: null,
    dataType: "VARCHAR(100)",
    businessLogic: "Direct mapping",
    businessMeaning: "Secondary relationship officer name",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_CI_OZ6_CUST_ARD",
    sourceColumn: "CID_CUST_EMPL_SCHOOL",
    bronzeSchema: "bronze",
    bronzeTable: "customer_master",
    bronzeColumn: "EMPLOYER_NAME",
    silverSchema: "silver",
    silverTable: "DIM_CUSTOMER",
    silverColumn: "EMPLOYER_NAME",
    goldSchema: "gold",
    goldTable: "FACT_CUSTOMER_DAILY",
    goldColumn: null,
    dataType: "VARCHAR(150)",
    businessLogic: "Cleanse and standardize company names",
    businessMeaning: "Employer or school name",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_CI_OZ6_CUST_ARD",
    sourceColumn: "CID_CUST_OPEN_DTE",
    bronzeSchema: "bronze",
    bronzeTable: "customer_master",
    bronzeColumn: "CUSTOMER_OPEN_DATE",
    silverSchema: "silver",
    silverTable: "DIM_CUSTOMER",
    silverColumn: "CUSTOMER_OPEN_DATE",
    goldSchema: "gold",
    goldTable: "FACT_CUSTOMER_DAILY",
    goldColumn: "CUSTOMER_OPEN_DATE",
    dataType: "DATE",
    businessLogic: "Direct mapping",
    businessMeaning: "Date customer relationship opened",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_CI_OZ6_CUST_ARD",
    sourceColumn: "CID_CUST_CLOSED_DTE",
    bronzeSchema: "bronze",
    bronzeTable: "customer_master",
    bronzeColumn: "CUSTOMER_CLOSED_DATE",
    silverSchema: "silver",
    silverTable: "DIM_CUSTOMER",
    silverColumn: "CUSTOMER_CLOSED_DATE",
    goldSchema: "gold",
    goldTable: "FACT_CUSTOMER_DAILY",
    goldColumn: "CUSTOMER_CLOSED_DATE",
    dataType: "DATE",
    businessLogic: "Direct mapping",
    businessMeaning: "Date customer relationship closed",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_CI_OZ6_CUST_ARD",
    sourceColumn: "CID_CUST_DEATH_DTE",
    bronzeSchema: "bronze",
    bronzeTable: "customer_master",
    bronzeColumn: "CUSTOMER_DEATH_DATE",
    silverSchema: "silver",
    silverTable: "DIM_CUSTOMER",
    silverColumn: "CUSTOMER_DEATH_DATE",
    goldSchema: "gold",
    goldTable: "FACT_CUSTOMER_DAILY",
    goldColumn: null,
    dataType: "DATE",
    businessLogic: "Direct mapping with deceased flag",
    businessMeaning: "Date of death for deceased customers",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_CI_OZ6_CUST_ARD",
    sourceColumn: "CID_CUST_SINCE_DTE",
    bronzeSchema: "bronze",
    bronzeTable: "customer_master",
    bronzeColumn: "CUSTOMER_SINCE_DATE",
    silverSchema: "silver",
    silverTable: "DIM_CUSTOMER",
    silverColumn: "CUSTOMER_SINCE_DATE",
    goldSchema: "gold",
    goldTable: "FACT_CUSTOMER_DAILY",
    goldColumn: "CUSTOMER_SINCE_DATE",
    dataType: "DATE",
    businessLogic: "Use for tenure calculations",
    businessMeaning: "Customer since date for tenure tracking",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_CI_OZ6_CUST_ARD",
    sourceColumn: "CID_CUST_STATUS_CDE",
    bronzeSchema: "bronze",
    bronzeTable: "customer_master",
    bronzeColumn: "CUSTOMER_STATUS_CODE",
    silverSchema: "silver",
    silverTable: "DIM_CUSTOMER",
    silverColumn: "CUSTOMER_STATUS_CODE",
    goldSchema: "gold",
    goldTable: "FACT_CUSTOMER_DAILY",
    goldColumn: "CUSTOMER_STATUS_CODE",
    dataType: "VARCHAR(20)",
    businessLogic: "Validate status codes (ACTIVE/INACTIVE/CLOSED/DECEASED)",
    businessMeaning: "Current customer status",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_CI_OZ6_CUST_ARD",
    sourceColumn: "CID_CUST_MISC_DEMO_6",
    bronzeSchema: "bronze",
    bronzeTable: "customer_master",
    bronzeColumn: "CREDIT_SCORE",
    silverSchema: "silver",
    silverTable: "DIM_CUSTOMER",
    silverColumn: "CREDIT_SCORE",
    goldSchema: "gold",
    goldTable: "FACT_CUSTOMER_DAILY",
    goldColumn: "CREDIT_SCORE",
    dataType: "VARCHAR(50)",
    businessLogic: "Convert to INT and validate range 300-850",
    businessMeaning: "Customer credit score",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_CI_OZ6_CUST_ARD",
    sourceColumn: "CID_CUST_LST_MNT_DTE",
    bronzeSchema: "bronze",
    bronzeTable: "customer_master",
    bronzeColumn: "LAST_MODIFIED_DATE",
    silverSchema: "silver",
    silverTable: "DIM_CUSTOMER",
    silverColumn: "EFFECTIVE_START_DATE",
    goldSchema: "gold",
    goldTable: "FACT_CUSTOMER_DAILY",
    goldColumn: null,
    dataType: "DATE",
    businessLogic: "Use for SCD Type 2 effective dating",
    businessMeaning: "Last maintenance date for SCD2 tracking",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_CI_OZ6_CUST_ARD",
    sourceColumn: "REFRESH_TIME",
    bronzeSchema: "bronze",
    bronzeTable: "customer_master",
    bronzeColumn: "REFRESH_TIME",
    silverSchema: "silver",
    silverTable: "DIM_CUSTOMER",
    silverColumn: "RECORD_TIMESTAMP",
    goldSchema: "gold",
    goldTable: "FACT_CUSTOMER_DAILY",
    goldColumn: null,
    dataType: "TIMESTAMP_NTZ",
    businessLogic: "MAX(REFRESH_TIME) for latest record",
    businessMeaning: "Source system refresh timestamp",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_CI_OZ6_CUST_ARD",
    sourceColumn: "PRCS_DTE",
    bronzeSchema: "bronze",
    bronzeTable: "customer_master",
    bronzeColumn: "PROCESS_DATE",
    silverSchema: "silver",
    silverTable: "DIM_CUSTOMER",
    silverColumn: "BUSINESS_DATE",
    goldSchema: "gold",
    goldTable: "FACT_CUSTOMER_DAILY",
    goldColumn: "BUSINESS_DATE",
    dataType: "DATE",
    businessLogic: "Direct mapping for batch tracking",
    businessMeaning: "Processing/business date for batch control",
  },
];

// ============================================================================
// CUSTOMER IDENTIFIERS - bronze.customer_identifiers → silver.DIM_CUSTOMER_IDENTIFIER
// ============================================================================
export const customerIdentifierMappings: ColumnMapping[] = [
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_CI_OZ4_CUST_ID_ARD",
    sourceColumn: "CID_CUST_CUST_NBR",
    bronzeSchema: "bronze",
    bronzeTable: "customer_identifiers",
    bronzeColumn: "CUSTOMER_ID",
    silverSchema: "silver",
    silverTable: "DIM_CUSTOMER_IDENTIFIER",
    silverColumn: "CUSTOMER_NUMBER",
    goldSchema: "gold",
    goldTable: "FACT_CUSTOMER_DAILY",
    goldColumn: "CUSTOMER_NUMBER",
    dataType: "VARCHAR(20)",
    businessLogic: "Foreign key to DIM_CUSTOMER",
    businessMeaning: "Customer reference",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_CI_OZ4_CUST_ID_ARD",
    sourceColumn: "CI_DMV21_ID_NUMBER",
    bronzeSchema: "bronze",
    bronzeTable: "customer_identifiers",
    bronzeColumn: "IDENTIFICATION_NUMBER",
    silverSchema: "silver",
    silverTable: "DIM_CUSTOMER_IDENTIFIER",
    silverColumn: "IDENTIFICATION_NUMBER",
    goldSchema: "gold",
    goldTable: "FACT_CUSTOMER_DAILY",
    goldColumn: null,
    dataType: "VARCHAR(50)",
    businessLogic: "Tokenize PII data",
    businessMeaning: "Document identification number (tokenized)",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_CI_OZ4_CUST_ID_ARD",
    sourceColumn: "ID_TYP_NME",
    bronzeSchema: "bronze",
    bronzeTable: "customer_identifiers",
    bronzeColumn: "IDENTIFICATION_TYPE",
    silverSchema: "silver",
    silverTable: "DIM_CUSTOMER_IDENTIFIER",
    silverColumn: "IDENTIFICATION_TYPE",
    goldSchema: "gold",
    goldTable: "FACT_CUSTOMER_DAILY",
    goldColumn: null,
    dataType: "VARCHAR(50)",
    businessLogic: "Standardize ID types",
    businessMeaning: "Type of identification document",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_CI_OZ4_CUST_ID_ARD",
    sourceColumn: "ID_ISSUE_DTE",
    bronzeSchema: "bronze",
    bronzeTable: "customer_identifiers",
    bronzeColumn: "ID_ISSUE_DATE",
    silverSchema: "silver",
    silverTable: "DIM_CUSTOMER_IDENTIFIER",
    silverColumn: "ISSUE_DATE",
    goldSchema: "gold",
    goldTable: "FACT_CUSTOMER_DAILY",
    goldColumn: null,
    dataType: "DATE",
    businessLogic: "Direct mapping",
    businessMeaning: "ID document issue date",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_CI_OZ4_CUST_ID_ARD",
    sourceColumn: "ID_EXP_DTE",
    bronzeSchema: "bronze",
    bronzeTable: "customer_identifiers",
    bronzeColumn: "ID_EXPIRATION_DATE",
    silverSchema: "silver",
    silverTable: "DIM_CUSTOMER_IDENTIFIER",
    silverColumn: "EXPIRATION_DATE",
    goldSchema: "gold",
    goldTable: "FACT_CUSTOMER_DAILY",
    goldColumn: null,
    dataType: "DATE",
    businessLogic: "Calculate days to expiration",
    businessMeaning: "ID document expiration date",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_CI_OZ4_CUST_ID_ARD",
    sourceColumn: "REFRESH_TIME",
    bronzeSchema: "bronze",
    bronzeTable: "customer_identifiers",
    bronzeColumn: "REFRESH_TIME",
    silverSchema: "silver",
    silverTable: "DIM_CUSTOMER_IDENTIFIER",
    silverColumn: "RECORD_TIMESTAMP",
    goldSchema: "gold",
    goldTable: "FACT_CUSTOMER_DAILY",
    goldColumn: null,
    dataType: "TIMESTAMP_NTZ",
    businessLogic: "Audit timestamp",
    businessMeaning: "Source refresh timestamp",
  },
];

// ============================================================================
// CUSTOMER NAMES & ADDRESSES - bronze.customer_names_addresses → silver.DIM_CUSTOMER_NAME + DIM_CUSTOMER_ADDRESS
// ============================================================================
export const customerNameAddressMappings: ColumnMapping[] = [
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_CI_OZ5_CUST_NAAD_ARD",
    sourceColumn: "CID_NAAD_APPL_ID",
    bronzeSchema: "bronze",
    bronzeTable: "customer_names_addresses",
    bronzeColumn: "CUSTOMER_ID",
    silverSchema: "silver",
    silverTable: "DIM_CUSTOMER_NAME",
    silverColumn: "CUSTOMER_NUMBER",
    goldSchema: "gold",
    goldTable: "FACT_CUSTOMER_DAILY",
    goldColumn: "CUSTOMER_NUMBER",
    dataType: "VARCHAR(20)",
    businessLogic: "Foreign key to DIM_CUSTOMER",
    businessMeaning: "Customer reference",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_CI_OZ5_CUST_NAAD_ARD",
    sourceColumn: "CID_NAAD_KEY_FIELD_2",
    bronzeSchema: "bronze",
    bronzeTable: "customer_names_addresses",
    bronzeColumn: "FIRST_NAME",
    silverSchema: "silver",
    silverTable: "DIM_CUSTOMER_NAME",
    silverColumn: "FIRST_NAME",
    goldSchema: "gold",
    goldTable: "FACT_CUSTOMER_DAILY",
    goldColumn: null,
    dataType: "VARCHAR(100)",
    businessLogic: "Proper case, trim whitespace",
    businessMeaning: "Customer first name",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_CI_OZ5_CUST_NAAD_ARD",
    sourceColumn: "CID_NAAD_SURNAME",
    bronzeSchema: "bronze",
    bronzeTable: "customer_names_addresses",
    bronzeColumn: "LAST_NAME",
    silverSchema: "silver",
    silverTable: "DIM_CUSTOMER_NAME",
    silverColumn: "LAST_NAME",
    goldSchema: "gold",
    goldTable: "FACT_CUSTOMER_DAILY",
    goldColumn: null,
    dataType: "VARCHAR(100)",
    businessLogic: "Proper case, trim whitespace",
    businessMeaning: "Customer last name",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_CI_OZ5_CUST_NAAD_ARD",
    sourceColumn: "CID_NAAD_KEY_FIELD_3",
    bronzeSchema: "bronze",
    bronzeTable: "customer_names_addresses",
    bronzeColumn: "MIDDLE_NAME_1",
    silverSchema: "silver",
    silverTable: "DIM_CUSTOMER_NAME",
    silverColumn: "MIDDLE_NAME",
    goldSchema: "gold",
    goldTable: "FACT_CUSTOMER_DAILY",
    goldColumn: null,
    dataType: "VARCHAR(100)",
    businessLogic: "Proper case, trim whitespace",
    businessMeaning: "Customer middle name",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_CI_OZ5_CUST_NAAD_ARD",
    sourceColumn: "CID_NAAD_NAME_LINE",
    bronzeSchema: "bronze",
    bronzeTable: "customer_names_addresses",
    bronzeColumn: "CUSTOMER_NAME",
    silverSchema: "silver",
    silverTable: "DIM_CUSTOMER_NAME",
    silverColumn: "FULL_NAME",
    goldSchema: "gold",
    goldTable: "FACT_CUSTOMER_DAILY",
    goldColumn: "CUSTOMER_NAME",
    dataType: "VARCHAR(200)",
    businessLogic: "Proper case, trim whitespace",
    businessMeaning: "Customer full name",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_CI_OZ5_CUST_NAAD_ARD",
    sourceColumn: "CID_NAAD_LINE_1",
    bronzeSchema: "bronze",
    bronzeTable: "customer_names_addresses",
    bronzeColumn: "ADDRESS_LINE_1",
    silverSchema: "silver",
    silverTable: "DIM_CUSTOMER_ADDRESS",
    silverColumn: "ADDRESS_LINE_1",
    goldSchema: "gold",
    goldTable: "FACT_CUSTOMER_DAILY",
    goldColumn: null,
    dataType: "VARCHAR(150)",
    businessLogic: "Standardize address formatting",
    businessMeaning: "Street address line 1",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_CI_OZ5_CUST_NAAD_ARD",
    sourceColumn: "CID_NAAD_CITY",
    bronzeSchema: "bronze",
    bronzeTable: "customer_names_addresses",
    bronzeColumn: "CITY",
    silverSchema: "silver",
    silverTable: "DIM_CUSTOMER_ADDRESS",
    silverColumn: "CITY",
    goldSchema: "gold",
    goldTable: "FACT_CUSTOMER_DAILY",
    goldColumn: null,
    dataType: "VARCHAR(50)",
    businessLogic: "Proper case",
    businessMeaning: "City name",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_CI_OZ5_CUST_NAAD_ARD",
    sourceColumn: "CID_NAAD_STATE_CDE",
    bronzeSchema: "bronze",
    bronzeTable: "customer_names_addresses",
    bronzeColumn: "STATE_CODE",
    silverSchema: "silver",
    silverTable: "DIM_CUSTOMER_ADDRESS",
    silverColumn: "STATE_CODE",
    goldSchema: "gold",
    goldTable: "FACT_CUSTOMER_DAILY",
    goldColumn: "STATE_CODE",
    dataType: "VARCHAR(5)",
    businessLogic: "Validate US state codes",
    businessMeaning: "State/province code",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_CI_OZ5_CUST_NAAD_ARD",
    sourceColumn: "CID_NAAD_ZIP_1",
    bronzeSchema: "bronze",
    bronzeTable: "customer_names_addresses",
    bronzeColumn: "ZIP_CODE_1",
    silverSchema: "silver",
    silverTable: "DIM_CUSTOMER_ADDRESS",
    silverColumn: "ZIP_CODE",
    goldSchema: "gold",
    goldTable: "FACT_CUSTOMER_DAILY",
    goldColumn: "ZIP_CODE",
    dataType: "VARCHAR(10)",
    businessLogic: "Format as 5-digit ZIP",
    businessMeaning: "ZIP/postal code",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_CI_OZ5_CUST_NAAD_ARD",
    sourceColumn: "CID_NAAD_COUNTRY",
    bronzeSchema: "bronze",
    bronzeTable: "customer_names_addresses",
    bronzeColumn: "COUNTRY_CODE",
    silverSchema: "silver",
    silverTable: "DIM_CUSTOMER_ADDRESS",
    silverColumn: "COUNTRY_CODE",
    goldSchema: "gold",
    goldTable: "FACT_CUSTOMER_DAILY",
    goldColumn: null,
    dataType: "VARCHAR(5)",
    businessLogic: "Validate ISO country codes",
    businessMeaning: "Country code",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_CI_OZ5_CUST_NAAD_ARD",
    sourceColumn: "CID_NAAD_PRIM_PHONE_NBR",
    bronzeSchema: "bronze",
    bronzeTable: "customer_names_addresses",
    bronzeColumn: "PRIMARY_PHONE_NUMBER",
    silverSchema: "silver",
    silverTable: "DIM_CUSTOMER_ADDRESS",
    silverColumn: "PRIMARY_PHONE",
    goldSchema: "gold",
    goldTable: "FACT_CUSTOMER_DAILY",
    goldColumn: null,
    dataType: "VARCHAR(20)",
    businessLogic: "Format as (XXX) XXX-XXXX",
    businessMeaning: "Primary phone number",
  },
];

// ============================================================================
// CUSTOMER EMAIL - bronze.customer_email → silver.DIM_CUSTOMER_EMAIL
// ============================================================================
export const customerEmailMappings: ColumnMapping[] = [
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_CI_OZ3_EMAIL_ARD",
    sourceColumn: "CID_EMLREL_CUST_NMB",
    bronzeSchema: "bronze",
    bronzeTable: "customer_email",
    bronzeColumn: "CUSTOMER_ID",
    silverSchema: "silver",
    silverTable: "DIM_CUSTOMER_EMAIL",
    silverColumn: "CUSTOMER_NUMBER",
    goldSchema: "gold",
    goldTable: "FACT_CUSTOMER_DAILY",
    goldColumn: "CUSTOMER_NUMBER",
    dataType: "VARCHAR(20)",
    businessLogic: "Foreign key to DIM_CUSTOMER",
    businessMeaning: "Customer reference",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_CI_OZ3_EMAIL_ARD",
    sourceColumn: "CID_EMLREL_ADDR_TXT",
    bronzeSchema: "bronze",
    bronzeTable: "customer_email",
    bronzeColumn: "EMAIL_ADDRESS",
    silverSchema: "silver",
    silverTable: "DIM_CUSTOMER_EMAIL",
    silverColumn: "EMAIL_ADDRESS",
    goldSchema: "gold",
    goldTable: "FACT_CUSTOMER_DAILY",
    goldColumn: null,
    dataType: "VARCHAR(255)",
    businessLogic: "Lowercase, validate format",
    businessMeaning: "Email address",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_CI_OZ3_EMAIL_ARD",
    sourceColumn: "CID_EMLREL_POC_RSN_CDE",
    bronzeSchema: "bronze",
    bronzeTable: "customer_email",
    bronzeColumn: "EMAIL_TYPE_CODE",
    silverSchema: "silver",
    silverTable: "DIM_CUSTOMER_EMAIL",
    silverColumn: "EMAIL_TYPE",
    goldSchema: "gold",
    goldTable: "FACT_CUSTOMER_DAILY",
    goldColumn: null,
    dataType: "VARCHAR(20)",
    businessLogic: "Standardize to PRIMARY/SECONDARY/WORK",
    businessMeaning: "Email type classification",
  },
];

// ============================================================================
// CUSTOMER-ACCOUNT RELATIONSHIPS - bronze.customer_account_relationships → silver.BRG_CUSTOMER_ACCOUNT
// ============================================================================
export const customerAccountRelationshipMappings: ColumnMapping[] = [
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_CI_OZW_CUST_ACCT_RLT_ARD",
    sourceColumn: "CID_RELA_R_APPL_ID",
    bronzeSchema: "bronze",
    bronzeTable: "customer_account_relationships",
    bronzeColumn: "CUSTOMER_ID",
    silverSchema: "silver",
    silverTable: "BRG_CUSTOMER_ACCOUNT",
    silverColumn: "CUSTOMER_NUMBER",
    goldSchema: "gold",
    goldTable: "FACT_CUSTOMER_DAILY",
    goldColumn: "CUSTOMER_NUMBER",
    dataType: "VARCHAR(20)",
    businessLogic: "Foreign key to DIM_CUSTOMER",
    businessMeaning: "Customer reference",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_CI_OZW_CUST_ACCT_RLT_ARD",
    sourceColumn: "CID_RELA_APPL_ID",
    bronzeSchema: "bronze",
    bronzeTable: "customer_account_relationships",
    bronzeColumn: "ACCOUNT_ID",
    silverSchema: "silver",
    silverTable: "BRG_CUSTOMER_ACCOUNT",
    silverColumn: "ACCOUNT_NUMBER",
    goldSchema: "gold",
    goldTable: "FACT_CUSTOMER_DAILY",
    goldColumn: null,
    dataType: "VARCHAR(20)",
    businessLogic: "Foreign key to DIM_ACCOUNT",
    businessMeaning: "Account reference",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_CI_OZW_CUST_ACCT_RLT_ARD",
    sourceColumn: "CID_RELA_E2_TO_E1_CDE",
    bronzeSchema: "bronze",
    bronzeTable: "customer_account_relationships",
    bronzeColumn: "RELATIONSHIP_TYPE_CODE",
    silverSchema: "silver",
    silverTable: "BRG_CUSTOMER_ACCOUNT",
    silverColumn: "RELATIONSHIP_TYPE",
    goldSchema: "gold",
    goldTable: "FACT_CUSTOMER_DAILY",
    goldColumn: null,
    dataType: "VARCHAR(20)",
    businessLogic: "Standardize relationship codes",
    businessMeaning: "Type of customer-account relationship",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_CI_OZW_CUST_ACCT_RLT_ARD",
    sourceColumn: "CID_RELA_E1_TO_E2_CDE",
    bronzeSchema: "bronze",
    bronzeTable: "customer_account_relationships",
    bronzeColumn: "RELATIONSHIP_ROLE_CODE",
    silverSchema: "silver",
    silverTable: "BRG_CUSTOMER_ACCOUNT",
    silverColumn: "RELATIONSHIP_ROLE",
    goldSchema: "gold",
    goldTable: "FACT_CUSTOMER_DAILY",
    goldColumn: null,
    dataType: "VARCHAR(20)",
    businessLogic: "Map to PRIMARY/JOINT/SIGNER/BENEFICIARY",
    businessMeaning: "Customer role on account",
  },
];

// Combine all Customer STTM mappings
export const customerSTTMMapping_Combined: ColumnMapping[] = [
  ...customerMasterMappings,
  ...customerIdentifierMappings,
  ...customerNameAddressMappings,
  ...customerEmailMappings,
  ...customerAccountRelationshipMappings,
];

// STTM gaps (columns not yet mapped) - Currently comprehensive with 0 gaps
export const customerSTTMGaps: ColumnMapping[] = [];

// Table coverage summary - Updated with accurate counts
export const customerTableCoverage = [
  {
    fisTable: "TB_CI_OZ6_CUST_ARD",
    bronzeTable: "customer_master",
    columnCount: 33,
    mappedCount: 33,
    coverage: "100%",
    businessKey: "CUSTOMER_ID",
    silverTable: "DIM_CUSTOMER",
    goldTable: "FACT_CUSTOMER_DAILY",
  },
  {
    fisTable: "TB_CI_OZ4_CUST_ID_ARD",
    bronzeTable: "customer_identifiers",
    columnCount: 6,
    mappedCount: 6,
    coverage: "100%",
    businessKey: "IDENTIFICATION_NUMBER",
    silverTable: "DIM_CUSTOMER_IDENTIFIER",
    goldTable: "FACT_CUSTOMER_DAILY",
  },
  {
    fisTable: "TB_CI_OZ5_CUST_NAAD_ARD",
    bronzeTable: "customer_names_addresses",
    columnCount: 12,
    mappedCount: 12,
    coverage: "100%",
    businessKey: "CUSTOMER_ID",
    silverTable: "DIM_CUSTOMER_NAME, DIM_CUSTOMER_ADDRESS",
    goldTable: "FACT_CUSTOMER_DAILY",
  },
  {
    fisTable: "TB_CI_OZ3_EMAIL_ARD",
    bronzeTable: "customer_email",
    columnCount: 3,
    mappedCount: 3,
    coverage: "100%",
    businessKey: "CUSTOMER_ID",
    silverTable: "DIM_CUSTOMER_EMAIL",
    goldTable: "FACT_CUSTOMER_DAILY",
  },
  {
    fisTable: "TB_CI_OZW_CUST_ACCT_RLT_ARD",
    bronzeTable: "customer_account_relationships",
    columnCount: 4,
    mappedCount: 4,
    coverage: "100%",
    businessKey: "CUSTOMER_ID, ACCOUNT_ID",
    silverTable: "BRG_CUSTOMER_ACCOUNT",
    goldTable: "FACT_CUSTOMER_DAILY",
  },
];

export default customerSTTMMapping_Combined;
