/**
 * TRANSACTIONS DOMAIN - GOLD LAYER - DDL SPECIFICATIONS
 *
 * Aggregated analytics layer optimized for BI reporting
 * Contains FACT tables for transaction details and aggregates
 * DIMENSION tables for channels, merchants, transaction types
 * AGGREGATE table for customer-transaction consolidated view
 * Source: CORE_TRANSACTIONS (Silver) + CORE_CUSTOMERS (Silver)
 */

export interface GoldTableColumn {
  columnName: string;
  dataType: string;
  sourceSchema: string;
  sourceTable: string;
  sourceColumn: string;
  businessMeaning: string;
  nullable: boolean;
}

export interface GoldTableSpec {
  name: string;
  schema: string;
  type: "FACT" | "DIMENSION" | "AGGREGATE";
  grain: string;
  description: string;
  columns: GoldTableColumn[];
  estimatedRows: number;
  updateFrequency: string;
  primaryKey: string[];
  partitionBy?: string;
  clusterBy?: string[];
}

// ============================================================================
// FCT_TRANSACTION_DETAIL - Transaction Detail Fact Table
// ============================================================================
export const fctTransactionDetailTable: GoldTableSpec = {
  name: "FCT_TRANSACTION_DETAIL",
  schema: "ANALYTICS",
  type: "FACT",
  grain: "One row per transaction",
  description: "Detailed transaction-level data including all transaction types (debit, credit, transfer), amounts, channels, and operational metrics",
  columns: [
    {
      columnName: "TRANSACTION_ID",
      dataType: "VARCHAR(50)",
      sourceSchema: "CORE_TRANSACTIONS",
      sourceTable: "FCT_TRANSACTION",
      sourceColumn: "TRANSACTION_ID",
      businessMeaning: "Unique transaction identifier",
      nullable: false,
    },
    {
      columnName: "CUSTOMER_NUMBER",
      dataType: "VARCHAR(50)",
      sourceSchema: "CORE_CUSTOMERS",
      sourceTable: "DIM_CUSTOMER",
      sourceColumn: "CUSTOMER_NUMBER",
      businessMeaning: "Customer initiating transaction",
      nullable: false,
    },
    {
      columnName: "ACCOUNT_NUMBER",
      dataType: "VARCHAR(20)",
      sourceSchema: "CORE_DEPOSITS",
      sourceTable: "DIM_ACCOUNT",
      sourceColumn: "ACCOUNT_NUMBER",
      businessMeaning: "Account associated with transaction",
      nullable: false,
    },
    {
      columnName: "TRANSACTION_DATE",
      dataType: "DATE",
      sourceSchema: "CORE_TRANSACTIONS",
      sourceTable: "FCT_TRANSACTION",
      sourceColumn: "TRANSACTION_DATE",
      businessMeaning: "Date transaction occurred",
      nullable: false,
    },
    {
      columnName: "POST_DATE",
      dataType: "DATE",
      sourceSchema: "CORE_TRANSACTIONS",
      sourceTable: "FCT_TRANSACTION",
      sourceColumn: "POST_DATE",
      businessMeaning: "Date transaction posted to account",
      nullable: false,
    },
    {
      columnName: "TRANSACTION_TIME",
      dataType: "TIMESTAMP",
      sourceSchema: "CORE_TRANSACTIONS",
      sourceTable: "FCT_TRANSACTION",
      sourceColumn: "TRANSACTION_TIME",
      businessMeaning: "Exact time of transaction",
      nullable: false,
    },
    {
      columnName: "TRANSACTION_TYPE_CODE",
      dataType: "VARCHAR(20)",
      sourceSchema: "CORE_TRANSACTIONS",
      sourceTable: "FCT_TRANSACTION",
      sourceColumn: "TRANSACTION_TYPE_CODE",
      businessMeaning: "Code for transaction type (DEBIT, CREDIT, TRANSFER, WITHDRAWAL, DEPOSIT)",
      nullable: false,
    },
    {
      columnName: "TRANSACTION_AMOUNT",
      dataType: "DECIMAL(18,2)",
      sourceSchema: "CORE_TRANSACTIONS",
      sourceTable: "FCT_TRANSACTION",
      sourceColumn: "TRANSACTION_AMOUNT",
      businessMeaning: "Transaction amount in account currency",
      nullable: false,
    },
    {
      columnName: "TRANSACTION_CURRENCY",
      dataType: "VARCHAR(3)",
      sourceSchema: "CORE_TRANSACTIONS",
      sourceTable: "FCT_TRANSACTION",
      sourceColumn: "CURRENCY_CODE",
      businessMeaning: "ISO currency code of transaction",
      nullable: false,
    },
    {
      columnName: "MERCHANT_ID",
      dataType: "VARCHAR(50)",
      sourceSchema: "CORE_TRANSACTIONS",
      sourceTable: "DIM_MERCHANT",
      sourceColumn: "MERCHANT_ID",
      businessMeaning: "Merchant identifier (for card transactions)",
      nullable: true,
    },
    {
      columnName: "MERCHANT_CATEGORY_CODE",
      dataType: "VARCHAR(10)",
      sourceSchema: "CORE_TRANSACTIONS",
      sourceTable: "DIM_MERCHANT",
      sourceColumn: "MERCHANT_CATEGORY_CODE",
      businessMeaning: "MCC code for merchant category",
      nullable: true,
    },
    {
      columnName: "CHANNEL_CODE",
      dataType: "VARCHAR(20)",
      sourceSchema: "CORE_TRANSACTIONS",
      sourceTable: "DIM_CHANNEL",
      sourceColumn: "CHANNEL_CODE",
      businessMeaning: "Channel used for transaction (BRANCH, ATM, ONLINE, MOBILE, PHONE, CARD)",
      nullable: false,
    },
    {
      columnName: "TRANSACTION_STATUS_CODE",
      dataType: "VARCHAR(20)",
      sourceSchema: "CORE_TRANSACTIONS",
      sourceTable: "FCT_TRANSACTION",
      sourceColumn: "TRANSACTION_STATUS_CODE",
      businessMeaning: "Transaction status (POSTED, PENDING, REVERSED, FAILED, CANCELLED)",
      nullable: false,
    },
    {
      columnName: "RESPONSE_CODE",
      dataType: "VARCHAR(10)",
      sourceSchema: "CORE_TRANSACTIONS",
      sourceTable: "FCT_TRANSACTION",
      sourceColumn: "RESPONSE_CODE",
      businessMeaning: "Response code for transaction authorization",
      nullable: true,
    },
    {
      columnName: "BALANCE_AFTER_TRANSACTION",
      dataType: "DECIMAL(18,2)",
      sourceSchema: "CORE_TRANSACTIONS",
      sourceTable: "FCT_TRANSACTION",
      sourceColumn: "BALANCE_AFTER_TRANSACTION",
      businessMeaning: "Account balance immediately after transaction",
      nullable: true,
    },
    {
      columnName: "AVAILABLE_BALANCE_AFTER",
      dataType: "DECIMAL(18,2)",
      sourceSchema: "CORE_TRANSACTIONS",
      sourceTable: "FCT_TRANSACTION",
      sourceColumn: "AVAILABLE_BALANCE_AFTER",
      businessMeaning: "Available balance after transaction",
      nullable: true,
    },
    {
      columnName: "PROCESSING_TIME_MS",
      dataType: "NUMBER(10,0)",
      sourceSchema: "CORE_TRANSACTIONS",
      sourceTable: "FCT_TRANSACTION",
      sourceColumn: "PROCESSING_TIME_MILLISECONDS",
      businessMeaning: "Transaction processing time in milliseconds",
      nullable: true,
    },
    {
      columnName: "IS_DUPLICATE",
      dataType: "VARCHAR(1)",
      sourceSchema: "CORE_TRANSACTIONS",
      sourceTable: "FCT_TRANSACTION",
      sourceColumn: "DUPLICATE_FLAG",
      businessMeaning: "Flag indicating duplicate transaction detection (Y/N)",
      nullable: true,
    },
    {
      columnName: "IS_FRAUDULENT",
      dataType: "VARCHAR(1)",
      sourceSchema: "ANALYTICS",
      sourceTable: "FRAUD_DETECTION",
      sourceColumn: "FRAUD_FLAG",
      businessMeaning: "Flag indicating fraudulent transaction (Y/N)",
      nullable: true,
    },
    {
      columnName: "FRAUD_SCORE",
      dataType: "DECIMAL(5,2)",
      sourceSchema: "ANALYTICS",
      sourceTable: "FRAUD_DETECTION",
      sourceColumn: "FRAUD_PROBABILITY_SCORE",
      businessMeaning: "Fraud probability score (0-100)",
      nullable: true,
    },
    {
      columnName: "FRAUD_RULE_TRIGGERED",
      dataType: "VARCHAR(100)",
      sourceSchema: "ANALYTICS",
      sourceTable: "FRAUD_DETECTION",
      sourceColumn: "FRAUD_RULE_NAME",
      businessMeaning: "Name of fraud rule that triggered",
      nullable: true,
    },
    {
      columnName: "AUTHORIZATION_METHOD",
      dataType: "VARCHAR(20)",
      sourceSchema: "CORE_TRANSACTIONS",
      sourceTable: "FCT_TRANSACTION",
      sourceColumn: "AUTHORIZATION_METHOD",
      businessMeaning: "Authorization method (PIN, SIGNATURE, BIOMETRIC, CONTACTLESS)",
      nullable: true,
    },
    {
      columnName: "CARD_ID",
      dataType: "VARCHAR(50)",
      sourceSchema: "CORE_TRANSACTIONS",
      sourceTable: "FCT_TRANSACTION",
      sourceColumn: "CARD_ID",
      businessMeaning: "Card identifier (for card transactions)",
      nullable: true,
    },
    {
      columnName: "CARD_LAST_FOUR",
      dataType: "VARCHAR(4)",
      sourceSchema: "CORE_TRANSACTIONS",
      sourceTable: "FCT_TRANSACTION",
      sourceColumn: "CARD_LAST_FOUR",
      businessMeaning: "Last four digits of card",
      nullable: true,
    },
    {
      columnName: "RECIPIENT_ACCOUNT_NUMBER",
      dataType: "VARCHAR(20)",
      sourceSchema: "CORE_TRANSACTIONS",
      sourceTable: "FCT_TRANSACTION",
      sourceColumn: "RECIPIENT_ACCOUNT_NUMBER",
      businessMeaning: "Recipient account (for transfer transactions)",
      nullable: true,
    },
    {
      columnName: "RECIPIENT_CUSTOMER_NUMBER",
      dataType: "VARCHAR(50)",
      sourceSchema: "CORE_TRANSACTIONS",
      sourceTable: "FCT_TRANSACTION",
      sourceColumn: "RECIPIENT_CUSTOMER_NUMBER",
      businessMeaning: "Recipient customer (for transfer transactions)",
      nullable: true,
    },
    {
      columnName: "REFERENCE_NUMBER",
      dataType: "VARCHAR(50)",
      sourceSchema: "CORE_TRANSACTIONS",
      sourceTable: "FCT_TRANSACTION",
      sourceColumn: "REFERENCE_NUMBER",
      businessMeaning: "Transaction reference number for reconciliation",
      nullable: true,
    },
    {
      columnName: "ORIGINAL_AMOUNT",
      dataType: "DECIMAL(18,2)",
      sourceSchema: "CORE_TRANSACTIONS",
      sourceTable: "FCT_TRANSACTION",
      sourceColumn: "ORIGINAL_AMOUNT",
      businessMeaning: "Original transaction amount (in original currency)",
      nullable: true,
    },
    {
      columnName: "EXCHANGE_RATE",
      dataType: "DECIMAL(18,6)",
      sourceSchema: "CORE_TRANSACTIONS",
      sourceTable: "FCT_TRANSACTION",
      sourceColumn: "EXCHANGE_RATE",
      businessMeaning: "Exchange rate applied (if multi-currency)",
      nullable: true,
    },
    {
      columnName: "FEES_CHARGED",
      dataType: "DECIMAL(10,2)",
      sourceSchema: "CORE_TRANSACTIONS",
      sourceTable: "FCT_TRANSACTION",
      sourceColumn: "FEES_CHARGED",
      businessMeaning: "Transaction fees charged",
      nullable: true,
    },
    {
      columnName: "DATA_LOAD_DATE",
      dataType: "DATE",
      sourceSchema: "SYSTEM",
      sourceTable: "SYSTEM_DATE",
      sourceColumn: "CURRENT_DATE",
      businessMeaning: "System load date",
      nullable: false,
    },
  ],
  estimatedRows: 2000000000,
  updateFrequency: "Real-time",
  primaryKey: ["TRANSACTION_ID"],
  partitionBy: "POST_DATE",
  clusterBy: ["CUSTOMER_NUMBER", "ACCOUNT_NUMBER", "TRANSACTION_DATE"],
};

// ============================================================================
// FCT_TRANSACTION_DAILY_SUMMARY - Transaction Daily Summary Fact Table
// ============================================================================
export const fctTransactionDailySummaryTable: GoldTableSpec = {
  name: "FCT_TRANSACTION_DAILY_SUMMARY",
  schema: "ANALYTICS",
  type: "FACT",
  grain: "One row per day with aggregated transaction metrics",
  description: "Daily aggregated transaction metrics including counts, volumes, and channel breakdowns for analytics and reporting",
  columns: [
    {
      columnName: "SUMMARY_DATE",
      dataType: "DATE",
      sourceSchema: "CORE_TRANSACTIONS",
      sourceTable: "FCT_TRANSACTION",
      sourceColumn: "TRANSACTION_DATE",
      businessMeaning: "Date of summary",
      nullable: false,
    },
    {
      columnName: "TOTAL_TRANSACTION_COUNT",
      dataType: "NUMBER(15,0)",
      sourceSchema: "CORE_TRANSACTIONS",
      sourceTable: "FCT_TRANSACTION",
      sourceColumn: "count(distinct TRANSACTION_ID)",
      businessMeaning: "Total number of transactions",
      nullable: false,
    },
    {
      columnName: "TOTAL_TRANSACTION_VOLUME",
      dataType: "DECIMAL(18,2)",
      sourceSchema: "CORE_TRANSACTIONS",
      sourceTable: "FCT_TRANSACTION",
      sourceColumn: "sum(TRANSACTION_AMOUNT)",
      businessMeaning: "Total transaction volume in base currency",
      nullable: false,
    },
    {
      columnName: "AVERAGE_TRANSACTION_AMOUNT",
      dataType: "DECIMAL(18,2)",
      sourceSchema: "CORE_TRANSACTIONS",
      sourceTable: "FCT_TRANSACTION",
      sourceColumn: "avg(TRANSACTION_AMOUNT)",
      businessMeaning: "Average transaction amount",
      nullable: true,
    },
    {
      columnName: "MEDIAN_TRANSACTION_AMOUNT",
      dataType: "DECIMAL(18,2)",
      sourceSchema: "CORE_TRANSACTIONS",
      sourceTable: "FCT_TRANSACTION",
      sourceColumn: "PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY TRANSACTION_AMOUNT)",
      businessMeaning: "Median transaction amount",
      nullable: true,
    },
    {
      columnName: "MIN_TRANSACTION_AMOUNT",
      dataType: "DECIMAL(18,2)",
      sourceSchema: "CORE_TRANSACTIONS",
      sourceTable: "FCT_TRANSACTION",
      sourceColumn: "min(TRANSACTION_AMOUNT)",
      businessMeaning: "Minimum transaction amount",
      nullable: true,
    },
    {
      columnName: "MAX_TRANSACTION_AMOUNT",
      dataType: "DECIMAL(18,2)",
      sourceSchema: "CORE_TRANSACTIONS",
      sourceTable: "FCT_TRANSACTION",
      sourceColumn: "max(TRANSACTION_AMOUNT)",
      businessMeaning: "Maximum transaction amount",
      nullable: true,
    },
    {
      columnName: "DEBIT_TRANSACTION_COUNT",
      dataType: "NUMBER(15,0)",
      sourceSchema: "CORE_TRANSACTIONS",
      sourceTable: "FCT_TRANSACTION",
      sourceColumn: "count(TRANSACTION_ID WHERE TRANSACTION_TYPE_CODE='DEBIT')",
      businessMeaning: "Count of debit transactions",
      nullable: true,
    },
    {
      columnName: "DEBIT_TRANSACTION_VOLUME",
      dataType: "DECIMAL(18,2)",
      sourceSchema: "CORE_TRANSACTIONS",
      sourceTable: "FCT_TRANSACTION",
      sourceColumn: "sum(TRANSACTION_AMOUNT WHERE TRANSACTION_TYPE_CODE='DEBIT')",
      businessMeaning: "Total debit transaction volume",
      nullable: true,
    },
    {
      columnName: "CREDIT_TRANSACTION_COUNT",
      dataType: "NUMBER(15,0)",
      sourceSchema: "CORE_TRANSACTIONS",
      sourceTable: "FCT_TRANSACTION",
      sourceColumn: "count(TRANSACTION_ID WHERE TRANSACTION_TYPE_CODE='CREDIT')",
      businessMeaning: "Count of credit transactions",
      nullable: true,
    },
    {
      columnName: "CREDIT_TRANSACTION_VOLUME",
      dataType: "DECIMAL(18,2)",
      sourceSchema: "CORE_TRANSACTIONS",
      sourceTable: "FCT_TRANSACTION",
      sourceColumn: "sum(TRANSACTION_AMOUNT WHERE TRANSACTION_TYPE_CODE='CREDIT')",
      businessMeaning: "Total credit transaction volume",
      nullable: true,
    },
    {
      columnName: "TRANSFER_TRANSACTION_COUNT",
      dataType: "NUMBER(15,0)",
      sourceSchema: "CORE_TRANSACTIONS",
      sourceTable: "FCT_TRANSACTION",
      sourceColumn: "count(TRANSACTION_ID WHERE TRANSACTION_TYPE_CODE='TRANSFER')",
      businessMeaning: "Count of transfer transactions",
      nullable: true,
    },
    {
      columnName: "TRANSFER_TRANSACTION_VOLUME",
      dataType: "DECIMAL(18,2)",
      sourceSchema: "CORE_TRANSACTIONS",
      sourceTable: "FCT_TRANSACTION",
      sourceColumn: "sum(TRANSACTION_AMOUNT WHERE TRANSACTION_TYPE_CODE='TRANSFER')",
      businessMeaning: "Total transfer volume",
      nullable: true,
    },
    {
      columnName: "WITHDRAWAL_TRANSACTION_COUNT",
      dataType: "NUMBER(15,0)",
      sourceSchema: "CORE_TRANSACTIONS",
      sourceTable: "FCT_TRANSACTION",
      sourceColumn: "count(TRANSACTION_ID WHERE TRANSACTION_TYPE_CODE='WITHDRAWAL')",
      businessMeaning: "Count of withdrawal transactions",
      nullable: true,
    },
    {
      columnName: "WITHDRAWAL_TRANSACTION_VOLUME",
      dataType: "DECIMAL(18,2)",
      sourceSchema: "CORE_TRANSACTIONS",
      sourceTable: "FCT_TRANSACTION",
      sourceColumn: "sum(TRANSACTION_AMOUNT WHERE TRANSACTION_TYPE_CODE='WITHDRAWAL')",
      businessMeaning: "Total withdrawal volume",
      nullable: true,
    },
    {
      columnName: "DEPOSIT_TRANSACTION_COUNT",
      dataType: "NUMBER(15,0)",
      sourceSchema: "CORE_TRANSACTIONS",
      sourceTable: "FCT_TRANSACTION",
      sourceColumn: "count(TRANSACTION_ID WHERE TRANSACTION_TYPE_CODE='DEPOSIT')",
      businessMeaning: "Count of deposit transactions",
      nullable: true,
    },
    {
      columnName: "DEPOSIT_TRANSACTION_VOLUME",
      dataType: "DECIMAL(18,2)",
      sourceSchema: "CORE_TRANSACTIONS",
      sourceTable: "FCT_TRANSACTION",
      sourceColumn: "sum(TRANSACTION_AMOUNT WHERE TRANSACTION_TYPE_CODE='DEPOSIT')",
      businessMeaning: "Total deposit volume",
      nullable: true,
    },
    {
      columnName: "BRANCH_TRANSACTION_COUNT",
      dataType: "NUMBER(15,0)",
      sourceSchema: "CORE_TRANSACTIONS",
      sourceTable: "FCT_TRANSACTION",
      sourceColumn: "count(TRANSACTION_ID WHERE CHANNEL_CODE='BRANCH')",
      businessMeaning: "Count of branch transactions",
      nullable: true,
    },
    {
      columnName: "ATM_TRANSACTION_COUNT",
      dataType: "NUMBER(15,0)",
      sourceSchema: "CORE_TRANSACTIONS",
      sourceTable: "FCT_TRANSACTION",
      sourceColumn: "count(TRANSACTION_ID WHERE CHANNEL_CODE='ATM')",
      businessMeaning: "Count of ATM transactions",
      nullable: true,
    },
    {
      columnName: "ONLINE_TRANSACTION_COUNT",
      dataType: "NUMBER(15,0)",
      sourceSchema: "CORE_TRANSACTIONS",
      sourceTable: "FCT_TRANSACTION",
      sourceColumn: "count(TRANSACTION_ID WHERE CHANNEL_CODE='ONLINE')",
      businessMeaning: "Count of online transactions",
      nullable: true,
    },
    {
      columnName: "MOBILE_TRANSACTION_COUNT",
      dataType: "NUMBER(15,0)",
      sourceSchema: "CORE_TRANSACTIONS",
      sourceTable: "FCT_TRANSACTION",
      sourceColumn: "count(TRANSACTION_ID WHERE CHANNEL_CODE='MOBILE')",
      businessMeaning: "Count of mobile transactions",
      nullable: true,
    },
    {
      columnName: "PHONE_TRANSACTION_COUNT",
      dataType: "NUMBER(15,0)",
      sourceSchema: "CORE_TRANSACTIONS",
      sourceTable: "FCT_TRANSACTION",
      sourceColumn: "count(TRANSACTION_ID WHERE CHANNEL_CODE='PHONE')",
      businessMeaning: "Count of phone transactions",
      nullable: true,
    },
    {
      columnName: "CARD_TRANSACTION_COUNT",
      dataType: "NUMBER(15,0)",
      sourceSchema: "CORE_TRANSACTIONS",
      sourceTable: "FCT_TRANSACTION",
      sourceColumn: "count(TRANSACTION_ID WHERE CHANNEL_CODE='CARD')",
      businessMeaning: "Count of card transactions",
      nullable: true,
    },
    {
      columnName: "CARD_TRANSACTION_VOLUME",
      dataType: "DECIMAL(18,2)",
      sourceSchema: "CORE_TRANSACTIONS",
      sourceTable: "FCT_TRANSACTION",
      sourceColumn: "sum(TRANSACTION_AMOUNT WHERE CHANNEL_CODE='CARD')",
      businessMeaning: "Total card transaction volume",
      nullable: true,
    },
    {
      columnName: "POSTED_TRANSACTION_COUNT",
      dataType: "NUMBER(15,0)",
      sourceSchema: "CORE_TRANSACTIONS",
      sourceTable: "FCT_TRANSACTION",
      sourceColumn: "count(TRANSACTION_ID WHERE TRANSACTION_STATUS_CODE='POSTED')",
      businessMeaning: "Count of posted transactions",
      nullable: true,
    },
    {
      columnName: "PENDING_TRANSACTION_COUNT",
      dataType: "NUMBER(15,0)",
      sourceSchema: "CORE_TRANSACTIONS",
      sourceTable: "FCT_TRANSACTION",
      sourceColumn: "count(TRANSACTION_ID WHERE TRANSACTION_STATUS_CODE='PENDING')",
      businessMeaning: "Count of pending transactions",
      nullable: true,
    },
    {
      columnName: "FAILED_TRANSACTION_COUNT",
      dataType: "NUMBER(15,0)",
      sourceSchema: "CORE_TRANSACTIONS",
      sourceTable: "FCT_TRANSACTION",
      sourceColumn: "count(TRANSACTION_ID WHERE TRANSACTION_STATUS_CODE='FAILED')",
      businessMeaning: "Count of failed transactions",
      nullable: true,
    },
    {
      columnName: "REVERSED_TRANSACTION_COUNT",
      dataType: "NUMBER(15,0)",
      sourceSchema: "CORE_TRANSACTIONS",
      sourceTable: "FCT_TRANSACTION",
      sourceColumn: "count(TRANSACTION_ID WHERE TRANSACTION_STATUS_CODE='REVERSED')",
      businessMeaning: "Count of reversed transactions",
      nullable: true,
    },
    {
      columnName: "FRAUDULENT_TRANSACTION_COUNT",
      dataType: "NUMBER(15,0)",
      sourceSchema: "ANALYTICS",
      sourceTable: "FRAUD_DETECTION",
      sourceColumn: "count(TRANSACTION_ID WHERE FRAUD_FLAG='Y')",
      businessMeaning: "Count of fraudulent transactions",
      nullable: true,
    },
    {
      columnName: "FRAUDULENT_TRANSACTION_VOLUME",
      dataType: "DECIMAL(18,2)",
      sourceSchema: "ANALYTICS",
      sourceTable: "FRAUD_DETECTION",
      sourceColumn: "sum(TRANSACTION_AMOUNT WHERE FRAUD_FLAG='Y')",
      businessMeaning: "Total fraudulent transaction volume",
      nullable: true,
    },
    {
      columnName: "TOTAL_FEES_CHARGED",
      dataType: "DECIMAL(18,2)",
      sourceSchema: "CORE_TRANSACTIONS",
      sourceTable: "FCT_TRANSACTION",
      sourceColumn: "sum(FEES_CHARGED)",
      businessMeaning: "Total fees charged across all transactions",
      nullable: true,
    },
    {
      columnName: "AVERAGE_PROCESSING_TIME_MS",
      dataType: "DECIMAL(10,2)",
      sourceSchema: "CORE_TRANSACTIONS",
      sourceTable: "FCT_TRANSACTION",
      sourceColumn: "avg(PROCESSING_TIME_MILLISECONDS)",
      businessMeaning: "Average transaction processing time in ms",
      nullable: true,
    },
    {
      columnName: "DATA_LOAD_DATE",
      dataType: "DATE",
      sourceSchema: "SYSTEM",
      sourceTable: "SYSTEM_DATE",
      sourceColumn: "CURRENT_DATE",
      businessMeaning: "System load date",
      nullable: false,
    },
  ],
  estimatedRows: 10000,
  updateFrequency: "Daily",
  primaryKey: ["SUMMARY_DATE"],
  partitionBy: "SUMMARY_DATE",
  clusterBy: [],
};

// ============================================================================
// FCT_TRANSACTION_BY_MERCHANT - Merchant Transaction Fact Table
// ============================================================================
export const fctTransactionByMerchantTable: GoldTableSpec = {
  name: "FCT_TRANSACTION_BY_MERCHANT",
  schema: "ANALYTICS",
  type: "FACT",
  grain: "One row per merchant per day with aggregated metrics",
  description: "Daily aggregated transaction metrics by merchant for spending analysis, category trends, and merchant performance tracking",
  columns: [
    {
      columnName: "TRANSACTION_DATE",
      dataType: "DATE",
      sourceSchema: "CORE_TRANSACTIONS",
      sourceTable: "FCT_TRANSACTION",
      sourceColumn: "TRANSACTION_DATE",
      businessMeaning: "Date of transactions",
      nullable: false,
    },
    {
      columnName: "MERCHANT_ID",
      dataType: "VARCHAR(50)",
      sourceSchema: "CORE_TRANSACTIONS",
      sourceTable: "DIM_MERCHANT",
      sourceColumn: "MERCHANT_ID",
      businessMeaning: "Merchant identifier",
      nullable: false,
    },
    {
      columnName: "MERCHANT_CATEGORY_CODE",
      dataType: "VARCHAR(10)",
      sourceSchema: "CORE_TRANSACTIONS",
      sourceTable: "DIM_MERCHANT",
      sourceColumn: "MERCHANT_CATEGORY_CODE",
      businessMeaning: "Merchant Category Code (MCC)",
      nullable: false,
    },
    {
      columnName: "TRANSACTION_COUNT",
      dataType: "NUMBER(15,0)",
      sourceSchema: "CORE_TRANSACTIONS",
      sourceTable: "FCT_TRANSACTION",
      sourceColumn: "count(distinct TRANSACTION_ID)",
      businessMeaning: "Count of transactions with this merchant",
      nullable: false,
    },
    {
      columnName: "TOTAL_TRANSACTION_VOLUME",
      dataType: "DECIMAL(18,2)",
      sourceSchema: "CORE_TRANSACTIONS",
      sourceTable: "FCT_TRANSACTION",
      sourceColumn: "sum(TRANSACTION_AMOUNT)",
      businessMeaning: "Total transaction volume with merchant",
      nullable: false,
    },
    {
      columnName: "AVERAGE_TRANSACTION_AMOUNT",
      dataType: "DECIMAL(18,2)",
      sourceSchema: "CORE_TRANSACTIONS",
      sourceTable: "FCT_TRANSACTION",
      sourceColumn: "avg(TRANSACTION_AMOUNT)",
      businessMeaning: "Average transaction amount with merchant",
      nullable: true,
    },
    {
      columnName: "UNIQUE_CUSTOMER_COUNT",
      dataType: "NUMBER(15,0)",
      sourceSchema: "CORE_TRANSACTIONS",
      sourceTable: "FCT_TRANSACTION",
      sourceColumn: "count(distinct CUSTOMER_NUMBER)",
      businessMeaning: "Count of unique customers transacting with merchant",
      nullable: true,
    },
    {
      columnName: "FRAUDULENT_TRANSACTION_COUNT",
      dataType: "NUMBER(15,0)",
      sourceSchema: "ANALYTICS",
      sourceTable: "FRAUD_DETECTION",
      sourceColumn: "count(TRANSACTION_ID WHERE FRAUD_FLAG='Y')",
      businessMeaning: "Count of fraudulent transactions with merchant",
      nullable: true,
    },
    {
      columnName: "FRAUDULENT_TRANSACTION_VOLUME",
      dataType: "DECIMAL(18,2)",
      sourceSchema: "ANALYTICS",
      sourceTable: "FRAUD_DETECTION",
      sourceColumn: "sum(TRANSACTION_AMOUNT WHERE FRAUD_FLAG='Y')",
      businessMeaning: "Volume of fraudulent transactions",
      nullable: true,
    },
    {
      columnName: "DATA_LOAD_DATE",
      dataType: "DATE",
      sourceSchema: "SYSTEM",
      sourceTable: "SYSTEM_DATE",
      sourceColumn: "CURRENT_DATE",
      businessMeaning: "System load date",
      nullable: false,
    },
  ],
  estimatedRows: 50000000,
  updateFrequency: "Daily",
  primaryKey: ["TRANSACTION_DATE", "MERCHANT_ID"],
  partitionBy: "TRANSACTION_DATE",
  clusterBy: ["MERCHANT_ID", "MERCHANT_CATEGORY_CODE"],
};

// ============================================================================
// FCT_TRANSACTION_FRAUD_DETECTION - Fraud Detection Fact Table
// ============================================================================
export const fctTransactionFraudDetectionTable: GoldTableSpec = {
  name: "FCT_TRANSACTION_FRAUD_DETECTION",
  schema: "ANALYTICS",
  type: "FACT",
  grain: "One row per flagged transaction with fraud detection metadata",
  description: "Transactions flagged for fraud with detection rules, scores, and investigation status",
  columns: [
    {
      columnName: "TRANSACTION_ID",
      dataType: "VARCHAR(50)",
      sourceSchema: "CORE_TRANSACTIONS",
      sourceTable: "FCT_TRANSACTION",
      sourceColumn: "TRANSACTION_ID",
      businessMeaning: "Unique transaction identifier",
      nullable: false,
    },
    {
      columnName: "CUSTOMER_NUMBER",
      dataType: "VARCHAR(50)",
      sourceSchema: "CORE_CUSTOMERS",
      sourceTable: "DIM_CUSTOMER",
      sourceColumn: "CUSTOMER_NUMBER",
      businessMeaning: "Customer with flagged transaction",
      nullable: false,
    },
    {
      columnName: "TRANSACTION_DATE",
      dataType: "DATE",
      sourceSchema: "CORE_TRANSACTIONS",
      sourceTable: "FCT_TRANSACTION",
      sourceColumn: "TRANSACTION_DATE",
      businessMeaning: "Date of transaction",
      nullable: false,
    },
    {
      columnName: "TRANSACTION_AMOUNT",
      dataType: "DECIMAL(18,2)",
      sourceSchema: "CORE_TRANSACTIONS",
      sourceTable: "FCT_TRANSACTION",
      sourceColumn: "TRANSACTION_AMOUNT",
      businessMeaning: "Amount of flagged transaction",
      nullable: false,
    },
    {
      columnName: "FRAUD_SCORE",
      dataType: "DECIMAL(5,2)",
      sourceSchema: "ANALYTICS",
      sourceTable: "FRAUD_DETECTION",
      sourceColumn: "FRAUD_PROBABILITY_SCORE",
      businessMeaning: "Fraud probability score (0-100)",
      nullable: false,
    },
    {
      columnName: "FRAUD_RULE_TRIGGERED",
      dataType: "VARCHAR(100)",
      sourceSchema: "ANALYTICS",
      sourceTable: "FRAUD_DETECTION",
      sourceColumn: "FRAUD_RULE_NAME",
      businessMeaning: "Name of fraud rule that triggered",
      nullable: false,
    },
    {
      columnName: "FRAUD_CATEGORY",
      dataType: "VARCHAR(50)",
      sourceSchema: "ANALYTICS",
      sourceTable: "FRAUD_DETECTION",
      sourceColumn: "FRAUD_CATEGORY",
      businessMeaning: "Category of fraud (CARD_FRAUD, IDENTITY_THEFT, ACCOUNT_TAKEOVER, etc)",
      nullable: true,
    },
    {
      columnName: "DEVIATION_REASON",
      dataType: "VARCHAR(200)",
      sourceSchema: "ANALYTICS",
      sourceTable: "FRAUD_DETECTION",
      sourceColumn: "DEVIATION_REASON",
      businessMeaning: "Reason for fraud flag (unusual amount, location, velocity, etc)",
      nullable: true,
    },
    {
      columnName: "CUSTOMER_HISTORY_RISK_SCORE",
      dataType: "DECIMAL(5,2)",
      sourceSchema: "ANALYTICS",
      sourceTable: "FRAUD_DETECTION",
      sourceColumn: "CUSTOMER_HISTORY_RISK_SCORE",
      businessMeaning: "Customer historical risk score",
      nullable: true,
    },
    {
      columnName: "TRANSACTION_VELOCITY",
      dataType: "VARCHAR(20)",
      sourceSchema: "ANALYTICS",
      sourceTable: "FRAUD_DETECTION",
      sourceColumn: "TRANSACTION_VELOCITY",
      businessMeaning: "Transaction velocity (LOW, MEDIUM, HIGH, CRITICAL)",
      nullable: true,
    },
    {
      columnName: "GEOGRAPHIC_RISK",
      dataType: "VARCHAR(20)",
      sourceSchema: "ANALYTICS",
      sourceTable: "FRAUD_DETECTION",
      sourceColumn: "GEOGRAPHIC_RISK_LEVEL",
      businessMeaning: "Geographic risk level of transaction",
      nullable: true,
    },
    {
      columnName: "DEVICE_RISK",
      dataType: "VARCHAR(20)",
      sourceSchema: "ANALYTICS",
      sourceTable: "FRAUD_DETECTION",
      sourceColumn: "DEVICE_RISK_LEVEL",
      businessMeaning: "Device risk level (known, new, suspicious, blocked)",
      nullable: true,
    },
    {
      columnName: "INVESTIGATION_STATUS",
      dataType: "VARCHAR(20)",
      sourceSchema: "ANALYTICS",
      sourceTable: "FRAUD_DETECTION",
      sourceColumn: "INVESTIGATION_STATUS",
      businessMeaning: "Status of fraud investigation (FLAGGED, UNDER_REVIEW, CONFIRMED, DISMISSED)",
      nullable: true,
    },
    {
      columnName: "CONFIRMATION_DATE",
      dataType: "DATE",
      sourceSchema: "ANALYTICS",
      sourceTable: "FRAUD_DETECTION",
      sourceColumn: "CONFIRMATION_DATE",
      businessMeaning: "Date fraud was confirmed",
      nullable: true,
    },
    {
      columnName: "ACTION_TAKEN",
      dataType: "VARCHAR(100)",
      sourceSchema: "ANALYTICS",
      sourceTable: "FRAUD_DETECTION",
      sourceColumn: "ACTION_TAKEN",
      businessMeaning: "Action taken on fraudulent transaction (BLOCKED, DECLINED, CHALLENGED, etc)",
      nullable: true,
    },
    {
      columnName: "RECOVERY_AMOUNT",
      dataType: "DECIMAL(18,2)",
      sourceSchema: "ANALYTICS",
      sourceTable: "FRAUD_DETECTION",
      sourceColumn: "RECOVERY_AMOUNT",
      businessMeaning: "Amount recovered for fraud",
      nullable: true,
    },
    {
      columnName: "DATA_LOAD_DATE",
      dataType: "DATE",
      sourceSchema: "SYSTEM",
      sourceTable: "SYSTEM_DATE",
      sourceColumn: "CURRENT_DATE",
      businessMeaning: "System load date",
      nullable: false,
    },
  ],
  estimatedRows: 500000000,
  updateFrequency: "Real-time",
  primaryKey: ["TRANSACTION_ID"],
  partitionBy: "TRANSACTION_DATE",
  clusterBy: ["CUSTOMER_NUMBER", "FRAUD_SCORE"],
};

// ============================================================================
// DIM_MERCHANT - Merchant Dimension Table (SCD Type 2)
// ============================================================================
export const dimMerchantTable: GoldTableSpec = {
  name: "DIM_MERCHANT",
  schema: "ANALYTICS",
  type: "DIMENSION",
  grain: "One row per merchant version (SCD2)",
  description: "Merchant dimension with complete merchant information and history",
  columns: [
    {
      columnName: "MERCHANT_KEY",
      dataType: "NUMBER(18,0)",
      sourceSchema: "CORE_TRANSACTIONS",
      sourceTable: "DIM_MERCHANT",
      sourceColumn: "MERCHANT_KEY",
      businessMeaning: "Surrogate key for merchant dimension",
      nullable: false,
    },
    {
      columnName: "MERCHANT_ID",
      dataType: "VARCHAR(50)",
      sourceSchema: "CORE_TRANSACTIONS",
      sourceTable: "DIM_MERCHANT",
      sourceColumn: "MERCHANT_ID",
      businessMeaning: "Business key - merchant identifier",
      nullable: false,
    },
    {
      columnName: "MERCHANT_NAME",
      dataType: "VARCHAR(255)",
      sourceSchema: "CORE_TRANSACTIONS",
      sourceTable: "DIM_MERCHANT",
      sourceColumn: "MERCHANT_NAME",
      businessMeaning: "Name of merchant",
      nullable: false,
    },
    {
      columnName: "MERCHANT_CATEGORY_CODE",
      dataType: "VARCHAR(10)",
      sourceSchema: "CORE_TRANSACTIONS",
      sourceTable: "DIM_MERCHANT",
      sourceColumn: "MERCHANT_CATEGORY_CODE",
      businessMeaning: "Merchant Category Code (MCC)",
      nullable: false,
    },
    {
      columnName: "MERCHANT_CATEGORY_NAME",
      dataType: "VARCHAR(100)",
      sourceSchema: "CORE_TRANSACTIONS",
      sourceTable: "DIM_MERCHANT",
      sourceColumn: "MERCHANT_CATEGORY_NAME",
      businessMeaning: "Description of merchant category",
      nullable: true,
    },
    {
      columnName: "MERCHANT_COUNTRY",
      dataType: "VARCHAR(50)",
      sourceSchema: "CORE_TRANSACTIONS",
      sourceTable: "DIM_MERCHANT",
      sourceColumn: "MERCHANT_COUNTRY",
      businessMeaning: "Country of merchant",
      nullable: true,
    },
    {
      columnName: "MERCHANT_STATE",
      dataType: "VARCHAR(50)",
      sourceSchema: "CORE_TRANSACTIONS",
      sourceTable: "DIM_MERCHANT",
      sourceColumn: "MERCHANT_STATE",
      businessMeaning: "State/Province of merchant",
      nullable: true,
    },
    {
      columnName: "MERCHANT_CITY",
      dataType: "VARCHAR(100)",
      sourceSchema: "CORE_TRANSACTIONS",
      sourceTable: "DIM_MERCHANT",
      sourceColumn: "MERCHANT_CITY",
      businessMeaning: "City of merchant",
      nullable: true,
    },
    {
      columnName: "IS_FRAUD_RISK",
      dataType: "VARCHAR(1)",
      sourceSchema: "CORE_TRANSACTIONS",
      sourceTable: "DIM_MERCHANT",
      sourceColumn: "IS_FRAUD_RISK",
      businessMeaning: "Flag indicating merchant is fraud risk (Y/N)",
      nullable: true,
    },
    {
      columnName: "FRAUD_INCIDENT_COUNT",
      dataType: "NUMBER(10,0)",
      sourceSchema: "ANALYTICS",
      sourceTable: "FRAUD_DETECTION",
      sourceColumn: "count(distinct incident_id WHERE merchant_id = MERCHANT_ID)",
      businessMeaning: "Count of fraud incidents with merchant",
      nullable: true,
    },
    {
      columnName: "EFFECTIVE_DATE",
      dataType: "DATE",
      sourceSchema: "SYSTEM",
      sourceTable: "SCD_DATE",
      sourceColumn: "EFFECTIVE_DATE",
      businessMeaning: "SCD Type 2 effective date",
      nullable: false,
    },
    {
      columnName: "END_DATE",
      dataType: "DATE",
      sourceSchema: "SYSTEM",
      sourceTable: "SCD_DATE",
      sourceColumn: "END_DATE",
      businessMeaning: "SCD Type 2 end date (NULL if current)",
      nullable: true,
    },
    {
      columnName: "IS_CURRENT",
      dataType: "VARCHAR(1)",
      sourceSchema: "SYSTEM",
      sourceTable: "SCD_DATE",
      sourceColumn: "IS_CURRENT",
      businessMeaning: "Flag indicating current version (Y/N)",
      nullable: false,
    },
  ],
  estimatedRows: 50000000,
  updateFrequency: "Daily",
  primaryKey: ["MERCHANT_KEY"],
  clusterBy: ["MERCHANT_ID", "MERCHANT_CATEGORY_CODE"],
};

// ============================================================================
// DIM_CHANNEL - Channel Dimension Table
// ============================================================================
export const dimChannelTable: GoldTableSpec = {
  name: "DIM_CHANNEL",
  schema: "ANALYTICS",
  type: "DIMENSION",
  grain: "One row per channel",
  description: "Transaction channel dimension with channel attributes",
  columns: [
    {
      columnName: "CHANNEL_KEY",
      dataType: "NUMBER(18,0)",
      sourceSchema: "CORE_TRANSACTIONS",
      sourceTable: "DIM_CHANNEL",
      sourceColumn: "CHANNEL_KEY",
      businessMeaning: "Surrogate key for channel dimension",
      nullable: false,
    },
    {
      columnName: "CHANNEL_CODE",
      dataType: "VARCHAR(20)",
      sourceSchema: "CORE_TRANSACTIONS",
      sourceTable: "DIM_CHANNEL",
      sourceColumn: "CHANNEL_CODE",
      businessMeaning: "Business key - channel code",
      nullable: false,
    },
    {
      columnName: "CHANNEL_NAME",
      dataType: "VARCHAR(100)",
      sourceSchema: "CORE_TRANSACTIONS",
      sourceTable: "DIM_CHANNEL",
      sourceColumn: "CHANNEL_NAME",
      businessMeaning: "Full channel name",
      nullable: false,
    },
    {
      columnName: "CHANNEL_DESCRIPTION",
      dataType: "VARCHAR(255)",
      sourceSchema: "CORE_TRANSACTIONS",
      sourceTable: "DIM_CHANNEL",
      sourceColumn: "CHANNEL_DESCRIPTION",
      businessMeaning: "Description of channel",
      nullable: true,
    },
    {
      columnName: "CHANNEL_TYPE",
      dataType: "VARCHAR(50)",
      sourceSchema: "CORE_TRANSACTIONS",
      sourceTable: "DIM_CHANNEL",
      sourceColumn: "CHANNEL_TYPE",
      businessMeaning: "Type of channel (PHYSICAL, DIGITAL, HYBRID)",
      nullable: true,
    },
    {
      columnName: "IS_REAL_TIME",
      dataType: "VARCHAR(1)",
      sourceSchema: "CORE_TRANSACTIONS",
      sourceTable: "DIM_CHANNEL",
      sourceColumn: "IS_REAL_TIME",
      businessMeaning: "Flag indicating real-time processing (Y/N)",
      nullable: true,
    },
    {
      columnName: "AVERAGE_PROCESSING_TIME_MS",
      dataType: "DECIMAL(10,2)",
      sourceSchema: "CORE_TRANSACTIONS",
      sourceTable: "DIM_CHANNEL",
      sourceColumn: "AVERAGE_PROCESSING_TIME_MS",
      businessMeaning: "Average processing time for channel",
      nullable: true,
    },
  ],
  estimatedRows: 20,
  updateFrequency: "Monthly",
  primaryKey: ["CHANNEL_KEY"],
  clusterBy: ["CHANNEL_CODE"],
};

// ============================================================================
// DIM_TRANSACTION_TYPE - Transaction Type Dimension Table
// ============================================================================
export const dimTransactionTypeTable: GoldTableSpec = {
  name: "DIM_TRANSACTION_TYPE",
  schema: "ANALYTICS",
  type: "DIMENSION",
  grain: "One row per transaction type",
  description: "Transaction type dimension with type attributes",
  columns: [
    {
      columnName: "TRANSACTION_TYPE_KEY",
      dataType: "NUMBER(18,0)",
      sourceSchema: "CORE_TRANSACTIONS",
      sourceTable: "DIM_TRANSACTION_TYPE",
      sourceColumn: "TRANSACTION_TYPE_KEY",
      businessMeaning: "Surrogate key for transaction type",
      nullable: false,
    },
    {
      columnName: "TRANSACTION_TYPE_CODE",
      dataType: "VARCHAR(20)",
      sourceSchema: "CORE_TRANSACTIONS",
      sourceTable: "DIM_TRANSACTION_TYPE",
      sourceColumn: "TRANSACTION_TYPE_CODE",
      businessMeaning: "Business key - transaction type code",
      nullable: false,
    },
    {
      columnName: "TRANSACTION_TYPE_NAME",
      dataType: "VARCHAR(100)",
      sourceSchema: "CORE_TRANSACTIONS",
      sourceTable: "DIM_TRANSACTION_TYPE",
      sourceColumn: "TRANSACTION_TYPE_NAME",
      businessMeaning: "Full transaction type name",
      nullable: false,
    },
    {
      columnName: "TRANSACTION_TYPE_DESCRIPTION",
      dataType: "VARCHAR(255)",
      sourceSchema: "CORE_TRANSACTIONS",
      sourceTable: "DIM_TRANSACTION_TYPE",
      sourceColumn: "TRANSACTION_TYPE_DESCRIPTION",
      businessMeaning: "Description of transaction type",
      nullable: true,
    },
    {
      columnName: "INCREASES_BALANCE",
      dataType: "VARCHAR(1)",
      sourceSchema: "CORE_TRANSACTIONS",
      sourceTable: "DIM_TRANSACTION_TYPE",
      sourceColumn: "INCREASES_BALANCE",
      businessMeaning: "Flag indicating if type increases balance (Y/N)",
      nullable: true,
    },
    {
      columnName: "REQUIRES_AUTHORIZATION",
      dataType: "VARCHAR(1)",
      sourceSchema: "CORE_TRANSACTIONS",
      sourceTable: "DIM_TRANSACTION_TYPE",
      sourceColumn: "REQUIRES_AUTHORIZATION",
      businessMeaning: "Flag indicating if authorization required (Y/N)",
      nullable: true,
    },
  ],
  estimatedRows: 50,
  updateFrequency: "Monthly",
  primaryKey: ["TRANSACTION_TYPE_KEY"],
  clusterBy: ["TRANSACTION_TYPE_CODE"],
};

// ============================================================================
// CUSTOMER_TRANSACTION_AGGR - Customer Transaction Aggregated View
// ============================================================================
export const customerTransactionAggrTable: GoldTableSpec = {
  name: "CUSTOMER_TRANSACTION_AGGR",
  schema: "ANALYTICS",
  type: "AGGREGATE",
  grain: "One row per customer with consolidated transaction metrics",
  description: "Comprehensive customer transaction aggregation with spending patterns, behavioral metrics, and risk indicators",
  columns: [
    {
      columnName: "CUSTOMER_NUMBER",
      dataType: "VARCHAR(50)",
      sourceSchema: "CORE_CUSTOMERS",
      sourceTable: "DIM_CUSTOMER",
      sourceColumn: "CUSTOMER_NUMBER",
      businessMeaning: "Unique customer identifier",
      nullable: false,
    },
    {
      columnName: "CUSTOMER_NAME",
      dataType: "VARCHAR(100)",
      sourceSchema: "CORE_CUSTOMERS",
      sourceTable: "DIM_CUSTOMER",
      sourceColumn: "CUSTOMER_NAME",
      businessMeaning: "Customer name",
      nullable: false,
    },
    {
      columnName: "TOTAL_TRANSACTION_COUNT_12M",
      dataType: "NUMBER(15,0)",
      sourceSchema: "CORE_TRANSACTIONS",
      sourceTable: "FCT_TRANSACTION",
      sourceColumn: "count(distinct TRANSACTION_ID WHERE TRANSACTION_DATE >= CURRENT_DATE - 365)",
      businessMeaning: "Total transactions in last 12 months",
      nullable: true,
    },
    {
      columnName: "TOTAL_TRANSACTION_VOLUME_12M",
      dataType: "DECIMAL(18,2)",
      sourceSchema: "CORE_TRANSACTIONS",
      sourceTable: "FCT_TRANSACTION",
      sourceColumn: "sum(TRANSACTION_AMOUNT WHERE TRANSACTION_DATE >= CURRENT_DATE - 365)",
      businessMeaning: "Total transaction volume in last 12 months",
      nullable: true,
    },
    {
      columnName: "AVERAGE_MONTHLY_VOLUME",
      dataType: "DECIMAL(18,2)",
      sourceSchema: "CORE_TRANSACTIONS",
      sourceTable: "FCT_TRANSACTION",
      sourceColumn: "sum(TRANSACTION_AMOUNT WHERE TRANSACTION_DATE >= CURRENT_DATE - 365) / 12",
      businessMeaning: "Average monthly transaction volume",
      nullable: true,
    },
    {
      columnName: "AVERAGE_TRANSACTION_AMOUNT",
      dataType: "DECIMAL(18,2)",
      sourceSchema: "CORE_TRANSACTIONS",
      sourceTable: "FCT_TRANSACTION",
      sourceColumn: "avg(TRANSACTION_AMOUNT WHERE TRANSACTION_DATE >= CURRENT_DATE - 365)",
      businessMeaning: "Average transaction amount",
      nullable: true,
    },
    {
      columnName: "DEBIT_TRANSACTION_COUNT_12M",
      dataType: "NUMBER(15,0)",
      sourceSchema: "CORE_TRANSACTIONS",
      sourceTable: "FCT_TRANSACTION",
      sourceColumn: "count(TRANSACTION_ID WHERE TRANSACTION_TYPE_CODE='DEBIT' AND TRANSACTION_DATE >= CURRENT_DATE - 365)",
      businessMeaning: "Count of debit transactions in 12 months",
      nullable: true,
    },
    {
      columnName: "DEBIT_VOLUME_12M",
      dataType: "DECIMAL(18,2)",
      sourceSchema: "CORE_TRANSACTIONS",
      sourceTable: "FCT_TRANSACTION",
      sourceColumn: "sum(TRANSACTION_AMOUNT WHERE TRANSACTION_TYPE_CODE='DEBIT' AND TRANSACTION_DATE >= CURRENT_DATE - 365)",
      businessMeaning: "Total debit volume in 12 months",
      nullable: true,
    },
    {
      columnName: "CREDIT_TRANSACTION_COUNT_12M",
      dataType: "NUMBER(15,0)",
      sourceSchema: "CORE_TRANSACTIONS",
      sourceTable: "FCT_TRANSACTION",
      sourceColumn: "count(TRANSACTION_ID WHERE TRANSACTION_TYPE_CODE='CREDIT' AND TRANSACTION_DATE >= CURRENT_DATE - 365)",
      businessMeaning: "Count of credit transactions in 12 months",
      nullable: true,
    },
    {
      columnName: "CREDIT_VOLUME_12M",
      dataType: "DECIMAL(18,2)",
      sourceSchema: "CORE_TRANSACTIONS",
      sourceTable: "FCT_TRANSACTION",
      sourceColumn: "sum(TRANSACTION_AMOUNT WHERE TRANSACTION_TYPE_CODE='CREDIT' AND TRANSACTION_DATE >= CURRENT_DATE - 365)",
      businessMeaning: "Total credit volume in 12 months",
      nullable: true,
    },
    {
      columnName: "TRANSFER_TRANSACTION_COUNT_12M",
      dataType: "NUMBER(15,0)",
      sourceSchema: "CORE_TRANSACTIONS",
      sourceTable: "FCT_TRANSACTION",
      sourceColumn: "count(TRANSACTION_ID WHERE TRANSACTION_TYPE_CODE='TRANSFER' AND TRANSACTION_DATE >= CURRENT_DATE - 365)",
      businessMeaning: "Count of transfer transactions in 12 months",
      nullable: true,
    },
    {
      columnName: "TRANSFER_VOLUME_12M",
      dataType: "DECIMAL(18,2)",
      sourceSchema: "CORE_TRANSACTIONS",
      sourceTable: "FCT_TRANSACTION",
      sourceColumn: "sum(TRANSACTION_AMOUNT WHERE TRANSACTION_TYPE_CODE='TRANSFER' AND TRANSACTION_DATE >= CURRENT_DATE - 365)",
      businessMeaning: "Total transfer volume in 12 months",
      nullable: true,
    },
    {
      columnName: "CARD_TRANSACTION_COUNT_12M",
      dataType: "NUMBER(15,0)",
      sourceSchema: "CORE_TRANSACTIONS",
      sourceTable: "FCT_TRANSACTION",
      sourceColumn: "count(TRANSACTION_ID WHERE CHANNEL_CODE='CARD' AND TRANSACTION_DATE >= CURRENT_DATE - 365)",
      businessMeaning: "Count of card transactions in 12 months",
      nullable: true,
    },
    {
      columnName: "CARD_VOLUME_12M",
      dataType: "DECIMAL(18,2)",
      sourceSchema: "CORE_TRANSACTIONS",
      sourceTable: "FCT_TRANSACTION",
      sourceColumn: "sum(TRANSACTION_AMOUNT WHERE CHANNEL_CODE='CARD' AND TRANSACTION_DATE >= CURRENT_DATE - 365)",
      businessMeaning: "Total card spending in 12 months",
      nullable: true,
    },
    {
      columnName: "MOBILE_TRANSACTION_COUNT_12M",
      dataType: "NUMBER(15,0)",
      sourceSchema: "CORE_TRANSACTIONS",
      sourceTable: "FCT_TRANSACTION",
      sourceColumn: "count(TRANSACTION_ID WHERE CHANNEL_CODE='MOBILE' AND TRANSACTION_DATE >= CURRENT_DATE - 365)",
      businessMeaning: "Count of mobile transactions in 12 months",
      nullable: true,
    },
    {
      columnName: "ONLINE_TRANSACTION_COUNT_12M",
      dataType: "NUMBER(15,0)",
      sourceSchema: "CORE_TRANSACTIONS",
      sourceTable: "FCT_TRANSACTION",
      sourceColumn: "count(TRANSACTION_ID WHERE CHANNEL_CODE='ONLINE' AND TRANSACTION_DATE >= CURRENT_DATE - 365)",
      businessMeaning: "Count of online transactions in 12 months",
      nullable: true,
    },
    {
      columnName: "BRANCH_TRANSACTION_COUNT_12M",
      dataType: "NUMBER(15,0)",
      sourceSchema: "CORE_TRANSACTIONS",
      sourceTable: "FCT_TRANSACTION",
      sourceColumn: "count(TRANSACTION_ID WHERE CHANNEL_CODE='BRANCH' AND TRANSACTION_DATE >= CURRENT_DATE - 365)",
      businessMeaning: "Count of branch transactions in 12 months",
      nullable: true,
    },
    {
      columnName: "ATM_TRANSACTION_COUNT_12M",
      dataType: "NUMBER(15,0)",
      sourceSchema: "CORE_TRANSACTIONS",
      sourceTable: "FCT_TRANSACTION",
      sourceColumn: "count(TRANSACTION_ID WHERE CHANNEL_CODE='ATM' AND TRANSACTION_DATE >= CURRENT_DATE - 365)",
      businessMeaning: "Count of ATM transactions in 12 months",
      nullable: true,
    },
    {
      columnName: "TOP_SPENDING_CATEGORY",
      dataType: "VARCHAR(100)",
      sourceSchema: "ANALYTICS",
      sourceTable: "CALCULATED",
      sourceColumn: "MODE(MERCHANT_CATEGORY_NAME ORDER BY sum(TRANSACTION_AMOUNT)) FILTER (WHERE TRANSACTION_DATE >= CURRENT_DATE - 365)",
      businessMeaning: "Top merchant category by spending",
      nullable: true,
    },
    {
      columnName: "TOP_SPENDING_CATEGORY_VOLUME",
      dataType: "DECIMAL(18,2)",
      sourceSchema: "ANALYTICS",
      sourceTable: "CALCULATED",
      sourceColumn: "sum(TRANSACTION_AMOUNT WHERE MERCHANT_CATEGORY_NAME = TOP_SPENDING_CATEGORY AND TRANSACTION_DATE >= CURRENT_DATE - 365)",
      businessMeaning: "Volume in top spending category",
      nullable: true,
    },
    {
      columnName: "UNIQUE_MERCHANT_COUNT_12M",
      dataType: "NUMBER(10,0)",
      sourceSchema: "CORE_TRANSACTIONS",
      sourceTable: "FCT_TRANSACTION",
      sourceColumn: "count(distinct MERCHANT_ID WHERE TRANSACTION_DATE >= CURRENT_DATE - 365)",
      businessMeaning: "Count of unique merchants transacted with",
      nullable: true,
    },
    {
      columnName: "UNIQUE_CHANNEL_COUNT",
      dataType: "NUMBER(5,0)",
      sourceSchema: "CORE_TRANSACTIONS",
      sourceTable: "FCT_TRANSACTION",
      sourceColumn: "count(distinct CHANNEL_CODE WHERE TRANSACTION_DATE >= CURRENT_DATE - 365)",
      businessMeaning: "Count of unique channels used",
      nullable: true,
    },
    {
      columnName: "DAYS_SINCE_LAST_TRANSACTION",
      dataType: "NUMBER(5,0)",
      sourceSchema: "CORE_TRANSACTIONS",
      sourceTable: "FCT_TRANSACTION",
      sourceColumn: "DATEDIFF(day, max(TRANSACTION_DATE), CURRENT_DATE)",
      businessMeaning: "Days since last transaction",
      nullable: true,
    },
    {
      columnName: "FRAUDULENT_TRANSACTION_COUNT_12M",
      dataType: "NUMBER(10,0)",
      sourceSchema: "ANALYTICS",
      sourceTable: "FRAUD_DETECTION",
      sourceColumn: "count(TRANSACTION_ID WHERE FRAUD_FLAG='Y' AND TRANSACTION_DATE >= CURRENT_DATE - 365)",
      businessMeaning: "Count of fraudulent transactions in 12 months",
      nullable: true,
    },
    {
      columnName: "FRAUDULENT_TRANSACTION_VOLUME_12M",
      dataType: "DECIMAL(18,2)",
      sourceSchema: "ANALYTICS",
      sourceTable: "FRAUD_DETECTION",
      sourceColumn: "sum(TRANSACTION_AMOUNT WHERE FRAUD_FLAG='Y' AND TRANSACTION_DATE >= CURRENT_DATE - 365)",
      businessMeaning: "Volume of fraudulent transactions in 12 months",
      nullable: true,
    },
    {
      columnName: "FRAUD_RATE_PCT",
      dataType: "DECIMAL(5,2)",
      sourceSchema: "ANALYTICS",
      sourceTable: "CALCULATED",
      sourceColumn: "(count(TRANSACTION_ID WHERE FRAUD_FLAG='Y' AND TRANSACTION_DATE >= CURRENT_DATE - 365) / count(TRANSACTION_ID WHERE TRANSACTION_DATE >= CURRENT_DATE - 365)) * 100",
      businessMeaning: "Percentage of transactions flagged as fraudulent",
      nullable: true,
    },
    {
      columnName: "FAILED_TRANSACTION_COUNT_12M",
      dataType: "NUMBER(10,0)",
      sourceSchema: "CORE_TRANSACTIONS",
      sourceTable: "FCT_TRANSACTION",
      sourceColumn: "count(TRANSACTION_ID WHERE TRANSACTION_STATUS_CODE='FAILED' AND TRANSACTION_DATE >= CURRENT_DATE - 365)",
      businessMeaning: "Count of failed transactions in 12 months",
      nullable: true,
    },
    {
      columnName: "TRANSACTION_VELOCITY_30D",
      dataType: "NUMBER(10,0)",
      sourceSchema: "CORE_TRANSACTIONS",
      sourceTable: "FCT_TRANSACTION",
      sourceColumn: "count(TRANSACTION_ID WHERE TRANSACTION_DATE >= CURRENT_DATE - 30)",
      businessMeaning: "Transaction count in last 30 days",
      nullable: true,
    },
    {
      columnName: "SPENDING_VOLATILITY_SCORE",
      dataType: "DECIMAL(5,2)",
      sourceSchema: "ANALYTICS",
      sourceTable: "CALCULATED",
      sourceColumn: "STDDEV(monthly_volumes) OVER (PARTITION BY CUSTOMER_NUMBER ORDER BY MONTH ROWS BETWEEN 11 PRECEDING AND CURRENT ROW)",
      businessMeaning: "Standard deviation of monthly spending amounts",
      nullable: true,
    },
    {
      columnName: "CUSTOMER_SEGMENT",
      dataType: "VARCHAR(50)",
      sourceSchema: "ANALYTICS",
      sourceTable: "CUSTOMER_SEGMENTATION",
      sourceColumn: "CUSTOMER_SEGMENT",
      businessMeaning: "Customer value segment based on transactions",
      nullable: true,
    },
    {
      columnName: "PRCS_DTE",
      dataType: "DATE",
      sourceSchema: "SYSTEM",
      sourceTable: "SYSTEM_DATE",
      sourceColumn: "BUSINESS_DATE",
      businessMeaning: "Processing/business date for aggregate snapshot",
      nullable: false,
    },
    {
      columnName: "DATA_LOAD_DATE",
      dataType: "DATE",
      sourceSchema: "SYSTEM",
      sourceTable: "SYSTEM_DATE",
      sourceColumn: "CURRENT_DATE",
      businessMeaning: "System load date",
      nullable: false,
    },
  ],
  estimatedRows: 5500000,
  updateFrequency: "Daily",
  primaryKey: ["CUSTOMER_NUMBER", "PRCS_DTE"],
  partitionBy: "PRCS_DTE",
  clusterBy: ["CUSTOMER_NUMBER"],
};

// ============================================================================
// GOLD TABLE CATALOG
// ============================================================================
export const transactionsGoldTableCatalog = {
  facts: [
    fctTransactionDetailTable,
    fctTransactionDailySummaryTable,
    fctTransactionByMerchantTable,
    fctTransactionFraudDetectionTable,
  ],
  dimensions: [dimMerchantTable, dimChannelTable, dimTransactionTypeTable],
  aggregates: [customerTransactionAggrTable],
  totalTables: 8,
  description: "Complete Gold Layer DDL specifications for Transactions domain with detailed column metadata and analytics tables",
};

export default transactionsGoldTableCatalog;
