/**
 * BRANCH-RETAIL ERD DEFINITIONS
 * 
 * Logical and Physical ERD definitions for branch operations
 * Sources: Branch systems, Teller platforms, ATM networks, Appointment systems
 */

// LOGICAL ERD - Business Model
export const branchRetailLogicalERD = {
  entities: [
    {
      name: 'Branch',
      type: 'core',
      description: 'Physical branch locations',
      attributes: [
        { name: 'branch_id', type: 'BIGINT', isPrimaryKey: true },
        { name: 'branch_code', type: 'STRING', description: 'Branch identifier code' },
        { name: 'branch_name', type: 'STRING', description: 'Branch name' },
        { name: 'branch_type', type: 'STRING', description: 'Full Service|Limited Service|In-Store|Drive-Through' },
        { name: 'branch_status', type: 'STRING', description: 'Active|Temporarily Closed|Permanently Closed' },
        { name: 'address_line1', type: 'STRING' },
        { name: 'city', type: 'STRING' },
        { name: 'state', type: 'STRING' },
        { name: 'postal_code', type: 'STRING' },
        { name: 'latitude', type: 'DECIMAL(10,8)' },
        { name: 'longitude', type: 'DECIMAL(11,8)' },
        { name: 'branch_manager_id', type: 'BIGINT', isForeignKey: true },
        { name: 'open_date', type: 'DATE', description: 'Branch opening date' },
        { name: 'close_date', type: 'DATE', description: 'Branch closure date if closed' },
        { name: 'square_footage', type: 'INTEGER', description: 'Branch size in sq ft' },
        { name: 'teller_count', type: 'INTEGER', description: 'Number of teller stations' },
        { name: 'atm_count', type: 'INTEGER', description: 'Number of ATMs at branch' },
        { name: 'drive_through_lanes', type: 'INTEGER' },
        { name: 'safe_deposit_boxes', type: 'INTEGER', description: 'Number of safe deposit boxes' },
      ],
    },
    {
      name: 'Teller Transaction',
      type: 'event',
      description: 'Teller-processed transactions',
      attributes: [
        { name: 'transaction_id', type: 'BIGINT', isPrimaryKey: true },
        { name: 'branch_id', type: 'BIGINT', isForeignKey: true },
        { name: 'teller_id', type: 'BIGINT', isForeignKey: true },
        { name: 'customer_id', type: 'BIGINT', isForeignKey: true },
        { name: 'transaction_timestamp', type: 'TIMESTAMP' },
        { name: 'transaction_type', type: 'STRING', description: 'Deposit|Withdrawal|Transfer|Payment|Account Opening' },
        { name: 'transaction_amount', type: 'DECIMAL(18,2)' },
        { name: 'account_id', type: 'BIGINT', isForeignKey: true, description: 'Related account' },
        { name: 'transaction_status', type: 'STRING', description: 'Completed|Reversed|Failed' },
        { name: 'service_time_seconds', type: 'INTEGER', description: 'Time taken to complete' },
        { name: 'wait_time_seconds', type: 'INTEGER', description: 'Customer wait time' },
        { name: 'transaction_channel', type: 'STRING', description: 'Lobby|Drive-Through' },
      ],
    },
    {
      name: 'Branch Visit',
      type: 'event',
      description: 'Customer branch visits and traffic',
      attributes: [
        { name: 'visit_id', type: 'BIGINT', isPrimaryKey: true },
        { name: 'branch_id', type: 'BIGINT', isForeignKey: true },
        { name: 'customer_id', type: 'BIGINT', isForeignKey: true },
        { name: 'visit_date', type: 'DATE' },
        { name: 'visit_timestamp', type: 'TIMESTAMP', description: 'Check-in time' },
        { name: 'exit_timestamp', type: 'TIMESTAMP', description: 'Exit time' },
        { name: 'visit_type', type: 'STRING', description: 'Transaction|Service Request|Inquiry|Appointment' },
        { name: 'visit_channel', type: 'STRING', description: 'Lobby|Drive-Through|ATM' },
        { name: 'wait_time_minutes', type: 'INTEGER' },
        { name: 'service_time_minutes', type: 'INTEGER' },
        { name: 'served_by_employee_id', type: 'BIGINT', isForeignKey: true },
        { name: 'transactions_completed', type: 'INTEGER' },
        { name: 'appointment_flag', type: 'BOOLEAN' },
      ],
    },
    {
      name: 'Branch Employee',
      type: 'core',
      description: 'Branch staff and tellers',
      attributes: [
        { name: 'employee_id', type: 'BIGINT', isPrimaryKey: true },
        { name: 'branch_id', type: 'BIGINT', isForeignKey: true },
        { name: 'employee_number', type: 'STRING' },
        { name: 'first_name', type: 'STRING' },
        { name: 'last_name', type: 'STRING' },
        { name: 'job_title', type: 'STRING', description: 'Teller|Personal Banker|Manager|CSR' },
        { name: 'job_level', type: 'STRING', description: 'Entry|Mid|Senior|Manager' },
        { name: 'hire_date', type: 'DATE' },
        { name: 'termination_date', type: 'DATE' },
        { name: 'employment_status', type: 'STRING', description: 'Active|On Leave|Terminated' },
        { name: 'full_time_flag', type: 'BOOLEAN' },
        { name: 'teller_drawer_limit', type: 'DECIMAL(18,2)', description: 'Cash handling limit' },
      ],
    },
    {
      name: 'ATM',
      type: 'core',
      description: 'ATM machines and locations',
      attributes: [
        { name: 'atm_id', type: 'BIGINT', isPrimaryKey: true },
        { name: 'atm_number', type: 'STRING', description: 'ATM identifier' },
        { name: 'branch_id', type: 'BIGINT', isForeignKey: true },
        { name: 'atm_location_type', type: 'STRING', description: 'Branch|Off-Site|In-Store|Airport' },
        { name: 'atm_type', type: 'STRING', description: 'Full Service|Cash Only|Deposit Capable' },
        { name: 'atm_status', type: 'STRING', description: 'Active|Out of Service|Under Maintenance' },
        { name: 'address_line1', type: 'STRING' },
        { name: 'city', type: 'STRING' },
        { name: 'state', type: 'STRING' },
        { name: 'postal_code', type: 'STRING' },
        { name: 'install_date', type: 'DATE' },
        { name: 'last_maintenance_date', type: 'DATE' },
        { name: 'cash_capacity', type: 'DECIMAL(18,2)', description: 'Max cash in ATM' },
      ],
    },
    {
      name: 'ATM Transaction',
      type: 'event',
      description: 'ATM transactions',
      attributes: [
        { name: 'transaction_id', type: 'BIGINT', isPrimaryKey: true },
        { name: 'atm_id', type: 'BIGINT', isForeignKey: true },
        { name: 'card_id', type: 'BIGINT', isForeignKey: true },
        { name: 'customer_id', type: 'BIGINT', isForeignKey: true },
        { name: 'transaction_timestamp', type: 'TIMESTAMP' },
        { name: 'transaction_type', type: 'STRING', description: 'Withdrawal|Deposit|Balance Inquiry|Transfer' },
        { name: 'transaction_amount', type: 'DECIMAL(18,2)' },
        { name: 'transaction_status', type: 'STRING', description: 'Approved|Declined|Partial|Timeout' },
        { name: 'fee_amount', type: 'DECIMAL(18,2)', description: 'ATM surcharge' },
        { name: 'account_id', type: 'BIGINT', isForeignKey: true },
        { name: 'network', type: 'STRING', description: 'Own|Allpoint|MoneyPass|Plus|Cirrus' },
      ],
    },
    {
      name: 'Appointment',
      type: 'event',
      description: 'Branch appointments',
      attributes: [
        { name: 'appointment_id', type: 'BIGINT', isPrimaryKey: true },
        { name: 'branch_id', type: 'BIGINT', isForeignKey: true },
        { name: 'customer_id', type: 'BIGINT', isForeignKey: true },
        { name: 'employee_id', type: 'BIGINT', isForeignKey: true },
        { name: 'appointment_date', type: 'DATE' },
        { name: 'appointment_time', type: 'TIME' },
        { name: 'appointment_type', type: 'STRING', description: 'Loan|Account Opening|Financial Review|General' },
        { name: 'appointment_status', type: 'STRING', description: 'Scheduled|Completed|Cancelled|No-Show' },
        { name: 'duration_minutes', type: 'INTEGER' },
        { name: 'scheduled_timestamp', type: 'TIMESTAMP', description: 'When appointment was booked' },
        { name: 'channel_booked', type: 'STRING', description: 'Online|Mobile App|Phone|In-Branch' },
      ],
    },
    {
      name: 'Branch Daily Snapshot',
      type: 'aggregated',
      description: 'Daily branch performance metrics',
      attributes: [
        { name: 'snapshot_id', type: 'BIGINT', isPrimaryKey: true },
        { name: 'branch_id', type: 'BIGINT', isForeignKey: true },
        { name: 'snapshot_date', type: 'DATE' },
        { name: 'total_visits', type: 'INTEGER' },
        { name: 'total_transactions', type: 'INTEGER' },
        { name: 'total_transaction_amount', type: 'DECIMAL(18,2)' },
        { name: 'average_wait_time_minutes', type: 'DECIMAL(10,2)' },
        { name: 'average_service_time_minutes', type: 'DECIMAL(10,2)' },
        { name: 'lobby_traffic', type: 'INTEGER' },
        { name: 'drive_through_traffic', type: 'INTEGER' },
        { name: 'atm_traffic', type: 'INTEGER' },
        { name: 'new_accounts_opened', type: 'INTEGER' },
        { name: 'staff_present', type: 'INTEGER', description: 'Staff count for day' },
      ],
    },
  ],
  
  relationships: [
    {
      from: 'Branch Employee',
      to: 'Branch',
      type: 'many-to-one',
      cardinality: 'N:1',
      foreignKey: 'branch_id',
      description: 'Employees work at branches',
    },
    {
      from: 'ATM',
      to: 'Branch',
      type: 'many-to-one',
      cardinality: 'N:1',
      foreignKey: 'branch_id',
      description: 'ATMs located at branches',
    },
    {
      from: 'Teller Transaction',
      to: 'Branch',
      type: 'many-to-one',
      cardinality: 'N:1',
      foreignKey: 'branch_id',
      description: 'Transactions processed at branches',
    },
    {
      from: 'Teller Transaction',
      to: 'Branch Employee',
      type: 'many-to-one',
      cardinality: 'N:1',
      foreignKey: 'teller_id',
      description: 'Teller processes transactions',
    },
    {
      from: 'Branch Visit',
      to: 'Branch',
      type: 'many-to-one',
      cardinality: 'N:1',
      foreignKey: 'branch_id',
      description: 'Visits occur at branches',
    },
    {
      from: 'Appointment',
      to: 'Branch',
      type: 'many-to-one',
      cardinality: 'N:1',
      foreignKey: 'branch_id',
      description: 'Appointments scheduled at branches',
    },
    {
      from: 'Appointment',
      to: 'Branch Employee',
      type: 'many-to-one',
      cardinality: 'N:1',
      foreignKey: 'employee_id',
      description: 'Employee conducts appointments',
    },
    {
      from: 'ATM Transaction',
      to: 'ATM',
      type: 'many-to-one',
      cardinality: 'N:1',
      foreignKey: 'atm_id',
      description: 'Transactions processed at ATMs',
    },
  ],
};

// PHYSICAL ERD - Technical Implementation (Bronze Layer Tables)
export const branchRetailPhysicalERD = {
  tables: [
    {
      name: 'bronze.retail_branch_master',
      description: 'Branch master data from branch management system',
      source: 'Branch Management System',
      updateFrequency: 'Daily',
      recordCount: '~3,500 branches',
      attributes: [
        { name: 'branch_id', type: 'BIGINT', isPrimaryKey: true },
        { name: 'branch_code', type: 'VARCHAR(20)' },
        { name: 'branch_name', type: 'VARCHAR(200)' },
        { name: 'branch_type', type: 'VARCHAR(50)' },
        { name: 'branch_status', type: 'VARCHAR(50)' },
        { name: 'address_line1', type: 'VARCHAR(200)' },
        { name: 'address_line2', type: 'VARCHAR(200)' },
        { name: 'city', type: 'VARCHAR(100)' },
        { name: 'state', type: 'VARCHAR(2)' },
        { name: 'postal_code', type: 'VARCHAR(10)' },
        { name: 'latitude', type: 'DECIMAL(10,8)' },
        { name: 'longitude', type: 'DECIMAL(11,8)' },
        { name: 'phone', type: 'VARCHAR(20)' },
        { name: 'branch_manager_id', type: 'BIGINT' },
        { name: 'open_date', type: 'DATE' },
        { name: 'close_date', type: 'DATE' },
        { name: 'square_footage', type: 'INTEGER' },
        { name: 'teller_count', type: 'INTEGER' },
        { name: 'atm_count', type: 'INTEGER' },
        { name: 'drive_through_lanes', type: 'INTEGER' },
        { name: 'safe_deposit_boxes', type: 'INTEGER' },
        { name: 'created_timestamp', type: 'TIMESTAMP' },
        { name: 'updated_timestamp', type: 'TIMESTAMP' },
        { name: 'source_system', type: 'VARCHAR(50)' },
      ],
    },
    {
      name: 'bronze.retail_teller_transactions',
      description: 'Teller transaction data',
      source: 'Teller Platform',
      updateFrequency: 'Real-time',
      recordCount: '~50M transactions/month',
      attributes: [
        { name: 'transaction_id', type: 'BIGINT', isPrimaryKey: true },
        { name: 'branch_id', type: 'BIGINT' },
        { name: 'teller_id', type: 'BIGINT' },
        { name: 'customer_id', type: 'BIGINT' },
        { name: 'transaction_timestamp', type: 'TIMESTAMP' },
        { name: 'transaction_type', type: 'VARCHAR(50)' },
        { name: 'transaction_amount', type: 'DECIMAL(18,2)' },
        { name: 'account_id', type: 'BIGINT' },
        { name: 'transaction_status', type: 'VARCHAR(50)' },
        { name: 'service_time_seconds', type: 'INTEGER' },
        { name: 'wait_time_seconds', type: 'INTEGER' },
        { name: 'transaction_channel', type: 'VARCHAR(50)' },
        { name: 'created_timestamp', type: 'TIMESTAMP' },
        { name: 'source_system', type: 'VARCHAR(50)' },
      ],
    },
    {
      name: 'bronze.retail_branch_traffic',
      description: 'Branch visit and traffic data',
      source: 'Queue Management System',
      updateFrequency: 'Real-time',
      recordCount: '~100M visits/year',
      attributes: [
        { name: 'visit_id', type: 'BIGINT', isPrimaryKey: true },
        { name: 'branch_id', type: 'BIGINT' },
        { name: 'customer_id', type: 'BIGINT' },
        { name: 'visit_date', type: 'DATE' },
        { name: 'visit_timestamp', type: 'TIMESTAMP' },
        { name: 'exit_timestamp', type: 'TIMESTAMP' },
        { name: 'visit_type', type: 'VARCHAR(50)' },
        { name: 'visit_channel', type: 'VARCHAR(50)' },
        { name: 'wait_time_minutes', type: 'INTEGER' },
        { name: 'service_time_minutes', type: 'INTEGER' },
        { name: 'served_by_employee_id', type: 'BIGINT' },
        { name: 'transactions_completed', type: 'INTEGER' },
        { name: 'appointment_flag', type: 'BOOLEAN' },
        { name: 'created_timestamp', type: 'TIMESTAMP' },
        { name: 'source_system', type: 'VARCHAR(50)' },
      ],
    },
    {
      name: 'bronze.retail_branch_employees',
      description: 'Branch employee data',
      source: 'HR System',
      updateFrequency: 'Daily',
      recordCount: '~45,000 employees',
      attributes: [
        { name: 'employee_id', type: 'BIGINT', isPrimaryKey: true },
        { name: 'branch_id', type: 'BIGINT' },
        { name: 'employee_number', type: 'VARCHAR(20)' },
        { name: 'first_name', type: 'VARCHAR(100)' },
        { name: 'last_name', type: 'VARCHAR(100)' },
        { name: 'job_title', type: 'VARCHAR(100)' },
        { name: 'job_level', type: 'VARCHAR(50)' },
        { name: 'hire_date', type: 'DATE' },
        { name: 'termination_date', type: 'DATE' },
        { name: 'employment_status', type: 'VARCHAR(50)' },
        { name: 'full_time_flag', type: 'BOOLEAN' },
        { name: 'teller_drawer_limit', type: 'DECIMAL(18,2)' },
        { name: 'created_timestamp', type: 'TIMESTAMP' },
        { name: 'updated_timestamp', type: 'TIMESTAMP' },
        { name: 'source_system', type: 'VARCHAR(50)' },
      ],
    },
    {
      name: 'bronze.retail_atm_master',
      description: 'ATM master data',
      source: 'ATM Network System',
      updateFrequency: 'Daily',
      recordCount: '~16,000 ATMs',
      attributes: [
        { name: 'atm_id', type: 'BIGINT', isPrimaryKey: true },
        { name: 'atm_number', type: 'VARCHAR(20)' },
        { name: 'branch_id', type: 'BIGINT' },
        { name: 'atm_location_type', type: 'VARCHAR(50)' },
        { name: 'atm_type', type: 'VARCHAR(50)' },
        { name: 'atm_status', type: 'VARCHAR(50)' },
        { name: 'address_line1', type: 'VARCHAR(200)' },
        { name: 'city', type: 'VARCHAR(100)' },
        { name: 'state', type: 'VARCHAR(2)' },
        { name: 'postal_code', type: 'VARCHAR(10)' },
        { name: 'install_date', type: 'DATE' },
        { name: 'last_maintenance_date', type: 'DATE' },
        { name: 'cash_capacity', type: 'DECIMAL(18,2)' },
        { name: 'created_timestamp', type: 'TIMESTAMP' },
        { name: 'updated_timestamp', type: 'TIMESTAMP' },
        { name: 'source_system', type: 'VARCHAR(50)' },
      ],
    },
    {
      name: 'bronze.retail_atm_transactions',
      description: 'ATM transaction data',
      source: 'ATM Network',
      updateFrequency: 'Real-time',
      recordCount: '~200M transactions/month',
      attributes: [
        { name: 'transaction_id', type: 'BIGINT', isPrimaryKey: true },
        { name: 'atm_id', type: 'BIGINT' },
        { name: 'card_id', type: 'BIGINT' },
        { name: 'customer_id', type: 'BIGINT' },
        { name: 'transaction_timestamp', type: 'TIMESTAMP' },
        { name: 'transaction_type', type: 'VARCHAR(50)' },
        { name: 'transaction_amount', type: 'DECIMAL(18,2)' },
        { name: 'transaction_status', type: 'VARCHAR(50)' },
        { name: 'fee_amount', type: 'DECIMAL(18,2)' },
        { name: 'account_id', type: 'BIGINT' },
        { name: 'network', type: 'VARCHAR(50)' },
        { name: 'created_timestamp', type: 'TIMESTAMP' },
        { name: 'source_system', type: 'VARCHAR(50)' },
      ],
    },
    {
      name: 'bronze.retail_branch_appointments',
      description: 'Branch appointment data',
      source: 'Appointment Scheduling System',
      updateFrequency: 'Real-time',
      recordCount: '~5M appointments/year',
      attributes: [
        { name: 'appointment_id', type: 'BIGINT', isPrimaryKey: true },
        { name: 'branch_id', type: 'BIGINT' },
        { name: 'customer_id', type: 'BIGINT' },
        { name: 'employee_id', type: 'BIGINT' },
        { name: 'appointment_date', type: 'DATE' },
        { name: 'appointment_time', type: 'TIME' },
        { name: 'appointment_type', type: 'VARCHAR(100)' },
        { name: 'appointment_status', type: 'VARCHAR(50)' },
        { name: 'duration_minutes', type: 'INTEGER' },
        { name: 'scheduled_timestamp', type: 'TIMESTAMP' },
        { name: 'channel_booked', type: 'VARCHAR(50)' },
        { name: 'created_timestamp', type: 'TIMESTAMP' },
        { name: 'updated_timestamp', type: 'TIMESTAMP' },
        { name: 'source_system', type: 'VARCHAR(50)' },
      ],
    },
    {
      name: 'bronze.retail_branch_daily_snapshot',
      description: 'Daily branch performance aggregates',
      source: 'Calculated',
      updateFrequency: 'Daily',
      recordCount: '~1.3M records/year',
      attributes: [
        { name: 'snapshot_id', type: 'BIGINT', isPrimaryKey: true },
        { name: 'branch_id', type: 'BIGINT' },
        { name: 'snapshot_date', type: 'DATE' },
        { name: 'total_visits', type: 'INTEGER' },
        { name: 'total_transactions', type: 'INTEGER' },
        { name: 'total_transaction_amount', type: 'DECIMAL(18,2)' },
        { name: 'average_wait_time_minutes', type: 'DECIMAL(10,2)' },
        { name: 'average_service_time_minutes', type: 'DECIMAL(10,2)' },
        { name: 'lobby_traffic', type: 'INTEGER' },
        { name: 'drive_through_traffic', type: 'INTEGER' },
        { name: 'atm_traffic', type: 'INTEGER' },
        { name: 'new_accounts_opened', type: 'INTEGER' },
        { name: 'staff_present', type: 'INTEGER' },
        { name: 'created_timestamp', type: 'TIMESTAMP' },
      ],
    },
  ],
  
  relationships: [
    {
      from: 'bronze.retail_teller_transactions',
      to: 'bronze.retail_branch_master',
      type: 'many-to-one',
      cardinality: 'N:1',
      foreignKey: 'branch_id',
      description: 'Transactions belong to branch',
    },
    {
      from: 'bronze.retail_branch_traffic',
      to: 'bronze.retail_branch_master',
      type: 'many-to-one',
      cardinality: 'N:1',
      foreignKey: 'branch_id',
      description: 'Visits belong to branch',
    },
    {
      from: 'bronze.retail_branch_employees',
      to: 'bronze.retail_branch_master',
      type: 'many-to-one',
      cardinality: 'N:1',
      foreignKey: 'branch_id',
      description: 'Employees work at branch',
    },
    {
      from: 'bronze.retail_atm_master',
      to: 'bronze.retail_branch_master',
      type: 'many-to-one',
      cardinality: 'N:1',
      foreignKey: 'branch_id',
      description: 'ATMs located at branch',
    },
    {
      from: 'bronze.retail_branch_appointments',
      to: 'bronze.retail_branch_master',
      type: 'many-to-one',
      cardinality: 'N:1',
      foreignKey: 'branch_id',
      description: 'Appointments at branch',
    },
    {
      from: 'bronze.retail_atm_transactions',
      to: 'bronze.retail_atm_master',
      type: 'many-to-one',
      cardinality: 'N:1',
      foreignKey: 'atm_id',
      description: 'Transactions at ATM',
    },
  ],
};

// Export default for easy import
export default {
  branchRetailLogicalERD,
  branchRetailPhysicalERD,
};
