/**
 * BRANCH-RETAIL METRICS CATALOG
 * 100 comprehensive metrics across 5 categories
 */

export const branchRetailMetricsCatalog = {
  description: 'Comprehensive retail branch metrics catalog',
  totalMetrics: 100,
  
  categories: [
    // Category 1: Traffic & Footfall Metrics (20 metrics)
    {
      name: 'Traffic & Footfall Metrics',
      description: 'Branch visits, foot traffic, and customer flow patterns',
      totalMetrics: 20,
      
      metrics: [
        {
          id: 'BRANCH-TRAF-001',
          name: 'Total Customer Visits',
          description: 'Number of customer visits to branches',
          category: 'Traffic',
          type: 'operational',
          subcategory: 'Volume',
          formula: "COUNT(DISTINCT visit_id)",
          businessLogic: 'Count of unique customer visits to branch locations',
          dataType: 'INTEGER',
          unit: 'count',
          aggregation: 'SUM',
          granularity: 'Daily',
          sourceTables: ['gold.fact_retail_branch_daily_snapshot'],
          benchmarks: {
            industryAverage: '100K visits/month',
            topQuartile: '200K visits/month',
            target: '150K visits/month',
          },
        },
        {
          id: 'BRANCH-TRAF-002',
          name: 'Lobby vs Drive-Through Traffic Mix',
          description: 'Percentage split of lobby vs drive-through traffic',
          category: 'Traffic',
          type: 'operational',
          subcategory: 'Mix',
        },
        {
          id: 'BRANCH-TRAF-003',
          name: 'Peak Hour Traffic Volume',
          description: 'Customer visits during peak hours (11am-2pm)',
          category: 'Traffic',
          type: 'operational',
          subcategory: 'Patterns',
        },
        {
          id: 'BRANCH-TRAF-004',
          name: 'Weekend Traffic Rate',
          description: 'Percentage of weekly traffic occurring on weekends',
          category: 'Traffic',
          type: 'operational',
          subcategory: 'Patterns',
        },
        {
          id: 'BRANCH-TRAF-005',
          name: 'Walk-In Customer Rate',
          description: 'Percentage of visitors without appointments',
          category: 'Traffic',
          type: 'operational',
          subcategory: 'Appointment',
        },
        {
          id: 'BRANCH-TRAF-006',
          name: 'Appointment-Based Visit Rate',
          description: 'Percentage of visits scheduled in advance',
          category: 'Traffic',
          type: 'operational',
          subcategory: 'Appointment',
        },
        {
          id: 'BRANCH-TRAF-007',
          name: 'Average Daily Foot Traffic per Branch',
          description: 'Mean daily customer visits per branch location',
          category: 'Traffic',
          type: 'operational',
          subcategory: 'Productivity',
        },
        {
          id: 'BRANCH-TRAF-008',
          name: 'Year-over-Year Traffic Change',
          description: 'Percentage change in branch traffic vs prior year',
          category: 'Traffic',
          type: 'operational',
          subcategory: 'Growth',
        },
        {
          id: 'BRANCH-TRAF-009',
          name: 'Traffic by Branch Size Tier',
          description: 'Visits segmented by branch size (small/medium/large)',
          category: 'Traffic',
          type: 'operational',
          subcategory: 'Segmentation',
        },
        {
          id: 'BRANCH-TRAF-010',
          name: 'Traffic by Geographic Region',
          description: 'Visits distribution across geographic markets',
          category: 'Traffic',
          type: 'operational',
          subcategory: 'Geography',
        },
        {
          id: 'BRANCH-TRAF-011',
          name: 'First-Time Visitor Rate',
          description: 'Percentage of visitors on their first branch visit',
          category: 'Traffic',
          type: 'operational',
          subcategory: 'New Customers',
        },
        {
          id: 'BRANCH-TRAF-012',
          name: 'Repeat Visitor Rate',
          description: 'Percentage of customers visiting multiple times per month',
          category: 'Traffic',
          type: 'operational',
          subcategory: 'Loyalty',
        },
        {
          id: 'BRANCH-TRAF-013',
          name: 'Urban vs Suburban Traffic Mix',
          description: 'Traffic distribution by branch location type',
          category: 'Traffic',
          type: 'operational',
          subcategory: 'Location',
        },
        {
          id: 'BRANCH-TRAF-014',
          name: 'Morning vs Afternoon Traffic Split',
          description: 'Traffic distribution by time of day',
          category: 'Traffic',
          type: 'operational',
          subcategory: 'Patterns',
        },
        {
          id: 'BRANCH-TRAF-015',
          name: 'Monthly Traffic Trend',
          description: 'Month-over-month traffic growth rate',
          category: 'Traffic',
          type: 'operational',
          subcategory: 'Trends',
        },
        {
          id: 'BRANCH-TRAF-016',
          name: 'Traffic per Square Foot',
          description: 'Customer visits per square foot of branch space',
          category: 'Traffic',
          type: 'operational',
          subcategory: 'Efficiency',
        },
        {
          id: 'BRANCH-TRAF-017',
          name: 'Queue Length at Peak',
          description: 'Average number of customers waiting during peak hours',
          category: 'Traffic',
          type: 'operational',
          subcategory: 'Queue',
        },
        {
          id: 'BRANCH-TRAF-018',
          name: 'Traffic Conversion Rate',
          description: 'Percentage of visitors completing transactions',
          category: 'Traffic',
          type: 'operational',
          subcategory: 'Conversion',
        },
        {
          id: 'BRANCH-TRAF-019',
          name: 'Cross-Branch Visit Rate',
          description: 'Percentage of customers visiting multiple branch locations',
          category: 'Traffic',
          type: 'operational',
          subcategory: 'Behavior',
        },
        {
          id: 'BRANCH-TRAF-020',
          name: 'Seasonal Traffic Variation',
          description: 'Traffic fluctuation across seasons',
          category: 'Traffic',
          type: 'operational',
          subcategory: 'Seasonality',
        },
      ],
    },

    // Category 2: Transaction Metrics (20 metrics)
    {
      name: 'Transaction Metrics',
      description: 'Teller transactions, transaction types, and processing metrics',
      totalMetrics: 20,
      
      metrics: [
        {
          id: 'BRANCH-TXN-001',
          name: 'Total Teller Transactions',
          description: 'Number of teller transactions processed',
          category: 'Transaction',
          type: 'operational',
          subcategory: 'Volume',
          formula: "COUNT(teller_transaction_id)",
          dataType: 'INTEGER',
          unit: 'count',
          aggregation: 'SUM',
          granularity: 'Daily',
          benchmarks: {
            industryAverage: '50M transactions/month',
            topQuartile: '75M transactions/month',
            target: '60M transactions/month',
          },
        },
        {
          id: 'BRANCH-TXN-002',
          name: 'Average Transaction Value',
          description: 'Mean dollar value of branch transactions',
          category: 'Transaction',
          type: 'operational',
          subcategory: 'Value',
        },
        {
          id: 'BRANCH-TXN-003',
          name: 'Cash Withdrawal Transaction Rate',
          description: 'Percentage of transactions that are cash withdrawals',
          category: 'Transaction',
          type: 'operational',
          subcategory: 'Type',
        },
        {
          id: 'BRANCH-TXN-004',
          name: 'Cash Deposit Transaction Rate',
          description: 'Percentage of transactions that are cash deposits',
          category: 'Transaction',
          type: 'operational',
          subcategory: 'Type',
        },
        {
          id: 'BRANCH-TXN-005',
          name: 'Check Deposit Transaction Rate',
          description: 'Percentage of transactions that are check deposits',
          category: 'Transaction',
          type: 'operational',
          subcategory: 'Type',
        },
        {
          id: 'BRANCH-TXN-006',
          name: 'Account Opening Transaction Rate',
          description: 'Percentage of visits resulting in new account opening',
          category: 'Transaction',
          type: 'operational',
          subcategory: 'Sales',
        },
        {
          id: 'BRANCH-TXN-007',
          name: 'Loan Application Transaction Rate',
          description: 'Percentage of visits involving loan applications',
          category: 'Transaction',
          type: 'operational',
          subcategory: 'Sales',
        },
        {
          id: 'BRANCH-TXN-008',
          name: 'Service Request Transaction Rate',
          description: 'Percentage of visits for service requests (address change, etc.)',
          category: 'Transaction',
          type: 'operational',
          subcategory: 'Service',
        },
        {
          id: 'BRANCH-TXN-009',
          name: 'Average Transactions per Visit',
          description: 'Mean number of transactions completed per customer visit',
          category: 'Transaction',
          type: 'operational',
          subcategory: 'Productivity',
        },
        {
          id: 'BRANCH-TXN-010',
          name: 'Transaction Processing Time',
          description: 'Average time to complete a transaction',
          category: 'Transaction',
          type: 'operational',
          subcategory: 'Efficiency',
        },
        {
          id: 'BRANCH-TXN-011',
          name: 'Complex Transaction Rate',
          description: 'Percentage of transactions requiring manager approval',
          category: 'Transaction',
          type: 'operational',
          subcategory: 'Complexity',
        },
        {
          id: 'BRANCH-TXN-012',
          name: 'Cross-Sell Transaction Rate',
          description: 'Percentage of visits where additional products were sold',
          category: 'Transaction',
          type: 'operational',
          subcategory: 'Sales',
        },
        {
          id: 'BRANCH-TXN-013',
          name: 'Foreign Currency Exchange Volume',
          description: 'Number of foreign exchange transactions',
          category: 'Transaction',
          type: 'operational',
          subcategory: 'Specialty',
        },
        {
          id: 'BRANCH-TXN-014',
          name: 'Cashier Check Issuance Rate',
          description: 'Number of cashier checks issued',
          category: 'Transaction',
          type: 'operational',
          subcategory: 'Specialty',
        },
        {
          id: 'BRANCH-TXN-015',
          name: 'Money Order Issuance Rate',
          description: 'Number of money orders issued',
          category: 'Transaction',
          type: 'operational',
          subcategory: 'Specialty',
        },
        {
          id: 'BRANCH-TXN-016',
          name: 'Safe Deposit Box Activity Rate',
          description: 'Number of safe deposit box accesses',
          category: 'Transaction',
          type: 'operational',
          subcategory: 'Specialty',
        },
        {
          id: 'BRANCH-TXN-017',
          name: 'Transaction Error Rate',
          description: 'Percentage of transactions requiring correction',
          category: 'Transaction',
          type: 'operational',
          subcategory: 'Quality',
        },
        {
          id: 'BRANCH-TXN-018',
          name: 'Transaction Reversal Rate',
          description: 'Percentage of transactions reversed or voided',
          category: 'Transaction',
          type: 'operational',
          subcategory: 'Quality',
        },
        {
          id: 'BRANCH-TXN-019',
          name: 'Large Cash Transaction Volume',
          description: 'Number of transactions over $10,000 (CTR threshold)',
          category: 'Transaction',
          type: 'operational',
          subcategory: 'Compliance',
        },
        {
          id: 'BRANCH-TXN-020',
          name: 'Average Transaction Queue Time',
          description: 'Mean wait time before transaction processing begins',
          category: 'Transaction',
          type: 'operational',
          subcategory: 'Service',
        },
      ],
    },

    // Category 3: Service Quality Metrics (20 metrics)
    {
      name: 'Service Quality Metrics',
      description: 'Wait times, service levels, and customer experience',
      totalMetrics: 20,
      
      metrics: [
        {
          id: 'BRANCH-SVC-001',
          name: 'Average Wait Time',
          description: 'Mean customer wait time from entry to service',
          category: 'Service',
          type: 'diagnostic',
          subcategory: 'Wait Time',
          formula: "AVG(DATEDIFF(second, queue_start, service_start))",
          dataType: 'DECIMAL',
          unit: 'minutes',
          aggregation: 'AVG',
          granularity: 'Hourly',
          benchmarks: {
            industryAverage: '5.5 minutes',
            topQuartile: '3.0 minutes',
            target: '4.0 minutes',
          },
        },
        {
          id: 'BRANCH-SVC-002',
          name: 'Service Level Achievement (% under 5 min)',
          description: 'Percentage of customers served within 5 minutes',
          category: 'Service',
          type: 'diagnostic',
          subcategory: 'Service Level',
        },
        {
          id: 'BRANCH-SVC-003',
          name: 'Peak Hour Wait Time',
          description: 'Average wait time during busiest hours',
          category: 'Service',
          type: 'diagnostic',
          subcategory: 'Wait Time',
        },
        {
          id: 'BRANCH-SVC-004',
          name: 'Customer Abandonment Rate',
          description: 'Percentage of customers leaving queue before service',
          category: 'Service',
          type: 'diagnostic',
          subcategory: 'Abandonment',
        },
        {
          id: 'BRANCH-SVC-005',
          name: 'Teller Utilization Rate',
          description: 'Percentage of time tellers are actively serving customers',
          category: 'Service',
          type: 'diagnostic',
          subcategory: 'Productivity',
        },
        {
          id: 'BRANCH-SVC-006',
          name: 'Service Resolution Rate',
          description: 'Percentage of issues resolved on first visit',
          category: 'Service',
          type: 'diagnostic',
          subcategory: 'Resolution',
        },
        {
          id: 'BRANCH-SVC-007',
          name: 'Branch Service Satisfaction Score',
          description: 'Average customer satisfaction rating for branch service',
          category: 'Service',
          type: 'diagnostic',
          subcategory: 'Satisfaction',
        },
        {
          id: 'BRANCH-SVC-008',
          name: 'Branch Net Promoter Score',
          description: 'NPS specific to branch experience',
          category: 'Service',
          type: 'diagnostic',
          subcategory: 'Advocacy',
        },
        {
          id: 'BRANCH-SVC-009',
          name: 'Complaint Rate per 1000 Visits',
          description: 'Number of complaints per thousand branch visits',
          category: 'Service',
          type: 'behavioral',
          subcategory: 'Quality',
        },
        {
          id: 'BRANCH-SVC-010',
          name: 'Greeter Deployment Rate',
          description: 'Percentage of branches with active greeters',
          category: 'Service',
          type: 'diagnostic',
          subcategory: 'Staffing',
        },
        {
          id: 'BRANCH-SVC-011',
          name: 'Personal Banker Availability Rate',
          description: 'Percentage of time personal bankers available for consultation',
          category: 'Service',
          type: 'diagnostic',
          subcategory: 'Availability',
        },
        {
          id: 'BRANCH-SVC-012',
          name: 'Appointment Kept Rate',
          description: 'Percentage of scheduled appointments that customers attend',
          category: 'Service',
          type: 'diagnostic',
          subcategory: 'Appointment',
        },
        {
          id: 'BRANCH-SVC-013',
          name: 'Appointment No-Show Rate',
          description: 'Percentage of appointments where customer doesn\'t arrive',
          category: 'Service',
          subcategory: 'Appointment',
        },
        {
          id: 'BRANCH-SVC-014',
          name: 'Service Recovery Success Rate',
          description: 'Percentage of service failures successfully recovered',
          category: 'Service',
          type: 'diagnostic',
          subcategory: 'Recovery',
        },
        {
          id: 'BRANCH-SVC-015',
          name: 'Digital Service Adoption at Branch',
          description: 'Percentage of customers using in-branch digital tools',
          category: 'Service',
          type: 'behavioral',
          subcategory: 'Digital',
        },
        {
          id: 'BRANCH-SVC-016',
          name: 'Video Banking Usage Rate',
          description: 'Percentage of branches with active video banking usage',
          category: 'Service',
          type: 'behavioral',
          subcategory: 'Digital',
        },
        {
          id: 'BRANCH-SVC-017',
          name: 'Multilingual Service Availability',
          description: 'Percentage of branches offering multilingual service',
          category: 'Service',
          type: 'diagnostic',
          subcategory: 'Accessibility',
        },
        {
          id: 'BRANCH-SVC-018',
          name: 'Extended Hours Utilization',
          description: 'Customer visits during extended hours as percentage of total',
          category: 'Service',
          type: 'diagnostic',
          subcategory: 'Hours',
        },
        {
          id: 'BRANCH-SVC-019',
          name: 'Branch Cleanliness Score',
          description: 'Customer rating of branch cleanliness and appearance',
          category: 'Service',
          type: 'diagnostic',
          subcategory: 'Facilities',
        },
        {
          id: 'BRANCH-SVC-020',
          name: 'Technology Uptime Rate',
          description: 'Percentage of time branch systems are operational',
          category: 'Service',
          type: 'diagnostic',
          subcategory: 'Technology',
        },
      ],
    },

    // Category 4: Staff Performance Metrics (20 metrics)
    {
      name: 'Staff Performance Metrics',
      description: 'Teller productivity, staffing levels, and employee metrics',
      totalMetrics: 20,
      
      metrics: [
        {
          id: 'BRANCH-STAFF-001',
          name: 'Average Transactions per Teller per Day',
          description: 'Mean number of transactions handled by each teller daily',
          category: 'Staff',
          type: 'operational',
          subcategory: 'Productivity',
          formula: "SUM(transaction_count) / COUNT(DISTINCT teller_id) / COUNT(DISTINCT business_days)",
          dataType: 'DECIMAL',
          unit: 'count',
          aggregation: 'AVG',
          granularity: 'Daily',
          benchmarks: {
            industryAverage: '85 transactions/day',
            topQuartile: '110 transactions/day',
            target: '95 transactions/day',
          },
        },
        {
          id: 'BRANCH-STAFF-002',
          name: 'Teller Accuracy Rate',
          description: 'Percentage of transactions with no errors',
          category: 'Staff',
          type: 'diagnostic',
          subcategory: 'Quality',
        },
        {
          id: 'BRANCH-STAFF-003',
          name: 'Cross-Sell Success Rate per Banker',
          description: 'Average products sold per personal banker',
          category: 'Staff',
          type: 'diagnostic',
          subcategory: 'Sales',
        },
        {
          id: 'BRANCH-STAFF-004',
          name: 'Staff Utilization Rate',
          description: 'Percentage of staff time spent on customer-facing activities',
          category: 'Staff',
          type: 'diagnostic',
          subcategory: 'Utilization',
        },
        {
          id: 'BRANCH-STAFF-005',
          name: 'Employee Turnover Rate',
          description: 'Annual staff turnover percentage',
          category: 'Staff',
          type: 'diagnostic',
          subcategory: 'Retention',
        },
        {
          id: 'BRANCH-STAFF-006',
          name: 'Training Completion Rate',
          description: 'Percentage of required training completed by staff',
          category: 'Staff',
          type: 'diagnostic',
          subcategory: 'Development',
        },
        {
          id: 'BRANCH-STAFF-007',
          name: 'Average Tenure of Branch Staff',
          description: 'Mean years of service for branch employees',
          category: 'Staff',
          type: 'diagnostic',
          subcategory: 'Retention',
        },
        {
          id: 'BRANCH-STAFF-008',
          name: 'Manager to Staff Ratio',
          description: 'Number of staff members per branch manager',
          category: 'Staff',
          type: 'diagnostic',
          subcategory: 'Structure',
        },
        {
          id: 'BRANCH-STAFF-009',
          name: 'Overtime Hours per Employee',
          description: 'Average overtime hours per staff member',
          category: 'Staff',
          type: 'diagnostic',
          subcategory: 'Workload',
        },
        {
          id: 'BRANCH-STAFF-010',
          name: 'Staff Satisfaction Score',
          description: 'Employee satisfaction survey score',
          category: 'Staff',
          type: 'diagnostic',
          subcategory: 'Engagement',
        },
        {
          id: 'BRANCH-STAFF-011',
          name: 'Teller Certification Rate',
          description: 'Percentage of tellers with advanced certifications',
          category: 'Staff',
          type: 'diagnostic',
          subcategory: 'Qualifications',
        },
        {
          id: 'BRANCH-STAFF-012',
          name: 'Bilingual Staff Percentage',
          description: 'Percentage of staff fluent in multiple languages',
          category: 'Staff',
          type: 'diagnostic',
          subcategory: 'Capabilities',
        },
        {
          id: 'BRANCH-STAFF-013',
          name: 'Average Customer Service Time',
          description: 'Mean time spent per customer interaction',
          category: 'Staff',
          type: 'diagnostic',
          subcategory: 'Efficiency',
        },
        {
          id: 'BRANCH-STAFF-014',
          name: 'Staff Scheduling Efficiency',
          description: 'Alignment of staff schedules with customer traffic patterns',
          category: 'Staff',
          type: 'diagnostic',
          subcategory: 'Planning',
        },
        {
          id: 'BRANCH-STAFF-015',
          name: 'Employee Referral Rate',
          description: 'Percentage of new hires from employee referrals',
          category: 'Staff',
          type: 'diagnostic',
          subcategory: 'Recruitment',
        },
        {
          id: 'BRANCH-STAFF-016',
          name: 'Average Time to Fill Open Position',
          description: 'Mean days to hire for vacant positions',
          category: 'Staff',
          type: 'diagnostic',
          subcategory: 'Recruitment',
        },
        {
          id: 'BRANCH-STAFF-017',
          name: 'Staff Compliance Training Rate',
          description: 'Percentage of staff current on compliance training',
          category: 'Staff',
          type: 'diagnostic',
          subcategory: 'Compliance',
        },
        {
          id: 'BRANCH-STAFF-018',
          name: 'Sales Target Achievement Rate',
          description: 'Percentage of staff meeting monthly sales goals',
          category: 'Staff',
          type: 'diagnostic',
          subcategory: 'Performance',
        },
        {
          id: 'BRANCH-STAFF-019',
          name: 'Customer Escalation Rate',
          description: 'Percentage of interactions requiring manager escalation',
          category: 'Staff',
          type: 'diagnostic',
          subcategory: 'Quality',
        },
        {
          id: 'BRANCH-STAFF-020',
          name: 'Staff Recognition Program Participation',
          description: 'Percentage of eligible staff recognized monthly',
          category: 'Staff',
          type: 'diagnostic',
          subcategory: 'Engagement',
        },
      ],
    },

    // Category 5: Operational & Financial Metrics (20 metrics)
    {
      name: 'Operational & Financial Metrics',
      description: 'Branch profitability, costs, and operational efficiency',
      totalMetrics: 20,
      
      metrics: [
        {
          id: 'BRANCH-OPS-001',
          name: 'Branch Profitability',
          description: 'Net profit generated by branch location',
          category: 'Operations',
          type: 'financial',
          subcategory: 'Profitability',
          formula: "SUM(revenue) - SUM(operating_costs)",
          dataType: 'DECIMAL',
          unit: 'USD',
          aggregation: 'SUM',
          granularity: 'Monthly',
          benchmarks: {
            industryAverage: '$150K/month',
            topQuartile: '$300K/month',
            target: '$225K/month',
          },
        },
        {
          id: 'BRANCH-OPS-002',
          name: 'Cost per Transaction',
          description: 'Average cost to process each transaction',
          category: 'Operations',
          type: 'financial',
          subcategory: 'Efficiency',
        },
        {
          id: 'BRANCH-OPS-003',
          name: 'Cost per Customer Visit',
          description: 'Average cost per customer interaction',
          category: 'Operations',
          type: 'financial',
          subcategory: 'Efficiency',
        },
        {
          id: 'BRANCH-OPS-004',
          name: 'Branch Operating Expense Ratio',
          description: 'Operating expenses as percentage of revenue',
          category: 'Operations',
          type: 'diagnostic',
          subcategory: 'Efficiency',
        },
        {
          id: 'BRANCH-OPS-005',
          name: 'Rent per Square Foot',
          description: 'Annual rent cost per square foot of branch space',
          category: 'Operations',
          type: 'diagnostic',
          subcategory: 'Real Estate',
        },
        {
          id: 'BRANCH-OPS-006',
          name: 'Utility Cost per Branch',
          description: 'Average monthly utility expenses per location',
          category: 'Operations',
          type: 'financial',
          subcategory: 'Facilities',
        },
        {
          id: 'BRANCH-OPS-007',
          name: 'Security System Uptime',
          description: 'Percentage of time security systems operational',
          category: 'Operations',
          type: 'diagnostic',
          subcategory: 'Security',
        },
        {
          id: 'BRANCH-OPS-008',
          name: 'ATM Uptime Rate',
          description: 'Percentage of time in-branch ATMs are operational',
          category: 'Operations',
          type: 'diagnostic',
          subcategory: 'Technology',
        },
        {
          id: 'BRANCH-OPS-009',
          name: 'Cash Management Efficiency',
          description: 'Optimal cash levels vs actual cash on hand',
          category: 'Operations',
          type: 'diagnostic',
          subcategory: 'Cash',
        },
        {
          id: 'BRANCH-OPS-010',
          name: 'Vault Cash Utilization',
          description: 'Percentage of vault cash actively used',
          category: 'Operations',
          type: 'diagnostic',
          subcategory: 'Cash',
        },
        {
          id: 'BRANCH-OPS-011',
          name: 'Branch Lease Renewal Rate',
          description: 'Percentage of expiring leases renewed',
          category: 'Operations',
          type: 'diagnostic',
          subcategory: 'Real Estate',
        },
        {
          id: 'BRANCH-OPS-012',
          name: 'Revenue per Square Foot',
          description: 'Annual revenue generated per square foot',
          category: 'Operations',
          type: 'financial',
          subcategory: 'Productivity',
        },
        {
          id: 'BRANCH-OPS-013',
          name: 'Deposits Captured per Branch',
          description: 'Total deposit balances per branch location',
          category: 'Operations',
          type: 'diagnostic',
          subcategory: 'Deposits',
        },
        {
          id: 'BRANCH-OPS-014',
          name: 'Loans Originated per Branch',
          description: 'Number of loans originated per branch',
          category: 'Operations',
          type: 'diagnostic',
          subcategory: 'Lending',
        },
        {
          id: 'BRANCH-OPS-015',
          name: 'New Accounts Opened per Branch',
          description: 'Number of new accounts opened per location',
          category: 'Operations',
          type: 'operational',
          subcategory: 'Sales',
        },
        {
          id: 'BRANCH-OPS-016',
          name: 'Maintenance Cost per Branch',
          description: 'Average monthly maintenance expenses',
          category: 'Operations',
          type: 'financial',
          subcategory: 'Facilities',
        },
        {
          id: 'BRANCH-OPS-017',
          name: 'Technology Investment per Branch',
          description: 'Annual technology spending per location',
          category: 'Operations',
          type: 'diagnostic',
          subcategory: 'Technology',
        },
        {
          id: 'BRANCH-OPS-018',
          name: 'Branch Closure Rate',
          description: 'Percentage of branches closed annually',
          category: 'Operations',
          type: 'diagnostic',
          subcategory: 'Network',
        },
        {
          id: 'BRANCH-OPS-019',
          name: 'Branch Remodel ROI',
          description: 'Return on investment for branch renovations',
          category: 'Operations',
          type: 'financial',
          subcategory: 'Facilities',
        },
        {
          id: 'BRANCH-OPS-020',
          name: 'Average Branch Age',
          description: 'Mean years since branch opened or last remodeled',
          category: 'Operations',
          type: 'diagnostic',
          subcategory: 'Facilities',
        },
      ],
    },
  ],
};

export default branchRetailMetricsCatalog;
