/**
 * CARDS-RETAIL METRICS CATALOG
 * 100 comprehensive metrics across 5 categories
 */

export const cardsRetailMetricsCatalog = {
  description: 'Comprehensive retail cards metrics catalog',
  totalMetrics: 100,
  
  categories: [
    // Category 1: Portfolio & Account Metrics (20 metrics)
    {
      name: 'Portfolio & Account Metrics',
      description: 'Card portfolio health, size, and composition',
      totalMetrics: 20,
      
      metrics: [
        {
          id: 'CARD-PORT-001',
          name: 'Total Active Card Accounts',
          description: 'Number of active credit and debit card accounts',
          category: 'Portfolio',
          type: 'operational',
          subcategory: 'Volume',
          formula: "COUNT(DISTINCT card_account_id WHERE account_status = 'Active')",
          businessLogic: 'Count of all active card accounts (credit, debit, prepaid)',
          dataType: 'INTEGER',
          unit: 'count',
          aggregation: 'COUNT',
          granularity: 'Daily',
          sourceTables: ['gold.dim_retail_card_account'],
          benchmarks: {
            industryAverage: '5M accounts',
            topQuartile: '10M accounts',
            target: '7.5M accounts',
          },
        },
        {
          id: 'CARD-PORT-002',
          name: 'Total Outstanding Balances',
          description: 'Total credit card balances across all accounts',
          category: 'Portfolio',
          type: 'operational',
          subcategory: 'Balance',
          formula: "SUM(current_balance WHERE card_type = 'Credit')",
          businessLogic: 'Sum of all outstanding credit card balances',
          dataType: 'DECIMAL',
          unit: 'USD',
          aggregation: 'SUM',
          granularity: 'Daily',
          benchmarks: {
            industryAverage: '$15B',
            topQuartile: '$25B',
            target: '$18B',
          },
        },
        {
          id: 'CARD-PORT-003',
          name: 'Total Credit Limits Extended',
          description: 'Total credit line capacity across all credit card accounts',
          category: 'Portfolio',
          type: 'operational',
          subcategory: 'Capacity',
        },
        {
          id: 'CARD-PORT-004',
          name: 'Portfolio Utilization Rate',
          description: 'Percentage of total credit limit being used',
          category: 'Portfolio',
          type: 'operational',
          subcategory: 'Utilization',
        },
        {
          id: 'CARD-PORT-005',
          name: 'Average Balance Per Account',
          description: 'Mean balance across all credit card accounts',
          category: 'Portfolio',
          type: 'operational',
          subcategory: 'Average',
        },
        {
          id: 'CARD-PORT-006',
          name: 'Average Credit Limit Per Account',
          description: 'Mean credit limit per account',
          category: 'Portfolio',
          type: 'operational',
          subcategory: 'Average',
        },
        {
          id: 'CARD-PORT-007',
          name: 'Credit Card vs Debit Card Mix',
          description: 'Percentage split of credit vs debit cards',
          category: 'Portfolio',
          type: 'operational',
          subcategory: 'Mix',
        },
        {
          id: 'CARD-PORT-008',
          name: 'Secured Card Portfolio Size',
          description: 'Number and balances of secured credit cards',
          category: 'Portfolio',
          type: 'operational',
          subcategory: 'Product Type',
        },
        {
          id: 'CARD-PORT-009',
          name: 'Premium Card Penetration',
          description: 'Percentage of accounts that are premium/rewards cards',
          category: 'Portfolio',
          type: 'operational',
          subcategory: 'Premium',
        },
        {
          id: 'CARD-PORT-010',
          name: 'Business Card vs Consumer Card Mix',
          description: 'Percentage of business vs consumer cards',
          category: 'Portfolio',
          type: 'operational',
          subcategory: 'Mix',
        },
        {
          id: 'CARD-PORT-011',
          name: 'Portfolio Growth Rate',
          description: 'Year-over-year account growth',
          category: 'Portfolio',
          type: 'operational',
          subcategory: 'Growth',
        },
        {
          id: 'CARD-PORT-012',
          name: 'Balance Growth Rate',
          description: 'Year-over-year balance growth',
          category: 'Portfolio',
          type: 'operational',
          subcategory: 'Growth',
        },
        {
          id: 'CARD-PORT-013',
          name: 'Revolving Balance Rate',
          description: 'Percentage of accounts carrying a balance',
          category: 'Portfolio',
          type: 'operational',
          subcategory: 'Revolver Mix',
        },
        {
          id: 'CARD-PORT-014',
          name: 'Transactor Rate',
          description: 'Percentage of accounts paying in full each month',
          category: 'Portfolio',
          type: 'operational',
          subcategory: 'Transactor Mix',
        },
        {
          id: 'CARD-PORT-015',
          name: 'Account Age Distribution',
          description: 'Distribution of accounts by tenure',
          category: 'Portfolio',
          type: 'operational',
          subcategory: 'Age',
        },
        {
          id: 'CARD-PORT-016',
          name: 'Co-Brand Card Penetration',
          description: 'Percentage of accounts that are co-branded',
          category: 'Portfolio',
          type: 'operational',
          subcategory: 'Co-Brand',
        },
        {
          id: 'CARD-PORT-017',
          name: 'Private Label Card Penetration',
          description: 'Percentage of accounts that are store cards',
          category: 'Portfolio',
          type: 'operational',
          subcategory: 'Private Label',
        },
        {
          id: 'CARD-PORT-018',
          name: 'Balance Transfer Balance',
          description: 'Total balances from balance transfers',
          category: 'Portfolio',
          type: 'operational',
          subcategory: 'Balance Type',
        },
        {
          id: 'CARD-PORT-019',
          name: 'Cash Advance Balance',
          description: 'Total balances from cash advances',
          category: 'Portfolio',
          type: 'operational',
          subcategory: 'Balance Type',
        },
        {
          id: 'CARD-PORT-020',
          name: 'Purchase Balance',
          description: 'Total balances from purchases',
          category: 'Portfolio',
          type: 'operational',
          subcategory: 'Balance Type',
        },
      ],
    },

    // Category 2: Account Lifecycle & Acquisition (20 metrics)
    {
      name: 'Account Lifecycle & Acquisition',
      description: 'New accounts, activations, closures, and attrition',
      totalMetrics: 20,
      
      metrics: [
        {
          id: 'CARD-ACCT-001',
          name: 'New Account Originations',
          description: 'Number of new card accounts opened in period',
          category: 'Account',
          type: 'diagnostic',
          subcategory: 'Acquisition',
          formula: "COUNT(DISTINCT card_account_id WHERE account_open_date BETWEEN period_start AND period_end)",
          dataType: 'INTEGER',
          unit: 'count',
          aggregation: 'SUM',
          granularity: 'Daily',
          benchmarks: {
            industryAverage: '100,000/month',
            topQuartile: '150,000/month',
            target: '125,000/month',
          },
        },
        {
          id: 'CARD-ACCT-002',
          name: 'Account Closure Rate',
          description: 'Percentage of accounts closed during period',
          category: 'Account',
          type: 'diagnostic',
          subcategory: 'Attrition',
        },
        {
          id: 'CARD-ACCT-003',
          name: 'Account Activation Rate',
          description: 'Percentage of new cards activated within 30 days',
          category: 'Account',
          type: 'diagnostic',
          subcategory: 'Activation',
        },
        {
          id: 'CARD-ACCT-004',
          name: 'Average Days to First Transaction',
          description: 'Mean days from activation to first purchase',
          category: 'Account',
          type: 'diagnostic',
          subcategory: 'Activation',
        },
        {
          id: 'CARD-ACCT-005',
          name: 'Dormant Account Rate',
          description: 'Percentage of accounts with no activity in 90+ days',
          category: 'Account',
          type: 'diagnostic',
          subcategory: 'Dormancy',
        },
        {
          id: 'CARD-ACCT-006',
          name: 'Reactivation Rate',
          description: 'Percentage of dormant accounts becoming active again',
          category: 'Account',
          type: 'diagnostic',
          subcategory: 'Reactivation',
        },
        {
          id: 'CARD-ACCT-007',
          name: 'Account Tenure Distribution',
          description: 'Distribution of accounts by age',
          category: 'Account',
          type: 'diagnostic',
          subcategory: 'Tenure',
        },
        {
          id: 'CARD-ACCT-008',
          name: 'Authorized User Adoption Rate',
          description: 'Percentage of accounts with authorized users',
          category: 'Account',
          type: 'behavioral',
          subcategory: 'Users',
        },
        {
          id: 'CARD-ACCT-009',
          name: 'AutoPay Enrollment Rate',
          description: 'Percentage of accounts enrolled in autopay',
          category: 'Account',
          type: 'diagnostic',
          subcategory: 'Payments',
        },
        {
          id: 'CARD-ACCT-010',
          name: 'Account Opening Cost',
          description: 'Average cost to acquire new account',
          category: 'Account',
          type: 'financial',
          subcategory: 'Acquisition Cost',
        },
        {
          id: 'CARD-ACCT-011',
          name: 'Digital Application Rate',
          description: 'Percentage of applications via digital channels',
          category: 'Account',
          type: 'diagnostic',
          subcategory: 'Channel',
        },
        {
          id: 'CARD-ACCT-012',
          name: 'Pre-Approved Offer Conversion',
          description: 'Percentage of pre-approved offers accepted',
          category: 'Account',
          type: 'diagnostic',
          subcategory: 'Marketing',
        },
        {
          id: 'CARD-ACCT-013',
          name: 'Card Replacement Rate',
          description: 'Frequency of card replacements due to loss/theft',
          category: 'Account',
          type: 'diagnostic',
          subcategory: 'Replacement',
        },
        {
          id: 'CARD-ACCT-014',
          name: 'Voluntary vs Involuntary Closure Mix',
          description: 'Percentage of closures by type',
          category: 'Account',
          type: 'diagnostic',
          subcategory: 'Closure Reason',
        },
        {
          id: 'CARD-ACCT-015',
          name: 'Account Upgrade Rate',
          description: 'Percentage of accounts upgraded to premium products',
          category: 'Account',
          type: 'diagnostic',
          subcategory: 'Product Migration',
        },
        {
          id: 'CARD-ACCT-016',
          name: 'Account Downgrade Rate',
          description: 'Percentage of accounts downgraded to basic products',
          category: 'Account',
          type: 'diagnostic',
          subcategory: 'Product Migration',
        },
        {
          id: 'CARD-ACCT-017',
          name: 'Credit Limit Increase Requests',
          description: 'Number of CLI requests per 1,000 accounts',
          category: 'Account',
          type: 'diagnostic',
          subcategory: 'Credit Management',
        },
        {
          id: 'CARD-ACCT-018',
          name: 'Credit Limit Increase Approval Rate',
          description: 'Percentage of CLI requests approved',
          category: 'Account',
          type: 'diagnostic',
          subcategory: 'Credit Management',
        },
        {
          id: 'CARD-ACCT-019',
          name: 'Credit Limit Decrease Rate',
          description: 'Percentage of accounts with CL reductions',
          category: 'Account',
          type: 'diagnostic',
          subcategory: 'Credit Management',
        },
        {
          id: 'CARD-ACCT-020',
          name: 'Average Account Lifetime Value',
          description: 'Mean LTV for card accounts',
          category: 'Account',
          type: 'diagnostic',
          subcategory: 'Value',
        },
      ],
    },

    // Category 3: Transaction & Spend Metrics (20 metrics)
    {
      name: 'Transaction & Spend Metrics',
      description: 'Transaction volume, value, and behavior patterns',
      totalMetrics: 20,
      
      metrics: [
        {
          id: 'CARD-TXN-001',
          name: 'Total Transaction Volume',
          description: 'Total number of card transactions processed',
          category: 'Transaction',
          type: 'operational',
          subcategory: 'Volume',
          formula: "COUNT(transaction_id WHERE is_posted = TRUE)",
          dataType: 'INTEGER',
          unit: 'count',
          aggregation: 'SUM',
          granularity: 'Hourly',
          benchmarks: {
            industryAverage: '50M transactions/month',
            topQuartile: '100M transactions/month',
            target: '75M transactions/month',
          },
        },
        {
          id: 'CARD-TXN-002',
          name: 'Total Transaction Value',
          description: 'Total dollar value of transactions processed',
          category: 'Transaction',
          type: 'operational',
          subcategory: 'Value',
          benchmarks: {
            industryAverage: '$3B/month',
            topQuartile: '$5B/month',
            target: '$4B/month',
          },
        },
        {
          id: 'CARD-TXN-003',
          name: 'Average Transaction Size',
          description: 'Average dollar amount per transaction',
          category: 'Transaction',
          type: 'operational',
          subcategory: 'Behavior',
        },
        {
          id: 'CARD-TXN-004',
          name: 'Purchase Transaction Rate',
          description: 'Percentage of transactions that are purchases',
          category: 'Transaction',
          type: 'operational',
          subcategory: 'Type',
        },
        {
          id: 'CARD-TXN-005',
          name: 'Cash Advance Rate',
          description: 'Percentage of transactions that are cash advances',
          category: 'Transaction',
          type: 'operational',
          subcategory: 'Type',
        },
        {
          id: 'CARD-TXN-006',
          name: 'E-Commerce Transaction Rate',
          description: 'Percentage of transactions made online',
          category: 'Transaction',
          type: 'operational',
          subcategory: 'Channel',
        },
        {
          id: 'CARD-TXN-007',
          name: 'Contactless Transaction Adoption',
          description: 'Percentage of in-person transactions using contactless',
          category: 'Transaction',
          type: 'operational',
          subcategory: 'Technology',
        },
        {
          id: 'CARD-TXN-008',
          name: 'International Transaction Volume',
          description: 'Number of transactions made outside home country',
          category: 'Transaction',
          type: 'operational',
          subcategory: 'Geography',
        },
        {
          id: 'CARD-TXN-009',
          name: 'Recurring Transaction Count',
          description: 'Number of subscription/recurring transactions',
          category: 'Transaction',
          type: 'operational',
          subcategory: 'Pattern',
        },
        {
          id: 'CARD-TXN-010',
          name: 'Weekend vs Weekday Transaction Mix',
          description: 'Transaction distribution by day of week',
          category: 'Transaction',
          type: 'operational',
          subcategory: 'Timing',
        },
        {
          id: 'CARD-TXN-011',
          name: 'Merchant Category Distribution',
          description: 'Spend distribution across MCC categories',
          category: 'Transaction',
          type: 'operational',
          subcategory: 'Merchant',
        },
        {
          id: 'CARD-TXN-012',
          name: 'Digital Wallet Transaction Rate',
          description: 'Percentage of transactions via digital wallets',
          category: 'Transaction',
          type: 'operational',
          subcategory: 'Digital',
        },
        {
          id: 'CARD-TXN-013',
          name: 'Card Present vs Card Not Present Mix',
          description: 'Transaction distribution by presence type',
          category: 'Transaction',
          type: 'operational',
          subcategory: 'Presence',
        },
        {
          id: 'CARD-TXN-014',
          name: 'Average Monthly Spend per Account',
          description: 'Mean monthly spending per active card',
          category: 'Transaction',
          type: 'operational',
          subcategory: 'Spend',
        },
        {
          id: 'CARD-TXN-015',
          name: 'Transaction Frequency per Account',
          description: 'Average transactions per account per month',
          category: 'Transaction',
          type: 'operational',
          subcategory: 'Frequency',
        },
        {
          id: 'CARD-TXN-016',
          name: 'Large Transaction Rate',
          description: 'Percentage of transactions over $500',
          category: 'Transaction',
          type: 'operational',
          subcategory: 'Size',
        },
        {
          id: 'CARD-TXN-017',
          name: 'Micro-Transaction Rate',
          description: 'Percentage of transactions under $10',
          category: 'Transaction',
          type: 'operational',
          subcategory: 'Size',
        },
        {
          id: 'CARD-TXN-018',
          name: 'Fuel Purchase Percentage',
          description: 'Percentage of transactions at gas stations',
          category: 'Transaction',
          type: 'operational',
          subcategory: 'Category',
        },
        {
          id: 'CARD-TXN-019',
          name: 'Grocery Purchase Percentage',
          description: 'Percentage of transactions at grocery stores',
          category: 'Transaction',
          type: 'operational',
          subcategory: 'Category',
        },
        {
          id: 'CARD-TXN-020',
          name: 'Restaurant Purchase Percentage',
          description: 'Percentage of transactions at restaurants',
          category: 'Transaction',
          type: 'operational',
          subcategory: 'Category',
        },
      ],
    },

    // Category 4: Credit Risk & Quality Metrics (20 metrics)
    {
      name: 'Credit Risk & Quality Metrics',
      description: 'Credit quality, utilization, delinquency, and risk management',
      totalMetrics: 20,
      
      metrics: [
        {
          id: 'CARD-RISK-001',
          name: 'Portfolio Utilization Rate',
          description: 'Percentage of total credit limit being used',
          category: 'Risk',
          type: 'risk',
          subcategory: 'Utilization',
          formula: "(SUM(current_balance) / SUM(credit_limit)) * 100",
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'AVG',
          granularity: 'Daily',
          benchmarks: {
            industryAverage: '30%',
            topQuartile: '25%',
            target: '28%',
          },
        },
        {
          id: 'CARD-RISK-002',
          name: 'Delinquency Rate (30+ DPD)',
          description: 'Percentage of accounts 30+ days past due',
          category: 'Risk',
          type: 'risk',
          subcategory: 'Delinquency',
          benchmarks: {
            industryAverage: '2.5%',
            topQuartile: '1.8%',
            target: '2.0%',
          },
        },
        {
          id: 'CARD-RISK-003',
          name: 'Delinquency Rate (60+ DPD)',
          description: 'Percentage of accounts 60+ days past due',
          category: 'Risk',
          type: 'risk',
          subcategory: 'Delinquency',
        },
        {
          id: 'CARD-RISK-004',
          name: 'Delinquency Rate (90+ DPD)',
          description: 'Percentage of accounts 90+ days past due',
          category: 'Risk',
          type: 'risk',
          subcategory: 'Delinquency',
        },
        {
          id: 'CARD-RISK-005',
          name: 'Charge-Off Rate',
          description: 'Percentage of accounts written off as uncollectible',
          category: 'Risk',
          type: 'risk',
          subcategory: 'Credit Loss',
          benchmarks: {
            industryAverage: '3.5%',
            topQuartile: '2.8%',
            target: '3.0%',
          },
        },
        {
          id: 'CARD-RISK-006',
          name: 'Net Charge-Off Rate',
          description: 'Charge-offs minus recoveries as percentage of balances',
          category: 'Risk',
          type: 'risk',
          subcategory: 'Credit Loss',
        },
        {
          id: 'CARD-RISK-007',
          name: 'Recovery Rate',
          description: 'Percentage of charged-off amounts recovered',
          category: 'Risk',
          type: 'risk',
          subcategory: 'Recoveries',
        },
        {
          id: 'CARD-RISK-008',
          name: 'Allowance for Credit Losses',
          description: 'Total reserves for expected credit losses',
          category: 'Risk',
          type: 'risk',
          subcategory: 'Reserves',
        },
        {
          id: 'CARD-RISK-009',
          name: 'High Utilization Account Rate',
          description: 'Percentage of accounts over 75% utilized',
          category: 'Risk',
          type: 'risk',
          subcategory: 'Utilization',
        },
        {
          id: 'CARD-RISK-010',
          name: 'Over Limit Account Rate',
          description: 'Percentage of accounts over credit limit',
          category: 'Risk',
          type: 'risk',
          subcategory: 'Overlimit',
        },
        {
          id: 'CARD-RISK-011',
          name: 'Minimum Payment Rate',
          description: 'Percentage of accounts making only minimum payment',
          category: 'Risk',
          type: 'risk',
          subcategory: 'Payment Behavior',
        },
        {
          id: 'CARD-RISK-012',
          name: 'Full Payment Rate',
          description: 'Percentage of accounts paying in full each month',
          category: 'Risk',
          type: 'risk',
          subcategory: 'Payment Behavior',
        },
        {
          id: 'CARD-RISK-013',
          name: 'Skipped Payment Rate',
          description: 'Percentage of accounts missing a payment',
          category: 'Risk',
          type: 'risk',
          subcategory: 'Payment Behavior',
        },
        {
          id: 'CARD-RISK-014',
          name: 'Average FICO Score',
          description: 'Mean FICO score of active cardholders',
          category: 'Risk',
          type: 'risk',
          subcategory: 'Credit Score',
        },
        {
          id: 'CARD-RISK-015',
          name: 'Subprime Account Percentage',
          description: 'Percentage of accounts with subprime credit scores',
          category: 'Risk',
          type: 'risk',
          subcategory: 'Risk Segmentation',
        },
        {
          id: 'CARD-RISK-016',
          name: 'Roll Rate (Current to 30 DPD)',
          description: 'Percentage of current accounts becoming 30 DPD',
          category: 'Risk',
          type: 'risk',
          subcategory: 'Roll Rates',
        },
        {
          id: 'CARD-RISK-017',
          name: 'Roll Rate (30 to 60 DPD)',
          description: 'Percentage of 30 DPD accounts rolling to 60 DPD',
          category: 'Risk',
          type: 'risk',
          subcategory: 'Roll Rates',
        },
        {
          id: 'CARD-RISK-018',
          name: 'Cure Rate',
          description: 'Percentage of delinquent accounts becoming current',
          category: 'Risk',
          type: 'risk',
          subcategory: 'Recovery',
        },
        {
          id: 'CARD-RISK-019',
          name: 'Balance at Charge-Off',
          description: 'Average balance when account is charged off',
          category: 'Risk',
          type: 'risk',
          subcategory: 'Loss Severity',
        },
        {
          id: 'CARD-RISK-020',
          name: 'Loss Given Default (LGD)',
          description: 'Average loss per defaulted account',
          category: 'Risk',
          type: 'risk',
          subcategory: 'Loss',
        },
      ],
    },

    // Category 5: Revenue & Profitability Metrics (20 metrics)
    {
      name: 'Revenue & Profitability Metrics',
      description: 'Interest income, fee income, interchange, and profitability',
      totalMetrics: 20,
      
      metrics: [
        {
          id: 'CARD-REV-001',
          name: 'Total Card Revenue',
          description: 'Total revenue from all card sources',
          category: 'Revenue',
          type: 'financial',
          subcategory: 'Total',
          formula: "SUM(interest_income + fee_income + interchange_income)",
          dataType: 'DECIMAL',
          unit: 'USD',
          aggregation: 'SUM',
          granularity: 'Daily',
          benchmarks: {
            industryAverage: '$500M/year',
            topQuartile: '$800M/year',
            target: '$650M/year',
          },
        },
        {
          id: 'CARD-REV-002',
          name: 'Interest Income',
          description: 'Revenue from credit card interest charges',
          category: 'Revenue',
          type: 'financial',
          subcategory: 'Interest',
          benchmarks: {
            industryAverage: '$300M/year',
            topQuartile: '$500M/year',
            target: '$400M/year',
          },
        },
        {
          id: 'CARD-REV-003',
          name: 'Fee Income',
          description: 'Revenue from card fees (annual, late, cash advance, etc.)',
          category: 'Revenue',
          type: 'financial',
          subcategory: 'Fees',
        },
        {
          id: 'CARD-REV-004',
          name: 'Interchange Income',
          description: 'Revenue from card network interchange fees',
          category: 'Revenue',
          type: 'financial',
          subcategory: 'Interchange',
        },
        {
          id: 'CARD-REV-005',
          name: 'Average Revenue Per Account (ARPA)',
          description: 'Mean revenue per active card account',
          category: 'Revenue',
          type: 'financial',
          subcategory: 'Unit Economics',
        },
        {
          id: 'CARD-REV-006',
          name: 'Revenue from Revolvers',
          description: 'Revenue from accounts carrying balances',
          category: 'Revenue',
          type: 'financial',
          subcategory: 'Revolver',
        },
        {
          id: 'CARD-REV-007',
          name: 'Revenue from Transactors',
          description: 'Revenue from accounts paying in full',
          category: 'Revenue',
          type: 'financial',
          subcategory: 'Transactor',
        },
        {
          id: 'CARD-REV-008',
          name: 'Annual Fee Revenue',
          description: 'Total revenue from annual account fees',
          category: 'Revenue',
          type: 'financial',
          subcategory: 'Fees',
        },
        {
          id: 'CARD-REV-009',
          name: 'Late Fee Revenue',
          description: 'Total revenue from late payment fees',
          category: 'Revenue',
          type: 'financial',
          subcategory: 'Fees',
        },
        {
          id: 'CARD-REV-010',
          name: 'Cash Advance Fee Revenue',
          description: 'Total revenue from cash advance fees',
          category: 'Revenue',
          type: 'financial',
          subcategory: 'Fees',
        },
        {
          id: 'CARD-REV-011',
          name: 'Balance Transfer Fee Revenue',
          description: 'Total revenue from balance transfer fees',
          category: 'Revenue',
          type: 'financial',
          subcategory: 'Fees',
        },
        {
          id: 'CARD-REV-012',
          name: 'Foreign Transaction Fee Revenue',
          description: 'Total revenue from foreign transaction fees',
          category: 'Revenue',
          type: 'financial',
          subcategory: 'Fees',
        },
        {
          id: 'CARD-REV-013',
          name: 'Over Limit Fee Revenue',
          description: 'Total revenue from over limit fees',
          category: 'Revenue',
          type: 'financial',
          subcategory: 'Fees',
        },
        {
          id: 'CARD-REV-014',
          name: 'Net Interest Margin',
          description: 'Interest income minus cost of funds',
          category: 'Revenue',
          type: 'financial',
          subcategory: 'Margin',
        },
        {
          id: 'CARD-REV-015',
          name: 'Cost of Funds',
          description: 'Average cost to fund card portfolio',
          category: 'Revenue',
          type: 'financial',
          subcategory: 'Cost',
        },
        {
          id: 'CARD-REV-016',
          name: 'Return on Assets (ROA)',
          description: 'Card portfolio ROA',
          category: 'Revenue',
          type: 'financial',
          subcategory: 'Returns',
        },
        {
          id: 'CARD-REV-017',
          name: 'Return on Equity (ROE)',
          description: 'Card portfolio ROE',
          category: 'Revenue',
          type: 'financial',
          subcategory: 'Returns',
        },
        {
          id: 'CARD-REV-018',
          name: 'Rewards Cost',
          description: 'Total cost of rewards programs',
          category: 'Revenue',
          type: 'financial',
          subcategory: 'Expenses',
        },
        {
          id: 'CARD-REV-019',
          name: 'Rewards Cost as % of Revenue',
          description: 'Rewards expense as percentage of total revenue',
          category: 'Revenue',
          type: 'financial',
          subcategory: 'Efficiency',
        },
        {
          id: 'CARD-REV-020',
          name: 'Account Profitability Score',
          description: 'Composite profitability metric per account',
          category: 'Revenue',
          type: 'financial',
          subcategory: 'Profitability',
        },
      ],
    },
  ],
};

export const cardsRetailMetricsComplete = {
  description: 'Complete metrics catalog for retail cards domain',
  catalog: cardsRetailMetricsCatalog,
  totalMetrics: 100,
  totalCategories: 5,
  version: '1.0',
  lastUpdated: '2025-01-08',
};

export default cardsRetailMetricsCatalog;
