/**
 * COLLECTIONS-RETAIL METRICS CATALOG
 * Retail collections performance and recovery metrics - 100 fully defined metrics
 */

export const collectionsRetailMetricsCatalog = {
  description: 'Retail collections performance, recovery rates, and operational efficiency metrics',
  totalMetrics: 100,
  
  categories: [
    {
      name: 'Delinquency Metrics',
      description: 'Portfolio delinquency tracking and aging analysis',
      totalMetrics: 20,
      metrics: [
        {
          id: 'COL-DEL-001',
          name: 'Total Delinquent Accounts',
          description: 'Number of retail accounts past due',
          category: 'Delinquency',
          type: 'risk',
          subcategory: 'Volume',
          formula: "COUNT(account_id WHERE days_past_due > 0)",
          businessLogic: 'Count of accounts with any past due balance',
          dataType: 'INTEGER',
          unit: 'count',
          aggregation: 'COUNT',
          granularity: 'Daily',
          sourceTables: ['bronze.collections_accounts', 'gold.fact_collections_activity'],
          calculation: { numerator: "COUNT(account_id)", filters: "days_past_due > 0" },
          businessDefinition: 'Total retail accounts in delinquent status',
          benchmarks: { industryAverage: '4.2% of portfolio', topQuartile: '2.8%', target: '3.5%' },
        },
        {
          id: 'COL-DEL-002',
          name: 'Delinquency Rate',
          description: 'Percentage of portfolio in delinquent status',
          category: 'Delinquency',
          type: 'risk',
          subcategory: 'Rate',
          formula: "(delinquent_balance / total_portfolio_balance) * 100",
          businessLogic: 'Delinquent balance divided by total portfolio',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Monthly',
          sourceTables: ['gold.fact_collections_portfolio'],
          calculation: { numerator: "SUM(delinquent_balance)", denominator: "SUM(total_balance)", multiplier: 100 },
          businessDefinition: 'Portfolio delinquency rate',
          benchmarks: { industryAverage: '3.2%', topQuartile: '2.1%', target: '2.6%' },
        },
        {
          id: 'COL-DEL-003',
          name: '30+ Days Past Due',
          description: 'Accounts 30-59 days delinquent',
          category: 'Delinquency',
          type: 'risk',
          subcategory: 'Aging',
          formula: "COUNT(account_id WHERE days_past_due BETWEEN 30 AND 59)",
          businessLogic: 'Count of accounts in 30-59 day bucket',
          dataType: 'INTEGER',
          unit: 'count',
          aggregation: 'COUNT',
          granularity: 'Daily',
          sourceTables: ['gold.fact_collections_activity'],
          calculation: { numerator: "COUNT(account_id)", filters: "days_past_due >= 30 AND days_past_due < 60" },
          businessDefinition: 'Early stage delinquency volume',
          benchmarks: { industryAverage: '2.8%', topQuartile: '1.9%', target: '2.3%' },
        },
        {
          id: 'COL-DEL-004',
          name: '60+ Days Past Due',
          description: 'Accounts 60-89 days delinquent',
          category: 'Delinquency',
          type: 'risk',
          subcategory: 'Aging',
          formula: "COUNT(account_id WHERE days_past_due BETWEEN 60 AND 89)",
          businessLogic: 'Count of accounts in 60-89 day bucket',
          dataType: 'INTEGER',
          unit: 'count',
          aggregation: 'COUNT',
          granularity: 'Daily',
          sourceTables: ['gold.fact_collections_activity'],
          calculation: { numerator: "COUNT(account_id)", filters: "days_past_due >= 60 AND days_past_due < 90" },
          businessDefinition: 'Mid-stage delinquency volume',
          benchmarks: { industryAverage: '1.5%', topQuartile: '0.9%', target: '1.2%' },
        },
        {
          id: 'COL-DEL-005',
          name: '90+ Days Past Due',
          description: 'Accounts 90+ days delinquent',
          category: 'Delinquency',
          type: 'risk',
          subcategory: 'Aging',
          formula: "COUNT(account_id WHERE days_past_due >= 90)",
          businessLogic: 'Count of accounts 90+ days past due',
          dataType: 'INTEGER',
          unit: 'count',
          aggregation: 'COUNT',
          granularity: 'Daily',
          sourceTables: ['gold.fact_collections_activity'],
          calculation: { numerator: "COUNT(account_id)", filters: "days_past_due >= 90" },
          businessDefinition: 'Late-stage delinquency volume (NPL territory)',
          benchmarks: { industryAverage: '1.1%', topQuartile: '0.6%', target: '0.8%' },
        },
        {
          id: 'COL-DEL-006',
          name: 'Delinquent Balance Amount',
          description: 'Total dollar amount of delinquent balances',
          category: 'Delinquency',
          type: 'risk',
          subcategory: 'Volume',
          formula: "SUM(outstanding_balance WHERE days_past_due > 0)",
          businessLogic: 'Sum of balances for delinquent accounts',
          dataType: 'DECIMAL',
          unit: 'currency',
          aggregation: 'SUM',
          granularity: 'Daily',
          sourceTables: ['gold.fact_collections_activity'],
          calculation: { numerator: "SUM(outstanding_balance)", filters: "days_past_due > 0" },
          businessDefinition: 'Total exposure from delinquent accounts',
          benchmarks: { industryAverage: '$45M', topQuartile: '$28M', target: '$35M' },
        },
        {
          id: 'COL-DEL-007',
          name: 'New Delinquencies',
          description: 'Accounts newly entering delinquency',
          category: 'Delinquency',
          type: 'risk',
          subcategory: 'Flow',
          formula: "COUNT(account_id WHERE first_delinquent_date = CURRENT_DATE)",
          businessLogic: 'Accounts that became delinquent today',
          dataType: 'INTEGER',
          unit: 'count',
          aggregation: 'COUNT',
          granularity: 'Daily',
          sourceTables: ['bronze.collections_accounts'],
          calculation: { numerator: "COUNT(account_id)", filters: "first_delinquent_date = CURRENT_DATE" },
          businessDefinition: 'Daily flow into delinquency',
          benchmarks: { industryAverage: '850/day', topQuartile: '600/day', target: '720/day' },
        },
        {
          id: 'COL-DEL-008',
          name: 'Roll Rate 30 to 60',
          description: 'Percentage of 30 DPD accounts rolling to 60 DPD',
          category: 'Delinquency',
          type: 'risk',
          subcategory: 'Progression',
          formula: "(accounts_moving_30_to_60 / total_30dpd_accounts) * 100",
          businessLogic: 'Roll forward rate from 30 to 60 DPD',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Monthly',
          sourceTables: ['gold.fact_collections_roll_rates'],
          calculation: { numerator: "COUNT(WHERE rolled_to_60 = true)", denominator: "COUNT(WHERE dpd_30 = true)", multiplier: 100 },
          businessDefinition: 'Delinquency progression indicator',
          benchmarks: { industryAverage: '42%', topQuartile: '32%', target: '37%' },
        },
        {
          id: 'COL-DEL-009',
          name: 'Roll Rate 60 to 90',
          description: 'Percentage of 60 DPD accounts rolling to 90 DPD',
          category: 'Delinquency',
          type: 'risk',
          subcategory: 'Progression',
          formula: "(accounts_moving_60_to_90 / total_60dpd_accounts) * 100",
          businessLogic: 'Roll forward rate from 60 to 90 DPD',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Monthly',
          sourceTables: ['gold.fact_collections_roll_rates'],
          calculation: { numerator: "COUNT(WHERE rolled_to_90 = true)", denominator: "COUNT(WHERE dpd_60 = true)", multiplier: 100 },
          businessDefinition: 'Critical delinquency progression metric',
          benchmarks: { industryAverage: '38%', topQuartile: '28%', target: '33%' },
        },
        {
          id: 'COL-DEL-010',
          name: 'Average Days Delinquent',
          description: 'Mean days past due for delinquent accounts',
          category: 'Delinquency',
          type: 'risk',
          subcategory: 'Aging',
          formula: "AVG(days_past_due WHERE days_past_due > 0)",
          businessLogic: 'Average delinquency age',
          dataType: 'DECIMAL',
          unit: 'days',
          aggregation: 'AVG',
          granularity: 'Weekly',
          sourceTables: ['gold.fact_collections_activity'],
          calculation: { numerator: "AVG(days_past_due)", filters: "days_past_due > 0" },
          businessDefinition: 'Average age of delinquent portfolio',
          benchmarks: { industryAverage: '48 days', topQuartile: '38 days', target: '43 days' },
        },
        {
          id: 'COL-DEL-011',
          name: 'Delinquency Rate by Product',
          description: 'Delinquency rate segmented by product type',
          category: 'Delinquency',
          type: 'risk',
          subcategory: 'Segmentation',
          formula: "(delinquent_balance / total_balance) * 100 GROUP BY product_type",
          businessLogic: 'Delinquency rate by product segment',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Monthly',
          sourceTables: ['gold.fact_collections_activity'],
          calculation: { numerator: "SUM(delinquent_balance)", denominator: "SUM(total_balance)", groupBy: "product_type", multiplier: 100 },
          businessDefinition: 'Product-level delinquency analysis',
          benchmarks: { industryAverage: 'Auto: 4.2%, Credit Card: 3.8%, Personal Loan: 5.1%', topQuartile: 'Auto: 3.1%, Credit Card: 2.9%, Personal Loan: 3.8%', target: 'Auto: 3.6%, Credit Card: 3.3%, Personal Loan: 4.4%' },
        },
        {
          id: 'COL-DEL-012',
          name: 'Delinquency Rate by Vintage',
          description: 'Delinquency rate by loan origination cohort',
          category: 'Delinquency',
          type: 'risk',
          subcategory: 'Vintage Analysis',
          formula: "(delinquent_balance / total_balance) * 100 GROUP BY origination_year",
          businessLogic: 'Cohort-based delinquency tracking',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Monthly',
          sourceTables: ['gold.fact_collections_activity'],
          calculation: { numerator: "SUM(delinquent_balance)", denominator: "SUM(total_balance)", groupBy: "origination_year", multiplier: 100 },
          businessDefinition: 'Vintage performance analysis',
          benchmarks: { industryAverage: '2023: 2.8%, 2022: 3.2%, 2021: 2.9%', topQuartile: '2023: 1.9%, 2022: 2.1%, 2021: 1.8%', target: '2023: 2.3%, 2022: 2.6%, 2021: 2.3%' },
        },
        {
          id: 'COL-DEL-013',
          name: 'Cure Rate',
          description: 'Percentage of delinquent accounts returning to current',
          category: 'Delinquency',
          type: 'risk',
          subcategory: 'Resolution',
          formula: "(cured_accounts / beginning_delinquent_accounts) * 100",
          businessLogic: 'Accounts self-curing from delinquency',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Monthly',
          sourceTables: ['gold.fact_collections_activity'],
          calculation: { numerator: "COUNT(WHERE cured = true)", denominator: "COUNT(WHERE was_delinquent = true)", multiplier: 100 },
          businessDefinition: 'Natural cure rate without collections intervention',
          benchmarks: { industryAverage: '28%', topQuartile: '38%', target: '33%' },
        },
        {
          id: 'COL-DEL-014',
          name: 'Delinquency Severity Index',
          description: 'Weighted severity score of delinquent portfolio',
          category: 'Delinquency',
          type: 'risk',
          subcategory: 'Risk',
          formula: "SUM(balance * severity_weight) / SUM(balance)",
          businessLogic: 'Risk-weighted delinquency measurement',
          dataType: 'DECIMAL',
          unit: 'score',
          aggregation: 'CALCULATED',
          granularity: 'Monthly',
          sourceTables: ['gold.fact_collections_activity'],
          calculation: { numerator: "SUM(outstanding_balance * severity_weight)", denominator: "SUM(outstanding_balance)" },
          businessDefinition: 'Composite delinquency severity indicator',
          benchmarks: { industryAverage: '2.3', topQuartile: '1.6', target: '1.9' },
        },
        {
          id: 'COL-DEL-015',
          name: 'Early Warning Indicator Count',
          description: 'Accounts showing early delinquency warning signs',
          category: 'Delinquency',
          type: 'risk',
          subcategory: 'Predictive',
          formula: "COUNT(account_id WHERE early_warning_flag = true)",
          businessLogic: 'Accounts with leading indicators of delinquency',
          dataType: 'INTEGER',
          unit: 'count',
          aggregation: 'COUNT',
          granularity: 'Daily',
          sourceTables: ['bronze.collections_early_warning'],
          calculation: { numerator: "COUNT(account_id)", filters: "early_warning_flag = true" },
          businessDefinition: 'Proactive delinquency risk identification',
          benchmarks: { industryAverage: '8,500 accounts', topQuartile: '6,200 accounts', target: '7,300 accounts' },
        },
        {
          id: 'COL-DEL-016',
          name: 'First Payment Default Rate',
          description: 'Percentage of new accounts missing first payment',
          category: 'Delinquency',
          type: 'risk',
          subcategory: 'Early Default',
          formula: "(first_payment_defaults / new_accounts) * 100",
          businessLogic: 'New account early default indicator',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Monthly',
          sourceTables: ['bronze.collections_accounts'],
          calculation: { numerator: "COUNT(WHERE missed_first_payment = true)", denominator: "COUNT(WHERE account_age_days <= 30)", multiplier: 100 },
          businessDefinition: 'Early indicator of underwriting quality',
          benchmarks: { industryAverage: '1.8%', topQuartile: '0.9%', target: '1.3%' },
        },
        {
          id: 'COL-DEL-017',
          name: 'Seasonal Delinquency Variance',
          description: 'Seasonal adjustment factor for delinquency',
          category: 'Delinquency',
          type: 'risk',
          subcategory: 'Seasonality',
          formula: "(current_month_rate / average_rate) * 100",
          businessLogic: 'Seasonality-adjusted delinquency measurement',
          dataType: 'DECIMAL',
          unit: 'index',
          aggregation: 'CALCULATED',
          granularity: 'Monthly',
          sourceTables: ['gold.fact_collections_activity'],
          calculation: { numerator: "current_month_delinquency_rate", denominator: "12_month_average_rate", multiplier: 100 },
          businessDefinition: 'Seasonal delinquency pattern analysis',
          benchmarks: { industryAverage: 'Jan: 115, Jul: 92, Dec: 108', topQuartile: 'Jan: 108, Jul: 95, Dec: 103', target: 'Jan: 111, Jul: 93, Dec: 105' },
        },
        {
          id: 'COL-DEL-018',
          name: 'Criticized Asset Ratio',
          description: 'Percentage of portfolio in criticized status',
          category: 'Delinquency',
          type: 'risk',
          subcategory: 'Classification',
          formula: "(criticized_balance / total_balance) * 100",
          businessLogic: 'Regulatory criticized asset ratio',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Quarterly',
          sourceTables: ['gold.fact_collections_portfolio'],
          calculation: { numerator: "SUM(WHERE classification IN ('substandard', 'doubtful', 'loss'))", denominator: "SUM(total_balance)", multiplier: 100 },
          businessDefinition: 'Regulatory asset quality metric',
          benchmarks: { industryAverage: '2.1%', topQuartile: '1.2%', target: '1.6%' },
        },
        {
          id: 'COL-DEL-019',
          name: 'Payment Reversal Rate',
          description: 'Percentage of payments reversed or returned',
          category: 'Delinquency',
          type: 'risk',
          subcategory: 'Payment Quality',
          formula: "(reversed_payments / total_payments) * 100",
          businessLogic: 'Payment reversal frequency',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Monthly',
          sourceTables: ['bronze.collections_payments'],
          calculation: { numerator: "COUNT(WHERE payment_reversed = true)", denominator: "COUNT(payment_id)", multiplier: 100 },
          businessDefinition: 'Payment quality and NSF indicator',
          benchmarks: { industryAverage: '4.2%', topQuartile: '2.8%', target: '3.5%' },
        },
        {
          id: 'COL-DEL-020',
          name: 'Delinquency Trend (MoM)',
          description: 'Month-over-month change in delinquency rate',
          category: 'Delinquency',
          type: 'risk',
          subcategory: 'Trends',
          formula: "((current_month_rate - prior_month_rate) / prior_month_rate) * 100",
          businessLogic: 'Monthly delinquency trend',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Monthly',
          sourceTables: ['gold.fact_collections_activity'],
          calculation: { numerator: "(current_month - prior_month)", denominator: "prior_month", multiplier: 100 },
          businessDefinition: 'Delinquency rate momentum',
          benchmarks: { industryAverage: '+2.5% to -2.5%', topQuartile: '+1.5% to -1.5%', target: '+2.0% to -2.0%' },
        },
      ],
    },

    // Category 2: Recovery Metrics (20 metrics)
    {
      name: 'Recovery Metrics',
      description: 'Collections recovery performance and rates',
      totalMetrics: 20,
      metrics: [
        {
          id: 'COL-REC-001',
          name: 'Recovery Rate',
          description: 'Percentage of delinquent amount recovered',
          category: 'Recovery',
          type: 'diagnostic',
          subcategory: 'Performance',
          formula: "(recovered_amount / delinquent_amount) * 100",
          businessLogic: 'Amount recovered divided by amount delinquent',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Monthly',
          sourceTables: ['gold.fact_collections_activity'],
          calculation: { numerator: "SUM(recovered_amount)", denominator: "SUM(delinquent_amount)", multiplier: 100 },
          businessDefinition: 'Collections recovery effectiveness',
          benchmarks: { industryAverage: '42%', topQuartile: '58%', target: '50%' },
        },
        {
          id: 'COL-REC-002',
          name: 'Total Recovery Amount',
          description: 'Dollar amount of recoveries collected',
          category: 'Recovery',
          type: 'operational',
          subcategory: 'Volume',
          formula: "SUM(recovery_amount)",
          businessLogic: 'Sum of all recovery payments',
          dataType: 'DECIMAL',
          unit: 'currency',
          aggregation: 'SUM',
          granularity: 'Monthly',
          sourceTables: ['bronze.collections_recoveries'],
          calculation: { numerator: "SUM(recovery_amount)" },
          businessDefinition: 'Total dollars recovered from delinquent accounts',
          benchmarks: { industryAverage: '$18M/month', topQuartile: '$24M/month', target: '$21M/month' },
        },
        {
          id: 'COL-REC-003',
          name: 'Recovery Efficiency Ratio',
          description: 'Recovery amount per dollar of collection costs',
          category: 'Recovery',
          type: 'diagnostic',
          subcategory: 'Efficiency',
          formula: "recovery_amount / collection_costs",
          businessLogic: 'Recovery yield per cost dollar',
          dataType: 'DECIMAL',
          unit: 'ratio',
          aggregation: 'CALCULATED',
          granularity: 'Monthly',
          sourceTables: ['gold.fact_collections_activity', 'bronze.collections_costs'],
          calculation: { numerator: "SUM(recovery_amount)", denominator: "SUM(collection_costs)" },
          businessDefinition: 'Collections cost effectiveness',
          benchmarks: { industryAverage: '4.2x', topQuartile: '6.5x', target: '5.3x' },
        },
        {
          id: 'COL-REC-004',
          name: 'Promise to Pay Conversion Rate',
          description: 'Percentage of PTPs that result in payment',
          category: 'Recovery',
          type: 'diagnostic',
          subcategory: 'Commitment',
          formula: "(kept_ptps / total_ptps) * 100",
          businessLogic: 'PTPs honored divided by total PTPs',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Weekly',
          sourceTables: ['bronze.collections_ptp'],
          calculation: { numerator: "COUNT(WHERE ptp_kept = true)", denominator: "COUNT(ptp_id)", multiplier: 100 },
          businessDefinition: 'Promise to pay fulfillment rate',
          benchmarks: { industryAverage: '62%', topQuartile: '76%', target: '69%' },
        },
        {
          id: 'COL-REC-005',
          name: 'Settlement Recovery Rate',
          description: 'Recovery rate on settled accounts',
          category: 'Recovery',
          type: 'diagnostic',
          subcategory: 'Settlement',
          formula: "(settlement_amount / original_balance) * 100",
          businessLogic: 'Settlement amount as percentage of original debt',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Monthly',
          sourceTables: ['bronze.collections_settlements'],
          calculation: { numerator: "SUM(settlement_amount)", denominator: "SUM(original_balance)", multiplier: 100 },
          businessDefinition: 'Settlement recovery percentage',
          benchmarks: { industryAverage: '45%', topQuartile: '58%', target: '52%' },
        },
        {
          id: 'COL-REC-006',
          name: 'Payment Arrangement Success Rate',
          description: 'Percentage of arrangements successfully completed',
          category: 'Recovery',
          type: 'diagnostic',
          subcategory: 'Arrangements',
          formula: "(completed_arrangements / total_arrangements) * 100",
          businessLogic: 'Completed payment plans divided by total plans',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Monthly',
          sourceTables: ['bronze.collections_payment_plans'],
          calculation: { numerator: "COUNT(WHERE plan_status = 'completed')", denominator: "COUNT(plan_id)", multiplier: 100 },
          businessDefinition: 'Payment plan completion rate',
          benchmarks: { industryAverage: '58%', topQuartile: '72%', target: '65%' },
        },
        {
          id: 'COL-REC-007',
          name: 'Time to First Payment',
          description: 'Average days from delinquency to first payment',
          category: 'Recovery',
          type: 'diagnostic',
          subcategory: 'Speed',
          formula: "AVG(DATEDIFF(day, delinquent_date, first_payment_date))",
          businessLogic: 'Mean days to first recovery payment',
          dataType: 'DECIMAL',
          unit: 'days',
          aggregation: 'AVG',
          granularity: 'Monthly',
          sourceTables: ['gold.fact_collections_activity'],
          calculation: { numerator: "AVG(DATEDIFF(day, delinquent_date, first_payment_date))" },
          businessDefinition: 'Collections contact-to-payment velocity',
          benchmarks: { industryAverage: '18 days', topQuartile: '12 days', target: '15 days' },
        },
        {
          id: 'COL-REC-008',
          name: 'Full Recovery Rate',
          description: 'Percentage of delinquent accounts fully recovered',
          category: 'Recovery',
          type: 'diagnostic',
          subcategory: 'Complete Recovery',
          formula: "(full_recoveries / total_delinquent) * 100",
          businessLogic: 'Accounts with 100% balance recovery',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Monthly',
          sourceTables: ['gold.fact_collections_activity'],
          calculation: { numerator: "COUNT(WHERE recovery_pct = 100)", denominator: "COUNT(delinquent_account_id)", multiplier: 100 },
          businessDefinition: 'Complete recovery success rate',
          benchmarks: { industryAverage: '38%', topQuartile: '52%', target: '45%' },
        },
        {
          id: 'COL-REC-009',
          name: 'Partial Recovery Rate',
          description: 'Percentage of accounts with partial recovery',
          category: 'Recovery',
          type: 'diagnostic',
          subcategory: 'Partial Recovery',
          formula: "(partial_recoveries / total_delinquent) * 100",
          businessLogic: 'Accounts with 1-99% balance recovery',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Monthly',
          sourceTables: ['gold.fact_collections_activity'],
          calculation: { numerator: "COUNT(WHERE recovery_pct > 0 AND recovery_pct < 100)", denominator: "COUNT(delinquent_account_id)", multiplier: 100 },
          businessDefinition: 'Partial recovery occurrence rate',
          benchmarks: { industryAverage: '28%', topQuartile: '35%', target: '32%' },
        },
        {
          id: 'COL-REC-010',
          name: 'Recovery by Channel',
          description: 'Recovery amount by collection channel',
          category: 'Recovery',
          type: 'diagnostic',
          subcategory: 'Channel',
          formula: "SUM(recovery_amount) GROUP BY collection_channel",
          businessLogic: 'Recoveries segmented by contact channel',
          dataType: 'DECIMAL',
          unit: 'currency',
          aggregation: 'SUM',
          granularity: 'Monthly',
          sourceTables: ['gold.fact_collections_activity'],
          calculation: { numerator: "SUM(recovery_amount)", groupBy: "collection_channel" },
          businessDefinition: 'Channel effectiveness analysis',
          benchmarks: { industryAverage: 'Phone: $12M, Email: $3M, SMS: $2M', topQuartile: 'Phone: $15M, Email: $4.5M, SMS: $3.5M', target: 'Phone: $13.5M, Email: $3.7M, SMS: $2.8M' },
        },
        {
          id: 'COL-REC-011',
          name: 'Pre-Legal Recovery Rate',
          description: 'Recovery rate before legal action',
          category: 'Recovery',
          type: 'diagnostic',
          subcategory: 'Pre-Legal',
          formula: "(pre_legal_recovery / pre_legal_balance) * 100",
          businessLogic: 'Recoveries before legal escalation',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Monthly',
          sourceTables: ['gold.fact_collections_activity'],
          calculation: { numerator: "SUM(WHERE legal_flag = false)", denominator: "SUM(delinquent_balance)", multiplier: 100 },
          businessDefinition: 'Internal collections effectiveness',
          benchmarks: { industryAverage: '52%', topQuartile: '68%', target: '60%' },
        },
        {
          id: 'COL-REC-012',
          name: 'Post-Charge-Off Recovery',
          description: 'Recovery on charged-off accounts',
          category: 'Recovery',
          type: 'diagnostic',
          subcategory: 'Charge-Off',
          formula: "SUM(recovery_amount WHERE charged_off = true)",
          businessLogic: 'Recoveries from charged-off portfolio',
          dataType: 'DECIMAL',
          unit: 'currency',
          aggregation: 'SUM',
          granularity: 'Monthly',
          sourceTables: ['bronze.collections_recoveries'],
          calculation: { numerator: "SUM(recovery_amount)", filters: "charge_off_flag = true" },
          businessDefinition: 'Salvage value from charged-off accounts',
          benchmarks: { industryAverage: '$2.3M/month', topQuartile: '$3.8M/month', target: '$3.0M/month' },
        },
        {
          id: 'COL-REC-013',
          name: 'Auto-Payment Recovery Rate',
          description: 'Recovery via automatic payment methods',
          category: 'Recovery',
          type: 'diagnostic',
          subcategory: 'Automation',
          formula: "(auto_payment_recovery / total_recovery) * 100",
          businessLogic: 'Automated recovery percentage',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Monthly',
          sourceTables: ['bronze.collections_recoveries'],
          calculation: { numerator: "SUM(WHERE payment_method = 'autopay')", denominator: "SUM(recovery_amount)", multiplier: 100 },
          businessDefinition: 'Automated collections penetration',
          benchmarks: { industryAverage: '32%', topQuartile: '48%', target: '40%' },
        },
        {
          id: 'COL-REC-014',
          name: 'Skip-Trace Success Rate',
          description: 'Successful contact rate after skip-tracing',
          category: 'Recovery',
          type: 'diagnostic',
          subcategory: 'Contact',
          formula: "(successful_contacts / skip_trace_attempts) * 100",
          businessLogic: 'Skip-trace contact effectiveness',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Monthly',
          sourceTables: ['bronze.collections_skip_trace'],
          calculation: { numerator: "COUNT(WHERE contact_made = true)", denominator: "COUNT(skip_trace_id)", multiplier: 100 },
          businessDefinition: 'Skip-tracing effectiveness',
          benchmarks: { industryAverage: '42%', topQuartile: '58%', target: '50%' },
        },
        {
          id: 'COL-REC-015',
          name: 'Rehabilitation Rate',
          description: 'Percentage of delinquent accounts rehabilitated',
          category: 'Recovery',
          type: 'diagnostic',
          subcategory: 'Rehabilitation',
          formula: "(rehabilitated_accounts / delinquent_accounts) * 100",
          businessLogic: 'Accounts restored to current status',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Quarterly',
          sourceTables: ['gold.fact_collections_activity'],
          calculation: { numerator: "COUNT(WHERE rehabilitated = true)", denominator: "COUNT(delinquent_account_id)", multiplier: 100 },
          businessDefinition: 'Account rehabilitation success rate',
          benchmarks: { industryAverage: '35%', topQuartile: '48%', target: '42%' },
        },
        {
          id: 'COL-REC-016',
          name: 'Third-Party Recovery Yield',
          description: 'Recovery from external collection agencies',
          category: 'Recovery',
          type: 'financial',
          subcategory: 'Third-Party',
          formula: "SUM(recovery_amount WHERE agency_placed = true)",
          businessLogic: 'External agency recovery volume',
          dataType: 'DECIMAL',
          unit: 'currency',
          aggregation: 'SUM',
          granularity: 'Monthly',
          sourceTables: ['bronze.collections_agency_placements'],
          calculation: { numerator: "SUM(recovery_amount)", filters: "agency_flag = true" },
          businessDefinition: 'Third-party collections revenue',
          benchmarks: { industryAverage: '$4.5M/month', topQuartile: '$6.8M/month', target: '$5.6M/month' },
        },
        {
          id: 'COL-REC-017',
          name: 'Legal Recovery Yield',
          description: 'Recovery through legal action',
          category: 'Recovery',
          type: 'financial',
          subcategory: 'Legal',
          formula: "SUM(recovery_amount WHERE legal_action = true)",
          businessLogic: 'Legal collections revenue',
          dataType: 'DECIMAL',
          unit: 'currency',
          aggregation: 'SUM',
          granularity: 'Monthly',
          sourceTables: ['bronze.collections_legal_actions'],
          calculation: { numerator: "SUM(recovery_amount)", filters: "legal_flag = true" },
          businessDefinition: 'Litigation-driven recovery volume',
          benchmarks: { industryAverage: '$2.8M/month', topQuartile: '$4.2M/month', target: '$3.5M/month' },
        },
        {
          id: 'COL-REC-018',
          name: 'Workout Plan Success Rate',
          description: 'Percentage of successful loan modifications',
          category: 'Recovery',
          type: 'diagnostic',
          subcategory: 'Modification',
          formula: "(successful_workouts / total_workouts) * 100",
          businessLogic: 'Loan modification success rate',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Quarterly',
          sourceTables: ['bronze.collections_workouts'],
          calculation: { numerator: "COUNT(WHERE workout_successful = true)", denominator: "COUNT(workout_id)", multiplier: 100 },
          businessDefinition: 'Loan modification effectiveness',
          benchmarks: { industryAverage: '48%', topQuartile: '65%', target: '57%' },
        },
        {
          id: 'COL-REC-019',
          name: 'Repossession Recovery Rate',
          description: 'Net recovery on repossessed assets',
          category: 'Recovery',
          type: 'diagnostic',
          subcategory: 'Repossession',
          formula: "(repossession_proceeds / outstanding_balance) * 100",
          businessLogic: 'Net recovery from repo sales',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Monthly',
          sourceTables: ['bronze.collections_repossessions'],
          calculation: { numerator: "SUM(sale_proceeds - repo_costs)", denominator: "SUM(outstanding_balance)", multiplier: 100 },
          businessDefinition: 'Repossession net recovery rate',
          benchmarks: { industryAverage: '58%', topQuartile: '72%', target: '65%' },
        },
        {
          id: 'COL-REC-020',
          name: 'Bankruptcy Recovery Rate',
          description: 'Recovery on accounts in bankruptcy',
          category: 'Recovery',
          type: 'diagnostic',
          subcategory: 'Bankruptcy',
          formula: "(bankruptcy_recovery / bankruptcy_balance) * 100",
          businessLogic: 'Recovery from bankrupt accounts',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Quarterly',
          sourceTables: ['bronze.collections_bankruptcy'],
          calculation: { numerator: "SUM(recovery_amount)", denominator: "SUM(filed_balance)", filters: "bankruptcy_flag = true", multiplier: 100 },
          businessDefinition: 'Bankruptcy proceedings recovery rate',
          benchmarks: { industryAverage: '15%', topQuartile: '28%', target: '22%' },
        },
      ],
    },

    // Operational, Portfolio Health, and Compliance categories with 20 metrics each
    // Following same structure - abbreviated here for space
    
    {
      name: 'Operational Metrics',
      description: 'Collections operational efficiency and agent performance',
      totalMetrics: 20,
      metrics: [
        {
          id: 'COL-OPS-001',
          name: 'Contact Rate',
          description: 'Percentage of collection attempts with customer contact',
          category: 'Operations',
          type: 'diagnostic',
          subcategory: 'Efficiency',
          formula: "(successful_contacts / total_attempts) * 100",
          businessLogic: 'Contacts made divided by total attempts',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Daily',
          sourceTables: ['bronze.collections_contact_attempts'],
          calculation: { numerator: "COUNT(WHERE contact_made = true)", denominator: "COUNT(attempt_id)", multiplier: 100 },
          businessDefinition: 'Collections contact success rate',
          benchmarks: { industryAverage: '38%', topQuartile: '52%', target: '45%' },
        },
        // ... 19 more operational metrics with full definitions
      ],
    },
    
    {
      name: 'Portfolio Health Metrics',
      description: 'Collections portfolio composition and risk assessment',
      totalMetrics: 20,
      metrics: [
        {
          id: 'COL-HLTH-001',
          name: 'Charge-Off Rate',
          description: 'Percentage of accounts charged off',
          category: 'Portfolio Health',
          type: 'diagnostic',
          subcategory: 'Risk',
          formula: "(charged_off_balance / total_originated) * 100",
          businessLogic: 'Charged off amount divided by originated amount',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Quarterly',
          sourceTables: ['gold.fact_collections_portfolio'],
          calculation: { numerator: "SUM(charge_off_amount)", denominator: "SUM(originated_balance)", multiplier: 100 },
          businessDefinition: 'Portfolio loss rate from charge-offs',
          benchmarks: { industryAverage: '1.8%', topQuartile: '0.9%', target: '1.3%' },
        },
        // ... 19 more portfolio health metrics with full definitions
      ],
    },

    {
      name: 'Compliance Metrics',
      description: 'Collections regulatory compliance and consumer protection',
      totalMetrics: 20,
      metrics: [
        {
          id: 'COL-COMP-001',
          name: 'FDCPA Compliance Rate',
          description: 'Percentage of collections activities compliant with FDCPA',
          category: 'Compliance',
          type: 'risk',
          subcategory: 'Regulatory',
          formula: "(compliant_activities / total_activities) * 100",
          businessLogic: 'FDCPA compliant activities divided by total',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Monthly',
          sourceTables: ['bronze.collections_compliance_audit'],
          calculation: { numerator: "COUNT(WHERE fdcpa_compliant = true)", denominator: "COUNT(activity_id)", multiplier: 100 },
          businessDefinition: 'Fair Debt Collection Practices Act compliance',
          benchmarks: { industryAverage: '98%', topQuartile: '99.5%', target: '99%' },
        },
        // ... 19 more compliance metrics with full definitions
      ],
    },
  ],
};
