/**
 * COLLECTIONS-RETAIL ERD DEFINITIONS
 * 
 * Logical and Physical ERD definitions for collections and recovery
 * Sources: Collections platform, Dialer systems, Payment arrangements, Recovery vendors
 */

// LOGICAL ERD - Business Model
export const collectionsRetailLogicalERD = {
  entities: [
    {
      name: 'Delinquent Account',
      type: 'core',
      description: 'Accounts in delinquency requiring collection',
      attributes: [
        { name: 'delinquent_account_id', type: 'BIGINT', isPrimaryKey: true },
        { name: 'account_id', type: 'BIGINT', isForeignKey: true },
        { name: 'customer_id', type: 'BIGINT', isForeignKey: true },
        { name: 'product_type', type: 'STRING', description: 'Loan|Credit Card|Deposit|Other' },
        { name: 'delinquency_status', type: 'STRING', description: '30 DPD|60 DPD|90 DPD|120+ DPD|Charged Off' },
        { name: 'days_past_due', type: 'INTEGER', description: 'Number of days past due' },
        { name: 'total_amount_due', type: 'DECIMAL(18,2)', description: 'Total outstanding amount' },
        { name: 'past_due_amount', type: 'DECIMAL(18,2)', description: 'Amount overdue' },
        { name: 'principal_past_due', type: 'DECIMAL(18,2)' },
        { name: 'interest_past_due', type: 'DECIMAL(18,2)' },
        { name: 'fees_past_due', type: 'DECIMAL(18,2)' },
        { name: 'first_delinquency_date', type: 'DATE' },
        { name: 'current_delinquency_date', type: 'DATE' },
        { name: 'collection_stage', type: 'STRING', description: 'Early|Mid|Late|Pre-Charge Off|Legal' },
        { name: 'assigned_collector_id', type: 'BIGINT', isForeignKey: true },
        { name: 'collection_strategy', type: 'STRING', description: 'Soft|Standard|Aggressive|Legal' },
      ],
    },
    {
      name: 'Collection Activity',
      type: 'event',
      description: 'Collection attempts and customer interactions',
      attributes: [
        { name: 'activity_id', type: 'BIGINT', isPrimaryKey: true },
        { name: 'delinquent_account_id', type: 'BIGINT', isForeignKey: true },
        { name: 'customer_id', type: 'BIGINT', isForeignKey: true },
        { name: 'activity_timestamp', type: 'TIMESTAMP' },
        { name: 'activity_type', type: 'STRING', description: 'Call|Email|SMS|Letter|Payment|Promise to Pay' },
        { name: 'activity_subtype', type: 'STRING', description: 'Inbound|Outbound|Automated' },
        { name: 'contact_result', type: 'STRING', description: 'Reached|Left Message|No Answer|Wrong Number|Disconnected' },
        { name: 'collector_id', type: 'BIGINT', isForeignKey: true },
        { name: 'contact_duration_seconds', type: 'INTEGER' },
        { name: 'promise_to_pay_amount', type: 'DECIMAL(18,2)' },
        { name: 'promise_to_pay_date', type: 'DATE' },
        { name: 'disposition_code', type: 'STRING', description: 'Payment Received|PTP Made|Refuse to Pay|Dispute' },
        { name: 'notes', type: 'TEXT', description: 'Collector notes' },
      ],
    },
    {
      name: 'Payment Arrangement',
      type: 'core',
      description: 'Payment plans and arrangements',
      attributes: [
        { name: 'arrangement_id', type: 'BIGINT', isPrimaryKey: true },
        { name: 'delinquent_account_id', type: 'BIGINT', isForeignKey: true },
        { name: 'customer_id', type: 'BIGINT', isForeignKey: true },
        { name: 'arrangement_type', type: 'STRING', description: 'Payment Plan|Settlement|Forbearance|Deferment' },
        { name: 'arrangement_date', type: 'DATE' },
        { name: 'arrangement_status', type: 'STRING', description: 'Active|Completed|Broken|Cancelled' },
        { name: 'total_arrangement_amount', type: 'DECIMAL(18,2)' },
        { name: 'number_of_payments', type: 'INTEGER' },
        { name: 'payment_frequency', type: 'STRING', description: 'Weekly|Bi-Weekly|Monthly' },
        { name: 'first_payment_date', type: 'DATE' },
        { name: 'final_payment_date', type: 'DATE' },
        { name: 'payment_amount', type: 'DECIMAL(18,2)', description: 'Per payment amount' },
        { name: 'payments_made', type: 'INTEGER' },
        { name: 'payments_missed', type: 'INTEGER' },
      ],
    },
    {
      name: 'Collection Payment',
      type: 'event',
      description: 'Payments received on delinquent accounts',
      attributes: [
        { name: 'payment_id', type: 'BIGINT', isPrimaryKey: true },
        { name: 'delinquent_account_id', type: 'BIGINT', isForeignKey: true },
        { name: 'arrangement_id', type: 'BIGINT', isForeignKey: true, description: 'Null if one-time payment' },
        { name: 'payment_date', type: 'DATE' },
        { name: 'payment_timestamp', type: 'TIMESTAMP' },
        { name: 'payment_amount', type: 'DECIMAL(18,2)' },
        { name: 'payment_method', type: 'STRING', description: 'ACH|Card|Check|Wire|Cash' },
        { name: 'payment_status', type: 'STRING', description: 'Posted|Pending|Returned|Failed' },
        { name: 'payment_source', type: 'STRING', description: 'Customer Portal|Phone|Mail|In-Branch' },
        { name: 'allocation_to_principal', type: 'DECIMAL(18,2)' },
        { name: 'allocation_to_interest', type: 'DECIMAL(18,2)' },
        { name: 'allocation_to_fees', type: 'DECIMAL(18,2)' },
      ],
    },
    {
      name: 'Collector',
      type: 'core',
      description: 'Collections staff',
      attributes: [
        { name: 'collector_id', type: 'BIGINT', isPrimaryKey: true },
        { name: 'employee_id', type: 'BIGINT', isForeignKey: true },
        { name: 'collector_name', type: 'STRING' },
        { name: 'collector_type', type: 'STRING', description: 'Internal|Agency|Legal' },
        { name: 'specialization', type: 'STRING', description: 'Auto Loans|Credit Cards|Personal Loans' },
        { name: 'active_flag', type: 'BOOLEAN' },
        { name: 'hire_date', type: 'DATE' },
        { name: 'license_number', type: 'STRING', description: 'Collection license' },
        { name: 'license_state', type: 'STRING' },
      ],
    },
    {
      name: 'Skip Trace',
      type: 'event',
      description: 'Skip tracing activities for locating customers',
      attributes: [
        { name: 'skip_trace_id', type: 'BIGINT', isPrimaryKey: true },
        { name: 'customer_id', type: 'BIGINT', isForeignKey: true },
        { name: 'delinquent_account_id', type: 'BIGINT', isForeignKey: true },
        { name: 'trace_date', type: 'DATE' },
        { name: 'trace_vendor', type: 'STRING', description: 'LexisNexis|TransUnion|Experian' },
        { name: 'trace_result', type: 'STRING', description: 'Located|Not Located|Deceased|Bankruptcy' },
        { name: 'new_phone_found', type: 'STRING' },
        { name: 'new_address_found', type: 'STRING' },
        { name: 'new_employer_found', type: 'STRING' },
        { name: 'trace_cost', type: 'DECIMAL(10,2)' },
      ],
    },
    {
      name: 'Legal Action',
      type: 'event',
      description: 'Legal collection actions',
      attributes: [
        { name: 'legal_action_id', type: 'BIGINT', isPrimaryKey: true },
        { name: 'delinquent_account_id', type: 'BIGINT', isForeignKey: true },
        { name: 'customer_id', type: 'BIGINT', isForeignKey: true },
        { name: 'action_type', type: 'STRING', description: 'Lawsuit|Judgment|Garnishment|Repossession|Foreclosure' },
        { name: 'action_date', type: 'DATE' },
        { name: 'action_status', type: 'STRING', description: 'Filed|In Progress|Completed|Dismissed' },
        { name: 'court_name', type: 'STRING' },
        { name: 'case_number', type: 'STRING' },
        { name: 'judgment_amount', type: 'DECIMAL(18,2)' },
        { name: 'judgment_date', type: 'DATE' },
        { name: 'attorney_name', type: 'STRING' },
        { name: 'legal_fees', type: 'DECIMAL(18,2)' },
      ],
    },
    {
      name: 'Charge-Off',
      type: 'event',
      description: 'Accounts written off as uncollectible',
      attributes: [
        { name: 'charge_off_id', type: 'BIGINT', isPrimaryKey: true },
        { name: 'account_id', type: 'BIGINT', isForeignKey: true },
        { name: 'customer_id', type: 'BIGINT', isForeignKey: true },
        { name: 'charge_off_date', type: 'DATE' },
        { name: 'charge_off_amount', type: 'DECIMAL(18,2)' },
        { name: 'principal_charged_off', type: 'DECIMAL(18,2)' },
        { name: 'interest_charged_off', type: 'DECIMAL(18,2)' },
        { name: 'fees_charged_off', type: 'DECIMAL(18,2)' },
        { name: 'days_past_due_at_charge_off', type: 'INTEGER' },
        { name: 'recovery_status', type: 'STRING', description: 'Assigned to Agency|Legal|Sold|Inactive' },
        { name: 'recovery_amount', type: 'DECIMAL(18,2)', description: 'Amount recovered post-charge off' },
      ],
    },
  ],
  
  relationships: [
    {
      from: 'Collection Activity',
      to: 'Delinquent Account',
      type: 'many-to-one',
      cardinality: 'N:1',
      foreignKey: 'delinquent_account_id',
      description: 'Activities for account',
    },
    {
      from: 'Payment Arrangement',
      to: 'Delinquent Account',
      type: 'many-to-one',
      cardinality: 'N:1',
      foreignKey: 'delinquent_account_id',
      description: 'Arrangements for account',
    },
    {
      from: 'Collection Payment',
      to: 'Delinquent Account',
      type: 'many-to-one',
      cardinality: 'N:1',
      foreignKey: 'delinquent_account_id',
      description: 'Payments on account',
    },
    {
      from: 'Collection Payment',
      to: 'Payment Arrangement',
      type: 'many-to-one',
      cardinality: 'N:1',
      foreignKey: 'arrangement_id',
      description: 'Payments per arrangement',
    },
    {
      from: 'Collection Activity',
      to: 'Collector',
      type: 'many-to-one',
      cardinality: 'N:1',
      foreignKey: 'collector_id',
      description: 'Collector performs activities',
    },
    {
      from: 'Skip Trace',
      to: 'Delinquent Account',
      type: 'many-to-one',
      cardinality: 'N:1',
      foreignKey: 'delinquent_account_id',
      description: 'Skip traces for account',
    },
    {
      from: 'Legal Action',
      to: 'Delinquent Account',
      type: 'many-to-one',
      cardinality: 'N:1',
      foreignKey: 'delinquent_account_id',
      description: 'Legal actions on account',
    },
    {
      from: 'Charge-Off',
      to: 'Delinquent Account',
      type: 'one-to-one',
      cardinality: '1:1',
      foreignKey: 'account_id',
      description: 'Charge-off of account',
    },
  ],
};

// PHYSICAL ERD - Technical Implementation
export const collectionsRetailPhysicalERD = {
  tables: [
    {
      name: 'bronze.retail_collections_delinquent_accounts',
      description: 'Delinquent account inventory',
      source: 'Collections Platform',
      updateFrequency: 'Daily',
      recordCount: '~500K active delinquent accounts',
      attributes: [
        { name: 'delinquent_account_id', type: 'BIGINT', isPrimaryKey: true },
        { name: 'account_id', type: 'BIGINT' },
        { name: 'customer_id', type: 'BIGINT' },
        { name: 'product_type', type: 'VARCHAR(50)' },
        { name: 'delinquency_status', type: 'VARCHAR(50)' },
        { name: 'days_past_due', type: 'INTEGER' },
        { name: 'total_amount_due', type: 'DECIMAL(18,2)' },
        { name: 'past_due_amount', type: 'DECIMAL(18,2)' },
        { name: 'principal_past_due', type: 'DECIMAL(18,2)' },
        { name: 'interest_past_due', type: 'DECIMAL(18,2)' },
        { name: 'fees_past_due', type: 'DECIMAL(18,2)' },
        { name: 'first_delinquency_date', type: 'DATE' },
        { name: 'current_delinquency_date', type: 'DATE' },
        { name: 'collection_stage', type: 'VARCHAR(50)' },
        { name: 'assigned_collector_id', type: 'BIGINT' },
        { name: 'collection_strategy', type: 'VARCHAR(50)' },
        { name: 'created_timestamp', type: 'TIMESTAMP' },
        { name: 'updated_timestamp', type: 'TIMESTAMP' },
        { name: 'source_system', type: 'VARCHAR(50)' },
      ],
    },
    {
      name: 'bronze.retail_collections_activities',
      description: 'Collection contact and activity logs',
      source: 'Dialer System / Collections Platform',
      updateFrequency: 'Real-time',
      recordCount: '~50M activities/year',
      attributes: [
        { name: 'activity_id', type: 'BIGINT', isPrimaryKey: true },
        { name: 'delinquent_account_id', type: 'BIGINT' },
        { name: 'customer_id', type: 'BIGINT' },
        { name: 'activity_timestamp', type: 'TIMESTAMP' },
        { name: 'activity_type', type: 'VARCHAR(50)' },
        { name: 'activity_subtype', type: 'VARCHAR(50)' },
        { name: 'contact_result', type: 'VARCHAR(100)' },
        { name: 'collector_id', type: 'BIGINT' },
        { name: 'contact_duration_seconds', type: 'INTEGER' },
        { name: 'promise_to_pay_amount', type: 'DECIMAL(18,2)' },
        { name: 'promise_to_pay_date', type: 'DATE' },
        { name: 'disposition_code', type: 'VARCHAR(100)' },
        { name: 'notes', type: 'TEXT' },
        { name: 'created_timestamp', type: 'TIMESTAMP' },
        { name: 'source_system', type: 'VARCHAR(50)' },
      ],
    },
    {
      name: 'bronze.retail_collections_payment_arrangements',
      description: 'Payment plan and settlement data',
      source: 'Collections Platform',
      updateFrequency: 'Real-time',
      recordCount: '~200K arrangements/year',
      attributes: [
        { name: 'arrangement_id', type: 'BIGINT', isPrimaryKey: true },
        { name: 'delinquent_account_id', type: 'BIGINT' },
        { name: 'customer_id', type: 'BIGINT' },
        { name: 'arrangement_type', type: 'VARCHAR(50)' },
        { name: 'arrangement_date', type: 'DATE' },
        { name: 'arrangement_status', type: 'VARCHAR(50)' },
        { name: 'total_arrangement_amount', type: 'DECIMAL(18,2)' },
        { name: 'number_of_payments', type: 'INTEGER' },
        { name: 'payment_frequency', type: 'VARCHAR(50)' },
        { name: 'first_payment_date', type: 'DATE' },
        { name: 'final_payment_date', type: 'DATE' },
        { name: 'payment_amount', type: 'DECIMAL(18,2)' },
        { name: 'payments_made', type: 'INTEGER' },
        { name: 'payments_missed', type: 'INTEGER' },
        { name: 'created_timestamp', type: 'TIMESTAMP' },
        { name: 'updated_timestamp', type: 'TIMESTAMP' },
        { name: 'source_system', type: 'VARCHAR(50)' },
      ],
    },
    {
      name: 'bronze.retail_collections_payments',
      description: 'Payments received on delinquent accounts',
      source: 'Payment Processing System',
      updateFrequency: 'Real-time',
      recordCount: '~1M payments/year',
      attributes: [
        { name: 'payment_id', type: 'BIGINT', isPrimaryKey: true },
        { name: 'delinquent_account_id', type: 'BIGINT' },
        { name: 'arrangement_id', type: 'BIGINT' },
        { name: 'payment_date', type: 'DATE' },
        { name: 'payment_timestamp', type: 'TIMESTAMP' },
        { name: 'payment_amount', type: 'DECIMAL(18,2)' },
        { name: 'payment_method', type: 'VARCHAR(50)' },
        { name: 'payment_status', type: 'VARCHAR(50)' },
        { name: 'payment_source', type: 'VARCHAR(50)' },
        { name: 'allocation_to_principal', type: 'DECIMAL(18,2)' },
        { name: 'allocation_to_interest', type: 'DECIMAL(18,2)' },
        { name: 'allocation_to_fees', type: 'DECIMAL(18,2)' },
        { name: 'created_timestamp', type: 'TIMESTAMP' },
        { name: 'source_system', type: 'VARCHAR(50)' },
      ],
    },
    {
      name: 'bronze.retail_collections_collectors',
      description: 'Collections staff data',
      source: 'HR System / Collections Platform',
      updateFrequency: 'Daily',
      recordCount: '~2,500 collectors',
      attributes: [
        { name: 'collector_id', type: 'BIGINT', isPrimaryKey: true },
        { name: 'employee_id', type: 'BIGINT' },
        { name: 'collector_name', type: 'VARCHAR(200)' },
        { name: 'collector_type', type: 'VARCHAR(50)' },
        { name: 'specialization', type: 'VARCHAR(100)' },
        { name: 'active_flag', type: 'BOOLEAN' },
        { name: 'hire_date', type: 'DATE' },
        { name: 'license_number', type: 'VARCHAR(50)' },
        { name: 'license_state', type: 'VARCHAR(2)' },
        { name: 'created_timestamp', type: 'TIMESTAMP' },
        { name: 'updated_timestamp', type: 'TIMESTAMP' },
        { name: 'source_system', type: 'VARCHAR(50)' },
      ],
    },
    {
      name: 'bronze.retail_collections_skip_traces',
      description: 'Skip tracing activity data',
      source: 'Skip Trace Vendors',
      updateFrequency: 'Daily',
      recordCount: '~100K traces/year',
      attributes: [
        { name: 'skip_trace_id', type: 'BIGINT', isPrimaryKey: true },
        { name: 'customer_id', type: 'BIGINT' },
        { name: 'delinquent_account_id', type: 'BIGINT' },
        { name: 'trace_date', type: 'DATE' },
        { name: 'trace_vendor', type: 'VARCHAR(100)' },
        { name: 'trace_result', type: 'VARCHAR(100)' },
        { name: 'new_phone_found', type: 'VARCHAR(20)' },
        { name: 'new_address_found', type: 'TEXT' },
        { name: 'new_employer_found', type: 'VARCHAR(200)' },
        { name: 'trace_cost', type: 'DECIMAL(10,2)' },
        { name: 'created_timestamp', type: 'TIMESTAMP' },
        { name: 'source_system', type: 'VARCHAR(50)' },
      ],
    },
    {
      name: 'bronze.retail_collections_legal_actions',
      description: 'Legal collection actions',
      source: 'Legal Management System',
      updateFrequency: 'Daily',
      recordCount: '~50K legal actions',
      attributes: [
        { name: 'legal_action_id', type: 'BIGINT', isPrimaryKey: true },
        { name: 'delinquent_account_id', type: 'BIGINT' },
        { name: 'customer_id', type: 'BIGINT' },
        { name: 'action_type', type: 'VARCHAR(50)' },
        { name: 'action_date', type: 'DATE' },
        { name: 'action_status', type: 'VARCHAR(50)' },
        { name: 'court_name', type: 'VARCHAR(200)' },
        { name: 'case_number', type: 'VARCHAR(50)' },
        { name: 'judgment_amount', type: 'DECIMAL(18,2)' },
        { name: 'judgment_date', type: 'DATE' },
        { name: 'attorney_name', type: 'VARCHAR(200)' },
        { name: 'legal_fees', type: 'DECIMAL(18,2)' },
        { name: 'created_timestamp', type: 'TIMESTAMP' },
        { name: 'updated_timestamp', type: 'TIMESTAMP' },
        { name: 'source_system', type: 'VARCHAR(50)' },
      ],
    },
    {
      name: 'bronze.retail_collections_charge_offs',
      description: 'Charged-off accounts data',
      source: 'Core Banking System',
      updateFrequency: 'Daily',
      recordCount: '~100K charge-offs/year',
      attributes: [
        { name: 'charge_off_id', type: 'BIGINT', isPrimaryKey: true },
        { name: 'account_id', type: 'BIGINT' },
        { name: 'customer_id', type: 'BIGINT' },
        { name: 'charge_off_date', type: 'DATE' },
        { name: 'charge_off_amount', type: 'DECIMAL(18,2)' },
        { name: 'principal_charged_off', type: 'DECIMAL(18,2)' },
        { name: 'interest_charged_off', type: 'DECIMAL(18,2)' },
        { name: 'fees_charged_off', type: 'DECIMAL(18,2)' },
        { name: 'days_past_due_at_charge_off', type: 'INTEGER' },
        { name: 'recovery_status', type: 'VARCHAR(50)' },
        { name: 'recovery_amount', type: 'DECIMAL(18,2)' },
        { name: 'created_timestamp', type: 'TIMESTAMP' },
        { name: 'updated_timestamp', type: 'TIMESTAMP' },
        { name: 'source_system', type: 'VARCHAR(50)' },
      ],
    },
  ],
  
  relationships: [
    {
      from: 'bronze.retail_collections_activities',
      to: 'bronze.retail_collections_delinquent_accounts',
      type: 'many-to-one',
      cardinality: 'N:1',
      foreignKey: 'delinquent_account_id',
      description: 'Activities for account',
    },
    {
      from: 'bronze.retail_collections_payment_arrangements',
      to: 'bronze.retail_collections_delinquent_accounts',
      type: 'many-to-one',
      cardinality: 'N:1',
      foreignKey: 'delinquent_account_id',
      description: 'Arrangements for account',
    },
    {
      from: 'bronze.retail_collections_payments',
      to: 'bronze.retail_collections_delinquent_accounts',
      type: 'many-to-one',
      cardinality: 'N:1',
      foreignKey: 'delinquent_account_id',
      description: 'Payments on account',
    },
    {
      from: 'bronze.retail_collections_payments',
      to: 'bronze.retail_collections_payment_arrangements',
      type: 'many-to-one',
      cardinality: 'N:1',
      foreignKey: 'arrangement_id',
      description: 'Payments per arrangement',
    },
    {
      from: 'bronze.retail_collections_activities',
      to: 'bronze.retail_collections_collectors',
      type: 'many-to-one',
      cardinality: 'N:1',
      foreignKey: 'collector_id',
      description: 'Collector performs activities',
    },
  ],
};

// Export default for easy import
export default {
  collectionsRetailLogicalERD,
  collectionsRetailPhysicalERD,
};
