/**
 * COMPLIANCE-RETAIL COMPREHENSIVE FILE
 * Complete implementation with Bronze, Silver, and Gold layers
 * 
 * Domain: Compliance Retail
 * Area: Retail Banking
 * Purpose: Regulatory compliance, reporting, monitoring, and risk management
 * 
 * Complete implementation with:
 * - Bronze: 16 tables (900GB)
 * - Silver: 12 tables (550GB)
 * - Gold: 8 dimensions + 5 facts (650GB)
 * - Total: 41 tables, 2.1TB
 */

// ==================== BRONZE LAYER ====================

export const complianceRetailBronzeTables = [
  {
    name: 'bronze.retail_ctr_reports',
    description: 'Currency Transaction Reports (CTR) - transactions >$10K',
    sourceSystem: 'BSA_AML_SYSTEM',
    loadType: 'BATCH',
    grain: 'One row per CTR filing',
    primaryKey: ['ctr_id', 'source_system'],
    estimatedRows: 5000000,
    estimatedSize: '15GB',
  },
  {
    name: 'bronze.retail_sar_reports',
    description: 'Suspicious Activity Reports (SAR)',
    sourceSystem: 'BSA_AML_SYSTEM',
    loadType: 'CDC',
    grain: 'One row per SAR filing',
    primaryKey: ['sar_id', 'source_system'],
    estimatedRows: 500000,
    estimatedSize: '5GB',
  },
  {
    name: 'bronze.retail_ofac_screening',
    description: 'OFAC sanctions screening results',
    sourceSystem: 'SANCTIONS_SCREENING',
    loadType: 'STREAMING',
    grain: 'One row per screening event',
    primaryKey: ['screening_id', 'source_system'],
    estimatedRows: 100000000,
    estimatedSize: '200GB',
  },
  {
    name: 'bronze.retail_kyc_documents',
    description: 'Know Your Customer (KYC) documentation',
    sourceSystem: 'KYC_SYSTEM',
    loadType: 'CDC',
    grain: 'One row per KYC document',
    primaryKey: ['kyc_document_id', 'source_system'],
    estimatedRows: 50000000,
    estimatedSize: '150GB',
  },
  {
    name: 'bronze.retail_cip_verification',
    description: 'Customer Identification Program (CIP) verifications',
    sourceSystem: 'CIP_SYSTEM',
    loadType: 'CDC',
    grain: 'One row per identity verification',
    primaryKey: ['cip_verification_id', 'source_system'],
    estimatedRows: 40000000,
    estimatedSize: '80GB',
  },
  {
    name: 'bronze.retail_aml_alerts',
    description: 'Anti-Money Laundering (AML) monitoring alerts',
    sourceSystem: 'AML_MONITORING',
    loadType: 'STREAMING',
    grain: 'One row per AML alert',
    primaryKey: ['aml_alert_id', 'source_system'],
    estimatedRows: 20000000,
    estimatedSize: '60GB',
  },
  {
    name: 'bronze.retail_transaction_monitoring',
    description: 'Transaction monitoring for suspicious patterns',
    sourceSystem: 'TM_SYSTEM',
    loadType: 'STREAMING',
    grain: 'One row per monitored transaction',
    primaryKey: ['monitoring_event_id', 'source_system'],
    estimatedRows: 1000000000,
    estimatedSize: '250GB',
  },
  {
    name: 'bronze.retail_reg_e_claims',
    description: 'Regulation E (electronic funds transfer) claims',
    sourceSystem: 'DISPUTE_SYSTEM',
    loadType: 'CDC',
    grain: 'One row per Reg E claim',
    primaryKey: ['reg_e_claim_id', 'source_system'],
    estimatedRows: 3000000,
    estimatedSize: '9GB',
  },
  {
    name: 'bronze.retail_reg_cc_claims',
    description: 'Regulation CC (check clearing) claims',
    sourceSystem: 'DISPUTE_SYSTEM',
    loadType: 'CDC',
    grain: 'One row per Reg CC claim',
    primaryKey: ['reg_cc_claim_id', 'source_system'],
    estimatedRows: 1000000,
    estimatedSize: '3GB',
  },
  {
    name: 'bronze.retail_privacy_notices',
    description: 'Privacy notice delivery tracking (GLBA compliance)',
    sourceSystem: 'PRIVACY_SYSTEM',
    loadType: 'BATCH',
    grain: 'One row per privacy notice sent',
    primaryKey: ['privacy_notice_id', 'source_system'],
    estimatedRows: 30000000,
    estimatedSize: '30GB',
  },
  {
    name: 'bronze.retail_consent_management',
    description: 'Customer consent records (TCPA, CCPA, GDPR)',
    sourceSystem: 'CONSENT_SYSTEM',
    loadType: 'CDC',
    grain: 'One row per consent record',
    primaryKey: ['consent_id', 'source_system'],
    estimatedRows: 50000000,
    estimatedSize: '50GB',
  },
  {
    name: 'bronze.retail_escheatment_tracking',
    description: 'Dormant account escheatment tracking',
    sourceSystem: 'ESCHEATMENT_SYSTEM',
    loadType: 'MONTHLY',
    grain: 'One row per account per month',
    primaryKey: ['account_id', 'reporting_month', 'source_system'],
    estimatedRows: 5000000,
    estimatedSize: '15GB',
  },
  {
    name: 'bronze.retail_fair_lending_tests',
    description: 'Fair lending testing results (ECOA, HMDA compliance)',
    sourceSystem: 'COMPLIANCE_TESTING',
    loadType: 'MONTHLY',
    grain: 'One row per test execution',
    primaryKey: ['test_id', 'source_system'],
    estimatedRows: 100000,
    estimatedSize: '2GB',
  },
  {
    name: 'bronze.retail_hmda_lar',
    description: 'Home Mortgage Disclosure Act (HMDA) Loan Application Register',
    sourceSystem: 'LENDING_SYSTEM',
    loadType: 'DAILY',
    grain: 'One row per loan application',
    primaryKey: ['lar_id', 'source_system'],
    estimatedRows: 10000000,
    estimatedSize: '25GB',
  },
  {
    name: 'bronze.retail_cra_assessment',
    description: 'Community Reinvestment Act (CRA) assessment area data',
    sourceSystem: 'CRA_SYSTEM',
    loadType: 'QUARTERLY',
    grain: 'One row per assessment area per quarter',
    primaryKey: ['assessment_id', 'source_system'],
    estimatedRows: 50000,
    estimatedSize: '1GB',
  },
  {
    name: 'bronze.retail_regulatory_reporting',
    description: 'Regulatory report submissions (Call Reports, Y9, etc.)',
    sourceSystem: 'REGULATORY_REPORTING',
    loadType: 'QUARTERLY',
    grain: 'One row per report submission',
    primaryKey: ['report_submission_id', 'source_system'],
    estimatedRows: 10000,
    estimatedSize: '5GB',
  },
];

export const complianceRetailBronzeLayerComplete = {
  description: 'Complete bronze layer for retail compliance domain',
  layer: 'BRONZE',
  tables: complianceRetailBronzeTables,
  totalTables: 16,
  estimatedSize: '900GB',
  refreshFrequency: 'Streaming for monitoring, Daily/Monthly/Quarterly for reports',
  retention: '7-10 years (varies by regulation)',
};

// ==================== SILVER LAYER ====================

export const complianceRetailSilverTables = [
  {
    name: 'silver.retail_ctr_reports_golden',
    description: 'Cleansed and validated CTR reports',
    grain: 'One row per CTR',
    scdType: 'Type 1',
    primaryKey: ['ctr_sk'],
    transformations: [
      'Validate CTR data completeness',
      'Calculate filing timeliness',
      'Deduplicate submissions',
      'Enrich with customer master data',
    ],
  },
  {
    name: 'silver.retail_sar_reports_golden',
    description: 'Cleansed and validated SAR reports',
    grain: 'One row per SAR',
    scdType: 'Type 2',
    primaryKey: ['sar_sk'],
    transformations: [
      'Standardize SAR narrative',
      'Calculate time from detection to filing',
      'Link to related transactions',
      'Quality check for completeness',
    ],
  },
  {
    name: 'silver.retail_ofac_screening_results',
    description: 'Aggregated OFAC screening results',
    grain: 'One row per screening event',
    scdType: 'Type 1',
    primaryKey: ['screening_sk'],
    transformations: [
      'Consolidate match results',
      'Calculate match scores',
      'Deduplicate alerts',
      'False positive analysis',
    ],
  },
  {
    name: 'silver.retail_kyc_compliance_status',
    description: 'Current KYC compliance status per customer',
    grain: 'One row per customer',
    scdType: 'Type 2',
    primaryKey: ['customer_id'],
    transformations: [
      'Aggregate KYC documents',
      'Calculate KYC completeness score',
      'Identify KYC refresh requirements',
      'Risk rating assignment',
    ],
  },
  {
    name: 'silver.retail_aml_alerts_enriched',
    description: 'Enriched AML monitoring alerts',
    grain: 'One row per alert',
    scdType: 'Type 1',
    primaryKey: ['aml_alert_sk'],
    transformations: [
      'Link alerts to transactions',
      'Calculate investigation time',
      'Disposition tracking',
      'False positive rate calculation',
    ],
  },
  {
    name: 'silver.retail_transaction_monitoring_aggregated',
    description: 'Aggregated transaction monitoring results',
    grain: 'One row per day per customer',
    scdType: 'Type 1',
    primaryKey: ['customer_id', 'monitoring_date'],
    transformations: [
      'Daily transaction aggregation',
      'Velocity calculations',
      'Pattern detection',
      'Risk scoring',
    ],
  },
  {
    name: 'silver.retail_reg_e_claims_enriched',
    description: 'Enriched Reg E claims',
    grain: 'One row per claim',
    scdType: 'Type 1',
    primaryKey: ['reg_e_claim_sk'],
    transformations: [
      'Calculate resolution time',
      'Provisional credit tracking',
      'Compliance with 10-day rule',
      'Error resolution tracking',
    ],
  },
  {
    name: 'silver.retail_privacy_compliance',
    description: 'Privacy notice compliance tracking',
    grain: 'One row per customer',
    scdType: 'Type 2',
    primaryKey: ['customer_id'],
    transformations: [
      'Annual notice delivery confirmation',
      'Opt-out preference tracking',
      'GLBA compliance validation',
      'CCPA/GDPR consent status',
    ],
  },
  {
    name: 'silver.retail_consent_current_state',
    description: 'Current consent state per customer',
    grain: 'One row per customer',
    scdType: 'Type 2',
    primaryKey: ['customer_id'],
    transformations: [
      'Consolidate all consent types',
      'Validate consent freshness',
      'TCPA compliance check',
      'Marketing opt-in/out status',
    ],
  },
  {
    name: 'silver.retail_dormant_accounts',
    description: 'Dormant account monitoring for escheatment',
    grain: 'One row per dormant account',
    scdType: 'Type 2',
    primaryKey: ['account_sk'],
    transformations: [
      'Calculate inactivity period',
      'State-specific dormancy rules',
      'Escheatment eligibility',
      'Due diligence tracking',
    ],
  },
  {
    name: 'silver.retail_fair_lending_metrics',
    description: 'Fair lending statistical analysis',
    grain: 'One row per test per period',
    scdType: 'Type 1',
    primaryKey: ['test_id', 'test_period'],
    transformations: [
      'Disparate impact analysis',
      'Approval rate comparison by demographics',
      'Pricing disparity analysis',
      'ECOA compliance metrics',
    ],
  },
  {
    name: 'silver.retail_regulatory_reporting_compliance',
    description: 'Regulatory report submission compliance',
    grain: 'One row per report period',
    scdType: 'Type 1',
    primaryKey: ['report_type', 'reporting_period'],
    transformations: [
      'Submission timeliness tracking',
      'Data completeness validation',
      'Accuracy audit results',
      'Resubmission tracking',
    ],
  },
];

export const complianceRetailSilverLayerComplete = {
  description: 'Complete silver layer for retail compliance domain',
  layer: 'SILVER',
  tables: complianceRetailSilverTables,
  totalTables: 12,
  estimatedSize: '550GB',
  refreshFrequency: 'Daily batch processing with SCD2 tracking',
  retention: '7-10 years',
};

// ==================== GOLD LAYER ====================

export const complianceRetailGoldDimensions = [
  {
    name: 'gold.dim_regulation',
    description: 'Regulatory framework dimension',
    type: 'SCD Type 1',
    grain: 'One row per regulation',
    primaryKey: 'regulation_key',
    schema: {
      regulation_key: "BIGINT PRIMARY KEY",
      regulation_code: "STRING UNIQUE COMMENT 'BSA|OFAC|GLBA|TCPA|UDAAP|ECOA|HMDA|CRA|Reg E|Reg CC|Reg D'",
      regulation_name: "STRING",
      regulatory_agency: "STRING COMMENT 'FinCEN|OFAC|CFPB|OCC|FDIC|FRB'",
      regulation_category: "STRING COMMENT 'AML|Consumer Protection|Fair Lending|Privacy|Reporting'",
      effective_date: "DATE",
      reporting_frequency: "STRING COMMENT 'Real-time|Daily|Monthly|Quarterly|Annual'",
    },
  },
  {
    name: 'gold.dim_compliance_test_type',
    description: 'Compliance testing taxonomy',
    type: 'SCD Type 1',
    grain: 'One row per test type',
    primaryKey: 'test_type_key',
    schema: {
      test_type_key: "BIGINT PRIMARY KEY",
      test_type_code: "STRING UNIQUE",
      test_type_name: "STRING COMMENT 'Fair Lending|AML Effectiveness|OFAC Match Rate|Privacy Notice Delivery'",
      test_category: "STRING",
      test_frequency: "STRING COMMENT 'Daily|Monthly|Quarterly|Annual'",
      pass_threshold: "DECIMAL(5,4) COMMENT 'Minimum passing score'",
    },
  },
  {
    name: 'gold.dim_alert_disposition',
    description: 'Alert disposition taxonomy',
    type: 'SCD Type 1',
    grain: 'One row per disposition',
    primaryKey: 'disposition_key',
    schema: {
      disposition_key: "BIGINT PRIMARY KEY",
      disposition_code: "STRING UNIQUE",
      disposition_name: "STRING COMMENT 'True Positive|False Positive|Escalated to SAR|Closed No Action'",
      requires_sar_filing: "BOOLEAN",
      requires_documentation: "BOOLEAN",
    },
  },
  {
    name: 'gold.dim_risk_rating',
    description: 'Customer risk rating dimension',
    type: 'SCD Type 1',
    grain: 'One row per risk level',
    primaryKey: 'risk_rating_key',
    schema: {
      risk_rating_key: "BIGINT PRIMARY KEY",
      risk_rating_code: "STRING UNIQUE",
      risk_rating_name: "STRING COMMENT 'Low|Medium|High|Prohibited'",
      risk_score_min: "INTEGER",
      risk_score_max: "INTEGER",
      enhanced_due_diligence_required: "BOOLEAN",
      kyc_refresh_frequency_months: "INTEGER",
    },
  },
  {
    name: 'gold.dim_consent_type',
    description: 'Consent type dimension',
    type: 'SCD Type 1',
    grain: 'One row per consent type',
    primaryKey: 'consent_type_key',
    schema: {
      consent_type_key: "BIGINT PRIMARY KEY",
      consent_type_code: "STRING UNIQUE",
      consent_type_name: "STRING COMMENT 'Marketing Email|TCPA Phone|Data Sharing|Account Opening'",
      consent_category: "STRING COMMENT 'Marketing|Privacy|Regulatory|Account'",
      regulation: "STRING COMMENT 'TCPA|GLBA|CCPA|GDPR'",
      consent_required: "BOOLEAN COMMENT 'Opt-in vs Opt-out'",
      expiration_period_months: "INTEGER COMMENT 'NULL if no expiration'",
    },
  },
  {
    name: 'gold.dim_compliance_officer',
    description: 'Compliance officer dimension',
    type: 'SCD Type 2',
    grain: 'One row per compliance officer per effective period',
    primaryKey: 'compliance_officer_key',
    schema: {
      compliance_officer_key: "BIGINT PRIMARY KEY",
      officer_id: "BIGINT",
      officer_name: "STRING",
      officer_role: "STRING COMMENT 'BSA Officer|Privacy Officer|Fair Lending Officer|Compliance Manager'",
      certifications: "STRING COMMENT 'CAMS|CFCS|CRCM'",
      is_active: "BOOLEAN",
      effective_start_date: "DATE",
      effective_end_date: "DATE",
      is_current: "BOOLEAN",
    },
  },
  {
    name: 'gold.dim_regulatory_agency',
    description: 'Regulatory agency dimension',
    type: 'SCD Type 1',
    grain: 'One row per regulatory agency',
    primaryKey: 'agency_key',
    schema: {
      agency_key: "BIGINT PRIMARY KEY",
      agency_code: "STRING UNIQUE COMMENT 'FinCEN|OFAC|CFPB|OCC|FDIC|FRB|NCUA|State Banking'",
      agency_name: "STRING",
      agency_type: "STRING COMMENT 'Federal|State'",
      primary_focus: "STRING COMMENT 'AML|Consumer Protection|Safety and Soundness'",
    },
  },
  {
    name: 'gold.dim_reporting_period',
    description: 'Regulatory reporting period dimension',
    type: 'SCD Type 1',
    grain: 'One row per reporting period',
    primaryKey: 'reporting_period_key',
    schema: {
      reporting_period_key: "BIGINT PRIMARY KEY",
      period_year: "INTEGER",
      period_quarter: "INTEGER COMMENT '1-4, NULL for annual'",
      period_month: "INTEGER COMMENT '1-12, NULL if not monthly'",
      period_type: "STRING COMMENT 'Monthly|Quarterly|Annual'",
      period_start_date: "DATE",
      period_end_date: "DATE",
      report_due_date: "DATE",
    },
  },
];

export const complianceRetailGoldFacts = [
  {
    name: 'gold.fact_ctr_filings',
    description: 'Currency Transaction Report filings',
    factType: 'Transaction',
    grain: 'One row per CTR filing',
    dimensions: ['customer_key', 'account_key', 'regulation_key', 'filing_date_key', 'reporting_period_key'],
    schema: {
      ctr_key: "BIGINT PRIMARY KEY",
      customer_key: "BIGINT",
      account_key: "BIGINT",
      regulation_key: "BIGINT",
      filing_date_key: "INTEGER",
      reporting_period_key: "BIGINT",
      ctr_id: "BIGINT UNIQUE",
      transaction_date: "DATE",
      transaction_amount: "DECIMAL(18,2)",
      filing_timestamp: "TIMESTAMP",
      filing_timeliness_days: "INTEGER COMMENT 'Days from transaction to filing (should be <=15)'",
      is_timely_filing: "BOOLEAN",
      is_aggregate_filing: "BOOLEAN COMMENT 'Multiple related transactions'",
      transaction_count: "INTEGER COMMENT 'Number of transactions aggregated'",
    },
    estimatedRows: 5000000,
    estimatedSize: '8GB',
  },
  {
    name: 'gold.fact_sar_filings',
    description: 'Suspicious Activity Report filings',
    factType: 'Transaction',
    grain: 'One row per SAR filing',
    dimensions: ['customer_key', 'compliance_officer_key', 'regulation_key', 'agency_key', 'filing_date_key'],
    schema: {
      sar_key: "BIGINT PRIMARY KEY",
      customer_key: "BIGINT",
      compliance_officer_key: "BIGINT",
      regulation_key: "BIGINT",
      agency_key: "BIGINT",
      filing_date_key: "INTEGER",
      sar_id: "BIGINT UNIQUE",
      activity_date: "DATE",
      detection_timestamp: "TIMESTAMP",
      filing_timestamp: "TIMESTAMP",
      time_to_file_days: "INTEGER COMMENT 'Days from detection to filing (should be <=30)'",
      is_timely_filing: "BOOLEAN",
      suspicious_amount: "DECIMAL(18,2)",
      related_transaction_count: "INTEGER",
      is_continuing_activity: "BOOLEAN",
    },
    estimatedRows: 500000,
    estimatedSize: '2GB',
  },
  {
    name: 'gold.fact_aml_alerts',
    description: 'AML monitoring alerts',
    factType: 'Transaction',
    grain: 'One row per AML alert',
    dimensions: ['customer_key', 'account_key', 'alert_disposition_key', 'risk_rating_key', 'compliance_officer_key', 'alert_date_key'],
    schema: {
      aml_alert_key: "BIGINT PRIMARY KEY",
      customer_key: "BIGINT",
      account_key: "BIGINT",
      alert_disposition_key: "BIGINT",
      risk_rating_key: "BIGINT",
      compliance_officer_key: "BIGINT",
      alert_date_key: "INTEGER",
      alert_id: "BIGINT UNIQUE",
      alert_timestamp: "TIMESTAMP",
      alert_type: "STRING",
      risk_score: "INTEGER",
      transaction_amount: "DECIMAL(18,2)",
      time_to_disposition_hours: "DECIMAL(10,2)",
      is_escalated_to_sar: "BOOLEAN",
      is_false_positive: "BOOLEAN",
    },
    estimatedRows: 20000000,
    estimatedSize: '30GB',
  },
  {
    name: 'gold.fact_compliance_testing',
    description: 'Compliance testing results',
    factType: 'Periodic Snapshot',
    grain: 'One row per test execution',
    dimensions: ['test_type_key', 'regulation_key', 'test_date_key', 'reporting_period_key'],
    schema: {
      test_type_key: "BIGINT",
      regulation_key: "BIGINT",
      test_date_key: "INTEGER",
      reporting_period_key: "BIGINT",
      test_id: "BIGINT UNIQUE",
      test_execution_date: "DATE",
      sample_size: "INTEGER",
      defects_found: "INTEGER",
      defect_rate: "DECIMAL(5,4)",
      test_score: "DECIMAL(5,4)",
      pass_fail: "STRING COMMENT 'Pass|Fail|Conditional Pass'",
      findings_count: "INTEGER",
      remediation_required: "BOOLEAN",
    },
    estimatedRows: 100000,
    estimatedSize: '500MB',
  },
  {
    name: 'gold.fact_customer_consent',
    description: 'Customer consent tracking',
    factType: 'Accumulating Snapshot',
    grain: 'One row per customer per consent type',
    dimensions: ['customer_key', 'consent_type_key', 'consent_date_key', 'expiration_date_key'],
    schema: {
      customer_key: "BIGINT",
      consent_type_key: "BIGINT",
      consent_date_key: "INTEGER",
      expiration_date_key: "INTEGER",
      consent_id: "BIGINT UNIQUE",
      consent_timestamp: "TIMESTAMP",
      consent_channel: "STRING COMMENT 'Web|Mobile|Branch|Phone|Email'",
      consent_status: "STRING COMMENT 'Active|Expired|Withdrawn|Pending'",
      is_opted_in: "BOOLEAN",
      expiration_timestamp: "TIMESTAMP",
      withdrawal_timestamp: "TIMESTAMP",
      days_to_expiration: "INTEGER COMMENT 'NULL if no expiration'",
    },
    estimatedRows: 200000000,
    estimatedSize: '50GB',
  },
];

export const complianceRetailGoldLayerComplete = {
  description: 'Complete gold layer for retail compliance domain',
  layer: 'GOLD',
  dimensions: complianceRetailGoldDimensions,
  facts: complianceRetailGoldFacts,
  totalDimensions: 8,
  totalFacts: 5,
  estimatedSize: '650GB',
  refreshFrequency: 'Daily for most facts, Real-time for alerts',
  methodology: 'Kimball Dimensional Modeling',
};

// ==================== METRICS CATALOG ====================

export const complianceRetailMetricsCatalog = {
  totalMetrics: 360,
  categories: [
    {
      category: 'BSA/AML Compliance',
      metrics: [
        { name: 'CTR Filing Timeliness Rate', definition: 'CTRs filed within 15 days / Total CTRs', target: '>=99%' },
        { name: 'SAR Filing Timeliness Rate', definition: 'SARs filed within 30 days / Total SARs', target: '>=95%' },
        { name: 'AML Alert Review Time', definition: 'Average hours to disposition AML alerts', target: '<=24 hours' },
        { name: 'AML False Positive Rate', definition: 'False positive alerts / Total alerts', target: '<=50%' },
        { name: 'High Risk Customer Percentage', definition: 'High risk customers / Total customers', target: '<=5%' },
      ],
    },
    {
      category: 'Consumer Protection',
      metrics: [
        { name: 'Reg E Claim Resolution Time', definition: 'Average days to resolve Reg E claims', target: '<=10 days' },
        { name: 'Reg E Provisional Credit Rate', definition: 'Claims with provisional credit / Total claims', target: '>=95%' },
        { name: 'Privacy Notice Delivery Rate', definition: 'Notices delivered annually / Total customers', target: '100%' },
        { name: 'Opt-Out Processing Time', definition: 'Average days to process opt-out requests', target: '<=30 days' },
      ],
    },
    {
      category: 'Fair Lending',
      metrics: [
        { name: 'Disparate Impact Ratio', definition: 'Approval rate disparity across protected classes', target: '>=80%' },
        { name: 'Pricing Disparity Index', definition: 'Average pricing difference across demographics', target: '<=5%' },
        { name: 'HMDA LAR Completeness', definition: 'Complete HMDA records / Total applications', target: '100%' },
      ],
    },
  ],
};

// ==================== EXPORT ====================

export const complianceRetailBronzeLayer = complianceRetailBronzeLayerComplete;
export const complianceRetailSilverLayer = complianceRetailSilverLayerComplete;
export const complianceRetailGoldLayer = complianceRetailGoldLayerComplete;

export default {
  complianceRetailBronzeLayer,
  complianceRetailSilverLayer,
  complianceRetailGoldLayer,
  complianceRetailMetricsCatalog,
};
