/**
 * CRM ANALYTICS - PRODUCTION TABLE STRUCTURES
 * 
 * Comprehensive table inventory for CRM Analytics domain
 * SALESFORCE-centric data warehouse for sales operations
 * Organized by layer: Bronze (raw), Silver (conformed), Gold (dimensional)
 */

// ============================================================
// BRONZE LAYER - Raw, immutable data from SALESFORCE
// ============================================================
export const crmAnalyticsBronzeTables = {
  "bronze_salesforce_account": {
    name: "bronze_salesforce_account",
    description: "Raw SALESFORCE account data",
    grain: "One row per account",
    columns: [
      { name: "account_id", type: "String", pk: true },
      { name: "account_name", type: "String" },
      { name: "account_number", type: "String" },
      { name: "industry", type: "String" },
      { name: "annual_revenue", type: "Decimal" },
      { name: "number_of_employees", type: "Integer" },
      { name: "billing_street", type: "String" },
      { name: "billing_city", type: "String" },
      { name: "billing_state", type: "String" },
      { name: "billing_country", type: "String" },
      { name: "account_owner_id", type: "String" },
      { name: "created_date", type: "Timestamp" },
      { name: "last_modified_date", type: "Timestamp" },
      { name: "account_status", type: "String" },
    ],
  },
  "bronze_salesforce_contact": {
    name: "bronze_salesforce_contact",
    description: "Raw SALESFORCE contact data",
    grain: "One row per contact",
    columns: [
      { name: "contact_id", type: "String", pk: true },
      { name: "account_id", type: "String", fk: true },
      { name: "first_name", type: "String" },
      { name: "last_name", type: "String" },
      { name: "title", type: "String" },
      { name: "department", type: "String" },
      { name: "email", type: "String" },
      { name: "phone", type: "String" },
      { name: "mobile", type: "String" },
      { name: "reports_to_id", type: "String" },
      { name: "created_date", type: "Timestamp" },
      { name: "last_modified_date", type: "Timestamp" },
      { name: "contact_status", type: "String" },
      { name: "last_activity_date", type: "Date" },
    ],
  },
  "bronze_salesforce_opportunity": {
    name: "bronze_salesforce_opportunity",
    description: "Raw SALESFORCE opportunity (deal) data",
    grain: "One row per opportunity",
    columns: [
      { name: "opportunity_id", type: "String", pk: true },
      { name: "account_id", type: "String", fk: true },
      { name: "opportunity_name", type: "String" },
      { name: "opportunity_type", type: "String" },
      { name: "amount", type: "Decimal" },
      { name: "close_date", type: "Date" },
      { name: "stage_name", type: "String" },
      { name: "probability_percent", type: "Decimal" },
      { name: "owner_id", type: "String" },
      { name: "created_date", type: "Timestamp" },
      { name: "last_modified_date", type: "Timestamp" },
      { name: "is_closed", type: "Integer" },
      { name: "is_won", type: "Integer" },
      { name: "primary_contact_id", type: "String" },
    ],
  },
  "bronze_salesforce_opportunity_line_item": {
    name: "bronze_salesforce_opportunity_line_item",
    description: "Raw SALESFORCE opportunity product line items",
    grain: "One row per product line item in opportunity",
    columns: [
      { name: "opportunity_line_item_id", type: "String", pk: true },
      { name: "opportunity_id", type: "String", fk: true },
      { name: "product_id", type: "String" },
      { name: "product_code", type: "String" },
      { name: "product_name", type: "String" },
      { name: "quantity", type: "Decimal" },
      { name: "unit_price", type: "Decimal" },
      { name: "total_price", type: "Decimal" },
      { name: "discount", type: "Decimal" },
      { name: "created_date", type: "Timestamp" },
    ],
  },
  "bronze_salesforce_task": {
    name: "bronze_salesforce_task",
    description: "Raw SALESFORCE task/activity records",
    grain: "One row per task",
    columns: [
      { name: "task_id", type: "String", pk: true },
      { name: "account_id", type: "String" },
      { name: "contact_id", type: "String" },
      { name: "opportunity_id", type: "String" },
      { name: "owner_id", type: "String" },
      { name: "task_type", type: "String" },
      { name: "subject", type: "String" },
      { name: "description", type: "String" },
      { name: "activity_date", type: "Date" },
      { name: "priority", type: "String" },
      { name: "status", type: "String" },
      { name: "completion_date", type: "Timestamp" },
      { name: "created_date", type: "Timestamp" },
      { name: "duration_minutes", type: "Integer" },
    ],
  },
  "bronze_salesforce_event": {
    name: "bronze_salesforce_event",
    description: "Raw SALESFORCE event and meeting data",
    grain: "One row per event",
    columns: [
      { name: "event_id", type: "String", pk: true },
      { name: "account_id", type: "String" },
      { name: "contact_id", type: "String" },
      { name: "opportunity_id", type: "String" },
      { name: "owner_id", type: "String" },
      { name: "event_type", type: "String" },
      { name: "subject", type: "String" },
      { name: "location", type: "String" },
      { name: "start_datetime", type: "Timestamp" },
      { name: "end_datetime", type: "Timestamp" },
      { name: "duration_minutes", type: "Integer" },
      { name: "created_date", type: "Timestamp" },
      { name: "attendees_count", type: "Integer" },
    ],
  },
  "bronze_salesforce_user": {
    name: "bronze_salesforce_user",
    description: "Raw SALESFORCE user (sales rep) data",
    grain: "One row per user",
    columns: [
      { name: "user_id", type: "String", pk: true },
      { name: "username", type: "String" },
      { name: "first_name", type: "String" },
      { name: "last_name", type: "String" },
      { name: "email", type: "String" },
      { name: "phone", type: "String" },
      { name: "title", type: "String" },
      { name: "department", type: "String" },
      { name: "manager_id", type: "String" },
      { name: "is_active", type: "Integer" },
      { name: "created_date", type: "Timestamp" },
    ],
  },
  "bronze_salesforce_forecast": {
    name: "bronze_salesforce_forecast",
    description: "Raw SALESFORCE sales forecast data",
    grain: "One row per user per period per category",
    columns: [
      { name: "forecast_id", type: "String", pk: true },
      { name: "forecast_period", type: "String" },
      { name: "user_id", type: "String" },
      { name: "product_family", type: "String" },
      { name: "forecast_category", type: "String" },
      { name: "quota_amount", type: "Decimal" },
      { name: "pipeline_amount", type: "Decimal" },
      { name: "forecast_amount", type: "Decimal" },
      { name: "created_date", type: "Timestamp" },
    ],
  },
  "bronze_salesforce_lead": {
    name: "bronze_salesforce_lead",
    description: "Raw SALESFORCE lead data",
    grain: "One row per lead",
    columns: [
      { name: "lead_id", type: "String", pk: true },
      { name: "first_name", type: "String" },
      { name: "last_name", type: "String" },
      { name: "company", type: "String" },
      { name: "email", type: "String" },
      { name: "phone", type: "String" },
      { name: "industry", type: "String" },
      { name: "annual_revenue", type: "Decimal" },
      { name: "lead_status", type: "String" },
      { name: "lead_source", type: "String" },
      { name: "owner_id", type: "String" },
      { name: "converted_account_id", type: "String" },
      { name: "converted_contact_id", type: "String" },
      { name: "created_date", type: "Timestamp" },
      { name: "converted_date", type: "Date" },
    ],
  },
};

// ============================================================
// SILVER LAYER - Conformed, deduplicated, business-ready
// ============================================================
export const crmAnalyticsSilverTables = {
  "silver_account": {
    name: "silver_account",
    description: "Conformed account master data",
    grain: "One row per account",
    columns: [
      { name: "account_id", type: "String", pk: true },
      { name: "account_name", type: "String" },
      { name: "account_code", type: "String" },
      { name: "industry_id", type: "String" },
      { name: "industry_name", type: "String" },
      { name: "annual_revenue_amount", type: "Decimal" },
      { name: "employee_count", type: "Integer" },
      { name: "account_owner_id", type: "String" },
      { name: "account_owner_name", type: "String" },
      { name: "account_status", type: "String" },
      { name: "country_code", type: "String" },
      { name: "created_date", type: "Timestamp" },
      { name: "updated_date", type: "Timestamp" },
    ],
  },
  "silver_contact": {
    name: "silver_contact",
    description: "Conformed contact master data",
    grain: "One row per contact",
    columns: [
      { name: "contact_id", type: "String", pk: true },
      { name: "account_id", type: "String", fk: true },
      { name: "contact_name", type: "String" },
      { name: "job_title", type: "String" },
      { name: "department_code", type: "String" },
      { name: "department_name", type: "String" },
      { name: "email_address", type: "String" },
      { name: "phone_number", type: "String" },
      { name: "mobile_number", type: "String" },
      { name: "is_decision_maker", type: "Integer" },
      { name: "decision_maker_level", type: "String" },
      { name: "contact_status", type: "String" },
      { name: "last_activity_date", type: "Date" },
      { name: "created_date", type: "Timestamp" },
    ],
  },
  "silver_opportunity": {
    name: "silver_opportunity",
    description: "Conformed opportunity fact data",
    grain: "One row per opportunity",
    columns: [
      { name: "opportunity_id", type: "String", pk: true },
      { name: "account_id", type: "String", fk: true },
      { name: "opportunity_name", type: "String" },
      { name: "opportunity_type", type: "String" },
      { name: "total_amount", type: "Decimal" },
      { name: "close_date", type: "Date" },
      { name: "stage_code", type: "String" },
      { name: "stage_name", type: "String" },
      { name: "probability_percent", type: "Decimal" },
      { name: "expected_revenue", type: "Decimal" },
      { name: "owner_id", type: "String" },
      { name: "owner_name", type: "String" },
      { name: "is_closed", type: "Integer" },
      { name: "is_won", type: "Integer" },
      { name: "created_date", type: "Timestamp" },
      { name: "days_in_stage", type: "Integer" },
    ],
  },
  "silver_sales_activity": {
    name: "silver_sales_activity",
    description: "Conformed sales activities (tasks and events)",
    grain: "One row per activity",
    columns: [
      { name: "activity_id", type: "String", pk: true },
      { name: "account_id", type: "String", fk: true },
      { name: "contact_id", type: "String" },
      { name: "opportunity_id", type: "String" },
      { name: "owner_id", type: "String" },
      { name: "activity_type", type: "String" },
      { name: "activity_date", type: "Date" },
      { name: "activity_subject", type: "String" },
      { name: "activity_outcome", type: "String" },
      { name: "duration_minutes", type: "Integer" },
      { name: "completion_date", type: "Timestamp" },
      { name: "created_date", type: "Timestamp" },
    ],
  },
  "silver_sales_rep": {
    name: "silver_sales_rep",
    description: "Conformed sales representative dimension",
    grain: "One row per sales rep",
    columns: [
      { name: "rep_id", type: "String", pk: true },
      { name: "rep_name", type: "String" },
      { name: "rep_email", type: "String" },
      { name: "rep_phone", type: "String" },
      { name: "rep_title", type: "String" },
      { name: "territory_code", type: "String" },
      { name: "territory_name", type: "String" },
      { name: "manager_id", type: "String" },
      { name: "manager_name", type: "String" },
      { name: "is_active", type: "Integer" },
      { name: "created_date", type: "Timestamp" },
    ],
  },
  "silver_sales_forecast": {
    name: "silver_sales_forecast",
    description: "Conformed sales forecast data",
    grain: "One row per rep per period",
    columns: [
      { name: "forecast_id", type: "String", pk: true },
      { name: "forecast_period_id", type: "String" },
      { name: "rep_id", type: "String", fk: true },
      { name: "quota_amount", type: "Decimal" },
      { name: "pipeline_amount", type: "Decimal" },
      { name: "forecast_amount", type: "Decimal" },
      { name: "actual_amount", type: "Decimal" },
      { name: "attainment_percent", type: "Decimal" },
      { name: "created_date", type: "Timestamp" },
    ],
  },
};

// ============================================================
// GOLD LAYER - Dimensional model for analytics and BI
// ============================================================
export const crmAnalyticsGoldTables = {
  // FACT TABLES
  "fact_sales_opportunity": {
    name: "fact_sales_opportunity",
    type: "Fact",
    description: "Sales opportunity fact table",
    grain: "One row per opportunity snapshot",
    columns: [
      { name: "opportunity_key", type: "String", pk: true },
      { name: "account_key", type: "String", fk: true },
      { name: "rep_key", type: "String", fk: true },
      { name: "stage_key", type: "String", fk: true },
      { name: "product_key", type: "String", fk: true },
      { name: "date_key", type: "String", fk: true },
      { name: "opportunity_amount", type: "Decimal" },
      { name: "probability_percent", type: "Decimal" },
      { name: "expected_revenue", type: "Decimal" },
      { name: "days_in_stage", type: "Integer" },
      { name: "is_closed", type: "Integer" },
      { name: "is_won", type: "Integer" },
    ],
  },
  "fact_sales_activity_daily": {
    name: "fact_sales_activity_daily",
    type: "Fact",
    description: "Sales activities aggregated daily",
    grain: "One row per day per rep",
    columns: [
      { name: "date_key", type: "String", pk: true },
      { name: "rep_key", type: "String", pk: true },
      { name: "account_count", type: "Integer" },
      { name: "opportunity_count", type: "Integer" },
      { name: "activity_count", type: "Integer" },
      { name: "calls_count", type: "Integer" },
      { name: "meetings_count", type: "Integer" },
      { name: "emails_count", type: "Integer" },
      { name: "tasks_count", type: "Integer" },
      { name: "completed_activities", type: "Integer" },
    ],
  },
  "fact_sales_pipeline_daily": {
    name: "fact_sales_pipeline_daily",
    type: "Fact",
    description: "Daily sales pipeline metrics",
    grain: "One row per day per rep",
    columns: [
      { name: "date_key", type: "String", pk: true },
      { name: "rep_key", type: "String", pk: true },
      { name: "total_pipeline_value", type: "Decimal" },
      { name: "prospect_stage_value", type: "Decimal" },
      { name: "qualification_stage_value", type: "Decimal" },
      { name: "proposal_stage_value", type: "Decimal" },
      { name: "negotiation_stage_value", type: "Decimal" },
      { name: "closed_won_value", type: "Decimal" },
      { name: "closed_lost_value", type: "Decimal" },
      { name: "pipeline_count", type: "Integer" },
      { name: "win_rate_percent", type: "Decimal" },
    ],
  },
  "fact_account_health_daily": {
    name: "fact_account_health_daily",
    type: "Fact",
    description: "Account health scorecard daily",
    grain: "One row per day per account",
    columns: [
      { name: "date_key", type: "String", pk: true },
      { name: "account_key", type: "String", pk: true },
      { name: "rep_key", type: "String", fk: true },
      { name: "health_score", type: "Decimal" },
      { name: "engagement_score", type: "Decimal" },
      { name: "opportunity_score", type: "Decimal" },
      { name: "risk_score", type: "Decimal" },
      { name: "days_since_last_activity", type: "Integer" },
      { name: "opportunity_count", type: "Integer" },
      { name: "opportunity_value", type: "Decimal" },
    ],
  },
  "fact_contact_engagement_daily": {
    name: "fact_contact_engagement_daily",
    type: "Fact",
    description: "Contact engagement metrics daily",
    grain: "One row per day per contact",
    columns: [
      { name: "date_key", type: "String", pk: true },
      { name: "contact_key", type: "String", pk: true },
      { name: "account_key", type: "String", fk: true },
      { name: "activity_count", type: "Integer" },
      { name: "last_activity_date", type: "Date" },
      { name: "engagement_level", type: "String" },
      { name: "opportunity_count", type: "Integer" },
      { name: "is_decision_maker", type: "Integer" },
    ],
  },

  // DIMENSION TABLES
  "dim_account": {
    name: "dim_account",
    type: "Dimension",
    description: "Account dimension",
    columns: [
      { name: "account_key", type: "String", pk: true },
      { name: "account_id", type: "String" },
      { name: "account_name", type: "String" },
      { name: "industry", type: "String" },
      { name: "annual_revenue", type: "Decimal" },
      { name: "employee_count", type: "Integer" },
      { name: "account_status", type: "String" },
      { name: "country", type: "String" },
      { name: "region", type: "String" },
    ],
  },
  "dim_contact": {
    name: "dim_contact",
    type: "Dimension",
    description: "Contact dimension",
    columns: [
      { name: "contact_key", type: "String", pk: true },
      { name: "contact_id", type: "String" },
      { name: "account_key", type: "String", fk: true },
      { name: "contact_name", type: "String" },
      { name: "job_title", type: "String" },
      { name: "department", type: "String" },
      { name: "is_decision_maker", type: "Integer" },
      { name: "decision_level", type: "String" },
    ],
  },
  "dim_sales_stage": {
    name: "dim_sales_stage",
    type: "Dimension",
    description: "Sales pipeline stage dimension",
    columns: [
      { name: "stage_key", type: "String", pk: true },
      { name: "stage_code", type: "String" },
      { name: "stage_name", type: "String" },
      { name: "stage_order", type: "Integer" },
      { name: "is_closed", type: "Integer" },
    ],
  },
  "dim_sales_rep": {
    name: "dim_sales_rep",
    type: "Dimension",
    description: "Sales representative dimension",
    columns: [
      { name: "rep_key", type: "String", pk: true },
      { name: "rep_id", type: "String" },
      { name: "rep_name", type: "String" },
      { name: "territory", type: "String" },
      { name: "manager_name", type: "String" },
      { name: "is_active", type: "Integer" },
    ],
  },
  "dim_product": {
    name: "dim_product",
    type: "Dimension",
    description: "Product dimension",
    columns: [
      { name: "product_key", type: "String", pk: true },
      { name: "product_id", type: "String" },
      { name: "product_code", type: "String" },
      { name: "product_name", type: "String" },
      { name: "product_line", type: "String" },
      { name: "product_category", type: "String" },
    ],
  },
  "dim_date": {
    name: "dim_date",
    type: "Dimension",
    description: "Date dimension",
    columns: [
      { name: "date_key", type: "String", pk: true },
      { name: "date", type: "Date" },
      { name: "year", type: "Integer" },
      { name: "quarter", type: "Integer" },
      { name: "month", type: "Integer" },
      { name: "week", type: "Integer" },
      { name: "day_of_week", type: "Integer" },
    ],
  },
};

export const crmAnalyticsTablesCatalog = {
  bronze: Object.keys(crmAnalyticsBronzeTables),
  silver: Object.keys(crmAnalyticsSilverTables),
  gold: {
    facts: [
      "fact_sales_opportunity",
      "fact_sales_activity_daily",
      "fact_sales_pipeline_daily",
      "fact_account_health_daily",
      "fact_contact_engagement_daily",
    ],
    dimensions: [
      "dim_account",
      "dim_contact",
      "dim_sales_stage",
      "dim_sales_rep",
      "dim_product",
      "dim_date",
    ],
  },
};
