/**
 * CUSTOMER-RETAIL METRICS CATALOG
 * 200 comprehensive metrics across 5 categories
 */

export const customerRetailMetricsCatalog = {
  description: 'Comprehensive retail customer metrics catalog',
  totalMetrics: 200,
  
  categories: [
    // Category 1: Acquisition Metrics (40 metrics)
    {
      name: 'Acquisition Metrics',
      description: 'New customer acquisition, onboarding, and source tracking',
      totalMetrics: 40,
      
      metrics: [
        // Original 20 metrics (CRM-ACQ-001 to CRM-ACQ-020)
        {
          id: 'CRM-ACQ-001',
          name: 'New Customer Acquisitions',
          description: 'Number of new retail customers acquired in period',
          category: 'Acquisition',
          type: 'kpi',
          subcategory: 'Volume',
          formula: "COUNT(DISTINCT customer_id WHERE customer_since_date BETWEEN period_start AND period_end)",
          unit: 'count',
          aggregation: 'SUM',
          silverTable: 'silver.retail_customer_lifecycle_events_golden',
          goldTable: 'gold.fact_customer_acquisition',
          silverTable: 'silver.retail_customer_lifecycle_events_golden',
          goldTable: 'gold.fact_customer_acquisition',
        },
        {
          id: 'CRM-ACQ-002',
          name: 'Customer Acquisition Cost (CAC)',
          description: 'Average cost to acquire a new customer',
          category: 'Acquisition',
          type: 'kpi',
          subcategory: 'Efficiency',
          formula: "SUM(marketing_spend + sales_cost + onboarding_cost) / COUNT(DISTINCT new_customers)",
          unit: 'USD',
          aggregation: 'AVG',
          silverTable: 'silver.retail_customer_lifecycle_events_golden',
          goldTable: 'gold.fact_customer_acquisition',
        },
        {
          id: 'CRM-ACQ-003',
          name: 'Digital Channel Acquisition Rate',
          description: 'Percentage of new customers acquired through digital channels',
          category: 'Acquisition',
          type: 'kpi',
          subcategory: 'Channel',
          formula: "(digital_acquisitions / total_acquisitions) * 100",
          unit: 'percentage',
          aggregation: 'CALCULATED',
          silverTable: 'silver.retail_customer_lifecycle_events_golden',
          goldTable: 'gold.fact_customer_acquisition',
        },
        {
          id: 'CRM-ACQ-004',
          name: 'Branch Acquisition Rate',
          description: 'Percentage of new customers acquired through branch channel',
          category: 'Acquisition',
          type: 'kpi',
          subcategory: 'Channel',
          silverTable: 'silver.retail_customer_lifecycle_events_golden',
          goldTable: 'gold.fact_customer_acquisition',
        },
        {
          id: 'CRM-ACQ-005',
          name: 'Referral Acquisition Rate',
          description: 'Percentage of new customers from referrals',
          category: 'Acquisition',
          type: 'kpi',
          subcategory: 'Source',
          silverTable: 'silver.retail_customer_lifecycle_events_golden',
          goldTable: 'gold.fact_customer_acquisition',
        },
        {
          id: 'CRM-ACQ-006',
          name: 'Time to First Transaction',
          description: 'Average days from account opening to first transaction',
          category: 'Acquisition',
          type: 'kpi',
          subcategory: 'Activation',
          silverTable: 'silver.retail_customer_lifecycle_events_golden',
          goldTable: 'gold.fact_customer_acquisition',
        },
        {
          id: 'CRM-ACQ-007',
          name: 'Product Adoption Rate at Onboarding',
          description: 'Average number of products opened by new customers',
          category: 'Acquisition',
          type: 'kpi',
          subcategory: 'Product Penetration',
          silverTable: 'silver.retail_customer_lifecycle_events_golden',
          goldTable: 'gold.fact_customer_acquisition',
        },
        {
          id: 'CRM-ACQ-008',
          name: 'New Customer Funding Rate',
          description: 'Percentage of new accounts funded within 30 days',
          category: 'Acquisition',
          type: 'kpi',
          subcategory: 'Activation',
          silverTable: 'silver.retail_customer_lifecycle_events_golden',
          goldTable: 'gold.fact_customer_acquisition',
        },
        {
          id: 'CRM-ACQ-009',
          name: 'Average Initial Deposit',
          description: 'Mean initial deposit amount for new customers',
          category: 'Acquisition',
          type: 'kpi',
          subcategory: 'Value',
          silverTable: 'silver.retail_customer_lifecycle_events_golden',
          goldTable: 'gold.fact_customer_acquisition',
        },
        {
          id: 'CRM-ACQ-010',
          name: 'Marketing Campaign Conversion Rate',
          description: 'Percentage of campaign leads converting to customers',
          category: 'Acquisition',
          type: 'kpi',
          subcategory: 'Marketing',
          silverTable: 'silver.retail_customer_lifecycle_events_golden',
          goldTable: 'gold.fact_customer_acquisition',
        },
        {
          id: 'CRM-ACQ-011',
          name: 'Acquisition by Age Segment',
          description: 'Distribution of new customers by age group',
          category: 'Acquisition',
          type: 'kpi',
          subcategory: 'Demographics',
          silverTable: 'silver.retail_customer_lifecycle_events_golden',
          goldTable: 'gold.fact_customer_acquisition',
        },
        {
          id: 'CRM-ACQ-012',
          name: 'Student Account Acquisition',
          description: 'Number of new student checking accounts opened',
          category: 'Acquisition',
          type: 'kpi',
          subcategory: 'Segment',
          silverTable: 'silver.retail_customer_lifecycle_events_golden',
          goldTable: 'gold.fact_customer_acquisition',
        },
        {
          id: 'CRM-ACQ-013',
          name: 'Young Professional Acquisition',
          description: 'New customers aged 22-35 with professional employment',
          category: 'Acquisition',
          type: 'kpi',
          subcategory: 'Segment',
          silverTable: 'silver.retail_customer_lifecycle_events_golden',
          goldTable: 'gold.fact_customer_acquisition',
        },
        {
          id: 'CRM-ACQ-014',
          name: 'Joint Account Acquisition Rate',
          description: 'Percentage of new accounts opened jointly',
          category: 'Acquisition',
          type: 'kpi',
          subcategory: 'Account Type',
          silverTable: 'silver.retail_customer_lifecycle_events_golden',
          goldTable: 'gold.fact_customer_acquisition',
        },
        {
          id: 'CRM-ACQ-015',
          name: 'Direct Mail Response Rate',
          description: 'Conversion from direct mail campaigns',
          category: 'Acquisition',
          type: 'kpi',
          subcategory: 'Marketing',
          silverTable: 'silver.retail_customer_lifecycle_events_golden',
          goldTable: 'gold.fact_customer_acquisition',
        },
        {
          id: 'CRM-ACQ-016',
          name: 'Online Application Completion Rate',
          description: 'Applications started vs. completed online',
          category: 'Acquisition',
          type: 'kpi',
          subcategory: 'Digital',
          silverTable: 'silver.retail_customer_lifecycle_events_golden',
          goldTable: 'gold.fact_customer_acquisition',
        },
        {
          id: 'CRM-ACQ-017',
          name: 'Mobile Account Opening Rate',
          description: 'Accounts opened via mobile app',
          category: 'Acquisition',
          type: 'kpi',
          subcategory: 'Mobile',
          silverTable: 'silver.retail_customer_lifecycle_events_golden',
          goldTable: 'gold.fact_customer_acquisition',
        },
        {
          id: 'CRM-ACQ-018',
          name: 'Acquisition Cost by Channel',
          description: 'CAC segmented by acquisition channel',
          category: 'Acquisition',
          type: 'kpi',
          subcategory: 'Channel',
          silverTable: 'silver.retail_customer_lifecycle_events_golden',
          goldTable: 'gold.fact_customer_acquisition',
        },
        {
          id: 'CRM-ACQ-019',
          name: 'Partner Channel Acquisition',
          description: 'New customers from partner referrals',
          category: 'Acquisition',
          type: 'kpi',
          subcategory: 'Source',
          silverTable: 'silver.retail_customer_lifecycle_events_golden',
          goldTable: 'gold.fact_customer_acquisition',
        },
        {
          id: 'CRM-ACQ-020',
          name: 'Acquisition Payback Period',
          description: 'Months to recover customer acquisition cost',
          category: 'Acquisition',
          type: 'kpi',
          subcategory: 'ROI',
          silverTable: 'silver.retail_customer_lifecycle_events_golden',
          goldTable: 'gold.fact_customer_acquisition',
        },
        
        // NEW: Additional 20 metrics (CRM-ACQ-021 to CRM-ACQ-040)
        {
          id: 'CRM-ACQ-021',
          name: 'Social Media Acquisition Rate',
          description: 'Customers acquired via social media campaigns',
          category: 'Acquisition',
          type: 'kpi',
          subcategory: 'Digital',
          silverTable: 'silver.retail_customer_lifecycle_events_golden',
          goldTable: 'gold.fact_customer_acquisition',
        },
        {
          id: 'CRM-ACQ-022',
          name: 'Email Campaign Conversion',
          description: 'Email recipients converting to customers',
          category: 'Acquisition',
          type: 'kpi',
          subcategory: 'Marketing',
          silverTable: 'silver.retail_customer_lifecycle_events_golden',
          goldTable: 'gold.fact_customer_acquisition',
        },
        {
          id: 'CRM-ACQ-023',
          name: 'SEO/Organic Acquisition',
          description: 'Customers from organic search',
          category: 'Acquisition',
          type: 'kpi',
          subcategory: 'Digital',
          silverTable: 'silver.retail_customer_lifecycle_events_golden',
          goldTable: 'gold.fact_customer_acquisition',
        },
        {
          id: 'CRM-ACQ-024',
          name: 'Paid Search Acquisition Cost',
          description: 'CAC for paid search campaigns',
          category: 'Acquisition',
          type: 'kpi',
          subcategory: 'Digital',
          silverTable: 'silver.retail_customer_lifecycle_events_golden',
          goldTable: 'gold.fact_customer_acquisition',
        },
        {
          id: 'CRM-ACQ-025',
          name: 'Application Approval Rate',
          description: 'Percentage of applications approved',
          category: 'Acquisition',
          type: 'kpi',
          subcategory: 'Credit',
          silverTable: 'silver.retail_customer_lifecycle_events_golden',
          goldTable: 'gold.fact_customer_acquisition',
        },
        {
          id: 'CRM-ACQ-026',
          name: 'Cross-Border Customer Acquisition',
          description: 'New customers with international banking needs',
          category: 'Acquisition',
          type: 'kpi',
          subcategory: 'Segment',
          silverTable: 'silver.retail_customer_lifecycle_events_golden',
          goldTable: 'gold.fact_customer_acquisition',
        },
        {
          id: 'CRM-ACQ-027',
          name: 'Business Account Conversion',
          description: 'Small business accounts opened by retail customers',
          category: 'Acquisition',
          type: 'kpi',
          subcategory: 'Product',
          silverTable: 'silver.retail_customer_lifecycle_events_golden',
          goldTable: 'gold.fact_customer_acquisition',
        },
        {
          id: 'CRM-ACQ-028',
          name: 'Family Package Acquisition',
          description: 'Multi-member household accounts opened',
          category: 'Acquisition',
          type: 'kpi',
          subcategory: 'Household',
          silverTable: 'silver.retail_customer_lifecycle_events_golden',
          goldTable: 'gold.fact_customer_acquisition',
        },
        {
          id: 'CRM-ACQ-029',
          name: 'Premium Account Acquisition',
          description: 'High-tier account openings',
          category: 'Acquisition',
          type: 'kpi',
          subcategory: 'Segment',
          silverTable: 'silver.retail_customer_lifecycle_events_golden',
          goldTable: 'gold.fact_customer_acquisition',
        },
        {
          id: 'CRM-ACQ-030',
          name: 'Account Opening Abandonment Rate',
          description: 'Applications started but not completed',
          category: 'Acquisition',
          type: 'kpi',
          subcategory: 'Friction',
          silverTable: 'silver.retail_customer_lifecycle_events_golden',
          goldTable: 'gold.fact_customer_acquisition',
        },
        {
          id: 'CRM-ACQ-031',
          name: 'Welcome Offer Redemption',
          description: 'New customers redeeming sign-up bonuses',
          category: 'Acquisition',
          type: 'kpi',
          subcategory: 'Promotion',
          silverTable: 'silver.retail_customer_lifecycle_events_golden',
          goldTable: 'gold.fact_customer_acquisition',
        },
        {
          id: 'CRM-ACQ-032',
          name: 'ATM-to-Account Acquisition',
          description: 'Customers acquired via ATM interactions',
          category: 'Acquisition',
          type: 'kpi',
          subcategory: 'Channel',
          silverTable: 'silver.retail_customer_lifecycle_events_golden',
          goldTable: 'gold.fact_customer_acquisition',
        },
        {
          id: 'CRM-ACQ-033',
          name: 'Call Center Acquisition',
          description: 'Accounts opened via phone banking',
          category: 'Acquisition',
          type: 'kpi',
          subcategory: 'Channel',
          silverTable: 'silver.retail_customer_lifecycle_events_golden',
          goldTable: 'gold.fact_customer_acquisition',
        },
        {
          id: 'CRM-ACQ-034',
          name: 'Acquisition Velocity',
          description: 'Rate of change in new customer growth',
          category: 'Acquisition',
          type: 'kpi',
          subcategory: 'Trend',
          silverTable: 'silver.retail_customer_lifecycle_events_golden',
          goldTable: 'gold.fact_customer_acquisition',
        },
        {
          id: 'CRM-ACQ-035',
          name: 'Geographic Market Penetration',
          description: 'New customers by geographic market',
          category: 'Acquisition',
          type: 'kpi',
          subcategory: 'Geography',
          silverTable: 'silver.retail_customer_lifecycle_events_golden',
          goldTable: 'gold.fact_customer_acquisition',
        },
        {
          id: 'CRM-ACQ-036',
          name: 'Seasonal Acquisition Index',
          description: 'Acquisition trends by season/quarter',
          category: 'Acquisition',
          type: 'kpi',
          subcategory: 'Seasonality',
          silverTable: 'silver.retail_customer_lifecycle_events_golden',
          goldTable: 'gold.fact_customer_acquisition',
        },
        {
          id: 'CRM-ACQ-037',
          name: 'Acquisition Quality Score',
          description: 'Composite score of customer value at acquisition',
          category: 'Acquisition',
          type: 'kpi',
          subcategory: 'Quality',
          silverTable: 'silver.retail_customer_lifecycle_events_golden',
          goldTable: 'gold.fact_customer_acquisition',
        },
        {
          id: 'CRM-ACQ-038',
          name: 'First-Time Bankers Acquisition',
          description: 'Customers with no prior banking relationships',
          category: 'Acquisition',
          type: 'kpi',
          subcategory: 'Segment',
          silverTable: 'silver.retail_customer_lifecycle_events_golden',
          goldTable: 'gold.fact_customer_acquisition',
        },
        {
          id: 'CRM-ACQ-039',
          name: 'Competitive Switch Rate',
          description: 'Customers switching from competitors',
          category: 'Acquisition',
          type: 'kpi',
          subcategory: 'Source',
          silverTable: 'silver.retail_customer_lifecycle_events_golden',
          goldTable: 'gold.fact_customer_acquisition',
        },
        {
          id: 'CRM-ACQ-040',
          name: 'KYC Completion Time',
          description: 'Average time to complete KYC verification',
          category: 'Acquisition',
          type: 'kpi',
          subcategory: 'Onboarding',
          silverTable: 'silver.retail_customer_lifecycle_events_golden',
          goldTable: 'gold.fact_customer_acquisition',
        },
      ],
    },

    // Category 2: Retention Metrics (40 metrics) - keeping original structure and adding 20 more
    {
      name: 'Retention Metrics',
      description: 'Customer retention, churn, and loyalty tracking',
      totalMetrics: 40,
      
      metrics: [
        {
          id: 'CRM-RET-001',
          name: 'Customer Retention Rate',
          description: 'Percentage of customers retained over period',
          category: 'Retention',
          type: 'kpi',
          subcategory: 'Core',
          formula: "(customers_end - new_customers) / customers_start * 100",
          unit: 'percentage',
          aggregation: 'CALCULATED',
          silverTable: 'silver.retail_customer_lifecycle_events_golden',
          goldTable: 'gold.fact_customer_churn',
        },
        {
          id: 'CRM-RET-002',
          name: 'Customer Churn Rate',
          description: 'Percentage of customers lost in period',
          category: 'Retention',
          type: 'kpi',
          subcategory: 'Churn',
          silverTable: 'silver.retail_customer_lifecycle_events_golden',
          goldTable: 'gold.fact_customer_churn',
        },
        {
          id: 'CRM-RET-003',
          name: 'Voluntary Attrition Rate',
          description: 'Customer-initiated account closures',
          category: 'Retention',
          type: 'kpi',
          subcategory: 'Churn',
          silverTable: 'silver.retail_customer_lifecycle_events_golden',
          goldTable: 'gold.fact_customer_churn',
        },
        {
          id: 'CRM-RET-004',
          name: 'Involuntary Attrition Rate',
          description: 'Bank-initiated account closures',
          category: 'Retention',
          type: 'kpi',
          subcategory: 'Churn',
          silverTable: 'silver.retail_customer_lifecycle_events_golden',
          goldTable: 'gold.fact_customer_churn',
        },
        {
          id: 'CRM-RET-005',
          name: 'Product Churn Rate',
          description: 'Rate of individual product closures',
          category: 'Retention',
          type: 'kpi',
          subcategory: 'Product',
          silverTable: 'silver.retail_customer_lifecycle_events_golden',
          goldTable: 'gold.fact_customer_churn',
        },
        {
          id: 'CRM-RET-006',
          name: 'Account Dormancy Rate',
          description: 'Percentage of inactive accounts',
          category: 'Retention',
          type: 'kpi',
          subcategory: 'Activity',
          silverTable: 'silver.retail_customer_lifecycle_events_golden',
          goldTable: 'gold.fact_customer_churn',
        },
        {
          id: 'CRM-RET-007',
          name: 'Reactivation Rate',
          description: 'Dormant accounts returning to active status',
          category: 'Retention',
          type: 'kpi',
          subcategory: 'Win-Back',
          silverTable: 'silver.retail_customer_lifecycle_events_golden',
          goldTable: 'gold.fact_customer_churn',
        },
        {
          id: 'CRM-RET-008',
          name: 'Relationship Tenure',
          description: 'Average customer relationship duration',
          category: 'Retention',
          type: 'kpi',
          subcategory: 'Loyalty',
          silverTable: 'silver.retail_customer_lifecycle_events_golden',
          goldTable: 'gold.fact_customer_churn',
        },
        {
          id: 'CRM-RET-009',
          name: 'Customer Tenure Distribution',
          description: 'Breakdown by years of relationship',
          category: 'Retention',
          type: 'kpi',
          subcategory: 'Tenure',
          silverTable: 'silver.retail_customer_lifecycle_events_golden',
          goldTable: 'gold.fact_customer_churn',
        },
        {
          id: 'CRM-RET-010',
          name: 'First Year Retention',
          description: 'Retention within first 12 months',
          category: 'Retention',
          type: 'kpi',
          subcategory: 'Early Stage',
          silverTable: 'silver.retail_customer_lifecycle_events_golden',
          goldTable: 'gold.fact_customer_churn',
        },
        {
          id: 'CRM-RET-011',
          name: 'Multi-Product Retention',
          description: 'Retention for customers with 2+ products',
          category: 'Retention',
          type: 'kpi',
          subcategory: 'Cross-Sell',
          silverTable: 'silver.retail_customer_lifecycle_events_golden',
          goldTable: 'gold.fact_customer_churn',
        },
        {
          id: 'CRM-RET-012',
          name: 'Primary Bank Status',
          description: 'Percentage using bank as primary institution',
          category: 'Retention',
          type: 'kpi',
          subcategory: 'Wallet Share',
          silverTable: 'silver.retail_customer_lifecycle_events_golden',
          goldTable: 'gold.fact_customer_churn',
        },
        {
          id: 'CRM-RET-013',
          name: 'Churn Prediction Accuracy',
          description: 'Accuracy of churn risk model',
          category: 'Retention',
          type: 'kpi',
          subcategory: 'Prediction',
          silverTable: 'silver.retail_customer_lifecycle_events_golden',
          goldTable: 'gold.fact_customer_churn',
        },
        {
          id: 'CRM-RET-014',
          name: 'Save Rate',
          description: 'Customers retained after expressing intent to leave',
          category: 'Retention',
          type: 'kpi',
          subcategory: 'Intervention',
          silverTable: 'silver.retail_customer_lifecycle_events_golden',
          goldTable: 'gold.fact_customer_churn',
        },
        {
          id: 'CRM-RET-015',
          name: 'Loyalty Program Participation',
          description: 'Active participants in rewards program',
          category: 'Retention',
          type: 'kpi',
          subcategory: 'Loyalty',
          silverTable: 'silver.retail_customer_lifecycle_events_golden',
          goldTable: 'gold.fact_customer_churn',
        },
        {
          id: 'CRM-RET-016',
          name: 'Zero Balance Closure Rate',
          description: 'Accounts closed with zero balance',
          category: 'Retention',
          type: 'kpi',
          subcategory: 'Churn',
          silverTable: 'silver.retail_customer_lifecycle_events_golden',
          goldTable: 'gold.fact_customer_churn',
        },
        {
          id: 'CRM-RET-017',
          name: 'Competitive Defection Rate',
          description: 'Customers lost to competitors',
          category: 'Retention',
          type: 'kpi',
          subcategory: 'Competitive',
          silverTable: 'silver.retail_customer_lifecycle_events_golden',
          goldTable: 'gold.fact_customer_churn',
        },
        {
          id: 'CRM-RET-018',
          name: 'Complaint-Related Churn',
          description: 'Attrition following complaints',
          category: 'Retention',
          type: 'kpi',
          subcategory: 'Service',
          silverTable: 'silver.retail_customer_lifecycle_events_golden',
          goldTable: 'gold.fact_customer_churn',
        },
        {
          id: 'CRM-RET-019',
          name: 'Customer Attrition Risk Score',
          description: 'Predictive churn probability score',
          category: 'Retention',
          type: 'kpi',
          subcategory: 'Risk',
          silverTable: 'silver.retail_customer_lifecycle_events_golden',
          goldTable: 'gold.fact_customer_churn',
        },
        {
          id: 'CRM-RET-020',
          name: 'Retention Rate by Acquisition Channel',
          description: 'Retention segmented by original acquisition channel',
          category: 'Retention',
          type: 'kpi',
          subcategory: 'Channel',
          silverTable: 'silver.retail_customer_lifecycle_events_golden',
          goldTable: 'gold.fact_customer_churn',
        },
        
        // NEW: Additional 20 metrics (CRM-RET-021 to CRM-RET-040)
        {
          id: 'CRM-RET-021',
          name: 'Digital-Only Customer Retention',
          description: 'Retention rate for purely digital customers',
          category: 'Retention',
          type: 'kpi',
          subcategory: 'Channel',
          silverTable: 'silver.retail_customer_lifecycle_events_golden',
          goldTable: 'gold.fact_customer_churn',
        },
        {
          id: 'CRM-RET-022',
          name: 'Win-Back Campaign Success',
          description: 'Lost customers successfully reacquired',
          category: 'Retention',
          type: 'kpi',
          subcategory: 'Win-Back',
          silverTable: 'silver.retail_customer_lifecycle_events_golden',
          goldTable: 'gold.fact_customer_churn',
        },
        {
          id: 'CRM-RET-023',
          name: 'Product Downgrade Rate',
          description: 'Customers moving to lower-tier products',
          category: 'Retention',
          type: 'kpi',
          subcategory: 'Product',
          silverTable: 'silver.retail_customer_lifecycle_events_golden',
          goldTable: 'gold.fact_customer_churn',
        },
        {
          id: 'CRM-RET-024',
          name: 'Relationship Depth Score',
          description: 'Number and type of products per customer',
          category: 'Retention',
          type: 'kpi',
          subcategory: 'Cross-Sell',
          silverTable: 'silver.retail_customer_lifecycle_events_golden',
          goldTable: 'gold.fact_customer_churn',
        },
        {
          id: 'CRM-RET-025',
          name: 'Fee-Based Attrition',
          description: 'Churn related to fee increases',
          category: 'Retention',
          type: 'kpi',
          subcategory: 'Pricing',
          silverTable: 'silver.retail_customer_lifecycle_events_golden',
          goldTable: 'gold.fact_customer_churn',
        },
        {
          id: 'CRM-RET-026',
          name: 'Service Quality Retention Impact',
          description: 'Retention correlation with service scores',
          category: 'Retention',
          type: 'kpi',
          subcategory: 'Service',
          silverTable: 'silver.retail_customer_lifecycle_events_golden',
          goldTable: 'gold.fact_customer_churn',
        },
        {
          id: 'CRM-RET-027',
          name: 'Mobile App Engagement Retention',
          description: 'Retention by app usage frequency',
          category: 'Retention',
          type: 'kpi',
          subcategory: 'Digital',
          silverTable: 'silver.retail_customer_lifecycle_events_golden',
          goldTable: 'gold.fact_customer_churn',
        },
        {
          id: 'CRM-RET-028',
          name: 'Household Retention Rate',
          description: 'Retention at household level',
          category: 'Retention',
          type: 'kpi',
          subcategory: 'Household',
          silverTable: 'silver.retail_customer_lifecycle_events_golden',
          goldTable: 'gold.fact_customer_churn',
        },
        {
          id: 'CRM-RET-029',
          name: 'Geographic Retention Variation',
          description: 'Retention differences by market',
          category: 'Retention',
          type: 'kpi',
          subcategory: 'Geography',
          silverTable: 'silver.retail_customer_lifecycle_events_golden',
          goldTable: 'gold.fact_customer_churn',
        },
        {
          id: 'CRM-RET-030',
          name: 'Age Cohort Retention',
          description: 'Retention by age demographic',
          category: 'Retention',
          type: 'kpi',
          subcategory: 'Demographics',
          silverTable: 'silver.retail_customer_lifecycle_events_golden',
          goldTable: 'gold.fact_customer_churn',
        },
        {
          id: 'CRM-RET-031',
          name: 'Proactive Retention Contact Rate',
          description: 'At-risk customers contacted preventatively',
          category: 'Retention',
          type: 'kpi',
          subcategory: 'Intervention',
          silverTable: 'silver.retail_customer_lifecycle_events_golden',
          goldTable: 'gold.fact_customer_churn',
        },
        {
          id: 'CRM-RET-032',
          name: 'Student-to-Regular Account Transition',
          description: 'Student account holders converting to regular accounts',
          category: 'Retention',
          type: 'kpi',
          subcategory: 'Lifecycle',
          silverTable: 'silver.retail_customer_lifecycle_events_golden',
          goldTable: 'gold.fact_customer_churn',
        },
        {
          id: 'CRM-RET-033',
          name: 'Direct Deposit Retention Impact',
          description: 'Retention for customers with direct deposit',
          category: 'Retention',
          type: 'kpi',
          subcategory: 'Engagement',
          silverTable: 'silver.retail_customer_interactions_golden',
          goldTable: 'gold.fact_customer_interactions',
          silverTable: 'silver.retail_customer_lifecycle_events_golden',
          goldTable: 'gold.fact_customer_churn',
          silverTable: 'silver.retail_customer_interactions_golden',
          goldTable: 'gold.fact_customer_interactions',
        },
        {
          id: 'CRM-RET-034',
          name: 'Relationship Manager Retention',
          description: 'Retention for customers with dedicated RM',
          category: 'Retention',
          type: 'kpi',
          subcategory: 'Service',
          silverTable: 'silver.retail_customer_lifecycle_events_golden',
          goldTable: 'gold.fact_customer_churn',
        },
        {
          id: 'CRM-RET-035',
          name: 'Seasonal Churn Pattern',
          description: 'Attrition trends by season',
          category: 'Retention',
          type: 'kpi',
          subcategory: 'Seasonality',
          silverTable: 'silver.retail_customer_lifecycle_events_golden',
          goldTable: 'gold.fact_customer_churn',
        },
        {
          id: 'CRM-RET-036',
          name: 'Overdraft User Retention',
          description: 'Retention among frequent overdraft users',
          category: 'Retention',
          type: 'kpi',
          subcategory: 'Behavior',
          silverTable: 'silver.retail_customer_lifecycle_events_golden',
          goldTable: 'gold.fact_customer_churn',
        },
        {
          id: 'CRM-RET-037',
          name: 'Branch Closure Impact',
          description: 'Retention change after branch closures',
          category: 'Retention',
          type: 'kpi',
          subcategory: 'Network',
          silverTable: 'silver.retail_customer_lifecycle_events_golden',
          goldTable: 'gold.fact_customer_churn',
        },
        {
          id: 'CRM-RET-038',
          name: 'Loyalty Points Redemption Rate',
          description: 'Customers actively using rewards',
          category: 'Retention',
          type: 'kpi',
          subcategory: 'Loyalty',
          silverTable: 'silver.retail_customer_lifecycle_events_golden',
          goldTable: 'gold.fact_customer_churn',
        },
        {
          id: 'CRM-RET-039',
          name: 'Post-Complaint Retention',
          description: 'Retention after successful complaint resolution',
          category: 'Retention',
          type: 'kpi',
          subcategory: 'Recovery',
          silverTable: 'silver.retail_customer_lifecycle_events_golden',
          goldTable: 'gold.fact_customer_churn',
        },
        {
          id: 'CRM-RET-040',
          name: 'Economic Downturn Retention',
          description: 'Retention during economic stress periods',
          category: 'Retention',
          type: 'kpi',
          subcategory: 'Macro',
          silverTable: 'silver.retail_customer_lifecycle_events_golden',
          goldTable: 'gold.fact_customer_churn',
        },
      ],
    },

    // Category 3: Engagement Metrics (40 metrics)
    {
      name: 'Engagement Metrics',
      description: 'Customer interaction frequency, channel usage, and activity levels',
      totalMetrics: 40,
      
      metrics: [
        {
          id: 'CRM-ENG-001',
          name: 'Average Monthly Logins',
          description: 'Mean number of digital banking logins per customer',
          category: 'Engagement',
          type: 'behavioral',
          subcategory: 'Digital',
          formula: "AVG(login_count)",
          unit: 'count',
          aggregation: 'AVG',
          silverTable: 'silver.retail_customer_interactions_golden',
          goldTable: 'gold.fact_customer_interactions',
        },
        {
          id: 'CRM-ENG-002',
          name: 'Mobile App Active Users',
          description: 'Percentage of customers actively using mobile app',
          category: 'Engagement',
          type: 'behavioral',
          subcategory: 'Mobile',
          silverTable: 'silver.retail_customer_interactions_golden',
          goldTable: 'gold.fact_customer_interactions',
        },
        {
          id: 'CRM-ENG-003',
          name: 'Digital Banking Adoption',
          description: 'Customers enrolled in online/mobile banking',
          category: 'Engagement',
          type: 'behavioral',
          subcategory: 'Digital',
          silverTable: 'silver.retail_customer_interactions_golden',
          goldTable: 'gold.fact_customer_interactions',
        },
        {
          id: 'CRM-ENG-004',
          name: 'Branch Visit Frequency',
          description: 'Average branch visits per customer',
          category: 'Engagement',
          type: 'behavioral',
          subcategory: 'Branch',
          silverTable: 'silver.retail_customer_interactions_golden',
          goldTable: 'gold.fact_customer_interactions',
        },
        {
          id: 'CRM-ENG-005',
          name: 'ATM Usage Rate',
          description: 'Monthly ATM transactions per customer',
          category: 'Engagement',
          type: 'behavioral',
          subcategory: 'ATM',
          silverTable: 'silver.retail_customer_interactions_golden',
          goldTable: 'gold.fact_customer_interactions',
        },
        {
          id: 'CRM-ENG-006',
          name: 'Call Center Contact Rate',
          description: 'Customer service calls per month',
          category: 'Engagement',
          type: 'behavioral',
          subcategory: 'Service',
          silverTable: 'silver.retail_customer_interactions_golden',
          goldTable: 'gold.fact_customer_interactions',
        },
        {
          id: 'CRM-ENG-007',
          name: 'Self-Service Adoption',
          description: 'Transactions via self-service channels',
          category: 'Engagement',
          type: 'behavioral',
          subcategory: 'Digital',
          silverTable: 'silver.retail_customer_interactions_golden',
          goldTable: 'gold.fact_customer_interactions',
        },
        {
          id: 'CRM-ENG-008',
          name: 'Transaction Volume per Customer',
          description: 'Average monthly transactions',
          category: 'Engagement',
          type: 'behavioral',
          subcategory: 'Activity',
          silverTable: 'silver.retail_customer_interactions_golden',
          goldTable: 'gold.fact_customer_interactions',
        },
        {
          id: 'CRM-ENG-009',
          name: 'Bill Pay Active Users',
          description: 'Customers using online bill payment',
          category: 'Engagement',
          type: 'behavioral',
          subcategory: 'Features',
          silverTable: 'silver.retail_customer_interactions_golden',
          goldTable: 'gold.fact_customer_interactions',
        },
        {
          id: 'CRM-ENG-010',
          name: 'P2P Payment Usage',
          description: 'Customers using Zelle or similar services',
          category: 'Engagement',
          type: 'behavioral',
          subcategory: 'Payments',
          silverTable: 'silver.retail_customer_interactions_golden',
          goldTable: 'gold.fact_customer_interactions',
        },
        {
          id: 'CRM-ENG-011',
          name: 'Mobile Deposit Adoption',
          description: 'Customers using mobile check deposit',
          category: 'Engagement',
          type: 'behavioral',
          subcategory: 'Mobile',
          silverTable: 'silver.retail_customer_interactions_golden',
          goldTable: 'gold.fact_customer_interactions',
        },
        {
          id: 'CRM-ENG-012',
          name: 'Account Alert Enrollment',
          description: 'Customers with active alerts configured',
          category: 'Engagement',
          type: 'behavioral',
          subcategory: 'Features',
          silverTable: 'silver.retail_customer_interactions_golden',
          goldTable: 'gold.fact_customer_interactions',
        },
        {
          id: 'CRM-ENG-013',
          name: 'Session Duration',
          description: 'Average time spent in digital banking',
          category: 'Engagement',
          type: 'behavioral',
          subcategory: 'Digital',
          silverTable: 'silver.retail_customer_interactions_golden',
          goldTable: 'gold.fact_customer_interactions',
        },
        {
          id: 'CRM-ENG-014',
          name: 'Cross-Channel Usage',
          description: 'Customers using multiple channels',
          category: 'Engagement',
          type: 'behavioral',
          subcategory: 'Omnichannel',
          silverTable: 'silver.retail_customer_interactions_golden',
          goldTable: 'gold.fact_customer_interactions',
        },
        {
          id: 'CRM-ENG-015',
          name: 'Statement View Rate',
          description: 'E-statement access frequency',
          category: 'Engagement',
          type: 'behavioral',
          subcategory: 'Digital',
          silverTable: 'silver.retail_customer_interactions_golden',
          goldTable: 'gold.fact_customer_interactions',
        },
        {
          id: 'CRM-ENG-016',
          name: 'Financial Wellness Tool Usage',
          description: 'Engagement with PFM features',
          category: 'Engagement',
          type: 'behavioral',
          subcategory: 'Features',
          silverTable: 'silver.retail_customer_interactions_golden',
          goldTable: 'gold.fact_customer_interactions',
        },
        {
          id: 'CRM-ENG-017',
          name: 'Chat/Messaging Usage',
          description: 'Digital messaging interactions',
          category: 'Engagement',
          type: 'behavioral',
          subcategory: 'Digital',
          silverTable: 'silver.retail_customer_interactions_golden',
          goldTable: 'gold.fact_customer_interactions',
        },
        {
          id: 'CRM-ENG-018',
          name: 'Video Banking Adoption',
          description: 'Customers using video banking services',
          category: 'Engagement',
          type: 'behavioral',
          subcategory: 'Digital',
          silverTable: 'silver.retail_customer_interactions_golden',
          goldTable: 'gold.fact_customer_interactions',
        },
        {
          id: 'CRM-ENG-019',
          name: 'Appointment Booking Rate',
          description: 'Customers scheduling branch appointments',
          category: 'Engagement',
          type: 'behavioral',
          subcategory: 'Branch',
          silverTable: 'silver.retail_customer_interactions_golden',
          goldTable: 'gold.fact_customer_interactions',
        },
        {
          id: 'CRM-ENG-020',
          name: 'Social Media Engagement Rate',
          description: 'Customer interactions on social platforms',
          category: 'Engagement',
          type: 'behavioral',
          subcategory: 'Social',
          silverTable: 'silver.retail_customer_interactions_golden',
          goldTable: 'gold.fact_customer_interactions',
        },
        
        // NEW: Additional 20 metrics (CRM-ENG-021 to CRM-ENG-040)
        {
          id: 'CRM-ENG-021',
          name: 'Biometric Authentication Adoption',
          description: 'Customers using fingerprint/face ID',
          category: 'Engagement',
          type: 'behavioral',
          subcategory: 'Security',
          silverTable: 'silver.retail_customer_interactions_golden',
          goldTable: 'gold.fact_customer_interactions',
        },
        {
          id: 'CRM-ENG-022',
          name: 'Savings Goal Tool Usage',
          description: 'Active users of savings goal features',
          category: 'Engagement',
          type: 'behavioral',
          subcategory: 'PFM',
          silverTable: 'silver.retail_customer_interactions_golden',
          goldTable: 'gold.fact_customer_interactions',
        },
        {
          id: 'CRM-ENG-023',
          name: 'Spending Analysis Tool Usage',
          description: 'Customers viewing spending analytics',
          category: 'Engagement',
          type: 'behavioral',
          subcategory: 'PFM',
          silverTable: 'silver.retail_customer_interactions_golden',
          goldTable: 'gold.fact_customer_interactions',
        },
        {
          id: 'CRM-ENG-024',
          name: 'Push Notification Opt-In',
          description: 'Customers with push notifications enabled',
          category: 'Engagement',
          type: 'behavioral',
          subcategory: 'Mobile',
          silverTable: 'silver.retail_customer_interactions_golden',
          goldTable: 'gold.fact_customer_interactions',
        },
        {
          id: 'CRM-ENG-025',
          name: 'Cardless Cash Withdrawal',
          description: 'ATM withdrawals via mobile app',
          category: 'Engagement',
          type: 'behavioral',
          subcategory: 'Mobile',
          silverTable: 'silver.retail_customer_interactions_golden',
          goldTable: 'gold.fact_customer_interactions',
        },
        {
          id: 'CRM-ENG-026',
          name: 'External Account Linking',
          description: 'Customers linking external accounts',
          category: 'Engagement',
          type: 'behavioral',
          subcategory: 'Aggregation',
          silverTable: 'silver.retail_customer_interactions_golden',
          goldTable: 'gold.fact_customer_interactions',
        },
        {
          id: 'CRM-ENG-027',
          name: 'Recurring Transfer Setup',
          description: 'Automated transfer configurations',
          category: 'Engagement',
          type: 'behavioral',
          subcategory: 'Automation',
          silverTable: 'silver.retail_customer_interactions_golden',
          goldTable: 'gold.fact_customer_interactions',
        },
        {
          id: 'CRM-ENG-028',
          name: 'Security Alert Response Time',
          description: 'Time to respond to fraud alerts',
          category: 'Engagement',
          type: 'behavioral',
          subcategory: 'Security',
          silverTable: 'silver.retail_customer_interactions_golden',
          goldTable: 'gold.fact_customer_interactions',
        },
        {
          id: 'CRM-ENG-029',
          name: 'Digital Onboarding Completion',
          description: 'Digital profile setup completion rate',
          category: 'Engagement',
          type: 'behavioral',
          subcategory: 'Onboarding',
          silverTable: 'silver.retail_customer_interactions_golden',
          goldTable: 'gold.fact_customer_interactions',
        },
        {
          id: 'CRM-ENG-030',
          name: 'Investment Tool Engagement',
          description: 'Usage of investment planning tools',
          category: 'Engagement',
          type: 'behavioral',
          subcategory: 'Wealth',
          silverTable: 'silver.retail_customer_interactions_golden',
          goldTable: 'gold.fact_customer_interactions',
        },
        {
          id: 'CRM-ENG-031',
          name: 'Credit Score Monitoring',
          description: 'Customers checking credit scores',
          category: 'Engagement',
          type: 'behavioral',
          subcategory: 'Credit',
          silverTable: 'silver.retail_customer_interactions_golden',
          goldTable: 'gold.fact_customer_interactions',
        },
        {
          id: 'CRM-ENG-032',
          name: 'Document Upload Usage',
          description: 'Digital document submission frequency',
          category: 'Engagement',
          type: 'behavioral',
          subcategory: 'Digital',
          silverTable: 'silver.retail_customer_interactions_golden',
          goldTable: 'gold.fact_customer_interactions',
        },
        {
          id: 'CRM-ENG-033',
          name: 'Financial Education Content',
          description: 'Engagement with educational materials',
          category: 'Engagement',
          type: 'behavioral',
          subcategory: 'Education',
          silverTable: 'silver.retail_customer_interactions_golden',
          goldTable: 'gold.fact_customer_interactions',
        },
        {
          id: 'CRM-ENG-034',
          name: 'Contactless Payment Adoption',
          description: 'Customers using tap-to-pay',
          category: 'Engagement',
          type: 'behavioral',
          subcategory: 'Payments',
          silverTable: 'silver.retail_customer_interactions_golden',
          goldTable: 'gold.fact_customer_interactions',
        },
        {
          id: 'CRM-ENG-035',
          name: 'Digital Wallet Integration',
          description: 'Cards added to Apple/Google Pay',
          category: 'Engagement',
          type: 'behavioral',
          subcategory: 'Mobile',
          silverTable: 'silver.retail_customer_interactions_golden',
          goldTable: 'gold.fact_customer_interactions',
        },
        {
          id: 'CRM-ENG-036',
          name: 'Loan Calculator Usage',
          description: 'Interactions with loan calculators',
          category: 'Engagement',
          type: 'behavioral',
          subcategory: 'Tools',
          silverTable: 'silver.retail_customer_interactions_golden',
          goldTable: 'gold.fact_customer_interactions',
        },
        {
          id: 'CRM-ENG-037',
          name: 'Multi-Factor Auth Adoption',
          description: 'Customers with MFA enabled',
          category: 'Engagement',
          type: 'behavioral',
          subcategory: 'Security',
          silverTable: 'silver.retail_customer_interactions_golden',
          goldTable: 'gold.fact_customer_interactions',
        },
        {
          id: 'CRM-ENG-038',
          name: 'Weekend/After-Hours Usage',
          description: 'Digital banking outside business hours',
          category: 'Engagement',
          type: 'behavioral',
          subcategory: 'Availability',
          silverTable: 'silver.retail_customer_interactions_golden',
          goldTable: 'gold.fact_customer_interactions',
        },
        {
          id: 'CRM-ENG-039',
          name: 'Voice Banking Adoption',
          description: 'Voice assistant banking usage',
          category: 'Engagement',
          type: 'behavioral',
          subcategory: 'Voice',
          silverTable: 'silver.retail_customer_interactions_golden',
          goldTable: 'gold.fact_customer_interactions',
        },
        {
          id: 'CRM-ENG-040',
          name: 'Gamification Feature Participation',
          description: 'Engagement with rewards challenges',
          category: 'Engagement',
          type: 'behavioral',
          subcategory: 'Loyalty',
          silverTable: 'silver.retail_customer_interactions_golden',
          goldTable: 'gold.fact_customer_interactions',
        },
      ],
    },

    // Category 4: Value Metrics (40 metrics)
    {
      name: 'Value Metrics',
      description: 'Customer profitability, lifetime value, and revenue metrics',
      totalMetrics: 40,
      
      metrics: [
        {
          id: 'CRM-PROF-001',
          name: 'Customer Lifetime Value (CLV)',
          description: 'Predicted total value of customer relationship',
          category: 'Profitability',
          type: 'financial',
          subcategory: 'Lifetime Value',
          formula: "NPV(future_revenue_stream) - NPV(future_cost_stream)",
          unit: 'USD',
          aggregation: 'AVG',
          silverTable: 'silver.retail_customer_master_golden',
          goldTable: 'gold.fact_customer_profitability',
        },
        {
          id: 'CRM-PROF-002',
          name: 'Average Revenue per Customer',
          description: 'Mean revenue generated per customer',
          category: 'Profitability',
          type: 'financial',
          subcategory: 'Revenue',
          silverTable: 'silver.retail_customer_master_golden',
          goldTable: 'gold.fact_customer_profitability',
        },
        {
          id: 'CRM-PROF-003',
          name: 'Customer Profitability Index',
          description: 'Revenue minus cost to serve ratio',
          category: 'Profitability',
          type: 'financial',
          subcategory: 'Profitability',
          silverTable: 'silver.retail_customer_master_golden',
          goldTable: 'gold.fact_customer_profitability',
          silverTable: 'silver.retail_customer_master_golden',
          goldTable: 'gold.fact_customer_profitability',
        },
        {
          id: 'CRM-PROF-004',
          name: 'Net Interest Income per Customer',
          description: 'NII contribution per customer',
          category: 'Profitability',
          type: 'financial',
          subcategory: 'Interest',
          silverTable: 'silver.retail_customer_master_golden',
          goldTable: 'gold.fact_customer_profitability',
        },
        {
          id: 'CRM-PROF-005',
          name: 'Non-Interest Income per Customer',
          description: 'Fee income per customer',
          category: 'Profitability',
          type: 'financial',
          subcategory: 'Fees',
          silverTable: 'silver.retail_customer_master_golden',
          goldTable: 'gold.fact_customer_profitability',
        },
        {
          id: 'CRM-PROF-006',
          name: 'Deposit Balance per Customer',
          description: 'Average deposit holdings',
          category: 'Profitability',
          type: 'financial',
          subcategory: 'Deposits',
          silverTable: 'silver.retail_customer_master_golden',
          goldTable: 'gold.fact_customer_profitability',
        },
        {
          id: 'CRM-PROF-007',
          name: 'Loan Balance per Customer',
          description: 'Average loan exposure',
          category: 'Profitability',
          type: 'financial',
          subcategory: 'Lending',
          silverTable: 'silver.retail_customer_master_golden',
          goldTable: 'gold.fact_customer_profitability',
        },
        {
          id: 'CRM-PROF-008',
          name: 'Products per Customer',
          description: 'Average number of products owned',
          category: 'Profitability',
          type: 'financial',
          subcategory: 'Cross-Sell',
          silverTable: 'silver.retail_customer_master_golden',
          goldTable: 'gold.fact_customer_profitability',
        },
        {
          id: 'CRM-PROF-009',
          name: 'Share of Wallet',
          description: 'Percentage of customer financial assets held',
          category: 'Profitability',
          type: 'financial',
          subcategory: 'Wallet Share',
          silverTable: 'silver.retail_customer_master_golden',
          goldTable: 'gold.fact_customer_profitability',
        },
        {
          id: 'CRM-PROF-010',
          name: 'Monthly Fee Revenue',
          description: 'Recurring fee income per month',
          category: 'Profitability',
          type: 'financial',
          subcategory: 'Fees',
          silverTable: 'silver.retail_customer_master_golden',
          goldTable: 'gold.fact_customer_profitability',
        },
        {
          id: 'CRM-PROF-011',
          name: 'Interchange Revenue per Customer',
          description: 'Card interchange fees generated',
          category: 'Profitability',
          type: 'financial',
          subcategory: 'Cards',
          silverTable: 'silver.retail_customer_master_golden',
          goldTable: 'gold.fact_customer_profitability',
        },
        {
          id: 'CRM-PROF-012',
          name: 'Overdraft Fee Revenue',
          description: 'Income from overdraft fees',
          category: 'Profitability',
          type: 'financial',
          subcategory: 'Fees',
          silverTable: 'silver.retail_customer_master_golden',
          goldTable: 'gold.fact_customer_profitability',
        },
        {
          id: 'CRM-PROF-013',
          name: 'Investment Product Revenue',
          description: 'Revenue from investment products',
          category: 'Profitability',
          type: 'financial',
          subcategory: 'Wealth',
          silverTable: 'silver.retail_customer_master_golden',
          goldTable: 'gold.fact_customer_profitability',
        },
        {
          id: 'CRM-PROF-014',
          name: 'CLV to CAC Ratio',
          description: 'Lifetime value vs acquisition cost',
          category: 'Profitability',
          type: 'financial',
          subcategory: 'ROI',
          silverTable: 'silver.retail_customer_master_golden',
          goldTable: 'gold.fact_customer_profitability',
        },
        {
          id: 'CRM-PROF-015',
          name: 'Cost to Serve',
          description: 'Operational cost per customer',
          category: 'Profitability',
          type: 'financial',
          subcategory: 'Cost',
          silverTable: 'silver.retail_customer_master_golden',
          goldTable: 'gold.fact_customer_profitability',
        },
        {
          id: 'CRM-PROF-016',
          name: 'Customer Profitability Tier Distribution',
          description: 'Segmentation by profitability',
          category: 'Profitability',
          type: 'financial',
          subcategory: 'Segmentation',
          silverTable: 'silver.retail_customer_master_golden',
          goldTable: 'gold.fact_customer_profitability',
        },
        {
          id: 'CRM-PROF-017',
          name: 'Average Account Balance',
          description: 'Mean balance across all accounts',
          category: 'Profitability',
          type: 'financial',
          subcategory: 'Deposits',
          silverTable: 'silver.retail_customer_master_golden',
          goldTable: 'gold.fact_customer_profitability',
        },
        {
          id: 'CRM-PROF-018',
          name: 'Revenue Growth per Customer',
          description: 'Year-over-year revenue growth',
          category: 'Profitability',
          type: 'financial',
          subcategory: 'Growth',
          silverTable: 'silver.retail_customer_master_golden',
          goldTable: 'gold.fact_customer_profitability',
        },
        {
          id: 'CRM-PROF-019',
          name: 'Cross-Sell Revenue Impact',
          description: 'Incremental revenue from cross-sold products',
          category: 'Profitability',
          type: 'financial',
          subcategory: 'Cross-Sell',
          silverTable: 'silver.retail_customer_master_golden',
          goldTable: 'gold.fact_customer_profitability',
        },
        {
          id: 'CRM-PROF-020',
          name: 'Customer Margin',
          description: 'Average profit margin per customer',
          category: 'Profitability',
          type: 'financial',
          subcategory: 'Margin',
          silverTable: 'silver.retail_customer_master_golden',
          goldTable: 'gold.fact_customer_profitability',
        },
        
        // NEW: Additional 20 metrics (CRM-PROF-021 to CRM-PROF-040)
        {
          id: 'CRM-PROF-021',
          name: 'Premium Product Penetration',
          description: 'Customers with premium accounts/services',
          category: 'Profitability',
          type: 'financial',
          subcategory: 'Product Mix',
          silverTable: 'silver.retail_customer_master_golden',
          goldTable: 'gold.fact_customer_profitability',
        },
        {
          id: 'CRM-PROF-022',
          name: 'Wealth Management AUM',
          description: 'Assets under management per customer',
          category: 'Profitability',
          type: 'financial',
          subcategory: 'Wealth',
          silverTable: 'silver.retail_customer_master_golden',
          goldTable: 'gold.fact_customer_profitability',
        },
        {
          id: 'CRM-PROF-023',
          name: 'Mortgage Portfolio Value',
          description: 'Total mortgage value per customer',
          category: 'Profitability',
          type: 'financial',
          subcategory: 'Lending',
          silverTable: 'silver.retail_customer_master_golden',
          goldTable: 'gold.fact_customer_profitability',
        },
        {
          id: 'CRM-PROF-024',
          name: 'Credit Card Revolving Balance',
          description: 'Average revolving balance per cardholder',
          category: 'Profitability',
          type: 'financial',
          subcategory: 'Cards',
          silverTable: 'silver.retail_customer_master_golden',
          goldTable: 'gold.fact_customer_profitability',
        },
        {
          id: 'CRM-PROF-025',
          name: 'Auto Loan Origination Value',
          description: 'New auto loan volume per customer',
          category: 'Profitability',
          type: 'financial',
          subcategory: 'Lending',
          silverTable: 'silver.retail_customer_master_golden',
          goldTable: 'gold.fact_customer_profitability',
        },
        {
          id: 'CRM-PROF-026',
          name: 'Small Business Revenue per Household',
          description: 'Business banking revenue from retail households',
          category: 'Profitability',
          type: 'financial',
          subcategory: 'Cross-Line',
          silverTable: 'silver.retail_customer_master_golden',
          goldTable: 'gold.fact_customer_profitability',
        },
        {
          id: 'CRM-PROF-027',
          name: 'Insurance Product Revenue',
          description: 'Income from insurance sales',
          category: 'Profitability',
          type: 'financial',
          subcategory: 'Insurance',
          silverTable: 'silver.retail_customer_master_golden',
          goldTable: 'gold.fact_customer_profitability',
        },
        {
          id: 'CRM-PROF-028',
          name: 'Foreign Exchange Revenue',
          description: 'FX fees per customer',
          category: 'Profitability',
          type: 'financial',
          subcategory: 'FX',
          silverTable: 'silver.retail_customer_master_golden',
          goldTable: 'gold.fact_customer_profitability',
        },
        {
          id: 'CRM-PROF-029',
          name: 'Wire Transfer Revenue',
          description: 'Income from wire transfers',
          category: 'Profitability',
          type: 'financial',
          subcategory: 'Fees',
          silverTable: 'silver.retail_customer_master_golden',
          goldTable: 'gold.fact_customer_profitability',
        },
        {
          id: 'CRM-PROF-030',
          name: 'Safe Deposit Box Revenue',
          description: 'Rental income from SDB',
          category: 'Profitability',
          type: 'financial',
          subcategory: 'Services',
          silverTable: 'silver.retail_customer_master_golden',
          goldTable: 'gold.fact_customer_profitability',
        },
        {
          id: 'CRM-PROF-031',
          name: 'Cashiers Check Revenue',
          description: 'Fees from check issuance',
          category: 'Profitability',
          type: 'financial',
          subcategory: 'Fees',
          silverTable: 'silver.retail_customer_master_golden',
          goldTable: 'gold.fact_customer_profitability',
        },
        {
          id: 'CRM-PROF-032',
          name: 'Direct Deposit Value',
          description: 'Payroll deposits per customer',
          category: 'Profitability',
          type: 'financial',
          subcategory: 'Deposits',
          silverTable: 'silver.retail_customer_master_golden',
          goldTable: 'gold.fact_customer_profitability',
        },
        {
          id: 'CRM-PROF-033',
          name: 'Average Monthly Balance',
          description: 'Mean daily balance maintained',
          category: 'Profitability',
          type: 'financial',
          subcategory: 'Deposits',
          silverTable: 'silver.retail_customer_master_golden',
          goldTable: 'gold.fact_customer_profitability',
        },
        {
          id: 'CRM-PROF-034',
          name: 'CD Portfolio Value',
          description: 'Certificate of deposit holdings',
          category: 'Profitability',
          type: 'financial',
          subcategory: 'Time Deposits',
          silverTable: 'silver.retail_customer_master_golden',
          goldTable: 'gold.fact_customer_profitability',
        },
        {
          id: 'CRM-PROF-035',
          name: 'Savings Account Growth Rate',
          description: 'Year-over-year savings growth',
          category: 'Profitability',
          type: 'financial',
          subcategory: 'Deposits',
          silverTable: 'silver.retail_customer_master_golden',
          goldTable: 'gold.fact_customer_profitability',
        },
        {
          id: 'CRM-PROF-036',
          name: 'Risk-Adjusted Return',
          description: 'Return after credit risk adjustment',
          category: 'Profitability',
          type: 'financial',
          subcategory: 'Risk',
          silverTable: 'silver.retail_customer_master_golden',
          goldTable: 'gold.fact_customer_profitability',
        },
        {
          id: 'CRM-PROF-037',
          name: 'Household Total Value',
          description: 'Aggregate value across household members',
          category: 'Profitability',
          type: 'financial',
          subcategory: 'Household',
          silverTable: 'silver.retail_customer_master_golden',
          goldTable: 'gold.fact_customer_profitability',
        },
        {
          id: 'CRM-PROF-038',
          name: 'Age Cohort Profitability',
          description: 'Profitability by age segment',
          category: 'Profitability',
          type: 'financial',
          subcategory: 'Segmentation',
          silverTable: 'silver.retail_customer_master_golden',
          goldTable: 'gold.fact_customer_profitability',
        },
        {
          id: 'CRM-PROF-039',
          name: 'Geographic Market Value',
          description: 'Revenue by geographic market',
          category: 'Profitability',
          type: 'financial',
          subcategory: 'Geography',
          silverTable: 'silver.retail_customer_master_golden',
          goldTable: 'gold.fact_customer_profitability',
        },
        {
          id: 'CRM-PROF-040',
          name: 'Channel Cost Efficiency',
          description: 'Cost per transaction by channel',
          category: 'Profitability',
          type: 'financial',
          subcategory: 'Efficiency',
          silverTable: 'silver.retail_customer_master_golden',
          goldTable: 'gold.fact_customer_profitability',
        },
      ],
    },

    // Category 5: Satisfaction Metrics (40 metrics)
    {
      name: 'Satisfaction Metrics',
      description: 'Customer satisfaction, NPS, and feedback metrics',
      totalMetrics: 40,
      
      metrics: [
        {
          id: 'CRM-SAT-001',
          name: 'Net Promoter Score (NPS)',
          description: 'Customer recommendation likelihood',
          category: 'Satisfaction',
          type: 'kpi',
          subcategory: 'Advocacy',
          formula: "((Promoters - Detractors) / Total Respondents) * 100",
          unit: 'score',
          aggregation: 'AVG',
          silverTable: 'silver.retail_customer_interactions_golden',
          goldTable: 'gold.fact_customer_satisfaction',
        },
        {
          id: 'CRM-SAT-002',
          name: 'Customer Satisfaction Score (CSAT)',
          description: 'Average satisfaction rating',
          category: 'Satisfaction',
          type: 'kpi',
          subcategory: 'Satisfaction',
          silverTable: 'silver.retail_customer_interactions_golden',
          goldTable: 'gold.fact_customer_satisfaction',
          silverTable: 'silver.retail_customer_interactions_golden',
          goldTable: 'gold.fact_customer_satisfaction',
        },
        {
          id: 'CRM-SAT-003',
          name: 'Customer Effort Score (CES)',
          description: 'Ease of completing banking tasks',
          category: 'Satisfaction',
          type: 'kpi',
          subcategory: 'Experience',
          silverTable: 'silver.retail_customer_interactions_golden',
          goldTable: 'gold.fact_customer_satisfaction',
        },
        {
          id: 'CRM-SAT-004',
          name: 'Mobile App Rating',
          description: 'Average app store rating',
          category: 'Satisfaction',
          type: 'kpi',
          subcategory: 'Digital',
          silverTable: 'silver.retail_customer_interactions_golden',
          goldTable: 'gold.fact_customer_satisfaction',
        },
        {
          id: 'CRM-SAT-005',
          name: 'Branch Service Rating',
          description: 'In-branch experience satisfaction',
          category: 'Satisfaction',
          type: 'kpi',
          subcategory: 'Branch',
          silverTable: 'silver.retail_customer_interactions_golden',
          goldTable: 'gold.fact_customer_satisfaction',
        },
        {
          id: 'CRM-SAT-006',
          name: 'Call Center CSAT',
          description: 'Phone service satisfaction',
          category: 'Satisfaction',
          type: 'kpi',
          subcategory: 'Service',
          silverTable: 'silver.retail_customer_interactions_golden',
          goldTable: 'gold.fact_customer_satisfaction',
        },
        {
          id: 'CRM-SAT-007',
          name: 'Issue Resolution Rate',
          description: 'First-contact resolution percentage',
          category: 'Satisfaction',
          type: 'kpi',
          subcategory: 'Service',
          silverTable: 'silver.retail_customer_interactions_golden',
          goldTable: 'gold.fact_customer_satisfaction',
        },
        {
          id: 'CRM-SAT-008',
          name: 'Complaint Rate',
          description: 'Formal complaints per 1000 customers',
          category: 'Satisfaction',
          type: 'kpi',
          subcategory: 'Complaints',
          silverTable: 'silver.retail_customer_interactions_golden',
          goldTable: 'gold.fact_customer_satisfaction',
        },
        {
          id: 'CRM-SAT-009',
          name: 'Complaint Resolution Time',
          description: 'Average days to resolve complaints',
          category: 'Satisfaction',
          type: 'kpi',
          subcategory: 'Resolution',
          silverTable: 'silver.retail_customer_interactions_golden',
          goldTable: 'gold.fact_customer_satisfaction',
        },
        {
          id: 'CRM-SAT-010',
          name: 'Voice of Customer Score',
          description: 'Composite feedback score',
          category: 'Satisfaction',
          type: 'kpi',
          subcategory: 'Feedback',
          silverTable: 'silver.retail_customer_interactions_golden',
          goldTable: 'gold.fact_customer_satisfaction',
        },
        {
          id: 'CRM-SAT-011',
          name: 'Trust & Reputation Index',
          description: 'Brand trust measurement',
          category: 'Satisfaction',
          type: 'kpi',
          subcategory: 'Brand',
          silverTable: 'silver.retail_customer_interactions_golden',
          goldTable: 'gold.fact_customer_satisfaction',
        },
        {
          id: 'CRM-SAT-012',
          name: 'Digital Experience Score',
          description: 'Online/mobile satisfaction composite',
          category: 'Satisfaction',
          type: 'kpi',
          subcategory: 'Digital',
          silverTable: 'silver.retail_customer_interactions_golden',
          goldTable: 'gold.fact_customer_satisfaction',
        },
        {
          id: 'CRM-SAT-013',
          name: 'Product Satisfaction by Type',
          description: 'Satisfaction segmented by product',
          category: 'Satisfaction',
          type: 'kpi',
          subcategory: 'Product',
          silverTable: 'silver.retail_customer_interactions_golden',
          goldTable: 'gold.fact_customer_satisfaction',
        },
        {
          id: 'CRM-SAT-014',
          name: 'Fee Transparency Score',
          description: 'Perceived clarity of fee structure',
          category: 'Satisfaction',
          type: 'kpi',
          subcategory: 'Pricing',
          silverTable: 'silver.retail_customer_interactions_golden',
          goldTable: 'gold.fact_customer_satisfaction',
        },
        {
          id: 'CRM-SAT-015',
          name: 'Security Perception Score',
          description: 'Confidence in security measures',
          category: 'Satisfaction',
          type: 'kpi',
          subcategory: 'Security',
          silverTable: 'silver.retail_customer_interactions_golden',
          goldTable: 'gold.fact_customer_satisfaction',
        },
        {
          id: 'CRM-SAT-016',
          name: 'Personalization Score',
          description: 'Perceived personalized service',
          category: 'Satisfaction',
          type: 'kpi',
          subcategory: 'Personalization',
          silverTable: 'silver.retail_customer_interactions_golden',
          goldTable: 'gold.fact_customer_satisfaction',
        },
        {
          id: 'CRM-SAT-017',
          name: 'Innovation Perception',
          description: 'Customer view of bank innovation',
          category: 'Satisfaction',
          type: 'kpi',
          subcategory: 'Innovation',
          silverTable: 'silver.retail_customer_interactions_golden',
          goldTable: 'gold.fact_customer_satisfaction',
        },
        {
          id: 'CRM-SAT-018',
          name: 'Referral Rate',
          description: 'Customers who have referred others',
          category: 'Satisfaction',
          type: 'kpi',
          subcategory: 'Advocacy',
          silverTable: 'silver.retail_customer_interactions_golden',
          goldTable: 'gold.fact_customer_satisfaction',
        },
        {
          id: 'CRM-SAT-019',
          name: 'Social Media Sentiment',
          description: 'Net sentiment from social mentions',
          category: 'Satisfaction',
          type: 'kpi',
          subcategory: 'Brand',
          silverTable: 'silver.retail_customer_interactions_golden',
          goldTable: 'gold.fact_customer_satisfaction',
        },
        {
          id: 'CRM-SAT-020',
          name: 'Service Recovery Satisfaction',
          description: 'Satisfaction after issue resolution',
          category: 'Satisfaction',
          type: 'kpi',
          subcategory: 'Recovery',
          silverTable: 'silver.retail_customer_interactions_golden',
          goldTable: 'gold.fact_customer_satisfaction',
        },
        
        // NEW: Additional 20 metrics (CRM-SAT-021 to CRM-SAT-040)
        {
          id: 'CRM-SAT-021',
          name: 'Proactive Communication Rating',
          description: 'Satisfaction with proactive updates',
          category: 'Satisfaction',
          type: 'kpi',
          subcategory: 'Communication',
          silverTable: 'silver.retail_customer_interactions_golden',
          goldTable: 'gold.fact_customer_satisfaction',
        },
        {
          id: 'CRM-SAT-022',
          name: 'Wait Time Satisfaction',
          description: 'Satisfaction with service wait times',
          category: 'Satisfaction',
          type: 'kpi',
          subcategory: 'Service',
          silverTable: 'silver.retail_customer_interactions_golden',
          goldTable: 'gold.fact_customer_satisfaction',
        },
        {
          id: 'CRM-SAT-023',
          name: 'ATM Availability Score',
          description: 'Satisfaction with ATM network',
          category: 'Satisfaction',
          type: 'kpi',
          subcategory: 'ATM',
          silverTable: 'silver.retail_customer_interactions_golden',
          goldTable: 'gold.fact_customer_satisfaction',
        },
        {
          id: 'CRM-SAT-024',
          name: 'Financial Advice Quality',
          description: 'Rating of advisory services',
          category: 'Satisfaction',
          type: 'kpi',
          subcategory: 'Advisory',
          silverTable: 'silver.retail_customer_interactions_golden',
          goldTable: 'gold.fact_customer_satisfaction',
        },
        {
          id: 'CRM-SAT-025',
          name: 'Mobile App Usability Score',
          description: 'Ease of use rating',
          category: 'Satisfaction',
          type: 'kpi',
          subcategory: 'Digital',
          silverTable: 'silver.retail_customer_interactions_golden',
          goldTable: 'gold.fact_customer_satisfaction',
        },
        {
          id: 'CRM-SAT-026',
          name: 'Website Usability Score',
          description: 'Online banking ease of use',
          category: 'Satisfaction',
          type: 'kpi',
          subcategory: 'Digital',
          silverTable: 'silver.retail_customer_interactions_golden',
          goldTable: 'gold.fact_customer_satisfaction',
        },
        {
          id: 'CRM-SAT-027',
          name: 'Statement Clarity Score',
          description: 'Understanding of statements',
          category: 'Satisfaction',
          type: 'kpi',
          subcategory: 'Communication',
          silverTable: 'silver.retail_customer_interactions_golden',
          goldTable: 'gold.fact_customer_satisfaction',
        },
        {
          id: 'CRM-SAT-028',
          name: 'Product Recommendation Relevance',
          description: 'Perceived relevance of offers',
          category: 'Satisfaction',
          type: 'kpi',
          subcategory: 'Personalization',
          silverTable: 'silver.retail_customer_interactions_golden',
          goldTable: 'gold.fact_customer_satisfaction',
        },
        {
          id: 'CRM-SAT-029',
          name: 'Fraud Protection Confidence',
          description: 'Trust in fraud prevention',
          category: 'Satisfaction',
          type: 'kpi',
          subcategory: 'Security',
          silverTable: 'silver.retail_customer_interactions_golden',
          goldTable: 'gold.fact_customer_satisfaction',
        },
        {
          id: 'CRM-SAT-030',
          name: 'Loan Application Experience',
          description: 'Satisfaction with loan process',
          category: 'Satisfaction',
          type: 'kpi',
          subcategory: 'Lending',
          silverTable: 'silver.retail_customer_interactions_golden',
          goldTable: 'gold.fact_customer_satisfaction',
        },
        {
          id: 'CRM-SAT-031',
          name: 'Account Opening Experience',
          description: 'Onboarding satisfaction',
          category: 'Satisfaction',
          type: 'kpi',
          subcategory: 'Onboarding',
          silverTable: 'silver.retail_customer_interactions_golden',
          goldTable: 'gold.fact_customer_satisfaction',
        },
        {
          id: 'CRM-SAT-032',
          name: 'Staff Knowledgeability Rating',
          description: 'Perceived staff expertise',
          category: 'Satisfaction',
          type: 'kpi',
          subcategory: 'Service',
          silverTable: 'silver.retail_customer_interactions_golden',
          goldTable: 'gold.fact_customer_satisfaction',
        },
        {
          id: 'CRM-SAT-033',
          name: 'Staff Friendliness Rating',
          description: 'Service courtesy score',
          category: 'Satisfaction',
          type: 'kpi',
          subcategory: 'Service',
          silverTable: 'silver.retail_customer_interactions_golden',
          goldTable: 'gold.fact_customer_satisfaction',
        },
        {
          id: 'CRM-SAT-034',
          name: 'Problem Resolution Effectiveness',
          description: 'Quality of issue resolution',
          category: 'Satisfaction',
          type: 'kpi',
          subcategory: 'Resolution',
          silverTable: 'silver.retail_customer_interactions_golden',
          goldTable: 'gold.fact_customer_satisfaction',
        },
        {
          id: 'CRM-SAT-035',
          name: 'Digital Support Quality',
          description: 'Chat/email support satisfaction',
          category: 'Satisfaction',
          type: 'kpi',
          subcategory: 'Digital Support',
          silverTable: 'silver.retail_customer_interactions_golden',
          goldTable: 'gold.fact_customer_satisfaction',
        },
        {
          id: 'CRM-SAT-036',
          name: 'Competitive Positioning Score',
          description: 'Perceived value vs competitors',
          category: 'Satisfaction',
          type: 'kpi',
          subcategory: 'Competitive',
          silverTable: 'silver.retail_customer_interactions_golden',
          goldTable: 'gold.fact_customer_satisfaction',
        },
        {
          id: 'CRM-SAT-037',
          name: 'ESG/Sustainability Rating',
          description: 'Perception of social responsibility',
          category: 'Satisfaction',
          type: 'kpi',
          subcategory: 'Brand',
          silverTable: 'silver.retail_customer_interactions_golden',
          goldTable: 'gold.fact_customer_satisfaction',
        },
        {
          id: 'CRM-SAT-038',
          name: 'Community Involvement Score',
          description: 'Perceived community engagement',
          category: 'Satisfaction',
          type: 'kpi',
          subcategory: 'Brand',
          silverTable: 'silver.retail_customer_interactions_golden',
          goldTable: 'gold.fact_customer_satisfaction',
        },
        {
          id: 'CRM-SAT-039',
          name: 'Value for Money Perception',
          description: 'Perceived value of services',
          category: 'Satisfaction',
          type: 'kpi',
          subcategory: 'Pricing',
          silverTable: 'silver.retail_customer_interactions_golden',
          goldTable: 'gold.fact_customer_satisfaction',
        },
        {
          id: 'CRM-SAT-040',
          name: 'Overall Relationship Satisfaction',
          description: 'Composite satisfaction score',
          category: 'Satisfaction',
          type: 'kpi',
          subcategory: 'Overall',
          silverTable: 'silver.retail_customer_interactions_golden',
          goldTable: 'gold.fact_customer_satisfaction',
        },
      ],
    },
  ],
};
