/**
 * CUSTOMER-SERVICE-RETAIL ERD DEFINITIONS
 * 
 * Logical and Physical ERD definitions for customer service and support
 * Sources: CRM systems, Call center platforms, Case management
 */

// LOGICAL ERD
export const customerServiceRetailLogicalERD = {
  entities: [
    {
      name: 'Service Case',
      type: 'core',
      description: 'Customer service cases and tickets',
      attributes: [
        { name: 'case_id', type: 'BIGINT', isPrimaryKey: true },
        { name: 'customer_id', type: 'BIGINT', isForeignKey: true },
        { name: 'case_number', type: 'STRING' },
        { name: 'case_type', type: 'STRING', description: 'Inquiry|Complaint|Request|Issue' },
        { name: 'case_category', type: 'STRING', description: 'Account|Card|Loan|General' },
        { name: 'case_priority', type: 'STRING', description: 'Low|Medium|High|Urgent' },
        { name: 'case_status', type: 'STRING', description: 'Open|In Progress|Escalated|Resolved|Closed' },
        { name: 'created_timestamp', type: 'TIMESTAMP' },
        { name: 'assigned_agent_id', type: 'BIGINT', isForeignKey: true },
        { name: 'resolution_timestamp', type: 'TIMESTAMP' },
        { name: 'resolution_notes', type: 'TEXT' },
      ],
    },
    {
      name: 'Call Record',
      type: 'event',
      description: 'Customer service call interactions',
      attributes: [
        { name: 'call_id', type: 'BIGINT', isPrimaryKey: true },
        { name: 'customer_id', type: 'BIGINT', isForeignKey: true },
        { name: 'case_id', type: 'BIGINT', isForeignKey: true },
        { name: 'call_timestamp', type: 'TIMESTAMP' },
        { name: 'call_direction', type: 'STRING', description: 'Inbound|Outbound' },
        { name: 'call_duration_seconds', type: 'INTEGER' },
        { name: 'agent_id', type: 'BIGINT', isForeignKey: true },
        { name: 'queue_time_seconds', type: 'INTEGER' },
        { name: 'call_disposition', type: 'STRING' },
        { name: 'first_call_resolution', type: 'BOOLEAN' },
      ],
    },
    {
      name: 'Chat Session',
      type: 'event',
      description: 'Chat and messaging interactions',
      attributes: [
        { name: 'chat_id', type: 'BIGINT', isPrimaryKey: true },
        { name: 'customer_id', type: 'BIGINT', isForeignKey: true },
        { name: 'case_id', type: 'BIGINT', isForeignKey: true },
        { name: 'session_start', type: 'TIMESTAMP' },
        { name: 'session_end', type: 'TIMESTAMP' },
        { name: 'agent_id', type: 'BIGINT', isForeignKey: true },
        { name: 'channel', type: 'STRING', description: 'Web Chat|SMS|WhatsApp|Mobile App' },
        { name: 'message_count', type: 'INTEGER' },
        { name: 'resolved_flag', type: 'BOOLEAN' },
      ],
    },
    {
      name: 'Service Agent',
      type: 'core',
      description: 'Customer service representatives',
      attributes: [
        { name: 'agent_id', type: 'BIGINT', isPrimaryKey: true },
        { name: 'employee_id', type: 'BIGINT', isForeignKey: true },
        { name: 'agent_name', type: 'STRING' },
        { name: 'agent_tier', type: 'STRING', description: 'Tier 1|Tier 2|Supervisor|Manager' },
        { name: 'specialization', type: 'STRING' },
        { name: 'active_flag', type: 'BOOLEAN' },
        { name: 'hire_date', type: 'DATE' },
      ],
    },
    {
      name: 'Customer Feedback',
      type: 'event',
      description: 'Customer satisfaction surveys and feedback',
      attributes: [
        { name: 'feedback_id', type: 'BIGINT', isPrimaryKey: true },
        { name: 'customer_id', type: 'BIGINT', isForeignKey: true },
        { name: 'case_id', type: 'BIGINT', isForeignKey: true },
        { name: 'feedback_timestamp', type: 'TIMESTAMP' },
        { name: 'satisfaction_score', type: 'INTEGER', description: '1-5 rating' },
        { name: 'nps_score', type: 'INTEGER', description: '0-10 rating' },
        { name: 'feedback_text', type: 'TEXT' },
        { name: 'survey_type', type: 'STRING', description: 'Post-Call|CSAT|NPS' },
      ],
    },
  ],
  
  relationships: [
    {
      from: 'Call Record',
      to: 'Service Case',
      type: 'many-to-one',
      cardinality: 'N:1',
      foreignKey: 'case_id',
      description: 'Calls for case',
    },
    {
      from: 'Chat Session',
      to: 'Service Case',
      type: 'many-to-one',
      cardinality: 'N:1',
      foreignKey: 'case_id',
      description: 'Chats for case',
    },
    {
      from: 'Service Case',
      to: 'Service Agent',
      type: 'many-to-one',
      cardinality: 'N:1',
      foreignKey: 'assigned_agent_id',
      description: 'Agent handles cases',
    },
    {
      from: 'Customer Feedback',
      to: 'Service Case',
      type: 'one-to-one',
      cardinality: '1:1',
      foreignKey: 'case_id',
      description: 'Feedback for case',
    },
  ],
};

// PHYSICAL ERD
export const customerServiceRetailPhysicalERD = {
  tables: [
    {
      name: 'bronze.retail_service_cases',
      description: 'Customer service case data',
      source: 'CRM / Case Management System',
      updateFrequency: 'Real-time',
      recordCount: '~10M cases/year',
      attributes: [
        { name: 'case_id', type: 'BIGINT', isPrimaryKey: true },
        { name: 'customer_id', type: 'BIGINT' },
        { name: 'case_number', type: 'VARCHAR(50)' },
        { name: 'case_type', type: 'VARCHAR(100)' },
        { name: 'case_category', type: 'VARCHAR(100)' },
        { name: 'case_priority', type: 'VARCHAR(50)' },
        { name: 'case_status', type: 'VARCHAR(50)' },
        { name: 'created_timestamp', type: 'TIMESTAMP' },
        { name: 'assigned_agent_id', type: 'BIGINT' },
        { name: 'resolution_timestamp', type: 'TIMESTAMP' },
        { name: 'resolution_notes', type: 'TEXT' },
        { name: 'updated_timestamp', type: 'TIMESTAMP' },
        { name: 'source_system', type: 'VARCHAR(50)' },
      ],
    },
    {
      name: 'bronze.retail_call_records',
      description: 'Call center interaction logs',
      source: 'Call Center Platform',
      updateFrequency: 'Real-time',
      recordCount: '~50M calls/year',
      attributes: [
        { name: 'call_id', type: 'BIGINT', isPrimaryKey: true },
        { name: 'customer_id', type: 'BIGINT' },
        { name: 'case_id', type: 'BIGINT' },
        { name: 'call_timestamp', type: 'TIMESTAMP' },
        { name: 'call_direction', type: 'VARCHAR(50)' },
        { name: 'call_duration_seconds', type: 'INTEGER' },
        { name: 'agent_id', type: 'BIGINT' },
        { name: 'queue_time_seconds', type: 'INTEGER' },
        { name: 'call_disposition', type: 'VARCHAR(200)' },
        { name: 'first_call_resolution', type: 'BOOLEAN' },
        { name: 'created_timestamp', type: 'TIMESTAMP' },
        { name: 'source_system', type: 'VARCHAR(50)' },
      ],
    },
    {
      name: 'bronze.retail_chat_sessions',
      description: 'Chat and messaging sessions',
      source: 'Chat Platform',
      updateFrequency: 'Real-time',
      recordCount: '~20M sessions/year',
      attributes: [
        { name: 'chat_id', type: 'BIGINT', isPrimaryKey: true },
        { name: 'customer_id', type: 'BIGINT' },
        { name: 'case_id', type: 'BIGINT' },
        { name: 'session_start', type: 'TIMESTAMP' },
        { name: 'session_end', type: 'TIMESTAMP' },
        { name: 'agent_id', type: 'BIGINT' },
        { name: 'channel', type: 'VARCHAR(50)' },
        { name: 'message_count', type: 'INTEGER' },
        { name: 'resolved_flag', type: 'BOOLEAN' },
        { name: 'created_timestamp', type: 'TIMESTAMP' },
        { name: 'source_system', type: 'VARCHAR(50)' },
      ],
    },
    {
      name: 'bronze.retail_service_agents',
      description: 'Customer service agent data',
      source: 'HR System',
      updateFrequency: 'Daily',
      recordCount: '~5,000 agents',
      attributes: [
        { name: 'agent_id', type: 'BIGINT', isPrimaryKey: true },
        { name: 'employee_id', type: 'BIGINT' },
        { name: 'agent_name', type: 'VARCHAR(200)' },
        { name: 'agent_tier', type: 'VARCHAR(50)' },
        { name: 'specialization', type: 'VARCHAR(100)' },
        { name: 'active_flag', type: 'BOOLEAN' },
        { name: 'hire_date', type: 'DATE' },
        { name: 'created_timestamp', type: 'TIMESTAMP' },
        { name: 'source_system', type: 'VARCHAR(50)' },
      ],
    },
    {
      name: 'bronze.retail_customer_feedback',
      description: 'Customer satisfaction survey data',
      source: 'Survey Platform',
      updateFrequency: 'Real-time',
      recordCount: '~5M surveys/year',
      attributes: [
        { name: 'feedback_id', type: 'BIGINT', isPrimaryKey: true },
        { name: 'customer_id', type: 'BIGINT' },
        { name: 'case_id', type: 'BIGINT' },
        { name: 'feedback_timestamp', type: 'TIMESTAMP' },
        { name: 'satisfaction_score', type: 'INTEGER' },
        { name: 'nps_score', type: 'INTEGER' },
        { name: 'feedback_text', type: 'TEXT' },
        { name: 'survey_type', type: 'VARCHAR(50)' },
        { name: 'created_timestamp', type: 'TIMESTAMP' },
        { name: 'source_system', type: 'VARCHAR(50)' },
      ],
    },
  ],
  
  relationships: [
    {
      from: 'bronze.retail_call_records',
      to: 'bronze.retail_service_cases',
      type: 'many-to-one',
      cardinality: 'N:1',
      foreignKey: 'case_id',
      description: 'Calls for cases',
    },
    {
      from: 'bronze.retail_chat_sessions',
      to: 'bronze.retail_service_cases',
      type: 'many-to-one',
      cardinality: 'N:1',
      foreignKey: 'case_id',
      description: 'Chats for cases',
    },
    {
      from: 'bronze.retail_service_cases',
      to: 'bronze.retail_service_agents',
      type: 'many-to-one',
      cardinality: 'N:1',
      foreignKey: 'assigned_agent_id',
      description: 'Agent assigned to cases',
    },
  ],
};

export default {
  customerServiceRetailLogicalERD,
  customerServiceRetailPhysicalERD,
};
