/**
 * CUSTOMER-RETAIL ERD DEFINITIONS - 100% ACCURATE
 * 
 * Complete Entity Relationship Diagrams covering Bronze, Silver, and Gold layers
 * Based on comprehensive data model with 18 Bronze + 15 Silver + 20 Gold tables
 * 
 * Sources: FIS, Temenos, Salesforce, Equifax, Experian, TransUnion
 * 
 * Domain: Customer Retail
 * Area: Retail Banking
 * Coverage: Individual consumers, households, demographics, financial profiles
 */

// LOGICAL ERD - Business-Focused Conceptual Model
export const customerRetailLogicalERD = {
  description: 'Customer domain logical model - business perspective',
  totalEntities: 8,
  
  entities: [
    {
      name: 'Customer',
      type: 'core',
      description: 'Individual retail banking customer - single source of truth',
      keyAttributes: ['customer_id', 'ssn_hash', 'email_primary', 'phone_mobile'],
      businessRules: [
        'Must be 18+ years old to open accounts independently',
        'SSN required for US citizens, ITIN for non-citizens',
        'Email or mobile phone required for digital banking',
        'KYC verification required within 30 days of account opening',
      ],
      attributes: [
        { name: 'customer_id', type: 'BIGINT', isPrimaryKey: true, description: 'Unique customer identifier (auto-increment)' },
        { name: 'ssn_hash', type: 'STRING', isUnique: true, description: 'SHA-256 hashed SSN for matching' },
        { name: 'customer_uuid', type: 'STRING', isUnique: true, description: 'RFC 4122 UUID for external systems' },
        
        // Personal Information
        { name: 'first_name', type: 'STRING', isRequired: true, description: 'Legal first name per ID' },
        { name: 'middle_name', type: 'STRING', description: 'Middle name or initial' },
        { name: 'last_name', type: 'STRING', isRequired: true, description: 'Legal last name per ID' },
        { name: 'suffix', type: 'STRING', description: 'Jr|Sr|II|III|IV' },
        { name: 'preferred_name', type: 'STRING', description: 'Name customer prefers to be called' },
        
        // Demographics
        { name: 'date_of_birth', type: 'DATE', isRequired: true, description: 'Birth date for age verification' },
        { name: 'age', type: 'INTEGER', description: 'Current age (calculated)' },
        { name: 'age_group', type: 'STRING', description: '<18|18-24|25-34|35-44|45-54|55-64|65+' },
        { name: 'gender', type: 'STRING', description: 'M|F|X (non-binary)|U (undisclosed)' },
        { name: 'marital_status', type: 'STRING', description: 'S (single)|M (married)|D (divorced)|W (widowed)|P (partner)' },
        { name: 'citizenship_status', type: 'STRING', description: 'US Citizen|Permanent Resident|Non-Resident Alien' },
        
        // Contact Information
        { name: 'email_primary', type: 'STRING', description: 'Primary email address (unique)' },
        { name: 'email_verified', type: 'BOOLEAN', description: 'Email verification status' },
        { name: 'phone_mobile', type: 'STRING', description: 'Mobile phone in E.164 format (+1XXXXXXXXXX)' },
        { name: 'phone_home', type: 'STRING', description: 'Home phone number' },
        { name: 'phone_work', type: 'STRING', description: 'Work phone number' },
        { name: 'phone_mobile_verified', type: 'BOOLEAN', description: 'SMS verification completed' },
        
        // Address
        { name: 'address_line1', type: 'STRING', isRequired: true, description: 'Street address' },
        { name: 'address_line2', type: 'STRING', description: 'Apt/Suite/Unit number' },
        { name: 'city', type: 'STRING', isRequired: true, description: 'City name' },
        { name: 'state', type: 'STRING', isRequired: true, description: 'Two-letter state code' },
        { name: 'postal_code', type: 'STRING', isRequired: true, description: 'ZIP code (5 or 9 digit)' },
        { name: 'county', type: 'STRING', description: 'County name' },
        { name: 'country_code', type: 'STRING', description: 'ISO 3166-1 alpha-2 (US, CA, MX)' },
        
        // Financial Profile
        { name: 'fico_score', type: 'INTEGER', description: 'FICO credit score 300-850' },
        { name: 'fico_score_date', type: 'DATE', description: 'Last FICO score pull date' },
        { name: 'credit_score_tier', type: 'STRING', description: 'Excellent (750+)|Good (700-749)|Fair (650-699)|Poor (<650)' },
        { name: 'annual_income', type: 'DECIMAL(18,2)', description: 'Self-reported annual income' },
        { name: 'annual_income_verified', type: 'BOOLEAN', description: 'Income verification completed' },
        { name: 'employment_status', type: 'STRING', description: 'Employed|Self-Employed|Unemployed|Retired|Student|Homemaker' },
        { name: 'employer_name', type: 'STRING', description: 'Current employer name' },
        { name: 'occupation', type: 'STRING', description: 'Job title or occupation' },
        { name: 'years_at_employer', type: 'DECIMAL(5,2)', description: 'Employment tenure' },
        
        // Customer Lifecycle
        { name: 'customer_since_date', type: 'DATE', description: 'Date of first account opening' },
        { name: 'customer_status', type: 'STRING', description: 'Active|Inactive|Dormant|Closed|Deceased' },
        { name: 'customer_type', type: 'STRING', description: 'Individual|Joint|Minor|Trust|Business (ref)' },
        { name: 'customer_segment', type: 'STRING', description: 'Mass|Mass Affluent (<$250K)|Affluent ($250K-$1M)|Private ($1M+)' },
        { name: 'customer_tier', type: 'STRING', description: 'Bronze|Silver|Gold|Platinum|Diamond (loyalty tier)' },
        { name: 'lifecycle_stage', type: 'STRING', description: 'Prospect|New (<6mo)|Growing (6-24mo)|Mature (2-10yr)|Declining|Attrition' },
        { name: 'tenure_months', type: 'INTEGER', description: 'Months since first account' },
        
        // Household Relationship
        { name: 'household_id', type: 'BIGINT', isForeignKey: true, references: 'Household', description: 'FK to household aggregation' },
        { name: 'household_role', type: 'STRING', description: 'Head of Household|Spouse|Dependent|Other' },
        
        // Risk & Compliance
        { name: 'kyc_status', type: 'STRING', description: 'Not Started|In Progress|Completed|Expired|Failed' },
        { name: 'kyc_completion_date', type: 'DATE', description: 'KYC verification date' },
        { name: 'kyc_next_review_date', type: 'DATE', description: 'Next periodic review due date' },
        { name: 'aml_risk_rating', type: 'STRING', description: 'Low|Medium|High|Prohibited (sanctions list)' },
        { name: 'aml_risk_score', type: 'INTEGER', description: 'AML risk score 0-100' },
        { name: 'pep_flag', type: 'BOOLEAN', description: 'Politically Exposed Person indicator' },
        { name: 'ofac_check_date', type: 'DATE', description: 'Last OFAC screening date' },
        { name: 'ofac_match_status', type: 'STRING', description: 'Clear|Potential Match|Confirmed Match' },
        
        // Digital Banking
        { name: 'online_banking_enrolled', type: 'BOOLEAN', description: 'Online banking access enabled' },
        { name: 'online_banking_last_login', type: 'TIMESTAMP', description: 'Last web login' },
        { name: 'mobile_banking_enrolled', type: 'BOOLEAN', description: 'Mobile app enrolled' },
        { name: 'mobile_banking_last_login', type: 'TIMESTAMP', description: 'Last mobile login' },
        { name: 'biometric_auth_enabled', type: 'BOOLEAN', description: 'Fingerprint/Face ID enabled' },
        
        // Preferences
        { name: 'paperless_statements', type: 'BOOLEAN', description: 'Opted for paperless' },
        { name: 'email_opt_in', type: 'BOOLEAN', description: 'Marketing email consent' },
        { name: 'sms_opt_in', type: 'BOOLEAN', description: 'SMS marketing consent' },
        { name: 'phone_opt_in', type: 'BOOLEAN', description: 'Phone marketing consent' },
        { name: 'preferred_language', type: 'STRING', description: 'ISO 639-1 code (en, es, zh, fr)' },
        { name: 'preferred_contact_method', type: 'STRING', description: 'Email|Phone|SMS|Mobile App|Mail' },
        
        // Timestamps
        { name: 'created_date', type: 'TIMESTAMP', description: 'Record creation timestamp' },
        { name: 'updated_date', type: 'TIMESTAMP', description: 'Last update timestamp' },
      ],
    },
    
    {
      name: 'Household',
      type: 'core',
      description: 'Household grouping for relationship management and combined analytics',
      keyAttributes: ['household_id', 'head_of_household_id'],
      businessRules: [
        'Household must have at least one member',
        'Head of household must be an active customer',
        'Household assets calculated as sum of all member account balances',
      ],
      attributes: [
        { name: 'household_id', type: 'BIGINT', isPrimaryKey: true, description: 'Unique household identifier' },
        { name: 'household_name', type: 'STRING', description: 'Household name (e.g., "Smith Family")' },
        { name: 'household_type', type: 'STRING', description: 'Single|Couple|Family|Multi-Generational' },
        { name: 'head_of_household_id', type: 'BIGINT', isForeignKey: true, references: 'Customer', description: 'Primary customer' },
        { name: 'household_size', type: 'INTEGER', description: 'Number of customer members' },
        { name: 'total_household_income', type: 'DECIMAL(18,2)', description: 'Combined annual income' },
        { name: 'total_household_assets', type: 'DECIMAL(18,2)', description: 'AUM - total across all accounts' },
        { name: 'household_segment', type: 'STRING', description: 'Mass|Affluent|High Net Worth' },
        { name: 'primary_branch_id', type: 'BIGINT', isForeignKey: true, description: 'Primary servicing branch' },
        { name: 'relationship_manager_id', type: 'BIGINT', isForeignKey: true, description: 'Assigned banker' },
        { name: 'household_status', type: 'STRING', description: 'Active|Inactive|Closed' },
      ],
    },
    
    {
      name: 'Customer Event',
      type: 'event',
      description: 'Audit trail of customer lifecycle events and changes',
      keyAttributes: ['event_id', 'customer_id', 'event_type', 'event_timestamp'],
      attributes: [
        { name: 'event_id', type: 'BIGINT', isPrimaryKey: true },
        { name: 'customer_id', type: 'BIGINT', isForeignKey: true, references: 'Customer' },
        { name: 'event_type', type: 'STRING', description: 'Onboarding|Status Change|Profile Update|KYC Update|Life Event|Risk Alert' },
        { name: 'event_subtype', type: 'STRING', description: 'Marriage|Divorce|Birth|Death|Home Purchase|Job Change|Retirement' },
        { name: 'event_timestamp', type: 'TIMESTAMP', description: 'When event occurred' },
        { name: 'event_date', type: 'DATE', description: 'Event date (for reporting)' },
        { name: 'event_source', type: 'STRING', description: 'System|Manual|Batch|API|External' },
        { name: 'field_changed', type: 'STRING', description: 'Field name that changed' },
        { name: 'previous_value', type: 'STRING', description: 'Value before change' },
        { name: 'new_value', type: 'STRING', description: 'Value after change' },
        { name: 'change_reason', type: 'STRING', description: 'Reason for change' },
        { name: 'triggered_by_user_id', type: 'STRING', description: 'User who made change' },
        { name: 'triggered_by_system', type: 'STRING', description: 'System that triggered event' },
      ],
    },
    
    {
      name: 'Customer Preference',
      type: 'core',
      description: 'Customer communication, product, and service preferences',
      keyAttributes: ['customer_id'],
      attributes: [
        { name: 'customer_id', type: 'BIGINT', isPrimaryKey: true, isForeignKey: true, references: 'Customer' },
        
        // Communication Preferences
        { name: 'email_opt_in', type: 'BOOLEAN', description: 'Marketing email consent (CAN-SPAM compliant)' },
        { name: 'sms_opt_in', type: 'BOOLEAN', description: 'SMS marketing consent (TCPA compliant)' },
        { name: 'phone_opt_in', type: 'BOOLEAN', description: 'Phone marketing consent' },
        { name: 'direct_mail_opt_in', type: 'BOOLEAN', description: 'Direct mail marketing consent' },
        { name: 'do_not_solicit', type: 'BOOLEAN', description: 'Global marketing opt-out' },
        
        { name: 'preferred_contact_method', type: 'STRING', description: 'Email|Phone|SMS|Mobile App|Mail' },
        { name: 'preferred_contact_time', type: 'STRING', description: 'Morning|Afternoon|Evening|Weekend' },
        { name: 'preferred_language', type: 'STRING', description: 'Communication language preference' },
        
        // Statement Preferences
        { name: 'paperless_statements', type: 'BOOLEAN', description: 'Paperless banking opt-in' },
        { name: 'statement_delivery_method', type: 'STRING', description: 'Paper Mail|Email|Online Portal|Mobile App' },
        { name: 'combined_statement', type: 'BOOLEAN', description: 'Combine all accounts in one statement' },
        
        // Product Interests (for targeting)
        { name: 'interested_in_savings', type: 'BOOLEAN', description: 'High-yield savings interest' },
        { name: 'interested_in_credit_card', type: 'BOOLEAN', description: 'Credit card offers' },
        { name: 'interested_in_mortgage', type: 'BOOLEAN', description: 'Home mortgage interest' },
        { name: 'interested_in_auto_loan', type: 'BOOLEAN', description: 'Auto loan interest' },
        { name: 'interested_in_investment', type: 'BOOLEAN', description: 'Investment/brokerage interest' },
        { name: 'interested_in_insurance', type: 'BOOLEAN', description: 'Insurance products' },
        
        // Privacy Settings
        { name: 'data_sharing_opt_out', type: 'BOOLEAN', description: 'Opt-out of info sharing (GLBA)' },
        { name: 'ccpa_opt_out', type: 'BOOLEAN', description: 'CCPA Do Not Sell (California)' },
        { name: 'gdpr_consent', type: 'BOOLEAN', description: 'GDPR consent (EU customers)' },
        
        { name: 'last_updated_date', type: 'TIMESTAMP', description: 'Preference last modified' },
      ],
    },
    
    {
      name: 'Customer Score',
      type: 'derived',
      description: 'Predictive scores and customer value metrics',
      keyAttributes: ['customer_id', 'score_date'],
      attributes: [
        { name: 'customer_id', type: 'BIGINT', isPrimaryKey: true, isForeignKey: true, references: 'Customer' },
        { name: 'score_date', type: 'DATE', isPrimaryKey: true, description: 'Score calculation date' },
        
        // Value Scores
        { name: 'customer_value_score', type: 'INTEGER', description: '0-100 current value score' },
        { name: 'lifetime_value_estimate', type: 'DECIMAL(18,2)', description: 'Predicted CLV (3-year)' },
        { name: 'total_relationship_revenue', type: 'DECIMAL(18,2)', description: 'Annual revenue from customer' },
        { name: 'wallet_share_estimate', type: 'DECIMAL(5,2)', description: 'Estimated % of banking with us' },
        
        // Risk Scores
        { name: 'propensity_to_churn', type: 'DECIMAL(5,4)', description: 'Churn probability 0-1' },
        { name: 'churn_risk_tier', type: 'STRING', description: 'Low|Medium|High|Critical' },
        { name: 'credit_risk_score', type: 'INTEGER', description: 'Internal credit risk score 0-1000' },
        { name: 'fraud_risk_score', type: 'INTEGER', description: 'Fraud propensity score 0-100' },
        { name: 'default_probability', type: 'DECIMAL(5,4)', description: 'Probability of default 0-1' },
        
        // Propensity Scores
        { name: 'propensity_to_buy_checking', type: 'DECIMAL(5,4)', description: 'Next product propensity' },
        { name: 'propensity_to_buy_credit_card', type: 'DECIMAL(5,4)' },
        { name: 'propensity_to_buy_mortgage', type: 'DECIMAL(5,4)' },
        { name: 'propensity_to_buy_investment', type: 'DECIMAL(5,4)' },
        { name: 'next_best_product', type: 'STRING', description: 'Recommended product for cross-sell' },
        
        // Engagement Scores
        { name: 'engagement_score', type: 'INTEGER', description: 'Digital engagement score 0-100' },
        { name: 'digital_adoption_score', type: 'INTEGER', description: 'Digital channel usage 0-100' },
        { name: 'branch_dependency_score', type: 'INTEGER', description: 'Branch reliance 0-100' },
        
        // Satisfaction Scores
        { name: 'satisfaction_score', type: 'INTEGER', description: 'CSAT score 1-5' },
        { name: 'nps_score', type: 'INTEGER', description: 'Net Promoter Score -100 to 100' },
        { name: 'nps_category', type: 'STRING', description: 'Promoter|Passive|Detractor' },
        
        // Model Metadata
        { name: 'model_version', type: 'STRING', description: 'Scoring model version' },
        { name: 'model_run_date', type: 'TIMESTAMP', description: 'When model was executed' },
      ],
    },
    
    {
      name: 'Customer Relationship',
      type: 'associative',
      description: 'Inter-customer relationships (joint owners, beneficiaries, POA, etc.)',
      keyAttributes: ['relationship_id', 'primary_customer_id', 'related_customer_id'],
      businessRules: [
        'A customer can have multiple relationships',
        'Joint owners have equal account rights by default',
        'Beneficiaries have no access until primary customer death',
        'POA requires legal documentation on file',
      ],
      attributes: [
        { name: 'relationship_id', type: 'BIGINT', isPrimaryKey: true },
        { name: 'primary_customer_id', type: 'BIGINT', isForeignKey: true, references: 'Customer', description: 'Primary customer' },
        { name: 'related_customer_id', type: 'BIGINT', isForeignKey: true, references: 'Customer', description: 'Related customer' },
        
        { name: 'relationship_type', type: 'STRING', description: 'Joint Owner|Beneficiary|Authorized Signer|POA|Custodian|Guardian' },
        { name: 'relationship_subtype', type: 'STRING', description: 'Spouse|Parent|Child|Sibling|Other Relative|Non-Relative' },
        { name: 'relationship_status', type: 'STRING', description: 'Active|Inactive|Terminated|Pending' },
        
        { name: 'authority_level', type: 'STRING', description: 'Full|Limited|View Only|Specific Accounts' },
        { name: 'signing_authority', type: 'BOOLEAN', description: 'Can sign on behalf' },
        { name: 'withdrawal_authority', type: 'BOOLEAN', description: 'Can withdraw funds' },
        { name: 'transfer_authority', type: 'BOOLEAN', description: 'Can transfer funds' },
        
        { name: 'percentage_ownership', type: 'DECIMAL(5,2)', description: 'Ownership % for joint accounts' },
        { name: 'beneficiary_percentage', type: 'DECIMAL(5,2)', description: 'Inheritance % for beneficiaries' },
        
        { name: 'effective_date', type: 'DATE', description: 'When relationship became active' },
        { name: 'termination_date', type: 'DATE', description: 'When relationship ended' },
        { name: 'termination_reason', type: 'STRING', description: 'Death|Divorce|Customer Request|Legal' },
        
        { name: 'documentation_on_file', type: 'BOOLEAN', description: 'Legal docs verified' },
        { name: 'document_type', type: 'STRING', description: 'POA|Court Order|Trust Agreement|Will' },
      ],
    },
    
    {
      name: 'Credit Report',
      type: 'external',
      description: 'Credit bureau data from Equifax/Experian/TransUnion',
      keyAttributes: ['report_id', 'customer_id', 'report_date'],
      attributes: [
        { name: 'report_id', type: 'BIGINT', isPrimaryKey: true },
        { name: 'customer_id', type: 'BIGINT', isForeignKey: true, references: 'Customer' },
        { name: 'bureau', type: 'STRING', description: 'Equifax|Experian|TransUnion' },
        { name: 'report_date', type: 'DATE', description: 'Report pull date' },
        { name: 'report_type', type: 'STRING', description: 'Hard Pull|Soft Pull|Monitoring' },
        { name: 'pull_reason', type: 'STRING', description: 'Application|Account Review|Collection|Marketing' },
        
        { name: 'fico_score', type: 'INTEGER', description: 'FICO 8 score 300-850' },
        { name: 'vantage_score', type: 'INTEGER', description: 'VantageScore 3.0' },
        { name: 'score_factors', type: 'JSON', description: 'Array of negative factors' },
        
        { name: 'total_accounts', type: 'INTEGER', description: 'Total trade lines' },
        { name: 'open_accounts', type: 'INTEGER', description: 'Currently open accounts' },
        { name: 'closed_accounts', type: 'INTEGER', description: 'Closed accounts' },
        { name: 'delinquent_accounts', type: 'INTEGER', description: 'Accounts with late payments' },
        { name: 'derogatory_marks', type: 'INTEGER', description: 'Collections, charge-offs, etc.' },
        
        { name: 'oldest_account_date', type: 'DATE', description: 'Age of credit history' },
        { name: 'newest_account_date', type: 'DATE', description: 'Most recent account' },
        
        { name: 'total_credit_limit', type: 'DECIMAL(18,2)', description: 'Total revolving credit' },
        { name: 'total_balance', type: 'DECIMAL(18,2)', description: 'Total amount owed' },
        { name: 'credit_utilization', type: 'DECIMAL(5,4)', description: 'Balance / Limit ratio' },
        
        { name: 'inquiries_6_months', type: 'INTEGER', description: 'Hard inquiries last 6mo' },
        { name: 'inquiries_12_months', type: 'INTEGER', description: 'Hard inquiries last 12mo' },
        
        { name: 'bankruptcy_flag', type: 'BOOLEAN' },
        { name: 'foreclosure_flag', type: 'BOOLEAN' },
        { name: 'judgment_flag', type: 'BOOLEAN' },
        { name: 'lien_flag', type: 'BOOLEAN' },
      ],
    },
    
    {
      name: 'Identity Document',
      type: 'compliance',
      description: 'KYC identity verification documents',
      keyAttributes: ['document_id', 'customer_id'],
      attributes: [
        { name: 'document_id', type: 'BIGINT', isPrimaryKey: true },
        { name: 'customer_id', type: 'BIGINT', isForeignKey: true, references: 'Customer' },
        
        { name: 'document_type', type: 'STRING', description: 'Drivers License|Passport|State ID|Military ID|SSN Card' },
        { name: 'document_number', type: 'STRING', description: 'Document number (encrypted)' },
        { name: 'issuing_authority', type: 'STRING', description: 'State DMV|US Dept of State|etc.' },
        { name: 'issuing_country', type: 'STRING', description: 'ISO 3166-1 code' },
        { name: 'issuing_state', type: 'STRING', description: 'State code if applicable' },
        
        { name: 'issue_date', type: 'DATE' },
        { name: 'expiration_date', type: 'DATE' },
        { name: 'is_expired', type: 'BOOLEAN', description: 'Document currently expired' },
        
        { name: 'verification_method', type: 'STRING', description: 'Manual|Automated IDV|Biometric|Notary' },
        { name: 'verification_status', type: 'STRING', description: 'Pending|Verified|Failed|Expired' },
        { name: 'verification_date', type: 'DATE' },
        { name: 'verified_by', type: 'STRING', description: 'User or system' },
        
        { name: 'document_image_path', type: 'STRING', description: 'Secure storage path' },
        { name: 'is_primary_id', type: 'BOOLEAN', description: 'Primary identification document' },
      ],
    },
  ],
  
  relationships: [
    {
      from: 'Customer',
      to: 'Household',
      type: 'many-to-one',
      cardinality: 'N:1',
      foreignKey: 'household_id',
      description: 'Multiple customers can belong to one household',
      referentialIntegrity: 'CASCADE on delete household removes customer assignments',
    },
    {
      from: 'Customer Event',
      to: 'Customer',
      type: 'many-to-one',
      cardinality: 'N:1',
      foreignKey: 'customer_id',
      description: 'Customer lifecycle events track all changes',
      referentialIntegrity: 'CASCADE on delete customer removes events',
    },
    {
      from: 'Customer Preference',
      to: 'Customer',
      type: 'one-to-one',
      cardinality: '1:1',
      foreignKey: 'customer_id',
      description: 'Each customer has exactly one preference record',
      referentialIntegrity: 'CASCADE on delete',
    },
    {
      from: 'Customer Score',
      to: 'Customer',
      type: 'one-to-many',
      cardinality: '1:N',
      foreignKey: 'customer_id',
      description: 'Customer has scores calculated daily/monthly',
      referentialIntegrity: 'CASCADE on delete',
    },
    {
      from: 'Customer Relationship',
      to: 'Customer',
      type: 'many-to-one',
      cardinality: 'N:1',
      foreignKey: 'primary_customer_id',
      description: 'Primary customer in relationship',
      referentialIntegrity: 'CASCADE on delete',
    },
    {
      from: 'Customer Relationship',
      to: 'Customer',
      type: 'many-to-one',
      cardinality: 'N:1',
      foreignKey: 'related_customer_id',
      description: 'Related/secondary customer in relationship',
      referentialIntegrity: 'RESTRICT on delete (must remove relationship first)',
    },
    {
      from: 'Credit Report',
      to: 'Customer',
      type: 'many-to-one',
      cardinality: 'N:1',
      foreignKey: 'customer_id',
      description: 'Customer can have multiple credit pulls over time',
      referentialIntegrity: 'CASCADE on delete',
    },
    {
      from: 'Identity Document',
      to: 'Customer',
      type: 'many-to-one',
      cardinality: 'N:1',
      foreignKey: 'customer_id',
      description: 'Customer can have multiple ID documents',
      referentialIntegrity: 'CASCADE on delete',
    },
  ],
};

// PHYSICAL ERD - Bronze Layer Implementation (18 Tables)
export const customerRetailPhysicalERD = {
  description: 'Customer domain physical model - Bronze layer (raw data from source systems)',
  totalTables: 18,
  dataVolume: '1.5TB',
  
  tables: [
    {
      name: 'bronze.retail_customer_master',
      description: 'Core customer demographic and identification data from FIS/Temenos',
      sourceSystem: 'CORE_BANKING_SYSTEM',
      loadType: 'CDC',
      estimatedRows: 50000000,
      avgRowSize: 4096,
      partitionKey: 'customer_id',
      clusterKey: ['customer_since_date', 'customer_status'],
      
      primaryKey: ['customer_id', 'source_system'],
      uniqueKeys: [['ssn_hash'], ['customer_uuid'], ['email_primary']],
      indexes: [
        { name: 'idx_household', columns: ['household_id'], type: 'BTREE' },
        { name: 'idx_name', columns: ['last_name', 'first_name'], type: 'BTREE' },
        { name: 'idx_postal_code', columns: ['postal_code'], type: 'BTREE' },
        { name: 'idx_status_segment', columns: ['customer_status', 'customer_segment'], type: 'BTREE' },
      ],
      
      totalColumns: 95,
      keyColumns: ['customer_id', 'ssn_hash', 'email_primary', 'household_id', 'customer_status'],
    },
    {
      name: 'bronze.retail_household_master',
      description: 'Household aggregation and family relationships',
      sourceSystem: 'CORE_BANKING_SYSTEM',
      estimatedRows: 25000000,
      primaryKey: ['household_id', 'source_system'],
      indexes: [
        { name: 'idx_head_customer', columns: ['head_of_household_id'], type: 'BTREE' },
        { name: 'idx_postal_code', columns: ['postal_code'], type: 'BTREE' },
      ],
      totalColumns: 22,
    },
    {
      name: 'bronze.retail_customer_lifecycle_events',
      description: 'Customer lifecycle events and status changes (SCD Type 4)',
      sourceSystem: 'CORE_BANKING_SYSTEM',
      estimatedRows: 500000000,
      partitionKey: 'event_date',
      primaryKey: ['event_id', 'source_system'],
      indexes: [
        { name: 'idx_customer_event_type', columns: ['customer_id', 'event_type', 'event_date'], type: 'BTREE' },
      ],
      totalColumns: 18,
    },
    {
      name: 'bronze.equifax_credit_report',
      description: 'Equifax credit bureau reports',
      sourceSystem: 'EQUIFAX_API',
      estimatedRows: 100000000,
      primaryKey: ['report_id', 'source_system'],
      totalColumns: 32,
    },
    {
      name: 'bronze.experian_credit_report',
      description: 'Experian credit bureau reports',
      sourceSystem: 'EXPERIAN_API',
      estimatedRows: 100000000,
      primaryKey: ['report_id', 'source_system'],
      totalColumns: 32,
    },
    {
      name: 'bronze.transunion_credit_report',
      description: 'TransUnion credit bureau reports',
      sourceSystem: 'TRANSUNION_API',
      estimatedRows: 100000000,
      primaryKey: ['report_id', 'source_system'],
      totalColumns: 32,
    },
    {
      name: 'bronze.salesforce_customer_profile',
      description: 'Extended customer profile from Salesforce CRM',
      sourceSystem: 'SALESFORCE',
      estimatedRows: 50000000,
      primaryKey: ['sfdc_account_id', 'source_system'],
      totalColumns: 28,
    },
    {
      name: 'bronze.customer_kyc_documents',
      description: 'KYC verification documents and status',
      sourceSystem: 'KYC_SYSTEM',
      estimatedRows: 100000000,
      primaryKey: ['document_id', 'source_system'],
      totalColumns: 24,
    },
    {
      name: 'bronze.customer_identity_verification',
      description: 'Identity verification attempts and results',
      sourceSystem: 'IDV_PROVIDER',
      estimatedRows: 80000000,
      primaryKey: ['verification_id', 'source_system'],
      totalColumns: 22,
    },
    {
      name: 'bronze.customer_addresses_history',
      description: 'Customer address change history',
      sourceSystem: 'CORE_BANKING_SYSTEM',
      estimatedRows: 200000000,
      primaryKey: ['address_history_id', 'source_system'],
      totalColumns: 20,
    },
    {
      name: 'bronze.customer_phone_history',
      description: 'Phone number change history',
      sourceSystem: 'CORE_BANKING_SYSTEM',
      estimatedRows: 150000000,
      primaryKey: ['phone_history_id', 'source_system'],
      totalColumns: 16,
    },
    {
      name: 'bronze.customer_email_history',
      description: 'Email address change history',
      sourceSystem: 'CORE_BANKING_SYSTEM',
      estimatedRows: 120000000,
      primaryKey: ['email_history_id', 'source_system'],
      totalColumns: 14,
    },
    {
      name: 'bronze.customer_preferences',
      description: 'Communication and product preferences',
      sourceSystem: 'PREFERENCE_CENTER',
      estimatedRows: 50000000,
      primaryKey: ['customer_id', 'source_system'],
      totalColumns: 26,
    },
    {
      name: 'bronze.customer_consent_records',
      description: 'Marketing consent records (TCPA, GDPR, CCPA)',
      sourceSystem: 'CONSENT_MANAGEMENT',
      estimatedRows: 200000000,
      primaryKey: ['consent_id', 'source_system'],
      totalColumns: 18,
    },
    {
      name: 'bronze.ofac_screening_results',
      description: 'OFAC sanctions screening results',
      sourceSystem: 'SANCTIONS_SCREENING',
      estimatedRows: 300000000,
      primaryKey: ['screening_id', 'source_system'],
      totalColumns: 20,
    },
    {
      name: 'bronze.customer_segments',
      description: 'Customer segmentation assignments from CDP',
      sourceSystem: 'CDP',
      estimatedRows: 100000000,
      primaryKey: ['segment_assignment_id', 'source_system'],
      totalColumns: 16,
    },
    {
      name: 'bronze.customer_scores',
      description: 'Predictive scores (CLV, churn, propensity)',
      sourceSystem: 'ANALYTICS_ENGINE',
      estimatedRows: 150000000,
      primaryKey: ['customer_id', 'score_date', 'source_system'],
      totalColumns: 35,
    },
    {
      name: 'bronze.customer_relationships',
      description: 'Inter-customer relationships',
      sourceSystem: 'CORE_BANKING_SYSTEM',
      estimatedRows: 30000000,
      primaryKey: ['relationship_id', 'source_system'],
      totalColumns: 22,
    },
  ],
  
  relationships: [
    // Customer Master Relationships
    {
      from: 'bronze.retail_customer_master',
      to: 'bronze.retail_household_master',
      type: 'many-to-one',
      foreignKey: 'household_id',
      indexSupport: 'idx_household on customer_master',
      description: 'Customer belongs to household',
    },
    {
      from: 'bronze.retail_household_master',
      to: 'bronze.retail_customer_master',
      type: 'many-to-one',
      foreignKey: 'head_of_household_id',
      description: 'Head of household reference',
    },
    {
      from: 'bronze.retail_customer_lifecycle_events',
      to: 'bronze.retail_customer_master',
      type: 'many-to-one',
      foreignKey: 'customer_id',
      description: 'Lifecycle events per customer',
    },
    // Credit Bureau Relationships
    {
      from: 'bronze.equifax_credit_report',
      to: 'bronze.retail_customer_master',
      type: 'many-to-one',
      foreignKey: 'customer_id',
      description: 'Equifax credit reports',
    },
    {
      from: 'bronze.experian_credit_report',
      to: 'bronze.retail_customer_master',
      type: 'many-to-one',
      foreignKey: 'customer_id',
      description: 'Experian credit reports',
    },
    {
      from: 'bronze.transunion_credit_report',
      to: 'bronze.retail_customer_master',
      type: 'many-to-one',
      foreignKey: 'customer_id',
      description: 'TransUnion credit reports',
    },
    // CRM and Extended Profile
    {
      from: 'bronze.salesforce_customer_profile',
      to: 'bronze.retail_customer_master',
      type: 'one-to-one',
      foreignKey: 'customer_id',
      description: 'Extended CRM profile',
    },
    // KYC and Compliance
    {
      from: 'bronze.customer_kyc_documents',
      to: 'bronze.retail_customer_master',
      type: 'many-to-one',
      foreignKey: 'customer_id',
      description: 'KYC documents per customer',
    },
    {
      from: 'bronze.customer_identity_verification',
      to: 'bronze.retail_customer_master',
      type: 'many-to-one',
      foreignKey: 'customer_id',
      description: 'Identity verification attempts',
    },
    {
      from: 'bronze.ofac_screening_results',
      to: 'bronze.retail_customer_master',
      type: 'many-to-one',
      foreignKey: 'customer_id',
      description: 'OFAC screening results',
    },
    // Contact History
    {
      from: 'bronze.customer_addresses_history',
      to: 'bronze.retail_customer_master',
      type: 'many-to-one',
      foreignKey: 'customer_id',
      description: 'Address change history',
    },
    {
      from: 'bronze.customer_phone_history',
      to: 'bronze.retail_customer_master',
      type: 'many-to-one',
      foreignKey: 'customer_id',
      description: 'Phone number history',
    },
    {
      from: 'bronze.customer_email_history',
      to: 'bronze.retail_customer_master',
      type: 'many-to-one',
      foreignKey: 'customer_id',
      description: 'Email address history',
    },
    // Preferences and Consent
    {
      from: 'bronze.customer_preferences',
      to: 'bronze.retail_customer_master',
      type: 'one-to-one',
      foreignKey: 'customer_id',
      description: 'Customer preferences',
    },
    {
      from: 'bronze.customer_consent_records',
      to: 'bronze.retail_customer_master',
      type: 'many-to-one',
      foreignKey: 'customer_id',
      description: 'Marketing consent records',
    },
    // Segmentation and Scoring
    {
      from: 'bronze.customer_segments',
      to: 'bronze.retail_customer_master',
      type: 'many-to-one',
      foreignKey: 'customer_id',
      description: 'Segment assignments',
    },
    {
      from: 'bronze.customer_scores',
      to: 'bronze.retail_customer_master',
      type: 'many-to-one',
      foreignKey: 'customer_id',
      description: 'Predictive scores',
    },
    // Relationships
    {
      from: 'bronze.customer_relationships',
      to: 'bronze.retail_customer_master',
      type: 'many-to-one',
      foreignKey: 'primary_customer_id',
      description: 'Primary customer in relationship',
    },
    {
      from: 'bronze.customer_relationships',
      to: 'bronze.retail_customer_master',
      type: 'many-to-one',
      foreignKey: 'related_customer_id',
      description: 'Related customer in relationship',
    },
  ],
};

// SILVER ERD - Cleansed and Conformed Data (15 Tables)
export const customerRetailSilverERD = {
  description: 'Customer domain silver layer - MDM golden records with SCD Type 2',
  totalTables: 15,
  dataVolume: '800GB',
  
  tables: [
    {
      name: 'silver.retail_customer_master_golden',
      description: 'MDM golden record - single source of truth for customer with SCD Type 2',
      grain: 'One current row per customer',
      scdType: 'Type 2',
      primaryKey: ['customer_sk'],
      naturalKey: ['customer_id'],
      estimatedRows: 75000000,
      keyFeatures: [
        'Data quality scoring',
        'Address standardization (USPS)',
        'Phone number E.164 formatting',
        'Email validation',
        'Duplicate detection and merge',
        'Survivorship rules applied',
      ],
    },
    {
      name: 'silver.retail_household_golden',
      description: 'MDM golden record for households with aggregated metrics',
      scdType: 'Type 2',
      primaryKey: ['household_sk'],
      naturalKey: ['household_id'],
      estimatedRows: 30000000,
    },
    {
      name: 'silver.retail_customer_360',
      description: 'Complete customer 360 view with aggregated metrics across all products',
      grain: 'One row per customer (current state)',
      scdType: 'Type 1',
      primaryKey: ['customer_id'],
      estimatedRows: 50000000,
      keyMetrics: [
        'Total relationship revenue',
        'Product count by category',
        'Average balances across products',
        'Transaction velocity metrics',
        'Digital engagement score',
        'Customer value score',
      ],
    },
    {
      name: 'silver.retail_customer_addresses_golden',
      description: 'Customer address history with USPS standardization',
      grain: 'One row per customer per address per effective period',
      scdType: 'Type 2',
      primaryKey: ['customer_address_sk'],
      estimatedRows: 250000000,
    },
    {
      name: 'silver.retail_customer_contacts_golden',
      description: 'Customer contact methods (phone, email) with verification status',
      grain: 'One row per contact method per effective period',
      scdType: 'Type 2',
      primaryKey: ['customer_contact_sk'],
      estimatedRows: 200000000,
    },
    {
      name: 'silver.retail_customer_preferences_golden',
      description: 'Customer communication and product preferences',
      grain: 'One row per customer',
      scdType: 'Type 1',
      primaryKey: ['customer_id'],
      estimatedRows: 50000000,
    },
    {
      name: 'silver.retail_customer_consent_golden',
      description: 'Marketing consent and privacy preferences (TCPA, GDPR, CCPA compliant)',
      grain: 'One row per customer per consent type per effective period',
      scdType: 'Type 2',
      primaryKey: ['customer_consent_sk'],
      estimatedRows: 150000000,
    },
    {
      name: 'silver.retail_customer_relationships_golden',
      description: 'Inter-customer relationships (joint owners, beneficiaries, POA)',
      grain: 'One row per customer relationship',
      scdType: 'Type 2',
      primaryKey: ['customer_relationship_sk'],
      estimatedRows: 40000000,
    },
    {
      name: 'silver.retail_customer_lifecycle_events',
      description: 'Customer lifecycle events and status changes',
      grain: 'One row per event',
      scdType: 'Type 1',
      primaryKey: ['lifecycle_event_id'],
      estimatedRows: 500000000,
    },
    {
      name: 'silver.retail_credit_reports_golden',
      description: 'Consolidated credit bureau data from all three bureaus',
      grain: 'One row per customer per report date',
      scdType: 'Type 1',
      primaryKey: ['customer_id', 'report_date'],
      estimatedRows: 300000000,
      keyFeatures: [
        'Bureau consolidation (best score across 3 bureaus)',
        'Trade line aggregation',
        'Inquiry deduplication',
      ],
    },
    {
      name: 'silver.retail_customer_kyc_golden',
      description: 'KYC/CDD compliance status and document tracking',
      grain: 'One row per customer per effective period',
      scdType: 'Type 2',
      primaryKey: ['customer_kyc_sk'],
      estimatedRows: 60000000,
    },
    {
      name: 'silver.retail_customer_identity_documents',
      description: 'Identity verification documents (drivers license, passport, etc.)',
      grain: 'One row per document',
      scdType: 'Type 1',
      primaryKey: ['document_id'],
      estimatedRows: 100000000,
    },
    {
      name: 'silver.retail_customer_ofac_screening',
      description: 'OFAC sanctions screening results',
      grain: 'One row per screening event',
      scdType: 'Type 1',
      primaryKey: ['screening_id'],
      estimatedRows: 300000000,
    },
    {
      name: 'silver.retail_customer_segmentation',
      description: 'Customer segmentation assignments (value, behavioral, lifecycle)',
      grain: 'One row per customer per effective period',
      scdType: 'Type 2',
      primaryKey: ['customer_segment_sk'],
      estimatedRows: 120000000,
    },
    {
      name: 'silver.retail_customer_scores',
      description: 'Predictive customer scores (CLV, churn, propensity, engagement)',
      grain: 'One row per customer per score date',
      scdType: 'Type 1',
      primaryKey: ['customer_id', 'score_date'],
      estimatedRows: 600000000,
    },
  ],

  relationships: [
    // Silver Layer Relationships
    {
      from: 'silver.retail_customer_360',
      to: 'silver.retail_customer_master_golden',
      type: 'one-to-one',
      foreignKey: 'customer_id',
      description: 'Customer 360 view linked to golden record',
    },
    {
      from: 'silver.retail_customer_addresses_golden',
      to: 'silver.retail_customer_master_golden',
      type: 'many-to-one',
      foreignKey: 'customer_id',
      description: 'Address history per customer',
    },
    {
      from: 'silver.retail_customer_contacts_golden',
      to: 'silver.retail_customer_master_golden',
      type: 'many-to-one',
      foreignKey: 'customer_id',
      description: 'Contact methods per customer',
    },
    {
      from: 'silver.retail_customer_preferences_golden',
      to: 'silver.retail_customer_master_golden',
      type: 'one-to-one',
      foreignKey: 'customer_id',
      description: 'Preferences per customer',
    },
    {
      from: 'silver.retail_customer_consent_golden',
      to: 'silver.retail_customer_master_golden',
      type: 'many-to-one',
      foreignKey: 'customer_id',
      description: 'Consent records per customer',
    },
    {
      from: 'silver.retail_customer_relationships_golden',
      to: 'silver.retail_customer_master_golden',
      type: 'many-to-one',
      foreignKey: 'primary_customer_id',
      description: 'Primary customer relationships',
    },
    {
      from: 'silver.retail_customer_relationships_golden',
      to: 'silver.retail_customer_master_golden',
      type: 'many-to-one',
      foreignKey: 'related_customer_id',
      description: 'Related customer relationships',
    },
    {
      from: 'silver.retail_customer_lifecycle_events',
      to: 'silver.retail_customer_master_golden',
      type: 'many-to-one',
      foreignKey: 'customer_id',
      description: 'Lifecycle events per customer',
    },
    {
      from: 'silver.retail_credit_reports_golden',
      to: 'silver.retail_customer_master_golden',
      type: 'many-to-one',
      foreignKey: 'customer_id',
      description: 'Consolidated credit reports',
    },
    {
      from: 'silver.retail_customer_kyc_golden',
      to: 'silver.retail_customer_master_golden',
      type: 'one-to-one',
      foreignKey: 'customer_id',
      description: 'KYC compliance status',
    },
    {
      from: 'silver.retail_customer_identity_documents',
      to: 'silver.retail_customer_master_golden',
      type: 'many-to-one',
      foreignKey: 'customer_id',
      description: 'Identity documents per customer',
    },
    {
      from: 'silver.retail_customer_ofac_screening',
      to: 'silver.retail_customer_master_golden',
      type: 'many-to-one',
      foreignKey: 'customer_id',
      description: 'OFAC screening results',
    },
    {
      from: 'silver.retail_customer_segmentation',
      to: 'silver.retail_customer_master_golden',
      type: 'many-to-one',
      foreignKey: 'customer_id',
      description: 'Segment assignments',
    },
    {
      from: 'silver.retail_customer_scores',
      to: 'silver.retail_customer_master_golden',
      type: 'many-to-one',
      foreignKey: 'customer_id',
      description: 'Predictive scores',
    },
    {
      from: 'silver.retail_customer_master_golden',
      to: 'silver.retail_household_golden',
      type: 'many-to-one',
      foreignKey: 'household_id',
      description: 'Customer belongs to household',
    },
  ],
};

// GOLD ERD - Dimensional Model (Kimball Star Schema)
export const customerRetailGoldERD = {
  description: 'Customer domain gold layer - Kimball dimensional model',
  totalDimensions: 12,
  totalFacts: 8,
  dataVolume: '1.2TB',
  
  dimensions: [
    {
      name: 'gold.dim_retail_customer',
      description: 'Customer dimension with demographic and behavioral attributes (SCD Type 1)',
      grain: 'One row per unique customer',
      primaryKey: 'customer_key',
      naturalKey: 'customer_id',
      scdType: 'Type 1',
      estimatedRows: 50000000,
      attributes: [
        'customer_id', 'full_name', 'date_of_birth', 'age', 'age_group', 'generation',
        'gender', 'marital_status', 'email_primary', 'phone_mobile', 'city', 'state', 'postal_code',
        'fico_score', 'credit_score_tier', 'annual_income', 'income_bracket', 'employment_status',
        'customer_since_date', 'customer_tenure_years', 'customer_status', 'customer_segment',
        'customer_tier', 'lifecycle_stage', 'value_segment', 'behavioral_segment', 'channel_preference',
        'total_products', 'has_checking', 'has_savings', 'has_credit_card', 'has_mortgage',
        'kyc_status', 'aml_risk_rating', 'online_banking_user', 'mobile_banking_user',
      ],
    },
    {
      name: 'gold.dim_household',
      description: 'Household dimension for relationship management (SCD Type 1)',
      grain: 'One row per household',
      primaryKey: 'household_key',
      naturalKey: 'household_id',
      scdType: 'Type 1',
      estimatedRows: 25000000,
      attributes: [
        'household_id', 'household_name', 'household_type', 'household_size',
        'total_household_income', 'total_household_assets', 'household_segment',
        'primary_branch_id', 'relationship_manager_id',
      ],
    },
    {
      name: 'gold.dim_customer_segment',
      description: 'Customer segmentation taxonomy (4-level hierarchy)',
      grain: 'One row per segment',
      primaryKey: 'segment_key',
      scdType: 'Type 1',
      estimatedRows: 100,
      attributes: [
        'segment_l1', 'segment_l2', 'segment_l3', 'segment_l4',
        'segment_description', 'target_products', 'marketing_strategy',
      ],
    },
    {
      name: 'gold.dim_lifecycle_stage',
      description: 'Customer lifecycle stage dimension',
      grain: 'One row per lifecycle stage',
      primaryKey: 'lifecycle_key',
      scdType: 'Type 1',
      estimatedRows: 10,
      attributes: ['stage_code', 'stage_name', 'stage_description', 'typical_tenure', 'retention_strategy'],
    },
    {
      name: 'gold.dim_customer_tier',
      description: 'Customer loyalty tier dimension',
      grain: 'One row per tier',
      primaryKey: 'tier_key',
      scdType: 'Type 1',
      estimatedRows: 6,
      attributes: ['tier_code', 'tier_name', 'tier_description', 'benefits', 'qualification_criteria'],
    },
    {
      name: 'gold.dim_risk_rating',
      description: 'Risk rating categories (credit, AML, fraud)',
      grain: 'One row per risk rating',
      primaryKey: 'risk_rating_key',
      scdType: 'Type 1',
      estimatedRows: 20,
      attributes: ['rating_type', 'rating_level', 'rating_description', 'score_range', 'review_frequency'],
    },
    {
      name: 'gold.dim_geography',
      description: 'Geographic dimension (state, county, city, postal code)',
      grain: 'One row per postal code',
      primaryKey: 'geography_key',
      scdType: 'Type 1',
      estimatedRows: 50000,
      attributes: [
        'postal_code', 'city', 'county', 'state', 'state_name', 'region',
        'metro_area', 'population', 'median_income', 'median_home_value',
      ],
    },
    {
      name: 'gold.dim_age_group',
      description: 'Age group dimension with generational cohorts',
      grain: 'One row per age group',
      primaryKey: 'age_group_key',
      scdType: 'Type 1',
      estimatedRows: 20,
      attributes: ['age_group_code', 'age_range', 'generation', 'description', 'target_products'],
    },
    {
      name: 'gold.dim_employment',
      description: 'Employment status and occupation taxonomy',
      grain: 'One row per occupation',
      primaryKey: 'employment_key',
      scdType: 'Type 1',
      estimatedRows: 1000,
      attributes: ['employment_status', 'occupation', 'occupation_code', 'industry', 'industry_code'],
    },
    {
      name: 'gold.dim_event_type',
      description: 'Customer lifecycle event type taxonomy',
      grain: 'One row per event type',
      primaryKey: 'event_type_key',
      scdType: 'Type 1',
      estimatedRows: 50,
      attributes: ['event_type_code', 'event_category', 'event_description', 'action_required'],
    },
    {
      name: 'gold.dim_date',
      description: 'Date dimension (conformed across all domains)',
      grain: 'One row per day',
      primaryKey: 'date_key',
      scdType: 'Type 1',
      estimatedRows: 7305,
      attributes: [
        'date', 'year', 'quarter', 'month', 'week', 'day',
        'day_of_week', 'day_of_year', 'is_weekend', 'is_holiday',
      ],
    },
    {
      name: 'gold.dim_branch',
      description: 'Branch dimension (conformed across domains)',
      grain: 'One row per branch',
      primaryKey: 'branch_key',
      naturalKey: 'branch_id',
      scdType: 'Type 2',
      estimatedRows: 5000,
      attributes: ['branch_id', 'branch_name', 'branch_type', 'city', 'state', 'region'],
    },
  ],
  
  facts: [
    {
      name: 'gold.fact_customer_snapshot',
      description: 'Daily customer snapshot (periodic snapshot)',
      factType: 'Periodic Snapshot',
      grain: 'One row per customer per day',
      estimatedRows: 1825000000,
      measures: [
        'total_balance',
        'deposit_balance',
        'loan_balance',
        'credit_card_balance',
        'product_count',
        'deposit_accounts_count',
        'loan_accounts_count',
        'card_accounts_count',
        'relationship_revenue_ytd',
        'fees_ytd',
        'interest_paid_ytd',
        'digital_engagement_score',
        'branch_visits_mtd',
        'mobile_logins_mtd',
        'satisfaction_score',
        'nps_score',
      ],
      dimensions: [
        'customer_key',
        'household_key',
        'date_key',
        'segment_key',
        'lifecycle_key',
        'tier_key',
        'geography_key',
        'primary_branch_key',
      ],
    },
    {
      name: 'gold.fact_customer_monthly_summary',
      description: 'Monthly customer aggregation (periodic snapshot)',
      factType: 'Periodic Snapshot',
      grain: 'One row per customer per month',
      estimatedRows: 600000000,
      measures: [
        'month_end_balance',
        'average_daily_balance',
        'product_count_eom',
        'revenue_month',
        'transactions_count',
        'digital_transactions_count',
        'branch_visits_count',
        'service_calls_count',
        'new_products_acquired',
        'products_closed',
      ],
      dimensions: ['customer_key', 'date_key', 'segment_key'],
    },
    {
      name: 'gold.fact_customer_lifecycle_events',
      description: 'Customer lifecycle events (transaction fact)',
      factType: 'Transaction',
      grain: 'One row per event',
      estimatedRows: 500000000,
      measures: [
        'event_count',
        'revenue_impact',
        'balance_change',
        'product_count_change',
      ],
      dimensions: [
        'customer_key',
        'event_date_key',
        'event_type_key',
        'branch_key',
      ],
    },
    {
      name: 'gold.fact_customer_scores',
      description: 'Customer predictive scores (accumulating snapshot)',
      factType: 'Accumulating Snapshot',
      grain: 'One row per customer per score date',
      estimatedRows: 600000000,
      measures: [
        'customer_value_score',
        'lifetime_value_estimate',
        'churn_probability',
        'churn_risk_score',
        'cross_sell_propensity_checking',
        'cross_sell_propensity_credit_card',
        'cross_sell_propensity_mortgage',
        'cross_sell_propensity_investment',
        'engagement_score',
        'digital_adoption_score',
        'satisfaction_score',
        'nps_score',
        'credit_risk_score',
        'fraud_risk_score',
      ],
      dimensions: [
        'customer_key',
        'score_date_key',
        'segment_key',
      ],
    },
    {
      name: 'gold.fact_customer_acquisition',
      description: 'Customer acquisition events (transaction fact)',
      factType: 'Transaction',
      grain: 'One row per customer acquisition',
      estimatedRows: 50000000,
      measures: [
        'acquisition_cost',
        'initial_deposit_amount',
        'initial_product_count',
        'estimated_ltv',
        'days_to_first_transaction',
        'days_to_digital_enrollment',
      ],
      dimensions: [
        'customer_key',
        'acquisition_date_key',
        'branch_key',
        'channel_key',
        'campaign_key',
      ],
    },
    {
      name: 'gold.fact_customer_attrition',
      description: 'Customer attrition events (transaction fact)',
      factType: 'Transaction',
      grain: 'One row per customer attrition',
      estimatedRows: 10000000,
      measures: [
        'ltv_realized',
        'relationship_tenure_days',
        'final_balance',
        'products_at_closure',
        'lifetime_revenue',
      ],
      dimensions: [
        'customer_key',
        'attrition_date_key',
        'attrition_reason_key',
      ],
    },
    {
      name: 'gold.fact_credit_bureau_pulls',
      description: 'Credit bureau pull history (transaction fact)',
      factType: 'Transaction',
      grain: 'One row per credit pull',
      estimatedRows: 300000000,
      measures: [
        'fico_score',
        'vantage_score',
        'total_accounts',
        'delinquent_accounts',
        'total_credit_limit',
        'total_balance',
        'credit_utilization',
        'inquiries_6_months',
        'bankruptcy_flag',
      ],
      dimensions: [
        'customer_key',
        'pull_date_key',
        'bureau_key',
        'pull_reason_key',
      ],
    },
    {
      name: 'gold.fact_kyc_reviews',
      description: 'KYC/AML review events (transaction fact)',
      factType: 'Transaction',
      grain: 'One row per KYC review',
      estimatedRows: 200000000,
      measures: [
        'review_count',
        'aml_risk_score',
        'documents_verified_count',
        'days_to_completion',
        'exception_count',
      ],
      dimensions: [
        'customer_key',
        'review_date_key',
        'review_type_key',
        'risk_rating_key',
      ],
    },
  ],

  relationships: [
    // Gold Layer Fact-to-Dimension Relationships
    // Fact: Customer Snapshot
    {
      from: 'gold.fact_customer_snapshot',
      to: 'gold.dim_retail_customer',
      type: 'many-to-one',
      foreignKey: 'customer_key',
      description: 'Customer dimension',
    },
    {
      from: 'gold.fact_customer_snapshot',
      to: 'gold.dim_household',
      type: 'many-to-one',
      foreignKey: 'household_key',
      description: 'Household dimension',
    },
    {
      from: 'gold.fact_customer_snapshot',
      to: 'gold.dim_date',
      type: 'many-to-one',
      foreignKey: 'date_key',
      description: 'Snapshot date',
    },
    {
      from: 'gold.fact_customer_snapshot',
      to: 'gold.dim_customer_segment',
      type: 'many-to-one',
      foreignKey: 'segment_key',
      description: 'Customer segment',
    },
    {
      from: 'gold.fact_customer_snapshot',
      to: 'gold.dim_lifecycle_stage',
      type: 'many-to-one',
      foreignKey: 'lifecycle_key',
      description: 'Lifecycle stage',
    },
    {
      from: 'gold.fact_customer_snapshot',
      to: 'gold.dim_customer_tier',
      type: 'many-to-one',
      foreignKey: 'tier_key',
      description: 'Customer tier',
    },
    {
      from: 'gold.fact_customer_snapshot',
      to: 'gold.dim_geography',
      type: 'many-to-one',
      foreignKey: 'geography_key',
      description: 'Geographic location',
    },
    {
      from: 'gold.fact_customer_snapshot',
      to: 'gold.dim_branch',
      type: 'many-to-one',
      foreignKey: 'primary_branch_key',
      description: 'Primary branch',
    },
    // Fact: Monthly Summary
    {
      from: 'gold.fact_customer_monthly_summary',
      to: 'gold.dim_retail_customer',
      type: 'many-to-one',
      foreignKey: 'customer_key',
      description: 'Customer dimension',
    },
    {
      from: 'gold.fact_customer_monthly_summary',
      to: 'gold.dim_date',
      type: 'many-to-one',
      foreignKey: 'date_key',
      description: 'Month date',
    },
    {
      from: 'gold.fact_customer_monthly_summary',
      to: 'gold.dim_customer_segment',
      type: 'many-to-one',
      foreignKey: 'segment_key',
      description: 'Customer segment',
    },
    // Fact: Lifecycle Events
    {
      from: 'gold.fact_customer_lifecycle_events',
      to: 'gold.dim_retail_customer',
      type: 'many-to-one',
      foreignKey: 'customer_key',
      description: 'Customer dimension',
    },
    {
      from: 'gold.fact_customer_lifecycle_events',
      to: 'gold.dim_date',
      type: 'many-to-one',
      foreignKey: 'event_date_key',
      description: 'Event date',
    },
    {
      from: 'gold.fact_customer_lifecycle_events',
      to: 'gold.dim_event_type',
      type: 'many-to-one',
      foreignKey: 'event_type_key',
      description: 'Event type',
    },
    {
      from: 'gold.fact_customer_lifecycle_events',
      to: 'gold.dim_branch',
      type: 'many-to-one',
      foreignKey: 'branch_key',
      description: 'Branch dimension',
      optional: true,
    },
    // Fact: Customer Scores
    {
      from: 'gold.fact_customer_scores',
      to: 'gold.dim_retail_customer',
      type: 'many-to-one',
      foreignKey: 'customer_key',
      description: 'Customer dimension',
    },
    {
      from: 'gold.fact_customer_scores',
      to: 'gold.dim_date',
      type: 'many-to-one',
      foreignKey: 'score_date_key',
      description: 'Score date',
    },
    {
      from: 'gold.fact_customer_scores',
      to: 'gold.dim_customer_segment',
      type: 'many-to-one',
      foreignKey: 'segment_key',
      description: 'Customer segment',
    },
    // Fact: Customer Acquisition
    {
      from: 'gold.fact_customer_acquisition',
      to: 'gold.dim_retail_customer',
      type: 'many-to-one',
      foreignKey: 'customer_key',
      description: 'Customer dimension',
    },
    {
      from: 'gold.fact_customer_acquisition',
      to: 'gold.dim_date',
      type: 'many-to-one',
      foreignKey: 'acquisition_date_key',
      description: 'Acquisition date',
    },
    {
      from: 'gold.fact_customer_acquisition',
      to: 'gold.dim_branch',
      type: 'many-to-one',
      foreignKey: 'branch_key',
      description: 'Branch dimension',
    },
    // Fact: Customer Attrition
    {
      from: 'gold.fact_customer_attrition',
      to: 'gold.dim_retail_customer',
      type: 'many-to-one',
      foreignKey: 'customer_key',
      description: 'Customer dimension',
    },
    {
      from: 'gold.fact_customer_attrition',
      to: 'gold.dim_date',
      type: 'many-to-one',
      foreignKey: 'attrition_date_key',
      description: 'Attrition date',
    },
    // Fact: Credit Bureau Pulls
    {
      from: 'gold.fact_credit_bureau_pulls',
      to: 'gold.dim_retail_customer',
      type: 'many-to-one',
      foreignKey: 'customer_key',
      description: 'Customer dimension',
    },
    {
      from: 'gold.fact_credit_bureau_pulls',
      to: 'gold.dim_date',
      type: 'many-to-one',
      foreignKey: 'pull_date_key',
      description: 'Pull date',
    },
    // Fact: KYC Reviews
    {
      from: 'gold.fact_kyc_reviews',
      to: 'gold.dim_retail_customer',
      type: 'many-to-one',
      foreignKey: 'customer_key',
      description: 'Customer dimension',
    },
    {
      from: 'gold.fact_kyc_reviews',
      to: 'gold.dim_date',
      type: 'many-to-one',
      foreignKey: 'review_date_key',
      description: 'Review date',
    },
    {
      from: 'gold.fact_kyc_reviews',
      to: 'gold.dim_risk_rating',
      type: 'many-to-one',
      foreignKey: 'risk_rating_key',
      description: 'Risk rating',
    },
    // Dimension Hierarchies
    {
      from: 'gold.dim_retail_customer',
      to: 'gold.dim_household',
      type: 'many-to-one',
      foreignKey: 'household_key',
      description: 'Customer belongs to household',
    },
    {
      from: 'gold.dim_retail_customer',
      to: 'gold.dim_customer_segment',
      type: 'many-to-one',
      foreignKey: 'segment_key',
      description: 'Customer segment',
    },
    {
      from: 'gold.dim_retail_customer',
      to: 'gold.dim_lifecycle_stage',
      type: 'many-to-one',
      foreignKey: 'lifecycle_key',
      description: 'Lifecycle stage',
    },
    {
      from: 'gold.dim_retail_customer',
      to: 'gold.dim_customer_tier',
      type: 'many-to-one',
      foreignKey: 'tier_key',
      description: 'Customer tier',
    },
    {
      from: 'gold.dim_retail_customer',
      to: 'gold.dim_geography',
      type: 'many-to-one',
      foreignKey: 'geography_key',
      description: 'Geographic location',
    },
    {
      from: 'gold.dim_retail_customer',
      to: 'gold.dim_branch',
      type: 'many-to-one',
      foreignKey: 'primary_branch_key',
      description: 'Primary branch',
    },
    {
      from: 'gold.dim_retail_customer',
      to: 'gold.dim_risk_rating',
      type: 'many-to-one',
      foreignKey: 'risk_rating_key',
      description: 'Risk rating',
    },
    {
      from: 'gold.dim_household',
      to: 'gold.dim_branch',
      type: 'many-to-one',
      foreignKey: 'primary_branch_key',
      description: 'Household primary branch',
    },
  ],
};

// ERD Visualization Metadata
export const customerRetailERDVisualization = {
  layoutEngine: 'dagre',
  direction: 'TB',
  nodeSpacing: 100,
  rankSpacing: 150,
  
  entityGroups: [
    { name: 'Core Entities', color: '#3B82F6', entities: ['Customer', 'Household'] },
    { name: 'Supporting', color: '#10B981', entities: ['Customer Preference', 'Customer Score'] },
    { name: 'Events', color: '#F59E0B', entities: ['Customer Event'] },
    { name: 'Relationships', color: '#8B5CF6', entities: ['Customer Relationship'] },
    { name: 'External', color: '#EF4444', entities: ['Credit Report', 'Identity Document'] },
  ],
  
  keyRelationships: [
    { name: 'Customer-Household', strength: 'strong', businessImportance: 'high' },
    { name: 'Customer-Events', strength: 'medium', businessImportance: 'high' },
    { name: 'Customer-Scores', strength: 'strong', businessImportance: 'critical' },
  ],
};

export default {
  customerRetailLogicalERD,
  customerRetailPhysicalERD,
  customerRetailSilverERD,
  customerRetailGoldERD,
  customerRetailERDVisualization,
};
