/**
 * DEPOSITS-RETAIL ERD DEFINITIONS - 100% ACCURATE
 * 
 * Complete Entity Relationship Diagrams covering Bronze, Silver, and Gold layers
 * Based on comprehensive data model with 20 Bronze + 15 Silver + 16 Gold tables
 * 
 * Sources: FIS Core Banking, Temenos T24, Jack Henry Silverlake
 * 
 * Domain: Deposits Retail
 * Area: Retail Banking
 * Coverage: Checking (DDA), Savings, Money Market, CDs, NOWs
 */

// LOGICAL ERD - Business Model
export const depositsRetailLogicalERD = {
  description: 'Deposits domain logical model - business perspective',
  totalEntities: 12,
  
  entities: [
    {
      name: 'Deposit Account',
      type: 'core',
      description: 'Checking, savings, money market, and CD accounts',
      keyAttributes: ['account_id', 'account_number', 'account_type', 'current_balance'],
      businessRules: [
        'Minimum balance requirements vary by product type',
        'Savings accounts subject to Regulation D (6 withdrawals/month limit)',
        'CDs have early withdrawal penalties',
        'Overdraft protection requires enrollment and eligible linked account',
        'FDIC insurance covers up to $250,000 per depositor per institution',
      ],
      attributes: [
        { name: 'account_id', type: 'BIGINT', isPrimaryKey: true, description: 'Unique account identifier' },
        { name: 'account_number', type: 'STRING', description: 'Customer-facing account number (10-12 digits)' },
        { name: 'account_type', type: 'STRING', description: 'DDA|Savings|MoneyMarket|CD|NOW|SuperNOW' },
        { name: 'account_subtype', type: 'STRING', description: 'Basic Checking|Premium Checking|Student|Senior Savings' },
        { name: 'product_code', type: 'STRING', description: 'Internal product SKU' },
        { name: 'product_name', type: 'STRING', description: 'Marketing product name' },
        { name: 'account_status', type: 'STRING', description: 'Active|Inactive|Dormant|Closed|Frozen|Restricted' },
        { name: 'account_open_date', type: 'DATE', description: 'Account opening date' },
        { name: 'account_close_date', type: 'DATE', description: 'Closure date if closed' },
        { name: 'account_maturity_date', type: 'DATE', description: 'CD maturity date' },
        { name: 'primary_customer_id', type: 'BIGINT', isForeignKey: true, references: 'Customer', description: 'Primary account holder' },
        { name: 'ownership_type', type: 'STRING', description: 'Individual|Joint|POD|TOD|Trust|Custodial' },
        { name: 'current_balance', type: 'DECIMAL(18,2)', description: 'Current ledger balance' },
        { name: 'available_balance', type: 'DECIMAL(18,2)', description: 'Available for withdrawal (current - holds)' },
        { name: 'interest_rate_current', type: 'DECIMAL(10,6)', description: 'Current APY' },
        { name: 'interest_accrued_ytd', type: 'DECIMAL(18,2)', description: 'Interest earned YTD' },
        { name: 'monthly_service_fee', type: 'DECIMAL(18,2)', description: 'Monthly maintenance fee' },
        { name: 'overdraft_protection', type: 'BOOLEAN', description: 'Overdraft protection enrolled' },
        { name: 'overdraft_limit', type: 'DECIMAL(18,2)', description: 'Overdraft limit amount' },
        { name: 'minimum_balance_required', type: 'DECIMAL(18,2)', description: 'Minimum balance to avoid fees' },
      ],
    },
    {
      name: 'Account Transaction',
      type: 'event',
      description: 'All deposit/withdrawal/transfer transactions',
      keyAttributes: ['transaction_id', 'account_id', 'transaction_date', 'transaction_type', 'amount'],
      businessRules: [
        'Transactions must balance (debits = credits for transfers)',
        'Pending transactions affect available balance but not current balance',
        'Reversals create offsetting transaction',
        'Cash transactions >$10,000 require CTR filing',
      ],
      attributes: [
        { name: 'transaction_id', type: 'BIGINT', isPrimaryKey: true },
        { name: 'account_id', type: 'BIGINT', isForeignKey: true, references: 'Deposit Account' },
        { name: 'transaction_date', type: 'DATE', description: 'Transaction date' },
        { name: 'transaction_timestamp', type: 'TIMESTAMP', description: 'Exact transaction time' },
        { name: 'post_date', type: 'DATE', description: 'Date transaction posted to account' },
        { name: 'transaction_type', type: 'STRING', description: 'Deposit|Withdrawal|Transfer|Fee|Interest|Reversal' },
        { name: 'transaction_subtype', type: 'STRING', description: 'ATM|Check|ACH|Wire|P2P|Branch|Card' },
        { name: 'transaction_amount', type: 'DECIMAL(18,2)', description: 'Transaction amount' },
        { name: 'running_balance', type: 'DECIMAL(18,2)', description: 'Balance after transaction' },
        { name: 'transaction_status', type: 'STRING', description: 'Posted|Pending|Reversed|Failed' },
        { name: 'description', type: 'STRING', description: 'Transaction description' },
        { name: 'transaction_channel', type: 'STRING', description: 'Branch|ATM|Online|Mobile|Phone' },
        { name: 'reversal_flag', type: 'BOOLEAN', description: 'Is this a reversal transaction' },
        { name: 'hold_amount', type: 'DECIMAL(18,2)', description: 'Funds on hold' },
      ],
    },
    {
      name: 'Account Holder',
      type: 'associative',
      description: 'Account ownership mapping (supports joint accounts, beneficiaries)',
      keyAttributes: ['account_holder_id', 'account_id', 'customer_id'],
      businessRules: [
        'Joint accounts have multiple holders with ownership percentages summing to 100%',
        'POD/TOD beneficiaries have no access until primary holder death',
        'Authorized signers can transact but have no ownership',
      ],
      attributes: [
        { name: 'account_holder_id', type: 'BIGINT', isPrimaryKey: true },
        { name: 'account_id', type: 'BIGINT', isForeignKey: true, references: 'Deposit Account' },
        { name: 'customer_id', type: 'BIGINT', isForeignKey: true, references: 'Customer' },
        { name: 'holder_type', type: 'STRING', description: 'Primary|Joint Owner|Beneficiary|Authorized Signer|POA' },
        { name: 'ownership_percentage', type: 'DECIMAL(5,2)', description: 'Ownership % for joint accounts' },
        { name: 'signing_authority', type: 'BOOLEAN', description: 'Can sign on behalf of account' },
        { name: 'withdrawal_authority', type: 'BOOLEAN', description: 'Can withdraw funds' },
        { name: 'added_date', type: 'DATE', description: 'Date added to account' },
      ],
    },
    {
      name: 'Interest Rate',
      type: 'configuration',
      description: 'Interest rate tiers and history',
      keyAttributes: ['rate_id', 'product_code', 'effective_date'],
      attributes: [
        { name: 'rate_id', type: 'BIGINT', isPrimaryKey: true },
        { name: 'product_code', type: 'STRING', description: 'Product this rate applies to' },
        { name: 'account_id', type: 'BIGINT', description: 'NULL for product rates, specific for account overrides' },
        { name: 'effective_date', type: 'DATE', description: 'Rate effective date' },
        { name: 'end_date', type: 'DATE', description: 'Rate expiration date' },
        { name: 'rate_tier', type: 'INTEGER', description: 'Tier level (1-10)' },
        { name: 'balance_minimum', type: 'DECIMAL(18,2)', description: 'Minimum balance for tier' },
        { name: 'balance_maximum', type: 'DECIMAL(18,2)', description: 'Maximum balance for tier' },
        { name: 'interest_rate', type: 'DECIMAL(10,6)', description: 'APY rate' },
        { name: 'rate_type', type: 'STRING', description: 'Fixed|Variable|Promotional' },
      ],
    },
    {
      name: 'Account Statement',
      type: 'document',
      description: 'Monthly account statements',
      keyAttributes: ['statement_id', 'account_id', 'statement_date'],
      attributes: [
        { name: 'statement_id', type: 'BIGINT', isPrimaryKey: true },
        { name: 'account_id', type: 'BIGINT', isForeignKey: true, references: 'Deposit Account' },
        { name: 'statement_date', type: 'DATE', description: 'Statement generation date' },
        { name: 'statement_period_start', type: 'DATE' },
        { name: 'statement_period_end', type: 'DATE' },
        { name: 'beginning_balance', type: 'DECIMAL(18,2)' },
        { name: 'ending_balance', type: 'DECIMAL(18,2)' },
        { name: 'total_deposits', type: 'DECIMAL(18,2)' },
        { name: 'total_withdrawals', type: 'DECIMAL(18,2)' },
        { name: 'total_fees', type: 'DECIMAL(18,2)' },
        { name: 'interest_paid', type: 'DECIMAL(18,2)' },
        { name: 'total_transactions', type: 'INTEGER' },
      ],
    },
    {
      name: 'Overdraft Event',
      type: 'event',
      description: 'Overdraft occurrences and coverage',
      keyAttributes: ['overdraft_id', 'account_id', 'overdraft_date'],
      businessRules: [
        'Overdraft protection can be from linked savings, line of credit, or credit card',
        'Standard overdraft fee applies if no protection or protection insufficient',
        'NSF fee charged if item returned unpaid',
      ],
      attributes: [
        { name: 'overdraft_id', type: 'BIGINT', isPrimaryKey: true },
        { name: 'account_id', type: 'BIGINT', isForeignKey: true, references: 'Deposit Account' },
        { name: 'overdraft_date', type: 'DATE' },
        { name: 'overdraft_amount', type: 'DECIMAL(18,2)' },
        { name: 'trigger_transaction_id', type: 'BIGINT', isForeignKey: true, description: 'Transaction that caused overdraft' },
        { name: 'overdraft_protection_type', type: 'STRING', description: 'None|Linked Account|Line of Credit|Standard' },
        { name: 'coverage_amount', type: 'DECIMAL(18,2)' },
        { name: 'nsf_fee', type: 'DECIMAL(10,2)', description: 'NSF fee if applicable' },
        { name: 'overdraft_fee', type: 'DECIMAL(10,2)', description: 'Overdraft fee charged' },
        { name: 'cleared_date', type: 'DATE', description: 'Date overdraft cleared' },
      ],
    },
    {
      name: 'Account Transfer',
      type: 'event',
      description: 'Internal and external account transfers',
      keyAttributes: ['transfer_id', 'from_account_id', 'to_account_id'],
      attributes: [
        { name: 'transfer_id', type: 'BIGINT', isPrimaryKey: true },
        { name: 'from_account_id', type: 'BIGINT', isForeignKey: true, description: 'Source account' },
        { name: 'to_account_id', type: 'BIGINT', isForeignKey: true, description: 'Destination account' },
        { name: 'transfer_date', type: 'DATE' },
        { name: 'transfer_amount', type: 'DECIMAL(18,2)' },
        { name: 'transfer_type', type: 'STRING', description: 'Internal|External|ACH|Wire' },
        { name: 'transfer_status', type: 'STRING', description: 'Pending|Completed|Failed|Cancelled' },
        { name: 'initiated_by', type: 'STRING', description: 'Customer|System|Employee' },
        { name: 'is_recurring', type: 'BOOLEAN' },
      ],
    },
    {
      name: 'Check',
      type: 'event',
      description: 'Check transactions and clearing',
      keyAttributes: ['check_id', 'account_id', 'check_number'],
      attributes: [
        { name: 'check_id', type: 'BIGINT', isPrimaryKey: true },
        { name: 'account_id', type: 'BIGINT', isForeignKey: true, references: 'Deposit Account' },
        { name: 'check_number', type: 'STRING' },
        { name: 'check_amount', type: 'DECIMAL(18,2)' },
        { name: 'check_date', type: 'DATE' },
        { name: 'clear_date', type: 'DATE' },
        { name: 'payee_name', type: 'STRING' },
        { name: 'check_status', type: 'STRING', description: 'Cleared|Pending|Returned|Stop Payment|Void' },
      ],
    },
    {
      name: 'Hold',
      type: 'event',
      description: 'Funds on hold (Regulation CC)',
      keyAttributes: ['hold_id', 'account_id'],
      businessRules: [
        'Regulation CC governs hold periods for check deposits',
        'New accounts may have extended hold periods',
        'Large deposits may have partial holds',
      ],
      attributes: [
        { name: 'hold_id', type: 'BIGINT', isPrimaryKey: true },
        { name: 'account_id', type: 'BIGINT', isForeignKey: true, references: 'Deposit Account' },
        { name: 'hold_placed_date', type: 'DATE' },
        { name: 'hold_release_date', type: 'DATE' },
        { name: 'hold_amount', type: 'DECIMAL(18,2)' },
        { name: 'hold_type', type: 'STRING', description: 'Check Hold|Deposit Hold|Legal Hold|Fraud Hold' },
        { name: 'hold_reason', type: 'STRING' },
        { name: 'hold_status', type: 'STRING', description: 'Active|Released|Expired' },
      ],
    },
    {
      name: 'Fee Assessment',
      type: 'event',
      description: 'Fees charged on deposit accounts',
      keyAttributes: ['fee_id', 'account_id', 'fee_date'],
      attributes: [
        { name: 'fee_id', type: 'BIGINT', isPrimaryKey: true },
        { name: 'account_id', type: 'BIGINT', isForeignKey: true, references: 'Deposit Account' },
        { name: 'fee_date', type: 'DATE' },
        { name: 'fee_type', type: 'STRING', description: 'Monthly|Overdraft|NSF|ATM|Wire|Stop Payment|Paper Statement' },
        { name: 'fee_amount', type: 'DECIMAL(10,2)' },
        { name: 'fee_waived', type: 'BOOLEAN' },
        { name: 'waiver_reason', type: 'STRING' },
      ],
    },
    {
      name: 'Interest Accrual',
      type: 'event',
      description: 'Daily interest accruals',
      keyAttributes: ['accrual_id', 'account_id', 'accrual_date'],
      attributes: [
        { name: 'accrual_id', type: 'BIGINT', isPrimaryKey: true },
        { name: 'account_id', type: 'BIGINT', isForeignKey: true, references: 'Deposit Account' },
        { name: 'accrual_date', type: 'DATE' },
        { name: 'interest_rate', type: 'DECIMAL(10,6)' },
        { name: 'balance_for_interest', type: 'DECIMAL(18,2)' },
        { name: 'interest_earned', type: 'DECIMAL(18,2)' },
        { name: 'interest_accrued_mtd', type: 'DECIMAL(18,2)' },
        { name: 'interest_paid', type: 'DECIMAL(18,2)' },
      ],
    },
    {
      name: 'Regulatory Event',
      type: 'compliance',
      description: 'Regulatory compliance events (Reg D violations, CTR, SAR)',
      keyAttributes: ['regulatory_event_id', 'account_id'],
      businessRules: [
        'Reg D limits savings/MMA to 6 convenience withdrawals per month',
        'CTR required for cash transactions >$10,000',
        'SAR required for suspicious activity',
      ],
      attributes: [
        { name: 'regulatory_event_id', type: 'BIGINT', isPrimaryKey: true },
        { name: 'account_id', type: 'BIGINT', isForeignKey: true, references: 'Deposit Account' },
        { name: 'event_date', type: 'DATE' },
        { name: 'event_type', type: 'STRING', description: 'Reg D Violation|CTR|SAR|Large Cash' },
        { name: 'regulation', type: 'STRING', description: 'Reg D|BSA|OFAC' },
        { name: 'filing_required', type: 'BOOLEAN' },
        { name: 'filing_date', type: 'DATE' },
      ],
    },
  ],
  
  relationships: [
    {
      from: 'Account Transaction',
      to: 'Deposit Account',
      type: 'many-to-one',
      cardinality: 'N:1',
      foreignKey: 'account_id',
      description: 'Each transaction belongs to one account',
    },
    {
      from: 'Account Holder',
      to: 'Deposit Account',
      type: 'many-to-one',
      cardinality: 'N:1',
      foreignKey: 'account_id',
      description: 'Multiple holders per account (joint ownership)',
    },
    {
      from: 'Account Holder',
      to: 'Customer',
      type: 'many-to-one',
      cardinality: 'N:1',
      foreignKey: 'customer_id',
      description: 'Each holder references a customer',
    },
    {
      from: 'Interest Rate',
      to: 'Deposit Account',
      type: 'many-to-one',
      cardinality: 'N:1',
      foreignKey: 'account_id',
      description: 'Rate history per account',
    },
    {
      from: 'Account Statement',
      to: 'Deposit Account',
      type: 'many-to-one',
      cardinality: 'N:1',
      foreignKey: 'account_id',
      description: 'Monthly statements per account',
    },
    {
      from: 'Overdraft Event',
      to: 'Deposit Account',
      type: 'many-to-one',
      cardinality: 'N:1',
      foreignKey: 'account_id',
      description: 'Overdraft events per account',
    },
    {
      from: 'Overdraft Event',
      to: 'Account Transaction',
      type: 'many-to-one',
      cardinality: 'N:1',
      foreignKey: 'trigger_transaction_id',
      description: 'Transaction that caused overdraft',
    },
    {
      from: 'Account Transfer',
      to: 'Deposit Account',
      type: 'many-to-one',
      cardinality: 'N:2',
      foreignKey: 'from_account_id, to_account_id',
      description: 'Transfer links two accounts',
    },
    {
      from: 'Check',
      to: 'Deposit Account',
      type: 'many-to-one',
      cardinality: 'N:1',
      foreignKey: 'account_id',
      description: 'Checks drawn on account',
    },
    {
      from: 'Hold',
      to: 'Deposit Account',
      type: 'many-to-one',
      cardinality: 'N:1',
      foreignKey: 'account_id',
      description: 'Holds placed on account',
    },
    {
      from: 'Fee Assessment',
      to: 'Deposit Account',
      type: 'many-to-one',
      cardinality: 'N:1',
      foreignKey: 'account_id',
      description: 'Fees charged to account',
    },
    {
      from: 'Interest Accrual',
      to: 'Deposit Account',
      type: 'many-to-one',
      cardinality: 'N:1',
      foreignKey: 'account_id',
      description: 'Daily interest accruals',
    },
    {
      from: 'Regulatory Event',
      to: 'Deposit Account',
      type: 'many-to-one',
      cardinality: 'N:1',
      foreignKey: 'account_id',
      description: 'Compliance events per account',
    },
  ],
};

// PHYSICAL ERD - Bronze Layer (20 Tables)
export const depositsRetailPhysicalERD = {
  description: 'Deposits domain physical model - Bronze layer (raw data from source systems)',
  totalTables: 20,
  dataVolume: '2.5TB',
  
  tables: [
    {
      name: 'bronze.retail_deposit_account_master',
      description: 'Core deposit account data including checking, savings, money market, and CDs',
      sourceSystem: 'FIS_CORE',
      loadType: 'CDC',
      estimatedRows: 100000000,
      avgRowSize: 2048,
      partitionKey: 'account_id',
      clusterKey: ['account_open_date'],
      primaryKey: ['account_id', 'source_system'],
      uniqueKeys: [['account_number'], ['account_uuid']],
      indexes: [
        { name: 'idx_customer', columns: ['primary_customer_id'], type: 'BTREE' },
        { name: 'idx_status', columns: ['account_status'], type: 'BTREE' },
        { name: 'idx_type', columns: ['account_type'], type: 'BTREE' },
        { name: 'idx_open_date', columns: ['account_open_date'], type: 'BTREE' },
      ],
      totalColumns: 120,
      keyColumns: ['account_id', 'account_number', 'primary_customer_id', 'account_type', 'account_status', 'current_balance'],
    },
    {
      name: 'bronze.retail_deposit_transactions',
      description: 'Deposit account transaction history (deposits, withdrawals, transfers)',
      sourceSystem: 'FIS_CORE',
      estimatedRows: 5000000000,
      avgRowSize: 512,
      partitionKey: 'transaction_date',
      primaryKey: ['transaction_id', 'source_system'],
      indexes: [
        { name: 'idx_account_date', columns: ['account_id', 'transaction_date'], type: 'BTREE' },
        { name: 'idx_type', columns: ['transaction_type'], type: 'BTREE' },
      ],
      totalColumns: 45,
    },
    {
      name: 'bronze.retail_deposit_account_holders',
      description: 'Account ownership and authorized signers (joint accounts, beneficiaries)',
      sourceSystem: 'FIS_CORE',
      estimatedRows: 150000000,
      primaryKey: ['account_holder_id', 'source_system'],
      indexes: [
        { name: 'idx_account', columns: ['account_id'], type: 'BTREE' },
        { name: 'idx_customer', columns: ['customer_id'], type: 'BTREE' },
      ],
      totalColumns: 22,
    },
    {
      name: 'bronze.retail_deposit_account_balances_daily',
      description: 'Daily account balance snapshots',
      sourceSystem: 'FIS_CORE',
      estimatedRows: 3650000000,
      partitionKey: 'balance_date',
      primaryKey: ['account_id', 'balance_date', 'source_system'],
      totalColumns: 28,
    },
    {
      name: 'bronze.retail_deposit_interest_rates',
      description: 'Interest rate tiers and history',
      sourceSystem: 'FIS_CORE',
      estimatedRows: 20000000,
      primaryKey: ['rate_id', 'source_system'],
      totalColumns: 18,
    },
    {
      name: 'bronze.retail_deposit_interest_accruals',
      description: 'Daily interest accruals',
      sourceSystem: 'FIS_CORE',
      estimatedRows: 1825000000,
      partitionKey: 'accrual_date',
      primaryKey: ['account_id', 'accrual_date', 'source_system'],
      totalColumns: 16,
    },
    {
      name: 'bronze.retail_deposit_statements',
      description: 'Monthly account statements',
      sourceSystem: 'FIS_CORE',
      estimatedRows: 1200000000,
      partitionKey: 'statement_date',
      primaryKey: ['statement_id', 'source_system'],
      totalColumns: 26,
    },
    {
      name: 'bronze.retail_deposit_fees',
      description: 'Fees charged to deposit accounts',
      sourceSystem: 'FIS_CORE',
      estimatedRows: 500000000,
      partitionKey: 'fee_date',
      primaryKey: ['fee_id', 'source_system'],
      totalColumns: 18,
    },
    {
      name: 'bronze.retail_deposit_overdrafts',
      description: 'Overdraft events and coverage details',
      sourceSystem: 'FIS_CORE',
      estimatedRows: 100000000,
      partitionKey: 'overdraft_date',
      primaryKey: ['overdraft_id', 'source_system'],
      totalColumns: 24,
    },
    {
      name: 'bronze.retail_deposit_transfers',
      description: 'Internal and external account transfers',
      sourceSystem: 'FIS_CORE',
      estimatedRows: 800000000,
      partitionKey: 'transfer_date',
      primaryKey: ['transfer_id', 'source_system'],
      totalColumns: 28,
    },
    {
      name: 'bronze.retail_deposit_checks',
      description: 'Check transactions and clearing',
      sourceSystem: 'FIS_CORE',
      estimatedRows: 600000000,
      partitionKey: 'check_date',
      primaryKey: ['check_id', 'source_system'],
      totalColumns: 22,
    },
    {
      name: 'bronze.retail_deposit_holds',
      description: 'Funds on hold (Regulation CC)',
      sourceSystem: 'FIS_CORE',
      estimatedRows: 200000000,
      primaryKey: ['hold_id', 'source_system'],
      totalColumns: 18,
    },
    {
      name: 'bronze.retail_deposit_rate_changes',
      description: 'Interest rate change history',
      sourceSystem: 'FIS_CORE',
      estimatedRows: 50000000,
      primaryKey: ['rate_change_id', 'source_system'],
      totalColumns: 16,
    },
    {
      name: 'bronze.retail_deposit_product_catalog',
      description: 'Deposit product definitions and features',
      sourceSystem: 'PRODUCT_CATALOG',
      estimatedRows: 500,
      primaryKey: ['product_code', 'source_system'],
      totalColumns: 32,
    },
    {
      name: 'bronze.retail_deposit_reg_d_violations',
      description: 'Regulation D violation tracking (savings withdrawal limits)',
      sourceSystem: 'COMPLIANCE_SYSTEM',
      estimatedRows: 20000000,
      primaryKey: ['violation_id', 'source_system'],
      totalColumns: 14,
    },
    {
      name: 'bronze.retail_deposit_account_events',
      description: 'Account lifecycle events (opened, closed, status changes)',
      sourceSystem: 'FIS_CORE',
      estimatedRows: 250000000,
      partitionKey: 'event_date',
      primaryKey: ['event_id', 'source_system'],
      totalColumns: 16,
    },
    {
      name: 'bronze.retail_deposit_cd_maturity',
      description: 'CD maturity tracking and renewal',
      sourceSystem: 'FIS_CORE',
      estimatedRows: 15000000,
      primaryKey: ['cd_account_id', 'source_system'],
      totalColumns: 20,
    },
    {
      name: 'bronze.retail_deposit_atm_transactions',
      description: 'ATM withdrawal and deposit transactions',
      sourceSystem: 'ATM_NETWORK',
      estimatedRows: 1000000000,
      partitionKey: 'transaction_date',
      primaryKey: ['atm_transaction_id', 'source_system'],
      totalColumns: 28,
    },
    {
      name: 'bronze.retail_deposit_ach_transactions',
      description: 'ACH transaction details',
      sourceSystem: 'ACH_PROCESSOR',
      estimatedRows: 2000000000,
      partitionKey: 'transaction_date',
      primaryKey: ['ach_transaction_id', 'source_system'],
      totalColumns: 32,
    },
    {
      name: 'bronze.retail_deposit_wire_transfers',
      description: 'Wire transfer details (incoming and outgoing)',
      sourceSystem: 'WIRE_SYSTEM',
      estimatedRows: 50000000,
      partitionKey: 'transfer_date',
      primaryKey: ['wire_id', 'source_system'],
      totalColumns: 36,
    },
  ],
  
  relationships: [
    // Account Master Relationships
    {
      from: 'bronze.retail_deposit_transactions',
      to: 'bronze.retail_deposit_account_master',
      type: 'many-to-one',
      foreignKey: 'account_id',
      indexSupport: 'idx_account_date on transactions',
      description: 'Each transaction belongs to one account',
    },
    {
      from: 'bronze.retail_deposit_account_holders',
      to: 'bronze.retail_deposit_account_master',
      type: 'many-to-one',
      foreignKey: 'account_id',
      description: 'Account ownership mapping',
    },
    {
      from: 'bronze.retail_deposit_account_holders',
      to: 'bronze.retail_customer_master',
      type: 'many-to-one',
      foreignKey: 'customer_id',
      description: 'Links to customer domain',
    },
    {
      from: 'bronze.retail_deposit_account_balances_daily',
      to: 'bronze.retail_deposit_account_master',
      type: 'many-to-one',
      foreignKey: 'account_id',
      description: 'Daily balance snapshots per account',
    },
    {
      from: 'bronze.retail_deposit_interest_rates',
      to: 'bronze.retail_deposit_product_catalog',
      type: 'many-to-one',
      foreignKey: 'product_code',
      description: 'Rate tiers by product',
    },
    {
      from: 'bronze.retail_deposit_interest_rates',
      to: 'bronze.retail_deposit_account_master',
      type: 'many-to-one',
      foreignKey: 'account_id',
      description: 'Account-specific rate overrides',
      optional: true,
    },
    {
      from: 'bronze.retail_deposit_interest_accruals',
      to: 'bronze.retail_deposit_account_master',
      type: 'many-to-one',
      foreignKey: 'account_id',
      description: 'Daily interest calculations',
    },
    {
      from: 'bronze.retail_deposit_statements',
      to: 'bronze.retail_deposit_account_master',
      type: 'many-to-one',
      foreignKey: 'account_id',
      description: 'Monthly statements per account',
    },
    {
      from: 'bronze.retail_deposit_fees',
      to: 'bronze.retail_deposit_account_master',
      type: 'many-to-one',
      foreignKey: 'account_id',
      description: 'Fee assessments',
    },
    {
      from: 'bronze.retail_deposit_fees',
      to: 'bronze.retail_deposit_transactions',
      type: 'many-to-one',
      foreignKey: 'triggering_transaction_id',
      description: 'Transaction that triggered fee',
      optional: true,
    },
    {
      from: 'bronze.retail_deposit_overdrafts',
      to: 'bronze.retail_deposit_account_master',
      type: 'many-to-one',
      foreignKey: 'account_id',
      description: 'Overdraft events per account',
    },
    {
      from: 'bronze.retail_deposit_overdrafts',
      to: 'bronze.retail_deposit_transactions',
      type: 'many-to-one',
      foreignKey: 'trigger_transaction_id',
      description: 'Transaction that caused overdraft',
    },
    {
      from: 'bronze.retail_deposit_transfers',
      to: 'bronze.retail_deposit_account_master',
      type: 'many-to-one',
      foreignKey: 'from_account_id',
      description: 'Source account for transfer',
    },
    {
      from: 'bronze.retail_deposit_transfers',
      to: 'bronze.retail_deposit_account_master',
      type: 'many-to-one',
      foreignKey: 'to_account_id',
      description: 'Destination account for transfer',
    },
    {
      from: 'bronze.retail_deposit_checks',
      to: 'bronze.retail_deposit_account_master',
      type: 'many-to-one',
      foreignKey: 'account_id',
      description: 'Checks drawn on account',
    },
    {
      from: 'bronze.retail_deposit_holds',
      to: 'bronze.retail_deposit_account_master',
      type: 'many-to-one',
      foreignKey: 'account_id',
      description: 'Funds on hold',
    },
    {
      from: 'bronze.retail_deposit_holds',
      to: 'bronze.retail_deposit_transactions',
      type: 'many-to-one',
      foreignKey: 'related_transaction_id',
      description: 'Transaction that triggered hold',
    },
    {
      from: 'bronze.retail_deposit_rate_changes',
      to: 'bronze.retail_deposit_account_master',
      type: 'many-to-one',
      foreignKey: 'account_id',
      description: 'Rate change history per account',
    },
    {
      from: 'bronze.retail_deposit_account_master',
      to: 'bronze.retail_deposit_product_catalog',
      type: 'many-to-one',
      foreignKey: 'product_code',
      description: 'Product features and configuration',
    },
    {
      from: 'bronze.retail_deposit_reg_d_violations',
      to: 'bronze.retail_deposit_account_master',
      type: 'many-to-one',
      foreignKey: 'account_id',
      description: 'Regulation D compliance tracking',
    },
    {
      from: 'bronze.retail_deposit_account_events',
      to: 'bronze.retail_deposit_account_master',
      type: 'many-to-one',
      foreignKey: 'account_id',
      description: 'Lifecycle events (open, close, status changes)',
    },
    {
      from: 'bronze.retail_deposit_cd_maturity',
      to: 'bronze.retail_deposit_account_master',
      type: 'one-to-one',
      foreignKey: 'cd_account_id',
      description: 'CD-specific maturity tracking',
    },
    {
      from: 'bronze.retail_deposit_atm_transactions',
      to: 'bronze.retail_deposit_account_master',
      type: 'many-to-one',
      foreignKey: 'account_id',
      description: 'ATM withdrawals and deposits',
    },
    {
      from: 'bronze.retail_deposit_atm_transactions',
      to: 'bronze.retail_deposit_transactions',
      type: 'one-to-one',
      foreignKey: 'transaction_id',
      description: 'Links to main transaction record',
    },
    {
      from: 'bronze.retail_deposit_ach_transactions',
      to: 'bronze.retail_deposit_account_master',
      type: 'many-to-one',
      foreignKey: 'account_id',
      description: 'ACH transaction details',
    },
    {
      from: 'bronze.retail_deposit_ach_transactions',
      to: 'bronze.retail_deposit_transactions',
      type: 'one-to-one',
      foreignKey: 'transaction_id',
      description: 'Links to main transaction record',
    },
    {
      from: 'bronze.retail_deposit_wire_transfers',
      to: 'bronze.retail_deposit_account_master',
      type: 'many-to-one',
      foreignKey: 'account_id',
      description: 'Wire transfer details',
    },
    {
      from: 'bronze.retail_deposit_wire_transfers',
      to: 'bronze.retail_deposit_transactions',
      type: 'one-to-one',
      foreignKey: 'transaction_id',
      description: 'Links to main transaction record',
    },
  ],
};

// SILVER ERD - Cleansed and Conformed Data (15 Tables)
export const depositsRetailSilverERD = {
  description: 'Deposits domain silver layer - Conformed data with MDM and SCD Type 2',
  totalTables: 15,
  dataVolume: '1.8TB',
  
  tables: [
    {
      name: 'silver.retail_deposit_account_golden',
      description: 'Golden record for deposit accounts with MDM and SCD Type 2',
      grain: 'One row per account per effective date',
      scdType: 'Type 2',
      primaryKey: ['account_sk'],
      naturalKey: ['account_id'],
      estimatedRows: 120000000,
      keyFeatures: [
        'MDM survivorship rules applied',
        'SCD Type 2 for historical tracking',
        'Data quality scoring',
        'Standardized account categorization',
      ],
    },
    {
      name: 'silver.retail_deposit_balances_daily',
      description: 'Daily account balance snapshots with quality checks',
      grain: 'One row per account per day',
      scdType: 'Type 1',
      primaryKey: ['account_id', 'balance_date'],
      estimatedRows: 3650000000,
    },
    {
      name: 'silver.retail_deposit_transactions_conformed',
      description: 'Conformed deposit transactions with enrichment',
      grain: 'One row per transaction',
      scdType: 'Type 1',
      primaryKey: ['transaction_id'],
      estimatedRows: 5000000000,
      keyFeatures: [
        'Transaction categorization',
        'Merchant enrichment',
        'Balance validation',
        'Reversal linking',
      ],
    },
    {
      name: 'silver.retail_deposit_owners_golden',
      description: 'Account ownership with relationship types',
      grain: 'One row per account-owner relationship',
      scdType: 'Type 2',
      primaryKey: ['account_owner_sk'],
      estimatedRows: 180000000,
    },
    {
      name: 'silver.retail_deposit_interest_accruals',
      description: 'Daily interest accruals with rate tracking',
      grain: 'One row per account per day',
      scdType: 'Type 1',
      primaryKey: ['account_id', 'accrual_date'],
      estimatedRows: 1825000000,
    },
    {
      name: 'silver.retail_deposit_fees_assessed',
      description: 'Fees charged on deposit accounts',
      grain: 'One row per fee assessment',
      scdType: 'Type 1',
      primaryKey: ['fee_id'],
      estimatedRows: 500000000,
    },
    {
      name: 'silver.retail_deposit_statements_golden',
      description: 'Monthly account statements',
      grain: 'One row per account per statement period',
      scdType: 'Type 1',
      primaryKey: ['statement_id'],
      estimatedRows: 1200000000,
    },
    {
      name: 'silver.retail_deposit_overdrafts',
      description: 'Overdraft events and coverage',
      grain: 'One row per overdraft event',
      scdType: 'Type 1',
      primaryKey: ['overdraft_id'],
      estimatedRows: 100000000,
    },
    {
      name: 'silver.retail_deposit_transfers',
      description: 'Internal and external transfers',
      grain: 'One row per transfer',
      scdType: 'Type 1',
      primaryKey: ['transfer_id'],
      estimatedRows: 800000000,
    },
    {
      name: 'silver.retail_deposit_checks',
      description: 'Check transactions and clearing',
      grain: 'One row per check',
      scdType: 'Type 1',
      primaryKey: ['check_id'],
      estimatedRows: 600000000,
    },
    {
      name: 'silver.retail_deposit_holds',
      description: 'Funds on hold tracking',
      grain: 'One row per hold',
      scdType: 'Type 1',
      primaryKey: ['hold_id'],
      estimatedRows: 200000000,
    },
    {
      name: 'silver.retail_deposit_product_features',
      description: 'Product configuration and features per account',
      grain: 'One row per account per effective date',
      scdType: 'Type 2',
      primaryKey: ['account_product_sk'],
      estimatedRows: 150000000,
    },
    {
      name: 'silver.retail_deposit_rate_changes_history',
      description: 'Interest rate change history',
      grain: 'One row per rate change per account',
      scdType: 'Type 1',
      primaryKey: ['rate_change_id'],
      estimatedRows: 50000000,
    },
    {
      name: 'silver.retail_deposit_regulatory_events',
      description: 'Regulatory compliance events (Reg D, CTR, SAR)',
      grain: 'One row per regulatory event',
      scdType: 'Type 1',
      primaryKey: ['regulatory_event_id'],
      estimatedRows: 20000000,
    },
    {
      name: 'silver.retail_deposit_lifecycle_events',
      description: 'Account lifecycle milestones and status changes',
      grain: 'One row per lifecycle event',
      scdType: 'Type 1',
      primaryKey: ['lifecycle_event_id'],
      estimatedRows: 250000000,
    },
  ],

  relationships: [
    // Silver Layer Relationships
    {
      from: 'silver.retail_deposit_balances_daily',
      to: 'silver.retail_deposit_account_golden',
      type: 'many-to-one',
      foreignKey: 'account_id',
      description: 'Daily balances linked to golden account',
    },
    {
      from: 'silver.retail_deposit_transactions_conformed',
      to: 'silver.retail_deposit_account_golden',
      type: 'many-to-one',
      foreignKey: 'account_id',
      description: 'Transactions linked to golden account',
    },
    {
      from: 'silver.retail_deposit_owners_golden',
      to: 'silver.retail_deposit_account_golden',
      type: 'many-to-one',
      foreignKey: 'account_id',
      description: 'Account ownership mappings',
    },
    {
      from: 'silver.retail_deposit_owners_golden',
      to: 'silver.retail_customer_master_golden',
      type: 'many-to-one',
      foreignKey: 'customer_id',
      description: 'Links to customer golden record',
    },
    {
      from: 'silver.retail_deposit_interest_accruals',
      to: 'silver.retail_deposit_account_golden',
      type: 'many-to-one',
      foreignKey: 'account_id',
      description: 'Interest accruals per account',
    },
    {
      from: 'silver.retail_deposit_fees_assessed',
      to: 'silver.retail_deposit_account_golden',
      type: 'many-to-one',
      foreignKey: 'account_id',
      description: 'Fees linked to account',
    },
    {
      from: 'silver.retail_deposit_statements_golden',
      to: 'silver.retail_deposit_account_golden',
      type: 'many-to-one',
      foreignKey: 'account_id',
      description: 'Statements per account',
    },
    {
      from: 'silver.retail_deposit_overdrafts',
      to: 'silver.retail_deposit_account_golden',
      type: 'many-to-one',
      foreignKey: 'account_id',
      description: 'Overdraft events per account',
    },
    {
      from: 'silver.retail_deposit_transfers',
      to: 'silver.retail_deposit_account_golden',
      type: 'many-to-one',
      foreignKey: 'from_account_id',
      description: 'Source account for transfers',
    },
    {
      from: 'silver.retail_deposit_transfers',
      to: 'silver.retail_deposit_account_golden',
      type: 'many-to-one',
      foreignKey: 'to_account_id',
      description: 'Destination account for transfers',
    },
    {
      from: 'silver.retail_deposit_checks',
      to: 'silver.retail_deposit_account_golden',
      type: 'many-to-one',
      foreignKey: 'account_id',
      description: 'Checks per account',
    },
    {
      from: 'silver.retail_deposit_holds',
      to: 'silver.retail_deposit_account_golden',
      type: 'many-to-one',
      foreignKey: 'account_id',
      description: 'Holds per account',
    },
    {
      from: 'silver.retail_deposit_product_features',
      to: 'silver.retail_deposit_account_golden',
      type: 'one-to-one',
      foreignKey: 'account_id',
      description: 'Product features per account',
    },
    {
      from: 'silver.retail_deposit_rate_changes_history',
      to: 'silver.retail_deposit_account_golden',
      type: 'many-to-one',
      foreignKey: 'account_id',
      description: 'Rate changes per account',
    },
    {
      from: 'silver.retail_deposit_regulatory_events',
      to: 'silver.retail_deposit_account_golden',
      type: 'many-to-one',
      foreignKey: 'account_id',
      description: 'Compliance events per account',
    },
    {
      from: 'silver.retail_deposit_lifecycle_events',
      to: 'silver.retail_deposit_account_golden',
      type: 'many-to-one',
      foreignKey: 'account_id',
      description: 'Account lifecycle events',
    },
  ],
};

// GOLD ERD - Dimensional Model (Kimball Star Schema)
export const depositsRetailGoldERD = {
  description: 'Deposits domain gold layer - Kimball dimensional model',
  totalDimensions: 10,
  totalFacts: 6,
  dataVolume: '2TB',
  
  dimensions: [
    {
      name: 'gold.dim_retail_deposit_account',
      description: 'Deposit account dimension with full account attributes',
      grain: 'One row per unique deposit account',
      primaryKey: 'account_key',
      naturalKey: 'account_id',
      scdType: 'Type 1',
      estimatedRows: 100000000,
      attributes: [
        'account_id', 'account_number', 'account_type', 'account_subtype', 'product_code',
        'ownership_type', 'account_status', 'account_open_date', 'interest_bearing',
        'monthly_fee', 'overdraft_protection', 'online_enabled', 'mobile_enabled',
      ],
    },
    {
      name: 'gold.dim_transaction_type',
      description: 'Transaction type taxonomy',
      grain: 'One row per transaction type',
      primaryKey: 'transaction_type_key',
      scdType: 'Type 1',
      estimatedRows: 100,
      attributes: ['transaction_type_code', 'transaction_category', 'debit_credit_indicator'],
    },
    {
      name: 'gold.dim_deposit_product',
      description: 'Deposit product catalog',
      grain: 'One row per product per effective date',
      primaryKey: 'product_key',
      naturalKey: 'product_code',
      scdType: 'Type 2',
      estimatedRows: 1000,
      attributes: ['product_code', 'product_name', 'product_type', 'interest_bearing', 'minimum_balance', 'monthly_fee'],
    },
    {
      name: 'gold.dim_account_status',
      description: 'Account status taxonomy',
      grain: 'One row per status',
      primaryKey: 'account_status_key',
      scdType: 'Type 1',
      estimatedRows: 10,
    },
    {
      name: 'gold.dim_ownership_type',
      description: 'Account ownership types',
      grain: 'One row per ownership type',
      primaryKey: 'ownership_type_key',
      scdType: 'Type 1',
      estimatedRows: 10,
    },
    {
      name: 'gold.dim_channel',
      description: 'Transaction channel dimension',
      grain: 'One row per channel',
      primaryKey: 'channel_key',
      scdType: 'Type 1',
      estimatedRows: 20,
      attributes: ['channel_code', 'channel_name', 'is_digital', 'is_self_service'],
    },
    {
      name: 'gold.dim_branch',
      description: 'Branch dimension (conformed across domains)',
      grain: 'One row per branch',
      primaryKey: 'branch_key',
      naturalKey: 'branch_id',
      scdType: 'Type 2',
      estimatedRows: 5000,
    },
    {
      name: 'gold.dim_customer',
      description: 'Customer dimension (conformed across domains)',
      grain: 'One row per customer',
      primaryKey: 'customer_key',
      naturalKey: 'customer_id',
      scdType: 'Type 1',
      estimatedRows: 50000000,
    },
    {
      name: 'gold.dim_date',
      description: 'Date dimension (conformed)',
      grain: 'One row per day',
      primaryKey: 'date_key',
      scdType: 'Type 1',
      estimatedRows: 7305,
    },
    {
      name: 'gold.dim_time',
      description: 'Time of day dimension',
      grain: 'One row per minute',
      primaryKey: 'time_key',
      scdType: 'Type 1',
      estimatedRows: 1440,
    },
  ],
  
  facts: [
    {
      name: 'gold.fact_deposit_transactions',
      description: 'Deposit transaction fact (transaction grain)',
      factType: 'Transaction',
      grain: 'One row per transaction',
      estimatedRows: 5000000000,
      measures: [
        'transaction_amount',
        'balance_before',
        'balance_after',
        'fee_amount',
        'hold_amount',
      ],
      dimensions: [
        'account_key',
        'customer_key',
        'transaction_date_key',
        'transaction_time_key',
        'transaction_type_key',
        'channel_key',
        'branch_key',
      ],
    },
    {
      name: 'gold.fact_deposit_balances_daily',
      description: 'Daily account balance snapshot (periodic snapshot)',
      factType: 'Periodic Snapshot',
      grain: 'One row per account per day',
      estimatedRows: 3650000000,
      measures: [
        'opening_balance',
        'closing_balance',
        'average_balance',
        'minimum_balance',
        'maximum_balance',
        'total_deposits',
        'total_withdrawals',
        'interest_earned',
        'fees_charged',
        'transaction_count',
      ],
      dimensions: ['account_key', 'customer_key', 'date_key', 'product_key'],
    },
    {
      name: 'gold.fact_deposit_account_snapshot',
      description: 'Monthly account snapshot (periodic snapshot)',
      factType: 'Periodic Snapshot',
      grain: 'One row per account per month',
      estimatedRows: 1200000000,
      measures: [
        'month_end_balance',
        'average_daily_balance',
        'total_deposits_month',
        'total_withdrawals_month',
        'total_fees_month',
        'interest_earned_month',
        'transaction_count_month',
      ],
      dimensions: ['account_key', 'customer_key', 'date_key'],
    },
    {
      name: 'gold.fact_deposit_interest',
      description: 'Interest accruals and payments',
      factType: 'Transaction',
      grain: 'One row per interest payment',
      estimatedRows: 1200000000,
      measures: [
        'interest_rate',
        'balance_for_interest',
        'interest_accrued',
        'interest_paid',
      ],
      dimensions: ['account_key', 'customer_key', 'date_key', 'product_key'],
    },
    {
      name: 'gold.fact_deposit_fees',
      description: 'Fee assessments and waivers',
      factType: 'Transaction',
      grain: 'One row per fee assessment',
      estimatedRows: 500000000,
      measures: [
        'fee_amount',
        'fee_waived_amount',
        'net_fee_charged',
      ],
      dimensions: ['account_key', 'customer_key', 'fee_date_key', 'fee_type_key'],
    },
    {
      name: 'gold.fact_deposit_overdrafts',
      description: 'Overdraft events and fees',
      factType: 'Transaction',
      grain: 'One row per overdraft event',
      estimatedRows: 100000000,
      measures: [
        'overdraft_amount',
        'overdraft_count',
        'coverage_amount',
        'nsf_fee',
        'overdraft_fee',
        'total_fees',
        'days_overdrawn',
      ],
      dimensions: ['account_key', 'customer_key', 'overdraft_date_key', 'product_key'],
    },
  ],

  relationships: [
    // Gold Layer Fact-to-Dimension Relationships
    // Fact: Deposit Transactions
    {
      from: 'gold.fact_deposit_transactions',
      to: 'gold.dim_retail_deposit_account',
      type: 'many-to-one',
      foreignKey: 'account_key',
      description: 'Account dimension',
    },
    {
      from: 'gold.fact_deposit_transactions',
      to: 'gold.dim_retail_customer',
      type: 'many-to-one',
      foreignKey: 'customer_key',
      description: 'Customer dimension',
    },
    {
      from: 'gold.fact_deposit_transactions',
      to: 'gold.dim_date',
      type: 'many-to-one',
      foreignKey: 'transaction_date_key',
      description: 'Transaction date',
    },
    {
      from: 'gold.fact_deposit_transactions',
      to: 'gold.dim_time',
      type: 'many-to-one',
      foreignKey: 'transaction_time_key',
      description: 'Transaction time',
    },
    {
      from: 'gold.fact_deposit_transactions',
      to: 'gold.dim_transaction_type',
      type: 'many-to-one',
      foreignKey: 'transaction_type_key',
      description: 'Transaction type',
    },
    {
      from: 'gold.fact_deposit_transactions',
      to: 'gold.dim_channel',
      type: 'many-to-one',
      foreignKey: 'channel_key',
      description: 'Transaction channel',
    },
    {
      from: 'gold.fact_deposit_transactions',
      to: 'gold.dim_branch',
      type: 'many-to-one',
      foreignKey: 'branch_key',
      description: 'Branch dimension',
      optional: true,
    },
    // Fact: Daily Balances
    {
      from: 'gold.fact_deposit_balances_daily',
      to: 'gold.dim_retail_deposit_account',
      type: 'many-to-one',
      foreignKey: 'account_key',
      description: 'Account dimension',
    },
    {
      from: 'gold.fact_deposit_balances_daily',
      to: 'gold.dim_retail_customer',
      type: 'many-to-one',
      foreignKey: 'customer_key',
      description: 'Customer dimension',
    },
    {
      from: 'gold.fact_deposit_balances_daily',
      to: 'gold.dim_date',
      type: 'many-to-one',
      foreignKey: 'date_key',
      description: 'Balance date',
    },
    {
      from: 'gold.fact_deposit_balances_daily',
      to: 'gold.dim_deposit_product',
      type: 'many-to-one',
      foreignKey: 'product_key',
      description: 'Product dimension',
    },
    // Fact: Account Snapshot
    {
      from: 'gold.fact_deposit_account_snapshot',
      to: 'gold.dim_retail_deposit_account',
      type: 'many-to-one',
      foreignKey: 'account_key',
      description: 'Account dimension',
    },
    {
      from: 'gold.fact_deposit_account_snapshot',
      to: 'gold.dim_retail_customer',
      type: 'many-to-one',
      foreignKey: 'customer_key',
      description: 'Customer dimension',
    },
    {
      from: 'gold.fact_deposit_account_snapshot',
      to: 'gold.dim_date',
      type: 'many-to-one',
      foreignKey: 'date_key',
      description: 'Snapshot date',
    },
    // Fact: Interest
    {
      from: 'gold.fact_deposit_interest',
      to: 'gold.dim_retail_deposit_account',
      type: 'many-to-one',
      foreignKey: 'account_key',
      description: 'Account dimension',
    },
    {
      from: 'gold.fact_deposit_interest',
      to: 'gold.dim_retail_customer',
      type: 'many-to-one',
      foreignKey: 'customer_key',
      description: 'Customer dimension',
    },
    {
      from: 'gold.fact_deposit_interest',
      to: 'gold.dim_date',
      type: 'many-to-one',
      foreignKey: 'date_key',
      description: 'Interest date',
    },
    {
      from: 'gold.fact_deposit_interest',
      to: 'gold.dim_deposit_product',
      type: 'many-to-one',
      foreignKey: 'product_key',
      description: 'Product dimension',
    },
    // Fact: Fees
    {
      from: 'gold.fact_deposit_fees',
      to: 'gold.dim_retail_deposit_account',
      type: 'many-to-one',
      foreignKey: 'account_key',
      description: 'Account dimension',
    },
    {
      from: 'gold.fact_deposit_fees',
      to: 'gold.dim_retail_customer',
      type: 'many-to-one',
      foreignKey: 'customer_key',
      description: 'Customer dimension',
    },
    {
      from: 'gold.fact_deposit_fees',
      to: 'gold.dim_date',
      type: 'many-to-one',
      foreignKey: 'fee_date_key',
      description: 'Fee date',
    },
    // Fact: Overdrafts
    {
      from: 'gold.fact_deposit_overdrafts',
      to: 'gold.dim_retail_deposit_account',
      type: 'many-to-one',
      foreignKey: 'account_key',
      description: 'Account dimension',
    },
    {
      from: 'gold.fact_deposit_overdrafts',
      to: 'gold.dim_retail_customer',
      type: 'many-to-one',
      foreignKey: 'customer_key',
      description: 'Customer dimension',
    },
    {
      from: 'gold.fact_deposit_overdrafts',
      to: 'gold.dim_date',
      type: 'many-to-one',
      foreignKey: 'overdraft_date_key',
      description: 'Overdraft date',
    },
    {
      from: 'gold.fact_deposit_overdrafts',
      to: 'gold.dim_deposit_product',
      type: 'many-to-one',
      foreignKey: 'product_key',
      description: 'Product dimension',
    },
    // Dimension Hierarchies
    {
      from: 'gold.dim_retail_deposit_account',
      to: 'gold.dim_retail_customer',
      type: 'many-to-one',
      foreignKey: 'primary_customer_key',
      description: 'Primary account holder',
    },
    {
      from: 'gold.dim_retail_deposit_account',
      to: 'gold.dim_deposit_product',
      type: 'many-to-one',
      foreignKey: 'product_key',
      description: 'Product type',
    },
    {
      from: 'gold.dim_retail_deposit_account',
      to: 'gold.dim_branch',
      type: 'many-to-one',
      foreignKey: 'primary_branch_key',
      description: 'Primary branch',
    },
    {
      from: 'gold.dim_retail_deposit_account',
      to: 'gold.dim_account_status',
      type: 'many-to-one',
      foreignKey: 'account_status_key',
      description: 'Account status',
    },
    {
      from: 'gold.dim_retail_deposit_account',
      to: 'gold.dim_ownership_type',
      type: 'many-to-one',
      foreignKey: 'ownership_type_key',
      description: 'Ownership type',
    },
  ],
};

// ERD Visualization Metadata
export const depositsRetailERDVisualization = {
  layoutEngine: 'dagre',
  direction: 'TB',
  nodeSpacing: 100,
  rankSpacing: 150,
  
  entityGroups: [
    { name: 'Core Entities', color: '#3B82F6', entities: ['Deposit Account', 'Account Transaction'] },
    { name: 'Ownership', color: '#10B981', entities: ['Account Holder'] },
    { name: 'Interest & Fees', color: '#F59E0B', entities: ['Interest Rate', 'Interest Accrual', 'Fee Assessment'] },
    { name: 'Documents', color: '#8B5CF6', entities: ['Account Statement'] },
    { name: 'Events', color: '#EF4444', entities: ['Overdraft Event', 'Account Transfer', 'Check', 'Hold'] },
    { name: 'Compliance', color: '#EC4899', entities: ['Regulatory Event'] },
  ],
  
  keyRelationships: [
    { name: 'Account-Transactions', strength: 'strong', businessImportance: 'critical' },
    { name: 'Account-Holders', strength: 'strong', businessImportance: 'high' },
    { name: 'Account-Balances', strength: 'strong', businessImportance: 'critical' },
  ],
};

export default {
  depositsRetailLogicalERD,
  depositsRetailPhysicalERD,
  depositsRetailSilverERD,
  depositsRetailGoldERD,
  depositsRetailERDVisualization,
};
