/**
 * DEPOSITS-RETAIL METRICS CATALOG
 * 100 comprehensive metrics across 5 categories
 */

export const depositsRetailMetricsCatalog = {
  description: 'Comprehensive retail deposits metrics catalog',
  totalMetrics: 100,
  
  categories: [
    // Category 1: Volume & Balance Metrics (20 metrics)
    {
      name: 'Volume & Balance Metrics',
      description: 'Account counts, balances, and portfolio composition',
      totalMetrics: 20,
      
      metrics: [
        {
          id: 'DEP-VOL-001',
          name: 'Total Deposit Accounts',
          description: 'Total number of active deposit accounts',
          category: 'Volume',
          type: 'operational',
          subcategory: 'Account Count',
          formula: "COUNT(DISTINCT account_id WHERE account_status = 'Active')",
          businessLogic: 'Count of all active deposit accounts (DDA, savings, CD, MMA)',
          dataType: 'INTEGER',
          unit: 'count',
          aggregation: 'SUM',
          granularity: 'Daily',
          sourceTables: ['gold.dim_retail_deposit_account'],
          benchmarks: {
            industryAverage: '500,000 accounts',
            topQuartile: '1,000,000 accounts',
            target: '750,000 accounts',
          },
        },
        {
          id: 'DEP-VOL-002',
          name: 'Total Deposit Balances',
          description: 'Total balances across all deposit accounts',
          category: 'Volume',
          type: 'operational',
          subcategory: 'Balances',
          formula: "SUM(ending_balance WHERE account_status = 'Active')",
          businessLogic: 'Sum of all ending balances for active deposit accounts',
          dataType: 'DECIMAL',
          unit: 'USD',
          aggregation: 'SUM',
          granularity: 'Daily',
          benchmarks: {
            industryAverage: '$5B',
            topQuartile: '$15B',
            target: '$10B',
          },
        },
        {
          id: 'DEP-VOL-003',
          name: 'New Account Openings',
          description: 'Number of new deposit accounts opened in period',
          category: 'Volume',
          type: 'operational',
          subcategory: 'Growth',
        },
        {
          id: 'DEP-VOL-004',
          name: 'Account Closures',
          description: 'Number of deposit accounts closed in period',
          category: 'Volume',
          type: 'operational',
          subcategory: 'Attrition',
        },
        {
          id: 'DEP-VOL-005',
          name: 'Net Account Growth',
          description: 'New accounts minus closed accounts',
          category: 'Volume',
          type: 'operational',
          subcategory: 'Growth',
        },
        {
          id: 'DEP-VOL-006',
          name: 'Average Balance per Account',
          description: 'Mean balance across all deposit accounts',
          category: 'Volume',
          type: 'operational',
          subcategory: 'Average',
        },
        {
          id: 'DEP-VOL-007',
          name: 'Checking Account Count',
          description: 'Total number of checking (DDA) accounts',
          category: 'Volume',
          type: 'operational',
          subcategory: 'Product Mix',
        },
        {
          id: 'DEP-VOL-008',
          name: 'Savings Account Count',
          description: 'Total number of savings accounts',
          category: 'Volume',
          type: 'operational',
          subcategory: 'Product Mix',
        },
        {
          id: 'DEP-VOL-009',
          name: 'Money Market Account Count',
          description: 'Total number of MMA accounts',
          category: 'Volume',
          type: 'operational',
          subcategory: 'Product Mix',
        },
        {
          id: 'DEP-VOL-010',
          name: 'CD Account Count',
          description: 'Total number of certificate of deposit accounts',
          category: 'Volume',
          type: 'operational',
          subcategory: 'Product Mix',
        },
        {
          id: 'DEP-VOL-011',
          name: 'Checking Balance Total',
          description: 'Total balances in checking accounts',
          category: 'Volume',
          type: 'operational',
          subcategory: 'Product Balance',
        },
        {
          id: 'DEP-VOL-012',
          name: 'Savings Balance Total',
          description: 'Total balances in savings accounts',
          category: 'Volume',
          type: 'operational',
          subcategory: 'Product Balance',
        },
        {
          id: 'DEP-VOL-013',
          name: 'Money Market Balance Total',
          description: 'Total balances in MMA accounts',
          category: 'Volume',
          type: 'operational',
          subcategory: 'Product Balance',
        },
        {
          id: 'DEP-VOL-014',
          name: 'CD Balance Total',
          description: 'Total balances in CD accounts',
          category: 'Volume',
          type: 'operational',
          subcategory: 'Product Balance',
        },
        {
          id: 'DEP-VOL-015',
          name: 'Deposit Growth Rate',
          description: 'Year-over-year deposit balance growth',
          category: 'Volume',
          type: 'operational',
          subcategory: 'Growth',
        },
        {
          id: 'DEP-VOL-016',
          name: 'Retail vs Commercial Mix',
          description: 'Percentage split of retail vs commercial deposits',
          category: 'Volume',
          type: 'operational',
          subcategory: 'Mix',
        },
        {
          id: 'DEP-VOL-017',
          name: 'Non-Interest Bearing Deposits',
          description: 'Total balances in non-interest accounts',
          category: 'Volume',
          type: 'operational',
          subcategory: 'Interest Type',
        },
        {
          id: 'DEP-VOL-018',
          name: 'Interest Bearing Deposits',
          description: 'Total balances in interest-bearing accounts',
          category: 'Volume',
          type: 'operational',
          subcategory: 'Interest Type',
        },
        {
          id: 'DEP-VOL-019',
          name: 'Average Account Age',
          description: 'Mean time since account opening',
          category: 'Volume',
          type: 'operational',
          subcategory: 'Age',
        },
        {
          id: 'DEP-VOL-020',
          name: 'Deposit Concentration Risk',
          description: 'Percentage of deposits from top 10 customers',
          category: 'Volume',
          type: 'operational',
          subcategory: 'Risk',
        },
      ],
    },

    // Category 2: Transaction & Activity Metrics (20 metrics)
    {
      name: 'Transaction & Activity Metrics',
      description: 'Transaction volume, velocity, and behavior patterns',
      totalMetrics: 20,
      
      metrics: [
        {
          id: 'DEP-TXN-001',
          name: 'Total Transaction Volume',
          description: 'Total number of transactions across all deposit accounts',
          category: 'Transaction',
          type: 'operational',
          subcategory: 'Volume',
          formula: "COUNT(*) FROM fact_deposit_transactions",
          dataType: 'INTEGER',
          unit: 'count',
          aggregation: 'SUM',
          granularity: 'Daily',
          benchmarks: {
            industryAverage: '50M transactions/month',
            topQuartile: '100M transactions/month',
            target: '75M transactions/month',
          },
        },
        {
          id: 'DEP-TXN-002',
          name: 'Deposit Transaction Volume',
          description: 'Total dollar amount of deposits',
          category: 'Transaction',
          type: 'operational',
          subcategory: 'Deposits',
        },
        {
          id: 'DEP-TXN-003',
          name: 'Withdrawal Transaction Volume',
          description: 'Total dollar amount of withdrawals',
          category: 'Transaction',
          type: 'operational',
          subcategory: 'Withdrawals',
        },
        {
          id: 'DEP-TXN-004',
          name: 'Average Transaction Size',
          description: 'Mean dollar amount per transaction',
          category: 'Transaction',
          type: 'operational',
          subcategory: 'Size',
        },
        {
          id: 'DEP-TXN-005',
          name: 'ATM Transaction Rate',
          description: 'Percentage of transactions via ATM',
          category: 'Transaction',
          type: 'operational',
          subcategory: 'Channel',
        },
        {
          id: 'DEP-TXN-006',
          name: 'Mobile Deposit Rate',
          description: 'Percentage of deposits via mobile check capture',
          category: 'Transaction',
          type: 'operational',
          subcategory: 'Channel',
        },
        {
          id: 'DEP-TXN-007',
          name: 'Branch Transaction Rate',
          description: 'Percentage of transactions at branch',
          category: 'Transaction',
          type: 'operational',
          subcategory: 'Channel',
        },
        {
          id: 'DEP-TXN-008',
          name: 'Online Transaction Rate',
          description: 'Percentage of transactions via online banking',
          category: 'Transaction',
          type: 'operational',
          subcategory: 'Channel',
        },
        {
          id: 'DEP-TXN-009',
          name: 'Transactions per Account per Month',
          description: 'Average monthly transaction count per account',
          category: 'Transaction',
          type: 'operational',
          subcategory: 'Activity',
        },
        {
          id: 'DEP-TXN-010',
          name: 'Direct Deposit Adoption Rate',
          description: 'Percentage of checking accounts with direct deposit',
          category: 'Transaction',
          type: 'operational',
          subcategory: 'Direct Deposit',
        },
        {
          id: 'DEP-TXN-011',
          name: 'ACH Transaction Volume',
          description: 'Number of ACH transactions processed',
          category: 'Transaction',
          type: 'operational',
          subcategory: 'ACH',
        },
        {
          id: 'DEP-TXN-012',
          name: 'Wire Transfer Volume',
          description: 'Number of wire transfers processed',
          category: 'Transaction',
          type: 'operational',
          subcategory: 'Wires',
        },
        {
          id: 'DEP-TXN-013',
          name: 'Internal Transfer Volume',
          description: 'Number of transfers between own accounts',
          category: 'Transaction',
          type: 'operational',
          subcategory: 'Transfers',
        },
        {
          id: 'DEP-TXN-014',
          name: 'Check Deposit Volume',
          description: 'Number of check deposits processed',
          category: 'Transaction',
          type: 'operational',
          subcategory: 'Checks',
        },
        {
          id: 'DEP-TXN-015',
          name: 'Check Written Volume',
          description: 'Number of checks written on accounts',
          category: 'Transaction',
          type: 'operational',
          subcategory: 'Checks',
        },
        {
          id: 'DEP-TXN-016',
          name: 'Debit Card Purchase Volume',
          description: 'Number of debit card transactions',
          category: 'Transaction',
          type: 'operational',
          subcategory: 'Debit Card',
        },
        {
          id: 'DEP-TXN-017',
          name: 'Cash Deposit Volume',
          description: 'Number of cash deposit transactions',
          category: 'Transaction',
          type: 'operational',
          subcategory: 'Cash',
        },
        {
          id: 'DEP-TXN-018',
          name: 'Cash Withdrawal Volume',
          description: 'Number of cash withdrawal transactions',
          category: 'Transaction',
          type: 'operational',
          subcategory: 'Cash',
        },
        {
          id: 'DEP-TXN-019',
          name: 'Weekend Transaction Rate',
          description: 'Percentage of transactions on weekends',
          category: 'Transaction',
          type: 'operational',
          subcategory: 'Timing',
        },
        {
          id: 'DEP-TXN-020',
          name: 'After-Hours Transaction Rate',
          description: 'Percentage of transactions outside business hours',
          category: 'Transaction',
          type: 'operational',
          subcategory: 'Timing',
        },
      ],
    },

    // Category 3: Profitability & Revenue Metrics (20 metrics)
    {
      name: 'Profitability & Revenue Metrics',
      description: 'Interest expense, fee revenue, and account profitability',
      totalMetrics: 20,
      
      metrics: [
        {
          id: 'DEP-PROF-001',
          name: 'Total Interest Expense',
          description: 'Total interest paid on deposit accounts',
          category: 'Profitability',
          type: 'financial',
          subcategory: 'Interest',
          formula: "SUM(interest_paid_amount)",
          dataType: 'DECIMAL',
          unit: 'USD',
          aggregation: 'SUM',
          granularity: 'Monthly',
        },
        {
          id: 'DEP-PROF-002',
          name: 'Total Fee Revenue',
          description: 'Total fee revenue from deposit accounts',
          category: 'Profitability',
          type: 'financial',
          subcategory: 'Fees',
          benchmarks: {
            industryAverage: '$5M/month',
            topQuartile: '$12M/month',
            target: '$8M/month',
          },
        },
        {
          id: 'DEP-PROF-003',
          name: 'Net Interest Margin on Deposits',
          description: 'Interest earned minus interest paid as percentage of deposits',
          category: 'Profitability',
          type: 'financial',
          subcategory: 'NIM',
        },
        {
          id: 'DEP-PROF-004',
          name: 'Cost of Deposits',
          description: 'Average interest rate paid on deposits',
          category: 'Profitability',
          type: 'financial',
          subcategory: 'Cost',
        },
        {
          id: 'DEP-PROF-005',
          name: 'Revenue per Account',
          description: 'Average revenue generated per deposit account',
          category: 'Profitability',
          type: 'financial',
          subcategory: 'Account Economics',
        },
        {
          id: 'DEP-PROF-006',
          name: 'Overdraft Fee Revenue',
          description: 'Total revenue from overdraft fees',
          category: 'Profitability',
          type: 'financial',
          subcategory: 'Fees',
        },
        {
          id: 'DEP-PROF-007',
          name: 'NSF Fee Revenue',
          description: 'Total revenue from insufficient funds fees',
          category: 'Profitability',
          type: 'financial',
          subcategory: 'Fees',
        },
        {
          id: 'DEP-PROF-008',
          name: 'Monthly Maintenance Fee Revenue',
          description: 'Total revenue from monthly account fees',
          category: 'Profitability',
          type: 'financial',
          subcategory: 'Fees',
        },
        {
          id: 'DEP-PROF-009',
          name: 'ATM Fee Revenue',
          description: 'Total revenue from ATM fees',
          category: 'Profitability',
          type: 'financial',
          subcategory: 'Fees',
        },
        {
          id: 'DEP-PROF-010',
          name: 'Wire Transfer Fee Revenue',
          description: 'Total revenue from wire transfer fees',
          category: 'Profitability',
          type: 'financial',
          subcategory: 'Fees',
        },
        {
          id: 'DEP-PROF-011',
          name: 'Stop Payment Fee Revenue',
          description: 'Total revenue from stop payment fees',
          category: 'Profitability',
          type: 'financial',
          subcategory: 'Fees',
        },
        {
          id: 'DEP-PROF-012',
          name: 'Account Profitability Score',
          description: 'Composite profitability metric per account',
          category: 'Profitability',
          type: 'financial',
          subcategory: 'Scoring',
        },
        {
          id: 'DEP-PROF-013',
          name: 'Profitable Account Rate',
          description: 'Percentage of accounts generating positive profit',
          category: 'Profitability',
          type: 'financial',
          subcategory: 'Mix',
        },
        {
          id: 'DEP-PROF-014',
          name: 'Fee Waiver Rate',
          description: 'Percentage of fees waived or refunded',
          category: 'Profitability',
          type: 'financial',
          subcategory: 'Fee Management',
        },
        {
          id: 'DEP-PROF-015',
          name: 'Deposit Premium Paid',
          description: 'Premium rates paid above benchmark for deposits',
          category: 'Profitability',
          type: 'financial',
          subcategory: 'Pricing',
        },
        {
          id: 'DEP-PROF-016',
          name: 'Deposit Beta',
          description: 'Deposit rate sensitivity to market rate changes',
          category: 'Profitability',
          type: 'financial',
          subcategory: 'Rate Risk',
        },
        {
          id: 'DEP-PROF-017',
          name: 'Account Servicing Cost',
          description: 'Average cost to service each account',
          category: 'Profitability',
          type: 'financial',
          subcategory: 'Cost',
        },
        {
          id: 'DEP-PROF-018',
          name: 'Deposit Gathering Cost',
          description: 'Cost to acquire new deposit balances',
          category: 'Profitability',
          type: 'financial',
          subcategory: 'Acquisition',
        },
        {
          id: 'DEP-PROF-019',
          name: 'Cross-Sell Revenue from Deposit Customers',
          description: 'Revenue from other products sold to deposit customers',
          category: 'Profitability',
          type: 'financial',
          subcategory: 'Cross-Sell',
        },
        {
          id: 'DEP-PROF-020',
          name: 'Deposit Account ROA',
          description: 'Return on assets for deposit portfolio',
          category: 'Profitability',
          type: 'financial',
          subcategory: 'Returns',
        },
      ],
    },

    // Category 4: Customer Behavior & Engagement Metrics (20 metrics)
    {
      name: 'Customer Behavior & Engagement Metrics',
      description: 'Customer activity patterns, engagement, and usage',
      totalMetrics: 20,
      
      metrics: [
        {
          id: 'DEP-BEH-001',
          name: 'Active Account Rate',
          description: 'Percentage of accounts with activity in last 90 days',
          category: 'Behavior',
          type: 'behavioral',
          subcategory: 'Activity',
          formula: "(active_accounts / total_accounts) * 100",
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Monthly',
          benchmarks: {
            industryAverage: '75%',
            topQuartile: '85%',
            target: '80%',
          },
        },
        {
          id: 'DEP-BEH-002',
          name: 'Dormant Account Rate',
          description: 'Percentage of accounts with no activity in 12+ months',
          category: 'Behavior',
          type: 'behavioral',
          subcategory: 'Dormancy',
        },
        {
          id: 'DEP-BEH-003',
          name: 'Digital Banking Adoption Rate',
          description: 'Percentage of customers using online/mobile banking',
          category: 'Behavior',
          type: 'behavioral',
          subcategory: 'Digital',
        },
        {
          id: 'DEP-BEH-004',
          name: 'Mobile Banking Active Users',
          description: 'Percentage of deposit customers active on mobile',
          category: 'Behavior',
          type: 'behavioral',
          subcategory: 'Mobile',
        },
        {
          id: 'DEP-BEH-005',
          name: 'Average Login Frequency',
          description: 'Mean logins per customer per month',
          category: 'Behavior',
          type: 'behavioral',
          subcategory: 'Engagement',
        },
        {
          id: 'DEP-BEH-006',
          name: 'Paperless Statement Adoption',
          description: 'Percentage of customers enrolled in paperless statements',
          category: 'Behavior',
          type: 'behavioral',
          subcategory: 'Preferences',
        },
        {
          id: 'DEP-BEH-007',
          name: 'Automatic Savings Transfer Adoption',
          description: 'Percentage of customers with automated savings transfers',
          category: 'Behavior',
          type: 'behavioral',
          subcategory: 'Savings Behavior',
        },
        {
          id: 'DEP-BEH-008',
          name: 'Balance Alert Enrollment',
          description: 'Percentage of customers enrolled in balance alerts',
          category: 'Behavior',
          type: 'behavioral',
          subcategory: 'Notifications',
        },
        {
          id: 'DEP-BEH-009',
          name: 'Multi-Account Holding Rate',
          description: 'Percentage of customers with multiple deposit accounts',
          category: 'Behavior',
          type: 'behavioral',
          subcategory: 'Product Holding',
        },
        {
          id: 'DEP-BEH-010',
          name: 'Average Balance Volatility',
          description: 'Standard deviation of account balances',
          category: 'Behavior',
          type: 'behavioral',
          subcategory: 'Stability',
        },
        {
          id: 'DEP-BEH-011',
          name: 'Minimum Balance Maintenance Rate',
          description: 'Percentage of accounts maintaining required minimums',
          category: 'Behavior',
          type: 'behavioral',
          subcategory: 'Balance Maintenance',
        },
        {
          id: 'DEP-BEH-012',
          name: 'External Account Linking Rate',
          description: 'Percentage of customers with external accounts linked',
          category: 'Behavior',
          type: 'behavioral',
          subcategory: 'External Connections',
        },
        {
          id: 'DEP-BEH-013',
          name: 'Bill Pay Adoption Rate',
          description: 'Percentage of deposit customers using bill pay',
          category: 'Behavior',
          type: 'behavioral',
          subcategory: 'Payments',
        },
        {
          id: 'DEP-BEH-014',
          name: 'P2P Payment Usage Rate',
          description: 'Percentage of customers using P2P payments',
          category: 'Behavior',
          type: 'behavioral',
          subcategory: 'Payments',
        },
        {
          id: 'DEP-BEH-015',
          name: 'Debit Card Attachment Rate',
          description: 'Percentage of checking accounts with active debit card',
          category: 'Behavior',
          type: 'behavioral',
          subcategory: 'Card Usage',
        },
        {
          id: 'DEP-BEH-016',
          name: 'ATM Usage Frequency',
          description: 'Average ATM transactions per customer per month',
          category: 'Behavior',
          type: 'behavioral',
          subcategory: 'ATM',
        },
        {
          id: 'DEP-BEH-017',
          name: 'Branch Visit Frequency',
          description: 'Average branch visits per customer per year',
          category: 'Behavior',
          type: 'behavioral',
          subcategory: 'Branch',
        },
        {
          id: 'DEP-BEH-018',
          name: 'Overdraft Protection Enrollment',
          description: 'Percentage of checking accounts with overdraft protection',
          category: 'Behavior',
          type: 'behavioral',
          subcategory: 'Protection',
        },
        {
          id: 'DEP-BEH-019',
          name: 'Savings Goal Setting Rate',
          description: 'Percentage of savings customers with defined goals',
          category: 'Behavior',
          type: 'behavioral',
          subcategory: 'Financial Planning',
        },
        {
          id: 'DEP-BEH-020',
          name: 'Round-Up Feature Adoption',
          description: 'Percentage of customers using purchase round-up to savings',
          category: 'Behavior',
          type: 'behavioral',
          subcategory: 'Savings Behavior',
        },
      ],
    },

    // Category 5: Risk & Compliance Metrics (20 metrics)
    {
      name: 'Risk & Compliance Metrics',
      description: 'Overdrafts, fraud, dormancy, and regulatory metrics',
      totalMetrics: 20,
      
      metrics: [
        {
          id: 'DEP-RISK-001',
          name: 'Overdraft Rate',
          description: 'Percentage of accounts with overdrafts in period',
          category: 'Risk',
          type: 'risk',
          subcategory: 'Overdraft',
          formula: "(COUNT(accounts_with_overdraft) / COUNT(total_accounts)) * 100",
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'AVG',
          granularity: 'Monthly',
          benchmarks: {
            industryAverage: '8%',
            topQuartile: '5%',
            target: '6%',
          },
        },
        {
          id: 'DEP-RISK-002',
          name: 'Chronic Overdraft Rate',
          description: 'Percentage of accounts overdrawn 10+ times per year',
          category: 'Risk',
          type: 'risk',
          subcategory: 'Overdraft',
        },
        {
          id: 'DEP-RISK-003',
          name: 'NSF Incident Rate',
          description: 'Frequency of insufficient funds incidents',
          category: 'Risk',
          type: 'risk',
          subcategory: 'NSF',
        },
        {
          id: 'DEP-RISK-004',
          name: 'Dormant Account Rate',
          description: 'Percentage of accounts dormant (no activity >12 months)',
          category: 'Risk',
          type: 'risk',
          subcategory: 'Dormancy',
        },
        {
          id: 'DEP-RISK-005',
          name: 'Account Fraud Rate',
          description: 'Percentage of accounts experiencing fraud',
          category: 'Risk',
          type: 'risk',
          subcategory: 'Fraud',
        },
        {
          id: 'DEP-RISK-006',
          name: 'Check Fraud Incident Rate',
          description: 'Frequency of check fraud per 1,000 accounts',
          category: 'Risk',
          type: 'risk',
          subcategory: 'Fraud',
        },
        {
          id: 'DEP-RISK-007',
          name: 'Account Takeover Rate',
          description: 'Frequency of account takeover incidents',
          category: 'Risk',
          type: 'risk',
          subcategory: 'Fraud',
        },
        {
          id: 'DEP-RISK-008',
          name: 'Unauthorized Transaction Rate',
          description: 'Percentage of transactions disputed as unauthorized',
          category: 'Risk',
          type: 'risk',
          subcategory: 'Fraud',
        },
        {
          id: 'DEP-RISK-009',
          name: 'Negative Balance Days',
          description: 'Average days accounts remain in negative balance',
          category: 'Risk',
          type: 'risk',
          subcategory: 'Overdraft',
        },
        {
          id: 'DEP-RISK-010',
          name: 'Escheatment Risk',
          description: 'Value of balances subject to escheatment',
          category: 'Risk',
          type: 'risk',
          subcategory: 'Regulatory',
        },
        {
          id: 'DEP-RISK-011',
          name: 'Large Cash Transaction Rate',
          description: 'Transactions over $10,000 requiring CTR',
          category: 'Risk',
          type: 'risk',
          subcategory: 'AML',
        },
        {
          id: 'DEP-RISK-012',
          name: 'Structuring Alert Rate',
          description: 'Suspicious activity related to structuring',
          category: 'Risk',
          type: 'risk',
          subcategory: 'AML',
        },
        {
          id: 'DEP-RISK-013',
          name: 'Reg D Violation Rate',
          description: 'Savings accounts exceeding transaction limits',
          category: 'Risk',
          type: 'risk',
          subcategory: 'Regulatory',
        },
        {
          id: 'DEP-RISK-014',
          name: 'Reg E Dispute Rate',
          description: 'Electronic transaction disputes per 1,000 accounts',
          category: 'Risk',
          type: 'risk',
          subcategory: 'Regulatory',
        },
        {
          id: 'DEP-RISK-015',
          name: 'Uncollected Funds Risk',
          description: 'Value of deposits subject to hold or verification',
          category: 'Risk',
          type: 'risk',
          subcategory: 'Credit Risk',
        },
        {
          id: 'DEP-RISK-016',
          name: 'Charge-Off Rate',
          description: 'Percentage of overdraft balances written off',
          category: 'Risk',
          type: 'risk',
          subcategory: 'Credit Loss',
        },
        {
          id: 'DEP-RISK-017',
          name: 'Account Closure for Cause Rate',
          description: 'Percentage of accounts closed due to fraud or abuse',
          category: 'Risk',
          type: 'risk',
          subcategory: 'Account Management',
        },
        {
          id: 'DEP-RISK-018',
          name: 'High-Risk Customer Rate',
          description: 'Percentage of customers flagged as high risk',
          category: 'Risk',
          type: 'risk',
          subcategory: 'Customer Risk',
        },
        {
          id: 'DEP-RISK-019',
          name: 'FDIC Insurance Compliance',
          description: 'Percentage of deposits within FDIC insurance limits',
          category: 'Risk',
          type: 'risk',
          subcategory: 'Regulatory',
        },
        {
          id: 'DEP-RISK-020',
          name: 'Deposit Concentration by Customer',
          description: 'Percentage of deposits from top depositors',
          category: 'Risk',
          type: 'risk',
          subcategory: 'Concentration',
        },
      ],
    },
  ],
};

export default depositsRetailMetricsCatalog;
