/**
 * DIGITAL-RETAIL BRONZE LAYER - Complete Implementation
 * 
 * Raw data tables from digital and mobile banking systems
 * 20 tables covering online banking, mobile app, digital wallets, and API banking
 * 
 * Grade A Target: Complete raw data capture from all digital channels
 */

export const digitalRetailBronzeTables = [
  // Table 1: Digital Banking Sessions
  {
    name: 'bronze.retail_digital_banking_sessions',
    description: 'Online banking web sessions',
    sourceSystem: 'ONLINE_BANKING_PLATFORM',
    sourceTable: 'WEB_SESSIONS',
    loadType: 'STREAMING',
    grain: 'One row per web session',
    primaryKey: ['session_id', 'source_system'],
    schema: {
      session_id: "STRING PRIMARY KEY",
      source_system: "STRING PRIMARY KEY",
      customer_id: "BIGINT",
      session_start_timestamp: "TIMESTAMP",
      session_end_timestamp: "TIMESTAMP",
      session_duration_seconds: "INTEGER",
      ip_address: "STRING",
      user_agent: "STRING",
      browser: "STRING",
      operating_system: "STRING",
      device_type: "STRING COMMENT 'Desktop|Tablet|Mobile'",
      pages_viewed: "INTEGER",
      actions_performed: "INTEGER",
      session_outcome: "STRING COMMENT 'Completed|Abandoned|Timeout'",
      source_record_id: "STRING",
      load_timestamp: "TIMESTAMP",
      cdc_operation: "STRING",
    },
  },

  // Table 2: Mobile App Sessions
  {
    name: 'bronze.retail_mobile_app_sessions',
    description: 'Mobile banking app sessions',
    sourceSystem: 'MOBILE_APP_ANALYTICS',
    sourceTable: 'APP_SESSIONS',
    loadType: 'STREAMING',
    grain: 'One row per app session',
    primaryKey: ['session_id', 'source_system'],
    schema: {
      session_id: "STRING PRIMARY KEY",
      source_system: "STRING PRIMARY KEY",
      customer_id: "BIGINT",
      device_id: "STRING",
      app_version: "STRING",
      os_version: "STRING",
      session_start_timestamp: "TIMESTAMP",
      session_end_timestamp: "TIMESTAMP",
      session_duration_seconds: "INTEGER",
      screens_viewed: "INTEGER",
      actions_performed: "INTEGER",
      crashes: "INTEGER",
      session_type: "STRING COMMENT 'Foreground|Background'",
      source_record_id: "STRING",
      load_timestamp: "TIMESTAMP",
      cdc_operation: "STRING",
    },
  },

  // Table 3: Digital Login Events
  {
    name: 'bronze.retail_digital_login_events',
    description: 'Login/authentication events across digital channels',
    sourceSystem: 'IAM_SYSTEM',
    sourceTable: 'LOGIN_EVENTS',
    loadType: 'STREAMING',
    grain: 'One row per login attempt',
    primaryKey: ['login_event_id', 'source_system'],
    schema: {
      login_event_id: "STRING PRIMARY KEY",
      source_system: "STRING PRIMARY KEY",
      customer_id: "BIGINT",
      login_timestamp: "TIMESTAMP",
      login_channel: "STRING COMMENT 'Web|Mobile App|API'",
      authentication_method: "STRING COMMENT 'Password|Biometric|OTP|SSO'",
      login_status: "STRING COMMENT 'Success|Failed|Locked'",
      failure_reason: "STRING",
      ip_address: "STRING",
      geolocation: "STRING",
      device_id: "STRING",
      risk_score: "INTEGER COMMENT '0-100'",
      source_record_id: "STRING",
      load_timestamp: "TIMESTAMP",
      cdc_operation: "STRING",
    },
  },

  // Table 4: Mobile App Interactions
  {
    name: 'bronze.retail_mobile_app_interactions',
    description: 'Detailed user interactions within mobile app',
    sourceSystem: 'MOBILE_APP_ANALYTICS',
    sourceTable: 'APP_INTERACTIONS',
    loadType: 'STREAMING',
    grain: 'One row per interaction event',
    primaryKey: ['interaction_id', 'source_system'],
    schema: {
      interaction_id: "STRING PRIMARY KEY",
      source_system: "STRING PRIMARY KEY",
      session_id: "STRING",
      customer_id: "BIGINT",
      interaction_timestamp: "TIMESTAMP",
      screen_name: "STRING",
      action_type: "STRING COMMENT 'Tap|Swipe|Scroll|Search|etc.'",
      element_id: "STRING",
      element_type: "STRING COMMENT 'Button|Link|Form Field|etc.'",
      interaction_value: "STRING",
      source_record_id: "STRING",
      load_timestamp: "TIMESTAMP",
      cdc_operation: "STRING",
    },
  },

  // Table 5: Online Account Actions
  {
    name: 'bronze.retail_online_account_actions',
    description: 'Account-related actions performed in digital channels',
    sourceSystem: 'ONLINE_BANKING_PLATFORM',
    sourceTable: 'ACCOUNT_ACTIONS',
    loadType: 'STREAMING',
    grain: 'One row per account action',
    primaryKey: ['action_id', 'source_system'],
    schema: {
      action_id: "STRING PRIMARY KEY",
      source_system: "STRING PRIMARY KEY",
      customer_id: "BIGINT",
      account_id: "BIGINT",
      action_timestamp: "TIMESTAMP",
      action_type: "STRING COMMENT 'View Balance|View Transactions|Download Statement|Update Settings'",
      action_channel: "STRING COMMENT 'Web|Mobile'",
      action_status: "STRING COMMENT 'Completed|Failed|Abandoned'",
      source_record_id: "STRING",
      load_timestamp: "TIMESTAMP",
      cdc_operation: "STRING",
    },
  },

  // Table 6: Mobile Deposits
  {
    name: 'bronze.retail_mobile_deposits',
    description: 'Mobile check deposit transactions',
    sourceSystem: 'MOBILE_DEPOSIT_SYSTEM',
    sourceTable: 'MOBILE_DEPOSITS',
    loadType: 'STREAMING',
    grain: 'One row per mobile deposit',
    primaryKey: ['deposit_id', 'source_system'],
    schema: {
      deposit_id: "BIGINT PRIMARY KEY",
      source_system: "STRING PRIMARY KEY",
      customer_id: "BIGINT",
      account_id: "BIGINT",
      deposit_timestamp: "TIMESTAMP",
      deposit_amount: "DECIMAL(18,2)",
      check_front_image_path: "STRING",
      check_back_image_path: "STRING",
      image_quality_score: "INTEGER COMMENT '0-100'",
      deposit_status: "STRING COMMENT 'Pending|Approved|Rejected|On Hold'",
      rejection_reason: "STRING",
      device_id: "STRING",
      app_version: "STRING",
      source_record_id: "STRING",
      load_timestamp: "TIMESTAMP",
      cdc_operation: "STRING",
    },
  },

  // Table 7: Digital Transfers
  {
    name: 'bronze.retail_digital_transfers',
    description: 'Transfers initiated through digital channels',
    sourceSystem: 'PAYMENT_HUB',
    sourceTable: 'DIGITAL_TRANSFERS',
    loadType: 'STREAMING',
    grain: 'One row per transfer',
    primaryKey: ['transfer_id', 'source_system'],
    schema: {
      transfer_id: "BIGINT PRIMARY KEY",
      source_system: "STRING PRIMARY KEY",
      customer_id: "BIGINT",
      from_account_id: "BIGINT",
      to_account_id: "BIGINT",
      transfer_timestamp: "TIMESTAMP",
      transfer_amount: "DECIMAL(18,2)",
      transfer_type: "STRING COMMENT 'Internal|External|P2P|Bill Pay'",
      transfer_channel: "STRING COMMENT 'Web|Mobile App'",
      transfer_status: "STRING COMMENT 'Completed|Pending|Failed'",
      device_id: "STRING",
      source_record_id: "STRING",
      load_timestamp: "TIMESTAMP",
      cdc_operation: "STRING",
    },
  },

  // Table 8: Biometric Auth Events
  {
    name: 'bronze.retail_biometric_auth_events',
    description: 'Biometric authentication events (Touch ID, Face ID)',
    sourceSystem: 'IAM_SYSTEM',
    sourceTable: 'BIOMETRIC_AUTH',
    loadType: 'STREAMING',
    grain: 'One row per biometric auth attempt',
    primaryKey: ['auth_event_id', 'source_system'],
    schema: {
      auth_event_id: "STRING PRIMARY KEY",
      source_system: "STRING PRIMARY KEY",
      customer_id: "BIGINT",
      device_id: "STRING",
      auth_timestamp: "TIMESTAMP",
      auth_type: "STRING COMMENT 'Touch ID|Face ID|Fingerprint|Iris Scan'",
      auth_result: "STRING COMMENT 'Success|Failed|Retry'",
      failure_count: "INTEGER",
      device_model: "STRING",
      os_version: "STRING",
      source_record_id: "STRING",
      load_timestamp: "TIMESTAMP",
      cdc_operation: "STRING",
    },
  },

  // Table 9: Digital Alerts/Notifications
  {
    name: 'bronze.retail_digital_alerts_notifications',
    description: 'Push notifications and alerts sent to customers',
    sourceSystem: 'NOTIFICATION_SYSTEM',
    sourceTable: 'DIGITAL_NOTIFICATIONS',
    loadType: 'STREAMING',
    grain: 'One row per notification',
    primaryKey: ['notification_id', 'source_system'],
    schema: {
      notification_id: "STRING PRIMARY KEY",
      source_system: "STRING PRIMARY KEY",
      customer_id: "BIGINT",
      notification_timestamp: "TIMESTAMP",
      notification_type: "STRING COMMENT 'Transaction Alert|Balance Alert|Security Alert|Marketing|etc.'",
      notification_channel: "STRING COMMENT 'Push|In-App|Email|SMS'",
      notification_message: "STRING",
      delivery_status: "STRING COMMENT 'Sent|Delivered|Opened|Clicked|Failed'",
      opened_timestamp: "TIMESTAMP",
      device_id: "STRING",
      source_record_id: "STRING",
      load_timestamp: "TIMESTAMP",
      cdc_operation: "STRING",
    },
  },

  // Table 10: Mobile App Crashes
  {
    name: 'bronze.retail_mobile_app_crashes',
    description: 'Mobile app crash events and diagnostics',
    sourceSystem: 'APP_MONITORING',
    sourceTable: 'APP_CRASHES',
    loadType: 'STREAMING',
    grain: 'One row per crash event',
    primaryKey: ['crash_id', 'source_system'],
    schema: {
      crash_id: "STRING PRIMARY KEY",
      source_system: "STRING PRIMARY KEY",
      customer_id: "BIGINT",
      device_id: "STRING",
      crash_timestamp: "TIMESTAMP",
      app_version: "STRING",
      os_version: "STRING",
      device_model: "STRING",
      crash_type: "STRING COMMENT 'Exception|ANR|Out of Memory|etc.'",
      error_message: "STRING",
      stack_trace: "STRING",
      screen_at_crash: "STRING",
      source_record_id: "STRING",
      load_timestamp: "TIMESTAMP",
      cdc_operation: "STRING",
    },
  },

  // Table 11: Chatbot Conversations
  {
    name: 'bronze.retail_digital_chatbot_conversations',
    description: 'AI chatbot conversation logs',
    sourceSystem: 'CHATBOT_PLATFORM',
    sourceTable: 'CONVERSATIONS',
    loadType: 'STREAMING',
    grain: 'One row per conversation',
    primaryKey: ['conversation_id', 'source_system'],
    schema: {
      conversation_id: "STRING PRIMARY KEY",
      source_system: "STRING PRIMARY KEY",
      customer_id: "BIGINT",
      conversation_start_timestamp: "TIMESTAMP",
      conversation_end_timestamp: "TIMESTAMP",
      conversation_duration_seconds: "INTEGER",
      channel: "STRING COMMENT 'Web Chat|Mobile App|SMS|Voice'",
      message_count: "INTEGER",
      intent: "STRING COMMENT 'Balance Inquiry|Transfer|Support|etc.'",
      resolution_status: "STRING COMMENT 'Resolved|Escalated|Abandoned'",
      handoff_to_human: "BOOLEAN",
      satisfaction_score: "INTEGER COMMENT '1-5'",
      source_record_id: "STRING",
      load_timestamp: "TIMESTAMP",
      cdc_operation: "STRING",
    },
  },

  // Table 12: API Banking Requests
  {
    name: 'bronze.retail_api_banking_requests',
    description: 'API requests for open banking and third-party integrations',
    sourceSystem: 'API_GATEWAY',
    sourceTable: 'API_REQUESTS',
    loadType: 'STREAMING',
    grain: 'One row per API request',
    primaryKey: ['request_id', 'source_system'],
    schema: {
      request_id: "STRING PRIMARY KEY",
      source_system: "STRING PRIMARY KEY",
      customer_id: "BIGINT",
      api_endpoint: "STRING",
      http_method: "STRING COMMENT 'GET|POST|PUT|DELETE'",
      request_timestamp: "TIMESTAMP",
      response_status_code: "INTEGER",
      response_time_ms: "INTEGER",
      api_key_id: "STRING",
      third_party_app: "STRING",
      request_payload_size_bytes: "INTEGER",
      response_payload_size_bytes: "INTEGER",
      error_message: "STRING",
      source_record_id: "STRING",
      load_timestamp: "TIMESTAMP",
      cdc_operation: "STRING",
    },
  },

  // Table 13: Digital Wallet Transactions
  {
    name: 'bronze.retail_digital_wallet_transactions',
    description: 'Digital wallet transactions (Venmo, PayPal, etc.)',
    sourceSystem: 'DIGITAL_WALLET_PLATFORM',
    sourceTable: 'WALLET_TRANSACTIONS',
    loadType: 'STREAMING',
    grain: 'One row per wallet transaction',
    primaryKey: ['wallet_transaction_id', 'source_system'],
    schema: {
      wallet_transaction_id: "STRING PRIMARY KEY",
      source_system: "STRING PRIMARY KEY",
      customer_id: "BIGINT",
      wallet_type: "STRING COMMENT 'Venmo|PayPal|Zelle|Cash App'",
      transaction_timestamp: "TIMESTAMP",
      transaction_type: "STRING COMMENT 'P2P Send|P2P Receive|Merchant Payment'",
      transaction_amount: "DECIMAL(18,2)",
      counterparty_id: "STRING",
      transaction_status: "STRING COMMENT 'Completed|Pending|Failed'",
      device_id: "STRING",
      source_record_id: "STRING",
      load_timestamp: "TIMESTAMP",
      cdc_operation: "STRING",
    },
  },

  // Table 14: Plaid Connections
  {
    name: 'bronze.retail_plaid_connections',
    description: 'Plaid account aggregation connections',
    sourceSystem: 'PLAID_API',
    sourceTable: 'CONNECTIONS',
    loadType: 'CDC',
    grain: 'One row per Plaid connection',
    primaryKey: ['connection_id', 'source_system'],
    schema: {
      connection_id: "STRING PRIMARY KEY",
      source_system: "STRING PRIMARY KEY",
      customer_id: "BIGINT",
      institution_name: "STRING",
      institution_id: "STRING",
      connection_timestamp: "TIMESTAMP",
      connection_status: "STRING COMMENT 'Active|Disconnected|Error'",
      accounts_linked_count: "INTEGER",
      last_sync_timestamp: "TIMESTAMP",
      error_code: "STRING",
      source_record_id: "STRING",
      load_timestamp: "TIMESTAMP",
      cdc_operation: "STRING",
    },
  },

  // Table 15: Digital Account Aggregation
  {
    name: 'bronze.retail_digital_account_aggregation',
    description: 'Aggregated external account data',
    sourceSystem: 'PLAID_API',
    sourceTable: 'AGGREGATED_ACCOUNTS',
    loadType: 'DAILY',
    grain: 'One row per external account',
    primaryKey: ['aggregated_account_id', 'source_system'],
    schema: {
      aggregated_account_id: "STRING PRIMARY KEY",
      source_system: "STRING PRIMARY KEY",
      customer_id: "BIGINT",
      connection_id: "STRING",
      external_institution: "STRING",
      account_type: "STRING COMMENT 'Checking|Savings|Credit Card|Loan|Investment'",
      account_name: "STRING",
      current_balance: "DECIMAL(18,2)",
      available_balance: "DECIMAL(18,2)",
      last_updated: "TIMESTAMP",
      source_record_id: "STRING",
      load_timestamp: "TIMESTAMP",
      cdc_operation: "STRING",
    },
  },

  // Table 16: Digital Budgeting Tools
  {
    name: 'bronze.retail_digital_budgeting_tools',
    description: 'Personal financial management tool usage',
    sourceSystem: 'PFM_PLATFORM',
    sourceTable: 'BUDGETING_ACTIVITY',
    loadType: 'CDC',
    grain: 'One row per budgeting action',
    primaryKey: ['budgeting_action_id', 'source_system'],
    schema: {
      budgeting_action_id: "STRING PRIMARY KEY",
      source_system: "STRING PRIMARY KEY",
      customer_id: "BIGINT",
      action_timestamp: "TIMESTAMP",
      action_type: "STRING COMMENT 'Create Budget|Update Budget|Set Goal|View Insights'",
      budget_category: "STRING COMMENT 'Groceries|Dining|Entertainment|etc.'",
      budget_amount: "DECIMAL(18,2)",
      spending_amount: "DECIMAL(18,2)",
      channel: "STRING COMMENT 'Web|Mobile App'",
      source_record_id: "STRING",
      load_timestamp: "TIMESTAMP",
      cdc_operation: "STRING",
    },
  },

  // Table 17: Digital Device Registrations
  {
    name: 'bronze.retail_digital_device_registrations',
    description: 'Registered devices for customers',
    sourceSystem: 'DEVICE_MANAGEMENT',
    sourceTable: 'DEVICE_REGISTRY',
    loadType: 'SCD2',
    grain: 'One row per device',
    primaryKey: ['device_id', 'source_system'],
    schema: {
      device_id: "STRING PRIMARY KEY",
      source_system: "STRING PRIMARY KEY",
      customer_id: "BIGINT",
      device_type: "STRING COMMENT 'Mobile|Tablet|Desktop'",
      device_model: "STRING",
      os_type: "STRING COMMENT 'iOS|Android|Windows|macOS'",
      os_version: "STRING",
      registration_timestamp: "TIMESTAMP",
      last_used_timestamp: "TIMESTAMP",
      device_status: "STRING COMMENT 'Active|Inactive|Blocked'",
      push_notification_enabled: "BOOLEAN",
      biometric_enabled: "BOOLEAN",
      source_record_id: "STRING",
      load_timestamp: "TIMESTAMP",
      cdc_operation: "STRING",
    },
  },

  // Table 18: Digital Security Events
  {
    name: 'bronze.retail_digital_security_events',
    description: 'Security events in digital channels',
    sourceSystem: 'SECURITY_MONITORING',
    sourceTable: 'SECURITY_EVENTS',
    loadType: 'STREAMING',
    grain: 'One row per security event',
    primaryKey: ['security_event_id', 'source_system'],
    schema: {
      security_event_id: "STRING PRIMARY KEY",
      source_system: "STRING PRIMARY KEY",
      customer_id: "BIGINT",
      event_timestamp: "TIMESTAMP",
      event_type: "STRING COMMENT 'Suspicious Login|Account Lockout|Device Change|Password Reset|etc.'",
      event_severity: "STRING COMMENT 'Low|Medium|High|Critical'",
      risk_score: "INTEGER COMMENT '0-100'",
      ip_address: "STRING",
      geolocation: "STRING",
      device_id: "STRING",
      action_taken: "STRING COMMENT 'Allowed|Blocked|MFA Required|Alert Sent'",
      source_record_id: "STRING",
      load_timestamp: "TIMESTAMP",
      cdc_operation: "STRING",
    },
  },

  // Table 19: Digital Customer Feedback
  {
    name: 'bronze.retail_digital_customer_feedback',
    description: 'In-app feedback and ratings',
    sourceSystem: 'FEEDBACK_SYSTEM',
    sourceTable: 'CUSTOMER_FEEDBACK',
    loadType: 'STREAMING',
    grain: 'One row per feedback submission',
    primaryKey: ['feedback_id', 'source_system'],
    schema: {
      feedback_id: "STRING PRIMARY KEY",
      source_system: "STRING PRIMARY KEY",
      customer_id: "BIGINT",
      feedback_timestamp: "TIMESTAMP",
      feedback_type: "STRING COMMENT 'Rating|Comment|Bug Report|Feature Request'",
      rating_score: "INTEGER COMMENT '1-5'",
      feedback_text: "STRING",
      feature_rated: "STRING",
      channel: "STRING COMMENT 'Web|Mobile App'",
      app_version: "STRING",
      sentiment: "STRING COMMENT 'Positive|Neutral|Negative'",
      source_record_id: "STRING",
      load_timestamp: "TIMESTAMP",
      cdc_operation: "STRING",
    },
  },

  // Table 20: Digital Feature Adoption
  {
    name: 'bronze.retail_digital_feature_adoption',
    description: 'Feature usage and adoption tracking',
    sourceSystem: 'ANALYTICS_PLATFORM',
    sourceTable: 'FEATURE_USAGE',
    loadType: 'DAILY',
    grain: 'One row per customer per feature per day',
    primaryKey: ['customer_id', 'feature_code', 'usage_date', 'source_system'],
    schema: {
      customer_id: "BIGINT PRIMARY KEY",
      feature_code: "STRING PRIMARY KEY",
      usage_date: "DATE PRIMARY KEY",
      source_system: "STRING PRIMARY KEY",
      feature_name: "STRING",
      feature_category: "STRING COMMENT 'Payments|Savings|Investing|Budgeting|etc.'",
      usage_count: "INTEGER",
      first_usage_timestamp: "TIMESTAMP",
      last_usage_timestamp: "TIMESTAMP",
      channel: "STRING COMMENT 'Web|Mobile App'",
      source_record_id: "STRING",
      load_timestamp: "TIMESTAMP",
      cdc_operation: "STRING",
    },
  },
];

export const digitalRetailBronzeLayerComplete = {
  description: 'Complete bronze layer for digital retail domain',
  layer: 'BRONZE',
  tables: digitalRetailBronzeTables,
  totalTables: 20,
  estimatedSize: '1.2TB',
  refreshFrequency: 'Real-time streaming + CDC',
  loadPattern: 'Streaming for events, CDC for dimensional, Daily for aggregations',
};
