/**
 * DIGITAL-RETAIL ERD DEFINITIONS
 * 
 * Logical and Physical ERD definitions for digital banking channels
 * Sources: Digital banking platform, mobile app analytics, session management
 */

// LOGICAL ERD - Business Model
export const digitalRetailLogicalERD = {
  entities: [
    {
      name: 'Digital User',
      type: 'core',
      description: 'Digital banking user profiles',
      attributes: [
        { name: 'digital_user_id', type: 'BIGINT', isPrimaryKey: true },
        { name: 'customer_id', type: 'BIGINT', isForeignKey: true },
        { name: 'username', type: 'STRING', description: 'Digital banking username' },
        { name: 'enrollment_date', type: 'DATE', description: 'Digital banking enrollment date' },
        { name: 'user_status', type: 'STRING', description: 'Active|Locked|Suspended|Inactive' },
        { name: 'online_banking_enabled', type: 'BOOLEAN' },
        { name: 'mobile_banking_enabled', type: 'BOOLEAN' },
        { name: 'last_login_timestamp', type: 'TIMESTAMP' },
        { name: 'last_password_change', type: 'DATE' },
        { name: 'mfa_enabled', type: 'BOOLEAN', description: 'Multi-factor authentication' },
        { name: 'mfa_method', type: 'STRING', description: 'SMS|Email|Authenticator App|Biometric' },
        { name: 'biometric_enabled', type: 'BOOLEAN' },
        { name: 'biometric_type', type: 'STRING', description: 'Fingerprint|Face ID|Voice' },
      ],
    },
    {
      name: 'Session',
      type: 'event',
      description: 'Digital banking sessions',
      attributes: [
        { name: 'session_id', type: 'BIGINT', isPrimaryKey: true },
        { name: 'digital_user_id', type: 'BIGINT', isForeignKey: true },
        { name: 'customer_id', type: 'BIGINT', isForeignKey: true },
        { name: 'session_start_timestamp', type: 'TIMESTAMP' },
        { name: 'session_end_timestamp', type: 'TIMESTAMP' },
        { name: 'session_duration_seconds', type: 'INTEGER' },
        { name: 'channel', type: 'STRING', description: 'Web|Mobile iOS|Mobile Android|Tablet' },
        { name: 'device_type', type: 'STRING', description: 'Desktop|Mobile|Tablet' },
        { name: 'device_id', type: 'STRING', description: 'Unique device identifier' },
        { name: 'os_version', type: 'STRING', description: 'Operating system version' },
        { name: 'app_version', type: 'STRING', description: 'Mobile app version' },
        { name: 'browser', type: 'STRING', description: 'Chrome|Safari|Firefox|Edge' },
        { name: 'ip_address', type: 'STRING' },
        { name: 'geolocation', type: 'STRING', description: 'City, State from IP' },
        { name: 'authentication_method', type: 'STRING', description: 'Password|Biometric|MFA' },
      ],
    },
    {
      name: 'Digital Transaction',
      type: 'event',
      description: 'Transactions initiated via digital channels',
      attributes: [
        { name: 'transaction_id', type: 'BIGINT', isPrimaryKey: true },
        { name: 'session_id', type: 'BIGINT', isForeignKey: true },
        { name: 'customer_id', type: 'BIGINT', isForeignKey: true },
        { name: 'transaction_timestamp', type: 'TIMESTAMP' },
        { name: 'transaction_type', type: 'STRING', description: 'Transfer|Bill Pay|P2P|Mobile Deposit' },
        { name: 'from_account_id', type: 'BIGINT', isForeignKey: true },
        { name: 'to_account_id', type: 'BIGINT', isForeignKey: true },
        { name: 'amount', type: 'DECIMAL(18,2)' },
        { name: 'transaction_status', type: 'STRING', description: 'Completed|Failed|Pending|Cancelled' },
        { name: 'channel', type: 'STRING', description: 'Web|Mobile' },
        { name: 'failure_reason', type: 'STRING', description: 'Reason if failed' },
      ],
    },
    {
      name: 'Page View',
      type: 'event',
      description: 'Page and screen views in digital banking',
      attributes: [
        { name: 'page_view_id', type: 'BIGINT', isPrimaryKey: true },
        { name: 'session_id', type: 'BIGINT', isForeignKey: true },
        { name: 'customer_id', type: 'BIGINT', isForeignKey: true },
        { name: 'page_view_timestamp', type: 'TIMESTAMP' },
        { name: 'page_url', type: 'STRING', description: 'Page URL' },
        { name: 'page_title', type: 'STRING', description: 'Page title' },
        { name: 'page_category', type: 'STRING', description: 'Accounts|Transfers|Bill Pay|Settings' },
        { name: 'time_on_page_seconds', type: 'INTEGER' },
        { name: 'previous_page_url', type: 'STRING' },
        { name: 'next_page_url', type: 'STRING' },
        { name: 'exit_page_flag', type: 'BOOLEAN' },
      ],
    },
    {
      name: 'Feature Usage',
      type: 'event',
      description: 'Digital banking feature adoption and usage',
      attributes: [
        { name: 'feature_usage_id', type: 'BIGINT', isPrimaryKey: true },
        { name: 'customer_id', type: 'BIGINT', isForeignKey: true },
        { name: 'feature_name', type: 'STRING', description: 'Bill Pay|P2P|Mobile Deposit|Budgeting' },
        { name: 'first_use_timestamp', type: 'TIMESTAMP' },
        { name: 'last_use_timestamp', type: 'TIMESTAMP' },
        { name: 'total_uses', type: 'INTEGER', description: 'Lifetime usage count' },
        { name: 'uses_last_30_days', type: 'INTEGER' },
        { name: 'adoption_flag', type: 'BOOLEAN', description: 'Has used feature' },
      ],
    },
    {
      name: 'Mobile Deposit',
      type: 'event',
      description: 'Mobile check deposit transactions',
      attributes: [
        { name: 'mobile_deposit_id', type: 'BIGINT', isPrimaryKey: true },
        { name: 'customer_id', type: 'BIGINT', isForeignKey: true },
        { name: 'account_id', type: 'BIGINT', isForeignKey: true },
        { name: 'deposit_timestamp', type: 'TIMESTAMP' },
        { name: 'check_amount', type: 'DECIMAL(18,2)' },
        { name: 'deposit_status', type: 'STRING', description: 'Pending|Approved|Rejected|Reversed' },
        { name: 'front_image_url', type: 'STRING', description: 'Check front image' },
        { name: 'back_image_url', type: 'STRING', description: 'Check back image' },
        { name: 'ocr_confidence_score', type: 'DECIMAL(5,4)', description: 'OCR accuracy 0-1' },
        { name: 'approval_timestamp', type: 'TIMESTAMP' },
        { name: 'funds_available_timestamp', type: 'TIMESTAMP' },
      ],
    },
    {
      name: 'Alert Subscription',
      type: 'core',
      description: 'Customer alert and notification preferences',
      attributes: [
        { name: 'subscription_id', type: 'BIGINT', isPrimaryKey: true },
        { name: 'customer_id', type: 'BIGINT', isForeignKey: true },
        { name: 'alert_type', type: 'STRING', description: 'Low Balance|Large Deposit|Bill Pay|Fraud' },
        { name: 'delivery_method', type: 'STRING', description: 'Email|SMS|Push|In-App' },
        { name: 'threshold_amount', type: 'DECIMAL(18,2)', description: 'Threshold for alerts' },
        { name: 'enabled_flag', type: 'BOOLEAN' },
        { name: 'created_timestamp', type: 'TIMESTAMP' },
      ],
    },
    {
      name: 'Push Notification',
      type: 'event',
      description: 'Push notifications sent to mobile devices',
      attributes: [
        { name: 'notification_id', type: 'BIGINT', isPrimaryKey: true },
        { name: 'customer_id', type: 'BIGINT', isForeignKey: true },
        { name: 'sent_timestamp', type: 'TIMESTAMP' },
        { name: 'notification_type', type: 'STRING', description: 'Alert|Marketing|Transactional' },
        { name: 'notification_title', type: 'STRING' },
        { name: 'notification_body', type: 'TEXT' },
        { name: 'delivery_status', type: 'STRING', description: 'Sent|Delivered|Opened|Failed' },
        { name: 'opened_timestamp', type: 'TIMESTAMP' },
      ],
    },
  ],
  
  relationships: [
    {
      from: 'Session',
      to: 'Digital User',
      type: 'many-to-one',
      cardinality: 'N:1',
      foreignKey: 'digital_user_id',
      description: 'Sessions belong to user',
    },
    {
      from: 'Digital Transaction',
      to: 'Session',
      type: 'many-to-one',
      cardinality: 'N:1',
      foreignKey: 'session_id',
      description: 'Transactions in session',
    },
    {
      from: 'Page View',
      to: 'Session',
      type: 'many-to-one',
      cardinality: 'N:1',
      foreignKey: 'session_id',
      description: 'Page views in session',
    },
    {
      from: 'Feature Usage',
      to: 'Digital User',
      type: 'many-to-one',
      cardinality: 'N:1',
      foreignKey: 'customer_id',
      description: 'User feature adoption',
    },
    {
      from: 'Mobile Deposit',
      to: 'Digital User',
      type: 'many-to-one',
      cardinality: 'N:1',
      foreignKey: 'customer_id',
      description: 'User mobile deposits',
    },
    {
      from: 'Alert Subscription',
      to: 'Digital User',
      type: 'many-to-one',
      cardinality: 'N:1',
      foreignKey: 'customer_id',
      description: 'User alert subscriptions',
    },
  ],
};

// PHYSICAL ERD - Technical Implementation
export const digitalRetailPhysicalERD = {
  tables: [
    {
      name: 'bronze.digital_banking_users',
      description: 'Digital banking enrollment and user data',
      source: 'Digital Banking Platform',
      updateFrequency: 'Real-time',
      recordCount: '~8M users',
      attributes: [
        { name: 'digital_user_id', type: 'BIGINT', isPrimaryKey: true },
        { name: 'customer_id', type: 'BIGINT' },
        { name: 'username', type: 'VARCHAR(100)' },
        { name: 'enrollment_date', type: 'DATE' },
        { name: 'user_status', type: 'VARCHAR(50)' },
        { name: 'online_banking_enabled', type: 'BOOLEAN' },
        { name: 'mobile_banking_enabled', type: 'BOOLEAN' },
        { name: 'last_login_timestamp', type: 'TIMESTAMP' },
        { name: 'last_password_change', type: 'DATE' },
        { name: 'mfa_enabled', type: 'BOOLEAN' },
        { name: 'mfa_method', type: 'VARCHAR(50)' },
        { name: 'biometric_enabled', type: 'BOOLEAN' },
        { name: 'biometric_type', type: 'VARCHAR(50)' },
        { name: 'created_timestamp', type: 'TIMESTAMP' },
        { name: 'updated_timestamp', type: 'TIMESTAMP' },
        { name: 'source_system', type: 'VARCHAR(50)' },
      ],
    },
    {
      name: 'bronze.digital_sessions',
      description: 'Digital banking session data',
      source: 'Session Management System',
      updateFrequency: 'Real-time',
      recordCount: '~200M sessions/month',
      attributes: [
        { name: 'session_id', type: 'BIGINT', isPrimaryKey: true },
        { name: 'digital_user_id', type: 'BIGINT' },
        { name: 'customer_id', type: 'BIGINT' },
        { name: 'session_start_timestamp', type: 'TIMESTAMP' },
        { name: 'session_end_timestamp', type: 'TIMESTAMP' },
        { name: 'session_duration_seconds', type: 'INTEGER' },
        { name: 'channel', type: 'VARCHAR(50)' },
        { name: 'device_type', type: 'VARCHAR(50)' },
        { name: 'device_id', type: 'VARCHAR(200)' },
        { name: 'os_version', type: 'VARCHAR(50)' },
        { name: 'app_version', type: 'VARCHAR(50)' },
        { name: 'browser', type: 'VARCHAR(50)' },
        { name: 'ip_address', type: 'VARCHAR(45)' },
        { name: 'geolocation', type: 'VARCHAR(200)' },
        { name: 'authentication_method', type: 'VARCHAR(50)' },
        { name: 'created_timestamp', type: 'TIMESTAMP' },
        { name: 'source_system', type: 'VARCHAR(50)' },
      ],
    },
    {
      name: 'bronze.digital_transactions',
      description: 'Digital channel transaction data',
      source: 'Digital Banking Platform',
      updateFrequency: 'Real-time',
      recordCount: '~75M transactions/month',
      attributes: [
        { name: 'transaction_id', type: 'BIGINT', isPrimaryKey: true },
        { name: 'session_id', type: 'BIGINT' },
        { name: 'customer_id', type: 'BIGINT' },
        { name: 'transaction_timestamp', type: 'TIMESTAMP' },
        { name: 'transaction_type', type: 'VARCHAR(50)' },
        { name: 'from_account_id', type: 'BIGINT' },
        { name: 'to_account_id', type: 'BIGINT' },
        { name: 'amount', type: 'DECIMAL(18,2)' },
        { name: 'transaction_status', type: 'VARCHAR(50)' },
        { name: 'channel', type: 'VARCHAR(50)' },
        { name: 'failure_reason', type: 'TEXT' },
        { name: 'created_timestamp', type: 'TIMESTAMP' },
        { name: 'source_system', type: 'VARCHAR(50)' },
      ],
    },
    {
      name: 'bronze.digital_page_views',
      description: 'Page view and navigation tracking',
      source: 'Google Analytics / Adobe Analytics',
      updateFrequency: 'Real-time',
      recordCount: '~1B page views/month',
      attributes: [
        { name: 'page_view_id', type: 'BIGINT', isPrimaryKey: true },
        { name: 'session_id', type: 'BIGINT' },
        { name: 'customer_id', type: 'BIGINT' },
        { name: 'page_view_timestamp', type: 'TIMESTAMP' },
        { name: 'page_url', type: 'TEXT' },
        { name: 'page_title', type: 'VARCHAR(200)' },
        { name: 'page_category', type: 'VARCHAR(100)' },
        { name: 'time_on_page_seconds', type: 'INTEGER' },
        { name: 'previous_page_url', type: 'TEXT' },
        { name: 'next_page_url', type: 'TEXT' },
        { name: 'exit_page_flag', type: 'BOOLEAN' },
        { name: 'created_timestamp', type: 'TIMESTAMP' },
        { name: 'source_system', type: 'VARCHAR(50)' },
      ],
    },
    {
      name: 'bronze.mobile_app_events',
      description: 'Mobile app events and analytics',
      source: 'Firebase / App Analytics',
      updateFrequency: 'Real-time',
      recordCount: '~500M events/month',
      attributes: [
        { name: 'event_id', type: 'BIGINT', isPrimaryKey: true },
        { name: 'customer_id', type: 'BIGINT' },
        { name: 'session_id', type: 'BIGINT' },
        { name: 'event_timestamp', type: 'TIMESTAMP' },
        { name: 'event_name', type: 'VARCHAR(100)' },
        { name: 'event_category', type: 'VARCHAR(100)' },
        { name: 'event_properties', type: 'JSON' },
        { name: 'screen_name', type: 'VARCHAR(100)' },
        { name: 'device_model', type: 'VARCHAR(100)' },
        { name: 'os_version', type: 'VARCHAR(50)' },
        { name: 'app_version', type: 'VARCHAR(50)' },
        { name: 'created_timestamp', type: 'TIMESTAMP' },
        { name: 'source_system', type: 'VARCHAR(50)' },
      ],
    },
    {
      name: 'bronze.mobile_check_deposits',
      description: 'Mobile check deposit data',
      source: 'Remote Deposit Capture System',
      updateFrequency: 'Real-time',
      recordCount: '~25M deposits/year',
      attributes: [
        { name: 'mobile_deposit_id', type: 'BIGINT', isPrimaryKey: true },
        { name: 'customer_id', type: 'BIGINT' },
        { name: 'account_id', type: 'BIGINT' },
        { name: 'deposit_timestamp', type: 'TIMESTAMP' },
        { name: 'check_amount', type: 'DECIMAL(18,2)' },
        { name: 'deposit_status', type: 'VARCHAR(50)' },
        { name: 'front_image_url', type: 'TEXT' },
        { name: 'back_image_url', type: 'TEXT' },
        { name: 'ocr_confidence_score', type: 'DECIMAL(5,4)' },
        { name: 'approval_timestamp', type: 'TIMESTAMP' },
        { name: 'funds_available_timestamp', type: 'TIMESTAMP' },
        { name: 'created_timestamp', type: 'TIMESTAMP' },
        { name: 'source_system', type: 'VARCHAR(50)' },
      ],
    },
    {
      name: 'bronze.digital_alerts',
      description: 'Alert subscription and delivery',
      source: 'Notification Service',
      updateFrequency: 'Real-time',
      recordCount: '~50M subscriptions',
      attributes: [
        { name: 'subscription_id', type: 'BIGINT', isPrimaryKey: true },
        { name: 'customer_id', type: 'BIGINT' },
        { name: 'alert_type', type: 'VARCHAR(100)' },
        { name: 'delivery_method', type: 'VARCHAR(50)' },
        { name: 'threshold_amount', type: 'DECIMAL(18,2)' },
        { name: 'enabled_flag', type: 'BOOLEAN' },
        { name: 'created_timestamp', type: 'TIMESTAMP' },
        { name: 'updated_timestamp', type: 'TIMESTAMP' },
        { name: 'source_system', type: 'VARCHAR(50)' },
      ],
    },
    {
      name: 'bronze.push_notifications',
      description: 'Push notification delivery logs',
      source: 'Push Notification Service',
      updateFrequency: 'Real-time',
      recordCount: '~100M notifications/month',
      attributes: [
        { name: 'notification_id', type: 'BIGINT', isPrimaryKey: true },
        { name: 'customer_id', type: 'BIGINT' },
        { name: 'sent_timestamp', type: 'TIMESTAMP' },
        { name: 'notification_type', type: 'VARCHAR(50)' },
        { name: 'notification_title', type: 'VARCHAR(200)' },
        { name: 'notification_body', type: 'TEXT' },
        { name: 'delivery_status', type: 'VARCHAR(50)' },
        { name: 'opened_timestamp', type: 'TIMESTAMP' },
        { name: 'created_timestamp', type: 'TIMESTAMP' },
        { name: 'source_system', type: 'VARCHAR(50)' },
      ],
    },
  ],
  
  relationships: [
    {
      from: 'bronze.digital_sessions',
      to: 'bronze.digital_banking_users',
      type: 'many-to-one',
      cardinality: 'N:1',
      foreignKey: 'digital_user_id',
      description: 'Sessions belong to users',
    },
    {
      from: 'bronze.digital_transactions',
      to: 'bronze.digital_sessions',
      type: 'many-to-one',
      cardinality: 'N:1',
      foreignKey: 'session_id',
      description: 'Transactions in sessions',
    },
    {
      from: 'bronze.digital_page_views',
      to: 'bronze.digital_sessions',
      type: 'many-to-one',
      cardinality: 'N:1',
      foreignKey: 'session_id',
      description: 'Page views in sessions',
    },
    {
      from: 'bronze.mobile_check_deposits',
      to: 'bronze.digital_banking_users',
      type: 'many-to-one',
      cardinality: 'N:1',
      foreignKey: 'customer_id',
      description: 'Deposits by users',
    },
    {
      from: 'bronze.digital_alerts',
      to: 'bronze.digital_banking_users',
      type: 'many-to-one',
      cardinality: 'N:1',
      foreignKey: 'customer_id',
      description: 'Alert subscriptions by users',
    },
  ],
};

// Export default for easy import
export default {
  digitalRetailLogicalERD,
  digitalRetailPhysicalERD,
};
