export const digitalRetailSilverTables = [
  // Table 1: Cleansed Digital Sessions
  {
    name: 'silver.retail_digital_sessions_cleansed',
    description: 'Cleansed and validated digital banking sessions',
    layer: 'SILVER',
    sourceLayer: 'BRONZE',
    sourceTables: ['bronze.retail_digital_banking_sessions', 'bronze.retail_mobile_app_sessions'],
    transformationType: 'CLEANSING',
    scdType: 'SCD_TYPE_1',
    grain: 'One row per unique session',
    primaryKey: ['session_sk'],
    partitionBy: ['session_date'],
    clusterBy: ['customer_id', 'channel_type'],
    dataQualityMetrics: {
      completeness: 99.5,
      accuracy: 99.8,
      consistency: 99.7,
      timeliness: 99.9,
      validity: 99.6
    },
    schema: {
      session_sk: "BIGINT PRIMARY KEY COMMENT 'Surrogate key'",
      session_id: "STRING NOT NULL COMMENT 'Business key'",
      customer_id: "BIGINT NOT NULL COMMENT 'Customer identifier'",
      channel_type: "STRING NOT NULL COMMENT 'WEB, MOBILE_IOS, MOBILE_ANDROID'",
      session_start_timestamp: "TIMESTAMP NOT NULL",
      session_end_timestamp: "TIMESTAMP",
      session_duration_seconds: "INT COMMENT 'Calculated duration'",
      device_type: "STRING COMMENT 'Desktop, Mobile, Tablet'",
      browser_name: "STRING",
      browser_version: "STRING",
      operating_system: "STRING",
      ip_address_masked: "STRING COMMENT 'Masked for privacy'",
      geolocation_country: "STRING",
      geolocation_city: "STRING",
      authentication_method: "STRING COMMENT 'PASSWORD, BIOMETRIC, OTP, SSO'",
      session_status: "STRING COMMENT 'ACTIVE, EXPIRED, LOGGED_OUT, TIMED_OUT'",
      pages_viewed: "INT",
      transactions_initiated: "INT",
      session_date: "DATE NOT NULL COMMENT 'Partition key'",
      is_suspicious_flag: "BOOLEAN COMMENT 'Flagged for suspicious activity'",
      created_timestamp: "TIMESTAMP DEFAULT CURRENT_TIMESTAMP",
      updated_timestamp: "TIMESTAMP DEFAULT CURRENT_TIMESTAMP"
    }
  },

  // Table 2: Digital Login Events Cleansed
  {
    name: 'silver.retail_digital_login_events_cleansed',
    description: 'Cleansed login events with authentication details',
    layer: 'SILVER',
    sourceLayer: 'BRONZE',
    sourceTables: ['bronze.retail_digital_login_events'],
    transformationType: 'CLEANSING',
    scdType: 'SCD_TYPE_1',
    grain: 'One row per login event',
    primaryKey: ['login_event_sk'],
    partitionBy: ['login_date'],
    clusterBy: ['customer_id', 'login_status'],
    dataQualityMetrics: {
      completeness: 99.8,
      accuracy: 99.9,
      consistency: 99.8,
      timeliness: 99.9,
      validity: 99.7
    },
    schema: {
      login_event_sk: "BIGINT PRIMARY KEY COMMENT 'Surrogate key'",
      login_event_id: "STRING NOT NULL COMMENT 'Business key'",
      customer_id: "BIGINT NOT NULL",
      login_timestamp: "TIMESTAMP NOT NULL",
      login_method: "STRING NOT NULL COMMENT 'PASSWORD, BIOMETRIC, OTP, SSO, TOKEN'",
      login_status: "STRING NOT NULL COMMENT 'SUCCESS, FAILED, LOCKED, MFA_REQUIRED'",
      failure_reason: "STRING COMMENT 'Invalid password, account locked, etc.'",
      device_fingerprint: "STRING",
      channel: "STRING COMMENT 'WEB, MOBILE_APP, API'",
      ip_address_masked: "STRING",
      geolocation_country: "STRING",
      geolocation_city: "STRING",
      is_new_device: "BOOLEAN",
      mfa_method: "STRING COMMENT 'SMS, EMAIL, AUTHENTICATOR_APP, BIOMETRIC'",
      mfa_status: "STRING COMMENT 'SUCCESS, FAILED, SKIPPED'",
      risk_score: "DECIMAL(5,2) COMMENT '0-100 risk assessment'",
      login_date: "DATE NOT NULL",
      created_timestamp: "TIMESTAMP DEFAULT CURRENT_TIMESTAMP",
      updated_timestamp: "TIMESTAMP DEFAULT CURRENT_TIMESTAMP"
    }
  },

  // Table 3: Digital Transactions Cleansed
  {
    name: 'silver.retail_digital_transactions_cleansed',
    description: 'Cleansed digital banking transactions',
    layer: 'SILVER',
    sourceLayer: 'BRONZE',
    sourceTables: ['bronze.retail_digital_transactions'],
    transformationType: 'CLEANSING',
    scdType: 'SCD_TYPE_1',
    grain: 'One row per digital transaction',
    primaryKey: ['digital_transaction_sk'],
    partitionBy: ['transaction_date'],
    clusterBy: ['customer_id', 'transaction_type', 'transaction_status'],
    dataQualityMetrics: {
      completeness: 99.7,
      accuracy: 99.9,
      consistency: 99.8,
      timeliness: 99.9,
      validity: 99.8
    },
    schema: {
      digital_transaction_sk: "BIGINT PRIMARY KEY",
      transaction_id: "STRING NOT NULL COMMENT 'Business key'",
      customer_id: "BIGINT NOT NULL",
      session_id: "STRING",
      transaction_type: "STRING NOT NULL COMMENT 'TRANSFER, PAYMENT, DEPOSIT, WITHDRAWAL'",
      transaction_timestamp: "TIMESTAMP NOT NULL",
      source_account_id: "BIGINT",
      destination_account_id: "BIGINT",
      transaction_amount: "DECIMAL(18,2) NOT NULL",
      transaction_currency: "STRING NOT NULL",
      transaction_status: "STRING NOT NULL COMMENT 'PENDING, COMPLETED, FAILED, CANCELLED'",
      channel: "STRING COMMENT 'WEB, MOBILE_APP'",
      device_type: "STRING",
      authentication_method: "STRING",
      beneficiary_name: "STRING",
      beneficiary_account_masked: "STRING",
      transaction_reference: "STRING",
      error_code: "STRING",
      error_description: "STRING",
      processing_time_ms: "INT",
      transaction_date: "DATE NOT NULL",
      created_timestamp: "TIMESTAMP DEFAULT CURRENT_TIMESTAMP",
      updated_timestamp: "TIMESTAMP DEFAULT CURRENT_TIMESTAMP"
    }
  },

  // Table 4: Digital Deposit Interactions Cleansed
  {
    name: 'silver.retail_digital_deposit_interactions_cleansed',
    description: 'Cleansed deposit-related digital interactions',
    layer: 'SILVER',
    sourceLayer: 'BRONZE',
    sourceTables: ['bronze.retail_digital_deposit_interactions'],
    transformationType: 'CLEANSING',
    scdType: 'SCD_TYPE_1',
    grain: 'One row per deposit interaction',
    primaryKey: ['deposit_interaction_sk'],
    partitionBy: ['interaction_date'],
    clusterBy: ['customer_id', 'interaction_type'],
    dataQualityMetrics: {
      completeness: 99.6,
      accuracy: 99.7,
      consistency: 99.6,
      timeliness: 99.8,
      validity: 99.5
    },
    schema: {
      deposit_interaction_sk: "BIGINT PRIMARY KEY",
      interaction_id: "STRING NOT NULL COMMENT 'Business key'",
      customer_id: "BIGINT NOT NULL",
      session_id: "STRING",
      account_id: "BIGINT",
      interaction_type: "STRING NOT NULL COMMENT 'CHECK_DEPOSIT, FUND_TRANSFER, BALANCE_INQUIRY'",
      interaction_timestamp: "TIMESTAMP NOT NULL",
      check_image_id: "STRING",
      check_amount: "DECIMAL(18,2)",
      deposit_method: "STRING COMMENT 'MOBILE_CHECK_CAPTURE, ATM, DIRECT_DEPOSIT'",
      processing_status: "STRING COMMENT 'SUBMITTED, PROCESSING, COMPLETED, FAILED'",
      approval_status: "STRING COMMENT 'AUTO_APPROVED, MANUAL_REVIEW, REJECTED'",
      channel: "STRING",
      device_type: "STRING",
      interaction_duration_seconds: "INT",
      error_code: "STRING",
      interaction_date: "DATE NOT NULL",
      created_timestamp: "TIMESTAMP DEFAULT CURRENT_TIMESTAMP",
      updated_timestamp: "TIMESTAMP DEFAULT CURRENT_TIMESTAMP"
    }
  },

  // Table 5: Digital Fund Transfers Cleansed
  {
    name: 'silver.retail_digital_fund_transfers_cleansed',
    description: 'Cleansed fund transfer transactions',
    layer: 'SILVER',
    sourceLayer: 'BRONZE',
    sourceTables: ['bronze.retail_digital_fund_transfers'],
    transformationType: 'CLEANSING',
    scdType: 'SCD_TYPE_1',
    grain: 'One row per fund transfer',
    primaryKey: ['fund_transfer_sk'],
    partitionBy: ['transfer_date'],
    clusterBy: ['customer_id', 'transfer_type', 'transfer_status'],
    dataQualityMetrics: {
      completeness: 99.8,
      accuracy: 99.9,
      consistency: 99.8,
      timeliness: 99.9,
      validity: 99.7
    },
    schema: {
      fund_transfer_sk: "BIGINT PRIMARY KEY",
      transfer_id: "STRING NOT NULL COMMENT 'Business key'",
      customer_id: "BIGINT NOT NULL",
      session_id: "STRING",
      transfer_type: "STRING NOT NULL COMMENT 'INTERNAL, EXTERNAL, P2P, WIRE'",
      transfer_timestamp: "TIMESTAMP NOT NULL",
      source_account_id: "BIGINT NOT NULL",
      destination_account_id: "BIGINT",
      transfer_amount: "DECIMAL(18,2) NOT NULL",
      transfer_currency: "STRING NOT NULL",
      transfer_status: "STRING NOT NULL COMMENT 'PENDING, COMPLETED, FAILED, CANCELLED'",
      transfer_method: "STRING COMMENT 'ACH, WIRE, INSTANT, SCHEDULED'",
      beneficiary_name: "STRING",
      beneficiary_bank: "STRING",
      beneficiary_account_masked: "STRING",
      transfer_fee: "DECIMAL(18,2)",
      scheduled_date: "DATE",
      completion_timestamp: "TIMESTAMP",
      channel: "STRING",
      authentication_method: "STRING",
      transfer_date: "DATE NOT NULL",
      created_timestamp: "TIMESTAMP DEFAULT CURRENT_TIMESTAMP",
      updated_timestamp: "TIMESTAMP DEFAULT CURRENT_TIMESTAMP"
    }
  },

  // Table 6: API Request Logs Cleansed
  {
    name: 'silver.retail_api_request_logs_cleansed',
    description: 'Cleansed API request logs with performance metrics',
    layer: 'SILVER',
    sourceLayer: 'BRONZE',
    sourceTables: ['bronze.retail_api_request_logs'],
    transformationType: 'CLEANSING',
    scdType: 'SCD_TYPE_1',
    grain: 'One row per API request',
    primaryKey: ['api_request_sk'],
    partitionBy: ['request_date'],
    clusterBy: ['api_endpoint', 'response_status_code'],
    dataQualityMetrics: {
      completeness: 99.9,
      accuracy: 99.9,
      consistency: 99.8,
      timeliness: 99.9,
      validity: 99.8
    },
    schema: {
      api_request_sk: "BIGINT PRIMARY KEY",
      request_id: "STRING NOT NULL COMMENT 'Business key'",
      customer_id: "BIGINT",
      session_id: "STRING",
      api_endpoint: "STRING NOT NULL",
      http_method: "STRING NOT NULL COMMENT 'GET, POST, PUT, DELETE'",
      request_timestamp: "TIMESTAMP NOT NULL",
      response_timestamp: "TIMESTAMP",
      response_time_ms: "INT",
      response_status_code: "INT NOT NULL",
      request_size_bytes: "BIGINT",
      response_size_bytes: "BIGINT",
      ip_address_masked: "STRING",
      user_agent: "STRING",
      api_version: "STRING",
      authentication_type: "STRING COMMENT 'OAUTH, API_KEY, JWT, BASIC'",
      error_code: "STRING",
      error_message: "STRING",
      rate_limit_remaining: "INT",
      request_date: "DATE NOT NULL",
      created_timestamp: "TIMESTAMP DEFAULT CURRENT_TIMESTAMP",
      updated_timestamp: "TIMESTAMP DEFAULT CURRENT_TIMESTAMP"
    }
  },

  // Table 7: Security Events Cleansed
  {
    name: 'silver.retail_security_events_cleansed',
    description: 'Cleansed security events and alerts',
    layer: 'SILVER',
    sourceLayer: 'BRONZE',
    sourceTables: ['bronze.retail_security_events'],
    transformationType: 'CLEANSING',
    scdType: 'SCD_TYPE_1',
    grain: 'One row per security event',
    primaryKey: ['security_event_sk'],
    partitionBy: ['event_date'],
    clusterBy: ['customer_id', 'event_type', 'severity_level'],
    dataQualityMetrics: {
      completeness: 99.9,
      accuracy: 99.9,
      consistency: 99.9,
      timeliness: 99.9,
      validity: 99.9
    },
    schema: {
      security_event_sk: "BIGINT PRIMARY KEY",
      event_id: "STRING NOT NULL COMMENT 'Business key'",
      customer_id: "BIGINT",
      session_id: "STRING",
      event_type: "STRING NOT NULL COMMENT 'FAILED_LOGIN, ACCOUNT_LOCKOUT, SUSPICIOUS_TRANSACTION, etc.'",
      event_timestamp: "TIMESTAMP NOT NULL",
      severity_level: "STRING NOT NULL COMMENT 'LOW, MEDIUM, HIGH, CRITICAL'",
      event_description: "STRING",
      source_ip_masked: "STRING",
      geolocation_country: "STRING",
      device_fingerprint: "STRING",
      channel: "STRING",
      action_taken: "STRING COMMENT 'BLOCKED, FLAGGED, ALERT_SENT, MFA_REQUIRED'",
      risk_score: "DECIMAL(5,2)",
      investigated_flag: "BOOLEAN",
      resolution_status: "STRING COMMENT 'OPEN, INVESTIGATING, RESOLVED, FALSE_POSITIVE'",
      event_date: "DATE NOT NULL",
      created_timestamp: "TIMESTAMP DEFAULT CURRENT_TIMESTAMP",
      updated_timestamp: "TIMESTAMP DEFAULT CURRENT_TIMESTAMP"
    }
  },

  // Table 8: Digital Customer Interactions Aggregated
  {
    name: 'silver.retail_digital_customer_interactions_agg',
    description: 'Aggregated customer interactions across digital channels',
    layer: 'SILVER',
    sourceLayer: 'BRONZE',
    sourceTables: ['bronze.retail_digital_customer_interactions'],
    transformationType: 'AGGREGATION',
    scdType: 'SCD_TYPE_1',
    grain: 'One row per customer per day',
    primaryKey: ['customer_interaction_agg_sk'],
    partitionBy: ['interaction_date'],
    clusterBy: ['customer_id'],
    dataQualityMetrics: {
      completeness: 99.5,
      accuracy: 99.6,
      consistency: 99.5,
      timeliness: 99.7,
      validity: 99.4
    },
    schema: {
      customer_interaction_agg_sk: "BIGINT PRIMARY KEY",
      customer_id: "BIGINT NOT NULL",
      interaction_date: "DATE NOT NULL",
      total_sessions: "INT",
      total_login_attempts: "INT",
      successful_logins: "INT",
      failed_logins: "INT",
      total_transactions: "INT",
      total_transaction_amount: "DECIMAL(18,2)",
      web_sessions: "INT",
      mobile_sessions: "INT",
      pages_viewed: "INT",
      average_session_duration_seconds: "DECIMAL(10,2)",
      total_api_calls: "INT",
      total_security_events: "INT",
      high_severity_events: "INT",
      created_timestamp: "TIMESTAMP DEFAULT CURRENT_TIMESTAMP",
      updated_timestamp: "TIMESTAMP DEFAULT CURRENT_TIMESTAMP"
    }
  },

  // Table 9: Bill Payment Events Cleansed
  {
    name: 'silver.retail_bill_payment_events_cleansed',
    description: 'Cleansed bill payment events',
    layer: 'SILVER',
    sourceLayer: 'BRONZE',
    sourceTables: ['bronze.retail_bill_payment_events'],
    transformationType: 'CLEANSING',
    scdType: 'SCD_TYPE_1',
    grain: 'One row per bill payment',
    primaryKey: ['bill_payment_sk'],
    partitionBy: ['payment_date'],
    clusterBy: ['customer_id', 'payment_status'],
    dataQualityMetrics: {
      completeness: 99.7,
      accuracy: 99.8,
      consistency: 99.7,
      timeliness: 99.8,
      validity: 99.6
    },
    schema: {
      bill_payment_sk: "BIGINT PRIMARY KEY",
      payment_id: "STRING NOT NULL COMMENT 'Business key'",
      customer_id: "BIGINT NOT NULL",
      session_id: "STRING",
      biller_id: "BIGINT",
      biller_name: "STRING",
      account_number_masked: "STRING",
      payment_amount: "DECIMAL(18,2) NOT NULL",
      payment_currency: "STRING NOT NULL",
      payment_date: "DATE NOT NULL",
      scheduled_payment_date: "DATE",
      payment_status: "STRING NOT NULL COMMENT 'SCHEDULED, PROCESSING, COMPLETED, FAILED'",
      payment_method: "STRING COMMENT 'ONE_TIME, RECURRING, AUTO_PAY'",
      source_account_id: "BIGINT",
      channel: "STRING",
      confirmation_number: "STRING",
      error_code: "STRING",
      created_timestamp: "TIMESTAMP DEFAULT CURRENT_TIMESTAMP",
      updated_timestamp: "TIMESTAMP DEFAULT CURRENT_TIMESTAMP"
    }
  },

  // Table 10: Mobile Check Deposits Cleansed
  {
    name: 'silver.retail_mobile_check_deposits_cleansed',
    description: 'Cleansed mobile check deposit transactions',
    layer: 'SILVER',
    sourceLayer: 'BRONZE',
    sourceTables: ['bronze.retail_mobile_check_deposits'],
    transformationType: 'CLEANSING',
    scdType: 'SCD_TYPE_1',
    grain: 'One row per mobile check deposit',
    primaryKey: ['mobile_check_deposit_sk'],
    partitionBy: ['deposit_date'],
    clusterBy: ['customer_id', 'approval_status'],
    dataQualityMetrics: {
      completeness: 99.6,
      accuracy: 99.7,
      consistency: 99.6,
      timeliness: 99.8,
      validity: 99.5
    },
    schema: {
      mobile_check_deposit_sk: "BIGINT PRIMARY KEY",
      deposit_id: "STRING NOT NULL COMMENT 'Business key'",
      customer_id: "BIGINT NOT NULL",
      account_id: "BIGINT NOT NULL",
      check_amount: "DECIMAL(18,2) NOT NULL",
      deposit_timestamp: "TIMESTAMP NOT NULL",
      front_image_id: "STRING",
      back_image_id: "STRING",
      image_quality_score: "DECIMAL(5,2)",
      check_number: "STRING",
      approval_status: "STRING NOT NULL COMMENT 'AUTO_APPROVED, MANUAL_REVIEW, REJECTED'",
      rejection_reason: "STRING",
      funds_availability_date: "DATE",
      hold_amount: "DECIMAL(18,2)",
      hold_release_date: "DATE",
      device_type: "STRING",
      app_version: "STRING",
      deposit_date: "DATE NOT NULL",
      created_timestamp: "TIMESTAMP DEFAULT CURRENT_TIMESTAMP",
      updated_timestamp: "TIMESTAMP DEFAULT CURRENT_TIMESTAMP"
    }
  },

  // Table 11: Chatbot Interactions Cleansed
  {
    name: 'silver.retail_chatbot_interactions_cleansed',
    description: 'Cleansed chatbot and virtual assistant interactions',
    layer: 'SILVER',
    sourceLayer: 'BRONZE',
    sourceTables: ['bronze.retail_chatbot_interactions'],
    transformationType: 'CLEANSING',
    scdType: 'SCD_TYPE_1',
    grain: 'One row per chatbot session',
    primaryKey: ['chatbot_interaction_sk'],
    partitionBy: ['interaction_date'],
    clusterBy: ['customer_id', 'resolution_status'],
    dataQualityMetrics: {
      completeness: 99.5,
      accuracy: 99.6,
      consistency: 99.5,
      timeliness: 99.7,
      validity: 99.4
    },
    schema: {
      chatbot_interaction_sk: "BIGINT PRIMARY KEY",
      interaction_id: "STRING NOT NULL COMMENT 'Business key'",
      customer_id: "BIGINT",
      session_id: "STRING",
      interaction_start_timestamp: "TIMESTAMP NOT NULL",
      interaction_end_timestamp: "TIMESTAMP",
      interaction_duration_seconds: "INT",
      channel: "STRING COMMENT 'WEB, MOBILE_APP, MESSAGING_APP'",
      intent_category: "STRING COMMENT 'BALANCE_INQUIRY, TRANSFER, SUPPORT, etc.'",
      message_count: "INT",
      customer_messages: "INT",
      bot_messages: "INT",
      resolution_status: "STRING COMMENT 'RESOLVED, ESCALATED, ABANDONED'",
      escalation_reason: "STRING",
      satisfaction_rating: "INT COMMENT '1-5 scale'",
      nps_score: "INT COMMENT 'Net Promoter Score'",
      interaction_date: "DATE NOT NULL",
      created_timestamp: "TIMESTAMP DEFAULT CURRENT_TIMESTAMP",
      updated_timestamp: "TIMESTAMP DEFAULT CURRENT_TIMESTAMP"
    }
  },

  // Table 12: Account Alerts Cleansed
  {
    name: 'silver.retail_account_alerts_cleansed',
    description: 'Cleansed account alerts and notifications',
    layer: 'SILVER',
    sourceLayer: 'BRONZE',
    sourceTables: ['bronze.retail_account_alerts'],
    transformationType: 'CLEANSING',
    scdType: 'SCD_TYPE_1',
    grain: 'One row per alert',
    primaryKey: ['account_alert_sk'],
    partitionBy: ['alert_date'],
    clusterBy: ['customer_id', 'alert_type'],
    dataQualityMetrics: {
      completeness: 99.8,
      accuracy: 99.8,
      consistency: 99.7,
      timeliness: 99.9,
      validity: 99.7
    },
    schema: {
      account_alert_sk: "BIGINT PRIMARY KEY",
      alert_id: "STRING NOT NULL COMMENT 'Business key'",
      customer_id: "BIGINT NOT NULL",
      account_id: "BIGINT",
      alert_type: "STRING NOT NULL COMMENT 'LOW_BALANCE, LARGE_TRANSACTION, SECURITY, etc.'",
      alert_timestamp: "TIMESTAMP NOT NULL",
      alert_channel: "STRING NOT NULL COMMENT 'EMAIL, SMS, PUSH_NOTIFICATION, IN_APP'",
      alert_status: "STRING COMMENT 'SENT, DELIVERED, READ, FAILED'",
      alert_message: "STRING",
      trigger_value: "DECIMAL(18,2)",
      threshold_value: "DECIMAL(18,2)",
      is_read: "BOOLEAN",
      read_timestamp: "TIMESTAMP",
      action_taken: "STRING",
      alert_date: "DATE NOT NULL",
      created_timestamp: "TIMESTAMP DEFAULT CURRENT_TIMESTAMP",
      updated_timestamp: "TIMESTAMP DEFAULT CURRENT_TIMESTAMP"
    }
  },

  // Table 13: Digital Enrollment Events Cleansed
  {
    name: 'silver.retail_digital_enrollment_events_cleansed',
    description: 'Cleansed digital banking enrollment events',
    layer: 'SILVER',
    sourceLayer: 'BRONZE',
    sourceTables: ['bronze.retail_digital_enrollment_events'],
    transformationType: 'CLEANSING',
    scdType: 'SCD_TYPE_1',
    grain: 'One row per enrollment event',
    primaryKey: ['enrollment_event_sk'],
    partitionBy: ['enrollment_date'],
    clusterBy: ['customer_id', 'enrollment_status'],
    dataQualityMetrics: {
      completeness: 99.7,
      accuracy: 99.8,
      consistency: 99.7,
      timeliness: 99.8,
      validity: 99.6
    },
    schema: {
      enrollment_event_sk: "BIGINT PRIMARY KEY",
      enrollment_id: "STRING NOT NULL COMMENT 'Business key'",
      customer_id: "BIGINT NOT NULL",
      enrollment_type: "STRING NOT NULL COMMENT 'NEW_USER, SERVICE_ACTIVATION, FEATURE_ENROLLMENT'",
      service_name: "STRING COMMENT 'ONLINE_BANKING, MOBILE_APP, BILL_PAY, ALERTS'",
      enrollment_timestamp: "TIMESTAMP NOT NULL",
      enrollment_status: "STRING NOT NULL COMMENT 'STARTED, COMPLETED, ABANDONED, FAILED'",
      enrollment_channel: "STRING COMMENT 'WEB, MOBILE_APP, BRANCH, CALL_CENTER'",
      verification_method: "STRING COMMENT 'EMAIL, SMS, ID_VERIFICATION, ACCOUNT_VERIFICATION'",
      verification_status: "STRING",
      completion_timestamp: "TIMESTAMP",
      time_to_complete_minutes: "INT",
      referral_source: "STRING",
      enrollment_date: "DATE NOT NULL",
      created_timestamp: "TIMESTAMP DEFAULT CURRENT_TIMESTAMP",
      updated_timestamp: "TIMESTAMP DEFAULT CURRENT_TIMESTAMP"
    }
  },

  // Table 14: P2P Payment Events Cleansed
  {
    name: 'silver.retail_p2p_payment_events_cleansed',
    description: 'Cleansed peer-to-peer payment events',
    layer: 'SILVER',
    sourceLayer: 'BRONZE',
    sourceTables: ['bronze.retail_p2p_payment_events'],
    transformationType: 'CLEANSING',
    scdType: 'SCD_TYPE_1',
    grain: 'One row per P2P payment',
    primaryKey: ['p2p_payment_sk'],
    partitionBy: ['payment_date'],
    clusterBy: ['sender_customer_id', 'payment_status'],
    dataQualityMetrics: {
      completeness: 99.7,
      accuracy: 99.8,
      consistency: 99.7,
      timeliness: 99.9,
      validity: 99.6
    },
    schema: {
      p2p_payment_sk: "BIGINT PRIMARY KEY",
      payment_id: "STRING NOT NULL COMMENT 'Business key'",
      sender_customer_id: "BIGINT NOT NULL",
      receiver_customer_id: "BIGINT",
      receiver_contact_info_masked: "STRING COMMENT 'Email or phone masked'",
      payment_amount: "DECIMAL(18,2) NOT NULL",
      payment_currency: "STRING NOT NULL",
      payment_timestamp: "TIMESTAMP NOT NULL",
      payment_status: "STRING NOT NULL COMMENT 'PENDING, COMPLETED, FAILED, CANCELLED'",
      payment_method: "STRING COMMENT 'INSTANT, STANDARD'",
      source_account_id: "BIGINT",
      payment_note: "STRING",
      channel: "STRING",
      device_type: "STRING",
      processing_fee: "DECIMAL(18,2)",
      completion_timestamp: "TIMESTAMP",
      payment_date: "DATE NOT NULL",
      created_timestamp: "TIMESTAMP DEFAULT CURRENT_TIMESTAMP",
      updated_timestamp: "TIMESTAMP DEFAULT CURRENT_TIMESTAMP"
    }
  },

  // Table 15: Digital Service Usage Aggregated
  {
    name: 'silver.retail_digital_service_usage_agg',
    description: 'Aggregated digital service usage metrics',
    layer: 'SILVER',
    sourceLayer: 'BRONZE',
    sourceTables: ['bronze.retail_digital_service_usage'],
    transformationType: 'AGGREGATION',
    scdType: 'SCD_TYPE_1',
    grain: 'One row per customer per service per month',
    primaryKey: ['service_usage_agg_sk'],
    partitionBy: ['usage_month'],
    clusterBy: ['customer_id', 'service_type'],
    dataQualityMetrics: {
      completeness: 99.6,
      accuracy: 99.7,
      consistency: 99.6,
      timeliness: 99.7,
      validity: 99.5
    },
    schema: {
      service_usage_agg_sk: "BIGINT PRIMARY KEY",
      customer_id: "BIGINT NOT NULL",
      service_type: "STRING NOT NULL COMMENT 'BILL_PAY, MOBILE_DEPOSIT, P2P, ALERTS, etc.'",
      usage_month: "DATE NOT NULL COMMENT 'First day of month'",
      total_usage_count: "INT",
      total_usage_amount: "DECIMAL(18,2)",
      average_transaction_amount: "DECIMAL(18,2)",
      first_usage_date: "DATE",
      last_usage_date: "DATE",
      unique_sessions: "INT",
      total_errors: "INT",
      error_rate: "DECIMAL(5,2)",
      created_timestamp: "TIMESTAMP DEFAULT CURRENT_TIMESTAMP",
      updated_timestamp: "TIMESTAMP DEFAULT CURRENT_TIMESTAMP"
    }
  }
];

export const digitalRetailSilverLayerComplete = {
  description: 'Silver layer for retail digital banking domain - cleansed and aggregated data',
  layer: 'SILVER',
  tables: digitalRetailSilverTables,
  totalTables: digitalRetailSilverTables.length
};

export default digitalRetailSilverLayerComplete;
