export const insuranceRetailBronzeTables = [
  // Table 1: Insurance Policies
  {
    name: 'bronze.retail_insurance_policies',
    description: 'Raw insurance policy data',
    sourceSystem: 'INSURANCE_SYSTEM',
    sourceTable: 'POLICIES',
    loadType: 'BATCH',
    grain: 'One row per policy snapshot',
    primaryKey: ['policy_id', 'source_system', 'load_timestamp'],
    schema: {
      policy_id: "BIGINT PRIMARY KEY",
      source_system: "STRING PRIMARY KEY",
      load_timestamp: "TIMESTAMP PRIMARY KEY",
      customer_id: "BIGINT",
      policy_number: "STRING",
      policy_type: "STRING COMMENT 'LIFE, AUTO, HOME, HEALTH, TRAVEL, CREDIT_PROTECTION'",
      product_code: "STRING",
      product_name: "STRING",
      policy_status: "STRING COMMENT 'ACTIVE, PENDING, LAPSED, CANCELLED, EXPIRED'",
      effective_date: "DATE",
      expiration_date: "DATE",
      issue_date: "DATE",
      cancellation_date: "DATE",
      renewal_date: "DATE",
      policy_term_months: "INT",
      coverage_amount: "DECIMAL(18,2)",
      premium_amount: "DECIMAL(18,2)",
      premium_frequency: "STRING COMMENT 'MONTHLY, QUARTERLY, ANNUAL, ONE_TIME'",
      premium_mode: "STRING COMMENT 'DIRECT_DEBIT, CREDIT_CARD, CHECK'",
      deductible_amount: "DECIMAL(18,2)",
      beneficiary_count: "INT",
      agent_id: "BIGINT",
      underwriter_id: "BIGINT",
      created_date: "TIMESTAMP",
      updated_date: "TIMESTAMP",
      record_source: "STRING",
      load_date: "TIMESTAMP DEFAULT CURRENT_TIMESTAMP"
    }
  },

  // Table 2: Policy Holders
  {
    name: 'bronze.retail_policy_holders',
    description: 'Raw policy holder data',
    sourceSystem: 'INSURANCE_SYSTEM',
    sourceTable: 'POLICY_HOLDERS',
    loadType: 'BATCH',
    grain: 'One row per policy holder',
    primaryKey: ['policy_holder_id', 'source_system'],
    schema: {
      policy_holder_id: "BIGINT PRIMARY KEY",
      source_system: "STRING PRIMARY KEY",
      load_timestamp: "TIMESTAMP",
      policy_id: "BIGINT",
      customer_id: "BIGINT",
      holder_type: "STRING COMMENT 'PRIMARY, SECONDARY, DEPENDENT'",
      relationship: "STRING COMMENT 'SELF, SPOUSE, CHILD, PARENT, OTHER'",
      full_name: "STRING",
      date_of_birth: "DATE",
      gender: "STRING",
      occupation: "STRING",
      smoker_status: "BOOLEAN",
      health_rating: "STRING COMMENT 'EXCELLENT, GOOD, FAIR, POOR'",
      coverage_start_date: "DATE",
      coverage_end_date: "DATE",
      created_date: "TIMESTAMP",
      record_source: "STRING",
      load_date: "TIMESTAMP DEFAULT CURRENT_TIMESTAMP"
    }
  },

  // Table 3: Insurance Claims
  {
    name: 'bronze.retail_insurance_claims',
    description: 'Raw insurance claim data',
    sourceSystem: 'INSURANCE_SYSTEM',
    sourceTable: 'CLAIMS',
    loadType: 'STREAMING',
    grain: 'One row per claim',
    primaryKey: ['claim_id', 'source_system'],
    schema: {
      claim_id: "BIGINT PRIMARY KEY",
      source_system: "STRING PRIMARY KEY",
      load_timestamp: "TIMESTAMP",
      policy_id: "BIGINT",
      customer_id: "BIGINT",
      claim_number: "STRING",
      claim_date: "DATE",
      incident_date: "DATE",
      report_date: "DATE",
      claim_type: "STRING COMMENT 'HEALTH, ACCIDENT, DEATH, PROPERTY_DAMAGE, LIABILITY'",
      claim_category: "STRING",
      claim_status: "STRING COMMENT 'SUBMITTED, REVIEWING, APPROVED, DENIED, PAID, CLOSED'",
      claimed_amount: "DECIMAL(18,2)",
      approved_amount: "DECIMAL(18,2)",
      paid_amount: "DECIMAL(18,2)",
      deductible_applied: "DECIMAL(18,2)",
      claim_description: "STRING",
      incident_location: "STRING",
      adjuster_id: "BIGINT",
      approval_date: "DATE",
      payment_date: "DATE",
      denial_reason: "STRING",
      fraud_flag: "BOOLEAN",
      created_date: "TIMESTAMP",
      updated_date: "TIMESTAMP",
      record_source: "STRING",
      load_date: "TIMESTAMP DEFAULT CURRENT_TIMESTAMP"
    }
  },

  // Table 4: Premium Payments
  {
    name: 'bronze.retail_premium_payments',
    description: 'Raw premium payment transactions',
    sourceSystem: 'INSURANCE_SYSTEM',
    sourceTable: 'PREMIUM_PAYMENTS',
    loadType: 'STREAMING',
    grain: 'One row per premium payment',
    primaryKey: ['payment_id', 'source_system'],
    schema: {
      payment_id: "BIGINT PRIMARY KEY",
      source_system: "STRING PRIMARY KEY",
      load_timestamp: "TIMESTAMP",
      policy_id: "BIGINT",
      customer_id: "BIGINT",
      payment_date: "DATE",
      due_date: "DATE",
      payment_amount: "DECIMAL(18,2)",
      premium_amount: "DECIMAL(18,2)",
      late_fee: "DECIMAL(18,2)",
      discount_amount: "DECIMAL(18,2)",
      payment_method: "STRING COMMENT 'DIRECT_DEBIT, CREDIT_CARD, CHECK, CASH'",
      payment_status: "STRING COMMENT 'PENDING, PROCESSED, FAILED, REVERSED'",
      transaction_id: "STRING",
      account_id: "BIGINT",
      grace_period_used: "BOOLEAN",
      payment_channel: "STRING COMMENT 'ONLINE, MOBILE, BRANCH, MAIL, AUTO_PAY'",
      created_date: "TIMESTAMP",
      record_source: "STRING",
      load_date: "TIMESTAMP DEFAULT CURRENT_TIMESTAMP"
    }
  },

  // Table 5: Policy Quotes
  {
    name: 'bronze.retail_policy_quotes',
    description: 'Raw insurance quote data',
    sourceSystem: 'INSURANCE_SYSTEM',
    sourceTable: 'QUOTES',
    loadType: 'STREAMING',
    grain: 'One row per quote',
    primaryKey: ['quote_id', 'source_system'],
    schema: {
      quote_id: "BIGINT PRIMARY KEY",
      source_system: "STRING PRIMARY KEY",
      load_timestamp: "TIMESTAMP",
      customer_id: "BIGINT",
      quote_number: "STRING",
      quote_date: "DATE",
      quote_expiry_date: "DATE",
      product_type: "STRING",
      coverage_amount: "DECIMAL(18,2)",
      quoted_premium: "DECIMAL(18,2)",
      premium_frequency: "STRING",
      deductible_amount: "DECIMAL(18,2)",
      quote_status: "STRING COMMENT 'ACTIVE, ACCEPTED, DECLINED, EXPIRED, MODIFIED'",
      conversion_date: "DATE",
      converted_policy_id: "BIGINT",
      channel: "STRING COMMENT 'ONLINE, MOBILE, AGENT, CALL_CENTER'",
      agent_id: "BIGINT",
      risk_score: "DECIMAL(5,2)",
      created_date: "TIMESTAMP",
      updated_date: "TIMESTAMP",
      record_source: "STRING",
      load_date: "TIMESTAMP DEFAULT CURRENT_TIMESTAMP"
    }
  },

  // Table 6: Beneficiaries
  {
    name: 'bronze.retail_beneficiaries',
    description: 'Raw beneficiary data',
    sourceSystem: 'INSURANCE_SYSTEM',
    sourceTable: 'BENEFICIARIES',
    loadType: 'BATCH',
    grain: 'One row per beneficiary',
    primaryKey: ['beneficiary_id', 'source_system'],
    schema: {
      beneficiary_id: "BIGINT PRIMARY KEY",
      source_system: "STRING PRIMARY KEY",
      load_timestamp: "TIMESTAMP",
      policy_id: "BIGINT",
      customer_id: "BIGINT",
      beneficiary_type: "STRING COMMENT 'PRIMARY, CONTINGENT, REVOCABLE, IRREVOCABLE'",
      full_name: "STRING",
      relationship: "STRING",
      date_of_birth: "DATE",
      allocation_percentage: "DECIMAL(5,2)",
      contact_phone: "STRING",
      contact_email: "STRING",
      address: "STRING",
      is_active: "BOOLEAN",
      effective_date: "DATE",
      termination_date: "DATE",
      created_date: "TIMESTAMP",
      updated_date: "TIMESTAMP",
      record_source: "STRING",
      load_date: "TIMESTAMP DEFAULT CURRENT_TIMESTAMP"
    }
  },

  // Table 7: Underwriting Decisions
  {
    name: 'bronze.retail_underwriting_decisions',
    description: 'Raw underwriting decision data',
    sourceSystem: 'INSURANCE_SYSTEM',
    sourceTable: 'UNDERWRITING',
    loadType: 'BATCH',
    grain: 'One row per underwriting decision',
    primaryKey: ['underwriting_id', 'source_system'],
    schema: {
      underwriting_id: "BIGINT PRIMARY KEY",
      source_system: "STRING PRIMARY KEY",
      load_timestamp: "TIMESTAMP",
      policy_id: "BIGINT",
      quote_id: "BIGINT",
      customer_id: "BIGINT",
      underwriting_date: "DATE",
      underwriter_id: "BIGINT",
      decision: "STRING COMMENT 'APPROVED, DECLINED, APPROVED_WITH_CONDITIONS, PENDING'",
      risk_classification: "STRING COMMENT 'PREFERRED, STANDARD, SUBSTANDARD, DECLINED'",
      premium_adjustment_pct: "DECIMAL(5,2)",
      conditions: "STRING",
      medical_exam_required: "BOOLEAN",
      medical_exam_date: "DATE",
      additional_documents_required: "STRING",
      decision_reason: "STRING",
      created_date: "TIMESTAMP",
      record_source: "STRING",
      load_date: "TIMESTAMP DEFAULT CURRENT_TIMESTAMP"
    }
  },

  // Table 8: Policy Renewals
  {
    name: 'bronze.retail_policy_renewals',
    description: 'Raw policy renewal data',
    sourceSystem: 'INSURANCE_SYSTEM',
    sourceTable: 'RENEWALS',
    loadType: 'BATCH',
    grain: 'One row per renewal event',
    primaryKey: ['renewal_id', 'source_system'],
    schema: {
      renewal_id: "BIGINT PRIMARY KEY",
      source_system: "STRING PRIMARY KEY",
      load_timestamp: "TIMESTAMP",
      policy_id: "BIGINT",
      customer_id: "BIGINT",
      renewal_date: "DATE",
      previous_expiration_date: "DATE",
      new_expiration_date: "DATE",
      previous_premium: "DECIMAL(18,2)",
      new_premium: "DECIMAL(18,2)",
      premium_change_pct: "DECIMAL(5,2)",
      renewal_status: "STRING COMMENT 'RENEWED, DECLINED, PENDING, LAPSED'",
      renewal_type: "STRING COMMENT 'AUTOMATIC, MANUAL, MODIFIED'",
      coverage_changes: "STRING",
      renewal_channel: "STRING",
      agent_id: "BIGINT",
      created_date: "TIMESTAMP",
      record_source: "STRING",
      load_date: "TIMESTAMP DEFAULT CURRENT_TIMESTAMP"
    }
  },

  // Table 9: Policy Cancellations
  {
    name: 'bronze.retail_policy_cancellations',
    description: 'Raw policy cancellation data',
    sourceSystem: 'INSURANCE_SYSTEM',
    sourceTable: 'CANCELLATIONS',
    loadType: 'BATCH',
    grain: 'One row per cancellation',
    primaryKey: ['cancellation_id', 'source_system'],
    schema: {
      cancellation_id: "BIGINT PRIMARY KEY",
      source_system: "STRING PRIMARY KEY",
      load_timestamp: "TIMESTAMP",
      policy_id: "BIGINT",
      customer_id: "BIGINT",
      cancellation_date: "DATE",
      effective_cancellation_date: "DATE",
      cancellation_reason: "STRING COMMENT 'CUSTOMER_REQUEST, NON_PAYMENT, FRAUD, UNDERWRITING'",
      initiated_by: "STRING COMMENT 'CUSTOMER, COMPANY'",
      refund_amount: "DECIMAL(18,2)",
      penalty_amount: "DECIMAL(18,2)",
      cancellation_type: "STRING COMMENT 'VOLUNTARY, INVOLUNTARY'",
      replacement_policy_flag: "BOOLEAN",
      created_date: "TIMESTAMP",
      record_source: "STRING",
      load_date: "TIMESTAMP DEFAULT CURRENT_TIMESTAMP"
    }
  },

  // Table 10: Policy Endorsements
  {
    name: 'bronze.retail_policy_endorsements',
    description: 'Raw policy endorsement/change data',
    sourceSystem: 'INSURANCE_SYSTEM',
    sourceTable: 'ENDORSEMENTS',
    loadType: 'BATCH',
    grain: 'One row per endorsement',
    primaryKey: ['endorsement_id', 'source_system'],
    schema: {
      endorsement_id: "BIGINT PRIMARY KEY",
      source_system: "STRING PRIMARY KEY",
      load_timestamp: "TIMESTAMP",
      policy_id: "BIGINT",
      customer_id: "BIGINT",
      endorsement_number: "STRING",
      endorsement_date: "DATE",
      effective_date: "DATE",
      endorsement_type: "STRING COMMENT 'COVERAGE_CHANGE, BENEFICIARY_CHANGE, ADDRESS_CHANGE, NAME_CHANGE'",
      change_description: "STRING",
      premium_impact: "DECIMAL(18,2)",
      new_premium_amount: "DECIMAL(18,2)",
      approval_status: "STRING COMMENT 'PENDING, APPROVED, REJECTED'",
      approval_date: "DATE",
      created_date: "TIMESTAMP",
      record_source: "STRING",
      load_date: "TIMESTAMP DEFAULT CURRENT_TIMESTAMP"
    }
  },

  // Table 11: Insurance Agents
  {
    name: 'bronze.retail_insurance_agents',
    description: 'Raw insurance agent data',
    sourceSystem: 'INSURANCE_SYSTEM',
    sourceTable: 'AGENTS',
    loadType: 'BATCH',
    grain: 'One row per agent snapshot',
    primaryKey: ['agent_id', 'source_system', 'load_timestamp'],
    schema: {
      agent_id: "BIGINT PRIMARY KEY",
      source_system: "STRING PRIMARY KEY",
      load_timestamp: "TIMESTAMP PRIMARY KEY",
      agent_code: "STRING",
      full_name: "STRING",
      agent_type: "STRING COMMENT 'CAPTIVE, INDEPENDENT, BROKER'",
      license_number: "STRING",
      license_state: "STRING",
      license_expiry_date: "DATE",
      specialization: "STRING",
      active_policies_count: "INT",
      total_premium_volume: "DECIMAL(18,2)",
      commission_rate: "DECIMAL(5,4)",
      branch_id: "BIGINT",
      hire_date: "DATE",
      termination_date: "DATE",
      is_active: "BOOLEAN",
      created_date: "TIMESTAMP",
      updated_date: "TIMESTAMP",
      record_source: "STRING",
      load_date: "TIMESTAMP DEFAULT CURRENT_TIMESTAMP"
    }
  },

  // Table 12: Claim Adjusters
  {
    name: 'bronze.retail_claim_adjusters',
    description: 'Raw claim adjuster data',
    sourceSystem: 'INSURANCE_SYSTEM',
    sourceTable: 'ADJUSTERS',
    loadType: 'BATCH',
    grain: 'One row per adjuster',
    primaryKey: ['adjuster_id', 'source_system'],
    schema: {
      adjuster_id: "BIGINT PRIMARY KEY",
      source_system: "STRING PRIMARY KEY",
      load_timestamp: "TIMESTAMP",
      adjuster_code: "STRING",
      full_name: "STRING",
      adjuster_type: "STRING COMMENT 'STAFF, INDEPENDENT, PUBLIC'",
      license_number: "STRING",
      specialization: "STRING COMMENT 'AUTO, PROPERTY, HEALTH, LIFE'",
      active_claims_count: "INT",
      average_settlement_time_days: "INT",
      certification: "STRING",
      hire_date: "DATE",
      is_active: "BOOLEAN",
      created_date: "TIMESTAMP",
      updated_date: "TIMESTAMP",
      record_source: "STRING",
      load_date: "TIMESTAMP DEFAULT CURRENT_TIMESTAMP"
    }
  },

  // Table 13: Claim Payments
  {
    name: 'bronze.retail_claim_payments',
    description: 'Raw claim payment transactions',
    sourceSystem: 'INSURANCE_SYSTEM',
    sourceTable: 'CLAIM_PAYMENTS',
    loadType: 'STREAMING',
    grain: 'One row per claim payment',
    primaryKey: ['payment_id', 'source_system'],
    schema: {
      payment_id: "BIGINT PRIMARY KEY",
      source_system: "STRING PRIMARY KEY",
      load_timestamp: "TIMESTAMP",
      claim_id: "BIGINT",
      policy_id: "BIGINT",
      customer_id: "BIGINT",
      payment_date: "DATE",
      payment_amount: "DECIMAL(18,2)",
      payment_method: "STRING COMMENT 'CHECK, ACH, WIRE, DEBIT_CARD'",
      payment_status: "STRING COMMENT 'ISSUED, CLEARED, CANCELLED'",
      payee_name: "STRING",
      payee_type: "STRING COMMENT 'POLICY_HOLDER, BENEFICIARY, PROVIDER, THIRD_PARTY'",
      check_number: "STRING",
      transaction_reference: "STRING",
      created_date: "TIMESTAMP",
      record_source: "STRING",
      load_date: "TIMESTAMP DEFAULT CURRENT_TIMESTAMP"
    }
  },

  // Table 14: Reinsurance Agreements
  {
    name: 'bronze.retail_reinsurance_agreements',
    description: 'Raw reinsurance agreement data',
    sourceSystem: 'INSURANCE_SYSTEM',
    sourceTable: 'REINSURANCE',
    loadType: 'BATCH',
    grain: 'One row per reinsurance agreement',
    primaryKey: ['reinsurance_id', 'source_system'],
    schema: {
      reinsurance_id: "BIGINT PRIMARY KEY",
      source_system: "STRING PRIMARY KEY",
      load_timestamp: "TIMESTAMP",
      policy_id: "BIGINT",
      reinsurer_id: "BIGINT",
      reinsurer_name: "STRING",
      agreement_number: "STRING",
      agreement_type: "STRING COMMENT 'FACULTATIVE, TREATY, QUOTA_SHARE, EXCESS_OF_LOSS'",
      effective_date: "DATE",
      expiration_date: "DATE",
      ceded_premium: "DECIMAL(18,2)",
      retention_amount: "DECIMAL(18,2)",
      coverage_limit: "DECIMAL(18,2)",
      commission_rate: "DECIMAL(5,4)",
      is_active: "BOOLEAN",
      created_date: "TIMESTAMP",
      record_source: "STRING",
      load_date: "TIMESTAMP DEFAULT CURRENT_TIMESTAMP"
    }
  },

  // Table 15: Policy Lapse Events
  {
    name: 'bronze.retail_policy_lapse_events',
    description: 'Raw policy lapse event data',
    sourceSystem: 'INSURANCE_SYSTEM',
    sourceTable: 'LAPSE_EVENTS',
    loadType: 'BATCH',
    grain: 'One row per lapse event',
    primaryKey: ['lapse_id', 'source_system'],
    schema: {
      lapse_id: "BIGINT PRIMARY KEY",
      source_system: "STRING PRIMARY KEY",
      load_timestamp: "TIMESTAMP",
      policy_id: "BIGINT",
      customer_id: "BIGINT",
      lapse_date: "DATE",
      lapse_reason: "STRING COMMENT 'NON_PAYMENT, VOLUNTARY_SURRENDER'",
      grace_period_days: "INT",
      missed_payments: "INT",
      outstanding_premium: "DECIMAL(18,2)",
      surrender_value: "DECIMAL(18,2)",
      reinstatement_eligible: "BOOLEAN",
      reinstatement_deadline: "DATE",
      created_date: "TIMESTAMP",
      record_source: "STRING",
      load_date: "TIMESTAMP DEFAULT CURRENT_TIMESTAMP"
    }
  },

  // Table 16: Policy Reinstatements
  {
    name: 'bronze.retail_policy_reinstatements',
    description: 'Raw policy reinstatement data',
    sourceSystem: 'INSURANCE_SYSTEM',
    sourceTable: 'REINSTATEMENTS',
    loadType: 'BATCH',
    grain: 'One row per reinstatement',
    primaryKey: ['reinstatement_id', 'source_system'],
    schema: {
      reinstatement_id: "BIGINT PRIMARY KEY",
      source_system: "STRING PRIMARY KEY",
      load_timestamp: "TIMESTAMP",
      policy_id: "BIGINT",
      customer_id: "BIGINT",
      lapse_id: "BIGINT",
      reinstatement_date: "DATE",
      lapse_date: "DATE",
      lapse_duration_days: "INT",
      reinstatement_premium: "DECIMAL(18,2)",
      late_fees: "DECIMAL(18,2)",
      interest_charges: "DECIMAL(18,2)",
      total_amount_paid: "DECIMAL(18,2)",
      new_effective_date: "DATE",
      underwriting_required: "BOOLEAN",
      created_date: "TIMESTAMP",
      record_source: "STRING",
      load_date: "TIMESTAMP DEFAULT CURRENT_TIMESTAMP"
    }
  },

  // Table 17: Risk Assessments
  {
    name: 'bronze.retail_risk_assessments',
    description: 'Raw risk assessment data',
    sourceSystem: 'INSURANCE_SYSTEM',
    sourceTable: 'RISK_ASSESSMENTS',
    loadType: 'BATCH',
    grain: 'One row per risk assessment',
    primaryKey: ['assessment_id', 'source_system'],
    schema: {
      assessment_id: "BIGINT PRIMARY KEY",
      source_system: "STRING PRIMARY KEY",
      load_timestamp: "TIMESTAMP",
      policy_id: "BIGINT",
      quote_id: "BIGINT",
      customer_id: "BIGINT",
      assessment_date: "DATE",
      risk_score: "DECIMAL(5,2)",
      risk_category: "STRING COMMENT 'LOW, MEDIUM, HIGH, VERY_HIGH'",
      assessment_factors: "STRING",
      health_score: "DECIMAL(5,2)",
      lifestyle_score: "DECIMAL(5,2)",
      occupation_risk: "STRING",
      geographic_risk: "STRING",
      credit_score: "INT",
      claims_history_score: "DECIMAL(5,2)",
      created_date: "TIMESTAMP",
      record_source: "STRING",
      load_date: "TIMESTAMP DEFAULT CURRENT_TIMESTAMP"
    }
  },

  // Table 18: Commission Payments
  {
    name: 'bronze.retail_commission_payments',
    description: 'Raw agent commission payment data',
    sourceSystem: 'INSURANCE_SYSTEM',
    sourceTable: 'COMMISSIONS',
    loadType: 'BATCH',
    grain: 'One row per commission payment',
    primaryKey: ['commission_id', 'source_system'],
    schema: {
      commission_id: "BIGINT PRIMARY KEY",
      source_system: "STRING PRIMARY KEY",
      load_timestamp: "TIMESTAMP",
      agent_id: "BIGINT",
      policy_id: "BIGINT",
      commission_type: "STRING COMMENT 'FIRST_YEAR, RENEWAL, OVERRIDE, BONUS'",
      commission_period_start: "DATE",
      commission_period_end: "DATE",
      premium_amount: "DECIMAL(18,2)",
      commission_rate: "DECIMAL(5,4)",
      commission_amount: "DECIMAL(18,2)",
      payment_date: "DATE",
      payment_status: "STRING COMMENT 'PENDING, PAID, REVERSED'",
      payment_method: "STRING",
      created_date: "TIMESTAMP",
      record_source: "STRING",
      load_date: "TIMESTAMP DEFAULT CURRENT_TIMESTAMP"
    }
  },

  // Table 19: Policy Documents
  {
    name: 'bronze.retail_policy_documents',
    description: 'Raw policy document metadata',
    sourceSystem: 'INSURANCE_SYSTEM',
    sourceTable: 'DOCUMENTS',
    loadType: 'STREAMING',
    grain: 'One row per document',
    primaryKey: ['document_id', 'source_system'],
    schema: {
      document_id: "BIGINT PRIMARY KEY",
      source_system: "STRING PRIMARY KEY",
      load_timestamp: "TIMESTAMP",
      policy_id: "BIGINT",
      customer_id: "BIGINT",
      document_type: "STRING COMMENT 'POLICY_CONTRACT, DECLARATION_PAGE, ENDORSEMENT, CLAIM_FORM'",
      document_name: "STRING",
      document_date: "DATE",
      document_url: "STRING",
      file_size_kb: "BIGINT",
      file_format: "STRING",
      version_number: "INT",
      is_signed: "BOOLEAN",
      signature_date: "DATE",
      created_date: "TIMESTAMP",
      record_source: "STRING",
      load_date: "TIMESTAMP DEFAULT CURRENT_TIMESTAMP"
    }
  },

  // Table 20: Customer Service Interactions
  {
    name: 'bronze.retail_insurance_service_interactions',
    description: 'Raw customer service interaction data',
    sourceSystem: 'INSURANCE_SYSTEM',
    sourceTable: 'SERVICE_INTERACTIONS',
    loadType: 'STREAMING',
    grain: 'One row per interaction',
    primaryKey: ['interaction_id', 'source_system'],
    schema: {
      interaction_id: "BIGINT PRIMARY KEY",
      source_system: "STRING PRIMARY KEY",
      load_timestamp: "TIMESTAMP",
      customer_id: "BIGINT",
      policy_id: "BIGINT",
      interaction_date: "DATE",
      interaction_timestamp: "TIMESTAMP",
      interaction_type: "STRING COMMENT 'INQUIRY, COMPLAINT, CLAIM_STATUS, POLICY_CHANGE'",
      channel: "STRING COMMENT 'PHONE, EMAIL, CHAT, MOBILE_APP, BRANCH'",
      agent_id: "BIGINT",
      duration_seconds: "INT",
      resolution_status: "STRING COMMENT 'RESOLVED, PENDING, ESCALATED'",
      satisfaction_rating: "INT COMMENT '1-5 scale'",
      interaction_notes: "STRING",
      created_date: "TIMESTAMP",
      record_source: "STRING",
      load_date: "TIMESTAMP DEFAULT CURRENT_TIMESTAMP"
    }
  }
];

export const insuranceRetailBronzeLayerComplete = {
  description: 'Bronze layer for retail insurance domain - raw data from source systems',
  layer: 'BRONZE',
  tables: insuranceRetailBronzeTables,
  totalTables: insuranceRetailBronzeTables.length
};

export default insuranceRetailBronzeLayerComplete;
