export const investmentRetailBronzeTables = [
  // Table 1: Investment Accounts
  {
    name: 'bronze.retail_investment_accounts',
    description: 'Raw investment account data',
    sourceSystem: 'INVESTMENT_PLATFORM',
    sourceTable: 'INVESTMENT_ACCOUNTS',
    loadType: 'BATCH',
    grain: 'One row per investment account snapshot',
    primaryKey: ['account_id', 'source_system', 'load_timestamp'],
    schema: {
      account_id: "BIGINT PRIMARY KEY",
      source_system: "STRING PRIMARY KEY",
      load_timestamp: "TIMESTAMP PRIMARY KEY",
      customer_id: "BIGINT",
      account_number: "STRING",
      account_type: "STRING COMMENT 'BROKERAGE, IRA, ROTH_IRA, 401K, 529_PLAN'",
      account_status: "STRING COMMENT 'ACTIVE, CLOSED, SUSPENDED, RESTRICTED'",
      open_date: "DATE",
      close_date: "DATE",
      account_balance: "DECIMAL(18,2)",
      cash_balance: "DECIMAL(18,2)",
      market_value: "DECIMAL(18,2)",
      total_cost_basis: "DECIMAL(18,2)",
      unrealized_gain_loss: "DECIMAL(18,2)",
      currency_code: "STRING",
      tax_status: "STRING COMMENT 'TAXABLE, TAX_DEFERRED, TAX_FREE'",
      managed_account_flag: "BOOLEAN",
      advisor_id: "BIGINT",
      margin_enabled_flag: "BOOLEAN",
      margin_balance: "DECIMAL(18,2)",
      buying_power: "DECIMAL(18,2)",
      created_date: "TIMESTAMP",
      updated_date: "TIMESTAMP",
      record_source: "STRING",
      load_date: "TIMESTAMP DEFAULT CURRENT_TIMESTAMP"
    }
  },

  // Table 2: Investment Holdings
  {
    name: 'bronze.retail_investment_holdings',
    description: 'Raw investment holdings data',
    sourceSystem: 'INVESTMENT_PLATFORM',
    sourceTable: 'HOLDINGS',
    loadType: 'BATCH',
    grain: 'One row per holding snapshot',
    primaryKey: ['holding_id', 'source_system', 'load_timestamp'],
    schema: {
      holding_id: "BIGINT PRIMARY KEY",
      source_system: "STRING PRIMARY KEY",
      load_timestamp: "TIMESTAMP PRIMARY KEY",
      account_id: "BIGINT",
      customer_id: "BIGINT",
      security_id: "BIGINT",
      symbol: "STRING",
      cusip: "STRING",
      isin: "STRING",
      security_type: "STRING COMMENT 'STOCK, BOND, MUTUAL_FUND, ETF, OPTION'",
      quantity: "DECIMAL(18,6)",
      market_price: "DECIMAL(18,6)",
      market_value: "DECIMAL(18,2)",
      cost_basis: "DECIMAL(18,2)",
      average_cost_per_share: "DECIMAL(18,6)",
      unrealized_gain_loss: "DECIMAL(18,2)",
      unrealized_gain_loss_pct: "DECIMAL(5,2)",
      currency_code: "STRING",
      holding_date: "DATE",
      acquisition_date: "DATE",
      maturity_date: "DATE",
      created_date: "TIMESTAMP",
      updated_date: "TIMESTAMP",
      record_source: "STRING",
      load_date: "TIMESTAMP DEFAULT CURRENT_TIMESTAMP"
    }
  },

  // Table 3: Investment Trades
  {
    name: 'bronze.retail_investment_trades',
    description: 'Raw investment trade transactions',
    sourceSystem: 'INVESTMENT_PLATFORM',
    sourceTable: 'TRADES',
    loadType: 'STREAMING',
    grain: 'One row per trade',
    primaryKey: ['trade_id', 'source_system'],
    schema: {
      trade_id: "BIGINT PRIMARY KEY",
      source_system: "STRING PRIMARY KEY",
      load_timestamp: "TIMESTAMP",
      account_id: "BIGINT",
      customer_id: "BIGINT",
      order_id: "BIGINT",
      security_id: "BIGINT",
      symbol: "STRING",
      cusip: "STRING",
      trade_date: "DATE",
      settlement_date: "DATE",
      trade_type: "STRING COMMENT 'BUY, SELL, SHORT, COVER'",
      order_type: "STRING COMMENT 'MARKET, LIMIT, STOP, STOP_LIMIT'",
      quantity: "DECIMAL(18,6)",
      price: "DECIMAL(18,6)",
      gross_amount: "DECIMAL(18,2)",
      commission: "DECIMAL(18,2)",
      sec_fee: "DECIMAL(18,2)",
      other_fees: "DECIMAL(18,2)",
      net_amount: "DECIMAL(18,2)",
      currency_code: "STRING",
      execution_timestamp: "TIMESTAMP",
      execution_venue: "STRING",
      trade_status: "STRING COMMENT 'PENDING, EXECUTED, SETTLED, CANCELLED'",
      solicited_flag: "BOOLEAN",
      created_date: "TIMESTAMP",
      record_source: "STRING",
      load_date: "TIMESTAMP DEFAULT CURRENT_TIMESTAMP"
    }
  },

  // Table 4: Investment Orders
  {
    name: 'bronze.retail_investment_orders',
    description: 'Raw investment order data',
    sourceSystem: 'INVESTMENT_PLATFORM',
    sourceTable: 'ORDERS',
    loadType: 'STREAMING',
    grain: 'One row per order',
    primaryKey: ['order_id', 'source_system'],
    schema: {
      order_id: "BIGINT PRIMARY KEY",
      source_system: "STRING PRIMARY KEY",
      load_timestamp: "TIMESTAMP",
      account_id: "BIGINT",
      customer_id: "BIGINT",
      security_id: "BIGINT",
      symbol: "STRING",
      order_date: "DATE",
      order_timestamp: "TIMESTAMP",
      order_type: "STRING COMMENT 'MARKET, LIMIT, STOP, STOP_LIMIT, TRAILING_STOP'",
      action: "STRING COMMENT 'BUY, SELL, SHORT, COVER'",
      quantity: "DECIMAL(18,6)",
      limit_price: "DECIMAL(18,6)",
      stop_price: "DECIMAL(18,6)",
      time_in_force: "STRING COMMENT 'DAY, GTC, IOC, FOK'",
      order_status: "STRING COMMENT 'PENDING, PARTIAL, FILLED, CANCELLED, REJECTED'",
      filled_quantity: "DECIMAL(18,6)",
      remaining_quantity: "DECIMAL(18,6)",
      average_fill_price: "DECIMAL(18,6)",
      channel: "STRING COMMENT 'ONLINE, MOBILE, PHONE, ADVISOR'",
      rejection_reason: "STRING",
      created_date: "TIMESTAMP",
      updated_date: "TIMESTAMP",
      record_source: "STRING",
      load_date: "TIMESTAMP DEFAULT CURRENT_TIMESTAMP"
    }
  },

  // Table 5: Investment Transactions
  {
    name: 'bronze.retail_investment_transactions',
    description: 'Raw investment account transactions',
    sourceSystem: 'INVESTMENT_PLATFORM',
    sourceTable: 'TRANSACTIONS',
    loadType: 'STREAMING',
    grain: 'One row per transaction',
    primaryKey: ['transaction_id', 'source_system'],
    schema: {
      transaction_id: "BIGINT PRIMARY KEY",
      source_system: "STRING PRIMARY KEY",
      load_timestamp: "TIMESTAMP",
      account_id: "BIGINT",
      customer_id: "BIGINT",
      transaction_date: "DATE",
      transaction_timestamp: "TIMESTAMP",
      transaction_type: "STRING COMMENT 'DEPOSIT, WITHDRAWAL, DIVIDEND, INTEREST, FEE'",
      transaction_category: "STRING COMMENT 'CASH, TRADE, INCOME, CORPORATE_ACTION'",
      amount: "DECIMAL(18,2)",
      currency_code: "STRING",
      security_id: "BIGINT",
      symbol: "STRING",
      quantity: "DECIMAL(18,6)",
      price: "DECIMAL(18,6)",
      description: "STRING",
      related_transaction_id: "BIGINT",
      trade_id: "BIGINT",
      created_date: "TIMESTAMP",
      record_source: "STRING",
      load_date: "TIMESTAMP DEFAULT CURRENT_TIMESTAMP"
    }
  },

  // Table 6: Investment Securities Master
  {
    name: 'bronze.retail_investment_securities',
    description: 'Raw securities master data',
    sourceSystem: 'MARKET_DATA_FEED',
    sourceTable: 'SECURITIES',
    loadType: 'BATCH',
    grain: 'One row per security snapshot',
    primaryKey: ['security_id', 'source_system', 'load_timestamp'],
    schema: {
      security_id: "BIGINT PRIMARY KEY",
      source_system: "STRING PRIMARY KEY",
      load_timestamp: "TIMESTAMP PRIMARY KEY",
      symbol: "STRING",
      cusip: "STRING",
      isin: "STRING",
      sedol: "STRING",
      security_name: "STRING",
      security_type: "STRING COMMENT 'STOCK, BOND, MUTUAL_FUND, ETF, OPTION, COMMODITY'",
      asset_class: "STRING COMMENT 'EQUITY, FIXED_INCOME, ALTERNATIVE, CASH'",
      exchange: "STRING",
      country_code: "STRING",
      currency_code: "STRING",
      sector: "STRING",
      industry: "STRING",
      issuer: "STRING",
      issue_date: "DATE",
      maturity_date: "DATE",
      coupon_rate: "DECIMAL(5,4)",
      par_value: "DECIMAL(18,2)",
      dividend_yield: "DECIMAL(5,4)",
      expense_ratio: "DECIMAL(5,4)",
      is_active: "BOOLEAN",
      created_date: "TIMESTAMP",
      updated_date: "TIMESTAMP",
      record_source: "STRING",
      load_date: "TIMESTAMP DEFAULT CURRENT_TIMESTAMP"
    }
  },

  // Table 7: Market Prices
  {
    name: 'bronze.retail_market_prices',
    description: 'Raw market price data',
    sourceSystem: 'MARKET_DATA_FEED',
    sourceTable: 'PRICES',
    loadType: 'STREAMING',
    grain: 'One row per security per price timestamp',
    primaryKey: ['security_id', 'price_timestamp', 'source_system'],
    schema: {
      security_id: "BIGINT PRIMARY KEY",
      price_timestamp: "TIMESTAMP PRIMARY KEY",
      source_system: "STRING PRIMARY KEY",
      load_timestamp: "TIMESTAMP",
      symbol: "STRING",
      price_date: "DATE",
      open_price: "DECIMAL(18,6)",
      high_price: "DECIMAL(18,6)",
      low_price: "DECIMAL(18,6)",
      close_price: "DECIMAL(18,6)",
      last_price: "DECIMAL(18,6)",
      bid_price: "DECIMAL(18,6)",
      ask_price: "DECIMAL(18,6)",
      volume: "BIGINT",
      vwap: "DECIMAL(18,6) COMMENT 'Volume Weighted Average Price'",
      adjusted_close: "DECIMAL(18,6)",
      currency_code: "STRING",
      created_date: "TIMESTAMP",
      record_source: "STRING",
      load_date: "TIMESTAMP DEFAULT CURRENT_TIMESTAMP"
    }
  },

  // Table 8: Dividend Payments
  {
    name: 'bronze.retail_dividend_payments',
    description: 'Raw dividend payment data',
    sourceSystem: 'INVESTMENT_PLATFORM',
    sourceTable: 'DIVIDENDS',
    loadType: 'BATCH',
    grain: 'One row per dividend payment',
    primaryKey: ['dividend_id', 'source_system'],
    schema: {
      dividend_id: "BIGINT PRIMARY KEY",
      source_system: "STRING PRIMARY KEY",
      load_timestamp: "TIMESTAMP",
      account_id: "BIGINT",
      customer_id: "BIGINT",
      security_id: "BIGINT",
      symbol: "STRING",
      ex_dividend_date: "DATE",
      record_date: "DATE",
      payment_date: "DATE",
      dividend_type: "STRING COMMENT 'CASH, STOCK, SPECIAL'",
      dividend_per_share: "DECIMAL(18,6)",
      shares_held: "DECIMAL(18,6)",
      gross_dividend: "DECIMAL(18,2)",
      withholding_tax: "DECIMAL(18,2)",
      net_dividend: "DECIMAL(18,2)",
      currency_code: "STRING",
      reinvestment_flag: "BOOLEAN",
      created_date: "TIMESTAMP",
      record_source: "STRING",
      load_date: "TIMESTAMP DEFAULT CURRENT_TIMESTAMP"
    }
  },

  // Table 9: Interest Payments
  {
    name: 'bronze.retail_interest_payments',
    description: 'Raw interest payment data',
    sourceSystem: 'INVESTMENT_PLATFORM',
    sourceTable: 'INTEREST',
    loadType: 'BATCH',
    grain: 'One row per interest payment',
    primaryKey: ['interest_id', 'source_system'],
    schema: {
      interest_id: "BIGINT PRIMARY KEY",
      source_system: "STRING PRIMARY KEY",
      load_timestamp: "TIMESTAMP",
      account_id: "BIGINT",
      customer_id: "BIGINT",
      security_id: "BIGINT",
      symbol: "STRING",
      payment_date: "DATE",
      interest_type: "STRING COMMENT 'COUPON, MARGIN, CASH_BALANCE'",
      gross_interest: "DECIMAL(18,2)",
      withholding_tax: "DECIMAL(18,2)",
      net_interest: "DECIMAL(18,2)",
      currency_code: "STRING",
      accrual_start_date: "DATE",
      accrual_end_date: "DATE",
      created_date: "TIMESTAMP",
      record_source: "STRING",
      load_date: "TIMESTAMP DEFAULT CURRENT_TIMESTAMP"
    }
  },

  // Table 10: Capital Gains
  {
    name: 'bronze.retail_capital_gains',
    description: 'Raw capital gains data',
    sourceSystem: 'INVESTMENT_PLATFORM',
    sourceTable: 'CAPITAL_GAINS',
    loadType: 'BATCH',
    grain: 'One row per capital gain event',
    primaryKey: ['capital_gain_id', 'source_system'],
    schema: {
      capital_gain_id: "BIGINT PRIMARY KEY",
      source_system: "STRING PRIMARY KEY",
      load_timestamp: "TIMESTAMP",
      account_id: "BIGINT",
      customer_id: "BIGINT",
      trade_id: "BIGINT",
      security_id: "BIGINT",
      symbol: "STRING",
      sale_date: "DATE",
      purchase_date: "DATE",
      quantity_sold: "DECIMAL(18,6)",
      sale_price: "DECIMAL(18,6)",
      purchase_price: "DECIMAL(18,6)",
      gross_proceeds: "DECIMAL(18,2)",
      cost_basis: "DECIMAL(18,2)",
      realized_gain_loss: "DECIMAL(18,2)",
      gain_loss_type: "STRING COMMENT 'SHORT_TERM, LONG_TERM'",
      holding_period_days: "INT",
      wash_sale_flag: "BOOLEAN",
      currency_code: "STRING",
      created_date: "TIMESTAMP",
      record_source: "STRING",
      load_date: "TIMESTAMP DEFAULT CURRENT_TIMESTAMP"
    }
  },

  // Table 11: Portfolio Rebalancing
  {
    name: 'bronze.retail_portfolio_rebalancing',
    description: 'Raw portfolio rebalancing events',
    sourceSystem: 'INVESTMENT_PLATFORM',
    sourceTable: 'REBALANCING',
    loadType: 'BATCH',
    grain: 'One row per rebalancing event',
    primaryKey: ['rebalancing_id', 'source_system'],
    schema: {
      rebalancing_id: "BIGINT PRIMARY KEY",
      source_system: "STRING PRIMARY KEY",
      load_timestamp: "TIMESTAMP",
      account_id: "BIGINT",
      customer_id: "BIGINT",
      rebalancing_date: "DATE",
      rebalancing_type: "STRING COMMENT 'SCHEDULED, THRESHOLD, MANUAL'",
      target_allocation_id: "BIGINT",
      previous_allocation_id: "BIGINT",
      total_trades: "INT",
      total_value_traded: "DECIMAL(18,2)",
      rebalancing_status: "STRING COMMENT 'PENDING, IN_PROGRESS, COMPLETED, FAILED'",
      trigger_reason: "STRING",
      created_date: "TIMESTAMP",
      updated_date: "TIMESTAMP",
      record_source: "STRING",
      load_date: "TIMESTAMP DEFAULT CURRENT_TIMESTAMP"
    }
  },

  // Table 12: Asset Allocation
  {
    name: 'bronze.retail_asset_allocation',
    description: 'Raw asset allocation data',
    sourceSystem: 'INVESTMENT_PLATFORM',
    sourceTable: 'ASSET_ALLOCATION',
    loadType: 'BATCH',
    grain: 'One row per account allocation snapshot',
    primaryKey: ['allocation_id', 'source_system', 'load_timestamp'],
    schema: {
      allocation_id: "BIGINT PRIMARY KEY",
      source_system: "STRING PRIMARY KEY",
      load_timestamp: "TIMESTAMP PRIMARY KEY",
      account_id: "BIGINT",
      customer_id: "BIGINT",
      allocation_date: "DATE",
      allocation_type: "STRING COMMENT 'CURRENT, TARGET, MODEL'",
      equity_pct: "DECIMAL(5,2)",
      fixed_income_pct: "DECIMAL(5,2)",
      cash_pct: "DECIMAL(5,2)",
      alternative_pct: "DECIMAL(5,2)",
      international_pct: "DECIMAL(5,2)",
      domestic_pct: "DECIMAL(5,2)",
      total_market_value: "DECIMAL(18,2)",
      risk_score: "DECIMAL(5,2)",
      created_date: "TIMESTAMP",
      updated_date: "TIMESTAMP",
      record_source: "STRING",
      load_date: "TIMESTAMP DEFAULT CURRENT_TIMESTAMP"
    }
  },

  // Table 13: Investment Goals
  {
    name: 'bronze.retail_investment_goals',
    description: 'Raw investment goal data',
    sourceSystem: 'INVESTMENT_PLATFORM',
    sourceTable: 'GOALS',
    loadType: 'BATCH',
    grain: 'One row per investment goal',
    primaryKey: ['goal_id', 'source_system'],
    schema: {
      goal_id: "BIGINT PRIMARY KEY",
      source_system: "STRING PRIMARY KEY",
      load_timestamp: "TIMESTAMP",
      customer_id: "BIGINT",
      account_id: "BIGINT",
      goal_name: "STRING",
      goal_type: "STRING COMMENT 'RETIREMENT, EDUCATION, HOME, WEALTH_BUILDING'",
      target_amount: "DECIMAL(18,2)",
      current_value: "DECIMAL(18,2)",
      target_date: "DATE",
      monthly_contribution: "DECIMAL(18,2)",
      risk_tolerance: "STRING COMMENT 'CONSERVATIVE, MODERATE, AGGRESSIVE'",
      goal_status: "STRING COMMENT 'ON_TRACK, BEHIND, AHEAD, ACHIEVED'",
      created_date: "TIMESTAMP",
      updated_date: "TIMESTAMP",
      record_source: "STRING",
      load_date: "TIMESTAMP DEFAULT CURRENT_TIMESTAMP"
    }
  },

  // Table 14: Investment Advisor Assignments
  {
    name: 'bronze.retail_investment_advisor_assignments',
    description: 'Raw advisor-customer assignment data',
    sourceSystem: 'INVESTMENT_PLATFORM',
    sourceTable: 'ADVISOR_ASSIGNMENTS',
    loadType: 'BATCH',
    grain: 'One row per advisor assignment',
    primaryKey: ['assignment_id', 'source_system'],
    schema: {
      assignment_id: "BIGINT PRIMARY KEY",
      source_system: "STRING PRIMARY KEY",
      load_timestamp: "TIMESTAMP",
      customer_id: "BIGINT",
      advisor_id: "BIGINT",
      account_id: "BIGINT",
      assignment_date: "DATE",
      assignment_type: "STRING COMMENT 'PRIMARY, SECONDARY, TEAM'",
      relationship_type: "STRING COMMENT 'MANAGED, ADVISORY, ROBO_ADVISOR'",
      fee_structure: "STRING COMMENT 'AUM_BASED, FLAT_FEE, COMMISSION'",
      fee_rate: "DECIMAL(5,4)",
      assignment_status: "STRING COMMENT 'ACTIVE, TERMINATED'",
      termination_date: "DATE",
      created_date: "TIMESTAMP",
      updated_date: "TIMESTAMP",
      record_source: "STRING",
      load_date: "TIMESTAMP DEFAULT CURRENT_TIMESTAMP"
    }
  },

  // Table 15: Investment Performance
  {
    name: 'bronze.retail_investment_performance',
    description: 'Raw investment performance metrics',
    sourceSystem: 'INVESTMENT_PLATFORM',
    sourceTable: 'PERFORMANCE',
    loadType: 'BATCH',
    grain: 'One row per account per period',
    primaryKey: ['performance_id', 'source_system'],
    schema: {
      performance_id: "BIGINT PRIMARY KEY",
      source_system: "STRING PRIMARY KEY",
      load_timestamp: "TIMESTAMP",
      account_id: "BIGINT",
      customer_id: "BIGINT",
      period_start_date: "DATE",
      period_end_date: "DATE",
      period_type: "STRING COMMENT 'DAILY, MONTHLY, QUARTERLY, ANNUAL, INCEPTION'",
      beginning_value: "DECIMAL(18,2)",
      ending_value: "DECIMAL(18,2)",
      net_contributions: "DECIMAL(18,2)",
      net_withdrawals: "DECIMAL(18,2)",
      total_return: "DECIMAL(18,2)",
      total_return_pct: "DECIMAL(5,2)",
      time_weighted_return_pct: "DECIMAL(5,2)",
      money_weighted_return_pct: "DECIMAL(5,2)",
      benchmark_return_pct: "DECIMAL(5,2)",
      alpha: "DECIMAL(5,2)",
      beta: "DECIMAL(5,2)",
      sharpe_ratio: "DECIMAL(5,2)",
      volatility: "DECIMAL(5,2)",
      created_date: "TIMESTAMP",
      record_source: "STRING",
      load_date: "TIMESTAMP DEFAULT CURRENT_TIMESTAMP"
    }
  },

  // Table 16: Tax Lot Details
  {
    name: 'bronze.retail_tax_lots',
    description: 'Raw tax lot data',
    sourceSystem: 'INVESTMENT_PLATFORM',
    sourceTable: 'TAX_LOTS',
    loadType: 'BATCH',
    grain: 'One row per tax lot',
    primaryKey: ['tax_lot_id', 'source_system'],
    schema: {
      tax_lot_id: "BIGINT PRIMARY KEY",
      source_system: "STRING PRIMARY KEY",
      load_timestamp: "TIMESTAMP",
      account_id: "BIGINT",
      customer_id: "BIGINT",
      security_id: "BIGINT",
      symbol: "STRING",
      acquisition_date: "DATE",
      quantity: "DECIMAL(18,6)",
      cost_basis: "DECIMAL(18,2)",
      cost_per_share: "DECIMAL(18,6)",
      current_market_value: "DECIMAL(18,2)",
      unrealized_gain_loss: "DECIMAL(18,2)",
      lot_method: "STRING COMMENT 'FIFO, LIFO, SPECIFIC_LOT, AVERAGE_COST'",
      is_short_term: "BOOLEAN",
      holding_period_days: "INT",
      created_date: "TIMESTAMP",
      updated_date: "TIMESTAMP",
      record_source: "STRING",
      load_date: "TIMESTAMP DEFAULT CURRENT_TIMESTAMP"
    }
  },

  // Table 17: Corporate Actions
  {
    name: 'bronze.retail_corporate_actions',
    description: 'Raw corporate action events',
    sourceSystem: 'MARKET_DATA_FEED',
    sourceTable: 'CORPORATE_ACTIONS',
    loadType: 'BATCH',
    grain: 'One row per corporate action',
    primaryKey: ['corporate_action_id', 'source_system'],
    schema: {
      corporate_action_id: "BIGINT PRIMARY KEY",
      source_system: "STRING PRIMARY KEY",
      load_timestamp: "TIMESTAMP",
      security_id: "BIGINT",
      symbol: "STRING",
      action_type: "STRING COMMENT 'SPLIT, MERGER, SPINOFF, DIVIDEND, TENDER_OFFER'",
      announcement_date: "DATE",
      ex_date: "DATE",
      record_date: "DATE",
      effective_date: "DATE",
      action_details: "STRING",
      split_ratio: "STRING",
      new_security_id: "BIGINT",
      exchange_ratio: "DECIMAL(18,6)",
      cash_amount: "DECIMAL(18,2)",
      created_date: "TIMESTAMP",
      record_source: "STRING",
      load_date: "TIMESTAMP DEFAULT CURRENT_TIMESTAMP"
    }
  },

  // Table 18: Investment Fees
  {
    name: 'bronze.retail_investment_fees',
    description: 'Raw investment fee data',
    sourceSystem: 'INVESTMENT_PLATFORM',
    sourceTable: 'FEES',
    loadType: 'BATCH',
    grain: 'One row per fee charge',
    primaryKey: ['fee_id', 'source_system'],
    schema: {
      fee_id: "BIGINT PRIMARY KEY",
      source_system: "STRING PRIMARY KEY",
      load_timestamp: "TIMESTAMP",
      account_id: "BIGINT",
      customer_id: "BIGINT",
      fee_date: "DATE",
      fee_type: "STRING COMMENT 'MANAGEMENT, ADVISORY, TRADING, ACCOUNT_MAINTENANCE'",
      fee_category: "STRING COMMENT 'TRANSACTION, PERIODIC, ONE_TIME'",
      fee_amount: "DECIMAL(18,2)",
      fee_rate: "DECIMAL(5,4)",
      basis_amount: "DECIMAL(18,2) COMMENT 'Amount fee is calculated on'",
      currency_code: "STRING",
      trade_id: "BIGINT",
      waived_flag: "BOOLEAN",
      waiver_reason: "STRING",
      created_date: "TIMESTAMP",
      record_source: "STRING",
      load_date: "TIMESTAMP DEFAULT CURRENT_TIMESTAMP"
    }
  },

  // Table 19: Margin Activity
  {
    name: 'bronze.retail_margin_activity',
    description: 'Raw margin account activity',
    sourceSystem: 'INVESTMENT_PLATFORM',
    sourceTable: 'MARGIN',
    loadType: 'BATCH',
    grain: 'One row per margin event',
    primaryKey: ['margin_activity_id', 'source_system'],
    schema: {
      margin_activity_id: "BIGINT PRIMARY KEY",
      source_system: "STRING PRIMARY KEY",
      load_timestamp: "TIMESTAMP",
      account_id: "BIGINT",
      customer_id: "BIGINT",
      activity_date: "DATE",
      activity_type: "STRING COMMENT 'MARGIN_CALL, MARGIN_LOAN, MARGIN_PAYMENT, INTEREST_CHARGE'",
      amount: "DECIMAL(18,2)",
      margin_balance: "DECIMAL(18,2)",
      margin_equity: "DECIMAL(18,2)",
      margin_requirement: "DECIMAL(18,2)",
      excess_liquidity: "DECIMAL(18,2)",
      buying_power: "DECIMAL(18,2)",
      interest_rate: "DECIMAL(5,4)",
      margin_call_flag: "BOOLEAN",
      due_date: "DATE",
      created_date: "TIMESTAMP",
      record_source: "STRING",
      load_date: "TIMESTAMP DEFAULT CURRENT_TIMESTAMP"
    }
  },

  // Table 20: Investment Research
  {
    name: 'bronze.retail_investment_research',
    description: 'Raw investment research access logs',
    sourceSystem: 'INVESTMENT_PLATFORM',
    sourceTable: 'RESEARCH_ACCESS',
    loadType: 'STREAMING',
    grain: 'One row per research access event',
    primaryKey: ['research_access_id', 'source_system'],
    schema: {
      research_access_id: "BIGINT PRIMARY KEY",
      source_system: "STRING PRIMARY KEY",
      load_timestamp: "TIMESTAMP",
      customer_id: "BIGINT",
      access_timestamp: "TIMESTAMP",
      research_type: "STRING COMMENT 'ANALYST_REPORT, MARKET_NEWS, EARNINGS, RATING'",
      security_id: "BIGINT",
      symbol: "STRING",
      report_id: "BIGINT",
      report_title: "STRING",
      report_date: "DATE",
      provider: "STRING",
      channel: "STRING COMMENT 'WEB, MOBILE, EMAIL'",
      view_duration_seconds: "INT",
      download_flag: "BOOLEAN",
      created_date: "TIMESTAMP",
      record_source: "STRING",
      load_date: "TIMESTAMP DEFAULT CURRENT_TIMESTAMP"
    }
  }
];

export const investmentRetailBronzeLayerComplete = {
  description: 'Bronze layer for retail investment domain - raw data from source systems',
  layer: 'BRONZE',
  tables: investmentRetailBronzeTables,
  totalTables: investmentRetailBronzeTables.length
};

export default investmentRetailBronzeLayerComplete;
