/**
 * INVESTMENT-RETAIL ERD DEFINITIONS
 * 
 * Logical and Physical ERD definitions for retail investment and brokerage
 * Sources: Brokerage platforms, Portfolio management systems, Trading platforms
 */

// LOGICAL ERD
export const investmentRetailLogicalERD = {
  entities: [
    {
      name: 'Investment Account',
      type: 'core',
      description: 'Investment and brokerage accounts',
      attributes: [
        { name: 'investment_account_id', type: 'BIGINT', isPrimaryKey: true },
        { name: 'customer_id', type: 'BIGINT', isForeignKey: true },
        { name: 'account_number', type: 'STRING' },
        { name: 'account_type', type: 'STRING', description: 'IRA|401k|Brokerage|529|Robo-Advisory' },
        { name: 'account_status', type: 'STRING', description: 'Active|Closed|Frozen' },
        { name: 'open_date', type: 'DATE' },
        { name: 'current_value', type: 'DECIMAL(18,2)' },
        { name: 'cash_balance', type: 'DECIMAL(18,2)' },
        { name: 'invested_balance', type: 'DECIMAL(18,2)' },
        { name: 'ytd_gain_loss', type: 'DECIMAL(18,2)' },
        { name: 'ytd_return_pct', type: 'DECIMAL(10,4)' },
      ],
    },
    {
      name: 'Portfolio Holding',
      type: 'core',
      description: 'Individual securities held in portfolios',
      attributes: [
        { name: 'holding_id', type: 'BIGINT', isPrimaryKey: true },
        { name: 'investment_account_id', type: 'BIGINT', isForeignKey: true },
        { name: 'security_id', type: 'STRING', description: 'Ticker or CUSIP' },
        { name: 'security_type', type: 'STRING', description: 'Stock|Bond|ETF|Mutual Fund|Option' },
        { name: 'quantity', type: 'DECIMAL(18,6)' },
        { name: 'average_cost', type: 'DECIMAL(18,6)' },
        { name: 'current_price', type: 'DECIMAL(18,6)' },
        { name: 'market_value', type: 'DECIMAL(18,2)' },
        { name: 'unrealized_gain_loss', type: 'DECIMAL(18,2)' },
      ],
    },
    {
      name: 'Trade',
      type: 'event',
      description: 'Buy/sell trade transactions',
      attributes: [
        { name: 'trade_id', type: 'BIGINT', isPrimaryKey: true },
        { name: 'investment_account_id', type: 'BIGINT', isForeignKey: true },
        { name: 'trade_date', type: 'DATE' },
        { name: 'settlement_date', type: 'DATE' },
        { name: 'trade_type', type: 'STRING', description: 'Buy|Sell|Short|Cover' },
        { name: 'security_id', type: 'STRING' },
        { name: 'quantity', type: 'DECIMAL(18,6)' },
        { name: 'price', type: 'DECIMAL(18,6)' },
        { name: 'total_amount', type: 'DECIMAL(18,2)' },
        { name: 'commission', type: 'DECIMAL(18,2)' },
        { name: 'trade_status', type: 'STRING', description: 'Executed|Pending|Cancelled' },
      ],
    },
    {
      name: 'Dividend',
      type: 'event',
      description: 'Dividend and interest payments',
      attributes: [
        { name: 'dividend_id', type: 'BIGINT', isPrimaryKey: true },
        { name: 'investment_account_id', type: 'BIGINT', isForeignKey: true },
        { name: 'security_id', type: 'STRING' },
        { name: 'payment_date', type: 'DATE' },
        { name: 'dividend_amount', type: 'DECIMAL(18,2)' },
        { name: 'dividend_type', type: 'STRING', description: 'Qualified|Non-Qualified|Interest' },
      ],
    },
    {
      name: 'Advisory Service',
      type: 'core',
      description: 'Robo-advisory and managed account services',
      attributes: [
        { name: 'advisory_id', type: 'BIGINT', isPrimaryKey: true },
        { name: 'investment_account_id', type: 'BIGINT', isForeignKey: true },
        { name: 'service_type', type: 'STRING', description: 'Robo-Advisory|Managed|Hybrid' },
        { name: 'risk_profile', type: 'STRING', description: 'Conservative|Moderate|Aggressive' },
        { name: 'target_allocation', type: 'JSON' },
        { name: 'advisory_fee_pct', type: 'DECIMAL(5,4)' },
        { name: 'last_rebalance_date', type: 'DATE' },
      ],
    },
  ],
  
  relationships: [
    {
      from: 'Portfolio Holding',
      to: 'Investment Account',
      type: 'many-to-one',
      cardinality: 'N:1',
      foreignKey: 'investment_account_id',
      description: 'Holdings in account',
    },
    {
      from: 'Trade',
      to: 'Investment Account',
      type: 'many-to-one',
      cardinality: 'N:1',
      foreignKey: 'investment_account_id',
      description: 'Trades for account',
    },
    {
      from: 'Dividend',
      to: 'Investment Account',
      type: 'many-to-one',
      cardinality: 'N:1',
      foreignKey: 'investment_account_id',
      description: 'Dividends for account',
    },
    {
      from: 'Advisory Service',
      to: 'Investment Account',
      type: 'one-to-one',
      cardinality: '1:1',
      foreignKey: 'investment_account_id',
      description: 'Advisory for account',
    },
  ],
};

// PHYSICAL ERD
export const investmentRetailPhysicalERD = {
  tables: [
    {
      name: 'bronze.retail_investment_accounts',
      description: 'Investment account data',
      source: 'Brokerage Platform',
      updateFrequency: 'Daily',
      recordCount: '~2M accounts',
      attributes: [
        { name: 'investment_account_id', type: 'BIGINT', isPrimaryKey: true },
        { name: 'customer_id', type: 'BIGINT' },
        { name: 'account_number', type: 'VARCHAR(50)' },
        { name: 'account_type', type: 'VARCHAR(50)' },
        { name: 'account_status', type: 'VARCHAR(50)' },
        { name: 'open_date', type: 'DATE' },
        { name: 'current_value', type: 'DECIMAL(18,2)' },
        { name: 'cash_balance', type: 'DECIMAL(18,2)' },
        { name: 'invested_balance', type: 'DECIMAL(18,2)' },
        { name: 'ytd_gain_loss', type: 'DECIMAL(18,2)' },
        { name: 'ytd_return_pct', type: 'DECIMAL(10,4)' },
        { name: 'created_timestamp', type: 'TIMESTAMP' },
        { name: 'source_system', type: 'VARCHAR(50)' },
      ],
    },
    {
      name: 'bronze.retail_portfolio_holdings',
      description: 'Portfolio position data',
      source: 'Portfolio System',
      updateFrequency: 'Daily',
      recordCount: '~10M holdings',
      attributes: [
        { name: 'holding_id', type: 'BIGINT', isPrimaryKey: true },
        { name: 'investment_account_id', type: 'BIGINT' },
        { name: 'security_id', type: 'VARCHAR(50)' },
        { name: 'security_type', type: 'VARCHAR(50)' },
        { name: 'quantity', type: 'DECIMAL(18,6)' },
        { name: 'average_cost', type: 'DECIMAL(18,6)' },
        { name: 'current_price', type: 'DECIMAL(18,6)' },
        { name: 'market_value', type: 'DECIMAL(18,2)' },
        { name: 'unrealized_gain_loss', type: 'DECIMAL(18,2)' },
        { name: 'created_timestamp', type: 'TIMESTAMP' },
        { name: 'source_system', type: 'VARCHAR(50)' },
      ],
    },
    {
      name: 'bronze.retail_trades',
      description: 'Trade execution data',
      source: 'Trading Platform',
      updateFrequency: 'Real-time',
      recordCount: '~50M trades/year',
      attributes: [
        { name: 'trade_id', type: 'BIGINT', isPrimaryKey: true },
        { name: 'investment_account_id', type: 'BIGINT' },
        { name: 'trade_date', type: 'DATE' },
        { name: 'settlement_date', type: 'DATE' },
        { name: 'trade_type', type: 'VARCHAR(50)' },
        { name: 'security_id', type: 'VARCHAR(50)' },
        { name: 'quantity', type: 'DECIMAL(18,6)' },
        { name: 'price', type: 'DECIMAL(18,6)' },
        { name: 'total_amount', type: 'DECIMAL(18,2)' },
        { name: 'commission', type: 'DECIMAL(18,2)' },
        { name: 'trade_status', type: 'VARCHAR(50)' },
        { name: 'created_timestamp', type: 'TIMESTAMP' },
        { name: 'source_system', type: 'VARCHAR(50)' },
      ],
    },
    {
      name: 'bronze.retail_dividends',
      description: 'Dividend and interest payments',
      source: 'Brokerage Platform',
      updateFrequency: 'Daily',
      recordCount: '~5M payments/year',
      attributes: [
        { name: 'dividend_id', type: 'BIGINT', isPrimaryKey: true },
        { name: 'investment_account_id', type: 'BIGINT' },
        { name: 'security_id', type: 'VARCHAR(50)' },
        { name: 'payment_date', type: 'DATE' },
        { name: 'dividend_amount', type: 'DECIMAL(18,2)' },
        { name: 'dividend_type', type: 'VARCHAR(50)' },
        { name: 'created_timestamp', type: 'TIMESTAMP' },
        { name: 'source_system', type: 'VARCHAR(50)' },
      ],
    },
    {
      name: 'bronze.retail_advisory_services',
      description: 'Managed account and advisory data',
      source: 'Advisory Platform',
      updateFrequency: 'Daily',
      recordCount: '~500K accounts',
      attributes: [
        { name: 'advisory_id', type: 'BIGINT', isPrimaryKey: true },
        { name: 'investment_account_id', type: 'BIGINT' },
        { name: 'service_type', type: 'VARCHAR(50)' },
        { name: 'risk_profile', type: 'VARCHAR(50)' },
        { name: 'target_allocation', type: 'JSON' },
        { name: 'advisory_fee_pct', type: 'DECIMAL(5,4)' },
        { name: 'last_rebalance_date', type: 'DATE' },
        { name: 'created_timestamp', type: 'TIMESTAMP' },
        { name: 'source_system', type: 'VARCHAR(50)' },
      ],
    },
  ],
  
  relationships: [
    {
      from: 'bronze.retail_portfolio_holdings',
      to: 'bronze.retail_investment_accounts',
      type: 'many-to-one',
      cardinality: 'N:1',
      foreignKey: 'investment_account_id',
      description: 'Holdings in accounts',
    },
    {
      from: 'bronze.retail_trades',
      to: 'bronze.retail_investment_accounts',
      type: 'many-to-one',
      cardinality: 'N:1',
      foreignKey: 'investment_account_id',
      description: 'Trades for accounts',
    },
    {
      from: 'bronze.retail_dividends',
      to: 'bronze.retail_investment_accounts',
      type: 'many-to-one',
      cardinality: 'N:1',
      foreignKey: 'investment_account_id',
      description: 'Dividends for accounts',
    },
  ],
};

export default {
  investmentRetailLogicalERD,
  investmentRetailPhysicalERD,
};
