/**
 * LOANS-RETAIL METRICS CATALOG
 * 100 comprehensive metrics across 5 categories
 */

export const loansRetailMetricsCatalog = {
  description: 'Comprehensive retail loans metrics catalog',
  totalMetrics: 100,
  
  categories: [
    // Category 1: Volume & Origination Metrics (20 metrics)
    {
      name: 'Volume & Origination Metrics',
      description: 'Loan counts, balances, and origination activity',
      totalMetrics: 20,
      
      metrics: [
        {
          id: 'LOAN-VOL-001',
          name: 'Total Outstanding Loans',
          description: 'Total number of active loans',
          category: 'Volume',
          type: 'operational',
          subcategory: 'Loan Count',
          formula: "COUNT(DISTINCT loan_id WHERE loan_status = 'Active')",
          dataType: 'INTEGER',
          unit: 'count',
          aggregation: 'SUM',
          granularity: 'Daily',
          benchmarks: {
            industryAverage: '250,000 loans',
            topQuartile: '500,000 loans',
            target: '375,000 loans',
          },
        },
        {
          id: 'LOAN-VOL-002',
          name: 'Total Outstanding Balance',
          description: 'Total principal balance of all active loans',
          category: 'Volume',
          type: 'operational',
          subcategory: 'Balances',
          formula: "SUM(principal_balance WHERE loan_status = 'Active')",
          dataType: 'DECIMAL',
          unit: 'USD',
          aggregation: 'SUM',
          granularity: 'Daily',
          benchmarks: {
            industryAverage: '$3B',
            topQuartile: '$8B',
            target: '$5B',
          },
        },
        {
          id: 'LOAN-VOL-003',
          name: 'New Loan Originations',
          description: 'Number of new loans originated in period',
          category: 'Volume',
          type: 'operational',
          subcategory: 'Originations',
        },
        {
          id: 'LOAN-VOL-004',
          name: 'Origination Volume ($)',
          description: 'Dollar volume of new loans originated',
          category: 'Volume',
          type: 'operational',
          subcategory: 'Originations',
        },
        {
          id: 'LOAN-VOL-005',
          name: 'Average Loan Size',
          description: 'Mean principal amount per loan',
          category: 'Volume',
          type: 'operational',
          subcategory: 'Size',
        },
        {
          id: 'LOAN-VOL-006',
          name: 'Auto Loan Count',
          description: 'Number of active auto loans',
          category: 'Volume',
          type: 'operational',
          subcategory: 'Product Type',
        },
        {
          id: 'LOAN-VOL-007',
          name: 'Personal Loan Count',
          description: 'Number of active personal loans',
          category: 'Volume',
          type: 'operational',
          subcategory: 'Product Type',
        },
        {
          id: 'LOAN-VOL-008',
          name: 'Student Loan Count',
          description: 'Number of active student loans',
          category: 'Volume',
          type: 'operational',
          subcategory: 'Product Type',
        },
        {
          id: 'LOAN-VOL-009',
          name: 'Home Equity Line Count',
          description: 'Number of active HELOCs',
          category: 'Volume',
          type: 'operational',
          subcategory: 'Product Type',
        },
        {
          id: 'LOAN-VOL-010',
          name: 'Other Consumer Loan Count',
          description: 'Number of other consumer loans',
          category: 'Volume',
          type: 'operational',
          subcategory: 'Product Type',
        },
        {
          id: 'LOAN-VOL-011',
          name: 'Auto Loan Balances',
          description: 'Total balances in auto loans',
          category: 'Volume',
          type: 'operational',
          subcategory: 'Product Balances',
        },
        {
          id: 'LOAN-VOL-012',
          name: 'Personal Loan Balances',
          description: 'Total balances in personal loans',
          category: 'Volume',
          type: 'operational',
          subcategory: 'Product Balances',
        },
        {
          id: 'LOAN-VOL-013',
          name: 'Student Loan Balances',
          description: 'Total balances in student loans',
          category: 'Volume',
          type: 'operational',
          subcategory: 'Product Balances',
        },
        {
          id: 'LOAN-VOL-014',
          name: 'HELOC Balances',
          description: 'Total balances in HELOCs',
          category: 'Volume',
          type: 'operational',
          subcategory: 'Product Balances',
        },
        {
          id: 'LOAN-VOL-015',
          name: 'Secured Loan Percentage',
          description: 'Percentage of loans that are secured',
          category: 'Volume',
          type: 'operational',
          subcategory: 'Collateral',
        },
        {
          id: 'LOAN-VOL-016',
          name: 'Unsecured Loan Percentage',
          description: 'Percentage of loans that are unsecured',
          category: 'Volume',
          type: 'operational',
          subcategory: 'Collateral',
        },
        {
          id: 'LOAN-VOL-017',
          name: 'Loan Growth Rate',
          description: 'Year-over-year loan portfolio growth',
          category: 'Volume',
          type: 'operational',
          subcategory: 'Growth',
        },
        {
          id: 'LOAN-VOL-018',
          name: 'Direct vs Indirect Origination Mix',
          description: 'Percentage of direct vs dealer-originated loans',
          category: 'Volume',
          type: 'operational',
          subcategory: 'Channel',
        },
        {
          id: 'LOAN-VOL-019',
          name: 'Average Remaining Term',
          description: 'Mean months remaining on active loans',
          category: 'Volume',
          type: 'operational',
          subcategory: 'Term',
        },
        {
          id: 'LOAN-VOL-020',
          name: 'Loan Concentration Risk',
          description: 'Percentage of balances from top 10 borrowers',
          category: 'Volume',
          type: 'operational',
          subcategory: 'Risk',
        },
      ],
    },

    // Category 2: Credit Quality & Risk Metrics (20 metrics)
    {
      name: 'Credit Quality & Risk Metrics',
      description: 'Delinquency, charge-offs, and credit performance',
      totalMetrics: 20,
      
      metrics: [
        {
          id: 'LOAN-QUAL-001',
          name: 'Delinquency Rate (30+ DPD)',
          description: 'Percentage of loans 30+ days past due',
          category: 'Credit Quality',
          type: 'diagnostic',
          subcategory: 'Delinquency',
          formula: "(COUNT(loans WHERE days_past_due >= 30) / COUNT(active_loans)) * 100",
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'AVG',
          granularity: 'Monthly',
          benchmarks: {
            industryAverage: '3.5%',
            topQuartile: '2.0%',
            target: '2.5%',
          },
        },
        {
          id: 'LOAN-QUAL-002',
          name: 'Delinquency Rate (60+ DPD)',
          description: 'Percentage of loans 60+ days past due',
          category: 'Credit Quality',
          type: 'diagnostic',
          subcategory: 'Delinquency',
        },
        {
          id: 'LOAN-QUAL-003',
          name: 'Delinquency Rate (90+ DPD)',
          description: 'Percentage of loans 90+ days past due',
          category: 'Credit Quality',
          type: 'diagnostic',
          subcategory: 'Delinquency',
        },
        {
          id: 'LOAN-QUAL-004',
          name: 'Net Charge-Off Rate',
          description: 'Net charge-offs as percentage of average loans',
          category: 'Credit Quality',
          type: 'diagnostic',
          subcategory: 'Charge-offs',
          formula: "((Charge-offs - Recoveries) / Average Outstanding Loans) * 100",
          benchmarks: {
            industryAverage: '1.2%',
            topQuartile: '0.8%',
            target: '1.0%',
          },
        },
        {
          id: 'LOAN-QUAL-005',
          name: 'Gross Charge-Off Rate',
          description: 'Gross charge-offs as percentage of loans',
          category: 'Credit Quality',
          type: 'diagnostic',
          subcategory: 'Charge-offs',
        },
        {
          id: 'LOAN-QUAL-006',
          name: 'Recovery Rate',
          description: 'Percentage of charged-off amounts recovered',
          category: 'Credit Quality',
          type: 'diagnostic',
          subcategory: 'Recoveries',
        },
        {
          id: 'LOAN-QUAL-007',
          name: 'Non-Performing Loan Rate',
          description: 'Percentage of loans in non-performing status',
          category: 'Credit Quality',
          type: 'diagnostic',
          subcategory: 'NPL',
        },
        {
          id: 'LOAN-QUAL-008',
          name: 'Loss Given Default (LGD)',
          description: 'Average loss per defaulted loan',
          category: 'Credit Quality',
          type: 'risk',
          subcategory: 'Loss Severity',
        },
        {
          id: 'LOAN-QUAL-009',
          name: 'Probability of Default (PD)',
          description: 'Estimated probability of loan default',
          category: 'Credit Quality',
          type: 'risk',
          subcategory: 'Default Risk',
        },
        {
          id: 'LOAN-QUAL-010',
          name: 'Cure Rate',
          description: 'Percentage of delinquent loans that become current',
          category: 'Credit Quality',
          type: 'diagnostic',
          subcategory: 'Recovery',
        },
        {
          id: 'LOAN-QUAL-011',
          name: 'Roll Rate (30 to 60 DPD)',
          description: 'Percentage of 30 DPD loans rolling to 60 DPD',
          category: 'Credit Quality',
          type: 'diagnostic',
          subcategory: 'Roll Rates',
        },
        {
          id: 'LOAN-QUAL-012',
          name: 'Roll Rate (60 to 90 DPD)',
          description: 'Percentage of 60 DPD loans rolling to 90 DPD',
          category: 'Credit Quality',
          type: 'diagnostic',
          subcategory: 'Roll Rates',
        },
        {
          id: 'LOAN-QUAL-013',
          name: 'Allowance for Loan Losses',
          description: 'Total reserves for expected credit losses',
          category: 'Credit Quality',
          type: 'risk',
          subcategory: 'Reserves',
        },
        {
          id: 'LOAN-QUAL-014',
          name: 'Allowance Coverage Ratio',
          description: 'Allowance as percentage of non-performing loans',
          category: 'Credit Quality',
          type: 'diagnostic',
          subcategory: 'Coverage',
        },
        {
          id: 'LOAN-QUAL-015',
          name: 'Criticized Asset Rate',
          description: 'Percentage of loans rated substandard or worse',
          category: 'Credit Quality',
          type: 'diagnostic',
          subcategory: 'Asset Quality',
        },
        {
          id: 'LOAN-QUAL-016',
          name: 'Loan to Value Ratio',
          description: 'Average LTV across secured loans',
          category: 'Credit Quality',
          type: 'diagnostic',
          subcategory: 'Collateral',
        },
        {
          id: 'LOAN-QUAL-017',
          name: 'Debt to Income Ratio',
          description: 'Average DTI across loan portfolio',
          category: 'Credit Quality',
          type: 'diagnostic',
          subcategory: 'Borrower Capacity',
        },
        {
          id: 'LOAN-QUAL-018',
          name: 'Average FICO Score',
          description: 'Mean FICO score of active borrowers',
          category: 'Credit Quality',
          type: 'diagnostic',
          subcategory: 'Credit Score',
        },
        {
          id: 'LOAN-QUAL-019',
          name: 'Subprime Loan Percentage',
          description: 'Percentage of loans to subprime borrowers',
          category: 'Credit Quality',
          type: 'diagnostic',
          subcategory: 'Risk Segmentation',
        },
        {
          id: 'LOAN-QUAL-020',
          name: 'Early Payment Default Rate',
          description: 'Percentage of new loans defaulting within 90 days',
          category: 'Credit Quality',
          type: 'risk',
          subcategory: 'Early Default',
        },
      ],
    },

    // Category 3: Profitability & Revenue Metrics (20 metrics)
    {
      name: 'Profitability & Revenue Metrics',
      description: 'Interest income, fees, and loan profitability',
      totalMetrics: 20,
      
      metrics: [
        {
          id: 'LOAN-PROF-001',
          name: 'Total Interest Income',
          description: 'Total interest earned on loans',
          category: 'Profitability',
          type: 'financial',
          subcategory: 'Interest',
          formula: "SUM(interest_paid_amount)",
          dataType: 'DECIMAL',
          unit: 'USD',
          aggregation: 'SUM',
          granularity: 'Monthly',
        },
        {
          id: 'LOAN-PROF-002',
          name: 'Weighted Average Interest Rate',
          description: 'Portfolio-weighted average APR',
          category: 'Profitability',
          type: 'financial',
          subcategory: 'Rate',
        },
        {
          id: 'LOAN-PROF-003',
          name: 'Net Interest Margin',
          description: 'Interest income minus cost of funds',
          category: 'Profitability',
          type: 'financial',
          subcategory: 'Margin',
        },
        {
          id: 'LOAN-PROF-004',
          name: 'Loan Origination Fee Revenue',
          description: 'Total revenue from origination fees',
          category: 'Profitability',
          type: 'financial',
          subcategory: 'Fees',
        },
        {
          id: 'LOAN-PROF-005',
          name: 'Late Payment Fee Revenue',
          description: 'Total revenue from late fees',
          category: 'Profitability',
          type: 'financial',
          subcategory: 'Fees',
        },
        {
          id: 'LOAN-PROF-006',
          name: 'Prepayment Penalty Revenue',
          description: 'Total revenue from early payoff penalties',
          category: 'Profitability',
          type: 'financial',
          subcategory: 'Fees',
        },
        {
          id: 'LOAN-PROF-007',
          name: 'Revenue per Loan',
          description: 'Average revenue generated per loan',
          category: 'Profitability',
          type: 'financial',
          subcategory: 'Unit Economics',
        },
        {
          id: 'LOAN-PROF-008',
          name: 'Loan ROA',
          description: 'Return on assets for loan portfolio',
          category: 'Profitability',
          type: 'financial',
          subcategory: 'Returns',
        },
        {
          id: 'LOAN-PROF-009',
          name: 'Loan ROE',
          description: 'Return on equity for loan portfolio',
          category: 'Profitability',
          type: 'financial',
          subcategory: 'Returns',
        },
        {
          id: 'LOAN-PROF-010',
          name: 'Servicing Fee Income',
          description: 'Revenue from servicing loans sold',
          category: 'Profitability',
          type: 'financial',
          subcategory: 'Servicing',
        },
        {
          id: 'LOAN-PROF-011',
          name: 'Gain on Sale Revenue',
          description: 'Revenue from selling loans to secondary market',
          category: 'Profitability',
          type: 'financial',
          subcategory: 'Secondary Market',
        },
        {
          id: 'LOAN-PROF-012',
          name: 'Cost per Loan',
          description: 'Average cost to originate and service each loan',
          category: 'Profitability',
          type: 'financial',
          subcategory: 'Costs',
        },
        {
          id: 'LOAN-PROF-013',
          name: 'Profit per Loan',
          description: 'Average profit margin per loan',
          category: 'Profitability',
          type: 'financial',
          subcategory: 'Profitability',
        },
        {
          id: 'LOAN-PROF-014',
          name: 'Profitable Loan Rate',
          description: 'Percentage of loans generating positive profit',
          category: 'Profitability',
          type: 'financial',
          subcategory: 'Mix',
        },
        {
          id: 'LOAN-PROF-015',
          name: 'Interest Rate Spread',
          description: 'Loan rate minus funding cost',
          category: 'Profitability',
          type: 'financial',
          subcategory: 'Spread',
        },
        {
          id: 'LOAN-PROF-016',
          name: 'Yield on Loans',
          description: 'Total return on loan portfolio',
          category: 'Profitability',
          type: 'financial',
          subcategory: 'Yield',
        },
        {
          id: 'LOAN-PROF-017',
          name: 'Cross-Sell Revenue from Borrowers',
          description: 'Revenue from other products sold to loan customers',
          category: 'Profitability',
          type: 'financial',
          subcategory: 'Cross-Sell',
        },
        {
          id: 'LOAN-PROF-018',
          name: 'Loan Insurance Premium Revenue',
          description: 'Revenue from credit insurance products',
          category: 'Profitability',
          type: 'financial',
          subcategory: 'Insurance',
        },
        {
          id: 'LOAN-PROF-019',
          name: 'Overdraft Protection Revenue',
          description: 'Revenue from overdraft protection on loans',
          category: 'Profitability',
          type: 'financial',
          subcategory: 'Protection',
        },
        {
          id: 'LOAN-PROF-020',
          name: 'Total Loan Portfolio Value',
          description: 'Mark-to-market value of loan portfolio',
          category: 'Profitability',
          type: 'financial',
          subcategory: 'Valuation',
        },
      ],
    },

    // Category 4: Origination & Underwriting Performance (20 metrics)
    {
      name: 'Origination & Underwriting Performance',
      description: 'Application volume, approval rates, pull-through',
      totalMetrics: 20,
      
      metrics: [
        {
          id: 'LOAN-ORIG-001',
          name: 'Application Volume',
          description: 'Number of loan applications received',
          category: 'Origination',
          type: 'operational',
          subcategory: 'Volume',
          formula: "COUNT(DISTINCT application_id)",
          dataType: 'INTEGER',
          unit: 'count',
          aggregation: 'SUM',
          granularity: 'Monthly',
        },
        {
          id: 'LOAN-ORIG-002',
          name: 'Approval Rate',
          description: 'Percentage of applications approved',
          category: 'Origination',
          type: 'operational',
          subcategory: 'Conversion',
          formula: "(COUNT(approved_applications) / COUNT(total_applications)) * 100",
          benchmarks: {
            industryAverage: '65%',
            topQuartile: '75%',
            target: '70%',
          },
        },
        {
          id: 'LOAN-ORIG-003',
          name: 'Denial Rate',
          description: 'Percentage of applications denied',
          category: 'Origination',
          type: 'operational',
          subcategory: 'Conversion',
        },
        {
          id: 'LOAN-ORIG-004',
          name: 'Pull-Through Rate',
          description: 'Percentage of approvals that fund',
          category: 'Origination',
          type: 'operational',
          subcategory: 'Conversion',
        },
        {
          id: 'LOAN-ORIG-005',
          name: 'Application Abandonment Rate',
          description: 'Percentage of started applications not completed',
          category: 'Origination',
          type: 'operational',
          subcategory: 'Funnel',
        },
        {
          id: 'LOAN-ORIG-006',
          name: 'Average Time to Decision',
          description: 'Mean hours from application to decision',
          category: 'Origination',
          type: 'operational',
          subcategory: 'Cycle Time',
        },
        {
          id: 'LOAN-ORIG-007',
          name: 'Average Time to Funding',
          description: 'Mean days from approval to funding',
          category: 'Origination',
          type: 'operational',
          subcategory: 'Cycle Time',
        },
        {
          id: 'LOAN-ORIG-008',
          name: 'Same-Day Decision Rate',
          description: 'Percentage of applications decided same day',
          category: 'Origination',
          type: 'operational',
          subcategory: 'Speed',
        },
        {
          id: 'LOAN-ORIG-009',
          name: 'Automated Underwriting Rate',
          description: 'Percentage of loans underwritten automatically',
          category: 'Origination',
          type: 'operational',
          subcategory: 'Automation',
        },
        {
          id: 'LOAN-ORIG-010',
          name: 'Digital Application Rate',
          description: 'Percentage of applications via digital channels',
          category: 'Origination',
          type: 'operational',
          subcategory: 'Channel',
        },
        {
          id: 'LOAN-ORIG-011',
          name: 'Branch Application Rate',
          description: 'Percentage of applications at branches',
          category: 'Origination',
          type: 'operational',
          subcategory: 'Channel',
        },
        {
          id: 'LOAN-ORIG-012',
          name: 'Dealer/Partner Application Rate',
          description: 'Percentage of applications from dealers/partners',
          category: 'Origination',
          type: 'operational',
          subcategory: 'Channel',
        },
        {
          id: 'LOAN-ORIG-013',
          name: 'Pre-Qualification Rate',
          description: 'Percentage of applicants who pre-qualified',
          category: 'Origination',
          type: 'operational',
          subcategory: 'Pre-Qual',
        },
        {
          id: 'LOAN-ORIG-014',
          name: 'Credit Score at Origination',
          description: 'Average FICO score of approved loans',
          category: 'Origination',
          type: 'operational',
          subcategory: 'Credit Quality',
        },
        {
          id: 'LOAN-ORIG-015',
          name: 'LTV at Origination',
          description: 'Average loan-to-value at origination',
          category: 'Origination',
          type: 'operational',
          subcategory: 'Risk Metrics',
        },
        {
          id: 'LOAN-ORIG-016',
          name: 'DTI at Origination',
          description: 'Average debt-to-income at origination',
          category: 'Origination',
          type: 'operational',
          subcategory: 'Risk Metrics',
        },
        {
          id: 'LOAN-ORIG-017',
          name: 'Exception Approval Rate',
          description: 'Percentage of approvals requiring exceptions',
          category: 'Origination',
          type: 'operational',
          subcategory: 'Exceptions',
        },
        {
          id: 'LOAN-ORIG-018',
          name: 'Application Fraud Rate',
          description: 'Percentage of applications flagged for fraud',
          category: 'Origination',
          type: 'operational',
          subcategory: 'Fraud',
        },
        {
          id: 'LOAN-ORIG-019',
          name: 'Origination Volume by Product',
          description: 'Loan originations segmented by product type',
          category: 'Origination',
          type: 'operational',
          subcategory: 'Product Mix',
        },
        {
          id: 'LOAN-ORIG-020',
          name: 'Refinance vs New Loan Mix',
          description: 'Percentage of originations that are refinances',
          category: 'Origination',
          type: 'operational',
          subcategory: 'Purpose',
        },
      ],
    },

    // Category 5: Servicing & Operations Metrics (20 metrics)
    {
      name: 'Servicing & Operations Metrics',
      description: 'Loan servicing, payments, and operational efficiency',
      totalMetrics: 20,
      
      metrics: [
        {
          id: 'LOAN-SERV-001',
          name: 'On-Time Payment Rate',
          description: 'Percentage of payments made on or before due date',
          category: 'Servicing',
          type: 'operational',
          subcategory: 'Payments',
          formula: "(COUNT(on_time_payments) / COUNT(total_payments)) * 100",
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'AVG',
          granularity: 'Monthly',
          benchmarks: {
            industryAverage: '92%',
            topQuartile: '96%',
            target: '94%',
          },
        },
        {
          id: 'LOAN-SERV-002',
          name: 'AutoPay Enrollment Rate',
          description: 'Percentage of loans on automatic payment',
          category: 'Servicing',
          type: 'operational',
          subcategory: 'Payments',
        },
        {
          id: 'LOAN-SERV-003',
          name: 'Prepayment Rate',
          description: 'Percentage of loans prepaid early',
          category: 'Servicing',
          type: 'operational',
          subcategory: 'Prepayment',
        },
        {
          id: 'LOAN-SERV-004',
          name: 'Extra Principal Payment Rate',
          description: 'Percentage of loans with extra principal payments',
          category: 'Servicing',
          type: 'operational',
          subcategory: 'Prepayment',
        },
        {
          id: 'LOAN-SERV-005',
          name: 'Loan Modification Rate',
          description: 'Percentage of loans modified',
          category: 'Servicing',
          type: 'operational',
          subcategory: 'Modifications',
        },
        {
          id: 'LOAN-SERV-006',
          name: 'Forbearance Rate',
          description: 'Percentage of loans in forbearance',
          category: 'Servicing',
          type: 'operational',
          subcategory: 'Forbearance',
        },
        {
          id: 'LOAN-SERV-007',
          name: 'Deferment Rate',
          description: 'Percentage of loans in deferment',
          category: 'Servicing',
          type: 'operational',
          subcategory: 'Deferment',
        },
        {
          id: 'LOAN-SERV-008',
          name: 'Payment Extension Rate',
          description: 'Percentage of loans with payment extensions',
          category: 'Servicing',
          type: 'operational',
          subcategory: 'Extensions',
        },
        {
          id: 'LOAN-SERV-009',
          name: 'Statement Accuracy Rate',
          description: 'Percentage of statements without errors',
          category: 'Servicing',
          type: 'operational',
          subcategory: 'Quality',
        },
        {
          id: 'LOAN-SERV-010',
          name: 'Payment Processing Time',
          description: 'Average time to process and post payments',
          category: 'Servicing',
          type: 'operational',
          subcategory: 'Efficiency',
        },
        {
          id: 'LOAN-SERV-011',
          name: 'Customer Service Contact Rate',
          description: 'Percentage of borrowers contacting servicing',
          category: 'Servicing',
          type: 'operational',
          subcategory: 'Service',
        },
        {
          id: 'LOAN-SERV-012',
          name: 'First Contact Resolution Rate',
          description: 'Percentage of servicing issues resolved on first contact',
          category: 'Servicing',
          type: 'operational',
          subcategory: 'Service Quality',
        },
        {
          id: 'LOAN-SERV-013',
          name: 'Servicing Complaint Rate',
          description: 'Number of complaints per 1,000 loans',
          category: 'Servicing',
          type: 'operational',
          subcategory: 'Quality',
        },
        {
          id: 'LOAN-SERV-014',
          name: 'Escrow Account Management',
          description: 'Percentage of loans with escrow accounts',
          category: 'Servicing',
          type: 'operational',
          subcategory: 'Escrow',
        },
        {
          id: 'LOAN-SERV-015',
          name: 'Online Account Access Rate',
          description: 'Percentage of borrowers using online servicing',
          category: 'Servicing',
          type: 'operational',
          subcategory: 'Digital',
        },
        {
          id: 'LOAN-SERV-016',
          name: 'Mobile Servicing Adoption',
          description: 'Percentage of borrowers using mobile app',
          category: 'Servicing',
          type: 'operational',
          subcategory: 'Mobile',
        },
        {
          id: 'LOAN-SERV-017',
          name: 'Payment Reversal Rate',
          description: 'Percentage of payments reversed or returned',
          category: 'Servicing',
          type: 'operational',
          subcategory: 'Payment Issues',
        },
        {
          id: 'LOAN-SERV-018',
          name: 'Payoff Quote Request Rate',
          description: 'Number of payoff quotes requested per 1,000 loans',
          category: 'Servicing',
          type: 'operational',
          subcategory: 'Payoff',
        },
        {
          id: 'LOAN-SERV-019',
          name: 'Average Servicing Cost per Loan',
          description: 'Mean cost to service each loan',
          category: 'Servicing',
          type: 'operational',
          subcategory: 'Costs',
        },
        {
          id: 'LOAN-SERV-020',
          name: 'Loan Servicing Satisfaction Score',
          description: 'Customer satisfaction with loan servicing',
          category: 'Servicing',
          type: 'operational',
          subcategory: 'Satisfaction',
        },
      ],
    },
  ],
};

export default loansRetailMetricsCatalog;
