/**
 * MARKETING-RETAIL METRICS CATALOG
 * 
 * Complete metrics catalog with 65 fully-defined metrics across 10 categories
 * Enterprise-Grade Quality Template
 */

export const marketingRetailMetricsCatalog = {
  description: 'Comprehensive marketing performance metrics catalog',
  totalMetrics: 65,
  
  categories: [
    // Category 1: Campaign Performance Metrics (10 metrics)
    {
      name: 'Campaign Performance Metrics',
      description: 'Multi-channel campaign effectiveness, reach, and engagement tracking',
      totalMetrics: 10,
      
      metrics: [
        {
          id: 'MKT-CMP-001',
          name: 'Campaign Impressions',
          description: 'Total number of times campaign creative was displayed',
          category: 'Campaign Performance',
          type: 'diagnostic',
          subcategory: 'Reach',
          formula: "SUM(impressions)",
          businessLogic: 'Count of ad impressions served across all channels',
          dataType: 'INTEGER',
          unit: 'count',
          aggregation: 'SUM',
          granularity: 'Daily',
          sourceTables: ['gold.fact_campaign_performance', 'bronze.mktg_google_ads', 'bronze.mktg_facebook_ads'],
          calculation: { numerator: "SUM(impressions)", filters: "campaign_status = 'active'" },
          businessDefinition: 'Number of times campaign ads were displayed to users across all marketing channels',
          benchmarks: { industryAverage: '10M impressions/month', topQuartile: '25M impressions/month', target: '15M impressions/month' },
        },
        {
          id: 'MKT-CMP-002',
          name: 'Campaign Click-Through Rate (CTR)',
          description: 'Percentage of impressions that resulted in clicks',
          category: 'Campaign Performance',
          type: 'risk',
          subcategory: 'Engagement',
          formula: "(SUM(clicks) / SUM(impressions)) * 100",
          businessLogic: 'Ratio of clicks to impressions, indicating ad relevance',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Daily',
          sourceTables: ['gold.fact_campaign_performance'],
          calculation: { numerator: "SUM(clicks)", denominator: "SUM(impressions)", multiplier: 100 },
          businessDefinition: 'Percentage indicating how often people click on ads after seeing them',
          benchmarks: { industryAverage: '0.8% for financial services', topQuartile: '1.5%', target: '1.2%' },
        },
        {
          id: 'MKT-CMP-003',
          name: 'Campaign Conversion Rate',
          description: 'Percentage of campaign clicks that resulted in conversions',
          category: 'Campaign Performance',
          type: 'diagnostic',
          subcategory: 'Conversion',
          formula: "(SUM(conversions) / SUM(clicks)) * 100",
          businessLogic: 'Percentage of users who completed desired action after clicking',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Daily',
          sourceTables: ['gold.fact_campaign_performance'],
          calculation: { numerator: "SUM(conversions)", denominator: "SUM(clicks)", multiplier: 100 },
          businessDefinition: 'Conversion rate from click to completed goal (application, signup, purchase)',
          benchmarks: { industryAverage: '3.5% for banking', topQuartile: '6.0%', target: '5.0%' },
        },
        {
          id: 'MKT-CMP-004',
          name: 'Cost Per Thousand Impressions (CPM)',
          description: 'Cost to reach 1,000 impressions',
          category: 'Campaign Performance',
          type: 'financial',
          subcategory: 'Cost Efficiency',
          formula: "(SUM(spend) / SUM(impressions)) * 1000",
          businessLogic: 'Average cost to serve 1,000 ad impressions',
          dataType: 'DECIMAL',
          unit: 'currency',
          aggregation: 'CALCULATED',
          granularity: 'Daily',
          sourceTables: ['gold.fact_campaign_performance', 'silver.mktg_spend'],
          calculation: { numerator: "SUM(spend)", denominator: "SUM(impressions)", multiplier: 1000 },
          businessDefinition: 'Media buying efficiency metric - cost per thousand ad impressions',
          benchmarks: { industryAverage: '$12 CPM', topQuartile: '$8 CPM', target: '$10 CPM' },
        },
        {
          id: 'MKT-CMP-005',
          name: 'Cost Per Click (CPC)',
          description: 'Average cost for each ad click',
          category: 'Campaign Performance',
          type: 'financial',
          subcategory: 'Cost Efficiency',
          formula: "SUM(spend) / SUM(clicks)",
          businessLogic: 'Total spend divided by number of clicks',
          dataType: 'DECIMAL',
          unit: 'currency',
          aggregation: 'CALCULATED',
          granularity: 'Daily',
          sourceTables: ['gold.fact_campaign_performance'],
          calculation: { numerator: "SUM(spend)", denominator: "SUM(clicks)" },
          businessDefinition: 'Average amount paid for each click on advertising',
          benchmarks: { industryAverage: '$3.50 for banking keywords', topQuartile: '$2.50', target: '$3.00' },
        },
        {
          id: 'MKT-CMP-006',
          name: 'Cost Per Acquisition (CPA)',
          description: 'Average cost to acquire one customer/conversion',
          category: 'Campaign Performance',
          type: 'financial',
          subcategory: 'Cost Efficiency',
          formula: "SUM(spend) / SUM(conversions)",
          businessLogic: 'Total marketing spend divided by number of conversions',
          dataType: 'DECIMAL',
          unit: 'currency',
          aggregation: 'CALCULATED',
          granularity: 'Daily',
          sourceTables: ['gold.fact_campaign_performance', 'gold.fact_marketing_roi'],
          calculation: { numerator: "SUM(spend)", denominator: "SUM(conversions)" },
          businessDefinition: 'Total cost to acquire one customer through marketing efforts',
          benchmarks: { industryAverage: '$250 for retail banking customer', topQuartile: '$150', target: '$200' },
        },
        {
          id: 'MKT-CMP-007',
          name: 'Return on Ad Spend (ROAS)',
          description: 'Revenue generated per dollar of ad spend',
          category: 'Campaign Performance',
          type: 'financial',
          subcategory: 'ROI',
          formula: "SUM(attributed_revenue) / SUM(spend)",
          businessLogic: 'Revenue attributed to campaign divided by campaign spend',
          dataType: 'DECIMAL',
          unit: 'ratio',
          aggregation: 'CALCULATED',
          granularity: 'Daily',
          sourceTables: ['gold.fact_marketing_roi', 'gold.fact_attribution'],
          calculation: { numerator: "SUM(attributed_revenue)", denominator: "SUM(spend)" },
          businessDefinition: 'Return on advertising spend - how much revenue each dollar of ad spend generates',
          benchmarks: { industryAverage: '3:1 ROAS', topQuartile: '5:1 ROAS', target: '4:1 ROAS' },
        },
        {
          id: 'MKT-CMP-008',
          name: 'Campaign ROI',
          description: 'Return on investment including all campaign costs',
          category: 'Campaign Performance',
          type: 'financial',
          subcategory: 'ROI',
          formula: "((SUM(revenue) - SUM(total_cost)) / SUM(total_cost)) * 100",
          businessLogic: 'Net profit divided by total investment',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Monthly',
          sourceTables: ['gold.fact_marketing_roi'],
          calculation: { numerator: "SUM(revenue - total_cost)", denominator: "SUM(total_cost)", multiplier: 100 },
          businessDefinition: 'Overall return on marketing investment including media, creative, and overhead',
          benchmarks: { industryAverage: '150% ROI', topQuartile: '300% ROI', target: '200% ROI' },
        },
        {
          id: 'MKT-CMP-009',
          name: 'Campaign Reach',
          description: 'Unique users exposed to campaign',
          category: 'Campaign Performance',
          type: 'diagnostic',
          subcategory: 'Reach',
          formula: "COUNT(DISTINCT user_id)",
          businessLogic: 'Deduplicated user count across all touchpoints',
          dataType: 'INTEGER',
          unit: 'count',
          aggregation: 'COUNT_DISTINCT',
          granularity: 'Daily',
          sourceTables: ['gold.fact_campaign_performance'],
          calculation: { numerator: "COUNT(DISTINCT user_id)" },
          businessDefinition: 'Number of unique users reached by campaign',
          benchmarks: { industryAverage: '2M users', topQuartile: '5M users', target: '3M users' },
        },
        {
          id: 'MKT-CMP-010',
          name: 'Campaign Frequency',
          description: 'Average number of impressions per unique user',
          category: 'Campaign Performance',
          type: 'diagnostic',
          subcategory: 'Reach',
          formula: "SUM(impressions) / COUNT(DISTINCT user_id)",
          businessLogic: 'Total impressions divided by unique users',
          dataType: 'DECIMAL',
          unit: 'count',
          aggregation: 'CALCULATED',
          granularity: 'Weekly',
          sourceTables: ['gold.fact_campaign_performance'],
          calculation: { numerator: "SUM(impressions)", denominator: "COUNT(DISTINCT user_id)" },
          businessDefinition: 'How many times each user saw the campaign on average',
          benchmarks: { industryAverage: '5 times', topQuartile: '7 times', target: '6 times' },
        },
      ],
    },

    // Category 2: Email Marketing Metrics (8 metrics)
    {
      name: 'Email Marketing Metrics',
      description: 'Email campaign delivery, engagement, and conversion tracking',
      totalMetrics: 8,
      
      metrics: [
        {
          id: 'MKT-EML-001',
          name: 'Email Deliverability Rate',
          description: 'Percentage of emails successfully delivered',
          category: 'Email Marketing',
          type: 'diagnostic',
          subcategory: 'Delivery',
          formula: "(SUM(delivered) / SUM(sent)) * 100",
          businessLogic: 'Successful deliveries divided by total sends',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Daily',
          sourceTables: ['silver.mktg_email_delivery_cleansed', 'bronze.mktg_email_sends'],
          calculation: { numerator: "COUNT(WHERE delivery_status = 'delivered')", denominator: "COUNT(total_sends)", multiplier: 100 },
          businessDefinition: 'Percentage of emails that reached recipient inboxes',
          benchmarks: { industryAverage: '95%', topQuartile: '98%', target: '97%' },
        },
        {
          id: 'MKT-EML-002',
          name: 'Email Open Rate',
          description: 'Percentage of delivered emails that were opened',
          category: 'Email Marketing',
          type: 'diagnostic',
          subcategory: 'Engagement',
          formula: "(SUM(opens) / SUM(delivered)) * 100",
          businessLogic: 'Unique opens divided by emails delivered (bot-filtered)',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Daily',
          sourceTables: ['silver.mktg_email_engagement_cleansed'],
          calculation: { numerator: "COUNT(DISTINCT customer_id WHERE event_type = 'open' AND is_bot = false)", denominator: "COUNT(delivered_emails)", multiplier: 100 },
          businessDefinition: 'Percentage of delivered emails opened by recipients (bot traffic filtered)',
          benchmarks: { industryAverage: '18% for banking', topQuartile: '25%', target: '22%' },
        },
        {
          id: 'MKT-EML-003',
          name: 'Email Click-Through Rate',
          description: 'Percentage of delivered emails with link clicks',
          category: 'Email Marketing',
          type: 'diagnostic',
          subcategory: 'Engagement',
          formula: "(SUM(clicks) / SUM(delivered)) * 100",
          businessLogic: 'Unique clicks divided by emails delivered',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Daily',
          sourceTables: ['silver.mktg_email_engagement_cleansed'],
          calculation: { numerator: "COUNT(DISTINCT customer_id WHERE event_type = 'click')", denominator: "COUNT(delivered_emails)", multiplier: 100 },
          businessDefinition: 'Percentage of delivered emails that generated clicks',
          benchmarks: { industryAverage: '2.5% for banking', topQuartile: '4.5%', target: '3.5%' },
        },
        {
          id: 'MKT-EML-004',
          name: 'Email Click-to-Open Rate (CTOR)',
          description: 'Percentage of opens that resulted in clicks',
          category: 'Email Marketing',
          type: 'diagnostic',
          subcategory: 'Engagement',
          formula: "(SUM(unique_clicks) / SUM(unique_opens)) * 100",
          businessLogic: 'Clicks divided by opens',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Daily',
          sourceTables: ['silver.mktg_email_engagement_cleansed'],
          calculation: { numerator: "COUNT(DISTINCT clicked_users)", denominator: "COUNT(DISTINCT opened_users)", multiplier: 100 },
          businessDefinition: 'Effectiveness of email content in driving action',
          benchmarks: { industryAverage: '14%', topQuartile: '22%', target: '18%' },
        },
        {
          id: 'MKT-EML-005',
          name: 'Email Bounce Rate',
          description: 'Percentage of emails that bounced (hard + soft)',
          category: 'Email Marketing',
          type: 'diagnostic',
          subcategory: 'Delivery',
          formula: "(SUM(bounces) / SUM(sent)) * 100",
          businessLogic: 'Bounced emails divided by total sends',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Daily',
          sourceTables: ['silver.mktg_email_delivery_cleansed'],
          calculation: { numerator: "COUNT(WHERE delivery_status = 'bounced')", denominator: "COUNT(sent)", multiplier: 100 },
          businessDefinition: 'Percentage of emails that failed to deliver',
          benchmarks: { industryAverage: '2.5%', topQuartile: '1.0%', target: '1.5%' },
        },
        {
          id: 'MKT-EML-006',
          name: 'Email Unsubscribe Rate',
          description: 'Percentage of delivered emails resulting in unsubscribes',
          category: 'Email Marketing',
          type: 'diagnostic',
          subcategory: 'List Health',
          formula: "(SUM(unsubscribes) / SUM(delivered)) * 100",
          businessLogic: 'Unsubscribes divided by deliveries',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Daily',
          sourceTables: ['silver.mktg_email_engagement_cleansed'],
          calculation: { numerator: "COUNT(WHERE event_type = 'unsubscribe')", denominator: "COUNT(delivered)", multiplier: 100 },
          businessDefinition: 'Rate at which recipients opt out of communications',
          benchmarks: { industryAverage: '0.3%', topQuartile: '0.1%', target: '0.2%' },
        },
        {
          id: 'MKT-EML-007',
          name: 'Email Spam Complaint Rate',
          description: 'Percentage of delivered emails marked as spam',
          category: 'Email Marketing',
          type: 'diagnostic',
          subcategory: 'List Health',
          formula: "(SUM(spam_complaints) / SUM(delivered)) * 100",
          businessLogic: 'Spam complaints divided by deliveries',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Daily',
          sourceTables: ['silver.mktg_email_engagement_cleansed'],
          calculation: { numerator: "COUNT(WHERE event_type = 'spam_complaint')", denominator: "COUNT(delivered)", multiplier: 100 },
          businessDefinition: 'Rate at which emails are flagged as spam',
          benchmarks: { industryAverage: '0.1%', topQuartile: '0.01%', target: '0.05%' },
        },
        {
          id: 'MKT-EML-008',
          name: 'Email Conversion Rate',
          description: 'Percentage of email recipients who converted',
          category: 'Email Marketing',
          type: 'diagnostic',
          subcategory: 'Conversion',
          formula: "(SUM(conversions) / SUM(delivered)) * 100",
          businessLogic: 'Conversions divided by emails delivered',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Daily',
          sourceTables: ['gold.fact_marketing_engagement'],
          calculation: { numerator: "COUNT(conversions)", denominator: "COUNT(delivered)", multiplier: 100 },
          businessDefinition: 'Percentage of email recipients who completed goal',
          benchmarks: { industryAverage: '1.5%', topQuartile: '3.0%', target: '2.2%' },
        },
      ],
    },

    // Category 3: Paid Media Metrics (6 metrics)
    {
      name: 'Paid Media Metrics',
      description: 'Paid search and social advertising performance',
      totalMetrics: 6,
      
      metrics: [
        {
          id: 'MKT-PD-001',
          name: 'Paid Search Quality Score',
          description: 'Average quality score across paid search campaigns',
          category: 'Paid Media',
          type: 'diagnostic',
          subcategory: 'Quality',
          formula: "AVG(quality_score)",
          businessLogic: 'Platform quality rating (1-10) for ads',
          dataType: 'DECIMAL',
          unit: 'score',
          aggregation: 'AVG',
          granularity: 'Daily',
          sourceTables: ['bronze.mktg_google_ads'],
          calculation: { numerator: "AVG(quality_score)" },
          businessDefinition: 'Google Ads quality rating based on relevance, CTR, and landing page experience',
          benchmarks: { industryAverage: '6.0', topQuartile: '8.5', target: '7.5' },
        },
        {
          id: 'MKT-PD-002',
          name: 'Paid Search Impression Share',
          description: 'Percentage of available impressions captured',
          category: 'Paid Media',
          type: 'diagnostic',
          subcategory: 'Reach',
          formula: "(actual_impressions / eligible_impressions) * 100",
          businessLogic: 'Market share of available ad inventory',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Daily',
          sourceTables: ['bronze.mktg_google_ads'],
          calculation: { numerator: "SUM(impressions)", denominator: "SUM(eligible_impressions)", multiplier: 100 },
          businessDefinition: 'Share of voice in search auctions',
          benchmarks: { industryAverage: '45%', topQuartile: '70%', target: '60%' },
        },
        {
          id: 'MKT-PD-003',
          name: 'Paid Social Engagement Rate',
          description: 'Percentage of reached users who engaged with ads',
          category: 'Paid Media',
          type: 'behavioral',
          subcategory: 'Engagement',
          formula: "(SUM(engagements) / SUM(reach)) * 100",
          businessLogic: 'Social actions divided by unique reach',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Daily',
          sourceTables: ['bronze.mktg_facebook_ads'],
          calculation: { numerator: "SUM(likes + comments + shares)", denominator: "SUM(reach)", multiplier: 100 },
          businessDefinition: 'Social media ad engagement rate',
          benchmarks: { industryAverage: '2.0%', topQuartile: '4.0%', target: '3.0%' },
        },
        {
          id: 'MKT-PD-004',
          name: 'Paid Video Completion Rate',
          description: 'Percentage of video ads watched to completion',
          category: 'Paid Media',
          type: 'diagnostic',
          subcategory: 'Engagement',
          formula: "(SUM(video_completions) / SUM(video_starts)) * 100",
          businessLogic: 'Videos completed divided by videos started',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Daily',
          sourceTables: ['bronze.mktg_facebook_ads'],
          calculation: { numerator: "SUM(video_completions)", denominator: "SUM(video_starts)", multiplier: 100 },
          businessDefinition: 'Video creative effectiveness',
          benchmarks: { industryAverage: '35%', topQuartile: '50%', target: '45%' },
        },
        {
          id: 'MKT-PD-005',
          name: 'Cost Per Lead (CPL)',
          description: 'Average cost to generate qualified lead from paid media',
          category: 'Paid Media',
          type: 'financial',
          subcategory: 'Efficiency',
          formula: "SUM(spend) / SUM(leads)",
          businessLogic: 'Total spend divided by leads generated',
          dataType: 'DECIMAL',
          unit: 'currency',
          aggregation: 'CALCULATED',
          granularity: 'Daily',
          sourceTables: ['gold.fact_campaign_performance'],
          calculation: { numerator: "SUM(spend)", denominator: "SUM(leads)" },
          businessDefinition: 'Cost efficiency for lead generation',
          benchmarks: { industryAverage: '$85', topQuartile: '$50', target: '$65' },
        },
        {
          id: 'MKT-PD-006',
          name: 'Paid Media ROAS',
          description: 'Return on ad spend for paid channels',
          category: 'Paid Media',
          type: 'financial',
          subcategory: 'ROI',
          formula: "SUM(revenue) / SUM(spend)",
          businessLogic: 'Revenue attributed to paid media / spend',
          dataType: 'DECIMAL',
          unit: 'ratio',
          aggregation: 'CALCULATED',
          granularity: 'Monthly',
          sourceTables: ['gold.fact_marketing_roi'],
          calculation: { numerator: "SUM(attributed_revenue)", denominator: "SUM(paid_media_spend)" },
          businessDefinition: 'Revenue return per dollar of paid advertising',
          benchmarks: { industryAverage: '3.5:1', topQuartile: '6.0:1', target: '4.5:1' },
        },
      ],
    },

    // Category 4: Web Analytics Metrics (6 metrics)
    {
      name: 'Web Analytics Metrics',
      description: 'Website traffic, behavior, and conversion tracking',
      totalMetrics: 6,
      
      metrics: [
        {
          id: 'MKT-WEB-001',
          name: 'Website Traffic Volume',
          description: 'Total sessions on website',
          category: 'Web Analytics',
          type: 'operational',
          subcategory: 'Traffic',
          formula: "COUNT(sessions)",
          businessLogic: 'Total number of website sessions',
          dataType: 'INTEGER',
          unit: 'count',
          aggregation: 'COUNT',
          granularity: 'Daily',
          sourceTables: ['silver.mktg_web_sessions_cleansed'],
          calculation: { numerator: "COUNT(session_id)" },
          businessDefinition: 'Total website visits',
          benchmarks: { industryAverage: '500K sessions/month', topQuartile: '1.2M sessions/month', target: '800K sessions/month' },
        },
        {
          id: 'MKT-WEB-002',
          name: 'Website Bounce Rate',
          description: 'Percentage of single-page sessions',
          category: 'Web Analytics',
          type: 'diagnostic',
          subcategory: 'Engagement',
          formula: "(SUM(bounces) / SUM(sessions)) * 100",
          businessLogic: 'Sessions with 1 page view / total sessions',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Daily',
          sourceTables: ['silver.mktg_web_sessions_cleansed'],
          calculation: { numerator: "COUNT(WHERE is_bounce = true)", denominator: "COUNT(sessions)", multiplier: 100 },
          businessDefinition: 'Percentage of visitors who leave after viewing one page',
          benchmarks: { industryAverage: '55%', topQuartile: '35%', target: '45%' },
        },
        {
          id: 'MKT-WEB-003',
          name: 'Average Session Duration',
          description: 'Mean time spent per session',
          category: 'Web Analytics',
          type: 'behavioral',
          subcategory: 'Engagement',
          formula: "AVG(session_duration_seconds)",
          businessLogic: 'Average time users spend on site',
          dataType: 'INTEGER',
          unit: 'seconds',
          aggregation: 'AVG',
          granularity: 'Daily',
          sourceTables: ['silver.mktg_web_sessions_cleansed'],
          calculation: { numerator: "AVG(session_duration_seconds)" },
          businessDefinition: 'Average engagement depth per visit',
          benchmarks: { industryAverage: '180 seconds', topQuartile: '300 seconds', target: '240 seconds' },
        },
        {
          id: 'MKT-WEB-004',
          name: 'Pages Per Session',
          description: 'Average pages viewed per session',
          category: 'Web Analytics',
          type: 'behavioral',
          subcategory: 'Engagement',
          formula: "AVG(page_views)",
          businessLogic: 'Mean pages per session',
          dataType: 'DECIMAL',
          unit: 'count',
          aggregation: 'AVG',
          granularity: 'Daily',
          sourceTables: ['silver.mktg_web_sessions_cleansed'],
          calculation: { numerator: "AVG(page_views)" },
          businessDefinition: 'Content engagement per visit',
          benchmarks: { industryAverage: '3.5 pages', topQuartile: '5.5 pages', target: '4.5 pages' },
        },
        {
          id: 'MKT-WEB-005',
          name: 'Website Conversion Rate',
          description: 'Percentage of sessions resulting in conversion',
          category: 'Web Analytics',
          type: 'diagnostic',
          subcategory: 'Conversion',
          formula: "(SUM(converting_sessions) / SUM(total_sessions)) * 100",
          businessLogic: 'Sessions with conversion / all sessions',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Daily',
          sourceTables: ['silver.mktg_web_sessions_cleansed'],
          calculation: { numerator: "COUNT(WHERE is_conversion = true)", denominator: "COUNT(sessions)", multiplier: 100 },
          businessDefinition: 'Percentage of website visits that result in goal completion',
          benchmarks: { industryAverage: '2.5%', topQuartile: '4.5%', target: '3.5%' },
        },
        {
          id: 'MKT-WEB-006',
          name: 'New vs Returning Visitor Ratio',
          description: 'Percentage of new vs returning visitors',
          category: 'Web Analytics',
          type: 'behavioral',
          subcategory: 'Traffic',
          formula: "(new_visitors / total_visitors) * 100",
          businessLogic: 'New visitors / total unique visitors',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Daily',
          sourceTables: ['silver.mktg_web_sessions_cleansed'],
          calculation: { numerator: "COUNT(DISTINCT WHERE is_new_user = true)", denominator: "COUNT(DISTINCT user_id)", multiplier: 100 },
          businessDefinition: 'Balance between acquisition and retention traffic',
          benchmarks: { industryAverage: '60% new', topQuartile: '70% new', target: '65% new' },
        },
      ],
    },

    // Category 5: Mobile Engagement Metrics (5 metrics)
    {
      name: 'Mobile Engagement Metrics',
      description: 'Mobile app and push notification performance',
      totalMetrics: 5,
      
      metrics: [
        {
          id: 'MKT-MOB-001',
          name: 'Push Notification Delivery Rate',
          description: 'Percentage of push notifications delivered',
          category: 'Mobile Engagement',
          type: 'diagnostic',
          subcategory: 'Delivery',
          formula: "(delivered / sent) * 100",
          businessLogic: 'Successful deliveries / total sends',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Daily',
          sourceTables: ['bronze.mktg_push_notifications'],
          calculation: { numerator: "COUNT(WHERE delivery_status = 'delivered')", denominator: "COUNT(sent)", multiplier: 100 },
          businessDefinition: 'Push notification delivery success rate',
          benchmarks: { industryAverage: '92%', topQuartile: '97%', target: '95%' },
        },
        {
          id: 'MKT-MOB-002',
          name: 'Push Notification Open Rate',
          description: 'Percentage of delivered push notifications opened',
          category: 'Mobile Engagement',
          type: 'diagnostic',
          subcategory: 'Engagement',
          formula: "(opened / delivered) * 100",
          businessLogic: 'Opens / successful deliveries',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Daily',
          sourceTables: ['bronze.mktg_push_notifications'],
          calculation: { numerator: "COUNT(WHERE opened = true)", denominator: "COUNT(WHERE delivered = true)", multiplier: 100 },
          businessDefinition: 'Percentage of users who tap push notifications',
          benchmarks: { industryAverage: '8%', topQuartile: '15%', target: '12%' },
        },
        {
          id: 'MKT-MOB-003',
          name: 'Push Notification CTR',
          description: 'Percentage of push opens that resulted in app action',
          category: 'Mobile Engagement',
          type: 'risk',
          subcategory: 'Engagement',
          formula: "(clicks / opened) * 100",
          businessLogic: 'In-app actions / opens',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Daily',
          sourceTables: ['bronze.mktg_push_notifications'],
          calculation: { numerator: "COUNT(WHERE clicked = true)", denominator: "COUNT(WHERE opened = true)", multiplier: 100 },
          businessDefinition: 'Effectiveness of push notification content',
          benchmarks: { industryAverage: '25%', topQuartile: '40%', target: '32%' },
        },
        {
          id: 'MKT-MOB-004',
          name: 'Mobile App Session Duration',
          description: 'Average time spent in app per session',
          category: 'Mobile Engagement',
          type: 'behavioral',
          subcategory: 'Engagement',
          formula: "AVG(session_duration_seconds)",
          businessLogic: 'Mean session length in mobile app',
          dataType: 'INTEGER',
          unit: 'seconds',
          aggregation: 'AVG',
          granularity: 'Daily',
          sourceTables: ['silver.mktg_web_sessions_cleansed'],
          calculation: { numerator: "AVG(session_duration_seconds)", filters: "device_category = 'mobile' AND is_app = true" },
          businessDefinition: 'Average engagement time in mobile app',
          benchmarks: { industryAverage: '240 seconds', topQuartile: '420 seconds', target: '330 seconds' },
        },
        {
          id: 'MKT-MOB-005',
          name: 'Mobile Conversion Rate',
          description: 'Percentage of mobile sessions that convert',
          category: 'Mobile Engagement',
          type: 'diagnostic',
          subcategory: 'Conversion',
          formula: "(mobile_conversions / mobile_sessions) * 100",
          businessLogic: 'Mobile conversions / mobile sessions',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Daily',
          sourceTables: ['silver.mktg_web_sessions_cleansed'],
          calculation: { numerator: "COUNT(WHERE is_conversion = true AND device_category = 'mobile')", denominator: "COUNT(WHERE device_category = 'mobile')", multiplier: 100 },
          businessDefinition: 'Mobile-specific conversion performance',
          benchmarks: { industryAverage: '1.8%', topQuartile: '3.5%', target: '2.5%' },
        },
      ],
    },

    // Category 6: Lead Generation & Scoring Metrics (6 metrics)
    {
      name: 'Lead Generation & Scoring Metrics',
      description: 'Lead capture, qualification, and conversion tracking',
      totalMetrics: 6,
      
      metrics: [
        {
          id: 'MKT-LEAD-001',
          name: 'Total Leads Generated',
          description: 'Count of all marketing-generated leads',
          category: 'Lead Generation',
          type: 'operational',
          subcategory: 'Volume',
          formula: "COUNT(lead_id)",
          businessLogic: 'Total lead form submissions',
          dataType: 'INTEGER',
          unit: 'count',
          aggregation: 'COUNT',
          granularity: 'Daily',
          sourceTables: ['bronze.mktg_lead_generation'],
          calculation: { numerator: "COUNT(lead_id)" },
          businessDefinition: 'All leads captured through marketing channels',
          benchmarks: { industryAverage: '3000/month', topQuartile: '6000/month', target: '4500/month' },
        },
        {
          id: 'MKT-LEAD-002',
          name: 'Lead-to-Opportunity Conversion Rate',
          description: 'Percentage of leads that become qualified opportunities',
          category: 'Lead Generation',
          type: 'diagnostic',
          subcategory: 'Conversion',
          formula: "(opportunities / leads) * 100",
          businessLogic: 'Qualified opportunities / total leads',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Monthly',
          sourceTables: ['silver.mktg_leads_enriched'],
          calculation: { numerator: "COUNT(WHERE lead_status = 'qualified')", denominator: "COUNT(lead_id)", multiplier: 100 },
          businessDefinition: 'Lead qualification rate',
          benchmarks: { industryAverage: '18%', topQuartile: '28%', target: '23%' },
        },
        {
          id: 'MKT-LEAD-003',
          name: 'Average Lead Score',
          description: 'Mean lead quality score across all leads',
          category: 'Lead Generation',
          type: 'diagnostic',
          subcategory: 'Quality',
          formula: "AVG(lead_score)",
          businessLogic: 'Average predictive score (0-100)',
          dataType: 'INTEGER',
          unit: 'score',
          aggregation: 'AVG',
          granularity: 'Daily',
          sourceTables: ['silver.mktg_leads_enriched'],
          calculation: { numerator: "AVG(lead_score)" },
          businessDefinition: 'Average quality score based on firmographic and behavioral data',
          benchmarks: { industryAverage: '55', topQuartile: '72', target: '65' },
        },
        {
          id: 'MKT-LEAD-004',
          name: 'Lead Velocity Rate',
          description: 'Month-over-month growth rate of qualified leads',
          category: 'Lead Generation',
          type: 'diagnostic',
          subcategory: 'Growth',
          formula: "((current_month_leads - previous_month_leads) / previous_month_leads) * 100",
          businessLogic: 'MoM lead growth',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Monthly',
          sourceTables: ['silver.mktg_leads_enriched'],
          calculation: { numerator: "(current_month_leads - previous_month_leads)", denominator: "previous_month_leads", multiplier: 100 },
          businessDefinition: 'Lead generation pipeline growth rate',
          benchmarks: { industryAverage: '8% MoM', topQuartile: '15% MoM', target: '12% MoM' },
        },
        {
          id: 'MKT-LEAD-005',
          name: 'Cost Per Lead',
          description: 'Average cost to generate one lead',
          category: 'Lead Generation',
          type: 'financial',
          subcategory: 'Efficiency',
          formula: "SUM(spend) / COUNT(leads)",
          businessLogic: 'Total marketing spend / leads generated',
          dataType: 'DECIMAL',
          unit: 'currency',
          aggregation: 'CALCULATED',
          granularity: 'Monthly',
          sourceTables: ['gold.fact_marketing_roi'],
          calculation: { numerator: "SUM(marketing_spend)", denominator: "COUNT(leads)" },
          businessDefinition: 'Lead generation cost efficiency',
          benchmarks: { industryAverage: '$75', topQuartile: '$45', target: '$60' },
        },
        {
          id: 'MKT-LEAD-006',
          name: 'Lead Response Time',
          description: 'Average time to first contact after lead submission',
          category: 'Lead Generation',
          type: 'diagnostic',
          subcategory: 'Speed',
          formula: "AVG(first_contact_time - lead_submission_time)",
          businessLogic: 'Mean time from submission to first outreach',
          dataType: 'INTEGER',
          unit: 'minutes',
          aggregation: 'AVG',
          granularity: 'Daily',
          sourceTables: ['silver.mktg_leads_enriched'],
          calculation: { numerator: "AVG(DATEDIFF(minute, submission_timestamp, first_contact_timestamp))" },
          businessDefinition: 'Sales follow-up speed',
          benchmarks: { industryAverage: '120 minutes', topQuartile: '30 minutes', target: '60 minutes' },
        },
      ],
    },

    // Category 7: Multi-Touch Attribution Metrics (6 metrics)
    {
      name: 'Multi-Touch Attribution Metrics',
      description: 'Cross-channel attribution and journey analysis',
      totalMetrics: 6,
      
      metrics: [
        {
          id: 'MKT-ATTR-001',
          name: 'Average Touchpoints to Conversion',
          description: 'Mean number of marketing interactions before conversion',
          category: 'Attribution',
          type: 'diagnostic',
          subcategory: 'Journey',
          formula: "AVG(touchpoint_count)",
          businessLogic: 'Average marketing touches in customer journey',
          dataType: 'DECIMAL',
          unit: 'count',
          aggregation: 'AVG',
          granularity: 'Monthly',
          sourceTables: ['gold.fact_attribution'],
          calculation: { numerator: "AVG(total_touchpoints)" },
          businessDefinition: 'Complexity of customer journey before conversion',
          benchmarks: { industryAverage: '7 touchpoints', topQuartile: '10 touchpoints', target: '8 touchpoints' },
        },
        {
          id: 'MKT-ATTR-002',
          name: 'First-Touch Attribution Revenue',
          description: 'Revenue credited to first marketing touchpoint',
          category: 'Attribution',
          type: 'financial',
          subcategory: 'Model',
          formula: "SUM(revenue WHERE attribution_type = 'first_touch')",
          businessLogic: 'Revenue attributed to initial touchpoint',
          dataType: 'DECIMAL',
          unit: 'currency',
          aggregation: 'SUM',
          granularity: 'Monthly',
          sourceTables: ['gold.fact_attribution'],
          calculation: { numerator: "SUM(attributed_revenue)", filters: "attribution_type = 'first_touch'" },
          businessDefinition: 'Revenue credited to awareness channels',
          benchmarks: { industryAverage: '$1.2M/month', topQuartile: '$2.5M/month', target: '$1.8M/month' },
        },
        {
          id: 'MKT-ATTR-003',
          name: 'Last-Touch Attribution Revenue',
          description: 'Revenue credited to last marketing touchpoint',
          category: 'Attribution',
          type: 'financial',
          subcategory: 'Model',
          formula: "SUM(revenue WHERE attribution_type = 'last_touch')",
          businessLogic: 'Revenue attributed to final touchpoint',
          dataType: 'DECIMAL',
          unit: 'currency',
          aggregation: 'SUM',
          granularity: 'Monthly',
          sourceTables: ['gold.fact_attribution'],
          calculation: { numerator: "SUM(attributed_revenue)", filters: "attribution_type = 'last_touch'" },
          businessDefinition: 'Revenue credited to conversion channels',
          benchmarks: { industryAverage: '$1.5M/month', topQuartile: '$3.0M/month', target: '$2.2M/month' },
        },
        {
          id: 'MKT-ATTR-004',
          name: 'Linear Attribution Revenue',
          description: 'Revenue distributed equally across all touchpoints',
          category: 'Attribution',
          type: 'financial',
          subcategory: 'Model',
          formula: "SUM(revenue * (1 / touchpoint_count))",
          businessLogic: 'Equal credit attribution model',
          dataType: 'DECIMAL',
          unit: 'currency',
          aggregation: 'SUM',
          granularity: 'Monthly',
          sourceTables: ['gold.fact_attribution'],
          calculation: { numerator: "SUM(attributed_revenue)", filters: "attribution_type = 'linear'" },
          businessDefinition: 'Balanced view across entire journey',
          benchmarks: { industryAverage: '$1.8M/month', topQuartile: '$3.5M/month', target: '$2.5M/month' },
        },
        {
          id: 'MKT-ATTR-005',
          name: 'Time Decay Attribution Revenue',
          description: 'Revenue weighted toward recent touchpoints',
          category: 'Attribution',
          type: 'financial',
          subcategory: 'Model',
          formula: "SUM(revenue * time_decay_weight)",
          businessLogic: 'Recency-weighted attribution',
          dataType: 'DECIMAL',
          unit: 'currency',
          aggregation: 'SUM',
          granularity: 'Monthly',
          sourceTables: ['gold.fact_attribution'],
          calculation: { numerator: "SUM(attributed_revenue)", filters: "attribution_type = 'time_decay'" },
          businessDefinition: 'Revenue credited with recency bias',
          benchmarks: { industryAverage: '$1.6M/month', topQuartile: '$3.2M/month', target: '$2.3M/month' },
        },
        {
          id: 'MKT-ATTR-006',
          name: 'Cross-Device Journey Rate',
          description: 'Percentage of journeys spanning multiple devices',
          category: 'Attribution',
          type: 'diagnostic',
          subcategory: 'Journey',
          formula: "(multi_device_journeys / total_journeys) * 100",
          businessLogic: 'Journeys with 2+ devices / all journeys',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Monthly',
          sourceTables: ['gold.fact_customer_journey'],
          calculation: { numerator: "COUNT(WHERE device_count > 1)", denominator: "COUNT(journey_id)", multiplier: 100 },
          businessDefinition: 'Complexity of multi-device customer behavior',
          benchmarks: { industryAverage: '35%', topQuartile: '50%', target: '42%' },
        },
      ],
    },

    // Category 8: Customer Journey Metrics (5 metrics)
    {
      name: 'Customer Journey Metrics',
      description: 'End-to-end customer journey performance',
      totalMetrics: 5,
      
      metrics: [
        {
          id: 'MKT-JRNY-001',
          name: 'Average Journey Duration',
          description: 'Mean time from first touch to conversion',
          category: 'Journey',
          type: 'diagnostic',
          subcategory: 'Timing',
          formula: "AVG(conversion_date - first_touch_date)",
          businessLogic: 'Time from awareness to purchase',
          dataType: 'INTEGER',
          unit: 'days',
          aggregation: 'AVG',
          granularity: 'Monthly',
          sourceTables: ['gold.fact_customer_journey'],
          calculation: { numerator: "AVG(DATEDIFF(day, journey_start_date, conversion_date))" },
          businessDefinition: 'Sales cycle length from first touchpoint',
          benchmarks: { industryAverage: '45 days', topQuartile: '28 days', target: '35 days' },
        },
        {
          id: 'MKT-JRNY-002',
          name: 'Journey Completion Rate',
          description: 'Percentage of started journeys that convert',
          category: 'Journey',
          type: 'diagnostic',
          subcategory: 'Conversion',
          formula: "(completed_journeys / total_journeys) * 100",
          businessLogic: 'Conversions / all journey starts',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Monthly',
          sourceTables: ['gold.fact_customer_journey'],
          calculation: { numerator: "COUNT(WHERE journey_status = 'converted')", denominator: "COUNT(journey_id)", multiplier: 100 },
          businessDefinition: 'Overall funnel conversion rate',
          benchmarks: { industryAverage: '8%', topQuartile: '15%', target: '12%' },
        },
        {
          id: 'MKT-JRNY-003',
          name: 'Journey Abandonment Rate',
          description: 'Percentage of journeys abandoned before conversion',
          category: 'Journey',
          type: 'diagnostic',
          subcategory: 'Conversion',
          formula: "(abandoned_journeys / total_journeys) * 100",
          businessLogic: 'Abandoned / all journeys',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Monthly',
          sourceTables: ['gold.fact_customer_journey'],
          calculation: { numerator: "COUNT(WHERE journey_status = 'abandoned')", denominator: "COUNT(journey_id)", multiplier: 100 },
          businessDefinition: 'Percentage of incomplete customer journeys',
          benchmarks: { industryAverage: '78%', topQuartile: '65%', target: '72%' },
        },
        {
          id: 'MKT-JRNY-004',
          name: 'Channel Mix Diversity',
          description: 'Average number of different channels used per journey',
          category: 'Journey',
          type: 'diagnostic',
          subcategory: 'Complexity',
          formula: "AVG(DISTINCT channel_count)",
          businessLogic: 'Unique channels per customer journey',
          dataType: 'DECIMAL',
          unit: 'count',
          aggregation: 'AVG',
          granularity: 'Monthly',
          sourceTables: ['gold.fact_customer_journey'],
          calculation: { numerator: "AVG(unique_channels_used)" },
          businessDefinition: 'Cross-channel journey complexity',
          benchmarks: { industryAverage: '3.5 channels', topQuartile: '5 channels', target: '4 channels' },
        },
        {
          id: 'MKT-JRNY-005',
          name: 'Journey Revenue Per Conversion',
          description: 'Average revenue per completed journey',
          category: 'Journey',
          type: 'financial',
          subcategory: 'Value',
          formula: "SUM(revenue) / COUNT(conversions)",
          businessLogic: 'Total journey revenue / conversions',
          dataType: 'DECIMAL',
          unit: 'currency',
          aggregation: 'CALCULATED',
          granularity: 'Monthly',
          sourceTables: ['gold.fact_customer_journey'],
          calculation: { numerator: "SUM(conversion_value)", denominator: "COUNT(WHERE journey_status = 'converted')" },
          businessDefinition: 'Average deal size from marketing journeys',
          benchmarks: { industryAverage: '$850', topQuartile: '$1500', target: '$1200' },
        },
      ],
    },

    // Category 9: Segmentation & Personalization Metrics (6 metrics)
    {
      name: 'Segmentation & Personalization Metrics',
      description: 'Audience targeting and content personalization effectiveness',
      totalMetrics: 6,
      
      metrics: [
        {
          id: 'MKT-SEG-001',
          name: 'Active Segment Count',
          description: 'Number of customer segments currently targeted',
          category: 'Segmentation',
          type: 'behavioral',
          subcategory: 'Coverage',
          formula: "COUNT(DISTINCT segment_id WHERE active = true)",
          businessLogic: 'Active marketing segments',
          dataType: 'INTEGER',
          unit: 'count',
          aggregation: 'COUNT_DISTINCT',
          granularity: 'Monthly',
          sourceTables: ['silver.mktg_customer_segments_unified'],
          calculation: { numerator: "COUNT(DISTINCT segment_id WHERE is_active = true)" },
          businessDefinition: 'Number of segments with active campaigns',
          benchmarks: { industryAverage: '25 segments', topQuartile: '45 segments', target: '35 segments' },
        },
        {
          id: 'MKT-SEG-002',
          name: 'Segment Response Rate',
          description: 'Average response rate across all segments',
          category: 'Segmentation',
          type: 'diagnostic',
          subcategory: 'Performance',
          formula: "AVG(segment_response_rate)",
          businessLogic: 'Mean response across segments',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'AVG',
          granularity: 'Monthly',
          sourceTables: ['silver.mktg_segment_performance_agg'],
          calculation: { numerator: "AVG(response_rate)" },
          businessDefinition: 'Average segment engagement rate',
          benchmarks: { industryAverage: '12%', topQuartile: '22%', target: '17%' },
        },
        {
          id: 'MKT-SEG-003',
          name: 'Personalization Lift',
          description: 'Performance uplift from personalized vs generic content',
          category: 'Personalization',
          type: 'diagnostic',
          subcategory: 'Effectiveness',
          formula: "((personalized_ctr - generic_ctr) / generic_ctr) * 100",
          businessLogic: 'CTR improvement from personalization',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Monthly',
          sourceTables: ['gold.fact_campaign_performance'],
          calculation: { numerator: "(personalized_ctr - generic_ctr)", denominator: "generic_ctr", multiplier: 100 },
          businessDefinition: 'Incremental performance from content personalization',
          benchmarks: { industryAverage: '35% lift', topQuartile: '65% lift', target: '50% lift' },
        },
        {
          id: 'MKT-SEG-004',
          name: 'RFM Segment Distribution',
          description: 'Customer distribution across RFM segments',
          category: 'Segmentation',
          type: 'diagnostic',
          subcategory: 'Composition',
          formula: "COUNT(customers) GROUP BY rfm_segment",
          businessLogic: 'Customer count by RFM tier',
          dataType: 'JSON',
          unit: 'distribution',
          aggregation: 'COUNT',
          granularity: 'Monthly',
          sourceTables: ['silver.mktg_customer_segments_unified'],
          calculation: { numerator: "COUNT(customer_id)", groupBy: "rfm_segment" },
          businessDefinition: 'Customer value distribution analysis',
          benchmarks: { industryAverage: '15% Champions', topQuartile: '25% Champions', target: '20% Champions' },
        },
        {
          id: 'MKT-SEG-005',
          name: 'Dynamic Content Usage Rate',
          description: 'Percentage of campaigns using dynamic content',
          category: 'Personalization',
          type: 'behavioral',
          subcategory: 'Adoption',
          formula: "(dynamic_campaigns / total_campaigns) * 100",
          businessLogic: 'Campaigns with personalization / all campaigns',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Monthly',
          sourceTables: ['gold.fact_campaign_performance'],
          calculation: { numerator: "COUNT(WHERE has_dynamic_content = true)", denominator: "COUNT(campaign_id)", multiplier: 100 },
          businessDefinition: 'Personalization technology adoption',
          benchmarks: { industryAverage: '45%', topQuartile: '75%', target: '60%' },
        },
        {
          id: 'MKT-SEG-006',
          name: 'Predicted LTV Accuracy',
          description: 'Accuracy of customer lifetime value predictions',
          category: 'Segmentation',
          type: 'kpi',
          subcategory: 'Quality',
          formula: "1 - (ABS(predicted_ltv - actual_ltv) / actual_ltv)",
          businessLogic: 'Model prediction accuracy',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'AVG',
          granularity: 'Quarterly',
          sourceTables: ['silver.mktg_customer_segments_unified'],
          calculation: { numerator: "AVG(1 - (ABS(predicted_ltv - actual_ltv) / actual_ltv))", multiplier: 100 },
          businessDefinition: 'Predictive model accuracy for customer value',
          benchmarks: { industryAverage: '72%', topQuartile: '88%', target: '80%' },
        },
      ],
    },

    // Category 10: Marketing ROI & Efficiency Metrics (7 metrics)
    {
      name: 'Marketing ROI & Efficiency Metrics',
      description: 'Overall marketing efficiency, budget utilization, and ROI tracking',
      totalMetrics: 7,
      
      metrics: [
        {
          id: 'MKT-ROI-001',
          name: 'Customer Acquisition Cost (CAC)',
          description: 'Total cost to acquire one new customer',
          category: 'Marketing ROI',
          type: 'kpi',
          subcategory: 'Efficiency',
          formula: "SUM(total_marketing_spend) / SUM(new_customers)",
          businessLogic: 'Total marketing investment / customers acquired',
          dataType: 'DECIMAL',
          unit: 'currency',
          aggregation: 'CALCULATED',
          granularity: 'Monthly',
          sourceTables: ['gold.fact_marketing_roi', 'silver.mktg_spend'],
          calculation: { numerator: "SUM(total_marketing_spend)", denominator: "SUM(new_customers)" },
          businessDefinition: 'Blended CAC across all marketing channels',
          benchmarks: { industryAverage: '$250', topQuartile: '$150', target: '$200' },
        },
        {
          id: 'MKT-ROI-002',
          name: 'Customer Lifetime Value (LTV)',
          description: 'Predicted total value of customer over lifetime',
          category: 'Marketing ROI',
          type: 'kpi',
          subcategory: 'Value',
          formula: "(avg_order_value * purchase_frequency * customer_lifespan)",
          businessLogic: 'Projected customer revenue',
          dataType: 'DECIMAL',
          unit: 'currency',
          aggregation: 'AVG',
          granularity: 'Quarterly',
          sourceTables: ['silver.mktg_customer_segments_unified'],
          calculation: { numerator: "AVG(predicted_ltv)" },
          businessDefinition: 'Expected customer lifetime revenue',
          benchmarks: { industryAverage: '$1200', topQuartile: '$2500', target: '$1800' },
        },
        {
          id: 'MKT-ROI-003',
          name: 'LTV:CAC Ratio',
          description: 'Customer lifetime value to acquisition cost ratio',
          category: 'Marketing ROI',
          type: 'kpi',
          subcategory: 'Efficiency',
          formula: "AVG(ltv) / AVG(cac)",
          businessLogic: 'Value created per dollar spent acquiring',
          dataType: 'DECIMAL',
          unit: 'ratio',
          aggregation: 'CALCULATED',
          granularity: 'Quarterly',
          sourceTables: ['gold.fact_marketing_roi'],
          calculation: { numerator: "AVG(ltv)", denominator: "AVG(cac)" },
          businessDefinition: 'Return on customer acquisition investment',
          benchmarks: { industryAverage: '4:1', topQuartile: '7:1', target: '5.5:1' },
        },
        {
          id: 'MKT-ROI-004',
          name: 'Marketing Efficiency Ratio (MER)',
          description: 'Total revenue divided by total marketing spend',
          category: 'Marketing ROI',
          type: 'diagnostic',
          subcategory: 'Efficiency',
          formula: "SUM(total_revenue) / SUM(total_marketing_spend)",
          businessLogic: 'Revenue generated per dollar of marketing',
          dataType: 'DECIMAL',
          unit: 'ratio',
          aggregation: 'CALCULATED',
          granularity: 'Monthly',
          sourceTables: ['gold.fact_marketing_roi'],
          calculation: { numerator: "SUM(total_revenue)", denominator: "SUM(total_marketing_spend)" },
          businessDefinition: 'Overall marketing return efficiency',
          benchmarks: { industryAverage: '4.5:1', topQuartile: '7.0:1', target: '5.8:1' },
        },
        {
          id: 'MKT-ROI-005',
          name: 'Payback Period',
          description: 'Time to recover customer acquisition cost',
          category: 'Marketing ROI',
          type: 'diagnostic',
          subcategory: 'Timing',
          formula: "cac / (monthly_revenue_per_customer)",
          businessLogic: 'Months to break even on acquisition',
          dataType: 'DECIMAL',
          unit: 'months',
          aggregation: 'AVG',
          granularity: 'Quarterly',
          sourceTables: ['gold.fact_marketing_roi'],
          calculation: { numerator: "AVG(cac)", denominator: "AVG(monthly_revenue_per_customer)" },
          businessDefinition: 'Time to recoup customer acquisition investment',
          benchmarks: { industryAverage: '12 months', topQuartile: '6 months', target: '9 months' },
        },
        {
          id: 'MKT-ROI-006',
          name: 'Marketing Budget as % of Revenue',
          description: 'Marketing spend as percentage of total company revenue',
          category: 'Marketing ROI',
          type: 'financial',
          subcategory: 'Investment',
          formula: "(marketing_spend / total_revenue) * 100",
          businessLogic: 'Marketing investment intensity',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Quarterly',
          sourceTables: ['gold.fact_marketing_roi'],
          calculation: { numerator: "SUM(marketing_spend)", denominator: "SUM(total_revenue)", multiplier: 100 },
          businessDefinition: 'Marketing investment as percent of sales',
          benchmarks: { industryAverage: '8%', topQuartile: '12%', target: '10%' },
        },
        {
          id: 'MKT-ROI-007',
          name: 'Incremental Marketing ROI',
          description: 'ROI of marketing above baseline organic performance',
          category: 'Marketing ROI',
          type: 'financial',
          subcategory: 'ROI',
          formula: "((incremental_revenue - marketing_spend) / marketing_spend) * 100",
          businessLogic: 'Return above baseline',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Quarterly',
          sourceTables: ['gold.fact_marketing_roi'],
          calculation: { numerator: "(incremental_revenue - marketing_spend)", denominator: "marketing_spend", multiplier: 100 },
          businessDefinition: 'True incremental return from marketing investment',
          benchmarks: { industryAverage: '180%', topQuartile: '350%', target: '250%' },
        },
      ],
    },
  ],
};
