/**
 * MARKETING ORCHESTRATION - PRODUCTION TABLE STRUCTURES
 * 
 * Comprehensive table inventory for Marketing Orchestration domain
 * Organized by layer: Bronze (raw), Silver (conformed), Gold (dimensional)
 * Follows industry best practices for data warehouse design
 */

// ============================================================
// BRONZE LAYER - Raw, immutable data from source systems
// ============================================================
export const marketingOrchestrationBronzeTables = {
  // PEGA Source System Tables
  "bronze_pega_campaign": {
    name: "bronze_pega_campaign",
    description: "Raw PEGA campaign master data",
    grain: "One row per campaign version",
    columns: [
      { name: "campaign_id", type: "String", pk: true },
      { name: "version", type: "Integer" },
      { name: "campaign_name", type: "String" },
      { name: "campaign_type", type: "String" },
      { name: "channel", type: "String" },
      { name: "target_segment", type: "String" },
      { name: "created_date", type: "Timestamp" },
      { name: "launch_date", type: "Timestamp" },
      { name: "end_date", type: "Timestamp" },
      { name: "budget_amount", type: "Decimal" },
      { name: "status", type: "String" },
      { name: "owner", type: "String" },
    ],
  },
  "bronze_pega_nba_decision": {
    name: "bronze_pega_nba_decision",
    description: "Raw PEGA Next-Best-Action decision events",
    grain: "One row per NBA decision made",
    columns: [
      { name: "decision_id", type: "String", pk: true },
      { name: "interaction_id", type: "String" },
      { name: "customer_id", type: "String" },
      { name: "timestamp", type: "Timestamp" },
      { name: "strategy_name", type: "String" },
      { name: "decision_action", type: "String" },
      { name: "predicted_propensity", type: "Decimal" },
      { name: "customer_segment", type: "String" },
      { name: "channel_code", type: "String" },
      { name: "offer_id", type: "String" },
      { name: "ranking_score", type: "Decimal" },
      { name: "business_issue", type: "String" },
    ],
  },
  "bronze_pega_nba_response": {
    name: "bronze_pega_nba_response",
    description: "Raw PEGA NBA decision outcomes and customer responses",
    grain: "One row per customer response to offer",
    columns: [
      { name: "response_id", type: "String", pk: true },
      { name: "decision_id", type: "String", fk: true },
      { name: "customer_id", type: "String" },
      { name: "interaction_id", type: "String" },
      { name: "response_timestamp", type: "Timestamp" },
      { name: "response_action", type: "String" },
      { name: "acceptance_flag", type: "Integer" },
      { name: "conversion_flag", type: "Integer" },
      { name: "revenue_amount", type: "Decimal" },
      { name: "channel_response", type: "String" },
    ],
  },
  "bronze_pega_offer": {
    name: "bronze_pega_offer",
    description: "Raw PEGA offer configuration and master data",
    grain: "One row per offer",
    columns: [
      { name: "offer_id", type: "String", pk: true },
      { name: "offer_name", type: "String" },
      { name: "offer_type", type: "String" },
      { name: "product_line", type: "String" },
      { name: "product_code", type: "String" },
      { name: "offer_value", type: "Decimal" },
      { name: "valid_from_date", type: "Date" },
      { name: "valid_to_date", type: "Date" },
      { name: "max_redemptions", type: "Integer" },
      { name: "current_redemptions", type: "Integer" },
      { name: "terms_conditions", type: "String" },
      { name: "created_date", type: "Timestamp" },
      { name: "created_by", type: "String" },
    ],
  },
  "bronze_pega_propensity_score": {
    name: "bronze_pega_propensity_score",
    description: "Raw PEGA customer propensity scores from ML models",
    grain: "One row per customer per day",
    columns: [
      { name: "customer_id", type: "String", pk: true },
      { name: "score_date", type: "Date", pk: true },
      { name: "product_propensity_score", type: "Decimal" },
      { name: "churn_risk_score", type: "Decimal" },
      { name: "campaign_response_score", type: "Decimal" },
      { name: "purchase_intent_score", type: "Decimal" },
      { name: "model_version", type: "String" },
      { name: "loaded_timestamp", type: "Timestamp" },
    ],
  },
  "bronze_pega_customer_interaction": {
    name: "bronze_pega_customer_interaction",
    description: "Raw PEGA customer interaction and event stream",
    grain: "One row per customer interaction",
    columns: [
      { name: "interaction_id", type: "String", pk: true },
      { name: "customer_id", type: "String" },
      { name: "interaction_timestamp", type: "Timestamp" },
      { name: "channel", type: "String" },
      { name: "interaction_type", type: "String" },
      { name: "subject", type: "String" },
      { name: "duration_seconds", type: "Integer" },
      { name: "initiated_by", type: "String" },
      { name: "outcome", type: "String" },
      { name: "agent_id", type: "String" },
    ],
  },
  "bronze_activation_channel": {
    name: "bronze_activation_channel",
    description: "Raw channel activation and delivery tracking",
    grain: "One row per message sent",
    columns: [
      { name: "message_id", type: "String", pk: true },
      { name: "customer_id", type: "String" },
      { name: "decision_id", type: "String" },
      { name: "campaign_id", type: "String" },
      { name: "channel_code", type: "String" },
      { name: "sent_timestamp", type: "Timestamp" },
      { name: "delivery_status", type: "String" },
      { name: "delivery_timestamp", type: "Timestamp" },
      { name: "open_timestamp", type: "Timestamp" },
      { name: "click_timestamp", type: "Timestamp" },
      { name: "unsubscribe_flag", type: "Integer" },
    ],
  },
  "bronze_segment_membership": {
    name: "bronze_segment_membership",
    description: "Raw customer segment membership data",
    grain: "One row per customer per segment per day",
    columns: [
      { name: "customer_id", type: "String", pk: true },
      { name: "segment_id", type: "String", pk: true },
      { name: "segment_date", type: "Date", pk: true },
      { name: "segment_name", type: "String" },
      { name: "segment_description", type: "String" },
      { name: "membership_score", type: "Decimal" },
      { name: "entered_date", type: "Date" },
      { name: "exited_date", type: "Date" },
    ],
  },
};

// ============================================================
// SILVER LAYER - Conformed, deduplicated, business-ready
// ============================================================
export const marketingOrchestrationSilverTables = {
  "silver_campaign": {
    name: "silver_campaign",
    description: "Conformed campaign master data",
    grain: "One row per campaign",
    columns: [
      { name: "campaign_id", type: "String", pk: true },
      { name: "campaign_name", type: "String" },
      { name: "campaign_type", type: "String" },
      { name: "primary_channel", type: "String" },
      { name: "target_segment_id", type: "String" },
      { name: "campaign_start_date", type: "Date" },
      { name: "campaign_end_date", type: "Date" },
      { name: "total_budget", type: "Decimal" },
      { name: "campaign_status", type: "String" },
      { name: "owner_id", type: "String" },
      { name: "created_date", type: "Timestamp" },
      { name: "updated_date", type: "Timestamp" },
    ],
  },
  "silver_nba_decision": {
    name: "silver_nba_decision",
    description: "Conformed NBA decision facts",
    grain: "One row per NBA decision",
    columns: [
      { name: "decision_id", type: "String", pk: true },
      { name: "interaction_id", type: "String" },
      { name: "customer_id", type: "String" },
      { name: "decision_timestamp", type: "Timestamp" },
      { name: "strategy_id", type: "String" },
      { name: "strategy_name", type: "String" },
      { name: "offered_action", type: "String" },
      { name: "offer_id", type: "String" },
      { name: "predicted_propensity", type: "Decimal" },
      { name: "customer_segment_id", type: "String" },
      { name: "channel_id", type: "String" },
      { name: "ranking_score", type: "Decimal" },
      { name: "business_issue_id", type: "String" },
      { name: "decision_quality_flag", type: "Integer" },
    ],
  },
  "silver_nba_acceptance": {
    name: "silver_nba_acceptance",
    description: "NBA decision acceptance and conversion outcomes",
    grain: "One row per customer decision response",
    columns: [
      { name: "decision_id", type: "String", pk: true },
      { name: "customer_id", type: "String" },
      { name: "interaction_id", type: "String" },
      { name: "response_timestamp", type: "Timestamp" },
      { name: "response_type", type: "String" },
      { name: "acceptance_flag", type: "Integer" },
      { name: "conversion_flag", type: "Integer" },
      { name: "conversion_amount", type: "Decimal" },
      { name: "conversion_product_code", type: "String" },
      { name: "days_to_conversion", type: "Integer" },
    ],
  },
  "silver_offer_master": {
    name: "silver_offer_master",
    description: "Conformed offer master dimension",
    grain: "One row per offer",
    columns: [
      { name: "offer_id", type: "String", pk: true },
      { name: "offer_name", type: "String" },
      { name: "offer_type_id", type: "String" },
      { name: "offer_type_name", type: "String" },
      { name: "product_code", type: "String" },
      { name: "product_line_id", type: "String" },
      { name: "product_line_name", type: "String" },
      { name: "offer_value_amount", type: "Decimal" },
      { name: "offer_currency", type: "String" },
      { name: "offer_start_date", type: "Date" },
      { name: "offer_end_date", type: "Date" },
      { name: "offer_redemption_limit", type: "Integer" },
      { name: "offer_redemption_count", type: "Integer" },
      { name: "offer_status", type: "String" },
    ],
  },
  "silver_propensity_score": {
    name: "silver_propensity_score",
    description: "Cleansed customer propensity scores",
    grain: "One row per customer per date",
    columns: [
      { name: "customer_id", type: "String", pk: true },
      { name: "score_date", type: "Date", pk: true },
      { name: "product_purchase_propensity", type: "Decimal" },
      { name: "churn_risk_propensity", type: "Decimal" },
      { name: "campaign_response_propensity", type: "Decimal" },
      { name: "high_value_propensity", type: "Decimal" },
      { name: "propensity_model_version", type: "String" },
      { name: "data_quality_flag", type: "Integer" },
    ],
  },
  "silver_customer_segment": {
    name: "silver_customer_segment",
    description: "Conformed customer segment membership",
    grain: "One row per customer segment",
    columns: [
      { name: "customer_id", type: "String", pk: true },
      { name: "segment_id", type: "String", pk: true },
      { name: "segment_date", type: "Date", pk: true },
      { name: "segment_code", type: "String" },
      { name: "segment_name", type: "String" },
      { name: "segment_description", type: "String" },
      { name: "membership_confidence_score", type: "Decimal" },
      { name: "segment_entry_date", type: "Date" },
      { name: "segment_exit_date", type: "Date" },
    ],
  },
  "silver_campaign_performance": {
    name: "silver_campaign_performance",
    description: "Campaign execution and performance tracking",
    grain: "One row per day per campaign",
    columns: [
      { name: "campaign_id", type: "String", pk: true },
      { name: "performance_date", type: "Date", pk: true },
      { name: "messages_sent", type: "BigInt" },
      { name: "messages_delivered", type: "BigInt" },
      { name: "messages_opened", type: "BigInt" },
      { name: "messages_clicked", type: "BigInt" },
      { name: "conversions_count", type: "Integer" },
      { name: "conversion_revenue", type: "Decimal" },
      { name: "campaign_cost", type: "Decimal" },
    ],
  },
};

// ============================================================
// GOLD LAYER - Dimensional model for analytics and BI
// ============================================================
export const marketingOrchestrationGoldTables = {
  // FACT TABLES
  "fact_nba_decision_daily": {
    name: "fact_nba_decision_daily",
    type: "Fact",
    description: "NBA decisions aggregated by day",
    grain: "One row per day per strategy per customer segment",
    columns: [
      { name: "decision_date_id", type: "String", pk: true },
      { name: "strategy_key", type: "String", fk: true },
      { name: "segment_key", type: "String", fk: true },
      { name: "channel_key", type: "String", fk: true },
      { name: "product_key", type: "String", fk: true },
      { name: "decision_count", type: "BigInt" },
      { name: "acceptance_count", type: "BigInt" },
      { name: "conversion_count", type: "BigInt" },
      { name: "decision_acceptance_rate", type: "Decimal" },
      { name: "decision_conversion_rate", type: "Decimal" },
      { name: "total_conversion_revenue", type: "Decimal" },
      { name: "avg_propensity_score", type: "Decimal" },
      { name: "avg_ranking_score", type: "Decimal" },
    ],
  },
  "fact_campaign_performance_daily": {
    name: "fact_campaign_performance_daily",
    type: "Fact",
    description: "Campaign performance metrics by day",
    grain: "One row per day per campaign",
    columns: [
      { name: "performance_date_id", type: "String", pk: true },
      { name: "campaign_key", type: "String", fk: true },
      { name: "channel_key", type: "String", fk: true },
      { name: "segment_key", type: "String", fk: true },
      { name: "sends_count", type: "BigInt" },
      { name: "delivery_count", type: "BigInt" },
      { name: "open_count", type: "BigInt" },
      { name: "click_count", type: "BigInt" },
      { name: "conversion_count", type: "BigInt" },
      { name: "revenue_amount", type: "Decimal" },
      { name: "cost_amount", type: "Decimal" },
      { name: "open_rate", type: "Decimal" },
      { name: "click_rate", type: "Decimal" },
      { name: "conversion_rate", type: "Decimal" },
      { name: "roi", type: "Decimal" },
    ],
  },
  "fact_offer_performance_daily": {
    name: "fact_offer_performance_daily",
    type: "Fact",
    description: "Offer performance by day",
    grain: "One row per day per offer",
    columns: [
      { name: "performance_date_id", type: "String", pk: true },
      { name: "offer_key", type: "String", fk: true },
      { name: "product_key", type: "String", fk: true },
      { name: "offers_presented", type: "BigInt" },
      { name: "offers_viewed", type: "BigInt" },
      { name: "offers_clicked", type: "BigInt" },
      { name: "offers_accepted", type: "BigInt" },
      { name: "offers_converted", type: "BigInt" },
      { name: "conversion_revenue", type: "Decimal" },
      { name: "offer_cost", type: "Decimal" },
      { name: "view_rate", type: "Decimal" },
      { name: "click_rate", type: "Decimal" },
      { name: "acceptance_rate", type: "Decimal" },
      { name: "conversion_rate", type: "Decimal" },
    ],
  },
  "fact_personalization_daily": {
    name: "fact_personalization_daily",
    type: "Fact",
    description: "Personalization impact metrics",
    grain: "One row per day",
    columns: [
      { name: "date_id", type: "String", pk: true },
      { name: "total_interactions", type: "BigInt" },
      { name: "personalized_interactions", type: "BigInt" },
      { name: "non_personalized_interactions", type: "BigInt" },
      { name: "personalized_conversions", type: "BigInt" },
      { name: "non_personalized_conversions", type: "BigInt" },
      { name: "personalized_conversion_rate", type: "Decimal" },
      { name: "non_personalized_conversion_rate", type: "Decimal" },
      { name: "personalization_lift", type: "Decimal" },
      { name: "personalized_revenue", type: "Decimal" },
    ],
  },

  // DIMENSION TABLES
  "dim_strategy": {
    name: "dim_strategy",
    type: "Dimension",
    description: "NBA strategy dimension",
    columns: [
      { name: "strategy_key", type: "String", pk: true },
      { name: "strategy_id", type: "String" },
      { name: "strategy_name", type: "String" },
      { name: "business_issue", type: "String" },
      { name: "strategy_type", type: "String" },
      { name: "priority_level", type: "String" },
      { name: "effective_from_date", type: "Date" },
      { name: "effective_to_date", type: "Date" },
    ],
  },
  "dim_campaign": {
    name: "dim_campaign",
    type: "Dimension",
    description: "Campaign dimension",
    columns: [
      { name: "campaign_key", type: "String", pk: true },
      { name: "campaign_id", type: "String" },
      { name: "campaign_name", type: "String" },
      { name: "campaign_type", type: "String" },
      { name: "campaign_status", type: "String" },
      { name: "campaign_start_date", type: "Date" },
      { name: "campaign_end_date", type: "Date" },
    ],
  },
  "dim_offer": {
    name: "dim_offer",
    type: "Dimension",
    description: "Offer dimension",
    columns: [
      { name: "offer_key", type: "String", pk: true },
      { name: "offer_id", type: "String" },
      { name: "offer_name", type: "String" },
      { name: "offer_type", type: "String" },
      { name: "offer_value", type: "Decimal" },
      { name: "offer_start_date", type: "Date" },
      { name: "offer_end_date", type: "Date" },
    ],
  },
  "dim_segment": {
    name: "dim_segment",
    type: "Dimension",
    description: "Customer segment dimension",
    columns: [
      { name: "segment_key", type: "String", pk: true },
      { name: "segment_id", type: "String" },
      { name: "segment_name", type: "String" },
      { name: "segment_description", type: "String" },
      { name: "segment_type", type: "String" },
      { name: "parent_segment_id", type: "String" },
    ],
  },
  "dim_channel": {
    name: "dim_channel",
    type: "Dimension",
    description: "Communication channel dimension",
    columns: [
      { name: "channel_key", type: "String", pk: true },
      { name: "channel_id", type: "String" },
      { name: "channel_name", type: "String" },
      { name: "channel_type", type: "String" },
      { name: "channel_subtype", type: "String" },
    ],
  },
  "dim_product": {
    name: "dim_product",
    type: "Dimension",
    description: "Product dimension",
    columns: [
      { name: "product_key", type: "String", pk: true },
      { name: "product_id", type: "String" },
      { name: "product_code", type: "String" },
      { name: "product_name", type: "String" },
      { name: "product_line", type: "String" },
      { name: "product_category", type: "String" },
    ],
  },
  "dim_date": {
    name: "dim_date",
    type: "Dimension",
    description: "Date dimension",
    columns: [
      { name: "date_id", type: "String", pk: true },
      { name: "date", type: "Date" },
      { name: "year", type: "Integer" },
      { name: "quarter", type: "Integer" },
      { name: "month", type: "Integer" },
      { name: "week", type: "Integer" },
      { name: "day_of_week", type: "Integer" },
      { name: "is_business_day", type: "Integer" },
    ],
  },
};

export const marketingOrchestrationTablesCatalog = {
  bronze: Object.keys(marketingOrchestrationBronzeTables),
  silver: Object.keys(marketingOrchestrationSilverTables),
  gold: {
    facts: [
      "fact_nba_decision_daily",
      "fact_campaign_performance_daily",
      "fact_offer_performance_daily",
      "fact_personalization_daily",
    ],
    dimensions: [
      "dim_strategy",
      "dim_campaign",
      "dim_offer",
      "dim_segment",
      "dim_channel",
      "dim_product",
      "dim_date",
    ],
  },
};
