/**
 * MARKETING-RETAIL LOGICAL DATA MODEL
 * Banking-Specific Conceptual Model
 * 
 * Purpose: Solve real retail banking marketing use cases including:
 * - Checking/savings account acquisition campaigns
 * - Credit card and personal loan lead generation
 * - Cross-sell/up-sell to existing customers
 * - Branch marketing and local market campaigns
 * - Regulatory compliance (TCPA, CAN-SPAM, CFPB)
 * - Customer lifecycle marketing
 * - Product-specific attribution
 * - Retention and win-back campaigns
 */

export const marketingRetailLogicalModel = {
  name: 'Marketing-Retail Logical Model',
  description: 'Business-oriented conceptual model for retail banking marketing',
  version: '2.0',
  
  // CORE ENTITIES
  entities: [
    {
      name: 'Banking Product Campaign',
      type: 'core',
      businessPurpose: 'Marketing campaigns for specific banking products',
      realWorldExample: 'Q1 2024 Premium Checking Account Acquisition Campaign',
      attributes: [
        { name: 'campaign_id', type: 'STRING', isPrimaryKey: true, description: 'Unique campaign identifier' },
        { name: 'campaign_name', type: 'STRING', description: 'Campaign name (e.g., "Spring 2024 Rewards Card Promo")' },
        { name: 'product_line', type: 'STRING', description: 'Deposits|Cards|Loans|Investments|Mortgage', businessRule: 'Must align with bank product catalog' },
        { name: 'product_sku', type: 'STRING', description: 'Specific product being marketed (e.g., "REWARDS_VISA_PLATINUM")' },
        { name: 'campaign_objective', type: 'STRING', description: 'New_Account|Cross_Sell|Up_Sell|Retention|Win_Back|Reactivation' },
        { name: 'target_customer_segment', type: 'STRING', description: 'Mass|Mass_Affluent|Affluent|Student|Senior', businessRule: 'Segment must exist in customer segmentation model' },
        { name: 'target_age_range', type: 'STRING', description: 'Age targeting (18-24, 25-34, 35-44, 45-54, 55-64, 65+)' },
        { name: 'target_income_range', type: 'STRING', description: 'Income bracket targeting' },
        { name: 'target_credit_tier', type: 'STRING', description: 'Excellent|Good|Fair|Poor|None (for non-credit products)' },
        { name: 'channel_mix', type: 'JSON', description: 'Array of channels: Email, SMS, Push, Paid_Search, Paid_Social, Display, Direct_Mail, Branch' },
        { name: 'budget_total', type: 'DECIMAL(18,2)', description: 'Total campaign budget' },
        { name: 'budget_by_channel', type: 'JSON', description: 'Budget allocation across channels' },
        { name: 'offer_id', type: 'STRING', isForeignKey: true, description: 'Link to promotional offer if applicable' },
        { name: 'compliance_approval_required', type: 'BOOLEAN', description: 'Requires legal/compliance review' },
        { name: 'compliance_approved_by', type: 'STRING', description: 'Compliance officer who approved' },
        { name: 'compliance_approval_date', type: 'DATE', description: 'Date of compliance approval' },
        { name: 'tcpa_compliant', type: 'BOOLEAN', description: 'Telephone Consumer Protection Act compliance' },
        { name: 'can_spam_compliant', type: 'BOOLEAN', description: 'CAN-SPAM Act compliance' },
        { name: 'cfpb_reviewed', type: 'BOOLEAN', description: 'Consumer Financial Protection Bureau review flag' },
        { name: 'target_accounts_opened', type: 'INTEGER', description: 'Goal for new accounts opened' },
        { name: 'target_funded_accounts', type: 'INTEGER', description: 'Goal for funded accounts (> $0 balance)' },
        { name: 'target_total_deposits', type: 'DECIMAL(18,2)', description: 'Goal for total deposits/balances acquired' },
        { name: 'start_date', type: 'DATE', description: 'Campaign start date' },
        { name: 'end_date', type: 'DATE', description: 'Campaign end date' },
        { name: 'campaign_status', type: 'STRING', description: 'Draft|Compliance_Review|Approved|Active|Paused|Completed|Cancelled' },
      ],
      businessRules: [
        'All customer communication campaigns must be TCPA and CAN-SPAM compliant',
        'Credit card and loan campaigns must be CFPB reviewed',
        'Offers must not discriminate based on protected classes (ECOA compliance)',
        'Target segments must align with product eligibility criteria',
      ],
    },
    {
      name: 'Banking Product Offer',
      type: 'core',
      businessPurpose: 'Promotional offers tied to banking products',
      realWorldExample: '$200 bonus for new checking account with $500 initial deposit and 3 months of $500+ direct deposits',
      attributes: [
        { name: 'offer_id', type: 'STRING', isPrimaryKey: true },
        { name: 'offer_name', type: 'STRING', description: 'Human-readable offer name' },
        { name: 'product_line', type: 'STRING', description: 'Banking product line' },
        { name: 'product_sku', type: 'STRING', description: 'Specific product SKU' },
        { name: 'offer_type', type: 'STRING', description: 'Cash_Bonus|APR_Discount|Fee_Waiver|Points_Bonus|Rate_Boost' },
        { name: 'cash_bonus_amount', type: 'DECIMAL(10,2)', description: 'Cash bonus amount (e.g., $200)' },
        { name: 'apr_rate', type: 'DECIMAL(10,6)', description: 'Promotional APR for loans/cards' },
        { name: 'apr_duration_months', type: 'INTEGER', description: 'Duration of promotional APR' },
        { name: 'fee_waiver_type', type: 'STRING', description: 'Monthly_Maintenance|Annual|Overdraft|Foreign_Transaction' },
        { name: 'fee_waiver_duration_months', type: 'INTEGER', description: 'Duration of fee waiver' },
        { name: 'points_bonus', type: 'INTEGER', description: 'Bonus rewards points' },
        { name: 'interest_rate_boost_bps', type: 'INTEGER', description: 'Basis points boost on savings/CD rates' },
        { name: 'eligibility_criteria', type: 'JSON', description: 'Qualification requirements' },
        { name: 'min_opening_deposit', type: 'DECIMAL(10,2)', description: 'Minimum opening deposit required' },
        { name: 'min_direct_deposit_amount', type: 'DECIMAL(10,2)', description: 'Minimum monthly direct deposit' },
        { name: 'min_credit_score', type: 'INTEGER', description: 'Minimum FICO score required' },
        { name: 'min_monthly_transactions', type: 'INTEGER', description: 'Minimum monthly debit card transactions' },
        { name: 'terms_and_conditions', type: 'STRING', description: 'Legal T&Cs' },
        { name: 'offer_code', type: 'STRING', description: 'Promotional code for tracking' },
        { name: 'start_date', type: 'DATE', description: 'Offer valid from' },
        { name: 'end_date', type: 'DATE', description: 'Offer valid until' },
        { name: 'max_redemptions', type: 'INTEGER', description: 'Total redemption limit' },
        { name: 'max_per_customer', type: 'INTEGER', description: 'Redemption limit per customer' },
        { name: 'compliance_disclosure', type: 'STRING', description: 'Required compliance disclosures' },
        { name: 'risk_rating', type: 'STRING', description: 'Low|Medium|High - fraud/abuse risk' },
      ],
      businessRules: [
        'Cash bonuses require IRS 1099-INT reporting if >$600/year',
        'APR disclosures must comply with Truth in Lending Act (TILA)',
        'Eligibility criteria cannot discriminate (ECOA)',
        'Offers must be available to all customers in same circumstances',
      ],
    },
    {
      name: 'Banking Lead',
      type: 'event',
      businessPurpose: 'Prospective customer expressing interest in banking product',
      realWorldExample: 'Customer fills out mortgage pre-qualification form on bank website',
      attributes: [
        { name: 'lead_id', type: 'STRING', isPrimaryKey: true },
        { name: 'customer_id', type: 'STRING', isForeignKey: true, description: 'Existing customer or NULL for prospects' },
        { name: 'lead_type', type: 'STRING', description: 'New_Customer|Existing_Customer_Cross_Sell' },
        { name: 'product_interest', type: 'STRING', description: 'Checking|Savings|CD|CreditCard|PersonalLoan|AutoLoan|Mortgage|Investment' },
        { name: 'product_sku_interest', type: 'STRING', description: 'Specific product variant' },
        { name: 'lead_source', type: 'STRING', description: 'Website|Mobile_App|Branch|Call_Center|Referral|Paid_Search|Paid_Social|Email|SMS|Direct_Mail' },
        { name: 'campaign_id', type: 'STRING', isForeignKey: true, description: 'Source campaign if applicable' },
        { name: 'utm_source', type: 'STRING', description: 'Marketing source tracking' },
        { name: 'utm_medium', type: 'STRING' },
        { name: 'utm_campaign', type: 'STRING' },
        { name: 'submission_timestamp', type: 'TIMESTAMP', description: 'When lead was created' },
        { name: 'lead_status', type: 'STRING', description: 'New|Contacted|Qualified|Application_Started|Application_Submitted|Approved|Funded|Disqualified|Lost' },
        { name: 'lead_score', type: 'INTEGER', description: 'Predictive lead score 0-100' },
        { name: 'lead_grade', type: 'STRING', description: 'A|B|C|D|F based on likelihood to convert' },
        { name: 'qualification_status', type: 'STRING', description: 'Pre_Qualified|Qualified|Not_Qualified' },
        { name: 'disqualification_reason', type: 'STRING', description: 'Credit_Score|Income|Existing_Account|Location|Age' },
        { name: 'submitted_credit_score', type: 'INTEGER', description: 'Self-reported credit score range' },
        { name: 'submitted_income', type: 'DECIMAL(18,2)', description: 'Self-reported income' },
        { name: 'submitted_employment_status', type: 'STRING', description: 'Employed|Self_Employed|Retired|Student|Unemployed' },
        { name: 'loan_amount_requested', type: 'DECIMAL(18,2)', description: 'For loan products' },
        { name: 'loan_term_requested_months', type: 'INTEGER', description: 'For loan products' },
        { name: 'contact_consent_email', type: 'BOOLEAN', description: 'TCPA consent for email' },
        { name: 'contact_consent_phone', type: 'BOOLEAN', description: 'TCPA consent for phone' },
        { name: 'contact_consent_sms', type: 'BOOLEAN', description: 'TCPA consent for SMS' },
        { name: 'consent_timestamp', type: 'TIMESTAMP', description: 'When consent was given' },
        { name: 'consent_ip_address', type: 'STRING', description: 'IP address for compliance record' },
        { name: 'assigned_to_branch', type: 'STRING', description: 'Branch assigned for follow-up' },
        { name: 'assigned_to_banker', type: 'STRING', description: 'Banker/relationship manager assigned' },
        { name: 'first_contact_date', type: 'DATE', description: 'First outreach date' },
        { name: 'application_opened_date', type: 'DATE', description: 'When customer started application' },
        { name: 'application_submitted_date', type: 'DATE', description: 'When application was completed' },
        { name: 'account_opened_date', type: 'DATE', description: 'When account was opened' },
        { name: 'account_funded_date', type: 'DATE', description: 'When account received first deposit' },
        { name: 'days_to_application', type: 'INTEGER', description: 'Lead to application duration' },
        { name: 'days_to_funding', type: 'INTEGER', description: 'Lead to funded account duration' },
      ],
      businessRules: [
        'Cannot contact lead without proper TCPA consent',
        'Must honor opt-out requests within 10 days',
        'Lead scoring must not consider protected class attributes',
        'Must maintain consent documentation for 3+ years',
      ],
    },
    {
      name: 'Customer Banking Journey',
      type: 'event',
      businessPurpose: 'Track customer journey through banking product consideration and acquisition',
      realWorldExample: 'Customer journey from seeing credit card ad → clicking → applying → approval → activation',
      attributes: [
        { name: 'journey_id', type: 'STRING', isPrimaryKey: true },
        { name: 'customer_id', type: 'STRING', isForeignKey: true },
        { name: 'journey_type', type: 'STRING', description: 'Acquisition|Cross_Sell|Up_Sell|Retention' },
        { name: 'product_line', type: 'STRING', description: 'Product being considered' },
        { name: 'journey_start_date', type: 'DATE', description: 'First touchpoint date' },
        { name: 'journey_end_date', type: 'DATE', description: 'Conversion or abandonment date' },
        { name: 'journey_duration_days', type: 'INTEGER', description: 'Total journey duration' },
        { name: 'journey_status', type: 'STRING', description: 'In_Progress|Converted|Abandoned|Lost' },
        { name: 'conversion_event', type: 'STRING', description: 'Account_Opened|Loan_Funded|Card_Activated' },
        { name: 'conversion_value', type: 'DECIMAL(18,2)', description: 'Value of conversion (deposits, loan amount, credit limit)' },
        { name: 'total_touchpoints', type: 'INTEGER', description: 'Number of marketing touchpoints' },
        { name: 'touchpoint_channels', type: 'JSON', description: 'Array of channels in journey' },
        { name: 'first_touchpoint_channel', type: 'STRING', description: 'First marketing channel' },
        { name: 'last_touchpoint_channel', type: 'STRING', description: 'Last touchpoint before conversion' },
        { name: 'assisted_channels', type: 'JSON', description: 'All channels in middle of journey' },
        { name: 'days_to_conversion', type: 'INTEGER', description: 'Days from first touch to conversion' },
        { name: 'branch_visit_count', type: 'INTEGER', description: 'Number of branch visits' },
        { name: 'call_center_contact_count', type: 'INTEGER', description: 'Number of call center interactions' },
        { name: 'website_session_count', type: 'INTEGER', description: 'Website sessions' },
        { name: 'mobile_app_session_count', type: 'INTEGER', description: 'Mobile app sessions' },
        { name: 'abandonment_stage', type: 'STRING', description: 'Awareness|Consideration|Application|Approval' },
        { name: 'abandonment_reason', type: 'STRING', description: 'Better_Offer|Complexity|Denied|Lost_Interest' },
      ],
      businessRules: [
        'Journey starts at first attributable marketing touchpoint',
        'Journey ends at conversion or 90 days of inactivity',
        'Cross-device and cross-channel stitching required for accurate journey',
        'Branch and call center interactions must be integrated',
      ],
    },
    {
      name: 'Multi-Touch Attribution',
      type: 'analytical',
      businessPurpose: 'Attribute revenue and conversions across marketing touchpoints',
      realWorldExample: 'Credit card application attributed 40% to paid search, 30% to email, 30% to branch visit',
      attributes: [
        { name: 'attribution_id', type: 'STRING', isPrimaryKey: true },
        { name: 'customer_id', type: 'STRING', isForeignKey: true },
        { name: 'journey_id', type: 'STRING', isForeignKey: true },
        { name: 'conversion_date', type: 'DATE', description: 'Date of conversion event' },
        { name: 'conversion_type', type: 'STRING', description: 'Account_Open|Loan_Funded|Card_Activated|Deposit_Made' },
        { name: 'conversion_value', type: 'DECIMAL(18,2)', description: 'Value being attributed' },
        { name: 'product_line', type: 'STRING', description: 'Product that converted' },
        { name: 'attribution_model', type: 'STRING', description: 'First_Touch|Last_Touch|Linear|Time_Decay|U_Shaped|W_Shaped|Custom' },
        { name: 'attribution_window_days', type: 'INTEGER', description: 'Lookback window (e.g., 30, 60, 90 days)' },
        { name: 'attributed_touchpoints', type: 'JSON', description: 'Array of touchpoints with attribution credit' },
        { name: 'first_touch_channel', type: 'STRING', description: 'First touch channel' },
        { name: 'first_touch_credit', type: 'DECIMAL(5,4)', description: 'Credit to first touch (0-1)' },
        { name: 'first_touch_revenue', type: 'DECIMAL(18,2)', description: 'Revenue attributed to first touch' },
        { name: 'last_touch_channel', type: 'STRING', description: 'Last touch channel' },
        { name: 'last_touch_credit', type: 'DECIMAL(5,4)', description: 'Credit to last touch (0-1)' },
        { name: 'last_touch_revenue', type: 'DECIMAL(18,2)', description: 'Revenue attributed to last touch' },
        { name: 'assisted_touch_channels', type: 'JSON', description: 'Mid-journey channels with credit' },
        { name: 'branch_attribution_credit', type: 'DECIMAL(5,4)', description: 'Credit to branch channel' },
        { name: 'branch_attribution_revenue', type: 'DECIMAL(18,2)', description: 'Revenue attributed to branch' },
        { name: 'paid_search_attribution_credit', type: 'DECIMAL(5,4)' },
        { name: 'paid_search_attribution_revenue', type: 'DECIMAL(18,2)' },
        { name: 'email_attribution_credit', type: 'DECIMAL(5,4)' },
        { name: 'email_attribution_revenue', type: 'DECIMAL(18,2)' },
        { name: 'sms_attribution_credit', type: 'DECIMAL(5,4)' },
        { name: 'sms_attribution_revenue', type: 'DECIMAL(18,2)' },
        { name: 'social_attribution_credit', type: 'DECIMAL(5,4)' },
        { name: 'social_attribution_revenue', type: 'DECIMAL(18,2)' },
        { name: 'display_attribution_credit', type: 'DECIMAL(5,4)' },
        { name: 'display_attribution_revenue', type: 'DECIMAL(18,2)' },
        { name: 'direct_mail_attribution_credit', type: 'DECIMAL(5,4)' },
        { name: 'direct_mail_attribution_revenue', type: 'DECIMAL(18,2)' },
      ],
      businessRules: [
        'Sum of all attribution credits must equal 1.0',
        'Attribution window varies by product: 30 days (deposits), 60 days (cards), 90 days (loans)',
        'Branch touchpoints always receive minimum 20% credit in W-shaped model',
        'Attribution revenue must reconcile to actual conversion value',
      ],
    },
    {
      name: 'Compliance Consent Management',
      type: 'core',
      businessPurpose: 'Track marketing communication consent and preferences (TCPA, CAN-SPAM, GDPR, CCPA)',
      realWorldExample: 'Customer opts in to email and SMS for credit card offers but opts out of phone calls',
      attributes: [
        { name: 'consent_id', type: 'STRING', isPrimaryKey: true },
        { name: 'customer_id', type: 'STRING', isForeignKey: true },
        { name: 'consent_type', type: 'STRING', description: 'Email|SMS|Phone|Push|Direct_Mail' },
        { name: 'opt_in_status', type: 'BOOLEAN', description: 'TRUE = opted in, FALSE = opted out' },
        { name: 'consent_timestamp', type: 'TIMESTAMP', description: 'When consent was given/withdrawn' },
        { name: 'consent_method', type: 'STRING', description: 'Web_Form|Mobile_App|Branch|Call_Center|Paper_Form' },
        { name: 'consent_ip_address', type: 'STRING', description: 'IP address for compliance audit' },
        { name: 'consent_geolocation', type: 'STRING', description: 'Location for jurisdiction compliance' },
        { name: 'consent_language', type: 'STRING', description: 'Language of consent form' },
        { name: 'tcpa_consent', type: 'BOOLEAN', description: 'TCPA (telephone) consent' },
        { name: 'tcpa_consent_text', type: 'STRING', description: 'Exact consent language shown' },
        { name: 'can_spam_consent', type: 'BOOLEAN', description: 'Email marketing consent' },
        { name: 'gdpr_consent', type: 'BOOLEAN', description: 'GDPR consent (EU customers)' },
        { name: 'ccpa_opt_out', type: 'BOOLEAN', description: 'CCPA Do Not Sell (CA customers)' },
        { name: 'product_category_preferences', type: 'JSON', description: '{deposits: true, loans: false, investments: true}' },
        { name: 'frequency_preference', type: 'STRING', description: 'Daily|Weekly|Monthly|Quarterly' },
        { name: 'suppression_list_flag', type: 'BOOLEAN', description: 'Globally suppressed from marketing' },
        { name: 'suppression_reason', type: 'STRING', description: 'Customer_Request|Regulatory|Fraud|Deceased|Litigation' },
        { name: 'last_modified_timestamp', type: 'TIMESTAMP' },
        { name: 'last_modified_by', type: 'STRING', description: 'System or user who made change' },
        { name: 'audit_trail', type: 'JSON', description: 'Full consent change history' },
      ],
      businessRules: [
        'Must honor opt-out requests immediately (max 10 business days)',
        'Cannot contact via channel without valid, current consent',
        'Consent records must be retained for 3-7 years depending on jurisdiction',
        'SMS requires explicit opt-in (TCPA)',
        'Must provide easy opt-out mechanism in every communication',
      ],
    },
    {
      name: 'Marketing ROI by Product',
      type: 'analytical',
      businessPurpose: 'Calculate marketing return on investment by banking product line',
      realWorldExample: 'Credit card campaign: $500K spend, 2,000 accounts, $10M credit extended, projected $2M revenue over 24 months = 400% ROI',
      attributes: [
        { name: 'roi_id', type: 'STRING', isPrimaryKey: true },
        { name: 'campaign_id', type: 'STRING', isForeignKey: true },
        { name: 'product_line', type: 'STRING', description: 'Product category' },
        { name: 'calculation_date', type: 'DATE', description: 'ROI calculation date' },
        { name: 'calculation_period', type: 'STRING', description: 'Campaign|30_Days|60_Days|90_Days|12_Months|24_Months' },
        { name: 'total_marketing_spend', type: 'DECIMAL(18,2)', description: 'All marketing costs' },
        { name: 'media_spend', type: 'DECIMAL(18,2)', description: 'Paid media costs' },
        { name: 'creative_production_cost', type: 'DECIMAL(18,2)', description: 'Creative and production costs' },
        { name: 'technology_cost', type: 'DECIMAL(18,2)', description: 'MarTech platform costs' },
        { name: 'agency_fees', type: 'DECIMAL(18,2)', description: 'Agency/consultant fees' },
        { name: 'accounts_opened', type: 'INTEGER', description: 'Total accounts opened' },
        { name: 'accounts_funded', type: 'INTEGER', description: 'Accounts with >$0 balance' },
        { name: 'total_deposits_acquired', type: 'DECIMAL(18,2)', description: 'For deposit products' },
        { name: 'total_loans_funded', type: 'DECIMAL(18,2)', description: 'For loan products' },
        { name: 'total_credit_extended', type: 'DECIMAL(18,2)', description: 'For credit card products' },
        { name: 'revenue_interest_income', type: 'DECIMAL(18,2)', description: 'Interest income from loans/cards' },
        { name: 'revenue_fee_income', type: 'DECIMAL(18,2)', description: 'Fee income (monthly fees, interchange, etc.)' },
        { name: 'revenue_total', type: 'DECIMAL(18,2)', description: 'Total revenue generated' },
        { name: 'cost_of_funds', type: 'DECIMAL(18,2)', description: 'Cost to fund deposits/loans' },
        { name: 'expected_credit_losses', type: 'DECIMAL(18,2)', description: 'Projected credit losses' },
        { name: 'operational_costs', type: 'DECIMAL(18,2)', description: 'Servicing costs' },
        { name: 'net_revenue', type: 'DECIMAL(18,2)', description: 'Revenue - costs' },
        { name: 'roi_percentage', type: 'DECIMAL(8,4)', description: '(Net Revenue - Marketing Spend) / Marketing Spend' },
        { name: 'roas', type: 'DECIMAL(8,4)', description: 'Revenue / Marketing Spend' },
        { name: 'customer_acquisition_cost', type: 'DECIMAL(10,2)', description: 'Marketing Spend / Accounts Opened' },
        { name: 'cost_per_funded_account', type: 'DECIMAL(10,2)', description: 'Marketing Spend / Accounts Funded' },
        { name: 'ltv_to_cac_ratio', type: 'DECIMAL(8,4)', description: 'Customer LTV / CAC (target 3:1)' },
        { name: 'payback_period_months', type: 'INTEGER', description: 'Months to recoup marketing spend' },
        { name: 'incremental_revenue_flag', type: 'BOOLEAN', description: 'Revenue is incremental (not cannibalized)' },
      ],
      businessRules: [
        'ROI calculations must include all costs: media, creative, technology, agency',
        'Revenue projections must use conservative assumptions',
        'Must account for expected credit losses on loan/card products',
        'LTV calculations typically use 24-36 month horizon',
        'Incremental analysis required to avoid counting organic growth',
      ],
    },
  ],
  
  relationships: [
    {
      from: 'Banking Lead',
      to: 'Banking Product Campaign',
      type: 'many-to-one',
      cardinality: 'N:1',
      foreignKey: 'campaign_id',
      businessMeaning: 'Leads are generated by campaigns',
    },
    {
      from: 'Banking Lead',
      to: 'Banking Product Offer',
      type: 'many-to-one',
      cardinality: 'N:1',
      foreignKey: 'offer_id',
      businessMeaning: 'Leads may be associated with promotional offers',
    },
    {
      from: 'Customer Banking Journey',
      to: 'Banking Lead',
      type: 'one-to-one',
      cardinality: '1:1',
      foreignKey: 'lead_id',
      businessMeaning: 'Journeys track lead progression',
    },
    {
      from: 'Multi-Touch Attribution',
      to: 'Customer Banking Journey',
      type: 'many-to-one',
      cardinality: 'N:1',
      foreignKey: 'journey_id',
      businessMeaning: 'Attribution breaks down journey touchpoint credit',
    },
    {
      from: 'Compliance Consent Management',
      to: 'Customer',
      type: 'one-to-one',
      cardinality: '1:1',
      foreignKey: 'customer_id',
      businessMeaning: 'Each customer has consent preferences',
    },
    {
      from: 'Marketing ROI by Product',
      to: 'Banking Product Campaign',
      type: 'many-to-one',
      cardinality: 'N:1',
      foreignKey: 'campaign_id',
      businessMeaning: 'ROI measured per campaign',
    },
  ],
  
  businessUseCases: [
    {
      name: 'Checking Account Acquisition',
      description: 'Acquire new checking accounts with $200 cash bonus offer',
      entitiesUsed: ['Banking Product Campaign', 'Banking Product Offer', 'Banking Lead', 'Customer Banking Journey', 'Multi-Touch Attribution', 'Marketing ROI by Product'],
      metrics: ['New Accounts Opened', 'Funded Accounts', 'Total Deposits Acquired', 'CAC', 'Payback Period'],
    },
    {
      name: 'Credit Card Cross-Sell to Existing Customers',
      description: 'Target existing checking customers for rewards credit card',
      entitiesUsed: ['Banking Product Campaign', 'Banking Product Offer', 'Customer Banking Journey', 'Compliance Consent Management'],
      metrics: ['Cross-Sell Rate', 'Credit Utilization', 'Interchange Revenue', 'ROI'],
    },
    {
      name: 'Personal Loan Lead Nurturing',
      description: 'Nurture personal loan leads with multi-channel drip campaigns',
      entitiesUsed: ['Banking Lead', 'Customer Banking Journey', 'Multi-Touch Attribution', 'Compliance Consent Management'],
      metrics: ['Lead-to-Application Rate', 'Application-to-Funding Rate', 'Days to Funding', 'Loan Amount Funded'],
    },
    {
      name: 'Branch Marketing for Local Markets',
      description: 'Drive branch traffic with geo-targeted campaigns and local offers',
      entitiesUsed: ['Banking Product Campaign', 'Banking Product Offer', 'Multi-Touch Attribution'],
      metrics: ['Branch Visit Lift', 'Accounts Opened at Branch', 'Cost per Branch Visit', 'Branch Attribution Credit'],
    },
    {
      name: 'Customer Lifecycle Marketing',
      description: 'Target customers at different lifecycle stages (onboarding, growth, retention, win-back)',
      entitiesUsed: ['Banking Product Campaign', 'Customer Banking Journey', 'Compliance Consent Management'],
      metrics: ['Lifecycle Progression Rate', 'Customer Tenure', 'Products per Customer', 'Retention Rate'],
    },
    {
      name: 'Compliance-Aware Multi-Touch Attribution',
      description: 'Attribute conversions across channels while respecting consent preferences',
      entitiesUsed: ['Multi-Touch Attribution', 'Customer Banking Journey', 'Compliance Consent Management'],
      metrics: ['Channel Attribution Mix', 'Consented vs Non-Consented Reach', 'Compliant Touchpoint Rate'],
    },
  ],
};

export default marketingRetailLogicalModel;
