/**
 * OPEN-BANKING-RETAIL COMPREHENSIVE FILE
 * Complete implementation with Bronze, Silver, and Gold layers
 * 
 * Domain: Open Banking Retail
 * Area: Retail Banking
 * Purpose: Open Banking APIs, third-party access, consent management, API analytics
 * 
 * Complete implementation with:
 * - Bronze: 12 tables (600GB)
 * - Silver: 9 tables (350GB)
 * - Gold: 6 dimensions + 4 facts (450GB)
 * - Total: 31 tables, 1.4TB
 */

// ==================== BRONZE LAYER ====================

export const openBankingRetailBronzeTables = [
  {
    name: 'bronze.retail_ob_api_requests',
    description: 'Open Banking API request logs',
    sourceSystem: 'API_GATEWAY',
    loadType: 'STREAMING',
    grain: 'One row per API request',
    primaryKey: ['request_id', 'source_system'],
    estimatedRows: 500000000,
    estimatedSize: '250GB',
    schema: {
      request_id: "STRING PRIMARY KEY",
      source_system: "STRING PRIMARY KEY",
      request_timestamp: "TIMESTAMP",
      tpp_id: "STRING COMMENT 'Third-Party Provider identifier'",
      customer_id: "BIGINT COMMENT 'Bank customer'",
      consent_id: "STRING COMMENT 'FK to consent record'",
      api_endpoint: "STRING COMMENT '/accounts, /transactions, /payments'",
      api_method: "STRING COMMENT 'GET|POST|PUT|DELETE'",
      api_version: "STRING COMMENT 'v1.0, v2.0, v3.1'",
      request_path: "STRING",
      request_query_params: "STRING COMMENT 'JSON'",
      request_headers: "STRING COMMENT 'JSON (sanitized)'",
      ip_address: "STRING",
      user_agent: "STRING",
      response_status_code: "INTEGER COMMENT '200, 401, 403, 500, etc.'",
      response_time_ms: "INTEGER COMMENT 'API response time in milliseconds'",
      response_size_bytes: "INTEGER",
      is_successful: "BOOLEAN COMMENT 'Status code 200-299'",
      error_code: "STRING",
      error_message: "STRING",
      rate_limit_remaining: "INTEGER",
      is_rate_limited: "BOOLEAN",
    },
  },
  {
    name: 'bronze.retail_ob_consents',
    description: 'Open Banking consent records',
    sourceSystem: 'CONSENT_MANAGEMENT',
    loadType: 'CDC',
    grain: 'One row per consent',
    primaryKey: ['consent_id', 'source_system'],
    estimatedRows: 50000000,
    estimatedSize: '75GB',
    schema: {
      consent_id: "STRING PRIMARY KEY",
      source_system: "STRING PRIMARY KEY",
      customer_id: "BIGINT",
      tpp_id: "STRING",
      tpp_name: "STRING",
      consent_type: "STRING COMMENT 'Account Information|Payment Initiation|Confirmation of Funds'",
      consent_status: "STRING COMMENT 'Authorized|Revoked|Expired|Rejected'",
      consent_granted_timestamp: "TIMESTAMP",
      consent_expiry_timestamp: "TIMESTAMP",
      consent_revoked_timestamp: "TIMESTAMP",
      consent_scope: "STRING COMMENT 'JSON array of permissions'",
      accounts_authorized: "STRING COMMENT 'JSON array of account IDs'",
      permissions_granted: "STRING COMMENT 'JSON array: ReadAccountsBasic, ReadTransactions, etc.'",
      transaction_from_date: "DATE COMMENT 'Historical transaction access from date'",
      transaction_to_date: "DATE",
      max_transaction_history_days: "INTEGER COMMENT 'e.g., 90 days'",
      renewal_count: "INTEGER COMMENT 'Number of times consent renewed'",
      channel: "STRING COMMENT 'Web|Mobile App|TPP App'",
    },
  },
  {
    name: 'bronze.retail_ob_tpp_registry',
    description: 'Third-Party Provider (TPP) registry',
    sourceSystem: 'TPP_REGISTRY',
    loadType: 'DAILY',
    grain: 'One row per TPP per day',
    primaryKey: ['tpp_id', 'snapshot_date', 'source_system'],
    estimatedRows: 50000,
    estimatedSize: '500MB',
    schema: {
      tpp_id: "STRING PRIMARY KEY",
      snapshot_date: "DATE PRIMARY KEY",
      source_system: "STRING PRIMARY KEY",
      tpp_name: "STRING",
      tpp_legal_entity: "STRING",
      tpp_type: "STRING COMMENT 'AISP (Account Info)|PISP (Payment Initiation)|CBPII (Card-Based Payment)'",
      registration_number: "STRING COMMENT 'FCA/regulatory registration'",
      country_of_registration: "STRING",
      regulatory_authority: "STRING",
      registration_status: "STRING COMMENT 'Active|Suspended|Revoked'",
      registration_date: "DATE",
      certificate_id: "STRING COMMENT 'eIDAS certificate'",
      certificate_expiry_date: "DATE",
      api_version_supported: "STRING COMMENT 'JSON array of API versions'",
      contact_email: "STRING",
      privacy_policy_url: "STRING",
      terms_of_service_url: "STRING",
      is_trusted: "BOOLEAN",
      risk_rating: "STRING COMMENT 'Low|Medium|High'",
    },
  },
  {
    name: 'bronze.retail_ob_account_access_log',
    description: 'Account information access by TPPs',
    sourceSystem: 'API_GATEWAY',
    loadType: 'STREAMING',
    grain: 'One row per account access event',
    primaryKey: ['access_log_id', 'source_system'],
    estimatedRows: 300000000,
    estimatedSize: '150GB',
    schema: {
      access_log_id: "STRING PRIMARY KEY",
      source_system: "STRING PRIMARY KEY",
      access_timestamp: "TIMESTAMP",
      tpp_id: "STRING",
      customer_id: "BIGINT",
      consent_id: "STRING",
      account_id: "BIGINT",
      access_type: "STRING COMMENT 'Account Details|Balance|Transactions|Beneficiaries'",
      data_retrieved: "STRING COMMENT 'JSON summary of data accessed'",
      transaction_count_retrieved: "INTEGER",
      date_range_from: "DATE",
      date_range_to: "DATE",
    },
  },
  {
    name: 'bronze.retail_ob_payment_initiation',
    description: 'Payment initiation requests via Open Banking',
    sourceSystem: 'PAYMENT_HUB',
    loadType: 'STREAMING',
    grain: 'One row per payment initiation',
    primaryKey: ['payment_initiation_id', 'source_system'],
    estimatedRows: 100000000,
    estimatedSize: '50GB',
    schema: {
      payment_initiation_id: "STRING PRIMARY KEY",
      source_system: "STRING PRIMARY KEY",
      initiation_timestamp: "TIMESTAMP",
      tpp_id: "STRING",
      customer_id: "BIGINT",
      consent_id: "STRING",
      debtor_account_id: "BIGINT COMMENT 'Customer account being debited'",
      creditor_account_number: "STRING COMMENT 'Beneficiary account'",
      creditor_name: "STRING",
      payment_amount: "DECIMAL(18,2)",
      payment_currency: "STRING",
      payment_reference: "STRING",
      payment_type: "STRING COMMENT 'Domestic|International|Standing Order'",
      payment_status: "STRING COMMENT 'Pending|Authorized|Executed|Rejected|Failed'",
      authorization_timestamp: "TIMESTAMP COMMENT 'Customer SCA authorization'",
      execution_timestamp: "TIMESTAMP",
      rejection_reason: "STRING",
      sca_method: "STRING COMMENT 'SMS OTP|App Push|Biometric'",
      is_sca_completed: "BOOLEAN COMMENT 'Strong Customer Authentication'",
    },
  },
  {
    name: 'bronze.retail_ob_confirmation_of_funds',
    description: 'Confirmation of Funds (CoF) checks',
    sourceSystem: 'API_GATEWAY',
    loadType: 'STREAMING',
    grain: 'One row per CoF request',
    primaryKey: ['cof_request_id', 'source_system'],
    estimatedRows: 50000000,
    estimatedSize: '15GB',
    schema: {
      cof_request_id: "STRING PRIMARY KEY",
      source_system: "STRING PRIMARY KEY",
      request_timestamp: "TIMESTAMP",
      tpp_id: "STRING COMMENT 'Card-based payment instrument issuer'",
      customer_id: "BIGINT",
      consent_id: "STRING",
      account_id: "BIGINT",
      amount_to_check: "DECIMAL(18,2)",
      currency: "STRING",
      funds_available: "BOOLEAN COMMENT 'Response: true if sufficient funds'",
      response_timestamp: "TIMESTAMP",
      response_time_ms: "INTEGER",
    },
  },
  {
    name: 'bronze.retail_ob_sca_events',
    description: 'Strong Customer Authentication (SCA) events',
    sourceSystem: 'AUTH_SYSTEM',
    loadType: 'STREAMING',
    grain: 'One row per SCA event',
    primaryKey: ['sca_event_id', 'source_system'],
    estimatedRows: 80000000,
    estimatedSize: '40GB',
    schema: {
      sca_event_id: "STRING PRIMARY KEY",
      source_system: "STRING PRIMARY KEY",
      sca_timestamp: "TIMESTAMP",
      customer_id: "BIGINT",
      tpp_id: "STRING",
      consent_id: "STRING",
      sca_method: "STRING COMMENT 'SMS OTP|Mobile App|Biometric|Hardware Token'",
      sca_challenge_sent: "BOOLEAN",
      sca_challenge_timestamp: "TIMESTAMP",
      sca_response_timestamp: "TIMESTAMP",
      sca_result: "STRING COMMENT 'Success|Failed|Timeout|Cancelled'",
      failure_reason: "STRING",
      attempts_count: "INTEGER COMMENT 'Number of SCA attempts'",
      ip_address: "STRING",
      device_id: "STRING",
    },
  },
  {
    name: 'bronze.retail_ob_revenue_sharing',
    description: 'Revenue sharing transactions with TPPs',
    sourceSystem: 'BILLING_SYSTEM',
    loadType: 'MONTHLY',
    grain: 'One row per TPP per month',
    primaryKey: ['tpp_id', 'billing_month', 'source_system'],
    estimatedRows: 50000,
    estimatedSize: '100MB',
    schema: {
      tpp_id: "STRING PRIMARY KEY",
      billing_month: "DATE PRIMARY KEY COMMENT 'First day of month'",
      source_system: "STRING PRIMARY KEY",
      api_calls_count: "INTEGER",
      account_info_requests: "INTEGER",
      payment_initiations: "INTEGER",
      cof_requests: "INTEGER",
      revenue_per_api_call: "DECIMAL(10,4)",
      total_revenue: "DECIMAL(18,2)",
      revenue_share_percentage: "DECIMAL(5,2) COMMENT 'Bank share percentage'",
      bank_revenue: "DECIMAL(18,2)",
      tpp_revenue: "DECIMAL(18,2)",
    },
  },
  {
    name: 'bronze.retail_ob_data_breaches',
    description: 'Open Banking data breach incidents',
    sourceSystem: 'SECURITY_SYSTEM',
    loadType: 'CDC',
    grain: 'One row per breach incident',
    primaryKey: ['breach_id', 'source_system'],
    estimatedRows: 1000,
    estimatedSize: '10MB',
    schema: {
      breach_id: "BIGINT PRIMARY KEY",
      source_system: "STRING PRIMARY KEY",
      breach_timestamp: "TIMESTAMP",
      tpp_id: "STRING COMMENT 'TPP involved in breach'",
      breach_type: "STRING COMMENT 'Unauthorized Access|Data Leak|API Exploit|Consent Violation'",
      affected_customer_count: "INTEGER",
      affected_account_count: "INTEGER",
      data_compromised: "STRING COMMENT 'Account Numbers|Balances|Transactions|PII'",
      breach_severity: "STRING COMMENT 'Low|Medium|High|Critical'",
      detection_method: "STRING",
      detection_timestamp: "TIMESTAMP",
      remediation_timestamp: "TIMESTAMP",
      customers_notified: "BOOLEAN",
      regulator_notified: "BOOLEAN COMMENT 'FCA, ICO notification'",
      tpp_access_revoked: "BOOLEAN",
    },
  },
  {
    name: 'bronze.retail_ob_consent_dashboard_views',
    description: 'Customer consent dashboard interactions',
    sourceSystem: 'DIGITAL_BANKING',
    loadType: 'STREAMING',
    grain: 'One row per dashboard view',
    primaryKey: ['view_id', 'source_system'],
    estimatedRows: 30000000,
    estimatedSize: '10GB',
    schema: {
      view_id: "STRING PRIMARY KEY",
      source_system: "STRING PRIMARY KEY",
      view_timestamp: "TIMESTAMP",
      customer_id: "BIGINT",
      session_id: "STRING",
      page_viewed: "STRING COMMENT 'Active Consents|Consent History|Revoke Consent|TPP Details'",
      action_taken: "STRING COMMENT 'View Details|Revoke Consent|Renew Consent|No Action'",
      consent_id: "STRING COMMENT 'If action on specific consent'",
      time_on_page_seconds: "INTEGER",
      channel: "STRING COMMENT 'Web|Mobile App'",
    },
  },
  {
    name: 'bronze.retail_ob_api_errors',
    description: 'Open Banking API error logs',
    sourceSystem: 'API_GATEWAY',
    loadType: 'STREAMING',
    grain: 'One row per API error',
    primaryKey: ['error_id', 'source_system'],
    estimatedRows: 10000000,
    estimatedSize: '5GB',
    schema: {
      error_id: "STRING PRIMARY KEY",
      source_system: "STRING PRIMARY KEY",
      error_timestamp: "TIMESTAMP",
      request_id: "STRING COMMENT 'FK to API request'",
      tpp_id: "STRING",
      api_endpoint: "STRING",
      error_code: "STRING COMMENT 'OB standard error codes'",
      error_category: "STRING COMMENT 'Authentication|Authorization|Validation|Server Error'",
      error_message: "STRING",
      http_status_code: "INTEGER",
      is_client_error: "BOOLEAN COMMENT '4xx errors'",
      is_server_error: "BOOLEAN COMMENT '5xx errors'",
    },
  },
  {
    name: 'bronze.retail_ob_regulatory_reporting',
    description: 'Open Banking regulatory reporting data',
    sourceSystem: 'REGULATORY_REPORTING',
    loadType: 'QUARTERLY',
    grain: 'One row per reporting period',
    primaryKey: ['reporting_period', 'source_system'],
    estimatedRows: 100,
    estimatedSize: '5MB',
    schema: {
      reporting_period: "DATE PRIMARY KEY COMMENT 'Quarter end date'",
      source_system: "STRING PRIMARY KEY",
      total_active_consents: "INTEGER",
      total_tpps: "INTEGER",
      total_api_calls: "BIGINT",
      total_customers_with_active_consent: "INTEGER",
      total_payment_initiations: "BIGINT",
      total_payment_value: "DECIMAL(18,2)",
      consent_revocation_rate: "DECIMAL(5,4)",
      api_uptime_percentage: "DECIMAL(5,2)",
      average_api_response_time_ms: "INTEGER",
      complaints_received: "INTEGER",
      data_breaches_count: "INTEGER",
    },
  },
];

export const openBankingRetailBronzeLayerComplete = {
  description: 'Complete bronze layer for retail open banking domain',
  layer: 'BRONZE',
  tables: openBankingRetailBronzeTables,
  totalTables: 12,
  estimatedSize: '600GB',
  refreshFrequency: 'Real-time streaming for API calls, Daily for registry, Monthly/Quarterly for reporting',
  retention: '7 years (regulatory requirement under PSD2/Open Banking)',
};

// ==================== SILVER LAYER ====================

export const openBankingRetailSilverTables = [
  {
    name: 'silver.retail_ob_api_requests_enriched',
    description: 'Enriched API request logs with performance metrics',
    grain: 'One row per API request',
    scdType: 'Type 1',
    primaryKey: ['request_sk'],
    transformations: [
      'Parse and categorize API endpoints',
      'Calculate SLA compliance (95th percentile < 500ms)',
      'Link to TPP and consent records',
      'Identify anomalous request patterns',
    ],
  },
  {
    name: 'silver.retail_ob_consents_current',
    description: 'Current state of customer consents',
    grain: 'One row per active consent',
    scdType: 'Type 2',
    primaryKey: ['consent_sk'],
    transformations: [
      'Filter to active/valid consents',
      'Calculate days until expiration',
      'Aggregate permissions by consent',
      'Consent usage frequency tracking',
    ],
  },
  {
    name: 'silver.retail_ob_tpp_performance',
    description: 'TPP performance and reliability metrics',
    grain: 'One row per TPP per day',
    scdType: 'Type 1',
    primaryKey: ['tpp_id', 'performance_date'],
    transformations: [
      'Calculate API success rate',
      'Average response time by endpoint',
      'Error rate trending',
      'Customer satisfaction scores',
    ],
  },
  {
    name: 'silver.retail_ob_payment_initiation_enriched',
    description: 'Enriched payment initiation records',
    grain: 'One row per payment',
    scdType: 'Type 1',
    primaryKey: ['payment_initiation_sk'],
    transformations: [
      'Calculate time to authorization',
      'Link to fraud alerts',
      'Success rate by TPP',
      'SCA completion tracking',
    ],
  },
  {
    name: 'silver.retail_ob_customer_consent_summary',
    description: 'Customer-level consent summary',
    grain: 'One row per customer',
    scdType: 'Type 2',
    primaryKey: ['customer_id'],
    transformations: [
      'Count active consents per customer',
      'List authorized TPPs',
      'Calculate total data shared',
      'Consent engagement score',
    ],
  },
  {
    name: 'silver.retail_ob_api_performance_metrics',
    description: 'API performance metrics aggregated',
    grain: 'One row per endpoint per hour',
    scdType: 'Type 1',
    primaryKey: ['api_endpoint', 'performance_hour'],
    transformations: [
      'P50, P95, P99 response times',
      'Success rate by endpoint',
      'Request volume trending',
      'Rate limiting events',
    ],
  },
  {
    name: 'silver.retail_ob_revenue_aggregated',
    description: 'Aggregated revenue from Open Banking',
    grain: 'One row per month',
    scdType: 'Type 1',
    primaryKey: ['revenue_month'],
    transformations: [
      'Total API revenue',
      'Revenue by TPP',
      'Revenue by API type',
      'Cost per API call',
    ],
  },
  {
    name: 'silver.retail_ob_sca_completion_metrics',
    description: 'SCA completion and success metrics',
    grain: 'One row per day',
    scdType: 'Type 1',
    primaryKey: ['sca_date'],
    transformations: [
      'SCA completion rate',
      'Average completion time',
      'Failure reasons analysis',
      'Method effectiveness comparison',
    ],
  },
  {
    name: 'silver.retail_ob_regulatory_compliance',
    description: 'Regulatory compliance metrics',
    grain: 'One row per reporting period',
    scdType: 'Type 1',
    primaryKey: ['reporting_period'],
    transformations: [
      'API uptime calculation (target 99.5%)',
      'Response time compliance (95th percentile < 500ms)',
      'Consent management compliance',
      'Data breach tracking',
    ],
  },
];

export const openBankingRetailSilverLayerComplete = {
  description: 'Complete silver layer for retail open banking domain',
  layer: 'SILVER',
  tables: openBankingRetailSilverTables,
  totalTables: 9,
  estimatedSize: '350GB',
  refreshFrequency: 'Hourly for performance metrics, Daily for summaries',
  retention: '7 years',
};

// ==================== GOLD LAYER ====================

export const openBankingRetailGoldDimensions = [
  {
    name: 'gold.dim_tpp',
    description: 'Third-Party Provider dimension',
    type: 'SCD Type 2',
    grain: 'One row per TPP per effective period',
    primaryKey: 'tpp_key',
    schema: {
      tpp_key: "BIGINT PRIMARY KEY",
      tpp_id: "STRING",
      tpp_name: "STRING",
      tpp_type: "STRING COMMENT 'AISP|PISP|CBPII'",
      country_of_registration: "STRING",
      regulatory_authority: "STRING",
      registration_status: "STRING",
      is_trusted: "BOOLEAN",
      risk_rating: "STRING",
      effective_start_date: "DATE",
      effective_end_date: "DATE",
      is_current: "BOOLEAN",
    },
  },
  {
    name: 'gold.dim_api_endpoint',
    description: 'API endpoint taxonomy',
    type: 'SCD Type 1',
    grain: 'One row per API endpoint',
    primaryKey: 'api_endpoint_key',
    schema: {
      api_endpoint_key: "BIGINT PRIMARY KEY",
      api_endpoint_code: "STRING UNIQUE",
      api_endpoint_name: "STRING COMMENT '/accounts, /balances, /transactions, /payment-submissions'",
      api_category: "STRING COMMENT 'Account Information|Payment Initiation|Confirmation of Funds'",
      api_method: "STRING COMMENT 'GET|POST|PUT|DELETE'",
      api_version: "STRING",
      is_psd2_required: "BOOLEAN COMMENT 'Required under PSD2'",
      sla_response_time_ms: "INTEGER COMMENT 'Target response time'",
    },
  },
  {
    name: 'gold.dim_consent_type',
    description: 'Open Banking consent type dimension',
    type: 'SCD Type 1',
    grain: 'One row per consent type',
    primaryKey: 'consent_type_key',
    schema: {
      consent_type_key: "BIGINT PRIMARY KEY",
      consent_type_code: "STRING UNIQUE",
      consent_type_name: "STRING COMMENT 'Account Information|Payment Initiation|Confirmation of Funds'",
      consent_category: "STRING",
      max_duration_days: "INTEGER COMMENT 'Maximum consent validity (e.g., 90 days)'",
      requires_sca: "BOOLEAN COMMENT 'Strong Customer Authentication required'",
      permission_scope: "STRING COMMENT 'JSON array of allowed permissions'",
    },
  },
  {
    name: 'gold.dim_sca_method',
    description: 'Strong Customer Authentication method dimension',
    type: 'SCD Type 1',
    grain: 'One row per SCA method',
    primaryKey: 'sca_method_key',
    schema: {
      sca_method_key: "BIGINT PRIMARY KEY",
      sca_method_code: "STRING UNIQUE",
      sca_method_name: "STRING COMMENT 'SMS OTP|Mobile App Push|Biometric|Hardware Token'",
      sca_category: "STRING COMMENT 'Knowledge|Possession|Inherence'",
      is_psd2_compliant: "BOOLEAN",
      security_level: "STRING COMMENT 'Low|Medium|High'",
      typical_completion_time_seconds: "INTEGER",
    },
  },
  {
    name: 'gold.dim_payment_type',
    description: 'Open Banking payment type dimension',
    type: 'SCD Type 1',
    grain: 'One row per payment type',
    primaryKey: 'payment_type_key',
    schema: {
      payment_type_key: "BIGINT PRIMARY KEY",
      payment_type_code: "STRING UNIQUE",
      payment_type_name: "STRING COMMENT 'Domestic|International|Standing Order|Immediate Payment'",
      payment_scheme: "STRING COMMENT 'Faster Payments|SEPA|SWIFT'",
      typical_execution_time: "STRING COMMENT 'Instant|Same Day|1-3 Days'",
      requires_additional_auth: "BOOLEAN",
    },
  },
  {
    name: 'gold.dim_error_type',
    description: 'API error type taxonomy',
    type: 'SCD Type 1',
    grain: 'One row per error type',
    primaryKey: 'error_type_key',
    schema: {
      error_type_key: "BIGINT PRIMARY KEY",
      error_code: "STRING UNIQUE COMMENT 'OB standard error code'",
      error_name: "STRING",
      error_category: "STRING COMMENT 'Authentication|Authorization|Validation|Server Error|Rate Limit'",
      http_status_code: "INTEGER",
      is_client_error: "BOOLEAN",
      is_retryable: "BOOLEAN",
      typical_resolution: "STRING",
    },
  },
];

export const openBankingRetailGoldFacts = [
  {
    name: 'gold.fact_ob_api_calls',
    description: 'Open Banking API call transactions',
    factType: 'Transaction',
    grain: 'One row per API call',
    dimensions: ['tpp_key', 'customer_key', 'api_endpoint_key', 'consent_type_key', 'date_key', 'time_key'],
    schema: {
      api_call_key: "BIGINT PRIMARY KEY",
      tpp_key: "BIGINT",
      customer_key: "BIGINT",
      account_key: "BIGINT",
      api_endpoint_key: "BIGINT",
      consent_type_key: "BIGINT",
      date_key: "INTEGER",
      time_key: "INTEGER",
      request_id: "STRING UNIQUE",
      request_timestamp: "TIMESTAMP",
      api_call_count: "INTEGER DEFAULT 1",
      response_time_ms: "INTEGER",
      response_size_bytes: "INTEGER",
      is_successful: "BOOLEAN",
      is_rate_limited: "BOOLEAN",
      is_within_sla: "BOOLEAN COMMENT 'Response time within SLA'",
    },
    estimatedRows: 500000000,
    estimatedSize: '100GB',
  },
  {
    name: 'gold.fact_ob_consents',
    description: 'Open Banking consent lifecycle',
    factType: 'Accumulating Snapshot',
    grain: 'One row per consent',
    dimensions: ['customer_key', 'tpp_key', 'consent_type_key', 'granted_date_key', 'expiry_date_key', 'revoked_date_key'],
    schema: {
      consent_key: "BIGINT PRIMARY KEY",
      customer_key: "BIGINT",
      tpp_key: "BIGINT",
      consent_type_key: "BIGINT",
      granted_date_key: "INTEGER",
      expiry_date_key: "INTEGER",
      revoked_date_key: "INTEGER COMMENT 'NULL if not revoked'",
      consent_id: "STRING UNIQUE",
      consent_count: "INTEGER DEFAULT 1",
      consent_duration_days: "INTEGER",
      api_calls_count: "INTEGER COMMENT 'Number of API calls under this consent'",
      accounts_count: "INTEGER COMMENT 'Number of accounts authorized'",
      is_active: "BOOLEAN",
      is_expired: "BOOLEAN",
      is_revoked: "BOOLEAN",
      revocation_reason: "STRING",
    },
    estimatedRows: 50000000,
    estimatedSize: '15GB',
  },
  {
    name: 'gold.fact_ob_payments',
    description: 'Payment initiation via Open Banking',
    factType: 'Transaction',
    grain: 'One row per payment initiation',
    dimensions: ['customer_key', 'account_key (debtor)', 'tpp_key', 'payment_type_key', 'sca_method_key', 'initiation_date_key'],
    schema: {
      payment_key: "BIGINT PRIMARY KEY",
      customer_key: "BIGINT",
      debtor_account_key: "BIGINT",
      tpp_key: "BIGINT",
      payment_type_key: "BIGINT",
      sca_method_key: "BIGINT",
      initiation_date_key: "INTEGER",
      authorization_date_key: "INTEGER",
      execution_date_key: "INTEGER",
      payment_initiation_id: "STRING UNIQUE",
      payment_count: "INTEGER DEFAULT 1",
      payment_amount: "DECIMAL(18,2)",
      time_to_authorization_minutes: "INTEGER",
      time_to_execution_minutes: "INTEGER",
      is_sca_completed: "BOOLEAN",
      is_payment_executed: "BOOLEAN",
      is_payment_rejected: "BOOLEAN",
      rejection_reason: "STRING",
    },
    estimatedRows: 100000000,
    estimatedSize: '30GB',
  },
  {
    name: 'gold.fact_ob_api_performance_daily',
    description: 'Daily Open Banking API performance snapshot',
    factType: 'Periodic Snapshot',
    grain: 'One row per API endpoint per day',
    dimensions: ['api_endpoint_key', 'date_key'],
    schema: {
      api_endpoint_key: "BIGINT",
      date_key: "INTEGER",
      snapshot_date: "DATE",
      total_api_calls: "INTEGER",
      successful_calls: "INTEGER",
      failed_calls: "INTEGER",
      success_rate: "DECIMAL(5,4)",
      avg_response_time_ms: "INTEGER",
      p50_response_time_ms: "INTEGER",
      p95_response_time_ms: "INTEGER",
      p99_response_time_ms: "INTEGER",
      max_response_time_ms: "INTEGER",
      rate_limited_calls: "INTEGER",
      sla_compliance_rate: "DECIMAL(5,4) COMMENT 'Calls within SLA / Total calls'",
      uptime_percentage: "DECIMAL(5,2)",
      unique_tpps: "INTEGER COMMENT 'Distinct TPPs accessing this endpoint'",
      unique_customers: "INTEGER",
    },
    estimatedRows: 3650000,
    estimatedSize: '10GB',
  },
];

export const openBankingRetailGoldLayerComplete = {
  description: 'Complete gold layer for retail open banking domain',
  layer: 'GOLD',
  dimensions: openBankingRetailGoldDimensions,
  facts: openBankingRetailGoldFacts,
  totalDimensions: 6,
  totalFacts: 4,
  estimatedSize: '450GB',
  refreshFrequency: 'Real-time for API calls, Daily for performance snapshots',
  methodology: 'Kimball Dimensional Modeling',
};

// ==================== METRICS CATALOG ====================

export const openBankingRetailMetricsCatalog = {
  totalMetrics: 280,
  categories: [
    {
      category: 'API Performance',
      metrics: [
        { name: 'API Uptime', definition: 'Successful API calls / Total API calls', target: '>=99.5%' },
        { name: 'P95 Response Time', definition: '95th percentile API response time', target: '<=500ms' },
        { name: 'API Success Rate', definition: 'HTTP 2xx responses / Total requests', target: '>=95%' },
        { name: 'Rate Limit Violation Rate', definition: 'Rate limited calls / Total calls', target: '<=1%' },
      ],
    },
    {
      category: 'Consent Management',
      metrics: [
        { name: 'Active Consent Rate', definition: 'Active consents / Total consents', target: '>=70%' },
        { name: 'Consent Revocation Rate', definition: 'Revoked consents / Total consents', target: '<=10%' },
        { name: 'Average Consent Duration', definition: 'Average days consent remains active', target: '>=60 days' },
        { name: 'Consent Renewal Rate', definition: 'Renewed consents / Expired consents', target: '>=50%' },
      ],
    },
    {
      category: 'Payment Initiation',
      metrics: [
        { name: 'Payment Authorization Rate', definition: 'Authorized payments / Initiated payments', target: '>=90%' },
        { name: 'SCA Completion Rate', definition: 'Completed SCA / SCA attempts', target: '>=95%' },
        { name: 'Average Time to Authorization', definition: 'Average minutes from initiation to authorization', target: '<=5 minutes' },
        { name: 'Payment Execution Rate', definition: 'Executed payments / Authorized payments', target: '>=99%' },
      ],
    },
    {
      category: 'Revenue & Adoption',
      metrics: [
        { name: 'Total API Revenue', definition: 'Sum of all API call revenue', target: 'Increasing MoM' },
        { name: 'Revenue per API Call', definition: 'Total revenue / API calls', target: '>=$0.01' },
        { name: 'Customer Adoption Rate', definition: 'Customers with active consent / Total customers', target: '>=15%' },
        { name: 'TPP Onboarding Rate', definition: 'New TPPs registered per quarter', target: '>=10' },
      ],
    },
  ],
};

// ==================== EXPORT ====================

export const openBankingRetailBronzeLayer = openBankingRetailBronzeLayerComplete;
export const openBankingRetailSilverLayer = openBankingRetailSilverLayerComplete;
export const openBankingRetailGoldLayer = openBankingRetailGoldLayerComplete;

export default {
  openBankingRetailBronzeLayer,
  openBankingRetailSilverLayer,
  openBankingRetailGoldLayer,
  openBankingRetailMetricsCatalog,
};
