/**
 * OPEN-BANKING-RETAIL METRICS CATALOG
 * Open banking API adoption, security, and third-party integration metrics
 */

export const openBankingRetailMetricsCatalog = {
  description: 'Open banking API usage, consent management, and third-party provider metrics',
  totalMetrics: 340,
  
  categories: [
    {
      name: 'API Usage Metrics',
      description: 'Open banking API call volume and performance',
      totalMetrics: 70,
      metrics: [
        {
          id: 'OB-API-001',
          name: 'Total API Calls',
          description: 'Number of open banking API requests',
          category: 'API Usage',
          type: 'operational',
          subcategory: 'Volume',
          formula: "COUNT(api_call_id)",
          businessLogic: 'Count of API requests',
          dataType: 'INTEGER',
          unit: 'count',
          aggregation: 'COUNT',
          granularity: 'Daily',
          sourceTables: ['bronze.open_banking_api_logs', 'gold.fact_api_usage'],
          calculation: { numerator: "COUNT(request_id)" },
          businessDefinition: 'Open banking API request volume',
          benchmarks: { industryAverage: '850K calls/day', topQuartile: '1.5M calls/day', target: '1.1M calls/day' },
        },
        {
          id: 'OB-API-002',
          name: 'API Success Rate',
          description: 'Percentage of successful API calls',
          category: 'API Usage',
          type: 'diagnostic',
          subcategory: 'Reliability',
          formula: "(successful_calls / total_calls) * 100",
          businessLogic: 'Successful API calls divided by total',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Daily',
          sourceTables: ['bronze.open_banking_api_logs'],
          calculation: { numerator: "COUNT(WHERE status_code = 200)", denominator: "COUNT(request_id)", multiplier: 100 },
          businessDefinition: 'API reliability measurement',
          benchmarks: { industryAverage: '99.2%', topQuartile: '99.8%', target: '99.5%' },
        },
      ],
    },
    {
      name: 'Consent Management Metrics',
      description: 'Customer consent tracking and authorization management',
      totalMetrics: 65,
      metrics: [
        {
          id: 'OB-CONS-001',
          name: 'Active Consents',
          description: 'Number of active open banking customer consents',
          category: 'Consent',
          type: 'behavioral',
          subcategory: 'Volume',
          formula: "COUNT(consent_id WHERE status = 'active')",
          businessLogic: 'Count of active customer consents',
          dataType: 'INTEGER',
          unit: 'count',
          aggregation: 'COUNT',
          granularity: 'Daily',
          sourceTables: ['bronze.open_banking_consents'],
          calculation: { numerator: "COUNT(consent_id)", filters: "status = 'active'" },
          businessDefinition: 'Active open banking authorizations',
          benchmarks: { industryAverage: '125K consents', topQuartile: '280K consents', target: '190K consents' },
        },
        {
          id: 'OB-CONS-002',
          name: 'Consent Revocation Rate',
          description: 'Percentage of consents revoked by customers',
          category: 'Consent',
          type: 'diagnostic',
          subcategory: 'Revocation',
          formula: "(revoked_consents / total_consents) * 100",
          businessLogic: 'Revoked consents divided by total granted',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Monthly',
          sourceTables: ['bronze.open_banking_consents'],
          calculation: { numerator: "COUNT(WHERE status = 'revoked')", denominator: "COUNT(consent_id)", multiplier: 100 },
          businessDefinition: 'Customer consent withdrawal rate',
          benchmarks: { industryAverage: '8.5%', topQuartile: '5.2%', target: '6.5%' },
        },
      ],
    },
    {
      name: 'Third-Party Provider Metrics',
      description: 'TPP registration, activity, and compliance tracking',
      totalMetrics: 65,
      metrics: [
        {
          id: 'OB-TPP-001',
          name: 'Registered Third-Party Providers',
          description: 'Number of registered TPPs accessing APIs',
          category: 'TPP',
          type: 'diagnostic',
          subcategory: 'Registration',
          formula: "COUNT(DISTINCT tpp_id WHERE status = 'active')",
          businessLogic: 'Count of active registered TPPs',
          dataType: 'INTEGER',
          unit: 'count',
          aggregation: 'COUNT_DISTINCT',
          granularity: 'Monthly',
          sourceTables: ['bronze.open_banking_tpp_registry'],
          calculation: { numerator: "COUNT(DISTINCT tpp_id)", filters: "registration_status = 'active'" },
          businessDefinition: 'Active third-party provider count',
          benchmarks: { industryAverage: '350 TPPs', topQuartile: '650 TPPs', target: '500 TPPs' },
        },
      ],
    },
    {
      name: 'Security Metrics',
      description: 'Open banking security and authentication tracking',
      totalMetrics: 70,
      metrics: [
        {
          id: 'OB-SEC-001',
          name: 'Strong Customer Authentication Rate',
          description: 'Percentage of API calls with SCA',
          category: 'Security',
          type: 'diagnostic',
          subcategory: 'Authentication',
          formula: "(sca_calls / total_sensitive_calls) * 100",
          businessLogic: 'SCA-protected calls divided by sensitive operations',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Daily',
          sourceTables: ['bronze.open_banking_api_logs'],
          calculation: { numerator: "COUNT(WHERE sca_performed = true)", denominator: "COUNT(WHERE requires_sca = true)", multiplier: 100 },
          businessDefinition: 'PSD2 strong authentication compliance',
          benchmarks: { industryAverage: '98%', topQuartile: '99.7%', target: '99%' },
        },
      ],
    },
    {
      name: 'Revenue Metrics',
      description: 'Open banking monetization and value creation',
      totalMetrics: 70,
      metrics: [
        {
          id: 'OB-REV-001',
          name: 'Premium API Revenue',
          description: 'Revenue from premium open banking API services',
          category: 'Revenue',
          type: 'financial',
          subcategory: 'API Monetization',
          formula: "SUM(api_fee_revenue)",
          businessLogic: 'Sum of premium API service fees',
          dataType: 'DECIMAL',
          unit: 'currency',
          aggregation: 'SUM',
          granularity: 'Monthly',
          sourceTables: ['bronze.open_banking_revenue'],
          calculation: { numerator: "SUM(premium_api_fees)" },
          businessDefinition: 'Open banking premium service revenue',
          benchmarks: { industryAverage: '$120K/month', topQuartile: '$280K/month', target: '$190K/month' },
        },
      ],
    },
  ],
};
