/**
 * CUSTOMER DOMAIN - GOLD LAYER
 * 
 * Aggregated analytics layer optimized for BI reporting
 * CUSTOMER_DEPOSIT_AGGR table consolidates customer behavioral and demographic data
 * Source: CORE_CUSTOMERS (Silver) + CORE_DEPOSIT (Silver)
 */

export interface GoldTableColumn {
  columnName: string;
  dataType: string;
  sourceSchema: string;
  sourceTable: string;
  sourceColumn: string;
  businessMeaning: string;
  nullable: boolean;
}

export interface GoldTable {
  name: string;
  schema: string;
  type: "FACT" | "DIMENSION" | "AGGREGATE";
  grain: string;
  description: string;
  columns: GoldTableColumn[];
  estimatedRows: number;
  updateFrequency: string;
}

// ============================================================================
// CUSTOMER_DEPOSIT_AGGR - Gold Aggregated Fact Table
// ============================================================================
export const customerDepositAggrTable: GoldTable = {
  name: "CUSTOMER_DEPOSIT_AGGR",
  schema: "ANALYTICS",
  type: "AGGREGATE",
  grain: "One row per customer with consolidated deposit metrics",
  description: "Comprehensive customer and deposit aggregation combining demographics, account behavior, and transaction analytics",
  estimatedRows: 5500000,
  updateFrequency: "Daily",
  columns: [
    // IDENTIFIERS
    {
      columnName: "CUSTOMER_NUMBER",
      dataType: "VARCHAR(50)",
      sourceSchema: "CORE_CUSTOMERS",
      sourceTable: "DIM_CUSTOMER_ATTRIBUTE",
      sourceColumn: "CUSTOMER_NUMBER",
      businessMeaning: "Unique customer identifier",
      nullable: false,
    },
    {
      columnName: "TAX_IDENTIFICATION_NUMBER",
      dataType: "VARCHAR(50)",
      sourceSchema: "CORE_CUSTOMERS",
      sourceTable: "DIM_CUSTOMER_IDENTIFER",
      sourceColumn: "TAX_IDENTIFICATION_NUMBER",
      businessMeaning: "Tax ID for customer",
      nullable: false,
    },
    {
      columnName: "PRCS_DTE",
      dataType: "DATE",
      sourceSchema: "CORE_CUSTOMERS",
      sourceTable: "DIM_CUSTOMER_DEMOGRAPHY",
      sourceColumn: "BUSINESS_DATE",
      businessMeaning: "Processing date for the aggregate snapshot",
      nullable: false,
    },
    {
      columnName: "DATA_LOAD_DATE",
      dataType: "DATE",
      sourceSchema: "SYSTEM",
      sourceTable: "SYSTEM_DATE",
      sourceColumn: "CURRENT_DATE",
      businessMeaning: "System load date",
      nullable: false,
    },
    // ACCOUNT METRICS
    {
      columnName: "ACC_TOTAL_ACCOUNTS",
      dataType: "NUMBER(38,0)",
      sourceSchema: "CORE_DEPOSIT",
      sourceTable: "DIM_ACCOUNT",
      sourceColumn: "count(distinct ACCOUNT_NUMBER)",
      businessMeaning: "Total number of accounts held by customer",
      nullable: true,
    },
    {
      columnName: "ACC_AVERAGE_TENURE_YEARS",
      dataType: "FLOAT",
      sourceSchema: "CORE_DEPOSIT",
      sourceTable: "DIM_ACCOUNT",
      sourceColumn: "DATEDIFF(year, ACCOUNT_OPEN_DATE, CURRENT_DATE)",
      businessMeaning: "Average account tenure in years",
      nullable: true,
    },
    {
      columnName: "ACC_SAVINGS_ACC_CNT",
      dataType: "NUMBER(38,0)",
      sourceSchema: "CORE_DEPOSIT",
      sourceTable: "DIM_ACCOUNT",
      sourceColumn: "count(distinct ACCOUNT_NUMBER WHERE ACCOUNT_TYPE='SAV')",
      businessMeaning: "Count of active savings accounts",
      nullable: true,
    },
    {
      columnName: "ACC_CHECKING_ACC_CNT",
      dataType: "NUMBER(38,0)",
      sourceSchema: "CORE_DEPOSIT",
      sourceTable: "DIM_ACCOUNT",
      sourceColumn: "count(distinct ACCOUNT_NUMBER WHERE ACCOUNT_TYPE='CHK')",
      businessMeaning: "Count of active checking accounts",
      nullable: true,
    },
    {
      columnName: "ACC_CD_ACC_CNT",
      dataType: "NUMBER(38,0)",
      sourceSchema: "CORE_DEPOSIT",
      sourceTable: "DIM_ACCOUNT",
      sourceColumn: "count(distinct ACCOUNT_NUMBER WHERE ACCOUNT_TYPE='CD')",
      businessMeaning: "Count of active certificate of deposit accounts",
      nullable: true,
    },
    {
      columnName: "ACC_IRA_ACC_CNT",
      dataType: "NUMBER(38,0)",
      sourceSchema: "CORE_DEPOSIT",
      sourceTable: "DIM_ACCOUNT",
      sourceColumn: "count(distinct ACCOUNT_NUMBER WHERE ACCOUNT_TYPE='IRA')",
      businessMeaning: "Count of active IRA accounts",
      nullable: true,
    },
    {
      columnName: "ACC_SAVINGS_ACC_BAL",
      dataType: "FLOAT",
      sourceSchema: "CORE_DEPOSIT",
      sourceTable: "FCT_DEPOSIT_DAILY_BALANCE",
      sourceColumn: "sum(CURRENT_BALANCE WHERE ACCOUNT_TYPE='SAV')",
      businessMeaning: "Total balance across all savings accounts",
      nullable: true,
    },
    {
      columnName: "ACC_CHECKING_ACC_BAL",
      dataType: "FLOAT",
      sourceSchema: "CORE_DEPOSIT",
      sourceTable: "FCT_DEPOSIT_DAILY_BALANCE",
      sourceColumn: "sum(CURRENT_BALANCE WHERE ACCOUNT_TYPE='CHK')",
      businessMeaning: "Total balance across all checking accounts",
      nullable: true,
    },
    {
      columnName: "ACC_CD_ACC_BAL",
      dataType: "FLOAT",
      sourceSchema: "CORE_DEPOSIT",
      sourceTable: "FCT_DEPOSIT_DAILY_BALANCE",
      sourceColumn: "sum(CURRENT_BALANCE WHERE ACCOUNT_TYPE='CD')",
      businessMeaning: "Total balance across all CD accounts",
      nullable: true,
    },
    {
      columnName: "ACC_IRA_ACC_BAL",
      dataType: "FLOAT",
      sourceSchema: "CORE_DEPOSIT",
      sourceTable: "FCT_DEPOSIT_DAILY_BALANCE",
      sourceColumn: "sum(CURRENT_BALANCE WHERE ACCOUNT_TYPE='IRA')",
      businessMeaning: "Total balance across all IRA accounts",
      nullable: true,
    },
    {
      columnName: "ACC_SAVINGS_TO_ALL_ACC_RATIO",
      dataType: "FLOAT",
      sourceSchema: "ANALYTICS",
      sourceTable: "CALCULATED",
      sourceColumn: "ACC_SAVINGS_ACC_BAL / (ACC_SAVINGS_ACC_BAL + ACC_CHECKING_ACC_BAL + ACC_CD_ACC_BAL + ACC_IRA_ACC_BAL)",
      businessMeaning: "Ratio of savings account balance to total balance",
      nullable: true,
    },
    {
      columnName: "ACC_CHECKING_TO_ALL_ACC_RATIO",
      dataType: "FLOAT",
      sourceSchema: "ANALYTICS",
      sourceTable: "CALCULATED",
      sourceColumn: "ACC_CHECKING_ACC_BAL / (ACC_SAVINGS_ACC_BAL + ACC_CHECKING_ACC_BAL + ACC_CD_ACC_BAL + ACC_IRA_ACC_BAL)",
      businessMeaning: "Ratio of checking account balance to total balance",
      nullable: true,
    },
    {
      columnName: "ACC_CD_TO_ALL_ACC_RATIO",
      dataType: "FLOAT",
      sourceSchema: "ANALYTICS",
      sourceTable: "CALCULATED",
      sourceColumn: "ACC_CD_ACC_BAL / (ACC_SAVINGS_ACC_BAL + ACC_CHECKING_ACC_BAL + ACC_CD_ACC_BAL + ACC_IRA_ACC_BAL)",
      businessMeaning: "Ratio of CD account balance to total balance",
      nullable: true,
    },
    {
      columnName: "ACC_IRA_TO_ALL_ACC_RATIO",
      dataType: "FLOAT",
      sourceSchema: "ANALYTICS",
      sourceTable: "CALCULATED",
      sourceColumn: "ACC_IRA_ACC_BAL / (ACC_SAVINGS_ACC_BAL + ACC_CHECKING_ACC_BAL + ACC_CD_ACC_BAL + ACC_IRA_ACC_BAL)",
      businessMeaning: "Ratio of IRA account balance to total balance",
      nullable: true,
    },
    {
      columnName: "ACC_ACCOUNTS_CLOSED_12M",
      dataType: "NUMBER(38,0)",
      sourceSchema: "CORE_DEPOSIT",
      sourceTable: "DIM_ACCOUNT",
      sourceColumn: "count(distinct ACCOUNT_NUMBER WHERE ACCOUNT_CLOSED_DATE >= DATEADD(month, -12, CURRENT_DATE))",
      businessMeaning: "Number of accounts closed in last 12 months",
      nullable: true,
    },
    {
      columnName: "ACC_CURRENT_LEDGER_BALANCE",
      dataType: "FLOAT",
      sourceSchema: "CORE_DEPOSIT",
      sourceTable: "FCT_DEPOSIT_DAILY_BALANCE",
      sourceColumn: "sum(ledger_balance)",
      businessMeaning: "Current ledger balance across all accounts",
      nullable: true,
    },
    {
      columnName: "ACC_AVAILABLE_BALANCE",
      dataType: "FLOAT",
      sourceSchema: "CORE_DEPOSIT",
      sourceTable: "FCT_DEPOSIT_DAILY_BALANCE",
      sourceColumn: "sum(AVAILABLE_BALANCE)",
      businessMeaning: "Current available balance across all accounts",
      nullable: true,
    },
    {
      columnName: "ACC_OVERDRAFT_LIMIT",
      dataType: "FLOAT",
      sourceSchema: "CORE_DEPOSIT",
      sourceTable: "DIM_ACCOUNT",
      sourceColumn: "sum(OVERDRAFT_LIMIT)",
      businessMeaning: "Total overdraft limit across accounts",
      nullable: true,
    },
    {
      columnName: "ACC_AVERAGE_DAILY_BALANCE_90D",
      dataType: "FLOAT",
      sourceSchema: "CORE_DEPOSIT",
      sourceTable: "FCT_DEPOSIT_DAILY_BALANCE",
      sourceColumn: "avg(CURRENT_BALANCE) OVER (PARTITION BY ACCOUNT_NUMBER ORDER BY BALANCE_DATE ROWS BETWEEN 89 PRECEDING AND CURRENT ROW)",
      businessMeaning: "Average daily balance over last 90 days",
      nullable: true,
    },
    {
      columnName: "ACC_HIGHEST_BALANCE_6M",
      dataType: "FLOAT",
      sourceSchema: "CORE_DEPOSIT",
      sourceTable: "FCT_DEPOSIT_DAILY_BALANCE",
      sourceColumn: "max(CURRENT_BALANCE) OVER (PARTITION BY ACCOUNT_NUMBER ORDER BY BALANCE_DATE ROWS BETWEEN 180 PRECEDING AND CURRENT ROW)",
      businessMeaning: "Highest balance in last 6 months",
      nullable: true,
    },
    {
      columnName: "CUST_MULTI_ACCOUNT_HOLDER_FLAG",
      dataType: "NUMBER(38,0)",
      sourceSchema: "CORE_DEPOSIT",
      sourceTable: "DIM_ACCOUNT",
      sourceColumn: "CASE WHEN count(distinct ACCOUNT_NUMBER) > 1 THEN 1 ELSE 0 END",
      businessMeaning: "Flag indicating if customer holds multiple accounts",
      nullable: true,
    },
    {
      columnName: "CUST_AVG_PRODUCTS_OWNED",
      dataType: "NUMBER(38,0)",
      sourceSchema: "ANALYTICS",
      sourceTable: "CALCULATED",
      sourceColumn: "ACC_TOTAL_ACCOUNTS / COUNT(DISTINCT PRODUCT_TYPE)",
      businessMeaning: "Average products owned per account",
      nullable: true,
    },
    {
      columnName: "ACC_MAX_BALANCE_90D",
      dataType: "FLOAT",
      sourceSchema: "CORE_DEPOSIT",
      sourceTable: "FCT_DEPOSIT_DAILY_BALANCE",
      sourceColumn: "max(CURRENT_BALANCE) OVER (PARTITION BY ACCOUNT_NUMBER ORDER BY BALANCE_DATE ROWS BETWEEN 89 PRECEDING AND CURRENT ROW)",
      businessMeaning: "Maximum balance in last 90 days",
      nullable: true,
    },
    {
      columnName: "ACC_MIN_BALANCE_90D",
      dataType: "FLOAT",
      sourceSchema: "CORE_DEPOSIT",
      sourceTable: "FCT_DEPOSIT_DAILY_BALANCE",
      sourceColumn: "min(CURRENT_BALANCE) OVER (PARTITION BY ACCOUNT_NUMBER ORDER BY BALANCE_DATE ROWS BETWEEN 89 PRECEDING AND CURRENT ROW)",
      businessMeaning: "Minimum balance in last 90 days",
      nullable: true,
    },
    {
      columnName: "ACC_MEDIAN_BALANCE_90D",
      dataType: "FLOAT",
      sourceSchema: "CORE_DEPOSIT",
      sourceTable: "FCT_DEPOSIT_DAILY_BALANCE",
      sourceColumn: "PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY CURRENT_BALANCE) OVER (PARTITION BY ACCOUNT_NUMBER ORDER BY BALANCE_DATE ROWS BETWEEN 89 PRECEDING AND CURRENT ROW)",
      businessMeaning: "Median balance in last 90 days",
      nullable: true,
    },
    {
      columnName: "ACC_LEDGER_BALANCE",
      dataType: "FLOAT",
      sourceSchema: "CORE_DEPOSIT",
      sourceTable: "FCT_DEPOSIT_DAILY_BALANCE",
      sourceColumn: "LGR_BAL_AMT",
      businessMeaning: "Current ledger balance for account",
      nullable: true,
    },
    {
      columnName: "ACC_ACCOUNT_CNT",
      dataType: "NUMBER(38,0)",
      sourceSchema: "CORE_DEPOSIT",
      sourceTable: "DIM_ACCOUNT",
      sourceColumn: "count(distinct ACCOUNT_NUMBER WHERE RECORD_FLAG='A')",
      businessMeaning: "Count of active accounts",
      nullable: true,
    },
    {
      columnName: "ACC_CLOSED_ACCOUNT_CNT",
      dataType: "NUMBER(38,0)",
      sourceSchema: "CORE_DEPOSIT",
      sourceTable: "DIM_ACCOUNT",
      sourceColumn: "count(distinct ACCOUNT_NUMBER WHERE RECORD_FLAG='I')",
      businessMeaning: "Count of closed/inactive accounts",
      nullable: true,
    },
    // DEPOSIT-SPECIFIC METRICS
    {
      columnName: "DP_CD_ACCOUNT_CNT",
      dataType: "NUMBER(38,0)",
      sourceSchema: "CORE_DEPOSIT",
      sourceTable: "DIM_ACCOUNT",
      sourceColumn: "count(distinct ACCOUNT_NUMBER WHERE DEPOSIT_CATEGORY='C')",
      businessMeaning: "Count of certificate of deposit accounts",
      nullable: true,
    },
    {
      columnName: "DP_CD_TOTAL_BALANCE",
      dataType: "FLOAT",
      sourceSchema: "CORE_DEPOSIT",
      sourceTable: "FCT_DEPOSIT_DAILY_BALANCE",
      sourceColumn: "sum(current_balance WHERE DEPOSIT_CATEGORY='C')",
      businessMeaning: "Total balance in CD accounts",
      nullable: true,
    },
    {
      columnName: "DP_HIGH_YIELD_SAVINGS_BALANCE",
      dataType: "FLOAT",
      sourceSchema: "CORE_DEPOSIT",
      sourceTable: "FCT_DEPOSIT_DAILY_BALANCE",
      sourceColumn: "sum(CURRENT_BALANCE WHERE ACCOUNT_TYPE='HYS')",
      businessMeaning: "Balance in high-yield savings accounts",
      nullable: true,
    },
    {
      columnName: "DP_HIGH_YIELD_SAVINGS_CNT",
      dataType: "NUMBER(38,0)",
      sourceSchema: "CORE_DEPOSIT",
      sourceTable: "DIM_ACCOUNT",
      sourceColumn: "count(distinct ACCOUNT_NUMBER WHERE ACCOUNT_TYPE='HYS')",
      businessMeaning: "Count of high-yield savings accounts",
      nullable: true,
    },
    {
      columnName: "DP_NEXT_CD_MATURITY_DATE",
      dataType: "DATE",
      sourceSchema: "CORE_DEPOSIT",
      sourceTable: "DIM_DEPOSIT",
      sourceColumn: "min(ACCOUNT_TD_NEXT_MATURITY_DATE WHERE ACCOUNT_TD_NEXT_MATURITY_DATE >= CURRENT_DATE)",
      businessMeaning: "Next CD maturity date",
      nullable: true,
    },
    {
      columnName: "DP_NEXT_CD_MATURITY_BALANCE",
      dataType: "FLOAT",
      sourceSchema: "CORE_DEPOSIT",
      sourceTable: "DIM_DEPOSIT",
      sourceColumn: "ACCOUNT_TD_ORIGINAL_BALANCE WHERE ACCOUNT_TD_NEXT_MATURITY_DATE = MIN_MATURITY_DATE",
      businessMeaning: "Balance of next maturing CD",
      nullable: true,
    },
    {
      columnName: "DP_CD_RETENTION_SEGMENT",
      dataType: "NUMBER(38,0)",
      sourceSchema: "ANALYTICS",
      sourceTable: "CALCULATED",
      sourceColumn: "CASE WHEN DP_CD_TOTAL_BALANCE > 100000 THEN 1 WHEN DP_CD_TOTAL_BALANCE > 50000 THEN 2 ELSE 3 END",
      businessMeaning: "CD retention segment (1=High, 2=Medium, 3=Low)",
      nullable: true,
    },
    {
      columnName: "DP_TOTAL_AMOUNT_12M",
      dataType: "FLOAT",
      sourceSchema: "CORE_DEPOSIT",
      sourceTable: "FCT_DEPOSIT_ACCOUNT_TRANSACTION",
      sourceColumn: "sum(TRANSACTION_AMOUNT) WHERE TRANSACTION_DATE >= DATEADD(month, -12, CURRENT_DATE)",
      businessMeaning: "Total deposit transaction amount in last 12 months",
      nullable: true,
    },
    {
      columnName: "DP_TRANSACTION_COUNT_12M",
      dataType: "NUMBER(38,0)",
      sourceSchema: "CORE_DEPOSIT",
      sourceTable: "FCT_DEPOSIT_ACCOUNT_TRANSACTION",
      sourceColumn: "count(distinct transaction_id) WHERE TRANSACTION_DATE >= DATEADD(month, -12, CURRENT_DATE)",
      businessMeaning: "Count of transactions in last 12 months",
      nullable: true,
    },
    {
      columnName: "DP_MEDIAN_SINGLE_DEPOSIT",
      dataType: "FLOAT",
      sourceSchema: "CORE_DEPOSIT",
      sourceTable: "FCT_DEPOSIT_ACCOUNT_TRANSACTION",
      sourceColumn: "PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY TRANSACTION_AMOUNT) WHERE TRANSACTION_DATE >= DATEADD(month, -12, CURRENT_DATE)",
      businessMeaning: "Median single deposit amount in last 12 months",
      nullable: true,
    },
    {
      columnName: "DP_HIGH_VALUE_INDICATOR",
      dataType: "NUMBER(38,0)",
      sourceSchema: "ANALYTICS",
      sourceTable: "CALCULATED",
      sourceColumn: "CASE WHEN ACC_CURRENT_LEDGER_BALANCE > 500000 THEN 1 ELSE 0 END",
      businessMeaning: "Flag for high-value customer ($500K+)",
      nullable: true,
    },
    {
      columnName: "DP_DAYS_SINCE_LAST_DEPOSIT",
      dataType: "NUMBER(38,0)",
      sourceSchema: "CORE_DEPOSIT",
      sourceTable: "FCT_DEPOSIT_ACCOUNT_TRANSACTION",
      sourceColumn: "DATEDIFF(day, max(TRANSACTION_DATE), CURRENT_DATE)",
      businessMeaning: "Days since last deposit transaction",
      nullable: true,
    },
    {
      columnName: "DP_AVERAGE_DEPOSITS_PER_MONTH_6M",
      dataType: "FLOAT",
      sourceSchema: "CORE_DEPOSIT",
      sourceTable: "FCT_DEPOSIT_ACCOUNT_TRANSACTION",
      sourceColumn: "count(distinct transaction_id) / 6 WHERE TRANSACTION_DATE >= DATEADD(month, -6, CURRENT_DATE)",
      businessMeaning: "Average deposits per month over 6 months",
      nullable: true,
    },
    {
      columnName: "DP_MONTHLY_AMOUNT_VOLATILITY_6M",
      dataType: "FLOAT",
      sourceSchema: "ANALYTICS",
      sourceTable: "CALCULATED",
      sourceColumn: "STDDEV(monthly_deposit_amounts) OVER (PARTITION BY CUSTOMER_NUMBER ORDER BY MONTH ROWS BETWEEN 5 PRECEDING AND CURRENT ROW)",
      businessMeaning: "Standard deviation of monthly deposit amounts",
      nullable: true,
    },
    {
      columnName: "DP_PREFERRED_CHANNEL",
      dataType: "VARCHAR(50)",
      sourceSchema: "CORE_DEPOSIT",
      sourceTable: "FCT_DEPOSIT_ACCOUNT_TRANSACTION",
      sourceColumn: "MODE(TRANSACTION_SOURCE_CODE)",
      businessMeaning: "Customer's most-used deposit channel",
      nullable: true,
    },
    {
      columnName: "DP_HIGH_VALUE_CHANNEL",
      dataType: "VARCHAR(50)",
      sourceSchema: "CORE_DEPOSIT",
      sourceTable: "FCT_DEPOSIT_ACCOUNT_TRANSACTION",
      sourceColumn: "MODE(TRANSACTION_SOURCE_CODE WHERE TRANSACTION_AMOUNT > PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY TRANSACTION_AMOUNT))",
      businessMeaning: "Channel used for highest value deposits",
      nullable: true,
    },
    {
      columnName: "DP_BRANCH_TO_DIGITAL_RATIO",
      dataType: "FLOAT",
      sourceSchema: "ANALYTICS",
      sourceTable: "CALCULATED",
      sourceColumn: "count(TRANSACTION_SOURCE_CODE='BRANCH') / count(TRANSACTION_SOURCE_CODE='DIGITAL')",
      businessMeaning: "Ratio of branch to digital transactions",
      nullable: true,
    },
    {
      columnName: "DP_PRIMARY_DEPOSIT_TYPE",
      dataType: "VARCHAR(50)",
      sourceSchema: "CORE_DEPOSIT",
      sourceTable: "FCT_DEPOSIT_ACCOUNT_TRANSACTION",
      sourceColumn: "MODE(TRANSACTION_CODE WHERE DEBIT_CREDIT_INDICATOR='C')",
      businessMeaning: "Most common type of deposit",
      nullable: true,
    },
    {
      columnName: "DP_DIRECT_PAYROLL_SHARE",
      dataType: "FLOAT",
      sourceSchema: "CORE_DEPOSIT",
      sourceTable: "FCT_DEPOSIT_ACCOUNT_TRANSACTION",
      sourceColumn: "sum(TRANSACTION_AMOUNT WHERE TRANSACTION_CODE='PAYROLL') / sum(TRANSACTION_AMOUNT)",
      businessMeaning: "Percentage of deposits from payroll",
      nullable: true,
    },
    {
      columnName: "DP_BALANCE_CHANGE_LAST_90D_PCT",
      dataType: "FLOAT",
      sourceSchema: "ANALYTICS",
      sourceTable: "CALCULATED",
      sourceColumn: "(ACC_CURRENT_LEDGER_BALANCE - LAG(ACC_CURRENT_LEDGER_BALANCE, 90)) / LAG(ACC_CURRENT_LEDGER_BALANCE, 90) * 100",
      businessMeaning: "Percentage change in balance over last 90 days",
      nullable: true,
    },
    {
      columnName: "DP_RETAINED_AFTER_30D_PCT",
      dataType: "FLOAT",
      sourceSchema: "ANALYTICS",
      sourceTable: "CALCULATED",
      sourceColumn: "sum(TRANSACTION_AMOUNT WHERE TRANSACTION_DATE <= DATEADD(day, 30, first_deposit_date)) / sum(TRANSACTION_AMOUNT WHERE TRANSACTION_DATE >= first_deposit_date)",
      businessMeaning: "Percentage of deposits retained after 30 days",
      nullable: true,
    },
    {
      columnName: "DP_WITHDRAWAL_WITHIN_30D_RATIO",
      dataType: "FLOAT",
      sourceSchema: "CORE_DEPOSIT",
      sourceTable: "FCT_DEPOSIT_ACCOUNT_TRANSACTION",
      sourceColumn: "count(TRANSACTION_CODE='WITHDRAWAL' WHERE TRANSACTION_DATE <= DATEADD(day, 30, DEPOSIT_DATE)) / count(distinct DEPOSIT_DATE)",
      businessMeaning: "Ratio of withdrawals within 30 days of deposit",
      nullable: true,
    },
    {
      columnName: "DP_SALARY_SPENT_WITHIN_10D_PCT",
      dataType: "FLOAT",
      sourceSchema: "ANALYTICS",
      sourceTable: "CALCULATED",
      sourceColumn: "sum(DEBIT_AMOUNT WHERE TRANSACTION_DATE <= DATEADD(day, 10, PAYROLL_DATE)) / sum(PAYROLL_AMOUNT) * 100",
      businessMeaning: "Percentage of salary spent within 10 days",
      nullable: true,
    },
    {
      columnName: "DP_AVERAGE_DAYS_ON_BOOK",
      dataType: "FLOAT",
      sourceSchema: "ANALYTICS",
      sourceTable: "CALCULATED",
      sourceColumn: "avg(DATEDIFF(day, DEPOSIT_DATE, WITHDRAWAL_DATE))",
      businessMeaning: "Average number of days funds stay in account",
      nullable: true,
    },
    {
      columnName: "DP_REDEPOSIT_WITHIN_60D_PCT",
      dataType: "FLOAT",
      sourceSchema: "ANALYTICS",
      sourceTable: "CALCULATED",
      sourceColumn: "count(distinct DEPOSIT_DATE WHERE NEXT_DEPOSIT_DATE <= DATEADD(day, 60, PREVIOUS_WITHDRAWAL_DATE)) / count(distinct WITHDRAWAL_DATE) * 100",
      businessMeaning: "Percentage of withdrawals followed by redeposit within 60 days",
      nullable: true,
    },
    {
      columnName: "DP_TO_INVESTMENT_CONVERSION_PCT",
      dataType: "FLOAT",
      sourceSchema: "ANALYTICS",
      sourceTable: "CALCULATED",
      sourceColumn: "CASE WHEN HAS_INVESTMENT_ACCOUNT=1 THEN 100 ELSE 0 END",
      businessMeaning: "Indicator if customer has investments (0/100)",
      nullable: true,
    },
    {
      columnName: "DP_CD_AVERAGE_TENOR_MONTHS",
      dataType: "FLOAT",
      sourceSchema: "ANALYTICS",
      sourceTable: "CALCULATED",
      sourceColumn: "avg(DATEDIFF(month, ACCOUNT_OPEN_DATE, ACCOUNT_TD_MATURITY_DATE))",
      businessMeaning: "Average CD term in months",
      nullable: true,
    },
    {
      columnName: "DP_OVERDRAFT_FEES_12M",
      dataType: "FLOAT",
      sourceSchema: "CORE_DEPOSIT",
      sourceTable: "FCT_DEPOSIT_DAILY_BALANCE",
      sourceColumn: "sum(FEE_AMOUNT WHERE FEE_TYPE='OVERDRAFT') WHERE TRANSACTION_DATE >= DATEADD(month, -12, CURRENT_DATE)",
      businessMeaning: "Total overdraft fees in last 12 months",
      nullable: true,
    },
    {
      columnName: "DP_CONFIRMED_FRAUD_INCIDENTS_12M",
      dataType: "NUMBER(38,0)",
      sourceSchema: "ANALYTICS",
      sourceTable: "FRAUD_DETECTION",
      sourceColumn: "count(distinct incident_id WHERE fraud_confirmed=1 AND incident_date >= DATEADD(month, -12, CURRENT_DATE))",
      businessMeaning: "Count of confirmed fraud incidents in last 12 months",
      nullable: true,
    },
    {
      columnName: "DP_DEPOSIT_CHURN_INDICATOR",
      dataType: "NUMBER(38,0)",
      sourceSchema: "ANALYTICS",
      sourceTable: "CALCULATED",
      sourceColumn: "CASE WHEN DP_DAYS_SINCE_LAST_DEPOSIT > 180 THEN 1 ELSE 0 END",
      businessMeaning: "Flag indicating potential deposit churn",
      nullable: true,
    },
    // WITHDRAWAL & CASH FLOW
    {
      columnName: "WD_DAYS_SINCE_LAST_WITHDRAWAL",
      dataType: "NUMBER(38,0)",
      sourceSchema: "CORE_DEPOSIT",
      sourceTable: "FCT_DEPOSIT_ACCOUNT_TRANSACTION",
      sourceColumn: "DATEDIFF(day, max(TRANSACTION_DATE WHERE DEBIT_CREDIT_INDICATOR='D'), CURRENT_DATE)",
      businessMeaning: "Days since last withdrawal",
      nullable: true,
    },
    {
      columnName: "WD_PREFERRED_WITHDRAWAL_CHANNEL",
      dataType: "VARCHAR(50)",
      sourceSchema: "CORE_DEPOSIT",
      sourceTable: "FCT_DEPOSIT_ACCOUNT_TRANSACTION",
      sourceColumn: "MODE(TRANSACTION_SOURCE_CODE WHERE DEBIT_CREDIT_INDICATOR='D')",
      businessMeaning: "Customer's preferred withdrawal channel",
      nullable: true,
    },
    {
      columnName: "WD_HIGH_VALUE_WITHDRAWAL_CHANNEL",
      dataType: "VARCHAR(50)",
      sourceSchema: "CORE_DEPOSIT",
      sourceTable: "FCT_DEPOSIT_ACCOUNT_TRANSACTION",
      sourceColumn: "MODE(TRANSACTION_SOURCE_CODE WHERE DEBIT_CREDIT_INDICATOR='D' AND TRANSACTION_AMOUNT > PERCENTILE_CONT(0.75))",
      businessMeaning: "Channel used for high-value withdrawals",
      nullable: true,
    },
    {
      columnName: "CASH_NET_FLOW_LAST_3M",
      dataType: "FLOAT",
      sourceSchema: "CORE_DEPOSIT",
      sourceTable: "FCT_DEPOSIT_ACCOUNT_TRANSACTION",
      sourceColumn: "sum(CASE WHEN DEBIT_CREDIT_INDICATOR='C' THEN TRANSACTION_AMOUNT ELSE -TRANSACTION_AMOUNT END) WHERE TRANSACTION_DATE >= DATEADD(month, -3, CURRENT_DATE)",
      businessMeaning: "Net cash flow (inflows - outflows) in last 3 months",
      nullable: true,
    },
    // DEMOGRAPHICS
    {
      columnName: "DG_AGE_BRACKET_CODE",
      dataType: "VARCHAR(10)",
      sourceSchema: "CORE_CUSTOMERS",
      sourceTable: "DIM_CUSTOMER_ATTRIBUTE",
      sourceColumn: "CASE WHEN BIRTH_DATE >= DATEADD(year, -30, CURRENT_DATE) THEN '18-30' WHEN BIRTH_DATE >= DATEADD(year, -50, CURRENT_DATE) THEN '31-50' ELSE '50+' END",
      businessMeaning: "Age bracket classification",
      nullable: true,
    },
    {
      columnName: "DG_EDUCATION_LEVEL_CODE",
      dataType: "NUMBER(38,0)",
      sourceSchema: "CORE_CUSTOMERS",
      sourceTable: "DIM_CUSTOMER_DEMOGRAPHY",
      sourceColumn: "EDUCATION_CODE",
      businessMeaning: "Education level code",
      nullable: true,
    },
    {
      columnName: "DG_MARITAL_STATUS_CODE",
      dataType: "NUMBER(38,0)",
      sourceSchema: "CORE_CUSTOMERS",
      sourceTable: "DIM_CUSTOMER_DEMOGRAPHY",
      sourceColumn: "MARITAL_STATUS_CODE",
      businessMeaning: "Marital status code",
      nullable: true,
    },
  ],
};

// Re-export dimensions and facts for compatibility with metadata
export const customerGoldDimensions = [];

export const customerGoldFacts = [customerDepositAggrTable];

export const customerGoldLayerComplete = {
  dimensions: customerGoldDimensions,
  facts: customerGoldFacts,
  tables: [customerDepositAggrTable],
  totalTables: 1,
  totalDimensions: customerGoldDimensions.length,
  totalFacts: customerGoldFacts.length,
  description: "Customer domain gold layer - Aggregated analytics table with comprehensive customer and deposit metrics",
};

export default customerGoldLayerComplete;
