// DIM_CUSTOMER_ADDRESS - Complete STTM Mapping
// Source: STTM Excel - CORE_CUSTOMERS schema
// 24 columns total
// Sources: FIS-ADS (TB_CI_OZ5_CUST_NAAD_ARD_RAW) and FIS-DDW (TB_CI_DZY_C2_CUST_SCD_DIM_RAW)

export interface ColumnMapping {
  sourceSystem: string;
  sourceTable: string;
  sourceColumn: string;
  bronzeSchema: string;
  bronzeTable: string;
  bronzeColumn: string;
  silverSchema: string;
  silverTable: string;
  silverColumn: string;
  goldSchema: string;
  goldTable: string;
  goldColumn: string | null;
  dataType: string;
  businessLogic: string;
  businessMeaning: string;
  mappingType?: "Direct" | "Derived" | "System" | "SCD2";
}

export const dimCustomerAddressMappings: ColumnMapping[] = [
  {
    sourceSystem: "SYSTEM",
    sourceTable: "N/A",
    sourceColumn: "AUTO_GENERATED",
    bronzeSchema: "N/A",
    bronzeTable: "N/A",
    bronzeColumn: "N/A",
    silverSchema: "CORE_CUSTOMERS",
    silverTable: "DIM_CUSTOMER_ADDRESS",
    silverColumn: "CUSTOMER_SK",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "NUMBER(38,0)",
    businessLogic: "Auto-generated surrogate key sequence",
    businessMeaning: "Surrogate key for customer address dimension",
    mappingType: "System",
  },
  {
    sourceSystem: "SYSTEM",
    sourceTable: "N/A",
    sourceColumn: "DERIVED_FK",
    bronzeSchema: "N/A",
    bronzeTable: "N/A",
    bronzeColumn: "N/A",
    silverSchema: "CORE_CUSTOMERS",
    silverTable: "DIM_CUSTOMER_ADDRESS",
    silverColumn: "CUSTOMER_NUMBER_FK",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "NUMBER(38,0)",
    businessLogic: "Foreign key lookup to DIM_CUSTOMER",
    businessMeaning: "Customer dimension foreign key reference",
    mappingType: "Derived",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_CI_OZ5_CUST_NAAD_ARD_RAW",
    sourceColumn: "CID_NAAD_APPL_ID",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_CI_OZ5_CUST_NAAD_ARD_RAW",
    bronzeColumn: "CID_NAAD_APPL_ID",
    silverSchema: "CORE_CUSTOMERS",
    silverTable: "DIM_CUSTOMER_ADDRESS",
    silverColumn: "CUSTOMER_NUMBER",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "VARCHAR(16777216)",
    businessLogic: "1:1 mapping from FIS-ADS, also from FIS-DDW as CUST_CIS_NBR",
    businessMeaning: "Unique customer identifier number",
    mappingType: "Direct",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_CI_OZ5_CUST_NAAD_ARD_RAW",
    sourceColumn: "CID_NAAD_ADDR_TYPE_CDE",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_CI_OZ5_CUST_NAAD_ARD_RAW",
    bronzeColumn: "CID_NAAD_ADDR_TYPE_CDE",
    silverSchema: "CORE_CUSTOMERS",
    silverTable: "DIM_CUSTOMER_ADDRESS",
    silverColumn: "ADDRESS_TYPE_CODE",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "VARCHAR(16777216)",
    businessLogic: "1:1 mapping (H=Home, B=Business, M=Mailing), also from FIS-DDW as ADDR_TYP_CDE",
    businessMeaning: "Address type classification code",
    mappingType: "Direct",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_CI_OZ5_CUST_NAAD_ARD_RAW",
    sourceColumn: "CID_NAAD_ADDR_TYPE_CDE",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_CI_OZ5_CUST_NAAD_ARD_RAW",
    bronzeColumn: "CID_NAAD_ADDR_TYPE_CDE",
    silverSchema: "CORE_CUSTOMERS",
    silverTable: "DIM_CUSTOMER_ADDRESS",
    silverColumn: "ADDRESS_TYPE_DESC",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "VARCHAR(16777216)",
    businessLogic: "Derived description from code mapping (Home, Business, Mailing, etc.)",
    businessMeaning: "Address type description",
    mappingType: "Derived",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_CI_OZ5_CUST_NAAD_ARD_RAW",
    sourceColumn: "CID_NAAD_ADDR_LINE_1",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_CI_OZ5_CUST_NAAD_ARD_RAW",
    bronzeColumn: "CID_NAAD_ADDR_LINE_1",
    silverSchema: "CORE_CUSTOMERS",
    silverTable: "DIM_CUSTOMER_ADDRESS",
    silverColumn: "ADDRESS_LINE_1",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "VARCHAR(16777216)",
    businessLogic: "1:1 mapping with INITCAP(TRIM()), also from FIS-DDW as ADDR_1_TXT (PII - masked)",
    businessMeaning: "First line of customer address (PII - masked for security)",
    mappingType: "Direct",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_CI_OZ5_CUST_NAAD_ARD_RAW",
    sourceColumn: "CID_NAAD_ADDR_LINE_2",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_CI_OZ5_CUST_NAAD_ARD_RAW",
    bronzeColumn: "CID_NAAD_ADDR_LINE_2",
    silverSchema: "CORE_CUSTOMERS",
    silverTable: "DIM_CUSTOMER_ADDRESS",
    silverColumn: "ADDRESS_LINE_2",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "VARCHAR(16777216)",
    businessLogic: "1:1 mapping with INITCAP(TRIM()), also from FIS-DDW as ADDR_2_TXT (PII - masked)",
    businessMeaning: "Second line of customer address (PII - masked for security)",
    mappingType: "Direct",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_CI_OZ5_CUST_NAAD_ARD_RAW",
    sourceColumn: "CID_NAAD_ADDR_LINE_3",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_CI_OZ5_CUST_NAAD_ARD_RAW",
    bronzeColumn: "CID_NAAD_ADDR_LINE_3",
    silverSchema: "CORE_CUSTOMERS",
    silverTable: "DIM_CUSTOMER_ADDRESS",
    silverColumn: "ADDRESS_LINE_3",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "VARCHAR(16777216)",
    businessLogic: "1:1 mapping with INITCAP(TRIM()), also from FIS-DDW as ADDR_3_TXT",
    businessMeaning: "Third line of customer address",
    mappingType: "Direct",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_CI_OZ5_CUST_NAAD_ARD_RAW",
    sourceColumn: "CID_NAAD_CITY",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_CI_OZ5_CUST_NAAD_ARD_RAW",
    bronzeColumn: "CID_NAAD_CITY",
    silverSchema: "CORE_CUSTOMERS",
    silverTable: "DIM_CUSTOMER_ADDRESS",
    silverColumn: "CITY",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "VARCHAR(16777216)",
    businessLogic: "1:1 mapping with INITCAP(TRIM()), also from FIS-DDW as CTY_NME",
    businessMeaning: "City name",
    mappingType: "Direct",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_CI_OZ5_CUST_NAAD_ARD_RAW",
    sourceColumn: "CID_NAAD_STATE_CDE",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_CI_OZ5_CUST_NAAD_ARD_RAW",
    bronzeColumn: "CID_NAAD_STATE_CDE",
    silverSchema: "CORE_CUSTOMERS",
    silverTable: "DIM_CUSTOMER_ADDRESS",
    silverColumn: "STATE_CODE",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "VARCHAR(16777216)",
    businessLogic: "1:1 mapping (2-letter state code), also from FIS-DDW as ST_CDE",
    businessMeaning: "State code (US 2-letter abbreviation)",
    mappingType: "Direct",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_CI_OZ5_CUST_NAAD_ARD_RAW",
    sourceColumn: "CID_NAAD_STATE_CDE",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_CI_OZ5_CUST_NAAD_ARD_RAW",
    bronzeColumn: "CID_NAAD_STATE_CDE",
    silverSchema: "CORE_CUSTOMERS",
    silverTable: "DIM_CUSTOMER_ADDRESS",
    silverColumn: "STATE_NAME",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "VARCHAR(16777216)",
    businessLogic: "Derived from STATE_CODE lookup to state reference table",
    businessMeaning: "Full state name",
    mappingType: "Derived",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_CI_OZ5_CUST_NAAD_ARD_RAW",
    sourceColumn: "CID_NAAD_ZIP_CDE",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_CI_OZ5_CUST_NAAD_ARD_RAW",
    bronzeColumn: "CID_NAAD_ZIP_CDE",
    silverSchema: "CORE_CUSTOMERS",
    silverTable: "DIM_CUSTOMER_ADDRESS",
    silverColumn: "ZIP_CODE",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "VARCHAR(16777216)",
    businessLogic: "1:1 mapping (5 or 9 digit ZIP), also from FIS-DDW as ZIP_CDE",
    businessMeaning: "ZIP/Postal code",
    mappingType: "Direct",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_CI_OZ5_CUST_NAAD_ARD_RAW",
    sourceColumn: "CID_NAAD_ZIP_PLUS_4",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_CI_OZ5_CUST_NAAD_ARD_RAW",
    bronzeColumn: "CID_NAAD_ZIP_PLUS_4",
    silverSchema: "CORE_CUSTOMERS",
    silverTable: "DIM_CUSTOMER_ADDRESS",
    silverColumn: "ZIP_PLUS_4",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "VARCHAR(16777216)",
    businessLogic: "1:1 mapping (4-digit ZIP extension), also from FIS-DDW as ZIP_PLS_4_CDE",
    businessMeaning: "ZIP+4 extension code",
    mappingType: "Direct",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_CI_OZ5_CUST_NAAD_ARD_RAW",
    sourceColumn: "CID_NAAD_COUNTRY_CDE",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_CI_OZ5_CUST_NAAD_ARD_RAW",
    bronzeColumn: "CID_NAAD_COUNTRY_CDE",
    silverSchema: "CORE_CUSTOMERS",
    silverTable: "DIM_CUSTOMER_ADDRESS",
    silverColumn: "COUNTRY_CODE",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "VARCHAR(16777216)",
    businessLogic: "1:1 mapping (ISO 2-letter country code), also from FIS-DDW as CNTRY_CDE",
    businessMeaning: "Country code (ISO 3166-1 alpha-2)",
    mappingType: "Direct",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_CI_OZ5_CUST_NAAD_ARD_RAW",
    sourceColumn: "CID_NAAD_COUNTRY_CDE",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_CI_OZ5_CUST_NAAD_ARD_RAW",
    bronzeColumn: "CID_NAAD_COUNTRY_CDE",
    silverSchema: "CORE_CUSTOMERS",
    silverTable: "DIM_CUSTOMER_ADDRESS",
    silverColumn: "COUNTRY_NAME",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "VARCHAR(16777216)",
    businessLogic: "Derived from COUNTRY_CODE lookup to country reference table",
    businessMeaning: "Full country name",
    mappingType: "Derived",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_CI_OZ5_CUST_NAAD_ARD_RAW",
    sourceColumn: "CID_NAAD_ADDR_LAST_CHG_DTE",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_CI_OZ5_CUST_NAAD_ARD_RAW",
    bronzeColumn: "CID_NAAD_ADDR_LAST_CHG_DTE",
    silverSchema: "CORE_CUSTOMERS",
    silverTable: "DIM_CUSTOMER_ADDRESS",
    silverColumn: "EFFECTIVE_START_DATE",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "TIMESTAMP_NTZ(9)",
    businessLogic: "SCD2 effective start date from last address change date, also from FIS-DDW as EFF_DTE",
    businessMeaning: "Date this address version became effective",
    mappingType: "SCD2",
  },
  {
    sourceSystem: "SYSTEM",
    sourceTable: "N/A",
    sourceColumn: "SCD2_LOGIC",
    bronzeSchema: "N/A",
    bronzeTable: "N/A",
    bronzeColumn: "N/A",
    silverSchema: "CORE_CUSTOMERS",
    silverTable: "DIM_CUSTOMER_ADDRESS",
    silverColumn: "EFFECTIVE_END_DATE",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "TIMESTAMP_NTZ(9)",
    businessLogic: "COALESCE(LEAD(EFFECTIVE_START_DATE) OVER (PARTITION BY CUSTOMER_NUMBER ORDER BY EFFECTIVE_START_DATE), '9999-12-31')",
    businessMeaning: "Date this address version expired (9999-12-31 for current)",
    mappingType: "SCD2",
  },
  {
    sourceSystem: "SYSTEM",
    sourceTable: "N/A",
    sourceColumn: "DERIVED",
    bronzeSchema: "N/A",
    bronzeTable: "N/A",
    bronzeColumn: "N/A",
    silverSchema: "CORE_CUSTOMERS",
    silverTable: "DIM_CUSTOMER_ADDRESS",
    silverColumn: "RECORD_FLAG",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "VARCHAR(16777216)",
    businessLogic: "CASE WHEN EFFECTIVE_END_DATE::DATE = TO_DATE('9999-12-31') THEN 'A' ELSE 'I' END",
    businessMeaning: "Active/Inactive record flag",
    mappingType: "Derived",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "VW_TB_CI_DZY_C2_CUST_SCD_DIM",
    sourceColumn: "PRCS_DTE",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "VW_TB_CI_DZY_C2_CUST_SCD_DIM",
    bronzeColumn: "PRCS_DTE",
    silverSchema: "CORE_CUSTOMERS",
    silverTable: "DIM_CUSTOMER_ADDRESS",
    silverColumn: "BUSINESS_DATE",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "TIMESTAMP_NTZ(9)",
    businessLogic: "1:1 mapping from FIS processing date, also from FIS-DDW as EFF_DTE",
    businessMeaning: "Business processing date",
    mappingType: "Direct",
  },
  {
    sourceSystem: "SYSTEM",
    sourceTable: "N/A",
    sourceColumn: "HASH_FUNCTION",
    bronzeSchema: "N/A",
    bronzeTable: "N/A",
    bronzeColumn: "N/A",
    silverSchema: "CORE_CUSTOMERS",
    silverTable: "DIM_CUSTOMER_ADDRESS",
    silverColumn: "ROW_HASH",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "VARCHAR(16777216)",
    businessLogic: "HASH(CUSTOMER_NUMBER, ADDRESS_TYPE_CODE, ADDRESS_LINE_1, ADDRESS_LINE_2, CITY, STATE_CODE, ZIP_CODE, COUNTRY_CODE)",
    businessMeaning: "Hash of address columns for SCD2 change detection",
    mappingType: "Derived",
  },
  {
    sourceSystem: "SYSTEM",
    sourceTable: "N/A",
    sourceColumn: "CURRENT_USER()",
    bronzeSchema: "N/A",
    bronzeTable: "N/A",
    bronzeColumn: "N/A",
    silverSchema: "CORE_CUSTOMERS",
    silverTable: "DIM_CUSTOMER_ADDRESS",
    silverColumn: "INSERT_BY",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "VARCHAR(16777216)",
    businessLogic: "CURRENT_USER() on insert",
    businessMeaning: "User who inserted the record",
    mappingType: "System",
  },
  {
    sourceSystem: "SYSTEM",
    sourceTable: "N/A",
    sourceColumn: "CURRENT_TIMESTAMP()",
    bronzeSchema: "N/A",
    bronzeTable: "N/A",
    bronzeColumn: "N/A",
    silverSchema: "CORE_CUSTOMERS",
    silverTable: "DIM_CUSTOMER_ADDRESS",
    silverColumn: "INSERT_DT",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "TIMESTAMP_NTZ(9)",
    businessLogic: "CURRENT_TIMESTAMP() on insert",
    businessMeaning: "Timestamp when record was inserted",
    mappingType: "System",
  },
  {
    sourceSystem: "SYSTEM",
    sourceTable: "N/A",
    sourceColumn: "CURRENT_USER()",
    bronzeSchema: "N/A",
    bronzeTable: "N/A",
    bronzeColumn: "N/A",
    silverSchema: "CORE_CUSTOMERS",
    silverTable: "DIM_CUSTOMER_ADDRESS",
    silverColumn: "LAST_MODIFIED_BY",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "VARCHAR(16777216)",
    businessLogic: "CURRENT_USER() on update",
    businessMeaning: "User who last modified the record",
    mappingType: "System",
  },
  {
    sourceSystem: "SYSTEM",
    sourceTable: "N/A",
    sourceColumn: "CURRENT_TIMESTAMP()",
    bronzeSchema: "N/A",
    bronzeTable: "N/A",
    bronzeColumn: "N/A",
    silverSchema: "CORE_CUSTOMERS",
    silverTable: "DIM_CUSTOMER_ADDRESS",
    silverColumn: "LAST_MODIFIED_DT",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "TIMESTAMP_NTZ(9)",
    businessLogic: "CURRENT_TIMESTAMP() on update",
    businessMeaning: "Timestamp when record was last modified",
    mappingType: "System",
  },
];

export default dimCustomerAddressMappings;
