// DIM_CUSTOMER_IDENTIFER - Complete STTM Mapping
// Source: STTM Excel - CORE_CUSTOMERS schema
// 32 columns total (includes 18 different ID types!)
// Sources: FIS-ADS (TB_CI_OZ6_CUST_ARD, TB_CI_OZ4_CUST_ID_ARD) and FIS-DDW (TB_CI_DZY_C2_CUST_SCD_DIM, TB_CI_DZL_CUST_DOC_ID_DIM)

export interface ColumnMapping {
  sourceSystem: string;
  sourceTable: string;
  sourceColumn: string;
  bronzeSchema: string;
  bronzeTable: string;
  bronzeColumn: string;
  silverSchema: string;
  silverTable: string;
  silverColumn: string;
  goldSchema: string;
  goldTable: string;
  goldColumn: string | null;
  dataType: string;
  businessLogic: string;
  businessMeaning: string;
  mappingType?: "Direct" | "Derived" | "System" | "SCD2";
}

export const dimCustomerIdentifierMappings: ColumnMapping[] = [
  // Surrogate & Foreign Keys
  {
    sourceSystem: "SYSTEM",
    sourceTable: "N/A",
    sourceColumn: "AUTO_GENERATED",
    bronzeSchema: "N/A",
    bronzeTable: "N/A",
    bronzeColumn: "N/A",
    silverSchema: "CORE_CUSTOMERS",
    silverTable: "DIM_CUSTOMER_IDENTIFER",
    silverColumn: "CUSTOMER_IDENTIFIER_SK",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "NUMBER(38,0)",
    businessLogic: "Auto-generated surrogate key sequence",
    businessMeaning: "Surrogate key for customer identifier dimension",
    mappingType: "System",
  },
  {
    sourceSystem: "SYSTEM",
    sourceTable: "N/A",
    sourceColumn: "DERIVED_FK",
    bronzeSchema: "N/A",
    bronzeTable: "N/A",
    bronzeColumn: "N/A",
    silverSchema: "CORE_CUSTOMERS",
    silverTable: "DIM_CUSTOMER_IDENTIFER",
    silverColumn: "CUSTOMER_NUMBER_FK",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "NUMBER(38,0)",
    businessLogic: "Foreign key lookup to DIM_CUSTOMER",
    businessMeaning: "Customer dimension foreign key reference",
    mappingType: "Derived",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_CI_OZ6_CUST_ARD",
    sourceColumn: "CID_CUST_CUST_NBR",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_CI_OZ6_CUST_ARD",
    bronzeColumn: "CID_CUST_CUST_NBR",
    silverSchema: "CORE_CUSTOMERS",
    silverTable: "DIM_CUSTOMER_IDENTIFER",
    silverColumn: "CUSTOMER_NUMBER",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "VARCHAR(16777216)",
    businessLogic: "1:1 mapping from FIS-ADS, also from FIS-DDW as CUST_CIS_NBR",
    businessMeaning: "Unique customer identifier number",
    mappingType: "Direct",
  },

  // Driver's License Number
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_CI_OZ4_CUST_ID_ARD",
    sourceColumn: "CI_DMV21_ID_NUMBER",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_CI_OZ4_CUST_ID_ARD",
    bronzeColumn: "CI_DMV21_ID_NUMBER, CI_DMV22_ID_NUMBER, CI_DMV23_ID_NUMBER, CI_DMV24_ID_NUMBER, CI_DMV25_ID_NUMBER",
    silverSchema: "CORE_CUSTOMERS",
    silverTable: "DIM_CUSTOMER_IDENTIFER",
    silverColumn: "DRIVING_LICENSE_NUMBER",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "VARCHAR(16777216)",
    businessLogic: "Extract from CI_DMV21-25_ID_NUMBER where ID_TYP_NME = 'DRIVER_LICENSE', also available from FIS-DDW",
    businessMeaning: "Driver's license identification number (PII - encrypted/tokenized)",
    mappingType: "Direct",
  },

  // Tax Identification Number
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_CI_OZ6_CUST_ARD",
    sourceColumn: "CID_CUST_TAX_ID",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_CI_OZ6_CUST_ARD",
    bronzeColumn: "CID_CUST_TAX_ID",
    silverSchema: "CORE_CUSTOMERS",
    silverTable: "DIM_CUSTOMER_IDENTIFER",
    silverColumn: "TAX_IDENTIFICATION_NUMBER",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "VARCHAR(16777216)",
    businessLogic: "1:1 mapping from FIS-ADS, also from FIS-DDW as TAX_ID_NBR (encrypted/tokenized)",
    businessMeaning: "Tax identification number (SSN/EIN) - encrypted for PII protection",
    mappingType: "Direct",
  },

  // Tax ID Last 4 Digits (for display)
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_CI_OZ6_CUST_ARD",
    sourceColumn: "CID_CUST_TAX_ID",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_CI_OZ6_CUST_ARD",
    bronzeColumn: "CID_CUST_TAX_ID",
    silverSchema: "CORE_CUSTOMERS",
    silverTable: "DIM_CUSTOMER_IDENTIFER",
    silverColumn: "TAX_IDENTIFICATION_LAST_4",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "VARCHAR(16777216)",
    businessLogic: "RIGHT(CID_CUST_TAX_ID, 4) for masked display (XXX-XX-1234)",
    businessMeaning: "Last 4 digits of tax ID for customer verification",
    mappingType: "Derived",
  },

  // Passport Number
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_CI_OZ4_CUST_ID_ARD",
    sourceColumn: "CI_DMV21_ID_NUMBER",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_CI_OZ4_CUST_ID_ARD",
    bronzeColumn: "CI_DMV21_ID_NUMBER, CI_DMV22_ID_NUMBER, CI_DMV23_ID_NUMBER, CI_DMV24_ID_NUMBER, CI_DMV25_ID_NUMBER",
    silverSchema: "CORE_CUSTOMERS",
    silverTable: "DIM_CUSTOMER_IDENTIFER",
    silverColumn: "PASSPORT_NUMBER",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "VARCHAR(16777216)",
    businessLogic: "Extract from CI_DMV21-25_ID_NUMBER where ID_TYP_NME = 'PASSPORT'",
    businessMeaning: "Passport identification number",
    mappingType: "Direct",
  },

  // Alien Registration Number
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_CI_OZ4_CUST_ID_ARD",
    sourceColumn: "CI_DMV21_ID_NUMBER",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_CI_OZ4_CUST_ID_ARD",
    bronzeColumn: "CI_DMV21_ID_NUMBER, CI_DMV22_ID_NUMBER, CI_DMV23_ID_NUMBER, CI_DMV24_ID_NUMBER, CI_DMV25_ID_NUMBER",
    silverSchema: "CORE_CUSTOMERS",
    silverTable: "DIM_CUSTOMER_IDENTIFER",
    silverColumn: "ALIEN_REGISTRATION",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "VARCHAR(16777216)",
    businessLogic: "Extract from CI_DMV21-25_ID_NUMBER where ID_TYP_NME = 'ALIEN_REGISTRATION'",
    businessMeaning: "Alien registration number for non-citizen customers",
    mappingType: "Direct",
  },

  // Amish Customer No ID
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_CI_OZ4_CUST_ID_ARD",
    sourceColumn: "CI_DMV21_ID_NUMBER",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_CI_OZ4_CUST_ID_ARD",
    bronzeColumn: "CI_DMV21_ID_NUMBER, CI_DMV22_ID_NUMBER, CI_DMV23_ID_NUMBER, CI_DMV24_ID_NUMBER, CI_DMV25_ID_NUMBER",
    silverSchema: "CORE_CUSTOMERS",
    silverTable: "DIM_CUSTOMER_IDENTIFER",
    silverColumn: "AMISH_CUST_NO_ID",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "VARCHAR(16777216)",
    businessLogic: "Extract from CI_DMV21-25_ID_NUMBER where ID_TYP_NME = 'AMISH_NO_ID'",
    businessMeaning: "Special identifier for Amish customers without standard ID",
    mappingType: "Direct",
  },

  // Certificate of Registration IVU
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_CI_OZ4_CUST_ID_ARD",
    sourceColumn: "CI_DMV21_ID_NUMBER",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_CI_OZ4_CUST_ID_ARD",
    bronzeColumn: "CI_DMV21_ID_NUMBER, CI_DMV22_ID_NUMBER, CI_DMV23_ID_NUMBER, CI_DMV24_ID_NUMBER, CI_DMV25_ID_NUMBER",
    silverSchema: "CORE_CUSTOMERS",
    silverTable: "DIM_CUSTOMER_IDENTIFER",
    silverColumn: "CERTIFICATE_OF_REGISTRATION_IVU",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "VARCHAR(16777216)",
    businessLogic: "Extract from CI_DMV21-25_ID_NUMBER where ID_TYP_NME = 'CERT_REGISTRATION_IVU'",
    businessMeaning: "Certificate of registration IVU identifier",
    mappingType: "Direct",
  },

  // Disabled/Elderly No ID
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_CI_OZ4_CUST_ID_ARD",
    sourceColumn: "CI_DMV21_ID_NUMBER",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_CI_OZ4_CUST_ID_ARD",
    bronzeColumn: "CI_DMV21_ID_NUMBER, CI_DMV22_ID_NUMBER, CI_DMV23_ID_NUMBER, CI_DMV24_ID_NUMBER, CI_DMV25_ID_NUMBER",
    silverSchema: "CORE_CUSTOMERS",
    silverTable: "DIM_CUSTOMER_IDENTIFER",
    silverColumn: "DISABLED_ELDERLY_NO_ID",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "VARCHAR(16777216)",
    businessLogic: "Extract from CI_DMV21-25_ID_NUMBER where ID_TYP_NME = 'DISABLED_ELDERLY_NO_ID'",
    businessMeaning: "Special identifier for disabled/elderly customers without standard ID",
    mappingType: "Direct",
  },

  // Foreign Entity No ID
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_CI_OZ4_CUST_ID_ARD",
    sourceColumn: "CI_DMV21_ID_NUMBER",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_CI_OZ4_CUST_ID_ARD",
    bronzeColumn: "CI_DMV21_ID_NUMBER, CI_DMV22_ID_NUMBER, CI_DMV23_ID_NUMBER, CI_DMV24_ID_NUMBER, CI_DMV25_ID_NUMBER",
    silverSchema: "CORE_CUSTOMERS",
    silverTable: "DIM_CUSTOMER_IDENTIFER",
    silverColumn: "FOREIGN_ENTITY_NO_ID",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "VARCHAR(16777216)",
    businessLogic: "Extract from CI_DMV21-25_ID_NUMBER where ID_TYP_NME = 'FOREIGN_ENTITY_NO_ID'",
    businessMeaning: "Identifier for foreign entities without standard ID",
    mappingType: "Direct",
  },

  // Government Agency No ID
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_CI_OZ4_CUST_ID_ARD",
    sourceColumn: "CI_DMV21_ID_NUMBER",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_CI_OZ4_CUST_ID_ARD",
    bronzeColumn: "CI_DMV21_ID_NUMBER, CI_DMV22_ID_NUMBER, CI_DMV23_ID_NUMBER, CI_DMV24_ID_NUMBER, CI_DMV25_ID_NUMBER",
    silverSchema: "CORE_CUSTOMERS",
    silverTable: "DIM_CUSTOMER_IDENTIFER",
    silverColumn: "GOVERNMENT_AGENCY_NO_ID",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "VARCHAR(16777216)",
    businessLogic: "Extract from CI_DMV21-25_ID_NUMBER where ID_TYP_NME = 'GOVT_AGENCY_NO_ID'",
    businessMeaning: "Identifier for government agencies without standard ID",
    mappingType: "Direct",
  },

  // Incorporation Register
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_CI_OZ4_CUST_ID_ARD",
    sourceColumn: "CI_DMV21_ID_NUMBER",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_CI_OZ4_CUST_ID_ARD",
    bronzeColumn: "CI_DMV21_ID_NUMBER, CI_DMV22_ID_NUMBER, CI_DMV23_ID_NUMBER, CI_DMV24_ID_NUMBER, CI_DMV25_ID_NUMBER",
    silverSchema: "CORE_CUSTOMERS",
    silverTable: "DIM_CUSTOMER_IDENTIFER",
    silverColumn: "INCORPORATION_REGISTER",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "VARCHAR(16777216)",
    businessLogic: "Extract from CI_DMV21-25_ID_NUMBER where ID_TYP_NME = 'INCORPORATION_REGISTER'",
    businessMeaning: "Incorporation registration number for corporate entities",
    mappingType: "Direct",
  },

  // License (General)
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_CI_OZ4_CUST_ID_ARD",
    sourceColumn: "CI_DMV21_ID_NUMBER",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_CI_OZ4_CUST_ID_ARD",
    bronzeColumn: "CI_DMV21_ID_NUMBER, CI_DMV22_ID_NUMBER, CI_DMV23_ID_NUMBER, CI_DMV24_ID_NUMBER, CI_DMV25_ID_NUMBER",
    silverSchema: "CORE_CUSTOMERS",
    silverTable: "DIM_CUSTOMER_IDENTIFER",
    silverColumn: "LICENSE",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "VARCHAR(16777216)",
    businessLogic: "Extract from CI_DMV21-25_ID_NUMBER where ID_TYP_NME = 'LICENSE'",
    businessMeaning: "General license number",
    mappingType: "Direct",
  },

  // Military ID
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_CI_OZ4_CUST_ID_ARD",
    sourceColumn: "CI_DMV21_ID_NUMBER",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_CI_OZ4_CUST_ID_ARD",
    bronzeColumn: "CI_DMV21_ID_NUMBER, CI_DMV22_ID_NUMBER, CI_DMV23_ID_NUMBER, CI_DMV24_ID_NUMBER, CI_DMV25_ID_NUMBER",
    silverSchema: "CORE_CUSTOMERS",
    silverTable: "DIM_CUSTOMER_IDENTIFER",
    silverColumn: "MILITARY_ID",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "VARCHAR(16777216)",
    businessLogic: "Extract from CI_DMV21-25_ID_NUMBER where ID_TYP_NME = 'MILITARY_ID'",
    businessMeaning: "Military identification number for active/veteran service members",
    mappingType: "Direct",
  },

  // Minor ID
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_CI_OZ4_CUST_ID_ARD",
    sourceColumn: "CI_DMV21_ID_NUMBER",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_CI_OZ4_CUST_ID_ARD",
    bronzeColumn: "CI_DMV21_ID_NUMBER, CI_DMV22_ID_NUMBER, CI_DMV23_ID_NUMBER, CI_DMV24_ID_NUMBER, CI_DMV25_ID_NUMBER",
    silverSchema: "CORE_CUSTOMERS",
    silverTable: "DIM_CUSTOMER_IDENTIFER",
    silverColumn: "MINOR",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "VARCHAR(16777216)",
    businessLogic: "Extract from CI_DMV21-25_ID_NUMBER where ID_TYP_NME = 'MINOR'",
    businessMeaning: "Special identifier for minor customers (under 18)",
    mappingType: "Direct",
  },

  // Other Identification
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_CI_OZ4_CUST_ID_ARD",
    sourceColumn: "CI_DMV21_ID_NUMBER",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_CI_OZ4_CUST_ID_ARD",
    bronzeColumn: "CI_DMV21_ID_NUMBER, CI_DMV22_ID_NUMBER, CI_DMV23_ID_NUMBER, CI_DMV24_ID_NUMBER, CI_DMV25_ID_NUMBER",
    silverSchema: "CORE_CUSTOMERS",
    silverTable: "DIM_CUSTOMER_IDENTIFER",
    silverColumn: "OTHER_IDENTIFICATION",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "VARCHAR(16777216)",
    businessLogic: "Extract from CI_DMV21-25_ID_NUMBER where ID_TYP_NME = 'OTHER'",
    businessMeaning: "Other non-standard identification types",
    mappingType: "Direct",
  },

  // State ID
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_CI_OZ4_CUST_ID_ARD",
    sourceColumn: "CI_DMV21_ID_NUMBER",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_CI_OZ4_CUST_ID_ARD",
    bronzeColumn: "CI_DMV21_ID_NUMBER, CI_DMV22_ID_NUMBER, CI_DMV23_ID_NUMBER, CI_DMV24_ID_NUMBER, CI_DMV25_ID_NUMBER",
    silverSchema: "CORE_CUSTOMERS",
    silverTable: "DIM_CUSTOMER_IDENTIFER",
    silverColumn: "STATE_ID",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "VARCHAR(16777216)",
    businessLogic: "Extract from CI_DMV21-25_ID_NUMBER where ID_TYP_NME = 'STATE_ID'",
    businessMeaning: "State-issued identification card number",
    mappingType: "Direct",
  },

  // VI Business License
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_CI_OZ4_CUST_ID_ARD",
    sourceColumn: "CI_DMV21_ID_NUMBER",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_CI_OZ4_CUST_ID_ARD",
    bronzeColumn: "CI_DMV21_ID_NUMBER, CI_DMV22_ID_NUMBER, CI_DMV23_ID_NUMBER, CI_DMV24_ID_NUMBER, CI_DMV25_ID_NUMBER",
    silverSchema: "CORE_CUSTOMERS",
    silverTable: "DIM_CUSTOMER_IDENTIFER",
    silverColumn: "VI_BUS_LICENSE",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "VARCHAR(16777216)",
    businessLogic: "Extract from CI_DMV21-25_ID_NUMBER where ID_TYP_NME = 'VI_BUS_LICENSE'",
    businessMeaning: "Virgin Islands business license number",
    mappingType: "Direct",
  },

  // SCD2 & System Columns
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_CI_OZ6_CUST_ARD",
    sourceColumn: "CID_CUST_LST_MNT_DTE",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_CI_OZ6_CUST_ARD",
    bronzeColumn: "CID_CUST_LST_MNT_DTE",
    silverSchema: "CORE_CUSTOMERS",
    silverTable: "DIM_CUSTOMER_IDENTIFER",
    silverColumn: "EFFECTIVE_START_DATE",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "DATE",
    businessLogic: "SCD2 effective start date from last maintenance date, also from FIS-DDW as EFF_DTE",
    businessMeaning: "Date this SCD2 version became effective",
    mappingType: "SCD2",
  },
  {
    sourceSystem: "SYSTEM",
    sourceTable: "N/A",
    sourceColumn: "SCD2_LOGIC",
    bronzeSchema: "N/A",
    bronzeTable: "N/A",
    bronzeColumn: "N/A",
    silverSchema: "CORE_CUSTOMERS",
    silverTable: "DIM_CUSTOMER_IDENTIFER",
    silverColumn: "EFFECTIVE_END_DATE",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "DATE",
    businessLogic: "COALESCE(LEAD(EFFECTIVE_START_DATE) OVER (PARTITION BY CUSTOMER_NUMBER ORDER BY EFFECTIVE_START_DATE), '9999-12-31')",
    businessMeaning: "Date this SCD2 version expired (9999-12-31 for current)",
    mappingType: "SCD2",
  },
  {
    sourceSystem: "SYSTEM",
    sourceTable: "N/A",
    sourceColumn: "HASH_FUNCTION",
    bronzeSchema: "N/A",
    bronzeTable: "N/A",
    bronzeColumn: "N/A",
    silverSchema: "CORE_CUSTOMERS",
    silverTable: "DIM_CUSTOMER_IDENTIFER",
    silverColumn: "ROW_HASH",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "VARCHAR(16777216)",
    businessLogic: "HASH of all ID columns for SCD2 change detection",
    businessMeaning: "Hash for change detection across all identifier columns",
    mappingType: "Derived",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_CI_OZ6_CUST_ARD",
    sourceColumn: "PRCS_DTE",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_CI_OZ6_CUST_ARD",
    bronzeColumn: "PRCS_DTE",
    silverSchema: "CORE_CUSTOMERS",
    silverTable: "DIM_CUSTOMER_IDENTIFER",
    silverColumn: "BUSINESS_DATE",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "DATE",
    businessLogic: "1:1 mapping from FIS processing date, also from FIS-DDW as CUST_LST_MAINT_DTE",
    businessMeaning: "Business processing date",
    mappingType: "Direct",
  },
  {
    sourceSystem: "SYSTEM",
    sourceTable: "N/A",
    sourceColumn: "CURRENT_USER()",
    bronzeSchema: "N/A",
    bronzeTable: "N/A",
    bronzeColumn: "N/A",
    silverSchema: "CORE_CUSTOMERS",
    silverTable: "DIM_CUSTOMER_IDENTIFER",
    silverColumn: "INSERT_BY",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "VARCHAR(16777216)",
    businessLogic: "CURRENT_USER() on insert",
    businessMeaning: "User who inserted the record",
    mappingType: "System",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_CI_OZ6_CUST_ARD",
    sourceColumn: "REFRESH_TIME",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_CI_OZ6_CUST_ARD",
    bronzeColumn: "REFRESH_TIME",
    silverSchema: "CORE_CUSTOMERS",
    silverTable: "DIM_CUSTOMER_IDENTIFER",
    silverColumn: "RECORD_DATE",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "DATE",
    businessLogic: "1:1 mapping from source refresh timestamp, also from FIS-DDW as REFRESH_TIME",
    businessMeaning: "Source data refresh date",
    mappingType: "Direct",
  },
  {
    sourceSystem: "SYSTEM",
    sourceTable: "N/A",
    sourceColumn: "DERIVED",
    bronzeSchema: "N/A",
    bronzeTable: "N/A",
    bronzeColumn: "N/A",
    silverSchema: "CORE_CUSTOMERS",
    silverTable: "DIM_CUSTOMER_IDENTIFER",
    silverColumn: "RECORD_FLAG",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "VARCHAR(16777216)",
    businessLogic: "CASE WHEN EFFECTIVE_END_DATE = '9999-12-31' THEN 'A' ELSE 'I' END",
    businessMeaning: "Active/Inactive record flag",
    mappingType: "Derived",
  },
  {
    sourceSystem: "SYSTEM",
    sourceTable: "N/A",
    sourceColumn: "CURRENT_TIMESTAMP()",
    bronzeSchema: "N/A",
    bronzeTable: "N/A",
    bronzeColumn: "N/A",
    silverSchema: "CORE_CUSTOMERS",
    silverTable: "DIM_CUSTOMER_IDENTIFER",
    silverColumn: "INSERT_DT",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "TIMESTAMP_NTZ(9)",
    businessLogic: "CURRENT_TIMESTAMP() on insert",
    businessMeaning: "Timestamp when record was inserted",
    mappingType: "System",
  },
  {
    sourceSystem: "SYSTEM",
    sourceTable: "N/A",
    sourceColumn: "CURRENT_USER()",
    bronzeSchema: "N/A",
    bronzeTable: "N/A",
    bronzeColumn: "N/A",
    silverSchema: "CORE_CUSTOMERS",
    silverTable: "DIM_CUSTOMER_IDENTIFER",
    silverColumn: "LAST_MODIFIED_BY",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "VARCHAR(16777216)",
    businessLogic: "CURRENT_USER() on update",
    businessMeaning: "User who last modified the record",
    mappingType: "System",
  },
  {
    sourceSystem: "SYSTEM",
    sourceTable: "N/A",
    sourceColumn: "CURRENT_TIMESTAMP()",
    bronzeSchema: "N/A",
    bronzeTable: "N/A",
    bronzeColumn: "N/A",
    silverSchema: "CORE_CUSTOMERS",
    silverTable: "DIM_CUSTOMER_IDENTIFER",
    silverColumn: "LAST_MODIFIED_DT",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "TIMESTAMP_NTZ(9)",
    businessLogic: "CURRENT_TIMESTAMP() on update",
    businessMeaning: "Timestamp when record was last modified",
    mappingType: "System",
  },
];

export default dimCustomerIdentifierMappings;
