// DIM_CUSTOMER_CONTACT - Complete STTM Mapping
// Source: STTM Excel - CORE_CUSTOMERS schema
// 18 columns total
// Sources: FIS-ADS (TB_CI_OZ5_CUST_NAAD_ARD_RAW) and FIS-DDW (TB_CI_DZY_C2_CUST_SCD_DIM_RAW)

export interface ColumnMapping {
  sourceSystem: string;
  sourceTable: string;
  sourceColumn: string;
  bronzeSchema: string;
  bronzeTable: string;
  bronzeColumn: string;
  silverSchema: string;
  silverTable: string;
  silverColumn: string;
  goldSchema: string;
  goldTable: string;
  goldColumn: string | null;
  dataType: string;
  businessLogic: string;
  businessMeaning: string;
  mappingType?: "Direct" | "Derived" | "System" | "SCD2";
}

export const dimCustomerContactMappings: ColumnMapping[] = [
  {
    sourceSystem: "SYSTEM",
    sourceTable: "N/A",
    sourceColumn: "AUTO_GENERATED",
    bronzeSchema: "N/A",
    bronzeTable: "N/A",
    bronzeColumn: "N/A",
    silverSchema: "CORE_CUSTOMERS",
    silverTable: "DIM_CUSTOMER_CONTACT",
    silverColumn: "CUSTOMER_SK",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "NUMBER(38,0)",
    businessLogic: "Auto-generated surrogate key sequence",
    businessMeaning: "Surrogate key for customer contact dimension",
    mappingType: "System",
  },
  {
    sourceSystem: "SYSTEM",
    sourceTable: "N/A",
    sourceColumn: "DERIVED_FK",
    bronzeSchema: "N/A",
    bronzeTable: "N/A",
    bronzeColumn: "N/A",
    silverSchema: "CORE_CUSTOMERS",
    silverTable: "DIM_CUSTOMER_CONTACT",
    silverColumn: "CUSTOMER_NUMBER_FK",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "NUMBER(38,0)",
    businessLogic: "Foreign key lookup to DIM_CUSTOMER",
    businessMeaning: "Customer dimension foreign key reference",
    mappingType: "Derived",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_CI_OZ5_CUST_NAAD_ARD_RAW",
    sourceColumn: "CID_NAAD_APPL_ID",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_CI_OZ5_CUST_NAAD_ARD_RAW",
    bronzeColumn: "CID_NAAD_APPL_ID",
    silverSchema: "CORE_CUSTOMERS",
    silverTable: "DIM_CUSTOMER_CONTACT",
    silverColumn: "CUSTOMER_NUMBER",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "VARCHAR(16777216)",
    businessLogic: "1:1 mapping from FIS-ADS, also from FIS-DDW as CUST_CIS_NBR",
    businessMeaning: "Unique customer identifier number",
    mappingType: "Direct",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_CI_OZ5_CUST_NAAD_ARD_RAW",
    sourceColumn: "CID_NAAD_PHONE_NBR",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_CI_OZ5_CUST_NAAD_ARD_RAW",
    bronzeColumn: "CID_NAAD_PHONE_NBR",
    silverSchema: "CORE_CUSTOMERS",
    silverTable: "DIM_CUSTOMER_CONTACT",
    silverColumn: "PRIMARY_PHONE_NUMBER",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "VARCHAR(16777216)",
    businessLogic: "1:1 mapping with masking for PII (show last 4 digits), also from FIS-DDW as PHN_NBR (PII - masked)",
    businessMeaning: "Customer primary phone number (PII - masked for security)",
    mappingType: "Direct",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_CI_OZ5_CUST_NAAD_ARD_RAW",
    sourceColumn: "CID_NAAD_PHONE_EXT",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_CI_OZ5_CUST_NAAD_ARD_RAW",
    bronzeColumn: "CID_NAAD_PHONE_EXT",
    silverSchema: "CORE_CUSTOMERS",
    silverTable: "DIM_CUSTOMER_CONTACT",
    silverColumn: "PRIMARY_PHONE_EXTENSION",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "VARCHAR(16777216)",
    businessLogic: "1:1 mapping, also from FIS-DDW as PHN_EXT",
    businessMeaning: "Extension number for primary phone",
    mappingType: "Direct",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_CI_OZ5_CUST_NAAD_ARD_RAW",
    sourceColumn: "CID_NAAD_PHONE_2_NBR",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_CI_OZ5_CUST_NAAD_ARD_RAW",
    bronzeColumn: "CID_NAAD_PHONE_2_NBR",
    silverSchema: "CORE_CUSTOMERS",
    silverTable: "DIM_CUSTOMER_CONTACT",
    silverColumn: "SECONDARY_PHONE_NUMBER",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "VARCHAR(16777216)",
    businessLogic: "1:1 mapping with masking for PII (show last 4 digits), also from FIS-DDW as SEC_PHN_NBR (PII - masked)",
    businessMeaning: "Customer secondary phone number (PII - masked for security)",
    mappingType: "Direct",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_CI_OZ5_CUST_NAAD_ARD_RAW",
    sourceColumn: "CID_NAAD_PHONE_2_EXT",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_CI_OZ5_CUST_NAAD_ARD_RAW",
    bronzeColumn: "CID_NAAD_PHONE_2_EXT",
    silverSchema: "CORE_CUSTOMERS",
    silverTable: "DIM_CUSTOMER_CONTACT",
    silverColumn: "SECONDARY_PHONE_EXTENSION",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "VARCHAR(16777216)",
    businessLogic: "1:1 mapping, also from FIS-DDW as SEC_PHN_EXT",
    businessMeaning: "Extension number for secondary phone",
    mappingType: "Direct",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_CI_OZ5_CUST_NAAD_ARD_RAW",
    sourceColumn: "CID_NAAD_FAX_NBR",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_CI_OZ5_CUST_NAAD_ARD_RAW",
    bronzeColumn: "CID_NAAD_FAX_NBR",
    silverSchema: "CORE_CUSTOMERS",
    silverTable: "DIM_CUSTOMER_CONTACT",
    silverColumn: "FAX_NUMBER",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "VARCHAR(16777216)",
    businessLogic: "1:1 mapping, also from FIS-DDW as FAX_NBR",
    businessMeaning: "Customer fax number",
    mappingType: "Direct",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_CI_OZ5_CUST_NAAD_ARD_RAW",
    sourceColumn: "CID_NAAD_MOBILE_NBR",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_CI_OZ5_CUST_NAAD_ARD_RAW",
    bronzeColumn: "CID_NAAD_MOBILE_NBR",
    silverSchema: "CORE_CUSTOMERS",
    silverTable: "DIM_CUSTOMER_CONTACT",
    silverColumn: "MOBILE_PHONE_NUMBER",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "VARCHAR(16777216)",
    businessLogic: "1:1 mapping with masking for PII (show last 4 digits), also from FIS-DDW as MOB_PHN_NBR (PII - masked)",
    businessMeaning: "Customer mobile phone number (PII - masked for security)",
    mappingType: "Direct",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_CI_OZ5_CUST_NAAD_ARD_RAW",
    sourceColumn: "CID_NAAD_CONTACT_LAST_CHG_DTE",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_CI_OZ5_CUST_NAAD_ARD_RAW",
    bronzeColumn: "CID_NAAD_CONTACT_LAST_CHG_DTE",
    silverSchema: "CORE_CUSTOMERS",
    silverTable: "DIM_CUSTOMER_CONTACT",
    silverColumn: "EFFECTIVE_START_DATE",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "TIMESTAMP_NTZ(9)",
    businessLogic: "SCD2 effective start date from last contact change date, also from FIS-DDW as EFF_DTE",
    businessMeaning: "Date this contact version became effective",
    mappingType: "SCD2",
  },
  {
    sourceSystem: "SYSTEM",
    sourceTable: "N/A",
    sourceColumn: "SCD2_LOGIC",
    bronzeSchema: "N/A",
    bronzeTable: "N/A",
    bronzeColumn: "N/A",
    silverSchema: "CORE_CUSTOMERS",
    silverTable: "DIM_CUSTOMER_CONTACT",
    silverColumn: "EFFECTIVE_END_DATE",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "TIMESTAMP_NTZ(9)",
    businessLogic: "COALESCE(LEAD(EFFECTIVE_START_DATE) OVER (PARTITION BY CUSTOMER_NUMBER ORDER BY EFFECTIVE_START_DATE), '9999-12-31')",
    businessMeaning: "Date this contact version expired (9999-12-31 for current)",
    mappingType: "SCD2",
  },
  {
    sourceSystem: "SYSTEM",
    sourceTable: "N/A",
    sourceColumn: "DERIVED",
    bronzeSchema: "N/A",
    bronzeTable: "N/A",
    bronzeColumn: "N/A",
    silverSchema: "CORE_CUSTOMERS",
    silverTable: "DIM_CUSTOMER_CONTACT",
    silverColumn: "RECORD_FLAG",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "VARCHAR(16777216)",
    businessLogic: "CASE WHEN EFFECTIVE_END_DATE::DATE = TO_DATE('9999-12-31') THEN 'A' ELSE 'I' END",
    businessMeaning: "Active/Inactive record flag",
    mappingType: "Derived",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "VW_TB_CI_DZY_C2_CUST_SCD_DIM",
    sourceColumn: "PRCS_DTE",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "VW_TB_CI_DZY_C2_CUST_SCD_DIM",
    bronzeColumn: "PRCS_DTE",
    silverSchema: "CORE_CUSTOMERS",
    silverTable: "DIM_CUSTOMER_CONTACT",
    silverColumn: "BUSINESS_DATE",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "TIMESTAMP_NTZ(9)",
    businessLogic: "1:1 mapping from FIS processing date, also from FIS-DDW as EFF_DTE",
    businessMeaning: "Business processing date",
    mappingType: "Direct",
  },
  {
    sourceSystem: "SYSTEM",
    sourceTable: "N/A",
    sourceColumn: "HASH_FUNCTION",
    bronzeSchema: "N/A",
    bronzeTable: "N/A",
    bronzeColumn: "N/A",
    silverSchema: "CORE_CUSTOMERS",
    silverTable: "DIM_CUSTOMER_CONTACT",
    silverColumn: "ROW_HASH",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "VARCHAR(16777216)",
    businessLogic: "HASH(CUSTOMER_NUMBER, PRIMARY_PHONE_NUMBER, SECONDARY_PHONE_NUMBER, FAX_NUMBER, MOBILE_PHONE_NUMBER)",
    businessMeaning: "Hash of contact columns for SCD2 change detection",
    mappingType: "Derived",
  },
  {
    sourceSystem: "SYSTEM",
    sourceTable: "N/A",
    sourceColumn: "CURRENT_USER()",
    bronzeSchema: "N/A",
    bronzeTable: "N/A",
    bronzeColumn: "N/A",
    silverSchema: "CORE_CUSTOMERS",
    silverTable: "DIM_CUSTOMER_CONTACT",
    silverColumn: "INSERT_BY",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "VARCHAR(16777216)",
    businessLogic: "CURRENT_USER() on insert",
    businessMeaning: "User who inserted the record",
    mappingType: "System",
  },
  {
    sourceSystem: "SYSTEM",
    sourceTable: "N/A",
    sourceColumn: "CURRENT_TIMESTAMP()",
    bronzeSchema: "N/A",
    bronzeTable: "N/A",
    bronzeColumn: "N/A",
    silverSchema: "CORE_CUSTOMERS",
    silverTable: "DIM_CUSTOMER_CONTACT",
    silverColumn: "INSERT_DT",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "TIMESTAMP_NTZ(9)",
    businessLogic: "CURRENT_TIMESTAMP() on insert",
    businessMeaning: "Timestamp when record was inserted",
    mappingType: "System",
  },
  {
    sourceSystem: "SYSTEM",
    sourceTable: "N/A",
    sourceColumn: "CURRENT_USER()",
    bronzeSchema: "N/A",
    bronzeTable: "N/A",
    bronzeColumn: "N/A",
    silverSchema: "CORE_CUSTOMERS",
    silverTable: "DIM_CUSTOMER_CONTACT",
    silverColumn: "LAST_MODIFIED_BY",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "VARCHAR(16777216)",
    businessLogic: "CURRENT_USER() on update",
    businessMeaning: "User who last modified the record",
    mappingType: "System",
  },
  {
    sourceSystem: "SYSTEM",
    sourceTable: "N/A",
    sourceColumn: "CURRENT_TIMESTAMP()",
    bronzeSchema: "N/A",
    bronzeTable: "N/A",
    bronzeColumn: "N/A",
    silverSchema: "CORE_CUSTOMERS",
    silverTable: "DIM_CUSTOMER_CONTACT",
    silverColumn: "LAST_MODIFIED_DT",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "TIMESTAMP_NTZ(9)",
    businessLogic: "CURRENT_TIMESTAMP() on update",
    businessMeaning: "Timestamp when record was last modified",
    mappingType: "System",
  },
];

export default dimCustomerContactMappings;
