// DIM_CUSTOMER_DEMOGRAPHY - Complete STTM Mapping
// Source: STTM Excel - CORE_CUSTOMERS schema
// 20 columns total
// Sources: FIS-ADS (TB_CI_OZ6_CUST_ARD) and FIS-DDW (TB_CI_DZY_C2_CUST_SCD_DIM)

export interface ColumnMapping {
  sourceSystem: string;
  sourceTable: string;
  sourceColumn: string;
  bronzeSchema: string;
  bronzeTable: string;
  bronzeColumn: string;
  silverSchema: string;
  silverTable: string;
  silverColumn: string;
  goldSchema: string;
  goldTable: string;
  goldColumn: string | null;
  dataType: string;
  businessLogic: string;
  businessMeaning: string;
  mappingType?: "Direct" | "Derived" | "System" | "SCD2";
}

export const dimCustomerDemographyMappings: ColumnMapping[] = [
  {
    sourceSystem: "SYSTEM",
    sourceTable: "N/A",
    sourceColumn: "AUTO_GENERATED",
    bronzeSchema: "N/A",
    bronzeTable: "N/A",
    bronzeColumn: "N/A",
    silverSchema: "CORE_CUSTOMERS",
    silverTable: "DIM_CUSTOMER_DEMOGRAPHY",
    silverColumn: "CUSTOMER_DEMOGRAPHY_SK",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "NUMBER(38,0)",
    businessLogic: "Auto-generated surrogate key sequence",
    businessMeaning: "Surrogate key for customer demography dimension",
    mappingType: "System",
  },
  {
    sourceSystem: "SYSTEM",
    sourceTable: "N/A",
    sourceColumn: "DERIVED_FK",
    bronzeSchema: "N/A",
    bronzeTable: "N/A",
    bronzeColumn: "N/A",
    silverSchema: "CORE_CUSTOMERS",
    silverTable: "DIM_CUSTOMER_DEMOGRAPHY",
    silverColumn: "CUSTOMER_NUMBER_FK",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "NUMBER(38,0)",
    businessLogic: "Foreign key lookup to DIM_CUSTOMER",
    businessMeaning: "Customer dimension foreign key reference",
    mappingType: "Derived",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_CI_OZ6_CUST_ARD",
    sourceColumn: "CID_CUST_CUST_NBR",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_CI_OZ6_CUST_ARD",
    bronzeColumn: "CID_CUST_CUST_NBR",
    silverSchema: "CORE_CUSTOMERS",
    silverTable: "DIM_CUSTOMER_DEMOGRAPHY",
    silverColumn: "CUSTOMER_NUMBER",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "VARCHAR(16777216)",
    businessLogic: "1:1 mapping from FIS-ADS, also available from FIS-DDW as CUST_CIS_NBR",
    businessMeaning: "Unique customer identifier number",
    mappingType: "Direct",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_CI_OZ6_CUST_ARD",
    sourceColumn: "CID_CUST_ETHNIC_CDE",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_CI_OZ6_CUST_ARD",
    bronzeColumn: "CID_CUST_ETHNIC_CDE",
    silverSchema: "CORE_CUSTOMERS",
    silverTable: "DIM_CUSTOMER_DEMOGRAPHY",
    silverColumn: "ETHNIC_CODE",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "VARCHAR(16777216)",
    businessLogic: "1:1 mapping from FIS-ADS, also available from FIS-DDW as ETHNC_CDE",
    businessMeaning: "Customer ethnicity code for demographic analysis",
    mappingType: "Direct",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_CI_OZ6_CUST_ARD",
    sourceColumn: "CID_CUST_ETHNIC_DESC",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_CI_OZ6_CUST_ARD",
    bronzeColumn: "CID_CUST_ETHNIC_DESC",
    silverSchema: "CORE_CUSTOMERS",
    silverTable: "DIM_CUSTOMER_DEMOGRAPHY",
    silverColumn: "ETHNIC_DESC",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "VARCHAR(16777216)",
    businessLogic: "1:1 mapping from FIS-ADS, also available from FIS-DDW as ETHNC_CDE_DESC",
    businessMeaning: "Customer ethnicity description",
    mappingType: "Direct",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_CI_OZ6_CUST_ARD",
    sourceColumn: "CID_CUST_TYPE_CDE",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_CI_OZ6_CUST_ARD",
    bronzeColumn: "CID_CUST_TYPE_CDE",
    silverSchema: "CORE_CUSTOMERS",
    silverTable: "DIM_CUSTOMER_DEMOGRAPHY",
    silverColumn: "GENDER",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "VARCHAR(16777216)",
    businessLogic: "1:1 mapping from FIS-ADS, also available from FIS-DDW as GNDR_CDE",
    businessMeaning: "Customer gender code (M/F/X/U)",
    mappingType: "Direct",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_CI_OZ6_CUST_ARD",
    sourceColumn: "CID_CUST_MARITAL_STAT_CDE",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_CI_OZ6_CUST_ARD",
    bronzeColumn: "CID_CUST_MARITAL_STAT_CDE",
    silverSchema: "CORE_CUSTOMERS",
    silverTable: "DIM_CUSTOMER_DEMOGRAPHY",
    silverColumn: "MARITAL_STATUS_CODE",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "VARCHAR(16777216)",
    businessLogic: "1:1 mapping from FIS-ADS, also available from FIS-DDW as MRTL_STAT_CDE",
    businessMeaning: "Marital status code for demographic segmentation",
    mappingType: "Direct",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_CI_OZ6_CUST_ARD",
    sourceColumn: "CID_CUST_MARITAL_STAT_DESC",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_CI_OZ6_CUST_ARD",
    bronzeColumn: "CID_CUST_MARITAL_STAT_DESC",
    silverSchema: "CORE_CUSTOMERS",
    silverTable: "DIM_CUSTOMER_DEMOGRAPHY",
    silverColumn: "MARITAL_STATUS_DESC",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "VARCHAR(16777216)",
    businessLogic: "1:1 mapping from FIS-ADS, also available from FIS-DDW as MRTL_STAT_DESC",
    businessMeaning: "Marital status description (Single, Married, Divorced, Widowed)",
    mappingType: "Direct",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_CI_OZ6_CUST_ARD",
    sourceColumn: "CID_CUST_EDUCATION_CDE",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_CI_OZ6_CUST_ARD",
    bronzeColumn: "CID_CUST_EDUCATION_CDE",
    silverSchema: "CORE_CUSTOMERS",
    silverTable: "DIM_CUSTOMER_DEMOGRAPHY",
    silverColumn: "EDUCATION_CODE",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "VARCHAR(16777216)",
    businessLogic: "1:1 mapping from FIS-ADS, also available from FIS-DDW as EDUC_CDE",
    businessMeaning: "Education level code for segmentation",
    mappingType: "Direct",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_CI_OZ6_CUST_ARD",
    sourceColumn: "CID_CUST_EDUCATION_DESC",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_CI_OZ6_CUST_ARD",
    bronzeColumn: "CID_CUST_EDUCATION_DESC",
    silverSchema: "CORE_CUSTOMERS",
    silverTable: "DIM_CUSTOMER_DEMOGRAPHY",
    silverColumn: "EDUCATION_DESC",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "VARCHAR(16777216)",
    businessLogic: "1:1 mapping from FIS-ADS, also available from FIS-DDW as EDUC_DESC",
    businessMeaning: "Education level description (High School, Bachelor's, Master's, etc.)",
    mappingType: "Direct",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_CI_OZ6_CUST_ARD",
    sourceColumn: "CID_CUST_INCOME_CDE",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_CI_OZ6_CUST_ARD",
    bronzeColumn: "CID_CUST_INCOME_CDE",
    silverSchema: "CORE_CUSTOMERS",
    silverTable: "DIM_CUSTOMER_DEMOGRAPHY",
    silverColumn: "INCOME_CODE",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "VARCHAR(16777216)",
    businessLogic: "1:1 mapping from FIS-ADS, also available from FIS-DDW as INCM_CDE",
    businessMeaning: "Income bracket code for customer segmentation",
    mappingType: "Direct",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_CI_OZ6_CUST_ARD",
    sourceColumn: "CID_CUST_INCOME_DESC",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_CI_OZ6_CUST_ARD",
    bronzeColumn: "CID_CUST_INCOME_DESC",
    silverSchema: "CORE_CUSTOMERS",
    silverTable: "DIM_CUSTOMER_DEMOGRAPHY",
    silverColumn: "INCOME_DESC",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "VARCHAR(16777216)",
    businessLogic: "1:1 mapping from FIS-ADS, also available from FIS-DDW as INCM_DESC",
    businessMeaning: "Income range description (0-50K, 50K-100K, 100K-250K, 250K+)",
    mappingType: "Direct",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_CI_OZ6_CUST_ARD",
    sourceColumn: "CID_CUST_LST_MNT_DTE",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_CI_OZ6_CUST_ARD",
    bronzeColumn: "CID_CUST_LST_MNT_DTE",
    silverSchema: "CORE_CUSTOMERS",
    silverTable: "DIM_CUSTOMER_DEMOGRAPHY",
    silverColumn: "EFFECTIVE_START_DATE",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "DATE",
    businessLogic: "SCD2 effective start date from last maintenance date",
    businessMeaning: "Date this SCD2 version became effective",
    mappingType: "SCD2",
  },
  {
    sourceSystem: "SYSTEM",
    sourceTable: "N/A",
    sourceColumn: "SCD2_LOGIC",
    bronzeSchema: "N/A",
    bronzeTable: "N/A",
    bronzeColumn: "N/A",
    silverSchema: "CORE_CUSTOMERS",
    silverTable: "DIM_CUSTOMER_DEMOGRAPHY",
    silverColumn: "EFFECTIVE_END_DATE",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "DATE",
    businessLogic: "COALESCE(LEAD(EFFECTIVE_START_DATE) OVER (PARTITION BY CUSTOMER_NUMBER ORDER BY EFFECTIVE_START_DATE), '9999-12-31')",
    businessMeaning: "Date this SCD2 version expired (9999-12-31 for current)",
    mappingType: "SCD2",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_CI_OZ6_CUST_ARD",
    sourceColumn: "PRCS_DTE",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_CI_OZ6_CUST_ARD",
    bronzeColumn: "PRCS_DTE",
    silverSchema: "CORE_CUSTOMERS",
    silverTable: "DIM_CUSTOMER_DEMOGRAPHY",
    silverColumn: "BUSINESS_DATE",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "DATE",
    businessLogic: "1:1 mapping from FIS processing date, also available from FIS-DDW as CUST_LST_MAINT_DTE",
    businessMeaning: "Business processing date",
    mappingType: "Direct",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_CI_OZ6_CUST_ARD",
    sourceColumn: "REFRESH_TIME",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_CI_OZ6_CUST_ARD",
    bronzeColumn: "REFRESH_TIME",
    silverSchema: "CORE_CUSTOMERS",
    silverTable: "DIM_CUSTOMER_DEMOGRAPHY",
    silverColumn: "RECORD_DATE",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "DATE",
    businessLogic: "1:1 mapping from source refresh timestamp",
    businessMeaning: "Source data refresh date",
    mappingType: "Direct",
  },
  {
    sourceSystem: "SYSTEM",
    sourceTable: "N/A",
    sourceColumn: "DERIVED",
    bronzeSchema: "N/A",
    bronzeTable: "N/A",
    bronzeColumn: "N/A",
    silverSchema: "CORE_CUSTOMERS",
    silverTable: "DIM_CUSTOMER_DEMOGRAPHY",
    silverColumn: "RECORD_FLAG",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "VARCHAR(16777216)",
    businessLogic: "CASE WHEN EFFECTIVE_END_DATE = '9999-12-31' THEN 'A' ELSE 'I' END",
    businessMeaning: "Active/Inactive record flag (A=Active current record, I=Inactive historical)",
    mappingType: "Derived",
  },
  {
    sourceSystem: "SYSTEM",
    sourceTable: "N/A",
    sourceColumn: "HASH_FUNCTION",
    bronzeSchema: "N/A",
    bronzeTable: "N/A",
    bronzeColumn: "N/A",
    silverSchema: "CORE_CUSTOMERS",
    silverTable: "DIM_CUSTOMER_DEMOGRAPHY",
    silverColumn: "ROW_HASH",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "VARCHAR(16777216)",
    businessLogic: "HASH(CUSTOMER_NUMBER, ETHNIC_CODE, ETHNIC_DESC, GENDER, MARITAL_STATUS_CODE, MARITAL_STATUS_DESC, EDUCATION_CODE, EDUCATION_DESC, INCOME_CODE, INCOME_DESC)",
    businessMeaning: "MD5/SHA hash of all business columns for SCD2 change detection",
    mappingType: "Derived",
  },
  {
    sourceSystem: "SYSTEM",
    sourceTable: "N/A",
    sourceColumn: "CURRENT_USER()",
    bronzeSchema: "N/A",
    bronzeTable: "N/A",
    bronzeColumn: "N/A",
    silverSchema: "CORE_CUSTOMERS",
    silverTable: "DIM_CUSTOMER_DEMOGRAPHY",
    silverColumn: "INSERT_BY",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "VARCHAR(16777216)",
    businessLogic: "CURRENT_USER() - Snowflake ETL user on insert",
    businessMeaning: "User who inserted the record",
    mappingType: "System",
  },
  {
    sourceSystem: "SYSTEM",
    sourceTable: "N/A",
    sourceColumn: "CURRENT_TIMESTAMP()",
    bronzeSchema: "N/A",
    bronzeTable: "N/A",
    bronzeColumn: "N/A",
    silverSchema: "CORE_CUSTOMERS",
    silverTable: "DIM_CUSTOMER_DEMOGRAPHY",
    silverColumn: "INSERT_DT",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "TIMESTAMP_NTZ(9)",
    businessLogic: "CURRENT_TIMESTAMP() on insert",
    businessMeaning: "Timestamp when record was inserted into silver layer",
    mappingType: "System",
  },
  {
    sourceSystem: "SYSTEM",
    sourceTable: "N/A",
    sourceColumn: "CURRENT_USER()",
    bronzeSchema: "N/A",
    bronzeTable: "N/A",
    bronzeColumn: "N/A",
    silverSchema: "CORE_CUSTOMERS",
    silverTable: "DIM_CUSTOMER_DEMOGRAPHY",
    silverColumn: "LAST_MODIFIED_BY",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "VARCHAR(16777216)",
    businessLogic: "CURRENT_USER() - Snowflake ETL user on update",
    businessMeaning: "User who last modified the record",
    mappingType: "System",
  },
  {
    sourceSystem: "SYSTEM",
    sourceTable: "N/A",
    sourceColumn: "CURRENT_TIMESTAMP()",
    bronzeSchema: "N/A",
    bronzeTable: "N/A",
    bronzeColumn: "N/A",
    silverSchema: "CORE_CUSTOMERS",
    silverTable: "DIM_CUSTOMER_DEMOGRAPHY",
    silverColumn: "LAST_MODIFIED_DT",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "TIMESTAMP_NTZ(9)",
    businessLogic: "CURRENT_TIMESTAMP() on update",
    businessMeaning: "Timestamp when record was last modified",
    mappingType: "System",
  },
];

export default dimCustomerDemographyMappings;
