// DIM_CUSTOMER_NAME - Complete STTM Mapping
// Source: STTM Excel - CORE_CUSTOMERS schema
// 19 columns total
// Sources: FIS-ADS (TB_CI_OZ5_CUST_NAAD_ARD_RAW) and FIS-DDW (TB_CI_DZY_C2_CUST_SCD_DIM_RAW)

export interface ColumnMapping {
  sourceSystem: string;
  sourceTable: string;
  sourceColumn: string;
  bronzeSchema: string;
  bronzeTable: string;
  bronzeColumn: string;
  silverSchema: string;
  silverTable: string;
  silverColumn: string;
  goldSchema: string;
  goldTable: string;
  goldColumn: string | null;
  dataType: string;
  businessLogic: string;
  businessMeaning: string;
  mappingType?: "Direct" | "Derived" | "System" | "SCD2";
}

export const dimCustomerNameMappings: ColumnMapping[] = [
  {
    sourceSystem: "SYSTEM",
    sourceTable: "N/A",
    sourceColumn: "AUTO_GENERATED",
    bronzeSchema: "N/A",
    bronzeTable: "N/A",
    bronzeColumn: "N/A",
    silverSchema: "CORE_CUSTOMERS",
    silverTable: "DIM_CUSTOMER_NAME",
    silverColumn: "CUSTOMER_SK",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "NUMBER(38,0)",
    businessLogic: "Auto-generated surrogate key sequence",
    businessMeaning: "Surrogate key for customer name dimension",
    mappingType: "System",
  },
  {
    sourceSystem: "SYSTEM",
    sourceTable: "N/A",
    sourceColumn: "DERIVED_FK",
    bronzeSchema: "N/A",
    bronzeTable: "N/A",
    bronzeColumn: "N/A",
    silverSchema: "CORE_CUSTOMERS",
    silverTable: "DIM_CUSTOMER_NAME",
    silverColumn: "CUSTOMER_NUMBER_FK",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "NUMBER(38,0)",
    businessLogic: "Foreign key lookup to DIM_CUSTOMER",
    businessMeaning: "Customer dimension foreign key reference",
    mappingType: "Derived",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_CI_OZ5_CUST_NAAD_ARD_RAW",
    sourceColumn: "CID_NAAD_APPL_ID",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_CI_OZ5_CUST_NAAD_ARD_RAW",
    bronzeColumn: "CID_NAAD_APPL_ID",
    silverSchema: "CORE_CUSTOMERS",
    silverTable: "DIM_CUSTOMER_NAME",
    silverColumn: "CUSTOMER_NUMBER",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "VARCHAR(16777216)",
    businessLogic: "1:1 mapping from FIS-ADS, also from FIS-DDW as CUST_CIS_NBR",
    businessMeaning: "Unique customer identifier number",
    mappingType: "Direct",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_CI_OZ5_CUST_NAAD_ARD_RAW",
    sourceColumn: "CID_NAAD_KEY_FIELD_2",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_CI_OZ5_CUST_NAAD_ARD_RAW",
    bronzeColumn: "CID_NAAD_KEY_FIELD_2",
    silverSchema: "CORE_CUSTOMERS",
    silverTable: "DIM_CUSTOMER_NAME",
    silverColumn: "FIRST_NAME",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "VARCHAR(16777216)",
    businessLogic: "1:1 mapping with INITCAP(TRIM()) normalization, also from FIS-DDW as FRST_NME (PII - encrypted)",
    businessMeaning: "Customer first name (PII - encrypted for security)",
    mappingType: "Direct",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_CI_OZ5_CUST_NAAD_ARD_RAW",
    sourceColumn: "CID_NAAD_SURNAME",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_CI_OZ5_CUST_NAAD_ARD_RAW",
    bronzeColumn: "CID_NAAD_SURNAME",
    silverSchema: "CORE_CUSTOMERS",
    silverTable: "DIM_CUSTOMER_NAME",
    silverColumn: "LAST_NAME",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "VARCHAR(16777216)",
    businessLogic: "1:1 mapping with INITCAP(TRIM()) normalization, also from FIS-DDW as LST_NME (PII - encrypted)",
    businessMeaning: "Customer last name/surname (PII - encrypted for security)",
    mappingType: "Direct",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_CI_OZ5_CUST_NAAD_ARD_RAW",
    sourceColumn: "CID_NAAD_KEY_FIELD_3",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_CI_OZ5_CUST_NAAD_ARD_RAW",
    bronzeColumn: "CID_NAAD_KEY_FIELD_3",
    silverSchema: "CORE_CUSTOMERS",
    silverTable: "DIM_CUSTOMER_NAME",
    silverColumn: "MIDDLE_NAME_1",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "VARCHAR(16777216)",
    businessLogic: "1:1 mapping with INITCAP(TRIM()) normalization, also from FIS-DDW as MID_1_NME",
    businessMeaning: "Customer first middle name",
    mappingType: "Direct",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_CI_OZ5_CUST_NAAD_ARD_RAW",
    sourceColumn: "CID_NAAD_KEY_FIELD_4",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_CI_OZ5_CUST_NAAD_ARD_RAW",
    bronzeColumn: "CID_NAAD_KEY_FIELD_4",
    silverSchema: "CORE_CUSTOMERS",
    silverTable: "DIM_CUSTOMER_NAME",
    silverColumn: "MIDDLE_NAME_2",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "VARCHAR(16777216)",
    businessLogic: "1:1 mapping with INITCAP(TRIM()) normalization, also from FIS-DDW as MID_2_NME",
    businessMeaning: "Customer second middle name",
    mappingType: "Direct",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_CI_OZ5_CUST_NAAD_ARD_RAW",
    sourceColumn: "CID_NAAD_NAME_LINE",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_CI_OZ5_CUST_NAAD_ARD_RAW",
    bronzeColumn: "CID_NAAD_NAME_LINE",
    silverSchema: "CORE_CUSTOMERS",
    silverTable: "DIM_CUSTOMER_NAME",
    silverColumn: "CUSTOMER_NAME",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "VARCHAR(16777216)",
    businessLogic: "Full name line, also from FIS-DDW as NME_LNE_TXT",
    businessMeaning: "Complete customer name as single line",
    mappingType: "Direct",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_CI_OZ5_CUST_NAAD_ARD_RAW",
    sourceColumn: "CID_NAAD_CUST_TYPE_CDE",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_CI_OZ5_CUST_NAAD_ARD_RAW",
    bronzeColumn: "CID_NAAD_CUST_TYPE_CDE",
    silverSchema: "CORE_CUSTOMERS",
    silverTable: "DIM_CUSTOMER_NAME",
    silverColumn: "CUSTOMERS_TYPE_CODE",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "VARCHAR(16777216)",
    businessLogic: "1:1 mapping (I=Individual, C=Corporate, P=Partnership), also from FIS-DDW as REC_TYP_CDE",
    businessMeaning: "Customer type code classification",
    mappingType: "Direct",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_CI_OZ5_CUST_NAAD_ARD_RAW",
    sourceColumn: "CID_NAAD_CUST_TYPE_CDE",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_CI_OZ5_CUST_NAAD_ARD_RAW",
    bronzeColumn: "CID_NAAD_CUST_TYPE_CDE",
    silverSchema: "CORE_CUSTOMERS",
    silverTable: "DIM_CUSTOMER_NAME",
    silverColumn: "CUSTOMERS_TYPE_DESC",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "VARCHAR(16777216)",
    businessLogic: "Derived description from code mapping, also from FIS-DDW as REC_TYP_CDE",
    businessMeaning: "Customer type description (Individual, Corporate, Partnership, etc.)",
    mappingType: "Derived",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_CI_OZ5_CUST_NAAD_ARD_RAW",
    sourceColumn: "CID_NAAD_NAME_LAST_CHG_DTE",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_CI_OZ5_CUST_NAAD_ARD_RAW",
    bronzeColumn: "CID_NAAD_NAME_LAST_CHG_DTE",
    silverSchema: "CORE_CUSTOMERS",
    silverTable: "DIM_CUSTOMER_NAME",
    silverColumn: "EFFECTIVE_START_DATE",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "TIMESTAMP_NTZ(9)",
    businessLogic: "SCD2 effective start date from last name change date, also from FIS-DDW as EFF_DTE",
    businessMeaning: "Date this name version became effective",
    mappingType: "SCD2",
  },
  {
    sourceSystem: "SYSTEM",
    sourceTable: "N/A",
    sourceColumn: "SCD2_LOGIC",
    bronzeSchema: "N/A",
    bronzeTable: "N/A",
    bronzeColumn: "N/A",
    silverSchema: "CORE_CUSTOMERS",
    silverTable: "DIM_CUSTOMER_NAME",
    silverColumn: "EFFECTIVE_END_DATE",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "TIMESTAMP_NTZ(9)",
    businessLogic: "COALESCE(LEAD(EFFECTIVE_START_DATE) OVER (PARTITION BY CUSTOMER_NUMBER ORDER BY EFFECTIVE_START_DATE), '9999-12-31')",
    businessMeaning: "Date this name version expired (9999-12-31 for current)",
    mappingType: "SCD2",
  },
  {
    sourceSystem: "SYSTEM",
    sourceTable: "N/A",
    sourceColumn: "DERIVED",
    bronzeSchema: "N/A",
    bronzeTable: "N/A",
    bronzeColumn: "N/A",
    silverSchema: "CORE_CUSTOMERS",
    silverTable: "DIM_CUSTOMER_NAME",
    silverColumn: "RECORD_FLAG",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "VARCHAR(16777216)",
    businessLogic: "CASE WHEN EFFECTIVE_END_DATE::DATE = TO_DATE('9999-12-31') THEN 'A' ELSE 'I' END",
    businessMeaning: "Active/Inactive record flag",
    mappingType: "Derived",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "VW_TB_CI_DZY_C2_CUST_SCD_DIM",
    sourceColumn: "PRCS_DTE",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "VW_TB_CI_DZY_C2_CUST_SCD_DIM",
    bronzeColumn: "PRCS_DTE",
    silverSchema: "CORE_CUSTOMERS",
    silverTable: "DIM_CUSTOMER_NAME",
    silverColumn: "BUSINESS_DATE",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "TIMESTAMP_NTZ(9)",
    businessLogic: "1:1 mapping from FIS processing date, also from FIS-DDW as EFF_DTE",
    businessMeaning: "Business processing date",
    mappingType: "Direct",
  },
  {
    sourceSystem: "SYSTEM",
    sourceTable: "N/A",
    sourceColumn: "HASH_FUNCTION",
    bronzeSchema: "N/A",
    bronzeTable: "N/A",
    bronzeColumn: "N/A",
    silverSchema: "CORE_CUSTOMERS",
    silverTable: "DIM_CUSTOMER_NAME",
    silverColumn: "ROW_HASH",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "VARCHAR(16777216)",
    businessLogic: "HASH(CUSTOMER_NUMBER, FIRST_NAME, LAST_NAME, MIDDLE_NAME_1, MIDDLE_NAME_2, CUSTOMER_NAME, CUSTOMERS_TYPE_CODE)",
    businessMeaning: "Hash of name columns for SCD2 change detection",
    mappingType: "Derived",
  },
  {
    sourceSystem: "SYSTEM",
    sourceTable: "N/A",
    sourceColumn: "CURRENT_USER()",
    bronzeSchema: "N/A",
    bronzeTable: "N/A",
    bronzeColumn: "N/A",
    silverSchema: "CORE_CUSTOMERS",
    silverTable: "DIM_CUSTOMER_NAME",
    silverColumn: "INSERT_BY",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "VARCHAR(16777216)",
    businessLogic: "CURRENT_USER() on insert",
    businessMeaning: "User who inserted the record",
    mappingType: "System",
  },
  {
    sourceSystem: "SYSTEM",
    sourceTable: "N/A",
    sourceColumn: "CURRENT_TIMESTAMP()",
    bronzeSchema: "N/A",
    bronzeTable: "N/A",
    bronzeColumn: "N/A",
    silverSchema: "CORE_CUSTOMERS",
    silverTable: "DIM_CUSTOMER_NAME",
    silverColumn: "INSERT_DT",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "TIMESTAMP_NTZ(9)",
    businessLogic: "CURRENT_TIMESTAMP() on insert",
    businessMeaning: "Timestamp when record was inserted",
    mappingType: "System",
  },
  {
    sourceSystem: "SYSTEM",
    sourceTable: "N/A",
    sourceColumn: "CURRENT_USER()",
    bronzeSchema: "N/A",
    bronzeTable: "N/A",
    bronzeColumn: "N/A",
    silverSchema: "CORE_CUSTOMERS",
    silverTable: "DIM_CUSTOMER_NAME",
    silverColumn: "LAST_MODIFIED_BY",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "VARCHAR(16777216)",
    businessLogic: "CURRENT_USER() on update",
    businessMeaning: "User who last modified the record",
    mappingType: "System",
  },
  {
    sourceSystem: "SYSTEM",
    sourceTable: "N/A",
    sourceColumn: "CURRENT_TIMESTAMP()",
    bronzeSchema: "N/A",
    bronzeTable: "N/A",
    bronzeColumn: "N/A",
    silverSchema: "CORE_CUSTOMERS",
    silverTable: "DIM_CUSTOMER_NAME",
    silverColumn: "LAST_MODIFIED_DT",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "TIMESTAMP_NTZ(9)",
    businessLogic: "CURRENT_TIMESTAMP() on update",
    businessMeaning: "Timestamp when record was last modified",
    mappingType: "System",
  },
];

export default dimCustomerNameMappings;
