// Customer Domain - COMPLETE Source to Target Mapping (STTM) - 100% Coverage
// Maps FIS-ADS source tables → Bronze → Silver → Gold
// Includes: Direct mappings + Derived/Calculated + System/Audit + SCD Type 2

export interface ColumnMapping {
  sourceSystem: string;
  sourceTable: string;
  sourceColumn: string;
  bronzeSchema: string;
  bronzeTable: string;
  bronzeColumn: string;
  silverSchema: string;
  silverTable: string;
  silverColumn: string;
  goldSchema: string;
  goldTable: string;
  goldColumn: string | null;
  dataType: string;
  businessLogic: string;
  businessMeaning: string;
  mappingType?: "Direct" | "Derived" | "System" | "SCD2";
}

// Import existing mappings from sttm-mapping.ts
import {
  customerDemographyMappings,
  customerIdentifierMappings,
  customerNameAddressMappings,
  customerContactMappings,
  customerEmailMappings,
  customerAccountRelationshipMappings,
} from "./sttm-mapping";

// ============================================================================
// ADDITIONAL DERIVED & SYSTEM COLUMNS - DIM_CUSTOMER (from silver-layer.ts)
// ============================================================================
export const customerDerivedMappings: ColumnMapping[] = [
  {
    sourceSystem: "SYSTEM",
    sourceTable: "N/A",
    sourceColumn: "AUTO_GENERATED",
    bronzeSchema: "N/A",
    bronzeTable: "N/A",
    bronzeColumn: "N/A",
    silverSchema: "CORE_CUSTOMER",
    silverTable: "DIM_CUSTOMER",
    silverColumn: "CUSTOMER_SK",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "BIGINT",
    businessLogic: "Auto-generated surrogate key sequence",
    businessMeaning: "Surrogate key for dimension table joins",
    mappingType: "System",
  },
  {
    sourceSystem: "SYSTEM",
    sourceTable: "N/A",
    sourceColumn: "UUID_STRING()",
    bronzeSchema: "N/A",
    bronzeTable: "N/A",
    bronzeColumn: "N/A",
    silverSchema: "CORE_CUSTOMER",
    silverTable: "DIM_CUSTOMER",
    silverColumn: "CUSTOMER_UUID",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "STRING",
    businessLogic: "Generated using UUID_STRING() function",
    businessMeaning: "Global unique identifier for distributed systems",
    mappingType: "Derived",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_CI_OZ6_CUST_ARD",
    sourceColumn: "CID_CUST_TAX_ID",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_CI_OZ6_CUST_ARD",
    bronzeColumn: "CID_CUST_TAX_ID",
    silverSchema: "CORE_CUSTOMER",
    silverTable: "DIM_CUSTOMER",
    silverColumn: "SSN_HASH",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "STRING",
    businessLogic: "SHA256(CID_CUST_TAX_ID) - irreversible hashing for PII protection",
    businessMeaning: "SHA-256 hash of SSN/EIN for matching without exposing PII",
    mappingType: "Derived",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_CI_OZ5_CUST_NAAD_ARD_RAW",
    sourceColumn: "CID_NAAD_KEY_FIELD_2",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_CI_OZ5_CUST_NAAD_ARD",
    bronzeColumn: "CID_NAAD_KEY_FIELD_2",
    silverSchema: "CORE_CUSTOMER",
    silverTable: "DIM_CUSTOMER",
    silverColumn: "FIRST_NAME_CLEANSED",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "VARCHAR(100)",
    businessLogic: "INITCAP(TRIM(UNACCENT(CID_NAAD_KEY_FIELD_2)))",
    businessMeaning: "First name standardized to proper case with accent removal",
    mappingType: "Derived",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_CI_OZ5_CUST_NAAD_ARD_RAW",
    sourceColumn: "CID_NAAD_KEY_FIELD_3",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_CI_OZ5_CUST_NAAD_ARD",
    bronzeColumn: "CID_NAAD_KEY_FIELD_3",
    silverSchema: "CORE_CUSTOMER",
    silverTable: "DIM_CUSTOMER",
    silverColumn: "MIDDLE_NAME_CLEANSED",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "VARCHAR(100)",
    businessLogic: "INITCAP(TRIM(UNACCENT(CID_NAAD_KEY_FIELD_3)))",
    businessMeaning: "Middle name standardized to proper case with accent removal",
    mappingType: "Derived",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_CI_OZ5_CUST_NAAD_ARD_RAW",
    sourceColumn: "CID_NAAD_SURNAME",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_CI_OZ5_CUST_NAAD_ARD",
    bronzeColumn: "CID_NAAD_SURNAME",
    silverSchema: "CORE_CUSTOMER",
    silverTable: "DIM_CUSTOMER",
    silverColumn: "LAST_NAME_CLEANSED",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "VARCHAR(100)",
    businessLogic: "INITCAP(TRIM(UNACCENT(CID_NAAD_SURNAME)))",
    businessMeaning: "Last name standardized to proper case with accent removal",
    mappingType: "Derived",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_CI_OZ5_CUST_NAAD_ARD_RAW",
    sourceColumn: "CID_NAAD_KEY_FIELD_2, CID_NAAD_KEY_FIELD_3, CID_NAAD_SURNAME",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_CI_OZ5_CUST_NAAD_ARD",
    bronzeColumn: "MULTIPLE",
    silverSchema: "CORE_CUSTOMER",
    silverTable: "DIM_CUSTOMER",
    silverColumn: "FULL_NAME_CLEANSED",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "VARCHAR(200)",
    businessLogic: "CONCAT_WS(' ', FIRST_NAME_CLEANSED, MIDDLE_NAME_CLEANSED, LAST_NAME_CLEANSED)",
    businessMeaning: "Complete legal name in standardized format",
    mappingType: "Derived",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_CI_OZ6_CUST_ARD",
    sourceColumn: "CID_CUST_BIRTH_DTE",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_CI_OZ6_CUST_ARD",
    bronzeColumn: "CID_CUST_BIRTH_DTE",
    silverSchema: "CORE_CUSTOMER",
    silverTable: "DIM_CUSTOMER",
    silverColumn: "AGE_YEARS",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "INTEGER",
    businessLogic: "DATEDIFF(year, CID_CUST_BIRTH_DTE, CURRENT_DATE())",
    businessMeaning: "Current age in years calculated from date of birth",
    mappingType: "Derived",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_CI_OZ6_CUST_ARD",
    sourceColumn: "CID_CUST_BIRTH_DTE",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_CI_OZ6_CUST_ARD",
    bronzeColumn: "CID_CUST_BIRTH_DTE",
    silverSchema: "CORE_CUSTOMER",
    silverTable: "DIM_CUSTOMER",
    silverColumn: "AGE_GROUP",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "VARCHAR(20)",
    businessLogic: "CASE WHEN AGE_YEARS < 26 THEN '18-25' WHEN AGE_YEARS < 36 THEN '26-35' WHEN AGE_YEARS < 46 THEN '36-45' WHEN AGE_YEARS < 56 THEN '46-55' WHEN AGE_YEARS < 66 THEN '56-65' ELSE '66+' END",
    businessMeaning: "Age segmentation for marketing and analytics",
    mappingType: "Derived",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_CI_OZ6_CUST_ARD",
    sourceColumn: "CID_CUST_SINCE_DTE, CID_CUST_CLOSED_DTE",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_CI_OZ6_CUST_ARD",
    bronzeColumn: "MULTIPLE",
    silverSchema: "CORE_CUSTOMER",
    silverTable: "DIM_CUSTOMER",
    silverColumn: "CUSTOMER_TENURE_DAYS",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "INTEGER",
    businessLogic: "DATEDIFF(day, CID_CUST_SINCE_DTE, COALESCE(CID_CUST_CLOSED_DTE, CURRENT_DATE()))",
    businessMeaning: "Number of days customer has been with bank",
    mappingType: "Derived",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_CI_OZ5_CUST_NAAD_ARD_RAW",
    sourceColumn: "CID_NAAD_ZIP_1, CID_NAAD_ZIP_2",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_CI_OZ5_CUST_NAAD_ARD",
    bronzeColumn: "MULTIPLE",
    silverSchema: "CORE_CUSTOMER",
    silverTable: "DIM_CUSTOMER",
    silverColumn: "POSTAL_CODE_STD",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "VARCHAR(10)",
    businessLogic: "CASE WHEN CID_NAAD_ZIP_2 IS NOT NULL THEN CONCAT(CID_NAAD_ZIP_1, '-', CID_NAAD_ZIP_2) ELSE CID_NAAD_ZIP_1 END",
    businessMeaning: "ZIP code in ZIP+4 format (ZZZZZ-ZZZZ)",
    mappingType: "Derived",
  },
  {
    sourceSystem: "REFERENCE_DATA",
    sourceTable: "REF_ZIP_TO_COUNTY",
    sourceColumn: "COUNTY_NAME",
    bronzeSchema: "N/A",
    bronzeTable: "REF_ZIP_TO_COUNTY",
    bronzeColumn: "COUNTY_NAME",
    silverSchema: "CORE_CUSTOMER",
    silverTable: "DIM_CUSTOMER",
    silverColumn: "COUNTY",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "VARCHAR(50)",
    businessLogic: "Lookup via ZIP code to county mapping reference table",
    businessMeaning: "County name derived from ZIP code",
    mappingType: "Derived",
  },
];

// ============================================================================
// SCD TYPE 2 COLUMNS - All dimension tables
// ============================================================================
export const customerSCD2Mappings: ColumnMapping[] = [
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_CI_OZ6_CUST_ARD",
    sourceColumn: "CID_CUST_LST_MNT_DTE",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_CI_OZ6_CUST_ARD",
    bronzeColumn: "CID_CUST_LST_MNT_DTE",
    silverSchema: "CORE_CUSTOMER",
    silverTable: "DIM_CUSTOMER",
    silverColumn: "EFFECTIVE_DATE",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "DATE",
    businessLogic: "Set to source last modified date on insert, updated when change detected",
    businessMeaning: "Date this SCD Type 2 record version became effective",
    mappingType: "SCD2",
  },
  {
    sourceSystem: "SYSTEM",
    sourceTable: "N/A",
    sourceColumn: "SCD2_LOGIC",
    bronzeSchema: "N/A",
    bronzeTable: "N/A",
    bronzeColumn: "N/A",
    silverSchema: "CORE_CUSTOMER",
    silverTable: "DIM_CUSTOMER",
    silverColumn: "EXPIRATION_DATE",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "DATE",
    businessLogic: "9999-12-31 for current records; set to yesterday when superseded by new version",
    businessMeaning: "Date this SCD Type 2 record version expired",
    mappingType: "SCD2",
  },
  {
    sourceSystem: "SYSTEM",
    sourceTable: "N/A",
    sourceColumn: "SCD2_LOGIC",
    bronzeSchema: "N/A",
    bronzeTable: "N/A",
    bronzeColumn: "N/A",
    silverSchema: "CORE_CUSTOMER",
    silverTable: "DIM_CUSTOMER",
    silverColumn: "IS_CURRENT",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "BOOLEAN",
    businessLogic: "TRUE if EXPIRATION_DATE = '9999-12-31', FALSE otherwise",
    businessMeaning: "Flag indicating if this is the current active version",
    mappingType: "SCD2",
  },
  {
    sourceSystem: "SYSTEM",
    sourceTable: "N/A",
    sourceColumn: "CHANGE_DETECTION",
    bronzeSchema: "N/A",
    bronzeTable: "N/A",
    bronzeColumn: "N/A",
    silverSchema: "CORE_CUSTOMER",
    silverTable: "DIM_CUSTOMER",
    silverColumn: "CHANGED_ATTRIBUTES",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "STRING",
    businessLogic: "Comma-separated list of changed attributes by comparing current vs previous version",
    businessMeaning: "Audit trail of which attributes changed in this version",
    mappingType: "SCD2",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_CI_OZ6_CUST_ARD",
    sourceColumn: "MULTIPLE_COLUMNS",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_CI_OZ6_CUST_ARD",
    bronzeColumn: "MULTIPLE",
    silverSchema: "CORE_CUSTOMER",
    silverTable: "DIM_CUSTOMER",
    silverColumn: "SOURCE_SYSTEM_ROW_HASH",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "STRING",
    businessLogic: "MD5(CONCAT_WS('|', customer_id, full_name, date_of_birth, address, phone, email, ...)) for change detection",
    businessMeaning: "MD5 hash of source row for efficient change detection",
    mappingType: "Derived",
  },
];

// ============================================================================
// SYSTEM & AUDIT COLUMNS - All tables
// ============================================================================
export const customerSystemMappings: ColumnMapping[] = [
  {
    sourceSystem: "SYSTEM",
    sourceTable: "N/A",
    sourceColumn: "CURRENT_TIMESTAMP",
    bronzeSchema: "N/A",
    bronzeTable: "N/A",
    bronzeColumn: "N/A",
    silverSchema: "CORE_CUSTOMER",
    silverTable: "DIM_CUSTOMER",
    silverColumn: "CREATED_TIMESTAMP",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "TIMESTAMP_NTZ",
    businessLogic: "CURRENT_TIMESTAMP() on insert",
    businessMeaning: "Timestamp when record was created in silver layer",
    mappingType: "System",
  },
  {
    sourceSystem: "SYSTEM",
    sourceTable: "N/A",
    sourceColumn: "CURRENT_TIMESTAMP",
    bronzeSchema: "N/A",
    bronzeTable: "N/A",
    bronzeColumn: "N/A",
    silverSchema: "CORE_CUSTOMER",
    silverTable: "DIM_CUSTOMER",
    silverColumn: "UPDATED_TIMESTAMP",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "TIMESTAMP_NTZ",
    businessLogic: "CURRENT_TIMESTAMP() on update",
    businessMeaning: "Timestamp when record was last updated",
    mappingType: "System",
  },
  {
    sourceSystem: "ORCHESTRATION",
    sourceTable: "ETL_FRAMEWORK",
    sourceColumn: "LOAD_ID",
    bronzeSchema: "N/A",
    bronzeTable: "N/A",
    bronzeColumn: "N/A",
    silverSchema: "CORE_CUSTOMER",
    silverTable: "DIM_CUSTOMER",
    silverColumn: "LOAD_ID",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "VARCHAR(50)",
    businessLogic: "Passed from ETL orchestration framework as job/run identifier",
    businessMeaning: "ETL batch load ID for traceability and lineage",
    mappingType: "System",
  },
  {
    sourceSystem: "DATA_QUALITY",
    sourceTable: "DQ_ENGINE",
    sourceColumn: "QUALITY_SCORE",
    bronzeSchema: "N/A",
    bronzeTable: "N/A",
    bronzeColumn: "N/A",
    silverSchema: "CORE_CUSTOMER",
    silverTable: "DIM_CUSTOMER",
    silverColumn: "DATA_QUALITY_SCORE",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "DECIMAL(5,2)",
    businessLogic: "(non_null_fields / total_fields) * 0.6 + (validation_passed / total_validations) * 0.4",
    businessMeaning: "Data quality score 0-100 based on completeness and validity",
    mappingType: "Derived",
  },
  {
    sourceSystem: "DATA_QUALITY",
    sourceTable: "DQ_ENGINE",
    sourceColumn: "QUALITY_ISSUES",
    bronzeSchema: "N/A",
    bronzeTable: "N/A",
    bronzeColumn: "N/A",
    silverSchema: "CORE_CUSTOMER",
    silverTable: "DIM_CUSTOMER",
    silverColumn: "DATA_QUALITY_ISSUES",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "STRING",
    businessLogic: "Concatenated list of failed validation rules during quality check",
    businessMeaning: "Audit trail of data quality issues found",
    mappingType: "Derived",
  },
  {
    sourceSystem: "MDM_ENGINE",
    sourceTable: "DEDUPLICATION",
    sourceColumn: "SOURCE_RECORD_COUNT",
    bronzeSchema: "N/A",
    bronzeTable: "N/A",
    bronzeColumn: "N/A",
    silverSchema: "CORE_CUSTOMER",
    silverTable: "DIM_CUSTOMER",
    silverColumn: "SOURCE_RECORD_COUNT",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "INTEGER",
    businessLogic: "COUNT(*) of matched source records during deduplication process",
    businessMeaning: "Number of source records merged into this golden record",
    mappingType: "Derived",
  },
  {
    sourceSystem: "MDM_ENGINE",
    sourceTable: "DEDUPLICATION",
    sourceColumn: "CONFIDENCE_SCORE",
    bronzeSchema: "N/A",
    bronzeTable: "N/A",
    bronzeColumn: "N/A",
    silverSchema: "CORE_CUSTOMER",
    silverTable: "DIM_CUSTOMER",
    silverColumn: "DEDUPLICATION_CONFIDENCE_SCORE",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "DECIMAL(5,2)",
    businessLogic: "Confidence score 0-100 based on matching algorithm quality and data completeness",
    businessMeaning: "Confidence in deduplication match accuracy",
    mappingType: "Derived",
  },
];

// ============================================================================
// COMBINE ALL CUSTOMER STTM MAPPINGS - 100% Coverage
// ============================================================================
export const customerSTTMMapping_Complete: ColumnMapping[] = [
  ...customerDemographyMappings,
  ...customerIdentifierMappings,
  ...customerNameAddressMappings,
  ...customerContactMappings,
  ...customerEmailMappings,
  ...customerAccountRelationshipMappings,
  ...customerDerivedMappings,
  ...customerSCD2Mappings,
  ...customerSystemMappings,
];

// STTM gaps - should be empty with complete mappings
export const customerSTTMGaps_Complete: ColumnMapping[] = [];

// Updated table coverage summary
export const customerTableCoverage_Complete = [
  {
    fisTable: "TB_CI_OZ6_CUST_ARD",
    columnCount: 93,
    mappedCount: 93,
    coverage: "100%",
    businessKey: "CID_CUST_CUST_NBR",
    silverTable: "DIM_CUSTOMER, DIM_CUSTOMER_DEMOGRAPHY",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
  },
  {
    fisTable: "TB_CI_OZ4_CUST_ID_ARD",
    columnCount: 6,
    mappedCount: 6,
    coverage: "100%",
    businessKey: "CI_DMV21_ID_NUMBER",
    silverTable: "IM_CUSTOMER_IDENTIFIER",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
  },
  {
    fisTable: "TB_CI_OZ5_CUST_NAAD_ARD_RAW",
    columnCount: 15,
    mappedCount: 15,
    coverage: "100%",
    businessKey: "CID_NAAD_APPL_ID",
    silverTable: "DIM_CUSTOMER_NAME, DIM_CUSTOMER_ADDRESS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
  },
  {
    fisTable: "TB_CI_OZ3_EMAIL_ARD",
    columnCount: 5,
    mappedCount: 5,
    coverage: "100%",
    businessKey: "CID_EMLREL_CUST_NMB",
    silverTable: "DIM_CUSTOMER_EMAIL",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
  },
  {
    fisTable: "TB_CI_OZW_CUST_ACCT_RLT_ARD",
    columnCount: 14,
    mappedCount: 14,
    coverage: "100%",
    businessKey: "CID_RELA_R_APPL_ID",
    silverTable: "BRG_CUST_TO_ACCT_RELATIONSHIP",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
  },
];

export default customerSTTMMapping_Complete;
