/**
 * DEPOSITS DOMAIN - GOLD LAYER - DDL SPECIFICATIONS
 *
 * Aggregated analytics layer optimized for BI reporting
 * Contains FACT tables for transactions and balances
 * DIMENSION tables for accounts and deposits
 * AGGREGATE table for customer-deposit consolidated view
 * Source: CORE_DEPOSIT (Silver) + CORE_CUSTOMERS (Silver)
 */

export interface GoldTableColumn {
  columnName: string;
  dataType: string;
  sourceSchema: string;
  sourceTable: string;
  sourceColumn: string;
  businessMeaning: string;
  nullable: boolean;
}

export interface GoldTableSpec {
  name: string;
  schema: string;
  type: "FACT" | "DIMENSION" | "AGGREGATE";
  grain: string;
  description: string;
  columns: GoldTableColumn[];
  estimatedRows: number;
  updateFrequency: string;
  primaryKey: string[];
  partitionBy?: string;
  clusterBy?: string[];
}

// ============================================================================
// FCT_DEPOSIT_DAILY_BALANCE - Deposit Daily Balance Fact Table
// ============================================================================
export const fctDepositDailyBalanceTable: GoldTableSpec = {
  name: "FCT_DEPOSIT_DAILY_BALANCE",
  schema: "ANALYTICS",
  type: "FACT",
  grain: "One row per account per day",
  description: "Daily deposit account balance metrics and calculations for all deposit accounts",
  columns: [
    {
      columnName: "ACCOUNT_NUMBER",
      dataType: "VARCHAR(20)",
      sourceSchema: "CORE_DEPOSIT",
      sourceTable: "DIM_ACCOUNT",
      sourceColumn: "ACCOUNT_NUMBER",
      businessMeaning: "Unique account identifier",
      nullable: false,
    },
    {
      columnName: "BALANCE_DATE",
      dataType: "DATE",
      sourceSchema: "CORE_DEPOSIT",
      sourceTable: "FCT_DEPOSIT_DAILY_BALANCE",
      sourceColumn: "BALANCE_DATE",
      businessMeaning: "Date of balance snapshot",
      nullable: false,
    },
    {
      columnName: "CUSTOMER_NUMBER",
      dataType: "VARCHAR(50)",
      sourceSchema: "CORE_CUSTOMERS",
      sourceTable: "DIM_CUSTOMER",
      sourceColumn: "CUSTOMER_NUMBER",
      businessMeaning: "Customer account owner",
      nullable: false,
    },
    {
      columnName: "CURRENT_BALANCE",
      dataType: "DECIMAL(18,2)",
      sourceSchema: "CORE_DEPOSIT",
      sourceTable: "FCT_DEPOSIT_DAILY_BALANCE",
      sourceColumn: "CURRENT_BALANCE_AMOUNT",
      businessMeaning: "Ledger/current balance at end of day",
      nullable: false,
    },
    {
      columnName: "AVAILABLE_BALANCE",
      dataType: "DECIMAL(18,2)",
      sourceSchema: "CORE_DEPOSIT",
      sourceTable: "FCT_DEPOSIT_DAILY_BALANCE",
      sourceColumn: "AVAILABLE_BALANCE_AMOUNT",
      businessMeaning: "Available balance for withdrawal/debit",
      nullable: false,
    },
    {
      columnName: "PENDING_DEBIT_AMOUNT",
      dataType: "DECIMAL(18,2)",
      sourceSchema: "CORE_DEPOSIT",
      sourceTable: "FCT_DEPOSIT_DAILY_BALANCE",
      sourceColumn: "PENDING_DEBIT_AMOUNT",
      businessMeaning: "Pending debit holds and authorizations",
      nullable: true,
    },
    {
      columnName: "PENDING_CREDIT_AMOUNT",
      dataType: "DECIMAL(18,2)",
      sourceSchema: "CORE_DEPOSIT",
      sourceTable: "FCT_DEPOSIT_DAILY_BALANCE",
      sourceColumn: "PENDING_CREDIT_AMOUNT",
      businessMeaning: "Pending incoming credits",
      nullable: true,
    },
    {
      columnName: "AVERAGE_BALANCE_MTD",
      dataType: "DECIMAL(18,2)",
      sourceSchema: "CORE_DEPOSIT",
      sourceTable: "FCT_DEPOSIT_DAILY_BALANCE",
      sourceColumn: "AVERAGE_LEDGER_BALANCE_MTD",
      businessMeaning: "Month-to-date average balance",
      nullable: true,
    },
    {
      columnName: "AVERAGE_BALANCE_YTD",
      dataType: "DECIMAL(18,2)",
      sourceSchema: "CORE_DEPOSIT",
      sourceTable: "FCT_DEPOSIT_DAILY_BALANCE",
      sourceColumn: "AVERAGE_LEDGER_BALANCE_YTD",
      businessMeaning: "Year-to-date average balance",
      nullable: true,
    },
    {
      columnName: "INTEREST_PAID_MTD",
      dataType: "DECIMAL(18,6)",
      sourceSchema: "CORE_DEPOSIT",
      sourceTable: "FCT_DEPOSIT_DAILY_BALANCE",
      sourceColumn: "INTEREST_PAID_MTD_AMOUNT",
      businessMeaning: "Interest paid month-to-date",
      nullable: true,
    },
    {
      columnName: "INTEREST_PAID_YTD",
      dataType: "DECIMAL(18,6)",
      sourceSchema: "CORE_DEPOSIT",
      sourceTable: "FCT_DEPOSIT_DAILY_BALANCE",
      sourceColumn: "INTEREST_PAID_YTD_AMOUNT",
      businessMeaning: "Interest paid year-to-date",
      nullable: true,
    },
    {
      columnName: "ACCOUNT_TIER",
      dataType: "VARCHAR(20)",
      sourceSchema: "CORE_DEPOSIT",
      sourceTable: "DIM_ACCOUNT",
      sourceColumn: "TIER_NAME",
      businessMeaning: "Account tier (Gold, Platinum, Standard)",
      nullable: true,
    },
    {
      columnName: "ACCOUNT_TYPE",
      dataType: "VARCHAR(20)",
      sourceSchema: "CORE_DEPOSIT",
      sourceTable: "DIM_ACCOUNT",
      sourceColumn: "ACCOUNT_TYPE",
      businessMeaning: "Account type (CHK, SAV, CD, IRA)",
      nullable: false,
    },
    {
      columnName: "ACCOUNT_STATUS",
      dataType: "VARCHAR(20)",
      sourceSchema: "CORE_DEPOSIT",
      sourceTable: "DIM_ACCOUNT",
      sourceColumn: "ACCOUNT_STATUS",
      businessMeaning: "Account status (ACTIVE, INACTIVE, CLOSED, DORMANT)",
      nullable: false,
    },
    {
      columnName: "DATA_LOAD_DATE",
      dataType: "DATE",
      sourceSchema: "SYSTEM",
      sourceTable: "SYSTEM_DATE",
      sourceColumn: "CURRENT_DATE",
      businessMeaning: "System load date",
      nullable: false,
    },
  ],
  estimatedRows: 18250000000,
  updateFrequency: "Daily",
  primaryKey: ["ACCOUNT_NUMBER", "BALANCE_DATE"],
  partitionBy: "BALANCE_DATE",
  clusterBy: ["ACCOUNT_NUMBER", "CUSTOMER_NUMBER"],
};

// ============================================================================
// FCT_DEPOSIT_ACCOUNT_TRANSACTION - Deposit Account Transactions Fact Table
// ============================================================================
export const fctDepositAccountTransactionTable: GoldTableSpec = {
  name: "FCT_DEPOSIT_ACCOUNT_TRANSACTION",
  schema: "ANALYTICS",
  type: "FACT",
  grain: "One row per transaction",
  description: "Individual transaction details for all deposit accounts (debits, credits, transfers)",
  columns: [
    {
      columnName: "TRANSACTION_ID",
      dataType: "VARCHAR(50)",
      sourceSchema: "CORE_DEPOSIT",
      sourceTable: "FCT_DEPOSIT_TRANSACTION",
      sourceColumn: "TRANSACTION_ID",
      businessMeaning: "Unique transaction identifier",
      nullable: false,
    },
    {
      columnName: "ACCOUNT_NUMBER",
      dataType: "VARCHAR(20)",
      sourceSchema: "CORE_DEPOSIT",
      sourceTable: "DIM_ACCOUNT",
      sourceColumn: "ACCOUNT_NUMBER",
      businessMeaning: "Account number",
      nullable: false,
    },
    {
      columnName: "CUSTOMER_NUMBER",
      dataType: "VARCHAR(50)",
      sourceSchema: "CORE_CUSTOMERS",
      sourceTable: "DIM_CUSTOMER",
      sourceColumn: "CUSTOMER_NUMBER",
      businessMeaning: "Customer account owner",
      nullable: false,
    },
    {
      columnName: "TRANSACTION_DATE",
      dataType: "DATE",
      sourceSchema: "CORE_DEPOSIT",
      sourceTable: "FCT_DEPOSIT_TRANSACTION",
      sourceColumn: "TRANSACTION_DATE",
      businessMeaning: "Date transaction occurred",
      nullable: false,
    },
    {
      columnName: "POST_DATE",
      dataType: "DATE",
      sourceSchema: "CORE_DEPOSIT",
      sourceTable: "FCT_DEPOSIT_TRANSACTION",
      sourceColumn: "POST_DATE",
      businessMeaning: "Date transaction posted to account",
      nullable: false,
    },
    {
      columnName: "TRANSACTION_TYPE",
      dataType: "VARCHAR(20)",
      sourceSchema: "CORE_DEPOSIT",
      sourceTable: "FCT_DEPOSIT_TRANSACTION",
      sourceColumn: "TRANSACTION_TYPE",
      businessMeaning: "Type of transaction (DEBIT, CREDIT, TRANSFER)",
      nullable: false,
    },
    {
      columnName: "TRANSACTION_AMOUNT",
      dataType: "DECIMAL(18,2)",
      sourceSchema: "CORE_DEPOSIT",
      sourceTable: "FCT_DEPOSIT_TRANSACTION",
      sourceColumn: "TRANSACTION_AMOUNT",
      businessMeaning: "Transaction amount",
      nullable: false,
    },
    {
      columnName: "BALANCE_AFTER_TRANSACTION",
      dataType: "DECIMAL(18,2)",
      sourceSchema: "CORE_DEPOSIT",
      sourceTable: "FCT_DEPOSIT_TRANSACTION",
      sourceColumn: "BALANCE_AFTER_TRANSACTION",
      businessMeaning: "Account balance after transaction posted",
      nullable: false,
    },
    {
      columnName: "TRANSACTION_DESCRIPTION",
      dataType: "VARCHAR(200)",
      sourceSchema: "CORE_DEPOSIT",
      sourceTable: "FCT_DEPOSIT_TRANSACTION",
      sourceColumn: "TRANSACTION_DESCRIPTION",
      businessMeaning: "Transaction description/memo",
      nullable: true,
    },
    {
      columnName: "TRANSACTION_STATUS",
      dataType: "VARCHAR(20)",
      sourceSchema: "CORE_DEPOSIT",
      sourceTable: "FCT_DEPOSIT_TRANSACTION",
      sourceColumn: "TRANSACTION_STATUS",
      businessMeaning: "Transaction status (POSTED, PENDING, REVERSED, FAILED)",
      nullable: false,
    },
    {
      columnName: "TRANSACTION_CHANNEL",
      dataType: "VARCHAR(20)",
      sourceSchema: "CORE_DEPOSIT",
      sourceTable: "FCT_DEPOSIT_TRANSACTION",
      sourceColumn: "CHANNEL_CODE",
      businessMeaning: "Channel of transaction (BRANCH, ATM, ONLINE, MOBILE, PHONE)",
      nullable: true,
    },
    {
      columnName: "DATA_LOAD_DATE",
      dataType: "DATE",
      sourceSchema: "SYSTEM",
      sourceTable: "SYSTEM_DATE",
      sourceColumn: "CURRENT_DATE",
      businessMeaning: "System load date",
      nullable: false,
    },
  ],
  estimatedRows: 500000000,
  updateFrequency: "Real-time",
  primaryKey: ["TRANSACTION_ID"],
  partitionBy: "POST_DATE",
  clusterBy: ["ACCOUNT_NUMBER", "CUSTOMER_NUMBER", "TRANSACTION_DATE"],
};

// ============================================================================
// FCT_DEPOSIT_HOLD_TRANSACTION - Deposit Hold Transactions Fact Table
// ============================================================================
export const fctDepositHoldTransactionTable: GoldTableSpec = {
  name: "FCT_DEPOSIT_HOLD_TRANSACTION",
  schema: "ANALYTICS",
  type: "FACT",
  grain: "One row per hold transaction",
  description: "Account holds and restrictions (legal holds, levies, NSF holds, compliance holds)",
  columns: [
    {
      columnName: "HOLD_ID",
      dataType: "VARCHAR(50)",
      sourceSchema: "CORE_DEPOSIT",
      sourceTable: "FCT_DEPOSIT_HOLD",
      sourceColumn: "HOLD_ID",
      businessMeaning: "Unique hold transaction identifier",
      nullable: false,
    },
    {
      columnName: "ACCOUNT_NUMBER",
      dataType: "VARCHAR(20)",
      sourceSchema: "CORE_DEPOSIT",
      sourceTable: "DIM_ACCOUNT",
      sourceColumn: "ACCOUNT_NUMBER",
      businessMeaning: "Account number subject to hold",
      nullable: false,
    },
    {
      columnName: "CUSTOMER_NUMBER",
      dataType: "VARCHAR(50)",
      sourceSchema: "CORE_CUSTOMERS",
      sourceTable: "DIM_CUSTOMER",
      sourceColumn: "CUSTOMER_NUMBER",
      businessMeaning: "Customer with hold",
      nullable: false,
    },
    {
      columnName: "HOLD_TYPE",
      dataType: "VARCHAR(20)",
      sourceSchema: "CORE_DEPOSIT",
      sourceTable: "FCT_DEPOSIT_HOLD",
      sourceColumn: "HOLD_TYPE",
      businessMeaning: "Type of hold (LEGAL, LEVY, NSF, COMPLIANCE, OTHER)",
      nullable: false,
    },
    {
      columnName: "HOLD_AMOUNT",
      dataType: "DECIMAL(18,2)",
      sourceSchema: "CORE_DEPOSIT",
      sourceTable: "FCT_DEPOSIT_HOLD",
      sourceColumn: "HOLD_AMOUNT",
      businessMeaning: "Amount on hold",
      nullable: false,
    },
    {
      columnName: "HOLD_REASON",
      dataType: "VARCHAR(200)",
      sourceSchema: "CORE_DEPOSIT",
      sourceTable: "FCT_DEPOSIT_HOLD",
      sourceColumn: "HOLD_REASON",
      businessMeaning: "Reason for hold",
      nullable: true,
    },
    {
      columnName: "HOLD_ENTERED_DATE",
      dataType: "DATE",
      sourceSchema: "CORE_DEPOSIT",
      sourceTable: "FCT_DEPOSIT_HOLD",
      sourceColumn: "HOLD_ENTERED_DATE",
      businessMeaning: "Date hold was entered",
      nullable: false,
    },
    {
      columnName: "HOLD_EXPIRATION_DATE",
      dataType: "DATE",
      sourceSchema: "CORE_DEPOSIT",
      sourceTable: "FCT_DEPOSIT_HOLD",
      sourceColumn: "HOLD_EXPIRATION_DATE",
      businessMeaning: "Scheduled expiration date of hold",
      nullable: true,
    },
    {
      columnName: "HOLD_RELEASED_DATE",
      dataType: "DATE",
      sourceSchema: "CORE_DEPOSIT",
      sourceTable: "FCT_DEPOSIT_HOLD",
      sourceColumn: "HOLD_RELEASED_DATE",
      businessMeaning: "Actual hold release date",
      nullable: true,
    },
    {
      columnName: "HOLD_STATUS",
      dataType: "VARCHAR(20)",
      sourceSchema: "CORE_DEPOSIT",
      sourceTable: "FCT_DEPOSIT_HOLD",
      sourceColumn: "HOLD_STATUS",
      businessMeaning: "Hold status (ACTIVE, RELEASED, EXPIRED)",
      nullable: false,
    },
    {
      columnName: "DATA_LOAD_DATE",
      dataType: "DATE",
      sourceSchema: "SYSTEM",
      sourceTable: "SYSTEM_DATE",
      sourceColumn: "CURRENT_DATE",
      businessMeaning: "System load date",
      nullable: false,
    },
  ],
  estimatedRows: 50000000,
  updateFrequency: "Daily",
  primaryKey: ["HOLD_ID"],
  partitionBy: "HOLD_ENTERED_DATE",
  clusterBy: ["ACCOUNT_NUMBER", "CUSTOMER_NUMBER"],
};

// ============================================================================
// FCT_DEPOSIT_MAINTENANCE_TRANSACTION - Deposit Maintenance Fact Table
// ============================================================================
export const fctDepositMaintenanceTransactionTable: GoldTableSpec = {
  name: "FCT_DEPOSIT_MAINTENANCE_TRANSACTION",
  schema: "ANALYTICS",
  type: "FACT",
  grain: "One row per maintenance event",
  description: "Account maintenance transactions (status changes, keyword updates, suspensions)",
  columns: [
    {
      columnName: "MAINTENANCE_ID",
      dataType: "VARCHAR(50)",
      sourceSchema: "CORE_DEPOSIT",
      sourceTable: "FCT_MAINTENANCE",
      sourceColumn: "MAINTENANCE_ID",
      businessMeaning: "Unique maintenance transaction identifier",
      nullable: false,
    },
    {
      columnName: "ACCOUNT_NUMBER",
      dataType: "VARCHAR(20)",
      sourceSchema: "CORE_DEPOSIT",
      sourceTable: "DIM_ACCOUNT",
      sourceColumn: "ACCOUNT_NUMBER",
      businessMeaning: "Account number",
      nullable: false,
    },
    {
      columnName: "CUSTOMER_NUMBER",
      dataType: "VARCHAR(50)",
      sourceSchema: "CORE_CUSTOMERS",
      sourceTable: "DIM_CUSTOMER",
      sourceColumn: "CUSTOMER_NUMBER",
      businessMeaning: "Customer account owner",
      nullable: false,
    },
    {
      columnName: "MAINTENANCE_TYPE",
      dataType: "VARCHAR(50)",
      sourceSchema: "CORE_DEPOSIT",
      sourceTable: "FCT_MAINTENANCE",
      sourceColumn: "MAINTENANCE_TYPE",
      businessMeaning: "Type of maintenance (STATUS_CHANGE, KEYWORD_UPDATE, SUSPENSION)",
      nullable: false,
    },
    {
      columnName: "MAINTENANCE_DATE",
      dataType: "DATE",
      sourceSchema: "CORE_DEPOSIT",
      sourceTable: "FCT_MAINTENANCE",
      sourceColumn: "MAINTENANCE_DATE",
      businessMeaning: "Date of maintenance action",
      nullable: false,
    },
    {
      columnName: "OLD_VALUE",
      dataType: "VARCHAR(100)",
      sourceSchema: "CORE_DEPOSIT",
      sourceTable: "FCT_MAINTENANCE",
      sourceColumn: "OLD_VALUE",
      businessMeaning: "Previous value before change",
      nullable: true,
    },
    {
      columnName: "NEW_VALUE",
      dataType: "VARCHAR(100)",
      sourceSchema: "CORE_DEPOSIT",
      sourceTable: "FCT_MAINTENANCE",
      sourceColumn: "NEW_VALUE",
      businessMeaning: "New value after change",
      nullable: true,
    },
    {
      columnName: "MAINTENANCE_REASON",
      dataType: "VARCHAR(200)",
      sourceSchema: "CORE_DEPOSIT",
      sourceTable: "FCT_MAINTENANCE",
      sourceColumn: "MAINTENANCE_REASON",
      businessMeaning: "Reason for maintenance",
      nullable: true,
    },
    {
      columnName: "DATA_LOAD_DATE",
      dataType: "DATE",
      sourceSchema: "SYSTEM",
      sourceTable: "SYSTEM_DATE",
      sourceColumn: "CURRENT_DATE",
      businessMeaning: "System load date",
      nullable: false,
    },
  ],
  estimatedRows: 100000000,
  updateFrequency: "Daily",
  primaryKey: ["MAINTENANCE_ID"],
  partitionBy: "MAINTENANCE_DATE",
  clusterBy: ["ACCOUNT_NUMBER", "CUSTOMER_NUMBER"],
};

// ============================================================================
// FCT_DEPOSIT_CERTIFICATE_TRANSACTION - Certificate of Deposit Fact Table
// ============================================================================
export const fctDepositCertificateTransactionTable: GoldTableSpec = {
  name: "FCT_DEPOSIT_CERTIFICATE_TRANSACTION",
  schema: "ANALYTICS",
  type: "FACT",
  grain: "One row per certificate transaction",
  description: "Certificate of Deposit (CD) and time deposit transactions (maturity, renewal, early withdrawal)",
  columns: [
    {
      columnName: "CERTIFICATE_ID",
      dataType: "VARCHAR(50)",
      sourceSchema: "CORE_DEPOSIT",
      sourceTable: "FCT_CERTIFICATE",
      sourceColumn: "CERTIFICATE_ID",
      businessMeaning: "Unique CD certificate identifier",
      nullable: false,
    },
    {
      columnName: "ACCOUNT_NUMBER",
      dataType: "VARCHAR(20)",
      sourceSchema: "CORE_DEPOSIT",
      sourceTable: "DIM_ACCOUNT",
      sourceColumn: "ACCOUNT_NUMBER",
      businessMeaning: "Account number",
      nullable: false,
    },
    {
      columnName: "CUSTOMER_NUMBER",
      dataType: "VARCHAR(50)",
      sourceSchema: "CORE_CUSTOMERS",
      sourceTable: "DIM_CUSTOMER",
      sourceColumn: "CUSTOMER_NUMBER",
      businessMeaning: "Customer account owner",
      nullable: false,
    },
    {
      columnName: "PRINCIPAL_AMOUNT",
      dataType: "DECIMAL(18,2)",
      sourceSchema: "CORE_DEPOSIT",
      sourceTable: "FCT_CERTIFICATE",
      sourceColumn: "PRINCIPAL_AMOUNT",
      businessMeaning: "Initial principal amount of CD",
      nullable: false,
    },
    {
      columnName: "INTEREST_RATE",
      dataType: "DECIMAL(8,6)",
      sourceSchema: "CORE_DEPOSIT",
      sourceTable: "FCT_CERTIFICATE",
      sourceColumn: "INTEREST_RATE",
      businessMeaning: "Annual interest rate percentage",
      nullable: false,
    },
    {
      columnName: "ISSUE_DATE",
      dataType: "DATE",
      sourceSchema: "CORE_DEPOSIT",
      sourceTable: "FCT_CERTIFICATE",
      sourceColumn: "ISSUE_DATE",
      businessMeaning: "CD issue date",
      nullable: false,
    },
    {
      columnName: "MATURITY_DATE",
      dataType: "DATE",
      sourceSchema: "CORE_DEPOSIT",
      sourceTable: "FCT_CERTIFICATE",
      sourceColumn: "MATURITY_DATE",
      businessMeaning: "CD maturity date",
      nullable: false,
    },
    {
      columnName: "TENOR_MONTHS",
      dataType: "NUMBER(5,0)",
      sourceSchema: "CORE_DEPOSIT",
      sourceTable: "FCT_CERTIFICATE",
      sourceColumn: "TENOR_MONTHS",
      businessMeaning: "CD tenor in months",
      nullable: false,
    },
    {
      columnName: "ACCRUED_INTEREST",
      dataType: "DECIMAL(18,6)",
      sourceSchema: "CORE_DEPOSIT",
      sourceTable: "FCT_CERTIFICATE",
      sourceColumn: "ACCRUED_INTEREST",
      businessMeaning: "Interest accrued to date",
      nullable: true,
    },
    {
      columnName: "RENEWAL_FLAG",
      dataType: "VARCHAR(1)",
      sourceSchema: "CORE_DEPOSIT",
      sourceTable: "FCT_CERTIFICATE",
      sourceColumn: "RENEWAL_FLAG",
      businessMeaning: "Auto-renewal indicator (Y/N)",
      nullable: true,
    },
    {
      columnName: "CERTIFICATE_STATUS",
      dataType: "VARCHAR(20)",
      sourceSchema: "CORE_DEPOSIT",
      sourceTable: "FCT_CERTIFICATE",
      sourceColumn: "CERTIFICATE_STATUS",
      businessMeaning: "Status (ACTIVE, MATURED, EARLY_WITHDRAWN, RENEWED)",
      nullable: false,
    },
    {
      columnName: "DATA_LOAD_DATE",
      dataType: "DATE",
      sourceSchema: "SYSTEM",
      sourceTable: "SYSTEM_DATE",
      sourceColumn: "CURRENT_DATE",
      businessMeaning: "System load date",
      nullable: false,
    },
  ],
  estimatedRows: 20000000,
  updateFrequency: "Daily",
  primaryKey: ["CERTIFICATE_ID"],
  partitionBy: "ISSUE_DATE",
  clusterBy: ["ACCOUNT_NUMBER", "CUSTOMER_NUMBER"],
};

// ============================================================================
// FCT_DEPOSIT_STOP_TRANSACTION - Stop Payment Fact Table
// ============================================================================
export const fctDepositStopTransactionTable: GoldTableSpec = {
  name: "FCT_DEPOSIT_STOP_TRANSACTION",
  schema: "ANALYTICS",
  type: "FACT",
  grain: "One row per stop payment",
  description: "Stop payment transactions and check stop requests for deposit accounts",
  columns: [
    {
      columnName: "STOP_ID",
      dataType: "VARCHAR(50)",
      sourceSchema: "CORE_DEPOSIT",
      sourceTable: "FCT_STOP",
      sourceColumn: "STOP_ID",
      businessMeaning: "Unique stop payment identifier",
      nullable: false,
    },
    {
      columnName: "ACCOUNT_NUMBER",
      dataType: "VARCHAR(20)",
      sourceSchema: "CORE_DEPOSIT",
      sourceTable: "DIM_ACCOUNT",
      sourceColumn: "ACCOUNT_NUMBER",
      businessMeaning: "Account number",
      nullable: false,
    },
    {
      columnName: "CUSTOMER_NUMBER",
      dataType: "VARCHAR(50)",
      sourceSchema: "CORE_CUSTOMERS",
      sourceTable: "DIM_CUSTOMER",
      sourceColumn: "CUSTOMER_NUMBER",
      businessMeaning: "Customer account owner",
      nullable: false,
    },
    {
      columnName: "STOP_TYPE",
      dataType: "VARCHAR(20)",
      sourceSchema: "CORE_DEPOSIT",
      sourceTable: "FCT_STOP",
      sourceColumn: "STOP_TYPE",
      businessMeaning: "Type of stop (CHECK, PAYMENT, TRANSFER)",
      nullable: false,
    },
    {
      columnName: "STOP_AMOUNT",
      dataType: "DECIMAL(18,2)",
      sourceSchema: "CORE_DEPOSIT",
      sourceTable: "FCT_STOP",
      sourceColumn: "STOP_AMOUNT",
      businessMeaning: "Amount of stop payment",
      nullable: false,
    },
    {
      columnName: "ITEM_NUMBER",
      dataType: "VARCHAR(20)",
      sourceSchema: "CORE_DEPOSIT",
      sourceTable: "FCT_STOP",
      sourceColumn: "ITEM_NUMBER",
      businessMeaning: "Check number or item reference",
      nullable: true,
    },
    {
      columnName: "STOP_REQUEST_DATE",
      dataType: "DATE",
      sourceSchema: "CORE_DEPOSIT",
      sourceTable: "FCT_STOP",
      sourceColumn: "STOP_REQUEST_DATE",
      businessMeaning: "Date stop was requested",
      nullable: false,
    },
    {
      columnName: "STOP_EFFECTIVE_DATE",
      dataType: "DATE",
      sourceSchema: "CORE_DEPOSIT",
      sourceTable: "FCT_STOP",
      sourceColumn: "STOP_EFFECTIVE_DATE",
      businessMeaning: "Date stop became effective",
      nullable: false,
    },
    {
      columnName: "STOP_EXPIRATION_DATE",
      dataType: "DATE",
      sourceSchema: "CORE_DEPOSIT",
      sourceTable: "FCT_STOP",
      sourceColumn: "STOP_EXPIRATION_DATE",
      businessMeaning: "Date stop expires",
      nullable: true,
    },
    {
      columnName: "STOP_REASON",
      dataType: "VARCHAR(100)",
      sourceSchema: "CORE_DEPOSIT",
      sourceTable: "FCT_STOP",
      sourceColumn: "STOP_REASON",
      businessMeaning: "Reason for stop payment",
      nullable: true,
    },
    {
      columnName: "STOP_STATUS",
      dataType: "VARCHAR(20)",
      sourceSchema: "CORE_DEPOSIT",
      sourceTable: "FCT_STOP",
      sourceColumn: "STOP_STATUS",
      businessMeaning: "Status (ACTIVE, EXPIRED, CANCELLED, PAID)",
      nullable: false,
    },
    {
      columnName: "DATA_LOAD_DATE",
      dataType: "DATE",
      sourceSchema: "SYSTEM",
      sourceTable: "SYSTEM_DATE",
      sourceColumn: "CURRENT_DATE",
      businessMeaning: "System load date",
      nullable: false,
    },
  ],
  estimatedRows: 10000000,
  updateFrequency: "Daily",
  primaryKey: ["STOP_ID"],
  partitionBy: "STOP_REQUEST_DATE",
  clusterBy: ["ACCOUNT_NUMBER", "CUSTOMER_NUMBER"],
};

// ============================================================================
// DIM_DEPOSIT - Deposit Dimension Table (SCD Type 2)
// ============================================================================
export const dimDepositTable: GoldTableSpec = {
  name: "DIM_DEPOSIT",
  schema: "ANALYTICS",
  type: "DIMENSION",
  grain: "One row per deposit account version (SCD2)",
  description: "Slowly changing dimension for deposit accounts with full history tracking",
  columns: [
    {
      columnName: "DEPOSIT_KEY",
      dataType: "NUMBER(18,0)",
      sourceSchema: "CORE_DEPOSIT",
      sourceTable: "DIM_DEPOSIT",
      sourceColumn: "DEPOSIT_KEY",
      businessMeaning: "Surrogate key for deposit dimension",
      nullable: false,
    },
    {
      columnName: "ACCOUNT_NUMBER",
      dataType: "VARCHAR(20)",
      sourceSchema: "CORE_DEPOSIT",
      sourceTable: "DIM_ACCOUNT",
      sourceColumn: "ACCOUNT_NUMBER",
      businessMeaning: "Business key - account number",
      nullable: false,
    },
    {
      columnName: "CUSTOMER_NUMBER",
      dataType: "VARCHAR(50)",
      sourceSchema: "CORE_CUSTOMERS",
      sourceTable: "DIM_CUSTOMER",
      sourceColumn: "CUSTOMER_NUMBER",
      businessMeaning: "Customer account owner",
      nullable: false,
    },
    {
      columnName: "ACCOUNT_TYPE",
      dataType: "VARCHAR(20)",
      sourceSchema: "CORE_DEPOSIT",
      sourceTable: "DIM_ACCOUNT",
      sourceColumn: "ACCOUNT_TYPE",
      businessMeaning: "Account type (CHK, SAV, CD, IRA)",
      nullable: false,
    },
    {
      columnName: "ACCOUNT_STATUS",
      dataType: "VARCHAR(20)",
      sourceSchema: "CORE_DEPOSIT",
      sourceTable: "DIM_ACCOUNT",
      sourceColumn: "ACCOUNT_STATUS",
      businessMeaning: "Account status (ACTIVE, INACTIVE, CLOSED, DORMANT)",
      nullable: false,
    },
    {
      columnName: "ACCOUNT_OPEN_DATE",
      dataType: "DATE",
      sourceSchema: "CORE_DEPOSIT",
      sourceTable: "DIM_ACCOUNT",
      sourceColumn: "ACCOUNT_OPEN_DATE",
      businessMeaning: "Date account was opened",
      nullable: false,
    },
    {
      columnName: "ACCOUNT_CLOSE_DATE",
      dataType: "DATE",
      sourceSchema: "CORE_DEPOSIT",
      sourceTable: "DIM_ACCOUNT",
      sourceColumn: "ACCOUNT_CLOSE_DATE",
      businessMeaning: "Date account was closed",
      nullable: true,
    },
    {
      columnName: "CURRENT_INTEREST_RATE",
      dataType: "DECIMAL(8,6)",
      sourceSchema: "CORE_DEPOSIT",
      sourceTable: "DIM_ACCOUNT",
      sourceColumn: "CURRENT_INTEREST_RATE",
      businessMeaning: "Current interest rate",
      nullable: true,
    },
    {
      columnName: "ACCOUNT_TIER",
      dataType: "VARCHAR(20)",
      sourceSchema: "CORE_DEPOSIT",
      sourceTable: "DIM_ACCOUNT",
      sourceColumn: "TIER_NAME",
      businessMeaning: "Account tier (Gold, Platinum, Standard)",
      nullable: true,
    },
    {
      columnName: "EFFECTIVE_DATE",
      dataType: "DATE",
      sourceSchema: "SYSTEM",
      sourceTable: "SCD_DATE",
      sourceColumn: "EFFECTIVE_DATE",
      businessMeaning: "SCD Type 2 effective date",
      nullable: false,
    },
    {
      columnName: "END_DATE",
      dataType: "DATE",
      sourceSchema: "SYSTEM",
      sourceTable: "SCD_DATE",
      sourceColumn: "END_DATE",
      businessMeaning: "SCD Type 2 end date (NULL if current)",
      nullable: true,
    },
    {
      columnName: "IS_CURRENT",
      dataType: "VARCHAR(1)",
      sourceSchema: "SYSTEM",
      sourceTable: "SCD_DATE",
      sourceColumn: "IS_CURRENT",
      businessMeaning: "Flag indicating current version (Y/N)",
      nullable: false,
    },
  ],
  estimatedRows: 50000000,
  updateFrequency: "Daily",
  primaryKey: ["DEPOSIT_KEY"],
  clusterBy: ["ACCOUNT_NUMBER", "CUSTOMER_NUMBER"],
};

// ============================================================================
// DIM_ACCOUNT - Account Dimension Table (SCD Type 2)
// ============================================================================
export const dimAccountTable: GoldTableSpec = {
  name: "DIM_ACCOUNT",
  schema: "ANALYTICS",
  type: "DIMENSION",
  grain: "One row per account version (SCD2)",
  description: "Account dimension with complete account-level attributes and history",
  columns: [
    {
      columnName: "ACCOUNT_KEY",
      dataType: "NUMBER(18,0)",
      sourceSchema: "CORE_DEPOSIT",
      sourceTable: "DIM_ACCOUNT",
      sourceColumn: "ACCOUNT_KEY",
      businessMeaning: "Surrogate key for account dimension",
      nullable: false,
    },
    {
      columnName: "ACCOUNT_NUMBER",
      dataType: "VARCHAR(20)",
      sourceSchema: "CORE_DEPOSIT",
      sourceTable: "DIM_ACCOUNT",
      sourceColumn: "ACCOUNT_NUMBER",
      businessMeaning: "Business key - account number",
      nullable: false,
    },
    {
      columnName: "CUSTOMER_NUMBER",
      dataType: "VARCHAR(50)",
      sourceSchema: "CORE_CUSTOMERS",
      sourceTable: "DIM_CUSTOMER",
      sourceColumn: "CUSTOMER_NUMBER",
      businessMeaning: "Account owner customer number",
      nullable: false,
    },
    {
      columnName: "BRANCH_NUMBER",
      dataType: "NUMBER(10,0)",
      sourceSchema: "CORE_DEPOSIT",
      sourceTable: "DIM_ACCOUNT",
      sourceColumn: "BRANCH_NUMBER",
      businessMeaning: "Branch where account opened",
      nullable: false,
    },
    {
      columnName: "ACCOUNT_TYPE",
      dataType: "VARCHAR(20)",
      sourceSchema: "CORE_DEPOSIT",
      sourceTable: "DIM_ACCOUNT",
      sourceColumn: "ACCOUNT_TYPE",
      businessMeaning: "Account type (CHK, SAV, CD, IRA, MMA)",
      nullable: false,
    },
    {
      columnName: "ACCOUNT_NAME",
      dataType: "VARCHAR(100)",
      sourceSchema: "CORE_DEPOSIT",
      sourceTable: "DIM_ACCOUNT",
      sourceColumn: "ACCOUNT_NAME",
      businessMeaning: "Account name/title",
      nullable: false,
    },
    {
      columnName: "ACCOUNT_STATUS",
      dataType: "VARCHAR(20)",
      sourceSchema: "CORE_DEPOSIT",
      sourceTable: "DIM_ACCOUNT",
      sourceColumn: "ACCOUNT_STATUS",
      businessMeaning: "Account status (ACTIVE, INACTIVE, CLOSED, DORMANT, SUSPENDED)",
      nullable: false,
    },
    {
      columnName: "ACCOUNT_OPEN_DATE",
      dataType: "DATE",
      sourceSchema: "CORE_DEPOSIT",
      sourceTable: "DIM_ACCOUNT",
      sourceColumn: "ACCOUNT_OPEN_DATE",
      businessMeaning: "Account open date",
      nullable: false,
    },
    {
      columnName: "ACCOUNT_CLOSE_DATE",
      dataType: "DATE",
      sourceSchema: "CORE_DEPOSIT",
      sourceTable: "DIM_ACCOUNT",
      sourceColumn: "ACCOUNT_CLOSE_DATE",
      businessMeaning: "Account close date",
      nullable: true,
    },
    {
      columnName: "CURRENT_INTEREST_RATE",
      dataType: "DECIMAL(8,6)",
      sourceSchema: "CORE_DEPOSIT",
      sourceTable: "DIM_ACCOUNT",
      sourceColumn: "CURRENT_INTEREST_RATE",
      businessMeaning: "Current interest rate percentage",
      nullable: true,
    },
    {
      columnName: "ACCOUNT_TIER",
      dataType: "VARCHAR(20)",
      sourceSchema: "CORE_DEPOSIT",
      sourceTable: "DIM_ACCOUNT",
      sourceColumn: "TIER_NAME",
      businessMeaning: "Account tier (Gold, Platinum, Standard, Premium)",
      nullable: true,
    },
    {
      columnName: "MONTHLY_FEE",
      dataType: "DECIMAL(10,2)",
      sourceSchema: "CORE_DEPOSIT",
      sourceTable: "DIM_ACCOUNT",
      sourceColumn: "MONTHLY_FEE_AMOUNT",
      businessMeaning: "Monthly maintenance fee",
      nullable: true,
    },
    {
      columnName: "EFFECTIVE_DATE",
      dataType: "DATE",
      sourceSchema: "SYSTEM",
      sourceTable: "SCD_DATE",
      sourceColumn: "EFFECTIVE_DATE",
      businessMeaning: "SCD Type 2 effective date",
      nullable: false,
    },
    {
      columnName: "END_DATE",
      dataType: "DATE",
      sourceSchema: "SYSTEM",
      sourceTable: "SCD_DATE",
      sourceColumn: "END_DATE",
      businessMeaning: "SCD Type 2 end date (NULL if current)",
      nullable: true,
    },
    {
      columnName: "IS_CURRENT",
      dataType: "VARCHAR(1)",
      sourceSchema: "SYSTEM",
      sourceTable: "SCD_DATE",
      sourceColumn: "IS_CURRENT",
      businessMeaning: "Flag indicating current version (Y/N)",
      nullable: false,
    },
  ],
  estimatedRows: 100000000,
  updateFrequency: "Daily",
  primaryKey: ["ACCOUNT_KEY"],
  clusterBy: ["ACCOUNT_NUMBER", "CUSTOMER_NUMBER"],
};

// ============================================================================
// CUSTOMER_DEPOSIT_AGGR - Customer Deposit Aggregated View
// ============================================================================
export const customerDepositAggrTable: GoldTableSpec = {
  name: "CUSTOMER_DEPOSIT_AGGR",
  schema: "ANALYTICS",
  type: "AGGREGATE",
  grain: "One row per customer with consolidated deposit metrics",
  description: "Comprehensive customer and deposit aggregation combining demographics, account behavior, and transaction analytics",
  columns: [
    {
      columnName: "CUSTOMER_NUMBER",
      dataType: "VARCHAR(50)",
      sourceSchema: "CORE_CUSTOMERS",
      sourceTable: "DIM_CUSTOMER",
      sourceColumn: "CUSTOMER_NUMBER",
      businessMeaning: "Unique customer identifier",
      nullable: false,
    },
    {
      columnName: "CUSTOMER_NAME",
      dataType: "VARCHAR(100)",
      sourceSchema: "CORE_CUSTOMERS",
      sourceTable: "DIM_CUSTOMER",
      sourceColumn: "CUSTOMER_NAME",
      businessMeaning: "Customer name",
      nullable: false,
    },
    {
      columnName: "TOTAL_DEPOSIT_ACCOUNTS",
      dataType: "NUMBER(5,0)",
      sourceSchema: "CORE_DEPOSIT",
      sourceTable: "DIM_ACCOUNT",
      sourceColumn: "count(distinct ACCOUNT_NUMBER)",
      businessMeaning: "Total number of deposit accounts",
      nullable: true,
    },
    {
      columnName: "ACTIVE_ACCOUNT_COUNT",
      dataType: "NUMBER(5,0)",
      sourceSchema: "CORE_DEPOSIT",
      sourceTable: "DIM_ACCOUNT",
      sourceColumn: "count(distinct ACCOUNT_NUMBER WHERE ACCOUNT_STATUS='ACTIVE')",
      businessMeaning: "Count of active deposit accounts",
      nullable: true,
    },
    {
      columnName: "CHECKING_ACCOUNT_COUNT",
      dataType: "NUMBER(5,0)",
      sourceSchema: "CORE_DEPOSIT",
      sourceTable: "DIM_ACCOUNT",
      sourceColumn: "count(distinct ACCOUNT_NUMBER WHERE ACCOUNT_TYPE='CHK')",
      businessMeaning: "Count of checking accounts",
      nullable: true,
    },
    {
      columnName: "SAVINGS_ACCOUNT_COUNT",
      dataType: "NUMBER(5,0)",
      sourceSchema: "CORE_DEPOSIT",
      sourceTable: "DIM_ACCOUNT",
      sourceColumn: "count(distinct ACCOUNT_NUMBER WHERE ACCOUNT_TYPE='SAV')",
      businessMeaning: "Count of savings accounts",
      nullable: true,
    },
    {
      columnName: "CD_ACCOUNT_COUNT",
      dataType: "NUMBER(5,0)",
      sourceSchema: "CORE_DEPOSIT",
      sourceTable: "DIM_ACCOUNT",
      sourceColumn: "count(distinct ACCOUNT_NUMBER WHERE ACCOUNT_TYPE='CD')",
      businessMeaning: "Count of CD accounts",
      nullable: true,
    },
    {
      columnName: "TOTAL_DEPOSIT_BALANCE",
      dataType: "DECIMAL(18,2)",
      sourceSchema: "CORE_DEPOSIT",
      sourceTable: "FCT_DEPOSIT_DAILY_BALANCE",
      sourceColumn: "sum(CURRENT_BALANCE)",
      businessMeaning: "Total balance across all deposit accounts",
      nullable: true,
    },
    {
      columnName: "CHECKING_BALANCE",
      dataType: "DECIMAL(18,2)",
      sourceSchema: "CORE_DEPOSIT",
      sourceTable: "FCT_DEPOSIT_DAILY_BALANCE",
      sourceColumn: "sum(CURRENT_BALANCE WHERE ACCOUNT_TYPE='CHK')",
      businessMeaning: "Total checking account balance",
      nullable: true,
    },
    {
      columnName: "SAVINGS_BALANCE",
      dataType: "DECIMAL(18,2)",
      sourceSchema: "CORE_DEPOSIT",
      sourceTable: "FCT_DEPOSIT_DAILY_BALANCE",
      sourceColumn: "sum(CURRENT_BALANCE WHERE ACCOUNT_TYPE='SAV')",
      businessMeaning: "Total savings account balance",
      nullable: true,
    },
    {
      columnName: "CD_BALANCE",
      dataType: "DECIMAL(18,2)",
      sourceSchema: "CORE_DEPOSIT",
      sourceTable: "FCT_DEPOSIT_DAILY_BALANCE",
      sourceColumn: "sum(CURRENT_BALANCE WHERE ACCOUNT_TYPE='CD')",
      businessMeaning: "Total CD balance",
      nullable: true,
    },
    {
      columnName: "INTEREST_EARNED_YTD",
      dataType: "DECIMAL(18,6)",
      sourceSchema: "CORE_DEPOSIT",
      sourceTable: "FCT_DEPOSIT_DAILY_BALANCE",
      sourceColumn: "sum(INTEREST_PAID_YTD_AMOUNT)",
      businessMeaning: "Interest earned year-to-date",
      nullable: true,
    },
    {
      columnName: "TOTAL_DEPOSITS_12M",
      dataType: "DECIMAL(18,2)",
      sourceSchema: "CORE_DEPOSIT",
      sourceTable: "FCT_DEPOSIT_ACCOUNT_TRANSACTION",
      sourceColumn: "sum(TRANSACTION_AMOUNT WHERE TRANSACTION_TYPE='CREDIT' AND TRANSACTION_DATE >= CURRENT_DATE - 365)",
      businessMeaning: "Total deposits in last 12 months",
      nullable: true,
    },
    {
      columnName: "TOTAL_WITHDRAWALS_12M",
      dataType: "DECIMAL(18,2)",
      sourceSchema: "CORE_DEPOSIT",
      sourceTable: "FCT_DEPOSIT_ACCOUNT_TRANSACTION",
      sourceColumn: "sum(TRANSACTION_AMOUNT WHERE TRANSACTION_TYPE='DEBIT' AND TRANSACTION_DATE >= CURRENT_DATE - 365)",
      businessMeaning: "Total withdrawals in last 12 months",
      nullable: true,
    },
    {
      columnName: "TRANSACTION_COUNT_12M",
      dataType: "NUMBER(10,0)",
      sourceSchema: "CORE_DEPOSIT",
      sourceTable: "FCT_DEPOSIT_ACCOUNT_TRANSACTION",
      sourceColumn: "count(distinct TRANSACTION_ID WHERE TRANSACTION_DATE >= CURRENT_DATE - 365)",
      businessMeaning: "Total transactions in last 12 months",
      nullable: true,
    },
    {
      columnName: "DAYS_SINCE_LAST_ACTIVITY",
      dataType: "NUMBER(5,0)",
      sourceSchema: "CORE_DEPOSIT",
      sourceTable: "FCT_DEPOSIT_ACCOUNT_TRANSACTION",
      sourceColumn: "DATEDIFF(day, max(TRANSACTION_DATE), CURRENT_DATE)",
      businessMeaning: "Days since last deposit activity",
      nullable: true,
    },
    {
      columnName: "AVERAGE_DAILY_BALANCE",
      dataType: "DECIMAL(18,2)",
      sourceSchema: "CORE_DEPOSIT",
      sourceTable: "FCT_DEPOSIT_DAILY_BALANCE",
      sourceColumn: "avg(CURRENT_BALANCE)",
      businessMeaning: "Average daily balance across accounts",
      nullable: true,
    },
    {
      columnName: "HIGHEST_BALANCE_90D",
      dataType: "DECIMAL(18,2)",
      sourceSchema: "CORE_DEPOSIT",
      sourceTable: "FCT_DEPOSIT_DAILY_BALANCE",
      sourceColumn: "max(CURRENT_BALANCE WHERE BALANCE_DATE >= CURRENT_DATE - 90)",
      businessMeaning: "Highest balance in last 90 days",
      nullable: true,
    },
    {
      columnName: "LOWEST_BALANCE_90D",
      dataType: "DECIMAL(18,2)",
      sourceSchema: "CORE_DEPOSIT",
      sourceTable: "FCT_DEPOSIT_DAILY_BALANCE",
      sourceColumn: "min(CURRENT_BALANCE WHERE BALANCE_DATE >= CURRENT_DATE - 90)",
      businessMeaning: "Lowest balance in last 90 days",
      nullable: true,
    },
    {
      columnName: "CUSTOMER_SEGMENT",
      dataType: "VARCHAR(50)",
      sourceSchema: "ANALYTICS",
      sourceTable: "CUSTOMER_SEGMENTATION",
      sourceColumn: "CUSTOMER_SEGMENT",
      businessMeaning: "Customer value segment (High Net Worth, Affluent, Mass Market, etc)",
      nullable: true,
    },
    {
      columnName: "DEPOSIT_BEHAVIOR_FLAG",
      dataType: "VARCHAR(20)",
      sourceSchema: "ANALYTICS",
      sourceTable: "CUSTOMER_ANALYTICS",
      sourceColumn: "BEHAVIOR_FLAG",
      businessMeaning: "Behavioral flag (Active, Dormant, Declining, Growing)",
      nullable: true,
    },
    {
      columnName: "PRCS_DTE",
      dataType: "DATE",
      sourceSchema: "SYSTEM",
      sourceTable: "SYSTEM_DATE",
      sourceColumn: "BUSINESS_DATE",
      businessMeaning: "Processing/business date for aggregate snapshot",
      nullable: false,
    },
    {
      columnName: "DATA_LOAD_DATE",
      dataType: "DATE",
      sourceSchema: "SYSTEM",
      sourceTable: "SYSTEM_DATE",
      sourceColumn: "CURRENT_DATE",
      businessMeaning: "System load date",
      nullable: false,
    },
  ],
  estimatedRows: 5500000,
  updateFrequency: "Daily",
  primaryKey: ["CUSTOMER_NUMBER", "PRCS_DTE"],
  partitionBy: "PRCS_DTE",
  clusterBy: ["CUSTOMER_NUMBER"],
};

// ============================================================================
// GOLD TABLE CATALOG
// ============================================================================
export const depositsGoldTableCatalog = {
  facts: [], // All fact tables moved to Silver layer
  dimensions: [], // All dimension tables moved to Silver layer
  aggregates: [
    customerDepositAggrTable, // Shared cross-domain aggregate
  ],
  totalTables: 1,
  description: "Gold Layer DDL specifications for Deposits domain - Aggregate tables only (facts and dimensions in Silver)",
};

export default depositsGoldTableCatalog;
