// FIS Source Schema
// Real Fiserv/FIS core banking system source tables and columns
// Maps to 3 pilot domains: Customer Core, Deposits & Funding, Transactions & Payments

export interface FISSourceTable {
  tableName: string;
  schema: string;
  businessEntity: string;
  domainId: string;
  description: string;
  recordEstimate: string;
  refreshFrequency: "Daily" | "Real-time" | "Weekly" | "Monthly";
  columns: FISColumn[];
  primaryKeys: string[];
  businessKey: string;
}

export interface FISColumn {
  name: string;
  dataType: string;
  businessName: string;
  description: string;
  nullable: boolean;
  isKey: boolean;
  businessDictionary?: string;
}

// ============================================================================
// DOMAIN 1: CUSTOMER CORE
// ============================================================================

export const customerFISTables: FISSourceTable[] = [
  {
    tableName: "CUSTOMER",
    schema: "DBO",
    businessEntity: "Customer",
    domainId: "customer",
    description: "Core customer master data - individuals and businesses",
    recordEstimate: "5-10M records",
    refreshFrequency: "Daily",
    businessKey: "CUSTOMER_ID",
    primaryKeys: ["CUSTOMER_ID"],
    columns: [
      {
        name: "CUSTOMER_ID",
        dataType: "BIGINT",
        businessName: "Customer ID",
        description: "Unique customer identifier in core banking system",
        nullable: false,
        isKey: true,
      },
      {
        name: "CUSTOMER_TYPE",
        dataType: "VARCHAR(20)",
        businessName: "Customer Type",
        description: "INDIVIDUAL, BUSINESS, GOVERNMENT",
        nullable: false,
        isKey: false,
      },
      {
        name: "FIRST_NAME",
        dataType: "VARCHAR(100)",
        businessName: "First Name",
        description: "Customer's first name (for individuals)",
        nullable: true,
        isKey: false,
      },
      {
        name: "LAST_NAME",
        dataType: "VARCHAR(100)",
        businessName: "Last Name",
        description: "Customer's last name (for individuals)",
        nullable: true,
        isKey: false,
      },
      {
        name: "MIDDLE_NAME",
        dataType: "VARCHAR(100)",
        businessName: "Middle Name",
        description: "Customer's middle name",
        nullable: true,
        isKey: false,
      },
      {
        name: "BUSINESS_NAME",
        dataType: "VARCHAR(200)",
        businessName: "Business Name",
        description: "Legal business name (for businesses)",
        nullable: true,
        isKey: false,
      },
      {
        name: "TAX_ID",
        dataType: "VARCHAR(20)",
        businessName: "Tax ID",
        description: "SSN (individuals) or EIN (businesses)",
        nullable: false,
        isKey: false,
      },
      {
        name: "DATE_OF_BIRTH",
        dataType: "DATE",
        businessName: "Date of Birth",
        description: "Customer birth date (individuals only)",
        nullable: true,
        isKey: false,
      },
      {
        name: "EMPLOYMENT_STATUS",
        dataType: "VARCHAR(20)",
        businessName: "Employment Status",
        description: "EMPLOYED, SELF_EMPLOYED, RETIRED, UNEMPLOYED, STUDENT",
        nullable: true,
        isKey: false,
      },
      {
        name: "OCCUPATION",
        dataType: "VARCHAR(100)",
        businessName: "Occupation",
        description: "Primary occupation or industry",
        nullable: true,
        isKey: false,
      },
      {
        name: "ANNUAL_INCOME_AMOUNT",
        dataType: "DECIMAL(15,2)",
        businessName: "Annual Income Amount",
        description: "Reported annual household/business income",
        nullable: true,
        isKey: false,
      },
      {
        name: "CUSTOMER_STATUS",
        dataType: "VARCHAR(20)",
        businessName: "Customer Status",
        description: "ACTIVE, INACTIVE, DORMANT, CLOSED, DECEASED, FRAUD",
        nullable: false,
        isKey: false,
      },
      {
        name: "CUSTOMER_SEGMENT",
        dataType: "VARCHAR(50)",
        businessName: "Customer Segment",
        description: "MASS_MARKET, AFFLUENT, BUSINESS, PREMIER",
        nullable: false,
        isKey: false,
      },
      {
        name: "RISK_RATING",
        dataType: "VARCHAR(10)",
        businessName: "Risk Rating",
        description: "Low, Medium, High, Critical risk assessment",
        nullable: false,
        isKey: false,
      },
      {
        name: "KYC_STATUS",
        dataType: "VARCHAR(20)",
        businessName: "KYC Status",
        description: "PENDING, VERIFIED, FAILED, EXCEPTION",
        nullable: false,
        isKey: false,
      },
      {
        name: "CREATED_DATE",
        dataType: "DATETIME",
        businessName: "Created Date",
        description: "Date customer record was created in system",
        nullable: false,
        isKey: false,
      },
      {
        name: "LAST_MODIFIED_DATE",
        dataType: "DATETIME",
        businessName: "Last Modified Date",
        description: "Last update to customer record",
        nullable: false,
        isKey: false,
      },
    ],
  },
  {
    tableName: "CUSTOMER_CONTACT",
    schema: "DBO",
    businessEntity: "Customer Contact Information",
    domainId: "customer",
    description: "Customer contact details - email, phone, address",
    recordEstimate: "12-20M records",
    refreshFrequency: "Daily",
    businessKey: "CONTACT_ID",
    primaryKeys: ["CONTACT_ID"],
    columns: [
      {
        name: "CONTACT_ID",
        dataType: "BIGINT",
        businessName: "Contact ID",
        description: "Unique contact record identifier",
        nullable: false,
        isKey: true,
      },
      {
        name: "CUSTOMER_ID",
        dataType: "BIGINT",
        businessName: "Customer ID",
        description: "Reference to CUSTOMER table",
        nullable: false,
        isKey: false,
      },
      {
        name: "CONTACT_TYPE",
        dataType: "VARCHAR(20)",
        businessName: "Contact Type",
        description: "HOME, WORK, MOBILE, ALTERNATE, BILLING, SHIPPING",
        nullable: false,
        isKey: false,
      },
      {
        name: "PHONE_NUMBER",
        dataType: "VARCHAR(20)",
        businessName: "Phone Number",
        description: "Phone number in E.164 format",
        nullable: true,
        isKey: false,
      },
      {
        name: "EMAIL_ADDRESS",
        dataType: "VARCHAR(255)",
        businessName: "Email Address",
        description: "Email address",
        nullable: true,
        isKey: false,
      },
      {
        name: "ADDRESS_LINE_1",
        dataType: "VARCHAR(100)",
        businessName: "Address Line 1",
        description: "Street address",
        nullable: true,
        isKey: false,
      },
      {
        name: "ADDRESS_LINE_2",
        dataType: "VARCHAR(100)",
        businessName: "Address Line 2",
        description: "Apartment, suite, etc.",
        nullable: true,
        isKey: false,
      },
      {
        name: "CITY",
        dataType: "VARCHAR(50)",
        businessName: "City",
        description: "City name",
        nullable: true,
        isKey: false,
      },
      {
        name: "STATE_PROVINCE_CODE",
        dataType: "VARCHAR(5)",
        businessName: "State/Province Code",
        description: "ISO 3166-2 state/province code",
        nullable: true,
        isKey: false,
      },
      {
        name: "POSTAL_CODE",
        dataType: "VARCHAR(20)",
        businessName: "Postal Code",
        description: "Zip/postal code",
        nullable: true,
        isKey: false,
      },
      {
        name: "COUNTRY_CODE",
        dataType: "VARCHAR(2)",
        businessName: "Country Code",
        description: "ISO 3166-1 alpha-2 country code",
        nullable: true,
        isKey: false,
      },
      {
        name: "IS_PRIMARY",
        dataType: "BIT",
        businessName: "Is Primary",
        description: "Flag indicating if this is primary contact",
        nullable: false,
        isKey: false,
      },
      {
        name: "VERIFIED_DATE",
        dataType: "DATE",
        businessName: "Verified Date",
        description: "Date contact was verified",
        nullable: true,
        isKey: false,
      },
    ],
  },
  {
    tableName: "CUSTOMER_RELATIONSHIP",
    schema: "DBO",
    businessEntity: "Customer Relationships",
    domainId: "customer",
    description: "Customer relationships - primary banker, group memberships",
    recordEstimate: "3-5M records",
    refreshFrequency: "Daily",
    businessKey: "RELATIONSHIP_ID",
    primaryKeys: ["RELATIONSHIP_ID"],
    columns: [
      {
        name: "RELATIONSHIP_ID",
        dataType: "BIGINT",
        businessName: "Relationship ID",
        description: "Unique relationship identifier",
        nullable: false,
        isKey: true,
      },
      {
        name: "CUSTOMER_ID",
        dataType: "BIGINT",
        businessName: "Customer ID",
        description: "Reference to CUSTOMER table",
        nullable: false,
        isKey: false,
      },
      {
        name: "PRIMARY_BANKER_ID",
        dataType: "BIGINT",
        businessName: "Primary Banker ID",
        description: "ID of primary relationship banker/officer",
        nullable: true,
        isKey: false,
      },
      {
        name: "BANKER_NAME",
        dataType: "VARCHAR(100)",
        businessName: "Banker Name",
        description: "Name of primary relationship manager",
        nullable: true,
        isKey: false,
      },
      {
        name: "RELATIONSHIP_TYPE",
        dataType: "VARCHAR(30)",
        businessName: "Relationship Type",
        description: "PERSONAL, BUSINESS, FAMILY_GROUP, CORPORATE",
        nullable: false,
        isKey: false,
      },
      {
        name: "RELATIONSHIP_START_DATE",
        dataType: "DATE",
        businessName: "Relationship Start Date",
        description: "Date relationship began",
        nullable: false,
        isKey: false,
      },
      {
        name: "RELATIONSHIP_STATUS",
        dataType: "VARCHAR(20)",
        businessName: "Relationship Status",
        description: "ACTIVE, INACTIVE, SUSPENDED, TERMINATED",
        nullable: false,
        isKey: false,
      },
      {
        name: "LIFETIME_VALUE_USD",
        dataType: "DECIMAL(15,2)",
        businessName: "Lifetime Value USD",
        description: "Calculated customer lifetime value in USD",
        nullable: true,
        isKey: false,
      },
    ],
  },
];

// ============================================================================
// DOMAIN 2: DEPOSITS & FUNDING
// ============================================================================

export const depositsFISTables: FISSourceTable[] = [
  {
    tableName: "ACCOUNT",
    schema: "DBO",
    businessEntity: "Account",
    domainId: "deposits",
    description: "Deposit and transaction accounts - checking, savings, money market",
    recordEstimate: "20-50M records",
    refreshFrequency: "Real-time",
    businessKey: "ACCOUNT_ID",
    primaryKeys: ["ACCOUNT_ID"],
    columns: [
      {
        name: "ACCOUNT_ID",
        dataType: "BIGINT",
        businessName: "Account ID",
        description: "Unique account identifier",
        nullable: false,
        isKey: true,
      },
      {
        name: "ACCOUNT_NUMBER",
        dataType: "VARCHAR(20)",
        businessName: "Account Number",
        description: "Masked account number for display",
        nullable: false,
        isKey: false,
      },
      {
        name: "CUSTOMER_ID",
        dataType: "BIGINT",
        businessName: "Customer ID",
        description: "Reference to CUSTOMER table",
        nullable: false,
        isKey: false,
      },
      {
        name: "ACCOUNT_TYPE",
        dataType: "VARCHAR(30)",
        businessName: "Account Type",
        description: "CHECKING, SAVINGS, MONEY_MARKET, CMA, NOW_ACCOUNT",
        nullable: false,
        isKey: false,
      },
      {
        name: "PRODUCT_CODE",
        dataType: "VARCHAR(20)",
        businessName: "Product Code",
        description: "Internal product code (e.g., 'CHK001')",
        nullable: false,
        isKey: false,
      },
      {
        name: "PRODUCT_NAME",
        dataType: "VARCHAR(100)",
        businessName: "Product Name",
        description: "Marketing product name",
        nullable: false,
        isKey: false,
      },
      {
        name: "ACCOUNT_STATUS",
        dataType: "VARCHAR(20)",
        businessName: "Account Status",
        description: "ACTIVE, INACTIVE, CLOSED, DORMANT, SUSPENDED, RESTRICTED",
        nullable: false,
        isKey: false,
      },
      {
        name: "OPENED_DATE",
        dataType: "DATE",
        businessName: "Opened Date",
        description: "Account open date",
        nullable: false,
        isKey: false,
      },
      {
        name: "CLOSED_DATE",
        dataType: "DATE",
        businessName: "Closed Date",
        description: "Account close date (if closed)",
        nullable: true,
        isKey: false,
      },
      {
        name: "BRANCH_ID",
        dataType: "BIGINT",
        businessName: "Branch ID",
        description: "Opening branch",
        nullable: true,
        isKey: false,
      },
      {
        name: "CURRENCY_CODE",
        dataType: "VARCHAR(3)",
        businessName: "Currency Code",
        description: "ISO 4217 currency code",
        nullable: false,
        isKey: false,
      },
      {
        name: "INTEREST_RATE_PERCENT",
        dataType: "DECIMAL(8,4)",
        businessName: "Interest Rate Percent",
        description: "Current interest rate as percentage",
        nullable: true,
        isKey: false,
      },
      {
        name: "MONTHLY_FEE_AMOUNT",
        dataType: "DECIMAL(10,2)",
        businessName: "Monthly Fee Amount",
        description: "Monthly maintenance fee",
        nullable: true,
        isKey: false,
      },
      {
        name: "MINIMUM_BALANCE_REQUIRED",
        dataType: "DECIMAL(15,2)",
        businessName: "Minimum Balance Required",
        description: "Required minimum balance to avoid fees",
        nullable: true,
        isKey: false,
      },
      {
        name: "OVERDRAFT_LIMIT_AMOUNT",
        dataType: "DECIMAL(15,2)",
        businessName: "Overdraft Limit Amount",
        description: "Overdraft protection limit",
        nullable: true,
        isKey: false,
      },
      {
        name: "LAST_MODIFIED_DATE",
        dataType: "DATETIME",
        businessName: "Last Modified Date",
        description: "Last update to account record",
        nullable: false,
        isKey: false,
      },
    ],
  },
  {
    tableName: "ACCOUNT_BALANCE",
    schema: "DBO",
    businessEntity: "Account Balance",
    domainId: "deposits",
    description: "Daily account balances - available, current, pending",
    recordEstimate: "100M+ records",
    refreshFrequency: "Real-time",
    businessKey: "BALANCE_ID",
    primaryKeys: ["BALANCE_ID"],
    columns: [
      {
        name: "BALANCE_ID",
        dataType: "BIGINT",
        businessName: "Balance ID",
        description: "Unique balance record identifier",
        nullable: false,
        isKey: true,
      },
      {
        name: "ACCOUNT_ID",
        dataType: "BIGINT",
        businessName: "Account ID",
        description: "Reference to ACCOUNT table",
        nullable: false,
        isKey: false,
      },
      {
        name: "BALANCE_DATE",
        dataType: "DATE",
        businessName: "Balance Date",
        description: "Date of balance snapshot",
        nullable: false,
        isKey: false,
      },
      {
        name: "CURRENT_BALANCE_AMOUNT",
        dataType: "DECIMAL(18,2)",
        businessName: "Current Balance Amount",
        description: "Ledger balance including posted transactions",
        nullable: false,
        isKey: false,
      },
      {
        name: "AVAILABLE_BALANCE_AMOUNT",
        dataType: "DECIMAL(18,2)",
        businessName: "Available Balance Amount",
        description: "Available for withdrawal/debit",
        nullable: false,
        isKey: false,
      },
      {
        name: "PENDING_DEBIT_AMOUNT",
        dataType: "DECIMAL(18,2)",
        businessName: "Pending Debit Amount",
        description: "Holds and pending transactions",
        nullable: false,
        isKey: false,
      },
      {
        name: "PENDING_CREDIT_AMOUNT",
        dataType: "DECIMAL(18,2)",
        businessName: "Pending Credit Amount",
        description: "Pending incoming transactions",
        nullable: false,
        isKey: false,
      },
      {
        name: "ACCRUED_INTEREST_AMOUNT",
        dataType: "DECIMAL(15,2)",
        businessName: "Accrued Interest Amount",
        description: "Interest earned not yet credited",
        nullable: true,
        isKey: false,
      },
      {
        name: "BALANCE_UPDATE_TIMESTAMP",
        dataType: "DATETIME",
        businessName: "Balance Update Timestamp",
        description: "Time balance was last updated",
        nullable: false,
        isKey: false,
      },
    ],
  },
  {
    tableName: "ACCOUNT_TRANSACTION",
    schema: "DBO",
    businessEntity: "Account Transaction",
    domainId: "deposits",
    description: "Individual account transactions - debits, credits, transfers",
    recordEstimate: "500M+ transactions/month",
    refreshFrequency: "Real-time",
    businessKey: "TRANSACTION_ID",
    primaryKeys: ["TRANSACTION_ID"],
    columns: [
      {
        name: "TRANSACTION_ID",
        dataType: "BIGINT",
        businessName: "Transaction ID",
        description: "Unique transaction identifier",
        nullable: false,
        isKey: true,
      },
      {
        name: "ACCOUNT_ID",
        dataType: "BIGINT",
        businessName: "Account ID",
        description: "Reference to ACCOUNT table",
        nullable: false,
        isKey: false,
      },
      {
        name: "TRANSACTION_DATE",
        dataType: "DATE",
        businessName: "Transaction Date",
        description: "Date transaction occurred",
        nullable: false,
        isKey: false,
      },
      {
        name: "POST_DATE",
        dataType: "DATE",
        businessName: "Post Date",
        description: "Date transaction posted to account",
        nullable: false,
        isKey: false,
      },
      {
        name: "TRANSACTION_TYPE",
        dataType: "VARCHAR(30)",
        businessName: "Transaction Type",
        description: "DEBIT, CREDIT, TRANSFER, ACH, WIRE, CHECK, ATM, POS",
        nullable: false,
        isKey: false,
      },
      {
        name: "TRANSACTION_AMOUNT",
        dataType: "DECIMAL(15,2)",
        businessName: "Transaction Amount",
        description: "Transaction amount in account currency",
        nullable: false,
        isKey: false,
      },
      {
        name: "BALANCE_AFTER_TRANSACTION",
        dataType: "DECIMAL(18,2)",
        businessName: "Balance After Transaction",
        description: "Account balance immediately after transaction",
        nullable: false,
        isKey: false,
      },
      {
        name: "DESCRIPTION",
        dataType: "VARCHAR(255)",
        businessName: "Description",
        description: "Transaction description/memo",
        nullable: true,
        isKey: false,
      },
      {
        name: "MERCHANT_NAME",
        dataType: "VARCHAR(100)",
        businessName: "Merchant Name",
        description: "Merchant or counterparty name",
        nullable: true,
        isKey: false,
      },
      {
        name: "MERCHANT_CATEGORY",
        dataType: "VARCHAR(50)",
        businessName: "Merchant Category",
        description: "MCC or merchant category code",
        nullable: true,
        isKey: false,
      },
      {
        name: "TRANSACTION_STATUS",
        dataType: "VARCHAR(20)",
        businessName: "Transaction Status",
        description: "POSTED, PENDING, REVERSED, FAILED",
        nullable: false,
        isKey: false,
      },
      {
        name: "CREATED_TIMESTAMP",
        dataType: "DATETIME",
        businessName: "Created Timestamp",
        description: "When transaction record was created",
        nullable: false,
        isKey: false,
      },
    ],
  },
  {
    tableName: "DEPOSIT_PRODUCT",
    schema: "DBO",
    businessEntity: "Deposit Product",
    domainId: "deposits",
    description: "Deposit product master data - product definitions, rates, fees",
    recordEstimate: "50-100 records",
    refreshFrequency: "Weekly",
    businessKey: "PRODUCT_CODE",
    primaryKeys: ["PRODUCT_CODE"],
    columns: [
      {
        name: "PRODUCT_CODE",
        dataType: "VARCHAR(20)",
        businessName: "Product Code",
        description: "Unique product code",
        nullable: false,
        isKey: true,
      },
      {
        name: "PRODUCT_NAME",
        dataType: "VARCHAR(100)",
        businessName: "Product Name",
        description: "Marketing name for product",
        nullable: false,
        isKey: false,
      },
      {
        name: "PRODUCT_TYPE",
        dataType: "VARCHAR(30)",
        businessName: "Product Type",
        description: "CHECKING, SAVINGS, MONEY_MARKET, CMA",
        nullable: false,
        isKey: false,
      },
      {
        name: "PRODUCT_DESCRIPTION",
        dataType: "VARCHAR(500)",
        businessName: "Product Description",
        description: "Detailed product description",
        nullable: true,
        isKey: false,
      },
      {
        name: "INTEREST_RATE_PERCENT",
        dataType: "DECIMAL(8,4)",
        businessName: "Interest Rate Percent",
        description: "Standard interest rate",
        nullable: true,
        isKey: false,
      },
      {
        name: "MINIMUM_OPENING_BALANCE",
        dataType: "DECIMAL(15,2)",
        businessName: "Minimum Opening Balance",
        description: "Minimum required to open account",
        nullable: true,
        isKey: false,
      },
      {
        name: "MONTHLY_MAINTENANCE_FEE",
        dataType: "DECIMAL(10,2)",
        businessName: "Monthly Maintenance Fee",
        description: "Monthly fee amount",
        nullable: true,
        isKey: false,
      },
      {
        name: "EFFECTIVE_DATE",
        dataType: "DATE",
        businessName: "Effective Date",
        description: "Product effective date",
        nullable: false,
        isKey: false,
      },
      {
        name: "EXPIRATION_DATE",
        dataType: "DATE",
        businessName: "Expiration Date",
        description: "Product end date (if retired)",
        nullable: true,
        isKey: false,
      },
      {
        name: "IS_ACTIVE",
        dataType: "BIT",
        businessName: "Is Active",
        description: "Is product currently available",
        nullable: false,
        isKey: false,
      },
    ],
  },
];

// ============================================================================
// DOMAIN 3: TRANSACTIONS & PAYMENTS
// ============================================================================

export const transactionsFISTables: FISSourceTable[] = [
  {
    tableName: "PAYMENT",
    schema: "DBO",
    businessEntity: "Payment",
    domainId: "transactions",
    description: "Payment transactions - ACH, Wire, Check, Card, Mobile, Person-to-Person",
    recordEstimate: "100M+ payments/month",
    refreshFrequency: "Real-time",
    businessKey: "PAYMENT_ID",
    primaryKeys: ["PAYMENT_ID"],
    columns: [
      {
        name: "PAYMENT_ID",
        dataType: "BIGINT",
        businessName: "Payment ID",
        description: "Unique payment identifier",
        nullable: false,
        isKey: true,
      },
      {
        name: "ORIGINATING_ACCOUNT_ID",
        dataType: "BIGINT",
        businessName: "Originating Account ID",
        description: "Account where payment originated",
        nullable: false,
        isKey: false,
      },
      {
        name: "RECEIVING_ACCOUNT_ID",
        dataType: "BIGINT",
        businessName: "Receiving Account ID",
        description: "Account receiving payment (if internal transfer)",
        nullable: true,
        isKey: false,
      },
      {
        name: "PAYMENT_METHOD",
        dataType: "VARCHAR(30)",
        businessName: "Payment Method",
        description: "ACH, WIRE, CHECK, CARD, MOBILE, P2P, BILL_PAY",
        nullable: false,
        isKey: false,
      },
      {
        name: "PAYMENT_TYPE",
        dataType: "VARCHAR(20)",
        businessName: "Payment Type",
        description: "DEBIT, CREDIT (direction of payment)",
        nullable: false,
        isKey: false,
      },
      {
        name: "PAYMENT_DATE",
        dataType: "DATE",
        businessName: "Payment Date",
        description: "Date payment was initiated",
        nullable: false,
        isKey: false,
      },
      {
        name: "SETTLEMENT_DATE",
        dataType: "DATE",
        businessName: "Settlement Date",
        description: "Expected/actual settlement date",
        nullable: true,
        isKey: false,
      },
      {
        name: "PAYMENT_AMOUNT",
        dataType: "DECIMAL(15,2)",
        businessName: "Payment Amount",
        description: "Payment amount in account currency",
        nullable: false,
        isKey: false,
      },
      {
        name: "CURRENCY_CODE",
        dataType: "VARCHAR(3)",
        businessName: "Currency Code",
        description: "ISO 4217 currency code",
        nullable: false,
        isKey: false,
      },
      {
        name: "EXCHANGE_RATE",
        dataType: "DECIMAL(10,6)",
        businessName: "Exchange Rate",
        description: "FX rate applied (if applicable)",
        nullable: true,
        isKey: false,
      },
      {
        name: "BENEFICIARY_NAME",
        dataType: "VARCHAR(100)",
        businessName: "Beneficiary Name",
        description: "Recipient name",
        nullable: true,
        isKey: false,
      },
      {
        name: "BENEFICIARY_ACCOUNT",
        dataType: "VARCHAR(50)",
        businessName: "Beneficiary Account",
        description: "Recipient account (masked)",
        nullable: true,
        isKey: false,
      },
      {
        name: "BENEFICIARY_BANK",
        dataType: "VARCHAR(100)",
        businessName: "Beneficiary Bank",
        description: "Receiving bank name",
        nullable: true,
        isKey: false,
      },
      {
        name: "PAYMENT_STATUS",
        dataType: "VARCHAR(20)",
        businessName: "Payment Status",
        description: "PENDING, POSTED, FAILED, REVERSED, CANCELLED",
        nullable: false,
        isKey: false,
      },
      {
        name: "PAYMENT_PURPOSE",
        dataType: "VARCHAR(200)",
        businessName: "Payment Purpose",
        description: "Purpose or reason for payment",
        nullable: true,
        isKey: false,
      },
      {
        name: "CREATED_TIMESTAMP",
        dataType: "DATETIME",
        businessName: "Created Timestamp",
        description: "When payment was created",
        nullable: false,
        isKey: false,
      },
    ],
  },
  {
    tableName: "ACH_ITEM",
    schema: "DBO",
    businessEntity: "ACH Item",
    domainId: "transactions",
    description: "ACH (Automated Clearing House) items - debits and credits",
    recordEstimate: "50M+ items/month",
    refreshFrequency: "Real-time",
    businessKey: "ACH_ITEM_ID",
    primaryKeys: ["ACH_ITEM_ID"],
    columns: [
      {
        name: "ACH_ITEM_ID",
        dataType: "BIGINT",
        businessName: "ACH Item ID",
        description: "Unique ACH item identifier",
        nullable: false,
        isKey: true,
      },
      {
        name: "ACH_BATCH_ID",
        dataType: "BIGINT",
        businessName: "ACH Batch ID",
        description: "Batch this item belongs to",
        nullable: false,
        isKey: false,
      },
      {
        name: "ENTRY_SEQUENCE",
        dataType: "INTEGER",
        businessName: "Entry Sequence",
        description: "Position in batch (1-based)",
        nullable: false,
        isKey: false,
      },
      {
        name: "ACCOUNT_ID",
        dataType: "BIGINT",
        businessName: "Account ID",
        description: "Account associated with entry",
        nullable: false,
        isKey: false,
      },
      {
        name: "TRANSACTION_CODE",
        dataType: "VARCHAR(3)",
        businessName: "Transaction Code",
        description: "ACH transaction code (22, 23, 24, 25, 26, 27, 28, 29)",
        nullable: false,
        isKey: false,
      },
      {
        name: "AMOUNT",
        dataType: "DECIMAL(10,2)",
        businessName: "Amount",
        description: "Item amount in cents (stored as integer * 0.01)",
        nullable: false,
        isKey: false,
      },
      {
        name: "RECEIVING_DFI_ID",
        dataType: "VARCHAR(9)",
        businessName: "Receiving DFI ID",
        description: "Receiving bank's routing number",
        nullable: false,
        isKey: false,
      },
      {
        name: "RECEIVING_ACCOUNT_NUMBER",
        dataType: "VARCHAR(17)",
        businessName: "Receiving Account Number",
        description: "Receiving account number (masked)",
        nullable: false,
        isKey: false,
      },
      {
        name: "INDIVIDUAL_ID",
        dataType: "VARCHAR(15)",
        businessName: "Individual ID",
        description: "Originating customer ID (non-bank)",
        nullable: true,
        isKey: false,
      },
      {
        name: "INDIVIDUAL_NAME",
        dataType: "VARCHAR(22)",
        businessName: "Individual Name",
        description: "Receiving party name",
        nullable: false,
        isKey: false,
      },
      {
        name: "DISCRETIONARY_DATA",
        dataType: "VARCHAR(2)",
        businessName: "Discretionary Data",
        description: "Optional data field",
        nullable: true,
        isKey: false,
      },
      {
        name: "ADDENDA_INDICATOR",
        dataType: "BIT",
        businessName: "Addenda Indicator",
        description: "Whether addenda records exist",
        nullable: false,
        isKey: false,
      },
      {
        name: "ENTRY_DATE",
        dataType: "DATE",
        businessName: "Entry Date",
        description: "Effective entry date",
        nullable: false,
        isKey: false,
      },
      {
        name: "SETTLEMENT_DATE",
        dataType: "DATE",
        businessName: "Settlement Date",
        description: "Actual settlement date",
        nullable: true,
        isKey: false,
      },
      {
        name: "ITEM_STATUS",
        dataType: "VARCHAR(20)",
        businessName: "Item Status",
        description: "PENDING, SETTLED, RETURNED, CORRECTED",
        nullable: false,
        isKey: false,
      },
    ],
  },
  {
    tableName: "WIRE_TRANSFER",
    schema: "DBO",
    businessEntity: "Wire Transfer",
    domainId: "transactions",
    description: "Wire transfer transactions - domestic and international",
    recordEstimate: "5-10M transfers/month",
    refreshFrequency: "Real-time",
    businessKey: "WIRE_ID",
    primaryKeys: ["WIRE_ID"],
    columns: [
      {
        name: "WIRE_ID",
        dataType: "BIGINT",
        businessName: "Wire ID",
        description: "Unique wire transfer identifier",
        nullable: false,
        isKey: true,
      },
      {
        name: "ORIGINATING_ACCOUNT_ID",
        dataType: "BIGINT",
        businessName: "Originating Account ID",
        description: "Account initiating wire",
        nullable: false,
        isKey: false,
      },
      {
        name: "WIRE_TYPE",
        dataType: "VARCHAR(20)",
        businessName: "Wire Type",
        description: "DOMESTIC, INTERNATIONAL, INCOMING",
        nullable: false,
        isKey: false,
      },
      {
        name: "WIRE_AMOUNT",
        dataType: "DECIMAL(15,2)",
        businessName: "Wire Amount",
        description: "Wire transfer amount",
        nullable: false,
        isKey: false,
      },
      {
        name: "CURRENCY_CODE",
        dataType: "VARCHAR(3)",
        businessName: "Currency Code",
        description: "ISO 4217 currency code",
        nullable: false,
        isKey: false,
      },
      {
        name: "ORIGINATING_BANK_NAME",
        dataType: "VARCHAR(100)",
        businessName: "Originating Bank Name",
        description: "Our bank name in message",
        nullable: false,
        isKey: false,
      },
      {
        name: "BENEFICIARY_BANK_NAME",
        dataType: "VARCHAR(100)",
        businessName: "Beneficiary Bank Name",
        description: "Receiving bank name",
        nullable: false,
        isKey: false,
      },
      {
        name: "BENEFICIARY_BANK_SWIFT",
        dataType: "VARCHAR(11)",
        businessName: "Beneficiary Bank SWIFT",
        description: "SWIFT code of receiving bank",
        nullable: true,
        isKey: false,
      },
      {
        name: "BENEFICIARY_NAME",
        dataType: "VARCHAR(100)",
        businessName: "Beneficiary Name",
        description: "Name of wire recipient",
        nullable: false,
        isKey: false,
      },
      {
        name: "BENEFICIARY_ACCOUNT",
        dataType: "VARCHAR(50)",
        businessName: "Beneficiary Account",
        description: "Recipient account number",
        nullable: false,
        isKey: false,
      },
      {
        name: "PURPOSE_CODE",
        dataType: "VARCHAR(10)",
        businessName: "Purpose Code",
        description: "ISO purpose code (PIMM, OTHR, etc.)",
        nullable: true,
        isKey: false,
      },
      {
        name: "WIRE_DATE",
        dataType: "DATE",
        businessName: "Wire Date",
        description: "Date wire was initiated",
        nullable: false,
        isKey: false,
      },
      {
        name: "SETTLEMENT_DATE",
        dataType: "DATE",
        businessName: "Settlement Date",
        description: "Expected settlement date",
        nullable: true,
        isKey: false,
      },
      {
        name: "WIRE_STATUS",
        dataType: "VARCHAR(20)",
        businessName: "Wire Status",
        description: "PENDING, SENT, SETTLED, FAILED, CANCELLED",
        nullable: false,
        isKey: false,
      },
      {
        name: "FEE_AMOUNT",
        dataType: "DECIMAL(10,2)",
        businessName: "Fee Amount",
        description: "Wire transfer fee",
        nullable: true,
        isKey: false,
      },
      {
        name: "CREATED_TIMESTAMP",
        dataType: "DATETIME",
        businessName: "Created Timestamp",
        description: "When wire record was created",
        nullable: false,
        isKey: false,
      },
    ],
  },
  {
    tableName: "CHECK_ITEM",
    schema: "DBO",
    businessEntity: "Check Item",
    domainId: "transactions",
    description: "Check transactions and images",
    recordEstimate: "20M+ checks/month",
    refreshFrequency: "Daily",
    businessKey: "CHECK_ID",
    primaryKeys: ["CHECK_ID"],
    columns: [
      {
        name: "CHECK_ID",
        dataType: "BIGINT",
        businessName: "Check ID",
        description: "Unique check identifier",
        nullable: false,
        isKey: true,
      },
      {
        name: "ACCOUNT_ID",
        dataType: "BIGINT",
        businessName: "Account ID",
        description: "Account check is written from",
        nullable: false,
        isKey: false,
      },
      {
        name: "CHECK_NUMBER",
        dataType: "VARCHAR(12)",
        businessName: "Check Number",
        description: "Check number",
        nullable: false,
        isKey: false,
      },
      {
        name: "ROUTING_NUMBER",
        dataType: "VARCHAR(9)",
        businessName: "Routing Number",
        description: "Bank routing number",
        nullable: false,
        isKey: false,
      },
      {
        name: "CHECK_AMOUNT",
        dataType: "DECIMAL(15,2)",
        businessName: "Check Amount",
        description: "Amount of check",
        nullable: false,
        isKey: false,
      },
      {
        name: "PAYEE_NAME",
        dataType: "VARCHAR(100)",
        businessName: "Payee Name",
        description: "Check payee name",
        nullable: true,
        isKey: false,
      },
      {
        name: "ISSUE_DATE",
        dataType: "DATE",
        businessName: "Issue Date",
        description: "Date check was written",
        nullable: false,
        isKey: false,
      },
      {
        name: "PRESENTED_DATE",
        dataType: "DATE",
        businessName: "Presented Date",
        description: "Date check was presented for payment",
        nullable: true,
        isKey: false,
      },
      {
        name: "CLEARED_DATE",
        dataType: "DATE",
        businessName: "Cleared Date",
        description: "Date check cleared",
        nullable: true,
        isKey: false,
      },
      {
        name: "CHECK_STATUS",
        dataType: "VARCHAR(20)",
        businessName: "Check Status",
        description: "ISSUED, PRESENTED, CLEARED, CANCELLED, RETURNED",
        nullable: false,
        isKey: false,
      },
      {
        name: "MICR_LINE",
        dataType: "VARCHAR(30)",
        businessName: "MICR Line",
        description: "Magnetic Ink Character Recognition line",
        nullable: true,
        isKey: false,
      },
      {
        name: "IMAGE_ID",
        dataType: "VARCHAR(50)",
        businessName: "Image ID",
        description: "Reference to stored check image",
        nullable: true,
        isKey: false,
      },
    ],
  },
];

// ============================================================================
// EXPORT FUNCTIONS
// ============================================================================

export function getAllFISTables(): FISSourceTable[] {
  return [...customerFISTables, ...depositsFISTables, ...transactionsFISTables];
}

export function getFISTablesByDomain(domainId: string): FISSourceTable[] {
  return getAllFISTables().filter((t) => t.domainId === domainId);
}

export function getFISTable(tableName: string): FISSourceTable | undefined {
  return getAllFISTables().find((t) => t.tableName === tableName);
}

export function getFISDomainSummary() {
  return {
    customer: {
      domain: "Customer Core",
      tables: customerFISTables,
      totalColumns: customerFISTables.reduce((sum, t) => sum + t.columns.length, 0),
      recordEstimate: "20-35M records",
      description: "Core customer master data, contact information, and relationships",
    },
    deposits: {
      domain: "Deposits & Funding",
      tables: depositsFISTables,
      totalColumns: depositsFISTables.reduce((sum, t) => sum + t.columns.length, 0),
      recordEstimate: "620M+ records/month",
      description: "Deposit accounts, balances, and transactions",
    },
    transactions: {
      domain: "Transactions & Payments",
      tables: transactionsFISTables,
      totalColumns: transactionsFISTables.reduce((sum, t) => sum + t.columns.length, 0),
      recordEstimate: "175M+ items/month",
      description: "Payment transactions, ACH, wires, and checks",
    },
  };
}
