/**
 * COMPLIANCE-COMMERCIAL METRICS CATALOG
 * Commercial banking regulatory compliance and governance metrics
 */

export const complianceCommercialMetricsCatalog = {
  description: 'Commercial banking regulatory compliance, AML/BSA, sanctions, and governance metrics',
  totalMetrics: 52,
  
  categories: [
    {
      name: 'AML/BSA Metrics',
      description: 'Anti-Money Laundering and Bank Secrecy Act compliance',
      totalMetrics: 14,
      metrics: [
        {
          id: 'CCM-AML-001',
          name: 'SAR Filing Rate',
          description: 'Suspicious Activity Reports filed per 1000 customers',
          category: 'AML/BSA',
          subcategory: 'SAR Filings',
          formula: "(COUNT(sars) / COUNT(customers)) * 1000",
          businessLogic: 'SAR count / customer count * 1000',
          dataType: 'DECIMAL',
          unit: 'per 1000',
          aggregation: 'CALCULATED',
          granularity: 'Quarterly',
          sourceTables: ['bronze.commercial_sar_filings'],
          calculation: { numerator: "COUNT(sar_id)", denominator: "COUNT(DISTINCT customer_id)", multiplier: 1000 },
          businessDefinition: 'SAR filing frequency',
          benchmarks: { industryAverage: '3.5 per 1000', topQuartile: '2.8 per 1000', target: '3.0 per 1000' },
        },
        {
          id: 'CCM-AML-002',
          name: 'SAR Backlog',
          description: 'Number of SAR investigations past due date',
          category: 'AML/BSA',
          subcategory: 'SAR Filings',
          formula: "COUNT(sar_id WHERE investigation_status = 'overdue')",
          businessLogic: 'Count of overdue SAR investigations',
          dataType: 'INTEGER',
          unit: 'count',
          aggregation: 'COUNT',
          granularity: 'Monthly',
          sourceTables: ['bronze.commercial_sar_filings'],
          calculation: { numerator: "COUNT(sar_id)", filters: "due_date < CURRENT_DATE AND status != 'filed'" },
          businessDefinition: 'SAR timeliness compliance',
          benchmarks: { industryAverage: '8', topQuartile: '2', target: '5' },
        },
        {
          id: 'CCM-AML-003',
          name: 'CTR Filing Volume',
          description: 'Currency Transaction Reports filed',
          category: 'AML/BSA',
          subcategory: 'CTR Filings',
          formula: "COUNT(ctr_id)",
          businessLogic: 'Count of CTR filings',
          dataType: 'INTEGER',
          unit: 'count',
          aggregation: 'COUNT',
          granularity: 'Monthly',
          sourceTables: ['bronze.commercial_ctr_filings'],
          calculation: { numerator: "COUNT(ctr_id)" },
          businessDefinition: 'BSA cash reporting volume',
          benchmarks: { industryAverage: '1,850/month', topQuartile: '1,200/month', target: '1,500/month' },
        },
        {
          id: 'CCM-AML-004',
          name: 'Transaction Monitoring Alert Rate',
          description: 'Transaction monitoring alerts per 1000 transactions',
          category: 'AML/BSA',
          subcategory: 'Monitoring',
          formula: "(COUNT(alerts) / COUNT(transactions)) * 1000",
          businessLogic: 'Alert count / transaction count * 1000',
          dataType: 'DECIMAL',
          unit: 'per 1000',
          aggregation: 'CALCULATED',
          granularity: 'Monthly',
          sourceTables: ['bronze.commercial_transaction_monitoring'],
          calculation: { numerator: "COUNT(alert_id)", denominator: "COUNT(transaction_id)", multiplier: 1000 },
          businessDefinition: 'Monitoring sensitivity',
          benchmarks: { industryAverage: '12 per 1000', topQuartile: '8 per 1000', target: '10 per 1000' },
        },
        {
          id: 'CCM-AML-005',
          name: 'Alert False Positive Rate',
          description: 'Percentage of alerts cleared as false positives',
          category: 'AML/BSA',
          subcategory: 'Monitoring',
          formula: "(COUNT(false_positives) / COUNT(total_alerts)) * 100",
          businessLogic: 'False positives / total alerts',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Monthly',
          sourceTables: ['bronze.commercial_transaction_monitoring'],
          calculation: { numerator: "COUNT(WHERE disposition = 'false_positive')", denominator: "COUNT(alert_id)", multiplier: 100 },
          businessDefinition: 'Monitoring precision',
          benchmarks: { industryAverage: '85%', topQuartile: '75%', target: '80%' },
        },
        {
          id: 'CCM-AML-006',
          name: 'Average Alert Investigation Time',
          description: 'Average days to investigate and clear alerts',
          category: 'AML/BSA',
          subcategory: 'Efficiency',
          formula: "AVG(close_date - alert_date)",
          businessLogic: 'Average investigation duration',
          dataType: 'INTEGER',
          unit: 'days',
          aggregation: 'AVG',
          granularity: 'Monthly',
          sourceTables: ['bronze.commercial_transaction_monitoring'],
          calculation: { sql: "AVG(EXTRACT(DAY FROM (closed_date - alert_date)))" },
          businessDefinition: 'Alert resolution efficiency',
          benchmarks: { industryAverage: '18 days', topQuartile: '10 days', target: '14 days' },
        },
        {
          id: 'CCM-AML-007',
          name: 'AML Model Tuning Frequency',
          description: 'Number of AML model threshold adjustments',
          category: 'AML/BSA',
          subcategory: 'Model Management',
          formula: "COUNT(model_tuning_event_id)",
          businessLogic: 'Count of model tuning events',
          dataType: 'INTEGER',
          unit: 'count',
          aggregation: 'COUNT',
          granularity: 'Annual',
          sourceTables: ['bronze.commercial_aml_model_changes'],
          calculation: { numerator: "COUNT(tuning_id)" },
          businessDefinition: 'Model optimization frequency',
          benchmarks: { industryAverage: '4/year', topQuartile: '6/year', target: '5/year' },
        },
        {
          id: 'CCM-AML-008',
          name: 'High-Risk Customer Percentage',
          description: 'Customers classified as high AML risk',
          category: 'AML/BSA',
          subcategory: 'Risk Rating',
          formula: "(COUNT(high_risk_customers) / COUNT(total_customers)) * 100",
          businessLogic: 'High risk / total customers',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Quarterly',
          sourceTables: ['bronze.commercial_aml_risk_ratings'],
          calculation: { numerator: "COUNT(WHERE risk_rating = 'high')", denominator: "COUNT(customer_id)", multiplier: 100 },
          businessDefinition: 'AML risk concentration',
          benchmarks: { industryAverage: '8.5%', topQuartile: '6.2%', target: '7.5%' },
        },
        {
          id: 'CCM-AML-009',
          name: 'EDD Review Completion Rate',
          description: 'Enhanced Due Diligence reviews completed on time',
          category: 'AML/BSA',
          subcategory: 'Due Diligence',
          formula: "(COUNT(completed_on_time) / COUNT(required_reviews)) * 100",
          businessLogic: 'Timely EDD / required EDD',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Quarterly',
          sourceTables: ['bronze.commercial_edd_reviews'],
          calculation: { numerator: "COUNT(WHERE completion_date <= due_date)", denominator: "COUNT(review_id)", multiplier: 100 },
          businessDefinition: 'EDD timeliness compliance',
          benchmarks: { industryAverage: '92%', topQuartile: '97%', target: '95%' },
        },
        {
          id: 'CCM-AML-010',
          name: 'PEP Customer Count',
          description: 'Number of Politically Exposed Person relationships',
          category: 'AML/BSA',
          subcategory: 'PEP',
          formula: "COUNT(DISTINCT customer_id WHERE is_pep = true)",
          businessLogic: 'Count of PEP customers',
          dataType: 'INTEGER',
          unit: 'count',
          aggregation: 'COUNT_DISTINCT',
          granularity: 'Monthly',
          sourceTables: ['bronze.commercial_pep_screening'],
          calculation: { numerator: "COUNT(DISTINCT customer_id)", filters: "pep_status = 'confirmed'" },
          businessDefinition: 'PEP exposure',
          benchmarks: { industryAverage: '42', topQuartile: '28', target: '35' },
        },
        {
          id: 'CCM-AML-011',
          name: 'PEP Monitoring Frequency',
          description: 'Average days between PEP account reviews',
          category: 'AML/BSA',
          subcategory: 'PEP',
          formula: "AVG(review_date - prior_review_date)",
          businessLogic: 'Average PEP review interval',
          dataType: 'INTEGER',
          unit: 'days',
          aggregation: 'AVG',
          granularity: 'Quarterly',
          sourceTables: ['bronze.commercial_pep_screening'],
          calculation: { sql: "AVG(EXTRACT(DAY FROM (current_review - prior_review)))" },
          businessDefinition: 'PEP oversight frequency',
          benchmarks: { industryAverage: '185 days', topQuartile: '120 days', target: '150 days' },
        },
        {
          id: 'CCM-AML-012',
          name: 'AML Training Completion Rate',
          description: 'Percentage of employees completing AML training',
          category: 'AML/BSA',
          subcategory: 'Training',
          formula: "(COUNT(completed_training) / COUNT(required_employees)) * 100",
          businessLogic: 'Trained employees / total required',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Annual',
          sourceTables: ['bronze.commercial_compliance_training'],
          calculation: { numerator: "COUNT(WHERE training_status = 'complete')", denominator: "COUNT(employee_id)", multiplier: 100, filters: "training_type = 'AML'" },
          businessDefinition: 'AML training compliance',
          benchmarks: { industryAverage: '96%', topQuartile: '99%', target: '98%', regulatory_requirement: '100%' },
        },
        {
          id: 'CCM-AML-013',
          name: 'Structuring Detection Rate',
          description: 'Suspected structuring cases per 10K CTRs',
          category: 'AML/BSA',
          subcategory: 'Detection',
          formula: "(COUNT(structuring_cases) / COUNT(ctrs)) * 10000",
          businessLogic: 'Structuring cases / CTR count * 10K',
          dataType: 'DECIMAL',
          unit: 'per 10K',
          aggregation: 'CALCULATED',
          granularity: 'Quarterly',
          sourceTables: ['bronze.commercial_structuring_analysis'],
          calculation: { numerator: "COUNT(structuring_id)", denominator: "COUNT(ctr_id)", multiplier: 10000 },
          businessDefinition: 'Structuring surveillance effectiveness',
          benchmarks: { industryAverage: '8 per 10K', topQuartile: '12 per 10K', target: '10 per 10K' },
        },
        {
          id: 'CCM-AML-014',
          name: 'Continuous Monitoring Coverage',
          description: 'Percentage of customers under continuous AML monitoring',
          category: 'AML/BSA',
          subcategory: 'Monitoring',
          formula: "(COUNT(monitored_customers) / COUNT(total_customers)) * 100",
          businessLogic: 'Monitored / total customers',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Monthly',
          sourceTables: ['bronze.commercial_transaction_monitoring'],
          calculation: { numerator: "COUNT(DISTINCT customer_id WHERE has_monitoring = true)", denominator: "COUNT(DISTINCT customer_id)", multiplier: 100 },
          businessDefinition: 'Continuous monitoring adoption',
          benchmarks: { industryAverage: '78%', topQuartile: '92%', target: '85%' },
        },
      ],
    },
    {
      name: 'Sanctions Compliance Metrics',
      description: 'OFAC and sanctions screening effectiveness',
      totalMetrics: 10,
      metrics: [
        {
          id: 'CCM-SANC-001',
          name: 'OFAC Screening Volume',
          description: 'Number of OFAC screening checks performed',
          category: 'Sanctions',
          subcategory: 'Screening',
          formula: "COUNT(screening_id)",
          businessLogic: 'Count of OFAC screens',
          dataType: 'INTEGER',
          unit: 'count',
          aggregation: 'COUNT',
          granularity: 'Daily',
          sourceTables: ['bronze.commercial_ofac_screening'],
          calculation: { numerator: "COUNT(screening_id)" },
          businessDefinition: 'Sanctions screening volume',
          benchmarks: { industryAverage: '195K/day', topQuartile: '385K/day', target: '280K/day' },
        },
        {
          id: 'CCM-SANC-002',
          name: 'OFAC Match Rate',
          description: 'Percentage of screenings with potential matches',
          category: 'Sanctions',
          subcategory: 'Screening',
          formula: "(COUNT(matches) / COUNT(total_screens)) * 100",
          businessLogic: 'Match count / total screens',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Monthly',
          sourceTables: ['bronze.commercial_ofac_screening'],
          calculation: { numerator: "COUNT(WHERE has_match = true)", denominator: "COUNT(screening_id)", multiplier: 100 },
          businessDefinition: 'Sanctions hit rate',
          benchmarks: { industryAverage: '0.25%', topQuartile: '0.18%', target: '0.22%' },
        },
        {
          id: 'CCM-SANC-003',
          name: 'OFAC False Positive Rate',
          description: 'Percentage of matches cleared as false positives',
          category: 'Sanctions',
          subcategory: 'Accuracy',
          formula: "(COUNT(false_positives) / COUNT(total_matches)) * 100",
          businessLogic: 'False positives / total matches',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Monthly',
          sourceTables: ['bronze.commercial_ofac_screening'],
          calculation: { numerator: "COUNT(WHERE match_result = 'false_positive')", denominator: "COUNT(WHERE has_match = true)", multiplier: 100 },
          businessDefinition: 'Sanctions screening precision',
          benchmarks: { industryAverage: '96.5%', topQuartile: '94.2%', target: '95.5%' },
        },
        {
          id: 'CCM-SANC-004',
          name: 'Average Match Resolution Time',
          description: 'Average hours to clear OFAC matches',
          category: 'Sanctions',
          subcategory: 'Efficiency',
          formula: "AVG(cleared_time - alert_time)",
          businessLogic: 'Average match clearance time',
          dataType: 'DECIMAL',
          unit: 'hours',
          aggregation: 'AVG',
          granularity: 'Monthly',
          sourceTables: ['bronze.commercial_ofac_screening'],
          calculation: { sql: "AVG(EXTRACT(EPOCH FROM (cleared_timestamp - alert_timestamp)) / 3600)" },
          businessDefinition: 'Match investigation speed',
          benchmarks: { industryAverage: '4.5 hours', topQuartile: '2.5 hours', target: '3.5 hours' },
        },
        {
          id: 'CCM-SANC-005',
          name: 'Sanctions List Update Timeliness',
          description: 'Average hours from OFAC update to system implementation',
          category: 'Sanctions',
          subcategory: 'List Management',
          formula: "AVG(implementation_time - publication_time)",
          businessLogic: 'System update lag time',
          dataType: 'DECIMAL',
          unit: 'hours',
          aggregation: 'AVG',
          granularity: 'Monthly',
          sourceTables: ['bronze.commercial_sanctions_list_updates'],
          calculation: { sql: "AVG(EXTRACT(EPOCH FROM (system_update_timestamp - ofac_publish_timestamp)) / 3600)" },
          businessDefinition: 'List update responsiveness',
          benchmarks: { industryAverage: '3 hours', topQuartile: '1 hour', target: '2 hours' },
        },
        {
          id: 'CCM-SANC-006',
          name: 'Blocked Transaction Count',
          description: 'Number of transactions blocked due to sanctions match',
          category: 'Sanctions',
          subcategory: 'Enforcement',
          formula: "COUNT(transaction_id WHERE status = 'blocked')",
          businessLogic: 'Count of blocked transactions',
          dataType: 'INTEGER',
          unit: 'count',
          aggregation: 'COUNT',
          granularity: 'Monthly',
          sourceTables: ['bronze.commercial_ofac_screening'],
          calculation: { numerator: "COUNT(transaction_id)", filters: "action_taken = 'blocked'" },
          businessDefinition: 'Sanctions enforcement actions',
          benchmarks: { industryAverage: '12/month', topQuartile: '8/month', target: '10/month' },
        },
        {
          id: 'CCM-SANC-007',
          name: 'SDN List Coverage',
          description: 'Percentage of sanctions lists monitored',
          category: 'Sanctions',
          subcategory: 'Coverage',
          formula: "(COUNT(monitored_lists) / COUNT(total_relevant_lists)) * 100",
          businessLogic: 'Monitored lists / relevant lists',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Quarterly',
          sourceTables: ['bronze.commercial_sanctions_list_coverage'],
          calculation: { numerator: "COUNT(WHERE monitored = true)", denominator: "COUNT(list_id)", multiplier: 100 },
          businessDefinition: 'Sanctions list completeness',
          benchmarks: { industryAverage: '95%', topQuartile: '100%', target: '98%', regulatory_expectation: '100%' },
        },
        {
          id: 'CCM-SANC-008',
          name: 'Pre-Transaction Screening Rate',
          description: 'Percentage of wire transfers screened before execution',
          category: 'Sanctions',
          subcategory: 'Prevention',
          formula: "(COUNT(pre_screened) / COUNT(total_wires)) * 100",
          businessLogic: 'Pre-screened / total wires',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Monthly',
          sourceTables: ['bronze.commercial_ofac_screening'],
          calculation: { numerator: "COUNT(WHERE screening_timing = 'pre_execution')", denominator: "COUNT(transaction_id)", multiplier: 100, filters: "transaction_type = 'wire'" },
          businessDefinition: 'Proactive sanctions screening',
          benchmarks: { industryAverage: '98.5%', topQuartile: '99.9%', target: '99.5%', regulatory_expectation: '100%' },
        },
        {
          id: 'CCM-SANC-009',
          name: 'Sanctions Training Completion',
          description: 'Percentage of staff completing sanctions training',
          category: 'Sanctions',
          subcategory: 'Training',
          formula: "(COUNT(completed_training) / COUNT(required_employees)) * 100",
          businessLogic: 'Trained / required employees',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Annual',
          sourceTables: ['bronze.commercial_compliance_training'],
          calculation: { numerator: "COUNT(WHERE training_status = 'complete')", denominator: "COUNT(employee_id)", multiplier: 100, filters: "training_type = 'sanctions'" },
          businessDefinition: 'Sanctions awareness compliance',
          benchmarks: { industryAverage: '97%', topQuartile: '100%', target: '99%', regulatory_requirement: '100%' },
        },
        {
          id: 'CCM-SANC-010',
          name: 'Sanctions Audit Findings',
          description: 'Number of audit findings related to sanctions compliance',
          category: 'Sanctions',
          subcategory: 'Audit',
          formula: "COUNT(finding_id WHERE area = 'sanctions')",
          businessLogic: 'Count of sanctions audit findings',
          dataType: 'INTEGER',
          unit: 'count',
          aggregation: 'COUNT',
          granularity: 'Annual',
          sourceTables: ['bronze.compliance_audit_findings'],
          calculation: { numerator: "COUNT(finding_id)", filters: "compliance_area = 'sanctions'" },
          businessDefinition: 'Sanctions program effectiveness',
          benchmarks: { industryAverage: '3/year', topQuartile: '1/year', target: '2/year' },
        },
      ],
    },
    {
      name: 'KYC/CDD Metrics',
      description: 'Know Your Customer and Customer Due Diligence effectiveness',
      totalMetrics: 10,
      metrics: [
        {
          id: 'CCM-KYC-001',
          name: 'KYC Refresh Compliance Rate',
          description: 'Percentage of KYC refreshes completed on schedule',
          category: 'KYC/CDD',
          subcategory: 'Timeliness',
          formula: "(COUNT(on_time_refreshes) / COUNT(required_refreshes)) * 100",
          businessLogic: 'On-time refreshes / required refreshes',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Quarterly',
          sourceTables: ['bronze.commercial_kyc_refresh'],
          calculation: { numerator: "COUNT(WHERE refresh_date <= due_date)", denominator: "COUNT(refresh_id)", multiplier: 100 },
          businessDefinition: 'KYC refresh timeliness',
          benchmarks: { industryAverage: '88%', topQuartile: '96%', target: '92%' },
        },
        {
          id: 'CCM-KYC-002',
          name: 'CDD Documentation Completeness',
          description: 'Percentage of customers with complete CDD files',
          category: 'KYC/CDD',
          subcategory: 'Quality',
          formula: "(COUNT(complete_cdd) / COUNT(total_customers)) * 100",
          businessLogic: 'Complete CDD / total customers',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Monthly',
          sourceTables: ['bronze.commercial_cdd_records'],
          calculation: { numerator: "COUNT(WHERE cdd_complete = true)", denominator: "COUNT(customer_id)", multiplier: 100 },
          businessDefinition: 'CDD file quality',
          benchmarks: { industryAverage: '94%', topQuartile: '98%', target: '96%' },
        },
        {
          id: 'CCM-KYC-003',
          name: 'Beneficial Owner Identification Rate',
          description: 'Percentage of entities with beneficial owners identified',
          category: 'KYC/CDD',
          subcategory: 'UBO',
          formula: "(COUNT(ubo_identified) / COUNT(required_entities)) * 100",
          businessLogic: 'UBO identified / required entities',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Quarterly',
          sourceTables: ['bronze.commercial_beneficial_owners'],
          calculation: { numerator: "COUNT(WHERE ubo_identified = true)", denominator: "COUNT(entity_id)", multiplier: 100 },
          businessDefinition: 'UBO transparency compliance',
          benchmarks: { industryAverage: '93%', topQuartile: '98%', target: '96%', regulatory_requirement: '100%' },
        },
        {
          id: 'CCM-KYC-004',
          name: 'Customer Risk Rating Distribution - High',
          description: 'Percentage of customers rated high risk',
          category: 'KYC/CDD',
          subcategory: 'Risk Rating',
          formula: "(COUNT(high_risk) / COUNT(total_customers)) * 100",
          businessLogic: 'High risk / total customers',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Monthly',
          sourceTables: ['bronze.commercial_customer_risk_ratings'],
          calculation: { numerator: "COUNT(WHERE risk_rating = 'high')", denominator: "COUNT(customer_id)", multiplier: 100 },
          businessDefinition: 'High-risk customer concentration',
          benchmarks: { industryAverage: '12%', topQuartile: '8%', target: '10%' },
        },
        {
          id: 'CCM-KYC-005',
          name: 'Average Customer Onboarding Time',
          description: 'Average days from application to account opening',
          category: 'KYC/CDD',
          subcategory: 'Efficiency',
          formula: "AVG(account_opening_date - application_date)",
          businessLogic: 'Average onboarding duration',
          dataType: 'INTEGER',
          unit: 'days',
          aggregation: 'AVG',
          granularity: 'Monthly',
          sourceTables: ['bronze.commercial_customer_onboarding'],
          calculation: { sql: "AVG(EXTRACT(DAY FROM (approval_date - application_date)))" },
          businessDefinition: 'KYC/CDD processing efficiency',
          benchmarks: { industryAverage: '8 days', topQuartile: '5 days', target: '6 days' },
        },
        {
          id: 'CCM-KYC-006',
          name: 'Adverse Media Screening Coverage',
          description: 'Percentage of customers screened for adverse media',
          category: 'KYC/CDD',
          subcategory: 'Screening',
          formula: "(COUNT(screened_customers) / COUNT(total_customers)) * 100",
          businessLogic: 'Screened / total customers',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Monthly',
          sourceTables: ['bronze.commercial_adverse_media'],
          calculation: { numerator: "COUNT(DISTINCT customer_id)", denominator: "COUNT(DISTINCT all_customer_id)", multiplier: 100 },
          businessDefinition: 'Reputational risk screening',
          benchmarks: { industryAverage: '85%', topQuartile: '95%', target: '90%' },
        },
        {
          id: 'CCM-KYC-007',
          name: 'EDD Customer Percentage',
          description: 'Percentage of customers requiring Enhanced Due Diligence',
          category: 'KYC/CDD',
          subcategory: 'EDD',
          formula: "(COUNT(edd_customers) / COUNT(total_customers)) * 100",
          businessLogic: 'EDD customers / total',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Quarterly',
          sourceTables: ['bronze.commercial_edd_records'],
          calculation: { numerator: "COUNT(WHERE edd_required = true)", denominator: "COUNT(customer_id)", multiplier: 100 },
          businessDefinition: 'Enhanced oversight requirement',
          benchmarks: { industryAverage: '15%', topQuartile: '12%', target: '13%' },
        },
        {
          id: 'CCM-KYC-008',
          name: 'Source of Wealth Documentation Rate',
          description: 'Percentage of high-risk customers with SOW documented',
          category: 'KYC/CDD',
          subcategory: 'Documentation',
          formula: "(COUNT(documented_sow) / COUNT(high_risk_customers)) * 100",
          businessLogic: 'SOW documented / high risk customers',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Quarterly',
          sourceTables: ['bronze.commercial_source_of_wealth'],
          calculation: { numerator: "COUNT(WHERE sow_documented = true)", denominator: "COUNT(WHERE risk_rating = 'high')", multiplier: 100 },
          businessDefinition: 'Source of wealth transparency',
          benchmarks: { industryAverage: '88%', topQuartile: '96%', target: '92%' },
        },
        {
          id: 'CCM-KYC-009',
          name: 'KYC Data Quality Score',
          description: 'Composite data quality score for KYC information',
          category: 'KYC/CDD',
          subcategory: 'Data Quality',
          formula: "AVG(completeness_score + accuracy_score + timeliness_score) / 3",
          businessLogic: 'Average data quality dimensions',
          dataType: 'INTEGER',
          unit: 'score',
          aggregation: 'AVG',
          granularity: 'Monthly',
          sourceTables: ['silver.commercial_kyc_data_quality'],
          calculation: { sql: "AVG((completeness + accuracy + timeliness) / 3)" },
          businessDefinition: 'KYC data integrity',
          benchmarks: { industryAverage: '85', topQuartile: '93', target: '90', scale: '0-100' },
        },
        {
          id: 'CCM-KYC-010',
          name: 'Third-Party Verification Usage',
          description: 'Percentage of KYC verified through third-party data sources',
          category: 'KYC/CDD',
          subcategory: 'Verification',
          formula: "(COUNT(third_party_verified) / COUNT(total_customers)) * 100",
          businessLogic: 'Third-party verified / total',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Quarterly',
          sourceTables: ['bronze.commercial_kyc_verification'],
          calculation: { numerator: "COUNT(WHERE uses_third_party_data = true)", denominator: "COUNT(customer_id)", multiplier: 100 },
          businessDefinition: 'Independent verification rate',
          benchmarks: { industryAverage: '72%', topQuartile: '88%', target: '80%' },
        },
      ],
    },
    {
      name: 'Regulatory Reporting Metrics',
      description: 'Regulatory filing timeliness and accuracy',
      totalMetrics: 10,
      metrics: [
        {
          id: 'CCM-REG-001',
          name: 'Call Report Timeliness',
          description: 'Days before deadline that Call Report is filed',
          category: 'Regulatory Reporting',
          subcategory: 'Timeliness',
          formula: "AVG(deadline_date - filing_date)",
          businessLogic: 'Filing buffer days',
          dataType: 'INTEGER',
          unit: 'days',
          aggregation: 'AVG',
          granularity: 'Quarterly',
          sourceTables: ['bronze.regulatory_filings'],
          calculation: { sql: "AVG(EXTRACT(DAY FROM (deadline_date - actual_filing_date)))", filters: "report_type = 'call_report'" },
          businessDefinition: 'Call Report submission buffer',
          benchmarks: { industryAverage: '5 days', topQuartile: '10 days', target: '7 days' },
        },
        {
          id: 'CCM-REG-002',
          name: 'Regulatory Filing Error Rate',
          description: 'Percentage of filings requiring correction',
          category: 'Regulatory Reporting',
          subcategory: 'Accuracy',
          formula: "(COUNT(corrections_required) / COUNT(total_filings)) * 100",
          businessLogic: 'Corrected filings / total filings',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Quarterly',
          sourceTables: ['bronze.regulatory_filings'],
          calculation: { numerator: "COUNT(WHERE correction_required = true)", denominator: "COUNT(filing_id)", multiplier: 100 },
          businessDefinition: 'Filing accuracy rate',
          benchmarks: { industryAverage: '8%', topQuartile: '3%', target: '5%' },
        },
        {
          id: 'CCM-REG-003',
          name: 'CRA Examination Rating',
          description: 'Current Community Reinvestment Act rating',
          category: 'Regulatory Reporting',
          subcategory: 'CRA',
          formula: "current_cra_rating",
          businessLogic: 'Latest CRA exam rating',
          dataType: 'TEXT',
          unit: 'rating',
          aggregation: 'LATEST',
          granularity: 'Annual',
          sourceTables: ['bronze.regulatory_examinations'],
          calculation: { sql: "MAX(examination_rating)", filters: "exam_type = 'CRA'" },
          businessDefinition: 'CRA performance rating',
          benchmarks: { industryAverage: 'Satisfactory', topQuartile: 'Outstanding', target: 'Satisfactory', ratings: ['Outstanding', 'Satisfactory', 'Needs Improvement', 'Substantial Noncompliance'] },
        },
        {
          id: 'CCM-REG-004',
          name: 'CRA Qualified Lending Volume',
          description: 'Total CRA-qualified lending',
          category: 'Regulatory Reporting',
          subcategory: 'CRA',
          formula: "SUM(loan_amount WHERE cra_qualified = true)",
          businessLogic: 'Total CRA lending',
          dataType: 'DECIMAL',
          unit: 'currency',
          aggregation: 'SUM',
          granularity: 'Annual',
          sourceTables: ['bronze.commercial_cra_lending'],
          calculation: { numerator: "SUM(loan_amount)", filters: "is_cra_qualified = true" },
          businessDefinition: 'Community investment volume',
          benchmarks: { industryAverage: '$85M', topQuartile: '$145M', target: '$110M' },
        },
        {
          id: 'CCM-REG-005',
          name: 'Regulatory Examination Findings',
          description: 'Number of findings from regulatory exams',
          category: 'Regulatory Reporting',
          subcategory: 'Examinations',
          formula: "COUNT(finding_id WHERE severity >= 'medium')",
          businessLogic: 'Count of exam findings',
          dataType: 'INTEGER',
          unit: 'count',
          aggregation: 'COUNT',
          granularity: 'Annual',
          sourceTables: ['bronze.regulatory_examinations'],
          calculation: { numerator: "COUNT(finding_id)", filters: "severity IN ('medium', 'high', 'critical')" },
          businessDefinition: 'Regulatory compliance status',
          benchmarks: { industryAverage: '6/year', topQuartile: '2/year', target: '4/year' },
        },
        {
          id: 'CCM-REG-006',
          name: 'MRA Closure Rate',
          description: 'Percentage of Matters Requiring Attention closed',
          category: 'Regulatory Reporting',
          subcategory: 'Remediation',
          formula: "(COUNT(closed_mras) / COUNT(total_mras)) * 100",
          businessLogic: 'Closed MRAs / total MRAs',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Quarterly',
          sourceTables: ['bronze.regulatory_mras'],
          calculation: { numerator: "COUNT(WHERE status = 'closed')", denominator: "COUNT(mra_id)", multiplier: 100 },
          businessDefinition: 'Remediation effectiveness',
          benchmarks: { industryAverage: '72%', topQuartile: '88%', target: '80%' },
        },
        {
          id: 'CCM-REG-007',
          name: 'HMDA Reporting Accuracy',
          description: 'Percentage of HMDA records passing validation',
          category: 'Regulatory Reporting',
          subcategory: 'HMDA',
          formula: "(COUNT(valid_records) / COUNT(total_records)) * 100",
          businessLogic: 'Valid HMDA / total records',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Annual',
          sourceTables: ['bronze.hmda_reporting'],
          calculation: { numerator: "COUNT(WHERE validation_status = 'pass')", denominator: "COUNT(record_id)", multiplier: 100 },
          businessDefinition: 'HMDA data quality',
          benchmarks: { industryAverage: '96%', topQuartile: '99%', target: '98%' },
        },
        {
          id: 'CCM-REG-008',
          name: 'Reg O Insider Lending Compliance',
          description: 'Percentage of insider loans in compliance',
          category: 'Regulatory Reporting',
          subcategory: 'Reg O',
          formula: "(COUNT(compliant_loans) / COUNT(insider_loans)) * 100",
          businessLogic: 'Compliant insider loans / total',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Quarterly',
          sourceTables: ['bronze.reg_o_insider_lending'],
          calculation: { numerator: "COUNT(WHERE reg_o_compliant = true)", denominator: "COUNT(loan_id)", multiplier: 100 },
          businessDefinition: 'Insider lending compliance',
          benchmarks: { industryAverage: '98%', topQuartile: '100%', target: '99%', regulatory_requirement: '100%' },
        },
        {
          id: 'CCM-REG-009',
          name: 'FDICIA Audit Compliance',
          description: 'Annual FDICIA audit completion status',
          category: 'Regulatory Reporting',
          subcategory: 'Audit',
          formula: "audit_completion_status",
          businessLogic: 'FDICIA audit status',
          dataType: 'BOOLEAN',
          unit: 'status',
          aggregation: 'LATEST',
          granularity: 'Annual',
          sourceTables: ['bronze.fdicia_audits'],
          calculation: { sql: "MAX(audit_complete)", filters: "audit_year = EXTRACT(YEAR FROM CURRENT_DATE)" },
          businessDefinition: 'FDICIA audit compliance',
          benchmarks: { industryAverage: 'Complete', topQuartile: 'Complete', target: 'Complete', regulatory_requirement: 'Complete' },
        },
        {
          id: 'CCM-REG-010',
          name: 'Suspicious Activity Reporting Timeliness',
          description: 'Average days from detection to SAR filing',
          category: 'Regulatory Reporting',
          subcategory: 'SAR Timeliness',
          formula: "AVG(filing_date - detection_date)",
          businessLogic: 'SAR filing lag time',
          dataType: 'INTEGER',
          unit: 'days',
          aggregation: 'AVG',
          granularity: 'Quarterly',
          sourceTables: ['bronze.commercial_sar_filings'],
          calculation: { sql: "AVG(EXTRACT(DAY FROM (filing_date - detection_date)))" },
          businessDefinition: 'SAR reporting speed',
          benchmarks: { industryAverage: '22 days', topQuartile: '14 days', target: '18 days', regulatory_deadline: '30 days' },
        },
      ],
    },
    {
      name: 'Consumer Protection Metrics',
      description: 'Fair lending, privacy, and consumer rights compliance',
      totalMetrics: 8,
      metrics: [
        {
          id: 'CCM-CONS-001',
          name: 'Fair Lending Testing Pass Rate',
          description: 'Percentage of fair lending tests passed',
          category: 'Consumer Protection',
          subcategory: 'Fair Lending',
          formula: "(COUNT(passed_tests) / COUNT(total_tests)) * 100",
          businessLogic: 'Passed tests / total tests',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Quarterly',
          sourceTables: ['bronze.fair_lending_testing'],
          calculation: { numerator: "COUNT(WHERE test_result = 'pass')", denominator: "COUNT(test_id)", multiplier: 100 },
          businessDefinition: 'Fair lending compliance',
          benchmarks: { industryAverage: '94%', topQuartile: '98%', target: '96%' },
        },
        {
          id: 'CCM-CONS-002',
          name: 'Disparate Impact Test Results',
          description: 'Number of products with potential disparate impact',
          category: 'Consumer Protection',
          subcategory: 'Fair Lending',
          formula: "COUNT(product_id WHERE disparate_impact_detected = true)",
          businessLogic: 'Products with potential disparate impact',
          dataType: 'INTEGER',
          unit: 'count',
          aggregation: 'COUNT',
          granularity: 'Annual',
          sourceTables: ['bronze.disparate_impact_analysis'],
          calculation: { numerator: "COUNT(DISTINCT product_id)", filters: "potential_impact = true" },
          businessDefinition: 'Fair lending risk areas',
          benchmarks: { industryAverage: '2/year', topQuartile: '0/year', target: '1/year' },
        },
        {
          id: 'CCM-CONS-003',
          name: 'Privacy Notice Distribution Rate',
          description: 'Percentage of customers receiving privacy notices',
          category: 'Consumer Protection',
          subcategory: 'Privacy',
          formula: "(COUNT(notice_sent) / COUNT(required_customers)) * 100",
          businessLogic: 'Notices sent / required customers',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Annual',
          sourceTables: ['bronze.privacy_notice_distribution'],
          calculation: { numerator: "COUNT(WHERE notice_delivered = true)", denominator: "COUNT(customer_id)", multiplier: 100 },
          businessDefinition: 'Privacy notice compliance',
          benchmarks: { industryAverage: '98%', topQuartile: '100%', target: '99%', regulatory_requirement: '100%' },
        },
        {
          id: 'CCM-CONS-004',
          name: 'Customer Complaint Rate',
          description: 'Customer complaints per 1000 customers',
          category: 'Consumer Protection',
          subcategory: 'Complaints',
          formula: "(COUNT(complaints) / COUNT(customers)) * 1000",
          businessLogic: 'Complaint count / customer count * 1000',
          dataType: 'DECIMAL',
          unit: 'per 1000',
          aggregation: 'CALCULATED',
          granularity: 'Quarterly',
          sourceTables: ['bronze.customer_complaints'],
          calculation: { numerator: "COUNT(complaint_id)", denominator: "COUNT(DISTINCT customer_id)", multiplier: 1000 },
          businessDefinition: 'Customer dissatisfaction rate',
          benchmarks: { industryAverage: '8 per 1000', topQuartile: '4 per 1000', target: '6 per 1000' },
        },
        {
          id: 'CCM-CONS-005',
          name: 'Complaint Resolution Time',
          description: 'Average days to resolve customer complaints',
          category: 'Consumer Protection',
          subcategory: 'Complaints',
          formula: "AVG(resolution_date - filing_date)",
          businessLogic: 'Average complaint resolution time',
          dataType: 'INTEGER',
          unit: 'days',
          aggregation: 'AVG',
          granularity: 'Quarterly',
          sourceTables: ['bronze.customer_complaints'],
          calculation: { sql: "AVG(EXTRACT(DAY FROM (resolution_date - filing_date)))" },
          businessDefinition: 'Complaint handling efficiency',
          benchmarks: { industryAverage: '16 days', topQuartile: '9 days', target: '12 days' },
        },
        {
          id: 'CCM-CONS-006',
          name: 'Data Breach Notification Timeliness',
          description: 'Average hours to notify customers of data breach',
          category: 'Consumer Protection',
          subcategory: 'Data Privacy',
          formula: "AVG(notification_time - breach_discovery_time)",
          businessLogic: 'Notification lag time',
          dataType: 'INTEGER',
          unit: 'hours',
          aggregation: 'AVG',
          granularity: 'Annual',
          sourceTables: ['bronze.data_breach_notifications'],
          calculation: { sql: "AVG(EXTRACT(EPOCH FROM (notification_timestamp - discovery_timestamp)) / 3600)" },
          businessDefinition: 'Breach notification compliance',
          benchmarks: { industryAverage: '48 hours', topQuartile: '24 hours', target: '36 hours', regulatory_requirement: '72 hours' },
        },
        {
          id: 'CCM-CONS-007',
          name: 'UDAAP Risk Assessment Coverage',
          description: 'Percentage of products assessed for UDAAP risk',
          category: 'Consumer Protection',
          subcategory: 'UDAAP',
          formula: "(COUNT(assessed_products) / COUNT(total_products)) * 100",
          businessLogic: 'Assessed products / total products',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Annual',
          sourceTables: ['bronze.udaap_risk_assessments'],
          calculation: { numerator: "COUNT(DISTINCT product_id WHERE assessed = true)", denominator: "COUNT(DISTINCT product_id)", multiplier: 100 },
          businessDefinition: 'UDAAP assessment coverage',
          benchmarks: { industryAverage: '92%', topQuartile: '100%', target: '96%' },
        },
        {
          id: 'CCM-CONS-008',
          name: 'Consent Management Opt-Out Rate',
          description: 'Percentage of customers opting out of data sharing',
          category: 'Consumer Protection',
          subcategory: 'Consent',
          formula: "(COUNT(opt_outs) / COUNT(total_customers)) * 100",
          businessLogic: 'Opt-outs / total customers',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Quarterly',
          sourceTables: ['bronze.customer_consent_preferences'],
          calculation: { numerator: "COUNT(WHERE data_sharing_consent = 'opt_out')", denominator: "COUNT(customer_id)", multiplier: 100 },
          businessDefinition: 'Customer privacy preference',
          benchmarks: { industryAverage: '12%', topQuartile: '8%', target: '10%' },
        },
      ],
    },
  ],
};
