/**
 * CUSTOMER-COMMERCIAL METRICS CATALOG
 * Commercial banking customer relationship and business entity metrics
 */

export const customerCommercialMetricsCatalog = {
  description: 'Commercial customer relationship and business entity performance metrics',
  totalMetrics: 72,
  
  categories: [
    {
      name: 'Business Entity Metrics',
      description: 'Business entity portfolio composition and demographics',
      totalMetrics: 15,
      metrics: [
        {
          id: 'CCM-ENT-001',
          name: 'Total Commercial Customers',
          description: 'Count of active commercial banking customers',
          category: 'Business Entity',
          subcategory: 'Volume',
          formula: "COUNT(DISTINCT entity_id WHERE status = 'active')",
          businessLogic: 'Active commercial customer count',
          dataType: 'INTEGER',
          unit: 'count',
          aggregation: 'COUNT_DISTINCT',
          granularity: 'Daily',
          sourceTables: ['bronze.commercial_business_entities', 'gold.dim_commercial_customer'],
          calculation: { numerator: "COUNT(DISTINCT entity_id)", filters: "status = 'active'" },
          businessDefinition: 'Total active commercial banking relationships',
          benchmarks: { industryAverage: '8,500', topQuartile: '15,000', target: '11,000' },
        },
        {
          id: 'CCM-ENT-002',
          name: 'New Customer Acquisition',
          description: 'Number of new commercial customers onboarded',
          category: 'Business Entity',
          subcategory: 'Growth',
          formula: "COUNT(entity_id WHERE onboarding_date >= PERIOD_START)",
          businessLogic: 'New customers in period',
          dataType: 'INTEGER',
          unit: 'count',
          aggregation: 'COUNT',
          granularity: 'Monthly',
          sourceTables: ['bronze.commercial_business_entities'],
          calculation: { numerator: "COUNT(entity_id)", filters: "onboarding_date BETWEEN period_start AND period_end" },
          businessDefinition: 'Commercial customer acquisition volume',
          benchmarks: { industryAverage: '85/month', topQuartile: '160/month', target: '120/month' },
        },
        {
          id: 'CCM-ENT-003',
          name: 'Customer Growth Rate',
          description: 'Year-over-year growth in commercial customer base',
          category: 'Business Entity',
          subcategory: 'Growth',
          formula: "((current_customers - prior_year_customers) / prior_year_customers) * 100",
          businessLogic: 'YoY customer growth percentage',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Annual',
          sourceTables: ['gold.dim_commercial_customer'],
          calculation: { sql: "((COUNT(current) - COUNT(prior)) / COUNT(prior)) * 100" },
          businessDefinition: 'Commercial customer base expansion',
          benchmarks: { industryAverage: '5.8%', topQuartile: '9.5%', target: '7.5%' },
        },
        {
          id: 'CCM-ENT-004',
          name: 'Customer Churn Rate',
          description: 'Percentage of commercial customers lost annually',
          category: 'Business Entity',
          subcategory: 'Retention',
          formula: "(COUNT(closed_accounts) / COUNT(total_customers)) * 100",
          businessLogic: 'Churned customers / total customers',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Annual',
          sourceTables: ['gold.dim_commercial_customer'],
          calculation: { numerator: "COUNT(WHERE status = 'closed')", denominator: "COUNT(entity_id)", multiplier: 100 },
          businessDefinition: 'Commercial customer attrition rate',
          benchmarks: { industryAverage: '8.5%', topQuartile: '4.2%', target: '6.0%' },
        },
        {
          id: 'CCM-ENT-005',
          name: 'Average Customer Tenure',
          description: 'Mean length of commercial customer relationships',
          category: 'Business Entity',
          subcategory: 'Longevity',
          formula: "AVG(CURRENT_DATE - onboarding_date)",
          businessLogic: 'Average relationship duration in years',
          dataType: 'DECIMAL',
          unit: 'years',
          aggregation: 'AVG',
          granularity: 'Quarterly',
          sourceTables: ['gold.dim_commercial_customer'],
          calculation: { sql: "AVG(EXTRACT(YEAR FROM AGE(CURRENT_DATE, onboarding_date)))" },
          businessDefinition: 'Commercial relationship longevity',
          benchmarks: { industryAverage: '7.2 years', topQuartile: '11.5 years', target: '9.0 years' },
        },
        {
          id: 'CCM-ENT-006',
          name: 'Middle Market Customers',
          description: 'Number of middle market segment customers',
          category: 'Business Entity',
          subcategory: 'Segmentation',
          formula: "COUNT(entity_id WHERE segment = 'middle_market')",
          businessLogic: 'Count of middle market customers',
          dataType: 'INTEGER',
          unit: 'count',
          aggregation: 'COUNT',
          granularity: 'Monthly',
          sourceTables: ['gold.dim_commercial_customer'],
          calculation: { numerator: "COUNT(entity_id)", filters: "customer_segment = 'middle_market'" },
          businessDefinition: 'Middle market customer base size',
          benchmarks: { industryAverage: '3,200', topQuartile: '5,800', target: '4,200' },
        },
        {
          id: 'CCM-ENT-007',
          name: 'Small Business Customers',
          description: 'Number of small business segment customers',
          category: 'Business Entity',
          subcategory: 'Segmentation',
          formula: "COUNT(entity_id WHERE segment = 'small_business')",
          businessLogic: 'Count of small business customers',
          dataType: 'INTEGER',
          unit: 'count',
          aggregation: 'COUNT',
          granularity: 'Monthly',
          sourceTables: ['gold.dim_commercial_customer'],
          calculation: { numerator: "COUNT(entity_id)", filters: "customer_segment = 'small_business'" },
          businessDefinition: 'Small business customer base size',
          benchmarks: { industryAverage: '4,800', topQuartile: '8,500', target: '6,200' },
        },
        {
          id: 'CCM-ENT-008',
          name: 'Corporate Customers',
          description: 'Number of large corporate segment customers',
          category: 'Business Entity',
          subcategory: 'Segmentation',
          formula: "COUNT(entity_id WHERE segment = 'corporate')",
          businessLogic: 'Count of corporate customers',
          dataType: 'INTEGER',
          unit: 'count',
          aggregation: 'COUNT',
          granularity: 'Monthly',
          sourceTables: ['gold.dim_commercial_customer'],
          calculation: { numerator: "COUNT(entity_id)", filters: "customer_segment = 'corporate'" },
          businessDefinition: 'Corporate customer base size',
          benchmarks: { industryAverage: '520', topQuartile: '1,200', target: '850' },
        },
        {
          id: 'CCM-ENT-009',
          name: 'Industry Concentration - Healthcare',
          description: 'Percentage of customers in healthcare industry',
          category: 'Business Entity',
          subcategory: 'Industry Mix',
          formula: "(COUNT(WHERE industry = 'healthcare') / COUNT(total)) * 100",
          businessLogic: 'Healthcare customers / total customers',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Quarterly',
          sourceTables: ['gold.dim_commercial_customer'],
          calculation: { numerator: "COUNT(WHERE industry_code = 'healthcare')", denominator: "COUNT(entity_id)", multiplier: 100 },
          businessDefinition: 'Healthcare industry exposure',
          benchmarks: { industryAverage: '12.5%', topQuartile: '15.8%', target: '14.0%' },
        },
        {
          id: 'CCM-ENT-010',
          name: 'Industry Concentration - Real Estate',
          description: 'Percentage of customers in real estate industry',
          category: 'Business Entity',
          subcategory: 'Industry Mix',
          formula: "(COUNT(WHERE industry = 'real_estate') / COUNT(total)) * 100",
          businessLogic: 'Real estate customers / total customers',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Quarterly',
          sourceTables: ['gold.dim_commercial_customer'],
          calculation: { numerator: "COUNT(WHERE industry_code = 'real_estate')", denominator: "COUNT(entity_id)", multiplier: 100 },
          businessDefinition: 'Real estate industry exposure',
          benchmarks: { industryAverage: '18.5%', topQuartile: '14.2%', target: '16.0%' },
        },
        {
          id: 'CCM-ENT-011',
          name: 'Industry Concentration - Manufacturing',
          description: 'Percentage of customers in manufacturing industry',
          category: 'Business Entity',
          subcategory: 'Industry Mix',
          formula: "(COUNT(WHERE industry = 'manufacturing') / COUNT(total)) * 100",
          businessLogic: 'Manufacturing customers / total customers',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Quarterly',
          sourceTables: ['gold.dim_commercial_customer'],
          calculation: { numerator: "COUNT(WHERE industry_code = 'manufacturing')", denominator: "COUNT(entity_id)", multiplier: 100 },
          businessDefinition: 'Manufacturing industry exposure',
          benchmarks: { industryAverage: '14.8%', topQuartile: '18.5%', target: '16.5%' },
        },
        {
          id: 'CCM-ENT-012',
          name: 'Multi-Product Customers',
          description: 'Number of customers with 3+ products',
          category: 'Business Entity',
          subcategory: 'Cross-sell',
          formula: "COUNT(DISTINCT entity_id WHERE product_count >= 3)",
          businessLogic: 'Customers with 3 or more products',
          dataType: 'INTEGER',
          unit: 'count',
          aggregation: 'COUNT_DISTINCT',
          granularity: 'Monthly',
          sourceTables: ['silver.commercial_customer_product_holdings'],
          calculation: { numerator: "COUNT(DISTINCT entity_id)", filters: "product_count >= 3" },
          businessDefinition: 'Deeply engaged customer relationships',
          benchmarks: { industryAverage: '3,850', topQuartile: '7,200', target: '5,200' },
        },
        {
          id: 'CCM-ENT-013',
          name: 'Average Products per Customer',
          description: 'Mean number of products per commercial customer',
          category: 'Business Entity',
          subcategory: 'Cross-sell',
          formula: "COUNT(products) / COUNT(DISTINCT customers)",
          businessLogic: 'Total products / unique customers',
          dataType: 'DECIMAL',
          unit: 'count',
          aggregation: 'CALCULATED',
          granularity: 'Monthly',
          sourceTables: ['silver.commercial_customer_product_holdings'],
          calculation: { numerator: "COUNT(product_id)", denominator: "COUNT(DISTINCT entity_id)" },
          businessDefinition: 'Product penetration per customer',
          benchmarks: { industryAverage: '2.4', topQuartile: '3.2', target: '2.8' },
        },
        {
          id: 'CCM-ENT-014',
          name: 'Customer Wallet Share',
          description: 'Estimated share of customer banking wallet',
          category: 'Business Entity',
          subcategory: 'Wallet Share',
          formula: "AVG(our_products / total_estimated_products)",
          businessLogic: 'Bank products / total customer banking needs',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'AVG',
          granularity: 'Quarterly',
          sourceTables: ['silver.commercial_wallet_share_estimates'],
          calculation: { numerator: "AVG(bank_share_pct)" },
          businessDefinition: 'Commercial wallet penetration',
          benchmarks: { industryAverage: '42%', topQuartile: '58%', target: '50%' },
        },
        {
          id: 'CCM-ENT-015',
          name: 'Primary Bank Designation',
          description: 'Percentage of customers naming us as primary bank',
          category: 'Business Entity',
          subcategory: 'Wallet Share',
          formula: "(COUNT(primary_bank = true) / COUNT(total)) * 100",
          businessLogic: 'Primary bank customers / total customers',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Annual',
          sourceTables: ['silver.commercial_relationship_depth'],
          calculation: { numerator: "COUNT(WHERE is_primary_bank = true)", denominator: "COUNT(entity_id)", multiplier: 100 },
          businessDefinition: 'Primary banking relationship share',
          benchmarks: { industryAverage: '38%', topQuartile: '52%', target: '45%' },
        },
      ],
    },
    {
      name: 'Credit Risk Metrics',
      description: 'Commercial credit quality and risk assessment',
      totalMetrics: 14,
      metrics: [
        {
          id: 'CCM-RISK-001',
          name: 'Average Commercial Credit Score',
          description: 'Mean business credit score across portfolio',
          category: 'Credit Risk',
          subcategory: 'Credit Quality',
          formula: "AVG(credit_score)",
          businessLogic: 'Average business credit rating',
          dataType: 'INTEGER',
          unit: 'score',
          aggregation: 'AVG',
          granularity: 'Monthly',
          sourceTables: ['bronze.commercial_credit_ratings', 'silver.commercial_credit_profiles_cleansed'],
          calculation: { numerator: "AVG(credit_score)" },
          businessDefinition: 'Portfolio credit quality indicator',
          benchmarks: { industryAverage: '725', topQuartile: '785', target: '755' },
        },
        {
          id: 'CCM-RISK-002',
          name: 'High Credit Quality Customers',
          description: 'Percentage of customers with credit scores >= 750',
          category: 'Credit Risk',
          subcategory: 'Credit Quality',
          formula: "(COUNT(WHERE score >= 750) / COUNT(total)) * 100",
          businessLogic: 'High-quality credit / total customers',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Quarterly',
          sourceTables: ['bronze.commercial_credit_ratings'],
          calculation: { numerator: "COUNT(WHERE credit_score >= 750)", denominator: "COUNT(entity_id)", multiplier: 100 },
          businessDefinition: 'Portfolio quality concentration',
          benchmarks: { industryAverage: '42%', topQuartile: '58%', target: '50%' },
        },
        {
          id: 'CCM-RISK-003',
          name: 'Credit Score Trend',
          description: 'Average change in customer credit scores over quarter',
          category: 'Credit Risk',
          subcategory: 'Trend',
          formula: "AVG(current_score - prior_quarter_score)",
          businessLogic: 'Average credit score change',
          dataType: 'INTEGER',
          unit: 'points',
          aggregation: 'AVG',
          granularity: 'Quarterly',
          sourceTables: ['bronze.commercial_credit_ratings'],
          calculation: { sql: "AVG(current_score - LAG(score, 1) OVER (PARTITION BY entity_id ORDER BY as_of_date))" },
          businessDefinition: 'Portfolio credit quality direction',
          benchmarks: { industryAverage: '+2 pts', topQuartile: '+5 pts', target: '+3 pts' },
        },
        {
          id: 'CCM-RISK-004',
          name: 'Risk Rating Distribution - Pass',
          description: 'Percentage of customers with Pass risk rating',
          category: 'Credit Risk',
          subcategory: 'Risk Rating',
          formula: "(COUNT(rating = 'pass') / COUNT(total)) * 100",
          businessLogic: 'Pass-rated customers / total',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Monthly',
          sourceTables: ['silver.commercial_risk_ratings'],
          calculation: { numerator: "COUNT(WHERE risk_rating = 'pass')", denominator: "COUNT(entity_id)", multiplier: 100 },
          businessDefinition: 'Low-risk customer concentration',
          benchmarks: { industryAverage: '78%', topQuartile: '85%', target: '82%' },
        },
        {
          id: 'CCM-RISK-005',
          name: 'Risk Rating Distribution - Special Mention',
          description: 'Percentage of customers with Special Mention rating',
          category: 'Credit Risk',
          subcategory: 'Risk Rating',
          formula: "(COUNT(rating = 'special_mention') / COUNT(total)) * 100",
          businessLogic: 'Special Mention / total',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Monthly',
          sourceTables: ['silver.commercial_risk_ratings'],
          calculation: { numerator: "COUNT(WHERE risk_rating = 'special_mention')", denominator: "COUNT(entity_id)", multiplier: 100 },
          businessDefinition: 'Watch list concentration',
          benchmarks: { industryAverage: '12%', topQuartile: '8%', target: '10%' },
        },
        {
          id: 'CCM-RISK-006',
          name: 'Risk Rating Distribution - Substandard',
          description: 'Percentage of customers with Substandard rating',
          category: 'Credit Risk',
          subcategory: 'Risk Rating',
          formula: "(COUNT(rating = 'substandard') / COUNT(total)) * 100",
          businessLogic: 'Substandard / total',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Monthly',
          sourceTables: ['silver.commercial_risk_ratings'],
          calculation: { numerator: "COUNT(WHERE risk_rating = 'substandard')", denominator: "COUNT(entity_id)", multiplier: 100 },
          businessDefinition: 'Problem asset concentration',
          benchmarks: { industryAverage: '6.5%', topQuartile: '4.2%', target: '5.0%' },
        },
        {
          id: 'CCM-RISK-007',
          name: 'Risk Rating Downgrades',
          description: 'Number of customers downgraded in risk rating',
          category: 'Credit Risk',
          subcategory: 'Migration',
          formula: "COUNT(WHERE current_rating < prior_rating)",
          businessLogic: 'Count of rating downgrades',
          dataType: 'INTEGER',
          unit: 'count',
          aggregation: 'COUNT',
          granularity: 'Quarterly',
          sourceTables: ['silver.commercial_risk_ratings'],
          calculation: { sql: "COUNT(WHERE rating_change = 'downgrade')" },
          businessDefinition: 'Credit quality deterioration count',
          benchmarks: { industryAverage: '185/quarter', topQuartile: '120/quarter', target: '145/quarter' },
        },
        {
          id: 'CCM-RISK-008',
          name: 'Risk Rating Upgrades',
          description: 'Number of customers upgraded in risk rating',
          category: 'Credit Risk',
          subcategory: 'Migration',
          formula: "COUNT(WHERE current_rating > prior_rating)",
          businessLogic: 'Count of rating upgrades',
          dataType: 'INTEGER',
          unit: 'count',
          aggregation: 'COUNT',
          granularity: 'Quarterly',
          sourceTables: ['silver.commercial_risk_ratings'],
          calculation: { sql: "COUNT(WHERE rating_change = 'upgrade')" },
          businessDefinition: 'Credit quality improvement count',
          benchmarks: { industryAverage: '220/quarter', topQuartile: '310/quarter', target: '265/quarter' },
        },
        {
          id: 'CCM-RISK-009',
          name: 'Debt Service Coverage Ratio',
          description: 'Average DSCR across commercial portfolio',
          category: 'Credit Risk',
          subcategory: 'Capacity',
          formula: "AVG(net_operating_income / debt_service)",
          businessLogic: 'Average debt service coverage',
          dataType: 'DECIMAL',
          unit: 'ratio',
          aggregation: 'AVG',
          granularity: 'Quarterly',
          sourceTables: ['bronze.commercial_financial_statements'],
          calculation: { numerator: "AVG(noi_amount / total_debt_service)" },
          businessDefinition: 'Portfolio debt servicing capacity',
          benchmarks: { industryAverage: '1.45x', topQuartile: '1.75x', target: '1.60x' },
        },
        {
          id: 'CCM-RISK-010',
          name: 'Leverage Ratio',
          description: 'Average total debt to EBITDA ratio',
          category: 'Credit Risk',
          subcategory: 'Leverage',
          formula: "AVG(total_debt / EBITDA)",
          businessLogic: 'Average leverage multiple',
          dataType: 'DECIMAL',
          unit: 'multiple',
          aggregation: 'AVG',
          granularity: 'Quarterly',
          sourceTables: ['bronze.commercial_financial_statements'],
          calculation: { numerator: "AVG(total_debt / ebitda)" },
          businessDefinition: 'Portfolio leverage level',
          benchmarks: { industryAverage: '3.2x', topQuartile: '2.5x', target: '2.8x' },
        },
        {
          id: 'CCM-RISK-011',
          name: 'Liquidity Ratio',
          description: 'Average current ratio across portfolio',
          category: 'Credit Risk',
          subcategory: 'Liquidity',
          formula: "AVG(current_assets / current_liabilities)",
          businessLogic: 'Average current ratio',
          dataType: 'DECIMAL',
          unit: 'ratio',
          aggregation: 'AVG',
          granularity: 'Quarterly',
          sourceTables: ['bronze.commercial_financial_statements'],
          calculation: { numerator: "AVG(current_assets / current_liabilities)" },
          businessDefinition: 'Portfolio liquidity position',
          benchmarks: { industryAverage: '1.8x', topQuartile: '2.4x', target: '2.1x' },
        },
        {
          id: 'CCM-RISK-012',
          name: 'Concentration Risk - Top 10 Customers',
          description: 'Total exposure to top 10 customers as % of capital',
          category: 'Credit Risk',
          subcategory: 'Concentration',
          formula: "(SUM(top_10_exposure) / total_capital) * 100",
          businessLogic: 'Top 10 exposure / capital',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Quarterly',
          sourceTables: ['silver.commercial_exposure_summary'],
          calculation: { sql: "SUM(top_10_total_exposure) / bank_capital * 100" },
          businessDefinition: 'Customer concentration risk',
          benchmarks: { industryAverage: '28%', topQuartile: '18%', target: '22%' },
        },
        {
          id: 'CCM-RISK-013',
          name: 'Sanctioned Customer Count',
          description: 'Number of customers with sanctions screening hits',
          category: 'Credit Risk',
          subcategory: 'Compliance Risk',
          formula: "COUNT(DISTINCT entity_id WHERE has_sanction_hit = true)",
          businessLogic: 'Customers with active sanctions screening alerts',
          dataType: 'INTEGER',
          unit: 'count',
          aggregation: 'COUNT_DISTINCT',
          granularity: 'Monthly',
          sourceTables: ['bronze.commercial_sanctions_screening'],
          calculation: { numerator: "COUNT(DISTINCT entity_id)", filters: "has_active_alert = true" },
          businessDefinition: 'Compliance-flagged customers',
          benchmarks: { industryAverage: '12', topQuartile: '5', target: '8' },
        },
        {
          id: 'CCM-RISK-014',
          name: 'Average Days to Credit Review',
          description: 'Average time from review due date to completion',
          category: 'Credit Risk',
          subcategory: 'Review Timeliness',
          formula: "AVG(review_completion_date - review_due_date)",
          businessLogic: 'Average review cycle time',
          dataType: 'INTEGER',
          unit: 'days',
          aggregation: 'AVG',
          granularity: 'Quarterly',
          sourceTables: ['bronze.commercial_credit_reviews'],
          calculation: { sql: "AVG(EXTRACT(DAY FROM (completion_date - due_date)))" },
          businessDefinition: 'Credit review efficiency',
          benchmarks: { industryAverage: '12 days', topQuartile: '5 days', target: '8 days' },
        },
      ],
    },
    {
      name: 'Financial Performance Metrics',
      description: 'Commercial customer financial health and performance',
      totalMetrics: 13,
      metrics: [
        {
          id: 'CCM-FIN-001',
          name: 'Average Annual Revenue',
          description: 'Mean annual revenue of commercial customers',
          category: 'Financial Performance',
          subcategory: 'Size',
          formula: "AVG(annual_revenue)",
          businessLogic: 'Average customer annual revenue',
          dataType: 'DECIMAL',
          unit: 'currency',
          aggregation: 'AVG',
          granularity: 'Quarterly',
          sourceTables: ['bronze.commercial_financial_statements'],
          calculation: { numerator: "AVG(annual_revenue)" },
          businessDefinition: 'Commercial customer size metric',
          benchmarks: { industryAverage: '$8.5M', topQuartile: '$22M', target: '$14M' },
        },
        {
          id: 'CCM-FIN-002',
          name: 'Median Annual Revenue',
          description: 'Median annual revenue of commercial customers',
          category: 'Financial Performance',
          subcategory: 'Size',
          formula: "MEDIAN(annual_revenue)",
          businessLogic: 'Median customer revenue',
          dataType: 'DECIMAL',
          unit: 'currency',
          aggregation: 'MEDIAN',
          granularity: 'Quarterly',
          sourceTables: ['bronze.commercial_financial_statements'],
          calculation: { sql: "PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY annual_revenue)" },
          businessDefinition: 'Typical customer size',
          benchmarks: { industryAverage: '$4.2M', topQuartile: '$8.5M', target: '$6.0M' },
        },
        {
          id: 'CCM-FIN-003',
          name: 'Average EBITDA',
          description: 'Mean EBITDA of commercial customers',
          category: 'Financial Performance',
          subcategory: 'Profitability',
          formula: "AVG(ebitda)",
          businessLogic: 'Average customer EBITDA',
          dataType: 'DECIMAL',
          unit: 'currency',
          aggregation: 'AVG',
          granularity: 'Quarterly',
          sourceTables: ['bronze.commercial_financial_statements'],
          calculation: { numerator: "AVG(ebitda)" },
          businessDefinition: 'Customer profitability metric',
          benchmarks: { industryAverage: '$1.2M', topQuartile: '$3.5M', target: '$2.0M' },
        },
        {
          id: 'CCM-FIN-004',
          name: 'Average EBITDA Margin',
          description: 'Mean EBITDA margin percentage',
          category: 'Financial Performance',
          subcategory: 'Profitability',
          formula: "AVG(ebitda / revenue) * 100",
          businessLogic: 'Average EBITDA margin',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'AVG',
          granularity: 'Quarterly',
          sourceTables: ['bronze.commercial_financial_statements'],
          calculation: { numerator: "AVG(ebitda / revenue * 100)" },
          businessDefinition: 'Customer operating efficiency',
          benchmarks: { industryAverage: '14.2%', topQuartile: '22.5%', target: '18.0%' },
        },
        {
          id: 'CCM-FIN-005',
          name: 'Revenue Growth Rate',
          description: 'Average YoY revenue growth of customer base',
          category: 'Financial Performance',
          subcategory: 'Growth',
          formula: "AVG((current_revenue - prior_revenue) / prior_revenue) * 100",
          businessLogic: 'Average customer revenue growth',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'AVG',
          granularity: 'Annual',
          sourceTables: ['bronze.commercial_financial_statements'],
          calculation: { sql: "AVG((current_year_revenue - prior_year_revenue) / prior_year_revenue * 100)" },
          businessDefinition: 'Customer business momentum',
          benchmarks: { industryAverage: '7.5%', topQuartile: '12.8%', target: '10.0%' },
        },
        {
          id: 'CCM-FIN-006',
          name: 'Customers with Revenue Decline',
          description: 'Percentage of customers with declining revenue',
          category: 'Financial Performance',
          subcategory: 'Risk',
          formula: "(COUNT(negative_growth) / COUNT(total)) * 100",
          businessLogic: 'Declining revenue customers / total',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Annual',
          sourceTables: ['bronze.commercial_financial_statements'],
          calculation: { numerator: "COUNT(WHERE revenue_growth < 0)", denominator: "COUNT(entity_id)", multiplier: 100 },
          businessDefinition: 'Customer stress indicator',
          benchmarks: { industryAverage: '28%', topQuartile: '18%', target: '22%' },
        },
        {
          id: 'CCM-FIN-007',
          name: 'Average Total Assets',
          description: 'Mean total assets of commercial customers',
          category: 'Financial Performance',
          subcategory: 'Size',
          formula: "AVG(total_assets)",
          businessLogic: 'Average customer total assets',
          dataType: 'DECIMAL',
          unit: 'currency',
          aggregation: 'AVG',
          granularity: 'Quarterly',
          sourceTables: ['bronze.commercial_financial_statements'],
          calculation: { numerator: "AVG(total_assets)" },
          businessDefinition: 'Customer balance sheet size',
          benchmarks: { industryAverage: '$12.5M', topQuartile: '$35M', target: '$22M' },
        },
        {
          id: 'CCM-FIN-008',
          name: 'Average Working Capital',
          description: 'Mean working capital position',
          category: 'Financial Performance',
          subcategory: 'Liquidity',
          formula: "AVG(current_assets - current_liabilities)",
          businessLogic: 'Average working capital',
          dataType: 'DECIMAL',
          unit: 'currency',
          aggregation: 'AVG',
          granularity: 'Quarterly',
          sourceTables: ['bronze.commercial_financial_statements'],
          calculation: { numerator: "AVG(current_assets - current_liabilities)" },
          businessDefinition: 'Customer liquidity position',
          benchmarks: { industryAverage: '$2.1M', topQuartile: '$5.5M', target: '$3.5M' },
        },
        {
          id: 'CCM-FIN-009',
          name: 'Return on Assets',
          description: 'Average ROA across customer portfolio',
          category: 'Financial Performance',
          subcategory: 'Returns',
          formula: "AVG(net_income / total_assets) * 100",
          businessLogic: 'Average customer ROA',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'AVG',
          granularity: 'Annual',
          sourceTables: ['bronze.commercial_financial_statements'],
          calculation: { numerator: "AVG(net_income / total_assets * 100)" },
          businessDefinition: 'Customer asset efficiency',
          benchmarks: { industryAverage: '8.5%', topQuartile: '14.2%', target: '11.0%' },
        },
        {
          id: 'CCM-FIN-010',
          name: 'Return on Equity',
          description: 'Average ROE across customer portfolio',
          category: 'Financial Performance',
          subcategory: 'Returns',
          formula: "AVG(net_income / equity) * 100",
          businessLogic: 'Average customer ROE',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'AVG',
          granularity: 'Annual',
          sourceTables: ['bronze.commercial_financial_statements'],
          calculation: { numerator: "AVG(net_income / total_equity * 100)" },
          businessDefinition: 'Customer equity returns',
          benchmarks: { industryAverage: '15.8%', topQuartile: '24.5%', target: '20.0%' },
        },
        {
          id: 'CCM-FIN-011',
          name: 'Cash Flow Coverage Ratio',
          description: 'Average operating cash flow to debt service',
          category: 'Financial Performance',
          subcategory: 'Cash Flow',
          formula: "AVG(operating_cash_flow / debt_service)",
          businessLogic: 'Average cash flow coverage',
          dataType: 'DECIMAL',
          unit: 'ratio',
          aggregation: 'AVG',
          granularity: 'Quarterly',
          sourceTables: ['bronze.commercial_financial_statements'],
          calculation: { numerator: "AVG(operating_cash_flow / total_debt_service)" },
          businessDefinition: 'Customer debt servicing from operations',
          benchmarks: { industryAverage: '1.65x', topQuartile: '2.2x', target: '1.95x' },
        },
        {
          id: 'CCM-FIN-012',
          name: 'Days Sales Outstanding',
          description: 'Average DSO across customer portfolio',
          category: 'Financial Performance',
          subcategory: 'Working Capital',
          formula: "AVG((accounts_receivable / revenue) * 365)",
          businessLogic: 'Average receivables collection period',
          dataType: 'INTEGER',
          unit: 'days',
          aggregation: 'AVG',
          granularity: 'Quarterly',
          sourceTables: ['bronze.commercial_financial_statements'],
          calculation: { sql: "AVG((accounts_receivable / annual_revenue) * 365)" },
          businessDefinition: 'Customer receivables efficiency',
          benchmarks: { industryAverage: '45 days', topQuartile: '32 days', target: '38 days' },
        },
        {
          id: 'CCM-FIN-013',
          name: 'Inventory Turnover',
          description: 'Average inventory turnover ratio',
          category: 'Financial Performance',
          subcategory: 'Working Capital',
          formula: "AVG(cost_of_goods_sold / average_inventory)",
          businessLogic: 'Average inventory efficiency',
          dataType: 'DECIMAL',
          unit: 'turns',
          aggregation: 'AVG',
          granularity: 'Annual',
          sourceTables: ['bronze.commercial_financial_statements'],
          calculation: { numerator: "AVG(cogs / avg_inventory)" },
          businessDefinition: 'Customer inventory management',
          benchmarks: { industryAverage: '6.5x', topQuartile: '9.2x', target: '7.8x' },
        },
      ],
    },
    {
      name: 'Relationship Management Metrics',
      description: 'RM coverage, productivity, and portfolio management',
      totalMetrics: 15,
      metrics: [
        {
          id: 'CCM-RM-001',
          name: 'Average Customers per RM',
          description: 'Mean number of commercial customers per relationship manager',
          category: 'Relationship Management',
          subcategory: 'Coverage',
          formula: "COUNT(customers) / COUNT(DISTINCT rm_id)",
          businessLogic: 'Customer count / RM count',
          dataType: 'DECIMAL',
          unit: 'count',
          aggregation: 'CALCULATED',
          granularity: 'Monthly',
          sourceTables: ['bronze.commercial_relationship_managers', 'gold.fact_rm_coverage'],
          calculation: { numerator: "COUNT(DISTINCT customer_id)", denominator: "COUNT(DISTINCT rm_id)" },
          businessDefinition: 'RM portfolio size and workload',
          benchmarks: { industryAverage: '45', topQuartile: '65', target: '55' },
        },
        {
          id: 'CCM-RM-002',
          name: 'RM Portfolio Revenue',
          description: 'Average total customer revenue per RM portfolio',
          category: 'Relationship Management',
          subcategory: 'Portfolio Quality',
          formula: "SUM(customer_revenue) / COUNT(DISTINCT rm_id)",
          businessLogic: 'Total customer revenue / RM count',
          dataType: 'DECIMAL',
          unit: 'currency',
          aggregation: 'CALCULATED',
          granularity: 'Quarterly',
          sourceTables: ['bronze.commercial_financial_statements', 'bronze.commercial_relationship_managers'],
          calculation: { sql: "SUM(annual_revenue) / COUNT(DISTINCT rm_id)" },
          businessDefinition: 'RM portfolio value management',
          benchmarks: { industryAverage: '$385M', topQuartile: '$650M', target: '$500M' },
        },
        {
          id: 'CCM-RM-003',
          name: 'RM Productivity - New Customers',
          description: 'Average new customers acquired per RM annually',
          category: 'Relationship Management',
          subcategory: 'Productivity',
          formula: "COUNT(new_customers) / COUNT(DISTINCT rm_id)",
          businessLogic: 'New customers / RM count',
          dataType: 'DECIMAL',
          unit: 'count',
          aggregation: 'CALCULATED',
          granularity: 'Annual',
          sourceTables: ['bronze.commercial_business_entities'],
          calculation: { numerator: "COUNT(WHERE onboarding_year = current_year)", denominator: "COUNT(DISTINCT rm_id)" },
          businessDefinition: 'RM acquisition productivity',
          benchmarks: { industryAverage: '8.5', topQuartile: '14.2', target: '11.0' },
        },
        {
          id: 'CCM-RM-004',
          name: 'RM Productivity - Cross-sell',
          description: 'Average new product sales per RM annually',
          category: 'Relationship Management',
          subcategory: 'Productivity',
          formula: "COUNT(new_products) / COUNT(DISTINCT rm_id)",
          businessLogic: 'New product sales / RM count',
          dataType: 'DECIMAL',
          unit: 'count',
          aggregation: 'CALCULATED',
          granularity: 'Annual',
          sourceTables: ['silver.commercial_product_sales'],
          calculation: { numerator: "COUNT(new_product_id)", denominator: "COUNT(DISTINCT rm_id)" },
          businessDefinition: 'RM cross-sell effectiveness',
          benchmarks: { industryAverage: '32', topQuartile: '55', target: '42' },
        },
        {
          id: 'CCM-RM-005',
          name: 'RM Tenure',
          description: 'Average years of experience for relationship managers',
          category: 'Relationship Management',
          subcategory: 'Experience',
          formula: "AVG(CURRENT_DATE - hire_date)",
          businessLogic: 'Average RM tenure',
          dataType: 'DECIMAL',
          unit: 'years',
          aggregation: 'AVG',
          granularity: 'Quarterly',
          sourceTables: ['bronze.commercial_relationship_managers'],
          calculation: { sql: "AVG(EXTRACT(YEAR FROM AGE(CURRENT_DATE, hire_date)))" },
          businessDefinition: 'RM experience level',
          benchmarks: { industryAverage: '8.5 years', topQuartile: '12.5 years', target: '10.5 years' },
        },
        {
          id: 'CCM-RM-006',
          name: 'RM Turnover Rate',
          description: 'Annual attrition rate for relationship managers',
          category: 'Relationship Management',
          subcategory: 'Retention',
          formula: "(COUNT(departed_rms) / AVG(total_rms)) * 100",
          businessLogic: 'Departed RMs / average RM count',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Annual',
          sourceTables: ['bronze.commercial_relationship_managers'],
          calculation: { numerator: "COUNT(WHERE status = 'departed')", denominator: "AVG(total_active)", multiplier: 100 },
          businessDefinition: 'RM retention metric',
          benchmarks: { industryAverage: '18%', topQuartile: '8%', target: '12%' },
        },
        {
          id: 'CCM-RM-007',
          name: 'Customer Contact Frequency',
          description: 'Average RM customer contacts per quarter',
          category: 'Relationship Management',
          subcategory: 'Engagement',
          formula: "COUNT(customer_contacts) / COUNT(DISTINCT rm_id)",
          businessLogic: 'Total contacts / RM count',
          dataType: 'DECIMAL',
          unit: 'contacts',
          aggregation: 'CALCULATED',
          granularity: 'Quarterly',
          sourceTables: ['bronze.commercial_rm_activities'],
          calculation: { numerator: "COUNT(contact_id)", denominator: "COUNT(DISTINCT rm_id)" },
          businessDefinition: 'RM customer engagement level',
          benchmarks: { industryAverage: '125/quarter', topQuartile: '185/quarter', target: '155/quarter' },
        },
        {
          id: 'CCM-RM-008',
          name: 'Credit Review Completion Rate',
          description: 'Percentage of annual reviews completed on time',
          category: 'Relationship Management',
          subcategory: 'Compliance',
          formula: "(COUNT(on_time_reviews) / COUNT(required_reviews)) * 100",
          businessLogic: 'On-time reviews / required reviews',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Quarterly',
          sourceTables: ['bronze.commercial_credit_reviews'],
          calculation: { numerator: "COUNT(WHERE completion_date <= due_date)", denominator: "COUNT(review_id)", multiplier: 100 },
          businessDefinition: 'RM credit review timeliness',
          benchmarks: { industryAverage: '92%', topQuartile: '98%', target: '95%' },
        },
        {
          id: 'CCM-RM-009',
          name: 'RM Call Reports Filed',
          description: 'Average call reports filed per RM monthly',
          category: 'Relationship Management',
          subcategory: 'Documentation',
          formula: "COUNT(call_reports) / COUNT(DISTINCT rm_id)",
          businessLogic: 'Call reports / RM count',
          dataType: 'DECIMAL',
          unit: 'reports',
          aggregation: 'CALCULATED',
          granularity: 'Monthly',
          sourceTables: ['bronze.commercial_rm_activities'],
          calculation: { numerator: "COUNT(call_report_id)", denominator: "COUNT(DISTINCT rm_id)" },
          businessDefinition: 'RM activity documentation',
          benchmarks: { industryAverage: '28/month', topQuartile: '42/month', target: '35/month' },
        },
        {
          id: 'CCM-RM-010',
          name: 'Pipeline Conversion Rate',
          description: 'Percentage of pipeline opportunities closed won',
          category: 'Relationship Management',
          subcategory: 'Sales Effectiveness',
          formula: "(COUNT(won_opportunities) / COUNT(total_opportunities)) * 100",
          businessLogic: 'Won opportunities / total opportunities',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Quarterly',
          sourceTables: ['bronze.commercial_sales_pipeline'],
          calculation: { numerator: "COUNT(WHERE status = 'won')", denominator: "COUNT(opportunity_id)", multiplier: 100 },
          businessDefinition: 'RM sales conversion effectiveness',
          benchmarks: { industryAverage: '28%', topQuartile: '42%', target: '35%' },
        },
        {
          id: 'CCM-RM-011',
          name: 'Average Deal Size',
          description: 'Mean dollar value of closed opportunities',
          category: 'Relationship Management',
          subcategory: 'Deal Quality',
          formula: "AVG(opportunity_value WHERE status = 'won')",
          businessLogic: 'Average won opportunity value',
          dataType: 'DECIMAL',
          unit: 'currency',
          aggregation: 'AVG',
          granularity: 'Quarterly',
          sourceTables: ['bronze.commercial_sales_pipeline'],
          calculation: { numerator: "AVG(deal_value)", filters: "status = 'won'" },
          businessDefinition: 'RM deal size metric',
          benchmarks: { industryAverage: '$485K', topQuartile: '$825K', target: '$650K' },
        },
        {
          id: 'CCM-RM-012',
          name: 'Sales Cycle Length',
          description: 'Average days from opportunity to closed won',
          category: 'Relationship Management',
          subcategory: 'Sales Velocity',
          formula: "AVG(closed_date - created_date)",
          businessLogic: 'Average sales cycle duration',
          dataType: 'INTEGER',
          unit: 'days',
          aggregation: 'AVG',
          granularity: 'Quarterly',
          sourceTables: ['bronze.commercial_sales_pipeline'],
          calculation: { sql: "AVG(EXTRACT(DAY FROM (closed_date - created_date)))", filters: "status = 'won'" },
          businessDefinition: 'RM sales efficiency',
          benchmarks: { industryAverage: '85 days', topQuartile: '52 days', target: '65 days' },
        },
        {
          id: 'CCM-RM-013',
          name: 'Referral Generation Rate',
          description: 'Average referrals generated per RM quarterly',
          category: 'Relationship Management',
          subcategory: 'Network Development',
          formula: "COUNT(referrals) / COUNT(DISTINCT rm_id)",
          businessLogic: 'Referral count / RM count',
          dataType: 'DECIMAL',
          unit: 'referrals',
          aggregation: 'CALCULATED',
          granularity: 'Quarterly',
          sourceTables: ['bronze.commercial_referrals'],
          calculation: { numerator: "COUNT(referral_id)", denominator: "COUNT(DISTINCT rm_id)" },
          businessDefinition: 'RM referral network activity',
          benchmarks: { industryAverage: '12/quarter', topQuartile: '22/quarter', target: '17/quarter' },
        },
        {
          id: 'CCM-RM-014',
          name: 'Customer Satisfaction Score',
          description: 'Average NPS score for RM portfolio',
          category: 'Relationship Management',
          subcategory: 'Service Quality',
          formula: "AVG(nps_score)",
          businessLogic: 'Average Net Promoter Score',
          dataType: 'INTEGER',
          unit: 'score',
          aggregation: 'AVG',
          granularity: 'Annual',
          sourceTables: ['bronze.commercial_customer_surveys'],
          calculation: { numerator: "AVG(nps_score)" },
          businessDefinition: 'RM customer satisfaction',
          benchmarks: { industryAverage: '42', topQuartile: '68', target: '55' },
        },
        {
          id: 'CCM-RM-015',
          name: 'RM Training Hours',
          description: 'Average annual training hours per RM',
          category: 'Relationship Management',
          subcategory: 'Development',
          formula: "SUM(training_hours) / COUNT(DISTINCT rm_id)",
          businessLogic: 'Total training hours / RM count',
          dataType: 'INTEGER',
          unit: 'hours',
          aggregation: 'CALCULATED',
          granularity: 'Annual',
          sourceTables: ['bronze.commercial_rm_training'],
          calculation: { numerator: "SUM(training_hours)", denominator: "COUNT(DISTINCT rm_id)" },
          businessDefinition: 'RM professional development',
          benchmarks: { industryAverage: '42 hours', topQuartile: '68 hours', target: '55 hours' },
        },
      ],
    },
    {
      name: 'Compliance & KYB Metrics',
      description: 'Know Your Business compliance and regulatory adherence',
      totalMetrics: 15,
      metrics: [
        {
          id: 'CCM-COMP-001',
          name: 'KYB Compliance Rate',
          description: 'Percentage of customers with complete KYB documentation',
          category: 'Compliance',
          subcategory: 'KYB',
          formula: "(COUNT(customers WHERE kyb_complete = true) / COUNT(total_customers)) * 100",
          businessLogic: 'Complete KYB / total customers',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Monthly',
          sourceTables: ['bronze.commercial_kyb_records'],
          calculation: { numerator: "COUNT(WHERE kyb_status = 'complete')", denominator: "COUNT(entity_id)", multiplier: 100 },
          businessDefinition: 'KYB documentation completeness',
          benchmarks: { industryAverage: '96%', topQuartile: '99%', target: '98%' },
        },
        {
          id: 'CCM-COMP-002',
          name: 'KYB Refresh Timeliness',
          description: 'Percentage of KYB refreshes completed on schedule',
          category: 'Compliance',
          subcategory: 'KYB',
          formula: "(COUNT(on_time_refreshes) / COUNT(required_refreshes)) * 100",
          businessLogic: 'On-time refreshes / total refreshes',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Quarterly',
          sourceTables: ['bronze.commercial_kyb_records'],
          calculation: { numerator: "COUNT(WHERE refresh_date <= due_date)", denominator: "COUNT(refresh_id)", multiplier: 100 },
          businessDefinition: 'KYB maintenance timeliness',
          benchmarks: { industryAverage: '88%', topQuartile: '96%', target: '92%' },
        },
        {
          id: 'CCM-COMP-003',
          name: 'CDD Documentation Complete',
          description: 'Percentage with complete Customer Due Diligence files',
          category: 'Compliance',
          subcategory: 'CDD',
          formula: "(COUNT(complete_cdd) / COUNT(total_customers)) * 100",
          businessLogic: 'Complete CDD / total customers',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Monthly',
          sourceTables: ['bronze.commercial_cdd_records'],
          calculation: { numerator: "COUNT(WHERE cdd_complete = true)", denominator: "COUNT(entity_id)", multiplier: 100 },
          businessDefinition: 'CDD file completeness',
          benchmarks: { industryAverage: '94%', topQuartile: '98%', target: '96%' },
        },
        {
          id: 'CCM-COMP-004',
          name: 'EDD Customers Count',
          description: 'Number of customers requiring Enhanced Due Diligence',
          category: 'Compliance',
          subcategory: 'EDD',
          formula: "COUNT(entity_id WHERE edd_required = true)",
          businessLogic: 'Count of EDD customers',
          dataType: 'INTEGER',
          unit: 'count',
          aggregation: 'COUNT',
          granularity: 'Monthly',
          sourceTables: ['bronze.commercial_edd_records'],
          calculation: { numerator: "COUNT(entity_id)", filters: "edd_status = 'required' OR edd_status = 'active'" },
          businessDefinition: 'High-risk customer count',
          benchmarks: { industryAverage: '285', topQuartile: '180', target: '225' },
        },
        {
          id: 'CCM-COMP-005',
          name: 'EDD Completion Rate',
          description: 'Percentage of required EDD reviews completed',
          category: 'Compliance',
          subcategory: 'EDD',
          formula: "(COUNT(complete_edd) / COUNT(required_edd)) * 100",
          businessLogic: 'Complete EDD / required EDD',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Quarterly',
          sourceTables: ['bronze.commercial_edd_records'],
          calculation: { numerator: "COUNT(WHERE edd_complete = true)", denominator: "COUNT(WHERE edd_required = true)", multiplier: 100 },
          businessDefinition: 'EDD compliance rate',
          benchmarks: { industryAverage: '91%', topQuartile: '97%', target: '94%' },
        },
        {
          id: 'CCM-COMP-006',
          name: 'UBO Identification Rate',
          description: 'Percentage of entities with Ultimate Beneficial Owner identified',
          category: 'Compliance',
          subcategory: 'UBO',
          formula: "(COUNT(ubo_identified) / COUNT(total_entities)) * 100",
          businessLogic: 'UBO identified / total entities',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Monthly',
          sourceTables: ['bronze.commercial_ubo_records'],
          calculation: { numerator: "COUNT(WHERE ubo_identified = true)", denominator: "COUNT(entity_id)", multiplier: 100 },
          businessDefinition: 'UBO transparency compliance',
          benchmarks: { industryAverage: '93%', topQuartile: '98%', target: '96%' },
        },
        {
          id: 'CCM-COMP-007',
          name: 'Sanctions Screening Frequency',
          description: 'Average days between sanctions screening checks',
          category: 'Compliance',
          subcategory: 'Sanctions',
          formula: "AVG(current_screening_date - prior_screening_date)",
          businessLogic: 'Average screening interval',
          dataType: 'INTEGER',
          unit: 'days',
          aggregation: 'AVG',
          granularity: 'Monthly',
          sourceTables: ['bronze.commercial_sanctions_screening'],
          calculation: { sql: "AVG(EXTRACT(DAY FROM (current_date - prior_screening_date)))" },
          businessDefinition: 'Sanctions monitoring frequency',
          benchmarks: { industryAverage: '45 days', topQuartile: '30 days', target: '35 days' },
        },
        {
          id: 'CCM-COMP-008',
          name: 'PEP Customers Count',
          description: 'Number of Politically Exposed Person relationships',
          category: 'Compliance',
          subcategory: 'PEP',
          formula: "COUNT(entity_id WHERE is_pep = true)",
          businessLogic: 'Count of PEP customers',
          dataType: 'INTEGER',
          unit: 'count',
          aggregation: 'COUNT',
          granularity: 'Monthly',
          sourceTables: ['bronze.commercial_pep_screening'],
          calculation: { numerator: "COUNT(entity_id)", filters: "pep_status = 'confirmed'" },
          businessDefinition: 'PEP relationship count',
          benchmarks: { industryAverage: '42', topQuartile: '28', target: '35' },
        },
        {
          id: 'CCM-COMP-009',
          name: 'SAR Filing Rate',
          description: 'Suspicious Activity Reports filed per 1000 customers',
          category: 'Compliance',
          subcategory: 'AML',
          formula: "(COUNT(sars) / COUNT(customers)) * 1000",
          businessLogic: 'SAR filings / customer count * 1000',
          dataType: 'DECIMAL',
          unit: 'per 1000',
          aggregation: 'CALCULATED',
          granularity: 'Annual',
          sourceTables: ['bronze.commercial_sar_filings'],
          calculation: { numerator: "COUNT(sar_id)", denominator: "COUNT(DISTINCT entity_id)", multiplier: 1000 },
          businessDefinition: 'AML reporting rate',
          benchmarks: { industryAverage: '3.2 per 1000', topQuartile: '2.5 per 1000', target: '2.8 per 1000' },
        },
        {
          id: 'CCM-COMP-010',
          name: 'CTR Filing Count',
          description: 'Currency Transaction Reports filed annually',
          category: 'Compliance',
          subcategory: 'BSA',
          formula: "COUNT(ctr_id)",
          businessLogic: 'Count of CTR filings',
          dataType: 'INTEGER',
          unit: 'count',
          aggregation: 'COUNT',
          granularity: 'Annual',
          sourceTables: ['bronze.commercial_ctr_filings'],
          calculation: { numerator: "COUNT(ctr_id)" },
          businessDefinition: 'BSA cash reporting volume',
          benchmarks: { industryAverage: '1,850', topQuartile: '1,200', target: '1,500' },
        },
        {
          id: 'CCM-COMP-011',
          name: 'Regulatory Exam Findings',
          description: 'Number of commercial banking exam findings YTD',
          category: 'Compliance',
          subcategory: 'Regulatory',
          formula: "COUNT(finding_id WHERE area = 'commercial')",
          businessLogic: 'Count of exam findings',
          dataType: 'INTEGER',
          unit: 'count',
          aggregation: 'COUNT',
          granularity: 'Annual',
          sourceTables: ['bronze.regulatory_exam_findings'],
          calculation: { numerator: "COUNT(finding_id)", filters: "business_line = 'commercial'" },
          businessDefinition: 'Regulatory examination results',
          benchmarks: { industryAverage: '8', topQuartile: '2', target: '4' },
        },
        {
          id: 'CCM-COMP-012',
          name: 'Customer Complaints',
          description: 'Number of formal customer complaints per quarter',
          category: 'Compliance',
          subcategory: 'Consumer Protection',
          formula: "COUNT(complaint_id)",
          businessLogic: 'Count of customer complaints',
          dataType: 'INTEGER',
          unit: 'count',
          aggregation: 'COUNT',
          granularity: 'Quarterly',
          sourceTables: ['bronze.commercial_customer_complaints'],
          calculation: { numerator: "COUNT(complaint_id)" },
          businessDefinition: 'Customer satisfaction/dispute volume',
          benchmarks: { industryAverage: '12/quarter', topQuartile: '5/quarter', target: '8/quarter' },
        },
        {
          id: 'CCM-COMP-013',
          name: 'Complaint Resolution Time',
          description: 'Average days to resolve customer complaints',
          category: 'Compliance',
          subcategory: 'Consumer Protection',
          formula: "AVG(resolution_date - filing_date)",
          businessLogic: 'Average complaint resolution time',
          dataType: 'INTEGER',
          unit: 'days',
          aggregation: 'AVG',
          granularity: 'Quarterly',
          sourceTables: ['bronze.commercial_customer_complaints'],
          calculation: { sql: "AVG(EXTRACT(DAY FROM (resolution_date - filing_date)))" },
          businessDefinition: 'Complaint handling efficiency',
          benchmarks: { industryAverage: '18 days', topQuartile: '10 days', target: '14 days' },
        },
        {
          id: 'CCM-COMP-014',
          name: 'Data Privacy Incidents',
          description: 'Number of customer data privacy incidents YTD',
          category: 'Compliance',
          subcategory: 'Data Privacy',
          formula: "COUNT(incident_id WHERE severity IN ('medium', 'high'))",
          businessLogic: 'Count of privacy incidents',
          dataType: 'INTEGER',
          unit: 'count',
          aggregation: 'COUNT',
          granularity: 'Annual',
          sourceTables: ['bronze.data_privacy_incidents'],
          calculation: { numerator: "COUNT(incident_id)", filters: "business_line = 'commercial' AND severity >= 'medium'" },
          businessDefinition: 'Data protection compliance',
          benchmarks: { industryAverage: '5', topQuartile: '1', target: '2' },
        },
        {
          id: 'CCM-COMP-015',
          name: 'Policy Exception Rate',
          description: 'Percentage of transactions requiring policy exceptions',
          category: 'Compliance',
          subcategory: 'Policy Adherence',
          formula: "(COUNT(exceptions) / COUNT(total_transactions)) * 100",
          businessLogic: 'Exceptions / total transactions',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Monthly',
          sourceTables: ['bronze.commercial_policy_exceptions'],
          calculation: { numerator: "COUNT(exception_id)", denominator: "COUNT(transaction_id)", multiplier: 100 },
          businessDefinition: 'Policy compliance rate',
          benchmarks: { industryAverage: '2.8%', topQuartile: '1.5%', target: '2.0%' },
        },
      ],
    },
  ],
};
