/**
 * DEPOSITS-COMMERCIAL METRICS CATALOG
 * Commercial deposit portfolio performance and cost of funds metrics
 */

export const depositsCommercialMetricsCatalog = {
  description: 'Commercial deposit portfolio volume, cost of funds, and customer retention metrics',
  totalMetrics: 62,
  
  categories: [
    {
      name: 'Deposit Volume Metrics',
      description: 'Commercial deposit portfolio size and composition',
      totalMetrics: 14,
      metrics: [
        {
          id: 'DCM-VOL-001',
          name: 'Total Commercial Deposits',
          description: 'Total commercial deposit balances',
          category: 'Deposit Volume',
          subcategory: 'Size',
          formula: "SUM(current_balance)",
          businessLogic: 'Sum of all commercial deposit balances',
          dataType: 'DECIMAL',
          unit: 'currency',
          aggregation: 'SUM',
          granularity: 'Daily',
          sourceTables: ['bronze.commercial_deposits', 'gold.fact_deposit_balances'],
          calculation: { numerator: "SUM(balance)" },
          businessDefinition: 'Total commercial deposit funding',
          benchmarks: { industryAverage: '$3.5B', topQuartile: '$7.2B', target: '$5.0B' },
        },
        {
          id: 'DCM-VOL-002',
          name: 'Average Deposit Balance per Customer',
          description: 'Mean deposit balance per commercial customer',
          category: 'Deposit Volume',
          subcategory: 'Concentration',
          formula: "SUM(balances) / COUNT(DISTINCT customers)",
          businessLogic: 'Total deposits / customer count',
          dataType: 'DECIMAL',
          unit: 'currency',
          aggregation: 'CALCULATED',
          granularity: 'Monthly',
          sourceTables: ['gold.fact_deposit_balances'],
          calculation: { numerator: "SUM(balance)", denominator: "COUNT(DISTINCT customer_id)" },
          businessDefinition: 'Average customer deposit relationship size',
          benchmarks: { industryAverage: '$485K', topQuartile: '$920K', target: '$680K' },
        },
        {
          id: 'DCM-VOL-003',
          name: 'DDA Volume',
          description: 'Total non-interest bearing demand deposit balances',
          category: 'Deposit Volume',
          subcategory: 'Product Type',
          formula: "SUM(balance WHERE product_type = 'DDA')",
          businessLogic: 'Sum of DDA balances',
          dataType: 'DECIMAL',
          unit: 'currency',
          aggregation: 'SUM',
          granularity: 'Daily',
          sourceTables: ['bronze.commercial_deposits'],
          calculation: { numerator: "SUM(balance)", filters: "product_code = 'DDA'" },
          businessDefinition: 'Non-interest bearing deposit volume',
          benchmarks: { industryAverage: '$1.2B', topQuartile: '$2.8B', target: '$1.9B' },
        },
        {
          id: 'DCM-VOL-004',
          name: 'Interest-Bearing DDA Volume',
          description: 'Total interest-bearing checking account balances',
          category: 'Deposit Volume',
          subcategory: 'Product Type',
          formula: "SUM(balance WHERE product_type = 'NOW')",
          businessLogic: 'Sum of NOW account balances',
          dataType: 'DECIMAL',
          unit: 'currency',
          aggregation: 'SUM',
          granularity: 'Daily',
          sourceTables: ['bronze.commercial_deposits'],
          calculation: { numerator: "SUM(balance)", filters: "product_code = 'NOW'" },
          businessDefinition: 'Interest-bearing checking volume',
          benchmarks: { industryAverage: '$850M', topQuartile: '$1.9B', target: '$1.3B' },
        },
        {
          id: 'DCM-VOL-005',
          name: 'Money Market Volume',
          description: 'Total money market account balances',
          category: 'Deposit Volume',
          subcategory: 'Product Type',
          formula: "SUM(balance WHERE product_type = 'MMDA')",
          businessLogic: 'Sum of MMDA balances',
          dataType: 'DECIMAL',
          unit: 'currency',
          aggregation: 'SUM',
          granularity: 'Daily',
          sourceTables: ['bronze.commercial_deposits'],
          calculation: { numerator: "SUM(balance)", filters: "product_code = 'MMDA'" },
          businessDefinition: 'Money market deposit volume',
          benchmarks: { industryAverage: '$950M', topQuartile: '$2.1B', target: '$1.5B' },
        },
        {
          id: 'DCM-VOL-006',
          name: 'Savings Volume',
          description: 'Total commercial savings account balances',
          category: 'Deposit Volume',
          subcategory: 'Product Type',
          formula: "SUM(balance WHERE product_type = 'SAVINGS')",
          businessLogic: 'Sum of savings balances',
          dataType: 'DECIMAL',
          unit: 'currency',
          aggregation: 'SUM',
          granularity: 'Daily',
          sourceTables: ['bronze.commercial_deposits'],
          calculation: { numerator: "SUM(balance)", filters: "product_code = 'SAVINGS'" },
          businessDefinition: 'Commercial savings volume',
          benchmarks: { industryAverage: '$285M', topQuartile: '$620M', target: '$420M' },
        },
        {
          id: 'DCM-VOL-007',
          name: 'Time Deposit Volume',
          description: 'Total certificate of deposit balances',
          category: 'Deposit Volume',
          subcategory: 'Product Type',
          formula: "SUM(balance WHERE product_type = 'CD')",
          businessLogic: 'Sum of CD balances',
          dataType: 'DECIMAL',
          unit: 'currency',
          aggregation: 'SUM',
          granularity: 'Daily',
          sourceTables: ['bronze.commercial_deposits'],
          calculation: { numerator: "SUM(balance)", filters: "product_code = 'CD'" },
          businessDefinition: 'Time deposit volume',
          benchmarks: { industryAverage: '$385M', topQuartile: '$850M', target: '$580M' },
        },
        {
          id: 'DCM-VOL-008',
          name: 'Core Deposit Percentage',
          description: 'Core deposits as percentage of total deposits',
          category: 'Deposit Volume',
          subcategory: 'Stability',
          formula: "(SUM(core_deposits) / SUM(total_deposits)) * 100",
          businessLogic: 'Core deposits / total deposits',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Monthly',
          sourceTables: ['gold.fact_deposit_balances'],
          calculation: { numerator: "SUM(WHERE is_core_deposit = true)", denominator: "SUM(balance)", multiplier: 100 },
          businessDefinition: 'Stable funding percentage',
          benchmarks: { industryAverage: '78%', topQuartile: '88%', target: '83%' },
        },
        {
          id: 'DCM-VOL-009',
          name: 'Deposit Concentration - Top 10',
          description: 'Top 10 customers as % of total deposits',
          category: 'Deposit Volume',
          subcategory: 'Concentration',
          formula: "(SUM(top_10_balances) / SUM(total_deposits)) * 100",
          businessLogic: 'Top 10 deposits / total',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Monthly',
          sourceTables: ['silver.commercial_deposit_concentration'],
          calculation: { sql: "SUM(top_10_customer_balances) / SUM(total_balances) * 100" },
          businessDefinition: 'Deposit concentration risk',
          benchmarks: { industryAverage: '24%', topQuartile: '16%', target: '20%' },
        },
        {
          id: 'DCM-VOL-010',
          name: 'Deposit Growth Rate',
          description: 'Year-over-year commercial deposit growth',
          category: 'Deposit Volume',
          subcategory: 'Growth',
          formula: "((current_balance - prior_year_balance) / prior_year_balance) * 100",
          businessLogic: 'YoY deposit growth',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Annual',
          sourceTables: ['gold.fact_deposit_balances'],
          calculation: { numerator: "(current_period - prior_period)", denominator: "prior_period", multiplier: 100 },
          businessDefinition: 'Commercial deposit portfolio expansion',
          benchmarks: { industryAverage: '6.5%', topQuartile: '12%', target: '9%' },
        },
        {
          id: 'DCM-VOL-011',
          name: 'Quarterly Deposit Growth',
          description: 'Quarter-over-quarter deposit balance change',
          category: 'Deposit Volume',
          subcategory: 'Growth',
          formula: "((current_qtr - prior_qtr) / prior_qtr) * 100",
          businessLogic: 'QoQ deposit growth',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Quarterly',
          sourceTables: ['gold.fact_deposit_balances'],
          calculation: { sql: "(SUM(current_quarter) - SUM(prior_quarter)) / SUM(prior_quarter) * 100" },
          businessDefinition: 'Short-term deposit trend',
          benchmarks: { industryAverage: '1.6%', topQuartile: '2.9%', target: '2.2%' },
        },
        {
          id: 'DCM-VOL-012',
          name: 'New Deposit Accounts Opened',
          description: 'Number of new commercial deposit accounts opened',
          category: 'Deposit Volume',
          subcategory: 'Acquisition',
          formula: "COUNT(account_id WHERE open_date IN PERIOD)",
          businessLogic: 'Count of new accounts',
          dataType: 'INTEGER',
          unit: 'count',
          aggregation: 'COUNT',
          granularity: 'Monthly',
          sourceTables: ['bronze.commercial_deposits'],
          calculation: { numerator: "COUNT(account_id)", filters: "open_date BETWEEN period_start AND period_end" },
          businessDefinition: 'Deposit account acquisition volume',
          benchmarks: { industryAverage: '125/month', topQuartile: '245/month', target: '180/month' },
        },
        {
          id: 'DCM-VOL-013',
          name: 'Closed Deposit Accounts',
          description: 'Number of commercial deposit accounts closed',
          category: 'Deposit Volume',
          subcategory: 'Attrition',
          formula: "COUNT(account_id WHERE close_date IN PERIOD)",
          businessLogic: 'Count of closed accounts',
          dataType: 'INTEGER',
          unit: 'count',
          aggregation: 'COUNT',
          granularity: 'Monthly',
          sourceTables: ['bronze.commercial_deposits'],
          calculation: { numerator: "COUNT(account_id)", filters: "close_date BETWEEN period_start AND period_end" },
          businessDefinition: 'Deposit account attrition volume',
          benchmarks: { industryAverage: '58/month', topQuartile: '32/month', target: '42/month' },
        },
        {
          id: 'DCM-VOL-014',
          name: 'Average Daily Balance',
          description: 'Average daily commercial deposit balance',
          category: 'Deposit Volume',
          subcategory: 'Utilization',
          formula: "AVG(daily_balance)",
          businessLogic: 'Average daily deposit balance',
          dataType: 'DECIMAL',
          unit: 'currency',
          aggregation: 'AVG',
          granularity: 'Monthly',
          sourceTables: ['silver.commercial_deposit_daily_balances'],
          calculation: { numerator: "AVG(eod_balance)" },
          businessDefinition: 'Average working capital held',
          benchmarks: { industryAverage: '$3.2B', topQuartile: '$6.5B', target: '$4.6B' },
        },
      ],
    },
    {
      name: 'Cost of Funds Metrics',
      description: 'Commercial deposit pricing and cost efficiency',
      totalMetrics: 12,
      metrics: [
        {
          id: 'DCM-COF-001',
          name: 'Commercial Deposit Cost Rate',
          description: 'Weighted average interest rate paid on commercial deposits',
          category: 'Cost of Funds',
          subcategory: 'Pricing',
          formula: "SUM(interest_expense) / AVG(deposit_balance)",
          businessLogic: 'Annualized cost of commercial deposits',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Quarterly',
          sourceTables: ['gold.fact_deposit_balances'],
          calculation: { numerator: "SUM(interest_paid)", denominator: "AVG(balance)", multiplier: 100 },
          businessDefinition: 'Commercial deposit cost rate',
          benchmarks: { industryAverage: '1.85%', topQuartile: '1.45%', target: '1.65%' },
        },
        {
          id: 'DCM-COF-002',
          name: 'DDA Cost Rate',
          description: 'Interest rate on non-interest DDA (service charges offset)',
          category: 'Cost of Funds',
          subcategory: 'Product Pricing',
          formula: "(service_charge_revenue - dda_costs) / AVG(dda_balance)",
          businessLogic: 'Net revenue/cost on DDA',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Quarterly',
          sourceTables: ['gold.fact_deposit_balances'],
          calculation: { sql: "(SUM(service_charges) - SUM(operating_costs)) / AVG(balance) * 100", filters: "product_type = 'DDA'" },
          businessDefinition: 'Net DDA profitability',
          benchmarks: { industryAverage: '-0.15%', topQuartile: '-0.35%', target: '-0.25%' },
        },
        {
          id: 'DCM-COF-003',
          name: 'NOW Account Cost Rate',
          description: 'Interest rate paid on NOW accounts',
          category: 'Cost of Funds',
          subcategory: 'Product Pricing',
          formula: "SUM(interest_expense) / AVG(now_balance)",
          businessLogic: 'Interest cost on NOW accounts',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Quarterly',
          sourceTables: ['gold.fact_deposit_balances'],
          calculation: { numerator: "SUM(interest_paid)", denominator: "AVG(balance)", multiplier: 100, filters: "product_type = 'NOW'" },
          businessDefinition: 'NOW account cost',
          benchmarks: { industryAverage: '0.85%', topQuartile: '0.65%', target: '0.75%' },
        },
        {
          id: 'DCM-COF-004',
          name: 'Money Market Cost Rate',
          description: 'Interest rate paid on money market accounts',
          category: 'Cost of Funds',
          subcategory: 'Product Pricing',
          formula: "SUM(interest_expense) / AVG(mmda_balance)",
          businessLogic: 'Interest cost on MMDA',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Quarterly',
          sourceTables: ['gold.fact_deposit_balances'],
          calculation: { numerator: "SUM(interest_paid)", denominator: "AVG(balance)", multiplier: 100, filters: "product_type = 'MMDA'" },
          businessDefinition: 'Money market account cost',
          benchmarks: { industryAverage: '2.15%', topQuartile: '1.85%', target: '2.00%' },
        },
        {
          id: 'DCM-COF-005',
          name: 'CD Cost Rate',
          description: 'Interest rate paid on certificates of deposit',
          category: 'Cost of Funds',
          subcategory: 'Product Pricing',
          formula: "SUM(interest_expense) / AVG(cd_balance)",
          businessLogic: 'Interest cost on CDs',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Quarterly',
          sourceTables: ['gold.fact_deposit_balances'],
          calculation: { numerator: "SUM(interest_paid)", denominator: "AVG(balance)", multiplier: 100, filters: "product_type = 'CD'" },
          businessDefinition: 'Certificate of deposit cost',
          benchmarks: { industryAverage: '3.25%', topQuartile: '2.95%', target: '3.10%' },
        },
        {
          id: 'DCM-COF-006',
          name: 'Cost of Funds vs Federal Funds Rate',
          description: 'Deposit cost rate compared to Fed Funds rate',
          category: 'Cost of Funds',
          subcategory: 'Benchmark',
          formula: "deposit_cost_rate - federal_funds_rate",
          businessLogic: 'Deposit cost spread over Fed Funds',
          dataType: 'DECIMAL',
          unit: 'basis_points',
          aggregation: 'CALCULATED',
          granularity: 'Monthly',
          sourceTables: ['gold.fact_deposit_balances', 'bronze.market_rates'],
          calculation: { sql: "(SUM(interest_paid) / AVG(balance) * 100) - fed_funds_rate" },
          businessDefinition: 'Deposit pricing competitiveness',
          benchmarks: { industryAverage: '+45 bps', topQuartile: '+25 bps', target: '+35 bps' },
        },
        {
          id: 'DCM-COF-007',
          name: 'Interest Expense Total',
          description: 'Total interest paid on commercial deposits',
          category: 'Cost of Funds',
          subcategory: 'Total Cost',
          formula: "SUM(interest_paid)",
          businessLogic: 'Total deposit interest expense',
          dataType: 'DECIMAL',
          unit: 'currency',
          aggregation: 'SUM',
          granularity: 'Monthly',
          sourceTables: ['gold.fact_deposit_balances'],
          calculation: { numerator: "SUM(interest_expense)" },
          businessDefinition: 'Commercial deposit interest cost',
          benchmarks: { industryAverage: '$5.4M/month', topQuartile: '$8.7M/month', target: '$6.9M/month' },
        },
        {
          id: 'DCM-COF-008',
          name: 'Interest Expense Growth',
          description: 'YoY growth in deposit interest expense',
          category: 'Cost of Funds',
          subcategory: 'Trend',
          formula: "((current_expense - prior_expense) / prior_expense) * 100",
          businessLogic: 'YoY interest expense growth',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Annual',
          sourceTables: ['gold.fact_deposit_balances'],
          calculation: { sql: "((SUM(current_year_interest) - SUM(prior_year_interest)) / SUM(prior_year_interest)) * 100" },
          businessDefinition: 'Deposit cost trend',
          benchmarks: { industryAverage: '12.5%', topQuartile: '8.2%', target: '10.0%' },
        },
        {
          id: 'DCM-COF-009',
          name: 'Non-Interest DDA Percentage',
          description: 'DDA as percentage of total commercial deposits',
          category: 'Cost of Funds',
          subcategory: 'Low-Cost Mix',
          formula: "(SUM(dda_balance) / SUM(total_deposits)) * 100",
          businessLogic: 'DDA / total deposits',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Monthly',
          sourceTables: ['gold.fact_deposit_balances'],
          calculation: { numerator: "SUM(balance WHERE product_type = 'DDA')", denominator: "SUM(balance)", multiplier: 100 },
          businessDefinition: 'Low-cost deposit composition',
          benchmarks: { industryAverage: '32%', topQuartile: '45%', target: '38%' },
        },
        {
          id: 'DCM-COF-010',
          name: 'Rate Exception Frequency',
          description: 'Percentage of accounts with pricing exceptions',
          category: 'Cost of Funds',
          subcategory: 'Pricing Discipline',
          formula: "(COUNT(rate_exceptions) / COUNT(total_accounts)) * 100",
          businessLogic: 'Exception accounts / total accounts',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Quarterly',
          sourceTables: ['bronze.commercial_deposits'],
          calculation: { numerator: "COUNT(WHERE has_rate_exception = true)", denominator: "COUNT(account_id)", multiplier: 100 },
          businessDefinition: 'Pricing governance adherence',
          benchmarks: { industryAverage: '18.5%', topQuartile: '10.2%', target: '14.0%' },
        },
        {
          id: 'DCM-COF-011',
          name: 'Beta Coefficient',
          description: 'Deposit rate sensitivity to market rate changes',
          category: 'Cost of Funds',
          subcategory: 'Sensitivity',
          formula: "change_in_deposit_rate / change_in_market_rate",
          businessLogic: 'Deposit rate beta to market',
          dataType: 'DECIMAL',
          unit: 'coefficient',
          aggregation: 'CALCULATED',
          granularity: 'Quarterly',
          sourceTables: ['gold.fact_deposit_balances', 'bronze.market_rates'],
          calculation: { sql: "(current_deposit_rate - prior_deposit_rate) / (current_market_rate - prior_market_rate)" },
          businessDefinition: 'Deposit pricing elasticity',
          benchmarks: { industryAverage: '0.65', topQuartile: '0.45', target: '0.55' },
        },
        {
          id: 'DCM-COF-012',
          name: 'Deposit Margin',
          description: 'Net interest margin on commercial deposits',
          category: 'Cost of Funds',
          subcategory: 'Profitability',
          formula: "(earning_rate - funding_cost) * deposit_balance",
          businessLogic: 'Earnings on deposits minus cost',
          dataType: 'DECIMAL',
          unit: 'currency',
          aggregation: 'CALCULATED',
          granularity: 'Quarterly',
          sourceTables: ['gold.fact_deposit_balances'],
          calculation: { sql: "(AVG(asset_yield) - AVG(deposit_cost)) * AVG(balance)" },
          businessDefinition: 'Deposit net interest income',
          benchmarks: { industryAverage: '$8.5M/qtr', topQuartile: '$16.2M/qtr', target: '$12.0M/qtr' },
        },
      ],
    },
    {
      name: 'Deposit Retention & Stability Metrics',
      description: 'Commercial deposit customer loyalty and account longevity',
      totalMetrics: 12,
      metrics: [
        {
          id: 'DCM-RET-001',
          name: 'Deposit Customer Retention Rate',
          description: 'Percentage of commercial deposit customers retained',
          category: 'Retention',
          subcategory: 'Loyalty',
          formula: "(retained_customers / prior_period_customers) * 100",
          businessLogic: 'Retained customers / total customers',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Annual',
          sourceTables: ['silver.commercial_deposit_customers'],
          calculation: { numerator: "COUNT(WHERE active_in_both_periods = true)", denominator: "COUNT(prior_period_customers)", multiplier: 100 },
          businessDefinition: 'Commercial deposit customer loyalty',
          benchmarks: { industryAverage: '94%', topQuartile: '97%', target: '96%' },
        },
        {
          id: 'DCM-RET-002',
          name: 'Deposit Runoff Rate',
          description: 'Percentage of deposits withdrawn/closed annually',
          category: 'Retention',
          subcategory: 'Attrition',
          formula: "(closed_balance / opening_balance) * 100",
          businessLogic: 'Closed deposits / beginning balance',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Annual',
          sourceTables: ['bronze.commercial_deposits'],
          calculation: { numerator: "SUM(WHERE close_date IS NOT NULL)", denominator: "SUM(opening_balance)", multiplier: 100 },
          businessDefinition: 'Annual deposit attrition rate',
          benchmarks: { industryAverage: '14.5%', topQuartile: '9.2%', target: '11.5%' },
        },
        {
          id: 'DCM-RET-003',
          name: 'Account Longevity',
          description: 'Average age of commercial deposit accounts',
          category: 'Retention',
          subcategory: 'Tenure',
          formula: "AVG(CURRENT_DATE - open_date)",
          businessLogic: 'Average account age in years',
          dataType: 'DECIMAL',
          unit: 'years',
          aggregation: 'AVG',
          granularity: 'Quarterly',
          sourceTables: ['bronze.commercial_deposits'],
          calculation: { sql: "AVG(EXTRACT(YEAR FROM AGE(CURRENT_DATE, open_date)))" },
          businessDefinition: 'Deposit relationship longevity',
          benchmarks: { industryAverage: '6.8 years', topQuartile: '9.5 years', target: '8.2 years' },
        },
        {
          id: 'DCM-RET-004',
          name: 'Balance Volatility',
          description: 'Standard deviation of daily balances',
          category: 'Retention',
          subcategory: 'Stability',
          formula: "STDDEV(daily_balance)",
          businessLogic: 'Standard deviation of balances',
          dataType: 'DECIMAL',
          unit: 'currency',
          aggregation: 'STDDEV',
          granularity: 'Quarterly',
          sourceTables: ['silver.commercial_deposit_daily_balances'],
          calculation: { sql: "STDDEV(eod_balance)" },
          businessDefinition: 'Deposit balance stability',
          benchmarks: { industryAverage: '$185M', topQuartile: '$95M', target: '$130M' },
        },
        {
          id: 'DCM-RET-005',
          name: 'Net Deposit Growth',
          description: 'New deposits minus closed deposits',
          category: 'Retention',
          subcategory: 'Net Growth',
          formula: "SUM(new_balances) - SUM(closed_balances)",
          businessLogic: 'Gross new deposits - closures',
          dataType: 'DECIMAL',
          unit: 'currency',
          aggregation: 'CALCULATED',
          granularity: 'Monthly',
          sourceTables: ['bronze.commercial_deposits'],
          calculation: { sql: "SUM(WHERE open_date IN PERIOD) - SUM(WHERE close_date IN PERIOD)" },
          businessDefinition: 'Organic deposit growth',
          benchmarks: { industryAverage: '$18M/month', topQuartile: '$42M/month', target: '$28M/month' },
        },
        {
          id: 'DCM-RET-006',
          name: 'Relationship Depth Score',
          description: 'Average number of deposit products per customer',
          category: 'Retention',
          subcategory: 'Cross-sell',
          formula: "COUNT(accounts) / COUNT(DISTINCT customers)",
          businessLogic: 'Total accounts / unique customers',
          dataType: 'DECIMAL',
          unit: 'accounts',
          aggregation: 'CALCULATED',
          granularity: 'Monthly',
          sourceTables: ['bronze.commercial_deposits'],
          calculation: { numerator: "COUNT(account_id)", denominator: "COUNT(DISTINCT customer_id)" },
          businessDefinition: 'Deposit product penetration',
          benchmarks: { industryAverage: '1.8', topQuartile: '2.6', target: '2.2' },
        },
        {
          id: 'DCM-RET-007',
          name: 'Customer Tenure Segmentation - 0-2 Years',
          description: 'Percentage of customers with 0-2 year tenure',
          category: 'Retention',
          subcategory: 'Tenure Distribution',
          formula: "(COUNT(WHERE tenure <= 2) / COUNT(total)) * 100",
          businessLogic: 'New customers / total',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Quarterly',
          sourceTables: ['silver.commercial_deposit_customers'],
          calculation: { numerator: "COUNT(WHERE customer_tenure_years <= 2)", denominator: "COUNT(customer_id)", multiplier: 100 },
          businessDefinition: 'New customer concentration',
          benchmarks: { industryAverage: '22%', topQuartile: '18%', target: '20%' },
        },
        {
          id: 'DCM-RET-008',
          name: 'Customer Tenure Segmentation - 3-5 Years',
          description: 'Percentage of customers with 3-5 year tenure',
          category: 'Retention',
          subcategory: 'Tenure Distribution',
          formula: "(COUNT(WHERE tenure BETWEEN 3 AND 5) / COUNT(total)) * 100",
          businessLogic: 'Established customers / total',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Quarterly',
          sourceTables: ['silver.commercial_deposit_customers'],
          calculation: { numerator: "COUNT(WHERE customer_tenure_years BETWEEN 3 AND 5)", denominator: "COUNT(customer_id)", multiplier: 100 },
          businessDefinition: 'Established customer concentration',
          benchmarks: { industryAverage: '28%', topQuartile: '32%', target: '30%' },
        },
        {
          id: 'DCM-RET-009',
          name: 'Customer Tenure Segmentation - 5+ Years',
          description: 'Percentage of customers with 5+ year tenure',
          category: 'Retention',
          subcategory: 'Tenure Distribution',
          formula: "(COUNT(WHERE tenure > 5) / COUNT(total)) * 100",
          businessLogic: 'Longstanding customers / total',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Quarterly',
          sourceTables: ['silver.commercial_deposit_customers'],
          calculation: { numerator: "COUNT(WHERE customer_tenure_years > 5)", denominator: "COUNT(customer_id)", multiplier: 100 },
          businessDefinition: 'Loyal customer concentration',
          benchmarks: { industryAverage: '50%', topQuartile: '62%', target: '56%' },
        },
        {
          id: 'DCM-RET-010',
          name: 'Sweep Account Adoption',
          description: 'Percentage of eligible customers using sweep services',
          category: 'Retention',
          subcategory: 'Service Adoption',
          formula: "(COUNT(sweep_accounts) / COUNT(eligible_customers)) * 100",
          businessLogic: 'Sweep users / eligible customers',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Quarterly',
          sourceTables: ['bronze.commercial_deposits'],
          calculation: { numerator: "COUNT(WHERE has_sweep_service = true)", denominator: "COUNT(WHERE sweep_eligible = true)", multiplier: 100 },
          businessDefinition: 'Cash management service adoption',
          benchmarks: { industryAverage: '38%', topQuartile: '56%', target: '47%' },
        },
        {
          id: 'DCM-RET-011',
          name: 'ZBA Account Adoption',
          description: 'Percentage of customers using Zero Balance Accounts',
          category: 'Retention',
          subcategory: 'Service Adoption',
          formula: "(COUNT(zba_accounts) / COUNT(eligible_customers)) * 100",
          businessLogic: 'ZBA users / eligible customers',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Quarterly',
          sourceTables: ['bronze.commercial_deposits'],
          calculation: { numerator: "COUNT(WHERE has_zba = true)", denominator: "COUNT(WHERE zba_eligible = true)", multiplier: 100 },
          businessDefinition: 'ZBA service penetration',
          benchmarks: { industryAverage: '24%', topQuartile: '38%', target: '31%' },
        },
        {
          id: 'DCM-RET-012',
          name: 'At-Risk Customer Count',
          description: 'Number of customers with declining balances',
          category: 'Retention',
          subcategory: 'Risk',
          formula: "COUNT(DISTINCT customer_id WHERE balance_trend = 'declining')",
          businessLogic: 'Customers with negative balance trends',
          dataType: 'INTEGER',
          unit: 'count',
          aggregation: 'COUNT_DISTINCT',
          granularity: 'Monthly',
          sourceTables: ['silver.commercial_deposit_trends'],
          calculation: { sql: "COUNT(DISTINCT customer_id WHERE 3_month_trend < 0)" },
          businessDefinition: 'Customer retention risk',
          benchmarks: { industryAverage: '850', topQuartile: '520', target: '680' },
        },
      ],
    },
    {
      name: 'Operational & Service Quality Metrics',
      description: 'Commercial deposit operations efficiency and service metrics',
      totalMetrics: 12,
      metrics: [
        {
          id: 'DCM-OPS-001',
          name: 'Account Opening Time',
          description: 'Average days from application to account funding',
          category: 'Operations',
          subcategory: 'Efficiency',
          formula: "AVG(funding_date - application_date)",
          businessLogic: 'Average account opening cycle time',
          dataType: 'INTEGER',
          unit: 'days',
          aggregation: 'AVG',
          granularity: 'Monthly',
          sourceTables: ['bronze.commercial_deposits'],
          calculation: { sql: "AVG(EXTRACT(DAY FROM (first_funding_date - application_date)))" },
          businessDefinition: 'Account onboarding efficiency',
          benchmarks: { industryAverage: '5.8 days', topQuartile: '3.2 days', target: '4.5 days' },
        },
        {
          id: 'DCM-OPS-002',
          name: 'Transaction Volume',
          description: 'Total commercial deposit transaction count',
          category: 'Operations',
          subcategory: 'Activity',
          formula: "COUNT(transaction_id)",
          businessLogic: 'Total transaction count',
          dataType: 'INTEGER',
          unit: 'count',
          aggregation: 'COUNT',
          granularity: 'Monthly',
          sourceTables: ['bronze.commercial_deposit_transactions'],
          calculation: { numerator: "COUNT(transaction_id)" },
          businessDefinition: 'Deposit transaction activity',
          benchmarks: { industryAverage: '285K/month', topQuartile: '520K/month', target: '385K/month' },
        },
        {
          id: 'DCM-OPS-003',
          name: 'Average Transactions per Account',
          description: 'Mean monthly transactions per deposit account',
          category: 'Operations',
          subcategory: 'Activity',
          formula: "COUNT(transactions) / COUNT(DISTINCT accounts)",
          businessLogic: 'Total transactions / account count',
          dataType: 'DECIMAL',
          unit: 'transactions',
          aggregation: 'CALCULATED',
          granularity: 'Monthly',
          sourceTables: ['bronze.commercial_deposit_transactions'],
          calculation: { numerator: "COUNT(transaction_id)", denominator: "COUNT(DISTINCT account_id)" },
          businessDefinition: 'Account utilization metric',
          benchmarks: { industryAverage: '42', topQuartile: '68', target: '55' },
        },
        {
          id: 'DCM-OPS-004',
          name: 'Exception Item Rate',
          description: 'Percentage of transactions requiring manual intervention',
          category: 'Operations',
          subcategory: 'Quality',
          formula: "(COUNT(exceptions) / COUNT(total_transactions)) * 100",
          businessLogic: 'Exception transactions / total',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Monthly',
          sourceTables: ['bronze.commercial_deposit_transactions'],
          calculation: { numerator: "COUNT(WHERE requires_manual_review = true)", denominator: "COUNT(transaction_id)", multiplier: 100 },
          businessDefinition: 'Transaction processing quality',
          benchmarks: { industryAverage: '1.8%', topQuartile: '0.9%', target: '1.3%' },
        },
        {
          id: 'DCM-OPS-005',
          name: 'Returned Item Rate',
          description: 'Percentage of deposit items returned',
          category: 'Operations',
          subcategory: 'Quality',
          formula: "(COUNT(returned_items) / COUNT(total_items)) * 100",
          businessLogic: 'Returned items / total items',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Monthly',
          sourceTables: ['bronze.commercial_deposit_transactions'],
          calculation: { numerator: "COUNT(WHERE item_returned = true)", denominator: "COUNT(item_id)", multiplier: 100 },
          businessDefinition: 'Deposit item quality',
          benchmarks: { industryAverage: '0.65%', topQuartile: '0.35%', target: '0.50%' },
        },
        {
          id: 'DCM-OPS-006',
          name: 'Overdraft Frequency',
          description: 'Average overdrafts per DDA account monthly',
          category: 'Operations',
          subcategory: 'Overdrafts',
          formula: "COUNT(overdrafts) / COUNT(DISTINCT dda_accounts)",
          businessLogic: 'Overdraft count / DDA accounts',
          dataType: 'DECIMAL',
          unit: 'overdrafts',
          aggregation: 'CALCULATED',
          granularity: 'Monthly',
          sourceTables: ['bronze.commercial_deposit_transactions'],
          calculation: { numerator: "COUNT(WHERE transaction_type = 'overdraft')", denominator: "COUNT(DISTINCT account_id)", filters: "product_type = 'DDA'" },
          businessDefinition: 'DDA overdraft activity',
          benchmarks: { industryAverage: '0.45/month', topQuartile: '0.25/month', target: '0.35/month' },
        },
        {
          id: 'DCM-OPS-007',
          name: 'Overdraft Fee Revenue',
          description: 'Total overdraft fees collected monthly',
          category: 'Operations',
          subcategory: 'Revenue',
          formula: "SUM(overdraft_fees)",
          businessLogic: 'Total overdraft fee income',
          dataType: 'DECIMAL',
          unit: 'currency',
          aggregation: 'SUM',
          granularity: 'Monthly',
          sourceTables: ['bronze.commercial_deposit_fees'],
          calculation: { numerator: "SUM(fee_amount)", filters: "fee_type = 'overdraft'" },
          businessDefinition: 'Overdraft fee income',
          benchmarks: { industryAverage: '$85K/month', topQuartile: '$65K/month', target: '$75K/month' },
        },
        {
          id: 'DCM-OPS-008',
          name: 'Service Charge Revenue',
          description: 'Total monthly service charge and fee income',
          category: 'Operations',
          subcategory: 'Revenue',
          formula: "SUM(service_charges)",
          businessLogic: 'Total service fee income',
          dataType: 'DECIMAL',
          unit: 'currency',
          aggregation: 'SUM',
          granularity: 'Monthly',
          sourceTables: ['bronze.commercial_deposit_fees'],
          calculation: { numerator: "SUM(fee_amount)", filters: "fee_type IN ('service_charge', 'maintenance', 'transaction')" },
          businessDefinition: 'Deposit service fee revenue',
          benchmarks: { industryAverage: '$220K/month', topQuartile: '$380K/month', target: '$295K/month' },
        },
        {
          id: 'DCM-OPS-009',
          name: 'Fee Waiver Rate',
          description: 'Percentage of fees waived for relationship pricing',
          category: 'Operations',
          subcategory: 'Waivers',
          formula: "(SUM(waived_fees) / SUM(total_fees_assessed)) * 100",
          businessLogic: 'Waived fees / total fees',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Monthly',
          sourceTables: ['bronze.commercial_deposit_fees'],
          calculation: { numerator: "SUM(WHERE fee_waived = true)", denominator: "SUM(fee_amount_assessed)", multiplier: 100 },
          businessDefinition: 'Fee waiver frequency',
          benchmarks: { industryAverage: '28.5%', topQuartile: '18.2%', target: '23.0%' },
        },
        {
          id: 'DCM-OPS-010',
          name: 'Wire Transfer Volume',
          description: 'Number of wire transfers on deposit accounts',
          category: 'Operations',
          subcategory: 'Activity',
          formula: "COUNT(wire_id)",
          businessLogic: 'Count of wire transfers',
          dataType: 'INTEGER',
          unit: 'count',
          aggregation: 'COUNT',
          granularity: 'Monthly',
          sourceTables: ['bronze.commercial_deposit_transactions'],
          calculation: { numerator: "COUNT(transaction_id)", filters: "transaction_type = 'wire'" },
          businessDefinition: 'Wire activity on deposits',
          benchmarks: { industryAverage: '8,500/month', topQuartile: '15,200/month', target: '11,500/month' },
        },
        {
          id: 'DCM-OPS-011',
          name: 'ACH Transaction Volume',
          description: 'Number of ACH transactions on deposit accounts',
          category: 'Operations',
          subcategory: 'Activity',
          formula: "COUNT(ach_id)",
          businessLogic: 'Count of ACH transactions',
          dataType: 'INTEGER',
          unit: 'count',
          aggregation: 'COUNT',
          granularity: 'Monthly',
          sourceTables: ['bronze.commercial_deposit_transactions'],
          calculation: { numerator: "COUNT(transaction_id)", filters: "transaction_type = 'ACH'" },
          businessDefinition: 'ACH activity on deposits',
          benchmarks: { industryAverage: '185K/month', topQuartile: '350K/month', target: '260K/month' },
        },
        {
          id: 'DCM-OPS-012',
          name: 'Customer Service Inquiries',
          description: 'Number of deposit-related service requests monthly',
          category: 'Operations',
          subcategory: 'Service',
          formula: "COUNT(inquiry_id WHERE category = 'deposits')",
          businessLogic: 'Count of deposit service inquiries',
          dataType: 'INTEGER',
          unit: 'count',
          aggregation: 'COUNT',
          granularity: 'Monthly',
          sourceTables: ['bronze.customer_service_inquiries'],
          calculation: { numerator: "COUNT(inquiry_id)", filters: "product_category = 'commercial_deposits'" },
          businessDefinition: 'Deposit customer service volume',
          benchmarks: { industryAverage: '1,250/month', topQuartile: '850/month', target: '1,050/month' },
        },
      ],
    },
    {
      name: 'Liquidity & Regulatory Metrics',
      description: 'Commercial deposit liquidity coverage and regulatory compliance',
      totalMetrics: 12,
      metrics: [
        {
          id: 'DCM-LIQ-001',
          name: 'LCR - Liquidity Coverage Ratio',
          description: 'High quality liquid assets / 30-day net cash outflow',
          category: 'Liquidity',
          subcategory: 'Basel III',
          formula: "HQLA / net_cash_outflow_30_days",
          businessLogic: 'LCR regulatory ratio',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Daily',
          sourceTables: ['gold.fact_deposit_balances', 'silver.liquidity_metrics'],
          calculation: { numerator: "SUM(high_quality_liquid_assets)", denominator: "SUM(30_day_net_outflow)" },
          businessDefinition: 'Liquidity coverage adequacy',
          benchmarks: { industryAverage: '125%', topQuartile: '145%', target: '135%', regulatory_minimum: '100%' },
        },
        {
          id: 'DCM-LIQ-002',
          name: 'NSFR - Net Stable Funding Ratio',
          description: 'Available stable funding / required stable funding',
          category: 'Liquidity',
          subcategory: 'Basel III',
          formula: "ASF / RSF",
          businessLogic: 'NSFR regulatory ratio',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Quarterly',
          sourceTables: ['gold.fact_deposit_balances', 'silver.liquidity_metrics'],
          calculation: { numerator: "SUM(available_stable_funding)", denominator: "SUM(required_stable_funding)" },
          businessDefinition: 'Structural liquidity position',
          benchmarks: { industryAverage: '118%', topQuartile: '128%', target: '123%', regulatory_minimum: '100%' },
        },
        {
          id: 'DCM-LIQ-003',
          name: 'Deposit Withdrawal Assumptions - DDA',
          description: 'Expected 30-day withdrawal rate for DDA',
          category: 'Liquidity',
          subcategory: 'Runoff Assumptions',
          formula: "historical_30_day_runoff_pct",
          businessLogic: 'Historical DDA withdrawal rate',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'AVG',
          granularity: 'Quarterly',
          sourceTables: ['silver.deposit_runoff_analysis'],
          calculation: { sql: "AVG(30_day_withdrawal_pct)" },
          businessDefinition: 'DDA liquidity stress assumption',
          benchmarks: { industryAverage: '8.5%', topQuartile: '6.2%', target: '7.5%' },
        },
        {
          id: 'DCM-LIQ-004',
          name: 'Uninsured Deposit Percentage',
          description: 'Deposits exceeding FDIC insurance limits',
          category: 'Liquidity',
          subcategory: 'Flight Risk',
          formula: "(SUM(uninsured_balance) / SUM(total_balance)) * 100",
          businessLogic: 'Uninsured deposits / total',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Quarterly',
          sourceTables: ['silver.commercial_deposit_insurance_analysis'],
          calculation: { numerator: "SUM(balance_over_insurance_limit)", denominator: "SUM(total_balance)", multiplier: 100 },
          businessDefinition: 'Uninsured deposit exposure',
          benchmarks: { industryAverage: '42%', topQuartile: '32%', target: '37%' },
        },
        {
          id: 'DCM-LIQ-005',
          name: 'Brokered Deposit Percentage',
          description: 'Brokered deposits as % of total commercial deposits',
          category: 'Liquidity',
          subcategory: 'Funding Stability',
          formula: "(SUM(brokered_deposits) / SUM(total_deposits)) * 100",
          businessLogic: 'Brokered / total deposits',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Quarterly',
          sourceTables: ['bronze.commercial_deposits'],
          calculation: { numerator: "SUM(balance WHERE is_brokered = true)", denominator: "SUM(balance)", multiplier: 100 },
          businessDefinition: 'Hot money concentration',
          benchmarks: { industryAverage: '8.5%', topQuartile: '3.2%', target: '5.5%', regulatory_threshold: '10%' },
        },
        {
          id: 'DCM-LIQ-006',
          name: 'Reciprocal Deposit Percentage',
          description: 'Reciprocal deposits (e.g., CDARS, ICS) as % of total',
          category: 'Liquidity',
          subcategory: 'Funding Stability',
          formula: "(SUM(reciprocal_deposits) / SUM(total_deposits)) * 100",
          businessLogic: 'Reciprocal / total deposits',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Quarterly',
          sourceTables: ['bronze.commercial_deposits'],
          calculation: { numerator: "SUM(balance WHERE is_reciprocal = true)", denominator: "SUM(balance)", multiplier: 100 },
          businessDefinition: 'Reciprocal deposit usage',
          benchmarks: { industryAverage: '4.5%', topQuartile: '2.8%', target: '3.5%' },
        },
        {
          id: 'DCM-LIQ-007',
          name: 'Average Deposit Maturity',
          description: 'Weighted average maturity of time deposits',
          category: 'Liquidity',
          subcategory: 'Maturity Profile',
          formula: "SUM(balance * days_to_maturity) / SUM(balance)",
          businessLogic: 'Weighted average CD maturity',
          dataType: 'INTEGER',
          unit: 'days',
          aggregation: 'CALCULATED',
          granularity: 'Monthly',
          sourceTables: ['bronze.commercial_deposits'],
          calculation: { sql: "SUM(balance * days_to_maturity) / SUM(balance)", filters: "product_type = 'CD'" },
          businessDefinition: 'Time deposit maturity profile',
          benchmarks: { industryAverage: '185 days', topQuartile: '245 days', target: '215 days' },
        },
        {
          id: 'DCM-LIQ-008',
          name: 'CD Maturities Next 30 Days',
          description: 'CDs maturing within next 30 days',
          category: 'Liquidity',
          subcategory: 'Rollover Risk',
          formula: "SUM(balance WHERE maturity_date <= CURRENT_DATE + 30)",
          businessLogic: 'Near-term maturing CDs',
          dataType: 'DECIMAL',
          unit: 'currency',
          aggregation: 'SUM',
          granularity: 'Daily',
          sourceTables: ['bronze.commercial_deposits'],
          calculation: { numerator: "SUM(balance)", filters: "product_type = 'CD' AND maturity_date <= CURRENT_DATE + 30" },
          businessDefinition: 'Near-term rollover exposure',
          benchmarks: { industryAverage: '$95M', topQuartile: '$65M', target: '$80M' },
        },
        {
          id: 'DCM-LIQ-009',
          name: 'CD Rollover Rate',
          description: 'Percentage of maturing CDs that renew',
          category: 'Liquidity',
          subcategory: 'Rollover Risk',
          formula: "(COUNT(renewed_cds) / COUNT(matured_cds)) * 100",
          businessLogic: 'Renewed CDs / matured CDs',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Monthly',
          sourceTables: ['bronze.commercial_deposits'],
          calculation: { numerator: "COUNT(WHERE renewed = true)", denominator: "COUNT(WHERE maturity_date IN PERIOD)", multiplier: 100, filters: "product_type = 'CD'" },
          businessDefinition: 'CD renewal retention rate',
          benchmarks: { industryAverage: '72%', topQuartile: '82%', target: '77%' },
        },
        {
          id: 'DCM-LIQ-010',
          name: 'Loan-to-Deposit Ratio',
          description: 'Total loans / total commercial deposits',
          category: 'Liquidity',
          subcategory: 'Balance Sheet',
          formula: "(total_loans / total_deposits) * 100",
          businessLogic: 'Loans funded by deposits',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Monthly',
          sourceTables: ['gold.fact_deposit_balances', 'gold.fact_loan_portfolio'],
          calculation: { numerator: "SUM(loan_balance)", denominator: "SUM(deposit_balance)", multiplier: 100 },
          businessDefinition: 'Deposit utilization for lending',
          benchmarks: { industryAverage: '82%', topQuartile: '78%', target: '80%' },
        },
        {
          id: 'DCM-LIQ-011',
          name: 'Large Deposit Concentration',
          description: 'Single deposits >= $100K as % of total',
          category: 'Liquidity',
          subcategory: 'Concentration Risk',
          formula: "(SUM(deposits >= 100000) / SUM(total_deposits)) * 100",
          businessLogic: 'Large deposits / total',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Quarterly',
          sourceTables: ['bronze.commercial_deposits'],
          calculation: { numerator: "SUM(balance WHERE balance >= 100000)", denominator: "SUM(balance)", multiplier: 100 },
          businessDefinition: 'Jumbo deposit concentration',
          benchmarks: { industryAverage: '68%', topQuartile: '58%', target: '63%' },
        },
        {
          id: 'DCM-LIQ-012',
          name: 'Deposit Beta Historical',
          description: 'Historical deposit rate sensitivity to Fed Funds changes',
          category: 'Liquidity',
          subcategory: 'Rate Sensitivity',
          formula: "change_in_deposit_cost / change_in_fed_funds",
          businessLogic: 'Deposit cost sensitivity coefficient',
          dataType: 'DECIMAL',
          unit: 'beta',
          aggregation: 'CALCULATED',
          granularity: 'Quarterly',
          sourceTables: ['silver.deposit_beta_analysis', 'bronze.market_rates'],
          calculation: { sql: "REGR_SLOPE(deposit_cost_rate, fed_funds_rate)" },
          businessDefinition: 'Deposit pricing elasticity',
          benchmarks: { industryAverage: '0.55', topQuartile: '0.40', target: '0.48' },
        },
      ],
    },
  ],
};
