/**
 * LOANS-COMMERCIAL METRICS CATALOG
 * Commercial lending portfolio performance and risk metrics
 */

export const loansCommercialMetricsCatalog = {
  description: 'Commercial loan portfolio performance, origination, and risk metrics',
  totalMetrics: 68,
  
  categories: [
    {
      name: 'Portfolio Volume Metrics',
      description: 'Commercial loan portfolio size and composition',
      totalMetrics: 14,
      metrics: [
        {
          id: 'LCM-VOL-001',
          name: 'Total Commercial Loan Portfolio',
          description: 'Total outstanding commercial loan balances',
          category: 'Portfolio Volume',
          subcategory: 'Size',
          formula: "SUM(outstanding_balance)",
          businessLogic: 'Sum of all commercial loan balances',
          dataType: 'DECIMAL',
          unit: 'currency',
          aggregation: 'SUM',
          granularity: 'Daily',
          sourceTables: ['bronze.commercial_loans', 'gold.fact_loan_portfolio'],
          calculation: { numerator: "SUM(current_balance)" },
          businessDefinition: 'Total commercial lending exposure',
          benchmarks: { industryAverage: '$2.8B', topQuartile: '$5.5B', target: '$4.0B' },
        },
        {
          id: 'LCM-VOL-002',
          name: 'Average Loan Size',
          description: 'Mean commercial loan outstanding balance',
          category: 'Portfolio Volume',
          subcategory: 'Concentration',
          formula: "AVG(outstanding_balance)",
          businessLogic: 'Average loan balance',
          dataType: 'DECIMAL',
          unit: 'currency',
          aggregation: 'AVG',
          granularity: 'Monthly',
          sourceTables: ['gold.fact_loan_portfolio'],
          calculation: { numerator: "AVG(current_balance)" },
          businessDefinition: 'Average commercial loan size',
          benchmarks: { industryAverage: '$485K', topQuartile: '$720K', target: '$600K' },
        },
        {
          id: 'LCM-VOL-003',
          name: 'C&I Loan Volume',
          description: 'Commercial & Industrial loan outstanding balances',
          category: 'Portfolio Volume',
          subcategory: 'Product Type',
          formula: "SUM(balance WHERE loan_type = 'C&I')",
          businessLogic: 'Sum of C&I loan balances',
          dataType: 'DECIMAL',
          unit: 'currency',
          aggregation: 'SUM',
          granularity: 'Daily',
          sourceTables: ['bronze.commercial_loans'],
          calculation: { numerator: "SUM(current_balance)", filters: "loan_type = 'C&I'" },
          businessDefinition: 'Commercial & Industrial lending volume',
          benchmarks: { industryAverage: '$1.2B', topQuartile: '$2.4B', target: '$1.8B' },
        },
        {
          id: 'LCM-VOL-004',
          name: 'CRE Loan Volume',
          description: 'Commercial Real Estate loan outstanding balances',
          category: 'Portfolio Volume',
          subcategory: 'Product Type',
          formula: "SUM(balance WHERE loan_type = 'CRE')",
          businessLogic: 'Sum of CRE loan balances',
          dataType: 'DECIMAL',
          unit: 'currency',
          aggregation: 'SUM',
          granularity: 'Daily',
          sourceTables: ['bronze.commercial_loans'],
          calculation: { numerator: "SUM(current_balance)", filters: "loan_type = 'CRE'" },
          businessDefinition: 'Commercial real estate lending volume',
          benchmarks: { industryAverage: '$950M', topQuartile: '$1.9B', target: '$1.4B' },
        },
        {
          id: 'LCM-VOL-005',
          name: 'Term Loan Volume',
          description: 'Commercial term loan balances',
          category: 'Portfolio Volume',
          subcategory: 'Product Structure',
          formula: "SUM(balance WHERE product_type = 'term_loan')",
          businessLogic: 'Sum of term loan balances',
          dataType: 'DECIMAL',
          unit: 'currency',
          aggregation: 'SUM',
          granularity: 'Monthly',
          sourceTables: ['bronze.commercial_loans'],
          calculation: { numerator: "SUM(current_balance)", filters: "product_category = 'term'" },
          businessDefinition: 'Term loan portfolio volume',
          benchmarks: { industryAverage: '$1.4B', topQuartile: '$2.8B', target: '$2.1B' },
        },
        {
          id: 'LCM-VOL-006',
          name: 'Line of Credit Volume',
          description: 'Commercial line of credit outstanding balances',
          category: 'Portfolio Volume',
          subcategory: 'Product Structure',
          formula: "SUM(balance WHERE product_type = 'LOC')",
          businessLogic: 'Sum of LOC balances',
          dataType: 'DECIMAL',
          unit: 'currency',
          aggregation: 'SUM',
          granularity: 'Daily',
          sourceTables: ['bronze.commercial_loans'],
          calculation: { numerator: "SUM(current_balance)", filters: "product_category = 'LOC'" },
          businessDefinition: 'Line of credit portfolio volume',
          benchmarks: { industryAverage: '$850M', topQuartile: '$1.6B', target: '$1.2B' },
        },
        {
          id: 'LCM-VOL-007',
          name: 'LOC Utilization Rate',
          description: 'Average line of credit utilization percentage',
          category: 'Portfolio Volume',
          subcategory: 'Utilization',
          formula: "(SUM(outstanding) / SUM(commitment)) * 100",
          businessLogic: 'Outstanding / commitment',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Monthly',
          sourceTables: ['bronze.commercial_loans'],
          calculation: { numerator: "SUM(current_balance)", denominator: "SUM(commitment_amount)", multiplier: 100, filters: "product_category = 'LOC'" },
          businessDefinition: 'Line of credit draw rate',
          benchmarks: { industryAverage: '52%', topQuartile: '48%', target: '50%' },
        },
        {
          id: 'LCM-VOL-008',
          name: 'Equipment Finance Volume',
          description: 'Equipment financing loan balances',
          category: 'Portfolio Volume',
          subcategory: 'Product Type',
          formula: "SUM(balance WHERE loan_purpose = 'equipment')",
          businessLogic: 'Sum of equipment loan balances',
          dataType: 'DECIMAL',
          unit: 'currency',
          aggregation: 'SUM',
          granularity: 'Monthly',
          sourceTables: ['bronze.commercial_loans'],
          calculation: { numerator: "SUM(current_balance)", filters: "loan_purpose = 'equipment'" },
          businessDefinition: 'Equipment financing volume',
          benchmarks: { industryAverage: '$385M', topQuartile: '$720M', target: '$550M' },
        },
        {
          id: 'LCM-VOL-009',
          name: 'SBA Loan Volume',
          description: 'SBA-guaranteed loan balances',
          category: 'Portfolio Volume',
          subcategory: 'Government Programs',
          formula: "SUM(balance WHERE has_sba_guarantee = true)",
          businessLogic: 'Sum of SBA loan balances',
          dataType: 'DECIMAL',
          unit: 'currency',
          aggregation: 'SUM',
          granularity: 'Monthly',
          sourceTables: ['bronze.commercial_loans'],
          calculation: { numerator: "SUM(current_balance)", filters: "sba_guaranteed = true" },
          businessDefinition: 'SBA lending program volume',
          benchmarks: { industryAverage: '$125M', topQuartile: '$280M', target: '$195M' },
        },
        {
          id: 'LCM-VOL-010',
          name: 'Loan Count',
          description: 'Total number of commercial loan accounts',
          category: 'Portfolio Volume',
          subcategory: 'Count',
          formula: "COUNT(DISTINCT loan_id)",
          businessLogic: 'Count of active loans',
          dataType: 'INTEGER',
          unit: 'count',
          aggregation: 'COUNT_DISTINCT',
          granularity: 'Daily',
          sourceTables: ['bronze.commercial_loans'],
          calculation: { numerator: "COUNT(DISTINCT loan_id)", filters: "status = 'active'" },
          businessDefinition: 'Active commercial loan count',
          benchmarks: { industryAverage: '5,850', topQuartile: '10,200', target: '7,800' },
        },
        {
          id: 'LCM-VOL-011',
          name: 'Portfolio Growth Rate',
          description: 'Year-over-year loan portfolio growth',
          category: 'Portfolio Volume',
          subcategory: 'Growth',
          formula: "((current_balance - prior_year) / prior_year) * 100",
          businessLogic: 'YoY portfolio growth',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Annual',
          sourceTables: ['gold.fact_loan_portfolio'],
          calculation: { sql: "((SUM(current) - SUM(prior)) / SUM(prior)) * 100" },
          businessDefinition: 'Commercial loan portfolio expansion',
          benchmarks: { industryAverage: '8.5%', topQuartile: '14.2%', target: '11.0%' },
        },
        {
          id: 'LCM-VOL-012',
          name: 'Unfunded Commitments',
          description: 'Total unfunded loan commitments (primarily LOC)',
          category: 'Portfolio Volume',
          subcategory: 'Exposure',
          formula: "SUM(commitment_amount - outstanding_balance)",
          businessLogic: 'Total unfunded commitment exposure',
          dataType: 'DECIMAL',
          unit: 'currency',
          aggregation: 'CALCULATED',
          granularity: 'Daily',
          sourceTables: ['bronze.commercial_loans'],
          calculation: { sql: "SUM(commitment_amount - current_balance)" },
          businessDefinition: 'Potential funding obligation',
          benchmarks: { industryAverage: '$650M', topQuartile: '$420M', target: '$530M' },
        },
        {
          id: 'LCM-VOL-013',
          name: 'Concentration - Top 20 Borrowers',
          description: 'Top 20 borrowers as % of total portfolio',
          category: 'Portfolio Volume',
          subcategory: 'Concentration',
          formula: "(SUM(top_20_exposure) / SUM(total_portfolio)) * 100",
          businessLogic: 'Top 20 / total portfolio',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Quarterly',
          sourceTables: ['silver.commercial_loan_concentration'],
          calculation: { sql: "SUM(top_20_balances) / SUM(total_balances) * 100" },
          businessDefinition: 'Borrower concentration risk',
          benchmarks: { industryAverage: '32%', topQuartile: '24%', target: '28%' },
        },
        {
          id: 'LCM-VOL-014',
          name: 'Average Loan-to-Value',
          description: 'Mean LTV ratio across CRE portfolio',
          category: 'Portfolio Volume',
          subcategory: 'Risk Metrics',
          formula: "AVG(loan_amount / collateral_value)",
          businessLogic: 'Average LTV ratio',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'AVG',
          granularity: 'Quarterly',
          sourceTables: ['bronze.commercial_loans'],
          calculation: { numerator: "AVG((current_balance / collateral_appraised_value) * 100)", filters: "loan_type = 'CRE'" },
          businessDefinition: 'CRE portfolio LTV',
          benchmarks: { industryAverage: '68%', topQuartile: '62%', target: '65%' },
        },
      ],
    },
    {
      name: 'Origination Metrics',
      description: 'Commercial loan origination volume and efficiency',
      totalMetrics: 12,
      metrics: [
        {
          id: 'LCM-ORIG-001',
          name: 'New Loan Originations',
          description: 'Dollar volume of new commercial loans originated',
          category: 'Origination',
          subcategory: 'Volume',
          formula: "SUM(loan_amount WHERE origination_date IN PERIOD)",
          businessLogic: 'Sum of new loan amounts',
          dataType: 'DECIMAL',
          unit: 'currency',
          aggregation: 'SUM',
          granularity: 'Monthly',
          sourceTables: ['bronze.commercial_loans'],
          calculation: { numerator: "SUM(original_amount)", filters: "origination_date BETWEEN period_start AND period_end" },
          businessDefinition: 'Commercial lending production volume',
          benchmarks: { industryAverage: '$145M/month', topQuartile: '$320M/month', target: '$220M/month' },
        },
        {
          id: 'LCM-ORIG-002',
          name: 'Loan Origination Count',
          description: 'Number of new commercial loans originated',
          category: 'Origination',
          subcategory: 'Volume',
          formula: "COUNT(loan_id WHERE origination_date IN PERIOD)",
          businessLogic: 'Count of new loans',
          dataType: 'INTEGER',
          unit: 'count',
          aggregation: 'COUNT',
          granularity: 'Monthly',
          sourceTables: ['bronze.commercial_loans'],
          calculation: { numerator: "COUNT(loan_id)", filters: "origination_date BETWEEN period_start AND period_end" },
          businessDefinition: 'Loan production count',
          benchmarks: { industryAverage: '285/month', topQuartile: '520/month', target: '385/month' },
        },
        {
          id: 'LCM-ORIG-003',
          name: 'Average New Loan Size',
          description: 'Mean size of newly originated loans',
          category: 'Origination',
          subcategory: 'Deal Size',
          formula: "AVG(loan_amount WHERE origination_date IN PERIOD)",
          businessLogic: 'Average new loan amount',
          dataType: 'DECIMAL',
          unit: 'currency',
          aggregation: 'AVG',
          granularity: 'Monthly',
          sourceTables: ['bronze.commercial_loans'],
          calculation: { numerator: "AVG(original_amount)", filters: "origination_date BETWEEN period_start AND period_end" },
          businessDefinition: 'Average origination size',
          benchmarks: { industryAverage: '$510K', topQuartile: '$615K', target: '$570K' },
        },
        {
          id: 'LCM-ORIG-004',
          name: 'Pipeline Volume',
          description: 'Total dollar value of loans in pipeline',
          category: 'Origination',
          subcategory: 'Pipeline',
          formula: "SUM(loan_amount WHERE status = 'pipeline')",
          businessLogic: 'Sum of pipeline loan amounts',
          dataType: 'DECIMAL',
          unit: 'currency',
          aggregation: 'SUM',
          granularity: 'Weekly',
          sourceTables: ['bronze.commercial_loan_pipeline'],
          calculation: { numerator: "SUM(requested_amount)", filters: "pipeline_status IN ('submitted', 'in_review', 'approved')" },
          businessDefinition: 'Commercial loan pipeline',
          benchmarks: { industryAverage: '$285M', topQuartile: '$520M', target: '$385M' },
        },
        {
          id: 'LCM-ORIG-005',
          name: 'Pipeline Conversion Rate',
          description: 'Percentage of pipeline loans that close',
          category: 'Origination',
          subcategory: 'Conversion',
          formula: "(COUNT(funded) / COUNT(total_pipeline)) * 100",
          businessLogic: 'Funded / total pipeline',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Quarterly',
          sourceTables: ['bronze.commercial_loan_pipeline'],
          calculation: { numerator: "COUNT(WHERE status = 'funded')", denominator: "COUNT(loan_id)", multiplier: 100 },
          businessDefinition: 'Pipeline win rate',
          benchmarks: { industryAverage: '62%', topQuartile: '74%', target: '68%' },
        },
        {
          id: 'LCM-ORIG-006',
          name: 'Application to Funding Time',
          description: 'Average days from application to loan funding',
          category: 'Origination',
          subcategory: 'Efficiency',
          formula: "AVG(funding_date - application_date)",
          businessLogic: 'Average origination cycle time',
          dataType: 'INTEGER',
          unit: 'days',
          aggregation: 'AVG',
          granularity: 'Monthly',
          sourceTables: ['bronze.commercial_loans'],
          calculation: { sql: "AVG(EXTRACT(DAY FROM (funding_date - application_date)))" },
          businessDefinition: 'Loan origination speed',
          benchmarks: { industryAverage: '42 days', topQuartile: '28 days', target: '35 days' },
        },
        {
          id: 'LCM-ORIG-007',
          name: 'Credit Approval Rate',
          description: 'Percentage of applications approved',
          category: 'Origination',
          subcategory: 'Underwriting',
          formula: "(COUNT(approved) / COUNT(total_applications)) * 100",
          businessLogic: 'Approved / total applications',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Monthly',
          sourceTables: ['bronze.commercial_loan_pipeline'],
          calculation: { numerator: "COUNT(WHERE decision = 'approved')", denominator: "COUNT(application_id)", multiplier: 100 },
          businessDefinition: 'Credit approval rate',
          benchmarks: { industryAverage: '68%', topQuartile: '72%', target: '70%' },
        },
        {
          id: 'LCM-ORIG-008',
          name: 'Declined Application Rate',
          description: 'Percentage of applications declined',
          category: 'Origination',
          subcategory: 'Underwriting',
          formula: "(COUNT(declined) / COUNT(total_applications)) * 100",
          businessLogic: 'Declined / total applications',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Monthly',
          sourceTables: ['bronze.commercial_loan_pipeline'],
          calculation: { numerator: "COUNT(WHERE decision = 'declined')", denominator: "COUNT(application_id)", multiplier: 100 },
          businessDefinition: 'Credit decline rate',
          benchmarks: { industryAverage: '22%', topQuartile: '18%', target: '20%' },
        },
        {
          id: 'LCM-ORIG-009',
          name: 'Pull-Through Rate',
          description: 'Percentage of approved loans that fund',
          category: 'Origination',
          subcategory: 'Conversion',
          formula: "(COUNT(funded) / COUNT(approved)) * 100",
          businessLogic: 'Funded / approved',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Quarterly',
          sourceTables: ['bronze.commercial_loan_pipeline'],
          calculation: { numerator: "COUNT(WHERE status = 'funded')", denominator: "COUNT(WHERE decision = 'approved')", multiplier: 100 },
          businessDefinition: 'Approval to funding conversion',
          benchmarks: { industryAverage: '85%', topQuartile: '92%', target: '88%' },
        },
        {
          id: 'LCM-ORIG-010',
          name: 'Average Origination Yield',
          description: 'Weighted average interest rate on new loans',
          category: 'Origination',
          subcategory: 'Pricing',
          formula: "AVG(interest_rate WHERE origination_date IN PERIOD)",
          businessLogic: 'Average new loan rate',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'AVG',
          granularity: 'Monthly',
          sourceTables: ['bronze.commercial_loans'],
          calculation: { numerator: "AVG(interest_rate)", filters: "origination_date BETWEEN period_start AND period_end" },
          businessDefinition: 'New loan pricing',
          benchmarks: { industryAverage: '6.25%', topQuartile: '6.85%', target: '6.55%' },
        },
        {
          id: 'LCM-ORIG-011',
          name: 'Origination Fee Revenue',
          description: 'Total fee income from new loan originations',
          category: 'Origination',
          subcategory: 'Revenue',
          formula: "SUM(origination_fees)",
          businessLogic: 'Sum of origination fees',
          dataType: 'DECIMAL',
          unit: 'currency',
          aggregation: 'SUM',
          granularity: 'Monthly',
          sourceTables: ['bronze.commercial_loan_fees'],
          calculation: { numerator: "SUM(fee_amount)", filters: "fee_type = 'origination'" },
          businessDefinition: 'Loan origination fee income',
          benchmarks: { industryAverage: '$285K/month', topQuartile: '$520K/month', target: '$385K/month' },
        },
        {
          id: 'LCM-ORIG-012',
          name: 'Referral Source - RM Direct',
          description: 'Percentage of originations from direct RM sourcing',
          category: 'Origination',
          subcategory: 'Source',
          formula: "(COUNT(rm_direct) / COUNT(total_originations)) * 100",
          businessLogic: 'RM sourced / total originations',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Quarterly',
          sourceTables: ['bronze.commercial_loans'],
          calculation: { numerator: "COUNT(WHERE referral_source = 'RM_direct')", denominator: "COUNT(loan_id)", multiplier: 100, filters: "origination_date IN PERIOD" },
          businessDefinition: 'RM-sourced loan percentage',
          benchmarks: { industryAverage: '58%', topQuartile: '72%', target: '65%' },
        },
      ],
    },
    {
      name: 'Credit Quality Metrics',
      description: 'Commercial loan credit quality and delinquency tracking',
      totalMetrics: 14,
      metrics: [
        {
          id: 'LCM-QUAL-001',
          name: 'Commercial NPL Ratio',
          description: 'Non-performing loans as percentage of total portfolio',
          category: 'Credit Quality',
          subcategory: 'Delinquency',
          formula: "(SUM(npl_balance) / SUM(total_balance)) * 100",
          businessLogic: 'NPL balance / total balance',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Monthly',
          sourceTables: ['gold.fact_loan_portfolio'],
          calculation: { numerator: "SUM(WHERE days_past_due >= 90)", denominator: "SUM(outstanding_balance)", multiplier: 100 },
          businessDefinition: 'Commercial loan asset quality',
          benchmarks: { industryAverage: '1.8%', topQuartile: '0.9%', target: '1.3%' },
        },
        {
          id: 'LCM-QUAL-002',
          name: '30+ Days Past Due',
          description: 'Loans 30-89 days past due as % of portfolio',
          category: 'Credit Quality',
          subcategory: 'Early Delinquency',
          formula: "(SUM(30_89_dpd) / SUM(total_balance)) * 100",
          businessLogic: '30-89 DPD / total',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Monthly',
          sourceTables: ['gold.fact_loan_portfolio'],
          calculation: { numerator: "SUM(WHERE days_past_due BETWEEN 30 AND 89)", denominator: "SUM(outstanding_balance)", multiplier: 100 },
          businessDefinition: 'Early stage delinquency',
          benchmarks: { industryAverage: '0.85%', topQuartile: '0.45%', target: '0.65%' },
        },
        {
          id: 'LCM-QUAL-003',
          name: 'Charge-Off Rate',
          description: 'Net charge-offs as % of average loans (annualized)',
          category: 'Credit Quality',
          subcategory: 'Losses',
          formula: "(SUM(charge_offs - recoveries) / AVG(loans)) * 100",
          businessLogic: 'Net charge-offs / average portfolio',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Quarterly',
          sourceTables: ['bronze.commercial_loan_charge_offs'],
          calculation: { sql: "((SUM(charge_off_amount) - SUM(recovery_amount)) / AVG(portfolio_balance)) * 100 * 4" },
          businessDefinition: 'Annualized net charge-off rate',
          benchmarks: { industryAverage: '0.65%', topQuartile: '0.35%', target: '0.50%' },
        },
        {
          id: 'LCM-QUAL-004',
          name: 'Criticized Loans',
          description: 'Special Mention + Substandard + Doubtful + Loss as % of portfolio',
          category: 'Credit Quality',
          subcategory: 'Risk Rating',
          formula: "(SUM(criticized) / SUM(total)) * 100",
          businessLogic: 'Criticized / total portfolio',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Quarterly',
          sourceTables: ['silver.commercial_loan_risk_ratings'],
          calculation: { numerator: "SUM(WHERE risk_rating IN ('special_mention', 'substandard', 'doubtful', 'loss'))", denominator: "SUM(outstanding_balance)", multiplier: 100 },
          businessDefinition: 'Criticized asset ratio',
          benchmarks: { industryAverage: '8.5%', topQuartile: '5.2%', target: '6.5%' },
        },
        {
          id: 'LCM-QUAL-005',
          name: 'Classified Loans',
          description: 'Substandard + Doubtful + Loss as % of portfolio',
          category: 'Credit Quality',
          subcategory: 'Risk Rating',
          formula: "(SUM(classified) / SUM(total)) * 100",
          businessLogic: 'Classified / total portfolio',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Quarterly',
          sourceTables: ['silver.commercial_loan_risk_ratings'],
          calculation: { numerator: "SUM(WHERE risk_rating IN ('substandard', 'doubtful', 'loss'))", denominator: "SUM(outstanding_balance)", multiplier: 100 },
          businessDefinition: 'Classified asset ratio',
          benchmarks: { industryAverage: '4.2%', topQuartile: '2.5%', target: '3.2%' },
        },
        {
          id: 'LCM-QUAL-006',
          name: 'Watch List Loans',
          description: 'Loans on watch list as % of portfolio',
          category: 'Credit Quality',
          subcategory: 'Monitoring',
          formula: "(SUM(watch_list) / SUM(total)) * 100",
          businessLogic: 'Watch list / total',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Monthly',
          sourceTables: ['silver.commercial_loan_watch_list'],
          calculation: { numerator: "SUM(WHERE on_watch_list = true)", denominator: "SUM(outstanding_balance)", multiplier: 100 },
          businessDefinition: 'Watch list concentration',
          benchmarks: { industryAverage: '12.5%', topQuartile: '8.2%', target: '10.0%' },
        },
        {
          id: 'LCM-QUAL-007',
          name: 'TDR Volume',
          description: 'Troubled Debt Restructurings as % of portfolio',
          category: 'Credit Quality',
          subcategory: 'Modifications',
          formula: "(SUM(tdr_balance) / SUM(total)) * 100",
          businessLogic: 'TDR / total portfolio',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Quarterly',
          sourceTables: ['bronze.commercial_loans'],
          calculation: { numerator: "SUM(WHERE is_tdr = true)", denominator: "SUM(outstanding_balance)", multiplier: 100 },
          businessDefinition: 'Restructured loan ratio',
          benchmarks: { industryAverage: '2.8%', topQuartile: '1.5%', target: '2.0%' },
        },
        {
          id: 'LCM-QUAL-008',
          name: 'Forbearance Volume',
          description: 'Loans in forbearance as % of portfolio',
          category: 'Credit Quality',
          subcategory: 'Modifications',
          formula: "(SUM(forbearance) / SUM(total)) * 100",
          businessLogic: 'Forbearance / total',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Monthly',
          sourceTables: ['bronze.commercial_loans'],
          calculation: { numerator: "SUM(WHERE in_forbearance = true)", denominator: "SUM(outstanding_balance)", multiplier: 100 },
          businessDefinition: 'Payment relief percentage',
          benchmarks: { industryAverage: '1.2%', topQuartile: '0.6%', target: '0.9%' },
        },
        {
          id: 'LCM-QUAL-009',
          name: 'Average FICO Score',
          description: 'Mean FICO score for commercial borrowers',
          category: 'Credit Quality',
          subcategory: 'Credit Strength',
          formula: "AVG(fico_score)",
          businessLogic: 'Average borrower FICO',
          dataType: 'INTEGER',
          unit: 'score',
          aggregation: 'AVG',
          granularity: 'Quarterly',
          sourceTables: ['bronze.commercial_borrower_credit'],
          calculation: { numerator: "AVG(fico_score)" },
          businessDefinition: 'Portfolio credit quality',
          benchmarks: { industryAverage: '715', topQuartile: '745', target: '730' },
        },
        {
          id: 'LCM-QUAL-010',
          name: 'Migration to NPL',
          description: 'Loans migrating to NPL status quarterly',
          category: 'Credit Quality',
          subcategory: 'Migration',
          formula: "SUM(new_npls) / SUM(performing_portfolio_start)",
          businessLogic: 'New NPLs / beginning performing loans',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Quarterly',
          sourceTables: ['silver.commercial_loan_migrations'],
          calculation: { numerator: "SUM(WHERE became_npl_this_quarter = true)", denominator: "SUM(performing_balance_start_of_quarter)", multiplier: 100 },
          businessDefinition: 'NPL migration rate',
          benchmarks: { industryAverage: '0.45%', topQuartile: '0.25%', target: '0.35%' },
        },
        {
          id: 'LCM-QUAL-011',
          name: 'NPL Resolution Rate',
          description: 'Percentage of NPLs resolved (cured or charged off) quarterly',
          category: 'Credit Quality',
          subcategory: 'Resolution',
          formula: "(COUNT(resolved_npls) / COUNT(beginning_npls)) * 100",
          businessLogic: 'Resolved NPLs / beginning NPLs',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Quarterly',
          sourceTables: ['silver.commercial_loan_migrations'],
          calculation: { numerator: "COUNT(WHERE npl_resolved = true)", denominator: "COUNT(WHERE was_npl_start_of_quarter = true)", multiplier: 100 },
          businessDefinition: 'NPL workout effectiveness',
          benchmarks: { industryAverage: '28%', topQuartile: '38%', target: '33%' },
        },
        {
          id: 'LCM-QUAL-012',
          name: 'Recovery Rate on Charge-Offs',
          description: 'Recoveries as % of prior period charge-offs',
          category: 'Credit Quality',
          subcategory: 'Recoveries',
          formula: "(SUM(recoveries) / SUM(prior_charge_offs)) * 100",
          businessLogic: 'Recoveries / charge-offs',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Annual',
          sourceTables: ['bronze.commercial_loan_charge_offs'],
          calculation: { numerator: "SUM(recovery_amount)", denominator: "SUM(charge_off_amount)", multiplier: 100 },
          businessDefinition: 'Charge-off recovery rate',
          benchmarks: { industryAverage: '32%', topQuartile: '45%', target: '38%' },
        },
        {
          id: 'LCM-QUAL-013',
          name: 'Collateral Coverage Ratio',
          description: 'Collateral value as % of outstanding loan balance',
          category: 'Credit Quality',
          subcategory: 'Security',
          formula: "(SUM(collateral_value) / SUM(outstanding_balance)) * 100",
          businessLogic: 'Collateral / loan balance',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Quarterly',
          sourceTables: ['bronze.commercial_loan_collateral'],
          calculation: { numerator: "SUM(current_appraised_value)", denominator: "SUM(outstanding_balance)", multiplier: 100 },
          businessDefinition: 'Secured loan coverage',
          benchmarks: { industryAverage: '145%', topQuartile: '165%', target: '155%' },
        },
        {
          id: 'LCM-QUAL-014',
          name: 'Environmental Risk Exposure',
          description: 'Loans with environmental liability risk as % of portfolio',
          category: 'Credit Quality',
          subcategory: 'Environmental Risk',
          formula: "(SUM(env_risk_loans) / SUM(total)) * 100",
          businessLogic: 'Environmental risk / total',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Annual',
          sourceTables: ['bronze.commercial_environmental_assessments'],
          calculation: { numerator: "SUM(WHERE has_environmental_risk = true)", denominator: "SUM(outstanding_balance)", multiplier: 100 },
          businessDefinition: 'Environmental liability exposure',
          benchmarks: { industryAverage: '8.5%', topQuartile: '5.2%', target: '6.8%' },
        },
      ],
    },
    {
      name: 'Profitability Metrics',
      description: 'Commercial loan profitability and yield',
      totalMetrics: 14,
      metrics: [
        {
          id: 'LCM-PROF-001',
          name: 'Commercial Loan Yield',
          description: 'Weighted average interest rate on commercial loans',
          category: 'Profitability',
          subcategory: 'Yield',
          formula: "SUM(interest_income) / AVG(outstanding_balance)",
          businessLogic: 'Annualized yield on portfolio',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Quarterly',
          sourceTables: ['gold.fact_loan_portfolio'],
          calculation: { numerator: "SUM(interest_income)", denominator: "AVG(outstanding_balance)", multiplier: 100 },
          businessDefinition: 'Commercial loan pricing realization',
          benchmarks: { industryAverage: '5.85%', topQuartile: '6.45%', target: '6.15%' },
        },
        {
          id: 'LCM-PROF-002',
          name: 'Net Interest Margin',
          description: 'Net interest income as % of average loans',
          category: 'Profitability',
          subcategory: 'Margin',
          formula: "((interest_income - funding_cost) / AVG(loans)) * 100",
          businessLogic: 'NIM on commercial loans',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Quarterly',
          sourceTables: ['gold.fact_loan_portfolio'],
          calculation: { sql: "((SUM(interest_income) - SUM(funding_cost)) / AVG(balance)) * 100" },
          businessDefinition: 'Commercial lending net margin',
          benchmarks: { industryAverage: '3.85%', topQuartile: '4.45%', target: '4.15%' },
        },
        {
          id: 'LCM-PROF-003',
          name: 'Total Interest Income',
          description: 'Total interest earned on commercial loans',
          category: 'Profitability',
          subcategory: 'Revenue',
          formula: "SUM(interest_income)",
          businessLogic: 'Total interest revenue',
          dataType: 'DECIMAL',
          unit: 'currency',
          aggregation: 'SUM',
          granularity: 'Monthly',
          sourceTables: ['gold.fact_loan_portfolio'],
          calculation: { numerator: "SUM(interest_income)" },
          businessDefinition: 'Commercial loan interest revenue',
          benchmarks: { industryAverage: '$13.5M/month', topQuartile: '$29.5M/month', target: '$20.5M/month' },
        },
        {
          id: 'LCM-PROF-004',
          name: 'Fee Income',
          description: 'Non-interest fee income from commercial loans',
          category: 'Profitability',
          subcategory: 'Fee Revenue',
          formula: "SUM(fees)",
          businessLogic: 'Total fee income',
          dataType: 'DECIMAL',
          unit: 'currency',
          aggregation: 'SUM',
          granularity: 'Monthly',
          sourceTables: ['bronze.commercial_loan_fees'],
          calculation: { numerator: "SUM(fee_amount)" },
          businessDefinition: 'Commercial loan fee revenue',
          benchmarks: { industryAverage: '$485K/month', topQuartile: '$920K/month', target: '$685K/month' },
        },
        {
          id: 'LCM-PROF-005',
          name: 'Unused Line Fee Revenue',
          description: 'Fee income from unused commitment fees',
          category: 'Profitability',
          subcategory: 'Fee Revenue',
          formula: "SUM(unused_commitment_fees)",
          businessLogic: 'Unused line fee income',
          dataType: 'DECIMAL',
          unit: 'currency',
          aggregation: 'SUM',
          granularity: 'Quarterly',
          sourceTables: ['bronze.commercial_loan_fees'],
          calculation: { numerator: "SUM(fee_amount)", filters: "fee_type = 'unused_commitment'" },
          businessDefinition: 'Commitment fee revenue',
          benchmarks: { industryAverage: '$185K/qtr', topQuartile: '$350K/qtr', target: '$260K/qtr' },
        },
        {
          id: 'LCM-PROF-006',
          name: 'Loan Servicing Fee Revenue',
          description: 'Fee income from servicing sold loans',
          category: 'Profitability',
          subcategory: 'Fee Revenue',
          formula: "SUM(servicing_fees)",
          businessLogic: 'Loan servicing income',
          dataType: 'DECIMAL',
          unit: 'currency',
          aggregation: 'SUM',
          granularity: 'Quarterly',
          sourceTables: ['bronze.commercial_loan_fees'],
          calculation: { numerator: "SUM(fee_amount)", filters: "fee_type = 'servicing'" },
          businessDefinition: 'Servicing rights revenue',
          benchmarks: { industryAverage: '$95K/qtr', topQuartile: '$185K/qtr', target: '$135K/qtr' },
        },
        {
          id: 'LCM-PROF-007',
          name: 'Return on Assets (ROA)',
          description: 'Net income as % of average commercial loan assets',
          category: 'Profitability',
          subcategory: 'Returns',
          formula: "(net_income / AVG(loan_assets)) * 100",
          businessLogic: 'Annualized ROA',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Quarterly',
          sourceTables: ['gold.fact_loan_portfolio'],
          calculation: { sql: "((SUM(net_income) * 4) / AVG(outstanding_balance)) * 100" },
          businessDefinition: 'Commercial lending ROA',
          benchmarks: { industryAverage: '1.85%', topQuartile: '2.45%', target: '2.15%' },
        },
        {
          id: 'LCM-PROF-008',
          name: 'Return on Equity (ROE)',
          description: 'Net income as % of allocated equity',
          category: 'Profitability',
          subcategory: 'Returns',
          formula: "(net_income / allocated_equity) * 100",
          businessLogic: 'Annualized ROE',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Quarterly',
          sourceTables: ['silver.commercial_loan_profitability'],
          calculation: { sql: "((SUM(net_income) * 4) / AVG(allocated_equity)) * 100" },
          businessDefinition: 'Commercial lending ROE',
          benchmarks: { industryAverage: '14.5%', topQuartile: '19.2%', target: '16.8%' },
        },
        {
          id: 'LCM-PROF-009',
          name: 'Provision Expense',
          description: 'Loan loss provision expense',
          category: 'Profitability',
          subcategory: 'Credit Costs',
          formula: "SUM(provision_expense)",
          businessLogic: 'Total provision for loan losses',
          dataType: 'DECIMAL',
          unit: 'currency',
          aggregation: 'SUM',
          granularity: 'Quarterly',
          sourceTables: ['silver.commercial_loan_profitability'],
          calculation: { numerator: "SUM(provision_amount)" },
          businessDefinition: 'Loan loss provisioning',
          benchmarks: { industryAverage: '$2.1M/qtr', topQuartile: '$1.4M/qtr', target: '$1.7M/qtr' },
        },
        {
          id: 'LCM-PROF-010',
          name: 'Efficiency Ratio',
          description: 'Operating expenses as % of net revenue',
          category: 'Profitability',
          subcategory: 'Efficiency',
          formula: "(operating_expenses / net_revenue) * 100",
          businessLogic: 'Expenses / revenue',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Quarterly',
          sourceTables: ['silver.commercial_loan_profitability'],
          calculation: { numerator: "SUM(operating_expenses)", denominator: "SUM(total_revenue)", multiplier: 100 },
          businessDefinition: 'Commercial lending efficiency',
          benchmarks: { industryAverage: '52%', topQuartile: '42%', target: '47%' },
        },
        {
          id: 'LCM-PROF-011',
          name: 'Cost per Loan',
          description: 'Average operating cost per commercial loan',
          category: 'Profitability',
          subcategory: 'Unit Economics',
          formula: "SUM(operating_expenses) / COUNT(loans)",
          businessLogic: 'Total costs / loan count',
          dataType: 'DECIMAL',
          unit: 'currency',
          aggregation: 'CALCULATED',
          granularity: 'Annual',
          sourceTables: ['silver.commercial_loan_profitability'],
          calculation: { numerator: "SUM(operating_expenses)", denominator: "COUNT(DISTINCT loan_id)" },
          businessDefinition: 'Per-loan operating cost',
          benchmarks: { industryAverage: '$1,850', topQuartile: '$1,420', target: '$1,620' },
        },
        {
          id: 'LCM-PROF-012',
          name: 'Spread Over Cost of Funds',
          description: 'Loan yield minus deposit cost rate',
          category: 'Profitability',
          subcategory: 'Spread',
          formula: "loan_yield - deposit_cost",
          businessLogic: 'Yield spread over funding cost',
          dataType: 'DECIMAL',
          unit: 'basis_points',
          aggregation: 'CALCULATED',
          granularity: 'Monthly',
          sourceTables: ['gold.fact_loan_portfolio', 'gold.fact_deposit_balances'],
          calculation: { sql: "AVG(loan_interest_rate) - AVG(deposit_cost_rate)" },
          businessDefinition: 'Lending spread',
          benchmarks: { industryAverage: '385 bps', topQuartile: '465 bps', target: '425 bps' },
        },
        {
          id: 'LCM-PROF-013',
          name: 'Risk-Adjusted Return',
          description: 'Return on assets adjusted for credit losses',
          category: 'Profitability',
          subcategory: 'Risk-Adjusted',
          formula: "(net_income - credit_losses) / AVG(assets)",
          businessLogic: 'RAROC calculation',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Annual',
          sourceTables: ['silver.commercial_loan_profitability'],
          calculation: { sql: "((SUM(net_income) - SUM(credit_losses)) / AVG(outstanding_balance)) * 100" },
          businessDefinition: 'Risk-adjusted return on capital',
          benchmarks: { industryAverage: '1.45%', topQuartile: '2.05%', target: '1.75%' },
        },
        {
          id: 'LCM-PROF-014',
          name: 'Customer Lifetime Value',
          description: 'Estimated lifetime profitability per commercial customer',
          category: 'Profitability',
          subcategory: 'Customer Value',
          formula: "AVG(cumulative_revenue - cumulative_costs)",
          businessLogic: 'LTV calculation',
          dataType: 'DECIMAL',
          unit: 'currency',
          aggregation: 'AVG',
          granularity: 'Annual',
          sourceTables: ['silver.commercial_customer_profitability'],
          calculation: { sql: "AVG(lifetime_revenue - lifetime_costs)" },
          businessDefinition: 'Commercial customer LTV',
          benchmarks: { industryAverage: '$125K', topQuartile: '$215K', target: '$170K' },
        },
      ],
    },
    {
      name: 'Risk Management Metrics',
      description: 'Commercial loan risk assessment and monitoring',
      totalMetrics: 14,
      metrics: [
        {
          id: 'LCM-RISK-001',
          name: 'Loan Loss Reserve Coverage',
          description: 'Allowance for loan losses as percentage of NPLs',
          category: 'Risk Management',
          subcategory: 'Provisions',
          formula: "(loan_loss_reserve / npl_balance) * 100",
          businessLogic: 'ALLL / NPL balance',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Quarterly',
          sourceTables: ['gold.fact_loan_portfolio'],
          calculation: { numerator: "SUM(allowance_for_loan_losses)", denominator: "SUM(npl_balance)", multiplier: 100 },
          businessDefinition: 'Loan loss reserve adequacy',
          benchmarks: { industryAverage: '145%', topQuartile: '185%', target: '165%' },
        },
        {
          id: 'LCM-RISK-002',
          name: 'Reserve as % of Portfolio',
          description: 'ALLL as percentage of total commercial loans',
          category: 'Risk Management',
          subcategory: 'Provisions',
          formula: "(ALLL / total_loans) * 100",
          businessLogic: 'Reserve / total portfolio',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Quarterly',
          sourceTables: ['gold.fact_loan_portfolio'],
          calculation: { numerator: "SUM(allowance_for_loan_losses)", denominator: "SUM(outstanding_balance)", multiplier: 100 },
          businessDefinition: 'Reserve ratio',
          benchmarks: { industryAverage: '1.85%', topQuartile: '2.15%', target: '2.00%' },
        },
        {
          id: 'LCM-RISK-003',
          name: 'CECL Reserve Coverage',
          description: 'CECL allowance as % of total loans',
          category: 'Risk Management',
          subcategory: 'CECL',
          formula: "(cecl_allowance / total_loans) * 100",
          businessLogic: 'CECL reserve / total portfolio',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Quarterly',
          sourceTables: ['silver.commercial_cecl_reserves'],
          calculation: { numerator: "SUM(cecl_allowance)", denominator: "SUM(outstanding_balance)", multiplier: 100 },
          businessDefinition: 'CECL lifetime loss coverage',
          benchmarks: { industryAverage: '2.15%', topQuartile: '2.45%', target: '2.30%' },
        },
        {
          id: 'LCM-RISK-004',
          name: 'Texas Ratio',
          description: '(NPLs + ORE) / (Tangible Equity + Loan Loss Reserves)',
          category: 'Risk Management',
          subcategory: 'Solvency',
          formula: "((NPLs + ORE) / (equity + reserves)) * 100",
          businessLogic: 'Texas ratio calculation',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Quarterly',
          sourceTables: ['gold.fact_loan_portfolio', 'silver.capital_metrics'],
          calculation: { sql: "((SUM(npl_balance) + SUM(oreo_balance)) / (bank_equity + SUM(loan_loss_reserve))) * 100" },
          businessDefinition: 'Asset quality vs capital strength',
          benchmarks: { industryAverage: '18%', topQuartile: '10%', target: '14%', warning_threshold: '50%' },
        },
        {
          id: 'LCM-RISK-005',
          name: 'Economic Capital Allocation',
          description: 'Risk-based capital allocated to commercial lending',
          category: 'Risk Management',
          subcategory: 'Capital',
          formula: "SUM(risk_weighted_assets * capital_factor)",
          businessLogic: 'RWA-based capital allocation',
          dataType: 'DECIMAL',
          unit: 'currency',
          aggregation: 'CALCULATED',
          granularity: 'Quarterly',
          sourceTables: ['silver.commercial_loan_capital'],
          calculation: { sql: "SUM(risk_weighted_balance * 0.08)" },
          businessDefinition: 'Economic capital requirement',
          benchmarks: { industryAverage: '$320M', topQuartile: '$280M', target: '$300M' },
        },
        {
          id: 'LCM-RISK-006',
          name: 'Risk-Weighted Assets',
          description: 'Total risk-weighted commercial loan assets',
          category: 'Risk Management',
          subcategory: 'Capital',
          formula: "SUM(loan_balance * risk_weight)",
          businessLogic: 'Basel III RWA calculation',
          dataType: 'DECIMAL',
          unit: 'currency',
          aggregation: 'CALCULATED',
          granularity: 'Quarterly',
          sourceTables: ['silver.commercial_loan_capital'],
          calculation: { sql: "SUM(outstanding_balance * risk_weight_pct / 100)" },
          businessDefinition: 'Risk-weighted lending exposure',
          benchmarks: { industryAverage: '$3.2B', topQuartile: '$4.8B', target: '$4.0B' },
        },
        {
          id: 'LCM-RISK-007',
          name: 'Average Probability of Default',
          description: 'Weighted average PD across commercial portfolio',
          category: 'Risk Management',
          subcategory: 'Credit Modeling',
          formula: "AVG(probability_of_default)",
          businessLogic: 'Average PD by balance',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'AVG',
          granularity: 'Quarterly',
          sourceTables: ['silver.commercial_loan_pd_lgd'],
          calculation: { sql: "SUM(pd * balance) / SUM(balance)" },
          businessDefinition: 'Portfolio default probability',
          benchmarks: { industryAverage: '2.85%', topQuartile: '2.15%', target: '2.50%' },
        },
        {
          id: 'LCM-RISK-008',
          name: 'Average Loss Given Default',
          description: 'Weighted average LGD across commercial portfolio',
          category: 'Risk Management',
          subcategory: 'Credit Modeling',
          formula: "AVG(loss_given_default)",
          businessLogic: 'Average LGD by balance',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'AVG',
          granularity: 'Quarterly',
          sourceTables: ['silver.commercial_loan_pd_lgd'],
          calculation: { sql: "SUM(lgd * balance) / SUM(balance)" },
          businessDefinition: 'Expected loss severity',
          benchmarks: { industryAverage: '42%', topQuartile: '35%', target: '38%' },
        },
        {
          id: 'LCM-RISK-009',
          name: 'Expected Credit Loss',
          description: 'Expected loss (PD * LGD * EAD)',
          category: 'Risk Management',
          subcategory: 'Credit Modeling',
          formula: "SUM(PD * LGD * EAD)",
          businessLogic: 'Total expected credit loss',
          dataType: 'DECIMAL',
          unit: 'currency',
          aggregation: 'CALCULATED',
          granularity: 'Quarterly',
          sourceTables: ['silver.commercial_loan_pd_lgd'],
          calculation: { sql: "SUM(probability_of_default * loss_given_default * exposure_at_default / 10000)" },
          businessDefinition: 'Modeled expected losses',
          benchmarks: { industryAverage: '$48M', topQuartile: '$35M', target: '$41M' },
        },
        {
          id: 'LCM-RISK-010',
          name: 'Stress Test Loss Rate',
          description: 'Projected loss rate under adverse scenario',
          category: 'Risk Management',
          subcategory: 'Stress Testing',
          formula: "modeled_losses_adverse / total_portfolio",
          businessLogic: 'Stress scenario loss projection',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Annual',
          sourceTables: ['silver.commercial_loan_stress_tests'],
          calculation: { numerator: "SUM(adverse_scenario_losses)", denominator: "SUM(outstanding_balance)", multiplier: 100 },
          businessDefinition: 'Stress test loss estimate',
          benchmarks: { industryAverage: '5.8%', topQuartile: '4.2%', target: '5.0%' },
        },
        {
          id: 'LCM-RISK-011',
          name: 'Industry Concentration - Real Estate',
          description: 'CRE exposure as % of total capital',
          category: 'Risk Management',
          subcategory: 'Concentration',
          formula: "(SUM(cre_balance) / total_capital) * 100",
          businessLogic: 'CRE / total capital',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Quarterly',
          sourceTables: ['bronze.commercial_loans', 'silver.capital_metrics'],
          calculation: { numerator: "SUM(WHERE loan_type = 'CRE')", denominator: "bank_total_capital", multiplier: 100 },
          businessDefinition: 'CRE concentration vs capital',
          benchmarks: { industryAverage: '285%', topQuartile: '225%', target: '255%', regulatory_guideline: '300%' },
        },
        {
          id: 'LCM-RISK-012',
          name: 'Single Borrower Limit Utilization',
          description: 'Largest borrower exposure as % of legal lending limit',
          category: 'Risk Management',
          subcategory: 'Concentration',
          formula: "(largest_exposure / lending_limit) * 100",
          businessLogic: 'Max exposure / legal limit',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Monthly',
          sourceTables: ['silver.commercial_loan_concentration'],
          calculation: { sql: "MAX(borrower_total_exposure) / (bank_capital * 0.15) * 100" },
          businessDefinition: 'Legal lending limit utilization',
          benchmarks: { industryAverage: '65%', topQuartile: '55%', target: '60%', regulatory_limit: '100%' },
        },
        {
          id: 'LCM-RISK-013',
          name: 'Interest Rate Risk - Duration',
          description: 'Duration of commercial loan portfolio',
          category: 'Risk Management',
          subcategory: 'Interest Rate Risk',
          formula: "SUM(modified_duration * balance) / SUM(balance)",
          businessLogic: 'Weighted average duration',
          dataType: 'DECIMAL',
          unit: 'years',
          aggregation: 'CALCULATED',
          granularity: 'Monthly',
          sourceTables: ['silver.commercial_loan_interest_rate_risk'],
          calculation: { sql: "SUM(duration * outstanding_balance) / SUM(outstanding_balance)" },
          businessDefinition: 'Portfolio interest rate sensitivity',
          benchmarks: { industryAverage: '3.2 years', topQuartile: '2.8 years', target: '3.0 years' },
        },
        {
          id: 'LCM-RISK-014',
          name: 'Variable Rate Loan Percentage',
          description: 'Variable/floating rate loans as % of portfolio',
          category: 'Risk Management',
          subcategory: 'Interest Rate Risk',
          formula: "(SUM(variable_rate_loans) / SUM(total_portfolio)) * 100",
          businessLogic: 'Variable rate / total',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Monthly',
          sourceTables: ['bronze.commercial_loans'],
          calculation: { numerator: "SUM(WHERE rate_type = 'variable')", denominator: "SUM(outstanding_balance)", multiplier: 100 },
          businessDefinition: 'Floating rate concentration',
          benchmarks: { industryAverage: '58%', topQuartile: '68%', target: '63%' },
        },
      ],
    },
  ],
};
