/**
 * PAYMENTS-COMMERCIAL METRICS CATALOG
 * Commercial payment processing volume, revenue, and operational metrics
 */

export const paymentsCommercialMetricsCatalog = {
  description: 'Commercial payment processing volume, fee revenue, and service quality metrics',
  totalMetrics: 75,
  
  categories: [
    {
      name: 'Payment Volume Metrics',
      description: 'Commercial payment transaction volume and value',
      totalMetrics: 18,
      metrics: [
        {
          id: 'PCM-VOL-001',
          name: 'Total Commercial Payment Volume',
          description: 'Total dollar value of commercial payments processed',
          category: 'Payment Volume',
          subcategory: 'Value',
          formula: "SUM(payment_amount)",
          businessLogic: 'Sum of all commercial payment amounts',
          dataType: 'DECIMAL',
          unit: 'currency',
          aggregation: 'SUM',
          granularity: 'Daily',
          sourceTables: ['bronze.commercial_payments', 'gold.fact_payment_transactions'],
          calculation: { numerator: "SUM(transaction_amount)" },
          businessDefinition: 'Total commercial payment processing volume',
          benchmarks: { industryAverage: '$850M/day', topQuartile: '$1.8B/day', target: '$1.2B/day' },
        },
        {
          id: 'PCM-VOL-002',
          name: 'Total Payment Transaction Count',
          description: 'Number of commercial payment transactions processed',
          category: 'Payment Volume',
          subcategory: 'Count',
          formula: "COUNT(transaction_id)",
          businessLogic: 'Count of all payment transactions',
          dataType: 'INTEGER',
          unit: 'count',
          aggregation: 'COUNT',
          granularity: 'Daily',
          sourceTables: ['bronze.commercial_payments', 'gold.fact_payment_transactions'],
          calculation: { numerator: "COUNT(transaction_id)" },
          businessDefinition: 'Total number of commercial payment transactions',
          benchmarks: { industryAverage: '185K/day', topQuartile: '420K/day', target: '290K/day' },
        },
        {
          id: 'PCM-VOL-003',
          name: 'Average Payment Amount',
          description: 'Average dollar value per commercial payment transaction',
          category: 'Payment Volume',
          subcategory: 'Average',
          formula: "AVG(payment_amount)",
          businessLogic: 'Average payment transaction amount',
          dataType: 'DECIMAL',
          unit: 'currency',
          aggregation: 'AVG',
          granularity: 'Daily',
          sourceTables: ['bronze.commercial_payments'],
          calculation: { numerator: "SUM(transaction_amount)", denominator: "COUNT(transaction_id)" },
          businessDefinition: 'Average size of commercial payment transactions',
          benchmarks: { industryAverage: '$4,590', topQuartile: '$4,280', target: '$4,140' },
        },
        {
          id: 'PCM-VOL-004',
          name: 'Payment Volume Growth Rate',
          description: 'Month-over-month growth in payment volume',
          category: 'Payment Volume',
          subcategory: 'Growth',
          formula: "((CURRENT_MONTH - PRIOR_MONTH) / PRIOR_MONTH) * 100",
          businessLogic: 'MoM volume growth percentage',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Monthly',
          sourceTables: ['gold.fact_payment_transactions'],
          calculation: { sql: "((SUM(current.amount) - SUM(prior.amount)) / SUM(prior.amount)) * 100" },
          businessDefinition: 'Month-over-month payment volume growth rate',
          benchmarks: { industryAverage: '3.2%', topQuartile: '5.8%', target: '4.5%' },
        },
        {
          id: 'PCM-VOL-005',
          name: 'Outbound Payment Volume',
          description: 'Total dollar value of outbound commercial payments',
          category: 'Payment Volume',
          subcategory: 'Direction',
          formula: "SUM(payment_amount WHERE direction = 'outbound')",
          businessLogic: 'Sum of outbound payment amounts',
          dataType: 'DECIMAL',
          unit: 'currency',
          aggregation: 'SUM',
          granularity: 'Daily',
          sourceTables: ['bronze.commercial_payments'],
          calculation: { numerator: "SUM(transaction_amount)", filters: "payment_direction = 'outbound'" },
          businessDefinition: 'Commercial outbound payment processing volume',
          benchmarks: { industryAverage: '$620M/day', topQuartile: '$1.3B/day', target: '$880M/day' },
        },
        {
          id: 'PCM-VOL-006',
          name: 'Inbound Payment Volume',
          description: 'Total dollar value of inbound commercial payments',
          category: 'Payment Volume',
          subcategory: 'Direction',
          formula: "SUM(payment_amount WHERE direction = 'inbound')",
          businessLogic: 'Sum of inbound payment amounts',
          dataType: 'DECIMAL',
          unit: 'currency',
          aggregation: 'SUM',
          granularity: 'Daily',
          sourceTables: ['bronze.commercial_payments'],
          calculation: { numerator: "SUM(transaction_amount)", filters: "payment_direction = 'inbound'" },
          businessDefinition: 'Commercial inbound payment processing volume',
          benchmarks: { industryAverage: '$230M/day', topQuartile: '$520M/day', target: '$340M/day' },
        },
        {
          id: 'PCM-VOL-007',
          name: 'Peak Hour Payment Volume',
          description: 'Maximum payment volume processed in a single hour',
          category: 'Payment Volume',
          subcategory: 'Peak',
          formula: "MAX(hourly_payment_amount)",
          businessLogic: 'Maximum hourly payment volume',
          dataType: 'DECIMAL',
          unit: 'currency',
          aggregation: 'MAX',
          granularity: 'Hourly',
          sourceTables: ['gold.fact_payment_transactions'],
          calculation: { sql: "MAX(SUM(amount) OVER (PARTITION BY date_trunc('hour', transaction_time)))" },
          businessDefinition: 'Peak hourly commercial payment volume',
          benchmarks: { industryAverage: '$95M/hour', topQuartile: '$210M/hour', target: '$145M/hour' },
        },
        {
          id: 'PCM-VOL-008',
          name: 'Same-Day Payment Volume',
          description: 'Dollar value of same-day ACH and RTP payments',
          category: 'Payment Volume',
          subcategory: 'Speed',
          formula: "SUM(payment_amount WHERE payment_speed = 'same_day')",
          businessLogic: 'Sum of same-day payment amounts',
          dataType: 'DECIMAL',
          unit: 'currency',
          aggregation: 'SUM',
          granularity: 'Daily',
          sourceTables: ['bronze.commercial_ach_originations', 'bronze.commercial_rtp_transactions'],
          calculation: { numerator: "SUM(amount)", filters: "payment_type IN ('same_day_ach', 'rtp')" },
          businessDefinition: 'Same-day commercial payment volume',
          benchmarks: { industryAverage: '$180M/day', topQuartile: '$420M/day', target: '$285M/day' },
        },
        {
          id: 'PCM-VOL-009',
          name: 'International Payment Volume',
          description: 'Dollar value of international wire transfers',
          category: 'Payment Volume',
          subcategory: 'Geography',
          formula: "SUM(wire_amount WHERE wire_type = 'international')",
          businessLogic: 'Sum of international wire amounts',
          dataType: 'DECIMAL',
          unit: 'currency',
          aggregation: 'SUM',
          granularity: 'Daily',
          sourceTables: ['bronze.commercial_wire_international'],
          calculation: { numerator: "SUM(amount)", filters: "wire_type = 'international'" },
          businessDefinition: 'International commercial wire transfer volume',
          benchmarks: { industryAverage: '$125M/day', topQuartile: '$290M/day', target: '$195M/day' },
        },
        {
          id: 'PCM-VOL-010',
          name: 'Domestic Payment Volume',
          description: 'Dollar value of domestic payments (ACH + domestic wires)',
          category: 'Payment Volume',
          subcategory: 'Geography',
          formula: "SUM(payment_amount WHERE geography = 'domestic')",
          businessLogic: 'Sum of domestic payment amounts',
          dataType: 'DECIMAL',
          unit: 'currency',
          aggregation: 'SUM',
          granularity: 'Daily',
          sourceTables: ['bronze.commercial_payments'],
          calculation: { numerator: "SUM(amount)", filters: "payment_geography = 'domestic'" },
          businessDefinition: 'Domestic commercial payment volume',
          benchmarks: { industryAverage: '$725M/day', topQuartile: '$1.51B/day', target: '$1.01B/day' },
        },
        {
          id: 'PCM-VOL-011',
          name: 'High-Value Payment Volume',
          description: 'Dollar value of payments exceeding $1M',
          category: 'Payment Volume',
          subcategory: 'Value Tier',
          formula: "SUM(payment_amount WHERE payment_amount >= 1000000)",
          businessLogic: 'Sum of high-value payment amounts',
          dataType: 'DECIMAL',
          unit: 'currency',
          aggregation: 'SUM',
          granularity: 'Daily',
          sourceTables: ['bronze.commercial_payments'],
          calculation: { numerator: "SUM(amount)", filters: "amount >= 1000000" },
          businessDefinition: 'High-value commercial payment volume (≥$1M)',
          benchmarks: { industryAverage: '$520M/day', topQuartile: '$1.15B/day', target: '$780M/day' },
        },
        {
          id: 'PCM-VOL-012',
          name: 'Payroll Payment Volume',
          description: 'Total dollar value of payroll payments',
          category: 'Payment Volume',
          subcategory: 'Purpose',
          formula: "SUM(payment_amount WHERE payment_purpose = 'payroll')",
          businessLogic: 'Sum of payroll payment amounts',
          dataType: 'DECIMAL',
          unit: 'currency',
          aggregation: 'SUM',
          granularity: 'Daily',
          sourceTables: ['bronze.commercial_payroll_payments'],
          calculation: { numerator: "SUM(amount)", filters: "payment_type = 'payroll'" },
          businessDefinition: 'Commercial payroll payment volume',
          benchmarks: { industryAverage: '$85M/day', topQuartile: '$195M/day', target: '$135M/day' },
        },
        {
          id: 'PCM-VOL-013',
          name: 'Vendor Payment Volume',
          description: 'Total dollar value of vendor/supplier payments',
          category: 'Payment Volume',
          subcategory: 'Purpose',
          formula: "SUM(payment_amount WHERE payment_purpose = 'vendor')",
          businessLogic: 'Sum of vendor payment amounts',
          dataType: 'DECIMAL',
          unit: 'currency',
          aggregation: 'SUM',
          granularity: 'Daily',
          sourceTables: ['bronze.commercial_payments'],
          calculation: { numerator: "SUM(amount)", filters: "payment_purpose IN ('vendor', 'supplier')" },
          businessDefinition: 'Commercial vendor payment volume',
          benchmarks: { industryAverage: '$420M/day', topQuartile: '$890M/day', target: '$620M/day' },
        },
        {
          id: 'PCM-VOL-014',
          name: 'Tax Payment Volume',
          description: 'Total dollar value of tax payments',
          category: 'Payment Volume',
          subcategory: 'Purpose',
          formula: "SUM(payment_amount WHERE payment_purpose = 'tax')",
          businessLogic: 'Sum of tax payment amounts',
          dataType: 'DECIMAL',
          unit: 'currency',
          aggregation: 'SUM',
          granularity: 'Daily',
          sourceTables: ['bronze.commercial_payments'],
          calculation: { numerator: "SUM(amount)", filters: "payment_purpose = 'tax'" },
          businessDefinition: 'Commercial tax payment volume',
          benchmarks: { industryAverage: '$65M/day', topQuartile: '$145M/day', target: '$95M/day' },
        },
        {
          id: 'PCM-VOL-015',
          name: 'Recurring Payment Volume',
          description: 'Dollar value of scheduled recurring payments',
          category: 'Payment Volume',
          subcategory: 'Frequency',
          formula: "SUM(payment_amount WHERE is_recurring = true)",
          businessLogic: 'Sum of recurring payment amounts',
          dataType: 'DECIMAL',
          unit: 'currency',
          aggregation: 'SUM',
          granularity: 'Daily',
          sourceTables: ['bronze.commercial_payments', 'bronze.commercial_payment_templates'],
          calculation: { numerator: "SUM(amount)", filters: "is_recurring_payment = true" },
          businessDefinition: 'Recurring commercial payment volume',
          benchmarks: { industryAverage: '$385M/day', topQuartile: '$820M/day', target: '$570M/day' },
        },
        {
          id: 'PCM-VOL-016',
          name: 'One-Time Payment Volume',
          description: 'Dollar value of ad-hoc one-time payments',
          category: 'Payment Volume',
          subcategory: 'Frequency',
          formula: "SUM(payment_amount WHERE is_recurring = false)",
          businessLogic: 'Sum of one-time payment amounts',
          dataType: 'DECIMAL',
          unit: 'currency',
          aggregation: 'SUM',
          granularity: 'Daily',
          sourceTables: ['bronze.commercial_payments'],
          calculation: { numerator: "SUM(amount)", filters: "is_recurring_payment = false" },
          businessDefinition: 'One-time commercial payment volume',
          benchmarks: { industryAverage: '$465M/day', topQuartile: '$980M/day', target: '$630M/day' },
        },
        {
          id: 'PCM-VOL-017',
          name: 'Batch Payment Volume',
          description: 'Dollar value of payments submitted via batch files',
          category: 'Payment Volume',
          subcategory: 'Channel',
          formula: "SUM(payment_amount WHERE submission_channel = 'batch')",
          businessLogic: 'Sum of batch payment amounts',
          dataType: 'DECIMAL',
          unit: 'currency',
          aggregation: 'SUM',
          granularity: 'Daily',
          sourceTables: ['bronze.commercial_ach_batches', 'bronze.commercial_payments'],
          calculation: { numerator: "SUM(amount)", filters: "submission_method = 'batch_file'" },
          businessDefinition: 'Commercial batch payment volume',
          benchmarks: { industryAverage: '$610M/day', topQuartile: '$1.28B/day', target: '$890M/day' },
        },
        {
          id: 'PCM-VOL-018',
          name: 'Online Payment Volume',
          description: 'Dollar value of payments initiated through online banking',
          category: 'Payment Volume',
          subcategory: 'Channel',
          formula: "SUM(payment_amount WHERE submission_channel = 'online')",
          businessLogic: 'Sum of online payment amounts',
          dataType: 'DECIMAL',
          unit: 'currency',
          aggregation: 'SUM',
          granularity: 'Daily',
          sourceTables: ['bronze.commercial_payments'],
          calculation: { numerator: "SUM(amount)", filters: "submission_channel = 'online_banking'" },
          businessDefinition: 'Commercial online payment volume',
          benchmarks: { industryAverage: '$240M/day', topQuartile: '$520M/day', target: '$330M/day' },
        },
      ],
    },
    {
      name: 'ACH Metrics',
      description: 'Commercial ACH transaction processing and quality',
      totalMetrics: 15,
      metrics: [
        {
          id: 'PCM-ACH-001',
          name: 'ACH Transaction Count',
          description: 'Number of commercial ACH transactions processed',
          category: 'ACH',
          subcategory: 'Volume',
          formula: "COUNT(transaction_id WHERE payment_type = 'ACH')",
          businessLogic: 'Count of ACH transactions',
          dataType: 'INTEGER',
          unit: 'count',
          aggregation: 'COUNT',
          granularity: 'Daily',
          sourceTables: ['bronze.commercial_ach_originations'],
          calculation: { numerator: "COUNT(transaction_id)", filters: "payment_method = 'ACH'" },
          businessDefinition: 'Commercial ACH processing volume',
          benchmarks: { industryAverage: '125K/day', topQuartile: '280K/day', target: '190K/day' },
        },
        {
          id: 'PCM-ACH-002',
          name: 'ACH Dollar Volume',
          description: 'Total dollar value of ACH payments',
          category: 'ACH',
          subcategory: 'Volume',
          formula: "SUM(ach_amount)",
          businessLogic: 'Sum of ACH payment amounts',
          dataType: 'DECIMAL',
          unit: 'currency',
          aggregation: 'SUM',
          granularity: 'Daily',
          sourceTables: ['bronze.commercial_ach_originations'],
          calculation: { numerator: "SUM(amount)", filters: "payment_type = 'ACH'" },
          businessDefinition: 'Commercial ACH payment value',
          benchmarks: { industryAverage: '$520M/day', topQuartile: '$1.15B/day', target: '$780M/day' },
        },
        {
          id: 'PCM-ACH-003',
          name: 'ACH Return Rate',
          description: 'Percentage of ACH transactions returned',
          category: 'ACH',
          subcategory: 'Quality',
          formula: "(COUNT(returns) / COUNT(total_ach)) * 100",
          businessLogic: 'ACH returns / total ACH transactions',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Daily',
          sourceTables: ['bronze.commercial_ach_returns', 'bronze.commercial_ach_originations'],
          calculation: { numerator: "COUNT(return_id)", denominator: "COUNT(transaction_id)", multiplier: 100 },
          businessDefinition: 'Commercial ACH return rate',
          benchmarks: { industryAverage: '1.8%', topQuartile: '0.9%', target: '1.2%' },
        },
        {
          id: 'PCM-ACH-004',
          name: 'Same-Day ACH Count',
          description: 'Number of same-day ACH transactions',
          category: 'ACH',
          subcategory: 'Speed',
          formula: "COUNT(transaction_id WHERE ach_type = 'same_day')",
          businessLogic: 'Count of same-day ACH transactions',
          dataType: 'INTEGER',
          unit: 'count',
          aggregation: 'COUNT',
          granularity: 'Daily',
          sourceTables: ['bronze.commercial_ach_originations'],
          calculation: { numerator: "COUNT(transaction_id)", filters: "ach_processing_type = 'same_day'" },
          businessDefinition: 'Same-day ACH transaction volume',
          benchmarks: { industryAverage: '42K/day', topQuartile: '95K/day', target: '65K/day' },
        },
        {
          id: 'PCM-ACH-005',
          name: 'Same-Day ACH Percentage',
          description: 'Percentage of ACH transactions processed same-day',
          category: 'ACH',
          subcategory: 'Speed',
          formula: "(COUNT(same_day_ach) / COUNT(total_ach)) * 100",
          businessLogic: 'Same-day ACH / total ACH',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Daily',
          sourceTables: ['bronze.commercial_ach_originations'],
          calculation: { numerator: "COUNT(WHERE processing_type = 'same_day')", denominator: "COUNT(transaction_id)", multiplier: 100 },
          businessDefinition: 'Same-day ACH adoption rate',
          benchmarks: { industryAverage: '33.6%', topQuartile: '48.2%', target: '42.0%' },
        },
        {
          id: 'PCM-ACH-006',
          name: 'CCD Transaction Count',
          description: 'Number of CCD (corporate credit/debit) ACH transactions',
          category: 'ACH',
          subcategory: 'SEC Code',
          formula: "COUNT(transaction_id WHERE sec_code = 'CCD')",
          businessLogic: 'Count of CCD ACH transactions',
          dataType: 'INTEGER',
          unit: 'count',
          aggregation: 'COUNT',
          granularity: 'Daily',
          sourceTables: ['bronze.commercial_ach_originations'],
          calculation: { numerator: "COUNT(transaction_id)", filters: "sec_code = 'CCD'" },
          businessDefinition: 'CCD ACH transaction volume',
          benchmarks: { industryAverage: '65K/day', topQuartile: '148K/day', target: '95K/day' },
        },
        {
          id: 'PCM-ACH-007',
          name: 'CTX Transaction Count',
          description: 'Number of CTX (corporate trade exchange) ACH transactions',
          category: 'ACH',
          subcategory: 'SEC Code',
          formula: "COUNT(transaction_id WHERE sec_code = 'CTX')",
          businessLogic: 'Count of CTX ACH transactions',
          dataType: 'INTEGER',
          unit: 'count',
          aggregation: 'COUNT',
          granularity: 'Daily',
          sourceTables: ['bronze.commercial_ach_originations'],
          calculation: { numerator: "COUNT(transaction_id)", filters: "sec_code = 'CTX'" },
          businessDefinition: 'CTX ACH transaction volume',
          benchmarks: { industryAverage: '18K/day', topQuartile: '42K/day', target: '28K/day' },
        },
        {
          id: 'PCM-ACH-008',
          name: 'PPD Transaction Count',
          description: 'Number of PPD (prearranged payment/deposit) ACH transactions',
          category: 'ACH',
          subcategory: 'SEC Code',
          formula: "COUNT(transaction_id WHERE sec_code = 'PPD')",
          businessLogic: 'Count of PPD ACH transactions (payroll)',
          dataType: 'INTEGER',
          unit: 'count',
          aggregation: 'COUNT',
          granularity: 'Daily',
          sourceTables: ['bronze.commercial_ach_originations', 'bronze.commercial_payroll_payments'],
          calculation: { numerator: "COUNT(transaction_id)", filters: "sec_code = 'PPD'" },
          businessDefinition: 'PPD ACH transaction volume (primarily payroll)',
          benchmarks: { industryAverage: '38K/day', topQuartile: '85K/day', target: '62K/day' },
        },
        {
          id: 'PCM-ACH-009',
          name: 'ACH NOC Count',
          description: 'Number of ACH Notifications of Change received',
          category: 'ACH',
          subcategory: 'Quality',
          formula: "COUNT(noc_id)",
          businessLogic: 'Count of ACH NOC transactions',
          dataType: 'INTEGER',
          unit: 'count',
          aggregation: 'COUNT',
          granularity: 'Daily',
          sourceTables: ['bronze.commercial_ach_nocs'],
          calculation: { numerator: "COUNT(noc_id)" },
          businessDefinition: 'ACH Notification of Change volume',
          benchmarks: { industryAverage: '1,250/day', topQuartile: '850/day', target: '950/day' },
        },
        {
          id: 'PCM-ACH-010',
          name: 'ACH Prenote Count',
          description: 'Number of ACH prenote verification transactions',
          category: 'ACH',
          subcategory: 'Validation',
          formula: "COUNT(prenote_id)",
          businessLogic: 'Count of ACH prenote transactions',
          dataType: 'INTEGER',
          unit: 'count',
          aggregation: 'COUNT',
          granularity: 'Daily',
          sourceTables: ['bronze.commercial_ach_prenotes'],
          calculation: { numerator: "COUNT(prenote_id)" },
          businessDefinition: 'ACH prenote verification volume',
          benchmarks: { industryAverage: '2,850/day', topQuartile: '1,950/day', target: '2,250/day' },
        },
        {
          id: 'PCM-ACH-011',
          name: 'ACH Batch Count',
          description: 'Number of ACH batch files processed',
          category: 'ACH',
          subcategory: 'Processing',
          formula: "COUNT(batch_id)",
          businessLogic: 'Count of ACH batch files',
          dataType: 'INTEGER',
          unit: 'count',
          aggregation: 'COUNT',
          granularity: 'Daily',
          sourceTables: ['bronze.commercial_ach_batches'],
          calculation: { numerator: "COUNT(batch_id)" },
          businessDefinition: 'ACH batch file processing volume',
          benchmarks: { industryAverage: '3,850/day', topQuartile: '8,200/day', target: '5,750/day' },
        },
        {
          id: 'PCM-ACH-012',
          name: 'Average ACH Batch Size',
          description: 'Average number of transactions per ACH batch',
          category: 'ACH',
          subcategory: 'Processing',
          formula: "AVG(batch_transaction_count)",
          businessLogic: 'Average transactions per batch',
          dataType: 'INTEGER',
          unit: 'count',
          aggregation: 'AVG',
          granularity: 'Daily',
          sourceTables: ['bronze.commercial_ach_batches'],
          calculation: { numerator: "COUNT(transaction_id)", denominator: "COUNT(DISTINCT batch_id)" },
          businessDefinition: 'Average ACH batch size',
          benchmarks: { industryAverage: '32.5', topQuartile: '42.8', target: '38.0' },
        },
        {
          id: 'PCM-ACH-013',
          name: 'ACH Reversal Count',
          description: 'Number of ACH reversal transactions',
          category: 'ACH',
          subcategory: 'Corrections',
          formula: "COUNT(reversal_id)",
          businessLogic: 'Count of ACH reversals',
          dataType: 'INTEGER',
          unit: 'count',
          aggregation: 'COUNT',
          granularity: 'Daily',
          sourceTables: ['bronze.commercial_ach_reversals'],
          calculation: { numerator: "COUNT(reversal_id)" },
          businessDefinition: 'ACH reversal transaction volume',
          benchmarks: { industryAverage: '420/day', topQuartile: '280/day', target: '320/day' },
        },
        {
          id: 'PCM-ACH-014',
          name: 'ACH Return Dollar Value',
          description: 'Total dollar value of returned ACH transactions',
          category: 'ACH',
          subcategory: 'Quality',
          formula: "SUM(return_amount)",
          businessLogic: 'Sum of ACH return amounts',
          dataType: 'DECIMAL',
          unit: 'currency',
          aggregation: 'SUM',
          granularity: 'Daily',
          sourceTables: ['bronze.commercial_ach_returns'],
          calculation: { numerator: "SUM(return_amount)" },
          businessDefinition: 'Total value of returned ACH payments',
          benchmarks: { industryAverage: '$9.4M/day', topQuartile: '$5.8M/day', target: '$6.9M/day' },
        },
        {
          id: 'PCM-ACH-015',
          name: 'ACH Positive Pay Exception Count',
          description: 'Number of ACH positive pay exceptions requiring review',
          category: 'ACH',
          subcategory: 'Fraud Prevention',
          formula: "COUNT(exception_id WHERE exception_type = 'ach_positive_pay')",
          businessLogic: 'Count of ACH positive pay exceptions',
          dataType: 'INTEGER',
          unit: 'count',
          aggregation: 'COUNT',
          granularity: 'Daily',
          sourceTables: ['bronze.commercial_ach_positive_pay'],
          calculation: { numerator: "COUNT(exception_id)", filters: "exception_status = 'pending_review'" },
          businessDefinition: 'ACH positive pay exception volume',
          benchmarks: { industryAverage: '685/day', topQuartile: '420/day', target: '520/day' },
        },
      ],
    },
    {
      name: 'Wire Transfer Metrics',
      description: 'Commercial wire transfer volume and timeliness',
      totalMetrics: 14,
      metrics: [
        {
          id: 'PCM-WIRE-001',
          name: 'Wire Transfer Volume',
          description: 'Dollar value of commercial wire transfers',
          category: 'Wire Transfer',
          subcategory: 'Volume',
          formula: "SUM(wire_amount)",
          businessLogic: 'Sum of wire transfer amounts',
          dataType: 'DECIMAL',
          unit: 'currency',
          aggregation: 'SUM',
          granularity: 'Daily',
          sourceTables: ['bronze.commercial_wire_domestic', 'bronze.commercial_wire_international'],
          calculation: { numerator: "SUM(amount)", filters: "payment_type = 'wire'" },
          businessDefinition: 'Commercial wire transfer value',
          benchmarks: { industryAverage: '$420M/day', topQuartile: '$920M/day', target: '$650M/day' },
        },
        {
          id: 'PCM-WIRE-002',
          name: 'Wire Transaction Count',
          description: 'Number of wire transfer transactions',
          category: 'Wire Transfer',
          subcategory: 'Volume',
          formula: "COUNT(wire_id)",
          businessLogic: 'Count of wire transfers',
          dataType: 'INTEGER',
          unit: 'count',
          aggregation: 'COUNT',
          granularity: 'Daily',
          sourceTables: ['bronze.commercial_wire_domestic', 'bronze.commercial_wire_international'],
          calculation: { numerator: "COUNT(wire_id)" },
          businessDefinition: 'Wire transfer transaction count',
          benchmarks: { industryAverage: '3,250/day', topQuartile: '7,200/day', target: '4,950/day' },
        },
        {
          id: 'PCM-WIRE-003',
          name: 'Domestic Wire Volume',
          description: 'Dollar value of domestic Fedwire transfers',
          category: 'Wire Transfer',
          subcategory: 'Geography',
          formula: "SUM(wire_amount WHERE wire_type = 'domestic')",
          businessLogic: 'Sum of domestic wire amounts',
          dataType: 'DECIMAL',
          unit: 'currency',
          aggregation: 'SUM',
          granularity: 'Daily',
          sourceTables: ['bronze.commercial_wire_domestic'],
          calculation: { numerator: "SUM(amount)", filters: "wire_type = 'domestic'" },
          businessDefinition: 'Domestic Fedwire transfer value',
          benchmarks: { industryAverage: '$295M/day', topQuartile: '$630M/day', target: '$455M/day' },
        },
        {
          id: 'PCM-WIRE-004',
          name: 'International Wire Volume',
          description: 'Dollar value of international SWIFT wire transfers',
          category: 'Wire Transfer',
          subcategory: 'Geography',
          formula: "SUM(wire_amount WHERE wire_type = 'international')",
          businessLogic: 'Sum of international wire amounts',
          dataType: 'DECIMAL',
          unit: 'currency',
          aggregation: 'SUM',
          granularity: 'Daily',
          sourceTables: ['bronze.commercial_wire_international'],
          calculation: { numerator: "SUM(amount)", filters: "wire_type = 'international'" },
          businessDefinition: 'International SWIFT wire transfer value',
          benchmarks: { industryAverage: '$125M/day', topQuartile: '$290M/day', target: '$195M/day' },
        },
        {
          id: 'PCM-WIRE-005',
          name: 'Average Wire Amount',
          description: 'Average dollar value per wire transfer',
          category: 'Wire Transfer',
          subcategory: 'Size',
          formula: "AVG(wire_amount)",
          businessLogic: 'Average wire transfer amount',
          dataType: 'DECIMAL',
          unit: 'currency',
          aggregation: 'AVG',
          granularity: 'Daily',
          sourceTables: ['bronze.commercial_wire_domestic', 'bronze.commercial_wire_international'],
          calculation: { numerator: "SUM(amount)", denominator: "COUNT(wire_id)" },
          businessDefinition: 'Average wire transfer size',
          benchmarks: { industryAverage: '$129,230', topQuartile: '$127,840', target: '$131,350' },
        },
        {
          id: 'PCM-WIRE-006',
          name: 'Wire Processing Time',
          description: 'Average time from initiation to completion (minutes)',
          category: 'Wire Transfer',
          subcategory: 'Timeliness',
          formula: "AVG(completion_time - initiation_time)",
          businessLogic: 'Average wire processing duration',
          dataType: 'INTEGER',
          unit: 'minutes',
          aggregation: 'AVG',
          granularity: 'Daily',
          sourceTables: ['bronze.commercial_wire_domestic', 'bronze.commercial_wire_international'],
          calculation: { sql: "AVG(EXTRACT(EPOCH FROM (completion_timestamp - initiation_timestamp))/60)" },
          businessDefinition: 'Average wire transfer processing time',
          benchmarks: { industryAverage: '32 min', topQuartile: '18 min', target: '22 min' },
        },
        {
          id: 'PCM-WIRE-007',
          name: 'Wire Completion Rate',
          description: 'Percentage of wires completed successfully',
          category: 'Wire Transfer',
          subcategory: 'Quality',
          formula: "(COUNT(completed) / COUNT(total_wires)) * 100",
          businessLogic: 'Completed wires / total wires',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Daily',
          sourceTables: ['bronze.commercial_wire_domestic', 'bronze.commercial_wire_international'],
          calculation: { numerator: "COUNT(WHERE status = 'completed')", denominator: "COUNT(wire_id)", multiplier: 100 },
          businessDefinition: 'Wire transfer success rate',
          benchmarks: { industryAverage: '97.8%', topQuartile: '99.1%', target: '98.5%' },
        },
        {
          id: 'PCM-WIRE-008',
          name: 'Wire Recall Count',
          description: 'Number of wire transfer recall requests',
          category: 'Wire Transfer',
          subcategory: 'Corrections',
          formula: "COUNT(recall_id)",
          businessLogic: 'Count of wire recalls',
          dataType: 'INTEGER',
          unit: 'count',
          aggregation: 'COUNT',
          granularity: 'Daily',
          sourceTables: ['bronze.commercial_wire_domestic', 'bronze.commercial_wire_international'],
          calculation: { numerator: "COUNT(recall_id)" },
          businessDefinition: 'Wire transfer recall volume',
          benchmarks: { industryAverage: '28/day', topQuartile: '16/day', target: '20/day' },
        },
        {
          id: 'PCM-WIRE-009',
          name: 'OFAC Wire Screening Match Rate',
          description: 'Percentage of wire transfers with OFAC screening matches',
          category: 'Wire Transfer',
          subcategory: 'Compliance',
          formula: "(COUNT(ofac_matches) / COUNT(total_wires)) * 100",
          businessLogic: 'OFAC matches / total wires',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Daily',
          sourceTables: ['bronze.commercial_ofac_screening'],
          calculation: { numerator: "COUNT(WHERE has_ofac_match = true)", denominator: "COUNT(transaction_id)", multiplier: 100, filters: "payment_type = 'wire'" },
          businessDefinition: 'Wire transfer OFAC screening match rate',
          benchmarks: { industryAverage: '0.18%', topQuartile: '0.12%', target: '0.14%' },
        },
        {
          id: 'PCM-WIRE-010',
          name: 'SWIFT MT103 Count',
          description: 'Number of SWIFT MT103 single customer credit transfers',
          category: 'Wire Transfer',
          subcategory: 'Message Type',
          formula: "COUNT(wire_id WHERE swift_message_type = 'MT103')",
          businessLogic: 'Count of MT103 messages',
          dataType: 'INTEGER',
          unit: 'count',
          aggregation: 'COUNT',
          granularity: 'Daily',
          sourceTables: ['bronze.commercial_wire_international'],
          calculation: { numerator: "COUNT(wire_id)", filters: "swift_message_type = 'MT103'" },
          businessDefinition: 'SWIFT MT103 message volume',
          benchmarks: { industryAverage: '1,850/day', topQuartile: '4,200/day', target: '2,950/day' },
        },
        {
          id: 'PCM-WIRE-011',
          name: 'SWIFT MT202 Count',
          description: 'Number of SWIFT MT202 financial institution transfers',
          category: 'Wire Transfer',
          subcategory: 'Message Type',
          formula: "COUNT(wire_id WHERE swift_message_type = 'MT202')",
          businessLogic: 'Count of MT202 messages',
          dataType: 'INTEGER',
          unit: 'count',
          aggregation: 'COUNT',
          granularity: 'Daily',
          sourceTables: ['bronze.commercial_wire_international'],
          calculation: { numerator: "COUNT(wire_id)", filters: "swift_message_type = 'MT202'" },
          businessDefinition: 'SWIFT MT202 message volume',
          benchmarks: { industryAverage: '420/day', topQuartile: '950/day', target: '650/day' },
        },
        {
          id: 'PCM-WIRE-012',
          name: 'Wire Approval Time',
          description: 'Average time for wire transfer approval (minutes)',
          category: 'Wire Transfer',
          subcategory: 'Timeliness',
          formula: "AVG(approval_time - submission_time)",
          businessLogic: 'Average wire approval duration',
          dataType: 'INTEGER',
          unit: 'minutes',
          aggregation: 'AVG',
          granularity: 'Daily',
          sourceTables: ['bronze.commercial_payment_approvals'],
          calculation: { sql: "AVG(EXTRACT(EPOCH FROM (approval_timestamp - submission_timestamp))/60)", filters: "payment_type = 'wire'" },
          businessDefinition: 'Average wire transfer approval time',
          benchmarks: { industryAverage: '14 min', topQuartile: '8 min', target: '10 min' },
        },
        {
          id: 'PCM-WIRE-013',
          name: 'Wire Fee Revenue',
          description: 'Total fee income from wire transfer services',
          category: 'Wire Transfer',
          subcategory: 'Revenue',
          formula: "SUM(wire_fee)",
          businessLogic: 'Sum of wire transfer fees',
          dataType: 'DECIMAL',
          unit: 'currency',
          aggregation: 'SUM',
          granularity: 'Daily',
          sourceTables: ['bronze.commercial_wire_fees'],
          calculation: { numerator: "SUM(fee_amount)", filters: "payment_type = 'wire'" },
          businessDefinition: 'Wire transfer fee revenue',
          benchmarks: { industryAverage: '$97.5K/day', topQuartile: '$216K/day', target: '$148.5K/day' },
        },
        {
          id: 'PCM-WIRE-014',
          name: 'Wire Cutoff Compliance Rate',
          description: 'Percentage of wires submitted before daily cutoff time',
          category: 'Wire Transfer',
          subcategory: 'Timeliness',
          formula: "(COUNT(before_cutoff) / COUNT(total_wires)) * 100",
          businessLogic: 'Pre-cutoff wires / total wires',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Daily',
          sourceTables: ['bronze.commercial_wire_domestic', 'bronze.commercial_wire_international'],
          calculation: { numerator: "COUNT(WHERE submission_time < cutoff_time)", denominator: "COUNT(wire_id)", multiplier: 100 },
          businessDefinition: 'Wire transfer cutoff compliance rate',
          benchmarks: { industryAverage: '87.3%', topQuartile: '94.8%', target: '92.0%' },
        },
      ],
    },
    {
      name: 'Payment Revenue Metrics',
      description: 'Commercial payment fee revenue and pricing',
      totalMetrics: 13,
      metrics: [
        {
          id: 'PCM-REV-001',
          name: 'Total Payment Fee Revenue',
          description: 'Total fee income from commercial payment services',
          category: 'Revenue',
          subcategory: 'Fee Income',
          formula: "SUM(payment_fee)",
          businessLogic: 'Sum of all payment processing fees',
          dataType: 'DECIMAL',
          unit: 'currency',
          aggregation: 'SUM',
          granularity: 'Monthly',
          sourceTables: ['bronze.commercial_payment_fees', 'gold.fact_payment_revenue'],
          calculation: { numerator: "SUM(fee_amount)" },
          businessDefinition: 'Commercial payment services revenue',
          benchmarks: { industryAverage: '$380K/month', topQuartile: '$850K/month', target: '$580K/month' },
        },
        {
          id: 'PCM-REV-002',
          name: 'ACH Fee Revenue',
          description: 'Fee income from ACH processing services',
          category: 'Revenue',
          subcategory: 'ACH',
          formula: "SUM(ach_fee)",
          businessLogic: 'Sum of ACH processing fees',
          dataType: 'DECIMAL',
          unit: 'currency',
          aggregation: 'SUM',
          granularity: 'Monthly',
          sourceTables: ['bronze.commercial_payment_fees'],
          calculation: { numerator: "SUM(fee_amount)", filters: "payment_type = 'ACH'" },
          businessDefinition: 'ACH processing fee revenue',
          benchmarks: { industryAverage: '$145K/month', topQuartile: '$325K/month', target: '$220K/month' },
        },
        {
          id: 'PCM-REV-003',
          name: 'Wire Fee Revenue',
          description: 'Fee income from wire transfer services',
          category: 'Revenue',
          subcategory: 'Wire',
          formula: "SUM(wire_fee)",
          businessLogic: 'Sum of wire transfer fees',
          dataType: 'DECIMAL',
          unit: 'currency',
          aggregation: 'SUM',
          granularity: 'Monthly',
          sourceTables: ['bronze.commercial_wire_fees'],
          calculation: { numerator: "SUM(fee_amount)", filters: "payment_type = 'wire'" },
          businessDefinition: 'Wire transfer fee revenue',
          benchmarks: { industryAverage: '$195K/month', topQuartile: '$435K/month', target: '$295K/month' },
        },
        {
          id: 'PCM-REV-004',
          name: 'RTP Fee Revenue',
          description: 'Fee income from Real-Time Payment services',
          category: 'Revenue',
          subcategory: 'RTP',
          formula: "SUM(rtp_fee)",
          businessLogic: 'Sum of RTP processing fees',
          dataType: 'DECIMAL',
          unit: 'currency',
          aggregation: 'SUM',
          granularity: 'Monthly',
          sourceTables: ['bronze.commercial_payment_fees'],
          calculation: { numerator: "SUM(fee_amount)", filters: "payment_type = 'RTP'" },
          businessDefinition: 'Real-Time Payment fee revenue',
          benchmarks: { industryAverage: '$28K/month', topQuartile: '$65K/month', target: '$42K/month' },
        },
        {
          id: 'PCM-REV-005',
          name: 'Positive Pay Fee Revenue',
          description: 'Fee income from positive pay services',
          category: 'Revenue',
          subcategory: 'Services',
          formula: "SUM(positive_pay_fee)",
          businessLogic: 'Sum of positive pay service fees',
          dataType: 'DECIMAL',
          unit: 'currency',
          aggregation: 'SUM',
          granularity: 'Monthly',
          sourceTables: ['bronze.commercial_payment_fees'],
          calculation: { numerator: "SUM(fee_amount)", filters: "service_type = 'positive_pay'" },
          businessDefinition: 'Positive pay service fee revenue',
          benchmarks: { industryAverage: '$12K/month', topQuartile: '$25K/month', target: '$18K/month' },
        },
        {
          id: 'PCM-REV-006',
          name: 'Average Fee Per Payment',
          description: 'Average fee charged per payment transaction',
          category: 'Revenue',
          subcategory: 'Pricing',
          formula: "AVG(payment_fee)",
          businessLogic: 'Average fee per transaction',
          dataType: 'DECIMAL',
          unit: 'currency',
          aggregation: 'AVG',
          granularity: 'Monthly',
          sourceTables: ['bronze.commercial_payment_fees'],
          calculation: { numerator: "SUM(fee_amount)", denominator: "COUNT(transaction_id)" },
          businessDefinition: 'Average payment processing fee',
          benchmarks: { industryAverage: '$2.05', topQuartile: '$2.28', target: '$2.00' },
        },
        {
          id: 'PCM-REV-007',
          name: 'Fee Waiver Rate',
          description: 'Percentage of fees waived for relationship pricing',
          category: 'Revenue',
          subcategory: 'Waivers',
          formula: "(COUNT(waived_fees) / COUNT(total_fees)) * 100",
          businessLogic: 'Waived fees / total fees',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Monthly',
          sourceTables: ['bronze.commercial_payment_fees'],
          calculation: { numerator: "COUNT(WHERE fee_waived = true)", denominator: "COUNT(fee_id)", multiplier: 100 },
          businessDefinition: 'Payment fee waiver rate',
          benchmarks: { industryAverage: '12.4%', topQuartile: '8.5%', target: '9.5%' },
        },
        {
          id: 'PCM-REV-008',
          name: 'Fee Waiver Dollar Impact',
          description: 'Dollar value of waived payment fees',
          category: 'Revenue',
          subcategory: 'Waivers',
          formula: "SUM(waived_fee_amount)",
          businessLogic: 'Sum of waived fee amounts',
          dataType: 'DECIMAL',
          unit: 'currency',
          aggregation: 'SUM',
          granularity: 'Monthly',
          sourceTables: ['bronze.commercial_payment_fees'],
          calculation: { numerator: "SUM(fee_amount)", filters: "fee_waived = true" },
          businessDefinition: 'Total value of waived payment fees',
          benchmarks: { industryAverage: '$47K/month', topQuartile: '$72K/month', target: '$55K/month' },
        },
        {
          id: 'PCM-REV-009',
          name: 'Revenue per Customer',
          description: 'Average monthly payment fee revenue per commercial customer',
          category: 'Revenue',
          subcategory: 'Customer',
          formula: "SUM(payment_fee) / COUNT(DISTINCT customer_id)",
          businessLogic: 'Total fee revenue / unique customers',
          dataType: 'DECIMAL',
          unit: 'currency',
          aggregation: 'CALCULATED',
          granularity: 'Monthly',
          sourceTables: ['bronze.commercial_payment_fees'],
          calculation: { numerator: "SUM(fee_amount)", denominator: "COUNT(DISTINCT customer_id)" },
          businessDefinition: 'Average payment fee revenue per customer',
          benchmarks: { industryAverage: '$485/month', topQuartile: '$1,085/month', target: '$750/month' },
        },
        {
          id: 'PCM-REV-010',
          name: 'Same-Day ACH Fee Premium',
          description: 'Additional revenue from same-day ACH pricing',
          category: 'Revenue',
          subcategory: 'Premium Services',
          formula: "SUM(same_day_fee - standard_fee)",
          businessLogic: 'Sum of same-day ACH fee premiums',
          dataType: 'DECIMAL',
          unit: 'currency',
          aggregation: 'SUM',
          granularity: 'Monthly',
          sourceTables: ['bronze.commercial_payment_fees'],
          calculation: { sql: "SUM(CASE WHEN processing_type = 'same_day' THEN fee_amount - standard_fee ELSE 0 END)", filters: "payment_type = 'ACH'" },
          businessDefinition: 'Same-day ACH premium revenue',
          benchmarks: { industryAverage: '$18K/month', topQuartile: '$42K/month', target: '$28K/month' },
        },
        {
          id: 'PCM-REV-011',
          name: 'International Wire Fee Premium',
          description: 'Additional revenue from international wire transfers',
          category: 'Revenue',
          subcategory: 'Premium Services',
          formula: "SUM(intl_wire_fee - domestic_wire_fee)",
          businessLogic: 'Sum of international wire fee premiums',
          dataType: 'DECIMAL',
          unit: 'currency',
          aggregation: 'SUM',
          granularity: 'Monthly',
          sourceTables: ['bronze.commercial_wire_fees'],
          calculation: { sql: "SUM(CASE WHEN wire_type = 'international' THEN fee_amount - domestic_fee ELSE 0 END)" },
          businessDefinition: 'International wire premium revenue',
          benchmarks: { industryAverage: '$62K/month', topQuartile: '$145K/month', target: '$95K/month' },
        },
        {
          id: 'PCM-REV-012',
          name: 'Fee Revenue Growth Rate',
          description: 'Year-over-year growth in payment fee revenue',
          category: 'Revenue',
          subcategory: 'Growth',
          formula: "((CURRENT_YEAR - PRIOR_YEAR) / PRIOR_YEAR) * 100",
          businessLogic: 'YoY fee revenue growth',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Annual',
          sourceTables: ['bronze.commercial_payment_fees'],
          calculation: { sql: "((SUM(current.fee_amount) - SUM(prior.fee_amount)) / SUM(prior.fee_amount)) * 100" },
          businessDefinition: 'Year-over-year payment fee revenue growth',
          benchmarks: { industryAverage: '6.8%', topQuartile: '11.2%', target: '9.5%' },
        },
        {
          id: 'PCM-REV-013',
          name: 'Payment Product Revenue Mix',
          description: 'Revenue distribution across payment products (ACH/Wire/RTP)',
          category: 'Revenue',
          subcategory: 'Product Mix',
          formula: "SUM(fee) GROUP BY payment_type",
          businessLogic: 'Fee revenue by payment product',
          dataType: 'DECIMAL',
          unit: 'currency',
          aggregation: 'SUM',
          granularity: 'Monthly',
          sourceTables: ['bronze.commercial_payment_fees'],
          calculation: { sql: "SUM(fee_amount) GROUP BY payment_type" },
          businessDefinition: 'Payment fee revenue by product type',
          benchmarks: { industryAverage: 'ACH: 38%, Wire: 51%, RTP: 7%, Other: 4%', topQuartile: 'Balanced mix', target: 'ACH: 38%, Wire: 51%, RTP: 7%, Other: 4%' },
        },
      ],
    },
    {
      name: 'Payment Quality & Fraud Metrics',
      description: 'Commercial payment processing quality, fraud detection, and compliance',
      totalMetrics: 15,
      metrics: [
        {
          id: 'PCM-QUAL-001',
          name: 'Payment Error Rate',
          description: 'Percentage of commercial payments with processing errors',
          category: 'Quality',
          subcategory: 'Accuracy',
          formula: "(COUNT(errors) / COUNT(total_payments)) * 100",
          businessLogic: 'Error payments / total payments',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Daily',
          sourceTables: ['bronze.commercial_payments'],
          calculation: { numerator: "COUNT(WHERE has_error = true)", denominator: "COUNT(transaction_id)", multiplier: 100 },
          businessDefinition: 'Commercial payment processing accuracy',
          benchmarks: { industryAverage: '0.35%', topQuartile: '0.15%', target: '0.25%' },
        },
        {
          id: 'PCM-QUAL-002',
          name: 'Payment Success Rate',
          description: 'Percentage of payments completed successfully',
          category: 'Quality',
          subcategory: 'Completion',
          formula: "(COUNT(completed) / COUNT(total_payments)) * 100",
          businessLogic: 'Completed payments / total payments',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Daily',
          sourceTables: ['bronze.commercial_payments'],
          calculation: { numerator: "COUNT(WHERE status = 'completed')", denominator: "COUNT(transaction_id)", multiplier: 100 },
          businessDefinition: 'Commercial payment completion rate',
          benchmarks: { industryAverage: '98.2%', topQuartile: '99.5%', target: '99.0%' },
        },
        {
          id: 'PCM-QUAL-003',
          name: 'SLA Compliance Rate',
          description: 'Percentage of payments meeting service level agreement timelines',
          category: 'Quality',
          subcategory: 'Timeliness',
          formula: "(COUNT(sla_met) / COUNT(total_payments)) * 100",
          businessLogic: 'SLA compliant payments / total payments',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Daily',
          sourceTables: ['bronze.commercial_payment_sla_tracking'],
          calculation: { numerator: "COUNT(WHERE sla_met = true)", denominator: "COUNT(transaction_id)", multiplier: 100 },
          businessDefinition: 'Payment SLA compliance rate',
          benchmarks: { industryAverage: '96.5%', topQuartile: '99.2%', target: '98.0%' },
        },
        {
          id: 'PCM-QUAL-004',
          name: 'Payment Reconciliation Rate',
          description: 'Percentage of payments reconciled with general ledger',
          category: 'Quality',
          subcategory: 'Reconciliation',
          formula: "(COUNT(reconciled) / COUNT(total_payments)) * 100",
          businessLogic: 'Reconciled payments / total payments',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Daily',
          sourceTables: ['bronze.commercial_payment_reconciliation'],
          calculation: { numerator: "COUNT(WHERE reconciliation_status = 'matched')", denominator: "COUNT(transaction_id)", multiplier: 100 },
          businessDefinition: 'Payment GL reconciliation rate',
          benchmarks: { industryAverage: '99.1%', topQuartile: '99.8%', target: '99.5%' },
        },
        {
          id: 'PCM-QUAL-005',
          name: 'Payment Exception Count',
          description: 'Number of payment transactions requiring manual intervention',
          category: 'Quality',
          subcategory: 'Exceptions',
          formula: "COUNT(exception_id)",
          businessLogic: 'Count of payment exceptions',
          dataType: 'INTEGER',
          unit: 'count',
          aggregation: 'COUNT',
          granularity: 'Daily',
          sourceTables: ['bronze.commercial_payment_approvals', 'bronze.commercial_positive_pay_exceptions'],
          calculation: { numerator: "COUNT(exception_id)" },
          businessDefinition: 'Payment exception volume',
          benchmarks: { industryAverage: '1,250/day', topQuartile: '850/day', target: '950/day' },
        },
        {
          id: 'PCM-FRAUD-001',
          name: 'Payment Fraud Alert Count',
          description: 'Number of fraud alerts generated for commercial payments',
          category: 'Fraud',
          subcategory: 'Detection',
          formula: "COUNT(fraud_alert_id)",
          businessLogic: 'Count of payment fraud alerts',
          dataType: 'INTEGER',
          unit: 'count',
          aggregation: 'COUNT',
          granularity: 'Daily',
          sourceTables: ['bronze.commercial_payment_fraud_alerts'],
          calculation: { numerator: "COUNT(alert_id)" },
          businessDefinition: 'Payment fraud alert volume',
          benchmarks: { industryAverage: '385/day', topQuartile: '280/day', target: '320/day' },
        },
        {
          id: 'PCM-FRAUD-002',
          name: 'Fraud Detection Rate',
          description: 'Percentage of fraudulent payments detected before completion',
          category: 'Fraud',
          subcategory: 'Detection',
          formula: "(COUNT(detected_fraud) / COUNT(total_fraud)) * 100",
          businessLogic: 'Detected fraud / total fraud',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Monthly',
          sourceTables: ['bronze.commercial_payment_fraud_alerts'],
          calculation: { numerator: "COUNT(WHERE fraud_detected = true AND blocked = true)", denominator: "COUNT(WHERE is_fraud = true)", multiplier: 100 },
          businessDefinition: 'Payment fraud detection effectiveness',
          benchmarks: { industryAverage: '82.5%', topQuartile: '94.2%', target: '90.0%' },
        },
        {
          id: 'PCM-FRAUD-003',
          name: 'Fraud Loss Amount',
          description: 'Total dollar value of confirmed fraudulent payments',
          category: 'Fraud',
          subcategory: 'Loss',
          formula: "SUM(fraud_loss)",
          businessLogic: 'Sum of fraud loss amounts',
          dataType: 'DECIMAL',
          unit: 'currency',
          aggregation: 'SUM',
          granularity: 'Monthly',
          sourceTables: ['bronze.commercial_payment_fraud_alerts'],
          calculation: { numerator: "SUM(transaction_amount)", filters: "is_confirmed_fraud = true AND blocked = false" },
          businessDefinition: 'Commercial payment fraud losses',
          benchmarks: { industryAverage: '$285K/month', topQuartile: '$125K/month', target: '$180K/month' },
        },
        {
          id: 'PCM-FRAUD-004',
          name: 'False Positive Rate',
          description: 'Percentage of fraud alerts that were false positives',
          category: 'Fraud',
          subcategory: 'Accuracy',
          formula: "(COUNT(false_positives) / COUNT(total_alerts)) * 100",
          businessLogic: 'False positive alerts / total alerts',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Monthly',
          sourceTables: ['bronze.commercial_payment_fraud_alerts'],
          calculation: { numerator: "COUNT(WHERE is_fraud = false)", denominator: "COUNT(alert_id)", multiplier: 100 },
          businessDefinition: 'Fraud alert false positive rate',
          benchmarks: { industryAverage: '24.5%', topQuartile: '12.8%', target: '15.0%' },
        },
        {
          id: 'PCM-FRAUD-005',
          name: 'Fraud Prevention Rate',
          description: 'Percentage of payment volume protected from fraud',
          category: 'Fraud',
          subcategory: 'Prevention',
          formula: "(SUM(protected_volume) / SUM(total_volume)) * 100",
          businessLogic: 'Protected volume / total volume',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Monthly',
          sourceTables: ['bronze.commercial_payment_fraud_alerts'],
          calculation: { numerator: "SUM(CASE WHEN fraud_detected = true AND blocked = true THEN amount ELSE 0 END)", denominator: "SUM(amount)", multiplier: 100 },
          businessDefinition: 'Payment fraud prevention effectiveness',
          benchmarks: { industryAverage: '99.97%', topQuartile: '99.99%', target: '99.98%' },
        },
        {
          id: 'PCM-FRAUD-006',
          name: 'Positive Pay Hit Rate',
          description: 'Percentage of positive pay exceptions that were actual fraud',
          category: 'Fraud',
          subcategory: 'Positive Pay',
          formula: "(COUNT(confirmed_fraud) / COUNT(total_exceptions)) * 100",
          businessLogic: 'Confirmed fraud / total exceptions',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Monthly',
          sourceTables: ['bronze.commercial_positive_pay_exceptions'],
          calculation: { numerator: "COUNT(WHERE is_fraud = true)", denominator: "COUNT(exception_id)", multiplier: 100 },
          businessDefinition: 'Positive pay fraud detection accuracy',
          benchmarks: { industryAverage: '6.8%', topQuartile: '8.5%', target: '7.5%' },
        },
        {
          id: 'PCM-OFAC-001',
          name: 'OFAC Screening Count',
          description: 'Number of payment OFAC screening checks performed',
          category: 'Compliance',
          subcategory: 'OFAC',
          formula: "COUNT(screening_id)",
          businessLogic: 'Count of OFAC screenings',
          dataType: 'INTEGER',
          unit: 'count',
          aggregation: 'COUNT',
          granularity: 'Daily',
          sourceTables: ['bronze.commercial_ofac_screening'],
          calculation: { numerator: "COUNT(screening_id)" },
          businessDefinition: 'Payment OFAC screening volume',
          benchmarks: { industryAverage: '195K/day', topQuartile: '430K/day', target: '290K/day' },
        },
        {
          id: 'PCM-OFAC-002',
          name: 'OFAC Match Count',
          description: 'Number of OFAC screening matches requiring review',
          category: 'Compliance',
          subcategory: 'OFAC',
          formula: "COUNT(match_id)",
          businessLogic: 'Count of OFAC matches',
          dataType: 'INTEGER',
          unit: 'count',
          aggregation: 'COUNT',
          granularity: 'Daily',
          sourceTables: ['bronze.commercial_ofac_screening'],
          calculation: { numerator: "COUNT(match_id)", filters: "has_match = true" },
          businessDefinition: 'OFAC screening match volume',
          benchmarks: { industryAverage: '485/day', topQuartile: '320/day', target: '380/day' },
        },
        {
          id: 'PCM-OFAC-003',
          name: 'OFAC False Positive Rate',
          description: 'Percentage of OFAC matches that were false positives',
          category: 'Compliance',
          subcategory: 'OFAC',
          formula: "(COUNT(false_positives) / COUNT(total_matches)) * 100",
          businessLogic: 'False positive matches / total matches',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Monthly',
          sourceTables: ['bronze.commercial_ofac_screening'],
          calculation: { numerator: "COUNT(WHERE is_false_positive = true)", denominator: "COUNT(WHERE has_match = true)", multiplier: 100 },
          businessDefinition: 'OFAC screening false positive rate',
          benchmarks: { industryAverage: '96.8%', topQuartile: '95.2%', target: '95.8%' },
        },
        {
          id: 'PCM-OFAC-004',
          name: 'OFAC Screening Processing Time',
          description: 'Average time to complete OFAC screening (seconds)',
          category: 'Compliance',
          subcategory: 'OFAC',
          formula: "AVG(completion_time - initiation_time)",
          businessLogic: 'Average OFAC screening duration',
          dataType: 'DECIMAL',
          unit: 'seconds',
          aggregation: 'AVG',
          granularity: 'Daily',
          sourceTables: ['bronze.commercial_ofac_screening'],
          calculation: { sql: "AVG(EXTRACT(EPOCH FROM (completion_timestamp - initiation_timestamp)))" },
          businessDefinition: 'OFAC screening processing time',
          benchmarks: { industryAverage: '2.8 sec', topQuartile: '1.5 sec', target: '2.0 sec' },
        },
      ],
    },
  ],
};
