/**
 * RISK-COMMERCIAL METRICS CATALOG
 * Commercial banking enterprise risk management metrics
 */

export const riskCommercialMetricsCatalog = {
  description: 'Commercial banking credit risk, market risk, operational risk, and enterprise risk metrics',
  totalMetrics: 50,
  
  categories: [
    {
      name: 'Credit Risk Metrics',
      description: 'Portfolio credit risk measurement and monitoring',
      totalMetrics: 15,
      metrics: [
        {
          id: 'RCM-CR-001',
          name: 'Expected Loss',
          description: 'Total expected credit loss across commercial portfolio',
          category: 'Credit Risk',
          subcategory: 'Expected Loss',
          formula: "SUM(PD * LGD * EAD)",
          businessLogic: 'Probability of Default * Loss Given Default * Exposure at Default',
          dataType: 'DECIMAL',
          unit: 'currency',
          aggregation: 'CALCULATED',
          granularity: 'Quarterly',
          sourceTables: ['silver.commercial_credit_models'],
          calculation: { sql: "SUM(pd * lgd * ead / 10000)" },
          businessDefinition: 'Expected credit losses',
          benchmarks: { industryAverage: '$52M', topQuartile: '$38M', target: '$45M' },
        },
        {
          id: 'RCM-CR-002',
          name: 'Unexpected Loss (Economic Capital)',
          description: 'Economic capital for unexpected losses',
          category: 'Credit Risk',
          subcategory: 'Economic Capital',
          formula: "SQRT(SUM((EAD * LGD * SQRT(PD))^2 * correlation))",
          businessLogic: 'VaR-based unexpected loss calculation',
          dataType: 'DECIMAL',
          unit: 'currency',
          aggregation: 'CALCULATED',
          granularity: 'Quarterly',
          sourceTables: ['silver.commercial_credit_models'],
          calculation: { sql: "credit_var_99_9_percentile" },
          businessDefinition: 'Unexpected loss capital requirement',
          benchmarks: { industryAverage: '$285M', topQuartile: '$220M', target: '$250M' },
        },
        {
          id: 'RCM-CR-003',
          name: 'Credit VaR (99.9%)',
          description: '99.9th percentile credit value at risk',
          category: 'Credit Risk',
          subcategory: 'VaR',
          formula: "quantile_0.999(credit_loss_distribution)",
          businessLogic: 'Monte Carlo credit VaR',
          dataType: 'DECIMAL',
          unit: 'currency',
          aggregation: 'CALCULATED',
          granularity: 'Monthly',
          sourceTables: ['silver.commercial_var_calculations'],
          calculation: { sql: "credit_var_99_9" },
          businessDefinition: '1-year 99.9% credit VaR',
          benchmarks: { industryAverage: '$295M', topQuartile: '$225M', target: '$260M' },
        },
        {
          id: 'RCM-CR-004',
          name: 'Concentration Risk Score',
          description: 'Herfindahl-Hirschman Index for credit concentration',
          category: 'Credit Risk',
          subcategory: 'Concentration',
          formula: "SUM((exposure_i / total_exposure)^2)",
          businessLogic: 'HHI concentration index',
          dataType: 'DECIMAL',
          unit: 'index',
          aggregation: 'CALCULATED',
          granularity: 'Quarterly',
          sourceTables: ['silver.commercial_concentration_analysis'],
          calculation: { sql: "SUM(POW(exposure_pct, 2))" },
          businessDefinition: 'Portfolio concentration risk',
          benchmarks: { industryAverage: '0.085', topQuartile: '0.065', target: '0.075', threshold: '0.10' },
        },
        {
          id: 'RCM-CR-005',
          name: 'Probability of Default - 1 Year',
          description: 'Weighted average 1-year PD',
          category: 'Credit Risk',
          subcategory: 'Default Probability',
          formula: "SUM(PD * exposure) / SUM(exposure)",
          businessLogic: 'Exposure-weighted PD',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Monthly',
          sourceTables: ['silver.commercial_credit_models'],
          calculation: { sql: "SUM(pd_1yr * exposure) / SUM(exposure) * 100" },
          businessDefinition: '1-year portfolio PD',
          benchmarks: { industryAverage: '2.65%', topQuartile: '2.05%', target: '2.35%' },
        },
        {
          id: 'RCM-CR-006',
          name: 'Loss Given Default Rate',
          description: 'Weighted average loss given default',
          category: 'Credit Risk',
          subcategory: 'Loss Severity',
          formula: "SUM(LGD * exposure) / SUM(exposure)",
          businessLogic: 'Exposure-weighted LGD',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Quarterly',
          sourceTables: ['silver.commercial_credit_models'],
          calculation: { sql: "SUM(lgd * exposure) / SUM(exposure) * 100" },
          businessDefinition: 'Portfolio loss severity',
          benchmarks: { industryAverage: '40%', topQuartile: '34%', target: '37%' },
        },
        {
          id: 'RCM-CR-007',
          name: 'Risk-Weighted Assets',
          description: 'Total credit risk-weighted assets',
          category: 'Credit Risk',
          subcategory: 'RWA',
          formula: "SUM(exposure * risk_weight)",
          businessLogic: 'Basel III RWA calculation',
          dataType: 'DECIMAL',
          unit: 'currency',
          aggregation: 'CALCULATED',
          granularity: 'Quarterly',
          sourceTables: ['silver.commercial_rwa_calculation'],
          calculation: { sql: "SUM(exposure * risk_weight_pct / 100)" },
          businessDefinition: 'Credit RWA',
          benchmarks: { industryAverage: '$3.8B', topQuartile: '$5.2B', target: '$4.5B' },
        },
        {
          id: 'RCM-CR-008',
          name: 'Leverage Exposure',
          description: 'Total leverage ratio exposure',
          category: 'Credit Risk',
          subcategory: 'Leverage',
          formula: "SUM(on_balance_sheet + off_balance_sheet_conversion)",
          businessLogic: 'Leverage exposure calculation',
          dataType: 'DECIMAL',
          unit: 'currency',
          aggregation: 'SUM',
          granularity: 'Quarterly',
          sourceTables: ['silver.commercial_leverage_exposure'],
          calculation: { sql: "SUM(total_leverage_exposure)" },
          businessDefinition: 'Basel III leverage exposure',
          benchmarks: { industryAverage: '$5.2B', topQuartile: '$7.5B', target: '$6.2B' },
        },
        {
          id: 'RCM-CR-009',
          name: 'Credit Migration Rate - Downgrades',
          description: 'Percentage of exposures downgraded in rating',
          category: 'Credit Risk',
          subcategory: 'Migration',
          formula: "(SUM(downgraded_exposure) / SUM(total_exposure)) * 100",
          businessLogic: 'Downgraded / total exposures',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Quarterly',
          sourceTables: ['silver.commercial_credit_migrations'],
          calculation: { numerator: "SUM(WHERE rating_change < 0)", denominator: "SUM(exposure)", multiplier: 100 },
          businessDefinition: 'Credit quality deterioration',
          benchmarks: { industryAverage: '6.8%', topQuartile: '4.2%', target: '5.5%' },
        },
        {
          id: 'RCM-CR-010',
          name: 'Stress Test Loss - Severe Recession',
          description: 'Projected losses under severe recession scenario',
          category: 'Credit Risk',
          subcategory: 'Stress Testing',
          formula: "SUM(stressed_losses)",
          businessLogic: 'Severe scenario loss projection',
          dataType: 'DECIMAL',
          unit: 'currency',
          aggregation: 'SUM',
          granularity: 'Annual',
          sourceTables: ['silver.commercial_stress_tests'],
          calculation: { numerator: "SUM(severe_scenario_losses)" },
          businessDefinition: 'Stress test credit losses',
          benchmarks: { industryAverage: '$285M', topQuartile: '$195M', target: '$240M' },
        },
        {
          id: 'RCM-CR-011',
          name: 'Counterparty Credit Risk',
          description: 'Credit value adjustment for derivative counterparties',
          category: 'Credit Risk',
          subcategory: 'Counterparty Risk',
          formula: "SUM(CVA)",
          businessLogic: 'Credit valuation adjustment',
          dataType: 'DECIMAL',
          unit: 'currency',
          aggregation: 'SUM',
          granularity: 'Monthly',
          sourceTables: ['silver.commercial_counterparty_risk'],
          calculation: { numerator: "SUM(cva_amount)" },
          businessDefinition: 'Derivative counterparty credit risk',
          benchmarks: { industryAverage: '$8.5M', topQuartile: '$5.2M', target: '$6.8M' },
        },
        {
          id: 'RCM-CR-012',
          name: 'Wrong-Way Risk Exposure',
          description: 'Exposures with wrong-way risk characteristics',
          category: 'Credit Risk',
          subcategory: 'Counterparty Risk',
          formula: "SUM(exposure WHERE has_wrong_way_risk = true)",
          businessLogic: 'Wrong-way risk exposures',
          dataType: 'DECIMAL',
          unit: 'currency',
          aggregation: 'SUM',
          granularity: 'Quarterly',
          sourceTables: ['silver.commercial_counterparty_risk'],
          calculation: { numerator: "SUM(exposure)", filters: "wrong_way_risk_flag = true" },
          businessDefinition: 'Correlated credit exposure',
          benchmarks: { industryAverage: '$125M', topQuartile: '$65M', target: '$95M' },
        },
        {
          id: 'RCM-CR-013',
          name: 'Industry Concentration - Top 3',
          description: 'Top 3 industries as % of total exposure',
          category: 'Credit Risk',
          subcategory: 'Concentration',
          formula: "(SUM(top_3_industries) / SUM(total_exposure)) * 100",
          businessLogic: 'Top 3 industry concentration',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Quarterly',
          sourceTables: ['silver.commercial_industry_concentration'],
          calculation: { sql: "SUM(top_3_exposure) / SUM(total_exposure) * 100" },
          businessDefinition: 'Industry diversification',
          benchmarks: { industryAverage: '42%', topQuartile: '35%', target: '38%' },
        },
        {
          id: 'RCM-CR-014',
          name: 'Geographic Concentration Risk',
          description: 'Herfindahl index for geographic concentration',
          category: 'Credit Risk',
          subcategory: 'Geographic Risk',
          formula: "SUM((geo_exposure_i / total_exposure)^2)",
          businessLogic: 'Geographic HHI',
          dataType: 'DECIMAL',
          unit: 'index',
          aggregation: 'CALCULATED',
          granularity: 'Quarterly',
          sourceTables: ['silver.commercial_geographic_concentration'],
          calculation: { sql: "SUM(POW(geographic_exposure_pct, 2))" },
          businessDefinition: 'Geographic diversification',
          benchmarks: { industryAverage: '0.095', topQuartile: '0.075', target: '0.085' },
        },
        {
          id: 'RCM-CR-015',
          name: 'CECL Reserve Adequacy',
          description: 'CECL allowance as % of expected losses',
          category: 'Credit Risk',
          subcategory: 'Reserves',
          formula: "(CECL_allowance / expected_losses) * 100",
          businessLogic: 'CECL coverage ratio',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Quarterly',
          sourceTables: ['silver.commercial_cecl_reserves'],
          calculation: { numerator: "SUM(cecl_allowance)", denominator: "SUM(lifetime_expected_losses)", multiplier: 100 },
          businessDefinition: 'CECL reserve coverage',
          benchmarks: { industryAverage: '115%', topQuartile: '125%', target: '120%' },
        },
      ],
    },
    {
      name: 'Market Risk Metrics',
      description: 'Interest rate, FX, and trading book market risk',
      totalMetrics: 12,
      metrics: [
        {
          id: 'RCM-MR-001',
          name: 'Interest Rate VaR',
          description: '99% 1-day interest rate value at risk',
          category: 'Market Risk',
          subcategory: 'Interest Rate Risk',
          formula: "quantile_0.99(ir_pnl_distribution)",
          businessLogic: '1-day 99% IR VaR',
          dataType: 'DECIMAL',
          unit: 'currency',
          aggregation: 'CALCULATED',
          granularity: 'Daily',
          sourceTables: ['silver.commercial_market_risk_var'],
          calculation: { sql: "interest_rate_var_99" },
          businessDefinition: 'Interest rate VaR',
          benchmarks: { industryAverage: '$2.8M', topQuartile: '$1.9M', target: '$2.3M' },
        },
        {
          id: 'RCM-MR-002',
          name: 'FX VaR',
          description: '99% 1-day foreign exchange value at risk',
          category: 'Market Risk',
          subcategory: 'FX Risk',
          formula: "quantile_0.99(fx_pnl_distribution)",
          businessLogic: '1-day 99% FX VaR',
          dataType: 'DECIMAL',
          unit: 'currency',
          aggregation: 'CALCULATED',
          granularity: 'Daily',
          sourceTables: ['silver.commercial_market_risk_var'],
          calculation: { sql: "fx_var_99" },
          businessDefinition: 'Foreign exchange VaR',
          benchmarks: { industryAverage: '$1.85M', topQuartile: '$1.25M', target: '$1.55M' },
        },
        {
          id: 'RCM-MR-003',
          name: 'Total Market Risk VaR',
          description: 'Aggregated market risk VaR (IR + FX + Commodity)',
          category: 'Market Risk',
          subcategory: 'Total VaR',
          formula: "SQRT(SUM(var_i^2) + 2*SUM(correlation*var_i*var_j))",
          businessLogic: 'Diversified total VaR',
          dataType: 'DECIMAL',
          unit: 'currency',
          aggregation: 'CALCULATED',
          granularity: 'Daily',
          sourceTables: ['silver.commercial_market_risk_var'],
          calculation: { sql: "total_market_var_99" },
          businessDefinition: 'Aggregated market VaR',
          benchmarks: { industryAverage: '$4.2M', topQuartile: '$2.9M', target: '$3.5M' },
        },
        {
          id: 'RCM-MR-004',
          name: 'Earnings at Risk (EaR)',
          description: 'Earnings impact from 200bp parallel rate shock',
          category: 'Market Risk',
          subcategory: 'Earnings Risk',
          formula: "net_interest_income_change(+/-200bp)",
          businessLogic: 'NII sensitivity to rate shock',
          dataType: 'DECIMAL',
          unit: 'currency',
          aggregation: 'CALCULATED',
          granularity: 'Quarterly',
          sourceTables: ['silver.commercial_interest_rate_risk'],
          calculation: { sql: "nii_200bp_shock_impact" },
          businessDefinition: '1-year NII at risk',
          benchmarks: { industryAverage: '$18.5M', topQuartile: '$12.5M', target: '$15.0M' },
        },
        {
          id: 'RCM-MR-005',
          name: 'Economic Value of Equity (EVE) Sensitivity',
          description: 'EVE impact from 200bp parallel rate shock',
          category: 'Market Risk',
          subcategory: 'EVE Risk',
          formula: "present_value_change(+/-200bp)",
          businessLogic: 'EVE sensitivity to rate shock',
          dataType: 'DECIMAL',
          unit: 'currency',
          aggregation: 'CALCULATED',
          granularity: 'Quarterly',
          sourceTables: ['silver.commercial_interest_rate_risk'],
          calculation: { sql: "eve_200bp_shock_impact" },
          businessDefinition: 'Economic value at risk',
          benchmarks: { industryAverage: '$85M', topQuartile: '$55M', target: '$70M' },
        },
        {
          id: 'RCM-MR-006',
          name: 'Duration Gap',
          description: 'Asset duration minus liability duration',
          category: 'Market Risk',
          subcategory: 'Interest Rate Risk',
          formula: "duration_assets - duration_liabilities",
          businessLogic: 'Duration mismatch',
          dataType: 'DECIMAL',
          unit: 'years',
          aggregation: 'CALCULATED',
          granularity: 'Monthly',
          sourceTables: ['silver.commercial_interest_rate_risk'],
          calculation: { sql: "asset_duration - liability_duration" },
          businessDefinition: 'ALM duration gap',
          benchmarks: { industryAverage: '1.2 years', topQuartile: '0.8 years', target: '1.0 years' },
        },
        {
          id: 'RCM-MR-007',
          name: 'Net Open FX Position',
          description: 'Net unhedged foreign exchange exposure',
          category: 'Market Risk',
          subcategory: 'FX Risk',
          formula: "SUM(long_positions - short_positions)",
          businessLogic: 'Net FX exposure',
          dataType: 'DECIMAL',
          unit: 'currency',
          aggregation: 'CALCULATED',
          granularity: 'Daily',
          sourceTables: ['bronze.commercial_fx_positions'],
          calculation: { sql: "SUM(long_exposure - short_exposure)" },
          businessDefinition: 'Unhedged FX exposure',
          benchmarks: { industryAverage: '$28M', topQuartile: '$15M', target: '$20M' },
        },
        {
          id: 'RCM-MR-008',
          name: 'VaR Backtesting Exceptions',
          description: 'Number of VaR model exceptions (actual loss > VaR)',
          category: 'Market Risk',
          subcategory: 'Model Validation',
          formula: "COUNT(days WHERE actual_loss > var_estimate)",
          businessLogic: 'VaR exception count',
          dataType: 'INTEGER',
          unit: 'count',
          aggregation: 'COUNT',
          granularity: 'Annual',
          sourceTables: ['silver.commercial_var_backtesting'],
          calculation: { numerator: "COUNT(WHERE actual_pnl < var_estimate)" },
          businessDefinition: 'VaR model accuracy',
          benchmarks: { industryAverage: '4 exceptions/year', topQuartile: '2 exceptions/year', target: '3 exceptions/year', regulatory_threshold: '10 exceptions/year' },
        },
        {
          id: 'RCM-MR-009',
          name: 'Stressed VaR',
          description: 'VaR calculated using stressed historical period',
          category: 'Market Risk',
          subcategory: 'Stressed VaR',
          formula: "quantile_0.99(stressed_pnl_distribution)",
          businessLogic: 'Stressed scenario VaR',
          dataType: 'DECIMAL',
          unit: 'currency',
          aggregation: 'CALCULATED',
          granularity: 'Weekly',
          sourceTables: ['silver.commercial_market_risk_var'],
          calculation: { sql: "stressed_var_99" },
          businessDefinition: 'Crisis period VaR',
          benchmarks: { industryAverage: '$8.5M', topQuartile: '$5.9M', target: '$7.2M' },
        },
        {
          id: 'RCM-MR-010',
          name: 'Commodity Price Risk',
          description: 'VaR from commodity price exposures',
          category: 'Market Risk',
          subcategory: 'Commodity Risk',
          formula: "quantile_0.99(commodity_pnl_distribution)",
          businessLogic: 'Commodity VaR',
          dataType: 'DECIMAL',
          unit: 'currency',
          aggregation: 'CALCULATED',
          granularity: 'Daily',
          sourceTables: ['silver.commercial_market_risk_var'],
          calculation: { sql: "commodity_var_99" },
          businessDefinition: 'Commodity price VaR',
          benchmarks: { industryAverage: '$1.25M', topQuartile: '$0.85M', target: '$1.05M' },
        },
        {
          id: 'RCM-MR-011',
          name: 'Basis Risk',
          description: 'Risk from imperfect hedging correlations',
          category: 'Market Risk',
          subcategory: 'Basis Risk',
          formula: "STDDEV(hedge_effectiveness)",
          businessLogic: 'Hedge basis volatility',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'STDDEV',
          granularity: 'Monthly',
          sourceTables: ['silver.commercial_hedge_effectiveness'],
          calculation: { sql: "STDDEV((hedge_pnl + exposure_pnl) / exposure_pnl) * 100" },
          businessDefinition: 'Hedging imperfection risk',
          benchmarks: { industryAverage: '8.5%', topQuartile: '5.2%', target: '6.8%' },
        },
        {
          id: 'RCM-MR-012',
          name: 'Option Vega Exposure',
          description: 'Sensitivity to volatility changes',
          category: 'Market Risk',
          subcategory: 'Greeks',
          formula: "SUM(option_vega)",
          businessLogic: 'Total volatility exposure',
          dataType: 'DECIMAL',
          unit: 'currency',
          aggregation: 'SUM',
          granularity: 'Daily',
          sourceTables: ['silver.commercial_option_greeks'],
          calculation: { numerator: "SUM(vega)" },
          businessDefinition: 'Implied volatility risk',
          benchmarks: { industryAverage: '$850K', topQuartile: '$520K', target: '$680K' },
        },
      ],
    },
    {
      name: 'Operational Risk Metrics',
      description: 'Operational loss events and control effectiveness',
      totalMetrics: 11,
      metrics: [
        {
          id: 'RCM-OR-001',
          name: 'Operational Loss Events',
          description: 'Number of operational risk loss events',
          category: 'Operational Risk',
          subcategory: 'Loss Events',
          formula: "COUNT(loss_event_id WHERE amount > threshold)",
          businessLogic: 'Count of loss events',
          dataType: 'INTEGER',
          unit: 'count',
          aggregation: 'COUNT',
          granularity: 'Quarterly',
          sourceTables: ['bronze.commercial_operational_losses'],
          calculation: { numerator: "COUNT(event_id)", filters: "loss_amount > 10000" },
          businessDefinition: 'Operational loss frequency',
          benchmarks: { industryAverage: '28/quarter', topQuartile: '18/quarter', target: '22/quarter' },
        },
        {
          id: 'RCM-OR-002',
          name: 'Total Operational Losses',
          description: 'Total dollar amount of operational losses',
          category: 'Operational Risk',
          subcategory: 'Loss Severity',
          formula: "SUM(loss_amount)",
          businessLogic: 'Total operational losses',
          dataType: 'DECIMAL',
          unit: 'currency',
          aggregation: 'SUM',
          granularity: 'Quarterly',
          sourceTables: ['bronze.commercial_operational_losses'],
          calculation: { numerator: "SUM(loss_amount)" },
          businessDefinition: 'Operational loss severity',
          benchmarks: { industryAverage: '$2.8M/qtr', topQuartile: '$1.5M/qtr', target: '$2.1M/qtr' },
        },
        {
          id: 'RCM-OR-003',
          name: 'Operational VaR',
          description: '99.9% operational risk value at risk',
          category: 'Operational Risk',
          subcategory: 'Capital',
          formula: "quantile_0.999(operational_loss_distribution)",
          businessLogic: 'Advanced Measurement Approach VaR',
          dataType: 'DECIMAL',
          unit: 'currency',
          aggregation: 'CALCULATED',
          granularity: 'Annual',
          sourceTables: ['silver.commercial_operational_var'],
          calculation: { sql: "operational_var_99_9" },
          businessDefinition: 'Operational risk capital',
          benchmarks: { industryAverage: '$85M', topQuartile: '$62M', target: '$73M' },
        },
        {
          id: 'RCM-OR-004',
          name: 'Fraud Loss Amount',
          description: 'Total losses from fraud events',
          category: 'Operational Risk',
          subcategory: 'Fraud',
          formula: "SUM(loss_amount WHERE event_type = 'fraud')",
          businessLogic: 'Fraud-related losses',
          dataType: 'DECIMAL',
          unit: 'currency',
          aggregation: 'SUM',
          granularity: 'Quarterly',
          sourceTables: ['bronze.commercial_operational_losses'],
          calculation: { numerator: "SUM(loss_amount)", filters: "event_category = 'external_fraud' OR event_category = 'internal_fraud'" },
          businessDefinition: 'Fraud loss severity',
          benchmarks: { industryAverage: '$850K/qtr', topQuartile: '$420K/qtr', target: '$620K/qtr' },
        },
        {
          id: 'RCM-OR-005',
          name: 'System Downtime',
          description: 'Hours of critical system downtime',
          category: 'Operational Risk',
          subcategory: 'Technology',
          formula: "SUM(downtime_hours)",
          businessLogic: 'Total system downtime',
          dataType: 'DECIMAL',
          unit: 'hours',
          aggregation: 'SUM',
          granularity: 'Monthly',
          sourceTables: ['bronze.commercial_system_availability'],
          calculation: { numerator: "SUM(downtime_duration_hours)", filters: "system_criticality = 'critical'" },
          businessDefinition: 'Technology availability',
          benchmarks: { industryAverage: '4.5 hrs/month', topQuartile: '2.0 hrs/month', target: '3.0 hrs/month' },
        },
        {
          id: 'RCM-OR-006',
          name: 'Control Deficiency Count',
          description: 'Number of identified control deficiencies',
          category: 'Operational Risk',
          subcategory: 'Controls',
          formula: "COUNT(deficiency_id WHERE severity IN ('medium', 'high'))",
          businessLogic: 'Count of control weaknesses',
          dataType: 'INTEGER',
          unit: 'count',
          aggregation: 'COUNT',
          granularity: 'Quarterly',
          sourceTables: ['bronze.commercial_control_testing'],
          calculation: { numerator: "COUNT(deficiency_id)", filters: "severity >= 'medium'" },
          businessDefinition: 'Control effectiveness',
          benchmarks: { industryAverage: '18/quarter', topQuartile: '10/quarter', target: '14/quarter' },
        },
        {
          id: 'RCM-OR-007',
          name: 'Cyber Security Incidents',
          description: 'Number of cyber security incidents',
          category: 'Operational Risk',
          subcategory: 'Cyber Risk',
          formula: "COUNT(incident_id WHERE incident_type = 'cyber')",
          businessLogic: 'Cyber incident count',
          dataType: 'INTEGER',
          unit: 'count',
          aggregation: 'COUNT',
          granularity: 'Quarterly',
          sourceTables: ['bronze.commercial_cyber_incidents'],
          calculation: { numerator: "COUNT(incident_id)" },
          businessDefinition: 'Cyber threat frequency',
          benchmarks: { industryAverage: '12/quarter', topQuartile: '6/quarter', target: '9/quarter' },
        },
        {
          id: 'RCM-OR-008',
          name: 'Data Breach Impact',
          description: 'Number of customer records impacted by breaches',
          category: 'Operational Risk',
          subcategory: 'Data Privacy',
          formula: "SUM(records_impacted)",
          businessLogic: 'Total records breached',
          dataType: 'INTEGER',
          unit: 'count',
          aggregation: 'SUM',
          granularity: 'Annual',
          sourceTables: ['bronze.commercial_data_breaches'],
          calculation: { numerator: "SUM(customer_records_affected)" },
          businessDefinition: 'Data breach severity',
          benchmarks: { industryAverage: '2,500/year', topQuartile: '500/year', target: '1,200/year' },
        },
        {
          id: 'RCM-OR-009',
          name: 'Business Continuity Test Success Rate',
          description: 'Percentage of BC tests passed successfully',
          category: 'Operational Risk',
          subcategory: 'Resilience',
          formula: "(COUNT(passed_tests) / COUNT(total_tests)) * 100",
          businessLogic: 'BC test success rate',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Annual',
          sourceTables: ['bronze.commercial_bc_testing'],
          calculation: { numerator: "COUNT(WHERE test_result = 'pass')", denominator: "COUNT(test_id)", multiplier: 100 },
          businessDefinition: 'BC preparedness',
          benchmarks: { industryAverage: '92%', topQuartile: '98%', target: '95%' },
        },
        {
          id: 'RCM-OR-010',
          name: 'Employee Turnover - Risk Functions',
          description: 'Annual turnover rate in risk management roles',
          category: 'Operational Risk',
          subcategory: 'People Risk',
          formula: "(COUNT(departed_employees) / AVG(total_employees)) * 100",
          businessLogic: 'Risk function turnover',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Annual',
          sourceTables: ['bronze.commercial_hr_data'],
          calculation: { numerator: "COUNT(WHERE status = 'departed')", denominator: "AVG(total_headcount)", multiplier: 100, filters: "department = 'risk_management'" },
          businessDefinition: 'Risk talent retention',
          benchmarks: { industryAverage: '15%', topQuartile: '8%', target: '11%' },
        },
        {
          id: 'RCM-OR-011',
          name: 'Model Risk Events',
          description: 'Number of model performance issues identified',
          category: 'Operational Risk',
          subcategory: 'Model Risk',
          formula: "COUNT(model_issue_id WHERE severity >= 'medium')",
          businessLogic: 'Model validation findings',
          dataType: 'INTEGER',
          unit: 'count',
          aggregation: 'COUNT',
          granularity: 'Annual',
          sourceTables: ['bronze.commercial_model_validation'],
          calculation: { numerator: "COUNT(finding_id)", filters: "severity >= 'medium'" },
          businessDefinition: 'Model risk governance',
          benchmarks: { industryAverage: '8/year', topQuartile: '4/year', target: '6/year' },
        },
      ],
    },
    {
      name: 'Liquidity Risk Metrics',
      description: 'Liquidity coverage and funding stability',
      totalMetrics: 12,
      metrics: [
        {
          id: 'RCM-LR-001',
          name: 'Liquidity Coverage Ratio',
          description: 'HQLA / 30-day net cash outflow',
          category: 'Liquidity Risk',
          subcategory: 'LCR',
          formula: "HQLA / net_cash_outflow_30_days",
          businessLogic: 'Basel III LCR',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Daily',
          sourceTables: ['silver.commercial_liquidity_metrics'],
          calculation: { numerator: "SUM(hqla)", denominator: "SUM(net_outflow_30d)" },
          businessDefinition: 'Short-term liquidity adequacy',
          benchmarks: { industryAverage: '135%', topQuartile: '155%', target: '145%', regulatory_minimum: '100%' },
        },
        {
          id: 'RCM-LR-002',
          name: 'Net Stable Funding Ratio',
          description: 'Available stable funding / required stable funding',
          category: 'Liquidity Risk',
          subcategory: 'NSFR',
          formula: "ASF / RSF",
          businessLogic: 'Basel III NSFR',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Monthly',
          sourceTables: ['silver.commercial_liquidity_metrics'],
          calculation: { numerator: "SUM(available_stable_funding)", denominator: "SUM(required_stable_funding)" },
          businessDefinition: 'Structural liquidity',
          benchmarks: { industryAverage: '122%', topQuartile: '135%', target: '128%', regulatory_minimum: '100%' },
        },
        {
          id: 'RCM-LR-003',
          name: 'Loan-to-Deposit Ratio',
          description: 'Total loans / total deposits',
          category: 'Liquidity Risk',
          subcategory: 'Funding',
          formula: "(total_loans / total_deposits) * 100",
          businessLogic: 'Loan-to-deposit ratio',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Daily',
          sourceTables: ['gold.fact_loan_portfolio', 'gold.fact_deposit_balances'],
          calculation: { numerator: "SUM(loan_balance)", denominator: "SUM(deposit_balance)", multiplier: 100 },
          businessDefinition: 'Deposit funding utilization',
          benchmarks: { industryAverage: '85%', topQuartile: '78%', target: '81%' },
        },
        {
          id: 'RCM-LR-004',
          name: 'Wholesale Funding Dependence',
          description: 'Wholesale funding / total funding',
          category: 'Liquidity Risk',
          subcategory: 'Funding',
          formula: "(wholesale_funding / total_funding) * 100",
          businessLogic: 'Wholesale funding ratio',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Monthly',
          sourceTables: ['silver.commercial_funding_mix'],
          calculation: { numerator: "SUM(wholesale_funding)", denominator: "SUM(total_funding)", multiplier: 100 },
          businessDefinition: 'Non-deposit funding dependence',
          benchmarks: { industryAverage: '28%', topQuartile: '18%', target: '23%' },
        },
        {
          id: 'RCM-LR-005',
          name: 'Cash Flow at Risk',
          description: 'Potential cash flow shortfall under stress',
          category: 'Liquidity Risk',
          subcategory: 'Stress Testing',
          formula: "baseline_cash_flow - stressed_cash_flow",
          businessLogic: 'Stress scenario cash gap',
          dataType: 'DECIMAL',
          unit: 'currency',
          aggregation: 'CALCULATED',
          granularity: 'Monthly',
          sourceTables: ['silver.commercial_liquidity_stress_tests'],
          calculation: { sql: "SUM(baseline_inflows - baseline_outflows) - SUM(stressed_inflows - stressed_outflows)" },
          businessDefinition: 'Liquidity stress vulnerability',
          benchmarks: { industryAverage: '$285M', topQuartile: '$185M', target: '$230M' },
        },
        {
          id: 'RCM-LR-006',
          name: 'Contingency Funding Plan Capacity',
          description: 'Available contingent funding sources',
          category: 'Liquidity Risk',
          subcategory: 'Contingency',
          formula: "SUM(contingent_funding_sources)",
          businessLogic: 'Total contingent liquidity',
          dataType: 'DECIMAL',
          unit: 'currency',
          aggregation: 'SUM',
          granularity: 'Monthly',
          sourceTables: ['silver.commercial_contingency_funding'],
          calculation: { numerator: "SUM(available_capacity)" },
          businessDefinition: 'Emergency funding access',
          benchmarks: { industryAverage: '$850M', topQuartile: '$1.2B', target: '$1.0B' },
        },
        {
          id: 'RCM-LR-007',
          name: 'Unencumbered Asset Ratio',
          description: 'Unencumbered assets / total assets',
          category: 'Liquidity Risk',
          subcategory: 'Collateral',
          formula: "(unencumbered_assets / total_assets) * 100",
          businessLogic: 'Free asset percentage',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Monthly',
          sourceTables: ['silver.commercial_asset_encumbrance'],
          calculation: { numerator: "SUM(unencumbered_value)", denominator: "SUM(total_asset_value)", multiplier: 100 },
          businessDefinition: 'Asset availability for funding',
          benchmarks: { industryAverage: '68%', topQuartile: '78%', target: '73%' },
        },
        {
          id: 'RCM-LR-008',
          name: 'Deposit Concentration - Top 10',
          description: 'Top 10 depositors as % of total deposits',
          category: 'Liquidity Risk',
          subcategory: 'Concentration',
          formula: "(SUM(top_10_deposits) / SUM(total_deposits)) * 100",
          businessLogic: 'Top 10 deposit concentration',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Monthly',
          sourceTables: ['silver.commercial_deposit_concentration'],
          calculation: { sql: "SUM(top_10_balances) / SUM(total_balance) * 100" },
          businessDefinition: 'Funding concentration risk',
          benchmarks: { industryAverage: '24%', topQuartile: '16%', target: '20%' },
        },
        {
          id: 'RCM-LR-009',
          name: 'Maturity Mismatch - 90 Day',
          description: 'Assets maturing < 90 days / Liabilities maturing < 90 days',
          category: 'Liquidity Risk',
          subcategory: 'Maturity Gap',
          formula: "assets_90d / liabilities_90d",
          businessLogic: '90-day maturity ratio',
          dataType: 'DECIMAL',
          unit: 'ratio',
          aggregation: 'CALCULATED',
          granularity: 'Monthly',
          sourceTables: ['silver.commercial_maturity_gap'],
          calculation: { numerator: "SUM(assets_maturing_90d)", denominator: "SUM(liabilities_maturing_90d)" },
          businessDefinition: 'Short-term maturity matching',
          benchmarks: { industryAverage: '0.85', topQuartile: '0.95', target: '0.90' },
        },
        {
          id: 'RCM-LR-010',
          name: 'Intraday Liquidity Peak Usage',
          description: 'Peak intraday liquidity usage',
          category: 'Liquidity Risk',
          subcategory: 'Intraday',
          formula: "MAX(intraday_liquidity_usage)",
          businessLogic: 'Peak intraday draw',
          dataType: 'DECIMAL',
          unit: 'currency',
          aggregation: 'MAX',
          granularity: 'Daily',
          sourceTables: ['bronze.commercial_intraday_liquidity'],
          calculation: { sql: "MAX(peak_usage_amount)" },
          businessDefinition: 'Payment system liquidity demand',
          benchmarks: { industryAverage: '$285M', topQuartile: '$195M', target: '$240M' },
        },
        {
          id: 'RCM-LR-011',
          name: 'Federal Funds Purchased',
          description: 'Average daily federal funds purchased',
          category: 'Liquidity Risk',
          subcategory: 'Short-term Funding',
          formula: "AVG(fed_funds_purchased)",
          businessLogic: 'Average fed funds borrowing',
          dataType: 'DECIMAL',
          unit: 'currency',
          aggregation: 'AVG',
          granularity: 'Monthly',
          sourceTables: ['bronze.commercial_fed_funds'],
          calculation: { numerator: "AVG(daily_fed_funds_purchased)" },
          businessDefinition: 'Overnight funding reliance',
          benchmarks: { industryAverage: '$85M', topQuartile: '$45M', target: '$65M' },
        },
        {
          id: 'RCM-LR-012',
          name: 'Repo Funding Volume',
          description: 'Total repurchase agreement funding',
          category: 'Liquidity Risk',
          subcategory: 'Secured Funding',
          formula: "SUM(repo_balance)",
          businessLogic: 'Total repo funding',
          dataType: 'DECIMAL',
          unit: 'currency',
          aggregation: 'SUM',
          granularity: 'Daily',
          sourceTables: ['bronze.commercial_repo_transactions'],
          calculation: { numerator: "SUM(repo_amount)" },
          businessDefinition: 'Secured short-term funding',
          benchmarks: { industryAverage: '$185M', topQuartile: '$95M', target: '$140M' },
        },
      ],
    },
  ],
};
