/**
 * TREASURY-COMMERCIAL METRICS CATALOG
 * Commercial treasury services, FX, hedging, and cash management metrics
 */

export const treasuryCommercialMetricsCatalog = {
  description: 'Commercial treasury services, foreign exchange, interest rate hedging, and cash management metrics',
  totalMetrics: 55,
  
  categories: [
    {
      name: 'Foreign Exchange Metrics',
      description: 'FX trading volume, revenue, and client activity',
      totalMetrics: 12,
      metrics: [
        {
          id: 'TCM-FX-001',
          name: 'Total FX Trading Volume',
          description: 'Total dollar value of FX transactions',
          category: 'Foreign Exchange',
          subcategory: 'Volume',
          formula: "SUM(fx_notional_amount)",
          businessLogic: 'Sum of FX notional values',
          dataType: 'DECIMAL',
          unit: 'currency',
          aggregation: 'SUM',
          granularity: 'Daily',
          sourceTables: ['bronze.commercial_fx_transactions'],
          calculation: { numerator: "SUM(notional_amount_usd)" },
          businessDefinition: 'Commercial FX trading volume',
          benchmarks: { industryAverage: '$185M/day', topQuartile: '$420M/day', target: '$285M/day' },
        },
        {
          id: 'TCM-FX-002',
          name: 'FX Transaction Count',
          description: 'Number of FX transactions executed',
          category: 'Foreign Exchange',
          subcategory: 'Activity',
          formula: "COUNT(fx_transaction_id)",
          businessLogic: 'Count of FX trades',
          dataType: 'INTEGER',
          unit: 'count',
          aggregation: 'COUNT',
          granularity: 'Daily',
          sourceTables: ['bronze.commercial_fx_transactions'],
          calculation: { numerator: "COUNT(transaction_id)" },
          businessDefinition: 'FX transaction activity',
          benchmarks: { industryAverage: '285/day', topQuartile: '520/day', target: '385/day' },
        },
        {
          id: 'TCM-FX-003',
          name: 'FX Spot Volume',
          description: 'Spot FX transaction volume',
          category: 'Foreign Exchange',
          subcategory: 'Product Type',
          formula: "SUM(notional WHERE product_type = 'spot')",
          businessLogic: 'Sum of spot FX notional',
          dataType: 'DECIMAL',
          unit: 'currency',
          aggregation: 'SUM',
          granularity: 'Daily',
          sourceTables: ['bronze.commercial_fx_transactions'],
          calculation: { numerator: "SUM(notional_amount_usd)", filters: "transaction_type = 'spot'" },
          businessDefinition: 'Spot FX trading volume',
          benchmarks: { industryAverage: '$125M/day', topQuartile: '$285M/day', target: '$195M/day' },
        },
        {
          id: 'TCM-FX-004',
          name: 'FX Forward Volume',
          description: 'Forward FX contract volume',
          category: 'Foreign Exchange',
          subcategory: 'Product Type',
          formula: "SUM(notional WHERE product_type = 'forward')",
          businessLogic: 'Sum of forward FX notional',
          dataType: 'DECIMAL',
          unit: 'currency',
          aggregation: 'SUM',
          granularity: 'Daily',
          sourceTables: ['bronze.commercial_fx_transactions'],
          calculation: { numerator: "SUM(notional_amount_usd)", filters: "transaction_type = 'forward'" },
          businessDefinition: 'Forward FX hedging volume',
          benchmarks: { industryAverage: '$60M/day', topQuartile: '$135M/day', target: '$90M/day' },
        },
        {
          id: 'TCM-FX-005',
          name: 'FX Swap Volume',
          description: 'FX swap transaction volume',
          category: 'Foreign Exchange',
          subcategory: 'Product Type',
          formula: "SUM(notional WHERE product_type = 'swap')",
          businessLogic: 'Sum of FX swap notional',
          dataType: 'DECIMAL',
          unit: 'currency',
          aggregation: 'SUM',
          granularity: 'Weekly',
          sourceTables: ['bronze.commercial_fx_transactions'],
          calculation: { numerator: "SUM(notional_amount_usd)", filters: "transaction_type = 'swap'" },
          businessDefinition: 'FX swap volume',
          benchmarks: { industryAverage: '$15M/day', topQuartile: '$35M/day', target: '$25M/day' },
        },
        {
          id: 'TCM-FX-006',
          name: 'FX Revenue',
          description: 'Total revenue from FX transactions (spread + fees)',
          category: 'Foreign Exchange',
          subcategory: 'Revenue',
          formula: "SUM(fx_spread_revenue + fx_fees)",
          businessLogic: 'FX trading revenue',
          dataType: 'DECIMAL',
          unit: 'currency',
          aggregation: 'SUM',
          granularity: 'Monthly',
          sourceTables: ['bronze.commercial_fx_transactions'],
          calculation: { sql: "SUM(spread_income + fee_income)" },
          businessDefinition: 'FX trading profitability',
          benchmarks: { industryAverage: '$385K/month', topQuartile: '$850K/month', target: '$580K/month' },
        },
        {
          id: 'TCM-FX-007',
          name: 'Average FX Spread',
          description: 'Average bid-ask spread on FX transactions',
          category: 'Foreign Exchange',
          subcategory: 'Pricing',
          formula: "AVG(ask_rate - bid_rate)",
          businessLogic: 'Average FX spread',
          dataType: 'DECIMAL',
          unit: 'basis_points',
          aggregation: 'AVG',
          granularity: 'Daily',
          sourceTables: ['bronze.commercial_fx_transactions'],
          calculation: { sql: "AVG((ask_rate - bid_rate) / mid_rate * 10000)" },
          businessDefinition: 'FX pricing spread',
          benchmarks: { industryAverage: '15 bps', topQuartile: '12 bps', target: '13 bps' },
        },
        {
          id: 'TCM-FX-008',
          name: 'Active FX Clients',
          description: 'Number of clients with FX activity',
          category: 'Foreign Exchange',
          subcategory: 'Client Activity',
          formula: "COUNT(DISTINCT customer_id WHERE has_fx_activity = true)",
          businessLogic: 'Unique FX clients',
          dataType: 'INTEGER',
          unit: 'count',
          aggregation: 'COUNT_DISTINCT',
          granularity: 'Monthly',
          sourceTables: ['bronze.commercial_fx_transactions'],
          calculation: { numerator: "COUNT(DISTINCT customer_id)" },
          businessDefinition: 'FX client base',
          benchmarks: { industryAverage: '285', topQuartile: '520', target: '385' },
        },
        {
          id: 'TCM-FX-009',
          name: 'FX Revenue per Transaction',
          description: 'Average revenue per FX transaction',
          category: 'Foreign Exchange',
          subcategory: 'Economics',
          formula: "SUM(fx_revenue) / COUNT(transactions)",
          businessLogic: 'Revenue / transaction count',
          dataType: 'DECIMAL',
          unit: 'currency',
          aggregation: 'CALCULATED',
          granularity: 'Monthly',
          sourceTables: ['bronze.commercial_fx_transactions'],
          calculation: { numerator: "SUM(total_revenue)", denominator: "COUNT(transaction_id)" },
          businessDefinition: 'Per-transaction FX profitability',
          benchmarks: { industryAverage: '$1,350', topQuartile: '$1,650', target: '$1,500' },
        },
        {
          id: 'TCM-FX-010',
          name: 'FX Currency Pair Concentration - EUR/USD',
          description: 'EUR/USD as % of total FX volume',
          category: 'Foreign Exchange',
          subcategory: 'Concentration',
          formula: "(SUM(eur_usd_volume) / SUM(total_fx_volume)) * 100",
          businessLogic: 'EUR/USD / total FX',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Monthly',
          sourceTables: ['bronze.commercial_fx_transactions'],
          calculation: { numerator: "SUM(WHERE currency_pair = 'EUR/USD')", denominator: "SUM(notional_amount_usd)", multiplier: 100 },
          businessDefinition: 'EUR/USD trading concentration',
          benchmarks: { industryAverage: '42%', topQuartile: '38%', target: '40%' },
        },
        {
          id: 'TCM-FX-011',
          name: 'FX Hedge Ratio',
          description: 'FX exposures hedged vs total FX exposure',
          category: 'Foreign Exchange',
          subcategory: 'Risk Management',
          formula: "(SUM(hedged_exposure) / SUM(total_exposure)) * 100",
          businessLogic: 'Hedged / total exposure',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Monthly',
          sourceTables: ['silver.commercial_fx_exposure'],
          calculation: { numerator: "SUM(hedged_notional)", denominator: "SUM(gross_exposure)", multiplier: 100 },
          businessDefinition: 'FX hedging coverage',
          benchmarks: { industryAverage: '72%', topQuartile: '85%', target: '78%' },
        },
        {
          id: 'TCM-FX-012',
          name: 'FX Settlement Efficiency',
          description: 'Percentage of FX trades settled on time',
          category: 'Foreign Exchange',
          subcategory: 'Operations',
          formula: "(COUNT(on_time_settlements) / COUNT(total_trades)) * 100",
          businessLogic: 'On-time / total settlements',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Monthly',
          sourceTables: ['bronze.commercial_fx_transactions'],
          calculation: { numerator: "COUNT(WHERE settlement_date <= expected_settlement)", denominator: "COUNT(transaction_id)", multiplier: 100 },
          businessDefinition: 'FX operational efficiency',
          benchmarks: { industryAverage: '98.5%', topQuartile: '99.5%', target: '99.0%' },
        },
      ],
    },
    {
      name: 'Interest Rate Derivatives Metrics',
      description: 'Interest rate swaps, caps, floors, and hedging activity',
      totalMetrics: 11,
      metrics: [
        {
          id: 'TCM-IRD-001',
          name: 'Interest Rate Swap Notional',
          description: 'Total notional value of interest rate swaps',
          category: 'Interest Rate Derivatives',
          subcategory: 'Volume',
          formula: "SUM(irs_notional)",
          businessLogic: 'Sum of IRS notional',
          dataType: 'DECIMAL',
          unit: 'currency',
          aggregation: 'SUM',
          granularity: 'Monthly',
          sourceTables: ['bronze.commercial_interest_rate_derivatives'],
          calculation: { numerator: "SUM(notional_amount)", filters: "product_type = 'IRS'" },
          businessDefinition: 'Interest rate swap portfolio size',
          benchmarks: { industryAverage: '$850M', topQuartile: '$1.8B', target: '$1.2B' },
        },
        {
          id: 'TCM-IRD-002',
          name: 'New Swap Originations',
          description: 'New interest rate swaps executed',
          category: 'Interest Rate Derivatives',
          subcategory: 'Activity',
          formula: "COUNT(new_swaps WHERE execution_date IN PERIOD)",
          businessLogic: 'Count of new swaps',
          dataType: 'INTEGER',
          unit: 'count',
          aggregation: 'COUNT',
          granularity: 'Monthly',
          sourceTables: ['bronze.commercial_interest_rate_derivatives'],
          calculation: { numerator: "COUNT(swap_id)", filters: "execution_date BETWEEN period_start AND period_end AND product_type = 'IRS'" },
          businessDefinition: 'Swap origination activity',
          benchmarks: { industryAverage: '42/month', topQuartile: '85/month', target: '62/month' },
        },
        {
          id: 'TCM-IRD-003',
          name: 'Interest Rate Cap Notional',
          description: 'Total notional value of interest rate caps',
          category: 'Interest Rate Derivatives',
          subcategory: 'Volume',
          formula: "SUM(cap_notional)",
          businessLogic: 'Sum of cap notional',
          dataType: 'DECIMAL',
          unit: 'currency',
          aggregation: 'SUM',
          granularity: 'Monthly',
          sourceTables: ['bronze.commercial_interest_rate_derivatives'],
          calculation: { numerator: "SUM(notional_amount)", filters: "product_type = 'CAP'" },
          businessDefinition: 'Interest rate cap portfolio',
          benchmarks: { industryAverage: '$285M', topQuartile: '$620M', target: '$420M' },
        },
        {
          id: 'TCM-IRD-004',
          name: 'Interest Rate Floor Notional',
          description: 'Total notional value of interest rate floors',
          category: 'Interest Rate Derivatives',
          subcategory: 'Volume',
          formula: "SUM(floor_notional)",
          businessLogic: 'Sum of floor notional',
          dataType: 'DECIMAL',
          unit: 'currency',
          aggregation: 'SUM',
          granularity: 'Monthly',
          sourceTables: ['bronze.commercial_interest_rate_derivatives'],
          calculation: { numerator: "SUM(notional_amount)", filters: "product_type = 'FLOOR'" },
          businessDefinition: 'Interest rate floor portfolio',
          benchmarks: { industryAverage: '$125M', topQuartile: '$285M', target: '$195M' },
        },
        {
          id: 'TCM-IRD-005',
          name: 'Swap Revenue',
          description: 'Fee revenue from interest rate swap execution',
          category: 'Interest Rate Derivatives',
          subcategory: 'Revenue',
          formula: "SUM(swap_fees)",
          businessLogic: 'Total swap fee income',
          dataType: 'DECIMAL',
          unit: 'currency',
          aggregation: 'SUM',
          granularity: 'Monthly',
          sourceTables: ['bronze.commercial_interest_rate_derivatives'],
          calculation: { numerator: "SUM(fee_income)", filters: "product_type = 'IRS'" },
          businessDefinition: 'Swap structuring revenue',
          benchmarks: { industryAverage: '$185K/month', topQuartile: '$420K/month', target: '$285K/month' },
        },
        {
          id: 'TCM-IRD-006',
          name: 'Active Derivative Clients',
          description: 'Number of clients using interest rate derivatives',
          category: 'Interest Rate Derivatives',
          subcategory: 'Client Activity',
          formula: "COUNT(DISTINCT customer_id)",
          businessLogic: 'Unique derivative clients',
          dataType: 'INTEGER',
          unit: 'count',
          aggregation: 'COUNT_DISTINCT',
          granularity: 'Quarterly',
          sourceTables: ['bronze.commercial_interest_rate_derivatives'],
          calculation: { numerator: "COUNT(DISTINCT customer_id)" },
          businessDefinition: 'Derivative client base',
          benchmarks: { industryAverage: '125', topQuartile: '285', target: '195' },
        },
        {
          id: 'TCM-IRD-007',
          name: 'Average Swap Tenor',
          description: 'Weighted average maturity of interest rate swaps',
          category: 'Interest Rate Derivatives',
          subcategory: 'Portfolio Characteristics',
          formula: "SUM(tenor * notional) / SUM(notional)",
          businessLogic: 'Weighted average tenor',
          dataType: 'DECIMAL',
          unit: 'years',
          aggregation: 'CALCULATED',
          granularity: 'Quarterly',
          sourceTables: ['bronze.commercial_interest_rate_derivatives'],
          calculation: { sql: "SUM(years_to_maturity * notional_amount) / SUM(notional_amount)", filters: "product_type = 'IRS'" },
          businessDefinition: 'Swap portfolio maturity profile',
          benchmarks: { industryAverage: '4.2 years', topQuartile: '3.8 years', target: '4.0 years' },
        },
        {
          id: 'TCM-IRD-008',
          name: 'Pay-Fixed Swap Percentage',
          description: 'Pay-fixed swaps as % of total swap notional',
          category: 'Interest Rate Derivatives',
          subcategory: 'Direction',
          formula: "(SUM(pay_fixed_notional) / SUM(total_swap_notional)) * 100",
          businessLogic: 'Pay-fixed / total swaps',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Monthly',
          sourceTables: ['bronze.commercial_interest_rate_derivatives'],
          calculation: { numerator: "SUM(WHERE swap_direction = 'pay_fixed')", denominator: "SUM(notional_amount)", multiplier: 100, filters: "product_type = 'IRS'" },
          businessDefinition: 'Swap direction mix',
          benchmarks: { industryAverage: '58%', topQuartile: '62%', target: '60%' },
        },
        {
          id: 'TCM-IRD-009',
          name: 'Swap Mark-to-Market Value',
          description: 'Total MTM value of interest rate swap portfolio',
          category: 'Interest Rate Derivatives',
          subcategory: 'Valuation',
          formula: "SUM(mtm_value)",
          businessLogic: 'Total swap MTM',
          dataType: 'DECIMAL',
          unit: 'currency',
          aggregation: 'SUM',
          granularity: 'Daily',
          sourceTables: ['silver.commercial_derivative_valuations'],
          calculation: { numerator: "SUM(mark_to_market_value)", filters: "product_type = 'IRS'" },
          businessDefinition: 'Swap portfolio valuation',
          benchmarks: { industryAverage: '$12.5M', topQuartile: '$8.2M', target: '$10.0M' },
        },
        {
          id: 'TCM-IRD-010',
          name: 'Derivative Collateral Posted',
          description: 'Collateral posted for derivative exposures',
          category: 'Interest Rate Derivatives',
          subcategory: 'Collateral',
          formula: "SUM(collateral_posted)",
          businessLogic: 'Total derivative collateral',
          dataType: 'DECIMAL',
          unit: 'currency',
          aggregation: 'SUM',
          granularity: 'Daily',
          sourceTables: ['bronze.commercial_derivative_collateral'],
          calculation: { numerator: "SUM(collateral_amount)" },
          businessDefinition: 'Derivative margin requirements',
          benchmarks: { industryAverage: '$28M', topQuartile: '$18M', target: '$22M' },
        },
        {
          id: 'TCM-IRD-011',
          name: 'Swap Documentation Efficiency',
          description: 'Average days to execute swap documentation',
          category: 'Interest Rate Derivatives',
          subcategory: 'Operations',
          formula: "AVG(execution_date - trade_date)",
          businessLogic: 'Average documentation time',
          dataType: 'INTEGER',
          unit: 'days',
          aggregation: 'AVG',
          granularity: 'Quarterly',
          sourceTables: ['bronze.commercial_interest_rate_derivatives'],
          calculation: { sql: "AVG(EXTRACT(DAY FROM (execution_date - trade_date)))" },
          businessDefinition: 'Swap execution efficiency',
          benchmarks: { industryAverage: '8 days', topQuartile: '5 days', target: '6 days' },
        },
      ],
    },
    {
      name: 'Cash Management Metrics',
      description: 'Treasury cash management services and account analysis',
      totalMetrics: 12,
      metrics: [
        {
          id: 'TCM-CM-001',
          name: 'Account Analysis Revenue',
          description: 'Fee revenue from account analysis services',
          category: 'Cash Management',
          subcategory: 'Revenue',
          formula: "SUM(account_analysis_fees)",
          businessLogic: 'Account analysis fee income',
          dataType: 'DECIMAL',
          unit: 'currency',
          aggregation: 'SUM',
          granularity: 'Monthly',
          sourceTables: ['bronze.commercial_treasury_fees'],
          calculation: { numerator: "SUM(fee_amount)", filters: "service_type = 'account_analysis'" },
          businessDefinition: 'Account analysis profitability',
          benchmarks: { industryAverage: '$125K/month', topQuartile: '$285K/month', target: '$195K/month' },
        },
        {
          id: 'TCM-CM-002',
          name: 'ZBA Service Clients',
          description: 'Number of clients using Zero Balance Account services',
          category: 'Cash Management',
          subcategory: 'Service Adoption',
          formula: "COUNT(DISTINCT customer_id WHERE has_zba = true)",
          businessLogic: 'Count of ZBA clients',
          dataType: 'INTEGER',
          unit: 'count',
          aggregation: 'COUNT_DISTINCT',
          granularity: 'Monthly',
          sourceTables: ['bronze.commercial_treasury_services'],
          calculation: { numerator: "COUNT(DISTINCT customer_id)", filters: "service_type = 'ZBA'" },
          businessDefinition: 'ZBA service penetration',
          benchmarks: { industryAverage: '185', topQuartile: '420', target: '285' },
        },
        {
          id: 'TCM-CM-003',
          name: 'Sweep Account Balances',
          description: 'Total balances in sweep accounts',
          category: 'Cash Management',
          subcategory: 'Balances',
          formula: "SUM(sweep_balance)",
          businessLogic: 'Sum of sweep balances',
          dataType: 'DECIMAL',
          unit: 'currency',
          aggregation: 'SUM',
          granularity: 'Daily',
          sourceTables: ['bronze.commercial_treasury_balances'],
          calculation: { numerator: "SUM(balance)", filters: "account_type = 'sweep'" },
          businessDefinition: 'Sweep account funding',
          benchmarks: { industryAverage: '$285M', topQuartile: '$620M', target: '$420M' },
        },
        {
          id: 'TCM-CM-004',
          name: 'Lockbox Transaction Volume',
          description: 'Number of lockbox items processed',
          category: 'Cash Management',
          subcategory: 'Receivables',
          formula: "COUNT(lockbox_item_id)",
          businessLogic: 'Count of lockbox items',
          dataType: 'INTEGER',
          unit: 'count',
          aggregation: 'COUNT',
          granularity: 'Monthly',
          sourceTables: ['bronze.commercial_lockbox_transactions'],
          calculation: { numerator: "COUNT(item_id)" },
          businessDefinition: 'Lockbox processing volume',
          benchmarks: { industryAverage: '28.5K/month', topQuartile: '52K/month', target: '38.5K/month' },
        },
        {
          id: 'TCM-CM-005',
          name: 'Lockbox Revenue',
          description: 'Fee revenue from lockbox services',
          category: 'Cash Management',
          subcategory: 'Revenue',
          formula: "SUM(lockbox_fees)",
          businessLogic: 'Lockbox fee income',
          dataType: 'DECIMAL',
          unit: 'currency',
          aggregation: 'SUM',
          granularity: 'Monthly',
          sourceTables: ['bronze.commercial_treasury_fees'],
          calculation: { numerator: "SUM(fee_amount)", filters: "service_type = 'lockbox'" },
          businessDefinition: 'Lockbox service profitability',
          benchmarks: { industryAverage: '$85K/month', topQuartile: '$185K/month', target: '$125K/month' },
        },
        {
          id: 'TCM-CM-006',
          name: 'ACH Origination Clients',
          description: 'Number of clients using ACH origination services',
          category: 'Cash Management',
          subcategory: 'Service Adoption',
          formula: "COUNT(DISTINCT customer_id WHERE has_ach_origination = true)",
          businessLogic: 'Count of ACH origination clients',
          dataType: 'INTEGER',
          unit: 'count',
          aggregation: 'COUNT_DISTINCT',
          granularity: 'Monthly',
          sourceTables: ['bronze.commercial_treasury_services'],
          calculation: { numerator: "COUNT(DISTINCT customer_id)", filters: "service_type = 'ACH_origination'" },
          businessDefinition: 'ACH service penetration',
          benchmarks: { industryAverage: '420', topQuartile: '850', target: '620' },
        },
        {
          id: 'TCM-CM-007',
          name: 'Wire Transfer Service Revenue',
          description: 'Fee revenue from wire transfer services',
          category: 'Cash Management',
          subcategory: 'Revenue',
          formula: "SUM(wire_fees)",
          businessLogic: 'Wire service fee income',
          dataType: 'DECIMAL',
          unit: 'currency',
          aggregation: 'SUM',
          granularity: 'Monthly',
          sourceTables: ['bronze.commercial_treasury_fees'],
          calculation: { numerator: "SUM(fee_amount)", filters: "service_type = 'wire_transfer'" },
          businessDefinition: 'Wire service profitability',
          benchmarks: { industryAverage: '$95K/month', topQuartile: '$220K/month', target: '$145K/month' },
        },
        {
          id: 'TCM-CM-008',
          name: 'Positive Pay Adoption',
          description: 'Percentage of eligible clients using positive pay',
          category: 'Cash Management',
          subcategory: 'Service Adoption',
          formula: "(COUNT(positive_pay_clients) / COUNT(eligible_clients)) * 100",
          businessLogic: 'Positive pay users / eligible',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Quarterly',
          sourceTables: ['bronze.commercial_treasury_services'],
          calculation: { numerator: "COUNT(WHERE has_positive_pay = true)", denominator: "COUNT(WHERE positive_pay_eligible = true)", multiplier: 100 },
          businessDefinition: 'Positive pay penetration',
          benchmarks: { industryAverage: '38%', topQuartile: '56%', target: '47%' },
        },
        {
          id: 'TCM-CM-009',
          name: 'Information Reporting Clients',
          description: 'Number of clients using treasury information reporting',
          category: 'Cash Management',
          subcategory: 'Service Adoption',
          formula: "COUNT(DISTINCT customer_id WHERE has_reporting = true)",
          businessLogic: 'Count of reporting clients',
          dataType: 'INTEGER',
          unit: 'count',
          aggregation: 'COUNT_DISTINCT',
          granularity: 'Monthly',
          sourceTables: ['bronze.commercial_treasury_services'],
          calculation: { numerator: "COUNT(DISTINCT customer_id)", filters: "service_type = 'information_reporting'" },
          businessDefinition: 'Reporting service adoption',
          benchmarks: { industryAverage: '520', topQuartile: '1,050', target: '750' },
        },
        {
          id: 'TCM-CM-010',
          name: 'Controlled Disbursement Clients',
          description: 'Number of clients using controlled disbursement accounts',
          category: 'Cash Management',
          subcategory: 'Service Adoption',
          formula: "COUNT(DISTINCT customer_id WHERE has_controlled_disbursement = true)",
          businessLogic: 'Count of controlled disbursement clients',
          dataType: 'INTEGER',
          unit: 'count',
          aggregation: 'COUNT_DISTINCT',
          granularity: 'Monthly',
          sourceTables: ['bronze.commercial_treasury_services'],
          calculation: { numerator: "COUNT(DISTINCT customer_id)", filters: "service_type = 'controlled_disbursement'" },
          businessDefinition: 'Controlled disbursement adoption',
          benchmarks: { industryAverage: '95', topQuartile: '220', target: '145' },
        },
        {
          id: 'TCM-CM-011',
          name: 'Treasury Services Revenue per Client',
          description: 'Average monthly treasury services revenue per client',
          category: 'Cash Management',
          subcategory: 'Economics',
          formula: "SUM(treasury_fees) / COUNT(DISTINCT clients)",
          businessLogic: 'Total fees / client count',
          dataType: 'DECIMAL',
          unit: 'currency',
          aggregation: 'CALCULATED',
          granularity: 'Monthly',
          sourceTables: ['bronze.commercial_treasury_fees'],
          calculation: { numerator: "SUM(fee_amount)", denominator: "COUNT(DISTINCT customer_id)" },
          businessDefinition: 'Per-client treasury profitability',
          benchmarks: { industryAverage: '$485', topQuartile: '$825', target: '$650' },
        },
        {
          id: 'TCM-CM-012',
          name: 'Online Banking Adoption - Treasury',
          description: 'Percentage of treasury clients using online banking',
          category: 'Cash Management',
          subcategory: 'Digital Adoption',
          formula: "(COUNT(online_users) / COUNT(total_clients)) * 100",
          businessLogic: 'Online users / total clients',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Quarterly',
          sourceTables: ['bronze.commercial_treasury_services'],
          calculation: { numerator: "COUNT(WHERE uses_online_banking = true)", denominator: "COUNT(DISTINCT customer_id)", multiplier: 100 },
          businessDefinition: 'Treasury digital channel adoption',
          benchmarks: { industryAverage: '78%', topQuartile: '92%', target: '85%' },
        },
      ],
    },
    {
      name: 'Liquidity Management Metrics',
      description: 'Corporate liquidity forecasting and concentration banking',
      totalMetrics: 10,
      metrics: [
        {
          id: 'TCM-LIQ-001',
          name: 'Total Liquidity Under Management',
          description: 'Total client funds in liquidity management programs',
          category: 'Liquidity Management',
          subcategory: 'AUM',
          formula: "SUM(liquidity_balance)",
          businessLogic: 'Total managed liquidity',
          dataType: 'DECIMAL',
          unit: 'currency',
          aggregation: 'SUM',
          granularity: 'Daily',
          sourceTables: ['bronze.commercial_liquidity_management'],
          calculation: { numerator: "SUM(managed_balance)" },
          businessDefinition: 'Liquidity assets under management',
          benchmarks: { industryAverage: '$850M', topQuartile: '$1.8B', target: '$1.2B' },
        },
        {
          id: 'TCM-LIQ-002',
          name: 'Concentration Banking Clients',
          description: 'Number of clients using concentration banking',
          category: 'Liquidity Management',
          subcategory: 'Client Base',
          formula: "COUNT(DISTINCT customer_id WHERE has_concentration_banking = true)",
          businessLogic: 'Count of concentration clients',
          dataType: 'INTEGER',
          unit: 'count',
          aggregation: 'COUNT_DISTINCT',
          granularity: 'Monthly',
          sourceTables: ['bronze.commercial_treasury_services'],
          calculation: { numerator: "COUNT(DISTINCT customer_id)", filters: "service_type = 'concentration_banking'" },
          businessDefinition: 'Concentration banking adoption',
          benchmarks: { industryAverage: '125', topQuartile: '285', target: '195' },
        },
        {
          id: 'TCM-LIQ-003',
          name: 'Daily Liquidity Forecast Accuracy',
          description: 'Accuracy of daily cash position forecasts',
          category: 'Liquidity Management',
          subcategory: 'Forecast Quality',
          formula: "1 - (ABS(forecast - actual) / actual)",
          businessLogic: 'Forecast accuracy percentage',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'AVG',
          granularity: 'Monthly',
          sourceTables: ['silver.commercial_liquidity_forecasts'],
          calculation: { sql: "AVG(1 - (ABS(forecasted_balance - actual_balance) / actual_balance)) * 100" },
          businessDefinition: 'Liquidity forecasting precision',
          benchmarks: { industryAverage: '94%', topQuartile: '97%', target: '96%' },
        },
        {
          id: 'TCM-LIQ-004',
          name: 'Notional Pooling Volume',
          description: 'Total notional value in cash pooling structures',
          category: 'Liquidity Management',
          subcategory: 'Cash Pooling',
          formula: "SUM(pooling_notional)",
          businessLogic: 'Total pooled balances',
          dataType: 'DECIMAL',
          unit: 'currency',
          aggregation: 'SUM',
          granularity: 'Daily',
          sourceTables: ['bronze.commercial_cash_pooling'],
          calculation: { numerator: "SUM(pooled_balance)" },
          businessDefinition: 'Cash pooling volume',
          benchmarks: { industryAverage: '$420M', topQuartile: '$920M', target: '$650M' },
        },
        {
          id: 'TCM-LIQ-005',
          name: 'Liquidity Optimization Savings',
          description: 'Estimated interest savings from liquidity optimization',
          category: 'Liquidity Management',
          subcategory: 'Value Add',
          formula: "SUM(optimized_interest - baseline_interest)",
          businessLogic: 'Interest savings realized',
          dataType: 'DECIMAL',
          unit: 'currency',
          aggregation: 'CALCULATED',
          granularity: 'Quarterly',
          sourceTables: ['silver.commercial_liquidity_optimization'],
          calculation: { sql: "SUM(optimized_interest_income - baseline_interest_income)" },
          businessDefinition: 'Client liquidity optimization benefit',
          benchmarks: { industryAverage: '$1.2M/qtr', topQuartile: '$2.8M/qtr', target: '$1.9M/qtr' },
        },
        {
          id: 'TCM-LIQ-006',
          name: 'Cross-Border Cash Pool Clients',
          description: 'Clients with multi-currency cash pooling',
          category: 'Liquidity Management',
          subcategory: 'International',
          formula: "COUNT(DISTINCT customer_id WHERE has_cross_border_pooling = true)",
          businessLogic: 'Count of multi-currency pooling clients',
          dataType: 'INTEGER',
          unit: 'count',
          aggregation: 'COUNT_DISTINCT',
          granularity: 'Quarterly',
          sourceTables: ['bronze.commercial_cash_pooling'],
          calculation: { numerator: "COUNT(DISTINCT customer_id)", filters: "is_cross_border = true" },
          businessDefinition: 'International cash pooling adoption',
          benchmarks: { industryAverage: '28', topQuartile: '62', target: '42' },
        },
        {
          id: 'TCM-LIQ-007',
          name: 'Average Idle Cash Reduction',
          description: 'Reduction in client idle cash through treasury services',
          category: 'Liquidity Management',
          subcategory: 'Efficiency',
          formula: "(baseline_idle_cash - current_idle_cash) / baseline_idle_cash * 100",
          businessLogic: 'Idle cash reduction percentage',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'AVG',
          granularity: 'Quarterly',
          sourceTables: ['silver.commercial_liquidity_optimization'],
          calculation: { sql: "AVG((baseline_idle - current_idle) / baseline_idle * 100)" },
          businessDefinition: 'Working capital efficiency gain',
          benchmarks: { industryAverage: '32%', topQuartile: '48%', target: '40%' },
        },
        {
          id: 'TCM-LIQ-008',
          name: 'Liquidity Report Generation Time',
          description: 'Average time to generate daily liquidity reports',
          category: 'Liquidity Management',
          subcategory: 'Operations',
          formula: "AVG(report_generation_time)",
          businessLogic: 'Average report processing time',
          dataType: 'INTEGER',
          unit: 'minutes',
          aggregation: 'AVG',
          granularity: 'Monthly',
          sourceTables: ['bronze.commercial_treasury_reporting'],
          calculation: { sql: "AVG(EXTRACT(EPOCH FROM generation_duration) / 60)", filters: "report_type = 'liquidity'" },
          businessDefinition: 'Reporting operational efficiency',
          benchmarks: { industryAverage: '12 min', topQuartile: '7 min', target: '9 min' },
        },
        {
          id: 'TCM-LIQ-009',
          name: 'Virtual Account Structures',
          description: 'Number of virtual account structures managed',
          category: 'Liquidity Management',
          subcategory: 'Virtual Accounts',
          formula: "COUNT(DISTINCT virtual_account_structure_id)",
          businessLogic: 'Count of virtual account setups',
          dataType: 'INTEGER',
          unit: 'count',
          aggregation: 'COUNT_DISTINCT',
          granularity: 'Monthly',
          sourceTables: ['bronze.commercial_virtual_accounts'],
          calculation: { numerator: "COUNT(DISTINCT structure_id)" },
          businessDefinition: 'Virtual account adoption',
          benchmarks: { industryAverage: '85', topQuartile: '185', target: '125' },
        },
        {
          id: 'TCM-LIQ-010',
          name: 'Treasury Workstation Active Users',
          description: 'Number of active users on treasury workstation platform',
          category: 'Liquidity Management',
          subcategory: 'Platform Usage',
          formula: "COUNT(DISTINCT user_id WHERE last_login <= 30_days_ago)",
          businessLogic: 'Active workstation users',
          dataType: 'INTEGER',
          unit: 'count',
          aggregation: 'COUNT_DISTINCT',
          granularity: 'Monthly',
          sourceTables: ['bronze.commercial_treasury_platform_usage'],
          calculation: { numerator: "COUNT(DISTINCT user_id)", filters: "last_login_date >= CURRENT_DATE - 30" },
          businessDefinition: 'Treasury platform engagement',
          benchmarks: { industryAverage: '850', topQuartile: '1,850', target: '1,250' },
        },
      ],
    },
    {
      name: 'Commodity & Energy Hedging Metrics',
      description: 'Commodity derivatives and energy risk management',
      totalMetrics: 10,
      metrics: [
        {
          id: 'TCM-COM-001',
          name: 'Commodity Derivative Notional',
          description: 'Total notional value of commodity derivatives',
          category: 'Commodity Hedging',
          subcategory: 'Volume',
          formula: "SUM(commodity_notional)",
          businessLogic: 'Sum of commodity derivative notional',
          dataType: 'DECIMAL',
          unit: 'currency',
          aggregation: 'SUM',
          granularity: 'Monthly',
          sourceTables: ['bronze.commercial_commodity_derivatives'],
          calculation: { numerator: "SUM(notional_amount_usd)" },
          businessDefinition: 'Commodity hedging volume',
          benchmarks: { industryAverage: '$185M', topQuartile: '$420M', target: '$285M' },
        },
        {
          id: 'TCM-COM-002',
          name: 'Energy Derivative Clients',
          description: 'Number of clients using energy derivatives',
          category: 'Commodity Hedging',
          subcategory: 'Client Base',
          formula: "COUNT(DISTINCT customer_id WHERE has_energy_derivatives = true)",
          businessLogic: 'Count of energy hedging clients',
          dataType: 'INTEGER',
          unit: 'count',
          aggregation: 'COUNT_DISTINCT',
          granularity: 'Quarterly',
          sourceTables: ['bronze.commercial_commodity_derivatives'],
          calculation: { numerator: "COUNT(DISTINCT customer_id)", filters: "commodity_type IN ('oil', 'natural_gas', 'power')" },
          businessDefinition: 'Energy hedging client base',
          benchmarks: { industryAverage: '42', topQuartile: '95', target: '65' },
        },
        {
          id: 'TCM-COM-003',
          name: 'Agricultural Commodity Volume',
          description: 'Notional value of agricultural commodity derivatives',
          category: 'Commodity Hedging',
          subcategory: 'Product Type',
          formula: "SUM(notional WHERE commodity_type = 'agriculture')",
          businessLogic: 'Ag commodity notional',
          dataType: 'DECIMAL',
          unit: 'currency',
          aggregation: 'SUM',
          granularity: 'Monthly',
          sourceTables: ['bronze.commercial_commodity_derivatives'],
          calculation: { numerator: "SUM(notional_amount_usd)", filters: "commodity_category = 'agriculture'" },
          businessDefinition: 'Agricultural hedging volume',
          benchmarks: { industryAverage: '$45M', topQuartile: '$105M', target: '$70M' },
        },
        {
          id: 'TCM-COM-004',
          name: 'Metal Commodity Volume',
          description: 'Notional value of metal commodity derivatives',
          category: 'Commodity Hedging',
          subcategory: 'Product Type',
          formula: "SUM(notional WHERE commodity_type = 'metals')",
          businessLogic: 'Metal commodity notional',
          dataType: 'DECIMAL',
          unit: 'currency',
          aggregation: 'SUM',
          granularity: 'Monthly',
          sourceTables: ['bronze.commercial_commodity_derivatives'],
          calculation: { numerator: "SUM(notional_amount_usd)", filters: "commodity_category = 'metals'" },
          businessDefinition: 'Metal hedging volume',
          benchmarks: { industryAverage: '$65M', topQuartile: '$145M', target: '$95M' },
        },
        {
          id: 'TCM-COM-005',
          name: 'Energy Commodity Volume',
          description: 'Notional value of energy commodity derivatives',
          category: 'Commodity Hedging',
          subcategory: 'Product Type',
          formula: "SUM(notional WHERE commodity_type = 'energy')",
          businessLogic: 'Energy commodity notional',
          dataType: 'DECIMAL',
          unit: 'currency',
          aggregation: 'SUM',
          granularity: 'Monthly',
          sourceTables: ['bronze.commercial_commodity_derivatives'],
          calculation: { numerator: "SUM(notional_amount_usd)", filters: "commodity_category = 'energy'" },
          businessDefinition: 'Energy hedging volume',
          benchmarks: { industryAverage: '$85M', topQuartile: '$195M', target: '$125M' },
        },
        {
          id: 'TCM-COM-006',
          name: 'Commodity Hedge Ratio',
          description: 'Commodity exposure hedged vs total exposure',
          category: 'Commodity Hedging',
          subcategory: 'Coverage',
          formula: "(SUM(hedged_exposure) / SUM(total_exposure)) * 100",
          businessLogic: 'Hedged / total commodity exposure',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Quarterly',
          sourceTables: ['silver.commercial_commodity_exposure'],
          calculation: { numerator: "SUM(hedged_notional)", denominator: "SUM(gross_exposure)", multiplier: 100 },
          businessDefinition: 'Commodity hedging coverage',
          benchmarks: { industryAverage: '68%', topQuartile: '82%', target: '75%' },
        },
        {
          id: 'TCM-COM-007',
          name: 'Commodity Derivative Revenue',
          description: 'Fee revenue from commodity derivative execution',
          category: 'Commodity Hedging',
          subcategory: 'Revenue',
          formula: "SUM(commodity_fees)",
          businessLogic: 'Commodity derivative fee income',
          dataType: 'DECIMAL',
          unit: 'currency',
          aggregation: 'SUM',
          granularity: 'Quarterly',
          sourceTables: ['bronze.commercial_commodity_derivatives'],
          calculation: { numerator: "SUM(fee_income)" },
          businessDefinition: 'Commodity hedging profitability',
          benchmarks: { industryAverage: '$125K/qtr', topQuartile: '$285K/qtr', target: '$195K/qtr' },
        },
        {
          id: 'TCM-COM-008',
          name: 'Commodity Swap Volume',
          description: 'Notional value of commodity swaps',
          category: 'Commodity Hedging',
          subcategory: 'Instrument Type',
          formula: "SUM(notional WHERE product_type = 'swap')",
          businessLogic: 'Commodity swap notional',
          dataType: 'DECIMAL',
          unit: 'currency',
          aggregation: 'SUM',
          granularity: 'Monthly',
          sourceTables: ['bronze.commercial_commodity_derivatives'],
          calculation: { numerator: "SUM(notional_amount_usd)", filters: "derivative_type = 'swap'" },
          businessDefinition: 'Commodity swap volume',
          benchmarks: { industryAverage: '$95M', topQuartile: '$220M', target: '$145M' },
        },
        {
          id: 'TCM-COM-009',
          name: 'Commodity Option Volume',
          description: 'Notional value of commodity options',
          category: 'Commodity Hedging',
          subcategory: 'Instrument Type',
          formula: "SUM(notional WHERE product_type = 'option')",
          businessLogic: 'Commodity option notional',
          dataType: 'DECIMAL',
          unit: 'currency',
          aggregation: 'SUM',
          granularity: 'Monthly',
          sourceTables: ['bronze.commercial_commodity_derivatives'],
          calculation: { numerator: "SUM(notional_amount_usd)", filters: "derivative_type = 'option'" },
          businessDefinition: 'Commodity option volume',
          benchmarks: { industryAverage: '$45M', topQuartile: '$105M', target: '$70M' },
        },
        {
          id: 'TCM-COM-010',
          name: 'Average Commodity Hedge Tenor',
          description: 'Weighted average maturity of commodity hedges',
          category: 'Commodity Hedging',
          subcategory: 'Profile',
          formula: "SUM(tenor * notional) / SUM(notional)",
          businessLogic: 'Weighted average tenor',
          dataType: 'DECIMAL',
          unit: 'months',
          aggregation: 'CALCULATED',
          granularity: 'Quarterly',
          sourceTables: ['bronze.commercial_commodity_derivatives'],
          calculation: { sql: "SUM(months_to_maturity * notional_amount) / SUM(notional_amount)" },
          businessDefinition: 'Commodity hedge maturity profile',
          benchmarks: { industryAverage: '14 months', topQuartile: '18 months', target: '16 months' },
        },
      ],
    },
  ],
};
