// FCT_DEPOSIT_DAILY_BALANCE - Complete STTM Mapping
// Source: STTM Excel - CORE_DEPOSIT schema
// 21 columns total
// Sources: FIS-ADS (TB_DP_OZX_BAL_ARD_RAW, TB_DP_SZ9_DP_ACCT_D_FACT_RAW) and FIS-DDW (TB_DP_DZ9_FIN_TXN_FACT_RAW)

export interface ColumnMapping {
  sourceSystem: string;
  sourceTable: string;
  sourceColumn: string;
  bronzeSchema: string;
  bronzeTable: string;
  bronzeColumn: string;
  silverSchema: string;
  silverTable: string;
  silverColumn: string;
  goldSchema: string;
  goldTable: string;
  goldColumn: string | null;
  dataType: string;
  businessLogic: string;
  businessMeaning: string;
  mappingType?: "Direct" | "Derived" | "System" | "SCD2";
}

export const fctDepositDailyBalanceMappings: ColumnMapping[] = [
  {
    sourceSystem: "SYSTEM",
    sourceTable: "N/A",
    sourceColumn: "AUTO_GENERATED",
    bronzeSchema: "N/A",
    bronzeTable: "N/A",
    bronzeColumn: "N/A",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "FCT_DEPOSIT_DAILY_BALANCE",
    silverColumn: "DAILY_BALANCE_SK",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "NUMBER(38,0)",
    businessLogic: "Auto-generated surrogate key sequence",
    businessMeaning: "Surrogate key for daily balance fact",
    mappingType: "System",
  },
  {
    sourceSystem: "SYSTEM",
    sourceTable: "N/A",
    sourceColumn: "DERIVED_FK",
    bronzeSchema: "N/A",
    bronzeTable: "N/A",
    bronzeColumn: "N/A",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "FCT_DEPOSIT_DAILY_BALANCE",
    silverColumn: "ACCOUNT_NUMBER_FK",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "NUMBER(38,0)",
    businessLogic: "Foreign key lookup to DIM_ACCOUNT",
    businessMeaning: "Account dimension foreign key reference",
    mappingType: "Derived",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_DP_OZX_BAL_ARD_RAW",
    sourceColumn: "BAL_ACCT_NBR",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_DP_OZX_BAL_ARD_RAW",
    bronzeColumn: "BAL_ACCT_NBR",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "FCT_DEPOSIT_DAILY_BALANCE",
    silverColumn: "ACCOUNT_NUMBER",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "VARCHAR(16777216)",
    businessLogic: "1:1 mapping from FIS-ADS, also from FIS-DDW as ACCT_NBR",
    businessMeaning: "Account number",
    mappingType: "Direct",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_DP_OZX_BAL_ARD_RAW",
    sourceColumn: "BAL_DATE",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_DP_OZX_BAL_ARD_RAW",
    bronzeColumn: "BAL_DATE",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "FCT_DEPOSIT_DAILY_BALANCE",
    silverColumn: "BALANCE_DATE",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "TIMESTAMP_NTZ(9)",
    businessLogic: "1:1 mapping, also from FIS-DDW as BAL_DTE",
    businessMeaning: "Balance date (daily snapshot date)",
    mappingType: "Direct",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_DP_OZX_BAL_ARD_RAW",
    sourceColumn: "BAL_LEDGER_AMT",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_DP_OZX_BAL_ARD_RAW",
    bronzeColumn: "BAL_LEDGER_AMT",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "FCT_DEPOSIT_DAILY_BALANCE",
    silverColumn: "LEDGER_BALANCE_AMOUNT",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "NUMBER(38,2)",
    businessLogic: "1:1 mapping, also from FIS-DDW as LDGR_BAL_AMT",
    businessMeaning: "Ledger balance amount",
    mappingType: "Direct",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_DP_OZX_BAL_ARD_RAW",
    sourceColumn: "BAL_AVAILABLE_AMT",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_DP_OZX_BAL_ARD_RAW",
    bronzeColumn: "BAL_AVAILABLE_AMT",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "FCT_DEPOSIT_DAILY_BALANCE",
    silverColumn: "AVAILABLE_BALANCE_AMOUNT",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "NUMBER(38,2)",
    businessLogic: "1:1 mapping, also from FIS-DDW as AVLBL_BAL_AMT",
    businessMeaning: "Available balance amount",
    mappingType: "Direct",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_DP_OZX_BAL_ARD_RAW",
    sourceColumn: "BAL_COLLECTED_AMT",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_DP_OZX_BAL_ARD_RAW",
    bronzeColumn: "BAL_COLLECTED_AMT",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "FCT_DEPOSIT_DAILY_BALANCE",
    silverColumn: "COLLECTED_BALANCE_AMOUNT",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "NUMBER(38,2)",
    businessLogic: "1:1 mapping, also from FIS-DDW as CLCTD_BAL_AMT",
    businessMeaning: "Collected balance amount",
    mappingType: "Direct",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_DP_OZX_BAL_ARD_RAW",
    sourceColumn: "BAL_FLOAT_AMT",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_DP_OZX_BAL_ARD_RAW",
    bronzeColumn: "BAL_FLOAT_AMT",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "FCT_DEPOSIT_DAILY_BALANCE",
    silverColumn: "FLOAT_AMOUNT",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "NUMBER(38,2)",
    businessLogic: "1:1 mapping (uncollected funds), also from FIS-DDW as FLT_AMT",
    businessMeaning: "Float amount (uncollected funds)",
    mappingType: "Direct",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_DP_OZX_BAL_ARD_RAW",
    sourceColumn: "BAL_HOLD_AMT",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_DP_OZX_BAL_ARD_RAW",
    bronzeColumn: "BAL_HOLD_AMT",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "FCT_DEPOSIT_DAILY_BALANCE",
    silverColumn: "HOLD_AMOUNT",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "NUMBER(38,2)",
    businessLogic: "1:1 mapping, also from FIS-DDW as HLD_AMT",
    businessMeaning: "Hold amount on account",
    mappingType: "Direct",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_DP_SZ9_DP_ACCT_D_FACT_RAW",
    sourceColumn: "ACCT_AVG_BALANCE_MTD_AMT",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_DP_SZ9_DP_ACCT_D_FACT_RAW",
    bronzeColumn: "ACCT_AVG_BALANCE_MTD_AMT",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "FCT_DEPOSIT_DAILY_BALANCE",
    silverColumn: "AVERAGE_BALANCE_MTD_AMOUNT",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "NUMBER(38,2)",
    businessLogic: "1:1 mapping (month-to-date average), also from FIS-DDW as AVG_BAL_MTD_AMT",
    businessMeaning: "Average balance month-to-date",
    mappingType: "Direct",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_DP_SZ9_DP_ACCT_D_FACT_RAW",
    sourceColumn: "ACCT_AVG_BALANCE_YTD_AMT",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_DP_SZ9_DP_ACCT_D_FACT_RAW",
    bronzeColumn: "ACCT_AVG_BALANCE_YTD_AMT",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "FCT_DEPOSIT_DAILY_BALANCE",
    silverColumn: "AVERAGE_BALANCE_YTD_AMOUNT",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "NUMBER(38,2)",
    businessLogic: "1:1 mapping (year-to-date average), also from FIS-DDW as AVG_BAL_YTD_AMT",
    businessMeaning: "Average balance year-to-date",
    mappingType: "Direct",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_DP_SZ9_DP_ACCT_D_FACT_RAW",
    sourceColumn: "ACCT_MIN_BALANCE_MTD_AMT",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_DP_SZ9_DP_ACCT_D_FACT_RAW",
    bronzeColumn: "ACCT_MIN_BALANCE_MTD_AMT",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "FCT_DEPOSIT_DAILY_BALANCE",
    silverColumn: "MINIMUM_BALANCE_MTD_AMOUNT",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "NUMBER(38,2)",
    businessLogic: "1:1 mapping (month-to-date minimum), also from FIS-DDW as MIN_BAL_MTD_AMT",
    businessMeaning: "Minimum balance month-to-date",
    mappingType: "Direct",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_DP_SZ9_DP_ACCT_D_FACT_RAW",
    sourceColumn: "ACCT_MAX_BALANCE_MTD_AMT",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_DP_SZ9_DP_ACCT_D_FACT_RAW",
    bronzeColumn: "ACCT_MAX_BALANCE_MTD_AMT",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "FCT_DEPOSIT_DAILY_BALANCE",
    silverColumn: "MAXIMUM_BALANCE_MTD_AMOUNT",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "NUMBER(38,2)",
    businessLogic: "1:1 mapping (month-to-date maximum), also from FIS-DDW as MAX_BAL_MTD_AMT",
    businessMeaning: "Maximum balance month-to-date",
    mappingType: "Direct",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_DP_SZ9_DP_ACCT_D_FACT_RAW",
    sourceColumn: "ACCT_INTEREST_ACCRUED_MTD_AMT",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_DP_SZ9_DP_ACCT_D_FACT_RAW",
    bronzeColumn: "ACCT_INTEREST_ACCRUED_MTD_AMT",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "FCT_DEPOSIT_DAILY_BALANCE",
    silverColumn: "INTEREST_ACCRUED_MTD_AMOUNT",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "NUMBER(38,2)",
    businessLogic: "1:1 mapping (month-to-date interest accrued), also from FIS-DDW as INT_ACCRD_MTD_AMT",
    businessMeaning: "Interest accrued month-to-date",
    mappingType: "Direct",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_DP_SZ9_DP_ACCT_D_FACT_RAW",
    sourceColumn: "ACCT_INTEREST_ACCRUED_YTD_AMT",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_DP_SZ9_DP_ACCT_D_FACT_RAW",
    bronzeColumn: "ACCT_INTEREST_ACCRUED_YTD_AMT",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "FCT_DEPOSIT_DAILY_BALANCE",
    silverColumn: "INTEREST_ACCRUED_YTD_AMOUNT",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "NUMBER(38,2)",
    businessLogic: "1:1 mapping (year-to-date interest accrued), also from FIS-DDW as INT_ACCRD_YTD_AMT",
    businessMeaning: "Interest accrued year-to-date",
    mappingType: "Direct",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "VW_TB_DP_DYY_C2_ACCT_SCD_DIM",
    sourceColumn: "PRCS_DTE",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "VW_TB_DP_DYY_C2_ACCT_SCD_DIM",
    bronzeColumn: "PRCS_DTE",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "FCT_DEPOSIT_DAILY_BALANCE",
    silverColumn: "BUSINESS_DATE",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "TIMESTAMP_NTZ(9)",
    businessLogic: "1:1 mapping from FIS processing date, also from FIS-DDW as EFF_DTE",
    businessMeaning: "Business processing date",
    mappingType: "Direct",
  },
  {
    sourceSystem: "SYSTEM",
    sourceTable: "N/A",
    sourceColumn: "CURRENT_USER()",
    bronzeSchema: "N/A",
    bronzeTable: "N/A",
    bronzeColumn: "N/A",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "FCT_DEPOSIT_DAILY_BALANCE",
    silverColumn: "INSERT_BY",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "VARCHAR(16777216)",
    businessLogic: "CURRENT_USER() on insert",
    businessMeaning: "User who inserted the record",
    mappingType: "System",
  },
  {
    sourceSystem: "SYSTEM",
    sourceTable: "N/A",
    sourceColumn: "CURRENT_TIMESTAMP()",
    bronzeSchema: "N/A",
    bronzeTable: "N/A",
    bronzeColumn: "N/A",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "FCT_DEPOSIT_DAILY_BALANCE",
    silverColumn: "INSERT_DT",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "TIMESTAMP_NTZ(9)",
    businessLogic: "CURRENT_TIMESTAMP() on insert",
    businessMeaning: "Timestamp when record was inserted",
    mappingType: "System",
  },
  {
    sourceSystem: "SYSTEM",
    sourceTable: "N/A",
    sourceColumn: "CURRENT_USER()",
    bronzeSchema: "N/A",
    bronzeTable: "N/A",
    bronzeColumn: "N/A",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "FCT_DEPOSIT_DAILY_BALANCE",
    silverColumn: "LAST_MODIFIED_BY",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "VARCHAR(16777216)",
    businessLogic: "CURRENT_USER() on update",
    businessMeaning: "User who last modified the record",
    mappingType: "System",
  },
  {
    sourceSystem: "SYSTEM",
    sourceTable: "N/A",
    sourceColumn: "CURRENT_TIMESTAMP()",
    bronzeSchema: "N/A",
    bronzeTable: "N/A",
    bronzeColumn: "N/A",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "FCT_DEPOSIT_DAILY_BALANCE",
    silverColumn: "LAST_MODIFIED_DT",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "TIMESTAMP_NTZ(9)",
    businessLogic: "CURRENT_TIMESTAMP() on update",
    businessMeaning: "Timestamp when record was last modified",
    mappingType: "System",
  },
];

export default fctDepositDailyBalanceMappings;
