// FCT_DEPOSIT_MAINTENANCE_TRANSACTION - Complete STTM Mapping
// Source: STTM Excel - CORE_DEPOSIT schema
// 15 columns total
// Sources: FIS-ADS (TB_DP_OZU_MAINT_ARD_RAW) and FIS-DDW (TB_DP_DZ0_TXN_DIM_RAW)

export interface ColumnMapping {
  sourceSystem: string;
  sourceTable: string;
  sourceColumn: string;
  bronzeSchema: string;
  bronzeTable: string;
  bronzeColumn: string;
  silverSchema: string;
  silverTable: string;
  silverColumn: string;
  goldSchema: string;
  goldTable: string;
  goldColumn: string | null;
  dataType: string;
  businessLogic: string;
  businessMeaning: string;
  mappingType?: "Direct" | "Derived" | "System" | "SCD2";
}

export const fctDepositMaintenanceTransactionMappings: ColumnMapping[] = [
  {
    sourceSystem: "SYSTEM",
    sourceTable: "N/A",
    sourceColumn: "AUTO_GENERATED",
    bronzeSchema: "N/A",
    bronzeTable: "N/A",
    bronzeColumn: "N/A",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "FCT_DEPOSIT_MAINTENANCE_TRANSACTION",
    silverColumn: "MAINTENANCE_TRANSACTION_SK",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "NUMBER(38,0)",
    businessLogic: "Auto-generated surrogate key sequence",
    businessMeaning: "Surrogate key for maintenance transaction fact",
    mappingType: "System",
  },
  {
    sourceSystem: "SYSTEM",
    sourceTable: "N/A",
    sourceColumn: "DERIVED_FK",
    bronzeSchema: "N/A",
    bronzeTable: "N/A",
    bronzeColumn: "N/A",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "FCT_DEPOSIT_MAINTENANCE_TRANSACTION",
    silverColumn: "ACCOUNT_NUMBER_FK",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "NUMBER(38,0)",
    businessLogic: "Foreign key lookup to DIM_ACCOUNT",
    businessMeaning: "Account dimension foreign key reference",
    mappingType: "Derived",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_DP_OZU_MAINT_ARD_RAW",
    sourceColumn: "MAINT_ACCT_NBR",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_DP_OZU_MAINT_ARD_RAW",
    bronzeColumn: "MAINT_ACCT_NBR",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "FCT_DEPOSIT_MAINTENANCE_TRANSACTION",
    silverColumn: "ACCOUNT_NUMBER",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "VARCHAR(16777216)",
    businessLogic: "1:1 mapping from FIS-ADS, also from FIS-DDW as ACCT_NBR",
    businessMeaning: "Account number",
    mappingType: "Direct",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_DP_OZU_MAINT_ARD_RAW",
    sourceColumn: "MAINT_TRANSACTION_DTE",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_DP_OZU_MAINT_ARD_RAW",
    bronzeColumn: "MAINT_TRANSACTION_DTE",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "FCT_DEPOSIT_MAINTENANCE_TRANSACTION",
    silverColumn: "TRANSACTION_DATE",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "TIMESTAMP_NTZ(9)",
    businessLogic: "1:1 mapping, also from FIS-DDW as TXN_DTE",
    businessMeaning: "Transaction date",
    mappingType: "Direct",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_DP_OZU_MAINT_ARD_RAW",
    sourceColumn: "MAINT_TYPE_CDE",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_DP_OZU_MAINT_ARD_RAW",
    bronzeColumn: "MAINT_TYPE_CDE",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "FCT_DEPOSIT_MAINTENANCE_TRANSACTION",
    silverColumn: "MAINTENANCE_TYPE_CODE",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "VARCHAR(16777216)",
    businessLogic: "1:1 mapping (ADDR_CHG, NAME_CHG, RATE_CHG, etc.), also from FIS-DDW as MAINT_TYP_CDE",
    businessMeaning: "Maintenance type code",
    mappingType: "Direct",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_DP_OZU_MAINT_ARD_RAW",
    sourceColumn: "MAINT_TYPE_CDE",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_DP_OZU_MAINT_ARD_RAW",
    bronzeColumn: "MAINT_TYPE_CDE",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "FCT_DEPOSIT_MAINTENANCE_TRANSACTION",
    silverColumn: "MAINTENANCE_TYPE_DESC",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "VARCHAR(16777216)",
    businessLogic: "Derived description from code mapping (Address Change, Name Change, Rate Change, etc.)",
    businessMeaning: "Maintenance type description",
    mappingType: "Derived",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_DP_OZU_MAINT_ARD_RAW",
    sourceColumn: "MAINT_OLD_VALUE_TXT",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_DP_OZU_MAINT_ARD_RAW",
    bronzeColumn: "MAINT_OLD_VALUE_TXT",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "FCT_DEPOSIT_MAINTENANCE_TRANSACTION",
    silverColumn: "OLD_VALUE_TEXT",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "VARCHAR(16777216)",
    businessLogic: "1:1 mapping, also from FIS-DDW as OLD_VAL_TXT",
    businessMeaning: "Old value before maintenance",
    mappingType: "Direct",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_DP_OZU_MAINT_ARD_RAW",
    sourceColumn: "MAINT_NEW_VALUE_TXT",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_DP_OZU_MAINT_ARD_RAW",
    bronzeColumn: "MAINT_NEW_VALUE_TXT",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "FCT_DEPOSIT_MAINTENANCE_TRANSACTION",
    silverColumn: "NEW_VALUE_TEXT",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "VARCHAR(16777216)",
    businessLogic: "1:1 mapping, also from FIS-DDW as NEW_VAL_TXT",
    businessMeaning: "New value after maintenance",
    mappingType: "Direct",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_DP_OZU_MAINT_ARD_RAW",
    sourceColumn: "MAINT_OFFICER_CDE",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_DP_OZU_MAINT_ARD_RAW",
    bronzeColumn: "MAINT_OFFICER_CDE",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "FCT_DEPOSIT_MAINTENANCE_TRANSACTION",
    silverColumn: "OFFICER_CODE",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "VARCHAR(16777216)",
    businessLogic: "1:1 mapping, also from FIS-DDW as OFFCR_CDE",
    businessMeaning: "Officer code who performed maintenance",
    mappingType: "Direct",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "VW_TB_DP_DYY_C2_ACCT_SCD_DIM",
    sourceColumn: "PRCS_DTE",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "VW_TB_DP_DYY_C2_ACCT_SCD_DIM",
    bronzeColumn: "PRCS_DTE",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "FCT_DEPOSIT_MAINTENANCE_TRANSACTION",
    silverColumn: "BUSINESS_DATE",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "TIMESTAMP_NTZ(9)",
    businessLogic: "1:1 mapping from FIS processing date, also from FIS-DDW as EFF_DTE",
    businessMeaning: "Business processing date",
    mappingType: "Direct",
  },
  {
    sourceSystem: "SYSTEM",
    sourceTable: "N/A",
    sourceColumn: "CURRENT_USER()",
    bronzeSchema: "N/A",
    bronzeTable: "N/A",
    bronzeColumn: "N/A",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "FCT_DEPOSIT_MAINTENANCE_TRANSACTION",
    silverColumn: "INSERT_BY",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "VARCHAR(16777216)",
    businessLogic: "CURRENT_USER() on insert",
    businessMeaning: "User who inserted the record",
    mappingType: "System",
  },
  {
    sourceSystem: "SYSTEM",
    sourceTable: "N/A",
    sourceColumn: "CURRENT_TIMESTAMP()",
    bronzeSchema: "N/A",
    bronzeTable: "N/A",
    bronzeColumn: "N/A",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "FCT_DEPOSIT_MAINTENANCE_TRANSACTION",
    silverColumn: "INSERT_DT",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "TIMESTAMP_NTZ(9)",
    businessLogic: "CURRENT_TIMESTAMP() on insert",
    businessMeaning: "Timestamp when record was inserted",
    mappingType: "System",
  },
  {
    sourceSystem: "SYSTEM",
    sourceTable: "N/A",
    sourceColumn: "CURRENT_USER()",
    bronzeSchema: "N/A",
    bronzeTable: "N/A",
    bronzeColumn: "N/A",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "FCT_DEPOSIT_MAINTENANCE_TRANSACTION",
    silverColumn: "LAST_MODIFIED_BY",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "VARCHAR(16777216)",
    businessLogic: "CURRENT_USER() on update",
    businessMeaning: "User who last modified the record",
    mappingType: "System",
  },
  {
    sourceSystem: "SYSTEM",
    sourceTable: "N/A",
    sourceColumn: "CURRENT_TIMESTAMP()",
    bronzeSchema: "N/A",
    bronzeTable: "N/A",
    bronzeColumn: "N/A",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "FCT_DEPOSIT_MAINTENANCE_TRANSACTION",
    silverColumn: "LAST_MODIFIED_DT",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "TIMESTAMP_NTZ(9)",
    businessLogic: "CURRENT_TIMESTAMP() on update",
    businessMeaning: "Timestamp when record was last modified",
    mappingType: "System",
  },
];

export default fctDepositMaintenanceTransactionMappings;
