// FCT_DEPOSIT_ACCOUNT_TRANSACTION - Complete STTM Mapping
// Source: STTM Excel - CORE_DEPOSIT schema
// 26 columns total
// Sources: FIS-ADS (DP_OZO_MNY_TXN_ARD_RAW) and FIS-DDW (TB_DP_DZ9_FIN_TXN_FACT_RAW)

export interface ColumnMapping {
  sourceSystem: string;
  sourceTable: string;
  sourceColumn: string;
  bronzeSchema: string;
  bronzeTable: string;
  bronzeColumn: string;
  silverSchema: string;
  silverTable: string;
  silverColumn: string;
  goldSchema: string;
  goldTable: string;
  goldColumn: string | null;
  dataType: string;
  businessLogic: string;
  businessMeaning: string;
  mappingType?: "Direct" | "Derived" | "System" | "SCD2";
}

export const fctDepositAccountTransactionMappings: ColumnMapping[] = [
  {
    sourceSystem: "SYSTEM",
    sourceTable: "N/A",
    sourceColumn: "AUTO_GENERATED",
    bronzeSchema: "N/A",
    bronzeTable: "N/A",
    bronzeColumn: "N/A",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "FCT_DEPOSIT_ACCOUNT_TRANSACTION",
    silverColumn: "ACCOUNT_TRANSACTION_SK",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "NUMBER(38,0)",
    businessLogic: "Auto-generated surrogate key sequence",
    businessMeaning: "Surrogate key for account transaction fact",
    mappingType: "System",
  },
  {
    sourceSystem: "SYSTEM",
    sourceTable: "N/A",
    sourceColumn: "DERIVED_FK",
    bronzeSchema: "N/A",
    bronzeTable: "N/A",
    bronzeColumn: "N/A",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "FCT_DEPOSIT_ACCOUNT_TRANSACTION",
    silverColumn: "ACCOUNT_NUMBER_FK",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "NUMBER(38,0)",
    businessLogic: "Foreign key lookup to DIM_ACCOUNT",
    businessMeaning: "Account dimension foreign key reference",
    mappingType: "Derived",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "DP_OZO_MNY_TXN_ARD_RAW",
    sourceColumn: "TXN_ACCT_NBR",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "DP_OZO_MNY_TXN_ARD_RAW",
    bronzeColumn: "TXN_ACCT_NBR",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "FCT_DEPOSIT_ACCOUNT_TRANSACTION",
    silverColumn: "ACCOUNT_NUMBER",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "VARCHAR(16777216)",
    businessLogic: "1:1 mapping from FIS-ADS, also from FIS-DDW as ACCT_NBR",
    businessMeaning: "Account number",
    mappingType: "Direct",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "DP_OZO_MNY_TXN_ARD_RAW",
    sourceColumn: "TXN_ID",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "DP_OZO_MNY_TXN_ARD_RAW",
    bronzeColumn: "TXN_ID",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "FCT_DEPOSIT_ACCOUNT_TRANSACTION",
    silverColumn: "TRANSACTION_ID",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "VARCHAR(16777216)",
    businessLogic: "1:1 mapping, also from FIS-DDW as TXN_ID",
    businessMeaning: "Unique transaction identifier",
    mappingType: "Direct",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "DP_OZO_MNY_TXN_ARD_RAW",
    sourceColumn: "TXN_DTE",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "DP_OZO_MNY_TXN_ARD_RAW",
    bronzeColumn: "TXN_DTE",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "FCT_DEPOSIT_ACCOUNT_TRANSACTION",
    silverColumn: "TRANSACTION_DATE",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "TIMESTAMP_NTZ(9)",
    businessLogic: "1:1 mapping, also from FIS-DDW as TXN_DTE",
    businessMeaning: "Transaction date",
    mappingType: "Direct",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "DP_OZO_MNY_TXN_ARD_RAW",
    sourceColumn: "TXN_TME",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "DP_OZO_MNY_TXN_ARD_RAW",
    bronzeColumn: "TXN_TME",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "FCT_DEPOSIT_ACCOUNT_TRANSACTION",
    silverColumn: "TRANSACTION_TIME",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "VARCHAR(16777216)",
    businessLogic: "1:1 mapping, also from FIS-DDW as TXN_TME",
    businessMeaning: "Transaction time",
    mappingType: "Direct",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "DP_OZO_MNY_TXN_ARD_RAW",
    sourceColumn: "TXN_TYPE_CDE",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "DP_OZO_MNY_TXN_ARD_RAW",
    bronzeColumn: "TXN_TYPE_CDE",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "FCT_DEPOSIT_ACCOUNT_TRANSACTION",
    silverColumn: "TRANSACTION_TYPE_CODE",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "VARCHAR(16777216)",
    businessLogic: "1:1 mapping (DEP, WD, XFER, FEE, etc.), also from FIS-DDW as TXN_TYP_CDE",
    businessMeaning: "Transaction type code",
    mappingType: "Direct",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "DP_OZO_MNY_TXN_ARD_RAW",
    sourceColumn: "TXN_TYPE_CDE",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "DP_OZO_MNY_TXN_ARD_RAW",
    bronzeColumn: "TXN_TYPE_CDE",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "FCT_DEPOSIT_ACCOUNT_TRANSACTION",
    silverColumn: "TRANSACTION_TYPE_DESC",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "VARCHAR(16777216)",
    businessLogic: "Derived description from code mapping (Deposit, Withdrawal, Transfer, Fee, etc.)",
    businessMeaning: "Transaction type description",
    mappingType: "Derived",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "DP_OZO_MNY_TXN_ARD_RAW",
    sourceColumn: "TXN_AMT",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "DP_OZO_MNY_TXN_ARD_RAW",
    bronzeColumn: "TXN_AMT",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "FCT_DEPOSIT_ACCOUNT_TRANSACTION",
    silverColumn: "TRANSACTION_AMOUNT",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "NUMBER(38,2)",
    businessLogic: "1:1 mapping, also from FIS-DDW as TXN_AMT",
    businessMeaning: "Transaction amount",
    mappingType: "Direct",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "DP_OZO_MNY_TXN_ARD_RAW",
    sourceColumn: "TXN_DEBIT_CREDIT_FLG",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "DP_OZO_MNY_TXN_ARD_RAW",
    bronzeColumn: "TXN_DEBIT_CREDIT_FLG",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "FCT_DEPOSIT_ACCOUNT_TRANSACTION",
    silverColumn: "DEBIT_CREDIT_FLAG",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "VARCHAR(16777216)",
    businessLogic: "1:1 mapping (D=Debit, C=Credit), also from FIS-DDW as DR_CR_IND",
    businessMeaning: "Debit or credit indicator",
    mappingType: "Direct",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "DP_OZO_MNY_TXN_ARD_RAW",
    sourceColumn: "TXN_DESCRIPTION",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "DP_OZO_MNY_TXN_ARD_RAW",
    bronzeColumn: "TXN_DESCRIPTION",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "FCT_DEPOSIT_ACCOUNT_TRANSACTION",
    silverColumn: "TRANSACTION_DESCRIPTION",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "VARCHAR(16777216)",
    businessLogic: "1:1 mapping with INITCAP(TRIM()), also from FIS-DDW as TXN_DESC",
    businessMeaning: "Transaction description",
    mappingType: "Direct",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "DP_OZO_MNY_TXN_ARD_RAW",
    sourceColumn: "TXN_CHANNEL_CDE",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "DP_OZO_MNY_TXN_ARD_RAW",
    bronzeColumn: "TXN_CHANNEL_CDE",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "FCT_DEPOSIT_ACCOUNT_TRANSACTION",
    silverColumn: "TRANSACTION_CHANNEL_CODE",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "VARCHAR(16777216)",
    businessLogic: "1:1 mapping (BR=Branch, ATM, OLB=Online Banking, MOB=Mobile), also from FIS-DDW as TXN_CHNL_CDE",
    businessMeaning: "Transaction channel code",
    mappingType: "Direct",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "DP_OZO_MNY_TXN_ARD_RAW",
    sourceColumn: "TXN_CHANNEL_CDE",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "DP_OZO_MNY_TXN_ARD_RAW",
    bronzeColumn: "TXN_CHANNEL_CDE",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "FCT_DEPOSIT_ACCOUNT_TRANSACTION",
    silverColumn: "TRANSACTION_CHANNEL_DESC",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "VARCHAR(16777216)",
    businessLogic: "Derived description from code mapping (Branch, ATM, Online Banking, Mobile, etc.)",
    businessMeaning: "Transaction channel description",
    mappingType: "Derived",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "DP_OZO_MNY_TXN_ARD_RAW",
    sourceColumn: "TXN_BALANCE_AFTER_AMT",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "DP_OZO_MNY_TXN_ARD_RAW",
    bronzeColumn: "TXN_BALANCE_AFTER_AMT",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "FCT_DEPOSIT_ACCOUNT_TRANSACTION",
    silverColumn: "BALANCE_AFTER_TRANSACTION",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "NUMBER(38,2)",
    businessLogic: "1:1 mapping, also from FIS-DDW as BAL_AFTR_TXN_AMT",
    businessMeaning: "Account balance after transaction",
    mappingType: "Direct",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "DP_OZO_MNY_TXN_ARD_RAW",
    sourceColumn: "TXN_CHECK_NBR",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "DP_OZO_MNY_TXN_ARD_RAW",
    bronzeColumn: "TXN_CHECK_NBR",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "FCT_DEPOSIT_ACCOUNT_TRANSACTION",
    silverColumn: "CHECK_NUMBER",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "NUMBER(38,0)",
    businessLogic: "1:1 mapping (for check transactions), also from FIS-DDW as CHK_NBR",
    businessMeaning: "Check number if applicable",
    mappingType: "Direct",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "DP_OZO_MNY_TXN_ARD_RAW",
    sourceColumn: "TXN_REFERENCE_NBR",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "DP_OZO_MNY_TXN_ARD_RAW",
    bronzeColumn: "TXN_REFERENCE_NBR",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "FCT_DEPOSIT_ACCOUNT_TRANSACTION",
    silverColumn: "REFERENCE_NUMBER",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "VARCHAR(16777216)",
    businessLogic: "1:1 mapping, also from FIS-DDW as REF_NBR",
    businessMeaning: "Transaction reference number",
    mappingType: "Direct",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "DP_OZO_MNY_TXN_ARD_RAW",
    sourceColumn: "TXN_TELLER_ID",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "DP_OZO_MNY_TXN_ARD_RAW",
    bronzeColumn: "TXN_TELLER_ID",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "FCT_DEPOSIT_ACCOUNT_TRANSACTION",
    silverColumn: "TELLER_ID",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "VARCHAR(16777216)",
    businessLogic: "1:1 mapping, also from FIS-DDW as TLLR_ID",
    businessMeaning: "Teller ID who processed transaction",
    mappingType: "Direct",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "DP_OZO_MNY_TXN_ARD_RAW",
    sourceColumn: "TXN_BRANCH_CDE",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "DP_OZO_MNY_TXN_ARD_RAW",
    bronzeColumn: "TXN_BRANCH_CDE",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "FCT_DEPOSIT_ACCOUNT_TRANSACTION",
    silverColumn: "BRANCH_CODE",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "VARCHAR(16777216)",
    businessLogic: "1:1 mapping, also from FIS-DDW as BRNCH_CDE",
    businessMeaning: "Branch code where transaction occurred",
    mappingType: "Direct",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "DP_OZO_MNY_TXN_ARD_RAW",
    sourceColumn: "TXN_REVERSAL_FLG",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "DP_OZO_MNY_TXN_ARD_RAW",
    bronzeColumn: "TXN_REVERSAL_FLG",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "FCT_DEPOSIT_ACCOUNT_TRANSACTION",
    silverColumn: "REVERSAL_FLAG",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "VARCHAR(16777216)",
    businessLogic: "1:1 mapping (Y/N), also from FIS-DDW as RVSL_IND",
    businessMeaning: "Indicates if transaction is a reversal",
    mappingType: "Direct",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "DP_OZO_MNY_TXN_ARD_RAW",
    sourceColumn: "TXN_ORIGINAL_TXN_ID",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "DP_OZO_MNY_TXN_ARD_RAW",
    bronzeColumn: "TXN_ORIGINAL_TXN_ID",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "FCT_DEPOSIT_ACCOUNT_TRANSACTION",
    silverColumn: "ORIGINAL_TRANSACTION_ID",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "VARCHAR(16777216)",
    businessLogic: "1:1 mapping (for reversals), also from FIS-DDW as ORGNL_TXN_ID",
    businessMeaning: "Original transaction ID if this is a reversal",
    mappingType: "Direct",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "VW_TB_DP_DYY_C2_ACCT_SCD_DIM",
    sourceColumn: "PRCS_DTE",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "VW_TB_DP_DYY_C2_ACCT_SCD_DIM",
    bronzeColumn: "PRCS_DTE",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "FCT_DEPOSIT_ACCOUNT_TRANSACTION",
    silverColumn: "BUSINESS_DATE",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "TIMESTAMP_NTZ(9)",
    businessLogic: "1:1 mapping from FIS processing date, also from FIS-DDW as EFF_DTE",
    businessMeaning: "Business processing date",
    mappingType: "Direct",
  },
  {
    sourceSystem: "SYSTEM",
    sourceTable: "N/A",
    sourceColumn: "CURRENT_USER()",
    bronzeSchema: "N/A",
    bronzeTable: "N/A",
    bronzeColumn: "N/A",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "FCT_DEPOSIT_ACCOUNT_TRANSACTION",
    silverColumn: "INSERT_BY",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "VARCHAR(16777216)",
    businessLogic: "CURRENT_USER() on insert",
    businessMeaning: "User who inserted the record",
    mappingType: "System",
  },
  {
    sourceSystem: "SYSTEM",
    sourceTable: "N/A",
    sourceColumn: "CURRENT_TIMESTAMP()",
    bronzeSchema: "N/A",
    bronzeTable: "N/A",
    bronzeColumn: "N/A",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "FCT_DEPOSIT_ACCOUNT_TRANSACTION",
    silverColumn: "INSERT_DT",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "TIMESTAMP_NTZ(9)",
    businessLogic: "CURRENT_TIMESTAMP() on insert",
    businessMeaning: "Timestamp when record was inserted",
    mappingType: "System",
  },
  {
    sourceSystem: "SYSTEM",
    sourceTable: "N/A",
    sourceColumn: "CURRENT_USER()",
    bronzeSchema: "N/A",
    bronzeTable: "N/A",
    bronzeColumn: "N/A",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "FCT_DEPOSIT_ACCOUNT_TRANSACTION",
    silverColumn: "LAST_MODIFIED_BY",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "VARCHAR(16777216)",
    businessLogic: "CURRENT_USER() on update",
    businessMeaning: "User who last modified the record",
    mappingType: "System",
  },
  {
    sourceSystem: "SYSTEM",
    sourceTable: "N/A",
    sourceColumn: "CURRENT_TIMESTAMP()",
    bronzeSchema: "N/A",
    bronzeTable: "N/A",
    bronzeColumn: "N/A",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "FCT_DEPOSIT_ACCOUNT_TRANSACTION",
    silverColumn: "LAST_MODIFIED_DT",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "TIMESTAMP_NTZ(9)",
    businessLogic: "CURRENT_TIMESTAMP() on update",
    businessMeaning: "Timestamp when record was last modified",
    mappingType: "System",
  },
];

export default fctDepositAccountTransactionMappings;
