// DIM_ACCOUNT - Complete STTM Mapping
// Source: STTM Excel - CORE_DEPOSIT schema
// 37 columns total
// Sources: FIS-ADS (TB_DP_OZZ_ACCT_ARD_RAW) and FIS-DDW (TB_DP_DYY_C2_ACCT_SCD_DIM_RAW)

export interface ColumnMapping {
  sourceSystem: string;
  sourceTable: string;
  sourceColumn: string;
  bronzeSchema: string;
  bronzeTable: string;
  bronzeColumn: string;
  silverSchema: string;
  silverTable: string;
  silverColumn: string;
  goldSchema: string;
  goldTable: string;
  goldColumn: string | null;
  dataType: string;
  businessLogic: string;
  businessMeaning: string;
  mappingType?: "Direct" | "Derived" | "System" | "SCD2";
}

export const dimAccountMappings: ColumnMapping[] = [
  {
    sourceSystem: "SYSTEM",
    sourceTable: "N/A",
    sourceColumn: "AUTO_GENERATED",
    bronzeSchema: "N/A",
    bronzeTable: "N/A",
    bronzeColumn: "N/A",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "DIM_ACCOUNT",
    silverColumn: "ACCOUNT_SK",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "NUMBER(38,0)",
    businessLogic: "Auto-generated surrogate key sequence",
    businessMeaning: "Surrogate key for account dimension",
    mappingType: "System",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_DP_OZZ_ACCT_ARD_RAW",
    sourceColumn: "DEP_ACCT_NBR",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_DP_OZZ_ACCT_ARD_RAW",
    bronzeColumn: "DEP_ACCT_NBR",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "DIM_ACCOUNT",
    silverColumn: "ACCOUNT_NUMBER",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "VARCHAR(16777216)",
    businessLogic: "1:1 mapping from FIS-ADS, also from FIS-DDW as ACCT_NBR",
    businessMeaning: "Unique account number",
    mappingType: "Direct",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_DP_OZZ_ACCT_ARD_RAW",
    sourceColumn: "DEP_ACCT_NBR_OPER",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_DP_OZZ_ACCT_ARD_RAW",
    bronzeColumn: "DEP_ACCT_NBR_OPER",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "DIM_ACCOUNT",
    silverColumn: "ACCOUNT_NUMBER_OPERATIONAL",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "VARCHAR(16777216)",
    businessLogic: "1:1 mapping (operational/display format), also from FIS-DDW as ACCT_NBR_OPER",
    businessMeaning: "Account number in operational format",
    mappingType: "Direct",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_DP_OZZ_ACCT_ARD_RAW",
    sourceColumn: "DEP_ACCT_TITLE",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_DP_OZZ_ACCT_ARD_RAW",
    bronzeColumn: "DEP_ACCT_TITLE",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "DIM_ACCOUNT",
    silverColumn: "ACCOUNT_TITLE",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "VARCHAR(16777216)",
    businessLogic: "1:1 mapping with INITCAP(TRIM()), also from FIS-DDW as ACCT_TTL",
    businessMeaning: "Account title/name",
    mappingType: "Direct",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_DP_OZZ_ACCT_ARD_RAW",
    sourceColumn: "DEP_SHORT_NAME",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_DP_OZZ_ACCT_ARD_RAW",
    bronzeColumn: "DEP_SHORT_NAME",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "DIM_ACCOUNT",
    silverColumn: "ACCOUNT_SHORT_NAME",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "VARCHAR(16777216)",
    businessLogic: "1:1 mapping with INITCAP(TRIM()), also from FIS-DDW as SHRT_NME",
    businessMeaning: "Short name for account",
    mappingType: "Direct",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_DP_OZZ_ACCT_ARD_RAW",
    sourceColumn: "DEP_OWNERSHIP_TYPE_CDE",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_DP_OZZ_ACCT_ARD_RAW",
    bronzeColumn: "DEP_OWNERSHIP_TYPE_CDE",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "DIM_ACCOUNT",
    silverColumn: "OWNERSHIP_TYPE_CODE",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "VARCHAR(16777216)",
    businessLogic: "1:1 mapping (I=Individual, J=Joint, T=Trust, etc.), also from FIS-DDW as OWNRSHP_TYP_CDE",
    businessMeaning: "Account ownership type code",
    mappingType: "Direct",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_DP_OZZ_ACCT_ARD_RAW",
    sourceColumn: "DEP_OWNERSHIP_TYPE_CDE",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_DP_OZZ_ACCT_ARD_RAW",
    bronzeColumn: "DEP_OWNERSHIP_TYPE_CDE",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "DIM_ACCOUNT",
    silverColumn: "OWNERSHIP_TYPE_DESC",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "VARCHAR(16777216)",
    businessLogic: "Derived description from code mapping (Individual, Joint, Trust, Corporate, etc.)",
    businessMeaning: "Account ownership type description",
    mappingType: "Derived",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_DP_OZZ_ACCT_ARD_RAW",
    sourceColumn: "DEP_JOINT_TENANCY_TYPE_CDE",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_DP_OZZ_ACCT_ARD_RAW",
    bronzeColumn: "DEP_JOINT_TENANCY_TYPE_CDE",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "DIM_ACCOUNT",
    silverColumn: "JOINT_TENANCY_TYPE_CODE",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "VARCHAR(16777216)",
    businessLogic: "1:1 mapping (JTWROS, TIC, etc.), also from FIS-DDW as JNT_TNNCY_TYP_CDE",
    businessMeaning: "Joint tenancy type code (Joint with Right of Survivorship, Tenants in Common, etc.)",
    mappingType: "Direct",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_DP_OZZ_ACCT_ARD_RAW",
    sourceColumn: "DEP_JOINT_TENANCY_TYPE_CDE",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_DP_OZZ_ACCT_ARD_RAW",
    bronzeColumn: "DEP_JOINT_TENANCY_TYPE_CDE",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "DIM_ACCOUNT",
    silverColumn: "JOINT_TENANCY_TYPE_DESC",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "VARCHAR(16777216)",
    businessLogic: "Derived description from code mapping",
    businessMeaning: "Joint tenancy type description",
    mappingType: "Derived",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_DP_OZZ_ACCT_ARD_RAW",
    sourceColumn: "DEP_TAX_REPORTING_CDE",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_DP_OZZ_ACCT_ARD_RAW",
    bronzeColumn: "DEP_TAX_REPORTING_CDE",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "DIM_ACCOUNT",
    silverColumn: "TAX_REPORTING_CODE",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "VARCHAR(16777216)",
    businessLogic: "1:1 mapping (1099-INT, 1099-DIV, etc.), also from FIS-DDW as TAX_RPTNG_CDE",
    businessMeaning: "Tax reporting code/form type",
    mappingType: "Direct",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_DP_OZZ_ACCT_ARD_RAW",
    sourceColumn: "DEP_TAX_REPORTING_CDE",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_DP_OZZ_ACCT_ARD_RAW",
    bronzeColumn: "DEP_TAX_REPORTING_CDE",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "DIM_ACCOUNT",
    silverColumn: "TAX_REPORTING_DESC",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "VARCHAR(16777216)",
    businessLogic: "Derived description from code mapping",
    businessMeaning: "Tax reporting description",
    mappingType: "Derived",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_DP_OZZ_ACCT_ARD_RAW",
    sourceColumn: "DEP_TAX_ID_NBR",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_DP_OZZ_ACCT_ARD_RAW",
    bronzeColumn: "DEP_TAX_ID_NBR",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "DIM_ACCOUNT",
    silverColumn: "TAX_ID_NUMBER",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "VARCHAR(16777216)",
    businessLogic: "1:1 mapping with masking for PII (show last 4 digits), also from FIS-DDW as TAX_ID_NBR (PII - masked)",
    businessMeaning: "Tax ID number for account (PII - masked for security)",
    mappingType: "Direct",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_DP_OZZ_ACCT_ARD_RAW",
    sourceColumn: "DEP_FDIC_INSURED_FLG",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_DP_OZZ_ACCT_ARD_RAW",
    bronzeColumn: "DEP_FDIC_INSURED_FLG",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "DIM_ACCOUNT",
    silverColumn: "FDIC_INSURED_FLAG",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "VARCHAR(16777216)",
    businessLogic: "1:1 mapping (Y/N), also from FIS-DDW as FDIC_INSRD_IND",
    businessMeaning: "Indicates if account is FDIC insured",
    mappingType: "Direct",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_DP_OZZ_ACCT_ARD_RAW",
    sourceColumn: "DEP_FDIC_COVERAGE_AMT",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_DP_OZZ_ACCT_ARD_RAW",
    bronzeColumn: "DEP_FDIC_COVERAGE_AMT",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "DIM_ACCOUNT",
    silverColumn: "FDIC_COVERAGE_AMOUNT",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "NUMBER(38,2)",
    businessLogic: "1:1 mapping (usually $250,000), also from FIS-DDW as FDIC_CVRG_AMT",
    businessMeaning: "FDIC insurance coverage amount",
    mappingType: "Direct",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_DP_OZZ_ACCT_ARD_RAW",
    sourceColumn: "DEP_REGULATION_D_FLG",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_DP_OZZ_ACCT_ARD_RAW",
    bronzeColumn: "DEP_REGULATION_D_FLG",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "DIM_ACCOUNT",
    silverColumn: "REGULATION_D_FLAG",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "VARCHAR(16777216)",
    businessLogic: "1:1 mapping (Y/N, for savings/MMA accounts), also from FIS-DDW as REG_D_IND",
    businessMeaning: "Indicates if account is subject to Regulation D limits",
    mappingType: "Direct",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_DP_OZZ_ACCT_ARD_RAW",
    sourceColumn: "DEP_REGULATION_D_LIMIT",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_DP_OZZ_ACCT_ARD_RAW",
    bronzeColumn: "DEP_REGULATION_D_LIMIT",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "DIM_ACCOUNT",
    silverColumn: "REGULATION_D_LIMIT",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "NUMBER(38,0)",
    businessLogic: "1:1 mapping (usually 6 transactions per month), also from FIS-DDW as REG_D_LMT",
    businessMeaning: "Regulation D transaction limit per month",
    mappingType: "Direct",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_DP_OZZ_ACCT_ARD_RAW",
    sourceColumn: "DEP_HOLD_MAIL_FLG",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_DP_OZZ_ACCT_ARD_RAW",
    bronzeColumn: "DEP_HOLD_MAIL_FLG",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "DIM_ACCOUNT",
    silverColumn: "HOLD_MAIL_FLAG",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "VARCHAR(16777216)",
    businessLogic: "1:1 mapping (Y/N), also from FIS-DDW as HLD_MAIL_IND",
    businessMeaning: "Indicates if mail is held for customer",
    mappingType: "Direct",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_DP_OZZ_ACCT_ARD_RAW",
    sourceColumn: "DEP_LINKED_ACCT_NBR",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_DP_OZZ_ACCT_ARD_RAW",
    bronzeColumn: "DEP_LINKED_ACCT_NBR",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "DIM_ACCOUNT",
    silverColumn: "LINKED_ACCOUNT_NUMBER",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "VARCHAR(16777216)",
    businessLogic: "1:1 mapping (for sweep/transfer accounts), also from FIS-DDW as LNKD_ACCT_NBR",
    businessMeaning: "Linked account number for sweeps/transfers",
    mappingType: "Direct",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_DP_OZZ_ACCT_ARD_RAW",
    sourceColumn: "DEP_SWEEP_TYPE_CDE",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_DP_OZZ_ACCT_ARD_RAW",
    bronzeColumn: "DEP_SWEEP_TYPE_CDE",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "DIM_ACCOUNT",
    silverColumn: "SWEEP_TYPE_CODE",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "VARCHAR(16777216)",
    businessLogic: "1:1 mapping (Full, Partial, Threshold), also from FIS-DDW as SWP_TYP_CDE",
    businessMeaning: "Sweep type code",
    mappingType: "Direct",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_DP_OZZ_ACCT_ARD_RAW",
    sourceColumn: "DEP_SWEEP_TYPE_CDE",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_DP_OZZ_ACCT_ARD_RAW",
    bronzeColumn: "DEP_SWEEP_TYPE_CDE",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "DIM_ACCOUNT",
    silverColumn: "SWEEP_TYPE_DESC",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "VARCHAR(16777216)",
    businessLogic: "Derived description from code mapping",
    businessMeaning: "Sweep type description",
    mappingType: "Derived",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_DP_OZZ_ACCT_ARD_RAW",
    sourceColumn: "DEP_ATM_ACCESS_FLG",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_DP_OZZ_ACCT_ARD_RAW",
    bronzeColumn: "DEP_ATM_ACCESS_FLG",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "DIM_ACCOUNT",
    silverColumn: "ATM_ACCESS_FLAG",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "VARCHAR(16777216)",
    businessLogic: "1:1 mapping (Y/N), also from FIS-DDW as ATM_ACCS_IND",
    businessMeaning: "Indicates if ATM access is enabled",
    mappingType: "Direct",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_DP_OZZ_ACCT_ARD_RAW",
    sourceColumn: "DEP_DEBIT_CARD_FLG",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_DP_OZZ_ACCT_ARD_RAW",
    bronzeColumn: "DEP_DEBIT_CARD_FLG",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "DIM_ACCOUNT",
    silverColumn: "DEBIT_CARD_FLAG",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "VARCHAR(16777216)",
    businessLogic: "1:1 mapping (Y/N), also from FIS-DDW as DBT_CRD_IND",
    businessMeaning: "Indicates if debit card is issued",
    mappingType: "Direct",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_DP_OZZ_ACCT_ARD_RAW",
    sourceColumn: "DEP_CHECK_ORDER_FLG",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_DP_OZZ_ACCT_ARD_RAW",
    bronzeColumn: "DEP_CHECK_ORDER_FLG",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "DIM_ACCOUNT",
    silverColumn: "CHECK_ORDER_FLAG",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "VARCHAR(16777216)",
    businessLogic: "1:1 mapping (Y/N), also from FIS-DDW as CHK_ORDR_IND",
    businessMeaning: "Indicates if checks have been ordered",
    mappingType: "Direct",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_DP_OZZ_ACCT_ARD_RAW",
    sourceColumn: "DEP_NEXT_CHECK_NBR",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_DP_OZZ_ACCT_ARD_RAW",
    bronzeColumn: "DEP_NEXT_CHECK_NBR",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "DIM_ACCOUNT",
    silverColumn: "NEXT_CHECK_NUMBER",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "NUMBER(38,0)",
    businessLogic: "1:1 mapping, also from FIS-DDW as NXT_CHK_NBR",
    businessMeaning: "Next check number in sequence",
    mappingType: "Direct",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_DP_OZZ_ACCT_ARD_RAW",
    sourceColumn: "DEP_STOP_PAYMENT_FLG",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_DP_OZZ_ACCT_ARD_RAW",
    bronzeColumn: "DEP_STOP_PAYMENT_FLG",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "DIM_ACCOUNT",
    silverColumn: "STOP_PAYMENT_FLAG",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "VARCHAR(16777216)",
    businessLogic: "1:1 mapping (Y/N), also from FIS-DDW as STP_PYMT_IND",
    businessMeaning: "Indicates if any stop payments are active",
    mappingType: "Direct",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_DP_OZZ_ACCT_ARD_RAW",
    sourceColumn: "DEP_LAST_CHG_DTE",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_DP_OZZ_ACCT_ARD_RAW",
    bronzeColumn: "DEP_LAST_CHG_DTE",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "DIM_ACCOUNT",
    silverColumn: "EFFECTIVE_START_DATE",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "TIMESTAMP_NTZ(9)",
    businessLogic: "SCD2 effective start date from last account change date, also from FIS-DDW as EFF_DTE",
    businessMeaning: "Date this account version became effective",
    mappingType: "SCD2",
  },
  {
    sourceSystem: "SYSTEM",
    sourceTable: "N/A",
    sourceColumn: "SCD2_LOGIC",
    bronzeSchema: "N/A",
    bronzeTable: "N/A",
    bronzeColumn: "N/A",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "DIM_ACCOUNT",
    silverColumn: "EFFECTIVE_END_DATE",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "TIMESTAMP_NTZ(9)",
    businessLogic: "COALESCE(LEAD(EFFECTIVE_START_DATE) OVER (PARTITION BY ACCOUNT_NUMBER ORDER BY EFFECTIVE_START_DATE), '9999-12-31')",
    businessMeaning: "Date this account version expired (9999-12-31 for current)",
    mappingType: "SCD2",
  },
  {
    sourceSystem: "SYSTEM",
    sourceTable: "N/A",
    sourceColumn: "DERIVED",
    bronzeSchema: "N/A",
    bronzeTable: "N/A",
    bronzeColumn: "N/A",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "DIM_ACCOUNT",
    silverColumn: "RECORD_FLAG",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "VARCHAR(16777216)",
    businessLogic: "CASE WHEN EFFECTIVE_END_DATE::DATE = TO_DATE('9999-12-31') THEN 'A' ELSE 'I' END",
    businessMeaning: "Active/Inactive record flag",
    mappingType: "Derived",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "VW_TB_DP_DYY_C2_ACCT_SCD_DIM",
    sourceColumn: "PRCS_DTE",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "VW_TB_DP_DYY_C2_ACCT_SCD_DIM",
    bronzeColumn: "PRCS_DTE",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "DIM_ACCOUNT",
    silverColumn: "BUSINESS_DATE",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "TIMESTAMP_NTZ(9)",
    businessLogic: "1:1 mapping from FIS processing date, also from FIS-DDW as EFF_DTE",
    businessMeaning: "Business processing date",
    mappingType: "Direct",
  },
  {
    sourceSystem: "SYSTEM",
    sourceTable: "N/A",
    sourceColumn: "HASH_FUNCTION",
    bronzeSchema: "N/A",
    bronzeTable: "N/A",
    bronzeColumn: "N/A",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "DIM_ACCOUNT",
    silverColumn: "ROW_HASH",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "VARCHAR(16777216)",
    businessLogic: "HASH(all account attribute columns for SCD2 change detection)",
    businessMeaning: "Hash of all account columns for SCD2 change detection",
    mappingType: "Derived",
  },
  {
    sourceSystem: "SYSTEM",
    sourceTable: "N/A",
    sourceColumn: "CURRENT_USER()",
    bronzeSchema: "N/A",
    bronzeTable: "N/A",
    bronzeColumn: "N/A",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "DIM_ACCOUNT",
    silverColumn: "INSERT_BY",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "VARCHAR(16777216)",
    businessLogic: "CURRENT_USER() on insert",
    businessMeaning: "User who inserted the record",
    mappingType: "System",
  },
  {
    sourceSystem: "SYSTEM",
    sourceTable: "N/A",
    sourceColumn: "CURRENT_TIMESTAMP()",
    bronzeSchema: "N/A",
    bronzeTable: "N/A",
    bronzeColumn: "N/A",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "DIM_ACCOUNT",
    silverColumn: "INSERT_DT",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "TIMESTAMP_NTZ(9)",
    businessLogic: "CURRENT_TIMESTAMP() on insert",
    businessMeaning: "Timestamp when record was inserted",
    mappingType: "System",
  },
  {
    sourceSystem: "SYSTEM",
    sourceTable: "N/A",
    sourceColumn: "CURRENT_USER()",
    bronzeSchema: "N/A",
    bronzeTable: "N/A",
    bronzeColumn: "N/A",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "DIM_ACCOUNT",
    silverColumn: "LAST_MODIFIED_BY",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "VARCHAR(16777216)",
    businessLogic: "CURRENT_USER() on update",
    businessMeaning: "User who last modified the record",
    mappingType: "System",
  },
  {
    sourceSystem: "SYSTEM",
    sourceTable: "N/A",
    sourceColumn: "CURRENT_TIMESTAMP()",
    bronzeSchema: "N/A",
    bronzeTable: "N/A",
    bronzeColumn: "N/A",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "DIM_ACCOUNT",
    silverColumn: "LAST_MODIFIED_DT",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "TIMESTAMP_NTZ(9)",
    businessLogic: "CURRENT_TIMESTAMP() on update",
    businessMeaning: "Timestamp when record was last modified",
    mappingType: "System",
  },
];

export default dimAccountMappings;
