// FCT_DEPOSIT_HOLD_TRANSACTION - Complete STTM Mapping
// Source: STTM Excel - CORE_DEPOSIT schema
// 21 columns total
// Sources: FIS-ADS (TB_DP_OZV_HLD_ARD_RAW) and FIS-DDW (TB_DP_DZ0_TXN_DIM_RAW)

export interface ColumnMapping {
  sourceSystem: string;
  sourceTable: string;
  sourceColumn: string;
  bronzeSchema: string;
  bronzeTable: string;
  bronzeColumn: string;
  silverSchema: string;
  silverTable: string;
  silverColumn: string;
  goldSchema: string;
  goldTable: string;
  goldColumn: string | null;
  dataType: string;
  businessLogic: string;
  businessMeaning: string;
  mappingType?: "Direct" | "Derived" | "System" | "SCD2";
}

export const fctDepositHoldTransactionMappings: ColumnMapping[] = [
  {
    sourceSystem: "SYSTEM",
    sourceTable: "N/A",
    sourceColumn: "AUTO_GENERATED",
    bronzeSchema: "N/A",
    bronzeTable: "N/A",
    bronzeColumn: "N/A",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "FCT_DEPOSIT_HOLD_TRANSACTION",
    silverColumn: "HOLD_TRANSACTION_SK",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "NUMBER(38,0)",
    businessLogic: "Auto-generated surrogate key sequence",
    businessMeaning: "Surrogate key for hold transaction fact",
    mappingType: "System",
  },
  {
    sourceSystem: "SYSTEM",
    sourceTable: "N/A",
    sourceColumn: "DERIVED_FK",
    bronzeSchema: "N/A",
    bronzeTable: "N/A",
    bronzeColumn: "N/A",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "FCT_DEPOSIT_HOLD_TRANSACTION",
    silverColumn: "ACCOUNT_NUMBER_FK",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "NUMBER(38,0)",
    businessLogic: "Foreign key lookup to DIM_ACCOUNT",
    businessMeaning: "Account dimension foreign key reference",
    mappingType: "Derived",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_DP_OZV_HLD_ARD_RAW",
    sourceColumn: "HLD_ACCT_NBR",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_DP_OZV_HLD_ARD_RAW",
    bronzeColumn: "HLD_ACCT_NBR",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "FCT_DEPOSIT_HOLD_TRANSACTION",
    silverColumn: "ACCOUNT_NUMBER",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "VARCHAR(16777216)",
    businessLogic: "1:1 mapping from FIS-ADS, also from FIS-DDW as ACCT_NBR",
    businessMeaning: "Account number",
    mappingType: "Direct",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_DP_OZV_HLD_ARD_RAW",
    sourceColumn: "HLD_ID",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_DP_OZV_HLD_ARD_RAW",
    bronzeColumn: "HLD_ID",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "FCT_DEPOSIT_HOLD_TRANSACTION",
    silverColumn: "HOLD_ID",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "VARCHAR(16777216)",
    businessLogic: "1:1 mapping, also from FIS-DDW as HLD_ID",
    businessMeaning: "Unique hold identifier",
    mappingType: "Direct",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_DP_OZV_HLD_ARD_RAW",
    sourceColumn: "HLD_TYPE_CDE",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_DP_OZV_HLD_ARD_RAW",
    bronzeColumn: "HLD_TYPE_CDE",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "FCT_DEPOSIT_HOLD_TRANSACTION",
    silverColumn: "HOLD_TYPE_CODE",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "VARCHAR(16777216)",
    businessLogic: "1:1 mapping (CHECK, LEGAL, ADMIN, etc.), also from FIS-DDW as HLD_TYP_CDE",
    businessMeaning: "Hold type code",
    mappingType: "Direct",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_DP_OZV_HLD_ARD_RAW",
    sourceColumn: "HLD_TYPE_CDE",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_DP_OZV_HLD_ARD_RAW",
    bronzeColumn: "HLD_TYPE_CDE",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "FCT_DEPOSIT_HOLD_TRANSACTION",
    silverColumn: "HOLD_TYPE_DESC",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "VARCHAR(16777216)",
    businessLogic: "Derived description from code mapping (Check Hold, Legal Hold, Administrative Hold, etc.)",
    businessMeaning: "Hold type description",
    mappingType: "Derived",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_DP_OZV_HLD_ARD_RAW",
    sourceColumn: "HLD_AMOUNT",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_DP_OZV_HLD_ARD_RAW",
    bronzeColumn: "HLD_AMOUNT",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "FCT_DEPOSIT_HOLD_TRANSACTION",
    silverColumn: "HOLD_AMOUNT",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "NUMBER(38,2)",
    businessLogic: "1:1 mapping, also from FIS-DDW as HLD_AMT",
    businessMeaning: "Hold amount",
    mappingType: "Direct",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_DP_OZV_HLD_ARD_RAW",
    sourceColumn: "HLD_PLACE_DTE",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_DP_OZV_HLD_ARD_RAW",
    bronzeColumn: "HLD_PLACE_DTE",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "FCT_DEPOSIT_HOLD_TRANSACTION",
    silverColumn: "HOLD_PLACE_DATE",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "TIMESTAMP_NTZ(9)",
    businessLogic: "1:1 mapping, also from FIS-DDW as HLD_PLC_DTE",
    businessMeaning: "Date hold was placed",
    mappingType: "Direct",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_DP_OZV_HLD_ARD_RAW",
    sourceColumn: "HLD_EXPIRATION_DTE",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_DP_OZV_HLD_ARD_RAW",
    bronzeColumn: "HLD_EXPIRATION_DTE",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "FCT_DEPOSIT_HOLD_TRANSACTION",
    silverColumn: "HOLD_EXPIRATION_DATE",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "TIMESTAMP_NTZ(9)",
    businessLogic: "1:1 mapping, also from FIS-DDW as HLD_EXP_DTE",
    businessMeaning: "Date hold expires",
    mappingType: "Direct",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_DP_OZV_HLD_ARD_RAW",
    sourceColumn: "HLD_RELEASE_DTE",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_DP_OZV_HLD_ARD_RAW",
    bronzeColumn: "HLD_RELEASE_DTE",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "FCT_DEPOSIT_HOLD_TRANSACTION",
    silverColumn: "HOLD_RELEASE_DATE",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "TIMESTAMP_NTZ(9)",
    businessLogic: "1:1 mapping, also from FIS-DDW as HLD_RLS_DTE",
    businessMeaning: "Date hold was released",
    mappingType: "Direct",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_DP_OZV_HLD_ARD_RAW",
    sourceColumn: "HLD_STATUS_CDE",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_DP_OZV_HLD_ARD_RAW",
    bronzeColumn: "HLD_STATUS_CDE",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "FCT_DEPOSIT_HOLD_TRANSACTION",
    silverColumn: "HOLD_STATUS_CODE",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "VARCHAR(16777216)",
    businessLogic: "1:1 mapping (A=Active, R=Released, E=Expired), also from FIS-DDW as HLD_STAT_CDE",
    businessMeaning: "Hold status code",
    mappingType: "Direct",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_DP_OZV_HLD_ARD_RAW",
    sourceColumn: "HLD_STATUS_CDE",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_DP_OZV_HLD_ARD_RAW",
    bronzeColumn: "HLD_STATUS_CDE",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "FCT_DEPOSIT_HOLD_TRANSACTION",
    silverColumn: "HOLD_STATUS_DESC",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "VARCHAR(16777216)",
    businessLogic: "Derived description from code mapping (Active, Released, Expired)",
    businessMeaning: "Hold status description",
    mappingType: "Derived",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_DP_OZV_HLD_ARD_RAW",
    sourceColumn: "HLD_REASON_TXT",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_DP_OZV_HLD_ARD_RAW",
    bronzeColumn: "HLD_REASON_TXT",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "FCT_DEPOSIT_HOLD_TRANSACTION",
    silverColumn: "HOLD_REASON_TEXT",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "VARCHAR(16777216)",
    businessLogic: "1:1 mapping with INITCAP(TRIM()), also from FIS-DDW as HLD_RSN_TXT",
    businessMeaning: "Reason for hold",
    mappingType: "Direct",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_DP_OZV_HLD_ARD_RAW",
    sourceColumn: "HLD_OFFICER_CDE",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_DP_OZV_HLD_ARD_RAW",
    bronzeColumn: "HLD_OFFICER_CDE",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "FCT_DEPOSIT_HOLD_TRANSACTION",
    silverColumn: "OFFICER_CODE",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "VARCHAR(16777216)",
    businessLogic: "1:1 mapping, also from FIS-DDW as OFFCR_CDE",
    businessMeaning: "Officer code who placed hold",
    mappingType: "Direct",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "VW_TB_DP_DYY_C2_ACCT_SCD_DIM",
    sourceColumn: "PRCS_DTE",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "VW_TB_DP_DYY_C2_ACCT_SCD_DIM",
    bronzeColumn: "PRCS_DTE",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "FCT_DEPOSIT_HOLD_TRANSACTION",
    silverColumn: "BUSINESS_DATE",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "TIMESTAMP_NTZ(9)",
    businessLogic: "1:1 mapping from FIS processing date, also from FIS-DDW as EFF_DTE",
    businessMeaning: "Business processing date",
    mappingType: "Direct",
  },
  {
    sourceSystem: "SYSTEM",
    sourceTable: "N/A",
    sourceColumn: "CURRENT_USER()",
    bronzeSchema: "N/A",
    bronzeTable: "N/A",
    bronzeColumn: "N/A",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "FCT_DEPOSIT_HOLD_TRANSACTION",
    silverColumn: "INSERT_BY",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "VARCHAR(16777216)",
    businessLogic: "CURRENT_USER() on insert",
    businessMeaning: "User who inserted the record",
    mappingType: "System",
  },
  {
    sourceSystem: "SYSTEM",
    sourceTable: "N/A",
    sourceColumn: "CURRENT_TIMESTAMP()",
    bronzeSchema: "N/A",
    bronzeTable: "N/A",
    bronzeColumn: "N/A",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "FCT_DEPOSIT_HOLD_TRANSACTION",
    silverColumn: "INSERT_DT",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "TIMESTAMP_NTZ(9)",
    businessLogic: "CURRENT_TIMESTAMP() on insert",
    businessMeaning: "Timestamp when record was inserted",
    mappingType: "System",
  },
  {
    sourceSystem: "SYSTEM",
    sourceTable: "N/A",
    sourceColumn: "CURRENT_USER()",
    bronzeSchema: "N/A",
    bronzeTable: "N/A",
    bronzeColumn: "N/A",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "FCT_DEPOSIT_HOLD_TRANSACTION",
    silverColumn: "LAST_MODIFIED_BY",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "VARCHAR(16777216)",
    businessLogic: "CURRENT_USER() on update",
    businessMeaning: "User who last modified the record",
    mappingType: "System",
  },
  {
    sourceSystem: "SYSTEM",
    sourceTable: "N/A",
    sourceColumn: "CURRENT_TIMESTAMP()",
    bronzeSchema: "N/A",
    bronzeTable: "N/A",
    bronzeColumn: "N/A",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "FCT_DEPOSIT_HOLD_TRANSACTION",
    silverColumn: "LAST_MODIFIED_DT",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "TIMESTAMP_NTZ(9)",
    businessLogic: "CURRENT_TIMESTAMP() on update",
    businessMeaning: "Timestamp when record was last modified",
    mappingType: "System",
  },
];

export default fctDepositHoldTransactionMappings;
