// FCT_DEPOSIT_CERTIFICATE_TRANSACTION - Complete STTM Mapping
// Source: STTM Excel - CORE_DEPOSIT schema
// 24 columns total
// Sources: FIS-ADS (TB_DP_OZP_TD_ARD_RAW) and FIS-DDW (TB_DP_DZ0_TXN_DIM_RAW)

export interface ColumnMapping {
  sourceSystem: string;
  sourceTable: string;
  sourceColumn: string;
  bronzeSchema: string;
  bronzeTable: string;
  bronzeColumn: string;
  silverSchema: string;
  silverTable: string;
  silverColumn: string;
  goldSchema: string;
  goldTable: string;
  goldColumn: string | null;
  dataType: string;
  businessLogic: string;
  businessMeaning: string;
  mappingType?: "Direct" | "Derived" | "System" | "SCD2";
}

export const fctDepositCertificateTransactionMappings: ColumnMapping[] = [
  {
    sourceSystem: "SYSTEM",
    sourceTable: "N/A",
    sourceColumn: "AUTO_GENERATED",
    bronzeSchema: "N/A",
    bronzeTable: "N/A",
    bronzeColumn: "N/A",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "FCT_DEPOSIT_CERTIFICATE_TRANSACTION",
    silverColumn: "CERTIFICATE_TRANSACTION_SK",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "NUMBER(38,0)",
    businessLogic: "Auto-generated surrogate key sequence",
    businessMeaning: "Surrogate key for certificate transaction fact",
    mappingType: "System",
  },
  {
    sourceSystem: "SYSTEM",
    sourceTable: "N/A",
    sourceColumn: "DERIVED_FK",
    bronzeSchema: "N/A",
    bronzeTable: "N/A",
    bronzeColumn: "N/A",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "FCT_DEPOSIT_CERTIFICATE_TRANSACTION",
    silverColumn: "ACCOUNT_NUMBER_FK",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "NUMBER(38,0)",
    businessLogic: "Foreign key lookup to DIM_ACCOUNT",
    businessMeaning: "Account dimension foreign key reference",
    mappingType: "Derived",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_DP_OZP_TD_ARD_RAW",
    sourceColumn: "TD_ACCT_NBR",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_DP_OZP_TD_ARD_RAW",
    bronzeColumn: "TD_ACCT_NBR",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "FCT_DEPOSIT_CERTIFICATE_TRANSACTION",
    silverColumn: "ACCOUNT_NUMBER",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "VARCHAR(16777216)",
    businessLogic: "1:1 mapping from FIS-ADS, also from FIS-DDW as ACCT_NBR",
    businessMeaning: "Time deposit account number",
    mappingType: "Direct",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_DP_OZP_TD_ARD_RAW",
    sourceColumn: "TD_CERTIFICATE_NBR",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_DP_OZP_TD_ARD_RAW",
    bronzeColumn: "TD_CERTIFICATE_NBR",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "FCT_DEPOSIT_CERTIFICATE_TRANSACTION",
    silverColumn: "CERTIFICATE_NUMBER",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "VARCHAR(16777216)",
    businessLogic: "1:1 mapping, also from FIS-DDW as CERT_NBR",
    businessMeaning: "Certificate number for CD",
    mappingType: "Direct",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_DP_OZP_TD_ARD_RAW",
    sourceColumn: "TD_TRANSACTION_DTE",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_DP_OZP_TD_ARD_RAW",
    bronzeColumn: "TD_TRANSACTION_DTE",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "FCT_DEPOSIT_CERTIFICATE_TRANSACTION",
    silverColumn: "TRANSACTION_DATE",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "TIMESTAMP_NTZ(9)",
    businessLogic: "1:1 mapping, also from FIS-DDW as TXN_DTE",
    businessMeaning: "Transaction date",
    mappingType: "Direct",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_DP_OZP_TD_ARD_RAW",
    sourceColumn: "TD_TRANSACTION_TYPE_CDE",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_DP_OZP_TD_ARD_RAW",
    bronzeColumn: "TD_TRANSACTION_TYPE_CDE",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "FCT_DEPOSIT_CERTIFICATE_TRANSACTION",
    silverColumn: "TRANSACTION_TYPE_CODE",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "VARCHAR(16777216)",
    businessLogic: "1:1 mapping (OPEN, CLOSE, RENEW, MODIFY), also from FIS-DDW as TXN_TYP_CDE",
    businessMeaning: "Transaction type code",
    mappingType: "Direct",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_DP_OZP_TD_ARD_RAW",
    sourceColumn: "TD_TRANSACTION_TYPE_CDE",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_DP_OZP_TD_ARD_RAW",
    bronzeColumn: "TD_TRANSACTION_TYPE_CDE",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "FCT_DEPOSIT_CERTIFICATE_TRANSACTION",
    silverColumn: "TRANSACTION_TYPE_DESC",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "VARCHAR(16777216)",
    businessLogic: "Derived description from code mapping (Open, Close, Renew, Modify)",
    businessMeaning: "Transaction type description",
    mappingType: "Derived",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_DP_OZP_TD_ARD_RAW",
    sourceColumn: "TD_ORIGINAL_AMOUNT",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_DP_OZP_TD_ARD_RAW",
    bronzeColumn: "TD_ORIGINAL_AMOUNT",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "FCT_DEPOSIT_CERTIFICATE_TRANSACTION",
    silverColumn: "ORIGINAL_AMOUNT",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "NUMBER(38,2)",
    businessLogic: "1:1 mapping, also from FIS-DDW as ORGNL_AMT",
    businessMeaning: "Original certificate amount",
    mappingType: "Direct",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_DP_OZP_TD_ARD_RAW",
    sourceColumn: "TD_MATURITY_AMOUNT",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_DP_OZP_TD_ARD_RAW",
    bronzeColumn: "TD_MATURITY_AMOUNT",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "FCT_DEPOSIT_CERTIFICATE_TRANSACTION",
    silverColumn: "MATURITY_AMOUNT",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "NUMBER(38,2)",
    businessLogic: "1:1 mapping, also from FIS-DDW as MTRTY_AMT",
    businessMeaning: "Maturity amount at end of term",
    mappingType: "Direct",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_DP_OZP_TD_ARD_RAW",
    sourceColumn: "TD_INTEREST_RATE",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_DP_OZP_TD_ARD_RAW",
    bronzeColumn: "TD_INTEREST_RATE",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "FCT_DEPOSIT_CERTIFICATE_TRANSACTION",
    silverColumn: "INTEREST_RATE",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "NUMBER(38,5)",
    businessLogic: "1:1 mapping (decimal percentage), also from FIS-DDW as INTRST_RT",
    businessMeaning: "Interest rate",
    mappingType: "Direct",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_DP_OZP_TD_ARD_RAW",
    sourceColumn: "TD_TERM_MONTHS",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_DP_OZP_TD_ARD_RAW",
    bronzeColumn: "TD_TERM_MONTHS",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "FCT_DEPOSIT_CERTIFICATE_TRANSACTION",
    silverColumn: "TERM_MONTHS",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "NUMBER(38,0)",
    businessLogic: "1:1 mapping, also from FIS-DDW as TRM_MNTH_NBR",
    businessMeaning: "Term in months",
    mappingType: "Direct",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_DP_OZP_TD_ARD_RAW",
    sourceColumn: "TD_OPEN_DTE",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_DP_OZP_TD_ARD_RAW",
    bronzeColumn: "TD_OPEN_DTE",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "FCT_DEPOSIT_CERTIFICATE_TRANSACTION",
    silverColumn: "OPEN_DATE",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "TIMESTAMP_NTZ(9)",
    businessLogic: "1:1 mapping, also from FIS-DDW as OPN_DTE",
    businessMeaning: "Certificate open date",
    mappingType: "Direct",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_DP_OZP_TD_ARD_RAW",
    sourceColumn: "TD_MATURITY_DTE",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_DP_OZP_TD_ARD_RAW",
    bronzeColumn: "TD_MATURITY_DTE",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "FCT_DEPOSIT_CERTIFICATE_TRANSACTION",
    silverColumn: "MATURITY_DATE",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "TIMESTAMP_NTZ(9)",
    businessLogic: "1:1 mapping, also from FIS-DDW as MTRTY_DTE",
    businessMeaning: "Certificate maturity date",
    mappingType: "Direct",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_DP_OZP_TD_ARD_RAW",
    sourceColumn: "TD_RENEWAL_TYPE_CDE",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_DP_OZP_TD_ARD_RAW",
    bronzeColumn: "TD_RENEWAL_TYPE_CDE",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "FCT_DEPOSIT_CERTIFICATE_TRANSACTION",
    silverColumn: "RENEWAL_TYPE_CODE",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "VARCHAR(16777216)",
    businessLogic: "1:1 mapping (AUTO, MANUAL, NONE), also from FIS-DDW as RNWL_TYP_CDE",
    businessMeaning: "Renewal type code",
    mappingType: "Direct",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_DP_OZP_TD_ARD_RAW",
    sourceColumn: "TD_RENEWAL_TYPE_CDE",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_DP_OZP_TD_ARD_RAW",
    bronzeColumn: "TD_RENEWAL_TYPE_CDE",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "FCT_DEPOSIT_CERTIFICATE_TRANSACTION",
    silverColumn: "RENEWAL_TYPE_DESC",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "VARCHAR(16777216)",
    businessLogic: "Derived description from code mapping (Automatic, Manual, None)",
    businessMeaning: "Renewal type description",
    mappingType: "Derived",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_DP_OZP_TD_ARD_RAW",
    sourceColumn: "TD_PENALTY_AMOUNT",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_DP_OZP_TD_ARD_RAW",
    bronzeColumn: "TD_PENALTY_AMOUNT",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "FCT_DEPOSIT_CERTIFICATE_TRANSACTION",
    silverColumn: "EARLY_WITHDRAWAL_PENALTY_AMOUNT",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "NUMBER(38,2)",
    businessLogic: "1:1 mapping, also from FIS-DDW as PNLTY_AMT",
    businessMeaning: "Early withdrawal penalty amount",
    mappingType: "Direct",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_DP_OZP_TD_ARD_RAW",
    sourceColumn: "TD_INTEREST_EARNED_AMT",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_DP_OZP_TD_ARD_RAW",
    bronzeColumn: "TD_INTEREST_EARNED_AMT",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "FCT_DEPOSIT_CERTIFICATE_TRANSACTION",
    silverColumn: "INTEREST_EARNED_AMOUNT",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "NUMBER(38,2)",
    businessLogic: "1:1 mapping, also from FIS-DDW as INT_ERND_AMT",
    businessMeaning: "Interest earned amount",
    mappingType: "Direct",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_DP_OZP_TD_ARD_RAW",
    sourceColumn: "TD_OFFICER_CDE",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_DP_OZP_TD_ARD_RAW",
    bronzeColumn: "TD_OFFICER_CDE",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "FCT_DEPOSIT_CERTIFICATE_TRANSACTION",
    silverColumn: "OFFICER_CODE",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "VARCHAR(16777216)",
    businessLogic: "1:1 mapping, also from FIS-DDW as OFFCR_CDE",
    businessMeaning: "Officer code who processed transaction",
    mappingType: "Direct",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "VW_TB_DP_DYY_C2_ACCT_SCD_DIM",
    sourceColumn: "PRCS_DTE",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "VW_TB_DP_DYY_C2_ACCT_SCD_DIM",
    bronzeColumn: "PRCS_DTE",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "FCT_DEPOSIT_CERTIFICATE_TRANSACTION",
    silverColumn: "BUSINESS_DATE",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "TIMESTAMP_NTZ(9)",
    businessLogic: "1:1 mapping from FIS processing date, also from FIS-DDW as EFF_DTE",
    businessMeaning: "Business processing date",
    mappingType: "Direct",
  },
  {
    sourceSystem: "SYSTEM",
    sourceTable: "N/A",
    sourceColumn: "CURRENT_USER()",
    bronzeSchema: "N/A",
    bronzeTable: "N/A",
    bronzeColumn: "N/A",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "FCT_DEPOSIT_CERTIFICATE_TRANSACTION",
    silverColumn: "INSERT_BY",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "VARCHAR(16777216)",
    businessLogic: "CURRENT_USER() on insert",
    businessMeaning: "User who inserted the record",
    mappingType: "System",
  },
  {
    sourceSystem: "SYSTEM",
    sourceTable: "N/A",
    sourceColumn: "CURRENT_TIMESTAMP()",
    bronzeSchema: "N/A",
    bronzeTable: "N/A",
    bronzeColumn: "N/A",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "FCT_DEPOSIT_CERTIFICATE_TRANSACTION",
    silverColumn: "INSERT_DT",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "TIMESTAMP_NTZ(9)",
    businessLogic: "CURRENT_TIMESTAMP() on insert",
    businessMeaning: "Timestamp when record was inserted",
    mappingType: "System",
  },
  {
    sourceSystem: "SYSTEM",
    sourceTable: "N/A",
    sourceColumn: "CURRENT_USER()",
    bronzeSchema: "N/A",
    bronzeTable: "N/A",
    bronzeColumn: "N/A",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "FCT_DEPOSIT_CERTIFICATE_TRANSACTION",
    silverColumn: "LAST_MODIFIED_BY",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "VARCHAR(16777216)",
    businessLogic: "CURRENT_USER() on update",
    businessMeaning: "User who last modified the record",
    mappingType: "System",
  },
  {
    sourceSystem: "SYSTEM",
    sourceTable: "N/A",
    sourceColumn: "CURRENT_TIMESTAMP()",
    bronzeSchema: "N/A",
    bronzeTable: "N/A",
    bronzeColumn: "N/A",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "FCT_DEPOSIT_CERTIFICATE_TRANSACTION",
    silverColumn: "LAST_MODIFIED_DT",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "TIMESTAMP_NTZ(9)",
    businessLogic: "CURRENT_TIMESTAMP() on update",
    businessMeaning: "Timestamp when record was last modified",
    mappingType: "System",
  },
];

export default fctDepositCertificateTransactionMappings;
