// Deposits Domain - Complete Source to Target Mapping (STTM)
// Maps FIS-ADS source tables → Bronze (Curated) → Silver (Core) → Gold (Analytics)

export interface ColumnMapping {
  sourceSystem: string;
  sourceTable: string;
  sourceColumn: string;
  bronzeSchema: string;
  bronzeTable: string;
  bronzeColumn: string;
  silverSchema: string;
  silverTable: string;
  silverColumn: string;
  goldSchema: string;
  goldTable: string;
  goldColumn: string;
  dataType: string;
  businessLogic: string;
  businessMeaning: string;
}

// ============================================================================
// ACCOUNT MASTER - FIS-ADS TB_DP_OZZ_ACCT_ARD
// ============================================================================
export const depositAccountMasterMappings: ColumnMapping[] = [
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_DP_OZZ_ACCT_ARD",
    sourceColumn: "AC_ACCT_NBR",
    bronzeSchema: "SNOWFLAKE_CURATED",
    bronzeTable: "TB_DP_OZZ_ACCT_ARD",
    bronzeColumn: "AC_ACCT_NBR",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "DIM_ACCOUNT",
    silverColumn: "ACCOUNT_NUMBER",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: "ACCOUNT_NUMBER",
    dataType: "VARCHAR(16777216)",
    businessLogic: "1=1",
    businessMeaning: "Unique account identifier",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_DP_OZZ_ACCT_ARD",
    sourceColumn: "AC_BANK_NBR",
    bronzeSchema: "SNOWFLAKE_CURATED",
    bronzeTable: "TB_DP_OZZ_ACCT_ARD",
    bronzeColumn: "AC_BANK_NBR",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "DIM_ACCOUNT",
    silverColumn: "BANK_NUMBER",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: "BANK_NUMBER",
    dataType: "NUMBER(38,0)",
    businessLogic: "1=1",
    businessMeaning: "Bank number identifier",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_DP_OZZ_ACCT_ARD",
    sourceColumn: "AC_BRNCH_NBR",
    bronzeSchema: "SNOWFLAKE_CURATED",
    bronzeTable: "TB_DP_OZZ_ACCT_ARD",
    bronzeColumn: "AC_BRNCH_NBR",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "DIM_ACCOUNT",
    silverColumn: "BRANCH_NUMBER",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: "CH_MOST_VISITED_BRANCH",
    dataType: "NUMBER(38,0)",
    businessLogic: "1=1",
    businessMeaning: "Branch number where account is opened",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_DP_OZZ_ACCT_ARD",
    sourceColumn: "AC_ACCT_TYP",
    bronzeSchema: "SNOWFLAKE_CURATED",
    bronzeTable: "TB_DP_OZZ_ACCT_ARD",
    bronzeColumn: "AC_ACCT_TYP",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "DIM_ACCOUNT",
    silverColumn: "ACCOUNT_TYPE_CODE",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "VARCHAR(10)",
    businessLogic: "1=1",
    businessMeaning: "Account type code (CHK, SAV, CD, etc)",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_DP_OZZ_ACCT_ARD",
    sourceColumn: "AC_NAME",
    bronzeSchema: "SNOWFLAKE_CURATED",
    bronzeTable: "TB_DP_OZZ_ACCT_ARD",
    bronzeColumn: "AC_NAME",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "DIM_DEPOSIT",
    silverColumn: "ACCOUNT_NAME",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "VARCHAR(100)",
    businessLogic: "1=1",
    businessMeaning: "Account display name",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_DP_OZZ_ACCT_ARD",
    sourceColumn: "AC_OPEN_IND",
    bronzeSchema: "SNOWFLAKE_CURATED",
    bronzeTable: "TB_DP_OZZ_ACCT_ARD",
    bronzeColumn: "AC_OPEN_IND",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "DIM_ACCOUNT",
    silverColumn: "ACCOUNT_STATUS",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "VARCHAR(100)",
    businessLogic: "CASE WHEN source='A' THEN 'Active' WHEN source='I' THEN 'Inactive' WHEN source='C' THEN 'Closed' ELSE 'Unknown' END",
    businessMeaning: "Account open indicator / status",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_DP_OZZ_ACCT_ARD",
    sourceColumn: "AC_OPEN_DTE",
    bronzeSchema: "SNOWFLAKE_CURATED",
    bronzeTable: "TB_DP_OZZ_ACCT_ARD",
    bronzeColumn: "AC_OPEN_DTE",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "DIM_ACCOUNT",
    silverColumn: "ACCOUNT_OPEN_DATE",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "DATE",
    businessLogic: "1=1",
    businessMeaning: "Date account was opened",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_DP_OZZ_ACCT_ARD",
    sourceColumn: "AC_CLSE_DTE",
    bronzeSchema: "SNOWFLAKE_CURATED",
    bronzeTable: "TB_DP_OZZ_ACCT_ARD",
    bronzeColumn: "AC_CLSE_DTE",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "DIM_ACCOUNT",
    silverColumn: "ACCOUNT_CLOSED_DATE",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "DATE",
    businessLogic: "1=1",
    businessMeaning: "Date account was closed",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_DP_OZZ_ACCT_ARD",
    sourceColumn: "AC_INT_STATED_RTE",
    bronzeSchema: "SNOWFLAKE_CURATED",
    bronzeTable: "TB_DP_OZZ_ACCT_ARD",
    bronzeColumn: "AC_INT_STATED_RTE",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "DIM_DEPOSIT",
    silverColumn: "CURRENT_INTEREST_RATE",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "NUMBER(18,6)",
    businessLogic: "1=1",
    businessMeaning: "Current stated interest rate",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_DP_OZZ_ACCT_ARD",
    sourceColumn: "AC_COST_CENTER",
    bronzeSchema: "SNOWFLAKE_CURATED",
    bronzeTable: "TB_DP_OZZ_ACCT_ARD",
    bronzeColumn: "AC_COST_CENTER",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "DIM_ACCOUNT",
    silverColumn: "COST_CENTER",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "VARCHAR(16777216)",
    businessLogic: "1=1",
    businessMeaning: "Cost center assignment",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_DP_OZZ_ACCT_ARD",
    sourceColumn: "REFRESH_TIME",
    bronzeSchema: "SNOWFLAKE_CURATED",
    bronzeTable: "TB_DP_OZZ_ACCT_ARD",
    bronzeColumn: "REFRESH_TIME",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "DIM_ACCOUNT",
    silverColumn: "RECORD_DATE",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "TIMESTAMP_NTZ(9)",
    businessLogic: "MAX(REFRESH_TIME)",
    businessMeaning: "Latest refresh timestamp from FIS-ADS",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_DP_OZZ_ACCT_ARD",
    sourceColumn: "PRCS_DTE",
    bronzeSchema: "SNOWFLAKE_CURATED",
    bronzeTable: "TB_DP_OZZ_ACCT_ARD",
    bronzeColumn: "PRCS_DTE",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "DIM_ACCOUNT",
    silverColumn: "BUSINESS_DATE",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: "PRCS_DTE",
    dataType: "DATE",
    businessLogic: "1=1",
    businessMeaning: "Processing date for batch tracking",
  },
];

// ============================================================================
// ACCOUNT BALANCE - FIS-ADS TB_DP_OZX_BAL_ARD
// ============================================================================
export const depositAccountBalanceMappings: ColumnMapping[] = [
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_DP_OZX_BAL_ARD",
    sourceColumn: "BL_ACCT_NBR",
    bronzeSchema: "SNOWFLAKE_CURATED",
    bronzeTable: "TB_DP_OZX_BAL_ARD",
    bronzeColumn: "BL_ACCT_NBR",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "FCT_DEPOSIT_DAILY_BALANCE",
    silverColumn: "ACCOUNT_NUMBER",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: "ACCOUNT_NUMBER",
    dataType: "VARCHAR(16777216)",
    businessLogic: "1=1",
    businessMeaning: "Account number for balance",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_DP_OZX_BAL_ARD",
    sourceColumn: "PRCS_DTE",
    bronzeSchema: "SNOWFLAKE_CURATED",
    bronzeTable: "TB_DP_OZX_BAL_ARD",
    bronzeColumn: "PRCS_DTE",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "FCT_DEPOSIT_DAILY_BALANCE",
    silverColumn: "BALANCE_DATE",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: "PRCS_DTE",
    dataType: "DATE",
    businessLogic: "1=1",
    businessMeaning: "Balance statement date",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_DP_OZX_BAL_ARD",
    sourceColumn: "BL_CUR_BAL",
    bronzeSchema: "SNOWFLAKE_CURATED",
    bronzeTable: "TB_DP_OZX_BAL_ARD",
    bronzeColumn: "BL_CUR_BAL",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "FCT_DEPOSIT_DAILY_BALANCE",
    silverColumn: "CURRENT_BALANCE",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: "ACC_CURRENT_LEDGER_BALANCE",
    dataType: "DECIMAL(18,6)",
    businessLogic: "1=1",
    businessMeaning: "Current ledger balance amount",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_DP_OZX_BAL_ARD",
    sourceColumn: "BL_AVL_BAL",
    bronzeSchema: "SNOWFLAKE_CURATED",
    bronzeTable: "TB_DP_OZX_BAL_ARD",
    bronzeColumn: "BL_AVL_BAL",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "FCT_DEPOSIT_DAILY_BALANCE",
    silverColumn: "AVAILABLE_BALANCE",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: "ACC_AVAILABLE_BALANCE",
    dataType: "DECIMAL(18,6)",
    businessLogic: "1=1",
    businessMeaning: "Available balance for transactions",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_DP_OZX_BAL_ARD",
    sourceColumn: "BL_SERV_CHRG_CDE",
    bronzeSchema: "SNOWFLAKE_CURATED",
    bronzeTable: "TB_DP_OZX_BAL_ARD",
    bronzeColumn: "BL_SERV_CHRG_CDE",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "DIM_DEPOSIT",
    silverColumn: "SERVICE_CHARGE_CODE",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "VARCHAR(100)",
    businessLogic: "1=1",
    businessMeaning: "Service charge code",
  },
];

// ============================================================================
// DAILY BALANCE FACTS - FIS-ADS TB_DP_SZ9_DP_ACCT_D_FACT
// ============================================================================
export const depositDailyBalanceFactMappings: ColumnMapping[] = [
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_DP_SZ9_DP_ACCT_D_FACT",
    sourceColumn: "ACCT_NBR",
    bronzeSchema: "SNOWFLAKE_CURATED",
    bronzeTable: "VW_TB_DP_SZ9_DP_ACCT_D_FACT",
    bronzeColumn: "ACCT_NBR",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "FCT_DEPOSIT_DAILY_BALANCE",
    silverColumn: "ACCOUNT_NUMBER",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: "ACCOUNT_NUMBER",
    dataType: "VARCHAR(16777216)",
    businessLogic: "1=1",
    businessMeaning: "Account number",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_DP_SZ9_DP_ACCT_D_FACT",
    sourceColumn: "PRCS_DTE",
    bronzeSchema: "SNOWFLAKE_CURATED",
    bronzeTable: "VW_TB_DP_SZ9_DP_ACCT_D_FACT",
    bronzeColumn: "PRCS_DTE",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "FCT_DEPOSIT_DAILY_BALANCE",
    silverColumn: "CALENDAR_DATE",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: "PRCS_DTE",
    dataType: "DATE",
    businessLogic: "1=1",
    businessMeaning: "Calendar/processing date",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_DP_SZ9_DP_ACCT_D_FACT",
    sourceColumn: "COL_BAL_AMT",
    bronzeSchema: "SNOWFLAKE_CURATED",
    bronzeTable: "VW_TB_DP_SZ9_DP_ACCT_D_FACT",
    bronzeColumn: "COL_BAL_AMT",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "FCT_DEPOSIT_DAILY_BALANCE",
    silverColumn: "CURRENT_BALANCE",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: "ACC_CURRENT_LEDGER_BALANCE",
    dataType: "DECIMAL(18,6)",
    businessLogic: "1=1",
    businessMeaning: "Current ledger balance",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_DP_SZ9_DP_ACCT_D_FACT",
    sourceColumn: "AVAIL_BAL_AMT",
    bronzeSchema: "SNOWFLAKE_CURATED",
    bronzeTable: "VW_TB_DP_SZ9_DP_ACCT_D_FACT",
    bronzeColumn: "AVAIL_BAL_AMT",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "FCT_DEPOSIT_DAILY_BALANCE",
    silverColumn: "AVAILABLE_BALANCE",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: "ACC_AVAILABLE_BALANCE",
    dataType: "DECIMAL(18,6)",
    businessLogic: "1=1",
    businessMeaning: "Available balance amount",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_DP_SZ9_DP_ACCT_D_FACT",
    sourceColumn: "PR_DAY_LGR_BAL_AMT",
    bronzeSchema: "SNOWFLAKE_CURATED",
    bronzeTable: "VW_TB_DP_SZ9_DP_ACCT_D_FACT",
    bronzeColumn: "PR_DAY_LGR_BAL_AMT",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "FCT_DEPOSIT_DAILY_BALANCE",
    silverColumn: "PREVIOUS_DAY_LEDGER_BALANCE_AMOUNT",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "DECIMAL(18,6)",
    businessLogic: "1=1",
    businessMeaning: "Previous day ledger balance",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_DP_SZ9_DP_ACCT_D_FACT",
    sourceColumn: "PR_MTH_LGR_BAL_AMT",
    bronzeSchema: "SNOWFLAKE_CURATED",
    bronzeTable: "VW_TB_DP_SZ9_DP_ACCT_D_FACT",
    bronzeColumn: "PR_MTH_LGR_BAL_AMT",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "FCT_DEPOSIT_DAILY_BALANCE",
    silverColumn: "PREVIOUS_MONTH_LEDGER_BALANCE_AMOUNT",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "DECIMAL(18,6)",
    businessLogic: "1=1",
    businessMeaning: "Previous month ledger balance",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_DP_SZ9_DP_ACCT_D_FACT",
    sourceColumn: "AVG_LGR_BAL_YTD_AMT",
    bronzeSchema: "SNOWFLAKE_CURATED",
    bronzeTable: "VW_TB_DP_SZ9_DP_ACCT_D_FACT",
    bronzeColumn: "AVG_LGR_BAL_YTD_AMT",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "FCT_DEPOSIT_DAILY_BALANCE",
    silverColumn: "AVG_LEDGER_BALANCE_YTD_AMOUNT",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "DECIMAL(18,6)",
    businessLogic: "1=1",
    businessMeaning: "Year-to-date average ledger balance",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_DP_SZ9_DP_ACCT_D_FACT",
    sourceColumn: "AVG_LGR_BAL_MTD_AMT",
    bronzeSchema: "SNOWFLAKE_CURATED",
    bronzeTable: "VW_TB_DP_SZ9_DP_ACCT_D_FACT",
    bronzeColumn: "AVG_LGR_BAL_MTD_AMT",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "FCT_DEPOSIT_DAILY_BALANCE",
    silverColumn: "AVG_LEDGER_BALANCE_MTD_AMOUNT",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "DECIMAL(18,6)",
    businessLogic: "1=1",
    businessMeaning: "Month-to-date average ledger balance",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_DP_SZ9_DP_ACCT_D_FACT",
    sourceColumn: "LGR_BAL_AMT",
    bronzeSchema: "SNOWFLAKE_CURATED",
    bronzeTable: "VW_TB_DP_SZ9_DP_ACCT_D_FACT",
    bronzeColumn: "LGR_BAL_AMT",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "FCT_DEPOSIT_DAILY_BALANCE",
    silverColumn: "LEDGER_BALANCE",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: "ACC_LEDGER_BALANCE",
    dataType: "DECIMAL(18,6)",
    businessLogic: "1=1",
    businessMeaning: "Ledger balance",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_DP_SZ9_DP_ACCT_D_FACT",
    sourceColumn: "INT_PD_YTD_AMT",
    bronzeSchema: "SNOWFLAKE_CURATED",
    bronzeTable: "VW_TB_DP_SZ9_DP_ACCT_D_FACT",
    bronzeColumn: "INT_PD_YTD_AMT",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "FCT_DEPOSIT_DAILY_BALANCE",
    silverColumn: "INTEREST_PAID_YTD_AMOUNT",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "DECIMAL(18,6)",
    businessLogic: "1=1",
    businessMeaning: "Year-to-date interest paid",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_DP_SZ9_DP_ACCT_D_FACT",
    sourceColumn: "INT_PD_MTD_AMT",
    bronzeSchema: "SNOWFLAKE_CURATED",
    bronzeTable: "VW_TB_DP_SZ9_DP_ACCT_D_FACT",
    bronzeColumn: "INT_PD_MTD_AMT",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "FCT_DEPOSIT_DAILY_BALANCE",
    silverColumn: "INTEREST_PAID_MTD_AMOUNT",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "DECIMAL(18,6)",
    businessLogic: "1=1",
    businessMeaning: "Month-to-date interest paid",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_DP_SZ9_DP_ACCT_D_FACT",
    sourceColumn: "INT_PD_PR_YTD_AMT",
    bronzeSchema: "SNOWFLAKE_CURATED",
    bronzeTable: "VW_TB_DP_SZ9_DP_ACCT_D_FACT",
    bronzeColumn: "INT_PD_PR_YTD_AMT",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "FCT_DEPOSIT_DAILY_BALANCE",
    silverColumn: "INTEREST_PAID_PREVIOUS_YTD_AMOUNT",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "DECIMAL(18,6)",
    businessLogic: "1=1",
    businessMeaning: "Prior year interest paid",
  },
];

// Combine all Deposits STTM mappings
export const depositsSTTMMapping_Combined: ColumnMapping[] = [
  ...depositAccountMasterMappings,
  ...depositAccountBalanceMappings,
  ...depositDailyBalanceFactMappings,
];

// STTM gaps (columns not yet mapped)
export const depositsSTTMGaps: ColumnMapping[] = [];

// Table coverage summary
export const depositsTableCoverage = [
  {
    fisTable: "TB_DP_OZZ_ACCT_ARD",
    columnCount: 11,
    mappedCount: 11,
    coverage: "100%",
    businessKey: "AC_ACCT_NBR",
    silverTable: "DIM_ACCOUNT, DIM_DEPOSIT",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
  },
  {
    fisTable: "TB_DP_OZX_BAL_ARD",
    columnCount: 5,
    mappedCount: 5,
    coverage: "100%",
    businessKey: "BL_ACCT_NBR",
    silverTable: "FCT_DEPOSIT_DAILY_BALANCE, DIM_DEPOSIT",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
  },
  {
    fisTable: "TB_DP_SZ9_DP_ACCT_D_FACT",
    columnCount: 12,
    mappedCount: 12,
    coverage: "100%",
    businessKey: "ACCT_NBR",
    silverTable: "FCT_DEPOSIT_DAILY_BALANCE",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
  },
];

export default depositsSTTMMapping_Combined;
