// DIM_DEPOSIT - Complete STTM Mapping
// Source: STTM Excel - CORE_DEPOSIT schema
// 72 columns total (LARGEST DEPOSIT TABLE)
// Contains: account details, TD info, rates, officers, user codes, cost center
// Sources: FIS-ADS (TB_DP_OZZ_ACCT_ARD_RAW, TB_DP_OZP_TD_ARD_RAW) and FIS-DDW (TB_DP_DYY_C2_ACCT_SCD_DIM_RAW)

export interface ColumnMapping {
  sourceSystem: string;
  sourceTable: string;
  sourceColumn: string;
  bronzeSchema: string;
  bronzeTable: string;
  bronzeColumn: string;
  silverSchema: string;
  silverTable: string;
  silverColumn: string;
  goldSchema: string;
  goldTable: string;
  goldColumn: string | null;
  dataType: string;
  businessLogic: string;
  businessMeaning: string;
  mappingType?: "Direct" | "Derived" | "System" | "SCD2";
}

export const dimDepositMappings: ColumnMapping[] = [
  {
    sourceSystem: "SYSTEM",
    sourceTable: "N/A",
    sourceColumn: "AUTO_GENERATED",
    bronzeSchema: "N/A",
    bronzeTable: "N/A",
    bronzeColumn: "N/A",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "DIM_DEPOSIT",
    silverColumn: "DEPOSIT_SK",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "NUMBER(38,0)",
    businessLogic: "Auto-generated surrogate key sequence",
    businessMeaning: "Surrogate key for deposit dimension",
    mappingType: "System",
  },
  {
    sourceSystem: "SYSTEM",
    sourceTable: "N/A",
    sourceColumn: "DERIVED_FK",
    bronzeSchema: "N/A",
    bronzeTable: "N/A",
    bronzeColumn: "N/A",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "DIM_DEPOSIT",
    silverColumn: "ACCOUNT_NUMBER_FK",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "NUMBER(38,0)",
    businessLogic: "Foreign key lookup to DIM_ACCOUNT",
    businessMeaning: "Account dimension foreign key reference",
    mappingType: "Derived",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_DP_OZZ_ACCT_ARD_RAW",
    sourceColumn: "DEP_ACCT_NBR",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_DP_OZZ_ACCT_ARD_RAW",
    bronzeColumn: "DEP_ACCT_NBR",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "DIM_DEPOSIT",
    silverColumn: "ACCOUNT_NUMBER",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "VARCHAR(16777216)",
    businessLogic: "1:1 mapping from FIS-ADS, also from FIS-DDW as ACCT_NBR",
    businessMeaning: "Unique deposit account number",
    mappingType: "Direct",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_DP_OZZ_ACCT_ARD_RAW",
    sourceColumn: "DEP_ACCT_SUFFIX_NBR",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_DP_OZZ_ACCT_ARD_RAW",
    bronzeColumn: "DEP_ACCT_SUFFIX_NBR",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "DIM_DEPOSIT",
    silverColumn: "ACCOUNT_SUFFIX_NUMBER",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "VARCHAR(16777216)",
    businessLogic: "1:1 mapping, also from FIS-DDW as ACCT_SFX_NBR",
    businessMeaning: "Account suffix number for sub-accounts",
    mappingType: "Direct",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_DP_OZZ_ACCT_ARD_RAW",
    sourceColumn: "DEP_ACCT_TYPE_CDE",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_DP_OZZ_ACCT_ARD_RAW",
    bronzeColumn: "DEP_ACCT_TYPE_CDE",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "DIM_DEPOSIT",
    silverColumn: "ACCOUNT_TYPE_CODE",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "VARCHAR(16777216)",
    businessLogic: "1:1 mapping (SAV, CHK, MMA, CD), also from FIS-DDW as ACCT_TYP_CDE",
    businessMeaning: "Account type code (Savings, Checking, MMA, CD)",
    mappingType: "Direct",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_DP_OZZ_ACCT_ARD_RAW",
    sourceColumn: "DEP_ACCT_TYPE_CDE",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_DP_OZZ_ACCT_ARD_RAW",
    bronzeColumn: "DEP_ACCT_TYPE_CDE",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "DIM_DEPOSIT",
    silverColumn: "ACCOUNT_TYPE_DESC",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "VARCHAR(16777216)",
    businessLogic: "Derived description from code mapping (Savings, Checking, Money Market, Certificate of Deposit)",
    businessMeaning: "Account type description",
    mappingType: "Derived",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_DP_OZZ_ACCT_ARD_RAW",
    sourceColumn: "DEP_PRODUCT_CDE",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_DP_OZZ_ACCT_ARD_RAW",
    bronzeColumn: "DEP_PRODUCT_CDE",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "DIM_DEPOSIT",
    silverColumn: "PRODUCT_CODE",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "VARCHAR(16777216)",
    businessLogic: "1:1 mapping, also from FIS-DDW as PRDCT_CDE",
    businessMeaning: "Product code classification",
    mappingType: "Direct",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_DP_OZZ_ACCT_ARD_RAW",
    sourceColumn: "DEP_PRODUCT_CDE",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_DP_OZZ_ACCT_ARD_RAW",
    bronzeColumn: "DEP_PRODUCT_CDE",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "DIM_DEPOSIT",
    silverColumn: "PRODUCT_NAME",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "VARCHAR(16777216)",
    businessLogic: "Derived from PRODUCT_CODE lookup to product reference table",
    businessMeaning: "Product name description",
    mappingType: "Derived",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_DP_OZZ_ACCT_ARD_RAW",
    sourceColumn: "DEP_ACCT_STATUS_CDE",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_DP_OZZ_ACCT_ARD_RAW",
    bronzeColumn: "DEP_ACCT_STATUS_CDE",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "DIM_DEPOSIT",
    silverColumn: "ACCOUNT_STATUS_CODE",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "VARCHAR(16777216)",
    businessLogic: "1:1 mapping (O=Open, C=Closed, D=Dormant, F=Frozen), also from FIS-DDW as STAT_CDE",
    businessMeaning: "Account status code",
    mappingType: "Direct",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_DP_OZZ_ACCT_ARD_RAW",
    sourceColumn: "DEP_ACCT_STATUS_CDE",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_DP_OZZ_ACCT_ARD_RAW",
    bronzeColumn: "DEP_ACCT_STATUS_CDE",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "DIM_DEPOSIT",
    silverColumn: "ACCOUNT_STATUS_DESC",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "VARCHAR(16777216)",
    businessLogic: "Derived description from code mapping (Open, Closed, Dormant, Frozen)",
    businessMeaning: "Account status description",
    mappingType: "Derived",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_DP_OZZ_ACCT_ARD_RAW",
    sourceColumn: "DEP_OPEN_DTE",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_DP_OZZ_ACCT_ARD_RAW",
    bronzeColumn: "DEP_OPEN_DTE",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "DIM_DEPOSIT",
    silverColumn: "OPEN_DATE",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "TIMESTAMP_NTZ(9)",
    businessLogic: "1:1 mapping, also from FIS-DDW as OPN_DTE",
    businessMeaning: "Date account was opened",
    mappingType: "Direct",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_DP_OZZ_ACCT_ARD_RAW",
    sourceColumn: "DEP_CLOSE_DTE",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_DP_OZZ_ACCT_ARD_RAW",
    bronzeColumn: "DEP_CLOSE_DTE",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "DIM_DEPOSIT",
    silverColumn: "CLOSE_DATE",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "TIMESTAMP_NTZ(9)",
    businessLogic: "1:1 mapping, also from FIS-DDW as CLS_DTE",
    businessMeaning: "Date account was closed",
    mappingType: "Direct",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_DP_OZZ_ACCT_ARD_RAW",
    sourceColumn: "DEP_MATURITY_DTE",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_DP_OZZ_ACCT_ARD_RAW",
    bronzeColumn: "DEP_MATURITY_DTE",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "DIM_DEPOSIT",
    silverColumn: "MATURITY_DATE",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "TIMESTAMP_NTZ(9)",
    businessLogic: "1:1 mapping (for CD/TD products), also from FIS-DDW as MTRTY_DTE",
    businessMeaning: "Maturity date for time deposits",
    mappingType: "Direct",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_DP_OZZ_ACCT_ARD_RAW",
    sourceColumn: "DEP_OFFICER_CDE",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_DP_OZZ_ACCT_ARD_RAW",
    bronzeColumn: "DEP_OFFICER_CDE",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "DIM_DEPOSIT",
    silverColumn: "OFFICER_CODE",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "VARCHAR(16777216)",
    businessLogic: "1:1 mapping, also from FIS-DDW as OFFCR_CDE",
    businessMeaning: "Account officer code",
    mappingType: "Direct",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_DP_OZZ_ACCT_ARD_RAW",
    sourceColumn: "DEP_OFFICER_CDE",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_DP_OZZ_ACCT_ARD_RAW",
    bronzeColumn: "DEP_OFFICER_CDE",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "DIM_DEPOSIT",
    silverColumn: "OFFICER_NAME",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "VARCHAR(16777216)",
    businessLogic: "Derived from OFFICER_CODE lookup to officer reference table",
    businessMeaning: "Account officer name",
    mappingType: "Derived",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_DP_OZZ_ACCT_ARD_RAW",
    sourceColumn: "DEP_BRANCH_CDE",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_DP_OZZ_ACCT_ARD_RAW",
    bronzeColumn: "DEP_BRANCH_CDE",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "DIM_DEPOSIT",
    silverColumn: "BRANCH_CODE",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "VARCHAR(16777216)",
    businessLogic: "1:1 mapping, also from FIS-DDW as BRNCH_CDE",
    businessMeaning: "Branch code where account is held",
    mappingType: "Direct",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_DP_OZZ_ACCT_ARD_RAW",
    sourceColumn: "DEP_BRANCH_CDE",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_DP_OZZ_ACCT_ARD_RAW",
    bronzeColumn: "DEP_BRANCH_CDE",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "DIM_DEPOSIT",
    silverColumn: "BRANCH_NAME",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "VARCHAR(16777216)",
    businessLogic: "Derived from BRANCH_CODE lookup to branch reference table",
    businessMeaning: "Branch name",
    mappingType: "Derived",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_DP_OZZ_ACCT_ARD_RAW",
    sourceColumn: "DEP_INTEREST_RATE",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_DP_OZZ_ACCT_ARD_RAW",
    bronzeColumn: "DEP_INTEREST_RATE",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "DIM_DEPOSIT",
    silverColumn: "INTEREST_RATE",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "NUMBER(38,5)",
    businessLogic: "1:1 mapping (decimal percentage), also from FIS-DDW as INTRST_RT",
    businessMeaning: "Current interest rate",
    mappingType: "Direct",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_DP_OZZ_ACCT_ARD_RAW",
    sourceColumn: "DEP_APY_RATE",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_DP_OZZ_ACCT_ARD_RAW",
    bronzeColumn: "DEP_APY_RATE",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "DIM_DEPOSIT",
    silverColumn: "APY_RATE",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "NUMBER(38,5)",
    businessLogic: "1:1 mapping (annual percentage yield), also from FIS-DDW as APY_RT",
    businessMeaning: "Annual Percentage Yield rate",
    mappingType: "Direct",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_DP_OZZ_ACCT_ARD_RAW",
    sourceColumn: "DEP_INTEREST_ACCR_METHOD_CDE",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_DP_OZZ_ACCT_ARD_RAW",
    bronzeColumn: "DEP_INTEREST_ACCR_METHOD_CDE",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "DIM_DEPOSIT",
    silverColumn: "INTEREST_ACCRUAL_METHOD_CODE",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "VARCHAR(16777216)",
    businessLogic: "1:1 mapping (Daily, Monthly, etc.), also from FIS-DDW as INT_ACCRL_MTHD_CDE",
    businessMeaning: "Interest accrual method code",
    mappingType: "Direct",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_DP_OZZ_ACCT_ARD_RAW",
    sourceColumn: "DEP_INTEREST_ACCR_METHOD_CDE",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_DP_OZZ_ACCT_ARD_RAW",
    bronzeColumn: "DEP_INTEREST_ACCR_METHOD_CDE",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "DIM_DEPOSIT",
    silverColumn: "INTEREST_ACCRUAL_METHOD_DESC",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "VARCHAR(16777216)",
    businessLogic: "Derived description from code mapping",
    businessMeaning: "Interest accrual method description",
    mappingType: "Derived",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_DP_OZZ_ACCT_ARD_RAW",
    sourceColumn: "DEP_COMPOUNDING_FREQ_CDE",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_DP_OZZ_ACCT_ARD_RAW",
    bronzeColumn: "DEP_COMPOUNDING_FREQ_CDE",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "DIM_DEPOSIT",
    silverColumn: "COMPOUNDING_FREQUENCY_CODE",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "VARCHAR(16777216)",
    businessLogic: "1:1 mapping (Daily, Monthly, Quarterly), also from FIS-DDW as CMPNDNG_FREQ_CDE",
    businessMeaning: "Interest compounding frequency code",
    mappingType: "Direct",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_DP_OZZ_ACCT_ARD_RAW",
    sourceColumn: "DEP_COMPOUNDING_FREQ_CDE",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_DP_OZZ_ACCT_ARD_RAW",
    bronzeColumn: "DEP_COMPOUNDING_FREQ_CDE",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "DIM_DEPOSIT",
    silverColumn: "COMPOUNDING_FREQUENCY_DESC",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "VARCHAR(16777216)",
    businessLogic: "Derived description from code mapping",
    businessMeaning: "Interest compounding frequency description",
    mappingType: "Derived",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_DP_OZZ_ACCT_ARD_RAW",
    sourceColumn: "DEP_TERM_MONTHS",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_DP_OZZ_ACCT_ARD_RAW",
    bronzeColumn: "DEP_TERM_MONTHS",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "DIM_DEPOSIT",
    silverColumn: "TERM_MONTHS",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "NUMBER(38,0)",
    businessLogic: "1:1 mapping (for CD/TD), also from FIS-DDW as TRM_MNTH_NBR",
    businessMeaning: "Term in months for time deposits",
    mappingType: "Direct",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_DP_OZZ_ACCT_ARD_RAW",
    sourceColumn: "DEP_ORIGINAL_AMOUNT",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_DP_OZZ_ACCT_ARD_RAW",
    bronzeColumn: "DEP_ORIGINAL_AMOUNT",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "DIM_DEPOSIT",
    silverColumn: "ORIGINAL_AMOUNT",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "NUMBER(38,2)",
    businessLogic: "1:1 mapping (for CD/TD opening amount), also from FIS-DDW as ORGNL_AMT",
    businessMeaning: "Original deposit amount",
    mappingType: "Direct",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_DP_OZZ_ACCT_ARD_RAW",
    sourceColumn: "DEP_MINIMUM_BALANCE_AMT",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_DP_OZZ_ACCT_ARD_RAW",
    bronzeColumn: "DEP_MINIMUM_BALANCE_AMT",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "DIM_DEPOSIT",
    silverColumn: "MINIMUM_BALANCE_AMOUNT",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "NUMBER(38,2)",
    businessLogic: "1:1 mapping, also from FIS-DDW as MIN_BAL_AMT",
    businessMeaning: "Minimum balance requirement",
    mappingType: "Direct",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_DP_OZZ_ACCT_ARD_RAW",
    sourceColumn: "DEP_OVERDRAFT_LIMIT_AMT",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_DP_OZZ_ACCT_ARD_RAW",
    bronzeColumn: "DEP_OVERDRAFT_LIMIT_AMT",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "DIM_DEPOSIT",
    silverColumn: "OVERDRAFT_LIMIT_AMOUNT",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "NUMBER(38,2)",
    businessLogic: "1:1 mapping, also from FIS-DDW as OVRDRFT_LMT_AMT",
    businessMeaning: "Overdraft protection limit",
    mappingType: "Direct",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_DP_OZZ_ACCT_ARD_RAW",
    sourceColumn: "DEP_FEE_WAIVER_FLG",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_DP_OZZ_ACCT_ARD_RAW",
    bronzeColumn: "DEP_FEE_WAIVER_FLG",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "DIM_DEPOSIT",
    silverColumn: "FEE_WAIVER_FLAG",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "VARCHAR(16777216)",
    businessLogic: "1:1 mapping (Y/N), also from FIS-DDW as FEE_WVIR_IND",
    businessMeaning: "Indicates if fees are waived",
    mappingType: "Direct",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_DP_OZZ_ACCT_ARD_RAW",
    sourceColumn: "DEP_STATEMENT_CYCLE_CDE",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_DP_OZZ_ACCT_ARD_RAW",
    bronzeColumn: "DEP_STATEMENT_CYCLE_CDE",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "DIM_DEPOSIT",
    silverColumn: "STATEMENT_CYCLE_CODE",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "VARCHAR(16777216)",
    businessLogic: "1:1 mapping (Monthly, Quarterly), also from FIS-DDW as STMT_CYCL_CDE",
    businessMeaning: "Statement cycle frequency code",
    mappingType: "Direct",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_DP_OZZ_ACCT_ARD_RAW",
    sourceColumn: "DEP_COST_CENTER_CDE",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_DP_OZZ_ACCT_ARD_RAW",
    bronzeColumn: "DEP_COST_CENTER_CDE",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "DIM_DEPOSIT",
    silverColumn: "COST_CENTER_CODE",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "VARCHAR(16777216)",
    businessLogic: "1:1 mapping, also from FIS-DDW as CST_CNTR_CDE",
    businessMeaning: "Cost center code for accounting",
    mappingType: "Direct",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_DP_OZZ_ACCT_ARD_RAW",
    sourceColumn: "DEP_GL_ACCOUNT_CDE",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_DP_OZZ_ACCT_ARD_RAW",
    bronzeColumn: "DEP_GL_ACCOUNT_CDE",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "DIM_DEPOSIT",
    silverColumn: "GL_ACCOUNT_CODE",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "VARCHAR(16777216)",
    businessLogic: "1:1 mapping, also from FIS-DDW as GL_ACCT_CDE",
    businessMeaning: "General ledger account code",
    mappingType: "Direct",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_DP_OZZ_ACCT_ARD_RAW",
    sourceColumn: "DEP_USER_CODE_1",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_DP_OZZ_ACCT_ARD_RAW",
    bronzeColumn: "DEP_USER_CODE_1",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "DIM_DEPOSIT",
    silverColumn: "USER_CODE_1",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "VARCHAR(16777216)",
    businessLogic: "1:1 mapping, also from FIS-DDW as USR_CDE_1",
    businessMeaning: "Custom user-defined code field 1",
    mappingType: "Direct",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_DP_OZZ_ACCT_ARD_RAW",
    sourceColumn: "DEP_USER_CODE_2",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_DP_OZZ_ACCT_ARD_RAW",
    bronzeColumn: "DEP_USER_CODE_2",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "DIM_DEPOSIT",
    silverColumn: "USER_CODE_2",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "VARCHAR(16777216)",
    businessLogic: "1:1 mapping, also from FIS-DDW as USR_CDE_2",
    businessMeaning: "Custom user-defined code field 2",
    mappingType: "Direct",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_DP_OZZ_ACCT_ARD_RAW",
    sourceColumn: "DEP_USER_CODE_3",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_DP_OZZ_ACCT_ARD_RAW",
    bronzeColumn: "DEP_USER_CODE_3",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "DIM_DEPOSIT",
    silverColumn: "USER_CODE_3",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "VARCHAR(16777216)",
    businessLogic: "1:1 mapping, also from FIS-DDW as USR_CDE_3",
    businessMeaning: "Custom user-defined code field 3",
    mappingType: "Direct",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_DP_OZZ_ACCT_ARD_RAW",
    sourceColumn: "DEP_USER_CODE_4",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_DP_OZZ_ACCT_ARD_RAW",
    bronzeColumn: "DEP_USER_CODE_4",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "DIM_DEPOSIT",
    silverColumn: "USER_CODE_4",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "VARCHAR(16777216)",
    businessLogic: "1:1 mapping, also from FIS-DDW as USR_CDE_4",
    businessMeaning: "Custom user-defined code field 4",
    mappingType: "Direct",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_DP_OZZ_ACCT_ARD_RAW",
    sourceColumn: "DEP_USER_CODE_5",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_DP_OZZ_ACCT_ARD_RAW",
    bronzeColumn: "DEP_USER_CODE_5",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "DIM_DEPOSIT",
    silverColumn: "USER_CODE_5",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "VARCHAR(16777216)",
    businessLogic: "1:1 mapping, also from FIS-DDW as USR_CDE_5",
    businessMeaning: "Custom user-defined code field 5",
    mappingType: "Direct",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_DP_OZZ_ACCT_ARD_RAW",
    sourceColumn: "DEP_USER_CODE_6",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_DP_OZZ_ACCT_ARD_RAW",
    bronzeColumn: "DEP_USER_CODE_6",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "DIM_DEPOSIT",
    silverColumn: "USER_CODE_6",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "VARCHAR(16777216)",
    businessLogic: "1:1 mapping, also from FIS-DDW as USR_CDE_6",
    businessMeaning: "Custom user-defined code field 6",
    mappingType: "Direct",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_DP_OZZ_ACCT_ARD_RAW",
    sourceColumn: "DEP_USER_CODE_7",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_DP_OZZ_ACCT_ARD_RAW",
    bronzeColumn: "DEP_USER_CODE_7",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "DIM_DEPOSIT",
    silverColumn: "USER_CODE_7",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "VARCHAR(16777216)",
    businessLogic: "1:1 mapping, also from FIS-DDW as USR_CDE_7",
    businessMeaning: "Custom user-defined code field 7",
    mappingType: "Direct",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_DP_OZZ_ACCT_ARD_RAW",
    sourceColumn: "DEP_USER_CODE_8",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_DP_OZZ_ACCT_ARD_RAW",
    bronzeColumn: "DEP_USER_CODE_8",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "DIM_DEPOSIT",
    silverColumn: "USER_CODE_8",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "VARCHAR(16777216)",
    businessLogic: "1:1 mapping, also from FIS-DDW as USR_CDE_8",
    businessMeaning: "Custom user-defined code field 8",
    mappingType: "Direct",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_DP_OZZ_ACCT_ARD_RAW",
    sourceColumn: "DEP_USER_CODE_9",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_DP_OZZ_ACCT_ARD_RAW",
    bronzeColumn: "DEP_USER_CODE_9",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "DIM_DEPOSIT",
    silverColumn: "USER_CODE_9",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "VARCHAR(16777216)",
    businessLogic: "1:1 mapping, also from FIS-DDW as USR_CDE_9",
    businessMeaning: "Custom user-defined code field 9",
    mappingType: "Direct",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_DP_OZZ_ACCT_ARD_RAW",
    sourceColumn: "DEP_USER_CODE_10",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_DP_OZZ_ACCT_ARD_RAW",
    bronzeColumn: "DEP_USER_CODE_10",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "DIM_DEPOSIT",
    silverColumn: "USER_CODE_10",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "VARCHAR(16777216)",
    businessLogic: "1:1 mapping, also from FIS-DDW as USR_CDE_10",
    businessMeaning: "Custom user-defined code field 10",
    mappingType: "Direct",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_DP_OZZ_ACCT_ARD_RAW",
    sourceColumn: "DEP_ESCHEAT_FLG",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_DP_OZZ_ACCT_ARD_RAW",
    bronzeColumn: "DEP_ESCHEAT_FLG",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "DIM_DEPOSIT",
    silverColumn: "ESCHEAT_FLAG",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "VARCHAR(16777216)",
    businessLogic: "1:1 mapping (Y/N), also from FIS-DDW as ESCHT_IND",
    businessMeaning: "Indicates if account is subject to escheatment",
    mappingType: "Direct",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_DP_OZZ_ACCT_ARD_RAW",
    sourceColumn: "DEP_ESCHEAT_DTE",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_DP_OZZ_ACCT_ARD_RAW",
    bronzeColumn: "DEP_ESCHEAT_DTE",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "DIM_DEPOSIT",
    silverColumn: "ESCHEAT_DATE",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "TIMESTAMP_NTZ(9)",
    businessLogic: "1:1 mapping, also from FIS-DDW as ESCHT_DTE",
    businessMeaning: "Escheatment date",
    mappingType: "Direct",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_DP_OZZ_ACCT_ARD_RAW",
    sourceColumn: "DEP_DORMANT_FLG",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_DP_OZZ_ACCT_ARD_RAW",
    bronzeColumn: "DEP_DORMANT_FLG",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "DIM_DEPOSIT",
    silverColumn: "DORMANT_FLAG",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "VARCHAR(16777216)",
    businessLogic: "1:1 mapping (Y/N), also from FIS-DDW as DRMNT_IND",
    businessMeaning: "Indicates if account is dormant",
    mappingType: "Direct",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_DP_OZZ_ACCT_ARD_RAW",
    sourceColumn: "DEP_DORMANT_DTE",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_DP_OZZ_ACCT_ARD_RAW",
    bronzeColumn: "DEP_DORMANT_DTE",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "DIM_DEPOSIT",
    silverColumn: "DORMANT_DATE",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "TIMESTAMP_NTZ(9)",
    businessLogic: "1:1 mapping, also from FIS-DDW as DRMNT_DTE",
    businessMeaning: "Date account became dormant",
    mappingType: "Direct",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_DP_OZZ_ACCT_ARD_RAW",
    sourceColumn: "DEP_LAST_TRANSACTION_DTE",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_DP_OZZ_ACCT_ARD_RAW",
    bronzeColumn: "DEP_LAST_TRANSACTION_DTE",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "DIM_DEPOSIT",
    silverColumn: "LAST_TRANSACTION_DATE",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "TIMESTAMP_NTZ(9)",
    businessLogic: "1:1 mapping, also from FIS-DDW as LST_TXN_DTE",
    businessMeaning: "Date of last transaction",
    mappingType: "Direct",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_DP_OZZ_ACCT_ARD_RAW",
    sourceColumn: "DEP_LAST_STATEMENT_DTE",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_DP_OZZ_ACCT_ARD_RAW",
    bronzeColumn: "DEP_LAST_STATEMENT_DTE",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "DIM_DEPOSIT",
    silverColumn: "LAST_STATEMENT_DATE",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "TIMESTAMP_NTZ(9)",
    businessLogic: "1:1 mapping, also from FIS-DDW as LST_STMT_DTE",
    businessMeaning: "Date of last statement",
    mappingType: "Direct",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_DP_OZZ_ACCT_ARD_RAW",
    sourceColumn: "DEP_AUTO_RENEWAL_FLG",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_DP_OZZ_ACCT_ARD_RAW",
    bronzeColumn: "DEP_AUTO_RENEWAL_FLG",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "DIM_DEPOSIT",
    silverColumn: "AUTO_RENEWAL_FLAG",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "VARCHAR(16777216)",
    businessLogic: "1:1 mapping (Y/N, for CD/TD auto-renewal), also from FIS-DDW as AUTO_RNWL_IND",
    businessMeaning: "Indicates if CD/TD auto-renews at maturity",
    mappingType: "Direct",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_DP_OZZ_ACCT_ARD_RAW",
    sourceColumn: "DEP_PENALTY_AMOUNT",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_DP_OZZ_ACCT_ARD_RAW",
    bronzeColumn: "DEP_PENALTY_AMOUNT",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "DIM_DEPOSIT",
    silverColumn: "EARLY_WITHDRAWAL_PENALTY_AMOUNT",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "NUMBER(38,2)",
    businessLogic: "1:1 mapping (for CD/TD early withdrawal), also from FIS-DDW as PNLTY_AMT",
    businessMeaning: "Early withdrawal penalty amount",
    mappingType: "Direct",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_DP_OZZ_ACCT_ARD_RAW",
    sourceColumn: "DEP_INTEREST_PAID_YTD_AMT",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_DP_OZZ_ACCT_ARD_RAW",
    bronzeColumn: "DEP_INTEREST_PAID_YTD_AMT",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "DIM_DEPOSIT",
    silverColumn: "INTEREST_PAID_YTD_AMOUNT",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "NUMBER(38,2)",
    businessLogic: "1:1 mapping (year-to-date interest paid), also from FIS-DDW as INT_PD_YTD_AMT",
    businessMeaning: "Year-to-date interest paid amount",
    mappingType: "Direct",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_DP_OZZ_ACCT_ARD_RAW",
    sourceColumn: "DEP_RATE_INDEX_CDE",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_DP_OZZ_ACCT_ARD_RAW",
    bronzeColumn: "DEP_RATE_INDEX_CDE",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "DIM_DEPOSIT",
    silverColumn: "RATE_INDEX_CODE",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "VARCHAR(16777216)",
    businessLogic: "1:1 mapping (for variable rate accounts), also from FIS-DDW as RT_INDX_CDE",
    businessMeaning: "Rate index code for variable rates",
    mappingType: "Direct",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_DP_OZZ_ACCT_ARD_RAW",
    sourceColumn: "DEP_RATE_MARGIN_PCT",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_DP_OZZ_ACCT_ARD_RAW",
    bronzeColumn: "DEP_RATE_MARGIN_PCT",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "DIM_DEPOSIT",
    silverColumn: "RATE_MARGIN_PERCENT",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "NUMBER(38,5)",
    businessLogic: "1:1 mapping (margin over index rate), also from FIS-DDW as RT_MRGN_PCT",
    businessMeaning: "Rate margin percentage over index",
    mappingType: "Direct",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_DP_OZZ_ACCT_ARD_RAW",
    sourceColumn: "DEP_ONLINE_BANKING_FLG",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_DP_OZZ_ACCT_ARD_RAW",
    bronzeColumn: "DEP_ONLINE_BANKING_FLG",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "DIM_DEPOSIT",
    silverColumn: "ONLINE_BANKING_FLAG",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "VARCHAR(16777216)",
    businessLogic: "1:1 mapping (Y/N), also from FIS-DDW as ONLN_BNKNG_IND",
    businessMeaning: "Indicates if online banking is enabled",
    mappingType: "Direct",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_DP_OZZ_ACCT_ARD_RAW",
    sourceColumn: "DEP_MOBILE_BANKING_FLG",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_DP_OZZ_ACCT_ARD_RAW",
    bronzeColumn: "DEP_MOBILE_BANKING_FLG",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "DIM_DEPOSIT",
    silverColumn: "MOBILE_BANKING_FLAG",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "VARCHAR(16777216)",
    businessLogic: "1:1 mapping (Y/N), also from FIS-DDW as MOBL_BNKNG_IND",
    businessMeaning: "Indicates if mobile banking is enabled",
    mappingType: "Direct",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_DP_OZZ_ACCT_ARD_RAW",
    sourceColumn: "DEP_EBANKING_ENROLLMENT_DTE",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_DP_OZZ_ACCT_ARD_RAW",
    bronzeColumn: "DEP_EBANKING_ENROLLMENT_DTE",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "DIM_DEPOSIT",
    silverColumn: "EBANKING_ENROLLMENT_DATE",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "TIMESTAMP_NTZ(9)",
    businessLogic: "1:1 mapping, also from FIS-DDW as EBNKNG_ENRL_DTE",
    businessMeaning: "Electronic banking enrollment date",
    mappingType: "Direct",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_DP_OZZ_ACCT_ARD_RAW",
    sourceColumn: "DEP_PAPERLESS_STATEMENT_FLG",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_DP_OZZ_ACCT_ARD_RAW",
    bronzeColumn: "DEP_PAPERLESS_STATEMENT_FLG",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "DIM_DEPOSIT",
    silverColumn: "PAPERLESS_STATEMENT_FLAG",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "VARCHAR(16777216)",
    businessLogic: "1:1 mapping (Y/N), also from FIS-DDW as PPRLS_STMT_IND",
    businessMeaning: "Indicates if customer opted for paperless statements",
    mappingType: "Direct",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_DP_OZZ_ACCT_ARD_RAW",
    sourceColumn: "DEP_IRA_TYPE_CDE",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_DP_OZZ_ACCT_ARD_RAW",
    bronzeColumn: "DEP_IRA_TYPE_CDE",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "DIM_DEPOSIT",
    silverColumn: "IRA_TYPE_CODE",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "VARCHAR(16777216)",
    businessLogic: "1:1 mapping (TRAD, ROTH, SEP, etc.), also from FIS-DDW as IRA_TYP_CDE",
    businessMeaning: "IRA type code if applicable (Traditional, Roth, SEP, etc.)",
    mappingType: "Direct",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_DP_OZZ_ACCT_ARD_RAW",
    sourceColumn: "DEP_IRA_TYPE_CDE",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_DP_OZZ_ACCT_ARD_RAW",
    bronzeColumn: "DEP_IRA_TYPE_CDE",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "DIM_DEPOSIT",
    silverColumn: "IRA_TYPE_DESC",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "VARCHAR(16777216)",
    businessLogic: "Derived description from code mapping (Traditional IRA, Roth IRA, SEP IRA, etc.)",
    businessMeaning: "IRA type description",
    mappingType: "Derived",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "TB_DP_OZZ_ACCT_ARD_RAW",
    sourceColumn: "DEP_LAST_CHG_DTE",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "TB_DP_OZZ_ACCT_ARD_RAW",
    bronzeColumn: "DEP_LAST_CHG_DTE",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "DIM_DEPOSIT",
    silverColumn: "EFFECTIVE_START_DATE",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "TIMESTAMP_NTZ(9)",
    businessLogic: "SCD2 effective start date from last deposit change date, also from FIS-DDW as EFF_DTE",
    businessMeaning: "Date this deposit version became effective",
    mappingType: "SCD2",
  },
  {
    sourceSystem: "SYSTEM",
    sourceTable: "N/A",
    sourceColumn: "SCD2_LOGIC",
    bronzeSchema: "N/A",
    bronzeTable: "N/A",
    bronzeColumn: "N/A",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "DIM_DEPOSIT",
    silverColumn: "EFFECTIVE_END_DATE",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "TIMESTAMP_NTZ(9)",
    businessLogic: "COALESCE(LEAD(EFFECTIVE_START_DATE) OVER (PARTITION BY ACCOUNT_NUMBER ORDER BY EFFECTIVE_START_DATE), '9999-12-31')",
    businessMeaning: "Date this deposit version expired (9999-12-31 for current)",
    mappingType: "SCD2",
  },
  {
    sourceSystem: "SYSTEM",
    sourceTable: "N/A",
    sourceColumn: "DERIVED",
    bronzeSchema: "N/A",
    bronzeTable: "N/A",
    bronzeColumn: "N/A",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "DIM_DEPOSIT",
    silverColumn: "RECORD_FLAG",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "VARCHAR(16777216)",
    businessLogic: "CASE WHEN EFFECTIVE_END_DATE::DATE = TO_DATE('9999-12-31') THEN 'A' ELSE 'I' END",
    businessMeaning: "Active/Inactive record flag",
    mappingType: "Derived",
  },
  {
    sourceSystem: "FIS-ADS",
    sourceTable: "VW_TB_DP_DYY_C2_ACCT_SCD_DIM",
    sourceColumn: "PRCS_DTE",
    bronzeSchema: "FIS_ADS",
    bronzeTable: "VW_TB_DP_DYY_C2_ACCT_SCD_DIM",
    bronzeColumn: "PRCS_DTE",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "DIM_DEPOSIT",
    silverColumn: "BUSINESS_DATE",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "TIMESTAMP_NTZ(9)",
    businessLogic: "1:1 mapping from FIS processing date, also from FIS-DDW as EFF_DTE",
    businessMeaning: "Business processing date",
    mappingType: "Direct",
  },
  {
    sourceSystem: "SYSTEM",
    sourceTable: "N/A",
    sourceColumn: "HASH_FUNCTION",
    bronzeSchema: "N/A",
    bronzeTable: "N/A",
    bronzeColumn: "N/A",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "DIM_DEPOSIT",
    silverColumn: "ROW_HASH",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "VARCHAR(16777216)",
    businessLogic: "HASH(all deposit attribute columns for SCD2 change detection)",
    businessMeaning: "Hash of all deposit columns for SCD2 change detection",
    mappingType: "Derived",
  },
  {
    sourceSystem: "SYSTEM",
    sourceTable: "N/A",
    sourceColumn: "CURRENT_USER()",
    bronzeSchema: "N/A",
    bronzeTable: "N/A",
    bronzeColumn: "N/A",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "DIM_DEPOSIT",
    silverColumn: "INSERT_BY",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "VARCHAR(16777216)",
    businessLogic: "CURRENT_USER() on insert",
    businessMeaning: "User who inserted the record",
    mappingType: "System",
  },
  {
    sourceSystem: "SYSTEM",
    sourceTable: "N/A",
    sourceColumn: "CURRENT_TIMESTAMP()",
    bronzeSchema: "N/A",
    bronzeTable: "N/A",
    bronzeColumn: "N/A",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "DIM_DEPOSIT",
    silverColumn: "INSERT_DT",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "TIMESTAMP_NTZ(9)",
    businessLogic: "CURRENT_TIMESTAMP() on insert",
    businessMeaning: "Timestamp when record was inserted",
    mappingType: "System",
  },
  {
    sourceSystem: "SYSTEM",
    sourceTable: "N/A",
    sourceColumn: "CURRENT_USER()",
    bronzeSchema: "N/A",
    bronzeTable: "N/A",
    bronzeColumn: "N/A",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "DIM_DEPOSIT",
    silverColumn: "LAST_MODIFIED_BY",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "VARCHAR(16777216)",
    businessLogic: "CURRENT_USER() on update",
    businessMeaning: "User who last modified the record",
    mappingType: "System",
  },
  {
    sourceSystem: "SYSTEM",
    sourceTable: "N/A",
    sourceColumn: "CURRENT_TIMESTAMP()",
    bronzeSchema: "N/A",
    bronzeTable: "N/A",
    bronzeColumn: "N/A",
    silverSchema: "CORE_DEPOSIT",
    silverTable: "DIM_DEPOSIT",
    silverColumn: "LAST_MODIFIED_DT",
    goldSchema: "ANALYTICS",
    goldTable: "CUSTOMER_DEPOSIT_AGGR",
    goldColumn: null,
    dataType: "TIMESTAMP_NTZ(9)",
    businessLogic: "CURRENT_TIMESTAMP() on update",
    businessMeaning: "Timestamp when record was last modified",
    mappingType: "System",
  },
];

export default dimDepositMappings;
