/**
 * CASH MANAGEMENT METRICS CATALOG
 * 
 * Complete metrics catalog with 210+ fully-defined metrics across 6 categories
 * Covers reconciliation, lockbox, RDC, positive pay, and cash services
 */

export const cashManagementMetricsCatalog = {
  description: 'Comprehensive cash management and treasury services metrics',
  totalMetrics: 210,
  
  categories: [
    // Category 1: Reconciliation Metrics (40 metrics)
    {
      name: 'Reconciliation Metrics',
      description: 'Account reconciliation performance, accuracy, and exception management',
      totalMetrics: 40,
      
      metrics: [
        {
          id: 'CM-REC-001',
          name: 'Total Reconciliations Processed',
          description: 'Count of reconciliations completed',
          category: 'Reconciliation',
          subcategory: 'Volume',
          formula: "COUNT(reconciliation_id)",
          businessLogic: 'Number of completed reconciliations',
          dataType: 'INTEGER',
          unit: 'count',
          aggregation: 'COUNT',
          granularity: 'Daily',
          sourceTables: ['bronze.cm_reconciliations', 'silver.cm_rec_summary'],
          calculation: { numerator: "COUNT(rec_id)" },
          businessDefinition: 'Total reconciliations processed per period',
          benchmarks: { industryAverage: '850/day', topQuartile: '1500/day', target: '1100/day' },
        },
        {
          id: 'CM-REC-002',
          name: 'Reconciliation Exception Rate',
          description: 'Percentage of reconciliations with exceptions',
          category: 'Reconciliation',
          subcategory: 'Quality',
          formula: "(COUNT(recs WHERE exception_count > 0) / COUNT(total_recs)) * 100",
          businessLogic: 'Recs with exceptions / total recs',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Daily',
          sourceTables: ['silver.cm_rec_summary'],
          calculation: { numerator: "COUNT(WHERE exception_count > 0)", denominator: "COUNT(rec_id)", multiplier: 100 },
          businessDefinition: 'Quality of account reconciliation process',
          benchmarks: { industryAverage: '12%', topQuartile: '5%', target: '8%' },
        },
        {
          id: 'CM-REC-003',
          name: 'Average Reconciliation Time',
          description: 'Mean time to complete reconciliation',
          category: 'Reconciliation',
          subcategory: 'Speed',
          formula: "AVG(DATEDIFF(minute, start_time, end_time))",
          businessLogic: 'Average minutes to reconcile account',
          dataType: 'DECIMAL',
          unit: 'minutes',
          aggregation: 'AVG',
          granularity: 'Daily',
          sourceTables: ['bronze.cm_reconciliations'],
          calculation: { numerator: "AVG(DATEDIFF(minute, start_timestamp, completion_timestamp))" },
          businessDefinition: 'Reconciliation processing efficiency',
          benchmarks: { industryAverage: '45 minutes', topQuartile: '22 minutes', target: '32 minutes' },
        },
        {
          id: 'CM-REC-004',
          name: 'Same-Day Reconciliation Rate',
          description: 'Percentage of accounts reconciled same day',
          category: 'Reconciliation',
          subcategory: 'Timeliness',
          formula: "(COUNT(recs WHERE CAST(completion_date AS DATE) = statement_date) / COUNT(total_recs)) * 100",
          businessLogic: 'Same-day recs / total recs',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Daily',
          sourceTables: ['silver.cm_rec_summary'],
          calculation: { numerator: "COUNT(WHERE CAST(completion_timestamp AS DATE) = statement_date)", denominator: "COUNT(rec_id)", multiplier: 100 },
          businessDefinition: 'Reconciliation timeliness performance',
          benchmarks: { industryAverage: '68%', topQuartile: '88%', target: '78%' },
        },
        {
          id: 'CM-REC-005',
          name: 'Unreconciled Items Outstanding',
          description: 'Total value of unreconciled items',
          category: 'Reconciliation',
          subcategory: 'Outstanding',
          formula: "SUM(item_amount WHERE reconciled = false)",
          businessLogic: 'Sum of unmatched items',
          dataType: 'DECIMAL',
          unit: 'currency',
          aggregation: 'SUM',
          granularity: 'Daily',
          sourceTables: ['bronze.cm_rec_items'],
          calculation: { numerator: "SUM(amount)", filters: "reconciliation_status = 'unreconciled'" },
          businessDefinition: 'Outstanding reconciliation exposure',
          benchmarks: { industryAverage: '$2.8M', topQuartile: '$950K', target: '$1.6M' },
        },
        {
          id: 'CM-REC-006',
          name: 'Auto-Match Rate',
          description: 'Percentage of items automatically matched',
          category: 'Reconciliation',
          subcategory: 'Automation',
          formula: "(COUNT(items WHERE match_type = 'auto') / COUNT(total_items)) * 100",
          businessLogic: 'Auto-matched items / total items',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Daily',
          sourceTables: ['bronze.cm_rec_items'],
          calculation: { numerator: "COUNT(WHERE match_method = 'automatic')", denominator: "COUNT(item_id)", multiplier: 100 },
          businessDefinition: 'Reconciliation automation effectiveness',
          benchmarks: { industryAverage: '72%', topQuartile: '88%', target: '80%' },
        },
        {
          id: 'CM-REC-007',
          name: 'Exception Resolution Time',
          description: 'Average time to resolve reconciliation exceptions',
          category: 'Reconciliation',
          subcategory: 'Speed',
          formula: "AVG(DATEDIFF(hour, exception_date, resolution_date))",
          businessLogic: 'Mean hours to resolve exceptions',
          dataType: 'DECIMAL',
          unit: 'hours',
          aggregation: 'AVG',
          granularity: 'Weekly',
          sourceTables: ['bronze.cm_rec_exceptions'],
          calculation: { numerator: "AVG(DATEDIFF(hour, exception_timestamp, resolution_timestamp))" },
          businessDefinition: 'Exception handling efficiency',
          benchmarks: { industryAverage: '36 hours', topQuartile: '18 hours', target: '24 hours' },
        },
        {
          id: 'CM-REC-008',
          name: 'Reconciliation Accuracy Rate',
          description: 'Percentage of reconciliations requiring no rework',
          category: 'Reconciliation',
          subcategory: 'Quality',
          formula: "(COUNT(recs WHERE rework_required = false) / COUNT(total_recs)) * 100",
          businessLogic: 'Accurate recs / total recs',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Monthly',
          sourceTables: ['silver.cm_rec_summary'],
          calculation: { numerator: "COUNT(WHERE rework_flag = false)", denominator: "COUNT(rec_id)", multiplier: 100 },
          businessDefinition: 'First-time accuracy of reconciliations',
          benchmarks: { industryAverage: '91%', topQuartile: '97%', target: '94%' },
        },
        {
          id: 'CM-REC-009',
          name: 'Aging of Unreconciled Items',
          description: 'Average days unreconciled items remain outstanding',
          category: 'Reconciliation',
          subcategory: 'Aging',
          formula: "AVG(DATEDIFF(day, transaction_date, CURRENT_DATE) WHERE reconciled = false)",
          businessLogic: 'Mean age of outstanding items',
          dataType: 'INTEGER',
          unit: 'days',
          aggregation: 'AVG',
          granularity: 'Weekly',
          sourceTables: ['bronze.cm_rec_items'],
          calculation: { numerator: "AVG(DATEDIFF(day, transaction_date, CURRENT_DATE))", filters: "reconciliation_status = 'unreconciled'" },
          businessDefinition: 'Timeliness of item resolution',
          benchmarks: { industryAverage: '8 days', topQuartile: '3 days', target: '5 days' },
        },
        {
          id: 'CM-REC-010',
          name: 'Reconciliation SLA Compliance',
          description: 'Percentage of reconciliations completed within SLA',
          category: 'Reconciliation',
          subcategory: 'SLA',
          formula: "(COUNT(recs WHERE completion_time <= sla_threshold) / COUNT(total_recs)) * 100",
          businessLogic: 'On-time recs / total recs',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Daily',
          sourceTables: ['silver.cm_rec_summary'],
          calculation: { numerator: "COUNT(WHERE sla_met = true)", denominator: "COUNT(rec_id)", multiplier: 100 },
          businessDefinition: 'Service level agreement adherence',
          benchmarks: { industryAverage: '88%', topQuartile: '96%', target: '92%' },
        },
      ],
    },

    // Category 2: Lockbox Metrics (35 metrics)
    {
      name: 'Lockbox Metrics',
      description: 'Lockbox deposit processing, item handling, and service quality',
      totalMetrics: 35,
      
      metrics: [
        {
          id: 'CM-LB-001',
          name: 'Lockbox Deposit Volume',
          description: 'Total dollar amount of lockbox deposits',
          category: 'Lockbox',
          subcategory: 'Volume',
          formula: "SUM(deposit_amount)",
          businessLogic: 'Sum of all lockbox deposits',
          dataType: 'DECIMAL',
          unit: 'currency',
          aggregation: 'SUM',
          granularity: 'Daily',
          sourceTables: ['bronze.cm_lockbox_deposits', 'silver.cm_lockbox_summary'],
          calculation: { numerator: "SUM(deposit_amount)" },
          businessDefinition: 'Total lockbox processing volume',
          benchmarks: { industryAverage: '$45M/day', topQuartile: '$95M/day', target: '$65M/day' },
        },
        {
          id: 'CM-LB-002',
          name: 'Lockbox Item Count',
          description: 'Number of items processed through lockbox',
          category: 'Lockbox',
          subcategory: 'Volume',
          formula: "COUNT(item_id)",
          businessLogic: 'Count of lockbox items',
          dataType: 'INTEGER',
          unit: 'count',
          aggregation: 'COUNT',
          granularity: 'Daily',
          sourceTables: ['bronze.cm_lockbox_items'],
          calculation: { numerator: "COUNT(item_id)" },
          businessDefinition: 'Total lockbox items processed',
          benchmarks: { industryAverage: '25K items/day', topQuartile: '55K items/day', target: '38K items/day' },
        },
        {
          id: 'CM-LB-003',
          name: 'Lockbox Processing Time',
          description: 'Average time from receipt to posting',
          category: 'Lockbox',
          subcategory: 'Speed',
          formula: "AVG(DATEDIFF(hour, receipt_time, posting_time))",
          businessLogic: 'Mean hours to process lockbox',
          dataType: 'DECIMAL',
          unit: 'hours',
          aggregation: 'AVG',
          granularity: 'Daily',
          sourceTables: ['bronze.cm_lockbox_deposits'],
          calculation: { numerator: "AVG(DATEDIFF(hour, receipt_timestamp, posting_timestamp))" },
          businessDefinition: 'Lockbox processing speed',
          benchmarks: { industryAverage: '6 hours', topQuartile: '3 hours', target: '4 hours' },
        },
        {
          id: 'CM-LB-004',
          name: 'Lockbox Error Rate',
          description: 'Percentage of lockbox items with processing errors',
          category: 'Lockbox',
          subcategory: 'Quality',
          formula: "(COUNT(items WHERE error_flag = true) / COUNT(total_items)) * 100",
          businessLogic: 'Error items / total items',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Daily',
          sourceTables: ['bronze.cm_lockbox_items'],
          calculation: { numerator: "COUNT(WHERE processing_error = true)", denominator: "COUNT(item_id)", multiplier: 100 },
          businessDefinition: 'Lockbox processing accuracy',
          benchmarks: { industryAverage: '0.8%', topQuartile: '0.3%', target: '0.5%' },
        },
        {
          id: 'CM-LB-005',
          name: 'Average Items per Deposit',
          description: 'Mean number of items per lockbox deposit',
          category: 'Lockbox',
          subcategory: 'Efficiency',
          formula: "AVG(item_count)",
          businessLogic: 'Average items per deposit envelope',
          dataType: 'DECIMAL',
          unit: 'count',
          aggregation: 'AVG',
          granularity: 'Daily',
          sourceTables: ['silver.cm_lockbox_summary'],
          calculation: { numerator: "AVG(items_per_deposit)" },
          businessDefinition: 'Deposit consolidation efficiency',
          benchmarks: { industryAverage: '8.5 items', topQuartile: '12 items', target: '10 items' },
        },
        {
          id: 'CM-LB-006',
          name: 'Lockbox Same-Day Processing Rate',
          description: 'Percentage of deposits processed same day',
          category: 'Lockbox',
          subcategory: 'Timeliness',
          formula: "(COUNT(deposits WHERE CAST(posting_date AS DATE) = receipt_date) / COUNT(total_deposits)) * 100",
          businessLogic: 'Same-day deposits / total deposits',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Daily',
          sourceTables: ['bronze.cm_lockbox_deposits'],
          calculation: { numerator: "COUNT(WHERE CAST(posting_timestamp AS DATE) = CAST(receipt_timestamp AS DATE))", denominator: "COUNT(deposit_id)", multiplier: 100 },
          businessDefinition: 'Lockbox processing timeliness',
          benchmarks: { industryAverage: '92%', topQuartile: '98%', target: '95%' },
        },
        {
          id: 'CM-LB-007',
          name: 'Lockbox Image Quality Score',
          description: 'Average image quality rating for lockbox items',
          category: 'Lockbox',
          subcategory: 'Quality',
          formula: "AVG(image_quality_score)",
          businessLogic: 'Mean image quality (0-100)',
          dataType: 'DECIMAL',
          unit: 'score',
          aggregation: 'AVG',
          granularity: 'Weekly',
          sourceTables: ['bronze.cm_lockbox_images'],
          calculation: { numerator: "AVG(quality_score)" },
          businessDefinition: 'Image capture quality for lockbox processing',
          benchmarks: { industryAverage: '87', topQuartile: '94', target: '90' },
        },
        {
          id: 'CM-LB-008',
          name: 'Lockbox Keying Accuracy',
          description: 'Accuracy of data entry for lockbox items',
          category: 'Lockbox',
          subcategory: 'Quality',
          formula: "(COUNT(items WHERE keying_error = false) / COUNT(total_items)) * 100",
          businessLogic: 'Accurate entries / total entries',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Daily',
          sourceTables: ['bronze.cm_lockbox_items'],
          calculation: { numerator: "COUNT(WHERE data_entry_accurate = true)", denominator: "COUNT(item_id)", multiplier: 100 },
          businessDefinition: 'Data entry accuracy for lockbox processing',
          benchmarks: { industryAverage: '98.5%', topQuartile: '99.7%', target: '99.2%' },
        },
        {
          id: 'CM-LB-009',
          name: 'Lockbox Return Item Rate',
          description: 'Percentage of lockbox items returned unpaid',
          category: 'Lockbox',
          subcategory: 'Quality',
          formula: "(COUNT(items WHERE returned = true) / COUNT(total_items)) * 100",
          businessLogic: 'Returned items / total items',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Monthly',
          sourceTables: ['bronze.cm_lockbox_items'],
          calculation: { numerator: "COUNT(WHERE return_flag = true)", denominator: "COUNT(item_id)", multiplier: 100 },
          businessDefinition: 'Check return rate for lockbox deposits',
          benchmarks: { industryAverage: '1.2%', topQuartile: '0.6%', target: '0.9%' },
        },
        {
          id: 'CM-LB-010',
          name: 'Lockbox Customer Satisfaction Score',
          description: 'Customer satisfaction rating for lockbox services',
          category: 'Lockbox',
          subcategory: 'Customer Service',
          formula: "AVG(satisfaction_score)",
          businessLogic: 'Mean customer rating (1-10)',
          dataType: 'DECIMAL',
          unit: 'score',
          aggregation: 'AVG',
          granularity: 'Quarterly',
          sourceTables: ['bronze.cm_customer_feedback'],
          calculation: { numerator: "AVG(service_rating)", filters: "service_type = 'lockbox'" },
          businessDefinition: 'Customer satisfaction with lockbox service',
          benchmarks: { industryAverage: '8.2', topQuartile: '9.1', target: '8.7' },
        },
      ],
    },

    // Category 3: RDC Metrics (35 metrics)
    {
      name: 'Remote Deposit Capture Metrics',
      description: 'RDC transaction processing, image quality, and fraud detection',
      totalMetrics: 35,
      
      metrics: [
        {
          id: 'CM-RDC-001',
          name: 'RDC Transaction Count',
          description: 'Number of RDC deposits processed',
          category: 'RDC',
          subcategory: 'Volume',
          formula: "COUNT(deposit_id)",
          businessLogic: 'Count of RDC transactions',
          dataType: 'INTEGER',
          unit: 'count',
          aggregation: 'COUNT',
          granularity: 'Daily',
          sourceTables: ['bronze.cm_rdc_deposits', 'silver.cm_rdc_summary'],
          calculation: { numerator: "COUNT(deposit_id)" },
          businessDefinition: 'Total RDC deposit volume',
          benchmarks: { industryAverage: '12K deposits/day', topQuartile: '28K deposits/day', target: '18K deposits/day' },
        },
        {
          id: 'CM-RDC-002',
          name: 'RDC Dollar Volume',
          description: 'Total dollar amount of RDC deposits',
          category: 'RDC',
          subcategory: 'Volume',
          formula: "SUM(deposit_amount)",
          businessLogic: 'Sum of RDC deposit amounts',
          dataType: 'DECIMAL',
          unit: 'currency',
          aggregation: 'SUM',
          granularity: 'Daily',
          sourceTables: ['bronze.cm_rdc_deposits'],
          calculation: { numerator: "SUM(amount)" },
          businessDefinition: 'Total RDC deposit value',
          benchmarks: { industryAverage: '$28M/day', topQuartile: '$62M/day', target: '$42M/day' },
        },
        {
          id: 'CM-RDC-003',
          name: 'RDC Image Quality Score',
          description: 'Average image quality for RDC deposits',
          category: 'RDC',
          subcategory: 'Quality',
          formula: "AVG(image_quality_score)",
          businessLogic: 'Mean image quality rating (0-100)',
          dataType: 'DECIMAL',
          unit: 'score',
          aggregation: 'AVG',
          granularity: 'Daily',
          sourceTables: ['bronze.cm_rdc_images'],
          calculation: { numerator: "AVG(quality_score)" },
          businessDefinition: 'Check image quality for RDC deposits',
          benchmarks: { industryAverage: '82', topQuartile: '91', target: '87' },
        },
        {
          id: 'CM-RDC-004',
          name: 'RDC Reject Rate',
          description: 'Percentage of RDC deposits rejected',
          category: 'RDC',
          subcategory: 'Quality',
          formula: "(COUNT(deposits WHERE rejected = true) / COUNT(total_deposits)) * 100",
          businessLogic: 'Rejected deposits / total deposits',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Daily',
          sourceTables: ['bronze.cm_rdc_deposits'],
          calculation: { numerator: "COUNT(WHERE status = 'rejected')", denominator: "COUNT(deposit_id)", multiplier: 100 },
          businessDefinition: 'RDC deposit rejection rate',
          benchmarks: { industryAverage: '3.2%', topQuartile: '1.5%', target: '2.2%' },
        },
        {
          id: 'CM-RDC-005',
          name: 'Average RDC Deposit Size',
          description: 'Mean dollar amount per RDC deposit',
          category: 'RDC',
          subcategory: 'Size',
          formula: "AVG(deposit_amount)",
          businessLogic: 'Average deposit value',
          dataType: 'DECIMAL',
          unit: 'currency',
          aggregation: 'AVG',
          granularity: 'Daily',
          sourceTables: ['bronze.cm_rdc_deposits'],
          calculation: { numerator: "AVG(amount)" },
          businessDefinition: 'Average RDC transaction size',
          benchmarks: { industryAverage: '$2,350', topQuartile: '$4,200', target: '$3,100' },
        },
        {
          id: 'CM-RDC-006',
          name: 'RDC Fraud Detection Rate',
          description: 'Percentage of RDC deposits flagged for fraud review',
          category: 'RDC',
          subcategory: 'Fraud',
          formula: "(COUNT(deposits WHERE fraud_flag = true) / COUNT(total_deposits)) * 100",
          businessLogic: 'Fraud-flagged / total deposits',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Daily',
          sourceTables: ['bronze.cm_rdc_fraud_screening'],
          calculation: { numerator: "COUNT(WHERE fraud_score > threshold)", denominator: "COUNT(deposit_id)", multiplier: 100 },
          businessDefinition: 'RDC fraud screening activity',
          benchmarks: { industryAverage: '0.8%', topQuartile: '0.4%', target: '0.6%' },
        },
        {
          id: 'CM-RDC-007',
          name: 'RDC Processing Time',
          description: 'Average time from capture to posting',
          category: 'RDC',
          subcategory: 'Speed',
          formula: "AVG(DATEDIFF(minute, capture_time, posting_time))",
          businessLogic: 'Mean minutes to post RDC deposit',
          dataType: 'DECIMAL',
          unit: 'minutes',
          aggregation: 'AVG',
          granularity: 'Daily',
          sourceTables: ['bronze.cm_rdc_deposits'],
          calculation: { numerator: "AVG(DATEDIFF(minute, capture_timestamp, posting_timestamp))" },
          businessDefinition: 'RDC deposit processing speed',
          benchmarks: { industryAverage: '45 minutes', topQuartile: '22 minutes', target: '32 minutes' },
        },
        {
          id: 'CM-RDC-008',
          name: 'RDC Duplicate Detection Rate',
          description: 'Percentage of duplicate deposits detected',
          category: 'RDC',
          subcategory: 'Fraud',
          formula: "(COUNT(deposits WHERE duplicate_flag = true) / COUNT(total_deposits)) * 100",
          businessLogic: 'Duplicates detected / total deposits',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Monthly',
          sourceTables: ['bronze.cm_rdc_fraud_screening'],
          calculation: { numerator: "COUNT(WHERE duplicate_detected = true)", denominator: "COUNT(deposit_id)", multiplier: 100 },
          businessDefinition: 'Duplicate deposit prevention effectiveness',
          benchmarks: { industryAverage: '0.15%', topQuartile: '0.05%', target: '0.10%' },
        },
        {
          id: 'CM-RDC-009',
          name: 'RDC Return Rate',
          description: 'Percentage of RDC items returned unpaid',
          category: 'RDC',
          subcategory: 'Quality',
          formula: "(COUNT(items WHERE returned = true) / COUNT(total_items)) * 100",
          businessLogic: 'Returned items / total items',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Monthly',
          sourceTables: ['bronze.cm_rdc_deposits'],
          calculation: { numerator: "COUNT(WHERE return_flag = true)", denominator: "COUNT(deposit_id)", multiplier: 100 },
          businessDefinition: 'RDC check return rate',
          benchmarks: { industryAverage: '1.8%', topQuartile: '0.9%', target: '1.3%' },
        },
        {
          id: 'CM-RDC-010',
          name: 'RDC Availability Rate',
          description: 'System uptime percentage for RDC service',
          category: 'RDC',
          subcategory: 'Availability',
          formula: "(uptime_minutes / total_minutes) * 100",
          businessLogic: 'Service availability percentage',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Monthly',
          sourceTables: ['bronze.cm_system_availability'],
          calculation: { numerator: "SUM(uptime_minutes)", denominator: "SUM(total_minutes)", filters: "service = 'RDC'", multiplier: 100 },
          businessDefinition: 'RDC system reliability',
          benchmarks: { industryAverage: '99.5%', topQuartile: '99.9%', target: '99.7%' },
        },
      ],
    },

    // Category 4: Positive Pay Metrics (35 metrics)
    {
      name: 'Positive Pay Metrics',
      description: 'Positive pay file processing, exception management, and fraud prevention',
      totalMetrics: 35,
      
      metrics: [
        {
          id: 'CM-PP-001',
          name: 'Positive Pay File Upload Rate',
          description: 'Percentage of expected files uploaded on time',
          category: 'Positive Pay',
          subcategory: 'Timeliness',
          formula: "(COUNT(files WHERE uploaded_on_time = true) / COUNT(expected_files)) * 100",
          businessLogic: 'On-time uploads / expected uploads',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Daily',
          sourceTables: ['bronze.cm_positive_pay_files'],
          calculation: { numerator: "COUNT(WHERE upload_timestamp <= cutoff_time)", denominator: "COUNT(expected_file_id)", multiplier: 100 },
          businessDefinition: 'Customer file upload compliance',
          benchmarks: { industryAverage: '88%', topQuartile: '96%', target: '92%' },
        },
        {
          id: 'CM-PP-002',
          name: 'Exception Item Count',
          description: 'Number of positive pay exceptions',
          category: 'Positive Pay',
          subcategory: 'Exceptions',
          formula: "COUNT(exception_id)",
          businessLogic: 'Count of PP exceptions',
          dataType: 'INTEGER',
          unit: 'count',
          aggregation: 'COUNT',
          granularity: 'Daily',
          sourceTables: ['bronze.cm_pp_exceptions'],
          calculation: { numerator: "COUNT(exception_id)" },
          businessDefinition: 'Total positive pay exceptions generated',
          benchmarks: { industryAverage: '450/day', topQuartile: '220/day', target: '320/day' },
        },
        {
          id: 'CM-PP-003',
          name: 'Exception Resolution Time',
          description: 'Average time to resolve positive pay exceptions',
          category: 'Positive Pay',
          subcategory: 'Speed',
          formula: "AVG(DATEDIFF(hour, exception_date, resolution_date))",
          businessLogic: 'Mean hours to resolve exception',
          dataType: 'DECIMAL',
          unit: 'hours',
          aggregation: 'AVG',
          granularity: 'Daily',
          sourceTables: ['bronze.cm_pp_exceptions'],
          calculation: { numerator: "AVG(DATEDIFF(hour, exception_timestamp, resolution_timestamp))" },
          businessDefinition: 'Exception handling efficiency',
          benchmarks: { industryAverage: '8 hours', topQuartile: '4 hours', target: '6 hours' },
        },
        {
          id: 'CM-PP-004',
          name: 'Pay Decision Rate',
          description: 'Percentage of exceptions marked as pay',
          category: 'Positive Pay',
          subcategory: 'Decisions',
          formula: "(COUNT(exceptions WHERE decision = 'pay') / COUNT(total_exceptions)) * 100",
          businessLogic: 'Pay decisions / total decisions',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Monthly',
          sourceTables: ['bronze.cm_pp_exceptions'],
          calculation: { numerator: "COUNT(WHERE decision = 'pay')", denominator: "COUNT(exception_id)", multiplier: 100 },
          businessDefinition: 'Exception pay rate analysis',
          benchmarks: { industryAverage: '82%', topQuartile: '88%', target: '85%' },
        },
        {
          id: 'CM-PP-005',
          name: 'Fraud Prevention Rate',
          description: 'Value of fraudulent checks prevented via positive pay',
          category: 'Positive Pay',
          subcategory: 'Fraud',
          formula: "SUM(check_amount WHERE decision = 'return' AND fraud_suspected = true)",
          businessLogic: 'Sum of suspected fraud returns',
          dataType: 'DECIMAL',
          unit: 'currency',
          aggregation: 'SUM',
          granularity: 'Monthly',
          sourceTables: ['bronze.cm_pp_exceptions'],
          calculation: { numerator: "SUM(amount)", filters: "decision = 'return' AND fraud_indicator = true" },
          businessDefinition: 'Fraud losses prevented through positive pay',
          benchmarks: { industryAverage: '$280K/month', topQuartile: '$520K/month', target: '$380K/month' },
        },
        {
          id: 'CM-PP-006',
          name: 'Positive Pay File Accuracy',
          description: 'Percentage of issue files with no errors',
          category: 'Positive Pay',
          subcategory: 'Quality',
          formula: "(COUNT(files WHERE error_count = 0) / COUNT(total_files)) * 100",
          businessLogic: 'Error-free files / total files',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Daily',
          sourceTables: ['bronze.cm_positive_pay_files'],
          calculation: { numerator: "COUNT(WHERE file_errors = 0)", denominator: "COUNT(file_id)", multiplier: 100 },
          businessDefinition: 'Customer file quality',
          benchmarks: { industryAverage: '91%', topQuartile: '97%', target: '94%' },
        },
        {
          id: 'CM-PP-007',
          name: 'Exception Auto-Resolution Rate',
          description: 'Percentage of exceptions auto-resolved via rules',
          category: 'Positive Pay',
          subcategory: 'Automation',
          formula: "(COUNT(exceptions WHERE auto_resolved = true) / COUNT(total_exceptions)) * 100",
          businessLogic: 'Auto-resolved / total exceptions',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Monthly',
          sourceTables: ['bronze.cm_pp_exceptions'],
          calculation: { numerator: "COUNT(WHERE resolution_method = 'automatic')", denominator: "COUNT(exception_id)", multiplier: 100 },
          businessDefinition: 'Positive pay automation effectiveness',
          benchmarks: { industryAverage: '35%', topQuartile: '55%', target: '45%' },
        },
        {
          id: 'CM-PP-008',
          name: 'Same-Day Exception Resolution Rate',
          description: 'Percentage of exceptions resolved same day',
          category: 'Positive Pay',
          subcategory: 'Timeliness',
          formula: "(COUNT(exceptions WHERE CAST(resolution_date AS DATE) = exception_date) / COUNT(total_exceptions)) * 100",
          businessLogic: 'Same-day resolutions / total exceptions',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Daily',
          sourceTables: ['bronze.cm_pp_exceptions'],
          calculation: { numerator: "COUNT(WHERE CAST(resolution_timestamp AS DATE) = CAST(exception_timestamp AS DATE))", denominator: "COUNT(exception_id)", multiplier: 100 },
          businessDefinition: 'Exception handling timeliness',
          benchmarks: { industryAverage: '75%', topQuartile: '88%', target: '82%' },
        },
        {
          id: 'CM-PP-009',
          name: 'Positive Pay Customer Adoption Rate',
          description: 'Percentage of eligible customers using positive pay',
          category: 'Positive Pay',
          subcategory: 'Adoption',
          formula: "(COUNT(customers WHERE pp_active = true) / COUNT(eligible_customers)) * 100",
          businessLogic: 'PP users / eligible customers',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Quarterly',
          sourceTables: ['bronze.cm_customer_services'],
          calculation: { numerator: "COUNT(WHERE positive_pay_enabled = true)", denominator: "COUNT(WHERE eligible_for_pp = true)", multiplier: 100 },
          businessDefinition: 'Positive pay service penetration',
          benchmarks: { industryAverage: '42%', topQuartile: '68%', target: '55%' },
        },
        {
          id: 'CM-PP-010',
          name: 'Payee Positive Pay Exception Rate',
          description: 'Percentage of items flagged for payee mismatch',
          category: 'Positive Pay',
          subcategory: 'Exceptions',
          formula: "(COUNT(items WHERE payee_mismatch = true) / COUNT(total_items)) * 100",
          businessLogic: 'Payee mismatches / total items',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Monthly',
          sourceTables: ['bronze.cm_pp_exceptions'],
          calculation: { numerator: "COUNT(WHERE exception_type = 'payee_mismatch')", denominator: "COUNT(item_id)", multiplier: 100 },
          businessDefinition: 'Payee verification exception rate',
          benchmarks: { industryAverage: '2.8%', topQuartile: '1.5%', target: '2.0%' },
        },
      ],
    },

    // Category 5: Revenue Metrics (30 metrics)
    {
      name: 'Revenue Metrics',
      description: 'Cash management service fees and revenue optimization',
      totalMetrics: 30,
      
      metrics: [
        {
          id: 'CM-REV-001',
          name: 'Lockbox Service Fees',
          description: 'Revenue from lockbox processing services',
          category: 'Revenue',
          subcategory: 'Fee Income',
          formula: "SUM(lockbox_fee)",
          businessLogic: 'Sum of lockbox service fees',
          dataType: 'DECIMAL',
          unit: 'currency',
          aggregation: 'SUM',
          granularity: 'Monthly',
          sourceTables: ['bronze.cm_fees', 'gold.fact_cm_revenue'],
          calculation: { numerator: "SUM(fee_amount)", filters: "service_type = 'lockbox'" },
          businessDefinition: 'Total lockbox service revenue',
          benchmarks: { industryAverage: '$180K/month', topQuartile: '$420K/month', target: '$280K/month' },
        },
        {
          id: 'CM-REV-002',
          name: 'RDC Service Fees',
          description: 'Revenue from remote deposit capture services',
          category: 'Revenue',
          subcategory: 'Fee Income',
          formula: "SUM(rdc_fee)",
          businessLogic: 'Sum of RDC service fees',
          dataType: 'DECIMAL',
          unit: 'currency',
          aggregation: 'SUM',
          granularity: 'Monthly',
          sourceTables: ['bronze.cm_fees'],
          calculation: { numerator: "SUM(fee_amount)", filters: "service_type = 'rdc'" },
          businessDefinition: 'Total RDC service revenue',
          benchmarks: { industryAverage: '$95K/month', topQuartile: '$220K/month', target: '$145K/month' },
        },
        {
          id: 'CM-REV-003',
          name: 'Positive Pay Fees',
          description: 'Revenue from positive pay services',
          category: 'Revenue',
          subcategory: 'Fee Income',
          formula: "SUM(pp_fee)",
          businessLogic: 'Sum of positive pay fees',
          dataType: 'DECIMAL',
          unit: 'currency',
          aggregation: 'SUM',
          granularity: 'Monthly',
          sourceTables: ['bronze.cm_fees'],
          calculation: { numerator: "SUM(fee_amount)", filters: "service_type = 'positive_pay'" },
          businessDefinition: 'Total positive pay revenue',
          benchmarks: { industryAverage: '$65K/month', topQuartile: '$145K/month', target: '$95K/month' },
        },
        {
          id: 'CM-REV-004',
          name: 'Account Analysis Fees',
          description: 'Revenue from account analysis services',
          category: 'Revenue',
          subcategory: 'Fee Income',
          formula: "SUM(analysis_fee)",
          businessLogic: 'Sum of account analysis fees',
          dataType: 'DECIMAL',
          unit: 'currency',
          aggregation: 'SUM',
          granularity: 'Monthly',
          sourceTables: ['bronze.cm_fees'],
          calculation: { numerator: "SUM(fee_amount)", filters: "service_type = 'account_analysis'" },
          businessDefinition: 'Account analysis revenue',
          benchmarks: { industryAverage: '$52K/month', topQuartile: '$115K/month', target: '$78K/month' },
        },
        {
          id: 'CM-REV-005',
          name: 'Information Reporting Fees',
          description: 'Revenue from reporting and data services',
          category: 'Revenue',
          subcategory: 'Fee Income',
          formula: "SUM(reporting_fee)",
          businessLogic: 'Sum of information reporting fees',
          dataType: 'DECIMAL',
          unit: 'currency',
          aggregation: 'SUM',
          granularity: 'Monthly',
          sourceTables: ['bronze.cm_fees'],
          calculation: { numerator: "SUM(fee_amount)", filters: "service_type = 'reporting'" },
          businessDefinition: 'Information services revenue',
          benchmarks: { industryAverage: '$38K/month', topQuartile: '$85K/month', target: '$58K/month' },
        },
        {
          id: 'CM-REV-006',
          name: 'Total Cash Management Revenue',
          description: 'All cash management service fees combined',
          category: 'Revenue',
          subcategory: 'Total Revenue',
          formula: "SUM(lockbox_fees + rdc_fees + pp_fees + analysis_fees + reporting_fees)",
          businessLogic: 'Total CM revenue across all services',
          dataType: 'DECIMAL',
          unit: 'currency',
          aggregation: 'SUM',
          granularity: 'Monthly',
          sourceTables: ['gold.fact_cm_revenue'],
          calculation: { numerator: "SUM(total_revenue)" },
          businessDefinition: 'Comprehensive cash management revenue',
          benchmarks: { industryAverage: '$430K/month', topQuartile: '$985K/month', target: '$656K/month' },
        },
        {
          id: 'CM-REV-007',
          name: 'Revenue per CM Customer',
          description: 'Average revenue per cash management client',
          category: 'Revenue',
          subcategory: 'Customer Value',
          formula: "SUM(total_revenue) / COUNT(DISTINCT customer_id)",
          businessLogic: 'Total revenue / unique customers',
          dataType: 'DECIMAL',
          unit: 'currency',
          aggregation: 'CALCULATED',
          granularity: 'Quarterly',
          sourceTables: ['gold.fact_cm_revenue'],
          calculation: { numerator: "SUM(total_revenue)", denominator: "COUNT(DISTINCT customer_id)" },
          businessDefinition: 'Customer revenue productivity',
          benchmarks: { industryAverage: '$1,250/quarter', topQuartile: '$2,850/quarter', target: '$1,900/quarter' },
        },
        {
          id: 'CM-REV-008',
          name: 'Fee per Lockbox Item',
          description: 'Average fee earned per lockbox item',
          category: 'Revenue',
          subcategory: 'Pricing',
          formula: "SUM(lockbox_fees) / SUM(lockbox_items)",
          businessLogic: 'Total fees / item count',
          dataType: 'DECIMAL',
          unit: 'currency',
          aggregation: 'CALCULATED',
          granularity: 'Monthly',
          sourceTables: ['gold.fact_cm_revenue'],
          calculation: { numerator: "SUM(lockbox_fee_revenue)", denominator: "SUM(lockbox_item_count)" },
          businessDefinition: 'Lockbox pricing realization',
          benchmarks: { industryAverage: '$0.42', topQuartile: '$0.68', target: '$0.55' },
        },
        {
          id: 'CM-REV-009',
          name: 'Fee per RDC Transaction',
          description: 'Average fee per RDC deposit',
          category: 'Revenue',
          subcategory: 'Pricing',
          formula: "SUM(rdc_fees) / COUNT(rdc_deposits)",
          businessLogic: 'Total fees / deposit count',
          dataType: 'DECIMAL',
          unit: 'currency',
          aggregation: 'CALCULATED',
          granularity: 'Monthly',
          sourceTables: ['gold.fact_cm_revenue'],
          calculation: { numerator: "SUM(rdc_fee_revenue)", denominator: "COUNT(rdc_deposit_id)" },
          businessDefinition: 'RDC pricing realization',
          benchmarks: { industryAverage: '$0.18', topQuartile: '$0.32', target: '$0.25' },
        },
        {
          id: 'CM-REV-010',
          name: 'CM Revenue Growth Rate',
          description: 'Year-over-year cash management revenue growth',
          category: 'Revenue',
          subcategory: 'Growth',
          formula: "((current_year_revenue - prior_year_revenue) / prior_year_revenue) * 100",
          businessLogic: 'YoY revenue growth percentage',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Annual',
          sourceTables: ['gold.fact_cm_revenue'],
          calculation: { numerator: "(current_year - prior_year)", denominator: "prior_year", multiplier: 100 },
          businessDefinition: 'Cash management revenue growth trend',
          benchmarks: { industryAverage: '8.5%', topQuartile: '15%', target: '12%' },
        },
      ],
    },

    // Category 6: Customer Metrics (35 metrics)
    {
      name: 'Customer Metrics',
      description: 'Customer adoption, retention, and service quality',
      totalMetrics: 35,
      
      metrics: [
        {
          id: 'CM-CUST-001',
          name: 'Active CM Customers',
          description: 'Number of active cash management clients',
          category: 'Customer',
          subcategory: 'Volume',
          formula: "COUNT(DISTINCT customer_id WHERE status = 'active')",
          businessLogic: 'Count of active CM customers',
          dataType: 'INTEGER',
          unit: 'count',
          aggregation: 'COUNT_DISTINCT',
          granularity: 'Monthly',
          sourceTables: ['bronze.cm_customer_services', 'silver.cm_customer_summary'],
          calculation: { numerator: "COUNT(DISTINCT customer_id)", filters: "service_status = 'active'" },
          businessDefinition: 'Total active cash management customers',
          benchmarks: { industryAverage: '3,500 customers', topQuartile: '7,200 customers', target: '5,100 customers' },
        },
        {
          id: 'CM-CUST-002',
          name: 'Service Penetration Rate',
          description: 'Percentage of commercial customers using CM services',
          category: 'Customer',
          subcategory: 'Adoption',
          formula: "(COUNT(cm_customers) / COUNT(total_commercial_customers)) * 100",
          businessLogic: 'CM customers / total eligible customers',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Quarterly',
          sourceTables: ['silver.cm_customer_summary'],
          calculation: { numerator: "COUNT(WHERE has_cm_service = true)", denominator: "COUNT(commercial_customer_id)", multiplier: 100 },
          businessDefinition: 'Cash management service adoption',
          benchmarks: { industryAverage: '38%', topQuartile: '62%', target: '50%' },
        },
        {
          id: 'CM-CUST-003',
          name: 'Average Revenue per Customer',
          description: 'Mean revenue per cash management client',
          category: 'Customer',
          subcategory: 'Value',
          formula: "SUM(revenue) / COUNT(DISTINCT customer_id)",
          businessLogic: 'Total revenue / customer count',
          dataType: 'DECIMAL',
          unit: 'currency',
          aggregation: 'CALCULATED',
          granularity: 'Quarterly',
          sourceTables: ['gold.fact_cm_revenue'],
          calculation: { numerator: "SUM(total_revenue)", denominator: "COUNT(DISTINCT customer_id)" },
          businessDefinition: 'Customer revenue value',
          benchmarks: { industryAverage: '$1,250/quarter', topQuartile: '$2,850/quarter', target: '$1,900/quarter' },
        },
        {
          id: 'CM-CUST-004',
          name: 'Customer Retention Rate',
          description: 'Percentage of customers retained year-over-year',
          category: 'Customer',
          subcategory: 'Retention',
          formula: "(COUNT(retained_customers) / COUNT(prior_year_customers)) * 100",
          businessLogic: 'Retained customers / prior year customers',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Annual',
          sourceTables: ['silver.cm_customer_summary'],
          calculation: { numerator: "COUNT(WHERE active_in_both_periods = true)", denominator: "COUNT(prior_period_customers)", multiplier: 100 },
          businessDefinition: 'Customer loyalty and satisfaction',
          benchmarks: { industryAverage: '92%', topQuartile: '97%', target: '95%' },
        },
        {
          id: 'CM-CUST-005',
          name: 'Cross-Sell Ratio',
          description: 'Average number of CM services per customer',
          category: 'Customer',
          subcategory: 'Cross-Sell',
          formula: "AVG(service_count)",
          businessLogic: 'Mean services per customer',
          dataType: 'DECIMAL',
          unit: 'count',
          aggregation: 'AVG',
          granularity: 'Quarterly',
          sourceTables: ['silver.cm_customer_summary'],
          calculation: { numerator: "AVG(active_service_count)" },
          businessDefinition: 'Service penetration and wallet share',
          benchmarks: { industryAverage: '2.3 services', topQuartile: '3.8 services', target: '3.0 services' },
        },
        {
          id: 'CM-CUST-006',
          name: 'Customer Satisfaction Score',
          description: 'Average customer satisfaction rating',
          category: 'Customer',
          subcategory: 'Satisfaction',
          formula: "AVG(satisfaction_score)",
          businessLogic: 'Mean customer rating (1-10)',
          dataType: 'DECIMAL',
          unit: 'score',
          aggregation: 'AVG',
          granularity: 'Quarterly',
          sourceTables: ['bronze.cm_customer_feedback'],
          calculation: { numerator: "AVG(overall_satisfaction)" },
          businessDefinition: 'Customer service quality measurement',
          benchmarks: { industryAverage: '8.1', topQuartile: '9.0', target: '8.6' },
        },
        {
          id: 'CM-CUST-007',
          name: 'Net Promoter Score (NPS)',
          description: 'Customer loyalty and recommendation score',
          category: 'Customer',
          subcategory: 'Loyalty',
          formula: "(%promoters - %detractors)",
          businessLogic: 'Promoters (9-10) minus detractors (0-6)',
          dataType: 'INTEGER',
          unit: 'score',
          aggregation: 'CALCULATED',
          granularity: 'Quarterly',
          sourceTables: ['bronze.cm_customer_feedback'],
          calculation: { numerator: "(COUNT(WHERE nps_score >= 9) - COUNT(WHERE nps_score <= 6)) / COUNT(total_responses) * 100" },
          businessDefinition: 'Customer advocacy measurement',
          benchmarks: { industryAverage: '42', topQuartile: '68', target: '55' },
        },
        {
          id: 'CM-CUST-008',
          name: 'Customer Onboarding Time',
          description: 'Average days to onboard new CM customer',
          category: 'Customer',
          subcategory: 'Onboarding',
          formula: "AVG(DATEDIFF(day, application_date, activation_date))",
          businessLogic: 'Mean days from application to activation',
          dataType: 'INTEGER',
          unit: 'days',
          aggregation: 'AVG',
          granularity: 'Monthly',
          sourceTables: ['bronze.cm_customer_onboarding'],
          calculation: { numerator: "AVG(DATEDIFF(day, application_timestamp, activation_timestamp))" },
          businessDefinition: 'Customer onboarding efficiency',
          benchmarks: { industryAverage: '12 days', topQuartile: '6 days', target: '9 days' },
        },
        {
          id: 'CM-CUST-009',
          name: 'Customer Support Response Time',
          description: 'Average time to respond to customer inquiries',
          category: 'Customer',
          subcategory: 'Support',
          formula: "AVG(DATEDIFF(hour, inquiry_date, response_date))",
          businessLogic: 'Mean hours to first response',
          dataType: 'DECIMAL',
          unit: 'hours',
          aggregation: 'AVG',
          granularity: 'Weekly',
          sourceTables: ['bronze.cm_customer_support'],
          calculation: { numerator: "AVG(DATEDIFF(hour, inquiry_timestamp, first_response_timestamp))" },
          businessDefinition: 'Customer service responsiveness',
          benchmarks: { industryAverage: '4 hours', topQuartile: '1.5 hours', target: '2.5 hours' },
        },
        {
          id: 'CM-CUST-010',
          name: 'Customer Churn Rate',
          description: 'Percentage of customers lost per period',
          category: 'Customer',
          subcategory: 'Retention',
          formula: "(COUNT(churned_customers) / COUNT(starting_customers)) * 100",
          businessLogic: 'Churned customers / starting customer base',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Quarterly',
          sourceTables: ['silver.cm_customer_summary'],
          calculation: { numerator: "COUNT(WHERE status_changed_to = 'inactive')", denominator: "COUNT(starting_active_customers)", multiplier: 100 },
          businessDefinition: 'Customer attrition rate',
          benchmarks: { industryAverage: '8%', topQuartile: '3%', target: '5%' },
        },
      ],
    },
  ],
};
