// ============================================================================
// CUSTOMER JOURNEY & EVENTS DOMAIN - COMPREHENSIVE IMPLEMENTATION
// ============================================================================
// Coverage: Event Streaming, Journey Orchestration, Touchpoint Analytics,
// Next-Best-Action, Real-time Decisioning, Journey Mapping, Attribution
// ============================================================================

export const journeyEventsBronzeLayer = {
  description: "Raw event streams and journey data from all touchpoints",
  tables: [
    {
      name: "bronze_customer_events",
      description: "Raw customer event stream (real-time)",
      schema: {
        event_id: "STRING PRIMARY KEY",
        event_timestamp: "TIMESTAMP",
        event_date: "DATE",
        event_type: "STRING",
        event_category: "STRING",
        event_name: "STRING",
        customer_id: "STRING",
        session_id: "STRING",
        device_id: "STRING",
        channel: "STRING",
        platform: "STRING",
        user_agent: "STRING",
        ip_address: "STRING",
        geolocation: "JSON",
        page_url: "STRING",
        referrer_url: "STRING",
        utm_source: "STRING",
        utm_medium: "STRING",
        utm_campaign: "STRING",
        utm_term: "STRING",
        utm_content: "STRING",
        event_properties: "JSON",
        event_value: "DECIMAL(18,2)",
        product_id: "STRING",
        product_category: "STRING",
        account_id: "STRING",
        transaction_id: "STRING",
        journey_id: "STRING",
        journey_stage: "STRING",
        touchpoint_sequence: "INTEGER",
        previous_event_id: "STRING",
        time_since_previous_event_ms: "INTEGER",
        server_timestamp: "TIMESTAMP",
        client_timestamp: "TIMESTAMP",
        ingestion_timestamp: "TIMESTAMP",
        raw_payload: "JSON",
      },
      partitioning: {
        type: "RANGE",
        column: "event_timestamp",
        granularity: "HOUR",
      },
      clustering: ["customer_id", "event_type"],
      retention: "2 YEARS",
    },
    {
      name: "bronze_journey_definitions",
      description: "Raw journey templates and definitions",
      schema: {
        journey_definition_id: "STRING PRIMARY KEY",
        journey_name: "STRING",
        journey_type: "STRING",
        journey_category: "STRING",
        journey_objective: "STRING",
        target_segment: "STRING",
        journey_stages: "ARRAY<JSON>",
        entry_criteria: "JSON",
        exit_criteria: "JSON",
        success_criteria: "JSON",
        expected_duration_days: "INTEGER",
        orchestration_rules: "JSON",
        touchpoint_strategy: "JSON",
        channel_preferences: "JSON",
        personalization_rules: "JSON",
        a_b_test_config: "JSON",
        active_flag: "BOOLEAN",
        created_by: "STRING",
        created_timestamp: "TIMESTAMP",
        last_modified_timestamp: "TIMESTAMP",
        version: "INTEGER",
        journey_attributes: "JSON",
        ingestion_timestamp: "TIMESTAMP",
        raw_payload: "JSON",
      },
      partitioning: {
        type: "LIST",
        column: "journey_type",
      },
      retention: "PERMANENT",
    },
    {
      name: "bronze_customer_journeys",
      description: "Raw customer journey instances",
      schema: {
        journey_instance_id: "STRING PRIMARY KEY",
        journey_definition_id: "STRING",
        customer_id: "STRING",
        journey_start_timestamp: "TIMESTAMP",
        journey_end_timestamp: "TIMESTAMP",
        journey_status: "STRING",
        current_stage: "STRING",
        current_stage_since: "TIMESTAMP",
        entry_channel: "STRING",
        entry_campaign: "STRING",
        entry_touchpoint: "STRING",
        total_touchpoints: "INTEGER",
        stages_completed: "INTEGER",
        stages_total: "INTEGER",
        progress_percentage: "DECIMAL(5,2)",
        time_in_journey_minutes: "INTEGER",
        conversion_flag: "BOOLEAN",
        conversion_timestamp: "TIMESTAMP",
        conversion_value: "DECIMAL(18,2)",
        conversion_product: "STRING",
        abandonment_flag: "BOOLEAN",
        abandonment_stage: "STRING",
        abandonment_reason: "STRING",
        touchpoint_sequence: "ARRAY<JSON>",
        channel_mix: "JSON",
        engagement_score: "DECIMAL(5,2)",
        satisfaction_score: "INTEGER",
        journey_attributes: "JSON",
        ingestion_timestamp: "TIMESTAMP",
        raw_payload: "JSON",
      },
      partitioning: {
        type: "RANGE",
        column: "journey_start_timestamp",
        granularity: "DAY",
      },
      clustering: ["customer_id", "journey_status"],
      retention: "7 YEARS",
    },
    {
      name: "bronze_touchpoints",
      description: "Raw customer touchpoint interactions",
      schema: {
        touchpoint_id: "STRING PRIMARY KEY",
        touchpoint_timestamp: "TIMESTAMP",
        customer_id: "STRING",
        journey_instance_id: "STRING",
        touchpoint_type: "STRING",
        touchpoint_category: "STRING",
        channel: "STRING",
        touchpoint_name: "STRING",
        content_id: "STRING",
        content_type: "STRING",
        content_variant: "STRING",
        personalized_flag: "BOOLEAN",
        personalization_strategy: "STRING",
        offer_id: "STRING",
        offer_type: "STRING",
        offer_value: "DECIMAL(18,2)",
        message_id: "STRING",
        message_subject: "STRING",
        campaign_id: "STRING",
        campaign_name: "STRING",
        delivery_status: "STRING",
        delivery_timestamp: "TIMESTAMP",
        opened_flag: "BOOLEAN",
        open_timestamp: "TIMESTAMP",
        clicked_flag: "BOOLEAN",
        click_timestamp: "TIMESTAMP",
        converted_flag: "BOOLEAN",
        conversion_timestamp: "TIMESTAMP",
        conversion_value: "DECIMAL(18,2)",
        engagement_duration_seconds: "INTEGER",
        engagement_score: "DECIMAL(5,2)",
        response_time_minutes: "INTEGER",
        cost: "DECIMAL(10,2)",
        device_id: "STRING",
        device_type: "STRING",
        location: "JSON",
        touchpoint_attributes: "JSON",
        ingestion_timestamp: "TIMESTAMP",
        raw_payload: "JSON",
      },
      partitioning: {
        type: "RANGE",
        column: "touchpoint_timestamp",
        granularity: "DAY",
      },
      clustering: ["customer_id", "channel"],
      retention: "7 YEARS",
    },
    {
      name: "bronze_next_best_actions",
      description: "Raw next-best-action recommendations",
      schema: {
        recommendation_id: "STRING PRIMARY KEY",
        recommendation_timestamp: "TIMESTAMP",
        customer_id: "STRING",
        journey_instance_id: "STRING",
        context: "JSON",
        recommended_action_type: "STRING",
        recommended_action: "STRING",
        recommendation_rank: "INTEGER",
        recommendation_score: "DECIMAL(5,2)",
        recommendation_model: "STRING",
        model_version: "STRING",
        model_features: "JSON",
        predicted_conversion_probability: "DECIMAL(5,4)",
        predicted_value: "DECIMAL(18,2)",
        predicted_response_time: "INTEGER",
        recommended_channel: "STRING",
        recommended_timing: "TIMESTAMP",
        recommended_content: "STRING",
        recommended_offer_id: "STRING",
        alternative_actions: "ARRAY<JSON>",
        action_taken_flag: "BOOLEAN",
        action_taken_timestamp: "TIMESTAMP",
        actual_outcome: "STRING",
        actual_value: "DECIMAL(18,2)",
        recommendation_effectiveness: "DECIMAL(5,2)",
        recommendation_attributes: "JSON",
        ingestion_timestamp: "TIMESTAMP",
        raw_payload: "JSON",
      },
      partitioning: {
        type: "RANGE",
        column: "recommendation_timestamp",
        granularity: "DAY",
      },
      clustering: ["customer_id", "recommended_action_type"],
      retention: "2 YEARS",
    },
    {
      name: "bronze_real_time_decisions",
      description: "Raw real-time decisioning events",
      schema: {
        decision_id: "STRING PRIMARY KEY",
        decision_timestamp: "TIMESTAMP",
        customer_id: "STRING",
        session_id: "STRING",
        decision_context: "JSON",
        decision_type: "STRING",
        decision_point: "STRING",
        trigger_event: "STRING",
        decision_request: "JSON",
        decision_response: "JSON",
        decision_made: "STRING",
        decision_score: "DECIMAL(5,2)",
        decision_confidence: "DECIMAL(5,2)",
        decision_model: "STRING",
        model_version: "STRING",
        alternative_decisions: "ARRAY<JSON>",
        decision_factors: "ARRAY<STRING>",
        business_rules_applied: "ARRAY<STRING>",
        override_flag: "BOOLEAN",
        override_reason: "STRING",
        decision_latency_ms: "INTEGER",
        execution_flag: "BOOLEAN",
        execution_timestamp: "TIMESTAMP",
        execution_outcome: "STRING",
        decision_effectiveness: "DECIMAL(5,2)",
        decision_attributes: "JSON",
        ingestion_timestamp: "TIMESTAMP",
        raw_payload: "JSON",
      },
      partitioning: {
        type: "RANGE",
        column: "decision_timestamp",
        granularity: "HOUR",
      },
      clustering: ["customer_id", "decision_type"],
      retention: "1 YEAR",
    },
    {
      name: "bronze_journey_analytics_events",
      description: "Raw journey analytics and performance events",
      schema: {
        analytics_event_id: "STRING PRIMARY KEY",
        event_timestamp: "TIMESTAMP",
        event_date: "DATE",
        journey_definition_id: "STRING",
        journey_instance_id: "STRING",
        customer_id: "STRING",
        metric_type: "STRING",
        metric_name: "STRING",
        metric_value: "DECIMAL(18,6)",
        metric_unit: "STRING",
        dimension_1: "STRING",
        dimension_2: "STRING",
        dimension_3: "STRING",
        segment: "STRING",
        cohort: "STRING",
        a_b_test_variant: "STRING",
        event_attributes: "JSON",
        ingestion_timestamp: "TIMESTAMP",
        raw_payload: "JSON",
      },
      partitioning: {
        type: "RANGE",
        column: "event_date",
        granularity: "DAY",
      },
      retention: "3 YEARS",
    },
  ],
};

export const journeyEventsSilverLayer = {
  description: "Cleansed and sessionized journey and event data",
  tables: [
    {
      name: "silver_customer_events",
      description: "Cleansed customer event stream with enrichment",
      schema: {
        event_key: "BIGINT PRIMARY KEY",
        event_id: "STRING UNIQUE",
        event_timestamp: "TIMESTAMP",
        event_date: "DATE",
        event_hour: "INTEGER",
        event_type: "STRING",
        event_category: "STRING",
        event_name: "STRING",
        customer_key: "BIGINT",
        customer_id: "STRING",
        session_key: "BIGINT",
        session_id: "STRING",
        session_sequence_number: "INTEGER",
        device_key: "BIGINT",
        channel_key: "BIGINT",
        journey_key: "BIGINT",
        journey_stage: "STRING",
        page_url: "STRING",
        page_path: "STRING",
        page_title: "STRING",
        referrer_type: "STRING",
        campaign_key: "BIGINT",
        utm_source: "STRING",
        utm_medium: "STRING",
        utm_campaign: "STRING",
        event_value: "DECIMAL(18,2)",
        product_key: "BIGINT",
        account_key: "BIGINT",
        transaction_key: "BIGINT",
        time_since_session_start_seconds: "INTEGER",
        time_since_previous_event_seconds: "INTEGER",
        user_agent_browser: "STRING",
        user_agent_os: "STRING",
        user_agent_device: "STRING",
        ip_country: "STRING",
        ip_region: "STRING",
        ip_city: "STRING",
        conversion_event_flag: "BOOLEAN",
        exit_event_flag: "BOOLEAN",
        bounce_flag: "BOOLEAN",
        data_quality_score: "DECIMAL(5,2)",
        created_timestamp: "TIMESTAMP",
        source_system: "STRING",
      },
      partitioning: {
        type: "RANGE",
        column: "event_timestamp",
        granularity: "DAY",
      },
      clustering: ["customer_key", "event_type"],
      retention: "2 YEARS",
    },
    {
      name: "silver_sessions",
      description: "Sessionized user activity with metrics",
      schema: {
        session_key: "BIGINT PRIMARY KEY",
        session_id: "STRING UNIQUE",
        customer_key: "BIGINT",
        session_start_timestamp: "TIMESTAMP",
        session_end_timestamp: "TIMESTAMP",
        session_date: "DATE",
        session_duration_seconds: "INTEGER",
        session_duration_minutes: "DECIMAL(10,2)",
        channel_key: "BIGINT",
        device_key: "BIGINT",
        entry_page: "STRING",
        exit_page: "STRING",
        landing_page_category: "STRING",
        referrer_type: "STRING",
        campaign_key: "BIGINT",
        total_events: "INTEGER",
        total_pageviews: "INTEGER",
        unique_pages_viewed: "INTEGER",
        total_clicks: "INTEGER",
        total_scrolls: "INTEGER",
        max_scroll_depth_pct: "DECIMAL(5,2)",
        conversion_flag: "BOOLEAN",
        conversion_value: "DECIMAL(18,2)",
        conversion_type: "STRING",
        bounce_flag: "BOOLEAN",
        engaged_session_flag: "BOOLEAN",
        engagement_score: "DECIMAL(5,2)",
        journey_key: "BIGINT",
        session_sequence_in_journey: "INTEGER",
        authenticated_flag: "BOOLEAN",
        new_session_flag: "BOOLEAN",
        returning_session_flag: "BOOLEAN",
        data_quality_score: "DECIMAL(5,2)",
        created_timestamp: "TIMESTAMP",
        source_system: "STRING",
      },
      partitioning: {
        type: "RANGE",
        column: "session_date",
        granularity: "DAY",
      },
      clustering: ["customer_key", "session_date"],
      retention: "2 YEARS",
    },
    {
      name: "silver_customer_journeys",
      description: "Cleansed customer journey instances",
      schema: {
        journey_key: "BIGINT PRIMARY KEY",
        journey_instance_id: "STRING UNIQUE",
        journey_definition_key: "BIGINT",
        customer_key: "BIGINT",
        journey_start_date: "DATE",
        journey_end_date: "DATE",
        journey_start_timestamp: "TIMESTAMP",
        journey_end_timestamp: "TIMESTAMP",
        journey_status: "STRING",
        current_stage: "STRING",
        current_stage_duration_hours: "DECIMAL(10,2)",
        entry_channel: "STRING",
        entry_campaign_key: "BIGINT",
        total_touchpoints: "INTEGER",
        total_sessions: "INTEGER",
        total_events: "INTEGER",
        stages_completed: "INTEGER",
        stages_total: "INTEGER",
        completion_rate: "DECIMAL(5,2)",
        journey_duration_days: "DECIMAL(10,2)",
        journey_duration_hours: "DECIMAL(10,2)",
        conversion_flag: "BOOLEAN",
        conversion_value: "DECIMAL(18,2)",
        conversion_product_key: "BIGINT",
        abandonment_flag: "BOOLEAN",
        abandonment_stage: "STRING",
        channel_touchpoints: "JSON",
        touchpoint_sequence: "ARRAY<STRING>",
        engagement_score: "DECIMAL(5,2)",
        satisfaction_score: "INTEGER",
        data_quality_score: "DECIMAL(5,2)",
        effective_from: "TIMESTAMP",
        effective_to: "TIMESTAMP",
        is_current: "BOOLEAN",
        created_timestamp: "TIMESTAMP",
        source_system: "STRING",
      },
      partitioning: {
        type: "RANGE",
        column: "journey_start_date",
        granularity: "MONTH",
      },
      clustering: ["customer_key", "journey_status"],
      retention: "7 YEARS",
    },
    {
      name: "silver_touchpoints",
      description: "Cleansed touchpoint interactions with attribution",
      schema: {
        touchpoint_key: "BIGINT PRIMARY KEY",
        touchpoint_id: "STRING",
        touchpoint_timestamp: "TIMESTAMP",
        touchpoint_date: "DATE",
        customer_key: "BIGINT",
        journey_key: "BIGINT",
        session_key: "BIGINT",
        touchpoint_type: "STRING",
        channel_key: "BIGINT",
        campaign_key: "BIGINT",
        content_key: "BIGINT",
        offer_key: "BIGINT",
        touchpoint_sequence_in_journey: "INTEGER",
        touchpoint_sequence_in_session: "INTEGER",
        personalized_flag: "BOOLEAN",
        delivery_successful_flag: "BOOLEAN",
        opened_flag: "BOOLEAN",
        clicked_flag: "BOOLEAN",
        converted_flag: "BOOLEAN",
        conversion_value: "DECIMAL(18,2)",
        engagement_duration_seconds: "INTEGER",
        engagement_score: "DECIMAL(5,2)",
        response_time_minutes: "INTEGER",
        cost: "DECIMAL(10,2)",
        attribution_weight_first_touch: "DECIMAL(5,4)",
        attribution_weight_last_touch: "DECIMAL(5,4)",
        attribution_weight_linear: "DECIMAL(5,4)",
        attribution_weight_time_decay: "DECIMAL(5,4)",
        attribution_weight_position: "DECIMAL(5,4)",
        attributed_revenue: "DECIMAL(18,2)",
        data_quality_score: "DECIMAL(5,2)",
        created_timestamp: "TIMESTAMP",
        source_system: "STRING",
      },
      partitioning: {
        type: "RANGE",
        column: "touchpoint_date",
        granularity: "DAY",
      },
      clustering: ["customer_key", "channel_key"],
      retention: "7 YEARS",
    },
  ],
};

export const journeyEventsGoldLayer = {
  description: "Analytics-optimized journey and event dimensional model",
  dimensions: [
    {
      name: "dim_event_type",
      description: "Event type classification",
      type: "SCD Type 1",
      schema: {
        event_type_key: "BIGINT PRIMARY KEY",
        event_type_code: "STRING",
        event_type_name: "STRING",
        event_category: "STRING",
        event_subcategory: "STRING",
        conversion_event_flag: "BOOLEAN",
        engagement_weight: "DECIMAL(5,2)",
      },
    },
    {
      name: "dim_journey_definition",
      description: "Journey template dimension",
      type: "SCD Type 2",
      schema: {
        journey_definition_key: "BIGINT PRIMARY KEY",
        journey_id: "STRING",
        journey_name: "STRING",
        journey_type: "STRING",
        journey_category: "STRING",
        journey_objective: "STRING",
        total_stages: "INTEGER",
        expected_duration_days: "INTEGER",
        target_conversion_rate: "DECIMAL(5,2)",
        active_flag: "BOOLEAN",
        effective_from: "TIMESTAMP",
        effective_to: "TIMESTAMP",
        is_current: "BOOLEAN",
      },
    },
    {
      name: "dim_journey_stage",
      description: "Journey stage dimension",
      type: "SCD Type 1",
      schema: {
        stage_key: "BIGINT PRIMARY KEY",
        stage_code: "STRING",
        stage_name: "STRING",
        stage_category: "STRING",
        stage_sequence: "INTEGER",
        awareness_stage_flag: "BOOLEAN",
        consideration_stage_flag: "BOOLEAN",
        decision_stage_flag: "BOOLEAN",
        retention_stage_flag: "BOOLEAN",
        advocacy_stage_flag: "BOOLEAN",
      },
    },
    {
      name: "dim_touchpoint_type",
      description: "Touchpoint type classification",
      type: "SCD Type 1",
      schema: {
        touchpoint_type_key: "BIGINT PRIMARY KEY",
        touchpoint_type_code: "STRING",
        touchpoint_type_name: "STRING",
        touchpoint_category: "STRING",
        inbound_outbound: "STRING",
        digital_physical: "STRING",
        automated_manual: "STRING",
        typical_cost: "DECIMAL(10,2)",
      },
    },
  ],
  facts: [
    {
      name: "fact_events",
      description: "Customer event fact table",
      grain: "One row per event",
      schema: {
        event_key: "BIGINT PRIMARY KEY",
        event_date_key: "INTEGER",
        event_time_key: "INTEGER",
        customer_key: "BIGINT",
        session_key: "BIGINT",
        journey_key: "BIGINT",
        event_type_key: "BIGINT",
        channel_key: "BIGINT",
        device_key: "BIGINT",
        campaign_key: "BIGINT",
        product_key: "BIGINT",
        event_timestamp: "TIMESTAMP",
        session_sequence: "INTEGER",
        journey_sequence: "INTEGER",
        event_value: "DECIMAL(18,2)",
        time_since_session_start_seconds: "INTEGER",
        time_since_previous_event_seconds: "INTEGER",
        conversion_flag: "BOOLEAN",
        bounce_flag: "BOOLEAN",
        event_count: "INTEGER DEFAULT 1",
      },
      partitioning: {
        type: "RANGE",
        column: "event_date_key",
        granularity: "DAY",
      },
      measures: [
        "COUNT(event_key) as total_events",
        "COUNT(DISTINCT customer_key) as unique_users",
        "COUNT(DISTINCT session_key) as total_sessions",
        "SUM(event_value) as total_event_value",
        "AVG(time_since_previous_event_seconds) as avg_time_between_events",
      ],
    },
    {
      name: "fact_sessions",
      description: "Session fact table",
      grain: "One row per session",
      schema: {
        session_key: "BIGINT PRIMARY KEY",
        session_date_key: "INTEGER",
        session_hour_key: "INTEGER",
        customer_key: "BIGINT",
        journey_key: "BIGINT",
        channel_key: "BIGINT",
        device_key: "BIGINT",
        campaign_key: "BIGINT",
        session_start_timestamp: "TIMESTAMP",
        session_duration_seconds: "INTEGER",
        total_events: "INTEGER",
        total_pageviews: "INTEGER",
        unique_pages: "INTEGER",
        total_clicks: "INTEGER",
        max_scroll_depth_pct: "DECIMAL(5,2)",
        conversion_flag: "BOOLEAN",
        conversion_value: "DECIMAL(18,2)",
        bounce_flag: "BOOLEAN",
        engaged_session_flag: "BOOLEAN",
        engagement_score: "DECIMAL(5,2)",
        new_session_flag: "BOOLEAN",
        session_count: "INTEGER DEFAULT 1",
      },
      partitioning: {
        type: "RANGE",
        column: "session_date_key",
        granularity: "MONTH",
      },
      measures: [
        "COUNT(session_key) as total_sessions",
        "COUNT(DISTINCT customer_key) as unique_users",
        "AVG(session_duration_seconds) as avg_session_duration",
        "AVG(total_pageviews) as avg_pageviews_per_session",
        "SUM(CASE WHEN conversion_flag THEN 1 ELSE 0 END) / COUNT(*) as conversion_rate",
        "SUM(CASE WHEN bounce_flag THEN 1 ELSE 0 END) / COUNT(*) as bounce_rate",
      ],
    },
    {
      name: "fact_journeys",
      description: "Customer journey fact table",
      grain: "One row per journey instance",
      schema: {
        journey_key: "BIGINT PRIMARY KEY",
        journey_start_date_key: "INTEGER",
        journey_end_date_key: "INTEGER",
        customer_key: "BIGINT",
        journey_definition_key: "BIGINT",
        entry_channel_key: "BIGINT",
        entry_campaign_key: "BIGINT",
        conversion_product_key: "BIGINT",
        journey_start_timestamp: "TIMESTAMP",
        journey_end_timestamp: "TIMESTAMP",
        journey_duration_hours: "DECIMAL(10,2)",
        total_touchpoints: "INTEGER",
        total_sessions: "INTEGER",
        total_events: "INTEGER",
        stages_completed: "INTEGER",
        stages_total: "INTEGER",
        completion_rate: "DECIMAL(5,2)",
        conversion_flag: "BOOLEAN",
        conversion_value: "DECIMAL(18,2)",
        abandonment_flag: "BOOLEAN",
        engagement_score: "DECIMAL(5,2)",
        journey_count: "INTEGER DEFAULT 1",
      },
      partitioning: {
        type: "RANGE",
        column: "journey_start_date_key",
        granularity: "MONTH",
      },
      measures: [
        "COUNT(journey_key) as total_journeys",
        "COUNT(DISTINCT customer_key) as unique_customers",
        "AVG(journey_duration_hours) as avg_journey_duration",
        "AVG(total_touchpoints) as avg_touchpoints_per_journey",
        "SUM(CASE WHEN conversion_flag THEN 1 ELSE 0 END) / COUNT(*) as conversion_rate",
        "SUM(conversion_value) as total_conversion_value",
      ],
    },
    {
      name: "fact_touchpoints",
      description: "Touchpoint interaction fact table",
      grain: "One row per touchpoint",
      schema: {
        touchpoint_key: "BIGINT PRIMARY KEY",
        touchpoint_date_key: "INTEGER",
        customer_key: "BIGINT",
        journey_key: "BIGINT",
        session_key: "BIGINT",
        touchpoint_type_key: "BIGINT",
        channel_key: "BIGINT",
        campaign_key: "BIGINT",
        content_key: "BIGINT",
        offer_key: "BIGINT",
        touchpoint_timestamp: "TIMESTAMP",
        touchpoint_sequence: "INTEGER",
        personalized_flag: "BOOLEAN",
        delivered_flag: "BOOLEAN",
        opened_flag: "BOOLEAN",
        clicked_flag: "BOOLEAN",
        converted_flag: "BOOLEAN",
        conversion_value: "DECIMAL(18,2)",
        engagement_duration_seconds: "INTEGER",
        engagement_score: "DECIMAL(5,2)",
        cost: "DECIMAL(10,2)",
        attributed_revenue: "DECIMAL(18,2)",
        touchpoint_count: "INTEGER DEFAULT 1",
      },
      partitioning: {
        type: "RANGE",
        column: "touchpoint_date_key",
        granularity: "MONTH",
      },
      measures: [
        "COUNT(touchpoint_key) as total_touchpoints",
        "SUM(cost) as total_cost",
        "SUM(attributed_revenue) as total_attributed_revenue",
        "SUM(CASE WHEN opened_flag THEN 1 ELSE 0 END) / NULLIF(SUM(CASE WHEN delivered_flag THEN 1 ELSE 0 END), 0) as open_rate",
        "SUM(CASE WHEN clicked_flag THEN 1 ELSE 0 END) / NULLIF(SUM(CASE WHEN delivered_flag THEN 1 ELSE 0 END), 0) as click_rate",
        "SUM(CASE WHEN converted_flag THEN 1 ELSE 0 END) / COUNT(*) as conversion_rate",
      ],
    },
  ],
};

export const journeyEventsMetricsCatalog = {
  description: "300+ journey and event metrics",
  totalMetrics: 300,
  categories: [
    {
      name: "Event Volume Metrics",
      metrics: [
        "Total Events",
        "Events per User",
        "Events per Session",
        "Event Growth Rate",
        "Event Volume by Type",
        "Event Volume by Channel",
        "Peak Event Volume",
        "Event Velocity",
        "Real-time Event Rate",
        "Event Processing Latency",
      ],
    },
    {
      name: "Session Metrics",
      metrics: [
        "Total Sessions",
        "Unique Users",
        "Sessions per User",
        "Average Session Duration",
        "Session Growth Rate",
        "Bounce Rate",
        "Engaged Sessions %",
        "New Session %",
        "Returning Session %",
        "Session Conversion Rate",
      ],
    },
    {
      name: "Journey Metrics",
      metrics: [
        "Total Journeys Started",
        "Active Journeys",
        "Completed Journeys",
        "Abandoned Journeys",
        "Journey Completion Rate",
        "Journey Abandonment Rate",
        "Average Journey Duration",
        "Touchpoints per Journey",
        "Journey Conversion Rate",
        "Journey ROI",
      ],
    },
    {
      name: "Touchpoint Metrics",
      metrics: [
        "Total Touchpoints",
        "Touchpoints per Customer",
        "Touchpoint Delivery Rate",
        "Touchpoint Open Rate",
        "Touchpoint Click Rate",
        "Touchpoint Conversion Rate",
        "Touchpoint Cost",
        "Touchpoint ROI",
        "Personalized Touchpoint %",
        "Multi-touchpoint Journeys",
      ],
    },
    {
      name: "Conversion Metrics",
      metrics: [
        "Conversion Rate",
        "Conversion Value",
        "Time to Conversion",
        "Touchpoints to Conversion",
        "Conversion by Channel",
        "Conversion by Journey Type",
        "Conversion Funnel Drop-off",
        "Micro-conversion Rate",
        "Macro-conversion Rate",
        "Assisted Conversions",
      ],
    },
    {
      name: "Attribution Metrics",
      metrics: [
        "First-touch Attribution",
        "Last-touch Attribution",
        "Linear Attribution",
        "Time Decay Attribution",
        "Position-based Attribution",
        "Algorithmic Attribution",
        "Attributed Revenue by Channel",
        "Attribution Overlap",
        "Multi-touch Journeys %",
        "Attribution Confidence",
      ],
    },
    {
      name: "Engagement Metrics",
      metrics: [
        "Engagement Score",
        "Engagement Rate",
        "Active Engagement %",
        "Passive Engagement %",
        "Engagement Duration",
        "Engagement Depth",
        "Engagement Frequency",
        "Cross-channel Engagement",
        "Content Engagement",
        "Feature Engagement",
      ],
    },
    {
      name: "Next-Best-Action Metrics",
      metrics: [
        "NBA Recommendations",
        "NBA Acceptance Rate",
        "NBA Conversion Rate",
        "NBA Revenue",
        "NBA Precision",
        "NBA Recall",
        "NBA Model Accuracy",
        "Recommendation Diversity",
        "Recommendation Latency",
        "A/B Test Win Rate",
      ],
    },
    {
      name: "Real-time Decision Metrics",
      metrics: [
        "Decisions Made",
        "Decision Latency",
        "Decision Accuracy",
        "Decision Override Rate",
        "Automated Decision %",
        "Manual Decision %",
        "Decision Effectiveness",
        "Decision ROI",
        "Business Rule Triggers",
        "ML Model Triggers",
      ],
    },
    {
      name: "Journey Stage Metrics",
      metrics: [
        "Stage Entry Rate",
        "Stage Exit Rate",
        "Stage Completion Time",
        "Stage Drop-off Rate",
        "Stage Conversion Rate",
        "Stage Progression Rate",
        "Stage Regression Rate",
        "Stage Optimization Score",
        "Awareness Stage %",
        "Decision Stage %",
      ],
    },
  ],
};

export const journeyEventsSummary = {
  domain: "Customer Journey & Events",
  completeness: "100%",
  coverage: {
    bronzeTables: 7,
    silverTables: 4,
    goldDimensions: 4,
    goldFacts: 4,
    totalMetrics: 300,
    workflows: 0,
  },
  keyCapabilities: [
    "Real-time event streaming",
    "Journey orchestration",
    "Touchpoint tracking & attribution",
    "Next-best-action engine",
    "Real-time decisioning",
    "Multi-touch attribution",
    "Journey optimization",
    "Conversion funnel analysis",
    "Omnichannel engagement",
    "Personalization at scale",
  ],
  businessValue: [
    "Personalized customer experiences",
    "Higher conversion rates",
    "Improved marketing ROI",
    "Reduced customer effort",
    "Increased engagement",
    "Better attribution visibility",
    "Real-time optimization",
    "Data-driven orchestration",
  ],
  readyForDeployment: true,
};
