// Enterprise Data Sources Catalog
// Comprehensive inventory of internal and external data sources

export type DataSourceType = "internal" | "external";
export type RefreshFrequency =
  | "real-time"
  | "near-real-time"
  | "hourly"
  | "daily"
  | "weekly"
  | "monthly"
  | "on-demand";
export type IntegrationMethod =
  | "CDC"
  | "API"
  | "Batch"
  | "Streaming"
  | "SFTP"
  | "Event Hub"
  | "Webhook";

export type DataSource = {
  id: string;
  name: string;
  type: DataSourceType;
  category: string;
  description: string;
  domains: string[];
  refreshFrequency: RefreshFrequency;
  volumeDaily: string;
  integrationMethod: IntegrationMethod;
  format: string;
  criticalityLevel: "Critical" | "High" | "Medium" | "Low";
  sla: string;
  vendor?: string;
  cost?: string;
  dataTypes: string[];
};

export const internalDataSources: DataSource[] = [
  {
    id: "core-banking",
    name: "Core Banking Platform",
    type: "internal",
    category: "Transaction System",
    description:
      "Central banking platform managing accounts, customers, transactions, and core banking operations (Finacle, T24, Temenos, Oracle FSS)",
    domains: [
      "customer-core",
      "customer-retail",
      "customer-commercial",
      "loans",
      "loans-retail",
      "loans-commercial",
      "deposits",
      "deposits-retail",
      "deposits-commercial",
      "credit-cards",
      "cards-retail",
      "payments",
      "payments-retail",
      "payments-commercial",
      "operations",
      "channels",
      "branch-retail",
      "digital-retail",
      "collections",
      "collections-retail",
      "revenue",
    ],
    refreshFrequency: "real-time",
    volumeDaily: "~10M transactions",
    integrationMethod: "CDC",
    format: "Database CDC (JSON Events)",
    criticalityLevel: "Critical",
    sla: "99.95% uptime, <5s latency",
    vendor: "Finacle/Oracle/Temenos",
    cost: "License + Infrastructure",
    dataTypes: [
      "Customer Master",
      "Account Master",
      "Transaction History",
      "Balance Snapshots",
      "Product Master",
      "Branch/Channel Data",
      "Chart of Accounts",
    ],
  },
  {
    id: "los",
    name: "Loan Origination System (LOS)",
    type: "internal",
    category: "Lending",
    description:
      "End-to-end loan origination platform handling applications, underwriting, decisioning, and loan booking",
    domains: [
      "loans",
      "loans-retail",
      "loans-commercial",
      "mortgages",
      "risk",
      "compliance",
      "compliance-retail",
      "revenue",
      "customer-core",
      "customer-retail",
      "customer-commercial",
    ],
    refreshFrequency: "daily",
    volumeDaily: "~50K applications",
    integrationMethod: "Batch",
    format: "CSV/Parquet via SFTP",
    criticalityLevel: "Critical",
    sla: "EOD batch by 2 AM",
    vendor: "Fiserv/FIS/nCino",
    cost: "$500K+ annually",
    dataTypes: [
      "Loan Applications",
      "Credit Decisions",
      "Underwriting Data",
      "Collateral Information",
      "Origination Metrics",
      "Application Status",
      "Credit Bureau Pulls",
    ],
  },
  {
    id: "card-system",
    name: "Card Management System",
    type: "internal",
    category: "Card Operations",
    description:
      "Credit and debit card platform managing card lifecycle, authorizations, and transactions",
    domains: ["credit-cards", "cards-retail", "fraud", "fraud-retail", "payments", "payments-retail"],
    refreshFrequency: "near-real-time",
    volumeDaily: "~5M transactions",
    integrationMethod: "Streaming",
    format: "Kafka Event Streams (Avro)",
    criticalityLevel: "Critical",
    sla: "99.99% uptime, <2s auth",
    vendor: "TSYS/FIS/ACI",
    cost: "$1M+ annually",
    dataTypes: [
      "Card Accounts",
      "Authorization Events",
      "Purchase Transactions",
      "Payment Transactions",
      "Merchant Data (MCC)",
      "Rewards Balances",
      "Cardholder Data (PCI)",
    ],
  },
  {
    id: "treasury-system",
    name: "Treasury Management System",
    type: "internal",
    category: "Treasury & ALM",
    description:
      "Treasury platform managing investments, securities, funding, liquidity, and ALM",
    domains: ["treasury", "deposits", "deposits-retail", "deposits-commercial", "risk", "fx", "revenue", "wealth", "investment-retail"],
    refreshFrequency: "hourly",
    volumeDaily: "~500K position updates",
    integrationMethod: "API",
    format: "REST API (JSON)",
    criticalityLevel: "Critical",
    sla: "Intraday refresh, 99.9%",
    vendor: "SunGard/ION/Clearwater",
    cost: "$750K+ annually",
    dataTypes: [
      "Security Holdings",
      "Trade Transactions",
      "Position Valuations",
      "Interest Rate Curves",
      "Liquidity Metrics",
      "Gap Reports",
      "Derivative Contracts",
    ],
  },
  {
    id: "general-ledger",
    name: "General Ledger (SAP/Oracle)",
    type: "internal",
    category: "Finance",
    description:
      "Enterprise accounting system managing chart of accounts, journal entries, and financial close",
    domains: [
      "revenue",
      "risk",
      "loans",
      "loans-retail",
      "loans-commercial",
      "deposits",
      "deposits-retail",
      "deposits-commercial",
      "treasury",
      "credit-cards",
      "cards-retail",
      "payments",
      "payments-retail",
      "payments-commercial",
      "mortgages",
      "wealth",
      "investment-retail",
      "insurance-retail",
      "operations",
    ],
    refreshFrequency: "daily",
    volumeDaily: "~2M journal entries",
    integrationMethod: "Batch",
    format: "ERP Extract (CSV/XML)",
    criticalityLevel: "Critical",
    sla: "Daily EOD load by 6 AM",
    vendor: "SAP/Oracle Financials",
    cost: "$2M+ annually",
    dataTypes: [
      "Journal Entries",
      "Chart of Accounts",
      "Trial Balance",
      "Financial Statements",
      "Cost Centers",
      "Profit Centers",
      "Intercompany Transactions",
    ],
  },
  {
    id: "crm",
    name: "CRM Platform (Salesforce)",
    type: "internal",
    category: "Customer Relationship",
    description:
      "Customer relationship management platform for sales, marketing, and customer service",
    domains: [
      "customer-core",
      "customer-retail",
      "customer-commercial",
      "channels",
      "branch-retail",
      "digital-retail",
      "wealth",
      "investment-retail",
      "deposits",
      "deposits-retail",
      "deposits-commercial",
      "loans",
      "loans-retail",
      "loans-commercial",
      "credit-cards",
      "cards-retail",
      "collections",
      "collections-retail",
      "customer-service-retail",
      "marketing-retail",
      "revenue",
    ],
    refreshFrequency: "hourly",
    volumeDaily: "~100K customer updates",
    integrationMethod: "API",
    format: "REST API (JSON)",
    criticalityLevel: "High",
    sla: "Hourly sync, 99.5%",
    vendor: "Salesforce",
    cost: "$500K+ annually",
    dataTypes: [
      "Customer Profiles",
      "Marketing Campaigns",
      "Sales Opportunities",
      "Service Cases",
      "Product Holdings",
      "Relationship Hierarchy",
      "Lead/Opportunity Data",
    ],
  },
  {
    id: "fraud-detection",
    name: "Fraud Detection System",
    type: "internal",
    category: "Risk & Fraud",
    description:
      "Real-time fraud detection and prevention platform with ML-based scoring",
    domains: ["fraud", "fraud-retail", "credit-cards", "cards-retail", "payments", "payments-retail", "channels", "digital-retail"],
    refreshFrequency: "real-time",
    volumeDaily: "~200K alerts",
    integrationMethod: "Event Hub",
    format: "Event Streams (JSON)",
    criticalityLevel: "Critical",
    sla: "Real-time, <500ms",
    vendor: "FICO/SAS/Featurespace",
    cost: "$1.5M+ annually",
    dataTypes: [
      "Fraud Alerts",
      "Fraud Scores",
      "Device Fingerprints",
      "IP/Geolocation",
      "Behavioral Analytics",
      "Transaction Patterns",
      "Confirmed Fraud Cases",
    ],
  },
  {
    id: "collections-platform",
    name: "Collections Platform",
    type: "internal",
    category: "Collections",
    description:
      "Collections and recovery management system for delinquent accounts",
    domains: ["collections", "collections-retail", "loans", "loans-retail", "loans-commercial", "credit-cards", "cards-retail"],
    refreshFrequency: "daily",
    volumeDaily: "~50K account updates",
    integrationMethod: "Batch",
    format: "SFTP (CSV)",
    criticalityLevel: "High",
    sla: "Daily load by 8 AM",
    vendor: "FICO/Experian/CSS",
    cost: "$400K+ annually",
    dataTypes: [
      "Delinquent Accounts",
      "Collection Actions",
      "Payment Promises",
      "Collection Strategies",
      "Collector Assignments",
      "Contact History",
      "Recovery Transactions",
    ],
  },
  {
    id: "wealth-platform",
    name: "Wealth/Brokerage Platform",
    type: "internal",
    category: "Wealth Management",
    description:
      "Brokerage and investment platform managing client portfolios, trades, and holdings",
    domains: ["wealth", "investment-retail", "insurance-retail"],
    refreshFrequency: "daily",
    volumeDaily: "~1M position updates",
    integrationMethod: "SFTP",
    format: "SFTP (Parquet/CSV)",
    criticalityLevel: "High",
    sla: "EOD by 10 PM",
    vendor: "Charles River/Black Diamond",
    cost: "$800K+ annually",
    dataTypes: [
      "Client Holdings",
      "Trade Orders",
      "Trade Executions",
      "Portfolio Valuations",
      "Asset Allocations",
      "Fee Transactions",
      "Performance Attribution",
    ],
  },
  {
    id: "digital-banking",
    name: "Digital Banking Platform",
    type: "internal",
    category: "Digital Channels",
    description:
      "Online and mobile banking platform with customer engagement analytics",
    domains: ["channels", "branch-retail", "digital-retail", "customer-service-retail"],
    refreshFrequency: "real-time",
    volumeDaily: "~20M clickstream events",
    integrationMethod: "Streaming",
    format: "Event Streams (JSON)",
    criticalityLevel: "High",
    sla: "Real-time, 99.9%",
    vendor: "Q2/Backbase/Alkami",
    cost: "$600K+ annually",
    dataTypes: [
      "User Sessions",
      "Clickstream Events",
      "Login Events",
      "Feature Usage",
      "Transaction History",
      "Bill Pay Transactions",
      "Mobile App Analytics",
    ],
  },
  {
    id: "payment-processing",
    name: "Payment Processing System",
    type: "internal",
    category: "Payments",
    description:
      "Payment processing platform for ACH, wires, real-time payments, and transfers",
    domains: ["payments", "payments-retail", "payments-commercial"],
    refreshFrequency: "near-real-time",
    volumeDaily: "~3M payment transactions",
    integrationMethod: "API",
    format: "REST/SOAP API (XML/JSON)",
    criticalityLevel: "Critical",
    sla: "Real-time, 99.95%",
    vendor: "FIS/ACI/Fiserv",
    cost: "$1M+ annually",
    dataTypes: [
      "Payment Instructions",
      "ACH Transactions",
      "Wire Transfers",
      "RTP Transactions",
      "Settlement Records",
      "Payment Status",
      "Return Items",
    ],
  },
  {
    id: "aml-platform",
    name: "AML/Compliance Platform",
    type: "internal",
    category: "Compliance",
    description: "Anti-money laundering and compliance monitoring platform",
    domains: ["compliance", "compliance-retail", "payments", "payments-retail", "payments-commercial", "open-banking-retail"],
    refreshFrequency: "near-real-time",
    volumeDaily: "~150K screening events",
    integrationMethod: "API",
    format: "REST API (JSON)",
    criticalityLevel: "Critical",
    sla: "Real-time, 99.9%",
    vendor: "Nice Actimize/FICO/SAS",
    cost: "$1.2M+ annually",
    dataTypes: [
      "AML Alerts",
      "Case Management",
      "SAR Filings",
      "Sanctions Screening",
      "Transaction Monitoring",
      "KYC Records",
      "Risk Ratings",
    ],
  },
  {
    id: "mortgage-servicing",
    name: "Mortgage Servicing Platform",
    type: "internal",
    category: "Mortgage",
    description:
      "Mortgage loan servicing system managing payments, escrow, and MSR",
    domains: ["mortgages", "loans", "loans-commercial", "revenue", "risk", "operations"],
    refreshFrequency: "daily",
    volumeDaily: "~200K servicing records",
    integrationMethod: "Batch",
    format: "SFTP (CSV/XML)",
    criticalityLevel: "Critical",
    sla: "Daily by 6 AM",
    vendor: "Black Knight/Fiserv",
    cost: "$900K+ annually",
    dataTypes: [
      "Servicing Records",
      "Payment History",
      "Escrow Accounts",
      "MSR Valuations",
      "Delinquency Data",
      "Prepayment Activity",
      "Investor Reporting",
    ],
  },
  {
    id: "trade-finance-platform",
    name: "Trade Finance Platform",
    type: "internal",
    category: "Trade Finance",
    description:
      "Platform for managing letters of credit, documentary collections, and trade documentation",
    domains: ["trade-finance", "payments", "payments-commercial", "compliance", "risk", "fx"],
    refreshFrequency: "daily",
    volumeDaily: "~10K trade transactions",
    integrationMethod: "API",
    format: "REST API (JSON)",
    criticalityLevel: "High",
    sla: "Daily by 8 AM",
    vendor: "Finastra/Misys",
    cost: "$400K+ annually",
    dataTypes: [
      "Letters of Credit",
      "Documentary Collections",
      "Bill of Lading",
      "Trade Documents",
      "SWIFT Messages",
      "Guarantees",
      "Trade Loans",
    ],
  },
  {
    id: "cash-management-platform",
    name: "Cash Management Platform",
    type: "internal",
    category: "Treasury Services",
    description: "Corporate cash management and treasury services platform",
    domains: [
      "cash-management",
      "payments",
      "payments-commercial",
      "deposits",
      "deposits-commercial",
      "treasury",
      "operations",
    ],
    refreshFrequency: "near-real-time",
    volumeDaily: "~500K transactions",
    integrationMethod: "API",
    format: "REST API (JSON)",
    criticalityLevel: "Critical",
    sla: "Real-time, 99.9%",
    vendor: "FIS/Treasury Prime",
    cost: "$600K+ annually",
    dataTypes: [
      "Sweep Accounts",
      "Lockbox Transactions",
      "ACH Origination",
      "Wire Transfers",
      "Positive Pay",
      "Concentration Accounts",
      "Zero Balance Accounts",
    ],
  },
  {
    id: "merchant-acquiring-platform",
    name: "Merchant Acquiring Platform",
    type: "internal",
    category: "Merchant Services",
    description: "Merchant acquiring and payment processing platform",
    domains: [
      "merchant-services",
      "payments",
      "payments-commercial",
      "fraud",
      "operations",
      "revenue",
    ],
    refreshFrequency: "real-time",
    volumeDaily: "~2M merchant transactions",
    integrationMethod: "Streaming",
    format: "Event Streams (Avro)",
    criticalityLevel: "Critical",
    sla: "Real-time, <2s",
    vendor: "Fiserv/First Data",
    cost: "$800K+ annually",
    dataTypes: [
      "Merchant Accounts",
      "Transaction Authorizations",
      "Settlement Records",
      "Chargebacks",
      "Interchange Fees",
      "Terminal Data",
      "Merchant Profiles",
    ],
  },
  {
    id: "leasing-platform",
    name: "Equipment Leasing Platform",
    type: "internal",
    category: "Leasing",
    description: "Equipment finance and leasing management system",
    domains: ["leasing", "loans", "loans-commercial", "risk", "revenue", "operations"],
    refreshFrequency: "daily",
    volumeDaily: "~50K lease records",
    integrationMethod: "Batch",
    format: "SFTP (CSV)",
    criticalityLevel: "High",
    sla: "Daily by 7 AM",
    vendor: "ODI/White Clarke",
    cost: "$300K+ annually",
    dataTypes: [
      "Lease Contracts",
      "Payment Schedules",
      "Equipment Details",
      "Residual Values",
      "Lease Modifications",
      "End of Lease Processing",
      "Asset Valuations",
    ],
  },
  {
    id: "abl-platform",
    name: "Asset-Based Lending Platform",
    type: "internal",
    category: "Commercial Lending",
    description: "Asset-based lending and collateral management system",
    domains: ["asset-based-lending", "loans", "loans-commercial", "risk", "operations", "revenue"],
    refreshFrequency: "daily",
    volumeDaily: "~20K ABL records",
    integrationMethod: "Batch",
    format: "SFTP (CSV/XML)",
    criticalityLevel: "High",
    sla: "Daily by 6 AM",
    vendor: "CRE Direct/Commercial Banking",
    cost: "$250K+ annually",
    dataTypes: [
      "ABL Facilities",
      "Borrowing Base Certificates",
      "Collateral Values",
      "Field Exam Reports",
      "Availability Calculations",
      "AR/Inventory Balances",
      "Covenant Compliance",
    ],
  },
  {
    id: "marketing-automation",
    name: "Marketing Automation Platform",
    type: "internal",
    category: "Marketing",
    description: "Marketing automation for campaigns, lead nurturing, and email orchestration (HubSpot, Marketo, Pardot)",
    domains: ["marketing-retail", "customer-retail", "customer-service-retail"],
    refreshFrequency: "hourly",
    volumeDaily: "~500K campaign events",
    integrationMethod: "API",
    format: "REST API (JSON)",
    criticalityLevel: "High",
    sla: "Hourly sync, 99.5%",
    vendor: "HubSpot/Marketo/Pardot",
    cost: "$150K+ annually",
    dataTypes: [
      "Campaign Data",
      "Email Campaigns",
      "Lead Nurturing Flows",
      "Drip Campaigns",
      "Campaign Responses",
      "Email Engagement",
      "Lead Scores",
      "Marketing Lists",
    ],
  },
  {
    id: "email-platform",
    name: "Email Delivery Platform",
    type: "internal",
    category: "Marketing",
    description: "Transactional and marketing email delivery platform (SendGrid, Braze, Iterable)",
    domains: ["marketing-retail", "customer-service-retail"],
    refreshFrequency: "real-time",
    volumeDaily: "~2M email events",
    integrationMethod: "Streaming",
    format: "Webhook (JSON)",
    criticalityLevel: "Critical",
    sla: "Real-time, 99.9%",
    vendor: "SendGrid/Braze/Iterable",
    cost: "$100K+ annually",
    dataTypes: [
      "Email Sends",
      "Deliveries",
      "Opens",
      "Clicks",
      "Bounces (Hard/Soft)",
      "Spam Complaints",
      "Unsubscribes",
      "Email Content",
    ],
  },
  {
    id: "web-analytics",
    name: "Web Analytics Platform",
    type: "internal",
    category: "Marketing",
    description: "Web and mobile analytics platform (Google Analytics 4, Adobe Analytics)",
    domains: ["marketing-retail", "digital-retail", "customer-retail"],
    refreshFrequency: "hourly",
    volumeDaily: "~10M pageviews",
    integrationMethod: "API",
    format: "REST API (JSON)",
    criticalityLevel: "High",
    sla: "Hourly batch, 99.5%",
    vendor: "Google/Adobe",
    cost: "$200K+ annually",
    dataTypes: [
      "Sessions",
      "Pageviews",
      "Events",
      "Conversions",
      "Traffic Sources",
      "User Behavior",
      "Ecommerce Transactions",
      "Goal Completions",
    ],
  },
  {
    id: "cdp-platform",
    name: "Customer Data Platform",
    type: "internal",
    category: "Marketing",
    description: "Customer data platform for unified profiles and segmentation (Segment, mParticle)",
    domains: ["marketing-retail", "customer-retail", "customer-core"],
    refreshFrequency: "real-time",
    volumeDaily: "~5M events",
    integrationMethod: "Streaming",
    format: "Event Streams (JSON)",
    criticalityLevel: "Critical",
    sla: "Real-time, 99.9%",
    vendor: "Segment/mParticle",
    cost: "$300K+ annually",
    dataTypes: [
      "Customer Events",
      "User Profiles",
      "Segments",
      "Traits",
      "Behavioral Data",
      "Identity Graph",
      "Audience Sync",
    ],
  },
  {
    id: "sms-platform",
    name: "SMS/MMS Messaging Platform",
    type: "internal",
    category: "Marketing",
    description: "SMS and MMS messaging platform (Twilio, Attentive)",
    domains: ["marketing-retail", "customer-service-retail"],
    refreshFrequency: "real-time",
    volumeDaily: "~300K SMS",
    integrationMethod: "API",
    format: "REST API (JSON)",
    criticalityLevel: "High",
    sla: "Real-time, 99.5%",
    vendor: "Twilio/Attentive",
    cost: "$150K+ annually",
    dataTypes: [
      "SMS Sends",
      "Deliveries",
      "Clicks",
      "Opt-ins",
      "Opt-outs",
      "Keywords",
      "Shortcodes",
      "Message Content",
    ],
  },
  {
    id: "push-notification",
    name: "Push Notification Platform",
    type: "internal",
    category: "Marketing",
    description: "Mobile push notification service (OneSignal, Airship)",
    domains: ["marketing-retail", "digital-retail"],
    refreshFrequency: "real-time",
    volumeDaily: "~1M push notifications",
    integrationMethod: "API",
    format: "REST API (JSON)",
    criticalityLevel: "Medium",
    sla: "Real-time, 99%",
    vendor: "OneSignal/Airship",
    cost: "$80K+ annually",
    dataTypes: [
      "Push Sends",
      "Deliveries",
      "Opens",
      "Actions",
      "Device Tokens",
      "Segments",
      "Notification Content",
    ],
  },
  {
    id: "ab-testing",
    name: "A/B Testing & Experimentation Platform",
    type: "internal",
    category: "Marketing",
    description: "Experimentation and optimization platform (Optimizely, VWO)",
    domains: ["marketing-retail", "digital-retail"],
    refreshFrequency: "hourly",
    volumeDaily: "~2M experiment events",
    integrationMethod: "API",
    format: "REST API (JSON)",
    criticalityLevel: "Medium",
    sla: "Hourly sync, 99%",
    vendor: "Optimizely/VWO",
    cost: "$120K+ annually",
    dataTypes: [
      "Experiments",
      "Variations",
      "Visitors",
      "Conversions",
      "Statistical Results",
      "Feature Flags",
      "Personalization Rules",
    ],
  },
  {
    id: "attribution-platform",
    name: "Marketing Attribution Platform",
    type: "internal",
    category: "Marketing",
    description: "Multi-touch attribution and marketing mix modeling (Bizible, Ruler Analytics)",
    domains: ["marketing-retail"],
    refreshFrequency: "daily",
    volumeDaily: "~500K attribution events",
    integrationMethod: "API",
    format: "REST API (JSON)",
    criticalityLevel: "High",
    sla: "Daily sync, 99%",
    vendor: "Bizible/Ruler Analytics",
    cost: "$200K+ annually",
    dataTypes: [
      "Touchpoints",
      "Attribution Models",
      "Revenue Attribution",
      "Channel Attribution",
      "Campaign ROI",
      "Customer Journeys",
      "Conversion Paths",
    ],
  },
  {
    id: "social-management",
    name: "Social Media Management Platform",
    type: "internal",
    category: "Marketing",
    description: "Social media management and analytics (Hootsuite, Sprinklr)",
    domains: ["marketing-retail"],
    refreshFrequency: "hourly",
    volumeDaily: "~100K social posts",
    integrationMethod: "API",
    format: "REST API (JSON)",
    criticalityLevel: "Medium",
    sla: "Hourly sync, 99%",
    vendor: "Hootsuite/Sprinklr",
    cost: "$100K+ annually",
    dataTypes: [
      "Social Posts",
      "Engagement Metrics",
      "Follower Growth",
      "Sentiment Analysis",
      "Mentions",
      "Hashtags",
      "Influencer Data",
    ],
  },
  {
    id: "marketing-cloud",
    name: "Salesforce Marketing Cloud",
    type: "internal",
    category: "Marketing",
    description: "Enterprise marketing cloud for journey orchestration and personalization",
    domains: ["marketing-retail", "customer-retail"],
    refreshFrequency: "hourly",
    volumeDaily: "~1M journey events",
    integrationMethod: "API",
    format: "REST API (JSON)",
    criticalityLevel: "High",
    sla: "Hourly sync, 99.5%",
    vendor: "Salesforce",
    cost: "$250K+ annually",
    dataTypes: [
      "Customer Journeys",
      "Journey Events",
      "Personalization Rules",
      "Content Blocks",
      "Triggered Sends",
      "Engagement Studio",
      "Einstein Recommendations",
    ],
  },
  {
    id: "referral-program",
    name: "Referral Program Platform",
    type: "internal",
    category: "Marketing",
    description: "Customer referral and advocacy program management",
    domains: ["marketing-retail", "customer-retail"],
    refreshFrequency: "daily",
    volumeDaily: "~50K referrals",
    integrationMethod: "API",
    format: "REST API (JSON)",
    criticalityLevel: "Medium",
    sla: "Daily sync, 99%",
    vendor: "ReferralCandy/Extole",
    cost: "$60K+ annually",
    dataTypes: [
      "Referrals",
      "Referrers",
      "Referees",
      "Rewards",
      "Conversion Tracking",
      "Referral Links",
      "Program Rules",
    ],
  },
  {
    id: "offer-management",
    name: "Offer Management System",
    type: "internal",
    category: "Marketing",
    description: "Centralized offer creation, targeting, and redemption tracking",
    domains: ["marketing-retail", "customer-retail"],
    refreshFrequency: "real-time",
    volumeDaily: "~200K offer events",
    integrationMethod: "API",
    format: "REST API (JSON)",
    criticalityLevel: "High",
    sla: "Real-time, 99.5%",
    vendor: "Internal/Pega",
    cost: "$100K+ annually",
    dataTypes: [
      "Offers",
      "Offer Rules",
      "Eligibility Criteria",
      "Redemptions",
      "Offer Performance",
      "Targeting Segments",
      "Expiration Tracking",
    ],
  },
  {
    id: "fis-ach-tracker",
    name: "FIS Corporate ACH Tracker",
    type: "internal",
    category: "Payments",
    description: "Real-time ACH transaction monitoring, exception management, and reconciliation platform for commercial banking clients",
    domains: ["payments-commercial", "treasury", "cash-management"],
    refreshFrequency: "real-time",
    volumeDaily: "~500K-5M ACH transactions",
    integrationMethod: "Streaming",
    format: "Real-time API + Batch files",
    criticalityLevel: "Critical",
    sla: "99.9% uptime, <500ms latency",
    vendor: "FIS (Fidelity Information Services)",
    cost: "$200K+ annually (per 1M transactions)",
    dataTypes: [
      "ACH Transaction Tracking",
      "Exception Events (Returns, NOCs, Reversals)",
      "Batch File Metadata",
      "Settlement Status",
      "Return Code Analysis (R01-R99)",
      "NOC Management (C01-C13)",
      "Reconciliation Data",
      "Same-Day ACH Tracking",
      "Transaction Status Lifecycle",
      "Validation Results",
    ],
  },
];

export const externalDataSources: DataSource[] = [
  {
    id: "experian",
    name: "Experian Credit Bureau",
    type: "external",
    category: "Credit Data",
    description:
      "Consumer credit reports, scores, and trade line data for underwriting and risk",
    domains: ["loans", "loans-retail", "loans-commercial", "credit-cards", "cards-retail", "risk"],
    refreshFrequency: "on-demand",
    volumeDaily: "~30K credit pulls",
    integrationMethod: "API",
    format: "REST API (XML/JSON)",
    criticalityLevel: "Critical",
    sla: "<3s response time",
    vendor: "Experian",
    cost: "$2-5 per pull",
    dataTypes: [
      "Credit Scores (FICO, VantageScore)",
      "Trade Lines",
      "Payment History",
      "Inquiries",
      "Public Records",
      "Collections",
      "Credit Utilization",
    ],
  },
  {
    id: "transunion",
    name: "TransUnion Credit Bureau",
    type: "external",
    category: "Credit Data",
    description: "Consumer credit reports and risk analytics",
    domains: ["loans", "loans-retail", "loans-commercial", "credit-cards", "cards-retail", "risk"],
    refreshFrequency: "on-demand",
    volumeDaily: "~25K credit pulls",
    integrationMethod: "API",
    format: "REST API (XML)",
    criticalityLevel: "Critical",
    sla: "<3s response time",
    vendor: "TransUnion",
    cost: "$2-5 per pull",
    dataTypes: [
      "Credit Reports",
      "Risk Scores",
      "Fraud Detection",
      "Identity Verification",
      "Trade Line Data",
      "Attribute Data",
    ],
  },
  {
    id: "equifax",
    name: "Equifax Credit Bureau",
    type: "external",
    category: "Credit Data",
    description: "Consumer credit data and commercial credit intelligence",
    domains: ["loans", "loans-retail", "loans-commercial", "credit-cards", "cards-retail", "risk"],
    refreshFrequency: "on-demand",
    volumeDaily: "~20K credit pulls",
    integrationMethod: "API",
    format: "REST API (JSON)",
    criticalityLevel: "Critical",
    sla: "<3s response time",
    vendor: "Equifax",
    cost: "$2-5 per pull",
    dataTypes: [
      "Consumer Credit Reports",
      "Commercial Credit Data",
      "ID Verification",
      "Fraud Scores",
      "Bankruptcy Data",
    ],
  },
  {
    id: "bloomberg",
    name: "Bloomberg Market Data",
    type: "external",
    category: "Market Data",
    description:
      "Real-time and historical market data for securities, rates, and FX",
    domains: ["treasury", "fx", "wealth", "investment-retail"],
    refreshFrequency: "real-time",
    volumeDaily: "Continuous streaming",
    integrationMethod: "API",
    format: "Bloomberg API (Proprietary)",
    criticalityLevel: "Critical",
    sla: "Real-time, <100ms",
    vendor: "Bloomberg",
    cost: "$2K+ per terminal/month",
    dataTypes: [
      "Security Prices",
      "Interest Rate Curves",
      "FX Rates",
      "Market Indices",
      "Corporate Actions",
      "Fixed Income Data",
      "Derivatives Pricing",
    ],
  },
  {
    id: "reuters",
    name: "Refinitiv (Reuters) Market Data",
    type: "external",
    category: "Market Data",
    description: "Market data, news, and analytics for trading and treasury",
    domains: ["treasury", "fx", "wealth", "investment-retail"],
    refreshFrequency: "real-time",
    volumeDaily: "Continuous streaming",
    integrationMethod: "API",
    format: "Elektron/TREP (Proprietary)",
    criticalityLevel: "Critical",
    sla: "Real-time, <100ms",
    vendor: "Refinitiv",
    cost: "$1.5K+ per user/month",
    dataTypes: [
      "Real-time Prices",
      "FX Rates",
      "Fixed Income",
      "News Feeds",
      "Reference Data",
      "Analytics",
    ],
  },
  {
    id: "dow-jones",
    name: "Dow Jones Watchlist",
    type: "external",
    category: "AML/Sanctions",
    description:
      "Global watchlist screening for PEP, sanctions, and adverse media",
    domains: ["compliance", "compliance-retail"],
    refreshFrequency: "daily",
    volumeDaily: "~50K screenings",
    integrationMethod: "API",
    format: "REST API (XML/JSON)",
    criticalityLevel: "Critical",
    sla: "Daily updates, <2s API",
    vendor: "Dow Jones Risk & Compliance",
    cost: "$100K+ annually",
    dataTypes: [
      "PEP Lists",
      "Sanctions Lists (OFAC, UN, EU)",
      "Adverse Media",
      "Law Enforcement Data",
      "State-owned Entities",
      "Risk Intelligence",
    ],
  },
  {
    id: "world-check",
    name: "World-Check (Refinitiv)",
    type: "external",
    category: "AML/Sanctions",
    description: "Global sanctions and PEP screening database",
    domains: ["compliance", "compliance-retail"],
    refreshFrequency: "daily",
    volumeDaily: "~40K screenings",
    integrationMethod: "API",
    format: "REST API (JSON)",
    criticalityLevel: "Critical",
    sla: "Daily updates, <2s API",
    vendor: "Refinitiv",
    cost: "$150K+ annually",
    dataTypes: [
      "Sanctions Lists",
      "PEP Database",
      "Special Interest Persons",
      "Adverse Media",
      "Government Lists",
    ],
  },
  {
    id: "corelogic",
    name: "CoreLogic Property Data",
    type: "external",
    category: "Property Valuation",
    description:
      "Property valuations, appraisals, and real estate data for mortgage lending",
    domains: ["mortgages", "loans", "loans-commercial"],
    refreshFrequency: "monthly",
    volumeDaily: "~5K property valuations",
    integrationMethod: "API",
    format: "REST API (JSON)",
    criticalityLevel: "High",
    sla: "Monthly refresh, <5s API",
    vendor: "CoreLogic",
    cost: "$200K+ annually",
    dataTypes: [
      "Automated Valuation Models (AVM)",
      "Property Characteristics",
      "Sales Comparables",
      "Foreclosure Data",
      "Lien Information",
      "Tax Assessments",
    ],
  },
  {
    id: "zillow",
    name: "Zillow Property Data",
    type: "external",
    category: "Property Valuation",
    description: "Home values and real estate market data",
    domains: ["mortgages", "loans", "loans-commercial"],
    refreshFrequency: "weekly",
    volumeDaily: "~3K property lookups",
    integrationMethod: "API",
    format: "REST API (JSON)",
    criticalityLevel: "Medium",
    sla: "Weekly refresh",
    vendor: "Zillow",
    cost: "$50K+ annually",
    dataTypes: [
      "Zestimate Valuations",
      "Property Details",
      "Market Trends",
      "Rental Estimates",
      "Property History",
    ],
  },
  {
    id: "federal-reserve",
    name: "Federal Reserve Economic Data (FRED)",
    type: "external",
    category: "Economic Data",
    description:
      "Macroeconomic indicators, interest rates, and economic research",
    domains: ["treasury", "risk", "revenue"],
    refreshFrequency: "daily",
    volumeDaily: "Batch download",
    integrationMethod: "API",
    format: "REST API (JSON/XML)",
    criticalityLevel: "High",
    sla: "Daily updates",
    vendor: "Federal Reserve Bank",
    cost: "Free",
    dataTypes: [
      "Fed Funds Rate",
      "Treasury Yields",
      "Economic Indicators (GDP, CPI, Unemployment)",
      "Monetary Policy Data",
      "Stress Test Scenarios",
    ],
  },
  {
    id: "bea",
    name: "Bureau of Economic Analysis",
    type: "external",
    category: "Economic Data",
    description: "National economic accounts and industry statistics",
    domains: ["risk", "treasury"],
    refreshFrequency: "monthly",
    volumeDaily: "Batch download",
    integrationMethod: "API",
    format: "REST API (JSON)",
    criticalityLevel: "Medium",
    sla: "Monthly updates",
    vendor: "U.S. Department of Commerce",
    cost: "Free",
    dataTypes: [
      "GDP Data",
      "Personal Income",
      "Industry Statistics",
      "Trade Data",
      "Regional Economics",
    ],
  },
  {
    id: "fico-fraud",
    name: "FICO Falcon Fraud Intelligence",
    type: "external",
    category: "Fraud Intelligence",
    description: "Consortium fraud intelligence and network analytics",
    domains: ["fraud", "fraud-retail", "credit-cards", "cards-retail"],
    refreshFrequency: "real-time",
    volumeDaily: "Continuous",
    integrationMethod: "API",
    format: "REST API (JSON)",
    criticalityLevel: "High",
    sla: "Real-time, <500ms",
    vendor: "FICO",
    cost: "$500K+ annually",
    dataTypes: [
      "Fraud Scores",
      "Network Analytics",
      "Consortium Data",
      "Device Intelligence",
      "Fraud Patterns",
    ],
  },
  {
    id: "google-geo",
    name: "Google Geolocation Services",
    type: "external",
    category: "Geolocation",
    description: "Address validation, geocoding, and location intelligence",
    domains: ["operations", "fraud", "compliance"],
    refreshFrequency: "on-demand",
    volumeDaily: "~10K API calls",
    integrationMethod: "API",
    format: "REST API (JSON)",
    criticalityLevel: "Medium",
    sla: "<1s response",
    vendor: "Google Cloud",
    cost: "Pay-per-use",
    dataTypes: [
      "Address Validation",
      "Geocoding",
      "Reverse Geocoding",
      "Distance Calculations",
      "Time Zones",
    ],
  },
  {
    id: "plaid",
    name: "Plaid Account Aggregation",
    type: "external",
    category: "Open Banking",
    description: "Account aggregation and open banking data connectivity",
    domains: ["channels", "digital-retail", "open-banking-retail", "deposits", "deposits-retail", "deposits-commercial", "loans", "loans-retail", "loans-commercial"],
    refreshFrequency: "real-time",
    volumeDaily: "~5K connections",
    integrationMethod: "API",
    format: "REST API (JSON)",
    criticalityLevel: "Medium",
    sla: "Real-time, 99.5%",
    vendor: "Plaid",
    cost: "$0.10-0.30 per connection",
    dataTypes: [
      "Account Balances",
      "Transaction History",
      "Identity Verification",
      "Income Verification",
      "Asset Verification",
    ],
  },
  {
    id: "mx",
    name: "MX Account Aggregation",
    type: "external",
    category: "Open Banking",
    description: "Financial data aggregation and personal financial management",
    domains: ["channels", "digital-retail", "open-banking-retail", "deposits", "deposits-retail", "deposits-commercial"],
    refreshFrequency: "real-time",
    volumeDaily: "~3K connections",
    integrationMethod: "API",
    format: "REST API (JSON)",
    criticalityLevel: "Medium",
    sla: "Real-time, 99.5%",
    vendor: "MX Technologies",
    cost: "Enterprise pricing",
    dataTypes: [
      "Aggregated Accounts",
      "Transactions",
      "Categorization",
      "Insights",
      "Account Verification",
    ],
  },
  {
    id: "google-ads",
    name: "Google Ads Platform",
    type: "external",
    category: "Paid Media",
    description: "Paid search advertising platform with keyword bidding and search network",
    domains: ["marketing-retail"],
    refreshFrequency: "daily",
    volumeDaily: "~1M ad impressions",
    integrationMethod: "API",
    format: "Google Ads API (JSON)",
    criticalityLevel: "High",
    sla: "Daily sync, 99%",
    vendor: "Google",
    cost: "$2M+ annually (ad spend)",
    dataTypes: [
      "Campaigns",
      "Ad Groups",
      "Keywords & Bids",
      "Ads & Extensions",
      "Impressions",
      "Clicks & CTR",
      "Conversions",
      "Cost & CPA Data",
      "Quality Scores",
      "Search Terms",
    ],
  },
  {
    id: "facebook-ads",
    name: "Meta Ads Manager",
    type: "external",
    category: "Paid Media",
    description: "Facebook and Instagram advertising with detailed audience targeting",
    domains: ["marketing-retail"],
    refreshFrequency: "daily",
    volumeDaily: "~800K ad impressions",
    integrationMethod: "API",
    format: "Marketing API (JSON)",
    criticalityLevel: "High",
    sla: "Daily sync, 99%",
    vendor: "Meta",
    cost: "$1.5M+ annually (ad spend)",
    dataTypes: [
      "Campaigns",
      "Ad Sets",
      "Ads & Creatives",
      "Impressions & Reach",
      "Clicks & Engagement",
      "Audience Demographics",
      "Conversion Events",
      "Cost per Result",
    ],
  },
  {
    id: "linkedin-ads",
    name: "LinkedIn Campaign Manager",
    type: "external",
    category: "Paid Media",
    description: "LinkedIn advertising for professional audience targeting",
    domains: ["marketing-retail"],
    refreshFrequency: "daily",
    volumeDaily: "~200K ad impressions",
    integrationMethod: "API",
    format: "Marketing API (JSON)",
    criticalityLevel: "Medium",
    sla: "Daily sync, 99%",
    vendor: "LinkedIn",
    cost: "$500K+ annually (ad spend)",
    dataTypes: [
      "Campaigns",
      "Creatives",
      "Impressions",
      "Clicks",
      "Lead Gen Forms",
      "Job Title/Industry Demographics",
      "Conversion Tracking",
      "Cost per Lead",
    ],
  },
  {
    id: "twitter-ads",
    name: "Twitter (X) Ads Platform",
    type: "external",
    category: "Paid Media",
    description: "Twitter advertising for real-time engagement campaigns",
    domains: ["marketing-retail"],
    refreshFrequency: "daily",
    volumeDaily: "~300K ad impressions",
    integrationMethod: "API",
    format: "Ads API (JSON)",
    criticalityLevel: "Medium",
    sla: "Daily sync, 99%",
    vendor: "Twitter/X",
    cost: "$400K+ annually (ad spend)",
    dataTypes: [
      "Campaigns",
      "Promoted Tweets",
      "Impressions",
      "Engagements",
      "Retweets & Likes",
      "Follower Growth",
      "Conversions",
      "Cost Data",
    ],
  },
];

export const allDataSources = [...internalDataSources, ...externalDataSources];

export const dataSourceStats = {
  totalSources: allDataSources.length,
  internal: internalDataSources.length,
  external: externalDataSources.length,
  realTime: allDataSources.filter((s) => s.refreshFrequency === "real-time")
    .length,
  critical: allDataSources.filter((s) => s.criticalityLevel === "Critical")
    .length,
};

// Helper to get data sources by domain
export const getDataSourcesByDomain = (domainId: string): DataSource[] => {
  return allDataSources.filter((source) => source.domains.includes(domainId));
};

// Helper to get domains by data source
export const getDomainsByDataSource = (sourceId: string): string[] => {
  const source = allDataSources.find((s) => s.id === sourceId);
  return source?.domains || [];
};
