// COMPREHENSIVE DEPOSITS & FUNDING DOMAIN - 100% COMPLETE
// Core Banking Deposit Products: DDA, Savings, MMA, CD, Sweep Accounts
// Regulatory: Reg D, Reg DD, Reg E, LCR, NSFR, Basel III Liquidity
// ALCO/Treasury: Interest Rate Risk, Liquidity Management, Funding Cost Analysis

// ============================================================================
// BRONZE LAYER - 15 TABLES
// ============================================================================

export const depositsBronzeLayer = {
  tables: [
    {
      name: "bronze.account_master_raw",
      key_fields: [
        "account_id",
        "customer_id",
        "product_code",
        "account_status",
      ],
    },
    {
      name: "bronze.account_transactions_raw",
      key_fields: [
        "transaction_id",
        "account_id",
        "transaction_date",
        "amount",
      ],
    },
    {
      name: "bronze.account_balances_eod_raw",
      key_fields: ["account_id", "balance_date", "eod_balance"],
    },
    {
      name: "bronze.interest_rates_raw",
      key_fields: [
        "product_code",
        "tier_from",
        "tier_to",
        "rate_effective_date",
      ],
    },
    {
      name: "bronze.interest_accruals_raw",
      key_fields: ["account_id", "accrual_date", "accrued_interest"],
    },
    {
      name: "bronze.cd_master_raw",
      key_fields: ["cd_id", "account_id", "maturity_date", "term_months"],
    },
    {
      name: "bronze.fee_schedules_raw",
      key_fields: ["product_code", "fee_type", "fee_amount", "effective_date"],
    },
    {
      name: "bronze.fee_transactions_raw",
      key_fields: ["fee_id", "account_id", "fee_date", "fee_amount"],
    },
    {
      name: "bronze.overdraft_events_raw",
      key_fields: ["od_id", "account_id", "od_date", "od_amount"],
    },
    {
      name: "bronze.dormant_accounts_raw",
      key_fields: ["account_id", "dormancy_date", "last_activity_date"],
    },
    {
      name: "bronze.escheatment_tracking_raw",
      key_fields: ["escheat_id", "account_id", "state", "escheat_date"],
    },
    {
      name: "bronze.account_holds_raw",
      key_fields: ["hold_id", "account_id", "hold_type", "hold_amount"],
    },
    {
      name: "bronze.reg_d_tracking_raw",
      key_fields: ["account_id", "statement_cycle", "withdrawal_count"],
    },
    {
      name: "bronze.rate_change_history_raw",
      key_fields: ["rate_id", "product_code", "change_date", "new_rate"],
    },
    {
      name: "bronze.account_statements_raw",
      key_fields: ["statement_id", "account_id", "statement_date", "cycle"],
    },
  ],
  totalTables: 15,
};

// ============================================================================
// SILVER LAYER - 12 TABLES
// ============================================================================

export const depositsSilverLayer = {
  tables: [
    {
      name: "silver.account_master_golden",
      scd2: true,
      description: "Golden record of deposit accounts with history",
    },
    {
      name: "silver.account_positions_daily",
      scd2: false,
      description: "Daily account balances and positions",
    },
    {
      name: "silver.account_transactions_cleansed",
      scd2: false,
      description: "Cleansed transaction history",
    },
    {
      name: "silver.interest_rate_schedules",
      scd2: true,
      description: "Rate tier schedules with SCD2",
    },
    {
      name: "silver.interest_accrual_daily",
      scd2: false,
      description: "Daily interest accrual calculations",
    },
    {
      name: "silver.cd_positions",
      scd2: true,
      description: "CD positions with maturity tracking",
    },
    {
      name: "silver.fee_revenue_tracking",
      scd2: false,
      description: "Fee revenue by account and product",
    },
    {
      name: "silver.overdraft_analysis",
      scd2: false,
      description: "Overdraft frequency and patterns",
    },
    {
      name: "silver.dormancy_tracking",
      scd2: false,
      description: "Dormant account monitoring",
    },
    {
      name: "silver.reg_d_compliance",
      scd2: false,
      description: "Reg D withdrawal limit monitoring",
    },
    {
      name: "silver.account_profitability",
      scd2: false,
      description: "Account-level P&L with FTP",
    },
    {
      name: "silver.customer_deposit_relationships",
      scd2: true,
      description: "Customer deposit relationships",
    },
  ],
  totalTables: 12,
};

// ============================================================================
// GOLD LAYER - 10 DIMENSIONS + 5 FACTS
// ============================================================================

export const depositsGoldLayer = {
  dimensions: [
    {
      name: "gold.dim_deposit_account",
      description: "Deposit account dimension with product hierarchy",
      type: "SCD Type 2",
      grain: "Account",
    },
    {
      name: "gold.dim_deposit_product",
      description: "Product dimension (DDA, SAV, MMA, CD)",
      type: "SCD Type 2",
      grain: "Product Code",
    },
    {
      name: "gold.dim_deposit_customer",
      description: "Customer dimension for deposit holders",
      type: "SCD Type 2",
      grain: "Customer",
    },
    {
      name: "gold.dim_branch",
      description: "Branch/location dimension",
      type: "SCD Type 2",
      grain: "Branch",
    },
    {
      name: "gold.dim_rate_tier",
      description: "Interest rate tier dimension",
      type: "SCD Type 2",
      grain: "Rate Tier",
    },
    {
      name: "gold.dim_fee_type",
      description: "Fee type dimension",
      type: "SCD Type 1",
      grain: "Fee Type",
    },
    {
      name: "gold.dim_transaction_type",
      description: "Transaction type dimension",
      type: "SCD Type 1",
      grain: "Transaction Type",
    },
    {
      name: "gold.dim_channel",
      description: "Transaction channel dimension",
      type: "SCD Type 1",
      grain: "Channel",
    },
    {
      name: "gold.dim_statement_cycle",
      description: "Statement cycle dimension",
      type: "SCD Type 1",
      grain: "Cycle",
    },
    {
      name: "gold.dim_geography",
      description: "Geographic hierarchy dimension",
      type: "SCD Type 2",
      grain: "Geography",
    },
  ],
  facts: [
    {
      name: "gold.fact_deposit_positions",
      description: "Daily deposit balances and positions",
      grain: "Account x Date",
      measures: [
        "balance_amount",
        "average_balance",
        "interest_earned",
        "fee_charged",
      ],
    },
    {
      name: "gold.fact_deposit_transactions",
      description: "Deposit transaction fact",
      grain: "Transaction",
      measures: ["transaction_amount", "running_balance"],
    },
    {
      name: "gold.fact_interest_accrual",
      description: "Interest accrual fact",
      grain: "Account x Date",
      measures: ["accrued_interest", "posted_interest", "rate_applied"],
    },
    {
      name: "gold.fact_fee_revenue",
      description: "Fee revenue fact",
      grain: "Account x Date x Fee Type",
      measures: ["fee_amount", "fee_count", "fee_waived"],
    },
    {
      name: "gold.fact_account_profitability",
      description: "Account profitability fact with FTP",
      grain: "Account x Month",
      measures: [
        "interest_income",
        "fee_income",
        "ftp_cost",
        "operating_expense",
        "net_income",
      ],
    },
  ],
  totalDimensions: 10,
  totalFacts: 5,
};

// ============================================================================
// METRICS CATALOG - 300+ METRICS
// ============================================================================

export const depositsMetricsCatalog = {
  description:
    "300+ deposits metrics across portfolio, product, segment, and granular levels",
  categories: [
    {
      name: "Portfolio Balance Metrics",
      metrics: [
        {
          id: "DEP-001",
          name: "Total Deposit Balances",
          description: "Total EOD deposit balances",
          formula: "SUM(balance_amount)",
          unit: "currency",
          aggregation: "SUM",
        },
        {
          id: "DEP-002",
          name: "Average Daily Balance (ADB) - Portfolio",
          description: "Portfolio average daily balance",
          formula: "AVG(daily_total_balance)",
          unit: "currency",
          aggregation: "AVG",
        },
        {
          id: "DEP-003",
          name: "Deposit Growth Rate (MoM)",
          description: "Month-over-month growth",
          formula: "(Current - Prior) / Prior * 100",
          unit: "percentage",
          aggregation: "AVG",
        },
        {
          id: "DEP-004",
          name: "Deposit Growth Rate (YoY)",
          description: "Year-over-year growth",
          formula: "(Current - Prior Year) / Prior Year * 100",
          unit: "percentage",
          aggregation: "AVG",
        },
        {
          id: "DEP-005",
          name: "Deposit Growth Rate (QoQ)",
          description: "Quarter-over-quarter growth",
          formula: "(Current - Prior Quarter) / Prior Quarter * 100",
          unit: "percentage",
          aggregation: "AVG",
        },
        {
          id: "DEP-006",
          name: "Total DDA Balances",
          description: "Demand deposit account balances",
          formula: "SUM(balance WHERE product = 'DDA')",
          unit: "currency",
          aggregation: "SUM",
        },
        {
          id: "DEP-007",
          name: "Total Savings Balances",
          description: "Savings account balances",
          formula: "SUM(balance WHERE product = 'SAV')",
          unit: "currency",
          aggregation: "SUM",
        },
        {
          id: "DEP-008",
          name: "Total MMA Balances",
          description: "Money market account balances",
          formula: "SUM(balance WHERE product = 'MMA')",
          unit: "currency",
          aggregation: "SUM",
        },
        {
          id: "DEP-009",
          name: "Total CD Balances",
          description: "Certificate of deposit balances",
          formula: "SUM(balance WHERE product = 'CD')",
          unit: "currency",
          aggregation: "SUM",
        },
        {
          id: "DEP-010",
          name: "Non-Interest Bearing Deposits",
          description: "Total non-interest deposits",
          formula: "SUM(balance WHERE interest_bearing = FALSE)",
          unit: "currency",
          aggregation: "SUM",
        },
        {
          id: "DEP-011",
          name: "Interest Bearing Deposits",
          description: "Total interest-bearing deposits",
          formula: "SUM(balance WHERE interest_bearing = TRUE)",
          unit: "currency",
          aggregation: "SUM",
        },
        {
          id: "DEP-012",
          name: "NIB/Total Ratio",
          description: "Non-interest bearing to total ratio",
          formula: "NIB Deposits / Total Deposits",
          unit: "ratio",
          aggregation: "AVG",
        },
        {
          id: "DEP-013",
          name: "Retail Deposit Balances",
          description: "Consumer deposit balances",
          formula: "SUM(balance WHERE segment = 'Retail')",
          unit: "currency",
          aggregation: "SUM",
        },
        {
          id: "DEP-014",
          name: "Commercial Deposit Balances",
          description: "Business deposit balances",
          formula: "SUM(balance WHERE segment = 'Commercial')",
          unit: "currency",
          aggregation: "SUM",
        },
        {
          id: "DEP-015",
          name: "Retail/Commercial Mix",
          description: "Retail vs commercial balance ratio",
          formula: "Retail / (Retail + Commercial)",
          unit: "ratio",
          aggregation: "AVG",
        },
        {
          id: "DEP-016",
          name: "Core Deposit Balances",
          description: "Core funding deposits (stable)",
          formula: "SUM(balance WHERE core_flag = TRUE)",
          unit: "currency",
          aggregation: "SUM",
        },
        {
          id: "DEP-017",
          name: "Core Deposit Ratio",
          description: "Core deposits as % of total",
          formula: "Core Deposits / Total Deposits * 100",
          unit: "percentage",
          aggregation: "AVG",
        },
        {
          id: "DEP-018",
          name: "Brokered Deposit Balances",
          description: "Brokered CD balances",
          formula: "SUM(balance WHERE brokered_flag = TRUE)",
          unit: "currency",
          aggregation: "SUM",
        },
        {
          id: "DEP-019",
          name: "Uninsured Deposit Balances",
          description: "Deposits exceeding FDIC limits",
          formula: "SUM(uninsured_amount)",
          unit: "currency",
          aggregation: "SUM",
        },
        {
          id: "DEP-020",
          name: "Insured Deposit Ratio",
          description: "Insured deposits as % of total",
          formula: "Insured Deposits / Total Deposits * 100",
          unit: "percentage",
          aggregation: "AVG",
        },
        {
          id: "DEP-021",
          name: "Public Funds Deposits",
          description: "Government/municipal deposits",
          formula: "SUM(balance WHERE public_funds = TRUE)",
          unit: "currency",
          aggregation: "SUM",
        },
        {
          id: "DEP-022",
          name: "Large Deposits (>$250K)",
          description: "Deposits over FDIC insurance limit",
          formula: "SUM(balance WHERE balance > 250000)",
          unit: "currency",
          aggregation: "SUM",
        },
        {
          id: "DEP-023",
          name: "Concentration Risk (Top 10)",
          description: "Top 10 depositor concentration",
          formula: "SUM(top_10_balances) / Total * 100",
          unit: "percentage",
          aggregation: "AVG",
        },
        {
          id: "DEP-024",
          name: "Concentration Risk (Top 20)",
          description: "Top 20 depositor concentration",
          formula: "SUM(top_20_balances) / Total * 100",
          unit: "percentage",
          aggregation: "AVG",
        },
        {
          id: "DEP-025",
          name: "Average Balance per Account",
          description: "Average account balance",
          formula: "Total Balance / Total Accounts",
          unit: "currency",
          aggregation: "AVG",
        },
        {
          id: "DEP-026",
          name: "Median Balance per Account",
          description: "Median account balance",
          formula: "MEDIAN(account_balance)",
          unit: "currency",
          aggregation: "MEDIAN",
        },
        {
          id: "DEP-027",
          name: "Balance Volatility (Std Dev)",
          description: "Standard deviation of balances",
          formula: "STDDEV(daily_balances)",
          unit: "currency",
          aggregation: "STDDEV",
        },
        {
          id: "DEP-028",
          name: "Seasonal Deposit Pattern",
          description: "Seasonal balance variation",
          formula: "AVG(balance) GROUP BY month",
          unit: "currency",
          aggregation: "AVG",
        },
        {
          id: "DEP-029",
          name: "Deposit Beta",
          description: "Deposit rate sensitivity to Fed Funds",
          formula: "CORR(deposit_rate, fed_funds_rate)",
          unit: "ratio",
          aggregation: "CORR",
        },
        {
          id: "DEP-030",
          name: "Cumulative Deposit Flow (Inflow)",
          description: "Period deposit inflows",
          formula: "SUM(transaction_amount WHERE amount > 0)",
          unit: "currency",
          aggregation: "SUM",
        },
      ],
    },
    {
      name: "Account & Customer Metrics",
      metrics: [
        {
          id: "DEP-031",
          name: "Total Deposit Accounts",
          description: "Count of active deposit accounts",
          formula: "COUNT(DISTINCT account_id WHERE status = 'ACTIVE')",
          unit: "count",
          aggregation: "SUM",
        },
        {
          id: "DEP-032",
          name: "New Accounts Opened",
          description: "New accounts opened in period",
          formula: "COUNT(DISTINCT account_id WHERE open_date IN period)",
          unit: "count",
          aggregation: "SUM",
        },
        {
          id: "DEP-033",
          name: "Accounts Closed",
          description: "Accounts closed in period",
          formula: "COUNT(DISTINCT account_id WHERE close_date IN period)",
          unit: "count",
          aggregation: "SUM",
        },
        {
          id: "DEP-034",
          name: "Net New Accounts",
          description: "Net account growth",
          formula: "Accounts Opened - Accounts Closed",
          unit: "count",
          aggregation: "SUM",
        },
        {
          id: "DEP-035",
          name: "Account Growth Rate",
          description: "Account count growth rate",
          formula: "(Current - Prior) / Prior * 100",
          unit: "percentage",
          aggregation: "AVG",
        },
        {
          id: "DEP-036",
          name: "Account Retention Rate",
          description: "Account retention percentage",
          formula: "(Beginning - Closed) / Beginning * 100",
          unit: "percentage",
          aggregation: "AVG",
        },
        {
          id: "DEP-037",
          name: "Account Churn Rate",
          description: "Account closure rate",
          formula: "Closed Accounts / Beginning Accounts * 100",
          unit: "percentage",
          aggregation: "AVG",
        },
        {
          id: "DEP-038",
          name: "DDA Account Count",
          description: "Number of DDA accounts",
          formula: "COUNT(DISTINCT account_id WHERE product = 'DDA')",
          unit: "count",
          aggregation: "SUM",
        },
        {
          id: "DEP-039",
          name: "Savings Account Count",
          description: "Number of savings accounts",
          formula: "COUNT(DISTINCT account_id WHERE product = 'SAV')",
          unit: "count",
          aggregation: "SUM",
        },
        {
          id: "DEP-040",
          name: "MMA Account Count",
          description: "Number of MMA accounts",
          formula: "COUNT(DISTINCT account_id WHERE product = 'MMA')",
          unit: "count",
          aggregation: "SUM",
        },
        {
          id: "DEP-041",
          name: "CD Account Count",
          description: "Number of CD accounts",
          formula: "COUNT(DISTINCT account_id WHERE product = 'CD')",
          unit: "count",
          aggregation: "SUM",
        },
        {
          id: "DEP-042",
          name: "Total Unique Customers",
          description: "Unique customers with deposits",
          formula: "COUNT(DISTINCT customer_id)",
          unit: "count",
          aggregation: "SUM",
        },
        {
          id: "DEP-043",
          name: "Accounts per Customer (Avg)",
          description: "Average accounts per customer",
          formula: "Total Accounts / Unique Customers",
          unit: "count",
          aggregation: "AVG",
        },
        {
          id: "DEP-044",
          name: "Multi-Product Customers",
          description: "Customers with 2+ deposit products",
          formula: "COUNT(DISTINCT customer_id WHERE product_count > 1)",
          unit: "count",
          aggregation: "SUM",
        },
        {
          id: "DEP-045",
          name: "Single Product Customers",
          description: "Customers with 1 deposit product",
          formula: "COUNT(DISTINCT customer_id WHERE product_count = 1)",
          unit: "count",
          aggregation: "SUM",
        },
        {
          id: "DEP-046",
          name: "Primary Account Holders",
          description: "Primary account ownership count",
          formula: "COUNT(DISTINCT account_id WHERE ownership = 'Primary')",
          unit: "count",
          aggregation: "SUM",
        },
        {
          id: "DEP-047",
          name: "Joint Account Holders",
          description: "Joint account count",
          formula: "COUNT(DISTINCT account_id WHERE ownership = 'Joint')",
          unit: "count",
          aggregation: "SUM",
        },
        {
          id: "DEP-048",
          name: "Business Account Count",
          description: "Business deposit accounts",
          formula: "COUNT(DISTINCT account_id WHERE account_type = 'Business')",
          unit: "count",
          aggregation: "SUM",
        },
        {
          id: "DEP-049",
          name: "Personal Account Count",
          description: "Personal deposit accounts",
          formula: "COUNT(DISTINCT account_id WHERE account_type = 'Personal')",
          unit: "count",
          aggregation: "SUM",
        },
        {
          id: "DEP-050",
          name: "Dormant Account Count",
          description: "Accounts with no activity 12+ months",
          formula: "COUNT(DISTINCT account_id WHERE days_inactive > 365)",
          unit: "count",
          aggregation: "SUM",
        },
        {
          id: "DEP-051",
          name: "Dormancy Rate",
          description: "Dormant accounts as % of total",
          formula: "Dormant Accounts / Total Accounts * 100",
          unit: "percentage",
          aggregation: "AVG",
        },
        {
          id: "DEP-052",
          name: "Zero Balance Account Count",
          description: "Accounts with zero balance",
          formula: "COUNT(DISTINCT account_id WHERE balance = 0)",
          unit: "count",
          aggregation: "SUM",
        },
        {
          id: "DEP-053",
          name: "Active Account Rate",
          description: "Accounts with activity in last 30 days",
          formula: "Active Accounts / Total Accounts * 100",
          unit: "percentage",
          aggregation: "AVG",
        },
        {
          id: "DEP-054",
          name: "Account Age (Avg)",
          description: "Average account tenure in months",
          formula: "AVG(DATEDIFF(MONTH, open_date, CURRENT_DATE))",
          unit: "months",
          aggregation: "AVG",
        },
        {
          id: "DEP-055",
          name: "Account Lifetime Value (Avg)",
          description: "Average revenue per account lifetime",
          formula: "AVG(lifetime_fee_revenue + lifetime_interest_income)",
          unit: "currency",
          aggregation: "AVG",
        },
        {
          id: "DEP-056",
          name: "Relationship Households",
          description: "Households with deposit relationships",
          formula: "COUNT(DISTINCT household_id)",
          unit: "count",
          aggregation: "SUM",
        },
        {
          id: "DEP-057",
          name: "Accounts per Household (Avg)",
          description: "Average accounts per household",
          formula: "Total Accounts / Total Households",
          unit: "count",
          aggregation: "AVG",
        },
        {
          id: "DEP-058",
          name: "Customer Acquisition Cost (CAC)",
          description: "Cost to acquire deposit customer",
          formula: "Marketing Spend / New Customers",
          unit: "currency",
          aggregation: "AVG",
        },
        {
          id: "DEP-059",
          name: "Customer Tenure (Avg)",
          description: "Average customer tenure in years",
          formula: "AVG(DATEDIFF(YEAR, first_account_open, CURRENT_DATE))",
          unit: "years",
          aggregation: "AVG",
        },
        {
          id: "DEP-060",
          name: "Cross-Sell Ratio",
          description: "Deposit customers with loans/cards",
          formula: "Customers with Deposits+Loans / Total Deposit Customers",
          unit: "ratio",
          aggregation: "AVG",
        },
      ],
    },
    {
      name: "Interest Expense & Rate Metrics",
      metrics: [
        {
          id: "DEP-061",
          name: "Total Interest Expense",
          description: "Total interest paid on deposits",
          formula: "SUM(interest_amount)",
          unit: "currency",
          aggregation: "SUM",
        },
        {
          id: "DEP-062",
          name: "Interest Expense (DDA)",
          description: "Interest paid on DDA accounts",
          formula: "SUM(interest_amount WHERE product = 'DDA')",
          unit: "currency",
          aggregation: "SUM",
        },
        {
          id: "DEP-063",
          name: "Interest Expense (Savings)",
          description: "Interest paid on savings",
          formula: "SUM(interest_amount WHERE product = 'SAV')",
          unit: "currency",
          aggregation: "SUM",
        },
        {
          id: "DEP-064",
          name: "Interest Expense (MMA)",
          description: "Interest paid on MMA",
          formula: "SUM(interest_amount WHERE product = 'MMA')",
          unit: "currency",
          aggregation: "SUM",
        },
        {
          id: "DEP-065",
          name: "Interest Expense (CD)",
          description: "Interest paid on CDs",
          formula: "SUM(interest_amount WHERE product = 'CD')",
          unit: "currency",
          aggregation: "SUM",
        },
        {
          id: "DEP-066",
          name: "Cost of Funds (Portfolio)",
          description: "Blended cost of deposits",
          formula: "Total Interest Expense / Average Balance",
          unit: "percentage",
          aggregation: "AVG",
        },
        {
          id: "DEP-067",
          name: "Cost of Funds (DDA)",
          description: "Cost of DDA deposits",
          formula: "DDA Interest / DDA Average Balance",
          unit: "percentage",
          aggregation: "AVG",
        },
        {
          id: "DEP-068",
          name: "Cost of Funds (Savings)",
          description: "Cost of savings deposits",
          formula: "SAV Interest / SAV Average Balance",
          unit: "percentage",
          aggregation: "AVG",
        },
        {
          id: "DEP-069",
          name: "Cost of Funds (MMA)",
          description: "Cost of MMA deposits",
          formula: "MMA Interest / MMA Average Balance",
          unit: "percentage",
          aggregation: "AVG",
        },
        {
          id: "DEP-070",
          name: "Cost of Funds (CD)",
          description: "Cost of CD deposits",
          formula: "CD Interest / CD Average Balance",
          unit: "percentage",
          aggregation: "AVG",
        },
        {
          id: "DEP-071",
          name: "Average Rate Paid (Portfolio)",
          description: "Average interest rate paid",
          formula: "(Interest Expense / ADB) * 100",
          unit: "percentage",
          aggregation: "AVG",
        },
        {
          id: "DEP-072",
          name: "Weighted Average Rate",
          description: "Balance-weighted average rate",
          formula: "SUM(balance * rate) / SUM(balance)",
          unit: "percentage",
          aggregation: "AVG",
        },
        {
          id: "DEP-073",
          name: "Interest Rate Spread",
          description: "Fed Funds vs deposit rate spread",
          formula: "Fed Funds Rate - Deposit Rate",
          unit: "basis_points",
          aggregation: "AVG",
        },
        {
          id: "DEP-074",
          name: "Rate Elasticity",
          description: "Balance sensitivity to rate changes",
          formula: "% Change in Balance / % Change in Rate",
          unit: "ratio",
          aggregation: "AVG",
        },
        {
          id: "DEP-075",
          name: "Rate Competitiveness Index",
          description: "Rate vs market benchmark",
          formula: "Bank Rate / Market Average Rate",
          unit: "ratio",
          aggregation: "AVG",
        },
        {
          id: "DEP-076",
          name: "Interest Accrued (Unpaid)",
          description: "Accrued but not yet paid interest",
          formula: "SUM(accrued_interest WHERE posted = FALSE)",
          unit: "currency",
          aggregation: "SUM",
        },
        {
          id: "DEP-077",
          name: "Interest Posted",
          description: "Interest posted to accounts",
          formula: "SUM(interest_amount WHERE posted = TRUE)",
          unit: "currency",
          aggregation: "SUM",
        },
        {
          id: "DEP-078",
          name: "Rate Tier Distribution",
          description: "Balance distribution by rate tier",
          formula: "SUM(balance) GROUP BY rate_tier",
          unit: "currency",
          aggregation: "SUM",
        },
        {
          id: "DEP-079",
          name: "Premium Rate Accounts",
          description: "Accounts with promotional rates",
          formula: "COUNT(account_id WHERE promo_rate = TRUE)",
          unit: "count",
          aggregation: "SUM",
        },
        {
          id: "DEP-080",
          name: "Rate Change Impact",
          description: "Revenue impact of rate changes",
          formula: "(New Rate - Old Rate) * Average Balance",
          unit: "currency",
          aggregation: "SUM",
        },
        {
          id: "DEP-081",
          name: "CD Maturity Wall",
          description: "CDs maturing in next 90 days",
          formula: "SUM(cd_balance WHERE days_to_maturity <= 90)",
          unit: "currency",
          aggregation: "SUM",
        },
        {
          id: "DEP-082",
          name: "CD Renewal Rate",
          description: "CDs renewed vs closed at maturity",
          formula: "Renewed CDs / Maturing CDs * 100",
          unit: "percentage",
          aggregation: "AVG",
        },
        {
          id: "DEP-083",
          name: "CD Early Withdrawal Penalty",
          description: "Penalties collected on early withdrawals",
          formula: "SUM(penalty_amount)",
          unit: "currency",
          aggregation: "SUM",
        },
        {
          id: "DEP-084",
          name: "Average CD Term",
          description: "Average CD term in months",
          formula: "AVG(term_months)",
          unit: "months",
          aggregation: "AVG",
        },
        {
          id: "DEP-085",
          name: "Callable CD Exposure",
          description: "Balance of callable CDs",
          formula: "SUM(cd_balance WHERE callable = TRUE)",
          unit: "currency",
          aggregation: "SUM",
        },
        {
          id: "DEP-086",
          name: "Rate Lock Period (Avg)",
          description: "Average CD rate lock period",
          formula: "AVG(days_to_maturity)",
          unit: "days",
          aggregation: "AVG",
        },
        {
          id: "DEP-087",
          name: "Promotional CD Balances",
          description: "Balance in promotional CD rates",
          formula: "SUM(cd_balance WHERE promo_flag = TRUE)",
          unit: "currency",
          aggregation: "SUM",
        },
        {
          id: "DEP-088",
          name: "Step-Rate CD Balances",
          description: "Balance in step-rate CDs",
          formula: "SUM(cd_balance WHERE step_rate = TRUE)",
          unit: "currency",
          aggregation: "SUM",
        },
        {
          id: "DEP-089",
          name: "Variable Rate Deposit Balances",
          description: "Deposits with variable rates",
          formula: "SUM(balance WHERE rate_type = 'Variable')",
          unit: "currency",
          aggregation: "SUM",
        },
        {
          id: "DEP-090",
          name: "Fixed Rate Deposit Balances",
          description: "Deposits with fixed rates",
          formula: "SUM(balance WHERE rate_type = 'Fixed')",
          unit: "currency",
          aggregation: "SUM",
        },
      ],
    },
    {
      name: "Fee Revenue Metrics",
      metrics: [
        {
          id: "DEP-091",
          name: "Total Fee Revenue",
          description: "Total fees collected on deposits",
          formula: "SUM(fee_amount)",
          unit: "currency",
          aggregation: "SUM",
        },
        {
          id: "DEP-092",
          name: "Monthly Maintenance Fee Revenue",
          description: "Monthly account maintenance fees",
          formula: "SUM(fee_amount WHERE fee_type = 'Monthly Maintenance')",
          unit: "currency",
          aggregation: "SUM",
        },
        {
          id: "DEP-093",
          name: "Overdraft Fee Revenue",
          description: "Overdraft/NSF fee revenue",
          formula: "SUM(fee_amount WHERE fee_type = 'Overdraft')",
          unit: "currency",
          aggregation: "SUM",
        },
        {
          id: "DEP-094",
          name: "ATM Fee Revenue",
          description: "ATM transaction fee revenue",
          formula: "SUM(fee_amount WHERE fee_type = 'ATM')",
          unit: "currency",
          aggregation: "SUM",
        },
        {
          id: "DEP-095",
          name: "Wire Transfer Fee Revenue",
          description: "Wire transfer fee revenue",
          formula: "SUM(fee_amount WHERE fee_type = 'Wire')",
          unit: "currency",
          aggregation: "SUM",
        },
        {
          id: "DEP-096",
          name: "Stop Payment Fee Revenue",
          description: "Stop payment fee revenue",
          formula: "SUM(fee_amount WHERE fee_type = 'Stop Payment')",
          unit: "currency",
          aggregation: "SUM",
        },
        {
          id: "DEP-097",
          name: "Early CD Withdrawal Fee Revenue",
          description: "CD early withdrawal penalties",
          formula: "SUM(fee_amount WHERE fee_type = 'Early CD Withdrawal')",
          unit: "currency",
          aggregation: "SUM",
        },
        {
          id: "DEP-098",
          name: "Dormancy Fee Revenue",
          description: "Dormant account fee revenue",
          formula: "SUM(fee_amount WHERE fee_type = 'Dormancy')",
          unit: "currency",
          aggregation: "SUM",
        },
        {
          id: "DEP-099",
          name: "Excess Transaction Fee Revenue",
          description: "Reg D excess transaction fees",
          formula: "SUM(fee_amount WHERE fee_type = 'Excess Transaction')",
          unit: "currency",
          aggregation: "SUM",
        },
        {
          id: "DEP-100",
          name: "Paper Statement Fee Revenue",
          description: "Paper statement fee revenue",
          formula: "SUM(fee_amount WHERE fee_type = 'Paper Statement')",
          unit: "currency",
          aggregation: "SUM",
        },
        {
          id: "DEP-101",
          name: "Check Order Fee Revenue",
          description: "Check ordering fee revenue",
          formula: "SUM(fee_amount WHERE fee_type = 'Check Order')",
          unit: "currency",
          aggregation: "SUM",
        },
        {
          id: "DEP-102",
          name: "Returned Item Fee Revenue",
          description: "Returned check/ACH fee revenue",
          formula: "SUM(fee_amount WHERE fee_type = 'Returned Item')",
          unit: "currency",
          aggregation: "SUM",
        },
        {
          id: "DEP-103",
          name: "Fee Waiver Amount",
          description: "Total fees waived",
          formula: "SUM(fee_waived_amount)",
          unit: "currency",
          aggregation: "SUM",
        },
        {
          id: "DEP-104",
          name: "Fee Waiver Rate",
          description: "Fees waived as % of total fees",
          formula: "Fee Waived / (Fee Charged + Fee Waived) * 100",
          unit: "percentage",
          aggregation: "AVG",
        },
        {
          id: "DEP-105",
          name: "Fee Revenue per Account (Avg)",
          description: "Average fee revenue per account",
          formula: "Total Fee Revenue / Total Accounts",
          unit: "currency",
          aggregation: "AVG",
        },
        {
          id: "DEP-106",
          name: "Fee-Generating Accounts",
          description: "Accounts generating fees",
          formula: "COUNT(DISTINCT account_id WHERE fee_amount > 0)",
          unit: "count",
          aggregation: "SUM",
        },
        {
          id: "DEP-107",
          name: "Fee Incidence Rate",
          description: "Accounts with fees as % of total",
          formula: "Fee-Generating Accounts / Total Accounts * 100",
          unit: "percentage",
          aggregation: "AVG",
        },
        {
          id: "DEP-108",
          name: "Overdraft Program Participants",
          description: "Accounts opted into overdraft",
          formula: "COUNT(DISTINCT account_id WHERE od_opt_in = TRUE)",
          unit: "count",
          aggregation: "SUM",
        },
        {
          id: "DEP-109",
          name: "Overdraft Opt-In Rate",
          description: "Overdraft program penetration",
          formula: "OD Participants / Eligible Accounts * 100",
          unit: "percentage",
          aggregation: "AVG",
        },
        {
          id: "DEP-110",
          name: "Average Overdraft Fee per Incident",
          description: "Average fee per overdraft",
          formula: "Total OD Fees / OD Incidents",
          unit: "currency",
          aggregation: "AVG",
        },
        {
          id: "DEP-111",
          name: "Overdraft Frequency",
          description: "Average overdrafts per account",
          formula: "Total OD Incidents / OD Accounts",
          unit: "count",
          aggregation: "AVG",
        },
        {
          id: "DEP-112",
          name: "Chronic Overdraft Accounts",
          description: "Accounts with 10+ overdrafts per year",
          formula: "COUNT(DISTINCT account_id WHERE annual_od_count > 10)",
          unit: "count",
          aggregation: "SUM",
        },
        {
          id: "DEP-113",
          name: "Fee Revenue Mix",
          description: "Fee revenue by fee type distribution",
          formula: "Fee Amount / Total Fees * 100 GROUP BY fee_type",
          unit: "percentage",
          aggregation: "AVG",
        },
        {
          id: "DEP-114",
          name: "Non-Sufficient Funds (NSF) Fee Count",
          description: "NSF fee transaction count",
          formula: "COUNT(fee_id WHERE fee_type = 'NSF')",
          unit: "count",
          aggregation: "SUM",
        },
        {
          id: "DEP-115",
          name: "NSF Fee Amount",
          description: "Total NSF fee revenue",
          formula: "SUM(fee_amount WHERE fee_type = 'NSF')",
          unit: "currency",
          aggregation: "SUM",
        },
        {
          id: "DEP-116",
          name: "Continuous Overdraft Fee Revenue",
          description: "Continuous/extended overdraft fees",
          formula: "SUM(fee_amount WHERE fee_type = 'Continuous OD')",
          unit: "currency",
          aggregation: "SUM",
        },
        {
          id: "DEP-117",
          name: "Account Closure Fee Revenue",
          description: "Early account closure fees",
          formula: "SUM(fee_amount WHERE fee_type = 'Early Closure')",
          unit: "currency",
          aggregation: "SUM",
        },
        {
          id: "DEP-118",
          name: "Minimum Balance Fee Revenue",
          description: "Minimum balance shortfall fees",
          formula: "SUM(fee_amount WHERE fee_type = 'Minimum Balance')",
          unit: "currency",
          aggregation: "SUM",
        },
        {
          id: "DEP-119",
          name: "Foreign Transaction Fee Revenue",
          description: "Foreign transaction fees",
          formula: "SUM(fee_amount WHERE fee_type = 'Foreign Transaction')",
          unit: "currency",
          aggregation: "SUM",
        },
        {
          id: "DEP-120",
          name: "Fee Revenue Growth (YoY)",
          description: "Year-over-year fee revenue growth",
          formula: "(Current Year - Prior Year) / Prior Year * 100",
          unit: "percentage",
          aggregation: "AVG",
        },
      ],
    },
    {
      name: "Transaction & Activity Metrics",
      metrics: [
        {
          id: "DEP-121",
          name: "Total Transactions",
          description: "Total deposit transaction count",
          formula: "COUNT(transaction_id)",
          unit: "count",
          aggregation: "SUM",
        },
        {
          id: "DEP-122",
          name: "Deposit Transactions",
          description: "Deposit/credit transactions",
          formula: "COUNT(transaction_id WHERE type = 'DEPOSIT')",
          unit: "count",
          aggregation: "SUM",
        },
        {
          id: "DEP-123",
          name: "Withdrawal Transactions",
          description: "Withdrawal/debit transactions",
          formula: "COUNT(transaction_id WHERE type = 'WITHDRAWAL')",
          unit: "count",
          aggregation: "SUM",
        },
        {
          id: "DEP-124",
          name: "Transfer Transactions",
          description: "Transfer transaction count",
          formula: "COUNT(transaction_id WHERE type = 'TRANSFER')",
          unit: "count",
          aggregation: "SUM",
        },
        {
          id: "DEP-125",
          name: "Total Transaction Volume",
          description: "Total transaction dollar volume",
          formula: "SUM(ABS(transaction_amount))",
          unit: "currency",
          aggregation: "SUM",
        },
        {
          id: "DEP-126",
          name: "Deposit Volume",
          description: "Total deposit dollar volume",
          formula: "SUM(transaction_amount WHERE amount > 0)",
          unit: "currency",
          aggregation: "SUM",
        },
        {
          id: "DEP-127",
          name: "Withdrawal Volume",
          description: "Total withdrawal dollar volume",
          formula: "SUM(ABS(transaction_amount) WHERE amount < 0)",
          unit: "currency",
          aggregation: "SUM",
        },
        {
          id: "DEP-128",
          name: "Transactions per Account (Avg)",
          description: "Average transactions per account",
          formula: "Total Transactions / Total Accounts",
          unit: "count",
          aggregation: "AVG",
        },
        {
          id: "DEP-129",
          name: "Average Transaction Size",
          description: "Average transaction amount",
          formula: "AVG(transaction_amount)",
          unit: "currency",
          aggregation: "AVG",
        },
        {
          id: "DEP-130",
          name: "Median Transaction Size",
          description: "Median transaction amount",
          formula: "MEDIAN(transaction_amount)",
          unit: "currency",
          aggregation: "MEDIAN",
        },
        {
          id: "DEP-131",
          name: "Branch Transactions",
          description: "Transactions via branch",
          formula: "COUNT(transaction_id WHERE channel = 'Branch')",
          unit: "count",
          aggregation: "SUM",
        },
        {
          id: "DEP-132",
          name: "ATM Transactions",
          description: "Transactions via ATM",
          formula: "COUNT(transaction_id WHERE channel = 'ATM')",
          unit: "count",
          aggregation: "SUM",
        },
        {
          id: "DEP-133",
          name: "Online Banking Transactions",
          description: "Transactions via online banking",
          formula: "COUNT(transaction_id WHERE channel = 'Online')",
          unit: "count",
          aggregation: "SUM",
        },
        {
          id: "DEP-134",
          name: "Mobile Banking Transactions",
          description: "Transactions via mobile app",
          formula: "COUNT(transaction_id WHERE channel = 'Mobile')",
          unit: "count",
          aggregation: "SUM",
        },
        {
          id: "DEP-135",
          name: "ACH Transactions",
          description: "ACH transaction count",
          formula: "COUNT(transaction_id WHERE channel = 'ACH')",
          unit: "count",
          aggregation: "SUM",
        },
        {
          id: "DEP-136",
          name: "Wire Transactions",
          description: "Wire transfer transaction count",
          formula: "COUNT(transaction_id WHERE channel = 'Wire')",
          unit: "count",
          aggregation: "SUM",
        },
        {
          id: "DEP-137",
          name: "Check Transactions",
          description: "Check transaction count",
          formula: "COUNT(transaction_id WHERE channel = 'Check')",
          unit: "count",
          aggregation: "SUM",
        },
        {
          id: "DEP-138",
          name: "Debit Card Transactions",
          description: "Debit card transaction count",
          formula: "COUNT(transaction_id WHERE channel = 'Debit Card')",
          unit: "count",
          aggregation: "SUM",
        },
        {
          id: "DEP-139",
          name: "Digital Transaction Rate",
          description: "Digital transactions as % of total",
          formula: "(Online + Mobile + ATM) / Total * 100",
          unit: "percentage",
          aggregation: "AVG",
        },
        {
          id: "DEP-140",
          name: "Branch Transaction Rate",
          description: "Branch transactions as % of total",
          formula: "Branch Transactions / Total * 100",
          unit: "percentage",
          aggregation: "AVG",
        },
        {
          id: "DEP-141",
          name: "ACH Volume",
          description: "ACH transaction dollar volume",
          formula: "SUM(transaction_amount WHERE channel = 'ACH')",
          unit: "currency",
          aggregation: "SUM",
        },
        {
          id: "DEP-142",
          name: "Wire Volume",
          description: "Wire transfer dollar volume",
          formula: "SUM(transaction_amount WHERE channel = 'Wire')",
          unit: "currency",
          aggregation: "SUM",
        },
        {
          id: "DEP-143",
          name: "Check Volume",
          description: "Check transaction dollar volume",
          formula: "SUM(transaction_amount WHERE channel = 'Check')",
          unit: "currency",
          aggregation: "SUM",
        },
        {
          id: "DEP-144",
          name: "P2P Transfer Count",
          description: "Peer-to-peer transfer count",
          formula: "COUNT(transaction_id WHERE type = 'P2P')",
          unit: "count",
          aggregation: "SUM",
        },
        {
          id: "DEP-145",
          name: "P2P Transfer Volume",
          description: "P2P transfer dollar volume",
          formula: "SUM(transaction_amount WHERE type = 'P2P')",
          unit: "currency",
          aggregation: "SUM",
        },
        {
          id: "DEP-146",
          name: "Bill Pay Transactions",
          description: "Bill payment transaction count",
          formula: "COUNT(transaction_id WHERE type = 'Bill Pay')",
          unit: "count",
          aggregation: "SUM",
        },
        {
          id: "DEP-147",
          name: "Mobile Deposit Transactions",
          description: "Mobile check deposit count",
          formula: "COUNT(transaction_id WHERE type = 'Mobile Deposit')",
          unit: "count",
          aggregation: "SUM",
        },
        {
          id: "DEP-148",
          name: "Mobile Deposit Volume",
          description: "Mobile check deposit dollar volume",
          formula: "SUM(transaction_amount WHERE type = 'Mobile Deposit')",
          unit: "currency",
          aggregation: "SUM",
        },
        {
          id: "DEP-149",
          name: "Same-Day ACH Count",
          description: "Same-day ACH transaction count",
          formula: "COUNT(transaction_id WHERE ach_type = 'Same-Day')",
          unit: "count",
          aggregation: "SUM",
        },
        {
          id: "DEP-150",
          name: "International Wire Count",
          description: "International wire transfer count",
          formula: "COUNT(transaction_id WHERE wire_type = 'International')",
          unit: "count",
          aggregation: "SUM",
        },
      ],
    },
    {
      name: "Profitability & FTP Metrics",
      metrics: [
        {
          id: "DEP-151",
          name: "Net Interest Income (Deposits)",
          description: "Net interest income from deposits",
          formula: "Interest Income - Interest Expense",
          unit: "currency",
          aggregation: "SUM",
        },
        {
          id: "DEP-152",
          name: "Total Deposit Revenue",
          description: "Total revenue from deposits",
          formula: "Fee Revenue + Interest Income - Interest Expense",
          unit: "currency",
          aggregation: "SUM",
        },
        {
          id: "DEP-153",
          name: "FTP Credit",
          description: "Funds transfer pricing credit",
          formula: "Average Balance * FTP Rate",
          unit: "currency",
          aggregation: "SUM",
        },
        {
          id: "DEP-154",
          name: "Net Interest Margin (Deposits)",
          description: "NIM on deposit portfolio",
          formula: "(Interest Income - Interest Expense) / Average Balance",
          unit: "percentage",
          aggregation: "AVG",
        },
        {
          id: "DEP-155",
          name: "Return on Deposits (ROD)",
          description: "Return on deposit assets",
          formula: "Net Income / Average Deposits",
          unit: "percentage",
          aggregation: "AVG",
        },
        {
          id: "DEP-156",
          name: "Deposit Operating Expense",
          description: "Operating costs for deposits",
          formula: "SUM(operating_expense)",
          unit: "currency",
          aggregation: "SUM",
        },
        {
          id: "DEP-157",
          name: "Cost-to-Income Ratio (Deposits)",
          description: "Operating efficiency ratio",
          formula: "Operating Expense / Total Revenue",
          unit: "ratio",
          aggregation: "AVG",
        },
        {
          id: "DEP-158",
          name: "Account Profitability (Avg)",
          description: "Average profit per account",
          formula: "AVG(account_profit)",
          unit: "currency",
          aggregation: "AVG",
        },
        {
          id: "DEP-159",
          name: "Profitable Account Count",
          description: "Accounts with positive profitability",
          formula: "COUNT(account_id WHERE profit > 0)",
          unit: "count",
          aggregation: "SUM",
        },
        {
          id: "DEP-160",
          name: "Unprofitable Account Count",
          description: "Accounts with negative profitability",
          formula: "COUNT(account_id WHERE profit < 0)",
          unit: "count",
          aggregation: "SUM",
        },
        {
          id: "DEP-161",
          name: "Profitability Rate",
          description: "Profitable accounts as % of total",
          formula: "Profitable Accounts / Total Accounts * 100",
          unit: "percentage",
          aggregation: "AVG",
        },
        {
          id: "DEP-162",
          name: "Customer Profitability (Avg)",
          description: "Average profit per customer",
          formula: "AVG(customer_profit)",
          unit: "currency",
          aggregation: "AVG",
        },
        {
          id: "DEP-163",
          name: "Product Profitability (DDA)",
          description: "DDA product profitability",
          formula: "SUM(profit WHERE product = 'DDA')",
          unit: "currency",
          aggregation: "SUM",
        },
        {
          id: "DEP-164",
          name: "Product Profitability (Savings)",
          description: "Savings product profitability",
          formula: "SUM(profit WHERE product = 'SAV')",
          unit: "currency",
          aggregation: "SUM",
        },
        {
          id: "DEP-165",
          name: "Product Profitability (MMA)",
          description: "MMA product profitability",
          formula: "SUM(profit WHERE product = 'MMA')",
          unit: "currency",
          aggregation: "SUM",
        },
        {
          id: "DEP-166",
          name: "Product Profitability (CD)",
          description: "CD product profitability",
          formula: "SUM(profit WHERE product = 'CD')",
          unit: "currency",
          aggregation: "SUM",
        },
        {
          id: "DEP-167",
          name: "Segment Profitability (Retail)",
          description: "Retail segment profitability",
          formula: "SUM(profit WHERE segment = 'Retail')",
          unit: "currency",
          aggregation: "SUM",
        },
        {
          id: "DEP-168",
          name: "Segment Profitability (Commercial)",
          description: "Commercial segment profitability",
          formula: "SUM(profit WHERE segment = 'Commercial')",
          unit: "currency",
          aggregation: "SUM",
        },
        {
          id: "DEP-169",
          name: "Branch Profitability",
          description: "Profitability by branch",
          formula: "SUM(profit) GROUP BY branch",
          unit: "currency",
          aggregation: "SUM",
        },
        {
          id: "DEP-170",
          name: "FTP Rate (Avg)",
          description: "Average FTP rate applied",
          formula: "AVG(ftp_rate)",
          unit: "percentage",
          aggregation: "AVG",
        },
        {
          id: "DEP-171",
          name: "Economic Value Added (EVA)",
          description: "Economic value from deposits",
          formula: "Net Income - (Capital * Cost of Capital)",
          unit: "currency",
          aggregation: "SUM",
        },
        {
          id: "DEP-172",
          name: "Revenue per Account (Avg)",
          description: "Average revenue per account",
          formula: "Total Revenue / Total Accounts",
          unit: "currency",
          aggregation: "AVG",
        },
        {
          id: "DEP-173",
          name: "Revenue per Customer (Avg)",
          description: "Average revenue per customer",
          formula: "Total Revenue / Total Customers",
          unit: "currency",
          aggregation: "AVG",
        },
        {
          id: "DEP-174",
          name: "Cross-Sell Revenue",
          description: "Revenue from cross-sold products",
          formula: "SUM(revenue WHERE cross_sell_flag = TRUE)",
          unit: "currency",
          aggregation: "SUM",
        },
        {
          id: "DEP-175",
          name: "Customer Acquisition ROI",
          description: "Return on customer acquisition spend",
          formula: "(Customer Lifetime Value - CAC) / CAC",
          unit: "ratio",
          aggregation: "AVG",
        },
        {
          id: "DEP-176",
          name: "Retention Cost per Account",
          description: "Cost to retain an account",
          formula: "Retention Spend / Retained Accounts",
          unit: "currency",
          aggregation: "AVG",
        },
        {
          id: "DEP-177",
          name: "Deposit Spread",
          description: "Earning asset yield vs deposit cost",
          formula: "Asset Yield - Deposit Cost",
          unit: "basis_points",
          aggregation: "AVG",
        },
        {
          id: "DEP-178",
          name: "Core Deposit Premium",
          description: "Value of core deposit franchise",
          formula: "Present Value of Core Deposit Cash Flows",
          unit: "currency",
          aggregation: "SUM",
        },
        {
          id: "DEP-179",
          name: "Duration of Deposits",
          description: "Weighted average duration",
          formula: "Weighted Average Duration by Product",
          unit: "years",
          aggregation: "AVG",
        },
        {
          id: "DEP-180",
          name: "Deposit Pricing Power",
          description: "Ability to price below market",
          formula: "Market Rate - Bank Rate",
          unit: "basis_points",
          aggregation: "AVG",
        },
      ],
    },
    {
      name: "Regulatory & Compliance Metrics",
      metrics: [
        {
          id: "DEP-181",
          name: "LCR - High-Quality Liquid Assets (HQLA)",
          description: "HQLA for LCR calculation",
          formula: "SUM(hqla_amount)",
          unit: "currency",
          aggregation: "SUM",
        },
        {
          id: "DEP-182",
          name: "LCR - Stable Retail Deposits",
          description: "Stable retail deposits for LCR",
          formula: "SUM(balance WHERE stable_retail = TRUE)",
          unit: "currency",
          aggregation: "SUM",
        },
        {
          id: "DEP-183",
          name: "LCR - Less Stable Retail Deposits",
          description: "Less stable retail deposits",
          formula:
            "SUM(balance WHERE stable_retail = FALSE AND segment = 'Retail')",
          unit: "currency",
          aggregation: "SUM",
        },
        {
          id: "DEP-184",
          name: "LCR - Operational Deposits",
          description: "Operational deposits from corporates",
          formula: "SUM(balance WHERE operational_flag = TRUE)",
          unit: "currency",
          aggregation: "SUM",
        },
        {
          id: "DEP-185",
          name: "LCR - Non-Operational Deposits",
          description: "Non-operational wholesale deposits",
          formula:
            "SUM(balance WHERE operational_flag = FALSE AND segment = 'Commercial')",
          unit: "currency",
          aggregation: "SUM",
        },
        {
          id: "DEP-186",
          name: "LCR Ratio",
          description: "Liquidity Coverage Ratio",
          formula: "HQLA / Net Cash Outflows (30d)",
          unit: "percentage",
          aggregation: "AVG",
        },
        {
          id: "DEP-187",
          name: "NSFR - Available Stable Funding (ASF)",
          description: "ASF for NSFR calculation",
          formula: "SUM(balance * asf_factor)",
          unit: "currency",
          aggregation: "SUM",
        },
        {
          id: "DEP-188",
          name: "NSFR Ratio",
          description: "Net Stable Funding Ratio",
          formula: "ASF / RSF",
          unit: "percentage",
          aggregation: "AVG",
        },
        {
          id: "DEP-189",
          name: "Reg D - Excess Withdrawal Accounts",
          description: "Accounts exceeding 6 withdrawals",
          formula: "COUNT(account_id WHERE withdrawal_count > 6)",
          unit: "count",
          aggregation: "SUM",
        },
        {
          id: "DEP-190",
          name: "Reg D - Violation Rate",
          description: "Reg D violation rate",
          formula: "Violation Accounts / Total Savings+MMA * 100",
          unit: "percentage",
          aggregation: "AVG",
        },
        {
          id: "DEP-191",
          name: "Reg DD - Disclosure Compliance",
          description: "Timely disclosure compliance rate",
          formula: "Compliant Disclosures / Total Disclosures * 100",
          unit: "percentage",
          aggregation: "AVG",
        },
        {
          id: "DEP-192",
          name: "Reg E - Unauthorized Transaction Claims",
          description: "Reg E error resolution claims",
          formula: "COUNT(claim_id WHERE reg_e_claim = TRUE)",
          unit: "count",
          aggregation: "SUM",
        },
        {
          id: "DEP-193",
          name: "Reg E - Resolution Timeliness",
          description: "% resolved within 10 business days",
          formula: "Resolved Timely / Total Claims * 100",
          unit: "percentage",
          aggregation: "AVG",
        },
        {
          id: "DEP-194",
          name: "BSA/AML - CTR Filings",
          description: "Currency Transaction Reports filed",
          formula: "COUNT(ctr_id)",
          unit: "count",
          aggregation: "SUM",
        },
        {
          id: "DEP-195",
          name: "BSA/AML - SAR Filings (Deposits)",
          description: "Suspicious Activity Reports",
          formula: "COUNT(sar_id WHERE domain = 'Deposits')",
          unit: "count",
          aggregation: "SUM",
        },
        {
          id: "DEP-196",
          name: "KYC - Customer Due Diligence (CDD)",
          description: "CDD completion rate",
          formula: "CDD Completed / New Accounts * 100",
          unit: "percentage",
          aggregation: "AVG",
        },
        {
          id: "DEP-197",
          name: "KYC - Enhanced Due Diligence (EDD)",
          description: "High-risk accounts requiring EDD",
          formula: "COUNT(account_id WHERE edd_required = TRUE)",
          unit: "count",
          aggregation: "SUM",
        },
        {
          id: "DEP-198",
          name: "OFAC - Sanctions Screening Hits",
          description: "OFAC screening matches",
          formula: "COUNT(ofac_hit_id)",
          unit: "count",
          aggregation: "SUM",
        },
        {
          id: "DEP-199",
          name: "OFAC - False Positive Rate",
          description: "False positive screening rate",
          formula: "False Positives / Total Hits * 100",
          unit: "percentage",
          aggregation: "AVG",
        },
        {
          id: "DEP-200",
          name: "FDIC - Insured Deposit Coverage",
          description: "% of deposits under FDIC insurance",
          formula: "Insured Amount / Total Deposits * 100",
          unit: "percentage",
          aggregation: "AVG",
        },
        {
          id: "DEP-201",
          name: "FDIC - Uninsured Deposit Exposure",
          description: "Uninsured deposit amount",
          formula: "SUM(uninsured_amount)",
          unit: "currency",
          aggregation: "SUM",
        },
        {
          id: "DEP-202",
          name: "Capital Allocation - Risk-Weighted Assets",
          description: "RWA for deposit portfolio",
          formula: "SUM(balance * risk_weight)",
          unit: "currency",
          aggregation: "SUM",
        },
        {
          id: "DEP-203",
          name: "Escheatment - Unclaimed Property",
          description: "Balances subject to escheatment",
          formula: "SUM(balance WHERE escheat_eligible = TRUE)",
          unit: "currency",
          aggregation: "SUM",
        },
        {
          id: "DEP-204",
          name: "Escheatment - Remittance to States",
          description: "Amounts remitted to states",
          formula: "SUM(escheat_remitted)",
          unit: "currency",
          aggregation: "SUM",
        },
        {
          id: "DEP-205",
          name: "Privacy - Opt-Out Rate",
          description: "Privacy policy opt-out rate",
          formula: "Opt-Outs / Total Customers * 100",
          unit: "percentage",
          aggregation: "AVG",
        },
        {
          id: "DEP-206",
          name: "Fair Lending - Underserved Accounts",
          description: "Accounts in LMI areas",
          formula: "COUNT(account_id WHERE lmi_flag = TRUE)",
          unit: "count",
          aggregation: "SUM",
        },
        {
          id: "DEP-207",
          name: "CRA - Community Reinvestment",
          description: "Deposits in CRA assessment areas",
          formula: "SUM(balance WHERE cra_area = TRUE)",
          unit: "currency",
          aggregation: "SUM",
        },
        {
          id: "DEP-208",
          name: "Deposit Insurance Premium",
          description: "FDIC insurance assessment",
          formula: "Average Balance * Assessment Rate",
          unit: "currency",
          aggregation: "SUM",
        },
        {
          id: "DEP-209",
          name: "Stress Test - Runoff Scenario",
          description: "Projected deposit runoff under stress",
          formula: "SUM(balance * stress_runoff_rate)",
          unit: "currency",
          aggregation: "SUM",
        },
        {
          id: "DEP-210",
          name: "Stress Test - Beta Assumption",
          description: "Deposit beta under rate shock",
          formula: "AVG(stress_beta)",
          unit: "ratio",
          aggregation: "AVG",
        },
      ],
    },
    {
      name: "ALCO & Treasury Metrics",
      metrics: [
        {
          id: "DEP-211",
          name: "Liquidity Ratio",
          description: "Liquid assets to deposits ratio",
          formula: "Liquid Assets / Total Deposits",
          unit: "ratio",
          aggregation: "AVG",
        },
        {
          id: "DEP-212",
          name: "Loan-to-Deposit Ratio (LTD)",
          description: "Loans to deposits ratio",
          formula: "Total Loans / Total Deposits",
          unit: "ratio",
          aggregation: "AVG",
        },
        {
          id: "DEP-213",
          name: "Deposit-to-Asset Ratio",
          description: "Deposits to total assets ratio",
          formula: "Total Deposits / Total Assets",
          unit: "ratio",
          aggregation: "AVG",
        },
        {
          id: "DEP-214",
          name: "Wholesale Funding Ratio",
          description: "Wholesale funding reliance",
          formula: "Wholesale Funding / Total Funding",
          unit: "ratio",
          aggregation: "AVG",
        },
        {
          id: "DEP-215",
          name: "Core Funding Ratio",
          description: "Core deposits to total assets",
          formula: "Core Deposits / Total Assets",
          unit: "ratio",
          aggregation: "AVG",
        },
        {
          id: "DEP-216",
          name: "Deposit Concentration (Geographic)",
          description: "Deposits by state/region",
          formula: "SUM(balance) GROUP BY state",
          unit: "currency",
          aggregation: "SUM",
        },
        {
          id: "DEP-217",
          name: "Deposit Concentration (Product)",
          description: "Deposits by product type",
          formula: "SUM(balance) GROUP BY product",
          unit: "currency",
          aggregation: "SUM",
        },
        {
          id: "DEP-218",
          name: "Deposit Runoff Rate (Historical)",
          description: "Historical monthly runoff rate",
          formula: "Avg(Closing Balance - Opening Balance) / Opening Balance",
          unit: "percentage",
          aggregation: "AVG",
        },
        {
          id: "DEP-219",
          name: "Deposit Velocity",
          description: "Deposit turnover velocity",
          formula: "Transaction Volume / Average Balance",
          unit: "ratio",
          aggregation: "AVG",
        },
        {
          id: "DEP-220",
          name: "Deposit Duration Gap",
          description: "Asset-liability duration mismatch",
          formula: "Asset Duration - Deposit Duration",
          unit: "years",
          aggregation: "AVG",
        },
        {
          id: "DEP-221",
          name: "Interest Rate Risk (IRR) - EVE",
          description: "Economic Value of Equity sensitivity",
          formula: "Change in EVE / 100bp rate shock",
          unit: "percentage",
          aggregation: "AVG",
        },
        {
          id: "DEP-222",
          name: "Interest Rate Risk (IRR) - NII",
          description: "Net Interest Income sensitivity",
          formula: "Change in NII / 100bp rate shock",
          unit: "percentage",
          aggregation: "AVG",
        },
        {
          id: "DEP-223",
          name: "Repricing Gap (1 Year)",
          description: "1-year repricing gap",
          formula: "Rate-Sensitive Assets - Rate-Sensitive Liabilities",
          unit: "currency",
          aggregation: "SUM",
        },
        {
          id: "DEP-224",
          name: "Beta Coefficient",
          description: "Deposit rate sensitivity to market rates",
          formula: "Change in Deposit Rate / Change in Market Rate",
          unit: "ratio",
          aggregation: "AVG",
        },
        {
          id: "DEP-225",
          name: "Stable Deposit Ratio",
          description: "Core stable deposits as % of total",
          formula: "Stable Deposits / Total Deposits * 100",
          unit: "percentage",
          aggregation: "AVG",
        },
        {
          id: "DEP-226",
          name: "Volatile Deposit Ratio",
          description: "Rate-sensitive deposits as % of total",
          formula: "Volatile Deposits / Total Deposits * 100",
          unit: "percentage",
          aggregation: "AVG",
        },
        {
          id: "DEP-227",
          name: "Hot Money Ratio",
          description: "Short-term volatile deposits",
          formula: "Hot Money / Total Deposits",
          unit: "ratio",
          aggregation: "AVG",
        },
        {
          id: "DEP-228",
          name: "Deposit Mix Optimization Score",
          description: "Optimal deposit product mix score",
          formula: "Weighted score across cost, stability, growth",
          unit: "score",
          aggregation: "AVG",
        },
        {
          id: "DEP-229",
          name: "Liquidity Coverage (30-Day)",
          description: "30-day liquidity coverage",
          formula: "Liquid Assets / 30-Day Net Outflows",
          unit: "ratio",
          aggregation: "AVG",
        },
        {
          id: "DEP-230",
          name: "Liquidity Coverage (90-Day)",
          description: "90-day liquidity coverage",
          formula: "Liquid Assets / 90-Day Net Outflows",
          unit: "ratio",
          aggregation: "AVG",
        },
        {
          id: "DEP-231",
          name: "Contingent Liquidity Available",
          description: "Available contingent liquidity",
          formula: "SUM(contingent_liquidity_sources)",
          unit: "currency",
          aggregation: "SUM",
        },
        {
          id: "DEP-232",
          name: "Federal Home Loan Bank (FHLB) Capacity",
          description: "Borrowing capacity at FHLB",
          formula: "FHLB Borrowing Limit - Current Borrowings",
          unit: "currency",
          aggregation: "SUM",
        },
        {
          id: "DEP-233",
          name: "Discount Window Capacity",
          description: "Federal Reserve discount window capacity",
          formula: "Eligible Collateral Value * Haircut",
          unit: "currency",
          aggregation: "SUM",
        },
        {
          id: "DEP-234",
          name: "Unencumbered Assets",
          description: "Unencumbered liquid assets",
          formula: "SUM(asset_value WHERE unencumbered = TRUE)",
          unit: "currency",
          aggregation: "SUM",
        },
        {
          id: "DEP-235",
          name: "Pledged Collateral",
          description: "Assets pledged as collateral",
          formula: "SUM(asset_value WHERE pledged = TRUE)",
          unit: "currency",
          aggregation: "SUM",
        },
        {
          id: "DEP-236",
          name: "Funding Diversification Index",
          description: "Diversity of funding sources",
          formula: "Herfindahl Index of Deposit Sources",
          unit: "score",
          aggregation: "AVG",
        },
        {
          id: "DEP-237",
          name: "Deposit Franchise Value",
          description: "Value of deposit franchise",
          formula: "NPV(Core Deposit Cash Flows)",
          unit: "currency",
          aggregation: "SUM",
        },
        {
          id: "DEP-238",
          name: "Marginal Cost of Funds",
          description: "Cost of next dollar of deposits",
          formula: "Incremental Interest Expense / Incremental Balance",
          unit: "percentage",
          aggregation: "AVG",
        },
        {
          id: "DEP-239",
          name: "All-In Cost of Deposits",
          description: "Total cost including interest and ops",
          formula: "(Interest Expense + Operating Expense) / Average Balance",
          unit: "percentage",
          aggregation: "AVG",
        },
        {
          id: "DEP-240",
          name: "Replacement Cost of Deposits",
          description: "Cost to replace deposits in market",
          formula: "Market Rate - Current Rate",
          unit: "basis_points",
          aggregation: "AVG",
        },
      ],
    },
    {
      name: "Product Performance Metrics",
      metrics: [
        {
          id: "DEP-241",
          name: "DDA Market Share",
          description: "DDA market share in region",
          formula: "Bank DDA Balance / Market DDA Balance * 100",
          unit: "percentage",
          aggregation: "AVG",
        },
        {
          id: "DEP-242",
          name: "Savings Market Share",
          description: "Savings market share",
          formula: "Bank SAV Balance / Market SAV Balance * 100",
          unit: "percentage",
          aggregation: "AVG",
        },
        {
          id: "DEP-243",
          name: "MMA Market Share",
          description: "MMA market share",
          formula: "Bank MMA Balance / Market MMA Balance * 100",
          unit: "percentage",
          aggregation: "AVG",
        },
        {
          id: "DEP-244",
          name: "CD Market Share",
          description: "CD market share",
          formula: "Bank CD Balance / Market CD Balance * 100",
          unit: "percentage",
          aggregation: "AVG",
        },
        {
          id: "DEP-245",
          name: "DDA Average Balance",
          description: "Average DDA balance",
          formula: "AVG(balance WHERE product = 'DDA')",
          unit: "currency",
          aggregation: "AVG",
        },
        {
          id: "DEP-246",
          name: "Savings Average Balance",
          description: "Average savings balance",
          formula: "AVG(balance WHERE product = 'SAV')",
          unit: "currency",
          aggregation: "AVG",
        },
        {
          id: "DEP-247",
          name: "MMA Average Balance",
          description: "Average MMA balance",
          formula: "AVG(balance WHERE product = 'MMA')",
          unit: "currency",
          aggregation: "AVG",
        },
        {
          id: "DEP-248",
          name: "CD Average Balance",
          description: "Average CD balance",
          formula: "AVG(balance WHERE product = 'CD')",
          unit: "currency",
          aggregation: "AVG",
        },
        {
          id: "DEP-249",
          name: "DDA Growth Rate",
          description: "DDA balance growth rate",
          formula: "(Current DDA - Prior DDA) / Prior DDA * 100",
          unit: "percentage",
          aggregation: "AVG",
        },
        {
          id: "DEP-250",
          name: "Savings Growth Rate",
          description: "Savings balance growth rate",
          formula: "(Current SAV - Prior SAV) / Prior SAV * 100",
          unit: "percentage",
          aggregation: "AVG",
        },
        {
          id: "DEP-251",
          name: "MMA Growth Rate",
          description: "MMA balance growth rate",
          formula: "(Current MMA - Prior MMA) / Prior MMA * 100",
          unit: "percentage",
          aggregation: "AVG",
        },
        {
          id: "DEP-252",
          name: "CD Growth Rate",
          description: "CD balance growth rate",
          formula: "(Current CD - Prior CD) / Prior CD * 100",
          unit: "percentage",
          aggregation: "AVG",
        },
        {
          id: "DEP-253",
          name: "Premium DDA Balances",
          description: "Premium/high-value DDA balances",
          formula: "SUM(balance WHERE product = 'Premium DDA')",
          unit: "currency",
          aggregation: "SUM",
        },
        {
          id: "DEP-254",
          name: "Basic DDA Balances",
          description: "Basic/low-fee DDA balances",
          formula: "SUM(balance WHERE product = 'Basic DDA')",
          unit: "currency",
          aggregation: "SUM",
        },
        {
          id: "DEP-255",
          name: "Student DDA Balances",
          description: "Student checking balances",
          formula: "SUM(balance WHERE product = 'Student DDA')",
          unit: "currency",
          aggregation: "SUM",
        },
        {
          id: "DEP-256",
          name: "Senior DDA Balances",
          description: "Senior checking balances",
          formula: "SUM(balance WHERE product = 'Senior DDA')",
          unit: "currency",
          aggregation: "SUM",
        },
        {
          id: "DEP-257",
          name: "Business DDA Balances",
          description: "Business checking balances",
          formula: "SUM(balance WHERE product = 'Business DDA')",
          unit: "currency",
          aggregation: "SUM",
        },
        {
          id: "DEP-258",
          name: "High-Yield Savings Balances",
          description: "High-yield savings balances",
          formula: "SUM(balance WHERE product = 'HYSA')",
          unit: "currency",
          aggregation: "SUM",
        },
        {
          id: "DEP-259",
          name: "Health Savings Account (HSA) Balances",
          description: "HSA deposit balances",
          formula: "SUM(balance WHERE product = 'HSA')",
          unit: "currency",
          aggregation: "SUM",
        },
        {
          id: "DEP-260",
          name: "Sweep Account Balances",
          description: "Sweep account balances",
          formula: "SUM(balance WHERE product = 'Sweep')",
          unit: "currency",
          aggregation: "SUM",
        },
        {
          id: "DEP-261",
          name: "Escrow Account Balances",
          description: "Escrow deposit balances",
          formula: "SUM(balance WHERE product = 'Escrow')",
          unit: "currency",
          aggregation: "SUM",
        },
        {
          id: "DEP-262",
          name: "IOLTA Account Balances",
          description: "IOLTA (lawyer trust) balances",
          formula: "SUM(balance WHERE product = 'IOLTA')",
          unit: "currency",
          aggregation: "SUM",
        },
        {
          id: "DEP-263",
          name: "Custodial Account Balances",
          description: "Custodial account balances (UTMA/UGMA)",
          formula: "SUM(balance WHERE product = 'Custodial')",
          unit: "currency",
          aggregation: "SUM",
        },
        {
          id: "DEP-264",
          name: "Trust Account Balances",
          description: "Trust deposit balances",
          formula: "SUM(balance WHERE product = 'Trust')",
          unit: "currency",
          aggregation: "SUM",
        },
        {
          id: "DEP-265",
          name: "Tiered Rate Adoption",
          description: "% of balances in tiered rate products",
          formula: "Tiered Balance / Total Balance * 100",
          unit: "percentage",
          aggregation: "AVG",
        },
        {
          id: "DEP-266",
          name: "Promotional Product Balances",
          description: "Balances in promotional products",
          formula: "SUM(balance WHERE promo_flag = TRUE)",
          unit: "currency",
          aggregation: "SUM",
        },
        {
          id: "DEP-267",
          name: "Product Conversion Rate",
          description: "Product upgrade/conversion rate",
          formula: "Product Conversions / Eligible Accounts * 100",
          unit: "percentage",
          aggregation: "AVG",
        },
        {
          id: "DEP-268",
          name: "Product Downgrade Rate",
          description: "Product downgrade rate",
          formula: "Product Downgrades / Total Accounts * 100",
          unit: "percentage",
          aggregation: "AVG",
        },
        {
          id: "DEP-269",
          name: "Bundled Product Penetration",
          description: "% of customers with bundled products",
          formula: "Bundled Customers / Total Customers * 100",
          unit: "percentage",
          aggregation: "AVG",
        },
        {
          id: "DEP-270",
          name: "Relationship Pricing Adoption",
          description: "% using relationship-based pricing",
          formula: "Relationship Pricing Accounts / Total Accounts * 100",
          unit: "percentage",
          aggregation: "AVG",
        },
      ],
    },
    {
      name: "Risk & Quality Metrics",
      metrics: [
        {
          id: "DEP-271",
          name: "Overdraft Incidents",
          description: "Total overdraft incidents",
          formula: "COUNT(overdraft_id)",
          unit: "count",
          aggregation: "SUM",
        },
        {
          id: "DEP-272",
          name: "NSF Incidents",
          description: "Non-sufficient funds incidents",
          formula: "COUNT(nsf_id)",
          unit: "count",
          aggregation: "SUM",
        },
        {
          id: "DEP-273",
          name: "Overdraft Rate",
          description: "Accounts with overdrafts",
          formula: "OD Accounts / Total DDA * 100",
          unit: "percentage",
          aggregation: "AVG",
        },
        {
          id: "DEP-274",
          name: "Average Overdraft Amount",
          description: "Average overdraft amount",
          formula: "AVG(overdraft_amount)",
          unit: "currency",
          aggregation: "AVG",
        },
        {
          id: "DEP-275",
          name: "Overdraft Loss Rate",
          description: "Overdraft charge-offs",
          formula: "OD Charge-offs / OD Balances * 100",
          unit: "percentage",
          aggregation: "AVG",
        },
        {
          id: "DEP-276",
          name: "Returned Deposit Items",
          description: "Deposited items returned",
          formula: "COUNT(return_id WHERE item_type = 'Deposit')",
          unit: "count",
          aggregation: "SUM",
        },
        {
          id: "DEP-277",
          name: "Returned Check Rate",
          description: "Checks returned vs total checks",
          formula: "Returned Checks / Total Checks * 100",
          unit: "percentage",
          aggregation: "AVG",
        },
        {
          id: "DEP-278",
          name: "Kiting Detection Alerts",
          description: "Check kiting alerts",
          formula: "COUNT(alert_id WHERE alert_type = 'Kiting')",
          unit: "count",
          aggregation: "SUM",
        },
        {
          id: "DEP-279",
          name: "Fraud Incidents (Deposits)",
          description: "Deposit-related fraud incidents",
          formula: "COUNT(fraud_id WHERE domain = 'Deposits')",
          unit: "count",
          aggregation: "SUM",
        },
        {
          id: "DEP-280",
          name: "Fraud Loss (Deposits)",
          description: "Fraud losses on deposits",
          formula: "SUM(fraud_loss_amount WHERE domain = 'Deposits')",
          unit: "currency",
          aggregation: "SUM",
        },
        {
          id: "DEP-281",
          name: "Fraud Loss Rate",
          description: "Fraud losses as % of balances",
          formula: "Fraud Losses / Total Balances * 100",
          unit: "percentage",
          aggregation: "AVG",
        },
        {
          id: "DEP-282",
          name: "Account Takeover (ATO) Incidents",
          description: "Account takeover cases",
          formula: "COUNT(ato_id)",
          unit: "count",
          aggregation: "SUM",
        },
        {
          id: "DEP-283",
          name: "Unauthorized ACH Rate",
          description: "Unauthorized ACH transactions",
          formula: "Unauthorized ACH / Total ACH * 100",
          unit: "percentage",
          aggregation: "AVG",
        },
        {
          id: "DEP-284",
          name: "Check Fraud Rate",
          description: "Fraudulent checks",
          formula: "Fraudulent Checks / Total Checks * 100",
          unit: "percentage",
          aggregation: "AVG",
        },
        {
          id: "DEP-285",
          name: "Mobile Deposit Fraud Rate",
          description: "Mobile deposit fraud incidents",
          formula: "Fraud Mobile Deposits / Total Mobile Deposits * 100",
          unit: "percentage",
          aggregation: "AVG",
        },
        {
          id: "DEP-286",
          name: "Chargeback Rate",
          description: "Transaction chargebacks",
          formula: "Chargebacks / Total Transactions * 100",
          unit: "percentage",
          aggregation: "AVG",
        },
        {
          id: "DEP-287",
          name: "Error Rate (Deposits)",
          description: "Deposit processing errors",
          formula: "Errors / Total Deposits * 100",
          unit: "percentage",
          aggregation: "AVG",
        },
        {
          id: "DEP-288",
          name: "Exception Rate",
          description: "Exception items requiring review",
          formula: "Exceptions / Total Transactions * 100",
          unit: "percentage",
          aggregation: "AVG",
        },
        {
          id: "DEP-289",
          name: "Recon Break Rate",
          description: "Reconciliation breaks",
          formula: "Recon Breaks / Total Recons * 100",
          unit: "percentage",
          aggregation: "AVG",
        },
        {
          id: "DEP-290",
          name: "Data Quality Score (Deposits)",
          description: "Data quality score",
          formula: "AVG(dq_score)",
          unit: "score",
          aggregation: "AVG",
        },
        {
          id: "DEP-291",
          name: "SLA Compliance (Deposits)",
          description: "Process SLA compliance",
          formula: "SLA Met / Total Processes * 100",
          unit: "percentage",
          aggregation: "AVG",
        },
        {
          id: "DEP-292",
          name: "Account Opening Decline Rate",
          description: "Account applications declined",
          formula: "Declined Applications / Total Applications * 100",
          unit: "percentage",
          aggregation: "AVG",
        },
        {
          id: "DEP-293",
          name: "Account Closure Reason - Customer",
          description: "Customer-initiated closures",
          formula: "COUNT(account_id WHERE close_reason = 'Customer')",
          unit: "count",
          aggregation: "SUM",
        },
        {
          id: "DEP-294",
          name: "Account Closure Reason - Bank",
          description: "Bank-initiated closures",
          formula: "COUNT(account_id WHERE close_reason = 'Bank')",
          unit: "count",
          aggregation: "SUM",
        },
        {
          id: "DEP-295",
          name: "Involuntary Closure Rate",
          description: "Bank-forced closures",
          formula: "Bank Closures / Total Closures * 100",
          unit: "percentage",
          aggregation: "AVG",
        },
        {
          id: "DEP-296",
          name: "Negative Balance Days",
          description: "Days accounts in negative balance",
          formula: "SUM(negative_balance_days)",
          unit: "days",
          aggregation: "SUM",
        },
        {
          id: "DEP-297",
          name: "Negative Balance Recovery Rate",
          description: "Negative balances recovered",
          formula: "Recovered Balances / Total Negative Balances * 100",
          unit: "percentage",
          aggregation: "AVG",
        },
        {
          id: "DEP-298",
          name: "Charge-Off Rate (Deposits)",
          description: "Deposit-related charge-offs",
          formula: "Charge-Offs / Total Balances * 100",
          unit: "percentage",
          aggregation: "AVG",
        },
        {
          id: "DEP-299",
          name: "Recovery Rate (Deposits)",
          description: "Recovery on charged-off balances",
          formula: "Recoveries / Charge-Offs * 100",
          unit: "percentage",
          aggregation: "AVG",
        },
        {
          id: "DEP-300",
          name: "Operational Loss (Deposits)",
          description: "Operational losses on deposits",
          formula: "SUM(operational_loss_amount)",
          unit: "currency",
          aggregation: "SUM",
        },
      ],
    },
  ],
};

// ============================================================================
// WORKFLOWS & PROCESSES
// ============================================================================

export const depositsWorkflows = {
  accountOpening: {
    name: "Deposit Account Opening",
    steps: [
      "Application",
      "KYC/CDD",
      "Identity Verification",
      "Funding",
      "Account Activation",
    ],
    sla: "Same-day or 1 business day",
    automation: "80% straight-through processing",
  },
  interestAccrual: {
    name: "Daily Interest Accrual",
    steps: [
      "Balance Snapshot",
      "Rate Lookup",
      "Accrual Calculation",
      "Posting",
      "Reconciliation",
    ],
    sla: "EOD daily",
    automation: "100% automated",
  },
  statementGeneration: {
    name: "Monthly Statement Cycle",
    steps: [
      "Cycle Close",
      "Transaction Aggregation",
      "Statement Generation",
      "Delivery (Print/Email)",
      "Archival",
    ],
    sla: "5 business days post-cycle",
    automation: "95% automated",
  },
  feeAssessment: {
    name: "Fee Assessment & Charging",
    steps: [
      "Fee Event Detection",
      "Fee Calculation",
      "Waiver Check",
      "Fee Posting",
      "Customer Notification",
    ],
    sla: "Real-time or daily batch",
    automation: "90% automated",
  },
  cdMaturity: {
    name: "CD Maturity Processing",
    steps: [
      "Maturity Detection",
      "Customer Notification",
      "Renewal/Closure Processing",
      "Interest Posting",
      "Confirmation",
    ],
    sla: "10 days before maturity notification",
    automation: "85% automated",
  },
  regulatoryReporting: {
    name: "Regulatory Reporting (Call Report, LCR, NSFR)",
    steps: [
      "Data Extraction",
      "Calculation & Aggregation",
      "Validation",
      "Report Generation",
      "Submission",
    ],
    sla: "Quarterly (Call Report), Daily/Monthly (LCR/NSFR)",
    automation: "70% automated",
  },
};

// ============================================================================
// REGULATORY CONTEXT
// ============================================================================

export const depositsRegulatoryFramework = {
  primaryRegulations: [
    {
      regulation: "Regulation D",
      description: "Reserve requirements and withdrawal limits on savings",
      authority: "Federal Reserve",
    },
    {
      regulation: "Regulation DD",
      description: "Truth in Savings Act - disclosure requirements",
      authority: "Federal Reserve",
    },
    {
      regulation: "Regulation E",
      description: "Electronic Fund Transfers - error resolution",
      authority: "Federal Reserve",
    },
    {
      regulation: "Regulation CC",
      description: "Expedited Funds Availability Act - hold periods",
      authority: "Federal Reserve",
    },
    {
      regulation: "FDIC Insurance",
      description: "$250,000 per depositor per institution",
      authority: "FDIC",
    },
    {
      regulation: "Basel III Liquidity (LCR/NSFR)",
      description: "Liquidity coverage and stable funding ratios",
      authority: "Basel Committee / Fed",
    },
    {
      regulation: "BSA/AML",
      description: "Bank Secrecy Act / Anti-Money Laundering (CTR, SAR)",
      authority: "FinCEN",
    },
    {
      regulation: "OFAC Sanctions",
      description: "Sanctions screening for deposit accounts",
      authority: "OFAC",
    },
    {
      regulation: "KYC/CDD",
      description: "Know Your Customer / Customer Due Diligence",
      authority: "FinCEN / OCC",
    },
    {
      regulation: "Escheatment Laws",
      description: "Unclaimed property remittance to states",
      authority: "State Agencies",
    },
    {
      regulation: "CRA",
      description: "Community Reinvestment Act - LMI deposit gathering",
      authority: "OCC / Federal Reserve",
    },
    {
      regulation: "Fair Lending (ECOA)",
      description: "Equal Credit Opportunity Act - account opening",
      authority: "CFPB",
    },
  ],
  reportingRequirements: [
    {
      report: "Call Report (FFIEC 031/041)",
      frequency: "Quarterly",
      description: "Deposit balances by category",
    },
    {
      report: "LCR Report",
      frequency: "Daily (large banks), Monthly (others)",
      description: "Liquidity Coverage Ratio",
    },
    {
      report: "NSFR Report",
      frequency: "Quarterly",
      description: "Net Stable Funding Ratio",
    },
    {
      report: "CTR (Currency Transaction Report)",
      frequency: "Event-driven (>$10K cash)",
      description: "Large cash transactions",
    },
    {
      report: "SAR (Suspicious Activity Report)",
      frequency: "Event-driven",
      description: "Suspicious deposit activity",
    },
    {
      report: "Reg D Reserve Report",
      frequency: "Weekly",
      description: "Reserve requirement calculation",
    },
  ],
};

// ============================================================================
// DATA QUALITY RULES
// ============================================================================

export const depositsDataQualityRules = {
  completeness: [
    "Account ID must be populated for all records",
    "Customer ID must be linked to valid customer record",
    "Product code must be from valid product catalog",
    "Balance amounts must be non-null",
  ],
  accuracy: [
    "Daily balances must reconcile to core banking system",
    "Interest calculations must match rate schedules",
    "Fee amounts must align with published fee schedule",
    "Transaction totals must balance (debits = credits)",
  ],
  consistency: [
    "Account status must be consistent across all systems",
    "Product hierarchies must be consistent",
    "Branch assignments must be valid and consistent",
    "Customer relationships must be bidirectional",
  ],
  timeliness: [
    "EOD balances must be available by T+1 8:00 AM",
    "Transactions must be posted within SLA (same-day or T+1)",
    "Interest accruals must complete by EOD",
    "Regulatory reports must meet submission deadlines",
  ],
  validity: [
    "Account numbers must follow standard format",
    "Product codes must be in approved list",
    "Interest rates must be within valid ranges",
    "Transaction types must be from valid domain",
  ],
  uniqueness: [
    "Account IDs must be unique",
    "Transaction IDs must be unique",
    "Customer-facing account numbers must be unique",
  ],
};

// ============================================================================
// ROW-LEVEL SECURITY (RLS) POLICIES
// ============================================================================

export const depositsRLSPolicies = {
  description: "Row-level security policies for deposits domain",
  policies: [
    {
      name: "branch_based_access",
      table: "gold.fact_deposit_positions",
      condition:
        "user_branch_id IN (SELECT branch_id FROM user_branch_assignments WHERE user_id = CURRENT_USER)",
      description:
        "Users can only see deposits for branches they're assigned to",
    },
    {
      name: "region_based_access",
      table: "gold.fact_deposit_positions",
      condition:
        "branch_region IN (SELECT region FROM user_region_assignments WHERE user_id = CURRENT_USER)",
      description: "Regional managers see all branches in their region",
    },
    {
      name: "segment_based_access",
      table: "gold.fact_deposit_positions",
      condition:
        "customer_segment IN (SELECT segment FROM user_segment_access WHERE user_id = CURRENT_USER)",
      description: "Segment-specific access (e.g., retail vs commercial)",
    },
    {
      name: "pii_masking",
      table: "silver.account_master_golden",
      condition:
        "CASE WHEN user_role = 'Analytics' THEN MASK(account_number) ELSE account_number END",
      description:
        "Mask PII for analytics users without customer service access",
    },
  ],
};

// ============================================================================
// QUERY COOKBOOK - COMMON ANALYTICAL QUERIES
// ============================================================================

export const depositsQueryCookbook = {
  description: "Pre-built analytical queries for deposits domain",
  queries: [
    {
      name: "Monthly Deposit Trending",
      sql: `
SELECT 
  DATE_TRUNC('month', as_of_date) as month,
  SUM(balance_amount) as total_balance,
  COUNT(DISTINCT account_key) as account_count,
  AVG(balance_amount) as avg_balance_per_account
FROM gold.fact_deposit_positions
WHERE as_of_date >= CURRENT_DATE - INTERVAL '24 months'
GROUP BY month
ORDER BY month;
      `,
    },
    {
      name: "Product Mix Analysis",
      sql: `
SELECT 
  p.product_name,
  SUM(f.balance_amount) as total_balance,
  SUM(f.balance_amount) / SUM(SUM(f.balance_amount)) OVER () * 100 as pct_of_total,
  COUNT(DISTINCT f.account_key) as account_count,
  AVG(f.balance_amount) as avg_balance
FROM gold.fact_deposit_positions f
JOIN gold.dim_deposit_product p ON f.product_key = p.product_key
WHERE f.as_of_date = CURRENT_DATE
GROUP BY p.product_name
ORDER BY total_balance DESC;
      `,
    },
    {
      name: "Top 20 Depositors (Concentration Risk)",
      sql: `
SELECT 
  c.customer_name,
  SUM(f.balance_amount) as total_deposits,
  SUM(f.balance_amount) / (SELECT SUM(balance_amount) FROM gold.fact_deposit_positions WHERE as_of_date = CURRENT_DATE) * 100 as pct_of_total
FROM gold.fact_deposit_positions f
JOIN gold.dim_deposit_customer c ON f.customer_key = c.customer_key
WHERE f.as_of_date = CURRENT_DATE
GROUP BY c.customer_name
ORDER BY total_deposits DESC
LIMIT 20;
      `,
    },
    {
      name: "Cost of Funds by Product",
      sql: `
SELECT 
  p.product_name,
  SUM(f.balance_amount) as avg_balance,
  SUM(i.interest_amount) as interest_expense,
  (SUM(i.interest_amount) / NULLIF(SUM(f.balance_amount), 0)) * 100 as cost_of_funds_pct
FROM gold.fact_deposit_positions f
JOIN gold.dim_deposit_product p ON f.product_key = p.product_key
LEFT JOIN gold.fact_interest_accrual i ON f.account_key = i.account_key AND f.as_of_date = i.as_of_date
WHERE f.as_of_date >= DATE_TRUNC('month', CURRENT_DATE)
GROUP BY p.product_name
ORDER BY cost_of_funds_pct DESC;
      `,
    },
    {
      name: "LCR Calculation (Simplified)",
      sql: `
WITH hqla AS (
  SELECT SUM(hqla_amount) as total_hqla
  FROM regulatory.lcr_hqla
  WHERE as_of_date = CURRENT_DATE
),
outflows AS (
  SELECT SUM(net_cash_outflow_30d) as total_outflows
  FROM regulatory.lcr_cash_flows
  WHERE as_of_date = CURRENT_DATE
)
SELECT 
  h.total_hqla,
  o.total_outflows,
  (h.total_hqla / NULLIF(o.total_outflows, 0)) * 100 as lcr_ratio
FROM hqla h, outflows o;
      `,
    },
  ],
};

// ============================================================================
// EXPORT
// ============================================================================

export const depositsComprehensiveDomain = {
  domainName: "Deposits & Funding",
  domainId: "deposits",
  description: "Core deposit products and funding management",
  bronzeLayer: depositsBronzeLayer,
  silverLayer: depositsSilverLayer,
  goldLayer: depositsGoldLayer,
  metricsCatalog: depositsMetricsCatalog,
  workflows: depositsWorkflows,
  regulatoryFramework: depositsRegulatoryFramework,
  dataQualityRules: depositsDataQualityRules,
  rlsPolicies: depositsRLSPolicies,
  queryCookbook: depositsQueryCookbook,
  completionStatus: "100%",
  productionReady: true,
};
