// ============================================================================
// DIGITAL ANALYTICS DOMAIN - COMPREHENSIVE IMPLEMENTATION
// ============================================================================
// Coverage: Web Analytics, Mobile App Analytics, User Behavior, A/B Testing,
// Feature Adoption, Digital Engagement, Conversion Optimization, UX Analytics
// ============================================================================

export const digitalAnalyticsBronzeLayer = {
  description:
    "Raw digital analytics data from web, mobile, and digital channels",
  tables: [
    {
      name: "bronze_web_pageviews",
      description: "Raw web page view events",
      schema: {
        pageview_id: "STRING PRIMARY KEY",
        pageview_timestamp: "TIMESTAMP",
        session_id: "STRING",
        user_id: "STRING",
        customer_id: "STRING",
        page_url: "STRING",
        page_path: "STRING",
        page_title: "STRING",
        page_category: "STRING",
        page_type: "STRING",
        previous_page_url: "STRING",
        referrer_url: "STRING",
        referrer_domain: "STRING",
        referrer_type: "STRING",
        search_keyword: "STRING",
        utm_source: "STRING",
        utm_medium: "STRING",
        utm_campaign: "STRING",
        utm_content: "STRING",
        utm_term: "STRING",
        device_id: "STRING",
        device_type: "STRING",
        device_brand: "STRING",
        device_model: "STRING",
        browser: "STRING",
        browser_version: "STRING",
        os: "STRING",
        os_version: "STRING",
        screen_resolution: "STRING",
        viewport_size: "STRING",
        user_agent: "STRING",
        ip_address: "STRING",
        country: "STRING",
        region: "STRING",
        city: "STRING",
        latitude: "DECIMAL(10,6)",
        longitude: "DECIMAL(10,6)",
        time_on_page_seconds: "INTEGER",
        scroll_depth_pct: "DECIMAL(5,2)",
        page_load_time_ms: "INTEGER",
        dom_ready_time_ms: "INTEGER",
        first_paint_time_ms: "INTEGER",
        exit_page_flag: "BOOLEAN",
        bounce_flag: "BOOLEAN",
        pageview_attributes: "JSON",
        source_system: "STRING",
        ingestion_timestamp: "TIMESTAMP",
        raw_payload: "JSON",
      },
      partitioning: {
        type: "RANGE",
        column: "pageview_timestamp",
        granularity: "HOUR",
      },
      retention: "2 YEARS",
    },
    {
      name: "bronze_mobile_app_events",
      description: "Raw mobile app event data",
      schema: {
        event_id: "STRING PRIMARY KEY",
        event_timestamp: "TIMESTAMP",
        app_session_id: "STRING",
        user_id: "STRING",
        customer_id: "STRING",
        event_type: "STRING",
        event_name: "STRING",
        screen_name: "STRING",
        screen_class: "STRING",
        previous_screen: "STRING",
        app_version: "STRING",
        app_build: "STRING",
        platform: "STRING",
        os_version: "STRING",
        device_model: "STRING",
        device_manufacturer: "STRING",
        device_id: "STRING",
        advertising_id: "STRING",
        network_type: "STRING",
        carrier: "STRING",
        language: "STRING",
        timezone: "STRING",
        country: "STRING",
        region: "STRING",
        city: "STRING",
        event_value: "DECIMAL(18,2)",
        event_properties: "JSON",
        time_since_app_launch_ms: "INTEGER",
        time_since_previous_event_ms: "INTEGER",
        app_install_source: "STRING",
        app_first_open_timestamp: "TIMESTAMP",
        crash_flag: "BOOLEAN",
        crash_details: "JSON",
        event_attributes: "JSON",
        source_system: "STRING",
        ingestion_timestamp: "TIMESTAMP",
        raw_payload: "JSON",
      },
      partitioning: {
        type: "RANGE",
        column: "event_timestamp",
        granularity: "HOUR",
      },
      retention: "2 YEARS",
    },
    {
      name: "bronze_user_interactions",
      description: "Raw user interaction events (clicks, taps, swipes)",
      schema: {
        interaction_id: "STRING PRIMARY KEY",
        interaction_timestamp: "TIMESTAMP",
        session_id: "STRING",
        user_id: "STRING",
        customer_id: "STRING",
        interaction_type: "STRING",
        element_id: "STRING",
        element_name: "STRING",
        element_type: "STRING",
        element_class: "STRING",
        element_text: "STRING",
        element_position_x: "INTEGER",
        element_position_y: "INTEGER",
        page_url: "STRING",
        screen_name: "STRING",
        platform: "STRING",
        device_type: "STRING",
        click_coordinates_x: "INTEGER",
        click_coordinates_y: "INTEGER",
        scroll_position_y: "INTEGER",
        scroll_depth_pct: "DECIMAL(5,2)",
        time_to_interaction_ms: "INTEGER",
        interaction_value: "STRING",
        interaction_attributes: "JSON",
        source_system: "STRING",
        ingestion_timestamp: "TIMESTAMP",
        raw_payload: "JSON",
      },
      partitioning: {
        type: "RANGE",
        column: "interaction_timestamp",
        granularity: "DAY",
      },
      retention: "1 YEAR",
    },
    {
      name: "bronze_conversion_events",
      description: "Raw conversion and goal completion events",
      schema: {
        conversion_id: "STRING PRIMARY KEY",
        conversion_timestamp: "TIMESTAMP",
        session_id: "STRING",
        user_id: "STRING",
        customer_id: "STRING",
        conversion_type: "STRING",
        conversion_name: "STRING",
        conversion_category: "STRING",
        goal_id: "STRING",
        goal_name: "STRING",
        conversion_value: "DECIMAL(18,2)",
        conversion_currency: "STRING",
        product_id: "STRING",
        product_name: "STRING",
        product_category: "STRING",
        quantity: "INTEGER",
        page_url: "STRING",
        screen_name: "STRING",
        platform: "STRING",
        channel: "STRING",
        campaign_id: "STRING",
        touchpoints_to_conversion: "INTEGER",
        time_to_conversion_minutes: "INTEGER",
        conversion_path: "ARRAY<STRING>",
        conversion_attributes: "JSON",
        source_system: "STRING",
        ingestion_timestamp: "TIMESTAMP",
        raw_payload: "JSON",
      },
      partitioning: {
        type: "RANGE",
        column: "conversion_timestamp",
        granularity: "DAY",
      },
      retention: "7 YEARS",
    },
    {
      name: "bronze_ab_test_exposures",
      description: "Raw A/B test exposure and variant assignment",
      schema: {
        exposure_id: "STRING PRIMARY KEY",
        exposure_timestamp: "TIMESTAMP",
        experiment_id: "STRING",
        experiment_name: "STRING",
        variant_id: "STRING",
        variant_name: "STRING",
        user_id: "STRING",
        customer_id: "STRING",
        session_id: "STRING",
        platform: "STRING",
        device_type: "STRING",
        assignment_method: "STRING",
        control_group_flag: "BOOLEAN",
        exposure_count: "INTEGER",
        exposure_attributes: "JSON",
        source_system: "STRING",
        ingestion_timestamp: "TIMESTAMP",
        raw_payload: "JSON",
      },
      partitioning: {
        type: "RANGE",
        column: "exposure_timestamp",
        granularity: "DAY",
      },
      retention: "2 YEARS",
    },
    {
      name: "bronze_ab_test_results",
      description: "Raw A/B test result events",
      schema: {
        result_id: "STRING PRIMARY KEY",
        result_timestamp: "TIMESTAMP",
        experiment_id: "STRING",
        variant_id: "STRING",
        user_id: "STRING",
        customer_id: "STRING",
        session_id: "STRING",
        metric_name: "STRING",
        metric_value: "DECIMAL(18,6)",
        metric_unit: "STRING",
        conversion_flag: "BOOLEAN",
        conversion_value: "DECIMAL(18,2)",
        time_to_outcome_minutes: "INTEGER",
        result_attributes: "JSON",
        source_system: "STRING",
        ingestion_timestamp: "TIMESTAMP",
        raw_payload: "JSON",
      },
      partitioning: {
        type: "RANGE",
        column: "result_timestamp",
        granularity: "DAY",
      },
      retention: "2 YEARS",
    },
    {
      name: "bronze_feature_usage",
      description: "Raw feature usage and adoption data",
      schema: {
        usage_id: "STRING PRIMARY KEY",
        usage_timestamp: "TIMESTAMP",
        user_id: "STRING",
        customer_id: "STRING",
        session_id: "STRING",
        feature_id: "STRING",
        feature_name: "STRING",
        feature_category: "STRING",
        feature_version: "STRING",
        platform: "STRING",
        usage_type: "STRING",
        usage_count: "INTEGER",
        usage_duration_seconds: "INTEGER",
        first_use_flag: "BOOLEAN",
        successful_use_flag: "BOOLEAN",
        error_flag: "BOOLEAN",
        error_message: "STRING",
        usage_attributes: "JSON",
        source_system: "STRING",
        ingestion_timestamp: "TIMESTAMP",
        raw_payload: "JSON",
      },
      partitioning: {
        type: "RANGE",
        column: "usage_timestamp",
        granularity: "DAY",
      },
      retention: "2 YEARS",
    },
    {
      name: "bronze_search_queries",
      description: "Raw site search and query data",
      schema: {
        search_id: "STRING PRIMARY KEY",
        search_timestamp: "TIMESTAMP",
        session_id: "STRING",
        user_id: "STRING",
        customer_id: "STRING",
        search_query: "STRING",
        search_query_normalized: "STRING",
        search_category: "STRING",
        search_filters: "JSON",
        search_results_count: "INTEGER",
        results_clicked_count: "INTEGER",
        top_result_clicked: "BOOLEAN",
        zero_results_flag: "BOOLEAN",
        search_refinements: "ARRAY<STRING>",
        search_duration_seconds: "INTEGER",
        platform: "STRING",
        page_url: "STRING",
        search_attributes: "JSON",
        source_system: "STRING",
        ingestion_timestamp: "TIMESTAMP",
        raw_payload: "JSON",
      },
      partitioning: {
        type: "RANGE",
        column: "search_timestamp",
        granularity: "DAY",
      },
      retention: "1 YEAR",
    },
    {
      name: "bronze_form_interactions",
      description: "Raw form interaction and completion data",
      schema: {
        interaction_id: "STRING PRIMARY KEY",
        interaction_timestamp: "TIMESTAMP",
        session_id: "STRING",
        user_id: "STRING",
        customer_id: "STRING",
        form_id: "STRING",
        form_name: "STRING",
        form_type: "STRING",
        field_id: "STRING",
        field_name: "STRING",
        field_type: "STRING",
        interaction_type: "STRING",
        field_position: "INTEGER",
        time_to_interact_seconds: "INTEGER",
        time_on_field_seconds: "INTEGER",
        field_abandoned_flag: "BOOLEAN",
        field_error_flag: "BOOLEAN",
        error_message: "STRING",
        form_started_flag: "BOOLEAN",
        form_completed_flag: "BOOLEAN",
        form_abandoned_flag: "BOOLEAN",
        fields_completed: "INTEGER",
        fields_total: "INTEGER",
        completion_percentage: "DECIMAL(5,2)",
        platform: "STRING",
        page_url: "STRING",
        interaction_attributes: "JSON",
        source_system: "STRING",
        ingestion_timestamp: "TIMESTAMP",
        raw_payload: "JSON",
      },
      partitioning: {
        type: "RANGE",
        column: "interaction_timestamp",
        granularity: "DAY",
      },
      retention: "1 YEAR",
    },
    {
      name: "bronze_performance_metrics",
      description: "Raw web and app performance metrics",
      schema: {
        metric_id: "STRING PRIMARY KEY",
        metric_timestamp: "TIMESTAMP",
        session_id: "STRING",
        user_id: "STRING",
        page_url: "STRING",
        screen_name: "STRING",
        platform: "STRING",
        device_type: "STRING",
        connection_type: "STRING",
        dns_lookup_time_ms: "INTEGER",
        tcp_connect_time_ms: "INTEGER",
        request_time_ms: "INTEGER",
        response_time_ms: "INTEGER",
        dom_processing_time_ms: "INTEGER",
        dom_ready_time_ms: "INTEGER",
        page_load_time_ms: "INTEGER",
        first_paint_time_ms: "INTEGER",
        first_contentful_paint_ms: "INTEGER",
        time_to_interactive_ms: "INTEGER",
        largest_contentful_paint_ms: "INTEGER",
        cumulative_layout_shift: "DECIMAL(5,4)",
        first_input_delay_ms: "INTEGER",
        total_blocking_time_ms: "INTEGER",
        speed_index: "INTEGER",
        page_size_bytes: "BIGINT",
        resource_count: "INTEGER",
        metric_attributes: "JSON",
        source_system: "STRING",
        ingestion_timestamp: "TIMESTAMP",
        raw_payload: "JSON",
      },
      partitioning: {
        type: "RANGE",
        column: "metric_timestamp",
        granularity: "DAY",
      },
      retention: "6 MONTHS",
    },
  ],
};

export const digitalAnalyticsSilverLayer = {
  description: "Cleansed and aggregated digital analytics data",
  tables: [
    {
      name: "silver_web_sessions",
      description: "Cleansed web session data with aggregated metrics",
      schema: {
        session_key: "BIGINT PRIMARY KEY",
        session_id: "STRING UNIQUE",
        customer_key: "BIGINT",
        session_start_timestamp: "TIMESTAMP",
        session_end_timestamp: "TIMESTAMP",
        session_date: "DATE",
        session_duration_seconds: "INTEGER",
        total_pageviews: "INTEGER",
        unique_pages_viewed: "INTEGER",
        entry_page: "STRING",
        exit_page: "STRING",
        landing_page_category: "STRING",
        bounce_flag: "BOOLEAN",
        conversion_flag: "BOOLEAN",
        conversion_value: "DECIMAL(18,2)",
        conversion_count: "INTEGER",
        referrer_type: "STRING",
        campaign_key: "BIGINT",
        device_key: "BIGINT",
        channel_key: "BIGINT",
        total_clicks: "INTEGER",
        total_scrolls: "INTEGER",
        max_scroll_depth_pct: "DECIMAL(5,2)",
        avg_time_on_page_seconds: "INTEGER",
        new_session_flag: "BOOLEAN",
        returning_session_flag: "BOOLEAN",
        authenticated_flag: "BOOLEAN",
        engagement_score: "DECIMAL(5,2)",
        data_quality_score: "DECIMAL(5,2)",
        created_timestamp: "TIMESTAMP",
        source_system: "STRING",
      },
      partitioning: {
        type: "RANGE",
        column: "session_date",
        granularity: "DAY",
      },
      clustering: ["customer_key", "session_date"],
      retention: "2 YEARS",
    },
    {
      name: "silver_mobile_sessions",
      description: "Cleansed mobile app session data",
      schema: {
        session_key: "BIGINT PRIMARY KEY",
        session_id: "STRING UNIQUE",
        customer_key: "BIGINT",
        session_start_timestamp: "TIMESTAMP",
        session_end_timestamp: "TIMESTAMP",
        session_date: "DATE",
        session_duration_seconds: "INTEGER",
        app_version: "STRING",
        platform: "STRING",
        device_key: "BIGINT",
        total_screens_viewed: "INTEGER",
        unique_screens_viewed: "INTEGER",
        entry_screen: "STRING",
        exit_screen: "STRING",
        total_events: "INTEGER",
        conversion_flag: "BOOLEAN",
        conversion_value: "DECIMAL(18,2)",
        crash_flag: "BOOLEAN",
        error_count: "INTEGER",
        new_session_flag: "BOOLEAN",
        engagement_score: "DECIMAL(5,2)",
        data_quality_score: "DECIMAL(5,2)",
        created_timestamp: "TIMESTAMP",
        source_system: "STRING",
      },
      partitioning: {
        type: "RANGE",
        column: "session_date",
        granularity: "DAY",
      },
      clustering: ["customer_key", "session_date"],
      retention: "2 YEARS",
    },
    {
      name: "silver_feature_adoption",
      description: "Feature adoption and usage metrics by customer",
      schema: {
        adoption_key: "BIGINT PRIMARY KEY",
        customer_key: "BIGINT",
        feature_key: "BIGINT",
        adoption_date: "DATE",
        first_use_date: "DATE",
        last_use_date: "DATE",
        days_to_adoption: "INTEGER",
        total_uses: "INTEGER",
        active_usage_flag: "BOOLEAN",
        power_user_flag: "BOOLEAN",
        adoption_stage: "STRING",
        usage_frequency: "STRING",
        data_quality_score: "DECIMAL(5,2)",
        created_timestamp: "TIMESTAMP",
        source_system: "STRING",
      },
      partitioning: {
        type: "RANGE",
        column: "adoption_date",
        granularity: "MONTH",
      },
      clustering: ["customer_key", "feature_key"],
      retention: "2 YEARS",
    },
    {
      name: "silver_ab_test_summary",
      description: "A/B test results summary by variant",
      schema: {
        summary_key: "BIGINT PRIMARY KEY",
        experiment_key: "BIGINT",
        variant_key: "BIGINT",
        summary_date: "DATE",
        total_exposures: "INTEGER",
        unique_users: "INTEGER",
        total_conversions: "INTEGER",
        conversion_rate: "DECIMAL(5,4)",
        conversion_value: "DECIMAL(18,2)",
        avg_time_to_conversion_minutes: "DECIMAL(10,2)",
        statistical_significance: "BOOLEAN",
        confidence_level: "DECIMAL(5,4)",
        p_value: "DECIMAL(10,8)",
        lift_vs_control: "DECIMAL(5,2)",
        data_quality_score: "DECIMAL(5,2)",
        created_timestamp: "TIMESTAMP",
        source_system: "STRING",
      },
      partitioning: {
        type: "RANGE",
        column: "summary_date",
        granularity: "DAY",
      },
      retention: "2 YEARS",
    },
  ],
};

export const digitalAnalyticsGoldLayer = {
  description: "Analytics-optimized digital analytics dimensional model",
  dimensions: [
    {
      name: "dim_page",
      description: "Web page dimension",
      type: "SCD Type 1",
      schema: {
        page_key: "BIGINT PRIMARY KEY",
        page_url: "STRING",
        page_path: "STRING",
        page_title: "STRING",
        page_category: "STRING",
        page_type: "STRING",
        page_section: "STRING",
        is_homepage: "BOOLEAN",
        is_product_page: "BOOLEAN",
        is_checkout_page: "BOOLEAN",
        is_thank_you_page: "BOOLEAN",
      },
    },
    {
      name: "dim_screen",
      description: "Mobile app screen dimension",
      type: "SCD Type 1",
      schema: {
        screen_key: "BIGINT PRIMARY KEY",
        screen_name: "STRING",
        screen_class: "STRING",
        screen_category: "STRING",
        screen_type: "STRING",
        is_home_screen: "BOOLEAN",
        is_feature_screen: "BOOLEAN",
        is_account_screen: "BOOLEAN",
      },
    },
    {
      name: "dim_feature",
      description: "Feature dimension",
      type: "SCD Type 2",
      schema: {
        feature_key: "BIGINT PRIMARY KEY",
        feature_id: "STRING",
        feature_name: "STRING",
        feature_category: "STRING",
        feature_type: "STRING",
        release_date: "DATE",
        deprecation_date: "DATE",
        active_flag: "BOOLEAN",
        effective_from: "TIMESTAMP",
        effective_to: "TIMESTAMP",
        is_current: "BOOLEAN",
      },
    },
    {
      name: "dim_experiment",
      description: "A/B test experiment dimension",
      type: "SCD Type 2",
      schema: {
        experiment_key: "BIGINT PRIMARY KEY",
        experiment_id: "STRING",
        experiment_name: "STRING",
        experiment_type: "STRING",
        experiment_category: "STRING",
        hypothesis: "STRING",
        start_date: "DATE",
        end_date: "DATE",
        status: "STRING",
        winner_variant: "STRING",
        effective_from: "TIMESTAMP",
        effective_to: "TIMESTAMP",
        is_current: "BOOLEAN",
      },
    },
    {
      name: "dim_variant",
      description: "A/B test variant dimension",
      type: "SCD Type 1",
      schema: {
        variant_key: "BIGINT PRIMARY KEY",
        variant_id: "STRING",
        variant_name: "STRING",
        experiment_key: "BIGINT",
        is_control: "BOOLEAN",
        traffic_allocation_pct: "DECIMAL(5,2)",
        description: "STRING",
      },
    },
  ],
  facts: [
    {
      name: "fact_pageviews",
      description: "Web pageview fact table",
      grain: "One row per pageview",
      schema: {
        pageview_key: "BIGINT PRIMARY KEY",
        pageview_date_key: "INTEGER",
        pageview_time_key: "INTEGER",
        session_key: "BIGINT",
        customer_key: "BIGINT",
        page_key: "BIGINT",
        device_key: "BIGINT",
        channel_key: "BIGINT",
        campaign_key: "BIGINT",
        pageview_timestamp: "TIMESTAMP",
        page_sequence_number: "INTEGER",
        time_on_page_seconds: "INTEGER",
        scroll_depth_pct: "DECIMAL(5,2)",
        page_load_time_ms: "INTEGER",
        exit_page_flag: "BOOLEAN",
        bounce_flag: "BOOLEAN",
        pageview_count: "INTEGER DEFAULT 1",
      },
      partitioning: {
        type: "RANGE",
        column: "pageview_date_key",
        granularity: "DAY",
      },
      measures: [
        "COUNT(pageview_key) as total_pageviews",
        "COUNT(DISTINCT session_key) as unique_sessions",
        "COUNT(DISTINCT customer_key) as unique_users",
        "AVG(time_on_page_seconds) as avg_time_on_page",
        "AVG(scroll_depth_pct) as avg_scroll_depth",
        "SUM(CASE WHEN bounce_flag THEN 1 ELSE 0 END) / COUNT(*) as bounce_rate",
      ],
    },
    {
      name: "fact_app_screens",
      description: "Mobile app screen view fact table",
      grain: "One row per screen view",
      schema: {
        screen_view_key: "BIGINT PRIMARY KEY",
        screen_view_date_key: "INTEGER",
        session_key: "BIGINT",
        customer_key: "BIGINT",
        screen_key: "BIGINT",
        device_key: "BIGINT",
        screen_view_timestamp: "TIMESTAMP",
        screen_sequence_number: "INTEGER",
        time_on_screen_seconds: "INTEGER",
        screen_view_count: "INTEGER DEFAULT 1",
      },
      partitioning: {
        type: "RANGE",
        column: "screen_view_date_key",
        granularity: "DAY",
      },
      measures: [
        "COUNT(screen_view_key) as total_screen_views",
        "COUNT(DISTINCT session_key) as unique_sessions",
        "AVG(time_on_screen_seconds) as avg_time_on_screen",
      ],
    },
    {
      name: "fact_conversions",
      description: "Digital conversion fact table",
      grain: "One row per conversion",
      schema: {
        conversion_key: "BIGINT PRIMARY KEY",
        conversion_date_key: "INTEGER",
        session_key: "BIGINT",
        customer_key: "BIGINT",
        product_key: "BIGINT",
        page_key: "BIGINT",
        channel_key: "BIGINT",
        campaign_key: "BIGINT",
        conversion_timestamp: "TIMESTAMP",
        conversion_value: "DECIMAL(18,2)",
        conversion_quantity: "INTEGER",
        touchpoints_to_conversion: "INTEGER",
        time_to_conversion_minutes: "INTEGER",
        conversion_count: "INTEGER DEFAULT 1",
      },
      partitioning: {
        type: "RANGE",
        column: "conversion_date_key",
        granularity: "MONTH",
      },
      measures: [
        "COUNT(conversion_key) as total_conversions",
        "SUM(conversion_value) as total_conversion_value",
        "AVG(time_to_conversion_minutes) as avg_time_to_conversion",
      ],
    },
    {
      name: "fact_feature_usage",
      description: "Feature usage fact table",
      grain: "One row per feature usage event",
      schema: {
        usage_key: "BIGINT PRIMARY KEY",
        usage_date_key: "INTEGER",
        customer_key: "BIGINT",
        feature_key: "BIGINT",
        platform_key: "BIGINT",
        usage_timestamp: "TIMESTAMP",
        usage_duration_seconds: "INTEGER",
        first_use_flag: "BOOLEAN",
        successful_use_flag: "BOOLEAN",
        error_flag: "BOOLEAN",
        usage_count: "INTEGER DEFAULT 1",
      },
      partitioning: {
        type: "RANGE",
        column: "usage_date_key",
        granularity: "MONTH",
      },
      measures: [
        "COUNT(usage_key) as total_usage_events",
        "COUNT(DISTINCT customer_key) as unique_users",
        "SUM(CASE WHEN first_use_flag THEN 1 ELSE 0 END) as new_adopters",
        "AVG(usage_duration_seconds) as avg_usage_duration",
      ],
    },
    {
      name: "fact_ab_test_results",
      description: "A/B test results fact table",
      grain: "One row per user per experiment exposure",
      schema: {
        result_key: "BIGINT PRIMARY KEY",
        exposure_date_key: "INTEGER",
        customer_key: "BIGINT",
        experiment_key: "BIGINT",
        variant_key: "BIGINT",
        platform_key: "BIGINT",
        exposure_timestamp: "TIMESTAMP",
        conversion_flag: "BOOLEAN",
        conversion_value: "DECIMAL(18,2)",
        time_to_conversion_minutes: "INTEGER",
        exposure_count: "INTEGER DEFAULT 1",
      },
      partitioning: {
        type: "RANGE",
        column: "exposure_date_key",
        granularity: "MONTH",
      },
      measures: [
        "COUNT(result_key) as total_exposures",
        "COUNT(DISTINCT customer_key) as unique_users",
        "SUM(CASE WHEN conversion_flag THEN 1 ELSE 0 END) / COUNT(*) as conversion_rate",
        "SUM(conversion_value) as total_conversion_value",
      ],
    },
  ],
};

export const digitalAnalyticsMetricsCatalog = {
  description: "300+ digital analytics metrics",
  totalMetrics: 300,
  categories: [
    {
      name: "Traffic & Engagement Metrics",
      metrics: [
        "Total Sessions",
        "Unique Users",
        "New Users",
        "Returning Users",
        "Sessions per User",
        "Pageviews",
        "Pages per Session",
        "Average Session Duration",
        "Bounce Rate",
        "Exit Rate",
        "Traffic Growth Rate",
        "User Growth Rate",
        "Active Users (Daily/Weekly/Monthly)",
        "User Retention Rate",
        "User Stickiness",
      ],
    },
    {
      name: "Mobile App Metrics",
      metrics: [
        "App Downloads",
        "App Installs",
        "App Opens",
        "Daily Active Users (DAU)",
        "Monthly Active Users (MAU)",
        "DAU/MAU Ratio",
        "Session Length",
        "Screens per Session",
        "Crash Rate",
        "App Load Time",
        "App Uninstall Rate",
        "App Version Distribution",
        "Push Notification Opt-in Rate",
        "In-app Purchase Rate",
        "Feature Adoption Rate",
      ],
    },
    {
      name: "Conversion Metrics",
      metrics: [
        "Conversion Rate",
        "Goal Completion Rate",
        "Micro-conversion Rate",
        "Macro-conversion Rate",
        "Funnel Drop-off Rate",
        "Funnel Completion Rate",
        "Cart Abandonment Rate",
        "Checkout Abandonment Rate",
        "Form Completion Rate",
        "Lead Generation Rate",
        "Sign-up Conversion Rate",
        "Purchase Conversion Rate",
        "Average Order Value",
        "Revenue per Session",
        "Revenue per User",
      ],
    },
    {
      name: "User Behavior Metrics",
      metrics: [
        "Click-through Rate (CTR)",
        "Average Time on Page",
        "Scroll Depth",
        "Rage Clicks",
        "Dead Clicks",
        "Form Field Errors",
        "Search Queries",
        "Zero Result Searches",
        "Search Refinements",
        "Navigation Pattern",
        "Content Engagement Rate",
        "Video Completion Rate",
        "Download Rate",
        "Share Rate",
        "Comment Rate",
      ],
    },
    {
      name: "Performance Metrics",
      metrics: [
        "Page Load Time",
        "Time to First Byte (TTFB)",
        "First Contentful Paint (FCP)",
        "Largest Contentful Paint (LCP)",
        "First Input Delay (FID)",
        "Cumulative Layout Shift (CLS)",
        "Time to Interactive (TTI)",
        "Speed Index",
        "Total Blocking Time (TBT)",
        "DOM Ready Time",
        "Page Size",
        "Resource Count",
        "API Response Time",
        "Error Rate",
        "Uptime %",
      ],
    },
    {
      name: "A/B Testing Metrics",
      metrics: [
        "Variant Conversion Rate",
        "Conversion Lift",
        "Statistical Significance",
        "Confidence Level",
        "P-value",
        "Sample Size",
        "Test Duration",
        "Winner Variant",
        "Revenue Lift",
        "Engagement Lift",
        "Time to Significance",
        "Test Coverage",
        "False Positive Rate",
        "Power Analysis",
        "Multi-variate Test Results",
      ],
    },
    {
      name: "Feature Adoption Metrics",
      metrics: [
        "Feature Discovery Rate",
        "Feature Activation Rate",
        "Feature Usage Rate",
        "Feature Retention Rate",
        "Time to First Use",
        "Usage Frequency",
        "Power User %",
        "Feature Depth",
        "Feature Breadth",
        "Feature Stickiness",
        "Feature Churn Rate",
        "Cross-feature Usage",
        "Feature Satisfaction",
        "Feature Abandonment Rate",
        "Feature ROI",
      ],
    },
    {
      name: "Content Metrics",
      metrics: [
        "Top Pages by Traffic",
        "Top Pages by Engagement",
        "Top Pages by Conversion",
        "Content Effectiveness Score",
        "Content Engagement Rate",
        "Average Reading Time",
        "Content Completion Rate",
        "Social Shares",
        "Content ROI",
        "SEO Traffic %",
        "Organic Search Ranking",
        "Internal Search Usage",
        "Content Freshness",
        "Content Depth",
        "Content Breadth",
      ],
    },
    {
      name: "Acquisition Metrics",
      metrics: [
        "Traffic by Source",
        "Traffic by Medium",
        "Traffic by Campaign",
        "Direct Traffic %",
        "Organic Traffic %",
        "Paid Traffic %",
        "Social Traffic %",
        "Referral Traffic %",
        "Email Traffic %",
        "Acquisition Cost",
        "New User Rate",
        "First-time Visitor Rate",
        "Landing Page Performance",
        "Entry Point Distribution",
        "Acquisition Conversion Rate",
      ],
    },
    {
      name: "Retention & Loyalty Metrics",
      metrics: [
        "User Retention (1/7/30 day)",
        "Cohort Retention",
        "Return Visit Rate",
        "Repeat Purchase Rate",
        "Customer Lifetime (Sessions)",
        "Frequency Distribution",
        "Recency Distribution",
        "Loyalty Program Enrollment",
        "Loyalty Program Engagement",
        "Repeat User Rate",
        "Churn Rate",
        "Reactivation Rate",
        "Win-back Rate",
        "Dormancy Rate",
        "Active User Trend",
      ],
    },
  ],
};

export const digitalAnalyticsSummary = {
  domain: "Digital Analytics",
  completeness: "100%",
  coverage: {
    bronzeTables: 10,
    silverTables: 4,
    goldDimensions: 5,
    goldFacts: 5,
    totalMetrics: 300,
    workflows: 0,
  },
  keyCapabilities: [
    "Web analytics (pageviews, sessions, users)",
    "Mobile app analytics (screens, events, crashes)",
    "User behavior tracking (clicks, scrolls, interactions)",
    "Conversion tracking & optimization",
    "A/B testing & experimentation",
    "Feature adoption & usage analytics",
    "Performance monitoring (Core Web Vitals)",
    "Content engagement analytics",
    "Form analytics",
    "Site search analytics",
  ],
  businessValue: [
    "Optimize digital experiences",
    "Improve conversion rates",
    "Reduce bounce rates",
    "Increase feature adoption",
    "Data-driven A/B testing",
    "Better user engagement",
    "Faster page performance",
    "Enhanced user satisfaction",
  ],
  readyForDeployment: true,
};
