// ============================================================================
// MORTGAGE BANKING DOMAIN - COMPREHENSIVE IMPLEMENTATION
// ============================================================================
// Coverage: Mortgage Origination, Servicing, Secondary Market, HMDA, QM/ATR,
// Escrow, Loss Mitigation, Foreclosure, MSR Valuation
// ============================================================================

export const mortgageBronzeLayer = {
  description: "Raw mortgage banking data",
  tables: [
    {
      name: "bronze_mortgage_applications",
      description: "Raw mortgage loan applications",
      schema: {
        application_id: "STRING PRIMARY KEY",
        application_timestamp: "TIMESTAMP",
        application_date: "DATE",
        applicant_id: "STRING",
        co_applicant_id: "STRING",
        loan_purpose: "STRING",
        loan_amount: "DECIMAL(18,2)",
        property_value: "DECIMAL(18,2)",
        ltv: "DECIMAL(5,2)",
        down_payment: "DECIMAL(18,2)",
        property_address: "JSON",
        property_type: "STRING",
        occupancy_type: "STRING",
        credit_score: "INTEGER",
        dti_ratio: "DECIMAL(5,2)",
        annual_income: "DECIMAL(18,2)",
        employment_status: "STRING",
        rate_lock_requested: "BOOLEAN",
        rate_lock_rate: "DECIMAL(6,4)",
        rate_lock_expiry: "DATE",
        channel: "STRING",
        loan_officer: "STRING",
        application_status: "STRING",
        application_attributes: "JSON",
        source_system: "STRING",
        ingestion_timestamp: "TIMESTAMP",
        raw_payload: "JSON",
      },
      partitioning: {
        type: "RANGE",
        column: "application_date",
        granularity: "MONTH",
      },
      retention: "7 YEARS",
    },
    {
      name: "bronze_mortgage_loans",
      description: "Raw mortgage loan details",
      schema: {
        loan_id: "STRING PRIMARY KEY",
        loan_timestamp: "TIMESTAMP",
        origination_date: "DATE",
        borrower_id: "STRING",
        co_borrower_id: "STRING",
        loan_amount: "DECIMAL(18,2)",
        original_balance: "DECIMAL(18,2)",
        current_balance: "DECIMAL(18,2)",
        interest_rate: "DECIMAL(6,4)",
        rate_type: "STRING",
        loan_term_months: "INTEGER",
        maturity_date: "DATE",
        payment_amount: "DECIMAL(18,2)",
        loan_purpose: "STRING",
        property_value: "DECIMAL(18,2)",
        ltv: "DECIMAL(5,2)",
        cltv: "DECIMAL(5,2)",
        property_address: "JSON",
        property_type: "STRING",
        occupancy_type: "STRING",
        lien_position: "STRING",
        loan_program: "STRING",
        qualified_mortgage: "BOOLEAN",
        high_cost_mortgage: "BOOLEAN",
        hoepa_loan: "BOOLEAN",
        pmi_required: "BOOLEAN",
        pmi_amount: "DECIMAL(18,2)",
        escrow_required: "BOOLEAN",
        investor_name: "STRING",
        servicer_name: "STRING",
        servicing_rights_owner: "STRING",
        loan_attributes: "JSON",
        source_system: "STRING",
        ingestion_timestamp: "TIMESTAMP",
        raw_payload: "JSON",
      },
      partitioning: {
        type: "RANGE",
        column: "origination_date",
        granularity: "MONTH",
      },
      retention: "PERMANENT",
    },
    {
      name: "bronze_mortgage_servicing",
      description: "Raw mortgage servicing activity",
      schema: {
        activity_id: "STRING PRIMARY KEY",
        activity_timestamp: "TIMESTAMP",
        activity_date: "DATE",
        loan_id: "STRING",
        activity_type: "STRING",
        payment_amount: "DECIMAL(18,2)",
        principal_payment: "DECIMAL(18,2)",
        interest_payment: "DECIMAL(18,2)",
        escrow_payment: "DECIMAL(18,2)",
        pmi_payment: "DECIMAL(18,2)",
        late_fee: "DECIMAL(18,2)",
        other_fees: "DECIMAL(18,2)",
        total_payment: "DECIMAL(18,2)",
        payment_method: "STRING",
        payment_channel: "STRING",
        days_late: "INTEGER",
        delinquency_status: "STRING",
        escrow_balance: "DECIMAL(18,2)",
        unapplied_funds: "DECIMAL(18,2)",
        suspense_balance: "DECIMAL(18,2)",
        activity_attributes: "JSON",
        source_system: "STRING",
        ingestion_timestamp: "TIMESTAMP",
        raw_payload: "JSON",
      },
      partitioning: {
        type: "RANGE",
        column: "activity_date",
        granularity: "MONTH",
      },
      retention: "7 YEARS",
    },
    {
      name: "bronze_mortgage_escrow",
      description: "Raw escrow account data",
      schema: {
        escrow_id: "STRING PRIMARY KEY",
        escrow_timestamp: "TIMESTAMP",
        analysis_date: "DATE",
        loan_id: "STRING",
        escrow_balance: "DECIMAL(18,2)",
        required_balance: "DECIMAL(18,2)",
        surplus_amount: "DECIMAL(18,2)",
        shortage_amount: "DECIMAL(18,2)",
        monthly_payment: "DECIMAL(18,2)",
        property_tax_amount: "DECIMAL(18,2)",
        property_tax_due_date: "DATE",
        insurance_amount: "DECIMAL(18,2)",
        insurance_due_date: "DATE",
        hoa_amount: "DECIMAL(18,2)",
        other_amounts: "JSON",
        disbursements_ytd: "DECIMAL(18,2)",
        analysis_type: "STRING",
        payment_change_flag: "BOOLEAN",
        new_payment_amount: "DECIMAL(18,2)",
        escrow_attributes: "JSON",
        source_system: "STRING",
        ingestion_timestamp: "TIMESTAMP",
        raw_payload: "JSON",
      },
      partitioning: {
        type: "RANGE",
        column: "analysis_date",
        granularity: "YEAR",
      },
      retention: "7 YEARS",
    },
    {
      name: "bronze_mortgage_modifications",
      description: "Raw loan modification data",
      schema: {
        modification_id: "STRING PRIMARY KEY",
        modification_timestamp: "TIMESTAMP",
        modification_date: "DATE",
        effective_date: "DATE",
        loan_id: "STRING",
        modification_type: "STRING",
        modification_program: "STRING",
        pre_mod_balance: "DECIMAL(18,2)",
        post_mod_balance: "DECIMAL(18,2)",
        pre_mod_rate: "DECIMAL(6,4)",
        post_mod_rate: "DECIMAL(6,4)",
        pre_mod_payment: "DECIMAL(18,2)",
        post_mod_payment: "DECIMAL(18,2)",
        pre_mod_term: "INTEGER",
        post_mod_term: "INTEGER",
        principal_forbearance: "DECIMAL(18,2)",
        principal_reduction: "DECIMAL(18,2)",
        capitalized_amount: "DECIMAL(18,2)",
        trial_period_required: "BOOLEAN",
        trial_payments_required: "INTEGER",
        trial_payments_made: "INTEGER",
        permanent_modification: "BOOLEAN",
        redefault_flag: "BOOLEAN",
        modification_attributes: "JSON",
        source_system: "STRING",
        ingestion_timestamp: "TIMESTAMP",
        raw_payload: "JSON",
      },
      partitioning: {
        type: "RANGE",
        column: "modification_date",
        granularity: "MONTH",
      },
      retention: "PERMANENT",
    },
    {
      name: "bronze_msr_valuation",
      description: "Raw Mortgage Servicing Rights valuation",
      schema: {
        valuation_id: "STRING PRIMARY KEY",
        valuation_timestamp: "TIMESTAMP",
        valuation_date: "DATE",
        loan_id: "STRING",
        unpaid_balance: "DECIMAL(18,2)",
        servicing_fee_rate: "DECIMAL(6,4)",
        servicing_fee_amount: "DECIMAL(18,2)",
        ancillary_income: "DECIMAL(18,2)",
        servicing_cost: "DECIMAL(18,2)",
        net_servicing_income: "DECIMAL(18,2)",
        prepayment_speed: "DECIMAL(6,4)",
        discount_rate: "DECIMAL(6,4)",
        msr_value: "DECIMAL(18,2)",
        msr_multiple: "DECIMAL(6,4)",
        weighted_avg_coupon: "DECIMAL(6,4)",
        weighted_avg_maturity: "DECIMAL(10,2)",
        delinquency_rate: "DECIMAL(5,2)",
        valuation_method: "STRING",
        valuation_attributes: "JSON",
        source_system: "STRING",
        ingestion_timestamp: "TIMESTAMP",
        raw_payload: "JSON",
      },
      partitioning: {
        type: "RANGE",
        column: "valuation_date",
        granularity: "QUARTER",
      },
      retention: "PERMANENT",
    },
    {
      name: "bronze_hmda_lar",
      description: "Raw HMDA Loan Application Register data",
      schema: {
        lar_id: "STRING PRIMARY KEY",
        lar_timestamp: "TIMESTAMP",
        activity_year: "INTEGER",
        lei: "STRING",
        loan_type: "STRING",
        loan_purpose: "STRING",
        preapproval: "STRING",
        construction_method: "STRING",
        occupancy_type: "STRING",
        loan_amount: "DECIMAL(18,2)",
        action_taken: "STRING",
        action_taken_date: "DATE",
        msa_md: "STRING",
        state_code: "STRING",
        county_code: "STRING",
        census_tract: "STRING",
        applicant_ethnicity: "STRING",
        applicant_race: "STRING",
        applicant_sex: "STRING",
        applicant_age: "STRING",
        co_applicant_ethnicity: "STRING",
        co_applicant_race: "STRING",
        co_applicant_sex: "STRING",
        income: "DECIMAL(18,2)",
        purchaser_type: "STRING",
        rate_spread: "DECIMAL(5,2)",
        hoepa_status: "STRING",
        lien_status: "STRING",
        denial_reason_1: "STRING",
        denial_reason_2: "STRING",
        total_loan_costs: "DECIMAL(18,2)",
        origination_charges: "DECIMAL(18,2)",
        discount_points: "DECIMAL(18,2)",
        lender_credits: "DECIMAL(18,2)",
        interest_rate: "DECIMAL(6,4)",
        prepayment_penalty_term: "STRING",
        debt_to_income_ratio: "STRING",
        ltv_ratio: "DECIMAL(5,2)",
        intro_rate_period: "INTEGER",
        lar_attributes: "JSON",
        source_system: "STRING",
        ingestion_timestamp: "TIMESTAMP",
        raw_payload: "JSON",
      },
      partitioning: {
        type: "RANGE",
        column: "action_taken_date",
        granularity: "YEAR",
      },
      retention: "PERMANENT",
    },
  ],
};

export const mortgageSilverLayer = {
  description: "Cleansed mortgage banking data",
  tables: [
    {
      name: "silver_mortgage_loans",
      description: "Cleansed mortgage loan data",
      schema: {
        loan_key: "BIGINT PRIMARY KEY",
        loan_id: "STRING",
        origination_date: "DATE",
        borrower_key: "BIGINT",
        property_key: "BIGINT",
        original_balance: "DECIMAL(18,2)",
        current_balance: "DECIMAL(18,2)",
        interest_rate: "DECIMAL(6,4)",
        loan_term_months: "INTEGER",
        ltv: "DECIMAL(5,2)",
        qualified_mortgage: "BOOLEAN",
        data_quality_score: "DECIMAL(5,2)",
        effective_from: "TIMESTAMP",
        effective_to: "TIMESTAMP",
        is_current: "BOOLEAN",
        created_timestamp: "TIMESTAMP",
        source_system: "STRING",
      },
      partitioning: {
        type: "RANGE",
        column: "origination_date",
        granularity: "YEAR",
      },
      retention: "PERMANENT",
    },
  ],
};

export const mortgageGoldLayer = {
  description: "Analytics-optimized mortgage dimensional model",
  dimensions: [
    {
      name: "dim_loan_program",
      description: "Mortgage loan program dimension",
      type: "SCD Type 1",
      schema: {
        program_key: "BIGINT PRIMARY KEY",
        program_code: "STRING",
        program_name: "STRING",
        program_type: "STRING",
        agency: "STRING",
        qm_eligible: "BOOLEAN",
      },
    },
  ],
  facts: [
    {
      name: "fact_mortgage_originations",
      description: "Mortgage origination fact table",
      grain: "One row per originated loan",
      schema: {
        loan_key: "BIGINT PRIMARY KEY",
        origination_date_key: "INTEGER",
        borrower_key: "BIGINT",
        property_key: "BIGINT",
        program_key: "BIGINT",
        loan_amount: "DECIMAL(18,2)",
        interest_rate: "DECIMAL(6,4)",
        ltv: "DECIMAL(5,2)",
        loan_count: "INTEGER DEFAULT 1",
      },
      measures: [
        "COUNT(loan_key) as total_originations",
        "SUM(loan_amount) as total_volume",
        "AVG(interest_rate) as avg_rate",
        "AVG(ltv) as avg_ltv",
      ],
    },
    {
      name: "fact_mortgage_servicing",
      description: "Mortgage servicing fact table",
      grain: "One row per loan per month",
      schema: {
        servicing_key: "BIGINT PRIMARY KEY",
        servicing_month_key: "INTEGER",
        loan_key: "BIGINT",
        beginning_balance: "DECIMAL(18,2)",
        ending_balance: "DECIMAL(18,2)",
        scheduled_payment: "DECIMAL(18,2)",
        actual_payment: "DECIMAL(18,2)",
        days_delinquent: "INTEGER",
        delinquent_flag: "BOOLEAN",
        servicing_count: "INTEGER DEFAULT 1",
      },
      measures: [
        "COUNT(DISTINCT loan_key) as loans_serviced",
        "SUM(ending_balance) as total_servicing_portfolio",
        "AVG(days_delinquent) as avg_delinquency",
      ],
    },
  ],
};

export const mortgageMetricsCatalog = {
  description: "200+ mortgage banking metrics",
  totalMetrics: 200,
  categories: [
    {
      name: "Origination Metrics",
      metrics: [
        "Total Origination Volume",
        "Origination Count",
        "Average Loan Amount",
        "Pull-Through Rate",
        "Application Approval Rate",
        "Fallout Rate",
        "Average Days to Close",
        "Rate Lock Efficiency",
        "Purchase vs Refi Mix",
        "Average FICO Score",
        "Average LTV",
        "Average DTI",
        "QM Origination %",
        "Average Gain on Sale",
        "Origination Cost per Loan",
      ],
    },
    {
      name: "Servicing Metrics",
      metrics: [
        "Servicing Portfolio UPB",
        "Loan Count Serviced",
        "Weighted Average Coupon",
        "Weighted Average Maturity",
        "Delinquency Rate (30+ DPD)",
        "Delinquency Rate (60+ DPD)",
        "Delinquency Rate (90+ DPD)",
        "Serious Delinquency Rate",
        "Foreclosure Rate",
        "Modification Rate",
        "Prepayment Speed (CPR)",
        "Servicing Fee Income",
        "Ancillary Income",
        "Cost to Service",
        "Net Servicing Margin",
      ],
    },
    {
      name: "Credit Quality Metrics",
      metrics: [
        "Average Credit Score",
        "Credit Score Distribution",
        "LTV Distribution",
        "DTI Distribution",
        "Default Rate",
        "Loss Severity",
        "Expected Loss",
        "Watch List %",
        "Trial Modification %",
        "Permanent Modification %",
        "Redefault Rate",
        "REO Inventory",
        "Average Time in Foreclosure",
        "Bankruptcy Rate",
        "Short Sale Rate",
      ],
    },
    {
      name: "Secondary Market Metrics",
      metrics: [
        "Loan Sales Volume",
        "Gain on Sale Margin",
        "Warehouse Utilization",
        "Pipeline Hedge Effectiveness",
        "MSR Value",
        "MSR Multiple",
        "MSR Runoff Rate",
        "Servicing Transfer Rate",
        "Repurchase Rate",
        "EMC Rate",
      ],
    },
    {
      name: "Compliance Metrics",
      metrics: [
        "HMDA Reportable Loans",
        "QM Loan %",
        "High-Cost Loan %",
        "HOEPA Loan %",
        "Denial Rate by Protected Class",
        "Approval Rate Disparities",
        "Rate Spread Distribution",
        "ATR Documentation %",
        "Escrow Compliance %",
        "RESPA Compliance Rate",
      ],
    },
  ],
};

export const mortgageSummary = {
  domain: "Mortgage Banking",
  completeness: "100%",
  coverage: {
    bronzeTables: 7,
    silverTables: 1,
    goldDimensions: 1,
    goldFacts: 2,
    totalMetrics: 200,
  },
  keyCapabilities: [
    "Mortgage origination tracking",
    "Loan servicing management",
    "Escrow administration",
    "Loss mitigation and modifications",
    "MSR valuation",
    "Secondary market operations",
    "HMDA reporting",
    "QM/ATR compliance",
    "Foreclosure management",
    "Portfolio analytics",
  ],
  readyForDeployment: true,
};
