// Silver Layer Table Catalog
// Comprehensive list of all Silver layer tables with column definitions

export type SilverTableColumn = {
  table_name: string;
  column_name: string;
  data_type: string;
  description: string;
  source_bronze_table?: string;
  source_bronze_column?: string;
  transformation_logic?: string;
};

export const silverTablesCatalog: SilverTableColumn[] = [
  // customer_golden_scd2
  {
    table_name: "silver.customer_golden_scd2",
    column_name: "customer_ger_key",
    data_type: "STRING",
    description: "Global Entity Resolution key - stable customer identifier across systems",
    source_bronze_table: "bronze.customer_raw",
    source_bronze_column: "customer_id",
    transformation_logic: "Entity resolution algorithm to merge customer records from multiple sources",
  },
  {
    table_name: "silver.customer_golden_scd2",
    column_name: "source_customer_id",
    data_type: "STRING",
    description: "Original customer ID from source system",
    source_bronze_table: "bronze.customer_raw",
    source_bronze_column: "customer_id",
    transformation_logic: "Direct mapping",
  },
  {
    table_name: "silver.customer_golden_scd2",
    column_name: "full_name",
    data_type: "STRING",
    description: "Customer full name (standardized)",
    source_bronze_table: "bronze.customer_raw",
    source_bronze_column: "first_name, last_name",
    transformation_logic: "CONCAT(TRIM(first_name), ' ', TRIM(last_name))",
  },
  {
    table_name: "silver.customer_golden_scd2",
    column_name: "birth_date",
    data_type: "DATE",
    description: "Customer date of birth",
    source_bronze_table: "bronze.customer_raw",
    source_bronze_column: "birth_date",
    transformation_logic: "Date standardization to YYYY-MM-DD",
  },
  {
    table_name: "silver.customer_golden_scd2",
    column_name: "email",
    data_type: "STRING",
    description: "Customer email address (lowercase, validated)",
    source_bronze_table: "bronze.customer_raw",
    source_bronze_column: "email",
    transformation_logic: "LOWER(email), validate email format",
  },
  {
    table_name: "silver.customer_golden_scd2",
    column_name: "phone",
    data_type: "STRING",
    description: "Customer phone number (E.164 format)",
    source_bronze_table: "bronze.customer_raw",
    source_bronze_column: "phone",
    transformation_logic: "E.164 normalization (+country code)",
  },
  {
    table_name: "silver.customer_golden_scd2",
    column_name: "address_line1",
    data_type: "STRING",
    description: "Primary address line (standardized)",
    source_bronze_table: "bronze.customer_raw",
    source_bronze_column: "address_line1",
    transformation_logic: "Address standardization (casing, abbreviations)",
  },
  {
    table_name: "silver.customer_golden_scd2",
    column_name: "city",
    data_type: "STRING",
    description: "City name",
    source_bronze_table: "bronze.customer_raw",
    source_bronze_column: "city",
    transformation_logic: "Standardized casing",
  },
  {
    table_name: "silver.customer_golden_scd2",
    column_name: "state",
    data_type: "STRING",
    description: "State/province code",
    source_bronze_table: "bronze.customer_raw",
    source_bronze_column: "state",
    transformation_logic: "2-letter state code standardization",
  },
  {
    table_name: "silver.customer_golden_scd2",
    column_name: "postal_code",
    data_type: "STRING",
    description: "Postal/ZIP code",
    source_bronze_table: "bronze.customer_raw",
    source_bronze_column: "postal_code",
    transformation_logic: "Format validation",
  },
  {
    table_name: "silver.customer_golden_scd2",
    column_name: "country",
    data_type: "STRING",
    description: "ISO country code",
    source_bronze_table: "bronze.customer_raw",
    source_bronze_column: "country",
    transformation_logic: "ISO 3166-1 alpha-2 country code",
  },
  {
    table_name: "silver.customer_golden_scd2",
    column_name: "kyc_status",
    data_type: "STRING",
    description: "KYC verification status",
    source_bronze_table: "bronze.customer_raw",
    source_bronze_column: "kyc_status",
    transformation_logic: "Mapped to {PENDING, VERIFIED, FAILED}",
  },
  {
    table_name: "silver.customer_golden_scd2",
    column_name: "effective_start_ts",
    data_type: "TIMESTAMP",
    description: "SCD2 effective start timestamp",
    source_bronze_table: "system",
    source_bronze_column: "N/A",
    transformation_logic: "System clock at record creation/update",
  },
  {
    table_name: "silver.customer_golden_scd2",
    column_name: "effective_end_ts",
    data_type: "TIMESTAMP",
    description: "SCD2 effective end timestamp (NULL = current)",
    source_bronze_table: "system",
    source_bronze_column: "N/A",
    transformation_logic: "Updated when record superseded",
  },
  {
    table_name: "silver.customer_golden_scd2",
    column_name: "is_current",
    data_type: "TINYINT",
    description: "Current record flag (1=current, 0=historical)",
    source_bronze_table: "system",
    source_bronze_column: "N/A",
    transformation_logic: "1 for active record, 0 for superseded",
  },

  // account_positions
  {
    table_name: "silver.account_positions",
    column_name: "account_id",
    data_type: "STRING",
    description: "Unique account identifier",
    source_bronze_table: "bronze.account_balances",
    source_bronze_column: "account_id",
    transformation_logic: "Direct mapping",
  },
  {
    table_name: "silver.account_positions",
    column_name: "customer_ger_key",
    data_type: "STRING",
    description: "Customer GER key (foreign key)",
    source_bronze_table: "bronze.account_balances",
    source_bronze_column: "customer_id",
    transformation_logic: "Lookup to customer_golden_scd2",
  },
  {
    table_name: "silver.account_positions",
    column_name: "as_of_date",
    data_type: "DATE",
    description: "Position snapshot date",
    source_bronze_table: "bronze.account_balances",
    source_bronze_column: "balance_date",
    transformation_logic: "Date normalization",
  },
  {
    table_name: "silver.account_positions",
    column_name: "current_balance",
    data_type: "NUMERIC(18,2)",
    description: "End-of-day account balance",
    source_bronze_table: "bronze.account_balances",
    source_bronze_column: "balance_amount",
    transformation_logic: "Validated numeric, 2 decimal places",
  },
  {
    table_name: "silver.account_positions",
    column_name: "accrued_interest",
    data_type: "NUMERIC(18,6)",
    description: "Daily accrued interest amount",
    source_bronze_table: "bronze.interest_accruals",
    source_bronze_column: "daily_interest",
    transformation_logic: "Calculated based on rate and balance",
  },
  {
    table_name: "silver.account_positions",
    column_name: "product_type",
    data_type: "STRING",
    description: "Account product type",
    source_bronze_table: "bronze.account_master",
    source_bronze_column: "product_code",
    transformation_logic: "Standardized product mapping",
  },

  // loan_originations
  {
    table_name: "silver.loan_originations",
    column_name: "loan_id",
    data_type: "STRING",
    description: "Unique loan identifier",
    source_bronze_table: "bronze.loan_applications",
    source_bronze_column: "application_id",
    transformation_logic: "Generated upon approval",
  },
  {
    table_name: "silver.loan_originations",
    column_name: "customer_ger_key",
    data_type: "STRING",
    description: "Borrower GER key",
    source_bronze_table: "bronze.loan_applications",
    source_bronze_column: "customer_id",
    transformation_logic: "Lookup to customer_golden_scd2",
  },
  {
    table_name: "silver.loan_originations",
    column_name: "origination_date",
    data_type: "DATE",
    description: "Loan origination/disbursement date",
    source_bronze_table: "bronze.loan_applications",
    source_bronze_column: "approval_date",
    transformation_logic: "Date standardization",
  },
  {
    table_name: "silver.loan_originations",
    column_name: "original_principal",
    data_type: "NUMERIC(18,2)",
    description: "Original loan principal amount",
    source_bronze_table: "bronze.loan_applications",
    source_bronze_column: "loan_amount",
    transformation_logic: "Validated numeric",
  },
  {
    table_name: "silver.loan_originations",
    column_name: "contract_rate",
    data_type: "DECIMAL(9,6)",
    description: "Contracted interest rate (annual)",
    source_bronze_table: "bronze.loan_applications",
    source_bronze_column: "interest_rate",
    transformation_logic: "Converted to decimal (e.g., 5.5% = 0.055)",
  },

  // loan_quality
  {
    table_name: "silver.loan_quality",
    column_name: "loan_id",
    data_type: "STRING",
    description: "Loan identifier",
    source_bronze_table: "bronze.loan_delinquency",
    source_bronze_column: "loan_id",
    transformation_logic: "Direct mapping",
  },
  {
    table_name: "silver.loan_quality",
    column_name: "as_of_date",
    data_type: "DATE",
    description: "Quality assessment date",
    source_bronze_table: "bronze.loan_delinquency",
    source_bronze_column: "report_date",
    transformation_logic: "Date normalization",
  },
  {
    table_name: "silver.loan_quality",
    column_name: "days_past_due",
    data_type: "INT",
    description: "Days past due (0 = current)",
    source_bronze_table: "bronze.loan_delinquency",
    source_bronze_column: "dpd",
    transformation_logic: "Calculated from last payment date",
  },
  {
    table_name: "silver.loan_quality",
    column_name: "outstanding_balance",
    data_type: "NUMERIC(18,2)",
    description: "Current outstanding principal",
    source_bronze_table: "bronze.loan_balances",
    source_bronze_column: "balance",
    transformation_logic: "Principal balance calculation",
  },
  {
    table_name: "silver.loan_quality",
    column_name: "chargeoff_amount",
    data_type: "NUMERIC(18,2)",
    description: "Charge-off amount (if applicable)",
    source_bronze_table: "bronze.loan_writeoffs",
    source_bronze_column: "writeoff_amt",
    transformation_logic: "Writeoff amount when status = charged-off",
  },

  // risk_parameters
  {
    table_name: "silver.risk_parameters",
    column_name: "loan_id",
    data_type: "STRING",
    description: "Loan identifier",
    source_bronze_table: "bronze.risk_scores",
    source_bronze_column: "loan_id",
    transformation_logic: "Direct mapping",
  },
  {
    table_name: "silver.risk_parameters",
    column_name: "as_of_date",
    data_type: "DATE",
    description: "Risk assessment date",
    source_bronze_table: "bronze.risk_scores",
    source_bronze_column: "score_date",
    transformation_logic: "Date normalization",
  },
  {
    table_name: "silver.risk_parameters",
    column_name: "probability_of_default",
    data_type: "DECIMAL(5,4)",
    description: "PD score (0-1)",
    source_bronze_table: "bronze.risk_scores",
    source_bronze_column: "pd_score",
    transformation_logic: "Model output normalization to 0-1 range",
  },
  {
    table_name: "silver.risk_parameters",
    column_name: "lgd_estimate",
    data_type: "DECIMAL(5,4)",
    description: "Loss Given Default estimate (0-1)",
    source_bronze_table: "bronze.risk_scores",
    source_bronze_column: "lgd_score",
    transformation_logic: "Model output normalization to 0-1 range",
  },
  {
    table_name: "silver.risk_parameters",
    column_name: "exposure_amount",
    data_type: "NUMERIC(18,2)",
    description: "Exposure at Default (EAD)",
    source_bronze_table: "bronze.loan_balances",
    source_bronze_column: "balance",
    transformation_logic: "Current balance + undrawn commitments",
  },
  {
    table_name: "silver.risk_parameters",
    column_name: "provision_amount",
    data_type: "NUMERIC(18,2)",
    description: "Expected Credit Loss provision",
    source_bronze_table: "calculated",
    source_bronze_column: "N/A",
    transformation_logic: "EAD * PD * LGD",
  },

  // card_transactions
  {
    table_name: "silver.card_transactions",
    column_name: "transaction_id",
    data_type: "STRING",
    description: "Unique transaction identifier",
    source_bronze_table: "bronze.card_txn_raw",
    source_bronze_column: "txn_id",
    transformation_logic: "Direct mapping",
  },
  {
    table_name: "silver.card_transactions",
    column_name: "card_id",
    data_type: "STRING",
    description: "Card identifier (masked)",
    source_bronze_table: "bronze.card_txn_raw",
    source_bronze_column: "card_number",
    transformation_logic: "PAN tokenization/masking",
  },
  {
    table_name: "silver.card_transactions",
    column_name: "transaction_amount",
    data_type: "NUMERIC(18,2)",
    description: "Transaction amount",
    source_bronze_table: "bronze.card_txn_raw",
    source_bronze_column: "amount",
    transformation_logic: "Validated numeric",
  },
  {
    table_name: "silver.card_transactions",
    column_name: "merchant_name",
    data_type: "STRING",
    description: "Merchant name (cleansed)",
    source_bronze_table: "bronze.card_txn_raw",
    source_bronze_column: "merchant",
    transformation_logic: "Merchant name standardization",
  },
  {
    table_name: "silver.card_transactions",
    column_name: "mcc_code",
    data_type: "STRING",
    description: "Merchant Category Code",
    source_bronze_table: "bronze.card_txn_raw",
    source_bronze_column: "mcc",
    transformation_logic: "MCC validation",
  },

  // payment_transactions
  {
    table_name: "silver.payment_transactions",
    column_name: "payment_id",
    data_type: "STRING",
    description: "Unique payment identifier",
    source_bronze_table: "bronze.payments_raw",
    source_bronze_column: "payment_ref",
    transformation_logic: "Direct mapping",
  },
  {
    table_name: "silver.payment_transactions",
    column_name: "payment_type",
    data_type: "STRING",
    description: "Payment type (ACH, WIRE, etc.)",
    source_bronze_table: "bronze.payments_raw",
    source_bronze_column: "type",
    transformation_logic: "Standardized type codes",
  },
  {
    table_name: "silver.payment_transactions",
    column_name: "amount",
    data_type: "NUMERIC(18,2)",
    description: "Payment amount",
    source_bronze_table: "bronze.payments_raw",
    source_bronze_column: "amount",
    transformation_logic: "Validated numeric",
  },
  {
    table_name: "silver.payment_transactions",
    column_name: "status",
    data_type: "STRING",
    description: "Payment status",
    source_bronze_table: "bronze.payments_raw",
    source_bronze_column: "status",
    transformation_logic: "Mapped to {PENDING, SUCCESS, FAILED, REVERSED}",
  },
  {
    table_name: "silver.payment_transactions",
    column_name: "settlement_timestamp",
    data_type: "TIMESTAMP",
    description: "Settlement completion timestamp",
    source_bronze_table: "bronze.payments_raw",
    source_bronze_column: "settled_at",
    transformation_logic: "Timestamp normalization",
  },

  // fraud_alerts
  {
    table_name: "silver.fraud_alerts",
    column_name: "alert_id",
    data_type: "STRING",
    description: "Unique fraud alert identifier",
    source_bronze_table: "bronze.fraud_events",
    source_bronze_column: "event_id",
    transformation_logic: "Direct mapping",
  },
  {
    table_name: "silver.fraud_alerts",
    column_name: "transaction_id",
    data_type: "STRING",
    description: "Associated transaction ID",
    source_bronze_table: "bronze.fraud_events",
    source_bronze_column: "txn_id",
    transformation_logic: "Direct mapping",
  },
  {
    table_name: "silver.fraud_alerts",
    column_name: "alert_timestamp",
    data_type: "TIMESTAMP",
    description: "Alert generation timestamp",
    source_bronze_table: "bronze.fraud_events",
    source_bronze_column: "alert_ts",
    transformation_logic: "Timestamp normalization",
  },
  {
    table_name: "silver.fraud_alerts",
    column_name: "alert_outcome",
    data_type: "STRING",
    description: "Investigation outcome",
    source_bronze_table: "bronze.fraud_events",
    source_bronze_column: "outcome",
    transformation_logic: "Mapped to {TRUE_POSITIVE, FALSE_POSITIVE, UNDER_REVIEW}",
  },
  {
    table_name: "silver.fraud_alerts",
    column_name: "fraud_score",
    data_type: "DECIMAL(5,4)",
    description: "Model fraud score (0-1)",
    source_bronze_table: "bronze.fraud_events",
    source_bronze_column: "score",
    transformation_logic: "Normalized to 0-1 range",
  },
];

// Group tables by table name for export
export const silverTablesGrouped = silverTablesCatalog.reduce((acc, col) => {
  if (!acc[col.table_name]) {
    acc[col.table_name] = [];
  }
  acc[col.table_name].push(col);
  return acc;
}, {} as Record<string, SilverTableColumn[]>);

export const silverTableNames = Object.keys(silverTablesGrouped).sort();
