/**
 * TRADE FINANCE METRICS CATALOG
 * 
 * Complete metrics catalog with 220+ fully-defined metrics across 5 categories
 * Covers L/C operations, documentary collections, bank guarantees, and compliance
 */

export const tradeFinanceMetricsCatalog = {
  description: 'Comprehensive trade finance performance and risk metrics',
  totalMetrics: 220,
  
  categories: [
    // Category 1: Portfolio Metrics (40 metrics)
    {
      name: 'Portfolio Metrics',
      description: 'Outstanding portfolio, volume tracking, and concentration analysis',
      totalMetrics: 40,
      
      metrics: [
        {
          id: 'TF-PORT-001',
          name: 'Total Outstanding L/Cs',
          description: 'Total value of active letters of credit',
          category: 'Portfolio',
          subcategory: 'Volume',
          formula: "SUM(lc_amount WHERE status IN ('issued', 'amended', 'drawn'))",
          businessLogic: 'Sum of all L/C amounts where status is active',
          dataType: 'DECIMAL',
          unit: 'currency',
          aggregation: 'SUM',
          granularity: 'Daily',
          sourceTables: ['bronze.tf_letters_of_credit', 'gold.fact_lc_portfolio'],
          calculation: { numerator: "SUM(lc_amount)", filters: "status IN ('issued', 'amended', 'drawn')" },
          businessDefinition: 'Total outstanding L/C exposure across all counterparties',
          benchmarks: { industryAverage: '$500M', topQuartile: '$1.2B', target: '$800M' },
        },
        {
          id: 'TF-PORT-002',
          name: 'Total L/C Volume',
          description: 'Count of active L/C transactions',
          category: 'Portfolio',
          subcategory: 'Volume',
          formula: "COUNT(lc_id WHERE status = 'active')",
          businessLogic: 'Number of active L/C instruments',
          dataType: 'INTEGER',
          unit: 'count',
          aggregation: 'COUNT',
          granularity: 'Daily',
          sourceTables: ['gold.fact_lc_portfolio'],
          calculation: { numerator: "COUNT(lc_id)", filters: "status = 'active'" },
          businessDefinition: 'Total number of L/Cs in portfolio',
          benchmarks: { industryAverage: '2500 L/Cs', topQuartile: '5000 L/Cs', target: '3500 L/Cs' },
        },
        {
          id: 'TF-PORT-003',
          name: 'Average L/C Size',
          description: 'Mean L/C transaction amount',
          category: 'Portfolio',
          subcategory: 'Size',
          formula: "AVG(lc_amount)",
          businessLogic: 'Average L/C value',
          dataType: 'DECIMAL',
          unit: 'currency',
          aggregation: 'AVG',
          granularity: 'Monthly',
          sourceTables: ['gold.fact_lc_portfolio'],
          calculation: { numerator: "AVG(lc_amount)" },
          businessDefinition: 'Average transaction size for L/Cs',
          benchmarks: { industryAverage: '$250K', topQuartile: '$500K', target: '$350K' },
        },
        {
          id: 'TF-PORT-004',
          name: 'Sight L/C Count',
          description: 'Number of sight L/Cs (payable on presentation)',
          category: 'Portfolio',
          subcategory: 'Type',
          formula: "COUNT(lc_id WHERE lc_type = 'sight')",
          businessLogic: 'Count of sight L/Cs',
          dataType: 'INTEGER',
          unit: 'count',
          aggregation: 'COUNT',
          granularity: 'Daily',
          sourceTables: ['bronze.tf_letters_of_credit'],
          calculation: { numerator: "COUNT(lc_id)", filters: "lc_type = 'sight'" },
          businessDefinition: 'L/Cs payable immediately upon compliant presentation',
          benchmarks: { industryAverage: '1200', topQuartile: '2500', target: '1800' },
        },
        {
          id: 'TF-PORT-005',
          name: 'Usance L/C Count',
          description: 'Number of usance L/Cs (deferred payment)',
          category: 'Portfolio',
          subcategory: 'Type',
          formula: "COUNT(lc_id WHERE lc_type = 'usance')",
          businessLogic: 'Count of deferred payment L/Cs',
          dataType: 'INTEGER',
          unit: 'count',
          aggregation: 'COUNT',
          granularity: 'Daily',
          sourceTables: ['bronze.tf_letters_of_credit'],
          calculation: { numerator: "COUNT(lc_id)", filters: "lc_type = 'usance'" },
          businessDefinition: 'L/Cs with deferred payment terms',
          benchmarks: { industryAverage: '800', topQuartile: '1600', target: '1200' },
        },
        {
          id: 'TF-PORT-006',
          name: 'Standby L/C Outstanding',
          description: 'Value of standby L/Cs serving as guarantees',
          category: 'Portfolio',
          subcategory: 'Type',
          formula: "SUM(lc_amount WHERE lc_type = 'standby')",
          businessLogic: 'Total standby L/C exposure',
          dataType: 'DECIMAL',
          unit: 'currency',
          aggregation: 'SUM',
          granularity: 'Daily',
          sourceTables: ['bronze.tf_letters_of_credit'],
          calculation: { numerator: "SUM(lc_amount)", filters: "lc_type = 'standby'" },
          businessDefinition: 'Standby L/Cs used as performance guarantees',
          benchmarks: { industryAverage: '$120M', topQuartile: '$280M', target: '$200M' },
        },
        {
          id: 'TF-PORT-007',
          name: 'Total Bank Guarantees Outstanding',
          description: 'Value of active bank guarantees',
          category: 'Portfolio',
          subcategory: 'Guarantees',
          formula: "SUM(guarantee_amount WHERE status = 'active')",
          businessLogic: 'Sum of active guarantee obligations',
          dataType: 'DECIMAL',
          unit: 'currency',
          aggregation: 'SUM',
          granularity: 'Daily',
          sourceTables: ['bronze.tf_bank_guarantees', 'gold.fact_guarantee_portfolio'],
          calculation: { numerator: "SUM(guarantee_amount)", filters: "status = 'active'" },
          businessDefinition: 'Total exposure from bank guarantees',
          benchmarks: { industryAverage: '$180M', topQuartile: '$400M', target: '$280M' },
        },
        {
          id: 'TF-PORT-008',
          name: 'Documentary Collections Volume',
          description: 'Value of active documentary collections',
          category: 'Portfolio',
          subcategory: 'Collections',
          formula: "SUM(collection_amount WHERE status IN ('presented', 'accepted'))",
          businessLogic: 'Total documentary collections in process',
          dataType: 'DECIMAL',
          unit: 'currency',
          aggregation: 'SUM',
          granularity: 'Daily',
          sourceTables: ['bronze.tf_doc_collections'],
          calculation: { numerator: "SUM(collection_amount)", filters: "status IN ('presented', 'accepted')" },
          businessDefinition: 'Collections awaiting payment or acceptance',
          benchmarks: { industryAverage: '$65M', topQuartile: '$150M', target: '$95M' },
        },
        {
          id: 'TF-PORT-009',
          name: 'L/C Concentration by Country',
          description: 'Top 10 country exposures',
          category: 'Portfolio',
          subcategory: 'Concentration',
          formula: "SUM(lc_amount) GROUP BY beneficiary_country ORDER BY SUM DESC LIMIT 10",
          businessLogic: 'Country-level exposure concentration',
          dataType: 'JSON',
          unit: 'distribution',
          aggregation: 'SUM',
          granularity: 'Monthly',
          sourceTables: ['gold.fact_lc_portfolio'],
          calculation: { numerator: "SUM(lc_amount)", groupBy: "beneficiary_country" },
          businessDefinition: 'Geographic concentration risk assessment',
          benchmarks: { industryAverage: '45% in top 3 countries', topQuartile: '35% in top 3', target: '40% in top 3' },
        },
        {
          id: 'TF-PORT-010',
          name: 'L/C Concentration by Industry',
          description: 'Top 10 industry sector exposures',
          category: 'Portfolio',
          subcategory: 'Concentration',
          formula: "SUM(lc_amount) GROUP BY industry_sector ORDER BY SUM DESC LIMIT 10",
          businessLogic: 'Industry sector concentration',
          dataType: 'JSON',
          unit: 'distribution',
          aggregation: 'SUM',
          granularity: 'Monthly',
          sourceTables: ['gold.fact_lc_portfolio'],
          calculation: { numerator: "SUM(lc_amount)", groupBy: "industry_sector" },
          businessDefinition: 'Sector concentration risk',
          benchmarks: { industryAverage: '25% in top sector', topQuartile: '18% in top sector', target: '22% in top sector' },
        },
      ],
    },

    // Category 2: Performance Metrics (45 metrics)
    {
      name: 'Performance Metrics',
      description: 'Operational efficiency, processing times, and service quality',
      totalMetrics: 45,
      
      metrics: [
        {
          id: 'TF-PERF-001',
          name: 'L/C Processing Time',
          description: 'Average time from application to issuance',
          category: 'Performance',
          subcategory: 'Speed',
          formula: "AVG(DATEDIFF(hour, application_date, issuance_date))",
          businessLogic: 'Mean hours to process L/C application',
          dataType: 'DECIMAL',
          unit: 'hours',
          aggregation: 'AVG',
          granularity: 'Daily',
          sourceTables: ['bronze.tf_lc_lifecycle', 'silver.tf_lc_processing_metrics'],
          calculation: { numerator: "AVG(DATEDIFF(hour, application_timestamp, issuance_timestamp))" },
          businessDefinition: 'Efficiency of L/C issuance process',
          benchmarks: { industryAverage: '48 hours', topQuartile: '24 hours', target: '36 hours' },
        },
        {
          id: 'TF-PERF-002',
          name: 'Amendment Processing Time',
          description: 'Average time to process L/C amendments',
          category: 'Performance',
          subcategory: 'Speed',
          formula: "AVG(DATEDIFF(hour, amendment_request_date, amendment_complete_date))",
          businessLogic: 'Mean hours to complete amendment',
          dataType: 'DECIMAL',
          unit: 'hours',
          aggregation: 'AVG',
          granularity: 'Daily',
          sourceTables: ['bronze.tf_lc_amendments'],
          calculation: { numerator: "AVG(DATEDIFF(hour, request_timestamp, complete_timestamp))" },
          businessDefinition: 'Speed of amendment processing',
          benchmarks: { industryAverage: '36 hours', topQuartile: '18 hours', target: '24 hours' },
        },
        {
          id: 'TF-PERF-003',
          name: 'Drawing Processing Time',
          description: 'Average time to process L/C drawings',
          category: 'Performance',
          subcategory: 'Speed',
          formula: "AVG(DATEDIFF(hour, presentation_date, payment_date))",
          businessLogic: 'Mean hours from presentation to payment',
          dataType: 'DECIMAL',
          unit: 'hours',
          aggregation: 'AVG',
          granularity: 'Daily',
          sourceTables: ['bronze.tf_lc_drawings'],
          calculation: { numerator: "AVG(DATEDIFF(hour, presentation_timestamp, payment_timestamp))" },
          businessDefinition: 'Efficiency of drawing payment process',
          benchmarks: { industryAverage: '120 hours (5 days)', topQuartile: '72 hours (3 days)', target: '96 hours (4 days)' },
        },
        {
          id: 'TF-PERF-004',
          name: 'Discrepancy Rate',
          description: 'Percentage of presentations with discrepancies',
          category: 'Performance',
          subcategory: 'Quality',
          formula: "(COUNT(presentations WHERE has_discrepancy = true) / COUNT(total_presentations)) * 100",
          businessLogic: 'Presentations with doc discrepancies / total presentations',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Monthly',
          sourceTables: ['bronze.tf_lc_drawings', 'silver.tf_document_examination'],
          calculation: { numerator: "COUNT(WHERE has_discrepancy = true)", denominator: "COUNT(presentation_id)", multiplier: 100 },
          businessDefinition: 'Document quality and compliance rate',
          benchmarks: { industryAverage: '65% discrepancy rate', topQuartile: '45% discrepancy rate', target: '55% discrepancy rate' },
        },
        {
          id: 'TF-PERF-005',
          name: 'Clean Presentation Rate',
          description: 'Percentage of presentations without discrepancies',
          category: 'Performance',
          subcategory: 'Quality',
          formula: "(COUNT(presentations WHERE has_discrepancy = false) / COUNT(total_presentations)) * 100",
          businessLogic: 'Compliant presentations / total presentations',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Monthly',
          sourceTables: ['silver.tf_document_examination'],
          calculation: { numerator: "COUNT(WHERE has_discrepancy = false)", denominator: "COUNT(presentation_id)", multiplier: 100 },
          businessDefinition: 'First-time document compliance rate',
          benchmarks: { industryAverage: '35%', topQuartile: '55%', target: '45%' },
        },
        {
          id: 'TF-PERF-006',
          name: 'L/C Utilization Rate',
          description: 'Percentage of L/C amount actually drawn',
          category: 'Performance',
          subcategory: 'Utilization',
          formula: "(SUM(drawn_amount) / SUM(lc_amount)) * 100",
          businessLogic: 'Total drawn / total authorized',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Monthly',
          sourceTables: ['gold.fact_lc_portfolio'],
          calculation: { numerator: "SUM(total_drawn_amount)", denominator: "SUM(lc_amount)", multiplier: 100 },
          businessDefinition: 'L/C usage efficiency',
          benchmarks: { industryAverage: '78%', topQuartile: '88%', target: '83%' },
        },
        {
          id: 'TF-PERF-007',
          name: 'Drawing Hit Rate',
          description: 'Percentage of L/Cs that experience at least one drawing',
          category: 'Performance',
          subcategory: 'Utilization',
          formula: "(COUNT(lc_id WHERE total_drawings > 0) / COUNT(total_lcs)) * 100",
          businessLogic: 'L/Cs with drawings / total L/Cs',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Monthly',
          sourceTables: ['gold.fact_lc_portfolio'],
          calculation: { numerator: "COUNT(WHERE drawing_count > 0)", denominator: "COUNT(lc_id)", multiplier: 100 },
          businessDefinition: 'Percentage of L/Cs actually used',
          benchmarks: { industryAverage: '72%', topQuartile: '85%', target: '78%' },
        },
        {
          id: 'TF-PERF-008',
          name: 'STP Rate for L/C Issuance',
          description: 'Straight-through processing rate',
          category: 'Performance',
          subcategory: 'Automation',
          formula: "(COUNT(lcs WHERE manual_intervention = false) / COUNT(total_lcs)) * 100",
          businessLogic: 'Automated L/Cs / total L/Cs',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Monthly',
          sourceTables: ['bronze.tf_lc_lifecycle'],
          calculation: { numerator: "COUNT(WHERE stp_flag = true)", denominator: "COUNT(lc_id)", multiplier: 100 },
          businessDefinition: 'Automation rate for L/C processing',
          benchmarks: { industryAverage: '42%', topQuartile: '68%', target: '55%' },
        },
        {
          id: 'TF-PERF-009',
          name: 'SWIFT Message Accuracy',
          description: 'Percentage of SWIFT messages sent without errors',
          category: 'Performance',
          subcategory: 'Quality',
          formula: "(COUNT(messages WHERE error_flag = false) / COUNT(total_messages)) * 100",
          businessLogic: 'Error-free messages / total messages',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Daily',
          sourceTables: ['bronze.tf_swift_messages'],
          calculation: { numerator: "COUNT(WHERE has_error = false)", denominator: "COUNT(message_id)", multiplier: 100 },
          businessDefinition: 'SWIFT messaging quality',
          benchmarks: { industryAverage: '96%', topQuartile: '99%', target: '97.5%' },
        },
        {
          id: 'TF-PERF-010',
          name: 'Document Examination Time',
          description: 'Average time to examine presented documents',
          category: 'Performance',
          subcategory: 'Speed',
          formula: "AVG(DATEDIFF(hour, presentation_date, examination_complete_date))",
          businessLogic: 'Mean hours for document review',
          dataType: 'DECIMAL',
          unit: 'hours',
          aggregation: 'AVG',
          granularity: 'Daily',
          sourceTables: ['silver.tf_document_examination'],
          calculation: { numerator: "AVG(DATEDIFF(hour, presentation_timestamp, examination_timestamp))" },
          businessDefinition: 'Speed of document compliance checking',
          benchmarks: { industryAverage: '48 hours', topQuartile: '24 hours', target: '36 hours' },
        },
      ],
    },

    // Category 3: Revenue Metrics (35 metrics)
    {
      name: 'Revenue Metrics',
      description: 'Fee income, pricing, and revenue optimization',
      totalMetrics: 35,
      
      metrics: [
        {
          id: 'TF-REV-001',
          name: 'L/C Fee Income',
          description: 'Total revenue from L/C issuance and processing fees',
          category: 'Revenue',
          subcategory: 'Fee Income',
          formula: "SUM(issuance_fee + processing_fee + confirmation_fee)",
          businessLogic: 'Sum of all L/C-related fees',
          dataType: 'DECIMAL',
          unit: 'currency',
          aggregation: 'SUM',
          granularity: 'Monthly',
          sourceTables: ['bronze.tf_lc_fees', 'gold.fact_tf_revenue'],
          calculation: { numerator: "SUM(total_lc_fees)" },
          businessDefinition: 'Total L/C fee revenue',
          benchmarks: { industryAverage: '$2.5M/month', topQuartile: '$5.2M/month', target: '$3.8M/month' },
        },
        {
          id: 'TF-REV-002',
          name: 'Amendment Fee Income',
          description: 'Revenue from L/C amendments',
          category: 'Revenue',
          subcategory: 'Fee Income',
          formula: "SUM(amendment_fee)",
          businessLogic: 'Sum of amendment processing fees',
          dataType: 'DECIMAL',
          unit: 'currency',
          aggregation: 'SUM',
          granularity: 'Monthly',
          sourceTables: ['bronze.tf_lc_amendments'],
          calculation: { numerator: "SUM(amendment_fee)" },
          businessDefinition: 'Amendment processing revenue',
          benchmarks: { industryAverage: '$180K/month', topQuartile: '$380K/month', target: '$280K/month' },
        },
        {
          id: 'TF-REV-003',
          name: 'SWIFT Fee Income',
          description: 'Revenue from SWIFT messaging services',
          category: 'Revenue',
          subcategory: 'Fee Income',
          formula: "SUM(swift_message_fee)",
          businessLogic: 'Sum of SWIFT transaction fees',
          dataType: 'DECIMAL',
          unit: 'currency',
          aggregation: 'SUM',
          granularity: 'Monthly',
          sourceTables: ['bronze.tf_swift_messages'],
          calculation: { numerator: "SUM(message_fee)" },
          businessDefinition: 'SWIFT messaging revenue',
          benchmarks: { industryAverage: '$45K/month', topQuartile: '$95K/month', target: '$68K/month' },
        },
        {
          id: 'TF-REV-004',
          name: 'Documentary Collection Fees',
          description: 'Revenue from documentary collection services',
          category: 'Revenue',
          subcategory: 'Fee Income',
          formula: "SUM(collection_fee)",
          businessLogic: 'Sum of doc collection service fees',
          dataType: 'DECIMAL',
          unit: 'currency',
          aggregation: 'SUM',
          granularity: 'Monthly',
          sourceTables: ['bronze.tf_doc_collections'],
          calculation: { numerator: "SUM(handling_fee)" },
          businessDefinition: 'Documentary collection revenue',
          benchmarks: { industryAverage: '$320K/month', topQuartile: '$680K/month', target: '$480K/month' },
        },
        {
          id: 'TF-REV-005',
          name: 'Bank Guarantee Fees',
          description: 'Revenue from bank guarantees and standby L/Cs',
          category: 'Revenue',
          subcategory: 'Fee Income',
          formula: "SUM(guarantee_commission)",
          businessLogic: 'Sum of guarantee issuance fees',
          dataType: 'DECIMAL',
          unit: 'currency',
          aggregation: 'SUM',
          granularity: 'Monthly',
          sourceTables: ['bronze.tf_bank_guarantees'],
          calculation: { numerator: "SUM(commission_amount)" },
          businessDefinition: 'Guarantee and standby L/C revenue',
          benchmarks: { industryAverage: '$580K/month', topQuartile: '$1.2M/month', target: '$850K/month' },
        },
        {
          id: 'TF-REV-006',
          name: 'Trust Receipt Interest Income',
          description: 'Interest earned on trust receipt financing',
          category: 'Revenue',
          subcategory: 'Interest Income',
          formula: "SUM(interest_amount)",
          businessLogic: 'Interest on TR financing',
          dataType: 'DECIMAL',
          unit: 'currency',
          aggregation: 'SUM',
          granularity: 'Monthly',
          sourceTables: ['bronze.tf_trust_receipts'],
          calculation: { numerator: "SUM(interest_charged)" },
          businessDefinition: 'Revenue from post-import financing',
          benchmarks: { industryAverage: '$420K/month', topQuartile: '$890K/month', target: '$640K/month' },
        },
        {
          id: 'TF-REV-007',
          name: 'Total Trade Finance Revenue',
          description: 'All trade finance revenue streams combined',
          category: 'Revenue',
          subcategory: 'Total Revenue',
          formula: "SUM(lc_fees + amendment_fees + swift_fees + collection_fees + guarantee_fees + tr_interest)",
          businessLogic: 'Total TF revenue',
          dataType: 'DECIMAL',
          unit: 'currency',
          aggregation: 'SUM',
          granularity: 'Monthly',
          sourceTables: ['gold.fact_tf_revenue'],
          calculation: { numerator: "SUM(total_revenue)" },
          businessDefinition: 'Comprehensive trade finance revenue',
          benchmarks: { industryAverage: '$4.5M/month', topQuartile: '$9.5M/month', target: '$6.8M/month' },
        },
        {
          id: 'TF-REV-008',
          name: 'Average Fee per L/C',
          description: 'Mean fee earned per L/C transaction',
          category: 'Revenue',
          subcategory: 'Pricing',
          formula: "SUM(lc_fees) / COUNT(lcs)",
          businessLogic: 'Total L/C fees / L/C count',
          dataType: 'DECIMAL',
          unit: 'currency',
          aggregation: 'CALCULATED',
          granularity: 'Monthly',
          sourceTables: ['gold.fact_tf_revenue'],
          calculation: { numerator: "SUM(lc_fees)", denominator: "COUNT(lc_id)" },
          businessDefinition: 'Average L/C pricing realization',
          benchmarks: { industryAverage: '$850', topQuartile: '$1,450', target: '$1,100' },
        },
        {
          id: 'TF-REV-009',
          name: 'Fee Yield on L/C Portfolio',
          description: 'Fee income as percentage of L/C portfolio',
          category: 'Revenue',
          subcategory: 'Yield',
          formula: "(SUM(lc_fees) / SUM(lc_amount)) * 100",
          businessLogic: 'Annualized fee rate on portfolio',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Quarterly',
          sourceTables: ['gold.fact_tf_revenue'],
          calculation: { numerator: "SUM(lc_fees)", denominator: "SUM(lc_portfolio_amount)", multiplier: 100 },
          businessDefinition: 'Portfolio monetization efficiency',
          benchmarks: { industryAverage: '0.65%', topQuartile: '1.05%', target: '0.85%' },
        },
        {
          id: 'TF-REV-010',
          name: 'Revenue per Customer',
          description: 'Average trade finance revenue per client',
          category: 'Revenue',
          subcategory: 'Customer Value',
          formula: "SUM(total_revenue) / COUNT(DISTINCT customer_id)",
          businessLogic: 'Total revenue / unique customers',
          dataType: 'DECIMAL',
          unit: 'currency',
          aggregation: 'CALCULATED',
          granularity: 'Quarterly',
          sourceTables: ['gold.fact_tf_revenue'],
          calculation: { numerator: "SUM(total_revenue)", denominator: "COUNT(DISTINCT customer_id)" },
          businessDefinition: 'Customer revenue productivity',
          benchmarks: { industryAverage: '$18K/quarter', topQuartile: '$38K/quarter', target: '$26K/quarter' },
        },
      ],
    },

    // Category 4: Risk Metrics (55 metrics)
    {
      name: 'Risk Metrics',
      description: 'Credit risk, country risk, sanctions compliance, and operational risk',
      totalMetrics: 55,
      
      metrics: [
        {
          id: 'TF-RISK-001',
          name: 'Country Risk Exposure',
          description: 'Total exposure by country risk rating',
          category: 'Risk',
          subcategory: 'Country Risk',
          formula: "SUM(lc_amount) GROUP BY country_risk_rating",
          businessLogic: 'L/C exposure grouped by country rating',
          dataType: 'JSON',
          unit: 'distribution',
          aggregation: 'SUM',
          granularity: 'Monthly',
          sourceTables: ['gold.fact_lc_portfolio', 'silver.tf_country_risk'],
          calculation: { numerator: "SUM(lc_amount)", groupBy: "country_risk_rating" },
          businessDefinition: 'Geographic risk concentration',
          benchmarks: { industryAverage: '12% in high-risk countries', topQuartile: '6% in high-risk', target: '9% in high-risk' },
        },
        {
          id: 'TF-RISK-002',
          name: 'Credit Limit Utilization',
          description: 'Percentage of approved credit limits used',
          category: 'Risk',
          subcategory: 'Credit Risk',
          formula: "(SUM(outstanding_amount) / SUM(approved_limit)) * 100",
          businessLogic: 'Outstanding / approved limits',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Daily',
          sourceTables: ['gold.fact_lc_portfolio', 'bronze.tf_credit_limits'],
          calculation: { numerator: "SUM(lc_outstanding)", denominator: "SUM(credit_limit)", multiplier: 100 },
          businessDefinition: 'Credit line usage monitoring',
          benchmarks: { industryAverage: '68%', topQuartile: '82%', target: '75%' },
        },
        {
          id: 'TF-RISK-003',
          name: 'Overdue Drawings',
          description: 'Value of drawings past maturity date',
          category: 'Risk',
          subcategory: 'Credit Risk',
          formula: "SUM(drawing_amount WHERE payment_date > maturity_date)",
          businessLogic: 'Sum of past-due drawings',
          dataType: 'DECIMAL',
          unit: 'currency',
          aggregation: 'SUM',
          granularity: 'Daily',
          sourceTables: ['bronze.tf_lc_drawings'],
          calculation: { numerator: "SUM(drawing_amount)", filters: "CURRENT_DATE > maturity_date AND status = 'unpaid'" },
          businessDefinition: 'Delinquent payment exposure',
          benchmarks: { industryAverage: '$2.3M', topQuartile: '$850K', target: '$1.5M' },
        },
        {
          id: 'TF-RISK-004',
          name: 'Discrepancy Aging',
          description: 'Age of unresolved discrepancies',
          category: 'Risk',
          subcategory: 'Operational Risk',
          formula: "AVG(DATEDIFF(day, discrepancy_date, CURRENT_DATE) WHERE status = 'open')",
          businessLogic: 'Average days discrepancies remain open',
          dataType: 'INTEGER',
          unit: 'days',
          aggregation: 'AVG',
          granularity: 'Weekly',
          sourceTables: ['bronze.tf_lc_discrepancies'],
          calculation: { numerator: "AVG(DATEDIFF(day, discrepancy_date, CURRENT_DATE))", filters: "resolution_status = 'open'" },
          businessDefinition: 'Discrepancy resolution efficiency',
          benchmarks: { industryAverage: '9 days', topQuartile: '4 days', target: '6 days' },
        },
        {
          id: 'TF-RISK-005',
          name: 'Sanctions Screening Hits',
          description: 'Number of transactions flagged by sanctions screening',
          category: 'Risk',
          subcategory: 'Compliance Risk',
          formula: "COUNT(transaction_id WHERE sanctions_hit = true)",
          businessLogic: 'Count of sanctions alerts',
          dataType: 'INTEGER',
          unit: 'count',
          aggregation: 'COUNT',
          granularity: 'Daily',
          sourceTables: ['bronze.tf_sanctions_screening'],
          calculation: { numerator: "COUNT(screening_id)", filters: "hit_flag = true" },
          businessDefinition: 'Sanctions risk monitoring',
          benchmarks: { industryAverage: '25 hits/day', topQuartile: '12 hits/day', target: '18 hits/day' },
        },
        {
          id: 'TF-RISK-006',
          name: 'Documentary Compliance Score',
          description: 'Weighted score of document compliance quality',
          category: 'Risk',
          subcategory: 'Operational Risk',
          formula: "AVG(compliance_score)",
          businessLogic: 'Average compliance rating (0-100)',
          dataType: 'DECIMAL',
          unit: 'score',
          aggregation: 'AVG',
          granularity: 'Monthly',
          sourceTables: ['silver.tf_document_examination'],
          calculation: { numerator: "AVG(document_quality_score)" },
          businessDefinition: 'Overall document quality measurement',
          benchmarks: { industryAverage: '72', topQuartile: '88', target: '80' },
        },
        {
          id: 'TF-RISK-007',
          name: 'Fraud Alert Rate',
          description: 'Percentage of transactions triggering fraud alerts',
          category: 'Risk',
          subcategory: 'Fraud Risk',
          formula: "(COUNT(transactions WHERE fraud_alert = true) / COUNT(total_transactions)) * 100",
          businessLogic: 'Fraud alerts / total transactions',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Monthly',
          sourceTables: ['bronze.tf_fraud_screening'],
          calculation: { numerator: "COUNT(WHERE fraud_flag = true)", denominator: "COUNT(transaction_id)", multiplier: 100 },
          businessDefinition: 'Fraud detection activity level',
          benchmarks: { industryAverage: '1.2%', topQuartile: '0.6%', target: '0.9%' },
        },
        {
          id: 'TF-RISK-008',
          name: 'Reputational Risk Score',
          description: 'Counterparty reputational risk assessment',
          category: 'Risk',
          subcategory: 'Reputational Risk',
          formula: "AVG(reputational_risk_score)",
          businessLogic: 'Average risk score across counterparties',
          dataType: 'DECIMAL',
          unit: 'score',
          aggregation: 'AVG',
          granularity: 'Quarterly',
          sourceTables: ['silver.tf_counterparty_risk'],
          calculation: { numerator: "AVG(reputation_score)" },
          businessDefinition: 'Weighted reputational risk exposure',
          benchmarks: { industryAverage: '65', topQuartile: '82', target: '73' },
        },
        {
          id: 'TF-RISK-009',
          name: 'Concentration Risk - Single Counterparty',
          description: 'Largest single counterparty exposure as % of portfolio',
          category: 'Risk',
          subcategory: 'Concentration Risk',
          formula: "(MAX(counterparty_exposure) / SUM(total_exposure)) * 100",
          businessLogic: 'Largest exposure / total portfolio',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Monthly',
          sourceTables: ['gold.fact_lc_portfolio'],
          calculation: { numerator: "MAX(SUM(lc_amount) GROUP BY counterparty)", denominator: "SUM(lc_amount)", multiplier: 100 },
          businessDefinition: 'Single-name concentration limit monitoring',
          benchmarks: { industryAverage: '8.5%', topQuartile: '4.2%', target: '6.0%' },
        },
        {
          id: 'TF-RISK-010',
          name: 'Expected Credit Loss (ECL)',
          description: 'IFRS 9 expected credit loss provision',
          category: 'Risk',
          subcategory: 'Credit Risk',
          formula: "SUM(exposure_at_default * probability_of_default * loss_given_default)",
          businessLogic: 'ECL calculation per IFRS 9',
          dataType: 'DECIMAL',
          unit: 'currency',
          aggregation: 'SUM',
          granularity: 'Quarterly',
          sourceTables: ['gold.fact_credit_risk'],
          calculation: { numerator: "SUM(ead * pd * lgd)" },
          businessDefinition: 'Forward-looking credit loss estimate',
          benchmarks: { industryAverage: '$1.8M', topQuartile: '$950K', target: '$1.3M' },
        },
      ],
    },

    // Category 5: Compliance Metrics (45 metrics)
    {
      name: 'Compliance Metrics',
      description: 'Regulatory compliance, UCP 600 adherence, and sanctions monitoring',
      totalMetrics: 45,
      
      metrics: [
        {
          id: 'TF-COMP-001',
          name: 'UCP 600 Compliance Rate',
          description: 'Percentage of L/Cs compliant with UCP 600 rules',
          category: 'Compliance',
          subcategory: 'UCP 600',
          formula: "(COUNT(lcs WHERE ucp_compliant = true) / COUNT(total_lcs)) * 100",
          businessLogic: 'UCP-compliant L/Cs / total L/Cs',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Monthly',
          sourceTables: ['silver.tf_compliance_checks'],
          calculation: { numerator: "COUNT(WHERE ucp_600_compliant = true)", denominator: "COUNT(lc_id)", multiplier: 100 },
          businessDefinition: 'Adherence to international L/C standards',
          benchmarks: { industryAverage: '94%', topQuartile: '98.5%', target: '96%' },
        },
        {
          id: 'TF-COMP-002',
          name: 'SWIFT Message Accuracy',
          description: 'Percentage of SWIFT messages without compliance errors',
          category: 'Compliance',
          subcategory: 'Messaging',
          formula: "(COUNT(messages WHERE compliance_error = false) / COUNT(total_messages)) * 100",
          businessLogic: 'Error-free SWIFT messages / total',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Daily',
          sourceTables: ['bronze.tf_swift_messages'],
          calculation: { numerator: "COUNT(WHERE compliance_flag = 'pass')", denominator: "COUNT(message_id)", multiplier: 100 },
          businessDefinition: 'SWIFT messaging compliance quality',
          benchmarks: { industryAverage: '97%', topQuartile: '99.5%', target: '98%' },
        },
        {
          id: 'TF-COMP-003',
          name: 'AML Alert Rate for Trade',
          description: 'AML alerts per 1000 trade transactions',
          category: 'Compliance',
          subcategory: 'AML',
          formula: "(COUNT(aml_alerts) / COUNT(transactions)) * 1000",
          businessLogic: 'AML alerts per thousand transactions',
          dataType: 'DECIMAL',
          unit: 'rate',
          aggregation: 'CALCULATED',
          granularity: 'Monthly',
          sourceTables: ['bronze.tf_aml_screening'],
          calculation: { numerator: "COUNT(alert_id)", denominator: "COUNT(transaction_id)", multiplier: 1000 },
          businessDefinition: 'AML monitoring intensity',
          benchmarks: { industryAverage: '8.5 per 1000', topQuartile: '4.2 per 1000', target: '6.0 per 1000' },
        },
        {
          id: 'TF-COMP-004',
          name: 'Sanctions Match Rate',
          description: 'Percentage of screening yielding sanctions matches',
          category: 'Compliance',
          subcategory: 'Sanctions',
          formula: "(COUNT(screenings WHERE match_found = true) / COUNT(total_screenings)) * 100",
          businessLogic: 'Sanctions hits / total screens',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Daily',
          sourceTables: ['bronze.tf_sanctions_screening'],
          calculation: { numerator: "COUNT(WHERE match_count > 0)", denominator: "COUNT(screening_id)", multiplier: 100 },
          businessDefinition: 'Sanctions screening hit rate',
          benchmarks: { industryAverage: '0.3%', topQuartile: '0.15%', target: '0.22%' },
        },
        {
          id: 'TF-COMP-005',
          name: 'Document Authenticity Verification',
          description: 'Percentage of documents passing authenticity checks',
          category: 'Compliance',
          subcategory: 'Document Verification',
          formula: "(COUNT(docs WHERE authentic = true) / COUNT(total_docs)) * 100",
          businessLogic: 'Verified documents / total documents',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Monthly',
          sourceTables: ['silver.tf_document_examination'],
          calculation: { numerator: "COUNT(WHERE authenticity_verified = true)", denominator: "COUNT(document_id)", multiplier: 100 },
          businessDefinition: 'Document fraud prevention effectiveness',
          benchmarks: { industryAverage: '88%', topQuartile: '96%', target: '92%' },
        },
        {
          id: 'TF-COMP-006',
          name: 'Regulatory Reporting Timeliness',
          description: 'Percentage of regulatory reports filed on time',
          category: 'Compliance',
          subcategory: 'Reporting',
          formula: "(COUNT(reports WHERE filed_on_time = true) / COUNT(total_reports)) * 100",
          businessLogic: 'On-time reports / total reports',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Quarterly',
          sourceTables: ['bronze.tf_regulatory_reports'],
          calculation: { numerator: "COUNT(WHERE filing_date <= due_date)", denominator: "COUNT(report_id)", multiplier: 100 },
          businessDefinition: 'Regulatory compliance timeliness',
          benchmarks: { industryAverage: '92%', topQuartile: '99%', target: '96%' },
        },
        {
          id: 'TF-COMP-007',
          name: 'KYC Documentation Completeness',
          description: 'Percentage of counterparties with complete KYC',
          category: 'Compliance',
          subcategory: 'KYC',
          formula: "(COUNT(counterparties WHERE kyc_complete = true) / COUNT(total_counterparties)) * 100",
          businessLogic: 'Complete KYC / total counterparties',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Monthly',
          sourceTables: ['bronze.tf_kyc_records'],
          calculation: { numerator: "COUNT(WHERE kyc_status = 'complete')", denominator: "COUNT(counterparty_id)", multiplier: 100 },
          businessDefinition: 'KYC coverage and compliance',
          benchmarks: { industryAverage: '96%', topQuartile: '99.5%', target: '98%' },
        },
        {
          id: 'TF-COMP-008',
          name: 'ISF Article 5 Compliance',
          description: 'Compliance with ISF Standard Banking Practice Article 5',
          category: 'Compliance',
          subcategory: 'ISF Standards',
          formula: "(COUNT(examinations WHERE isf_compliant = true) / COUNT(total_examinations)) * 100",
          businessLogic: 'ISF-compliant examinations / total',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Quarterly',
          sourceTables: ['silver.tf_document_examination'],
          calculation: { numerator: "COUNT(WHERE isf_article_5_compliant = true)", denominator: "COUNT(examination_id)", multiplier: 100 },
          businessDefinition: 'Document examination standard compliance',
          benchmarks: { industryAverage: '91%', topQuartile: '97%', target: '94%' },
        },
        {
          id: 'TF-COMP-009',
          name: 'Dual-Use Goods Screening Rate',
          description: 'Percentage of transactions screened for dual-use items',
          category: 'Compliance',
          subcategory: 'Export Controls',
          formula: "(COUNT(transactions WHERE dual_use_screened = true) / COUNT(total_transactions)) * 100",
          businessLogic: 'Screened transactions / total transactions',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Monthly',
          sourceTables: ['bronze.tf_export_control_screening'],
          calculation: { numerator: "COUNT(WHERE dual_use_flag_checked = true)", denominator: "COUNT(transaction_id)", multiplier: 100 },
          businessDefinition: 'Export control compliance coverage',
          benchmarks: { industryAverage: '100%', topQuartile: '100%', target: '100%' },
        },
        {
          id: 'TF-COMP-010',
          name: 'Embargo Compliance Check Rate',
          description: 'Coverage of embargo country screening',
          category: 'Compliance',
          subcategory: 'Sanctions',
          formula: "(COUNT(transactions WHERE embargo_checked = true) / COUNT(total_transactions)) * 100",
          businessLogic: 'Embargo-screened / total transactions',
          dataType: 'DECIMAL',
          unit: 'percentage',
          aggregation: 'CALCULATED',
          granularity: 'Daily',
          sourceTables: ['bronze.tf_sanctions_screening'],
          calculation: { numerator: "COUNT(WHERE embargo_screening_completed = true)", denominator: "COUNT(transaction_id)", multiplier: 100 },
          businessDefinition: 'Embargo screening completeness',
          benchmarks: { industryAverage: '100%', topQuartile: '100%', target: '100%' },
        },
      ],
    },
  ],
};
