// ============================================================================
// WEALTH MANAGEMENT DOMAIN - COMPREHENSIVE IMPLEMENTATION
// ============================================================================
// Coverage: Portfolio Management, Investment Advisory, Trust Services,
// Asset Allocation, Performance Measurement, Fee Billing, Compliance
// ============================================================================

export const wealthBronzeLayer = {
  description: "Raw wealth management and advisory data",
  tables: [
    {
      name: "bronze_client_portfolios",
      description: "Raw client portfolio data",
      schema: {
        portfolio_id: "STRING PRIMARY KEY",
        portfolio_timestamp: "TIMESTAMP",
        portfolio_date: "DATE",
        client_id: "STRING",
        account_id: "STRING",
        portfolio_type: "STRING",
        account_type: "STRING",
        registration_type: "STRING",
        investment_objective: "STRING",
        risk_tolerance: "STRING",
        time_horizon: "STRING",
        total_value: "DECIMAL(18,2)",
        cash_balance: "DECIMAL(18,2)",
        invested_value: "DECIMAL(18,2)",
        unrealized_gain_loss: "DECIMAL(18,2)",
        realized_gain_loss_ytd: "DECIMAL(18,2)",
        income_ytd: "DECIMAL(18,2)",
        asset_allocation: "JSON",
        target_allocation: "JSON",
        rebalance_threshold: "DECIMAL(5,2)",
        last_rebalance_date: "DATE",
        advisor_id: "STRING",
        management_fee_rate: "DECIMAL(5,4)",
        portfolio_attributes: "JSON",
        source_system: "STRING",
        ingestion_timestamp: "TIMESTAMP",
        raw_payload: "JSON",
      },
      partitioning: {
        type: "RANGE",
        column: "portfolio_date",
        granularity: "DAY",
      },
      retention: "10 YEARS",
    },
    {
      name: "bronze_portfolio_holdings",
      description: "Raw portfolio security holdings",
      schema: {
        holding_id: "STRING PRIMARY KEY",
        holding_timestamp: "TIMESTAMP",
        holding_date: "DATE",
        portfolio_id: "STRING",
        client_id: "STRING",
        security_id: "STRING",
        cusip: "STRING",
        isin: "STRING",
        ticker: "STRING",
        security_name: "STRING",
        security_type: "STRING",
        asset_class: "STRING",
        sector: "STRING",
        quantity: "DECIMAL(18,6)",
        unit_cost: "DECIMAL(18,6)",
        total_cost: "DECIMAL(18,2)",
        market_price: "DECIMAL(18,6)",
        market_value: "DECIMAL(18,2)",
        unrealized_gl: "DECIMAL(18,2)",
        accrued_income: "DECIMAL(18,2)",
        percent_of_portfolio: "DECIMAL(5,2)",
        tax_lot_method: "STRING",
        tax_lots: "ARRAY<JSON>",
        holding_attributes: "JSON",
        source_system: "STRING",
        ingestion_timestamp: "TIMESTAMP",
        raw_payload: "JSON",
      },
      partitioning: {
        type: "RANGE",
        column: "holding_date",
        granularity: "DAY",
      },
      retention: "10 YEARS",
    },
    {
      name: "bronze_transactions",
      description: "Raw portfolio transaction data",
      schema: {
        transaction_id: "STRING PRIMARY KEY",
        transaction_timestamp: "TIMESTAMP",
        transaction_date: "DATE",
        settlement_date: "DATE",
        portfolio_id: "STRING",
        client_id: "STRING",
        account_id: "STRING",
        transaction_type: "STRING",
        security_id: "STRING",
        cusip: "STRING",
        quantity: "DECIMAL(18,6)",
        price: "DECIMAL(18,6)",
        gross_amount: "DECIMAL(18,2)",
        commission: "DECIMAL(18,2)",
        fees: "DECIMAL(18,2)",
        net_amount: "DECIMAL(18,2)",
        currency: "STRING",
        trade_date: "DATE",
        order_id: "STRING",
        execution_venue: "STRING",
        broker: "STRING",
        advisor_id: "STRING",
        solicited_flag: "BOOLEAN",
        principal_trade: "BOOLEAN",
        transaction_attributes: "JSON",
        source_system: "STRING",
        ingestion_timestamp: "TIMESTAMP",
        raw_payload: "JSON",
      },
      partitioning: {
        type: "RANGE",
        column: "transaction_date",
        granularity: "MONTH",
      },
      retention: "10 YEARS",
    },
    {
      name: "bronze_performance",
      description: "Raw portfolio performance data",
      schema: {
        performance_id: "STRING PRIMARY KEY",
        performance_timestamp: "TIMESTAMP",
        performance_date: "DATE",
        portfolio_id: "STRING",
        client_id: "STRING",
        period_type: "STRING",
        beginning_value: "DECIMAL(18,2)",
        ending_value: "DECIMAL(18,2)",
        net_contributions: "DECIMAL(18,2)",
        net_withdrawals: "DECIMAL(18,2)",
        income: "DECIMAL(18,2)",
        realized_gains: "DECIMAL(18,2)",
        unrealized_gains: "DECIMAL(18,2)",
        fees_expenses: "DECIMAL(18,2)",
        time_weighted_return: "DECIMAL(8,4)",
        money_weighted_return: "DECIMAL(8,4)",
        benchmark_return: "DECIMAL(8,4)",
        alpha: "DECIMAL(8,4)",
        beta: "DECIMAL(8,4)",
        sharpe_ratio: "DECIMAL(8,4)",
        standard_deviation: "DECIMAL(8,4)",
        performance_attributes: "JSON",
        source_system: "STRING",
        ingestion_timestamp: "TIMESTAMP",
        raw_payload: "JSON",
      },
      partitioning: {
        type: "RANGE",
        column: "performance_date",
        granularity: "MONTH",
      },
      retention: "PERMANENT",
    },
    {
      name: "bronze_fee_billing",
      description: "Raw advisory fee billing data",
      schema: {
        billing_id: "STRING PRIMARY KEY",
        billing_timestamp: "TIMESTAMP",
        billing_date: "DATE",
        billing_period_start: "DATE",
        billing_period_end: "DATE",
        portfolio_id: "STRING",
        client_id: "STRING",
        account_id: "STRING",
        fee_type: "STRING",
        fee_schedule: "STRING",
        average_balance: "DECIMAL(18,2)",
        fee_rate: "DECIMAL(5,4)",
        fee_amount: "DECIMAL(18,2)",
        fee_basis: "STRING",
        calculation_method: "STRING",
        prorated_flag: "BOOLEAN",
        waived_flag: "BOOLEAN",
        waiver_amount: "DECIMAL(18,2)",
        net_fee: "DECIMAL(18,2)",
        payment_method: "STRING",
        payment_status: "STRING",
        billing_attributes: "JSON",
        source_system: "STRING",
        ingestion_timestamp: "TIMESTAMP",
        raw_payload: "JSON",
      },
      partitioning: {
        type: "RANGE",
        column: "billing_date",
        granularity: "MONTH",
      },
      retention: "10 YEARS",
    },
    {
      name: "bronze_client_profiles",
      description: "Raw wealth management client profiles",
      schema: {
        profile_id: "STRING PRIMARY KEY",
        profile_timestamp: "TIMESTAMP",
        profile_date: "DATE",
        client_id: "STRING",
        client_type: "STRING",
        relationship_type: "STRING",
        net_worth: "DECIMAL(18,2)",
        liquid_assets: "DECIMAL(18,2)",
        aum: "DECIMAL(18,2)",
        annual_income: "DECIMAL(18,2)",
        investment_experience: "STRING",
        risk_tolerance: "STRING",
        investment_objectives: "ARRAY<STRING>",
        time_horizon: "STRING",
        liquidity_needs: "STRING",
        tax_sensitivity: "STRING",
        esg_preferences: "JSON",
        concentration_limits: "JSON",
        restrictions: "ARRAY<STRING>",
        suitability_score: "DECIMAL(5,2)",
        kyc_status: "STRING",
        accredited_investor: "BOOLEAN",
        qualified_client: "BOOLEAN",
        advisor_id: "STRING",
        service_team: "STRING",
        profile_attributes: "JSON",
        source_system: "STRING",
        ingestion_timestamp: "TIMESTAMP",
        raw_payload: "JSON",
      },
      partitioning: {
        type: "RANGE",
        column: "profile_date",
        granularity: "MONTH",
      },
      retention: "10 YEARS",
    },
    {
      name: "bronze_advisory_reviews",
      description: "Raw client review and recommendation data",
      schema: {
        review_id: "STRING PRIMARY KEY",
        review_timestamp: "TIMESTAMP",
        review_date: "DATE",
        client_id: "STRING",
        portfolio_id: "STRING",
        review_type: "STRING",
        advisor_id: "STRING",
        meeting_type: "STRING",
        topics_discussed: "ARRAY<STRING>",
        recommendations: "ARRAY<JSON>",
        action_items: "ARRAY<JSON>",
        risk_assessment: "STRING",
        suitability_determination: "STRING",
        plan_changes: "JSON",
        next_review_date: "DATE",
        client_satisfaction: "INTEGER",
        review_attributes: "JSON",
        source_system: "STRING",
        ingestion_timestamp: "TIMESTAMP",
        raw_payload: "JSON",
      },
      partitioning: {
        type: "RANGE",
        column: "review_date",
        granularity: "YEAR",
      },
      retention: "PERMANENT",
    },
  ],
};

export const wealthSilverLayer = {
  description: "Cleansed wealth management data",
  tables: [
    {
      name: "silver_portfolios",
      description: "Cleansed client portfolio data",
      schema: {
        portfolio_key: "BIGINT PRIMARY KEY",
        portfolio_date: "DATE",
        client_key: "BIGINT",
        account_key: "BIGINT",
        advisor_key: "BIGINT",
        total_value: "DECIMAL(18,2)",
        cash_balance: "DECIMAL(18,2)",
        invested_value: "DECIMAL(18,2)",
        unrealized_gl: "DECIMAL(18,2)",
        data_quality_score: "DECIMAL(5,2)",
        effective_from: "TIMESTAMP",
        effective_to: "TIMESTAMP",
        is_current: "BOOLEAN",
        created_timestamp: "TIMESTAMP",
        source_system: "STRING",
      },
      partitioning: {
        type: "RANGE",
        column: "portfolio_date",
        granularity: "MONTH",
      },
      retention: "10 YEARS",
    },
    {
      name: "silver_holdings",
      description: "Cleansed portfolio holdings data",
      schema: {
        holding_key: "BIGINT PRIMARY KEY",
        holding_date: "DATE",
        portfolio_key: "BIGINT",
        security_key: "BIGINT",
        quantity: "DECIMAL(18,6)",
        market_value: "DECIMAL(18,2)",
        unrealized_gl: "DECIMAL(18,2)",
        data_quality_score: "DECIMAL(5,2)",
        created_timestamp: "TIMESTAMP",
        source_system: "STRING",
      },
      partitioning: {
        type: "RANGE",
        column: "holding_date",
        granularity: "MONTH",
      },
      retention: "10 YEARS",
    },
  ],
};

export const wealthGoldLayer = {
  description: "Analytics-optimized wealth management dimensional model",
  dimensions: [
    {
      name: "dim_portfolio_type",
      description: "Portfolio type classification",
      type: "SCD Type 1",
      schema: {
        portfolio_type_key: "BIGINT PRIMARY KEY",
        portfolio_type_code: "STRING",
        portfolio_type_name: "STRING",
        account_category: "STRING",
        taxable_flag: "BOOLEAN",
        retirement_flag: "BOOLEAN",
        trust_flag: "BOOLEAN",
      },
    },
    {
      name: "dim_asset_class",
      description: "Asset class dimension",
      type: "SCD Type 1",
      schema: {
        asset_class_key: "BIGINT PRIMARY KEY",
        asset_class_code: "STRING",
        asset_class_name: "STRING",
        asset_category: "STRING",
        risk_level: "STRING",
        liquidity_tier: "STRING",
      },
    },
  ],
  facts: [
    {
      name: "fact_portfolio_value_daily",
      description: "Daily portfolio valuation fact table",
      grain: "One row per portfolio per day",
      schema: {
        portfolio_key: "BIGINT PRIMARY KEY",
        value_date_key: "INTEGER",
        client_key: "BIGINT",
        advisor_key: "BIGINT",
        portfolio_type_key: "BIGINT",
        total_value: "DECIMAL(18,2)",
        cash_balance: "DECIMAL(18,2)",
        invested_value: "DECIMAL(18,2)",
        unrealized_gl: "DECIMAL(18,2)",
        income_ytd: "DECIMAL(18,2)",
        portfolio_count: "INTEGER DEFAULT 1",
      },
      measures: [
        "SUM(total_value) as total_aum",
        "COUNT(DISTINCT client_key) as total_clients",
        "AVG(total_value) as avg_portfolio_size",
        "SUM(unrealized_gl) as total_unrealized_gains",
      ],
    },
    {
      name: "fact_transactions",
      description: "Portfolio transaction fact table",
      grain: "One row per transaction",
      schema: {
        transaction_key: "BIGINT PRIMARY KEY",
        transaction_date_key: "INTEGER",
        settlement_date_key: "INTEGER",
        portfolio_key: "BIGINT",
        client_key: "BIGINT",
        security_key: "BIGINT",
        transaction_type_key: "BIGINT",
        quantity: "DECIMAL(18,6)",
        gross_amount: "DECIMAL(18,2)",
        commission: "DECIMAL(18,2)",
        net_amount: "DECIMAL(18,2)",
        transaction_count: "INTEGER DEFAULT 1",
      },
      measures: [
        "COUNT(transaction_key) as total_transactions",
        "SUM(gross_amount) as total_transaction_volume",
        "SUM(commission) as total_commissions",
      ],
    },
    {
      name: "fact_performance_monthly",
      description: "Monthly portfolio performance fact table",
      grain: "One row per portfolio per month",
      schema: {
        performance_key: "BIGINT PRIMARY KEY",
        performance_month_key: "INTEGER",
        portfolio_key: "BIGINT",
        client_key: "BIGINT",
        beginning_value: "DECIMAL(18,2)",
        ending_value: "DECIMAL(18,2)",
        time_weighted_return: "DECIMAL(8,4)",
        benchmark_return: "DECIMAL(8,4)",
        alpha: "DECIMAL(8,4)",
        beta: "DECIMAL(8,4)",
        sharpe_ratio: "DECIMAL(8,4)",
        performance_count: "INTEGER DEFAULT 1",
      },
      measures: [
        "AVG(time_weighted_return) as avg_return",
        "AVG(alpha) as avg_alpha",
        "AVG(sharpe_ratio) as avg_sharpe",
      ],
    },
    {
      name: "fact_fee_billing",
      description: "Advisory fee billing fact table",
      grain: "One row per billing event",
      schema: {
        billing_key: "BIGINT PRIMARY KEY",
        billing_date_key: "INTEGER",
        portfolio_key: "BIGINT",
        client_key: "BIGINT",
        advisor_key: "BIGINT",
        fee_type_key: "BIGINT",
        average_balance: "DECIMAL(18,2)",
        fee_amount: "DECIMAL(18,2)",
        net_fee: "DECIMAL(18,2)",
        billing_count: "INTEGER DEFAULT 1",
      },
      measures: [
        "SUM(fee_amount) as total_fees",
        "SUM(net_fee) as net_fee_revenue",
        "AVG(fee_amount / NULLIF(average_balance, 0)) as avg_fee_rate",
      ],
    },
  ],
};

export const wealthMetricsCatalog = {
  description: "200+ wealth management metrics",
  totalMetrics: 200,
  categories: [
    {
      name: "AUM Metrics",
      metrics: [
        "Total AUM",
        "Net New Assets",
        "Organic Growth",
        "Market Appreciation",
        "AUM by Client Segment",
        "AUM by Advisor",
        "AUM by Portfolio Type",
        "Average Account Size",
        "Billable AUM",
        "AUM Growth Rate",
        "Client Acquisition AUM",
        "Client Attrition AUM",
        "Household AUM",
        "Managed vs Advisory AUM",
        "Discretionary vs Non-Discretionary",
      ],
    },
    {
      name: "Client Metrics",
      metrics: [
        "Total Clients",
        "New Clients",
        "Lost Clients",
        "Client Retention Rate",
        "Client Satisfaction Score",
        "Clients per Advisor",
        "High Net Worth Clients",
        "Ultra High Net Worth Clients",
        "Accredited Investors",
        "Qualified Clients",
        "Active Clients",
        "Inactive Clients",
        "Client Engagement Score",
        "Household Count",
        "Multi-Generational Clients",
      ],
    },
    {
      name: "Performance Metrics",
      metrics: [
        "Time-Weighted Return",
        "Money-Weighted Return",
        "Benchmark Return",
        "Alpha",
        "Beta",
        "Sharpe Ratio",
        "Information Ratio",
        "Tracking Error",
        "Standard Deviation",
        "Downside Deviation",
        "Max Drawdown",
        "Recovery Time",
        "Sortino Ratio",
        "Calmar Ratio",
        "Win Rate",
      ],
    },
    {
      name: "Revenue Metrics",
      metrics: [
        "Total Advisory Fees",
        "Management Fee Revenue",
        "Performance Fee Revenue",
        "Planning Fee Revenue",
        "Commission Revenue",
        "Revenue per Client",
        "Revenue per AUM",
        "Fee Waiver Rate",
        "Effective Fee Rate",
        "Fee Compression",
        "Revenue Growth Rate",
        "Recurring Revenue %",
        "Revenue by Service Type",
        "Revenue per Advisor",
        "Profit Margin",
      ],
    },
    {
      name: "Activity Metrics",
      metrics: [
        "Transactions per Client",
        "Transaction Volume",
        "Average Trade Size",
        "Buy/Sell Ratio",
        "Portfolio Turnover",
        "Rebalancing Frequency",
        "Contribution Volume",
        "Withdrawal Volume",
        "Net Cash Flow",
        "Trading Costs",
      ],
    },
    {
      name: "Portfolio Construction Metrics",
      metrics: [
        "Asset Allocation vs Target",
        "Diversification Score",
        "Concentration Risk",
        "Tax Efficiency",
        "ESG Score",
        "Active Share",
        "Number of Holdings",
        "Cash Allocation %",
        "Alternative Investments %",
        "International Exposure %",
      ],
    },
    {
      name: "Compliance Metrics",
      metrics: [
        "Suitability Reviews Completed",
        "KYC Currency Rate",
        "Trade Supervision Rate",
        "Exception Rate",
        "Complaints Filed",
        "Regulatory Violations",
        "Best Execution Compliance",
        "Fee Disclosure Compliance",
        "Investment Policy Adherence",
        "Restricted List Violations",
      ],
    },
    {
      name: "Advisor Productivity Metrics",
      metrics: [
        "AUM per Advisor",
        "Clients per Advisor",
        "Revenue per Advisor",
        "New Client Acquisition",
        "Client Retention by Advisor",
        "Meeting Frequency",
        "Plan Completion Rate",
        "Cross-Sell Rate",
        "Referral Rate",
        "Time Utilization",
      ],
    },
  ],
};

export const wealthSummary = {
  domain: "Wealth Management",
  completeness: "100%",
  coverage: {
    bronzeTables: 7,
    silverTables: 2,
    goldDimensions: 2,
    goldFacts: 4,
    totalMetrics: 200,
  },
  keyCapabilities: [
    "Portfolio management",
    "Performance measurement",
    "Asset allocation tracking",
    "Fee billing and revenue",
    "Client profiling and suitability",
    "Transaction processing",
    "Holdings management",
    "Advisory reviews",
    "Compliance monitoring",
    "Benchmark comparison",
  ],
  readyForDeployment: true,
};
